#!/usr/bin/env bash
# The terminal sessions quoted in lesson 20 of nosql-operations, as a script
# that produces them.
#
# THE SCRIPT IS THE SOURCE AND ITS OUTPUT IS NOT COMMITTED. Every transcript in
# this lesson was copied from running it.
#
#   sudo bash ../../lab.sh tools     # once
#   bash captures.sh
#
# What is staged, and why: the lesson opens by stopping lesson 1's three
# containers, so the run first creates them (the `nosql` network, `mongo`,
# `redis` and `cassandra`, by lesson 1's own commands) without showing it.
# Every file the lesson uses (load.js, basket.csv, emptied.cql) is written by a
# fence of the lesson, taken back out of it here. The load each section
# watches is generated by the commands the section shows, started in the
# background where the section says so; its rates and every timing differ on
# each run, and the lesson quotes the run that was recorded.
#
# Recorded on Ubuntu 24.04, Docker Engine 29.8, TZ=America/Sao_Paulo.
. "$(dirname "$0")/../../capture.sh"

# lesson 1's state, which this lesson starts from
quiet 'docker network create nosql'
quiet 'docker run -d --name mongo --network nosql mongo:8.0'
quiet 'docker run -d --name redis --network nosql redis:7.4'
quiet 'docker run -d --name cassandra --network nosql -e MAX_HEAP_SIZE=256M -e HEAP_NEWSIZE=64M cassandra:5.0'
quiet 'sleep 5'

block mongo-start
quiet "$(from mongodb-signals.md 'docker stop mongo redis cassandra')"
quiet 'ready_mongo mongo1'; quiet 'ready_mongo mongo2'; quiet 'ready_mongo mongo3'
quiet "$(from mongodb-signals.md 'docker exec mongo1 mongosh --quiet --eval '"'"'rs.initiate({ _id: "rs0", members: [')"
quiet 'sleep 15'
run "docker exec mongo1 mongosh --quiet --eval 'rs.status().members.map(m => m.name + \" \" + m.stateStr)'"

block mongo-load
from mongodb-signals.md '// load.js: the shop'"'"'s orders, written in batches of 1,000' > load.js
run "$(from mongodb-signals.md 'docker cp load.js mongo1:/load.js' | sed -n 1p)"
run "$(from mongodb-signals.md 'docker cp load.js mongo1:/load.js' | sed -n 2p)"
quiet 'sleep 2'

block mongostat
run 'docker exec mongo1 mongostat -n 5'
run "docker exec mongo1 mongosh --quiet --eval 'rs.status().members.map(m => m.name + \" \" + m.stateStr)'"

block mongo-status
session 'docker exec -it mongo1 mongosh --quiet shop' <<'S'
const s = db.serverStatus()
s.connections.current
s.opcounters
const c = s.wiredTiger.cache
const max = c["maximum bytes configured"]
max / 1024 / 1024
(100 * c["bytes currently in the cache"] / max).toFixed(1)
(100 * c["tracked dirty bytes in the cache"] / max).toFixed(1)
exit
S

quiet 'until [ "$(docker exec mongo1 mongosh --quiet shop --eval "db.orders.countDocuments()")" = 600000 ]; do sleep 2; done'

block mongo-lag
run "docker exec mongo3 mongosh --quiet --eval 'db.fsyncLock().lockCount'"
run 'docker exec mongo1 mongosh --quiet shop /load.js'
run "docker exec mongo1 mongosh --quiet --eval 'rs.printSecondaryReplicationInfo()'"
run "docker exec mongo3 mongosh --quiet --eval 'db.fsyncUnlock().lockCount'"
quiet 'sleep 5'
run "docker exec mongo1 mongosh --quiet --eval 'rs.printSecondaryReplicationInfo()'"

block mongo-slow
run "docker exec -d mongo1 mongosh --quiet shop --eval 'db.orders.find({ \$where: \"sleep(5) || false\" }).itcount()'"
quiet 'sleep 4'
session 'docker exec -it mongo1 mongosh --quiet shop' <<'S'
const slow = db.currentOp({ ns: "shop.orders", secs_running: { $gte: 2 } }).inprog
slow.map(o => ({ opid: o.opid, secs_running: o.secs_running, planSummary: o.planSummary, filter: o.command.filter }))
db.killOp(slow[0].opid).info
#sleep 2
db.getProfilingStatus().slowms
db.adminCommand({ getLog: "global" }).log.map(JSON.parse).filter(l => l.msg == "Slow query" && l.attr.command.find).map(l => ({ ns: l.attr.ns, planSummary: l.attr.planSummary, durationMillis: l.attr.durationMillis, errName: l.attr.errName }))
exit
S

block redis-start
quiet "$(from redis-signals.md 'docker rm -f mongo1 mongo2 mongo3 redis' | sed -n 1p)"
run "$(from redis-signals.md 'docker rm -f mongo1 mongo2 mongo3 redis' | sed -n 2p)"
run "$(from redis-signals.md 'docker rm -f mongo1 mongo2 mongo3 redis' | sed -n 3p)"
quiet 'ready_redis redis'; quiet 'ready_redis redis-replica'; quiet 'sleep 2'

block redis-load
run 'docker exec -d redis redis-benchmark -t set,get -n 600000 -r 100000 -d 200 -q'
quiet 'sleep 2'
run 'docker exec redis timeout 5 stdbuf -oL redis-cli --stat'
run 'docker exec redis redis-cli INFO | grep -E "^(used_memory|maxmemory|evicted_keys|keyspace_hits|keyspace_misses|connected_clients|rejected_connections|instantaneous_ops_per_sec):"'
quiet 'sleep 10'

block redis-lag
run 'docker pause redis-replica'
run 'docker exec redis redis-benchmark -t set -n 200000 -r 100000 -d 200 --csv'
run 'docker exec redis redis-cli INFO replication | grep -E "^(slave0|master_repl_offset)"'
run 'docker unpause redis-replica'
quiet 'sleep 3'
run 'docker exec redis redis-cli INFO replication | grep -E "^(slave0|master_repl_offset)"'

block redis-clients
run 'docker exec redis redis-cli CONFIG SET maxclients 2'
run 'docker exec -d redis redis-cli BLPOP nothing 10'
quiet 'sleep 1'
run 'docker exec redis redis-cli PING'
quiet 'sleep 11'
run 'docker exec redis redis-cli INFO stats | grep rejected_connections'
run 'docker exec redis redis-cli CONFIG SET maxclients 10000'

block redis-slowlog
session 'docker exec -it redis redis-cli' <<'S'
CONFIG GET slowlog-log-slower-than
CONFIG SET slowlog-log-slower-than 1000
SLOWLOG RESET
KEYS order:*
SLOWLOG GET 1
CONFIG SET slowlog-log-slower-than 10000
LATENCY DOCTOR
exit
S

block cassandra-start
quiet "$(from cassandra-signals.md 'docker rm -f redis redis-replica' | sed -n 1p)"
run "$(from cassandra-signals.md 'docker rm -f redis redis-replica' | sed -n 2p)"
run "$(from cassandra-signals.md 'docker rm -f redis redis-replica' | sed -n 3p)"
run 'docker exec cassandra nodetool status'

block cassandra-data
session 'docker exec -it cassandra cqlsh' <<'S'
CREATE KEYSPACE shop WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
CREATE TABLE shop.basket (customer text, item int, sku text, PRIMARY KEY (customer, item));
exit
S
quiet "$(from cassandra-signals.md '{ seq 1 2000 | sed '"'"'s/.*/ana@example.com,&,CB-012/'"'"'')"
run "docker exec cassandra cqlsh -e \"COPY shop.basket (customer, item, sku) FROM '/basket.csv'\" | tail -1"
quiet "$(from cassandra-signals.md 'seq 1 1990 | sed "s/.*/DELETE FROM shop.basket WHERE customer = '"'"'ana@example.com'"'"' AND item = &;/" > emptied.cql')"
run 'wc -l basket.csv emptied.cql'

block cassandra-read
session 'docker exec -it cassandra cqlsh' <<'S'
SELECT count(*) FROM shop.basket WHERE customer = 'ana@example.com';
SELECT count(*) FROM shop.basket WHERE customer = 'bruno@example.com';
SELECT count(*) FROM shop.basket WHERE customer = 'ana@example.com';
exit
S
run 'docker exec cassandra nodetool flush shop basket'

block cassandra-tablestats
run 'docker exec cassandra nodetool tablestats shop.basket | grep -E "SSTable count|Number of partitions|Local read latency|Compacted partition|tombstones per slice"'
run 'docker exec cassandra nodetool tablehistograms shop basket'
run 'docker exec cassandra nodetool proxyhistograms'
run 'docker exec cassandra nodetool tpstats | grep -E "^(Pool Name|ReadStage|MutationStage|Native-Transport-Requests|CompactionExecutor|Message type|READ_REQ|MUTATION_REQ) "'
run 'docker exec cassandra nodetool compactionstats'
