#!/usr/bin/env bash
# The terminal sessions quoted in lesson 3 of llm-observability, as a script
# that produces them.
#
# THE SCRIPT IS THE SOURCE AND ITS OUTPUT IS NOT COMMITTED. Every transcript in
# this lesson was copied from running it.
#
#   sudo bash ../../lab.sh up        # once
#   sudo bash captures.sh
#
# What is STAGED rather than typed, and not shown in the lesson: the lab
# (lab.sh reset), and copying the course's programs into ~/obs from
# ../../lab/code. replay.py and costs.py are shown in the lesson; the others
# are lesson 1's and 2's. The programs this lesson writes are put below and
# shown in full.
#
# THE WEEK IS SIMULATED. The requests are data/traffic.jsonl, generated by
# ../../lab/traffic.py; what the simulated customers do after a reply is
# decided by rules written in replay.py. Every reply comes from extract-1, the
# lab's stand-in model, and THE PRICES IN prices.json WERE WRITTEN BY THE
# COURSE: no provider charges them. Token counts are labobs' usage figures.
# What is computed here, every count, sum and share, is real arithmetic on
# those.
#
# Recorded on Ubuntu 24.04, Python 3.11, TZ=America/Sao_Paulo, on 2026-10-06.
set -uo pipefail
export TZ=America/Sao_Paulo LC_ALL=C.UTF-8
cd "$(dirname "$0")"
LAB_SH=${LAB_SH:-../../lab.sh}
CODE=$(cd "$(dirname "$LAB_SH")" && pwd)/lab/code
lab() { bash "$LAB_SH" "$@"; }
on() { printf 'ana@lab:~/obs$ %s\n' "$*"; lab exec "$*" 2>&1 || true; }
put() { lab exec "mkdir -p \"\$(dirname '$1')\" && cat > '$1'"; }
use() { for f in "$@"; do put "$f" < "$CODE/$f"; done; }
block() { printf '##### %s\n' "$1"; }
exec 9>/var/tmp/llmobs-capture.lock; flock 9
lab reset >/dev/null
use telemetry.py redact.py assistant.py replay.py tree.py costs.py
lab exec 'python assistant.py "warm up" >/dev/null; rm -f spans.jsonl'

put bill.py <<'PY'
"""bill.py: the week's cost, grouped by one field of the request."""
import argparse
from collections import defaultdict
from decimal import Decimal

import costs

p = argparse.ArgumentParser()
p.add_argument("--by", default="feature", choices=["feature", "user", "day", "release", "outcome"])
p.add_argument("--top", type=int)
a = p.parse_args()

rows = costs.requests()
key = (lambda r: r["at"].strftime("%a %d")) if a.by == "day" else (lambda r: r[a.by])
groups = defaultdict(list)
for r in rows:
    groups[key(r)].append(r)
total = sum((r["cost"] for r in rows), Decimal(0))
spend = {g: sum((r["cost"] for r in rs), Decimal(0)) for g, rs in groups.items()}
order = list(groups) if a.by == "day" else sorted(groups, key=lambda g: -spend[g])
print(f"{a.by:18} {'requests':>8} {'input':>8} {'output':>7} {'cost US$':>9} {'per 1k':>7} {'share':>6}  features")
for g in order[:a.top]:
    rs = groups[g]
    features = "/".join(sorted({r["feature"] for r in rs}))
    print(f"{str(g):18} {len(rs):8} {sum(r['input'] for r in rs):8} {sum(r['output'] for r in rs):7} "
          f"{spend[g]:9.4f} {spend[g] / len(rs) * 1000:7.2f} {spend[g] / total:6.1%}  {features}")
print(f"{'total':18} {len(rows):8} {sum(r['input'] for r in rows):8} {sum(r['output'] for r in rows):7} "
      f"{total:9.4f} {total / len(rows) * 1000:7.2f}")
PY

put spread.py <<'PY'
"""spread.py: how the cost of one request is distributed, per feature."""
from collections import defaultdict

import costs

by = defaultdict(list)
for r in costs.requests():
    by[r["feature"]].append(r["cost"] * 1_000_000)
print(f"{'feature':8} {'requests':>8} {'no model call':>13}   cost of one request in millionths of a dollar")
print(f"{'':8} {'':>8} {'':>13}   {'min':>6} {'median':>6} {'p95':>6} {'max':>6}")
for feature, c in by.items():
    c.sort()
    pick = lambda q: c[min(len(c) - 1, int(q * len(c)))]
    free = sum(1 for x in c if x < 100)
    print(f"{feature:8} {len(c):8} {free:13}   {c[0]:6.0f} {pick(0.5):6.0f} {pick(0.95):6.0f} {c[-1]:6.0f}")
PY

put budget.py <<'PY'
"""budget.py: each day's spend per feature against a daily budget, and the users over a daily cap."""
import json
from collections import defaultdict
from decimal import Decimal

import costs

BUDGET = {k: Decimal(v) for k, v in json.load(open("budgets.json"))["daily"].items()}
CAP = Decimal(json.load(open("budgets.json"))["per_user_daily"])
day_feature, day_user = defaultdict(Decimal), defaultdict(Decimal)
for r in costs.requests():
    day = r["at"].strftime("%a %d")
    day_feature[day, r["feature"]] += r["cost"]
    day_user[day, r["user"]] += r["cost"]
print(f"{'day':7}" + "".join(f"{f:>16}" for f in BUDGET))
for day in dict.fromkeys(d for d, _ in day_feature):
    cells = []
    for f, b in BUDGET.items():
        spent = day_feature[day, f]
        cells.append(f"{spent:.4f}{' OVER' if spent > b else '     '}".rjust(16))
    print(f"{day:7}" + "".join(cells))
over = sorted((v, d, u) for (d, u), v in day_user.items() if v > CAP)
print(f"users over {CAP} a day: {len(over)}")
for v, d, u in over[-3:]:
    print(f"  {d}  {u}  {v:.4f}")
PY

put budgets.json <<'JSON'
{"daily": {"help": "0.10", "order": "0.04", "summary": "0.012"}, "per_user_daily": "0.005"}
JSON

block replay
on 'python replay.py'
on 'wc -l spans.jsonl feedback.jsonl'
on 'python tree.py --attrs $(head -1 spans.jsonl | python -c "import json,sys; print(json.load(sys.stdin)[\"trace\"])") | head -12'

block prices
on 'cat prices.json'
on 'python -c "import costs; print(costs.price_at(\"extract-1\", \"2026-09-30\"), costs.price_at(\"extract-1\", \"2026-10-01\"))"'

block one-request
on 'python -c "import costs; r = next(r for r in costs.requests() if r[\"output\"]); print(r[\"trace\"], r[\"feature\"], r[\"input\"], r[\"output\"], r[\"cost\"])"'

T=$(lab exec 'python -c "import costs; print(next(r for r in costs.requests() if r[\"output\"])[\"trace\"][:8])"')
on "python tree.py --attrs $T | grep -E \" ms |usage|model\""

block by-feature
on 'python bill.py --by feature'
on 'python spread.py'

block by-user
on 'python bill.py --by user --top 6'

block by-day
on 'python bill.py --by day'
on 'python bill.py --by release'

block budget
on 'cat budgets.json'
on 'python budget.py'
