#!/usr/bin/env bash
# The terminal sessions quoted in lesson 3 of llm-observability, as a script
# that produces them.
#
# THE SCRIPT IS THE SOURCE AND ITS OUTPUT IS NOT COMMITTED. Every transcript in
# this lesson was copied from running it.
#
#   sudo bash ../../lab.sh up        # once
#   sudo bash captures.sh
#
# What is STAGED rather than typed, and not shown: ~/obs rebuilt as lesson 1
# leaves it (lab.sh reset), and the programs and files lessons 1 to 3 show,
# read out of the lessons that show them whole (stage, put). The replayed week
# is kept afterwards (lab.sh keep-week) for the lessons after this one.
#
# THE WEEK IS SIMULATED. The requests are data/traffic.jsonl, generated by
# lesson 2's traffic.py; what the simulated customers do after a reply is
# decided by rules written in replay.py. Every reply comes from llama3.2:3b
# (a80c4f17acd5) through Ollama 0.40.0, at temperature 0, taken 2026-10-07 on
# 4 cores and 15 GB with no GPU. THE PRICES IN prices.json WERE WRITTEN BY THE
# COURSE: Ollama charges nothing, and no provider charges these. Token counts
# are Ollama's usage figures. What is computed here, every count, sum and
# share, is real arithmetic on those.
#
# Recorded on Ubuntu 24.04, TZ=America/Sao_Paulo.
set -uo pipefail
cd "$(dirname "$0")"
. ../../lab/capture.sh
exec 9>/var/tmp/llmobs-capture.lock; flock 9

quiet lab reset
stage telemetry.py le-6wxafmfh/the-chain.md
stage assistant.py le-6wxafmfh/the-chain.md
stage tree.py le-6wxafmfh/the-chain.md
stage traffic.py le-pdj3wk00/what-customers-type.md
stage replay.py le-3s3pd3qk/replaying-a-week.md
stage costs.py le-3s3pd3qk/tokens-to-money.md
stage bill.py le-3s3pd3qk/per-feature.md
stage spread.py le-3s3pd3qk/per-feature.md
stage budget.py le-3s3pd3qk/budgets.md
python3 "$COURSE/lab/fences.py" block tokens-to-money.md '{' | put prices.json
python3 "$COURSE/lab/fences.py" block budgets.md '{"daily": {"help": "0.020", "order": "0.008", "summary": "0.003"}, "per_user_daily": "0.002"}' | put budgets.json
quiet lab exec 'python traffic.py data/traffic.jsonl'
quiet lab exec 'python assistant.py "warm up" >/dev/null; rm -f spans.jsonl feedback.jsonl'

block replay
on 'python replay.py'
on 'wc -l spans.jsonl feedback.jsonl'
quiet lab keep-week
block first
on 'python tree.py --attrs $(head -1 spans.jsonl | python -c "import json,sys; print(json.load(sys.stdin)[\"trace\"])") | head -12'

block prices
on 'python -c "import costs; print(costs.price_at(\"llama3.2:3b\", \"2026-09-29\"), costs.price_at(\"llama3.2:3b\", \"2026-09-30\"))"'

block one-request
on 'python -c "import costs; r = next(r for r in costs.requests() if r[\"output\"] and r[\"feature\"] == \"help\"); print(r[\"trace\"], r[\"feature\"], r[\"input\"], r[\"output\"], r[\"cost\"])"'
T=$(lab exec 'python -c "import costs; print(next(r for r in costs.requests() if r[\"output\"] and r[\"feature\"] == \"help\")[\"trace\"][:8])"')
on "python tree.py --attrs $T | grep -E \" ms |usage|model\""

block by-feature
on 'python bill.py --by feature'
on 'python spread.py'

block by-user
on 'python bill.py --by user --top 6'

block by-day
on 'python bill.py --by day'
on 'python bill.py --by release'

block budget
on 'python budget.py'
