"""The course exam: about four questions per lesson, none of them drillable."""
from questions import exam, quiz, mc, order, match, cloze, num

exam()

# lesson 1 — the new unit

quiz('ex-6m90yt4g', None, 'easy',
     ('By Grove’s sum, what is a manager’s output?',
      'Pela soma de Grove, qual é o resultado de uma gestora?'),
     ('Two terms.', 'Dois termos.'),
     [(1, 'Her organisation’s output plus that of neighbouring organisations under her influence',
       'Right: what she produces alone counts only through what the team produces.',
       'O resultado da organização dela mais o das organizações vizinhas sob a influência dela',
       'Isso: o que ela produz sozinha só conta pelo que o time produz.'),
      (0, 'The code she still writes',
       'That is the measure the lesson says stops applying.',
       'O código que ela ainda escreve',
       'Essa é a medida que a aula diz que deixa de valer.'),
      (0, 'The number of meetings she runs',
       'Meetings count only if they change what the team produces.',
       'O número de reuniões que ela conduz',
       'Reuniões só contam se mudam o que o time produz.'),
      (0, 'Her own output, weighted by the seniority of the people she manages',
       'No weighting; the sum is the teams’ output.',
       'O resultado dela, ponderado pela senioridade de quem ela gerencia',
       'Não há ponderação; a soma é o resultado dos times.')])

quiz('ex-2rq41dt4', None, 'medium',
     ('Renata persuades Payments to ship an endpoint a quarter early. Which term of Grove’s sum does that raise?',
      'A Renata convence Pagamentos a entregar um endpoint um trimestre antes. Que termo da soma de Grove isso aumenta?'),
     ('Not her own team’s effort.', 'Não o esforço do próprio time.'),
     [(1, 'The neighbouring organisations under her influence',
       'Right: her team’s output rises with nobody on it working harder.',
       'As organizações vizinhas sob a influência dela',
       'Isso: o resultado do time sobe sem ninguém nele trabalhar mais.'),
      (0, 'Her own individual contribution',
       'She produced nothing herself.',
       'A contribuição individual dela',
       'Ela não produziu nada sozinha.'),
      (0, 'Neither; it is a favour, outside the sum',
       'The lesson counts it as managerial work.',
       'Nenhum; é um favor, fora da soma',
       'A aula conta isso como trabalho de gestão.'),
      (0, 'The Payments team’s own output, since the work was theirs',
       'It counts for both; for Renata, through the second term.',
       'O resultado do próprio time de Pagamentos, já que o trabalho foi deles',
       'Conta para os dois; para a Renata, pelo segundo termo.')])

num('ex-x4dbk4rh', None, 'medium',
    ('A test run answers in about ten seconds; a hire shows whether it was right in about six months. By the lesson’s figure, about how many orders of magnitude separate the two loops?',
     'Um teste responde em cerca de dez segundos; uma contratação mostra se estava certa em cerca de seis meses. Pela figura da aula, cerca de quantas ordens de grandeza separam os dois ciclos?'),
    ('Six months is about sixteen million seconds.', 'Seis meses são cerca de dezesseis milhões de segundos.'),
    6, 0.5, ('orders of magnitude', 'ordens de grandeza'), (['orders'], ['ordens']))

quiz('ex-b37nxpfe', None, 'medium',
     ('Why does the lesson say a manager needs written records to learn at all?',
      'Por que a aula diz que uma gestora precisa de registros escritos para aprender?'),
     ('The length of the loop.', 'O tamanho do ciclo.'),
     [(1, 'The result arrives months later, after memory has rewritten the decision',
       'Right: without a record there is nothing to compare the outcome against.',
       'O resultado chega meses depois, quando a memória já reescreveu a decisão',
       'Isso: sem registro não há com o que comparar o resultado.'),
      (0, 'The company audits her decisions',
       'Not the reason given.',
       'A empresa audita as decisões dela',
       'Não é o motivo dado.'),
      (0, 'Her team expects to read them',
       'Her notebook is private.',
       'O time espera lê-los',
       'O caderno dela é privado.'),
      (0, 'A short loop needs them more',
       'It is the long loops that need them.',
       'Um ciclo curto precisa mais deles',
       'São os ciclos longos que precisam.')])

# lesson 2 — two shapes

match('ex-mmcamctz', None, 'easy',
      ('Match each role to what it answers for.',
       'Ligue cada papel àquilo por que ele responde.'),
      ('Two shapes of the role.', 'Duas formas do papel.'),
      [('tech lead', 'how the software is built', 'tech lead', 'como o software é construído'),
       ('engineering manager', 'the people building it and what they deliver',
        'gestora de engenharia', 'as pessoas que o constroem e o que entregam')],
      [('the product roadmap', 'o roadmap do produto')])

quiz('ex-4456d1mk', None, 'medium',
     ('What is the mistake the lesson calls the worst in this area?',
      'Qual é o erro que a aula chama de pior nessa área?'),
     ('The only way up.', 'O único caminho para cima.'),
     [(1, 'Taking the management job because it is the only way up, then being bad at a job never wanted',
       'Right: leading technically is a senior engineering job, not a junior management one.',
       'Aceitar o cargo de gestão por ser o único caminho para cima, e depois ser ruim num trabalho que nunca quis',
       'Isso: liderar tecnicamente é um trabalho sênior de engenharia, não um trabalho júnior de gestão.'),
      (0, 'Writing code as a manager',
       'Some code fits; what does not is work the plan depends on.',
       'Escrever código sendo gestora',
       'Algum código cabe; o que não cabe é trabalho de que o plano depende.'),
      (0, 'Going back to engineering after managing',
       'The choice is reversible.',
       'Voltar para a engenharia depois de gerenciar',
       'A escolha é reversível.'),
      (0, 'Having a tech lead and a manager on one team',
       'The lesson describes that pair working.',
       'Ter uma tech lead e uma gestora no mesmo time',
       'A aula descreve essa dupla funcionando.')])

quiz('ex-wvmzsvv7', None, 'medium',
     ('A year into managing full-time, what usually still works and what usually does not?',
      'Um ano depois de gerenciar em tempo integral, o que ainda funciona e o que não funciona mais?'),
     ('Judgement and currency.', 'Julgamento e atualização.'),
     [(1, 'Technical judgement still works; technical currency does not',
       'Right: she can still tell a good design, not write today’s code as fast.',
       'O julgamento técnico ainda funciona; a atualização técnica não',
       'Isso: ela ainda reconhece um bom design, mas não escreve o código de hoje no mesmo ritmo.'),
      (0, 'Both are gone',
       'Judgement survives.',
       'Os dois se foram',
       'O julgamento sobrevive.'),
      (0, 'Currency still works; judgement does not',
       'The other way round.',
       'A atualização ainda funciona; o julgamento não',
       'É o contrário.'),
      (0, 'Both are intact, as long as she reads the team’s pull requests every week',
       'Reading is not the same as staying current.',
       'Os dois estão intactos, desde que ela leia os pull requests do time toda semana',
       'Ler não é o mesmo que se manter atualizada.')])

quiz('ex-c0nq27d0', None, 'hard',
     ('Renata and Diego gave Thiago opposite answers about the calendar-sync work. On the page they wrote afterwards, what does either do when unsure whose decision it is?',
      'A Renata e o Diego deram ao Thiago respostas opostas sobre o trabalho de sincronização de calendário. Na página que escreveram depois, o que cada um faz quando não sabe de quem é a decisão?'),
     ('Before anybody else.', 'Antes de qualquer outra pessoa.'),
     [(1, 'Ask each other before answering anybody else',
       'Right: the page is what both can point at when they disagree.',
       'Perguntar um ao outro antes de responder a qualquer outra pessoa',
       'Isso: a página é o que os dois podem apontar quando discordam.'),
      (0, 'The manager decides',
       'The page splits decisions; it does not default to her.',
       'A gestora decide',
       'A página divide as decisões; não cai nela por padrão.'),
      (0, 'Take it to Otávio',
       'They settle it between themselves first.',
       'Levar ao Otávio',
       'Eles resolvem entre si primeiro.'),
      (0, 'Let the team vote on it at the next planning meeting',
       'Not described.',
       'Deixar o time votar na próxima reunião de planejamento',
       'Não é o descrito.')])

# lesson 3 — delegating outcomes

quiz('ex-9ytbqgpr', None, 'easy',
     ('What is the difference between delegating a task and delegating an outcome?',
      'Qual é a diferença entre delegar uma tarefa e delegar um resultado?'),
     ('What has to be true.', 'O que precisa ser verdade.'),
     [(1, 'An outcome says what has to be true at the end and leaves the doing to the person',
       'Right: a task says what to do and keeps the thinking with the manager.',
       'Um resultado diz o que precisa ser verdade no fim e deixa o fazer com a pessoa',
       'Isso: uma tarefa diz o que fazer e mantém o pensar com a gestora.'),
      (0, 'An outcome is bigger',
       'Size is not the difference.',
       'Um resultado é maior',
       'Tamanho não é a diferença.'),
      (0, 'A task has a deadline',
       'Both have dates.',
       'Uma tarefa tem prazo',
       'Os dois têm datas.'),
      (0, 'An outcome comes with a written design the person follows',
       'That is a task with extra steps.',
       'Um resultado vem com um design escrito que a pessoa segue',
       'Isso é uma tarefa com passos a mais.')])

order('ex-3vdsrvws', None, 'medium',
      ('Put Appelo’s levels of delegation in order, from the manager deciding alone to the team deciding alone.',
       'Ponha em ordem os níveis de delegação de Appelo, da gestora decidindo sozinha ao time decidindo sozinho.'),
      ('Seven levels.', 'Sete níveis.'),
      [('tell', 'dizer'), ('sell', 'vender'), ('consult', 'consultar'), ('agree', 'concordar'),
       ('advise', 'aconselhar'), ('inquire', 'perguntar'), ('delegate', 'delegar')],
      trap=('Advise comes after agree: the manager only offers an opinion and the person decides.',
            'Aconselhar vem depois de concordar: a gestora só dá opinião e a pessoa decide.'))

quiz('ex-5yz318yv', None, 'medium',
     ('Which two questions does the lesson use to pick a level of delegation?',
      'Que duas perguntas a aula usa para escolher um nível de delegação?'),
     ('Cost and record.', 'Custo e histórico.'),
     [(1, 'How costly a wrong decision is, and how many times this person has made one like it',
       'Right: both move the level, and the level moves over time.',
       'Quão caro é errar, e quantas vezes essa pessoa já tomou uma decisão parecida',
       'Isso: as duas mudam o nível, e o nível muda com o tempo.'),
      (0, 'How senior the person is',
       'Seniority is not either question.',
       'Quão sênior a pessoa é',
       'Senioridade não é nenhuma das perguntas.'),
      (0, 'How much time the manager has this week, and whether the person has asked to own it',
       'Not the two questions.',
       'Quanto tempo a gestora tem nesta semana, e se a pessoa pediu para ser dona disso',
       'Não são as duas perguntas.'),
      (0, 'Whether the team agrees',
       'Not the two questions.',
       'Se o time concorda',
       'Não são as duas perguntas.')])

quiz('ex-mp4tb96b', None, 'hard',
     ('Paula’s pull request looks wrong to Renata. By the lesson’s rule, what comes first?',
      'O pull request da Paula parece errado para a Renata. Pela regra da aula, o que vem primeiro?'),
     ('Before a correction.', 'Antes de uma correção.'),
     [(1, 'A question',
       'Right: here it was Renata’s model of the problem that was wrong.',
       'Uma pergunta',
       'Isso: aqui era o modelo da Renata sobre o problema que estava errado.'),
      (0, 'Taking the work back so the date holds',
       'Grabbing it back is one of the two failures.',
       'Pegar o trabalho de volta para a data se manter',
       'Pegar de volta é uma das duas falhas.'),
      (0, 'A written review listing what to change',
       'A correction before understanding.',
       'Uma revisão escrita listando o que mudar',
       'Uma correção antes de entender.'),
      (0, 'Waiting until it ships',
       'Never looking is the other failure.',
       'Esperar até ir para produção',
       'Nunca olhar é a outra falha.')])

# lesson 4 — autonomy and alignment

match('ex-n06f113x', None, 'medium',
      ('Match each of Kniberg’s corners to what it looks like.',
       'Ligue cada canto de Kniberg ao que ele parece.'),
      ('Alignment against autonomy.', 'Alinhamento contra autonomia.'),
      [('high alignment, low autonomy', 'the manager says what to build and how',
        'alto alinhamento, baixa autonomia', 'a gestora diz o que construir e como'),
       ('low alignment, high autonomy', 'everybody builds what they think best, in different directions',
        'baixo alinhamento, alta autonomia', 'cada um constrói o que acha melhor, em direções diferentes'),
       ('high alignment, high autonomy', 'the problem is explained and the team works out the solution',
        'alto alinhamento, alta autonomia', 'o problema é explicado e o time descobre a solução')],
      [('the team writes its own goal and keeps it to itself',
        'o time escreve o próprio objetivo e o guarda para si')])

mc('ex-kh17bc3c', None, 'medium',
   ('Which are the three gaps Bungay names between a plan and what happens?',
    'Quais são as três lacunas que Bungay aponta entre um plano e o que acontece?'),
   ('Three of five.', 'Três das cinco.'),
   [(1, 'The knowledge gap', 'Right: between what we would like to know and what we do.',
     'A lacuna de conhecimento', 'Isso: entre o que gostaríamos de saber e o que sabemos.'),
    (1, 'The alignment gap', 'Right: between what we want people to do and what they do.',
     'A lacuna de alinhamento', 'Isso: entre o que queremos que as pessoas façam e o que fazem.'),
    (1, 'The effects gap', 'Right: between what we expect our actions to do and what they do.',
     'A lacuna de efeitos', 'Isso: entre o que esperamos que as ações façam e o que fazem.'),
    (0, 'The skills gap', 'Not one of Bungay’s three.',
     'A lacuna de habilidades', 'Não é uma das três de Bungay.'),
    (0, 'The budget gap', 'Not one of Bungay’s three.',
     'A lacuna de orçamento', 'Não é uma das três de Bungay.')])

quiz('ex-ncdcqc22', None, 'medium',
     ('Against each of the three gaps, a manager’s instinct is the same. What is it, and why does it fail?',
      'Contra cada uma das três lacunas, o instinto da gestora é o mesmo. Qual é, e por que falha?'),
     ('More of something.', 'Mais de alguma coisa.'),
     [(1, 'More detail, which widens each gap',
       'Right: the answer is to decide only what you must and explain the intent.',
       'Mais detalhe, que alarga cada lacuna',
       'Isso: a resposta é decidir só o necessário e explicar a intenção.'),
      (0, 'More meetings, which take time from the work',
       'Not the instinct the lesson names.',
       'Mais reuniões, que tiram tempo do trabalho',
       'Não é o instinto que a aula aponta.'),
      (0, 'Hiring, which is slow',
       'Not the instinct the lesson names.',
       'Contratar, o que é lento',
       'Não é o instinto que a aula aponta.'),
      (0, 'Delegating more, which leaves the team without direction',
       'Delegating with intent is the remedy, not the instinct.',
       'Delegar mais, o que deixa o time sem direção',
       'Delegar com intenção é o remédio, não o instinto.')])

quiz('ex-vz99k39p', None, 'hard',
     ('Where does the lesson say two-way-door decisions belong?',
      'Onde a aula diz que ficam as decisões de porta de mão dupla?'),
     ('They are cheap to reverse.', 'São baratas de reverter.'),
     [(1, 'As close to the work as possible',
       'Right: reversing them is cheap, so speed wins.',
       'O mais perto possível do trabalho',
       'Isso: revertê-las é barato, então a velocidade ganha.'),
      (0, 'With the manager, written down',
       'That is where one-way doors belong.',
       'Com a gestora, por escrito',
       'É aí que ficam as portas de mão única.'),
      (0, 'With the director',
       'Too far from the work.',
       'Com o diretor',
       'Longe demais do trabalho.'),
      (0, 'With whoever spots the problem first, after a vote of the whole team at planning',
       'A vote is slower than the door needs.',
       'Com quem notar o problema primeiro, depois de uma votação do time inteiro no planejamento',
       'Uma votação é mais lenta do que a porta precisa.')])

# lesson 5 — one-to-ones

quiz('ex-3cdctb82', None, 'easy',
     ('Whose meeting is a one-to-one, in Grove’s framing?',
      'De quem é a reunião de 1:1, no enquadramento de Grove?'),
     ('Not the manager’s.', 'Não da gestora.'),
     [(1, 'The report’s',
       'Right: the agenda is theirs and the manager makes room for it.',
       'Da pessoa liderada',
       'Isso: a pauta é dela e a gestora abre espaço para ela.'),
      (0, 'The manager’s',
       'That is the default the lesson argues against.',
       'Da gestora',
       'Esse é o padrão contra o qual a aula argumenta.'),
      (0, 'The company’s, as a status channel',
       'Status has better homes.',
       'Da empresa, como canal de status',
       'Status tem casas melhores.'),
      (0, 'Shared equally, with topics alternating week by week',
       'The person’s topics come first every week.',
       'Dividida igualmente, com assuntos alternando a cada semana',
       'Os assuntos da pessoa vêm primeiro toda semana.')])

match('ex-9ya7pjmm', None, 'medium',
      ('Match each person to the cadence in the lesson’s table.',
       'Ligue cada pessoa à cadência da tabela da aula.'),
      ('Experience at the work decides.', 'A experiência no trabalho decide.'),
      [('a new hire, first three months', 'weekly, thirty minutes',
        'uma pessoa recém-contratada, primeiros três meses', 'semanal, trinta minutos'),
       ('an experienced person on familiar work', 'every two weeks, forty-five minutes',
        'uma pessoa experiente em trabalho conhecido', 'a cada duas semanas, quarenta e cinco minutos'),
       ('somebody on an improvement plan', 'weekly',
        'alguém num plano de melhoria', 'semanal')],
      [('monthly, an hour', 'mensal, uma hora')])

quiz('ex-hg51jz0a', None, 'medium',
     ('Which is worse, by the lesson?',
      'Qual é pior, pela aula?'),
     ('Reliability.', 'Confiabilidade.'),
     [(1, 'A weekly meeting cancelled every other week',
       'Right: a fortnightly one that always runs is better, and a cancellation says something.',
       'Uma reunião semanal cancelada semana sim, semana não',
       'Isso: uma quinzenal que sempre acontece é melhor, e um cancelamento diz alguma coisa.'),
      (0, 'A fortnightly meeting that always runs',
       'That is the better of the two.',
       'Uma reunião quinzenal que sempre acontece',
       'Essa é a melhor das duas.'),
      (0, 'They are equivalent, since the total time is the same',
       'Reliability is the point, not total time.',
       'São equivalentes, já que o tempo total é o mesmo',
       'O ponto é a confiabilidade, não o tempo total.'),
      (0, 'Neither; cadence does not matter',
       'Regularity and reliability are what matter.',
       'Nenhuma; a cadência não importa',
       'Regularidade e confiabilidade são o que importa.')])

quiz('ex-k7v6yk86', None, 'hard',
     ('Marcos’s section of the shared document stayed empty for six weeks. What did Renata learn by asking about it directly?',
      'A seção do Marcos no documento compartilhado ficou vazia por seis semanas. O que a Renata descobriu perguntando diretamente?'),
     ('The previous manager.', 'O gestor anterior.'),
     [(1, 'That the meeting did not serve him, because his last manager had used it to go over his mistakes',
       'Right: the empty section was information.',
       'Que a reunião não servia para ele, porque o gestor anterior a usava para repassar os erros dele',
       'Isso: a seção vazia era informação.'),
      (0, 'That he was content and reserved',
       'That was one possibility; it was not his answer.',
       'Que ele estava contente e era reservado',
       'Essa era uma possibilidade; não foi a resposta dele.'),
      (0, 'That he was interviewing elsewhere',
       'Not what he said.',
       'Que ele estava fazendo entrevistas em outro lugar',
       'Não foi o que ele disse.'),
      (0, 'That he had not known the document existed',
       'Not what he said.',
       'Que ele não sabia que o documento existia',
       'Não foi o que ele disse.')])

cloze('ex-zxw78061', None, 'medium',
      ('In the shared one-to-one notes, each action has an owner and a ____.',
       'Nas notas compartilhadas da 1:1, cada ação tem um dono e uma ____.'),
      ('When it is due.', 'Quando vence.'),
      [(['date', 'deadline', 'due date'], ['data', 'prazo'])])

# lesson 6 — past "fine"

quiz('ex-3fyx9ft7', None, 'easy',
     ('Why does the lesson say "fine" is not a failure of trust when somebody answers "how are things?"',
      'Por que a aula diz que "tudo bem" não é falta de confiança quando alguém responde "como estão as coisas?"'),
     ('Look at the question.', 'Olhe a pergunta.'),
     [(1, 'It is the correct reply to the question asked',
       'Right: the question is a greeting with no edges, asked by somebody with power.',
       'É a resposta correta para a pergunta feita',
       'Isso: a pergunta é um cumprimento sem bordas, feito por alguém com poder.'),
      (0, 'People lie to managers',
       'The lesson says it is not a lie.',
       'As pessoas mentem para gestoras',
       'A aula diz que não é mentira.'),
      (0, 'Most people really are fine, most of the time, and the answer reports exactly that',
       'Thiago’s "fine" left out the cost.',
       'A maioria das pessoas está mesmo bem, a maior parte do tempo, e a resposta relata exatamente isso',
       'O "tudo bem" do Thiago deixou o custo de fora.'),
      (0, 'Trust takes a year to build',
       'Not the argument.',
       'Confiança leva um ano para ser construída',
       'Não é o argumento.')])

mc('ex-cp6t6c8h', None, 'medium',
   ('Which of these are kinds of question the lesson says get past "fine"?',
    'Quais destes são tipos de pergunta que a aula diz que passam do "tudo bem"?'),
   ('Something to search for.', 'Algo para procurar.'),
   [(1, 'Bounded in time: "what was the most frustrating part of last week?"', 'Right.',
     'Limitada no tempo: "qual foi a parte mais frustrante da semana passada?"', 'Isso.'),
    (1, 'About the team, not the person', 'Right: easier to answer honestly.',
     'Sobre o time, não sobre a pessoa', 'Isso: mais fácil de responder com honestidade.'),
    (1, 'About you: "what could I do differently?"', 'Right.',
     'Sobre você: "o que eu poderia fazer diferente?"', 'Isso.'),
    (0, '"Why did you choose to do it that way?"', 'A "why" about the person’s choices sounds like a charge.',
     '"Por que você escolheu fazer daquele jeito?"', 'Um "por quê" sobre as escolhas da pessoa soa como acusação.'),
    (0, '"Don’t you think the deploy should go out on Thursday?"', 'The answer is in the question.',
     '"Você não acha que o deploy deveria sair na quinta?"', 'A resposta está na pergunta.')])

order('ex-xtd7w29g', None, 'medium',
      ('Put the lesson’s three steps for listening past the first answer in order.',
       'Ponha em ordem os três passos da aula para escutar além da primeira resposta.'),
      ('The useful part is the second or third.', 'A parte útil é a segunda ou a terceira.'),
      [('wait', 'espere'), ('ask for more, without direction', 'peça mais, sem direção'),
       ('say it back', 'devolva')],
      trap=('Saying it back before asking for more closes the subject at the first answer.',
            'Devolver antes de pedir mais fecha o assunto na primeira resposta.'))

quiz('ex-g8r23vhe', None, 'hard',
     ('According to the lesson, what decides the quality of the answers a manager gets?',
      'Segundo a aula, o que decide a qualidade das respostas que uma gestora recebe?'),
     ('A record.', 'Um registro.'),
     [(1, 'How she handled the previous ones',
       'Right: people answer by what happened last time.',
       'Como ela lidou com as anteriores',
       'Isso: as pessoas respondem pelo que aconteceu da última vez.'),
      (0, 'The wording of each question',
       'Wording helps; the record decides.',
       'A formulação de cada pergunta',
       'A formulação ajuda; o histórico decide.'),
      (0, 'Her seniority',
       'Not the claim.',
       'A senioridade dela',
       'Não é a afirmação.'),
      (0, 'How long the meeting is, since thirty minutes is too short for anything real',
       'Not the claim.',
       'Quanto dura a reunião, já que trinta minutos é pouco para algo real',
       'Não é a afirmação.')])

# lesson 7 — follow-through

quiz('ex-rt66hbra', None, 'easy',
     ('Which promise does the lesson say can always be kept?',
      'Que promessa a aula diz que dá sempre para cumprir?'),
     ('Your own action.', 'Uma ação sua.'),
     [(1, '"I’ll find out and tell you."',
       'Right: it depends only on the manager.',
       '"Vou descobrir e te contar."',
       'Isso: depende só da gestora.'),
      (0, '"I’ll get you the budget."',
       'That depends on somebody else’s decision.',
       '"Vou conseguir o orçamento para você."',
       'Isso depende da decisão de outra pessoa.'),
      (0, '"I’ll make sure you’re on the next project you want, whatever else comes up this quarter."',
       'Not hers alone to guarantee.',
       '"Vou garantir que você entre no próximo projeto que quiser, aconteça o que acontecer no trimestre."',
       'Não cabe só a ela garantir.'),
      (0, '"I’ll fix the rota."',
       'Depends on other teams.',
       '"Vou resolver a escala."',
       'Depende de outros times.')])

order('ex-gd3apwqn', None, 'medium',
      ('Put the four parts of closing the loop on a no in order.',
       'Ponha em ordem as quatro partes de fechar o ciclo com um não.'),
      ('The answer leads.', 'A resposta vem na frente.'),
      [('the answer', 'a resposta'), ('the real reason', 'o motivo real'),
       ('what is possible instead', 'o que é possível em vez disso'),
       ('when it will be revisited', 'quando vai ser revisto')],
      trap=('Starting with the reasons makes the person wait for the answer they came for.',
            'Começar pelos motivos faz a pessoa esperar pela resposta que veio buscar.'))

quiz('ex-w36fwkjj', None, 'medium',
     ('Dependencies on Payments came up in five of seven people’s notes. What does the lesson say a count like that protects against?',
      'Dependências com Pagamentos apareceram nas notas de cinco de sete pessoas. Contra o que a aula diz que uma contagem assim protege?'),
     ('Loud against repeated.', 'Barulhento contra repetido.'),
     [(1, 'The loud thing winning over the repeated thing',
       'Right: a pattern across a team shows only when it is counted.',
       'A coisa barulhenta ganhar da coisa repetida',
       'Isso: um padrão no time só aparece quando é contado.'),
      (0, 'Missing a deadline',
       'Not the point.',
       'Perder um prazo',
       'Não é o ponto.'),
      (0, 'Forgetting what a person said',
       'The notes themselves do that.',
       'Esquecer o que uma pessoa disse',
       'As próprias notas fazem isso.'),
      (0, 'Payments refusing the next request because nobody had written it down in a ticket',
       'Not the point.',
       'Pagamentos recusar o próximo pedido porque ninguém tinha escrito num ticket',
       'Não é o ponto.')])

quiz('ex-h63t3zxt', None, 'hard',
     ('Otávio says no to two days a week for Paula’s reminders handover. How does Renata deliver it?',
      'O Otávio diz não aos dois dias por semana para a passagem do serviço de lembretes da Paula. Como a Renata comunica isso?'),
     ('The team’s answer.', 'A resposta do time.'),
     [(1, 'As the team’s answer, with the reason and what is possible instead',
       'Right: a no from above is delivered as the team’s answer.',
       'Como resposta do time, com o motivo e o que é possível no lugar',
       'Isso: um não de cima é comunicado como resposta do time.'),
      (0, 'As Otávio’s decision, which she disagrees with',
       'That turns it into a grievance.',
       'Como decisão do Otávio, da qual ela discorda',
       'Isso o transforma em queixa.'),
      (0, 'She does not; Paula will see it in the plan',
       'Silence answers for her, badly.',
       'Ela não comunica; a Paula vai ver no plano',
       'O silêncio responde por ela, mal.'),
      (0, 'By promising to try again next week',
       'The revisit date is part of it, but a promise to win is not hers.',
       'Prometendo tentar de novo na semana seguinte',
       'A data de revisão faz parte, mas prometer ganhar não cabe a ela.')])

# lesson 8 — feedback

match('ex-z1brwq3x', None, 'easy',
      ('Match each part of situation, behaviour, impact to what it says.',
       'Ligue cada parte de situação, comportamento, impacto ao que ela diz.'),
      ('When, what, what it caused.', 'Quando, o quê, o que causou.'),
      [('situation', 'when it happened', 'situação', 'quando aconteceu'),
       ('behaviour', 'what he did, as somebody could have filmed it', 'comportamento', 'o que ele fez, como alguém poderia ter filmado'),
       ('impact', 'what it caused', 'impacto', 'o que isso causou')],
      [('what kind of person he is', 'que tipo de pessoa ele é')])

quiz('ex-fv51exz3', None, 'medium',
     ('"You’re not a team player." Which problem does the lesson find with that sentence as feedback?',
      '"Você não joga em equipe." Que problema a aula vê nessa frase como feedback?'),
     ('Judgement or observation.', 'Julgamento ou observação.'),
     [(1, 'It is a judgement about the person, arguable and with no instruction in it',
       'Right: the person cannot picture a moment or know what to change.',
       'É um julgamento sobre a pessoa, discutível e sem instrução dentro',
       'Isso: a pessoa não consegue visualizar um momento nem saber o que mudar.'),
      (0, 'It is too long',
       'Length is not the problem.',
       'É longa demais',
       'O tamanho não é o problema.'),
      (0, 'It should have been written down',
       'Writing a judgement does not make it feedback.',
       'Deveria ter sido escrita',
       'Escrever um julgamento não o torna feedback.'),
      (0, 'It is too gentle',
       'It is not gentle; it is unusable.',
       'É suave demais',
       'Não é suave; é inútil.')])

match('ex-cjb85hht', None, 'medium',
      ('Match each corner of Kim Scott’s picture to its name.',
       'Ligue cada canto da imagem de Kim Scott ao seu nome.'),
      ('Caring and challenging.', 'Importar-se e desafiar.'),
      [('caring without challenging', 'ruinous empathy', 'importar-se sem desafiar', 'empatia ruinosa'),
       ('challenging without caring', 'obnoxious aggression', 'desafiar sem se importar', 'agressividade detestável'),
       ('neither', 'manipulative insincerity', 'nenhum dos dois', 'falsidade manipuladora'),
       ('both', 'radical candour', 'os dois', 'franqueza radical')])

quiz('ex-9fjmr6s6', None, 'medium',
     ('What does the lesson say follows from feedback being given soon after the event?',
      'O que a aula diz que decorre de o feedback ser dado logo depois do acontecido?'),
     ('Reviews.', 'Avaliações.'),
     [(1, 'Nothing in a performance review should be a surprise',
       'Right: the review collects what was already said.',
       'Nada numa avaliação de desempenho deveria ser surpresa',
       'Isso: a avaliação reúne o que já foi dito.'),
      (0, 'Corrective feedback goes in writing first',
       'Say it first, write it after.',
       'Feedback corretivo vai por escrito primeiro',
       'Diga primeiro, escreva depois.'),
      (0, 'Corrective feedback is best in the team meeting, while everybody still remembers the event',
       'Corrective feedback is private.',
       'Feedback corretivo funciona melhor na reunião do time, enquanto todo mundo ainda lembra do caso',
       'Feedback corretivo é em particular.'),
      (0, 'Feedback is saved for the review',
       'The opposite.',
       'O feedback é guardado para a avaliação',
       'O contrário.')])

# lesson 9 — positive feedback

quiz('ex-n3jgfhck', None, 'easy',
     ('Why does the lesson say most praise is wasted?',
      'Por que a aula diz que quase todo elogio é desperdiçado?'),
     ('Great in what way?', 'Ótimo em quê?'),
     [(1, 'It is too vague to say what to repeat',
       'Right: "great job" does not say in what way, against what, or for whom.',
       'É vago demais para dizer o que repetir',
       'Isso: "ótimo trabalho" não diz em quê, comparado com quê, nem para quem.'),
      (0, 'People distrust it, because managers praise to soften criticism',
       'Specific praise is trusted.',
       'As pessoas desconfiam dele, porque gestoras elogiam para amaciar críticas',
       'Elogio específico é confiável.'),
      (0, 'There is too much of it in most teams, so each piece counts for less than the last',
       'Quantity is not the claim.',
       'Há elogio demais na maioria dos times, então cada um vale menos que o anterior',
       'Quantidade não é a afirmação.'),
      (0, 'It is given in public',
       'Not the claim.',
       'É dado em público',
       'Não é a afirmação.')])

quiz('ex-jvqmsqs2', None, 'medium',
     ('What happened to the Losada ratio of positive to negative interactions?',
      'O que aconteceu com a proporção de Losada entre interações positivas e negativas?'),
     ('Its mathematics.', 'A matemática dela.'),
     [(1, 'The mathematics behind it was withdrawn',
       'Right: no ratio tells a manager how much praise to give.',
       'A matemática por trás dela foi retirada',
       'Isso: nenhuma proporção diz a uma gestora quanto elogiar.'),
      (0, 'It was confirmed by later studies across hundreds of teams',
       'It was not.',
       'Foi confirmada por estudos posteriores com centenas de times',
       'Não foi.'),
      (0, 'It became the standard for performance reviews across the industry',
       'Not described.',
       'Virou o padrão das avaliações de desempenho no setor',
       'Não é o descrito.'),
      (0, 'It was raised from 3 to 5',
       'Not described.',
       'Foi elevada de 3 para 5',
       'Não é o descrito.')])

quiz('ex-dy4zavrd', None, 'medium',
     ('Praise for a trait against praise for a choice: what does each teach?',
      'Elogio a um traço contra elogio a uma escolha: o que cada um ensina?'),
     ('The label.', 'O rótulo.'),
     [(1, 'A trait teaches people to protect the label; a choice teaches them to repeat the choice',
       'Right.',
       'Um traço ensina a proteger o rótulo; uma escolha ensina a repetir a escolha',
       'Isso.'),
      (0, 'A trait and a choice teach the same thing',
       'They do not.',
       'Elogio a um traço e elogio a uma escolha: cada um ensina a mesma coisa',
       'Não ensinam.'),
      (0, 'A trait builds confidence; a choice builds dependence',
       'Not the claim.',
       'Um traço gera confiança; uma escolha gera dependência',
       'Não é a afirmação.'),
      (0, 'A choice is for juniors and a trait is for seniors',
       'Not the claim.',
       'Uma escolha é para juniores e um traço é para seniores',
       'Não é a afirmação.')])

mc('ex-g29q4da9', None, 'hard',
   ('Which are the lesson’s reasons public praise can go wrong?',
    'Quais são os motivos da aula para um elogio público dar errado?'),
   ('Three of five.', 'Três das cinco.'),
   [(1, 'The person dislikes attention', 'Right.', 'A pessoa não gosta de atenção', 'Isso.'),
    (1, 'It credits whoever presented rather than whoever did the work', 'Right: be precise about who did what.',
     'Credita quem apresentou, e não quem fez o trabalho', 'Isso: seja precisa sobre quem fez o quê.'),
    (1, 'It goes to the same people each time', 'Right: visible work goes to the same few.',
     'Vai para as mesmas pessoas a cada vez', 'Isso: trabalho visível vai para os mesmos poucos.'),
    (0, 'It is against company policy', 'Not a reason given.',
     'É contra a política da empresa', 'Não é um motivo dado.'),
    (0, 'It makes the praise count for less', 'Not a reason given.',
     'Faz o elogio valer menos', 'Não é um motivo dado.')])

# lesson 10 — the line

mc('ex-pfpxwz3q', None, 'medium',
   ('Which are the three tests for when feedback has become a performance conversation?',
    'Quais são os três testes para saber quando o feedback virou uma conversa de desempenho?'),
   ('Three of five.', 'Três das cinco.'),
   [(1, 'It has happened more than once', 'Right: a pattern, not a moment.',
     'Aconteceu mais de uma vez', 'Isso: um padrão, não um momento.'),
    (1, 'The person has had clear feedback about it', 'Right.',
     'A pessoa já recebeu feedback claro sobre isso', 'Isso.'),
    (1, 'It affects what the role requires', 'Right.',
     'Afeta o que o cargo exige', 'Isso.'),
    (0, 'The manager is frustrated', 'Not a test.',
     'A gestora está frustrada', 'Não é um teste.'),
    (0, 'A peer has complained', 'Not a test.',
     'Um colega reclamou', 'Não é um teste.')])

quiz('ex-rcg38nkr', None, 'medium',
     ('Which way of opening a performance conversation does the lesson call burying it?',
      'Que jeito de abrir uma conversa de desempenho a aula chama de enterrá-la?'),
     ('Ten minutes first.', 'Dez minutos antes.'),
     [(1, 'Ten minutes on how the team is doing and some praise, then the concern near the end',
       'Right: the person leaves remembering the first part.',
       'Dez minutos sobre como o time está e um elogio, e então a preocupação perto do fim',
       'Isso: a pessoa sai lembrando da primeira parte.'),
      (0, '"Maybe think a little about your estimates"',
       'That is softening it into a suggestion.',
       '"Talvez valha pensar um pouco nas suas estimativas"',
       'Isso é amaciá-la até virar sugestão.'),
      (0, 'Disputing each example',
       'That is arguing about each instance.',
       'Disputar cada exemplo',
       'Isso é discutir cada caso.'),
      (0, 'Naming the pattern first',
       'That is the recommended opening.',
       'Nomear o padrão primeiro',
       'Essa é a abertura recomendada.')])

quiz('ex-hg1ny4cd', None, 'hard',
     ('What does the lesson say the written summary after a performance conversation records, beside the facts?',
      'O que a aula diz que o resumo escrito depois de uma conversa de desempenho registra, além dos fatos?'),
     ('Both sides.', 'Os dois lados.'),
     [(1, 'What the person said, with an invitation to correct it',
       'Right: facts, not conclusions, and room for correction.',
       'O que a pessoa disse, com um convite para corrigir',
       'Isso: fatos, não conclusões, e espaço para correção.'),
      (0, 'The manager’s conclusion about the person',
       'Facts, not conclusions.',
       'A conclusão da gestora sobre a pessoa',
       'Fatos, não conclusões.'),
      (0, 'A deadline for dismissal',
       'Not at this stage.',
       'Um prazo para demissão',
       'Não nesta etapa.'),
      (0, 'A comparison with how other people on the team perform the same work, by name',
       'Not described.',
       'Uma comparação com como outras pessoas do time fazem o mesmo trabalho, nominalmente',
       'Não é o descrito.')])

cloze('ex-ta5q7ngb', None, 'medium',
      ('If the person cannot say what the meeting was about, the meeting did not ____.',
       'Se a pessoa não consegue dizer sobre o que foi a reunião, a reunião não ____.'),
      ('It might as well not have.', 'Como se não tivesse.'),
      [(['happen', 'take place'], ['aconteceu', 'existiu'])])

# lesson 11 — the ladder

quiz('ex-axv0m58v', None, 'easy',
     ('What is a career ladder for, by the lesson?',
      'Para que serve uma escada de carreira, pela aula?'),
     ('From a feeling.', 'De um sentimento.'),
     [(1, 'Turning "is this person senior?" into a question with a written answer',
       'Right: so the same work earns the same title under any manager.',
       'Transformar "esta pessoa é sênior?" numa pergunta com resposta escrita',
       'Isso: para o mesmo trabalho valer o mesmo título com qualquer gestora.'),
      (0, 'A checklist to tick',
       'It is not a checklist.',
       'Uma lista para ticar',
       'Não é uma lista de verificação.'),
      (0, 'A schedule of promotions by years of service, so people know when their turn comes',
       'It is not a schedule.',
       'Um calendário de promoções por tempo de casa, para cada um saber quando chega a vez',
       'Não é um calendário.'),
      (0, 'Setting salaries',
       'Not its purpose in the lesson.',
       'Definir salários',
       'Não é o propósito na aula.')])

quiz('ex-ezfe5j2r', None, 'medium',
     ('Why does Caju’s ladder leave years of experience out?',
      'Por que a escada da Caju deixa os anos de experiência de fora?'),
     ('Exposure.', 'Exposição.'),
     [(1, 'Years measure exposure, not growth',
       'Right: and they correlate with things a company should not reward for their own sake.',
       'Anos medem exposição, não crescimento',
       'Isso: e se correlacionam com coisas que uma empresa não deveria recompensar por si.'),
      (0, 'They are hard to verify',
       'Not the reason.',
       'São difíceis de verificar',
       'Não é o motivo.'),
      (0, 'Labour law forbids mentioning them in a ladder, so the company removed them on legal advice',
       'Not the reason.',
       'A lei trabalhista proíbe citá-los numa escada, então a empresa os tirou por orientação jurídica',
       'Não é o motivo.'),
      (0, 'Everybody at Caju has similar experience',
       'Not the reason.',
       'Todo mundo na Caju tem experiência parecida',
       'Não é o motivo.')])

quiz('ex-vbf0n293', None, 'medium',
     ('On Caju’s ladder, what is becoming a manager?',
      'Na escada da Caju, o que é virar gestora?'),
     ('Not the next rung.', 'Não o próximo degrau.'),
     [(1, 'A move sideways into a different job, at roughly the same level of responsibility',
       'Right: an E4 can earn more than an M1.',
       'Um movimento lateral para outro trabalho, com mais ou menos o mesmo nível de responsabilidade',
       'Isso: um E4 pode ganhar mais que um M1.'),
      (0, 'A promotion above E5',
       'M1 sits beside E3 and E4.',
       'Uma promoção acima do E5',
       'O M1 fica ao lado do E3 e do E4.'),
      (0, 'A step down',
       'Not a step down either.',
       'Um passo para baixo',
       'Também não é um passo para baixo.'),
      (0, 'The only route past senior',
       'The engineering track continues to E4 and E5.',
       'O único caminho além de sênior',
       'A trilha de engenharia continua até E4 e E5.')])

match('ex-46gxnr9t', None, 'medium',
      ('Match each level on Caju’s ladder with its scope.',
       'Ligue cada nível da escada da Caju ao seu escopo.'),
      ('Scope grows.', 'O escopo cresce.'),
      [('E4, staff', 'an area spanning several teams',
        'E4, staff', 'uma área que abrange vários times'),
       ('E5, principal', 'the technical direction of a product line, over years',
        'E5, principal', 'a direção técnica de uma linha de produto, ao longo de anos'),
       ('M2', 'a manager of managers', 'M2', 'uma gestora de gestoras')],
      [('a single feature', 'uma única funcionalidade')])

# lesson 12 — the case

quiz('ex-tatvpyd6', None, 'easy',
     ('How long do most panels want to see next-level work sustained?',
      'Por quanto tempo a maioria dos comitês quer ver o trabalho do próximo nível sustentado?'),
     ('A pattern.', 'Um padrão.'),
     [(1, 'Something like six months to a year',
       'Right: enough time to show a pattern.',
       'Algo como seis meses a um ano',
       'Isso: tempo suficiente para mostrar um padrão.'),
      (0, 'One project, if it was large and went well',
       'One project is a moment.',
       'Um projeto, se foi grande e deu certo',
       'Um projeto é um momento.'),
      (0, 'Two weeks',
       'Too short.',
       'Duas semanas',
       'Curto demais.'),
      (0, 'Three years, to be certain the person will not slip back once promoted',
       'Longer than the lesson describes.',
       'Três anos, para ter certeza de que a pessoa não vai regredir depois de promovida',
       'Mais longo do que a aula descreve.')])

quiz('ex-aqnpwzsj', None, 'medium',
     ('Why does a promotion case name its own gaps?',
      'Por que um caso de promoção cita as próprias lacunas?'),
     ('What a panel does with a hidden one.', 'O que um comitê faz com uma escondida.'),
     [(1, 'A panel that finds a weakness the manager left out starts doubting everything else',
       'Right: naming it keeps the rest credible.',
       'Um comitê que acha uma fraqueza que a gestora deixou de fora passa a duvidar de todo o resto',
       'Isso: citá-la mantém o resto crível.'),
      (0, 'The template requires it',
       'Not the reason.',
       'O modelo exige',
       'Não é o motivo.'),
      (0, 'To lower expectations',
       'Not the reason.',
       'Para baixar as expectativas',
       'Não é o motivo.'),
      (0, 'To show modesty',
       'Not the reason.',
       'Para mostrar modéstia',
       'Não é o motivo.')])

order('ex-2k70qxd6', None, 'medium',
      ('Put the parts of the conversation after the panel in order.',
       'Ponha em ordem as partes da conversa depois do comitê.'),
      ('The decision leads.', 'A decisão vem na frente.'),
      [('the decision, plainly', 'a decisão, com clareza'),
       ('the panel’s reasons, specifically', 'os motivos do comitê, especificamente'),
       ('what would change the answer', 'o que mudaria a resposta'),
       ('room for the person’s reaction', 'espaço para a reação da pessoa')],
      trap=('Leading with reasons before the decision keeps the person guessing.',
            'Começar pelos motivos antes da decisão deixa a pessoa adivinhando.'))

quiz('ex-p284qa6w', None, 'hard',
     ('Which question does the lesson say a panel asks about each piece of evidence?',
      'Que pergunta a aula diz que um comitê faz sobre cada evidência?'),
     ('Whose work.', 'De quem é o trabalho.'),
     [(1, 'Is this the person’s work or the team’s?',
       'Right: among sustained, real scope, and what peers would say.',
       'Isto é trabalho da pessoa ou do time?',
       'Isso: ao lado de sustentado, escopo real, e o que os pares diriam.'),
      (0, 'Does the manager vouch for the person, and how strongly?',
       'The panel exists to remove that.',
       'A gestora garante a pessoa, e com que força?',
       'O comitê existe para remover isso.'),
      (0, 'How many years has the person been at the company, and at the current level?',
       'Years are not on the ladder.',
       'Há quantos anos a pessoa está na empresa, e no nível atual?',
       'Anos não estão na escada.'),
      (0, 'Was it shipped on time?',
       'Not one of the panel’s questions.',
       'Foi entregue no prazo?',
       'Não é uma das perguntas do comitê.')])

# lesson 13 — growth without promotion

mc('ex-cy2gthr7', None, 'easy',
   ('Which are the three directions of growth between promotions?',
    'Quais são as três direções de crescimento entre promoções?'),
   ('Three of five.', 'Três das cinco.'),
   [(1, 'Scope', 'Right: the most direct preparation for a promotion.', 'Escopo', 'Isso: a preparação mais direta para uma promoção.'),
    (1, 'Depth', 'Right: needs a supply of hard problems.', 'Profundidade', 'Isso: precisa de um suprimento de problemas difíceis.'),
    (1, 'Visibility', 'Right: work nobody outside has seen counts for nothing beyond the team.',
     'Visibilidade', 'Isso: trabalho que ninguém de fora viu não conta além do time.'),
    (0, 'Tenure', 'Years measure exposure, not growth.', 'Tempo de casa', 'Anos medem exposição, não crescimento.'),
    (0, 'Headcount', 'Not one of the three.', 'Número de pessoas', 'Não é uma das três.')])

quiz('ex-bfrvp52m', None, 'medium',
     ('Tanya Reilly’s glue work: what does the lesson say is wrong with it in most teams?',
      'O trabalho de cola de Tanya Reilly: o que a aula diz que está errado com ele na maioria dos times?'),
     ('Undescribed.', 'Não descrito.'),
     [(1, 'It is essential, under-rewarded, and handed to the same kinds of people',
       'Right: the fix is to rotate it, name it, and map it to the ladder.',
       'É essencial, pouco recompensado, e entregue ao mesmo tipo de pessoa',
       'Isso: o conserto é fazer rodízio, nomear e ligar à escada.'),
      (0, 'It is unnecessary',
       'It is essential.',
       'É desnecessário',
       'É essencial.'),
      (0, 'It should be done by managers',
       'Not the claim.',
       'Deveria ser feito por gestoras',
       'Não é a afirmação.'),
      (0, 'It is invisible',
       'The lesson says it is undescribed, not invisible.',
       'É invisível',
       'A aula diz que ele não é descrito, não que é invisível.')])

quiz('ex-8mke5164', None, 'medium',
     ('What makes a stretch assignment a stretch rather than a setup to fail?',
      'O que faz uma tarefa desafiadora ser um desafio e não uma armadilha?'),
     ('Survivable.', 'Sobrevivível.'),
     [(1, 'Enough support that failing at it is survivable',
       'Right: at the edge of ability, with one new thing and a plan for going wrong.',
       'Apoio suficiente para que falhar seja sobrevivível',
       'Isso: no limite da capacidade, com uma coisa nova e um plano se der errado.'),
      (0, 'It is very hard',
       'Hard alone is not a stretch.',
       'É muito difícil',
       'Difícil sozinho não é desafio.'),
      (0, 'Several new things at once, so the person grows faster in a single quarter',
       'One new thing.',
       'Várias coisas novas ao mesmo tempo, para a pessoa crescer mais rápido num só trimestre',
       'Uma coisa nova.'),
      (0, 'A promotion if it succeeds',
       'Not part of the definition.',
       'Uma promoção se der certo',
       'Não faz parte da definição.')])

quiz('ex-nhcm534t', None, 'hard',
     ('An excellent E3 says she wants none of the three directions this year. What does the lesson say?',
      'Uma E3 excelente diz que não quer nenhuma das três direções este ano. O que a aula diz?'),
     ('A person can want none.', 'Uma pessoa pode não querer nenhuma.'),
     [(1, 'That is a legitimate answer, and staying at E3 doing excellent work is not failing',
       'Right: valuing only upward growth leaves a team that feels it is failing.',
       'É uma resposta legítima, e ficar em E3 fazendo um trabalho excelente não é fracasso',
       'Isso: valorizar só o crescimento para cima deixa um time que se sente fracassando.'),
      (0, 'She should be put on a plan',
       'There is no gap.',
       'Ela deveria entrar num plano',
       'Não há lacuna.'),
      (0, 'Give her a stretch anyway',
       'Against her stated wish.',
       'Dar um desafio mesmo assim',
       'Contra o desejo declarado dela.'),
      (0, 'Ask again every week',
       'Not what the lesson says.',
       'Perguntar de novo toda semana',
       'Não é o que a aula diz.')])

# lesson 14 — hiring

quiz('ex-dwdba46b', None, 'easy',
     ('Which question should a job description start from?',
      'De que pergunta uma descrição de vaga deveria partir?'),
     ('First six months.', 'Primeiros seis meses.'),
     [(1, 'What will this person actually do in their first six months?',
       'Right: and then three musts, not fourteen.',
       'O que esta pessoa vai fazer de fato nos primeiros seis meses?',
       'Isso: e depois três obrigatórios, não catorze.'),
      (0, 'What did the last job description say?',
       'Copying keeps its mistakes.',
       'O que dizia a última descrição de vaga?',
       'Copiar mantém os erros.'),
      (0, 'Which technologies are we using?',
       'Years of a technology are a filter that misleads.',
       'Que tecnologias estamos usando?',
       'Anos de uma tecnologia são um filtro que engana.'),
      (0, 'What would the ideal candidate have, if we could hire anybody at all?',
       'That produces fourteen musts.',
       'O que a candidata ideal teria, se pudéssemos contratar qualquer pessoa?',
       'Isso produz catorze obrigatórios.')])

num('ex-kpvwsfen', None, 'medium',
    ('Six candidates each had four final interviews of 1.5 hours. How many hours of interviewers’ time is that?',
     'Seis candidatas tiveram cada uma quatro entrevistas finais de 1,5 hora. Quantas horas de tempo de entrevistadores isso dá?'),
    ('6 × 4 × 1.5.', '6 × 4 × 1,5.'),
    36, 0, ('hours', 'horas'), (['h', 'hour'], ['h', 'hora']))

num('ex-4r5ezgwh', None, 'medium',
    ('In Agenda’s funnel, 30 people had the recruiter call and 15 passed. What percentage passed?',
     'No funil do Agenda, 30 pessoas fizeram a conversa com a recrutadora e 15 passaram. Que porcentagem passou?'),
    ('15 over 30.', '15 sobre 30.'),
    50, 0, ('percent', 'por cento'), (['%'], ['%']))

quiz('ex-gbpe52z2', None, 'medium',
     ('One of Agenda’s two offers was declined. Why, and what does the lesson take from it?',
      'Uma das duas propostas do Agenda foi recusada. Por quê, e o que a aula tira disso?'),
     ('The week to decide.', 'A semana para decidir.'),
     [(1, 'The candidate accepted elsewhere during the week Caju took to decide; nobody should wait more than a week between stages',
       'Right: a process that loses offers at the end wasted the earlier effort.',
       'A candidata aceitou outra proposta na semana que a Caju levou para decidir; ninguém deveria esperar mais de uma semana entre etapas',
       'Isso: um processo que perde propostas no fim desperdiçou o esforço anterior.'),
      (0, 'The salary was too low',
       'Not the reason given.',
       'O salário era baixo demais',
       'Não é o motivo dado.'),
      (0, 'The interview was too hard',
       'Not the reason given.',
       'A entrevista foi difícil demais',
       'Não é o motivo dado.'),
      (0, 'The candidate disliked the team',
       'Not the reason given.',
       'A candidata não gostou do time',
       'Não é o motivo dado.')])

quiz('ex-46zqbxwe', None, 'hard',
     ('At week six, Helena asked whether the bar could be lowered because the confirmations work was late. What does the lesson weigh against that?',
      'Na sexta semana, a Helena perguntou se a barra podia baixar porque o trabalho de confirmações estava atrasado. O que a aula pesa contra isso?'),
     ('The cost of a wrong hire.', 'O custo de uma contratação errada.'),
     [(1, 'A hire who cannot do the job costs months of the team’s time',
       'Right: in support, difficult conversations and perhaps a dismissal.',
       'Uma contratação que não dá conta do trabalho custa meses de tempo do time',
       'Isso: em apoio, conversas difíceis e talvez uma demissão.'),
      (0, 'The recruiter would object',
       'Not the argument.',
       'A recrutadora se oporia',
       'Não é o argumento.'),
      (0, 'Lowering the bar is illegal',
       'Not the argument.',
       'Baixar a barra é ilegal',
       'Não é o argumento.'),
      (0, 'The confirmations work was not important enough to justify any trade-off at all',
       'It was important; the trade was still bad.',
       'O trabalho de confirmações não era importante o bastante para justificar troca nenhuma',
       'Era importante; a troca continuava ruim.')])

# lesson 15 — structured interviews

quiz('ex-25gx7926', None, 'easy',
     ('What makes an interview structured?',
      'O que faz uma entrevista ser estruturada?'),
     ('Same, from the job, anchored.', 'Mesmas, do cargo, ancoradas.'),
     [(1, 'The same questions for every candidate, from the job, scored against a scale written in advance',
       'Right: and each interviewer scores alone before discussion.',
       'As mesmas perguntas para toda candidata, vindas do cargo, pontuadas contra uma escala escrita antes',
       'Isso: e cada pessoa entrevistadora pontua sozinha antes da discussão.'),
      (0, 'A fixed length',
       'Length is not structure.',
       'Uma duração fixa',
       'Duração não é estrutura.'),
      (0, 'A panel of four',
       'Not the definition.',
       'Uma banca de quatro pessoas',
       'Não é a definição.'),
      (0, 'A coding exercise',
       'Not the definition.',
       'Um exercício de código',
       'Não é a definição.')])

num('ex-xt70d5xn', None, 'medium',
    ('In Schmidt and Hunter’s review, structured interviews had a validity of about 0.42 and unstructured ones about 0.19. Roughly how many times more predictive were structured ones? Give a whole number.',
     'Na revisão de Schmidt e Hunter, entrevistas estruturadas tinham validade de cerca de 0,42 e as não estruturadas cerca de 0,19. Aproximadamente quantas vezes mais preditivas eram as estruturadas? Dê um número inteiro.'),
    ('0.42 over 0.19.', '0,42 sobre 0,19.'),
    2, 0, ('times', 'vezes'), (['x', '×'], ['x', '×']))

quiz('ex-p9cvqqgk', None, 'medium',
     ('Where does the lesson say questions you have no right to ask slip into an interview?',
      'Por onde a aula diz que escapam as perguntas que você não tem direito de fazer numa entrevista?'),
     ('Before the real questions.', 'Antes das perguntas de verdade.'),
     [(1, 'Small talk',
       'Right: the interview is for evidence about the must list.',
       'A conversa informal',
       'Isso: a entrevista é para evidência sobre os obrigatórios.'),
      (0, 'The technical exercise',
       'Not where the lesson places them.',
       'O exercício técnico',
       'Não é onde a aula os coloca.'),
      (0, 'The written rubric',
       'The rubric is what keeps them out.',
       'A rubrica escrita',
       'A rubrica é o que as mantém fora.'),
      (0, 'The offer letter, when the terms are negotiated and the candidate’s situation comes up',
       'Not where the lesson places them.',
       'A carta de proposta, quando os termos são negociados e a situação da candidata aparece',
       'Não é onde a aula os coloca.')])

cloze('ex-ye1pvdwr', None, 'medium',
      ('Each level of a rubric describes what is in the answer, not how good it ____.',
       'Cada nível de uma rubrica descreve o que está na resposta, não quão boa ela ____.'),
      ('An impression.', 'Uma impressão.'),
      [(['felt', 'seemed'], ['pareceu', 'soou'])])

# lesson 16 — formats

match('ex-kmze3m4r', None, 'medium',
      ('Match each format to what it measures besides the job.',
       'Ligue cada formato ao que ele mede além do trabalho.'),
      ('The incidental thing.', 'A coisa incidental.'),
      [('take-home', 'how much free time the candidate has', 'exercício para casa', 'quanto tempo livre a candidata tem'),
       ('pairing', 'comfort with being observed', 'pareamento', 'conforto em ser observada'),
       ('live coding', 'performance under pressure, and anxiety', 'código ao vivo', 'desempenho sob pressão, e ansiedade')],
      [('the candidate’s degree', 'o diploma da candidata')])

quiz('ex-v2k6vbvr', None, 'medium',
     ('Of the three formats, which does the lesson call furthest from how the job is done?',
      'Dos três formatos, qual a aula chama de mais distante de como o trabalho é feito?'),
     ('A stranger watching.', 'Uma pessoa estranha olhando.'),
     [(1, 'Live coding',
       'Right: a candidate who freezes in front of a stranger may be excellent at a desk.',
       'Código ao vivo',
       'Isso: quem trava diante de uma pessoa estranha pode ser excelente numa mesa.'),
      (0, 'Take-home',
       'It is close to working alone, if it is short.',
       'Exercício para casa',
       'É próximo de trabalhar sozinha, se for curto.'),
      (0, 'Pairing',
       'Close to how Agenda works.',
       'Pareamento',
       'Próximo de como o Agenda trabalha.'),
      (0, 'They are equally far from the job, since every interview is artificial in the same way',
       'The lesson ranks them.',
       'Estão igualmente longe do trabalho, já que toda entrevista é artificial do mesmo jeito',
       'A aula os ordena.')])

mc('ex-2vt0n14e', None, 'hard',
   ('Which choices did Caju make in its pairing interview for Agenda’s E2 role?',
    'Que escolhas a Caju fez na entrevista de pareamento para a vaga de E2 do Agenda?'),
   ('Three of five.', 'Três das cinco.'),
   [(1, 'Give the problem in advance', 'Right.', 'Dar o problema antes', 'Isso.'),
    (1, 'Let them use real tools', 'Right.', 'Deixar usar ferramentas de verdade', 'Isso.'),
    (1, 'The interviewer pairs rather than watches', 'Right: Yara pairs, she does not watch.',
     'Quem entrevista pareia em vez de observar', 'Isso: a Yara pareia, não observa.'),
    (0, 'Add a second interviewer to observe', 'More observation, not less.',
     'Acrescentar uma segunda pessoa para observar', 'Mais observação, não menos.'),
    (0, 'Time each step', 'Adds pressure.', 'Cronometrar cada passo', 'Acrescenta pressão.')])

quiz('ex-94pnm1t9', None, 'medium',
     ('What does the lesson say about a take-home exercise of several hours?',
      'O que a aula diz sobre um exercício para casa de várias horas?'),
     ('Free time.', 'Tempo livre.'),
     [(1, 'Keep it short and mean it, or pay for it, or replace it',
       'Right: otherwise it measures who has free evenings.',
       'Mantenha curto e de verdade, ou pague, ou ofereça alternativa',
       'Isso: senão mede quem tem noites livres.'),
      (0, 'Longer is fairer',
       'Longer favours free time.',
       'Mais longo é mais justo',
       'Mais longo favorece tempo livre.'),
      (0, 'Never discuss it afterwards',
       'Talking about it afterwards is one of the fixes.',
       'Nunca discutir depois',
       'Conversar depois é um dos consertos.'),
      (0, 'Use it only for senior roles, where candidates are expected to give more of their own time',
       'Not the lesson’s advice.',
       'Usar só em vagas seniores, em que se espera que candidatas deem mais do próprio tempo',
       'Não é o conselho da aula.')])

# lesson 17 — calibration and bias

quiz('ex-306j1mj2', None, 'easy',
     ('In Renata’s debriefs, who speaks last?',
      'Nas conversas de decisão da Renata, quem fala por último?'),
     ('The anchor.', 'A âncora.'),
     [(1, 'The hiring manager',
       'Right: otherwise everybody adjusts towards her.',
       'A gestora que contrata',
       'Isso: senão todo mundo se ajusta a ela.'),
      (0, 'The most senior engineer',
       'Diego speaking first was the problem.',
       'O engenheiro mais sênior',
       'O Diego falar primeiro era o problema.'),
      (0, 'The recruiter',
       'Not the rule.',
       'A recrutadora',
       'Não é a regra.'),
      (0, 'Whoever gave the lowest score, so the disagreement is heard after the others',
       'Renata started with the disagreement, not ended with it.',
       'Quem deu a nota mais baixa, para a discordância ser ouvida depois das outras',
       'A Renata começou pela discordância, não terminou com ela.')])

match('ex-1mb3967a', None, 'medium',
      ('Match each bias to what it does in an interview.',
       'Ligue cada viés ao que ele faz numa entrevista.'),
      ('Five named in the lesson.', 'Cinco citados na aula.'),
      [('halo effect', 'one strong impression colours every other score', 'efeito halo', 'uma impressão forte colore todas as outras notas'),
       ('similarity', 'liking candidates who resemble the interviewer', 'semelhança', 'gostar de quem se parece com quem entrevista'),
       ('confirmation', 'seeking evidence for a first impression', 'confirmação', 'procurar evidência para uma primeira impressão'),
       ('contrast', 'judging a candidate against the one before', 'contraste', 'julgar uma candidata pela anterior')],
      [('rewarding years of experience', 'recompensar anos de experiência')])

quiz('ex-2gpwetm8', None, 'medium',
     ('Why may nobody change their written score in the debrief?',
      'Por que ninguém pode mudar a nota escrita na conversa de decisão?'),
     ('Anchors.', 'Âncoras.'),
     [(1, 'Changes there come from the anchor, not from new evidence',
       'Right: independent scores are what the rest protects.',
       'Mudanças ali vêm da âncora, não de evidência nova',
       'Isso: notas independentes são o que o resto protege.'),
      (0, 'The scores are sent to HR the evening before, and HR files them',
       'Not the reason.',
       'As notas vão para o RH na véspera, e o RH as arquiva',
       'Não é o motivo.'),
      (0, 'It would take too long to redo the arithmetic for every candidate in the round',
       'Not the reason.',
       'Levaria tempo demais refazer as contas de cada candidata da rodada',
       'Não é o motivo.'),
      (0, 'Labour law forbids it',
       'Not the reason.',
       'A lei trabalhista proíbe',
       'Não é o motivo.')])

quiz('ex-2ba2fn6f', None, 'hard',
     ('Lucas scored 3 and 4 on two musts and 2 on the third. Caju’s rule needed at least 3 on two of three and no 1. What did Renata do?',
      'O Lucas teve 3 e 4 em dois obrigatórios e 2 no terceiro. A regra da Caju pedia pelo menos 3 em dois dos três e nenhum 1. O que a Renata fez?'),
     ('The rule written in advance.', 'A regra escrita antes.'),
     [(1, 'Made the offer, recording the third must as the area to support in his first months',
       'Right: decided against the rule, with the reason written down.',
       'Fez a proposta, registrando o terceiro obrigatório como a área a apoiar nos primeiros meses',
       'Isso: decidiu pela regra, com o motivo escrito.'),
      (0, 'Rejected him for the 2',
       'The rule allowed one score below 3.',
       'Recusou por causa do 2',
       'A regra permitia uma nota abaixo de 3.'),
      (0, 'Asked for another round',
       'Not what happened.',
       'Pediu outra rodada',
       'Não foi o que aconteceu.'),
      (0, 'Raised his 2 to a 3',
       'Nobody changes a written score.',
       'Subiu o 2 dele para 3',
       'Ninguém muda uma nota escrita.')])

# lesson 18 — onboarding

quiz('ex-jnj594t8', None, 'easy',
     ('What does the lesson say should happen in a new person’s first week?',
      'O que a aula diz que deveria acontecer na primeira semana de uma pessoa nova?'),
     ('Visitor or member.', 'Visitante ou membro.'),
     [(1, 'A small, real change of theirs reaches production',
       'Right: after it they are a member who has contributed.',
       'Uma mudança pequena e real dela chega à produção',
       'Isso: depois disso ela é um membro que contribuiu.'),
      (0, 'They read all the documentation first, so nothing in the code surprises them later',
       'Reading alone leaves them a visitor.',
       'Ela lê toda a documentação antes, para nada no código surpreender depois',
       'Só ler a deixa visitante.'),
      (0, 'They take their first on-call shift',
       'On-call comes in stages, later.',
       'Ela pega o primeiro plantão',
       'O plantão vem em etapas, depois.'),
      (0, 'They meet every team in the company',
       'Not the goal named.',
       'Ela conhece todos os times da empresa',
       'Não é o objetivo citado.')])

order('ex-02aneqfh', None, 'medium',
      ('Put the stages of a first on-call shift in order.',
       'Ponha em ordem as etapas de um primeiro plantão.'),
      ('Never truly alone.', 'Nunca de fato sozinha.'),
      [('shadow', 'sombra'), ('reverse shadow', 'sombra invertida'),
       ('primary, with a named backup', 'titular, com apoio nomeado')],
      trap=('Reverse shadow comes second: the new person leads while the experienced one watches.',
            'Sombra invertida vem em segundo: a pessoa nova conduz enquanto a experiente observa.'))

mc('ex-x9mg6wpp', None, 'medium',
   ('Which does the lesson give as signs a new person is struggling quietly?',
    'Quais a aula dá como sinais de que uma pessoa nova está com dificuldade em silêncio?'),
   ('Three of five.', 'Três das cinco.'),
   [(1, 'They stop asking questions', 'Right.', 'Ela para de perguntar', 'Isso.'),
    (1, 'They work late', 'Right.', 'Ela trabalha até tarde', 'Isso.'),
    (1, 'They are quiet in team meetings', 'Right.', 'Ela fica calada nas reuniões do time', 'Isso.'),
    (0, 'They ship a change in the first week', 'That is the goal.', 'Ela entrega uma mudança na primeira semana', 'Esse é o objetivo.'),
    (0, 'They ask the buddy for help', 'That is the system working.', 'Ela pede ajuda à pessoa de referência', 'Esse é o sistema funcionando.')])

quiz('ex-35bx4mdd', None, 'hard',
     ('Lucas’s thirty-sixty-ninety plan says something is off at day forty. What does the lesson say about waiting to give him time to settle in?',
      'O plano de trinta, sessenta e noventa dias do Lucas indica que algo não vai bem no dia quarenta. O que a aula diz sobre esperar para dar tempo de ele se adaptar?'),
     ('Kindest-sounding.', 'O que soa mais gentil.'),
     [(1, 'It is the kindest-sounding version of letting a problem run without feedback',
       'Right: the plan exists so the gap is named early.',
       'É a versão mais gentil na aparência de deixar um problema correr sem feedback',
       'Isso: o plano existe para a lacuna ser nomeada cedo.'),
      (0, 'Ninety days is the right time to judge',
       'The plan has stages so nobody waits for the end.',
       'Noventa dias é o tempo certo para julgar',
       'O plano tem etapas para ninguém esperar o fim.'),
      (0, 'Changing the plan is a failure',
       'A plan is a starting point; changing it is not failure.',
       'Mudar o plano é fracasso',
       'Um plano é um ponto de partida; mudá-lo não é fracasso.'),
      (0, 'Tell the buddy and wait',
       'The manager talks to him.',
       'Avisar a pessoa de referência e esperar',
       'A gestora fala com ele.')])

# lesson 19 — diagnosing underperformance

order('ex-wzpg33cb', None, 'medium',
      ('Put the questions of the lesson’s diagnostic in order.',
       'Ponha em ordem as perguntas do diagnóstico da aula.'),
      ('The manager’s own part comes first; motivation last.', 'A parte da própria gestora vem primeiro; motivação por último.'),
      [('are the expectations clear?', 'as expectativas estão claras?'),
       ('do they have what they need?', 'a pessoa tem o que precisa?'),
       ('could they do it if their life depended on it?', 'conseguiria fazer se a vida dependesse disso?'),
       ('does anything reward doing it badly, or punish doing it well?', 'algo recompensa fazer mal, ou pune fazer bem?'),
       ('is something outside work getting in the way?', 'algo fora do trabalho está atrapalhando?'),
       ('is it motivation?', 'é motivação?')],
      trap=('Starting with motivation blames the person before the manager has checked her own part.',
            'Começar pela motivação culpa a pessoa antes de a gestora conferir a própria parte.'))

quiz('ex-cdbzyj3s', None, 'medium',
     ('Mager and Pipe ask whether the person could do it if their life depended on it. What does a yes tell the manager?',
      'Mager e Pipe perguntam se a pessoa conseguiria fazer se a vida dependesse disso. O que um sim diz à gestora?'),
     ('Skill.', 'Habilidade.'),
     [(1, 'The skill is there, so training is the wrong response',
       'Right: look at consequences, environment and expectations instead.',
       'A habilidade está lá, então treinamento é a resposta errada',
       'Isso: olhe consequências, ambiente e expectativas.'),
      (0, 'The person is lazy',
       'Motivation is the last question, not the conclusion of this one.',
       'A pessoa é preguiçosa',
       'Motivação é a última pergunta, não a conclusão desta.'),
      (0, 'Start an improvement plan straight away, since the gap is now proven to be a choice',
       'Nothing is proven yet.',
       'Começar um plano de melhoria na hora, já que a lacuna agora está provada como escolha',
       'Nada está provado ainda.'),
      (0, 'Give more feedback',
       'Not what the answer points to.',
       'Dar mais feedback',
       'Não é para onde a resposta aponta.')])

quiz('ex-s4fv0pp4', None, 'hard',
     ('Why did Renata start her conversation with Marcos with her own part?',
      'Por que a Renata começou a conversa com o Marcos pela própria parte?'),
     ('What he was willing to say.', 'O que ele estava disposto a dizer.'),
     [(1, 'It changes what the person is willing to say',
       'Right: the conversation was for learning why, not for judging.',
       'Muda o que a pessoa está disposta a dizer',
       'Isso: a conversa era para entender por quê, não para julgar.'),
      (0, 'HR requires it',
       'Not the reason given.',
       'O RH exige',
       'Não é o motivo dado.'),
      (0, 'To soften the bad news before naming the gap',
       'This was a diagnostic conversation, not bad news.',
       'Para amaciar a má notícia antes de nomear a lacuna',
       'Era uma conversa de diagnóstico, não de má notícia.'),
      (0, 'Because the problem was entirely hers, as she had set no expectations at all',
       'None of the six causes was a single answer.',
       'Porque o problema era todo dela, já que não tinha definido expectativa nenhuma',
       'Nenhuma das seis causas era uma resposta única.')])

# lesson 20 — the improvement plan

quiz('ex-yqnn951n', None, 'easy',
     ('What are the two honest outcomes of an improvement plan, which the person has to be told?',
      'Quais são os dois resultados honestos de um plano de melhoria, que a pessoa precisa ouvir?'),
     ('Both of them.', 'Os dois.'),
     [(1, 'The gap closes, or the employment may end',
       'Right: a plan that hides either is not honest.',
       'A lacuna fecha, ou o vínculo pode terminar',
       'Isso: um plano que esconde qualquer um dos dois não é honesto.'),
      (0, 'Promotion or demotion',
       'Not the two outcomes.',
       'Promoção ou rebaixamento',
       'Não são os dois resultados.'),
      (0, 'A raise or a warning',
       'Not the two outcomes.',
       'Aumento ou advertência',
       'Não são os dois resultados.'),
      (0, 'The plan may be extended, or quietly closed and not mentioned again',
       'Not the two outcomes.',
       'O plano pode ser prorrogado, ou encerrado em silêncio sem voltar ao assunto',
       'Não são os dois resultados.')])

quiz('ex-5ya99jzq', None, 'medium',
     ('A manager has already decided somebody must leave. What does the lesson say about writing an improvement plan anyway?',
      'Uma gestora já decidiu que alguém precisa sair. O que a aula diz sobre escrever um plano de melhoria mesmo assim?'),
     ('The honest course.', 'O caminho honesto.'),
     [(1, 'Say so and go through the company’s process for ending employment instead',
       'Right: a plan with a decided ending is a pretence.',
       'Dizer isso e seguir o processo da empresa para encerrar o vínculo',
       'Isso: um plano com o fim já decidido é fingimento.'),
      (0, 'Write it, to have a record',
       'That is the pretence the lesson rules out.',
       'Escrever, para ter registro',
       'Esse é o fingimento que a aula descarta.'),
      (0, 'Make it short, two weeks',
       'Length does not make it honest.',
       'Fazer curto, duas semanas',
       'O tamanho não o torna honesto.'),
      (0, 'Write it without the consequences section, so the person stays motivated',
       'Consequences are said plainly.',
       'Escrever sem a seção de consequências, para a pessoa continuar motivada',
       'As consequências são ditas com clareza.')])

num('ex-g0cnm2zp', None, 'medium',
    ('Marcos’s plan required four of six tickets within one and a half times their estimate. Three were. What fraction of the required number did he reach, as a percentage?',
     'O plano do Marcos pedia quatro de seis tickets dentro de uma vez e meia a estimativa. Três ficaram. Que fração do número exigido ele atingiu, em porcentagem?'),
    ('3 over 4.', '3 sobre 4.'),
    75, 0, ('percent', 'por cento'), (['%'], ['%']))

quiz('ex-wndbp98a', None, 'hard',
     ('Renata, Sônia and Otávio decided against extending Marcos’s plan. On what did the decision rest?',
      'A Renata, a Sônia e o Otávio decidiram não prorrogar o plano do Marcos. Em que a decisão se apoiou?'),
     ('A record he had read.', 'Um registro que ele tinha lido.'),
     [(1, 'The plan’s own record, which Marcos had read and corrected every week',
       'Right: all the support was given and nothing suggested two more weeks would differ.',
       'No próprio registro do plano, que o Marcos tinha lido e corrigido toda semana',
       'Isso: todo o apoio foi dado e nada sugeria que mais duas semanas mudariam algo.'),
      (0, 'Otávio’s opinion',
       'The record decided, not an opinion.',
       'Na opinião do Otávio',
       'O registro decidiu, não uma opinião.'),
      (0, 'Complaints from the team',
       'Not part of the record.',
       'Em reclamações do time',
       'Não fazem parte do registro.'),
      (0, 'A budget cut',
       'Not the reason.',
       'Num corte de orçamento',
       'Não é o motivo.')])

# lesson 21 — letting someone go

quiz('ex-cc0y2kkm', None, 'easy',
     ('Where does the decision go in a dismissal conversation?',
      'Onde fica a decisão numa conversa de demissão?'),
     ('First minute.', 'Primeiro minuto.'),
     [(1, 'In the second sentence',
       'Right: it is not open for discussion, and the rest of the time is the person’s.',
       'Na segunda frase',
       'Isso: não está aberta a discussão, e o resto do tempo é da pessoa.'),
      (0, 'At the end, after the reasons',
       'Over-explaining first is one of the failures.',
       'No fim, depois dos motivos',
       'Explicar demais antes é uma das falhas.'),
      (0, 'In a letter sent before the meeting',
       'The letter is ready at the meeting, with the terms.',
       'Numa carta enviada antes da reunião',
       'A carta fica pronta na reunião, com os termos.'),
      (0, 'After ten minutes on how things have been going, so the person is prepared for it',
       'That is burying it.',
       'Depois de dez minutos sobre como as coisas vinham indo, para a pessoa estar preparada',
       'Isso é enterrá-la.')])

match('ex-6n01a3me', None, 'medium',
      ('Match each arrangement for a dismissal to the reason the lesson gives.',
       'Ligue cada arranjo de uma demissão ao motivo que a aula dá.'),
      ('Dignity.', 'Dignidade.'),
      [('early in the week, not a Friday afternoon', 'the person can reach the people team the next day',
        'no começo da semana, não numa sexta à tarde', 'a pessoa consegue falar com o time de pessoas no dia seguinte'),
       ('access changed after the conversation', 'nobody learns the news from a locked laptop',
        'acessos mudados depois da conversa', 'ninguém fica sabendo por um notebook bloqueado'),
       ('a written letter ready, with the terms', 'the person will remember little of what was said',
        'uma carta escrita pronta, com os termos', 'a pessoa vai lembrar pouco do que foi dito')],
      [('the manager has more time on Fridays', 'a gestora tem mais tempo às sextas')])

quiz('ex-ay6v2sd9', None, 'medium',
     ('What did Renata tell the team the next morning, and what did she leave out?',
      'O que a Renata disse ao time na manhã seguinte, e o que deixou de fora?'),
     ('The why.', 'O porquê.'),
     [(1, 'That Marcos had left and how his work would be covered; not why',
       'Right: the reasons are his, and the team had seen a fair process.',
       'Que o Marcos tinha saído e como o trabalho dele seria coberto; não por quê',
       'Isso: os motivos são dele, e o time tinha visto um processo justo.'),
      (0, 'Everything, so there would be no rumours',
       'The reasons stay private.',
       'Tudo, para não haver boatos',
       'Os motivos ficam em sigilo.'),
      (0, 'Nothing; the empty desk speaks for itself',
       'A team fills silence with the worst explanation.',
       'Nada; a mesa vazia fala por si',
       'Um time preenche o silêncio com a pior explicação.'),
      (0, 'That nobody else will be let go this year, whatever happens with the company',
       'A promise that is not hers to make.',
       'Que mais ninguém vai ser desligado este ano, aconteça o que acontecer com a empresa',
       'Uma promessa que não cabe a ela.')])

quiz('ex-s0m1d077', None, 'hard',
     ('Before a dismissal, the lesson asks whether this person is treated as others in the same situation would be. If that answer is weak, what happens?',
      'Antes de uma demissão, a aula pergunta se essa pessoa está sendo tratada como outras na mesma situação seriam. Se a resposta é fraca, o que acontece?'),
     ('Wait.', 'Esperar.'),
     [(1, 'The decision waits',
       'Right: so does it if the expectation or the support was weak.',
       'A decisão espera',
       'Isso: também espera se a expectativa ou o apoio foram fracos.'),
      (0, 'The people team decides',
       'The question is asked by the people team; a weak answer stops the decision.',
       'O time de pessoas decide',
       'A pergunta é feita pelo time de pessoas; uma resposta fraca para a decisão.'),
      (0, 'The manager writes a stronger case and proceeds the same week',
       'Writing does not fix the process.',
       'A gestora escreve um caso mais forte e segue na mesma semana',
       'Escrever não conserta o processo.'),
      (0, 'Nothing changes',
       'It does.',
       'Nada muda',
       'Muda.')])

# lesson 22 — conflict

match('ex-yam51ptc', None, 'easy',
      ('Match each kind of conflict to what it is about.',
       'Ligue cada tipo de conflito àquilo de que ele trata.'),
      ('Useful and harmful.', 'Útil e nocivo.'),
      [('task conflict', 'a disagreement about the work', 'conflito de tarefa', 'uma discordância sobre o trabalho'),
       ('relationship conflict', 'a disagreement about each other', 'conflito de relacionamento', 'uma discordância sobre o outro')],
      [('a disagreement about pay', 'uma discordância sobre salário')])

quiz('ex-3pcn9b75', None, 'medium',
     ('Paula and Diego each told Renata the other was the problem. What did she do first?',
      'A Paula e o Diego disseram cada um à Renata que o outro era o problema. O que ela fez primeiro?'),
     ('Separately.', 'Separadamente.'),
     [(1, 'Talked to each of them separately, without deciding who was right',
       'Right: then brought them together around a shared problem.',
       'Conversou com cada um separadamente, sem decidir quem tinha razão',
       'Isso: depois reuniu os dois em torno de um problema comum.'),
      (0, 'Decided on Diego’s account, as the more senior',
       'She decided from neither account.',
       'Decidiu pelo relato do Diego, por ser o mais sênior',
       'Ela não decidiu por nenhum dos relatos.'),
      (0, 'Put them in a room together straight away',
       'Separate conversations came first.',
       'Pôs os dois numa sala na hora',
       'As conversas separadas vieram primeiro.'),
      (0, 'Moved one of them to another team',
       'Not what happened.',
       'Mudou um deles de time',
       'Não foi o que aconteceu.')])

quiz('ex-297ggft3', None, 'medium',
     ('Agenda and Payments disagreed about a dependency. What made the escalation healthy?',
      'O Agenda e Pagamentos discordaram sobre uma dependência. O que tornou a escalada saudável?'),
     ('Together, on one page.', 'Juntas, numa página.'),
     [(1, 'Both managers escalated together, with the disagreement written fairly on one page',
       'Right: the directors decided on the facts, not on who spoke first.',
       'As duas gestoras escalaram juntas, com a discordância escrita de forma justa numa página',
       'Isso: os diretores decidiram pelos fatos, não por quem falou primeiro.'),
      (0, 'Renata escalated first',
       'Escalating alone is one of the failures.',
       'A Renata escalou primeiro',
       'Escalar sozinha é uma das falhas.'),
      (0, 'Agenda built a workaround',
       'Working around it is the other failure.',
       'O Agenda construiu um contorno',
       'Contornar é a outra falha.'),
      (0, 'Payments was told to drop the legal deadline',
       'The law was the one fixed thing.',
       'Mandaram Pagamentos abandonar o prazo legal',
       'A lei era a única coisa fixa.')])

cloze('ex-56bx46d1', None, 'medium',
      ('Disagree and ____: argue fully while the decision is open, then back it once it is made.',
       'Discordar e se ____: argumentar tudo enquanto a decisão está aberta, depois sustentá-la quando for tomada.'),
      ('Three words.', 'Três palavras.'),
      [(['commit'], ['comprometer'])])

# lesson 23 — why people leave

num('ex-ctff0bg8', None, 'easy',
    ('Agenda averaged 7 people over the year and 2 left. What was its attrition rate, to one decimal place?',
     'O Agenda teve média de 7 pessoas no ano e 2 saíram. Qual foi a taxa de rotatividade, com uma casa decimal?'),
    ('2 over 7.', '2 sobre 7.'),
    28.6, 0.05, ('percent', 'por cento'), (['%'], ['%']))

quiz('ex-adn9hhkr', None, 'medium',
     ('Why does the lesson say a small team’s attrition percentage needs care?',
      'Por que a aula diz que a porcentagem de rotatividade de um time pequeno precisa de cuidado?'),
     ('Single events.', 'Eventos únicos.'),
     [(1, 'One departure makes a large percentage',
       'Right: the question is always the regretted line.',
       'Uma saída produz uma porcentagem grande',
       'Isso: a pergunta é sempre a linha das saídas lamentadas.'),
      (0, 'People on small teams hide that they are planning to leave',
       'Not the claim.',
       'Pessoas em times pequenos escondem que planejam sair',
       'Não é a afirmação.'),
      (0, 'The formula only works above fifty people, because the average headcount is unstable below that',
       'Not the claim.',
       'A fórmula só funciona acima de cinquenta pessoas, porque a média de pessoas é instável abaixo disso',
       'Não é a afirmação.'),
      (0, 'HR counts it differently',
       'Not the claim.',
       'O RH conta de outro jeito',
       'Não é a afirmação.')])

quiz('ex-jn59c3hh', None, 'medium',
     ('What is a stay conversation?',
      'O que é uma conversa de permanência?'),
     ('Before anybody decides.', 'Antes de alguém decidir.'),
     [(1, 'Asking the questions of an exit interview to somebody who has not decided to leave',
       'Right: three of five named a moment within Renata’s control.',
       'Fazer as perguntas de uma entrevista de saída a alguém que não decidiu sair',
       'Isso: três de cinco nomearam um momento sob o controle da Renata.'),
      (0, 'A counter-offer',
       'A counter-offer comes after the decision.',
       'Uma contraproposta',
       'Uma contraproposta vem depois da decisão.'),
      (0, 'A retention bonus',
       'Not what it is.',
       'Um bônus de retenção',
       'Não é o que ela é.'),
      (0, 'The talk with somebody who has resigned, to persuade them to stay one more quarter',
       'That is after the decision.',
       'A conversa com quem pediu demissão, para convencer a ficar mais um trimestre',
       'Isso é depois da decisão.')])

quiz('ex-jw6qa872', None, 'hard',
     ('"If the reasons someone is leaving could have been fixed with a counter-offer..." How does the lesson finish the sentence?',
      '"Se os motivos de alguém sair pudessem ter sido resolvidos com uma contraproposta..." Como a aula termina a frase?'),
     ('Earlier.', 'Antes.'),
     [(1, '...in most cases they could have been fixed earlier',
       'Right: the reasons started months before the resignation.',
       '...na maioria dos casos poderiam ter sido resolvidos antes',
       'Isso: os motivos começaram meses antes do pedido de demissão.'),
      (0, '...the counter-offer is the right answer',
       'The lesson argues the opposite.',
       '...a contraproposta é a resposta certa',
       'A aula argumenta o contrário.'),
      (0, '...they were about money',
       'Not the ending.',
       '...eram sobre dinheiro',
       'Não é o final.'),
      (0, '...the manager should match the offer at once, before the person tells the rest of the team',
       'Not the ending.',
       '...a gestora deveria igualar a proposta na hora, antes de a pessoa contar ao resto do time',
       'Não é o final.')])

# lesson 24 — managing up

quiz('ex-anv7gtjn', None, 'easy',
     ('Which of these did Otávio say he needed from Renata?',
      'Qual destes o Otávio disse que precisava da Renata?'),
     ('Bad news first.', 'Más notícias primeiro.'),
     [(1, 'No surprises',
       'Right: with problems that come with options, and her honest read.',
       'Nenhuma surpresa',
       'Isso: com problemas que chegam com opções, e a leitura honesta dela.'),
      (0, 'A weekly ticket report',
       'He had eleven teams; status was not the ask.',
       'Um relatório semanal de tickets',
       'Ele tinha onze times; status não era o pedido.'),
      (0, 'Problems solved before they reach him, so that his week stays free for the other ten teams',
       'He wanted problems brought, with options.',
       'Problemas resolvidos antes de chegarem a ele, para a semana dele ficar livre para os outros dez times',
       'Ele queria os problemas trazidos, com opções.'),
      (0, 'Agreement in leadership meetings',
       'He asked for her honest read.',
       'Concordância nas reuniões da liderança',
       'Ele pediu a leitura honesta dela.')])

quiz('ex-1dga2fbp', None, 'medium',
     ('Who is a leader’s first team, in Lencioni’s argument?',
      'Quem é o primeiro time de uma liderança, no argumento de Lencioni?'),
     ('Beside, not below.', 'Ao lado, não abaixo.'),
     [(1, 'Their peers',
       'Right: the other managers reporting to the same person.',
       'Os pares',
       'Isso: as outras gestoras que se reportam à mesma pessoa.'),
      (0, 'Their reports',
       'The natural view he argues against.',
       'Quem se reporta a ela',
       'A visão natural contra a qual ele argumenta.'),
      (0, 'Their manager and the leadership group above them, who set the priorities for every team',
       'Not the claim.',
       'O gestor dela e o grupo de liderança acima, que define as prioridades de todos os times',
       'Não é a afirmação.'),
      (0, 'Their product partner',
       'Not the claim.',
       'A parceira de produto',
       'Não é a afirmação.')])

quiz('ex-1t6121ec', None, 'medium',
     ('Thiago asks whether his job is safe after rumours of cost-cutting. Which reply follows the lesson?',
      'O Thiago pergunta se o emprego dele está seguro depois de boatos de corte de custos. Qual resposta segue a aula?'),
     ('What she knows, and her own action.', 'O que ela sabe, e a ação dela.'),
     [(1, '"I don’t know of any plans affecting this team, and I’ll tell you as soon as I’m allowed to if I learn something."',
       'Right: it promises her own action, not somebody else’s decision.',
       '"Não sei de nenhum plano que afete este time, e te conto assim que puder se souber de algo."',
       'Isso: promete uma ação dela, não a decisão de outra pessoa.'),
      (0, '"Nobody on this team will be laid off."',
       'Not hers to promise.',
       '"Ninguém deste time vai ser demitido."',
       'Não cabe a ela prometer.'),
      (0, '"There’s nothing going on."',
       'If wrong, every later reassurance is discounted.',
       '"Não está acontecendo nada."',
       'Se estiver errado, toda tranquilização futura é descontada.'),
      (0, '"Don’t listen to rumours."',
       'Dismisses the question.',
       '"Não ouça boatos."',
       'Descarta a pergunta.')])

quiz('ex-cbvznh74', None, 'hard',
     ('Renata argued against a decision from above and lost. What does she say if the team asks?',
      'A Renata argumentou contra uma decisão de cima e perdeu. O que ela diz se o time perguntar?'),
     ('Honest, and still committed.', 'Honesta, e ainda comprometida.'),
     [(1, '"I argued for something different, it went the other way, and here’s what we’re going to do."',
       'Right: honest about the disagreement, without turning it into a grievance.',
       '"Eu defendi outra coisa, foi para o outro lado, e é isto que vamos fazer."',
       'Isso: honesta sobre a discordância, sem transformá-la em queixa.'),
      (0, '"It was my idea."',
       'Dishonest about the disagreement.',
       '"Foi ideia minha."',
       'Desonesta sobre a discordância.'),
      (0, '"Otávio decided it; I think it’s wrong."',
       'A grievance the team can hold.',
       '"O Otávio decidiu; acho que está errado."',
       'Uma queixa que o time pode guardar.'),
      (0, '"I can’t discuss decisions from above."',
       'She can acknowledge it if asked.',
       '"Não posso discutir decisões de cima."',
       'Ela pode reconhecer se perguntarem.')])

# three more, across the course

quiz('ex-aw8zrnxj', None, 'medium',
     ('David Marquet asked his officers to come to him with a phrase instead of waiting for orders. Which one?',
      'David Marquet pediu aos oficiais que viessem com uma frase em vez de esperar ordens. Qual?'),
     ('What they planned.', 'O que planejavam.'),
     [(1, '"I intend to…"',
       'Right: the officer did the thinking and the commander checked it.',
       '"Eu pretendo…"',
       'Isso: o oficial pensava e o comandante conferia.'),
      (0, '"Permission to…?"',
       'That is the habit he removed.',
       '"Permissão para…?"',
       'Esse é o hábito que ele eliminou.'),
      (0, '"What would you like me to do about…?"',
       'That returns the thinking to the commander.',
       '"O que o senhor quer que eu faça sobre…?"',
       'Isso devolve o pensar ao comandante.'),
      (0, '"I have finished the task you gave me this morning, sir."',
       'A report, not an intention.',
       '"Terminei a tarefa que o senhor me deu hoje de manhã."',
       'Um relato, não uma intenção.')])

quiz('ex-zkg76rf5', None, 'medium',
     ('In a dismissal, what does the people team explain that the manager does not?',
      'Numa demissão, o que o time de pessoas explica e a gestora não?'),
     ('Money, dates and rights.', 'Dinheiro, datas e direitos.'),
     [(1, 'The terms',
       'Right: the manager says what has been decided; the people team explains what it means in money, dates and rights.',
       'Os termos',
       'Isso: a gestora diz o que foi decidido; o time de pessoas explica o que isso significa em dinheiro, datas e direitos.'),
      (0, 'The decision itself',
       'That is the manager’s to say.',
       'A própria decisão',
       'Isso cabe à gestora dizer.'),
      (0, 'Why the manager reached the decision, in full, with the history of each conversation',
       'Over-explaining is a failure, whoever does it.',
       'Por que a gestora chegou à decisão, por inteiro, com o histórico de cada conversa',
       'Explicar demais é uma falha, seja quem for.'),
      (0, 'What the team will be told',
       'That is the manager’s plan.',
       'O que vai ser dito ao time',
       'Esse é o plano da gestora.')])

quiz('ex-st4pe0jv', None, 'medium',
     ('Where does the lesson tell you to keep your notebook?',
      'Onde a aula diz para guardar o seu caderno?'),
     ('Who can open it.', 'Quem pode abri-lo.'),
     [(1, 'Somewhere only you can open',
       'Right: and write each note as if the person might one day read it.',
       'Num lugar que só você abre',
       'Isso: e escreva cada nota como se a pessoa pudesse lê-la um dia.'),
      (0, 'In the team’s shared drive',
       'It holds notes about people.',
       'No drive compartilhado do time',
       'Ele guarda notas sobre pessoas.'),
      (0, 'In the company wiki, so that the next manager can pick it up if you leave the role',
       'Not what the lesson says.',
       'Na wiki da empresa, para a próxima gestora pegar se você deixar o cargo',
       'Não é o que a aula diz.'),
      (0, 'With HR',
       'Not what the lesson says.',
       'Com o RH',
       'Não é o que a aula diz.')])
