"""Lesson 1: what changes when your output becomes other people's output."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-13wsva6h')

quiz('ex-aejaa81b', 'the-new-unit', 'easy',
     ('By Grove’s sum, what is a manager’s output?',
      'Pela soma de Grove, qual é a entrega de quem gerencia?'),
     ('Two terms, and neither is the manager’s own work.',
      'Dois termos, e nenhum é o trabalho da própria pessoa.'),
     [(1, 'Their team’s output plus that of neighbouring teams they influence',
       'Right: the sum has two terms, the organisation and the neighbours under its influence, and nothing the manager does alone.',
       'A entrega do time mais a dos times vizinhos que influencia',
       'Isso: a soma tem dois termos, a organização e as vizinhas sob a sua influência, e nada do que a pessoa faz sozinha.'),
      (0, 'The work they still do with their own hands',
       'That is the old ruler. Grove’s sum leaves the manager’s own work out unless it changes what the team produces.',
       'O trabalho que ainda faz com as próprias mãos',
       'Essa é a régua antiga. A soma de Grove deixa de fora o trabalho da própria pessoa, a menos que ele mude o que o time produz.'),
      (0, 'The number of decisions they make in a week, weighted by what each one costs',
       'A decision counts only through what it changes in the team’s output; a count of decisions measures activity.',
       'O número de decisões que toma por semana, pesadas pelo custo de cada uma',
       'Uma decisão só conta pelo que muda na entrega do time; contar decisões mede atividade.'),
      (0, 'Their team’s output alone',
       'Half of it. The second term, the neighbouring teams under the manager’s influence, is as much part of the job.',
       'Só a entrega do time',
       'Metade. O segundo termo, os times vizinhos sob a influência da pessoa, também é parte do trabalho.')])

quiz('ex-67mz8pnp', 'the-new-unit', 'medium',
     ('Renata persuades the Payments team to expose an endpoint a quarter early, and Agenda ships a feature sooner as a result. Where does that appear in Grove’s sum?',
      'A Renata convence o time de Pagamentos a expor um endpoint um trimestre antes, e o Agenda entrega uma funcionalidade mais cedo por causa disso. Onde isso aparece na soma de Grove?'),
     ('Who did the extra work, and whose output went up?',
      'Quem fez o trabalho a mais, e a entrega de quem subiu?'),
     [(1, 'In both terms: her influence on a neighbour raised her own team’s output',
       'Right. Payments is a neighbour under her influence, and the result is that Agenda’s output rose without anybody on it working harder.',
       'Nos dois termos: a influência sobre um vizinho aumentou a entrega do próprio time',
       'Isso. Pagamentos é um vizinho sob a influência dela, e o resultado é que a entrega do Agenda subiu sem ninguém trabalhar mais.'),
      (0, 'Nowhere, because she wrote no code',
       'That measures her by commits, the ruler the lesson says belongs to the old job.',
       'Em lugar nenhum, porque ela não escreveu código',
       'Isso a mede por commits, a régua que a aula diz pertencer ao trabalho antigo.'),
      (0, 'Only in the Payments team’s output, since they built the endpoint',
       'They built it, but the point of persuading them was what it let Agenda ship sooner.',
       'Só na entrega de Pagamentos, que construiu o endpoint',
       'Eles construíram, mas o objetivo de convencê-los era o que isso permitiu ao Agenda entregar antes.'),
      (0, 'As her personal output for the quarter',
       'The sum has no personal term at all; the conversation counts through what the team then delivered.',
       'Como entrega pessoal dela no trimestre',
       'A soma não tem termo pessoal; a conversa conta pelo que o time entregou depois.')])

quiz('ex-sbe1e1ax', 'the-new-unit', 'medium',
     ('In her second week Renata takes a small ticket because nobody else is free. By Wednesday two people are waiting on her decisions and the ticket is still open. What does the lesson draw from it?',
      'Na segunda semana a Renata pega um ticket pequeno porque ninguém está livre. Na quarta, duas pessoas esperam decisões dela e o ticket continua aberto. O que a aula tira disso?'),
     ('Is the problem the code, or the reason she picked it up?',
      'O problema é o código, ou o motivo de ela ter pegado o ticket?'),
     [(1, 'Code is now a choice, and comfort is a poor reason for it',
       'Right. The lesson says code is not wrong for a manager; the reason matters, and comfort is a reason that costs the team.',
       'Código agora é escolha, e conforto é um motivo ruim para ele',
       'Isso. A aula diz que código não é errado para quem gerencia; o motivo importa, e conforto é um motivo que custa ao time.'),
      (0, 'A manager should never write code',
       'Lesson 2 describes a shape of the role where code is part of the job, so the lesson does not say this.',
       'Uma gestora nunca deveria escrever código',
       'A aula 2 descreve um formato do papel em que código faz parte do trabalho, então a aula não diz isso.'),
      (0, 'The ticket was too large for somebody with meetings',
       'It was small; size was not what went wrong, the decisions left waiting were.',
       'O ticket era grande demais para quem tem reuniões',
       'Ele era pequeno; o tamanho não foi o problema, as decisões que ficaram esperando foram.'),
      (0, 'She should have asked Otávio before picking up a ticket in her first month',
       'Nothing in the lesson makes this a question of permission; it is about where her hours multiply.',
       'Ela deveria ter pedido ao Otávio antes de pegar um ticket no primeiro mês',
       'Nada na aula torna isso uma questão de permissão; é sobre onde as horas dela multiplicam.')])

match('ex-dknfw6rm', 'the-new-unit', 'easy',
      ('Match each thing that moves with the lessons that deal with it.',
       'Ligue cada coisa que se move às aulas que tratam dela.'),
      ('Leverage, information, effect on people.', 'Alavanca, informação, efeito sobre as pessoas.'),
      [('your leverage', 'delegating outcomes and deciding how much freedom goes with them',
        'a sua alavanca', 'delegar resultados e decidir quanta liberdade vai junto'),
       ('your information', 'the one-to-one, the meeting that fixes what people stop telling you',
        'a sua informação', 'a 1:1, a reunião que corrige o que as pessoas param de contar'),
       ('your effect on people', 'feedback, promotion and the hard conversations',
        'o seu efeito sobre as pessoas', 'feedback, promoção e as conversas difíceis')],
      [('the deploy pipeline and the on-call rota', 'o pipeline de deploy e a escala de plantão')])

quiz('ex-cf6wawn1', 'where-the-time-goes', 'easy',
     ('Why does a team meeting at 11:00 cost more than it looks?',
      'Por que uma reunião do time às 11:00 custa mais do que parece?'),
     ('Think of the people in it, not the hour.', 'Pense nas pessoas, não na hora.'),
     [(1, 'It cuts every attendee’s morning in half',
       'Right: seven engineers lose seven unbroken mornings, which is why the team moved its regular meetings to the edges of the day.',
       'Ela corta ao meio a manhã de cada participante',
       'Isso: sete engenheiros perdem sete manhãs inteiras, e foi por isso que o time levou as reuniões fixas para as pontas do dia.'),
      (0, 'Meetings before lunch run longer than meetings after it',
       'The lesson says nothing about length; the cost is where the meeting falls in a maker’s day.',
       'Reuniões antes do almoço duram mais do que as de depois',
       'A aula não fala de duração; o custo é onde a reunião cai no dia de quem constrói.'),
      (0, 'Managers are least productive at that hour',
       'The cost falls on the engineers, whose long blocks it breaks, not on the manager.',
       'Gestores rendem menos nesse horário',
       'O custo cai sobre os engenheiros, cujos blocos longos ela quebra, não sobre a gestora.'),
      (0, 'It leaves twenty-minute gaps in the manager’s calendar that are too short to use for anything',
       'Those gaps are real, but they are a cost of the manager’s own fragmented day, not of this meeting.',
       'Ela deixa buracos de vinte minutos na agenda da gestora, curtos demais para servir para alguma coisa',
       'Esses buracos existem, mas são custo do dia fragmentado da gestora, não desta reunião.')])

quiz('ex-ve83s465', 'where-the-time-goes', 'medium',
     ('Which of these answers its question soonest?',
      'Qual destes responde à sua pergunta mais cedo?'),
     ('Place each on the figure’s axis.', 'Ponha cada um no eixo da figura.'),
     [(1, 'A code review',
       'Right: a review answers the same day, hours rather than weeks.',
       'Uma revisão de código',
       'Isso: uma revisão responde no mesmo dia, em horas e não em semanas.'),
      (0, 'Feedback given in a one-to-one',
       'Whether feedback worked shows over the following weeks, when the behaviour changes or not.',
       'Um feedback dado numa 1:1',
       'Se o feedback funcionou aparece nas semanas seguintes, quando o comportamento muda ou não.'),
      (0, 'A promotion case written today',
       'It is decided at the next review cycle, about six months away at Caju.',
       'Um caso de promoção escrito hoje',
       'Ele é decidido no próximo ciclo de avaliação, a uns seis meses na Caju.'),
      (0, 'A hire made this month',
       'A hire shows whether it was right somewhere between three months and a year.',
       'Uma contratação feita este mês',
       'Uma contratação mostra se deu certo entre três meses e um ano.')])

quiz('ex-894f2zsv', 'where-the-time-goes', 'medium',
     ('Agenda ships a strong first quarter under Renata. Why should she not conclude that her changes worked?',
      'O Agenda entrega um bom primeiro trimestre com a Renata. Por que ela não deveria concluir que as mudanças dela funcionaram?'),
     ('What else could explain a good quarter?', 'O que mais explicaria um bom trimestre?'),
     [(1, 'The quarter may run on decisions made before she arrived',
       'Right: with loops this long, luck and the previous manager’s work cannot yet be told apart from her own.',
       'O trimestre pode estar rodando em decisões anteriores a ela',
       'Isso: com ciclos tão longos, sorte e o trabalho da gestão anterior ainda não se distinguem do dela.'),
      (0, 'One quarter is always too short to measure any team',
       'Teams can be measured over a quarter; what one quarter cannot show is the effect of a new manager’s choices.',
       'Um trimestre é sempre curto demais para medir qualquer time',
       'Times podem ser medidos num trimestre; o que um trimestre não mostra é o efeito das escolhas de uma gestora nova.'),
      (0, 'Good results usually mean the team is being pushed too hard',
       'Nothing in the lesson links good results to pressure; the point is about attribution.',
       'Bons resultados geralmente indicam que o time está sendo pressionado demais',
       'Nada na aula liga bons resultados a pressão; o ponto é sobre a quem atribuir.'),
      (0, 'Results only count once the next review cycle has looked at them and confirmed them',
       'A review cycle is one of the long loops, but nothing makes results invisible until it runs.',
       'Resultados só contam quando o próximo ciclo de avaliação os examina e confirma',
       'O ciclo de avaliação é um dos ciclos longos, mas nada torna os resultados invisíveis até ele acontecer.')])

cloze('ex-5x6b54ts', 'where-the-time-goes', 'easy',
      ('Paul Graham’s essay contrasts the maker’s schedule with the ___ schedule.',
       'O ensaio de Paul Graham contrapõe a agenda de quem constrói à agenda de quem ___.'),
      ('The other person in the essay’s title.', 'A outra pessoa do título do ensaio.'),
      [(['manager’s', "manager's", 'manager'], ['gerencia'])])

quiz('ex-xtefdmv1', 'first-ninety-days', 'easy',
     ('Which listening-tour question does the lesson say people skip, and matters most?',
      'Qual pergunta da rodada de escuta a aula diz que as pessoas pulam, e é a que mais importa?'),
     ('A new manager arrives looking for problems.', 'Uma gestora nova chega procurando problemas.'),
     [(1, 'What is going well that I should be careful not to break?',
       'Right: it is what surfaced Diego’s fast reviews, which Renata had been about to cut back.',
       'O que está indo bem e eu preciso tomar cuidado para não quebrar?',
       'Isso: foi ela que revelou as revisões rápidas do Diego, que a Renata estava prestes a reduzir.'),
      (0, 'What is getting in your way?',
       'People answer this one readily; it finds problems, which a new manager is already looking for.',
       'O que está atrapalhando você?',
       'As pessoas respondem esta com facilidade; ela acha problemas, que a gestora nova já procura.'),
      (0, 'If you were in my seat, what would you change first?',
       'Useful, but it points at change, and the risk the lesson names is breaking what works.',
       'Se você estivesse na minha cadeira, o que mudaria primeiro?',
       'Útil, mas aponta para mudança, e o risco que a aula nomeia é quebrar o que funciona.'),
      (0, 'What do you need from me?',
       'A good question, though not the one the lesson singles out as skipped.',
       'O que você precisa de mim?',
       'Boa pergunta, mas não a que a aula destaca como a pulada.')])

num('ex-0jnj81we', 'first-ninety-days', 'easy',
    ('In Renata’s table, how many more people raised the dependency on Payments than raised the slow pipeline?',
     'Na tabela da Renata, quantas pessoas a mais citaram a dependência de Pagamentos do que o pipeline lento?'),
    ('Six against two.', 'Seis contra duas.'),
    4, 0, ('people', 'pessoas'), (['person'], ['pessoa']))

quiz('ex-fpcrnad2', 'first-ninety-days', 'medium',
     ('Why did Renata ask the two people who built the old on-call rota to draft the new one?',
      'Por que a Renata pediu às duas pessoas que montaram a escala de plantão antiga que rascunhassem a nova?'),
     ('An early change can be read as something.', 'Uma mudança cedo pode ser lida como alguma coisa.'),
     [(1, 'So the change became their project rather than a verdict on their work',
       'Right: the lesson warns that early changes read as verdicts, and handing the redesign to its authors avoids that.',
       'Para a mudança virar um projeto delas, e não um veredito sobre o trabalho delas',
       'Isso: a aula avisa que mudanças cedo são lidas como veredito, e entregar o redesenho a quem fez o original evita isso.'),
      (0, 'Because a manager should not spend time on rotas',
       'The lesson does not rank rotas below the manager; it is about how the change is received.',
       'Porque gestora não deveria gastar tempo com escalas',
       'A aula não coloca escalas abaixo da gestora; o ponto é como a mudança é recebida.'),
      (0, 'Because they were the two people who had covered the most holidays under the old rota',
       'Five people raised the problem; the two were chosen because they had designed the old rota.',
       'Porque eram as duas pessoas que mais tinham coberto feriados na escala antiga',
       'Cinco pessoas citaram o problema; as duas foram escolhidas por terem desenhado a escala antiga.'),
      (0, 'To delay the change until after her first ninety days',
       'She made the change inside the window, in the second month, on purpose.',
       'Para adiar a mudança até depois dos noventa dias',
       'Ela fez a mudança dentro da janela, no segundo mês, de propósito.')])

quiz('ex-3gbpa15f', 'your-notebook', 'easy',
     ('What does the course ask you to install?',
      'O que o curso pede que você instale?'),
     ('Look at what the practice is made of.', 'Veja do que a prática é feita.'),
     [(1, 'Nothing beyond somewhere to write and count',
       'Right. LibreOffice is recommended, but a plain text file and paper are enough to do every task.',
       'Nada além de um lugar para escrever e contar',
       'Isso. O LibreOffice é recomendado, mas um arquivo de texto e papel bastam para todas as tarefas.'),
      (0, 'An HR system to practise performance reviews in',
       'No lesson uses one; every template is written out in the lesson that needs it.',
       'Um sistema de RH para treinar avaliações de desempenho',
       'Nenhuma aula usa um; todo modelo está escrito na aula que precisa dele.'),
      (0, 'A shared drive where the notebook lives',
       'The opposite: the notebook holds personal data and belongs where only you can open it.',
       'Um drive compartilhado onde o caderno fica',
       'O contrário: o caderno guarda dados pessoais e fica onde só você abre.'),
      (0, 'A video-call tool, for the practice one-to-ones',
       'The practice is scenario questions and written tasks; there are no calls.',
       'Uma ferramenta de videochamada, para as 1:1 de treino',
       'A prática são perguntas de cenário e tarefas escritas; não há chamadas.')])

quiz('ex-0yt3vepx', 'your-notebook', 'medium',
     ('Thiago tells Renata he needs Thursdays flexible for two months because of a medical treatment. What goes in her notebook?',
      'O Thiago conta à Renata que precisa de quintas flexíveis por dois meses por causa de um tratamento médico. O que vai para o caderno dela?'),
     ('Write what you need to act on.', 'Escreva o que você precisa para agir.'),
     [(1, 'The request and its dates, without the medical reason',
       'Right: health information is sensitive personal data, and the action needs only the request.',
       'O pedido e as datas, sem o motivo médico',
       'Isso: informação de saúde é dado pessoal sensível, e a ação só precisa do pedido.'),
      (0, 'The treatment, so she can follow up on how he is',
       'Caring about him does not need a medical record in her notes, and the law treats it as sensitive.',
       'O tratamento, para ela poder acompanhar como ele está',
       'Cuidar dele não exige um registro médico nas notas dela, e a lei trata isso como sensível.'),
      (0, 'Nothing, since personal matters never belong in work notes',
       'The request itself is something she has to act on and remember, so it belongs there.',
       'Nada, porque assuntos pessoais nunca entram em notas de trabalho',
       'O pedido em si é algo em que ela precisa agir e lembrar, então ele entra.'),
      (0, 'A note in the team wiki, so others can cover Thursdays',
       'The team may need to know there is cover to arrange; it does not need his reasons, and the wiki is shared.',
       'Uma nota na wiki do time, para outros cobrirem as quintas',
       'O time pode precisar saber que há cobertura a combinar; não precisa dos motivos, e a wiki é compartilhada.')])

order('ex-4787cx5n', 'your-notebook', 'easy',
      ('Put the four parts of the notebook in the order the lesson lists them.',
       'Ponha as quatro partes do caderno na ordem em que a aula as lista.'),
      ('Who, then what was decided, then what was promised, then the writing.',
       'Quem, depois o que foi decidido, depois o que foi prometido, depois a escrita.'),
      [('People', 'Pessoas'), ('Decisions', 'Decisões'), ('Promises', 'Promessas'),
       ('Drafts', 'Rascunhos')])

quiz('ex-dwj7vkcc', 'drill', 'hard',
     ('A newly promoted manager says: “I spent the whole week in meetings and got nothing done, so next week I’m blocking two days to clear my tickets.” What would you check first?',
      'Um gestor recém-promovido diz: “Passei a semana inteira em reuniões e não fiz nada, então semana que vem vou bloquear dois dias para zerar meus tickets.” O que você verificaria primeiro?'),
     ('What is “got nothing done” measured against?', '“Não fiz nada” está medido contra o quê?'),
     [(1, 'Which of those meetings changed what the team produces',
       'Right: by Grove’s sum the week may have been productive, and two days on tickets may cost the team more than they return.',
       'Quais daquelas reuniões mudaram o que o time produz',
       'Isso: pela soma de Grove a semana pode ter sido produtiva, e dois dias em tickets podem custar ao time mais do que devolvem.'),
      (0, 'Whether two days is enough to clear the tickets',
       'That accepts his ruler, commits and tickets, which is the one the lesson says the job no longer uses.',
       'Se dois dias bastam para zerar os tickets',
       'Isso aceita a régua dele, commits e tickets, que é a que a aula diz que o cargo não usa mais.'),
      (0, 'Whether he could decline all his meetings next week instead of just most of them',
       'Some of those meetings are the job; cutting all of them assumes the meetings were the waste.',
       'Se ele poderia recusar todas as reuniões da semana que vem, e não só a maioria',
       'Algumas daquelas reuniões são o trabalho; cortar todas pressupõe que as reuniões eram o desperdício.'),
      (0, 'Whether his manager approves the blocked days',
       'Approval does not answer whether the days are well spent, which is the question.',
       'Se o gestor dele aprova os dias bloqueados',
       'A aprovação não responde se os dias são bem gastos, que é a pergunta.')])

mc('ex-wnx7ftbx', 'drill', 'hard',
   ('Which of these are reasons the lesson gives for not changing things in a new manager’s first weeks? Choose all that apply.',
    'Quais destes são motivos que a aula dá para não mudar coisas nas primeiras semanas de uma gestora nova? Marque todos que se aplicam.'),
   ('Three reasons, each concrete.', 'Três motivos, cada um concreto.'),
   [(1, 'She knows the problems from one seat', 'Yes: the platform migration and Helena’s use of planning were invisible from where she sat.',
     'Ela conhece os problemas de uma cadeira só', 'Sim: a migração da plataforma e o uso que a Helena fazia do planejamento eram invisíveis de onde ela estava.'),
    (1, 'Early changes are read as verdicts', 'Yes: changing the rota in week one would have told its authors their work was wrong.',
     'Mudanças cedo são lidas como veredito', 'Sim: mudar a escala na primeira semana diria a quem a fez que o trabalho estava errado.'),
    (1, 'She has no record of what people told her yet', 'Yes: after a month she can say what she heard; in week one only what she thinks.',
     'Ela ainda não tem registro do que as pessoas disseram', 'Sim: depois de um mês ela consegue dizer o que ouviu; na primeira semana, só o que acha.'),
    (0, 'A new manager has no authority to change anything for ninety days', 'She had the authority from the first week; the lesson is about using it well.',
     'Uma gestora nova não tem autoridade para mudar nada por noventa dias', 'Ela tinha autoridade desde a primeira semana; a aula é sobre usá-la bem.'),
    (0, 'Changes made early are harder to undo', 'The lesson does not argue reversibility here; its reasons are about knowledge and how a change is read.',
     'Mudanças feitas cedo são mais difíceis de desfazer', 'A aula não argumenta reversibilidade aqui; os motivos são sobre conhecimento e sobre como a mudança é lida.')])
