"""Lesson 2: the two shapes of the role."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-t25vkndf')

quiz('ex-y3y3xycf', 'two-shapes', 'easy',
     ('Which of these does the lesson give to the tech lead rather than the engineering manager?',
      'Qual destes a aula dá à liderança técnica, e não à gestão de engenharia?'),
     ('One answers for how the software is built.', 'Uma responde por como o software é construído.'),
     [(1, 'The quality bar in review',
       'Right: the review bar is part of how the software is built, the tech lead’s half.',
       'O padrão de qualidade na revisão',
       'Isso: o padrão da revisão é parte de como o software é construído, a metade da liderança técnica.'),
      (0, 'The commitments the team makes to the rest of the company',
       'Commitments to the company belong to the manager, who answers for what the team delivers.',
       'Os compromissos que o time assume com o resto da empresa',
       'Compromissos com a empresa são da gestão, que responde pelo que o time entrega.'),
      (0, 'Whether people are still on the team a year from now',
       'Retention is in the manager’s half of the figure.',
       'Se as pessoas ainda estão no time daqui a um ano',
       'Retenção está na metade da gestão na figura.'),
      (0, 'Growth and feedback',
       'Growth and feedback are the manager’s; the tech lead gives technical feedback in review, which is a different thing.',
       'Crescimento e feedback',
       'Crescimento e feedback são da gestão; a liderança técnica dá feedback técnico na revisão, que é outra coisa.')])

quiz('ex-pfm3fy81', 'two-shapes', 'medium',
     ('Why does the lesson say a tech lead’s credibility depends on still writing code?',
      'Por que a aula diz que a credibilidade da liderança técnica depende de ainda escrever código?'),
     ('What is a technical decision from somebody outside the codebase?',
      'O que é uma decisão técnica de alguém fora do código?'),
     [(1, 'Without it, a design call is a guess with authority',
       'Right: the lesson’s phrase is “a guess with authority”, and staying in the code is what keeps the decisions informed.',
       'Sem isso, uma decisão de design é um palpite com autoridade',
       'Isso: a expressão da aula é “um palpite com autoridade”, e continuar no código é o que mantém as decisões informadas.'),
      (0, 'Because the team measures leads by commits',
       'The lesson rejects commits as a measure of leadership in lesson 1; the point is informed judgement.',
       'Porque o time mede lideranças por commits',
       'A aula rejeita commits como medida de liderança desde a aula 1; o ponto é julgamento informado.'),
      (0, 'Because a tech lead has no other way to contribute to the team',
       'Reviews, design and unblocking are contributions too, and they take a third of Diego’s week.',
       'Porque a liderança técnica não tem outra forma de contribuir com o time',
       'Revisões, design e desbloqueio também são contribuições, e ocupam um terço da semana do Diego.'),
      (0, 'Because company policy requires it of the role',
       'No policy is involved; the argument is about where technical judgement comes from.',
       'Porque a política da empresa exige isso do papel',
       'Não há política envolvida; o argumento é sobre de onde vem o julgamento técnico.')])

quiz('ex-j5ejvrmw', 'two-shapes', 'medium',
     ('Will Larson lists the tech lead as one of four shapes of which job?',
      'Will Larson lista a liderança técnica como um de quatro formatos de qual trabalho?'),
     ('Look at the title of his book.', 'Olhe o título do livro dele.'),
     [(1, 'A senior engineer’s',
       'Right: tech lead sits beside architect, solver and right hand as a senior engineering role.',
       'O de uma pessoa engenheira sênior',
       'Isso: a liderança técnica fica ao lado de arquiteto, solucionador e braço direito como papel sênior de engenharia.'),
      (0, 'A first-time manager’s, before they take on people',
       'The lesson draws the opposite conclusion: leading technically is a senior engineering job, not a junior management one.',
       'O de uma gestora de primeira viagem, antes de assumir pessoas',
       'A aula tira a conclusão oposta: liderar tecnicamente é trabalho sênior de engenharia, não trabalho júnior de gestão.'),
      (0, 'A product manager’s',
       'Product management is a different job and not one of Larson’s four.',
       'O de uma gerente de produto',
       'Gestão de produto é outro trabalho e não é um dos quatro de Larson.'),
      (0, 'A director of engineering’s, who leads several managers at once',
       'Larson’s four shapes describe senior engineers who do not manage people.',
       'O de uma diretora de engenharia, que lidera várias gestoras ao mesmo tempo',
       'Os quatro formatos de Larson descrevem pessoas engenheiras sêniores que não gerenciam pessoas.')])

match('ex-mb288tp9', 'two-shapes', 'medium',
      ('Match each item from the middle of the figure with the reason both leads touch it.',
       'Ligue cada item do meio da figura ao motivo de as duas lideranças mexerem nele.'),
      ('Each side knows something the other does not.', 'Cada lado sabe algo que o outro não sabe.'),
      [('estimates and plans', 'one knows what the work involves, the other what the company needs and when',
        'estimativas e planos', 'uma sabe o que o trabalho envolve, a outra do que a empresa precisa e quando'),
       ('interviews', 'one judges technical skill, the other owns the hiring decision',
        'entrevistas', 'uma julga habilidade técnica, a outra é dona da decisão de contratar'),
       ('incidents', 'one leads the response during it, the other schedules the follow-up after it',
        'incidentes', 'uma lidera a resposta durante, a outra agenda o acompanhamento depois'),
       ('who works on what', 'one knows who could do it, the other who needs it to grow',
        'quem trabalha em quê', 'uma sabe quem conseguiria, a outra quem precisa para crescer')],
      [('one writes the code, the other writes the tests', 'uma escreve o código, a outra escreve os testes')])

quiz('ex-7smr781c', 'two-shapes', 'hard',
     ('Diego said he wanted the manager’s job. What did the listening-tour conversation reveal?',
      'O Diego disse que queria o cargo de gestão. O que a conversa da rodada de escuta revelou?'),
     ('Which half of the figure did he want?', 'Qual metade da figura ele queria?'),
     [(1, 'He wanted the technical half, not the people half',
       'Right: he wanted the left half and assumed it came with the right, and nobody had offered it alone.',
       'Ele queria a metade técnica, não a das pessoas',
       'Isso: ele queria a metade esquerda e achava que ela vinha com a direita, e ninguém a tinha oferecido sozinha.'),
      (0, 'He wanted the title and the pay that come with management',
       'Nothing in the conversation points to title or pay; it was about decisions over the software.',
       'Ele queria o título e o salário que vêm com a gestão',
       'Nada na conversa aponta para título ou salário; era sobre decisões sobre o software.'),
      (0, 'He wanted to manage people and lacked experience',
       'When they listed what managing contained, he did not want most of it.',
       'Ele queria gerenciar pessoas e faltava experiência',
       'Quando listaram o que a gestão continha, ele não queria quase nada.'),
      (0, 'He wanted to leave the team and was looking for a reason',
       'He stayed and took the tech lead role, which was what he had been after.',
       'Ele queria sair do time e procurava um motivo',
       'Ele ficou e assumiu a liderança técnica, que era o que buscava.')])

quiz('ex-6badf912', 'the-pendulum', 'easy',
     ('What is the mistake the lesson calls the worst in this area?',
      'Qual é o erro que a aula chama de pior nesse assunto?'),
     ('Why do people take the management job?', 'Por que as pessoas aceitam a gestão?'),
     [(1, 'Taking management as the only way up, then being bad at it',
       'Right: the promotion framing pushes people into a job they never wanted.',
       'Aceitar a gestão como único caminho para cima, e depois ser ruim nela',
       'Isso: o enquadramento de promoção empurra pessoas para um trabalho que nunca quiseram.'),
      (0, 'Going back to engineering after a few years of managing, which looks like failure to the team',
       'The lesson, following Charity Majors, calls that a normal career, not a failure.',
       'Voltar para a engenharia depois de alguns anos gerenciando, o que parece fracasso para o time',
       'A aula, seguindo Charity Majors, chama isso de carreira normal, não de fracasso.'),
      (0, 'A manager reviewing pull requests',
       'Reviews are in the table of code that fits a manager’s week.',
       'Uma gestora revisar pull requests',
       'Revisões estão na tabela de código que cabe na semana de uma gestora.'),
      (0, 'A tech lead deciding by persuasion rather than authority',
       'The lesson calls that a feature as much as a cost.',
       'Uma liderança técnica decidir por persuasão em vez de autoridade',
       'A aula chama isso de vantagem tanto quanto de custo.')])

quiz('ex-jd79d86v', 'the-pendulum', 'medium',
     ('A year into managing full-time, what does the lesson say usually still works, and what does not?',
      'Depois de um ano gerenciando em tempo integral, o que a aula diz que costuma continuar funcionando, e o que não?'),
     ('Two kinds of technical knowledge decay at different speeds.', 'Dois tipos de conhecimento técnico se desgastam em velocidades diferentes.'),
     [(1, 'Judgement, but not currency',
       'Right: knowing how a system should be designed lasts; knowing the framework version and the deploy tooling fades.',
       'Julgamento, não atualização',
       'Isso: saber como um sistema deveria ser desenhado dura; saber a versão do framework e as ferramentas de deploy se apaga.'),
      (0, 'Both are lost in the same year',
       'The lesson separates them precisely because they decay at different speeds.',
       'Os dois se perdem no mesmo ano',
       'A aula os separa justamente porque se desgastam em velocidades diferentes.'),
      (0, 'Currency with tools survives, but design judgement fades without daily practice',
       'It is the other way round: the specific, current knowledge is what goes first.',
       'A atualização nas ferramentas sobrevive, mas o julgamento de design se apaga sem prática diária',
       'É o contrário: o conhecimento específico e atual é o que vai primeiro.'),
      (0, 'Neither, if the manager keeps reading about technology',
       'Reading does not replace working in the codebase, which is where the specific knowledge comes from.',
       'Nenhum dos dois, se a gestora continuar lendo sobre tecnologia',
       'Ler não substitui trabalhar no código, que é de onde vem o conhecimento específico.')])

mc('ex-6e42hvnb', 'the-pendulum', 'medium',
   ('Which kinds of code fit a manager’s week, by the lesson’s table? Choose all that apply.',
    'Quais tipos de código cabem na semana de uma gestora, pela tabela da aula? Marque todos que se aplicam.'),
   ('Nobody should be waiting on it.', 'Ninguém deveria estar esperando por ele.'),
   [(1, 'Reviewing pull requests', 'Yes: it keeps them current and fits between meetings.',
     'Revisar pull requests', 'Sim: mantém a gestora atualizada e cabe entre reuniões.'),
    (1, 'Small fixes and tooling off the critical path', 'Yes: nobody waits on them if a meeting runs over.',
     'Correções pequenas e ferramentas fora do caminho crítico', 'Sim: ninguém espera por elas se uma reunião atrasar.'),
    (1, 'Prototypes that will be thrown away', 'Yes: they answer a question without becoming something to maintain.',
     'Protótipos que vão para o lixo', 'Sim: respondem uma pergunta sem virar algo a manter.'),
    (0, 'A feature with a date in the sprint plan', 'No: that is the one kind the lesson rules out, because the team will wait for it.',
     'Uma funcionalidade com data no plano da sprint', 'Não: é o único tipo que a aula descarta, porque o time vai esperar por ela.'),
    (0, 'The most technically difficult ticket, to keep sharp', 'No: difficulty is not the test; whether the plan depends on it is.',
     'O ticket mais difícil tecnicamente, para se manter afiada', 'Não: dificuldade não é o critério; o plano depender dele é.')])

quiz('ex-h534ayp0', 'the-pendulum', 'medium',
     ('Why does the lesson call a tech lead’s lack of formal authority a feature as much as a cost?',
      'Por que a aula chama a falta de autoridade formal da liderança técnica de vantagem tanto quanto de custo?'),
     ('Who decides your promotion?', 'Quem decide a sua promoção?'),
     [(1, 'Engineers argue more openly with somebody who does not decide their pay or promotion',
       'Right: without the review in their hands, disagreements about design happen in the open.',
       'Engenheiros discutem mais abertamente com quem não decide o salário nem a promoção deles',
       'Isso: sem a avaliação nas mãos, as discordâncias de design acontecem às claras.'),
      (0, 'It frees the tech lead from reviewing other people’s code',
       'Reviews are a large part of the tech lead’s week, a third of Diego’s.',
       'Ela libera a liderança técnica de revisar o código dos outros',
       'Revisões são grande parte da semana da liderança técnica, um terço da do Diego.'),
      (0, 'It means the tech lead never has to persuade anybody',
       'The opposite: without authority, persuasion is the main tool.',
       'Significa que a liderança técnica nunca precisa convencer ninguém',
       'O contrário: sem autoridade, persuasão é a principal ferramenta.'),
      (0, 'Decisions get made faster, because nobody on the team is in a position to overrule a tech lead',
       'Speed is not the argument, and somebody can still overrule a design through the escalation the team agreed.',
       'Decisões saem mais rápido, porque ninguém no time está em posição de passar por cima de uma liderança técnica',
       'Velocidade não é o argumento, e alguém ainda pode passar por cima de um design pela escalada que o time combinou.')])

quiz('ex-9427bdf3', 'the-pendulum', 'hard',
     ('An engineer has managed for ten years and wants to go back to engineering. What does the lesson’s reasoning predict?',
      'Uma pessoa gerencia há dez anos e quer voltar para a engenharia. O que o raciocínio da aula prevê?'),
     ('What decays, and how fast?', 'O que se desgasta, e com que velocidade?'),
     [(1, 'A restart, not a return',
       'Right: the lesson puts two or three years away as a return and ten as a restart.',
       'Um recomeço, não uma volta',
       'Isso: a aula diz que dois ou três anos fora é uma volta, e dez é recomeçar.'),
      (0, 'An easy move, because judgement does not decay',
       'Judgement holds up, but the specific knowledge the job needs daily has gone.',
       'Uma mudança fácil, porque o julgamento não se desgasta',
       'O julgamento resiste, mas o conhecimento específico de que o trabalho precisa todo dia se foi.'),
      (0, 'A failure, which the pendulum essay warns against',
       'The essay argues the opposite: moving back is a normal career.',
       'Um fracasso, contra o qual o ensaio do pêndulo alerta',
       'O ensaio defende o contrário: voltar é uma carreira normal.'),
      (0, 'A move the company should refuse, since the dual track does not allow it',
       'A dual track exists to make such moves possible; nothing in the lesson says it forbids them.',
       'Uma mudança que a empresa deveria recusar, já que a trilha dupla não permite',
       'A trilha dupla existe para tornar esse movimento possível; nada na aula diz que ela o proíbe.')])

cloze('ex-zmk3k86a', 'the-pendulum', 'easy',
      ('Charity Majors’s 2017 essay compares the move between engineering and management to a ___.',
       'O ensaio de 2017 de Charity Majors compara o movimento entre engenharia e gestão a um ___.'),
      ('It swings both ways.', 'Ele balança para os dois lados.'),
      [(['pendulum'], ['pêndulo', 'pendulo'])])

quiz('ex-mv7btv9s', 'writing-it-down', 'easy',
     ('Why does every row of the agreement have exactly one name under “decides”?',
      'Por que toda linha do acordo tem exatamente um nome em “decide”?'),
     ('What is a decision with two deciders?', 'O que é uma decisão com duas pessoas decidindo?'),
     [(1, 'A decision with two deciders is a decision with none',
       'Right: two owners means both act, and they disagree in front of the team, as with Thiago.',
       'Uma decisão com duas pessoas decidindo é uma decisão sem nenhuma',
       'Isso: dois donos significa que os dois agem, e discordam na frente do time, como no caso do Thiago.'),
      (0, 'So that the manager can always overrule the tech lead',
       'Several rows give the decision to Diego, so it does not put Renata on top.',
       'Para a gestora sempre poder passar por cima da liderança técnica',
       'Várias linhas dão a decisão ao Diego, então ela não põe a Renata por cima.'),
      (0, 'Because HR requires a single owner for each decision',
       'Nobody outside the two asked for the page; the reason is the conflict in the team channel.',
       'Porque o RH exige um dono por decisão',
       'Ninguém além dos dois pediu a página; o motivo é o conflito no canal do time.'),
      (0, 'To keep the page short enough that the team will read it',
       'Length is not the reason; a page with two deciders per row would be no longer.',
       'Para manter a página curta o bastante para o time ler',
       'Tamanho não é o motivo; uma página com dois por linha não seria mais longa.')])

quiz('ex-ar3p3k1p', 'writing-it-down', 'medium',
     ('Renata and Diego disagree about the design of a feature, which the page gives to Diego. What does their second rule say happens?',
      'A Renata e o Diego discordam do design de uma funcionalidade, que a página dá ao Diego. O que diz a segunda regra deles?'),
     ('Argue where, then who decides, then what in public?', 'Discutir onde, depois quem decide, depois o quê em público?'),
     [(1, 'They argue in private, Diego decides, and Renata supports it in public',
       'Right: the owner decides after a private argument, and the other backs the decision in front of the team.',
       'Discutem em particular, o Diego decide, e a Renata apoia em público',
       'Isso: o dono decide depois de uma discussão em particular, e a outra apoia a decisão na frente do time.'),
      (0, 'Renata decides, because she is Diego’s manager',
       'The page gives design to Diego, and being his manager does not move that row.',
       'A Renata decide, porque é gestora do Diego',
       'A página dá o design ao Diego, e ser gestora dele não muda essa linha.'),
      (0, 'They take it to the team and vote',
       'The rule keeps the disagreement private; a vote would put it in front of the team.',
       'Levam ao time e votam',
       'A regra mantém a discordância em particular; uma votação a colocaria na frente do time.'),
      (0, 'They escalate it to Otávio, who decides between them',
       'Otávio is informed about some rows; he does not arbitrate the ones already assigned.',
       'Escalam para o Otávio, que decide entre eles',
       'O Otávio é informado de algumas linhas; ele não arbitra as que já têm dono.')])

quiz('ex-pkr96ys3', 'writing-it-down', 'medium',
     ('Why does the lesson say the page matters more than the conversation that produced it?',
      'Por que a aula diz que a página importa mais que a conversa que a produziu?'),
     ('How do people remember an agreement?', 'Como as pessoas lembram de um acordo?'),
     [(1, 'Memory drifts, and the team reads a page',
       'Right: two reasons in the lesson, the drift of memory and the team being able to read the page.',
       'A memória deriva; a página o time lê',
       'Isso: dois motivos na aula, a deriva da memória e o time poder ler a página.'),
      (0, 'Because a written agreement is legally binding',
       'Nothing about this is legal; it is about what people can point at.',
       'Porque um acordo escrito tem valor legal',
       'Nada disso é jurídico; é sobre aquilo que as pessoas podem apontar.'),
      (0, 'Because the conversation happened before the split',
       'It happened after the split, the week of the calendar-sync messages.',
       'Porque a conversa aconteceu antes da divisão',
       'Ela aconteceu depois da divisão, na semana das mensagens sobre a sincronização de calendário.'),
      (0, 'Because conversations between leads are never honest',
       'The lesson does not doubt the conversation’s honesty, only how it is remembered later.',
       'Porque conversas entre lideranças nunca são honestas',
       'A aula não duvida da honestidade da conversa, só de como ela é lembrada depois.')])

quiz('ex-fs3nwp92', 'drill', 'hard',
     ('A team has a tech lead and a manager. In planning, the tech lead says a feature takes six weeks and the manager has already told the director four. Which row of an agreement like Agenda’s was missing?',
      'Um time tem uma liderança técnica e uma gestora. No planejamento, a liderança técnica diz que uma funcionalidade leva seis semanas, e a gestora já disse quatro à diretoria. Qual linha de um acordo como o do Agenda estava faltando?'),
     ('Which item from the middle of the figure is this?', 'Qual item do meio da figura é este?'),
     [(1, 'Who decides the team’s commitments, and who is consulted first',
       'Right: on Agenda, Renata decides commitments after consulting Diego, which would have caught the gap before the director heard a number.',
       'Quem decide os compromissos do time, e quem é consultado antes',
       'Isso: no Agenda, a Renata decide compromissos depois de consultar o Diego, o que teria pegado a diferença antes de a diretoria ouvir um número.'),
      (0, 'Who decides how the feature is designed',
       'The disagreement is about the date promised, not the design.',
       'Quem decide como a funcionalidade é desenhada',
       'A discordância é sobre a data prometida, não sobre o design.'),
      (0, 'Who leads the technical response during an incident',
       'There is no incident here.',
       'Quem lidera a resposta técnica num incidente',
       'Não há incidente aqui.'),
      (0, 'Whether a pull request meets the bar',
       'Review standards have nothing to do with the estimate given upwards.',
       'Se um pull request atinge o padrão',
       'O padrão de revisão não tem relação com a estimativa passada para cima.')])

order('ex-3dfbxa7m', 'drill', 'medium',
      ('Put the steps of the agreement’s second rule in order, for a disagreement about a decision that already has an owner.',
       'Ponha em ordem os passos da segunda regra do acordo, para uma discordância sobre uma decisão que já tem dono.'),
      ('Private first, public last.', 'Particular primeiro, público por último.'),
      [('Both argue their case in private', 'Os dois defendem a sua posição em particular'),
       ('The owner of the decision decides', 'O dono da decisão decide'),
       ('The other supports the decision in public', 'O outro apoia a decisão em público')],
      ('Supporting in public before the private argument has happened means the disagreement is never heard.',
       'Apoiar em público antes da discussão em particular quer dizer que a discordância nunca é ouvida.'))
