"""Lesson 3: delegating outcomes instead of tasks."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-rhsw1kcx')

quiz('ex-4j3gq9de', 'tasks-and-outcomes', 'easy',
     ('What did Renata keep when she sent Paula the first, task-shaped message?',
      'Com o que a Renata ficou quando mandou à Paula a primeira mensagem, a de tarefa?'),
     ('The lesson’s phrase: she kept one thing and handed over another.',
      'A expressão da aula: ela ficou com uma coisa e entregou outra.'),
     [(1, 'The thinking',
       'Right: the diagnosis, the design and the estimate were all hers, and Paula got the typing.',
       'O raciocínio',
       'Isso: o diagnóstico, o design e a estimativa eram todos dela, e a Paula ficou com a digitação.'),
      (0, 'The deadline, which she left out of the message on purpose',
       'The deadline is not what the lesson says she kept; the task message did lack one, but that is not the point made.',
       'O prazo, que ela deixou de fora da mensagem de propósito',
       'O prazo não é o que a aula diz que ela reteve; a mensagem de tarefa não tinha um, mas o ponto é outro.'),
      (0, 'The contact with the clinics who complained about the duplicates',
       'Helena held the complaints, and the outcome message pointed Paula to her.',
       'O contato com as clínicas que reclamaram das duplicatas',
       'Quem tinha as reclamações era a Helena, e a mensagem de resultado apontava a Paula para ela.'),
      (0, 'The code review of whatever Paula wrote',
       'Review is not mentioned as what she kept; she kept the decisions about cause and design.',
       'A revisão de código do que a Paula escrevesse',
       'A revisão não aparece como o que ela reteve; ela reteve as decisões sobre causa e design.')])

quiz('ex-bcfajxp7', 'tasks-and-outcomes', 'medium',
     ('Which of these is an outcome rather than a task?',
      'Qual destes é um resultado, e não uma tarefa?'),
     ('Does it name a mechanism?', 'Ele nomeia um mecanismo?'),
     [(1, 'Clinics see a patient’s full history within two seconds',
       'Right: it says what has to be true and leaves the how open.',
       'As clínicas veem o histórico completo de um paciente em até dois segundos',
       'Isso: diz o que precisa ser verdade e deixa o como em aberto.'),
      (0, 'Add an index on the appointments table',
       'It names a table and a technique, so the design has been decided.',
       'Criar um índice na tabela de consultas',
       'Nomeia uma tabela e uma técnica, então o design já foi decidido.'),
      (0, 'Move the history query to the read replica so the primary is less loaded at peak times',
       'A mechanism with a reason attached is still a mechanism.',
       'Passar a consulta de histórico para a réplica de leitura para aliviar o primário nos picos',
       'Um mecanismo com motivo anexado continua sendo um mecanismo.'),
      (0, 'Cache the patient history in Redis',
       'It names a tool and a design.',
       'Guardar o histórico do paciente em cache no Redis',
       'Nomeia uma ferramenta e um design.')])

quiz('ex-dhypryqj', 'tasks-and-outcomes', 'medium',
     ('Why would the task version of the reminders fix have left the problem half solved?',
      'Por que a versão de tarefa da correção dos lembretes teria deixado o problema pela metade?'),
     ('Where did the duplicates actually come from?', 'De onde vinham de fato as duplicatas?'),
     [(1, 'Most duplicates came from reschedules made more than a day ahead, which the 24-hour check would miss',
       'Right: the cause was rescheduling, and a check on `sent_at` within a day misses every reschedule made further ahead.',
       'Boa parte vinha de remarcações feitas com mais de um dia de antecedência, que a checagem de 24 horas perderia',
       'Isso: a causa era a remarcação, e uma checagem de `sent_at` em um dia perde toda remarcação feita com mais antecedência.'),
      (0, 'Paula would have built it wrongly',
       'She would have built exactly what was asked; the problem was in what was asked.',
       'A Paula teria construído errado',
       'Ela teria construído exatamente o que foi pedido; o problema estava no pedido.'),
      (0, 'The review would have rejected it',
       'The lesson says it would have passed review, which is why the failure would have been invisible.',
       'A revisão a teria rejeitado',
       'A aula diz que teria passado na revisão, por isso a falha seria invisível.'),
      (0, 'The `sent_at` column did not exist in the reminder service',
       'Nothing says the column was missing; the guess about the cause was what was wrong.',
       'A coluna `sent_at` não existia no serviço de lembretes',
       'Nada diz que a coluna faltava; o que estava errado era o palpite sobre a causa.')])

mc('ex-xp1qfxyc', 'tasks-and-outcomes', 'medium',
   ('Which are tests the lesson gives for spotting a task disguised as an outcome? Choose all that apply.',
    'Quais são testes que a aula dá para identificar uma tarefa disfarçada de resultado? Marque todos que se aplicam.'),
   ('Three tests.', 'Três testes.'),
   [(1, 'It names a mechanism such as a table or a library', 'Yes: then the design has been decided for the person.',
     'Ela nomeia um mecanismo, como uma tabela ou uma biblioteca', 'Sim: aí o design foi decidido pela pessoa.'),
    (1, 'It could be done exactly as written and still fail', 'Yes: the `sent_at` check could; “exactly one reminder” could not.',
     'Dá para fazer exatamente como escrito e ainda falhar', 'Sim: a checagem de `sent_at` podia; “exatamente um lembrete” não.'),
    (1, 'The person would need to come back if the first idea failed', 'Yes: with a task the plan was the manager’s.',
     'A pessoa precisaria voltar se a primeira ideia falhasse', 'Sim: numa tarefa, o plano era da gestora.'),
    (0, 'It has no deadline', 'A missing deadline is a gap in the context, not the mark of a task.',
     'Ela não tem prazo', 'Prazo ausente é uma lacuna de contexto, não a marca de uma tarefa.'),
    (0, 'It is shorter than three sentences', 'Length says nothing; an outcome can be one line.',
     'Ela tem menos de três frases', 'Tamanho não diz nada; um resultado pode ter uma linha.')])

quiz('ex-epydrmjj', 'the-context', 'easy',
     ('What did Marquet ask his officers to start their proposals with?',
      'Com o que Marquet pediu que os oficiais começassem as propostas?'),
     ('Two words and a plan.', 'Duas palavras e um plano.'),
     [(1, '“I intend to…”',
       'Right: the officer states the plan, and over time why it is safe, and the commander checks it.',
       '“Eu pretendo…”',
       'Isso: o oficial declara o plano e, com o tempo, por que é seguro, e o comandante confere.'),
      (0, '“Permission to…”, so the commander can approve each step before it happens',
       'That keeps the thinking with the commander, which is what he stopped doing.',
       '“Permissão para…”, para o comandante aprovar cada passo antes de acontecer',
       'Isso mantém o raciocínio com o comandante, que é o que ele parou de fazer.'),
      (0, '“What should I do about…”',
       'A question hands the decision back up; the point was for the officer to decide.',
       '“O que eu devo fazer sobre…”',
       'Uma pergunta devolve a decisão para cima; o objetivo era o oficial decidir.'),
      (0, 'A written risk assessment for the operation',
       'He asked for intent first; the reason it was safe came with it over time.',
       'Uma avaliação de risco por escrito da operação',
       'Ele pediu a intenção primeiro; o motivo de ser seguro veio junto com o tempo.')])

match('ex-9dvzw99j', 'the-context', 'easy',
      ('Match each heading of Renata’s delegation with what she wrote under it for the reminders work.',
       'Ligue cada título da delegação da Renata ao que ela escreveu nele para o trabalho dos lembretes.'),
      ('Five headings; one right-hand item belongs to none.', 'Cinco títulos; um item da direita não pertence a nenhum.'),
      [('the outcome', 'one reminder per appointment, and an alert if not',
        'o resultado', 'um lembrete por consulta, e um alerta se não'),
       ('why it matters', 'patients ignore the messages; two clinics complained',
        'por que importa', 'pacientes ignoram as mensagens; duas clínicas reclamaram'),
       ('the limits', 'no change to the message text legal approved',
        'os limites', 'nenhuma mudança no texto que o jurídico aprovou'),
       ('what you decide', 'the cause, the design, whether it needs a migration',
        'o que você decide', 'a causa, o design, se precisa de migração'),
       ('who knows what', 'Helena has the complaints; Yara wrote the reschedule code',
        'quem sabe o quê', 'a Helena tem as reclamações; a Yara escreveu o código de remarcação')],
      [('I think it might be the `sent_at` check', 'acho que pode ser a checagem de `sent_at`')])

quiz('ex-9h0wskpr', 'the-context', 'medium',
     ('Why are the limits the part of the context only the manager can supply?',
      'Por que os limites são a parte do contexto que só a gestora pode fornecer?'),
     ('Think of the reminder text.', 'Pense no texto do lembrete.'),
     [(1, 'They are facts the person has no way of knowing',
       'Right: Paula could not have known that legal had approved the message text.',
       'São fatos de fora que a pessoa não tem como saber sozinha',
       'Isso: a Paula não tinha como saber que o jurídico havia aprovado o texto da mensagem.'),
      (0, 'Because setting limits is how the manager keeps control of the design',
       'Limits are constraints from outside, not a way to steer the design; the design was Paula’s.',
       'Porque definir limites é como a gestora mantém o controle do design',
       'Limites são restrições de fora, não um jeito de conduzir o design; o design era da Paula.'),
      (0, 'Because the person would set limits that are too loose',
       'Nothing suggests Paula would be careless; she simply lacked the information.',
       'Porque a pessoa definiria limites frouxos demais',
       'Nada sugere que a Paula seria descuidada; faltava a ela a informação.'),
      (0, 'Because company policy says only managers may write limits',
       'No such policy appears; the reason is who holds the facts.',
       'Porque a política da empresa diz que só gestoras escrevem limites',
       'Não aparece política nenhuma; o motivo é quem tem os fatos.')])

quiz('ex-2jwnarf4', 'the-context', 'hard',
     ('A manager delegating a slow-page problem adds: “I think it’s probably the ORM doing N+1 queries.” What does the lesson advise?',
      'Uma gestora delegando um problema de página lenta acrescenta: “Acho que provavelmente é o ORM fazendo consultas N+1.” O que a aula aconselha?'),
     ('A guess from your manager is hard to discard.', 'Um palpite da sua gestora é difícil de descartar.'),
     [(1, 'Leave it out, or label it a hypothesis and put it after the outcome',
       'Right: the person will otherwise start there and struggle to let go of it, even against the evidence.',
       'Deixar de fora, ou chamá-lo de hipótese e pôr depois do resultado',
       'Isso: senão a pessoa começa por ali e tem dificuldade de largar, mesmo contra a evidência.'),
      (0, 'Put it first, since it saves the person time',
       'Leading with it makes it the starting point, which is the risk the lesson describes.',
       'Pôr primeiro, porque economiza tempo da pessoa',
       'Abrir com ele o torna o ponto de partida, que é o risco que a aula descreve.'),
      (0, 'Turn it into the outcome: “remove the N+1 queries”',
       'That is a task naming a mechanism, the opposite of an outcome.',
       'Transformá-lo no resultado: “remover as consultas N+1”',
       'Isso é uma tarefa que nomeia um mecanismo, o contrário de um resultado.'),
      (0, 'Keep it, as long as the deadline also carries a reason the person can weigh against what they find',
       'A reason for the deadline is good advice, but it does nothing about an anchoring guess.',
       'Mantê-lo, desde que o prazo também traga um motivo que a pessoa possa pesar contra o que encontrar',
       'Um motivo para o prazo é bom conselho, mas não resolve um palpite que ancora.')])

quiz('ex-yv5fqn2c', 'levels', 'easy',
     ('At which of Appelo’s levels does the person decide and tell the manager afterwards?',
      'Em qual dos níveis de Appelo a pessoa decide e conta à gestora depois?'),
     ('Between advise and delegate.', 'Entre aconselhar e delegar.'),
     [(1, 'Inquire',
       'Right: at inquire the person decides, and the manager asks, or hears, afterwards.',
       'Perguntar',
       'Isso: em perguntar a pessoa decide, e a gestora pergunta, ou fica sabendo, depois.'),
      (0, 'Advise, where the manager gives a view before the decision',
       'At advise the person hears the manager first, then decides.',
       'Aconselhar, em que a gestora dá a opinião antes da decisão',
       'Em aconselhar a pessoa ouve a gestora antes, depois decide.'),
      (0, 'Consult',
       'At consult the manager still decides, after asking.',
       'Consultar',
       'Em consultar quem decide ainda é a gestora, depois de perguntar.'),
      (0, 'Delegate, the top rung of the ladder',
       'At delegate the manager does not need to hear at all.',
       'Delegar, o degrau mais alto da escada',
       'Em delegar a gestora nem precisa ficar sabendo.')])

order('ex-5nfjnp60', 'levels', 'medium',
      ('Put Appelo’s seven levels of delegation in order, from the manager deciding alone to the person deciding alone.',
       'Ponha os sete níveis de delegação de Appelo em ordem, da gestora decidindo sozinha à pessoa decidindo sozinha.'),
      ('Authority moves across in the middle.', 'A autoridade muda de lado no meio.'),
      [('Tell', 'Dizer'), ('Sell', 'Vender'), ('Consult', 'Consultar'), ('Agree', 'Concordar'),
       ('Advise', 'Aconselhar'), ('Inquire', 'Perguntar'), ('Delegate', 'Delegar')],
      ('Consult and advise are easy to swap: at consult the manager decides, at advise the person does.',
       'Consultar e aconselhar são fáceis de trocar: em consultar a gestora decide, em aconselhar a pessoa decide.'))

quiz('ex-c1j485nt', 'levels', 'medium',
     ('Paula has worked on the reminder service for a year, and a wrong fix can be reverted the same day. Which rung did Renata choose for the design, and why?',
      'A Paula trabalha no serviço de lembretes há um ano, e uma correção errada pode ser revertida no mesmo dia. Que degrau a Renata escolheu para o design, e por quê?'),
     ('Familiar and cheap to get wrong.', 'Familiar e barato de errar.'),
     [(1, 'Inquire: familiar work and a cheap mistake sit high',
       'Right: level 6, because the two questions, cost and familiarity, both pointed up.',
       'Perguntar: trabalho familiar e erro barato ficam no alto',
       'Isso: nível 6, porque as duas perguntas, custo e familiaridade, apontavam para cima.'),
      (0, 'Agree, because a fix that touches production should always need two people to consent',
       'Agree is slow and kept for decisions that really need two people; this one did not.',
       'Concordar, porque uma correção que mexe em produção sempre deveria precisar do consentimento de duas pessoas',
       'Concordar é lento e fica para decisões que de fato precisam de duas pessoas; esta não precisava.'),
      (0, 'Consult, since Renata was still new as a manager',
       'The rung depends on the decision and the person, not on how new the manager is.',
       'Consultar, já que a Renata ainda era nova como gestora',
       'O degrau depende da decisão e da pessoa, não de quão nova a gestora é.'),
      (0, 'Tell, so Paula would not waste time',
       'Telling hands over the typing, which is the task version the lesson started by rejecting.',
       'Dizer, para a Paula não perder tempo',
       'Dizer entrega a digitação, a versão de tarefa que a aula começa rejeitando.')])

quiz('ex-2aevncsv', 'levels', 'hard',
     ('A manager thinks a decision was delegated at advise. The engineer thinks it was at delegate, decides, and says nothing. What does the lesson say prevents this?',
      'Uma gestora acha que uma decisão foi delegada em aconselhar. O engenheiro acha que foi em delegar, decide e não diz nada. O que a aula diz que evita isso?'),
     ('One more line under the five headings.', 'Mais uma linha sob os cinco títulos.'),
     [(1, 'Saying the rung in words when delegating',
       'Right: “show me before it goes live” is advise, and saying it costs one sentence.',
       'Dizer em palavras, no momento de delegar, qual é o degrau',
       'Isso: “me mostra antes de ir para produção” é aconselhar, e dizer custa uma frase.'),
      (0, 'Never delegating above consult until trust is built',
       'That keeps the manager as a bottleneck; the problem was that the rung was never said.',
       'Nunca delegar acima de consultar até haver confiança',
       'Isso mantém a gestora como gargalo; o problema foi o degrau nunca ter sido dito.'),
      (0, 'A weekly status report from every engineer on the team',
       'A report might surface it later, but it would not have stopped the mismatch.',
       'Um relatório semanal de status de cada engenheiro do time',
       'Um relatório talvez revelasse depois, mas não teria evitado o desencontro.'),
      (0, 'Reversing the engineer’s decision quietly, to make the point',
       'The lesson calls a silent reversal the worst version, because it teaches that the rung meant nothing.',
       'Reverter a decisão do engenheiro às escondidas, para deixar claro',
       'A aula chama a reversão silenciosa de pior versão, porque ensina que o degrau não significava nada.')])

quiz('ex-ss1krbjq', 'when-it-goes-wrong', 'easy',
     ('What does the lesson say a manager should do before correcting delegated work that looks wrong?',
      'O que a aula diz que uma gestora deveria fazer antes de corrigir um trabalho delegado que parece errado?'),
     ('Renata did it in the pull request.', 'A Renata fez isso no pull request.'),
     [(1, 'Ask what the person found and why they chose that approach',
       'Right: Paula’s answer revealed the reschedule cause, and the work only looked wrong because Renata’s model was.',
       'Perguntar o que a pessoa descobriu e por que escolheu essa abordagem',
       'Isso: a resposta da Paula revelou a causa nas remarcações, e o trabalho só parecia errado porque o modelo da Renata estava.'),
      (0, 'Offer to pair',
       'The lesson calls that the same rescue with better manners.',
       'Oferecer parear',
       'A aula chama isso do mesmo resgate com modos melhores.'),
      (0, 'Comment with the fix she has in mind',
       'That was her first instinct, and it would have replaced a correct fix with a wrong one.',
       'Comentar com a correção que tem em mente',
       'Esse foi o primeiro instinto dela, e teria trocado uma correção certa por uma errada.'),
      (0, 'Move the work down the ladder to tell',
       'Changing the rung is for real trouble, said openly; here a question was enough.',
       'Descer o trabalho na escada até dizer',
       'Mudar o degrau é para problema de verdade, dito às claras; aqui uma pergunta bastava.')])

quiz('ex-56dy02dj', 'when-it-goes-wrong', 'medium',
     ('Marcos was stuck for two weeks on a delegated upgrade and said nothing. What would have surfaced it in days?',
      'O Marcos ficou duas semanas travado numa atualização delegada e não disse nada. O que teria revelado isso em dias?'),
     ('Agreed in advance, about progress.', 'Combinado de antemão, sobre progresso.'),
     [(1, 'An early checkpoint agreed when the work was delegated',
       'Right: the early checkpoint catches the person who is stuck before they have been stuck for long.',
       'Um ponto de verificação cedo, combinado ao delegar',
       'Isso: o ponto cedo pega a pessoa travada antes de ela ficar travada por muito tempo.'),
      (0, 'Delegating at a higher rung, so he felt more ownership',
       'He was already at the top rung; ownership was not what was missing.',
       'Delegar num degrau mais alto, para ele se sentir mais dono',
       'Ele já estava no degrau mais alto; não era senso de dono o que faltava.'),
      (0, 'Not delegating library upgrades at all',
       'Routine work is a good thing to delegate; the failure was the absence of any checkpoint.',
       'Nunca delegar atualizações de biblioteca',
       'Trabalho de rotina é bom de delegar; a falha foi não haver ponto de verificação nenhum.'),
      (0, 'Asking him every day how it was going, even though that would feel like supervision to most people',
       'Daily unplanned questions are the supervision the lesson distinguishes from a checkpoint.',
       'Perguntar todo dia como estava indo, mesmo que isso pareça supervisão para a maioria das pessoas',
       'Perguntas diárias sem combinar são a supervisão que a aula distingue de um ponto de verificação.')])

mc('ex-ggxw2c23', 'when-it-goes-wrong', 'medium',
   ('In which situations does the lesson say taking delegated work back is right? Choose all that apply.',
    'Em quais situações a aula diz que pegar de volta um trabalho delegado é certo? Marque todas que se aplicam.'),
   ('Said openly, with the rung changed.', 'Dito às claras, com o degrau mudado.'),
   [(1, 'A real date is about to be missed', 'Yes, said openly and with the rung changed.',
     'Uma data real está prestes a estourar', 'Sim, dito às claras e com o degrau mudado.'),
    (1, 'A security or data-protection problem is being introduced', 'Yes.',
     'Um problema de segurança ou de proteção de dados está sendo introduzido', 'Sim.'),
    (1, 'The person asks for somebody else to take over', 'Yes: that is help they asked for.',
     'A pessoa pede que outra pessoa assuma', 'Sim: é a ajuda que ela pediu.'),
    (0, 'The approach differs from the one the manager would take', 'No: that is the rescue the lesson warns against.',
     'A abordagem difere da que a gestora usaria', 'Não: esse é o resgate contra o qual a aula alerta.'),
    (0, 'The pull request is bigger than expected', 'No: size alone was what alarmed Renata, wrongly.',
     'O pull request está maior do que o esperado', 'Não: tamanho sozinho foi o que alarmou a Renata, sem razão.')])

quiz('ex-pvmyfw0b', 'drill', 'hard',
     ('Yara will lead the migration of booking data to a new schema, a month of work she has never done before, with a date the clinics were promised. Which arrangement fits the lesson best?',
      'A Yara vai liderar a migração dos dados de agendamento para um novo esquema, um mês de trabalho que ela nunca fez, com uma data prometida às clínicas. Qual arranjo combina melhor com a aula?'),
     ('Unfamiliar, costly, dated.', 'Pouco familiar, cara, com data.'),
     [(1, 'Outcome with full context, design at advise, a checkpoint early, weekly ones and one at halfway',
       'Right: an unfamiliar and expensive decision sits lower, and a dated, long piece of work wants the early, weekly and halfway checkpoints.',
       'Resultado com contexto completo, design em aconselhar, um ponto cedo, pontos semanais e um na metade',
       'Isso: decisão pouco familiar e cara fica mais embaixo, e trabalho longo com data pede ponto cedo, semanais e um na metade.'),
      (0, 'Delegate at the top rung and check at the end, to show trust',
       'That is the disappearance, and on unfamiliar work with a date it is how Marcos’s two lost weeks happen.',
       'Delegar no degrau mais alto e verificar no fim, para mostrar confiança',
       'Esse é o desaparecimento, e em trabalho pouco familiar com data é como acontecem as duas semanas perdidas do Marcos.'),
      (0, 'A detailed task list written by Renata',
       'Tasks keep the thinking with the manager; Yara is senior and the work needs her judgement.',
       'Uma lista de tarefas detalhada escrita pela Renata',
       'Tarefas mantêm o raciocínio com a gestora; a Yara é sênior e o trabalho precisa do julgamento dela.'),
      (0, 'Agree on every decision, so nothing goes wrong',
       'Agree on everything is slow and makes Renata a bottleneck; few of the decisions need two people.',
       'Concordar em toda decisão, para nada dar errado',
       'Concordar em tudo é lento e faz da Renata um gargalo; poucas decisões precisam de duas pessoas.')])
