"""Lesson 4: autonomy against alignment."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-jmbzmjxk')

quiz('ex-xasswwes', 'the-two-axes', 'easy',
     ('What is wrong with picturing team freedom as one slider from “manager decides” to “team decides”?',
      'O que há de errado em imaginar a liberdade do time como um controle só, de “a gestão decide” a “o time decide”?'),
     ('How many axes did Kniberg draw?', 'Quantos eixos Kniberg desenhou?'),
     [(1, 'It makes autonomy and alignment opposites, when they are independent',
       'Right: on two axes, a team can have more of both at once.',
       'Ele faz de autonomia e alinhamento opostos, quando são independentes',
       'Isso: em dois eixos, um time pode ter mais dos dois ao mesmo tempo.'),
      (0, 'It leaves out the team’s product manager',
       'The picture is about who decides and who knows the goal, not about roles.',
       'Ele deixa de fora a gerente de produto do time',
       'A imagem é sobre quem decide e quem conhece o objetivo, não sobre papéis.'),
      (0, 'Teams have no autonomy anyway',
       'The lesson treats autonomy as real and worth having, at a price.',
       'Times não têm autonomia de qualquer jeito',
       'A aula trata autonomia como real e valiosa, com um preço.'),
      (0, 'It puts the manager at one end, when the manager should sit in the middle of every decision the team makes',
       'Sitting in the middle of every decision is the bottleneck lesson 3 warned against.',
       'Ele põe a gestão numa ponta, quando a gestão deveria estar no meio de toda decisão que o time toma',
       'Estar no meio de toda decisão é o gargalo contra o qual a aula 3 alertou.')])

match('ex-zrb6mjdb', 'the-two-axes', 'medium',
      ('Match each corner of Kniberg’s grid with what the manager says in it.',
       'Ligue cada canto da grade de Kniberg ao que a gestão diz nele.'),
      ('Goal explained or not; solution chosen or not.', 'Objetivo explicado ou não; solução escolhida ou não.'),
      [('high alignment, low autonomy', '“we need to cross; build this bridge, this way”',
        'alinhamento alto, autonomia baixa', '“precisamos atravessar; construam esta ponte, assim”'),
       ('high alignment, high autonomy', '“we need to cross, and this is why”',
        'alinhamento alto, autonomia alta', '“precisamos atravessar, e o motivo é este”'),
       ('low alignment, high autonomy', '“do what you think best”',
        'alinhamento baixo, autonomia alta', '“façam o que acharem melhor”'),
       ('low alignment, low autonomy', '“do this”', 'alinhamento baixo, autonomia baixa', '“faça isto”')])

quiz('ex-6ct36nkn', 'the-two-axes', 'medium',
     ('A manager wants to give the team more autonomy. On the two axes, what should change in what they say?',
      'Uma gestora quer dar mais autonomia ao time. Nos dois eixos, o que deveria mudar no que ela diz?'),
     ('The total does not go down; it moves.', 'O total não diminui; ele muda de lugar.'),
     [(1, 'More about the goal, less about the method',
       'Right: communication moves from how to why, and the team decides the how.',
       'Mais sobre o objetivo, menos sobre o método',
       'Isso: a comunicação passa do como para o porquê, e o time decide o como.'),
      (0, 'Less overall, so the team has room to think for itself',
       'Saying less overall is the slider picture, and it leaves the team without the goal.',
       'Menos no total, para o time ter espaço de pensar sozinho',
       'Falar menos no total é a imagem do controle deslizante, e deixa o time sem o objetivo.'),
      (0, 'Nothing; autonomy is about trust, not words',
       'The lesson describes the price of aligned autonomy as the manager’s effort explaining the problem.',
       'Nada; autonomia é questão de confiança, não de palavras',
       'A aula descreve o preço da autonomia alinhada como o esforço da gestão em explicar o problema.'),
      (0, 'More about the method, so mistakes are avoided',
       'That moves the team towards the authoritative corner, with less autonomy.',
       'Mais sobre o método, para evitar erros',
       'Isso leva o time para o canto autoritário, com menos autonomia.')])

quiz('ex-tptjepvv', 'the-two-axes', 'hard',
     ('Why did Renata ask Otávio for the problem instead of accepting his list of three features?',
      'Por que a Renata pediu ao Otávio o problema em vez de aceitar a lista de três funcionalidades?'),
     ('Which corner was the list?', 'Em que canto estava a lista?'),
     [(1, 'The list chose the solution for the team, while the problem left the team free to find one',
       'Right, and the team then found that most no-shows came from bookings made weeks ahead, which none of the three targeted.',
       'A lista escolhia a solução pelo time, enquanto o problema deixava o time livre para achar uma',
       'Isso, e o time descobriu que a maioria das faltas vinha de marcações feitas semanas antes, que nenhuma das três atacava.'),
      (0, 'She thought the three features were wrong and wanted to replace them with her own',
       'She did not reject them; two shipped later, and she called them ideas rather than a plan.',
       'Ela achava as três funcionalidades erradas e queria trocá-las pelas dela',
       'Ela não as rejeitou; duas foram ao ar depois, e ela as chamou de ideias, não de plano.'),
      (0, 'Because a manager should never accept a list from above',
       'Nothing says that; the point is which corner of the grid the list put the team in.',
       'Porque uma gestora nunca deveria aceitar uma lista de cima',
       'Nada diz isso; o ponto é em que canto da grade a lista punha o time.'),
      (0, 'To delay the quarter until there was more data',
       'Gathering more before acting is the instinct against the knowledge gap that the next section warns about.',
       'Para adiar o trimestre até haver mais dados',
       'Juntar mais antes de agir é o instinto contra a lacuna de conhecimento de que a próxima seção alerta.')])

num('ex-x16a7yw4', 'the-two-axes', 'easy',
    ('Agenda’s data says about one appointment in nine is a no-show. Out of 900 appointments, about how many is that?',
     'Os dados do Agenda dizem que cerca de uma consulta em nove é falta. Em 900 consultas, isso dá cerca de quantas?'),
    ('900 divided by 9.', '900 dividido por 9.'),
    100, 0, ('appointments', 'consultas'), (['appointment'], ['consulta']))

quiz('ex-48gdzzd0', 'three-gaps', 'easy',
     ('Which gap is between what people do and what it achieves?',
      'Qual lacuna fica entre o que as pessoas fazem e o que isso alcança?'),
     ('The work was done as intended.', 'O trabalho foi feito como pretendido.'),
     [(1, 'Effects',
       'Right: actions done as planned that do not have the effect planned.',
       'Efeitos',
       'Isso: ações feitas como planejado que não têm o efeito planejado.'),
      (0, 'Knowledge, between the plan and what is really out there',
       'That one is between plans and outcomes: planning on incomplete information.',
       'Conhecimento, entre o plano e o que de fato existe lá fora',
       'Essa fica entre planos e resultados: planejar com informação incompleta.'),
      (0, 'Alignment, between the plan and what people do',
       'That one is people doing something other than what was meant.',
       'Alinhamento, entre o plano e o que as pessoas fazem',
       'Essa é as pessoas fazerem algo diferente do que se pretendia.'),
      (0, 'Communication',
       'Not one of Bungay’s three.',
       'Comunicação',
       'Não é uma das três de Bungay.')])

quiz('ex-7gbkztdd', 'three-gaps', 'medium',
     ('What do the three instinctive responses to Bungay’s gaps have in common?',
      'O que as três respostas instintivas às lacunas de Bungay têm em comum?'),
     ('Information, instructions, controls.', 'Informação, instruções, controles.'),
     [(1, 'Each adds detail, and widens the gap it meant to close',
       'Right: more information, more instructions, more controls, and less room to respond.',
       'Cada uma acrescenta detalhe, e alarga a lacuna que queria fechar',
       'Isso: mais informação, mais instruções, mais controles, e menos espaço para responder.'),
      (0, 'Each moves decisions down to the team',
       'The instincts do the opposite and pull decisions up.',
       'Cada uma passa decisões para o time',
       'Os instintos fazem o contrário e puxam decisões para cima.'),
      (0, 'Each one works for a while, until the team grows past about ten people and the gap returns',
       'Bungay’s point is that they make the gap worse, not that they stop working at some size.',
       'Cada uma funciona por um tempo, até o time passar de umas dez pessoas e a lacuna voltar',
       'O ponto de Bungay é que elas pioram a lacuna, não que param de funcionar a partir de certo tamanho.'),
      (0, 'Each is what Bungay recommends',
       'He recommends the opposite of each: decide only what you must, explain intent, give freedom to adjust.',
       'Cada uma é o que Bungay recomenda',
       'Ele recomenda o oposto de cada uma: decidir só o necessário, explicar a intenção, dar liberdade para ajustar.')])

match('ex-g201syh3', 'three-gaps', 'medium',
      ('Match each gap with what Bungay recommends against it.',
       'Ligue cada lacuna ao que Bungay recomenda contra ela.'),
      ('Less detail, more intent.', 'Menos detalhe, mais intenção.'),
      [('the knowledge gap', 'decide only what you must, at your level',
        'a lacuna de conhecimento', 'decidir só o necessário, no seu nível'),
       ('the alignment gap', 'explain the intent rather than add instructions',
        'a lacuna de alinhamento', 'explicar a intenção em vez de acrescentar instruções'),
       ('the effects gap', 'give people freedom to adjust within limits',
        'a lacuna de efeitos', 'dar liberdade para ajustar dentro de limites')],
      [('add a weekly report against a target', 'acrescentar um relatório semanal contra uma meta')])

quiz('ex-5pqp923j', 'three-gaps', 'hard',
     ('Freed slots late in the day stayed empty after the cancellation link shipped. Why did the plan change without anybody issuing an instruction?',
      'Horários liberados tarde no dia ficavam vazios depois que o link de cancelamento foi ao ar. Por que o plano mudou sem ninguém dar uma instrução?'),
     ('What did the team know the plan was for?', 'O que o time sabia sobre para que o plano servia?'),
     [(1, 'The team knew the goal was appointments kept, so it moved the waiting list up',
       'Right: knowing the intent let the people who saw the effects gap act on it.',
       'O time sabia que o objetivo era consultas mantidas, então subiu a lista de espera',
       'Isso: conhecer a intenção deixou quem viu a lacuna de efeitos agir sobre ela.'),
      (0, 'Otávio added a weekly target for slot reuse',
       'That was the instinct the lesson describes, and it did not happen.',
       'O Otávio acrescentou uma meta semanal de reaproveitamento de horários',
       'Esse era o instinto que a aula descreve, e não aconteceu.'),
      (0, 'The clinics fixed it themselves',
       'The clinics complained; the team changed the product.',
       'As próprias clínicas resolveram',
       'As clínicas reclamaram; o time mudou o produto.'),
      (0, 'Renata decided it alone and told the team',
       'She shared the complaint and the goal; the team chose the waiting list.',
       'A Renata decidiu sozinha e avisou o time',
       'Ela compartilhou a reclamação e o objetivo; o time escolheu a lista de espera.')])

quiz('ex-3nb2paw6', 'who-decides', 'easy',
     ('By the Amazon letter’s distinction, where do two-way doors belong?',
      'Pela distinção da carta da Amazon, onde ficam as portas de mão dupla?'),
     ('A wrong decision is cheap to undo.', 'Uma decisão errada é barata de desfazer.'),
     [(1, 'As close to the work as possible',
       'Right: the cost of a wrong decision is small and the cost of waiting is not.',
       'O mais perto possível do trabalho',
       'Isso: o custo de uma decisão errada é pequeno e o de esperar não é.'),
      (0, 'With the most senior person available',
       'That treats a two-way door as a one-way door, which the letter warns makes everything slow.',
       'Com a pessoa mais sênior disponível',
       'Isso trata uma porta de mão dupla como de mão única, o que a carta diz deixar tudo lento.'),
      (0, 'In a design review across teams',
       'That is for consequential one-way doors, like changing the database engine.',
       'Numa revisão de design entre times',
       'Isso é para portas de mão única com consequências, como trocar o motor de banco de dados.'),
      (0, 'With whoever will live with the consequences longest, after a formal written review of the options',
       'That is where one-way doors go.',
       'Com quem vai viver mais tempo com as consequências, depois de uma revisão formal por escrito das opções',
       'É para lá que vão as portas de mão única.')])

quiz('ex-wkxwtp9z', 'who-decides', 'medium',
     ('A new public API field looks easy to rename on the day it ships. Why does the lesson warn against treating it as a two-way door?',
      'Um campo novo de uma API pública parece fácil de renomear no dia em que vai ao ar. Por que a aula alerta contra tratá-lo como porta de mão dupla?'),
     ('What happens to it over the next six months?', 'O que acontece com ele nos seis meses seguintes?'),
     [(1, 'Things get built on it, and it hardens',
       'Right: clinics’ systems start calling it, and six months later the rename is expensive.',
       'Coisas são construídas em cima dele, e ele endurece',
       'Isso: os sistemas das clínicas começam a chamá-lo, e seis meses depois renomear sai caro.'),
      (0, 'APIs are never allowed to change',
       'They change; the cost of changing grows with what depends on them.',
       'APIs nunca podem mudar',
       'Elas mudam; o custo de mudar cresce com o que depende delas.'),
      (0, 'Field names need the legal team’s approval',
       'Legal approved the reminder text, not API fields.',
       'Nomes de campo precisam de aprovação do jurídico',
       'O jurídico aprovou o texto do lembrete, não campos de API.'),
      (0, 'Because the team has no right to make technical decisions about anything clinics will see',
       'Nothing removes the team’s right; the question is how reversible the decision really is.',
       'Porque o time não tem direito de tomar decisões técnicas sobre nada que as clínicas vão ver',
       'Nada tira esse direito do time; a questão é quão reversível a decisão de fato é.')])

quiz('ex-f26dr88g', 'who-decides', 'medium',
     ('At three in the morning, nobody knew who could turn off a feature flag. What does the lesson draw from it?',
      'Às três da manhã, ninguém sabia quem podia desligar uma feature flag. O que a aula tira disso?'),
     ('Some owners can be found over a week; some cannot.', 'Alguns donos dá para descobrir em uma semana; outros não.'),
     [(1, 'Write down first the decisions needed in a hurry',
       'Right: a rollback owner cannot be worked out while customers are failing to book.',
       'Escreva primeiro as decisões necessárias com pressa',
       'Isso: o dono de um rollback não se descobre enquanto clientes não conseguem marcar.'),
      (0, 'Feature flags should only be turned off by the tech lead',
       'The lesson does not assign the flag to Diego; it says the decision had no owner.',
       'Feature flags só deveriam ser desligadas pela liderança técnica',
       'A aula não dá a flag ao Diego; diz que a decisão não tinha dono.'),
      (0, 'On-call engineers should wake the manager for every decision',
       'That is the twenty-minute wait, made a rule.',
       'Quem está de plantão deveria acordar a gestora para toda decisão',
       'Isso é a espera de vinte minutos virando regra.'),
      (0, 'Incidents are too rare to plan decision rights for',
       'The lesson argues the opposite: hurried decisions are the ones most worth writing down.',
       'Incidentes são raros demais para planejar direitos de decisão',
       'A aula argumenta o contrário: decisões com pressa são as que mais vale escrever.')])

cloze('ex-g6ht42hp', 'who-decides', 'easy',
      ('A decision that is consequential and hard to reverse is called a ___-way door.',
       'Uma decisão com consequências e difícil de reverter é chamada de porta de mão ___.'),
      ('The other kind is two-way.', 'O outro tipo é de mão dupla.'),
      [(['one'], ['única', 'unica'])])

mc('ex-gsrgjdx7', 'drill', 'hard',
   ('Renata’s decisions page shows her own name on nine of the last ten lines. Which conclusions does the lesson support? Choose all that apply.',
    'A página de decisões da Renata mostra o nome dela em nove das últimas dez linhas. Quais conclusões a aula sustenta? Marque todas que se aplicam.'),
   ('What does one name on most lines mean?', 'O que significa um nome na maioria das linhas?'),
   [(1, 'The team has less autonomy than she thinks', 'Yes: the lesson says exactly this about a page where every line says “Renata”.',
     'O time tem menos autonomia do que ela acha', 'Sim: a aula diz exatamente isso sobre uma página em que toda linha diz “Renata”.'),
    (1, 'Some two-way doors are probably being decided too far from the work', 'Yes: two-way doors belong close to the work.',
     'Algumas portas de mão dupla provavelmente estão sendo decididas longe demais do trabalho', 'Sim: portas de mão dupla ficam perto do trabalho.'),
    (0, 'She is doing her job well, since a manager should decide most things', 'No: by lessons 3 and 4, that makes her the bottleneck.',
     'Ela está fazendo bem o trabalho, já que gestoras deveriam decidir quase tudo', 'Não: pelas aulas 3 e 4, isso faz dela o gargalo.'),
    (0, 'The page should stop recording who decided', 'No: that column is what revealed the pattern.',
     'A página deveria parar de registrar quem decidiu', 'Não: essa coluna é o que revelou o padrão.')])

quiz('ex-m5f77rn9', 'drill', 'hard',
     ('A director tells a team: “Reduce checkout failures by half this quarter. Here is why it matters, here is what you may not touch, and here is the dashboard.” The team asks which fix to build. Which corner of Kniberg’s grid is the director aiming at, and what is missing?',
      'Uma diretora diz a um time: “Reduzam as falhas de pagamento pela metade neste trimestre. Eis por que importa, eis o que vocês não podem mexer, e eis o painel.” O time pergunta qual correção construir. Em que canto da grade de Kniberg a diretora mira, e o que falta?'),
     ('Is the problem the goal, or the team expecting a solution?', 'O problema é o objetivo, ou o time esperar uma solução?'),
     [(1, 'Aligned autonomy; the team has yet to take up the “how”',
       'Right: the four things alignment needs are there, and the remaining step is the team deciding the method.',
       'Autonomia alinhada; falta o time assumir o “como”',
       'Isso: as quatro coisas que o alinhamento pede estão lá, e o passo que resta é o time decidir o método.'),
      (0, 'High alignment and low autonomy; she should choose the fix',
       'Choosing the fix would move the team to the authoritative corner, which she deliberately avoided.',
       'Alinhamento alto e autonomia baixa; ela deveria escolher a correção',
       'Escolher a correção levaria o time ao canto autoritário, que ela evitou de propósito.'),
      (0, 'Low alignment and high autonomy; the goal is too vague',
       'The goal has a measure, a reason, limits and a dashboard, which is not vague.',
       'Alinhamento baixo e autonomia alta; o objetivo está vago demais',
       'O objetivo tem medida, motivo, limites e painel, o que não é vago.'),
      (0, 'Low on both axes',
       'The goal is explained thoroughly, so alignment is high.',
       'Baixo nos dois eixos',
       'O objetivo está explicado a fundo, então o alinhamento é alto.')])
