"""Lesson 5: one-to-ones, cadence, agenda and notes."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-fyzk9ah4')

quiz('ex-v9vwegh6', 'what-it-is-for', 'easy',
     ('By Grove’s framing, whose meeting is a one-to-one?',
      'Pelo enquadramento de Grove, de quem é a reunião de 1:1?'),
     ('Whose agenda is it?', 'De quem é a pauta?'),
     [(1, 'The report’s',
       'Right: the agenda is theirs, and the manager makes room for what they bring.',
       'Da pessoa liderada',
       'Isso: a pauta é dela, e a gestora abre espaço para o que ela traz.'),
      (0, 'The manager’s, since the manager calls it and runs it every week',
       'The manager may book it; Grove’s point is that it exists for what the report brings.',
       'Da gestora, que marca e conduz a reunião toda semana',
       'A gestora pode marcar; o ponto de Grove é que ela existe para o que a pessoa traz.'),
      (0, 'Both equally, alternating weeks',
       'There is no alternation; the person’s topics come first every time.',
       'Das duas igualmente, alternando semanas',
       'Não há alternância; os assuntos da pessoa vêm primeiro toda vez.'),
      (0, 'The team’s, as a summary of its week',
       'A team summary is status, which belongs elsewhere.',
       'Do time, como um resumo da semana',
       'Um resumo do time é status, que tem outra casa.')])

quiz('ex-2jztjvrp', 'what-it-is-for', 'medium',
     ('Why does status not belong in a one-to-one?',
      'Por que status não pertence a uma 1:1?'),
     ('Where else can a ticket’s state be found?', 'Onde mais dá para achar o estado de um ticket?'),
     [(1, 'It has a better home in the tracker and the stand-up',
       'Right: the meeting is for what can be found nowhere else, and status can be found by looking.',
       'Tem casa melhor no quadro e na daily',
       'Isso: a reunião é para o que não se acha em outro lugar, e status se acha olhando.'),
      (0, 'Talking about work in private is against most companies’ policies',
       'No policy forbids it; it is a question of what the meeting is uniquely good for.',
       'Falar de trabalho em particular vai contra a política da maioria das empresas',
       'Nenhuma política proíbe; é uma questão do que só essa reunião faz bem.'),
      (0, 'Because people lie about status in private',
       'Nothing suggests that; the issue is waste, not honesty.',
       'Porque as pessoas mentem sobre status em particular',
       'Nada sugere isso; a questão é desperdício, não honestidade.'),
      (0, 'Status takes too long to explain and would leave no time for anything else in thirty minutes',
       'Length is not the reason; status crowds out the conversations with no other home.',
       'Status leva tempo demais para explicar e não deixaria tempo para mais nada em trinta minutos',
       'Duração não é o motivo; status expulsa as conversas que não têm outra casa.')])

mc('ex-zk5tszdt', 'what-it-is-for', 'medium',
   ('Which reasons does the lesson give for one-to-ones drifting into status? Choose all that apply.',
    'Que motivos a aula dá para as 1:1 derivarem para status? Marque todos que se aplicam.'),
   ('Three reasons.', 'Três motivos.'),
   [(1, 'Status is safe for both people', 'Yes: nobody has to raise anything awkward.',
     'Status é seguro para as duas pessoas', 'Sim: ninguém precisa levantar nada desconfortável.'),
    (1, 'Nobody prepared, and the manager fills the silence', 'Yes: the easiest filler is a work question.',
     'Ninguém se preparou, e a gestora preenche o silêncio', 'Sim: o recheio mais fácil é uma pergunta de trabalho.'),
    (1, 'The manager owns the agenda by default', 'Yes: the meeting follows the manager’s interests, which lean to delivery.',
     'A gestora é dona da pauta por padrão', 'Sim: a reunião segue os interesses da gestora, que pendem para a entrega.'),
    (0, 'Companies require written status every week', 'No such requirement appears in the lesson.',
     'As empresas exigem status por escrito toda semana', 'Essa exigência não aparece na aula.'),
    (0, 'Engineers prefer not to talk about themselves', 'The lesson does not blame the engineers; Paula had plenty to raise once there was room.',
     'Engenheiros preferem não falar de si', 'A aula não culpa os engenheiros; a Paula tinha muito a levantar quando houve espaço.')])

quiz('ex-m8e9gyxf', 'what-it-is-for', 'hard',
     ('Paula’s first topic, in week three, was that she was the only person who understood the reminder service. What does the lesson draw from it having waited a year?',
      'O primeiro assunto da Paula, na terceira semana, foi ser a única pessoa que entendia o serviço de lembretes. O que a aula tira de ele ter esperado um ano?'),
     ('Was the problem new?', 'O problema era novo?'),
     [(1, 'There had been no meeting where it fitted',
       'Right: the topic existed all along, and the status meeting had no room for it.',
       'Não havia reunião onde ele coubesse',
       'Isso: o assunto existia o tempo todo, e a reunião de status não tinha espaço para ele.'),
      (0, 'Paula did not trust her previous manager, and would not have trusted any manager she had at the time',
       'The lesson attributes the silence to the meeting’s shape, not to Paula’s trust in managers in general.',
       'A Paula não confiava no gestor anterior, e não teria confiado em nenhum gestor que tivesse na época',
       'A aula atribui o silêncio ao formato da reunião, não à confiança da Paula em gestores em geral.'),
      (0, 'The problem had only just appeared',
       'It had been true for a year, which is the point.',
       'O problema tinha acabado de aparecer',
       'Ele era verdade havia um ano, que é justamente o ponto.'),
      (0, 'The reminder service was a minor concern',
       'Being unable to take a week off is not minor, and it is also a risk for the team.',
       'O serviço de lembretes era uma preocupação menor',
       'Não poder tirar uma semana de folga não é menor, e também é um risco para o time.')])

quiz('ex-2b5yw1st', 'cadence', 'easy',
     ('Which is worse, by the lesson?',
      'Qual é pior, pela aula?'),
     ('Regular and reliable.', 'Regular e confiável.'),
     [(1, 'A weekly one-to-one cancelled every other week',
       'Right: it is less reliable than a fortnightly meeting that always runs, and reliability is what builds trust in it.',
       'Uma 1:1 semanal cancelada semana sim, semana não',
       'Isso: ela é menos confiável que uma quinzenal que sempre acontece, e confiabilidade é o que cria confiança nela.'),
      (0, 'A fortnightly one-to-one that always runs',
       'That is the better of the two, regular and reliable.',
       'Uma 1:1 quinzenal que sempre acontece',
       'Essa é a melhor das duas, regular e confiável.'),
      (0, 'A forty-five-minute one-to-one every two weeks with an experienced engineer on familiar work',
       'That is the table’s suggestion for exactly that situation.',
       'Uma 1:1 de quarenta e cinco minutos a cada duas semanas com uma pessoa experiente em trabalho familiar',
       'É a sugestão da tabela exatamente para essa situação.'),
      (0, 'A weekly thirty-minute one-to-one',
       'That is a common and sound default.',
       'Uma 1:1 semanal de trinta minutos',
       'É um padrão comum e sólido.')])

match('ex-nwsq04j3', 'cadence', 'medium',
      ('Match each situation with the cadence the lesson’s table suggests.',
       'Ligue cada situação à cadência que a tabela da aula sugere.'),
      ('Frequent signal where the person needs it.', 'Sinal frequente onde a pessoa precisa dele.'),
      [('a new hire in their first three months', 'weekly, thirty minutes',
        'uma contratação nova nos três primeiros meses', 'semanal, trinta minutos'),
       ('an experienced person on familiar work', 'every two weeks, forty-five minutes',
        'uma pessoa experiente em trabalho familiar', 'a cada duas semanas, quarenta e cinco minutos'),
       ('somebody on an improvement plan', 'weekly, for the length of the plan',
        'alguém num plano de melhoria', 'semanal, pela duração do plano')],
      [('monthly, an hour', 'mensal, uma hora')])

num('ex-vvh83t1w', 'cadence', 'easy',
    ('Renata has seven reports and meets each weekly for thirty minutes. How many hours a week is that?',
     'A Renata tem sete pessoas e se reúne com cada uma toda semana por trinta minutos. Quantas horas por semana dá?'),
    ('Seven half-hours.', 'Sete meias horas.'),
    3.5, 0, ('hours', 'horas'), (['hour', 'h'], ['hora', 'h']))

quiz('ex-qv3sjsm1', 'cadence', 'medium',
     ('Why does the lesson say hard feedback in week two is usually heard as an attack?',
      'Por que a aula diz que um feedback duro na segunda semana costuma ser ouvido como ataque?'),
     ('Look at the shape over months.', 'Olhe o formato ao longo dos meses.'),
     [(1, 'The relationship cannot carry it yet',
       'Right: feedback in both directions becomes possible as trust builds.',
       'A relação ainda não aguenta',
       'Isso: feedback nos dois sentidos se torna possível conforme a confiança cresce.'),
      (0, 'Feedback is only allowed after the first review cycle at most companies, including Caju',
       'No such rule appears; the reason is the relationship.',
       'Feedback só é permitido depois do primeiro ciclo de avaliação na maioria das empresas, inclusive na Caju',
       'Essa regra não aparece; o motivo é a relação.'),
      (0, 'New managers give feedback badly',
       'The point holds for any manager new to the relationship, however skilled.',
       'Gestoras novas dão feedback mal',
       'O ponto vale para qualquer gestora nova na relação, por mais habilidosa.'),
      (0, 'Week two is when people are most defensive about their work',
       'The lesson ties it to trust, not to a particular week of the calendar.',
       'A segunda semana é quando as pessoas estão mais defensivas sobre o trabalho',
       'A aula liga isso à confiança, não a uma semana específica do calendário.')])

quiz('ex-39846e97', 'cadence', 'medium',
     ('Thiago offered to skip his one-to-one because he had nothing to discuss. Renata asked for ten minutes. What happened?',
      'O Thiago se ofereceu para pular a 1:1 porque não tinha nada para discutir. A Renata pediu dez minutos. O que aconteceu?'),
     ('Nothing to discuss is not always nothing.', 'Nada para discutir nem sempre é nada.'),
     [(1, 'He mentioned he was struggling with on-call',
       'Right: the short meeting surfaced something he had not thought worth raising.',
       'Ele contou que estava com dificuldade no plantão',
       'Isso: a reunião curta revelou algo que ele não achava que valia levantar.'),
      (0, 'They ended after two minutes, as he had said there was nothing to talk about',
       'The lesson tells the story because something did come up.',
       'Terminaram depois de dois minutos, já que ele tinha dito que não havia nada para conversar',
       'A aula conta a história porque algo apareceu.'),
      (0, 'He complained that she had not respected his time',
       'Nothing like that happens in the story.',
       'Ele reclamou que ela não respeitou o tempo dele',
       'Nada disso acontece na história.'),
      (0, 'She used the slot to ask about his tickets',
       'That would be status, which she avoids in one-to-ones.',
       'Ela usou o horário para perguntar dos tickets dele',
       'Isso seria status, que ela evita nas 1:1.')])

quiz('ex-d27jre2k', 'whose-agenda', 'easy',
     ('In the shared document, which topics are discussed first?',
      'No documento compartilhado, quais assuntos são discutidos primeiro?'),
     ('Who has fewer other ways to reach whom?', 'Quem tem menos outras formas de chegar a quem?'),
     [(1, 'The person’s',
       'Right: the manager has other ways to reach the person, and the person has fewer ways to reach the manager.',
       'Os da pessoa',
       'Isso: a gestora tem outras formas de chegar à pessoa, e a pessoa tem menos formas de chegar à gestora.'),
      (0, 'The manager’s, because they are usually more urgent',
       'Urgent things go to a message; the order puts the person first.',
       'Os da gestora, porque costumam ser mais urgentes',
       'Coisas urgentes vão por mensagem; a ordem põe a pessoa primeiro.'),
      (0, 'Whichever topic was added to the document first during the week, regardless of who added it',
       'The order is by whose topic it is, not by when it was added.',
       'O assunto que entrou primeiro no documento durante a semana, não importa quem o pôs',
       'A ordem é por de quem é o assunto, não por quando entrou.'),
      (0, 'The actions from last time',
       'Actions matter, and lesson 7 is about them, but they do not open the meeting.',
       'As ações da última vez',
       'Ações importam, e a aula 7 trata delas, mas não abrem a reunião.')])

quiz('ex-xxnwx0k4', 'whose-agenda', 'medium',
     ('Renata needs to know whether calendar sync will be ready for a meeting next week. Where does the lesson say she asks?',
      'A Renata precisa saber se a sincronização de calendário vai estar pronta para uma reunião na semana que vem. Onde a aula diz que ela pergunta?'),
     ('It is status.', 'É status.'),
     [(1, 'In the ticket or a message, the day she needs it',
       'Right: putting status in the one-to-one document invites the meeting to drift back.',
       'No ticket ou numa mensagem, no dia em que precisa',
       'Isso: pôr status no documento da 1:1 convida a reunião a derivar de volta.'),
      (0, 'In “my topics” in the shared document',
       'That section is for feedback and context, not status.',
       'Em “meus assuntos” no documento compartilhado',
       'Essa seção é para feedback e contexto, não status.'),
      (0, 'At the start of the one-to-one',
       'The meeting opens with the person’s topics, and status does not belong in it.',
       'No começo da 1:1',
       'A reunião abre com os assuntos da pessoa, e status não pertence a ela.'),
      (0, 'In a team meeting, in front of everybody, so the whole team hears the answer',
       'A team meeting is not wrong for status, but the lesson’s answer is the ticket or a message.',
       'Numa reunião do time, na frente de todos, para o time inteiro ouvir a resposta',
       'Uma reunião do time não é errada para status, mas a resposta da aula é o ticket ou uma mensagem.')])

quiz('ex-7yvtx05s', 'whose-agenda', 'hard',
     ('Marcos’s section stayed empty for six weeks. What did asking about it directly reveal?',
      'A seção do Marcos ficou vazia por seis semanas. O que perguntar diretamente revelou?'),
     ('The empty section was information.', 'A seção vazia era informação.'),
     [(1, 'His previous manager had used one-to-ones to go through his mistakes',
       'Right: he had learnt that the meeting was dangerous, and the silence was the result.',
       'O gestor anterior usava as 1:1 para repassar os erros dele',
       'Isso: ele tinha aprendido que a reunião era perigosa, e o silêncio era o resultado.'),
      (0, 'He was content',
       'He said the meeting was not useful to him, which is different.',
       'Ele estava contente',
       'Ele disse que a reunião não servia para ele, o que é diferente.'),
      (0, 'He did not know what the document was for',
       'That is a common cause, but not the one he gave.',
       'Ele não sabia para que servia o documento',
       'É uma causa comum, mas não a que ele deu.'),
      (0, 'He wanted fewer meetings',
       'He said nothing about frequency; it was about what the meeting had been used for.',
       'Ele queria menos reuniões',
       'Ele não falou de frequência; era sobre para que a reunião tinha sido usada.')])

quiz('ex-ras70293', 'what-gets-written', 'easy',
     ('Which of these is an action in the lesson’s sense?',
      'Qual destes é uma ação no sentido da aula?'),
     ('An owner and a date.', 'Um dono e uma data.'),
     [(1, 'Renata asks the platform team about a second rota by Friday',
       'Right: it has an owner, a thing to do and a date.',
       'Renata pergunta ao time de plataforma sobre uma segunda escala até sexta',
       'Isso: tem dono, uma coisa a fazer e data.'),
      (0, 'Look into the on-call rota',
       'No owner and no date; the lesson uses this exact line as the bad example.',
       'Ver a escala de plantão',
       'Sem dono e sem data; a aula usa essa linha exata como mau exemplo.'),
      (0, 'Discussed on-call, which has been hard for Thiago',
       'That is a note, not an action.',
       'Conversamos sobre o plantão, que está difícil para o Thiago',
       'Isso é uma nota, não uma ação.'),
      (0, 'On-call to be improved',
       'Passive, with no owner and no date.',
       'Plantão a ser melhorado',
       'Passiva, sem dono e sem data.')])

quiz('ex-t6vj908d', 'what-gets-written', 'medium',
     ('Which private note breaks the lesson’s rule?',
      'Qual nota privada quebra a regra da aula?'),
     ('Write as if the person might read it.', 'Escreva como se a pessoa pudesse ler.'),
     [(1, '“Probably going through a divorce, explains a lot”',
       'Right: speculation about somebody’s private life has no business on any page.',
       '“Provavelmente passando por um divórcio, explica muita coisa”',
       'Isso: especulação sobre a vida privada de alguém não tem lugar em página nenhuma.'),
      (0, '“Seemed distracted again, third week running; ask if something is going on”',
       'The lesson calls this one fair: an observation and an intended action.',
       '“Parecia distraído de novo, terceira semana seguida; perguntar se está acontecendo alguma coisa”',
       'A aula chama esta de justa: uma observação e uma ação pretendida.'),
      (0, '“Thursdays flexible until March”',
       'This is the barest form of an agreed adjustment, which is what the lesson recommends.',
       '“Quintas flexíveis até março”',
       'É a forma mais enxuta de um ajuste combinado, que é o que a aula recomenda.'),
      (0, '“Away from the 12th to the 16th”',
       'A family matter reduced to what changes at work, as the table suggests.',
       '“Fora do dia 12 ao 16”',
       'Um assunto de família reduzido ao que muda no trabalho, como a tabela sugere.')])

quiz('ex-dten480a', 'what-gets-written', 'medium',
     ('What does Renata tell each person, in one sentence, in the first meeting?',
      'O que a Renata diz a cada pessoa, numa frase, na primeira reunião?'),
     ('People decide what to say by what happens to it afterwards.', 'As pessoas decidem o que dizer pelo que acontece com aquilo depois.'),
     [(1, 'What they write stays between them, and she will say first if it must go further',
       'Right: that sentence is what makes the rest of the meeting possible.',
       'O que escrevem fica entre elas, e ela avisa antes se precisar ir além',
       'Isso: essa frase é o que torna o resto da reunião possível.'),
      (0, 'That HR will read the notes every quarter to check on progress',
       'Nobody else reads the document by default.',
       'Que o RH vai ler as notas a cada trimestre para acompanhar o progresso',
       'Ninguém mais lê o documento por padrão.'),
      (0, 'That nothing they say will ever leave the room, under any circumstances at all',
       'She does not promise that, because harassment or a performance process may need to go further, and she says she will tell them first.',
       'Que nada do que disserem vai sair da sala, em nenhuma circunstância',
       'Ela não promete isso, porque assédio ou um processo de desempenho podem precisar ir além, e ela diz que avisa antes.'),
      (0, 'That the notes will be used for their review',
       'Notes do become evidence later, but that is not the sentence she says, and it would shut the meeting down.',
       'Que as notas vão ser usadas na avaliação',
       'As notas viram evidência depois, mas não é a frase que ela diz, e ela fecharia a reunião.')])

quiz('ex-qhvgnr4m', 'drill', 'hard',
     ('A manager’s one-to-one notes for an engineer say “all good” every week for six months. The engineer is now being considered for promotion. What is the weakness the lesson points to?',
      'As notas de 1:1 de uma gestora sobre um engenheiro dizem “tudo certo” toda semana por seis meses. Ele agora está sendo considerado para promoção. Qual fraqueza a aula aponta?'),
     ('Notes become evidence.', 'Notas viram evidência.'),
     [(1, 'The notes give the promotion case no evidence of anything specific',
       'Right: a case that cites six months of “doing great” is weak; specific notes are the evidence.',
       'As notas não dão ao caso de promoção evidência de nada específico',
       'Isso: um caso que cita seis meses de “indo muito bem” é fraco; notas específicas são a evidência.'),
      (0, 'Positive notes always count against a promotion',
       'Positive notes are fine; vague ones are what fail.',
       'Notas positivas sempre contam contra uma promoção',
       'Notas positivas tudo bem; as vagas é que falham.'),
      (0, 'The engineer should have written the notes',
       'The manager writes them and the engineer agrees with them.',
       'O engenheiro deveria ter escrito as notas',
       'A gestora escreve e o engenheiro concorda.'),
      (0, 'Notes from one-to-ones may not be used in promotion cases',
       'Lesson 12 uses them for exactly that.',
       'Notas de 1:1 não podem ser usadas em casos de promoção',
       'A aula 12 as usa exatamente para isso.')])
