"""Lesson 6: the questions that get past "everything is fine"."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-w35bc900')

quiz('ex-jgf7xekb', 'why-fine', 'easy',
     ('Why does the lesson call “fine” the correct reply to “how’s it going?”',
      'Por que a aula chama “tudo bem” de resposta correta a “como estão as coisas?”'),
     ('What kind of question is it?', 'Que tipo de pergunta é essa?'),
     [(1, 'The question is a greeting with no edges, and “fine” is its standard reply',
       'Right: nobody has been asked anything yet, so a summary is an accurate answer.',
       'A pergunta é um cumprimento sem contornos, e “tudo bem” é a resposta padrão',
       'Isso: ninguém perguntou nada ainda, então um resumo é uma resposta correta.'),
      (0, 'People always lie to their managers',
       'The lesson says “fine” is not a lie; it is an honest summary of a vague question.',
       'As pessoas sempre mentem para a gestão',
       'A aula diz que “tudo bem” não é mentira; é um resumo honesto de uma pergunta vaga.'),
      (0, 'Things usually are fine',
       'Sometimes they are, but that is not why the reply is correct; it would be the same answer either way.',
       'As coisas geralmente estão bem',
       'Às vezes estão, mas não é por isso que a resposta é correta; ela seria a mesma de qualquer jeito.'),
      (0, 'Engineers prefer short answers in meetings',
       'Nothing in the lesson is about engineers’ preferences.',
       'Engenheiros preferem respostas curtas em reuniões',
       'Nada na aula é sobre preferências de engenheiros.')])

quiz('ex-pxtxgzmq', 'why-fine', 'medium',
     ('Which of the three reasons for “fine” does not go away with better wording?',
      'Qual dos três motivos para “tudo bem” não some com uma redação melhor?'),
     ('Who writes the review?', 'Quem escreve a avaliação?'),
     [(1, 'The manager’s power',
       'Right: the power is real even when the manager is kind, and wording cannot remove it.',
       'O poder da gestora',
       'Isso: o poder é real mesmo quando a gestora é gentil, e a redação não o remove.'),
      (0, 'The question is a greeting',
       'Better wording turns the greeting into a real question.',
       'A pergunta é um cumprimento',
       'Uma redação melhor transforma o cumprimento numa pergunta de verdade.'),
      (0, 'The question has no edges',
       'Edges are exactly what better wording adds.',
       'A pergunta não tem contornos',
       'Contornos são exatamente o que uma redação melhor acrescenta.'),
      (0, 'The meeting is too short to say anything that matters, however the question is phrased',
       'Not one of the three reasons; the lesson’s third reason is the manager’s power.',
       'A reunião é curta demais para dizer qualquer coisa importante, seja qual for a pergunta',
       'Não é um dos três motivos; o terceiro motivo da aula é o poder da gestora.')])

quiz('ex-13b6jwas', 'why-fine', 'medium',
     ('Thiago said on-call was fine. What did “fine” describe, and what did it leave out?',
      'O Thiago disse que o plantão estava bem. O que o “tudo bem” descrevia, e o que deixava de fora?'),
     ('Pages were answered and incidents resolved.', 'Os chamados eram atendidos e os incidentes resolvidos.'),
     [(1, 'The outcome, which was working, and left out what that outcome was costing him every week',
       'Right: on-call was functioning; the sleepless nights and the unexplained alert were the cost nobody asked about.',
       'O resultado, que funcionava, e deixava de fora o que esse resultado custava a ele toda semana',
       'Isso: o plantão funcionava; as noites mal dormidas e o alerta sem explicação eram o custo que ninguém perguntou.'),
      (0, 'Nothing true; he was hiding a failure',
       'Nothing he said was false; incidents were resolved.',
       'Nada verdadeiro; ele escondia uma falha',
       'Nada do que ele disse era falso; os incidentes eram resolvidos.'),
      (0, 'The team’s on-call, and left out his own week, which had gone badly in every respect',
       'His own pages were answered; what was missing was the cost, not a failed week.',
       'O plantão do time, e deixava de fora a semana dele, que tinha ido mal em todos os sentidos',
       'Os chamados dele foram atendidos; faltava o custo, não uma semana fracassada.'),
      (0, 'His feelings, and left out the facts',
       'It was the other way round: the facts were there and the cost was missing.',
       'Os sentimentos dele, e deixava de fora os fatos',
       'Era o contrário: os fatos estavam lá e faltava o custo.')])

mc('ex-c2be2hys', 'why-fine', 'medium',
   ('Which three things does the lesson say a manager controls and the person does not? Choose all that apply.',
    'Quais três coisas a aula diz que a gestora controla e a pessoa não? Marque todas que se aplicam.'),
   ('Before, during and after the answer.', 'Antes, durante e depois da resposta.'),
   [(1, 'The question', 'Yes.', 'A pergunta', 'Sim.'),
    (1, 'The reaction to the answer', 'Yes: a bad reaction teaches the person not to raise things.',
     'A reação à resposta', 'Sim: uma reação ruim ensina a pessoa a não levantar coisas.'),
    (1, 'What happens afterwards', 'Yes: lesson 7 is about it.', 'O que acontece depois', 'Sim: a aula 7 trata disso.'),
    (0, 'How open the person is by nature', 'No: the lesson rejects putting the work on the person’s openness.',
     'Quão aberta a pessoa é por natureza', 'Não: a aula rejeita pôr o trabalho na abertura da pessoa.'),
    (0, 'Whether there is a problem to raise', 'No: the manager controls how easy it is to raise one, not whether one exists.',
     'Se existe um problema para levantar', 'Não: a gestora controla quão fácil é levantar um, não se ele existe.')])

quiz('ex-ngwwyatw', 'better-questions', 'easy',
     ('Which question has edges, in the lesson’s sense?',
      'Qual pergunta tem contornos, no sentido da aula?'),
     ('Something to search for rather than to summarise.', 'Algo para procurar, e não para resumir.'),
     [(1, '“What was the most frustrating part of last week?”',
       'Right: a week, and “most”, give the person something specific to look for.',
       '“Qual foi a parte mais frustrante da semana passada?”',
       'Isso: uma semana, e o “mais”, dão à pessoa algo específico para procurar.'),
      (0, '“How are things?”',
       'No edges at all; it invites a summary.',
       '“Como vão as coisas?”',
       'Sem contorno nenhum; convida a um resumo.'),
      (0, '“Is everything OK with you?”',
       'A yes-or-no question with nothing to search for.',
       '“Está tudo bem com você?”',
       'Uma pergunta de sim ou não sem nada para procurar.'),
      (0, '“Anything you want to tell me about work, home, the team, the product or your career?”',
       'A long list is still no edge; the person answers the easiest one, or none.',
       '“Algo que queira me contar sobre trabalho, casa, o time, o produto ou a sua carreira?”',
       'Uma lista longa continua sem contorno; a pessoa responde a mais fácil, ou nenhuma.')])

quiz('ex-2eezdthf', 'better-questions', 'medium',
     ('In a scaled question, which part does the lesson say does the work?',
      'Numa pergunta em escala, que parte a aula diz que faz o trabalho?'),
     ('People use the scale differently.', 'As pessoas usam a escala de jeitos diferentes.'),
     [(1, 'The follow-up: what would make it one higher',
       'Right: the number alone says little; the follow-up asks for something small and concrete.',
       'O seguimento: o que faria subir um ponto',
       'Isso: o número sozinho diz pouco; o seguimento pede algo pequeno e concreto.'),
      (0, 'The number, which can be compared across the team every week to spot trends early',
       'People use the scale differently, so numbers do not compare well across people.',
       'O número, que pode ser comparado no time toda semana para notar tendências cedo',
       'As pessoas usam a escala de jeitos diferentes, então números não se comparam bem entre pessoas.'),
      (0, 'Choosing a scale of ten rather than five',
       'The size of the scale is not what the lesson discusses.',
       'Escolher uma escala de dez em vez de cinco',
       'O tamanho da escala não é o que a aula discute.'),
      (0, 'Asking it at the start of the meeting',
       'Placement is not the point; the follow-up is.',
       'Fazê-la no começo da reunião',
       'A posição não é o ponto; o seguimento é.')])

match('ex-hntaqvye', 'better-questions', 'medium',
      ('Match each question that closes a conversation with what is wrong with it.',
       'Ligue cada pergunta que fecha a conversa ao que há de errado nela.'),
      ('Four ways to close it.', 'Quatro jeitos de fechar.'),
      [('“Why did you take that approach?”', 'heard as an accusation even when it is curiosity',
        '“Por que você fez desse jeito?”', 'ouvida como acusação mesmo quando é curiosidade'),
       ('“You’re fine with the rota, right?”', 'the only answer is the one inside it',
        '“Você está de boa com a escala, né?”', 'a única resposta é a que está dentro dela'),
       ('“Have you thought about pairing with Diego?”', 'a suggestion wearing a question mark',
        '“Já pensou em parear com o Diego?”', 'uma sugestão vestida de ponto de interrogação'),
       ('“How’s on-call, and the calendar work, and the new process?”', 'the person answers the easiest one',
        '“Como está o plantão, e o calendário, e o processo novo?”', 'a pessoa responde a mais fácil')],
      [('it has edges in time', 'tem contornos no tempo')])

quiz('ex-wm9sg2rg', 'better-questions', 'medium',
     ('Why does the lesson suggest asking about the team rather than the person, sometimes?',
      'Por que a aula sugere às vezes perguntar sobre o time em vez de sobre a pessoa?'),
     ('A way in.', 'Uma entrada.'),
     [(1, 'Some people find it easier to report a problem as everybody’s',
       'Right: the answer often turns out to be their own, and the question gave them a way in.',
       'Algumas pessoas acham mais fácil relatar um problema como sendo de todos',
       'Isso: a resposta muitas vezes acaba sendo dela mesma, e a pergunta lhe deu uma entrada.'),
      (0, 'To find out who is causing problems on the team',
       'It is not a way to collect information about colleagues.',
       'Para descobrir quem está causando problemas no time',
       'Não é um jeito de recolher informação sobre colegas.'),
      (0, 'Because personal questions are inappropriate at work',
       'Several questions in the bank are personal, offered carefully.',
       'Porque perguntas pessoais são inadequadas no trabalho',
       'Várias perguntas do banco são pessoais, oferecidas com cuidado.'),
      (0, 'Because team problems matter more than individual ones in a company of ninety engineers',
       'The lesson does not rank them; it is about making a problem easier to raise.',
       'Porque problemas do time importam mais do que os individuais numa empresa de noventa engenheiros',
       'A aula não os hierarquiza; é sobre tornar um problema mais fácil de levantar.')])

quiz('ex-gf0mefc6', 'better-questions', 'hard',
     ('A manager asks, “What’s one thing I could do differently that would help you?” and gets “Nothing, you’re great.” What does the lesson suggest?',
      'Uma gestora pergunta “Qual é uma coisa que eu poderia fazer diferente que ajudaria você?” e ouve “Nada, você é ótima.” O que a aula sugere?'),
     ('The hardest question to answer honestly.', 'A pergunta mais difícil de responder com honestidade.'),
     [(1, 'Keep asking regularly, and expect honest answers after a few months',
       'Right: the power gap makes this the hardest question, and honest answers come with time and repetition.',
       'Continuar perguntando com regularidade, e esperar respostas honestas depois de alguns meses',
       'Isso: a diferença de poder faz dela a pergunta mais difícil, e as respostas honestas vêm com tempo e repetição.'),
      (0, 'Stop asking, since the answer was clear',
       'One answer to the hardest question is not a verdict.',
       'Parar de perguntar, já que a resposta foi clara',
       'Uma resposta à pergunta mais difícil não é um veredito.'),
      (0, 'Insist until the person names something',
       'Insisting makes it a demand, which is the opposite of an easy way in.',
       'Insistir até a pessoa nomear algo',
       'Insistir transforma em exigência, o oposto de uma entrada fácil.'),
      (0, 'Ask the person’s colleagues instead',
       'That goes around the person and is not in the lesson.',
       'Perguntar aos colegas da pessoa',
       'Isso contorna a pessoa e não está na aula.')])

quiz('ex-npybtes0', 'listening', 'easy',
     ('Thiago mentions the confusing alert. Renata replies, “I’ll get Diego to write a runbook.” Which of the three conversation-enders is that?',
      'O Thiago menciona o alerta confuso. A Renata responde: “Vou pedir ao Diego para escrever um runbook.” Qual dos três jeitos de encerrar a conversa é esse?'),
     ('Helpful, and too early.', 'Útil, e cedo demais.'),
     [(1, 'Fixing',
       'Right: it closes the topic before the sleep and the reluctance to speak have come out.',
       'Consertar',
       'Isso: fecha o assunto antes de o sono e a hesitação em falar aparecerem.'),
      (0, 'Explaining why on-call is hard for everybody at first',
       'That is explaining; here she offered a fix.',
       'Explicar por que o plantão é difícil para todo mundo no começo',
       'Isso é explicar; aqui ela ofereceu um conserto.'),
      (0, 'Moving on',
       'She engaged with it; moving on would be “OK, good to know”.',
       'Seguir em frente',
       'Ela se envolveu com o assunto; seguir em frente seria “ok, bom saber”.'),
      (0, 'Saying it back',
       'Saying it back is one of the habits that keep the conversation open.',
       'Devolver',
       'Devolver é um dos hábitos que mantêm a conversa aberta.')])

order('ex-ecaceer9', 'listening', 'medium',
      ('Put the response the lesson recommends to hard feedback about you in order.',
       'Ponha em ordem a resposta que a aula recomenda para um feedback difícil sobre você.'),
      ('Short, and the explanation waits.', 'Curta, e a explicação espera.'),
      [('Thank them', 'Agradecer'),
       ('Ask one question to understand it', 'Fazer uma pergunta para entender'),
       ('Say what you will do with it', 'Dizer o que vai fazer com aquilo'),
       ('Explain, if needed, about a week later', 'Explicar, se precisar, uma semana depois')],
      ('Explaining first is the natural reaction, and it teaches the person not to say such things again.',
       'Explicar primeiro é a reação natural, e ensina a pessoa a não dizer essas coisas de novo.'))

quiz('ex-tmppdkyj', 'listening', 'medium',
     ('Why does the lesson prefer “tell me more” to a specific follow-up at first?',
      'Por que a aula prefere “me conta mais” a um seguimento específico no começo?'),
     ('Whose guess does a specific follow-up carry?', 'O palpite de quem um seguimento específico carrega?'),
     [(1, 'It steers the person towards the manager’s guess',
       'Right: an open prompt carries no assumption about where the answer should go.',
       'Ela empurra a pessoa para o palpite da gestora',
       'Isso: um convite aberto não carrega suposição sobre para onde a resposta deve ir.'),
      (0, 'It is quicker',
       'It is not about speed.',
       'É mais rápido',
       'Não é sobre velocidade.'),
      (0, 'Specific questions are against the lesson’s rules',
       'The previous section is all about specific questions; the order matters here.',
       'Perguntas específicas vão contra as regras da aula',
       'A seção anterior inteira é sobre perguntas específicas; aqui importa a ordem.'),
      (0, 'Because people answer open prompts with shorter answers, which keeps the meeting on time',
       'The aim is the second and third answer, not a shorter meeting.',
       'Porque as pessoas respondem convites abertos com respostas mais curtas, o que mantém o horário',
       'O objetivo é a segunda e a terceira resposta, não uma reunião mais curta.')])

quiz('ex-yzys7q3z', 'listening', 'medium',
     ('Renata summarises: “So the alert was confusing, and the worse part was not knowing who to call.” Thiago says, “Not exactly, I didn’t want to wake anybody.” What did saying it back achieve?',
      'A Renata resume: “Então o alerta era confuso, e a pior parte era não saber para quem ligar.” O Thiago diz: “Não é bem isso, eu não queria acordar ninguém.” O que devolver conseguiu?'),
     ('What did Thiago do next?', 'O que o Thiago fez em seguida?'),
     [(1, 'A chance to correct her',
       'Right: the correction is the real problem, which a fix for the alert would have missed.',
       'Uma chance de corrigi-la',
       'Isso: a correção é o problema de verdade, que um conserto do alerta teria perdido.'),
      (0, 'It showed she was right all along',
       'He corrected her, which is the point of saying it back.',
       'Mostrou que ela estava certa desde o começo',
       'Ele a corrigiu, que é o objetivo de devolver.'),
      (0, 'It ended the topic politely so the meeting could move on to the next item on the agenda',
       'Saying it back keeps the topic open.',
       'Encerrou o assunto com educação para a reunião passar ao próximo item da pauta',
       'Devolver mantém o assunto aberto.'),
      (0, 'Nothing; summaries waste time',
       'The correction is what it bought.',
       'Nada; resumos desperdiçam tempo',
       'A correção foi o que ele trouxe.')])

cloze('ex-8rkrm46e', 'listening', 'easy',
      ('After the first answer, Renata waits by counting to ___ in her head.',
       'Depois da primeira resposta, a Renata espera contando até ___ de cabeça.'),
      ('A few seconds longer than feels comfortable.', 'Alguns segundos a mais do que parece confortável.'),
      [(['five', '5'], ['cinco', '5'])])

quiz('ex-dyy1w9ks', 'drill', 'hard',
     ('An engineer says in a one-to-one: “The new deploy process is fine, I guess.” Which reply follows the lesson best?',
      'Uma engenheira diz numa 1:1: “O processo novo de deploy está ok, acho.” Qual resposta segue melhor a aula?'),
     ('Edges, and no direction yet.', 'Contornos, e ainda sem direção.'),
     [(1, '“What annoyed you most about it last week?”',
       'Right: a question with edges, asking for an event, with no fix and no explanation yet.',
       '“O que mais irritou semana passada?”',
       'Isso: uma pergunta com contornos, pedindo um acontecimento, sem conserto e sem explicação ainda.'),
      (0, '“Great, glad it’s working. Next topic?”',
       'Moving on, after a “fine” with a hedge on the end.',
       '“Ótimo, que bom que funciona. Próximo assunto?”',
       'Seguir em frente, depois de um “ok” com um “acho” no fim.'),
      (0, '“It takes some getting used to; everybody struggled with the old one too.”',
       'Explaining, which tells her the problem was already known.',
       '“Leva um tempo para acostumar; todo mundo sofreu com o antigo também.”',
       'Explicar, o que diz a ela que o problema já era conhecido.'),
      (0, '“Why do you only guess? Is something wrong with it?”',
       'A “why” about her choice of words, heard as an accusation.',
       '“Por que só acha? Tem algo errado com ele?”',
       'Um “por quê” sobre a escolha de palavras dela, ouvido como acusação.')])
