"""Lesson 7: follow-through after the one-to-one."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-erjww605')

quiz('ex-k6nab87j', 'the-promise-list', 'easy',
     ('Why did Paula never raise the reminder-service problem again after Renata said she would “think about” it?',
      'Por que a Paula nunca mais levantou o problema do serviço de lembretes depois que a Renata disse que ia “pensar” nele?'),
     ('Five weeks with nothing beside the line.', 'Cinco semanas sem nada ao lado da linha.'),
     [(1, 'The silence had answered her',
       'Right: with no date and no first step, nothing happened, and the absence told Paula what she needed to know.',
       'O silêncio já tinha respondido',
       'Isso: sem data e sem primeiro passo, nada aconteceu, e a ausência disse à Paula o que ela precisava saber.'),
      (0, 'She had solved it herself by documenting the service over a weekend',
       'Nothing says so; the problem was still there when Renata noticed.',
       'Ela mesma resolveu, documentando o serviço num fim de semana',
       'Nada diz isso; o problema continuava lá quando a Renata percebeu.'),
      (0, 'She had decided the problem was not important after all',
       'She raised it four times in eight weeks before going quiet; it mattered to her.',
       'Ela decidiu que o problema afinal não era importante',
       'Ela levantou o assunto quatro vezes em oito semanas antes de silenciar; importava para ela.'),
      (0, 'Renata had asked her not to bring it up again until the quarter planning in eight weeks',
       'Renata had promised to think about it; she never asked Paula to stay quiet.',
       'A Renata pediu que ela não voltasse ao assunto até o planejamento do trimestre, dali a oito semanas',
       'A Renata prometeu pensar no assunto; nunca pediu à Paula que ficasse quieta.')])

match('ex-1mqjwn18', 'the-promise-list', 'medium',
      ('Match each unkeepable promise with its keepable version from the lesson’s table.',
       'Ligue cada promessa não cumprível à versão cumprível da tabela da aula.'),
      ('An action, a date, and a report back.', 'Uma ação, uma data e um retorno.'),
      [('“I’ll look into the alerts”', '“I’ll get a runbook page written for that alert by Friday”',
        '“Vou ver os alertas”', '“Consigo uma página de runbook para esse alerta até sexta”'),
       ('“I’ll see what I can do about on-call”', '“I’ll ask the platform team about a second rota and tell you on Thursday”',
        '“Vou ver o que posso fazer pelo plantão”', '“Pergunto ao time de plataforma sobre uma segunda escala e te conto na quinta”'),
       ('“Leave it with me”', '“I’ll talk to Otávio about the budget this week and come back either way”',
        '“Deixa comigo”', '“Falo com o Otávio sobre o orçamento esta semana e te dou retorno de qualquer jeito”')],
      [('“I’ll get you the conference budget”', '“Vou conseguir o orçamento da conferência para você”')])

quiz('ex-f4q9eaag', 'the-promise-list', 'medium',
     ('Why can “I’ll find out and tell you” always be kept, while “I’ll get you the budget” cannot?',
      'Por que “vou descobrir e te contar” sempre pode ser cumprida, e “vou conseguir o orçamento para você” não?'),
     ('Whose decision is the budget?', 'De quem é a decisão do orçamento?'),
     [(1, 'The first depends only on the manager; the budget is somebody else’s decision',
       'Right: when the outcome is out of your hands, promise the report back, not the result.',
       'A primeira depende só da gestora; o orçamento é decisão de outra pessoa',
       'Isso: quando o resultado não está nas suas mãos, prometa o retorno, não o resultado.'),
      (0, 'Budgets are never approved',
       'Some are; the point is that approval is not the manager’s to promise.',
       'Orçamentos nunca são aprovados',
       'Alguns são; o ponto é que aprovar não cabe à gestora prometer.'),
      (0, 'The first is vaguer',
       'It is more precise about what the manager will do, which is why it can be kept.',
       'A primeira é mais vaga',
       'Ela é mais precisa sobre o que a gestora vai fazer, e é por isso que pode ser cumprida.'),
      (0, 'Because promises about money need HR’s approval at most companies, and Caju is no exception',
       'No such rule appears; the reason is who decides.',
       'Porque promessas sobre dinheiro precisam de aprovação do RH na maioria das empresas, e a Caju não é exceção',
       'Essa regra não aparece; o motivo é quem decide.')])

quiz('ex-a2pb57ey', 'the-promise-list', 'medium',
     ('Before promising anything, what does the lesson suggest asking?',
      'Antes de prometer qualquer coisa, o que a aula sugere perguntar?'),
     ('Sometimes no promise is needed.', 'Às vezes não é preciso promessa.'),
     [(1, '“Do you want me to do something, or did you want to tell me?”',
       'Right: often the person wanted to be heard, and a promise would be a debt nobody asked for.',
       '“Você quer que eu faça algo, ou queria me contar?”',
       'Isso: muitas vezes a pessoa queria ser ouvida, e uma promessa seria uma dívida que ninguém pediu.'),
      (0, '“How urgent is this?”',
       'Urgency matters later; the first question is whether action is wanted at all.',
       '“Quão urgente é isso?”',
       'Urgência importa depois; a primeira pergunta é se alguma ação é desejada.'),
      (0, '“Who else knows?”',
       'Not the lesson’s question.',
       '“Quem mais sabe?”',
       'Não é a pergunta da aula.'),
      (0, '“Can you write it up so I can forward it?”',
       'That pushes work back onto the person, which the lesson does not suggest.',
       '“Você pode escrever isso para eu encaminhar?”',
       'Isso devolve trabalho à pessoa, o que a aula não sugere.')])

quiz('ex-ygt4jhbj', 'the-promise-list', 'hard',
     ('A line on Renata’s promise list is stuck: the platform team will not decide on a second rota for a month. What does the lesson say she does?',
      'Uma linha da lista de promessas da Renata está travada: o time de plataforma só vai decidir sobre uma segunda escala daqui a um mês. O que a aula diz que ela faz?'),
     ('A promise you cannot keep can still be closed.', 'Uma promessa que não dá para cumprir ainda pode ser fechada.'),
     [(1, 'Message the person that day, saying it is stuck and why',
       'Right: telling the person closes the promise honestly even though the result is not there.',
       'Mandar mensagem à pessoa no mesmo dia, dizendo que travou e por quê',
       'Isso: contar à pessoa fecha a promessa com honestidade, mesmo sem o resultado.'),
      (0, 'Wait until the platform team decides, then report the result',
       'A month of silence looks exactly like a dropped promise from the person’s side.',
       'Esperar o time de plataforma decidir, depois contar o resultado',
       'Um mês de silêncio parece exatamente uma promessa abandonada, do lado da pessoa.'),
      (0, 'Remove the line from the list so it does not distract her during her twice-weekly review',
       'Removing it without telling the person is the silent drop the lesson says cannot be closed.',
       'Tirar a linha da lista para não atrapalhar a revisão de duas vezes por semana',
       'Tirar a linha sem contar à pessoa é o abandono silencioso que a aula diz que não se fecha.'),
      (0, 'Set up the second rota herself',
       'The rota is the platform team’s decision; going around them is not in the lesson.',
       'Montar ela mesma a segunda escala',
       'A escala é decisão do time de plataforma; contorná-lo não está na aula.')])

quiz('ex-sby0eb8q', 'closing-the-loop', 'easy',
     ('Which of the three outcomes does the lesson say is most often skipped when closing a loop?',
      'Qual dos três desfechos a aula diz que é mais pulado ao fechar um ciclo?'),
     ('The person will notice eventually.', 'A pessoa vai perceber em algum momento.'),
     [(1, 'It was done',
       'Right: the manager assumes the person will notice, and the person may not connect the change with what they said.',
       'Foi feito',
       'Isso: a gestora supõe que a pessoa vai perceber, e a pessoa pode não ligar a mudança ao que disse.'),
      (0, 'It is still happening, with a date for the next report',
       'That one needs saying, but the lesson singles out the first as the one skipped.',
       'Ainda está acontecendo, com data para o próximo retorno',
       'Esse precisa ser dito, mas a aula destaca o primeiro como o pulado.'),
      (0, 'The answer is no',
       'Managers avoid that one most, which is a different claim from being skipped because it seems obvious.',
       'A resposta é não',
       'Gestoras evitam mais esse, o que é diferente de ser pulado por parecer óbvio.'),
      (0, 'It was forgotten by the manager',
       'Not one of the three outcomes, though it happens.',
       'Foi esquecido pela gestora',
       'Não é um dos três desfechos, embora aconteça.')])

order('ex-r5nmwt8e', 'closing-the-loop', 'medium',
      ('Put the four parts of Renata’s no to Paula in order.',
       'Ponha em ordem as quatro partes do não da Renata à Paula.'),
      ('The answer leads.', 'A resposta vem na frente.'),
      [('The answer', 'A resposta'), ('The real reason', 'O motivo de verdade'),
       ('What is possible instead', 'O que é possível em vez disso'),
       ('When it will be revisited', 'Quando vai ser revisto')],
      ('Opening with the reason or an apology buries the answer, and the person spends the conversation guessing.',
       'Abrir com o motivo ou com um pedido de desculpas enterra a resposta, e a pessoa passa a conversa adivinhando.'))

quiz('ex-m7xtmpj7', 'closing-the-loop', 'medium',
     ('Renata argued for yes, and Otávio said no. How does the lesson say she delivers it?',
      'A Renata defendeu o sim, e o Otávio disse não. Como a aula diz que ela entrega isso?'),
     ('Whose answer is it, in front of the team?', 'De quem é a resposta, na frente do time?'),
     [(1, 'As the team’s answer, without hinting that she disagreed',
       'Right: blaming Otávio would undermine the decision and her place in the middle.',
       'Como a resposta do time, sem insinuar que discordava',
       'Isso: culpar o Otávio minaria a decisão e o lugar dela no meio.'),
      (0, 'As Otávio’s decision, so that Paula knows Renata was on her side',
       'That is the blame the lesson says she avoided.',
       'Como decisão do Otávio, para a Paula saber que a Renata estava do lado dela',
       'Essa é a culpa que a aula diz que ela evitou.'),
      (0, 'Softened into a maybe',
       'The lesson says she did not soften it, because a maybe keeps the person waiting.',
       'Amaciado num talvez',
       'A aula diz que ela não amaciou, porque um talvez mantém a pessoa esperando.'),
      (0, 'By message, to avoid the conversation',
       'She told Paula in the one-to-one, in four parts.',
       'Por mensagem, para evitar a conversa',
       'Ela contou à Paula na 1:1, em quatro partes.')])

quiz('ex-ydszxvvw', 'closing-the-loop', 'medium',
     ('Why does the lesson say a clear no is better than silence?',
      'Por que a aula diz que um não claro é melhor que o silêncio?'),
     ('What can the person do after each?', 'O que a pessoa consegue fazer depois de cada um?'),
     [(1, 'It lets the person stop waiting',
       'Right: with a no they can make their own decisions; silence keeps them waiting for something that is not coming.',
       'Deixa a pessoa parar de esperar',
       'Isso: com um não ela pode tomar as próprias decisões; o silêncio a mantém esperando algo que não vem.'),
      (0, 'Because a no can always be turned into a yes later, if the manager keeps arguing upwards for long enough',
       'A no can be revisited, but that is not why it beats silence.',
       'Porque um não sempre pode virar sim depois, se a gestora continuar argumentando para cima por tempo suficiente',
       'Um não pode ser revisto, mas não é por isso que ele ganha do silêncio.'),
      (0, 'Silence is against company policy',
       'No policy is involved.',
       'Silêncio vai contra a política da empresa',
       'Não há política envolvida.'),
      (0, 'People prefer bad news to good news',
       'Nobody prefers bad news; they prefer knowing.',
       'As pessoas preferem notícias ruins às boas',
       'Ninguém prefere notícia ruim; preferem saber.')])

mc('ex-qds5hjj8', 'closing-the-loop', 'medium',
   ('Which of these close a loop, by the lesson? Choose all that apply.',
    'Quais destes fecham um ciclo, pela aula? Marque todos que se aplicam.'),
   ('The person learns what happened.', 'A pessoa fica sabendo o que aconteceu.'),
   [(1, '“The runbook page is up, and Yara is your backup for two weeks.”', 'Yes: done, and what changed.',
     '“A página do runbook está no ar, e a Yara é o seu apoio por duas semanas.”', 'Sim: feito, e o que mudou.'),
    (1, '“They discuss it on Tuesday; I’ll tell you on Wednesday.”', 'Yes: still happening, visibly.',
     '“Eles discutem na terça; te conto na quarta.”', 'Sim: ainda acontecendo, de forma visível.'),
    (1, '“We dropped the second half of planning, as you suggested.”', 'Yes: the loop running the other way, for an opinion asked for.',
     '“Cortamos a segunda metade do planejamento, como você sugeriu.”', 'Sim: o ciclo no outro sentido, para uma opinião pedida.'),
    (0, '“I’m on it.”', 'No: it says nothing about what happened or when.',
     '“Estou cuidando disso.”', 'Não: não diz nada sobre o que aconteceu nem quando.'),
    (0, 'Fixing it quietly and saying nothing', 'No: the person may never connect the change to what they raised.',
     'Resolver em silêncio e não dizer nada', 'Não: a pessoa pode nunca ligar a mudança ao que levantou.')])

quiz('ex-cpmqrt99', 'patterns-over-time', 'easy',
     ('What did reading a quarter of one-to-one notes together reveal that no single meeting showed?',
      'O que ler juntas as notas de 1:1 de um trimestre revelou que nenhuma reunião isolada mostrou?'),
     ('Five of seven.', 'Cinco de sete.'),
     [(1, 'Payments was the team’s largest single drag',
       'Right: each person treated it as one irritation among several; together it was the biggest.',
       'Pagamentos era, somado, o maior freio isolado do time',
       'Isso: cada pessoa tratava aquilo como uma irritação entre várias; juntas, era a maior.'),
      (0, 'Diego was frustrated with design reviews',
       'That was vivid and raised once; the tally showed it was not a pattern.',
       'O Diego estava frustrado com revisões de design',
       'Isso foi vívido e levantado uma vez; a contagem mostrou que não era padrão.'),
      (0, 'On-call was getting worse',
       'It was getting better: four mentions in month one, one in month three.',
       'O plantão estava piorando',
       'Estava melhorando: quatro menções no primeiro mês, uma no terceiro.'),
      (0, 'Everybody wanted promotion',
       'Growth came up for four people, which is not the same thing.',
       'Todo mundo queria promoção',
       'Crescimento apareceu para quatro pessoas, o que não é a mesma coisa.')])

num('ex-g90k7dt8', 'patterns-over-time', 'easy',
    ('In the tally, on-call came up for four people in month one and one person in month three. By how many people did it fall?',
     'Na contagem, plantão apareceu para quatro pessoas no mês um e uma pessoa no mês três. Caiu em quantas pessoas?'),
    ('Four minus one.', 'Quatro menos um.'),
    3, 0, ('people', 'pessoas'), (['person'], ['pessoa']))

quiz('ex-benayb7q', 'patterns-over-time', 'medium',
     ('Why does the lesson say themes need counting rather than remembering?',
      'Por que a aula diz que temas precisam ser contados, e não lembrados?'),
     ('Diego once; Paula four times.', 'O Diego uma vez; a Paula quatro.'),
     [(1, 'Without a count, the loud wins over the repeated',
       'Right: Diego’s vivid complaint was raised once, Paula’s calm sentence four times, and memory favours the first.',
       'Sem contar, o alto ganha',
       'Isso: a queixa vívida do Diego foi levantada uma vez, a frase calma da Paula quatro, e a memória favorece a primeira.'),
      (0, 'Counting is required for the quarterly report that goes to Otávio and the rest of leadership',
       'Nothing says the tally is reported upwards; it is Renata’s instrument.',
       'A contagem é exigida pelo relatório trimestral que vai para o Otávio e o resto da liderança',
       'Nada diz que a contagem vai para cima; ela é instrumento da Renata.'),
      (0, 'Memory is always wrong',
       'Memory is not always wrong; it is biased towards the vivid.',
       'A memória sempre erra',
       'A memória não erra sempre; ela pende para o vívido.'),
      (0, 'Themes that are not counted disappear from the notes',
       'They stay in the notes; nobody reads them together.',
       'Temas não contados somem das notas',
       'Eles ficam nas notas; ninguém os lê juntos.')])

quiz('ex-fptdshj8', 'patterns-over-time', 'hard',
     ('Otávio’s skip-level meetings surface something that never appeared in Renata’s own notes. How does the lesson read that?',
      'As skip-levels do Otávio revelam algo que nunca apareceu nas notas da própria Renata. Como a aula lê isso?'),
     ('A second instrument, not an audit.', 'Um segundo instrumento, não uma auditoria.'),
     [(1, 'It says something about what people find easy to tell her',
       'Right: that is the more useful finding, because it shows a gap in what reaches her.',
       'Diz algo sobre o que as pessoas acham fácil contar a ela',
       'Isso: esse é o achado mais útil, porque mostra uma lacuna no que chega até ela.'),
      (0, 'Otávio is checking up on her, and she should be careful about what she does next',
       'The lesson suggests treating skip-levels as a second instrument rather than an audit.',
       'O Otávio está fiscalizando, e ela deveria tomar cuidado com o que faz em seguida',
       'A aula sugere tratar as skip-levels como segundo instrumento, não como auditoria.'),
      (0, 'Her notes are wrong and should be rewritten',
       'The notes may be accurate about what she was told; the gap is in what she was told.',
       'As notas dela estão erradas e deveriam ser reescritas',
       'As notas podem estar certas sobre o que lhe contaram; a lacuna está no que lhe contaram.'),
      (0, 'The skip-level is unreliable',
       'Nothing in the lesson doubts the skip-level.',
       'A skip-level não é confiável',
       'Nada na aula duvida da skip-level.')])

quiz('ex-p471a6nt', 'drill', 'hard',
     ('A manager promised a report three weeks ago to “look into” getting them a better laptop. Nothing has happened, and the report has stopped mentioning it. What is the best next step, by this lesson?',
      'Um gestor prometeu há três semanas “ver” um notebook melhor para uma pessoa do time. Nada aconteceu, e a pessoa parou de mencionar. Qual é o melhor próximo passo, por esta aula?'),
     ('Close it, with an outcome and a shape.', 'Feche, com um desfecho e um formato.'),
     [(1, 'Tell them what happened, apologise once, and make a dated promise',
       'Right: like Renata with Paula, close the silent loop and replace the vague promise with a keepable one.',
       'Contar o que aconteceu, pedir desculpas uma vez e fazer uma promessa com data',
       'Isso: como a Renata com a Paula, fechar o ciclo silencioso e trocar a promessa vaga por uma cumprível.'),
      (0, 'Say nothing, since they have stopped asking',
       'Their silence is the answer they drew from his, which is the failure the lesson describes.',
       'Não dizer nada, já que a pessoa parou de pedir',
       'O silêncio dela é a conclusão que tirou do dele, que é a falha que a aula descreve.'),
      (0, 'Order the laptop without telling them',
       'They may not connect it to what they asked, and the loop stays open in their mind.',
       'Pedir o notebook sem contar',
       'A pessoa pode não ligar uma coisa à outra, e o ciclo continua aberto na cabeça dela.'),
      (0, 'Ask them to raise it again in writing',
       'That puts the work of the manager’s promise back on the person.',
       'Pedir que a pessoa levante o assunto de novo por escrito',
       'Isso devolve à pessoa o trabalho da promessa do gestor.')])
