"""Lesson 8: feedback, situation-behaviour-impact, and asking first."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-54k0bf5s')

quiz('ex-bmejqvq8', 'judgement-and-observation', 'easy',
     ('Which of these is an observation rather than a judgement?',
      'Qual destes é uma observação, e não um julgamento?'),
     ('What would a camera have recorded?', 'O que uma câmera teria gravado?'),
     [(1, '“You declined the last three requests to pair.”',
       'Right: it is something that happened and could be checked.',
       '“Você recusou os três últimos pedidos para parear.”',
       'Isso: é algo que aconteceu e pode ser conferido.'),
      (0, '“You’re not a team player, and the rest of the team has started to notice it too.”',
       'A judgement about who the person is, with a claim about others attached.',
       '“Você não joga em equipe, e o resto do time também começou a perceber.”',
       'Um julgamento sobre quem a pessoa é, com uma afirmação sobre os outros anexada.'),
      (0, '“You need to communicate more with the team.”',
       'A conclusion with no instruction about what “more” looks like.',
       '“Você precisa se comunicar mais com o time.”',
       'Uma conclusão sem instrução sobre como seria esse “mais”.'),
      (0, '“Your code is sloppy.”',
       'An adjective about the work, with nothing a camera would show.',
       '“O seu código é desleixado.”',
       'Um adjetivo sobre o trabalho, sem nada que uma câmera mostraria.')])

quiz('ex-z72nwqdz', 'judgement-and-observation', 'medium',
     ('Why do people defend against a judgement harder than against an observation?',
      'Por que as pessoas se defendem de um julgamento com mais força do que de uma observação?'),
     ('What does a judgement say?', 'O que um julgamento diz?'),
     [(1, 'A judgement is about what they are, and nobody knows how to change what they are, while what they did can be done differently next time',
       'Right: identity is defended harder than action, because action can change and identity cannot be changed on request.',
       'Um julgamento é sobre o que a pessoa é, e ninguém sabe mudar o que é, enquanto o que fez pode ser feito diferente da próxima vez',
       'Isso: identidade é defendida com mais força que ação, porque ação pode mudar e identidade não muda a pedido.'),
      (0, 'Judgements are usually wrong',
       'They may be right; the problem is that they are arguable and about identity.',
       'Julgamentos geralmente estão errados',
       'Eles podem estar certos; o problema é serem discutíveis e sobre identidade.'),
      (0, 'Observations are always delivered more gently',
       'Delivery is a separate matter; an observation can be said harshly too.',
       'Observações sempre são ditas com mais delicadeza',
       'O tom é outra questão; uma observação também pode ser dita com dureza.'),
      (0, 'People do not listen to managers',
       'Nothing in the lesson suggests this.',
       'As pessoas não ouvem gestoras',
       'Nada na aula sugere isso.')])

quiz('ex-vxqfs8sb', 'judgement-and-observation', 'medium',
     ('Renata has an impression that somebody is “disengaged” but cannot find a specific moment behind it. What does the lesson say she has?',
      'A Renata tem a impressão de que alguém está “desengajado”, mas não encontra um momento específico por trás disso. O que a aula diz que ela tem?'),
     ('Not feedback yet.', 'Ainda não é feedback.'),
     [(1, 'An impression to watch for and note privately',
       'Right: without observations there is no feedback yet, only something to watch and write down.',
       'Uma impressão, a anotar',
       'Isso: sem observações ainda não há feedback, só algo para observar e anotar.'),
      (0, 'Feedback to give at once, before it gets worse',
       'Without a moment the person could picture, it would be a judgement.',
       'Um feedback para dar já, antes que piore',
       'Sem um momento que a pessoa consiga visualizar, seria um julgamento.'),
      (0, 'Grounds for a performance conversation',
       'A performance conversation needs far more than an impression; lesson 10 covers it.',
       'Motivo para uma conversa de desempenho',
       'Uma conversa de desempenho precisa de muito mais que uma impressão; a aula 10 trata disso.'),
      (0, 'Nothing worth keeping',
       'It is worth keeping, in the private notes, until there is something concrete.',
       'Nada que valha guardar',
       'Vale guardar, nas notas privadas, até haver algo concreto.')])

match('ex-kpz6dbfd', 'judgement-and-observation', 'easy',
      ('Match each judgement with its observation from the lesson’s table.',
       'Ligue cada julgamento à observação da tabela da aula.'),
      ('Find the moment behind each.', 'Encontre o momento por trás de cada um.'),
      [('“You’re too negative in planning.”', 'four of six proposals met with “that won’t work”',
        '“Você é negativo demais no planejamento.”', 'quatro de seis propostas receberam “isso não vai funcionar”'),
       ('“Your code is sloppy.”', 'two pull requests without error-path tests came back from review',
        '“O seu código é desleixado.”', 'dois pull requests sem testes de erro voltaram da revisão'),
       ('“You need to communicate more.”', 'the slip reached Renata through Helena, not through you',
        '“Você precisa se comunicar mais.”', 'o atraso chegou à Renata pela Helena, e não por você'),
       ('“Great job!”', 'the runbook let Thiago fix the alert alone at 3 a.m.',
        '“Ótimo trabalho!”', 'o runbook fez o Thiago resolver o alerta sozinho às 3 da manhã')],
      [('you have a bad attitude about reviews', 'você tem uma atitude ruim com revisões')])

order('ex-4hxyvc0z', 'sbi', 'easy',
      ('Put the parts of the Center for Creative Leadership’s feedback structure in order.',
       'Ponha em ordem as partes da estrutura de feedback do Center for Creative Leadership.'),
      ('When, what, and what it caused.', 'Quando, o quê, e o que causou.'),
      [('Situation', 'Situação'), ('Behaviour', 'Comportamento'), ('Impact', 'Impacto')])

quiz('ex-veem3ky1', 'sbi', 'medium',
     ('Which sentence is the impact in Renata’s feedback to Diego?',
      'Qual frase é o impacto no feedback da Renata ao Diego?'),
     ('What did the behaviour cause?', 'O que o comportamento causou?'),
     [(1, '“Thiago didn’t push anything for two days.”',
       'Right: an observable effect of the comment.',
       '“O Thiago não enviou nada por dois dias.”',
       'Isso: um efeito observável do comentário.'),
      (0, '“Your first comment was ‘this is wrong, redo it’, and it didn’t say what was wrong.”',
       'That is the behaviour, what a camera would record.',
       '“O seu primeiro comentário foi ‘isso está errado, refaz’, e não dizia o que estava errado.”',
       'Isso é o comportamento, o que uma câmera gravaria.'),
      (0, '“The review on Thiago’s pull request on Tuesday.”',
       'That is the situation.',
       '“A revisão do pull request do Thiago na terça.”',
       'Essa é a situação.'),
      (0, '“You were too harsh with him.”',
       'A judgement, and not in Renata’s feedback at all.',
       '“Você foi duro demais com ele.”',
       'Um julgamento, e que nem está no feedback da Renata.')])

quiz('ex-nsvakmpg', 'sbi', 'medium',
     ('Why did Renata end the impact with Thiago going to Yara for reviews?',
      'Por que a Renata terminou o impacto com o Thiago indo à Yara pedir revisões?'),
     ('What does Diego care about?', 'Com o que o Diego se importa?'),
     [(1, 'It tied the behaviour to something Diego himself cares about, which is the quality of the calendar code',
       'Right: the person who knows the calendar code best was no longer reviewing it.',
       'Ligava o comportamento a algo com que o próprio Diego se importa, que é a qualidade do código de calendário',
       'Isso: a pessoa que mais conhece o código de calendário tinha deixado de revisá-lo.'),
      (0, 'To make Diego jealous of Yara',
       'Nothing in it is about rivalry.',
       'Para deixar o Diego com ciúme da Yara',
       'Nada ali é sobre rivalidade.'),
      (0, 'Because Yara had complained about the extra reviews landing on her desk every week',
       'Yara had not complained; the point was the calendar code.',
       'Porque a Yara tinha reclamado das revisões extras que caíam na mesa dela toda semana',
       'A Yara não tinha reclamado; o ponto era o código de calendário.'),
      (0, 'To show the team had sided with Thiago',
       'It describes one effect, not a team taking sides.',
       'Para mostrar que o time tinha ficado do lado do Thiago',
       'Descreve um efeito, não um time tomando partido.')])

mc('ex-0v5qc39g', 'sbi', 'medium',
   ('Which of these does situation-behaviour-impact leave out on purpose? Choose all that apply.',
    'Quais destes a estrutura situação, comportamento e impacto deixa de fora de propósito? Marque todos que se aplicam.'),
   ('Look at the line under the figure.', 'Olhe a linha embaixo da figura.'),
   [(1, 'Adjectives about the person', 'Yes: no “harsh”, no “arrogant”.',
     'Adjetivos sobre a pessoa', 'Sim: nada de “duro”, nada de “arrogante”.'),
    (1, 'Guesses about what the person intended', 'Yes: intent is the person’s to tell, not the manager’s to assume.',
     'Palpites sobre o que a pessoa pretendia', 'Sim: a intenção é a pessoa quem conta, não a gestora quem supõe.'),
    (1, 'Comparisons with how other people do it', 'Yes: Renata said nothing about how others review.',
     'Comparações com como outras pessoas fazem', 'Sim: a Renata não disse nada sobre como outros revisam.'),
    (0, 'The effect the behaviour had', 'No: the impact is one of the three parts.',
     'O efeito que o comportamento teve', 'Não: o impacto é uma das três partes.'),
    (0, 'The day it happened', 'No: the situation anchors it in a specific moment.',
     'O dia em que aconteceu', 'Não: a situação ancora num momento específico.')])

quiz('ex-588kb4hg', 'ask-first', 'easy',
     ('What did Renata learn by asking Diego how the review went, before giving the feedback?',
      'O que a Renata aprendeu ao perguntar ao Diego como foi a revisão, antes de dar o feedback?'),
     ('Style or lapse?', 'Estilo ou deslize?'),
     [(1, 'A lapse, not a style',
       'Right: her feedback could be shorter, and Diego named the problem himself.',
       'Um deslize, não um estilo',
       'Isso: o feedback dela podia ser mais curto, e o próprio Diego nomeou o problema.'),
      (0, 'That Thiago had asked for blunt comments',
       'That was a hypothetical in the lesson, to show how an answer could change the feedback.',
       'Que o Thiago tinha pedido comentários diretos',
       'Isso era uma hipótese na aula, para mostrar como uma resposta poderia mudar o feedback.'),
      (0, 'Nothing she did not already know',
       'She learned that he regretted it and did not know about the two lost days.',
       'Nada que ela já não soubesse',
       'Ela aprendeu que ele se arrependia e não sabia dos dois dias perdidos.'),
      (0, 'That Diego thought Thiago’s pull request was badly written and deserved the comment',
       'He said the comment was short because he wrote it between meetings, not that it was deserved.',
       'Que o Diego achava o pull request do Thiago mal escrito e merecedor do comentário',
       'Ele disse que o comentário saiu curto porque escreveu entre reuniões, não que fosse merecido.')])

quiz('ex-0aak9dh1', 'ask-first', 'medium',
     ('When does asking first become a trap?',
      'Quando perguntar primeiro vira armadilha?'),
     ('Could the answer change what you say?', 'A resposta poderia mudar o que você diz?'),
     [(1, 'When nothing could change it',
       'Right: then the question only waits for a confession, and people recognise it.',
       'Quando nada poderia mudar',
       'Isso: aí a pergunta só espera uma confissão, e as pessoas reconhecem.'),
      (0, 'When the person is senior',
       'Seniority does not make the question a trap.',
       'Quando a pessoa é sênior',
       'Senioridade não torna a pergunta armadilha.'),
      (0, 'When the feedback is positive',
       'The lesson does not discuss this case as a trap.',
       'Quando o feedback é positivo',
       'A aula não trata esse caso como armadilha.'),
      (0, 'When the manager has not prepared the situation, behaviour and impact in writing beforehand',
       'Preparation is not what makes it a trap; a closed mind is.',
       'Quando a gestora não preparou por escrito a situação, o comportamento e o impacto antes',
       'Preparação não é o que faz dela armadilha; uma cabeça fechada é.')])

match('ex-1e0fq05d', 'ask-first', 'medium',
      ('Match each of Kim Scott’s quadrants with what it does.',
       'Ligue cada quadrante de Kim Scott ao que ele faz.'),
      ('Caring personally, challenging directly.', 'Se importar pessoalmente, desafiar diretamente.'),
      [('radical candour', 'cares about the person and challenges the work',
        'franqueza radical', 'se importa com a pessoa e desafia o trabalho'),
       ('ruinous empathy', 'cares, and never says the hard thing',
        'empatia ruinosa', 'se importa, e nunca diz a coisa difícil'),
       ('obnoxious aggression', 'challenges, without caring',
        'agressividade detestável', 'desafia, sem se importar'),
       ('manipulative insincerity', 'neither, to protect itself',
        'falsidade manipuladora', 'nenhum dos dois, para se proteger')])

quiz('ex-qp1abmgb', 'ask-first', 'hard',
     ('An engineer made a joke about a colleague’s accent in a team meeting. Should the manager open the conversation with “How do you think that meeting went?”',
      'Um engenheiro fez uma piada com o sotaque de uma colega numa reunião do time. A gestora deveria abrir a conversa com “Como você acha que foi aquela reunião?”'),
     ('Some behaviour is not negotiable.', 'Alguns comportamentos não são negociáveis.'),
     [(1, 'No: for serious behaviour, say what happened and what it means first',
       'Right: asking first would make discriminatory behaviour sound negotiable.',
       'Não: para comportamento grave, dizer primeiro o que aconteceu e o que significa',
       'Isso: perguntar primeiro faria um comportamento discriminatório soar negociável.'),
      (0, 'Yes: asking first always works better',
       'The lesson names exactly this kind of case as the exception.',
       'Sim: perguntar primeiro sempre funciona melhor',
       'A aula nomeia exatamente esse tipo de caso como exceção.'),
      (0, 'Yes, so that he can explain the joke and the manager can judge whether it was really meant to offend anybody',
       'Intent does not change what the joke did, and the lesson puts serious cases outside asking first.',
       'Sim, para ele explicar a piada e a gestora julgar se ele de fato quis ofender alguém',
       'A intenção não muda o que a piada fez, e a aula põe casos graves fora do perguntar primeiro.'),
      (0, 'No: the manager should raise it in the next team meeting instead',
       'Corrective feedback is private, and this is a conversation with him first.',
       'Não: a gestora deveria levantar o assunto na próxima reunião do time',
       'Feedback corretivo é em particular, e isto é uma conversa com ele antes.')])

quiz('ex-1602vta0', 'timing-and-place', 'easy',
     ('What does the lesson say should be in a performance review that the person has not heard before?',
      'O que a aula diz que deveria haver numa avaliação de desempenho que a pessoa nunca ouviu antes?'),
     ('A summary of conversations that took place.', 'Um resumo de conversas que aconteceram.'),
     [(1, 'Nothing',
       'Right: everything in it should already have been said, close to when it happened.',
       'Nada',
       'Isso: tudo nela já deveria ter sido dito, perto de quando aconteceu.'),
      (0, 'The corrective feedback, saved for the formal moment',
       'Saving it is what the lesson argues against.',
       'O feedback corretivo, guardado para o momento formal',
       'Guardar é exatamente o que a aula critica.'),
      (0, 'The rating, which managers decide only at review time and should not hint at before',
       'A rating may be decided then, but the feedback behind it should not be new.',
       'A nota, que gestoras decidem só na avaliação e não deveriam antecipar',
       'A nota pode ser decidida ali, mas o feedback por trás dela não deveria ser novo.'),
      (0, 'Praise from colleagues',
       'Nothing says praise should be held back for the review.',
       'Elogios de colegas',
       'Nada diz que elogios devam ser guardados para a avaliação.')])

quiz('ex-7y3dtapf', 'timing-and-place', 'medium',
     ('Why does the lesson say “say it first, write it after”?',
      'Por que a aula diz “diga primeiro, escreva depois”?'),
     ('What does writing lose?', 'O que a escrita perde?'),
     [(1, 'In writing the person cannot ask what you meant, and you cannot see how it lands',
       'Right: and a sentence gentle out loud reads cold on a screen; the written version is the record afterwards.',
       'Por escrito a pessoa não pode perguntar o que você quis dizer, e você não vê como chega',
       'Isso: e uma frase gentil em voz alta soa fria na tela; a versão escrita é o registro depois.'),
      (0, 'Written feedback is not legally valid',
       'Nothing legal is involved.',
       'Feedback escrito não tem validade legal',
       'Não há nada jurídico envolvido.'),
      (0, 'Because writing takes longer',
       'Writing is often quicker, which is why it is tempting.',
       'Porque escrever demora mais',
       'Escrever muitas vezes é mais rápido, e por isso é tentador.'),
      (0, 'People do not read messages',
       'They read them; what is lost is the conversation.',
       'As pessoas não leem mensagens',
       'Elas leem; o que se perde é a conversa.')])

quiz('ex-exjtb5ym', 'drill', 'hard',
     ('A manager writes in the team channel after an incident: “Whoever deployed on Friday without checking the dashboard, please don’t.” Which rules from this lesson does that break?',
      'Uma gestora escreve no canal do time depois de um incidente: “Quem fez deploy na sexta sem olhar o painel, por favor, não faça isso.” Quais regras desta aula isso quebra?'),
     ('Where, how, and what it describes.', 'Onde, como, e o que descreve.'),
     [(1, 'Corrective feedback given in public, in writing first, with no conversation',
       'Right: it is public, written, and leaves the person no chance to explain or ask.',
       'Feedback corretivo dado em público, primeiro por escrito, sem conversa',
       'Isso: é público, escrito, e não dá à pessoa chance de explicar ou perguntar.'),
      (0, 'None: it names no one, so it is private',
       'Everybody on the team knows who deployed on Friday.',
       'Nenhuma: não cita ninguém, então é privado',
       'Todo mundo no time sabe quem fez deploy na sexta.'),
      (0, 'Only the timing, since it should have waited for the review',
       'Waiting for the review would break another rule; soon was right, the place and form were wrong.',
       'Só o momento, já que deveria esperar a avaliação',
       'Esperar a avaliação quebraria outra regra; logo estava certo, o lugar e a forma estavam errados.'),
      (0, 'It is a judgement rather than an observation',
       'It describes a behaviour; the problems are where and how it was said.',
       'É um julgamento e não uma observação',
       'Descreve um comportamento; os problemas são onde e como foi dito.')])
