"""Lesson 9: positive feedback as calibration."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-g1d0wsyt')

mc('ex-mneyy1xa', 'why-specific', 'easy',
   ('Which questions does “Great write-up, Paula!” leave unanswered? Choose all that apply.',
    'Quais perguntas o “Ótimo texto, Paula!” deixa sem resposta? Marque todas que se aplicam.'),
   ('Three questions.', 'Três perguntas.'),
   [(1, 'Great in what way?', 'Yes: speed, tone, accuracy or length?', 'Ótimo em quê?', 'Sim: velocidade, tom, precisão ou tamanho?'),
    (1, 'Great compared with what?', 'Yes: better than usual, or the expected bar?', 'Ótimo comparado com quê?', 'Sim: melhor que o normal, ou o padrão esperado?'),
    (1, 'Great for whom?', 'Yes: did it matter to anybody?', 'Ótimo para quem?', 'Sim: importou para alguém?'),
    (0, 'Who wrote it?', 'No: the message names Paula.', 'Quem escreveu?', 'Não: a mensagem cita a Paula.'),
    (0, 'Was Renata sincere?', 'No: the lesson grants it was sincere; the problem is the information.',
     'A Renata foi sincera?', 'Não: a aula admite que era sincero; o problema é a informação.')])

quiz('ex-4axjmmw6', 'why-specific', 'medium',
     ('What does the lesson mean by calling positive feedback calibration?',
      'O que a aula quer dizer ao chamar o feedback positivo de calibragem?'),
     ('People learn what a team values from what it notices.', 'As pessoas aprendem o que um time valoriza pelo que ele percebe.'),
     [(1, 'What good looks like',
       'Right: corrective feedback teaches what to avoid; specific praise shows the top of the range.',
       'Como é o bom aqui',
       'Isso: o feedback corretivo ensina o que evitar; o elogio específico mostra o topo da escala.'),
      (0, 'It balances the negative feedback given in the same week, so the person’s mood stays level',
       'That is the ratio idea the next section takes apart.',
       'Equilibra o feedback negativo dado na mesma semana, para o humor da pessoa ficar estável',
       'Essa é a ideia da proporção que a próxima seção desmonta.'),
      (0, 'It adjusts the person’s pay',
       'Pay is not mentioned.',
       'Ajusta o salário da pessoa',
       'Salário não é mencionado.'),
      (0, 'It measures how motivated the team is',
       'It is not a measurement of the team.',
       'Mede quão motivado o time está',
       'Não é uma medida do time.')])

quiz('ex-7whqdxwx', 'why-specific', 'medium',
     ('Two weeks after Renata praised Yara’s design document in public, Thiago’s first design document had a section on what he considered and dropped. What does that show?',
      'Duas semanas depois de a Renata elogiar em público o documento de design da Yara, o primeiro documento de design do Thiago tinha uma seção sobre o que ele considerou e descartou. O que isso mostra?'),
     ('Nobody asked him to add it.', 'Ninguém pediu que ele acrescentasse.'),
     [(1, 'The precise praise told the whole team what a design document at Caju should contain, without anybody writing a rule',
       'Right: praising Yara precisely calibrated the whole team.',
       'O elogio preciso disse ao time inteiro o que um documento de design na Caju deveria conter, sem ninguém escrever uma regra',
       'Isso: elogiar a Yara com precisão calibrou o time inteiro.'),
      (0, 'Thiago copied Yara',
       'He adopted a practice, which is what calibration is for.',
       'O Thiago copiou a Yara',
       'Ele adotou uma prática, que é para isso que a calibragem serve.'),
      (0, 'Renata had told Thiago privately to add it to every design document he writes from now on',
       'The lesson says nobody asked him.',
       'A Renata tinha dito ao Thiago em particular para pôr isso em todo documento de design dali em diante',
       'A aula diz que ninguém pediu.'),
      (0, 'Design documents at Caju have a template',
       'No template is mentioned; the change came from the praise.',
       'Os documentos de design da Caju têm um modelo',
       'Nenhum modelo é mencionado; a mudança veio do elogio.')])

quiz('ex-5r9ac1t2', 'why-specific', 'medium',
     ('In Mueller and Dweck’s 1998 study, what happened to children praised for being clever?',
      'No estudo de 1998 de Mueller e Dweck, o que aconteceu com as crianças elogiadas por serem inteligentes?'),
     ('Protecting the label.', 'Proteger o rótulo.'),
     [(1, 'They chose easier tasks afterwards, and did worse after a failure',
       'Right: praise for a trait teaches people to protect the label.',
       'Escolheram tarefas mais fáceis depois, e foram pior depois de um fracasso',
       'Isso: elogiar um traço ensina as pessoas a proteger o rótulo.'),
      (0, 'They worked harder',
       'The children praised for effort were the ones who kept taking on harder tasks.',
       'Se esforçaram mais',
       'As crianças elogiadas pelo esforço é que continuaram pegando tarefas mais difíceis.'),
      (0, 'Nothing measurable',
       'The study found a clear difference.',
       'Nada mensurável',
       'O estudo encontrou uma diferença clara.'),
      (0, 'They asked for more praise',
       'Not what the study reported.',
       'Pediram mais elogios',
       'Não foi o que o estudo relatou.')])

quiz('ex-8b2q1a8k', 'why-specific', 'hard',
     ('Which praise follows the lesson’s advice best?',
      'Qual elogio segue melhor o conselho da aula?'),
     ('A choice, not a trait.', 'Uma escolha, não um traço.'),
     [(1, '“Putting the cause last was the right call.”',
       'Right: it names a choice Paula can repeat on purpose.',
       '“Deixar a causa por último foi a decisão certa.”',
       'Isso: nomeia uma escolha que a Paula consegue repetir de propósito.'),
      (0, '“You’re a natural at incident writing, and everybody on the team knows it.”',
       'Praise for a trait, which makes the next hard incident a risk to the label.',
       '“Você tem um dom para escrever sobre incidentes, e todo mundo no time sabe.”',
       'Elogio de traço, que transforma o próximo incidente difícil num risco para o rótulo.'),
      (0, '“Great job as always!”',
       'Vague, and “as always” tells her nothing about this one.',
       '“Ótimo trabalho como sempre!”',
       'Vago, e o “como sempre” não diz nada sobre este.'),
      (0, '“You’re so good with clinics.”',
       'Another trait, with nothing to repeat.',
       '“Você é muito boa com as clínicas.”',
       'Outro traço, sem nada a repetir.')])

quiz('ex-9wrhe7vv', 'the-ratio-myth', 'easy',
     ('What happened to the mathematical model behind the positivity ratio?',
      'O que aconteceu com o modelo matemático por trás da proporção de positividade?'),
     ('2013.', '2013.'),
     [(1, 'It was withdrawn',
       'Right: Brown, Sokal and Friedman showed the equations did not fit, and the journal withdrew the modelling.',
       'Foi retirado',
       'Isso: Brown, Sokal e Friedman mostraram que as equações não se aplicavam, e a revista retirou a modelagem.'),
      (0, 'It was confirmed by a larger study',
       'It was critiqued and the modelling withdrawn.',
       'Foi confirmado por um estudo maior',
       'Foi criticado e a modelagem retirada.'),
      (0, 'It was refined to 5 to 1',
       'Numbers like that are folk versions; no refinement rescued the model.',
       'Foi refinado para 5 para 1',
       'Números assim são versões populares; nenhum refinamento salvou o modelo.'),
      (0, 'It was adopted by most management courses as the standard rule for how often to praise',
       'It spread before the critique; adoption is not what happened to the model.',
       'Foi adotado pela maioria dos cursos de gestão como a regra padrão de quanto elogiar',
       'Ele se espalhou antes da crítica; adoção não é o que aconteceu com o modelo.')])

quiz('ex-ykzcnm7m', 'the-ratio-myth', 'medium',
     ('Why does the feedback sandwich stop working after a few uses?',
      'Por que o sanduíche de feedback para de funcionar depois de algumas vezes?'),
     ('What does the first compliment start to mean?', 'O que o primeiro elogio passa a significar?'),
     [(1, 'People learn the pattern, and start hearing any compliment from that manager as the warning before a “but”',
       'Right: praise becomes the signal that a “but” is coming, so it no longer works on its own.',
       'As pessoas aprendem o padrão, e passam a ouvir qualquer elogio daquela gestora como o aviso antes de um “mas”',
       'Isso: o elogio vira o sinal de que um “mas” vem aí, então deixa de funcionar sozinho.'),
      (0, 'The criticism gets lost in the middle',
       'That happens too, but the lesson’s first point is that people learn the pattern.',
       'A crítica se perde no meio',
       'Isso também acontece, mas o primeiro ponto da aula é que as pessoas aprendem o padrão.'),
      (0, 'Managers run out of compliments',
       'Not the problem described.',
       'As gestoras ficam sem elogios',
       'Não é o problema descrito.'),
      (0, 'It takes too long to prepare three parts for every piece of feedback you need to give',
       'Time is not the objection; the pattern and the lost message are.',
       'Leva tempo demais preparar três partes para cada feedback que você precisa dar',
       'Tempo não é a objeção; o padrão e a mensagem perdida são.')])

quiz('ex-c8ya3zvm', 'the-ratio-myth', 'medium',
     ('Renata counts positive and corrective feedback per person each month. What is she looking for?',
      'A Renata conta os feedbacks positivos e corretivos por pessoa todo mês. O que ela procura?'),
     ('Not a ratio.', 'Não uma proporção.'),
     [(1, 'Anybody who has heard only one kind',
       'Right: somebody who hears only corrections gets a false picture of what she thinks.',
       'Alguém que só ouviu um tipo',
       'Isso: quem só ouve correções recebe uma imagem falsa do que ela pensa.'),
      (0, 'Whether each person gets at least three positives per negative',
       'She is explicitly not aiming at a ratio.',
       'Se cada pessoa recebe pelo menos três positivos por negativo',
       'Ela explicitamente não mira uma proporção.'),
      (0, 'Who deserves a bonus',
       'Nothing about bonuses.',
       'Quem merece bônus',
       'Nada sobre bônus.'),
      (0, 'Which people are performing worst on the team, so she can start improvement plans early',
       'The count is about the picture her feedback gives, not ranking performance.',
       'Quais pessoas estão rendendo pior no time, para começar planos de melhoria cedo',
       'A contagem é sobre a imagem que o feedback dela passa, não sobre ranquear desempenho.')])

cloze('ex-km8fn1te', 'the-ratio-myth', 'easy',
      ('The feedback ___ wraps criticism between two compliments.',
       'O ___ de feedback embrulha a crítica entre dois elogios.'),
      ('Bread, filling, bread.', 'Pão, recheio, pão.'),
      [(['sandwich'], ['sanduíche', 'sanduiche'])])

quiz('ex-654pdx03', 'public-and-private', 'easy',
     ('What does public recognition do that private recognition does not?',
      'O que o reconhecimento público faz que o particular não faz?'),
     ('Two messages at once.', 'Duas mensagens de uma vez.'),
     [(1, 'Tells the team what is valued',
       'Right: it recognises the person and calibrates everybody else.',
       'Diz ao time o que é valorizado',
       'Isso: reconhece a pessoa e calibra todo mundo.'),
      (0, 'Counts more towards promotion',
       'Nothing says promotion weighs public praise more.',
       'Conta mais para promoção',
       'Nada diz que a promoção pesa mais o elogio público.'),
      (0, 'Is always more welcome to the person',
       'Some people dislike it, which is the first risk the lesson names.',
       'É sempre mais bem-vindo pela pessoa',
       'Algumas pessoas não gostam, que é o primeiro risco que a aula nomeia.'),
      (0, 'Replaces the need for any specific detail, since the audience already knows what happened',
       'Public praise needs precision too, especially about who did what.',
       'Dispensa qualquer detalhe específico, já que a plateia já sabe o que aconteceu',
       'Elogio público também precisa de precisão, sobretudo sobre quem fez o quê.')])

match('ex-q42za35d', 'public-and-private', 'medium',
      ('Match each way public praise backfires with its fix.',
       'Ligue cada jeito de o elogio público sair pela culatra à correção.'),
      ('Three risks.', 'Três riscos.'),
      [('the person dislikes attention', 'ask early how they prefer to hear it',
        'a pessoa não gosta de atenção', 'perguntar cedo como ela prefere saber'),
       ('it credits the wrong person', 'say precisely who did what',
        'credita a pessoa errada', 'dizer com precisão quem fez o quê'),
       ('it always goes to the same people', 'notice invisible work too',
        'vai sempre para as mesmas pessoas', 'perceber o trabalho invisível também')],
      [('praise less often', 'elogiar menos vezes')])

quiz('ex-e97acjhq', 'public-and-private', 'medium',
     ('Why does the lesson say “that’s what I’d expect from a senior engineer” carries more than enthusiasm?',
      'Por que a aula diz que “é o que eu esperaria de uma pessoa engenheira sênior” carrega mais que entusiasmo?'),
     ('A scale the person cares about.', 'Uma escala que importa à pessoa.'),
     [(1, 'It places the work on a written scale',
       'Right: it says where the work sits against what is expected, which lesson 11 writes down.',
       'Situa o trabalho numa escala escrita',
       'Isso: diz onde o trabalho fica em relação ao esperado, que a aula 11 põe por escrito.'),
      (0, 'It promises a promotion',
       'It does not, and lesson 24 warns against promises like that.',
       'Promete uma promoção',
       'Não promete, e a aula 24 alerta contra promessas assim.'),
      (0, 'It is said in public, where the rest of the team can hear what the expected level is',
       'It can be said privately; its value is the scale, not the audience.',
       'É dito em público, onde o resto do time ouve qual é o nível esperado',
       'Pode ser dito em particular; o valor está na escala, não na plateia.'),
      (0, 'It is longer',
       'Length is not the point.',
       'É mais longo',
       'Tamanho não é o ponto.')])

quiz('ex-4gyrcmw1', 'drill', 'hard',
     ('At the demo, a manager says: “Huge thanks to Camila for the new booking screen!” Camila presented it; Fábio wrote most of the code and does not like attention. What went wrong?',
      'Na demonstração, uma gestora diz: “Muito obrigada à Camila pela nova tela de agendamento!” A Camila apresentou; o Fábio escreveu a maior parte do código e não gosta de atenção. O que deu errado?'),
     ('Precision, and preference.', 'Precisão, e preferência.'),
     [(1, 'The credit went to the presenter, not the author, and Fábio needed a private thank-you that said what he did',
       'Right: be precise about who did what, and use the channel the person prefers.',
       'O crédito foi para quem apresentou, não para quem fez, e o Fábio precisava de um agradecimento em particular que dissesse o que ele fez',
       'Isso: seja precisa sobre quem fez o quê, e use o canal que a pessoa prefere.'),
      (0, 'Nothing: thanking the presenter is enough',
       'The person who did the work sees it, and so does everybody who knows.',
       'Nada: agradecer quem apresenta basta',
       'Quem fez o trabalho vê, e todo mundo que sabe também vê.'),
      (0, 'She should have thanked the whole team instead',
       '“Thanks, team” avoids the wrong name and still credits nobody precisely.',
       'Ela deveria ter agradecido o time inteiro',
       '“Obrigada, time” evita o nome errado e ainda não credita ninguém com precisão.'),
      (0, 'Praise should never be given at a demo',
       'Demos are a fine place for public recognition, done precisely.',
       'Elogio nunca deveria ser dado numa demonstração',
       'Demonstrações são um bom lugar para reconhecimento público, feito com precisão.')])
