"""Lesson 10: when feedback becomes a performance conversation."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-8eh0ppjw')

order('ex-2ty9sret', 'the-line', 'easy',
      ('Put Renata’s three tests in the order the figure asks them.',
       'Ponha os três testes da Renata na ordem em que a figura os faz.'),
      ('Repeated, then told, then the role.', 'Repetido, depois avisado, depois o cargo.'),
      [('Has it happened more than once?', 'Aconteceu mais de uma vez?'),
       ('Has the person had clear feedback about it?', 'A pessoa já recebeu feedback claro sobre isso?'),
       ('Does it affect what the role requires?', 'Afeta o que o cargo exige?')])

quiz('ex-kw1ac45z', 'the-line', 'easy',
     ('A behaviour has happened several times and affects what the role requires, but the manager has only ever hinted at it. What comes next?',
      'Um comportamento aconteceu várias vezes e afeta o que o cargo exige, mas a gestora só fez indiretas sobre ele. O que vem a seguir?'),
     ('Hints do not count.', 'Indiretas não contam.'),
     [(1, 'Clear feedback',
       'Right: the second test fails, so the next step is clear feedback, not a performance conversation.',
       'Feedback claro',
       'Isso: o segundo teste falha, então o próximo passo é feedback claro, não uma conversa de desempenho.'),
      (0, 'A performance conversation, since two of the three tests are met',
       'All three are needed; without clear feedback the person has never been told plainly.',
       'Uma conversa de desempenho, já que dois dos três testes passam',
       'As três são necessárias; sem feedback claro, a pessoa nunca ouviu com clareza.'),
      (0, 'An improvement plan',
       'That is far further down the road, and lesson 20 covers it.',
       'Um plano de melhoria',
       'Isso fica muito mais adiante, e a aula 20 trata disso.'),
      (0, 'Another hint, a little stronger',
       'Hints are what failed; clear means specific, said, and written.',
       'Outra indireta, um pouco mais forte',
       'Indiretas foram o que falhou; claro quer dizer específico, dito e escrito.')])

quiz('ex-vp7ad7h9', 'the-line', 'medium',
     ('Why does the lesson say waiting too long costs the person most of all?',
      'Por que a aula diz que esperar demais custa sobretudo à pessoa?'),
     ('“This has been a problem for a year.”', '“Isso é um problema há um ano.”'),
     [(1, 'They lose the time in which they could have fixed it, and every mild comment told them things were basically fine',
       'Right: by the time it is named, the person has lost a year and has every right to ask why nobody said so.',
       'Perde o tempo em que poderia ter corrigido, e cada comentário leve dizia que no fundo estava tudo bem',
       'Isso: quando o assunto é nomeado, a pessoa perdeu um ano e tem todo direito de perguntar por que ninguém disse.'),
      (0, 'Their salary is frozen while the manager waits',
       'Nothing about salary.',
       'O salário dela fica congelado enquanto a gestora espera',
       'Nada sobre salário.'),
      (0, 'Because the manager will be angrier when it finally comes out',
       'The cost described is the person’s lost time, not the manager’s mood.',
       'Porque a gestora vai estar mais irritada quando finalmente falar',
       'O custo descrito é o tempo perdido da pessoa, não o humor da gestora.'),
      (0, 'The team forgets the examples',
       'Forgetting is a risk, but not the cost the lesson names.',
       'O time esquece os exemplos',
       'Esquecer é um risco, mas não o custo que a aula nomeia.')])

mc('ex-jskne7ne', 'the-line', 'medium',
   ('Which of Marcos’s observations did Renata bring to the conversation? Choose all that apply.',
    'Quais observações sobre o Marcos a Renata levou para a conversa? Marque todas que se aplicam.'),
   ('Three things over two months.', 'Três coisas em dois meses.'),
   [(1, 'Two weeks stuck on the notification upgrade without saying so', 'Yes.',
     'Duas semanas travado na atualização de notificações sem dizer nada', 'Sim.'),
    (1, 'Two tickets estimated at three days that took over two weeks each', 'Yes.',
     'Dois tickets estimados em três dias que levaram mais de duas semanas cada', 'Sim.'),
    (1, 'A page acknowledged and not acted on for forty minutes', 'Yes.',
     'Um chamado reconhecido e só tratado quarenta minutos depois', 'Sim.'),
    (0, 'His empty section in the one-to-one document', 'No: that is information about the meeting, not a performance observation.',
     'A seção vazia dele no documento de 1:1', 'Não: isso é informação sobre a reunião, não uma observação de desempenho.'),
    (0, 'What was going on in his life outside work', 'No: she did not know, and it is not hers to raise as evidence.',
     'O que estava acontecendo na vida dele fora do trabalho', 'Não: ela não sabia, e não cabe a ela levantar isso como evidência.')])

quiz('ex-7rzycwrq', 'naming-it', 'easy',
     ('What is the one job of the first performance conversation?',
      'Qual é a única tarefa da primeira conversa de desempenho?'),
     ('What should the person leave knowing?', 'O que a pessoa deveria saber ao sair?'),
     [(1, 'That there is a concern, what it is, and what happens next',
       'Right: everything else is secondary to that knowledge surviving the meeting.',
       'Que há uma preocupação, qual é, e o que acontece em seguida',
       'Isso: todo o resto é secundário a esse saber sobreviver à reunião.'),
      (0, 'To agree on an improvement plan',
       'Renata was nowhere near a plan, and mentioning one would have been a threat.',
       'Combinar um plano de melhoria',
       'A Renata estava longe de um plano, e mencioná-lo seria uma ameaça.'),
      (0, 'To find out the cause, so that the manager can decide by the end of the meeting what to do',
       'She listened for causes, but deciding is lesson 19’s work, after diagnosis.',
       'Descobrir a causa, para a gestora decidir até o fim da reunião o que fazer',
       'Ela escutou causas, mas decidir é trabalho da aula 19, depois do diagnóstico.'),
      (0, 'To keep the person motivated',
       'Motivation matters, but softening the message for it is how the meeting fails.',
       'Manter a pessoa motivada',
       'Motivação importa, mas amaciar a mensagem por ela é como a reunião falha.')])

quiz('ex-bv6aeame', 'naming-it', 'medium',
     ('Why did Renata tell Marcos the day before what the meeting was for?',
      'Por que a Renata disse ao Marcos no dia anterior para que era a reunião?'),
     ('What would it do to the one-to-ones otherwise?', 'O que isso faria com as 1:1 de outro jeito?'),
     [(1, 'So he would not learn to dread every routine one-to-one',
       'Right: a serious conversation sprung inside a routine meeting makes every routine meeting feel dangerous.',
       'Para ele não aprender a temer toda 1:1 de rotina',
       'Isso: uma conversa séria jogada numa reunião de rotina faz toda reunião de rotina parecer perigosa.'),
      (0, 'Company policy requires a day’s notice',
       'No policy is mentioned; the reason is the one-to-ones.',
       'A política da empresa exige um dia de aviso',
       'Nenhuma política é mencionada; o motivo são as 1:1.'),
      (0, 'So he could prepare a defence of each example, with evidence of his own',
       'The point is the pattern, and she wanted to avoid arguing each instance.',
       'Para ele preparar uma defesa de cada exemplo, com evidências próprias',
       'O ponto é o padrão, e ela queria evitar discutir cada caso.'),
      (0, 'So Sônia could attend',
       'Sônia did not attend; Renata told her afterwards.',
       'Para a Sônia poder participar',
       'A Sônia não participou; a Renata contou a ela depois.')])

match('ex-zm642tcc', 'naming-it', 'medium',
      ('Match each way the message gets lost with what it looks like.',
       'Ligue cada jeito de a mensagem se perder com a cara que ele tem.'),
      ('Three failures.', 'Três falhas.'),
      [('burying it', 'ten minutes of small talk and the concern in the last five',
        'enterrá-la', 'dez minutos de conversa fiada e a preocupação nos últimos cinco'),
       ('softening it into a suggestion', '“it might be worth thinking about your estimates”',
        'amaciá-la até virar sugestão', '“talvez valha pensar nas suas estimativas”'),
       ('arguing about each instance', 'the meeting spent on whether the upgrade was his fault',
        'discutir cada caso', 'a reunião gasta discutindo se a atualização foi culpa dele')],
      [('naming the pattern in the first minute', 'nomear o padrão no primeiro minuto')])

quiz('ex-v1k850x1', 'naming-it', 'medium',
     ('Marcos disputes the first example. What did Renata plan to say?',
      'O Marcos contesta o primeiro exemplo. O que a Renata planejava dizer?'),
     ('The pattern, not any one example.', 'O padrão, não um exemplo.'),
     [(1, '“We might see that one differently. What I want us to look at is the three together.”',
       'Right: she keeps the conversation on the pattern instead of litigating each case.',
       '“Talvez a gente veja esse de jeitos diferentes. O que eu quero que a gente olhe são os três juntos.”',
       'Isso: ela mantém a conversa no padrão em vez de julgar cada caso.'),
      (0, '“I have the dates.”',
       'Winning the argument about one example is not the point.',
       '“Eu tenho as datas.”',
       'Ganhar a discussão sobre um exemplo não é o ponto.'),
      (0, '“Fine, let’s drop it.”',
       'Dropping it erases the purpose of the meeting.',
       '“Tudo bem, vamos deixar para lá.”',
       'Deixar para lá apaga o propósito da reunião.'),
      (0, '“Let’s go through the upgrade in detail.”',
       'That is the third way the message gets lost.',
       '“Vamos repassar a atualização em detalhe.”',
       'Esse é o terceiro jeito de a mensagem se perder.')])

quiz('ex-xfr3rp5s', 'naming-it', 'hard',
     ('Why did Renata avoid the words “performance improvement plan” in the first conversation?',
      'Por que a Renata evitou as palavras “plano de melhoria de desempenho” na primeira conversa?'),
     ('Where was she in the process?', 'Em que ponto do processo ela estava?'),
     [(1, 'She was nowhere near one, and saying it would have been a threat',
       'Right: the words would have dominated the conversation and been untrue about where things stood.',
       'Ela estava longe de um, e dizer seria uma ameaça',
       'Isso: as palavras dominariam a conversa e seriam falsas sobre onde as coisas estavam.'),
      (0, 'Plans are illegal in Brazil',
       'They are not; lesson 20 is about writing one honestly.',
       'Planos são ilegais no Brasil',
       'Não são; a aula 20 é sobre escrever um com honestidade.'),
      (0, 'Because only the people team may say those words to an employee, under Caju’s written policy',
       'No such rule appears in the lesson.',
       'Porque só o time de pessoas pode dizer essas palavras a um funcionário, pela política escrita da Caju',
       'Essa regra não aparece na aula.'),
      (0, 'She wanted to keep it vague',
       'She was deliberately clear about the concern; she avoided a term that overstated it.',
       'Ela queria manter tudo vago',
       'Ela foi clara de propósito sobre a preocupação; evitou um termo que a exagerava.')])

quiz('ex-411vsqpy', 'writing-it-down', 'easy',
     ('Which of these belongs in the written summary of a performance conversation?',
      'Qual destes pertence ao resumo escrito de uma conversa de desempenho?'),
     ('Facts both people could check.', 'Fatos que as duas pessoas conseguiriam conferir.'),
     [(1, '“Page on 14 April acknowledged at 02:10, first action at 02:50.”',
       'Right: dates and times both people can check.',
       '“Chamado de 14 de abril reconhecido às 02:10, primeira ação às 02:50.”',
       'Isso: datas e horários que as duas pessoas conseguem conferir.'),
      (0, '“Marcos is unreliable.”',
       'A conclusion, not a fact.',
       '“O Marcos não é confiável.”',
       'Uma conclusão, não um fato.'),
      (0, '“Marcos is going through a family crisis.”',
       'He chose not to explain; the summary records only that something outside work is making it hard.',
       '“O Marcos está passando por uma crise familiar.”',
       'Ele escolheu não explicar; o resumo registra só que algo fora do trabalho está dificultando.'),
      (0, '“This is a formal warning.”',
       'The summary is not a warning, and calling it one changes what the conversation was.',
       '“Esta é uma advertência formal.”',
       'O resumo não é uma advertência, e chamá-lo assim muda o que a conversa foi.')])

quiz('ex-z797whe3', 'writing-it-down', 'medium',
     ('Why did Renata tell Sônia about the conversation the same day?',
      'Por que a Renata contou à Sônia sobre a conversa no mesmo dia?'),
     ('Three reasons.', 'Três motivos.'),
     [(1, 'Process rules, support for Marcos, and consistency if it became formal',
       'Right: the company’s rules, help the manager cannot give, and fair treatment from the start.',
       'Regras do processo, apoio ao Marcos, e consistência se virasse formal',
       'Isso: as regras da empresa, ajuda que a gestora não consegue dar e tratamento justo desde o começo.'),
      (0, 'To hand the case over',
       'She did not ask Sônia to do anything; she wanted her to know.',
       'Para passar o caso adiante',
       'Ela não pediu que a Sônia fizesse nada; queria que ela soubesse.'),
      (0, 'Because Sônia needed to read the one-to-one notes in full before the summary went out',
       'Renata deliberately shared no more of the notes than was needed.',
       'Porque a Sônia precisava ler as notas de 1:1 inteiras antes de o resumo sair',
       'A Renata de propósito não compartilhou das notas mais que o necessário.'),
      (0, 'To start a dismissal',
       'Nothing had been decided, and the summary was explicitly not a step towards one.',
       'Para começar uma demissão',
       'Nada tinha sido decidido, e o resumo explicitamente não era um passo nessa direção.')])

quiz('ex-0g3r6f2e', 'writing-it-down', 'medium',
     ('Marcos replies to the summary saying the page was acknowledged at 02:15, not 02:10. What does the lesson say Renata does?',
      'O Marcos responde ao resumo dizendo que o chamado foi reconhecido às 02:15, não às 02:10. O que a aula diz que a Renata faz?'),
     ('A correction is added.', 'Uma correção é acrescentada.'),
     [(1, 'Adds the correction',
       'Right: the summary invites correction, and a correction is added rather than argued with.',
       'Acrescenta a correção',
       'Isso: o resumo convida correção, e uma correção é acrescentada, e não discutida.'),
      (0, 'Checks the logs and argues if he is wrong',
       'The point of the summary is a shared record; five minutes does not change the pattern.',
       'Confere os logs e discute se ele estiver errado',
       'O ponto do resumo é um registro compartilhado; cinco minutos não mudam o padrão.'),
      (0, 'Ignores it, since the difference is small',
       'Ignoring a correction makes the summary her version rather than a shared one.',
       'Ignora, já que a diferença é pequena',
       'Ignorar uma correção torna o resumo a versão dela, e não um registro comum.'),
      (0, 'Forwards the exchange to Sônia, so that the disagreement is on record with the people team',
       'Nothing in the lesson escalates a minor correction.',
       'Encaminha a troca à Sônia, para a discordância ficar registrada com o time de pessoas',
       'Nada na aula escala uma correção pequena.')])

cloze('ex-r62cv7g4', 'writing-it-down', 'easy',
      ('The summary records facts, not ___.',
       'O resumo registra fatos, não ___.'),
      ('What a judgement is.', 'O que um julgamento é.'),
      [(['conclusions', 'conclusion', 'judgements', 'judgments', 'opinions'], ['conclusões', 'conclusoes', 'julgamentos', 'opiniões', 'opinioes'])])

quiz('ex-hz183z7x', 'drill', 'hard',
     ('A manager has mentioned in passing, twice, that an engineer’s code reviews are slow. Now a release has slipped because of it, and the manager wants to “have the performance talk”. What would this lesson say first?',
      'Um gestor mencionou de passagem, duas vezes, que as revisões de código de uma engenheira são lentas. Agora um release atrasou por causa disso, e ele quer “ter a conversa de desempenho”. O que esta aula diria primeiro?'),
     ('Which test has not been met?', 'Que teste não foi atendido?'),
     [(1, 'Give clear feedback first',
       'Right: repeated, and affecting the role, but the second test fails.',
       'Dar feedback claro primeiro',
       'Isso: repetido, e afetando o cargo, mas o segundo teste falha.'),
      (0, 'Go ahead, since the release slipped',
       'The impact makes it urgent, not a performance conversation yet.',
       'Seguir em frente, já que o release atrasou',
       'O impacto torna urgente, mas ainda não uma conversa de desempenho.'),
      (0, 'Wait for the next review cycle',
       'Waiting is the commoner failure; clear feedback should come now.',
       'Esperar o próximo ciclo de avaliação',
       'Esperar é a falha mais comum; o feedback claro deveria vir agora.'),
      (0, 'Bring in the people team to start a plan',
       'Far too early: she has not been told plainly what is wrong.',
       'Trazer o time de pessoas para começar um plano',
       'Cedo demais: ninguém disse a ela com clareza o que está errado.')])
