"""Lesson 11: career levels."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-msd9y5r5')

quiz('ex-f3exsehk', 'what-a-ladder-is', 'easy',
     ('What is a career ladder for, by the lesson?',
      'Para que serve uma escada de carreira, pela aula?'),
     ('From a feeling to a written answer.', 'De uma sensação a uma resposta escrita.'),
     [(1, 'Turning “is this person senior?” into a question with a written answer that the person, the manager and a panel all read',
       'Right: the levels exist anyway; writing them down makes them shared and checkable.',
       'Transformar “essa pessoa é sênior?” numa pergunta com resposta escrita que a pessoa, a gestora e um comitê conseguem ler',
       'Isso: os níveis existem de qualquer jeito; escrevê-los os torna compartilhados e conferíveis.'),
      (0, 'Setting salaries',
       'Pay bands may follow levels, but the lesson’s purpose is a shared written answer.',
       'Definir salários',
       'Faixas salariais podem seguir os níveis, mas o propósito na aula é uma resposta escrita comum.'),
      (0, 'Deciding how long each level takes',
       'A ladder is not a schedule.',
       'Decidir quanto tempo leva cada nível',
       'Uma escada não é um cronograma.'),
      (0, 'Giving managers a list of boxes to tick',
       'The lesson warns against treating it as a checklist.',
       'Dar às gestoras uma lista de caixas a marcar',
       'A aula alerta contra tratá-la como lista de verificação.')])

mc('ex-rtpmqy5h', 'what-a-ladder-is', 'medium',
   ('What goes wrong when levels exist only in managers’ heads? Choose all that apply.',
    'O que dá errado quando os níveis existem só na cabeça das gestoras? Marque todos que se aplicam.'),
   ('Three consequences.', 'Três consequências.'),
   [(1, 'The same work earns different titles under different managers', 'Yes: a career depends on who you report to.',
     'O mesmo trabalho ganha títulos diferentes com gestoras diferentes', 'Sim: a carreira depende de a quem você se reporta.'),
    (1, 'People cannot tell what to work on', 'Yes: and the confident guess best.',
     'As pessoas não sabem no que trabalhar', 'Sim: e quem é confiante adivinha melhor.'),
    (1, 'Nobody can check a decision', 'Yes: a refusal against an unwritten standard cannot be explained or appealed.',
     'Ninguém consegue conferir uma decisão', 'Sim: uma recusa contra um padrão não escrito não se explica nem se contesta.'),
    (0, 'Nobody gets promoted', 'Promotions still happen, unevenly.',
     'Ninguém é promovido', 'Promoções continuam acontecendo, de forma desigual.'),
    (0, 'Salaries go down', 'Not a consequence the lesson names.',
     'Os salários caem', 'Não é uma consequência que a aula nomeia.')])

match('ex-q5jwttdb', 'what-a-ladder-is', 'easy',
      ('Match each of Caju’s four dimensions with the question it answers.',
       'Ligue cada uma das quatro dimensões da Caju à pergunta que ela responde.'),
      ('Scope, autonomy, influence, craft.', 'Escopo, autonomia, influência, ofício.'),
      [('scope', 'how big a piece of work can this person own?',
        'escopo', 'de que tamanho é o trabalho que essa pessoa consegue assumir?'),
       ('autonomy', 'how clear must the problem be before they run with it?',
        'autonomia', 'quão claro o problema precisa estar para ela tocar sozinha?'),
       ('influence', 'whose work, beyond theirs, gets better because of them?',
        'influência', 'o trabalho de quem, além do dela, melhora por causa dela?'),
       ('craft', 'how good is the work itself?', 'ofício', 'quão bom é o trabalho em si?')],
      [('how many years have they been in the industry?', 'há quantos anos ela está na área?')])

quiz('ex-04zkek65', 'what-a-ladder-is', 'medium',
     ('A manager tells an engineer, “Going by the ladder, you’ll be senior in eighteen months.” What is wrong with that?',
      'Uma gestora diz a um engenheiro: “Pela escada, você vai ser sênior em dezoito meses.” O que há de errado nisso?'),
     ('What the ladder does not contain.', 'O que a escada não contém.'),
     [(1, 'A ladder is not a schedule',
       'Right: nothing in it says how long a level takes, so the promise has no support.',
       'Escada não é cronograma',
       'Isso: nada nela diz quanto tempo leva um nível, então a promessa não tem base.'),
      (0, 'Eighteen months is too short for anybody to move from mid-level to senior at a company like Caju',
       'The objection is to promising a time at all, not to this particular number.',
       'Dezoito meses é pouco demais para alguém passar de pleno a sênior numa empresa como a Caju',
       'A objeção é a prometer um prazo, não a esse número em particular.'),
      (0, 'Only the panel may talk about levels',
       'Managers talk about levels all the time; this is about the promise.',
       'Só o comitê pode falar de níveis',
       'Gestoras falam de níveis o tempo todo; isto é sobre a promessa.'),
      (0, 'The ladder is revised every year',
       'True at Caju, but not the problem with the sentence.',
       'A escada é revisada todo ano',
       'Verdade na Caju, mas não é o problema da frase.')])

quiz('ex-a6bfh5g4', 'reading-senior', 'easy',
     ('What separates E3 from E2 on Caju’s ladder?',
      'O que separa E3 de E2 na escada da Caju?'),
     ('Not doing the same things better.', 'Não é fazer as mesmas coisas melhor.'),
     [(1, 'Larger scope, a vaguer starting point, and effect beyond their own work',
       'Right: an excellent E2 still needs somebody to frame the problem first.',
       'Escopo maior, ponto de partida mais vago e efeito além do próprio trabalho',
       'Isso: uma pessoa E2 excelente ainda precisa que alguém enquadre o problema antes.'),
      (0, 'More years at the company',
       'Years are deliberately not on the ladder.',
       'Mais anos na empresa',
       'Anos ficam de fora da escada de propósito.'),
      (0, 'Writing more code per week',
       'Output volume is not one of the four dimensions.',
       'Escrever mais código por semana',
       'Volume de entrega não é uma das quatro dimensões.'),
      (0, 'Fewer pull requests coming back',
       'That is in the E2 craft row already.',
       'Menos pull requests voltando',
       'Isso já está na linha de ofício de E2.')])

order('ex-khh9mpgt', 'reading-senior', 'medium',
      ('Put the three tests inside the E3 autonomy row in the order the lesson lists them.',
       'Ponha os três testes dentro da linha de autonomia de E3 na ordem em que a aula os lista.'),
      ('Problem, output, other people.', 'Problema, resultado, outras pessoas.'),
      [('The problem was ambiguous', 'O problema era ambíguo'),
       ('The output was a plan', 'O resultado foi um plano'),
       ('Other people worked from it', 'Outras pessoas trabalharam a partir dele')])

quiz('ex-0qkbsbdw', 'reading-senior', 'medium',
     ('An engineer built a feature flawlessly from a design Diego had already broken into tasks. Which E3 autonomy test does that fail?',
      'Uma engenheira construiu uma funcionalidade sem falhas a partir de um design que o Diego já tinha quebrado em tarefas. Qual teste de autonomia de E3 isso não passa?'),
     ('Who did the decomposition?', 'Quem fez a decomposição?'),
     [(1, 'The problem was ambiguous',
       'Right: somebody else broke it down, so she executed a plan, however well.',
       'O problema era ambíguo',
       'Isso: outra pessoa decompôs, então ela executou um plano, por melhor que tenha executado.'),
      (0, 'Other people worked from it',
       'That test depends on there being a plan of hers in the first place.',
       'Outras pessoas trabalharam a partir dele',
       'Esse teste depende de haver um plano dela, para começar.'),
      (0, 'The craft row, since flawless code is expected at every level including E1 and E2',
       'The craft is fine; the gap is in autonomy.',
       'A linha de ofício, já que código sem falhas é esperado em todo nível, incluindo E1 e E2',
       'O ofício está bem; a lacuna é na autonomia.'),
      (0, 'None: flawless delivery meets all three',
       'Delivery quality is not what the autonomy row measures.',
       'Nenhum: uma entrega sem falhas passa nos três',
       'A qualidade da entrega não é o que a linha de autonomia mede.')])

quiz('ex-rsvrd9f6', 'reading-senior', 'medium',
     ('Why does the lesson say counting years penalises some people unfairly?',
      'Por que a aula diz que contar anos penaliza algumas pessoas de forma injusta?'),
     ('Who has fewer years for the same growth?', 'Quem tem menos anos para o mesmo crescimento?'),
     [(1, 'Years reward starting young and never taking a break, and penalise people who had a child, cared for a parent or changed careers',
       'Right: years correlate with circumstances a company should not reward for their own sake.',
       'Anos recompensam quem começou jovem e nunca parou, e penalizam quem teve filho, cuidou de pai ou mãe ou mudou de carreira',
       'Isso: anos se correlacionam com circunstâncias que a empresa não deveria recompensar por si mesmas.'),
      (0, 'Older engineers are paid too much',
       'Pay is not the argument.',
       'Engenheiros mais velhos ganham demais',
       'Salário não é o argumento.'),
      (0, 'Years are hard to verify',
       'They are easy to verify; that is not the problem.',
       'Anos são difíceis de verificar',
       'São fáceis de verificar; esse não é o problema.'),
      (0, 'Juniors complain',
       'Not the reason given.',
       'Os juniores reclamam',
       'Não é o motivo dado.')])

quiz('ex-y8b59dsj', 'drill', 'hard',
     ('A candidate was “senior engineer” at a ten-person startup, where they owned everything. Caju levels them at E2. By the lesson, is that a contradiction?',
      'Uma candidata era “engenheira sênior” numa startup de dez pessoas, onde era dona de tudo. A Caju a nivela em E2. Pela aula, isso é uma contradição?'),
     ('The ladder describes the work.', 'A escada descreve o trabalho.'),
     [(1, 'No: the evidence is read against Caju’s row, not the old title',
       'Right: scope and expectations differ between companies, and a past title is not evidence of the row.',
       'Não: a evidência é lida contra a linha da Caju, não contra o título antigo',
       'Isso: escopo e expectativas diferem entre empresas, e um título passado não é evidência da linha.'),
      (0, 'Yes: a senior title should carry over',
       'Titles do not carry over; the work is what is levelled.',
       'Sim: um título sênior deveria ser mantido',
       'Títulos não se transferem; o que se nivela é o trabalho.'),
      (0, 'Yes, because owning everything at a startup is more scope than any area at Caju could ever offer',
       'Owning everything at ten people is not the same as owning an area, with its operation, at ninety.',
       'Sim, porque ser dona de tudo numa startup é mais escopo do que qualquer área da Caju poderia oferecer',
       'Ser dona de tudo com dez pessoas não é o mesmo que ser dona de uma área, com a operação, com noventa.'),
      (0, 'No, because startups have no real engineering',
       'The lesson makes no such claim.',
       'Não, porque startups não têm engenharia de verdade',
       'A aula não afirma nada parecido.')])

quiz('ex-wsqds61z', 'two-tracks', 'easy',
     ('Why is Caju’s M1 drawn beside E3 and E4 rather than above E3?',
      'Por que o M1 da Caju está desenhado ao lado de E3 e E4, e não acima de E3?'),
     ('Sideways, not up.', 'De lado, não para cima.'),
     [(1, 'Managing is a different job at about the same level of responsibility',
       'Right: the move is sideways, and the pay bands overlap.',
       'Gerenciar é outro trabalho, com mais ou menos a mesma responsabilidade',
       'Isso: o movimento é lateral, e as faixas salariais se sobrepõem.'),
      (0, 'Managers are paid less',
       'Bands overlap; an E4 can earn more than an M1, not that every manager earns less.',
       'Gestoras ganham menos',
       'As faixas se sobrepõem; uma E4 pode ganhar mais que uma M1, não que toda gestora ganha menos.'),
      (0, 'To save space',
       'The placement is the point of the figure.',
       'Para economizar espaço',
       'A posição é o ponto da figura.'),
      (0, 'Because only E3 engineers may become managers',
       'Nothing restricts it that way; that is where people usually start when they cross.',
       'Porque só engenheiros E3 podem virar gestores',
       'Nada restringe assim; é onde as pessoas costumam começar ao atravessar.')])

quiz('ex-4jzwpb23', 'two-tracks', 'medium',
     ('At Caju, what is true of an engineer who stays at E3 for a whole career, doing excellent work?',
      'Na Caju, o que é verdade sobre uma pessoa que fica em E3 a carreira inteira, fazendo um trabalho excelente?'),
     ('The level everybody is expected to reach.', 'O nível que todos devem alcançar.'),
     [(1, 'They are not failing',
       'Right: levels above E3 are optional, and require scope not everybody wants.',
       'Não está fracassando',
       'Isso: os níveis acima de E3 são opcionais, e exigem um escopo que nem todos querem.'),
      (0, 'They should be moved onto an improvement plan',
       'Nothing about staying at E3 is a performance problem.',
       'Deveria entrar num plano de melhoria',
       'Nada em ficar em E3 é problema de desempenho.'),
      (0, 'They will be asked to manage',
       'Management is a different job, not a destination for experienced engineers.',
       'Vai ser convidada a gerenciar',
       'Gestão é outro trabalho, não destino para quem tem experiência.'),
      (0, 'They have reached the top of the ladder and can no longer be given any new responsibilities or scope',
       'E4 and E5 exist; staying at E3 is a choice, and growth without promotion is lesson 13.',
       'Chegou ao topo da escada e não pode mais receber novas responsabilidades nem escopo',
       'E4 e E5 existem; ficar em E3 é uma escolha, e crescer sem promoção é a aula 13.')])

quiz('ex-x1c2vv7b', 'drill', 'hard',
     ('At a company you are considering, nobody can reach the highest pay band without managing people. What does the lesson conclude?',
      'Numa empresa que você está considerando, ninguém chega à faixa salarial mais alta sem gerenciar pessoas. O que a aula conclui?'),
     ('Whatever it says in words.', 'Diga ela o que disser em palavras.'),
     [(1, 'Its ladder makes management a promotion, whatever it says',
       'Right: if the top is only reachable by managing, people will manage to get there.',
       'A escada dela torna a gestão uma promoção, diga o que disser',
       'Isso: se o topo só se alcança gerenciando, as pessoas vão gerenciar para chegar lá.'),
      (0, 'Nothing: pay is separate from levels',
       'Pay is exactly where the claim becomes real or stays a slogan.',
       'Nada: salário é separado de níveis',
       'Salário é exatamente onde a afirmação vira realidade ou continua slogan.'),
      (0, 'That it has a well-designed dual track, since managers carry the most responsibility in any company',
       'The lesson argues staff and principal carry comparable scope through influence.',
       'Que ela tem uma trilha dupla bem desenhada, já que gestores carregam a maior responsabilidade em qualquer empresa',
       'A aula defende que staff e principal carregam escopo comparável por influência.'),
      (0, 'That it pays managers too much',
       'The point is about the shape of the ladder, not the size of manager pay.',
       'Que ela paga demais a gestores',
       'O ponto é o formato da escada, não o tamanho do salário de gestão.')])
