"""Lesson 12: evidence and the promotion case."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-rgwv9az2')

quiz('ex-6amd97t7', 'evidence', 'easy',
     ('Which of these counts as evidence for a promotion, by the lesson?',
      'Qual destes conta como evidência para uma promoção, pela aula?'),
     ('Something a stranger could check.', 'Algo que um estranho conseguiria conferir.'),
     [(1, 'Two other teams adopted her pattern, and say so in writing',
       'Right: specific, dated, and confirmed by people outside the team.',
       'Dois outros times adotaram o padrão dela, e dizem isso por escrito',
       'Isso: específico, datado e confirmado por gente de fora do time.'),
      (0, 'She works very hard',
       'True and irrelevant: effort is not on the ladder.',
       'Ela trabalha muito',
       'Verdade e irrelevante: esforço não está na escada.'),
      (0, 'She has been at the company for six years',
       'Tenure is deliberately left off the ladder.',
       'Ela está na empresa há seis anos',
       'Tempo de casa fica fora da escada de propósito.'),
      (0, 'She is clearly ready',
       '“Ready” is the conclusion the case has to reach, not evidence for it.',
       'Ela claramente está pronta',
       '“Pronta” é a conclusão a que o caso precisa chegar, não evidência para ela.')])

quiz('ex-82p769w7', 'evidence', 'medium',
     ('Why do most panels want to see next-level work sustained over six months to a year?',
      'Por que a maioria dos comitês quer ver o trabalho do próximo nível sustentado por seis meses a um ano?'),
     ('Once, or reliably?', 'Uma vez, ou com regularidade?'),
     [(1, 'To see a pattern',
       'Right: one excellent project shows somebody can do it once; a promotion says they do it reliably.',
       'Para ver um padrão',
       'Isso: um projeto excelente mostra que alguém consegue uma vez; uma promoção diz que faz com regularidade.'),
      (0, 'Because promotions are only processed once a year at most companies, so the window has to match',
       'Cycle timing is not the reason; it is about pattern.',
       'Porque promoções só são processadas uma vez por ano na maioria das empresas, então a janela precisa bater',
       'O momento do ciclo não é o motivo; é sobre padrão.'),
      (0, 'To make the person wait',
       'Waiting is not the purpose.',
       'Para a pessoa esperar',
       'Esperar não é o propósito.'),
      (0, 'To collect more praise for the case',
       'Praise is not evidence; varied work against different rows is.',
       'Para juntar mais elogios para o caso',
       'Elogio não é evidência; trabalho variado contra linhas diferentes é.')])

quiz('ex-4j7sv6cs', 'evidence', 'medium',
     ('Why did the one-to-one notes matter for Yara’s case?',
      'Por que as notas de 1:1 importaram para o caso da Yara?'),
     ('Vivid against vague.', 'Vívido contra vago.'),
     [(1, 'Without them, Renata would have remembered the migration and little else',
       'Right: dated notes protect the case from recency and vividness.',
       'Sem elas, a Renata lembraria da migração e de pouco mais',
       'Isso: notas datadas protegem o caso do recente e do vívido.'),
      (0, 'The panel reads them',
       'The panel reads the case; the notes are where Renata found the evidence.',
       'O comitê as lê',
       'O comitê lê o caso; as notas são onde a Renata achou a evidência.'),
      (0, 'They are required by Caju’s process',
       'No requirement is mentioned.',
       'O processo da Caju as exige',
       'Nenhuma exigência é mencionada.'),
      (0, 'They contained Yara’s own written statement of why she deserved to be promoted to staff',
       'They contained dated observations, not a statement from Yara.',
       'Elas continham a declaração escrita da Yara sobre por que merecia ser promovida a staff',
       'Elas continham observações datadas, não uma declaração da Yara.')])

match('ex-hxkc1402', 'evidence', 'medium',
      ('Match each piece of Yara’s evidence with the staff row it supports.',
       'Ligue cada evidência da Yara à linha de staff que ela sustenta.'),
      ('Scope, autonomy, influence, craft.', 'Escopo, autonomia, influência, ofício.'),
      [('the booking migration across three teams', 'scope',
        'a migração dos agendamentos entre três times', 'escopo'),
       ('the waiting-list design from an ambiguous problem', 'autonomy',
        'o design da lista de espera a partir de um problema ambíguo', 'autonomia'),
       ('two teams adopting the reminder pattern', 'influence',
        'dois times adotando o padrão dos lembretes', 'influência'),
       ('the rollback plan that was used once and worked', 'craft',
        'o plano de rollback que foi usado uma vez e funcionou', 'ofício')],
      [('tenure', 'tempo de casa')])

quiz('ex-knmytngg', 'evidence', 'hard',
     ('Sorting the evidence shows one row is thin. What does the lesson say a manager must not do?',
      'Separar a evidência mostra que uma linha está fina. O que a aula diz que uma gestora não pode fazer?'),
     ('Who has the conversation instead?', 'Quem tem a conversa no lugar dela?'),
     [(1, 'Send a thin case',
       'Right: the panel will have that conversation instead, with less care, and the no will come from strangers.',
       'Mandar um caso fino',
       'Isso: o comitê vai ter essa conversa no lugar dela, com menos cuidado, e o não vai vir de estranhos.'),
      (0, 'Tell the person which row is thin',
       'That is the most useful outcome of the conversation.',
       'Dizer à pessoa qual linha está fina',
       'Esse é o resultado mais útil da conversa.'),
      (0, 'Suggest the kind of work that would fill the gap in that row over the coming months',
       'That gives the person a plan, which the lesson recommends.',
       'Sugerir o tipo de trabalho que preencheria a lacuna dessa linha nos próximos meses',
       'Isso dá um plano à pessoa, o que a aula recomenda.'),
      (0, 'Wait another cycle',
       'Waiting with a plan is fine; the failure is sending a case that cannot pass.',
       'Esperar mais um ciclo',
       'Esperar com um plano está bem; a falha é mandar um caso que não passa.')])

order('ex-qzr4gjr0', 'writing-the-case', 'easy',
      ('Put the four parts of Caju’s promotion-case template in order.',
       'Ponha em ordem as quatro partes do modelo de caso de promoção da Caju.'),
      ('Summary first, voices last.', 'Resumo primeiro, vozes por último.'),
      [('The summary', 'O resumo'), ('One section per row of the ladder', 'Uma seção por linha da escada'),
       ('The gaps', 'As lacunas'), ('Statements from outside the team', 'Depoimentos de fora do time')])

quiz('ex-jbys8g4d', 'writing-the-case', 'medium',
     ('Why does the gaps section make a case stronger?',
      'Por que a seção de lacunas fortalece um caso?'),
     ('What happens when a panel finds a weakness itself?', 'O que acontece quando o comitê acha uma fraqueza sozinho?'),
     [(1, 'A weakness the panel finds itself makes it doubt everything else; one the manager names shows she knows the person',
       'Right: naming it first protects the credibility of the rest.',
       'Uma fraqueza que o comitê acha sozinho faz ele duvidar de todo o resto; uma que a gestora nomeia mostra que ela conhece a pessoa',
       'Isso: nomear primeiro protege a credibilidade do resto.'),
      (0, 'Panels reward modesty',
       'It is about credibility, not modesty.',
       'Comitês recompensam modéstia',
       'É sobre credibilidade, não modéstia.'),
      (0, 'It makes the case longer',
       'Length is not the point.',
       'Deixa o caso mais longo',
       'Tamanho não é o ponto.'),
      (0, 'It is required by the template',
       'It is in the template for a reason, which is the question.',
       'O modelo exige',
       'Está no modelo por um motivo, que é a pergunta.')])

quiz('ex-xceeqg42', 'writing-the-case', 'medium',
     ('“Yara is a natural leader who is always willing to help other teams.” What is wrong with it as a case paragraph?',
      '“A Yara é uma líder nata, sempre disposta a ajudar outros times.” O que há de errado nisso como parágrafo de caso?'),
     ('What does the panel learn?', 'O que o comitê aprende?'),
     [(1, 'Nothing in it is checkable; it only tells the panel that Renata likes Yara',
       'Right: the rewrite makes a claim about effect, with months, names and links.',
       'Nada nele é conferível; só diz ao comitê que a Renata gosta da Yara',
       'Isso: a reescrita faz uma afirmação sobre efeito, com meses, nomes e links.'),
      (0, 'It is untrue',
       'The lesson says every word was true.',
       'É falso',
       'A aula diz que cada palavra era verdade.'),
      (0, 'It is too short',
       'Length is not the problem; checkability is.',
       'É curto demais',
       'Tamanho não é o problema; conferibilidade é.'),
      (0, 'It should be in the summary',
       'It would be as weak there.',
       'Deveria estar no resumo',
       'Seria igualmente fraco ali.')])

match('ex-eqwm1fq1', 'writing-the-case', 'medium',
      ('Match each weak phrase with what the lesson suggests instead.',
       'Ligue cada expressão fraca ao que a aula sugere no lugar.'),
      ('Words that weaken a case.', 'Palavras que enfraquecem um caso.'),
      [('“always”, “never”', 'the specific instances', '“sempre”, “nunca”', 'os casos específicos'),
       ('“helped with”', '“designed”, “led”, “decided”', '“ajudou com”', '“desenhou”, “liderou”, “decidiu”'),
       ('“the team delivered”', 'what she did inside the team’s work', '“o time entregou”', 'o que ela fez dentro do trabalho do time'),
       ('“has potential”', 'evidence of the next level now', '“tem potencial”', 'evidência do próximo nível agora')])

quiz('ex-2zv5tkf2', 'the-panel', 'easy',
     ('Why do companies use a panel rather than letting each manager decide promotions?',
      'Por que as empresas usam um comitê em vez de deixar cada gestora decidir promoções?'),
     ('One bar.', 'Uma régua.'),
     [(1, 'To apply one bar across many managers',
       'Right: and to bring in people with no stake, which limits each manager’s biases.',
       'Para aplicar uma régua só a muitas gestoras',
       'Isso: e trazer gente sem interesse no resultado, o que limita os vieses de cada gestora.'),
      (0, 'Because managers cannot be trusted with anything that touches pay',
       'The reason is consistency and bias, not a general distrust of managers.',
       'Porque não se pode confiar a gestoras nada que toque salário',
       'O motivo é consistência e viés, não desconfiança geral das gestoras.'),
      (0, 'To slow promotions down',
       'Speed is not the purpose.',
       'Para desacelerar as promoções',
       'Velocidade não é o propósito.'),
      (0, 'Because the law requires it',
       'No law is mentioned.',
       'Porque a lei exige',
       'Nenhuma lei é mencionada.')])

quiz('ex-venrdg2s', 'the-panel', 'medium',
     ('Diego was told “not this time” after his staff case, and nothing else. What did the panel’s actual reasoning turn out to be?',
      'Disseram ao Diego “não foi desta vez” depois do caso para staff, e nada mais. Qual era de fato o raciocínio do comitê?'),
     ('Within Agenda, and beyond it.', 'Dentro do Agenda, e fora dele.'),
     [(1, 'Deep technical work within Agenda, no influence beyond it',
       'Right: specific, against a row, and something he could work on.',
       'Trabalho técnico profundo dentro do Agenda, nenhuma influência fora dele',
       'Isso: específico, contra uma linha, e algo em que ele poderia trabalhar.'),
      (0, 'He had not been at Caju long enough',
       'Tenure is not on the ladder.',
       'Ele não estava na Caju havia tempo suficiente',
       'Tempo de casa não está na escada.'),
      (0, 'His code quality was poor',
       'The case showed deep technical work; craft was not the gap.',
       'A qualidade do código dele era ruim',
       'O caso mostrava trabalho técnico profundo; ofício não era a lacuna.'),
      (0, 'There were no staff positions available that cycle, so every case in his batch was refused',
       'Nothing says so; the reasoning was about his evidence.',
       'Não havia vagas de staff naquele ciclo, então todo caso do lote dele foi recusado',
       'Nada diz isso; o raciocínio era sobre a evidência dele.')])

quiz('ex-534aeq7b', 'the-panel', 'medium',
     ('What does the lesson say a manager must never do after a no?',
      'O que a aula diz que uma gestora nunca deve fazer depois de um não?'),
     ('“I fought for you.”', '“Eu briguei por você.”'),
     [(1, 'Blame the panel',
       'Right: it teaches the process is arbitrary and gives the person nothing to work on.',
       'Culpar o comitê',
       'Isso: ensina que o processo é arbitrário e não dá à pessoa nada em que trabalhar.'),
      (0, 'Give the panel’s reasons',
       'Giving the reasons is the second part of the conversation.',
       'Dar os motivos do comitê',
       'Dar os motivos é a segunda parte da conversa.'),
      (0, 'Let the person react',
       'Room for their reaction is the fourth part.',
       'Deixar a pessoa reagir',
       'Espaço para a reação é a quarta parte.'),
      (0, 'Describe the work that would change the answer next time, without promising the outcome',
       'That is the third part, done correctly.',
       'Descrever o trabalho que mudaria a resposta da próxima vez, sem prometer o resultado',
       'Essa é a terceira parte, feita do jeito certo.')])

cloze('ex-p15q9nqa', 'the-panel', 'easy',
      ('At Caju, the manager is not in the room, so the case has to stand on its ___.',
       'Na Caju, a gestora não está na sala, então o caso precisa se sustentar ___.'),
      ('Nobody is there to explain it.', 'Ninguém está lá para explicá-lo.'),
      [(['own'], ['sozinho'])])

quiz('ex-zsxgr7yf', 'drill', 'hard',
     ('A manager’s case for a promotion to senior says: “He helped with the payments migration, always delivers, and has huge potential.” Which single change would improve it most?',
      'O caso de uma gestora para uma promoção a sênior diz: “Ele ajudou com a migração de pagamentos, sempre entrega e tem um potencial enorme.” Que mudança, sozinha, mais melhoraria o caso?'),
     ('What did he actually do?', 'O que ele de fato fez?'),
     [(1, 'Replace each phrase with what he did, when, and the result',
       'Right: “helped with”, “always” and “potential” are the weak words; specific dated work replaces all three.',
       'Trocar cada expressão pelo que ele fez, quando e com que resultado',
       'Isso: “ajudou com”, “sempre” e “potencial” são as palavras fracas; trabalho específico e datado substitui as três.'),
      (0, 'Add more praise from the team, so the panel sees how much everybody around him values his work',
       'Praise is not evidence; it would make the case warmer and no stronger.',
       'Acrescentar mais elogios do time, para o comitê ver quanto todos em volta valorizam o trabalho dele',
       'Elogio não é evidência; deixaria o caso mais caloroso e não mais forte.'),
      (0, 'Mention his years at the company',
       'Tenure is off the ladder.',
       'Mencionar os anos dele na empresa',
       'Tempo de casa fica fora da escada.'),
      (0, 'Remove the gaps section',
       'There is no gaps section, and removing one would weaken a case.',
       'Tirar a seção de lacunas',
       'Não há seção de lacunas, e tirar uma enfraqueceria o caso.')])
