"""Lesson 13: growth without promotion."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-q02zcp09')

match('ex-vvjwm08f', 'three-directions', 'easy',
      ('Match each person with the direction of growth they agreed with Renata.',
       'Ligue cada pessoa à direção de crescimento que combinou com a Renata.'),
      ('Paula, Fábio, Diego.', 'Paula, Fábio, Diego.'),
      [('Paula takes over calendar sync as well as reminders', 'scope',
        'a Paula assume a sincronização de calendário além dos lembretes', 'escopo'),
       ('Fábio leads the next database investigations', 'depth',
        'o Fábio lidera as próximas investigações de banco de dados', 'profundidade'),
       ('Diego writes up his retry design for all of engineering', 'visibility',
        'o Diego documenta o design de novas tentativas para toda a engenharia', 'visibilidade')],
      [('promotion', 'promoção')])

quiz('ex-8295g8jq', 'three-directions', 'easy',
     ('Why does the lesson say a manager who talks about growth only in terms of levels has little to offer?',
      'Por que a aula diz que uma gestora que só fala de crescimento em termos de níveis tem pouco a oferecer?'),
     ('How often does a level change?', 'Com que frequência um nível muda?'),
     [(1, 'Promotions come a handful of times in a career, so most people are not near one most of the year',
       'Right: between promotions there is still scope, depth and visibility to grow in.',
       'Promoções vêm poucas vezes numa carreira, então a maioria das pessoas não está perto de uma na maior parte do ano',
       'Isso: entre promoções ainda há escopo, profundidade e visibilidade para crescer.'),
      (0, 'Levels are not real',
       'They are real and written down; they just change rarely.',
       'Níveis não existem de verdade',
       'Eles existem e estão escritos; só mudam raramente.'),
      (0, 'Engineers do not care about levels',
       'Many do; the problem is frequency.',
       'Engenheiros não se importam com níveis',
       'Muitos se importam; o problema é a frequência.'),
      (0, 'Promotions are decided by the panel',
       'True, but not the reason given.',
       'Promoções são decididas pelo comitê',
       'Verdade, mas não o motivo dado.')])

quiz('ex-6tytbakn', 'three-directions', 'medium',
     ('What does depth need from the manager, by the lesson?',
      'Do que a profundidade precisa da gestora, pela aula?'),
     ('Fábio and the database.', 'O Fábio e o banco de dados.'),
     [(1, 'A supply of hard problems in that area, routed to the person',
       'Right: depth grows on hard problems, and the manager decides where they go.',
       'Um suprimento de problemas difíceis naquela área, encaminhados à pessoa',
       'Isso: profundidade cresce em problemas difíceis, e a gestora decide para onde eles vão.'),
      (0, 'A new title',
       'Depth is growth at the same level.',
       'Um título novo',
       'Profundidade é crescimento no mesmo nível.'),
      (0, 'Public recognition at every demo',
       'Fábio dislikes attention; depth is about the problems, not the audience.',
       'Reconhecimento público em toda demonstração',
       'O Fábio não gosta de atenção; profundidade é sobre os problemas, não sobre a plateia.'),
      (0, 'Fewer on-call shifts',
       'Not mentioned as what depth needs.',
       'Menos plantões',
       'Não é mencionado como algo de que a profundidade precisa.')])

quiz('ex-z4gwdczt', 'three-directions', 'medium',
     ('Why did Renata suggest Diego write up existing work rather than change what he worked on?',
      'Por que a Renata sugeriu ao Diego documentar trabalho que já existia em vez de mudar aquilo em que trabalhava?'),
     ('His case lacked influence beyond Agenda.', 'O caso dele não tinha influência fora do Agenda.'),
     [(1, 'Work nobody outside the team has seen cannot count beyond the team',
       'Right: the same work, made visible, becomes evidence of influence.',
       'Trabalho que ninguém fora do time viu não pode contar além do time',
       'Isso: o mesmo trabalho, tornado visível, vira evidência de influência.'),
      (0, 'His work was not good enough',
       'The panel praised his technical depth; the gap was visibility.',
       'O trabalho dele não era bom o bastante',
       'O comitê elogiou a profundidade técnica dele; a lacuna era visibilidade.'),
      (0, 'Write-ups are faster than projects',
       'Speed was not the reason.',
       'Textos são mais rápidos que projetos',
       'Velocidade não era o motivo.'),
      (0, 'Because the architecture review requires one presentation a year from each senior engineer at Caju',
       'No such requirement appears.',
       'Porque a revisão de arquitetura exige uma apresentação por ano de cada pessoa sênior da Caju',
       'Essa exigência não aparece.')])

quiz('ex-3zh0ka54', 'three-directions', 'hard',
     ('An engineer with a newborn tells Renata she wants her job to stay the same size for the next six months. What does the lesson say?',
      'Uma engenheira com um bebê recém-nascido diz à Renata que quer que o trabalho dela continue do mesmo tamanho pelos próximos seis meses. O que a aula diz?'),
     ('A person can want none of them.', 'Uma pessoa pode não querer nenhuma delas.'),
     [(1, 'That is a legitimate answer, and pushing growth on her would not help',
       'Right: stability is a valid choice for a period.',
       'É uma resposta legítima, e empurrar crescimento para ela não ajudaria',
       'Isso: estabilidade é uma escolha válida por um período.'),
      (0, 'Renata should assign a small stretch anyway',
       'That ignores what she asked for.',
       'A Renata deveria dar um pequeno desafio mesmo assim',
       'Isso ignora o que ela pediu.'),
      (0, 'It counts against her next promotion case',
       'Nothing in the lesson penalises a period of stability.',
       'Isso conta contra o próximo caso de promoção dela',
       'Nada na aula penaliza um período de estabilidade.'),
      (0, 'She should move to part-time',
       'Not suggested anywhere.',
       'Ela deveria passar a meio período',
       'Não é sugerido em lugar nenhum.')])

quiz('ex-b1bnd60a', 'glue-work', 'easy',
     ('Who named glue work, and in what?',
      'Quem deu nome ao trabalho de cola, e onde?'),
     ('2019.', '2019.'),
     [(1, 'Tanya Reilly',
       'Right.',
       'Tanya Reilly',
       'Isso.'),
      (0, 'Will Larson, in Staff Engineer',
       'Larson’s book gives the four staff shapes, not the term glue work.',
       'Will Larson, em Staff Engineer',
       'O livro de Larson traz os quatro formatos de staff, não o termo trabalho de cola.'),
      (0, 'Kim Scott, in Radical Candor',
       'Scott’s book is about caring and challenging.',
       'Kim Scott, em Radical Candor',
       'O livro de Scott é sobre se importar e desafiar.'),
      (0, 'Andy Grove, in High Output Management, when describing what makes a manager’s output',
       'Grove gave the output sum, not this term.',
       'Andy Grove, em High Output Management, ao descrever o que compõe a entrega de quem gerencia',
       'Grove deu a soma da entrega, não esse termo.')])

mc('ex-213hc5m3', 'glue-work', 'medium',
   ('Which of these are glue work, in the lesson’s sense? Choose all that apply.',
    'Quais destes são trabalho de cola, no sentido da aula? Marque todos que se aplicam.'),
   ('Keeps the team functioning; appears in nobody’s list.', 'Mantém o time funcionando; não aparece na lista de ninguém.'),
   [(1, 'Onboarding a new hire', 'Yes.', 'Integrar uma pessoa nova', 'Sim.'),
    (1, 'Keeping the runbooks current', 'Yes.', 'Manter os runbooks em dia', 'Sim.'),
    (1, 'Noticing that two people are building the same thing', 'Yes.', 'Perceber que duas pessoas estão construindo a mesma coisa', 'Sim.'),
    (0, 'Shipping the feature on the roadmap', 'No: that is the work glue makes possible, and it is counted.',
     'Entregar a funcionalidade do roadmap', 'Não: esse é o trabalho que a cola torna possível, e ele é contado.'),
    (0, 'Presenting at the architecture review', 'No: that is visibility, and it is seen by definition.',
     'Apresentar na revisão de arquitetura', 'Não: isso é visibilidade, e é visto por definição.')])

quiz('ex-pah7qfdy', 'glue-work', 'medium',
     ('Paula onboarded Thiago, and he shipped in his first week. How does the lesson suggest describing that in her record?',
      'A Paula integrou o Thiago, e ele entregou na primeira semana. Como a aula sugere descrever isso no registro dela?'),
     ('Which row of the ladder?', 'Qual linha da escada?'),
     [(1, 'As influence: she raised a teammate’s work, with the effect stated',
       'Right: glue work written with its effect against the influence row becomes evidence.',
       'Como influência: ela elevou o trabalho de um colega, com o efeito dito',
       'Isso: trabalho de cola escrito com o efeito contra a linha de influência vira evidência.'),
      (0, 'As “helping out”',
       '“Helped with” is one of the weak phrases from lesson 12.',
       'Como “dar uma mão”',
       '“Ajudou com” é uma das expressões fracas da aula 12.'),
      (0, 'It should not be in her record, since onboarding is part of each engineer’s normal duties',
       'Leaving it out is exactly how glue work holds people back.',
       'Não deveria estar no registro, já que integrar pessoas é parte das tarefas normais de cada engenheiro',
       'Deixar de fora é exatamente como o trabalho de cola segura as pessoas.'),
      (0, 'As craft',
       'Craft is about the quality of her own work; this is about others’ work.',
       'Como ofício',
       'Ofício é sobre a qualidade do trabalho dela; isto é sobre o trabalho dos outros.')])

quiz('ex-kgcavpyb', 'glue-work', 'medium',
     ('What does the lesson mean by saying glue work is not invisible but undescribed?',
      'O que a aula quer dizer ao afirmar que o trabalho de cola não é invisível, mas está sem descrição?'),
     ('Who is best placed to describe it?', 'Quem está mais bem posicionado para descrevê-lo?'),
     [(1, 'Nobody wrote it down',
       'Right: the manager is best placed to describe it, with its effect.',
       'Ninguém registrou',
       'Isso: a gestora é a mais bem posicionada para descrevê-lo, com o efeito.'),
      (0, 'Nobody does it',
       'Somebody always does it, often the same person.',
       'Ninguém o faz',
       'Alguém sempre faz, muitas vezes a mesma pessoa.'),
      (0, 'It should be done in secret',
       'Nothing suggests that.',
       'Deveria ser feito em segredo',
       'Nada sugere isso.'),
      (0, 'It belongs in a separate document from the rest of the person’s work, kept by the people team',
       'The point is to put it in the same record, as evidence.',
       'Pertence a um documento separado do resto do trabalho da pessoa, mantido pelo time de pessoas',
       'O ponto é pô-lo no mesmo registro, como evidência.')])

order('ex-s1m5x2nz', 'stretch', 'easy',
      ('Put Renata’s three sizing questions for a stretch assignment in order.',
       'Ponha em ordem as três perguntas da Renata para dimensionar um desafio.'),
      ('Direction, novelty, consequences.', 'Direção, novidade, consequências.'),
      [('Which direction does it stretch?', 'Em que direção ele estica?'),
       ('What is the one new thing?', 'Qual é a única coisa nova?'),
       ('What happens if it goes wrong?', 'O que acontece se der errado?')])

quiz('ex-kvw5z2jc', 'stretch', 'medium',
     ('Leading a first project, in an unfamiliar codebase, with another department, on a fixed date. What does the lesson call that?',
      'Liderar um primeiro projeto, num código desconhecido, com outro departamento, com data fixa. Como a aula chama isso?'),
     ('One new thing, not four.', 'Uma coisa nova, não quatro.'),
     [(1, 'A gamble',
       'Right: a stretch adds one significant unfamiliar element; this adds several.',
       'Uma aposta',
       'Isso: um desafio acrescenta um elemento desconhecido significativo; este acrescenta vários.'),
      (0, 'A well-sized stretch, since a senior person should be able to handle several unknowns at once',
       'The lesson sizes it by the number of new things, and four is too many for a first time.',
       'Um desafio bem dimensionado, já que uma pessoa sênior deveria lidar com várias incógnitas ao mesmo tempo',
       'A aula dimensiona pelo número de coisas novas, e quatro é demais para uma primeira vez.'),
      (0, 'Glue work',
       'It is a project, not glue work.',
       'Trabalho de cola',
       'É um projeto, não trabalho de cola.'),
      (0, 'Depth',
       'It stretches several ways at once, not deeper in one area.',
       'Profundidade',
       'Estica em vários sentidos ao mesmo tempo, não mais fundo numa área.')])

quiz('ex-n1ven615', 'stretch', 'medium',
     ('Why did Renata arrange for Thiago to ask Yara anything during his first project?',
      'Por que a Renata combinou que o Thiago pudesse perguntar qualquer coisa à Yara durante o primeiro projeto dele?'),
     ('A safe place to say something.', 'Um lugar seguro para dizer algo.'),
     [(1, 'He needed somewhere to say “I don’t know how” that was not his manager',
       'Right: the manager is rarely the safe place for that sentence.',
       'Ele precisava de um lugar para dizer “não sei fazer” que não fosse a gestora',
       'Isso: a gestora raramente é o lugar seguro para essa frase.'),
      (0, 'Renata was too busy',
       'She set the checkpoints herself; this is about a different kind of support.',
       'A Renata estava ocupada demais',
       'Ela mesma marcou os pontos de verificação; isto é sobre outro tipo de apoio.'),
      (0, 'Yara was going to take over the project if Thiago struggled with any part of it',
       'That would be the rescue the lesson warns against.',
       'A Yara ia assumir o projeto se o Thiago tivesse dificuldade em qualquer parte',
       'Isso seria o resgate contra o qual a aula alerta.'),
      (0, 'To give Yara visibility',
       'Not the reason given.',
       'Para dar visibilidade à Yara',
       'Não é o motivo dado.')])

cloze('ex-hqrvvk9r', 'stretch', 'easy',
      ('A stretch with no conversation afterwards is just a hard ___.',
       'Um desafio sem conversa depois é só um ___ difícil.'),
      ('A unit of time.', 'Uma unidade de tempo.'),
      [(['month'], ['mês', 'mes'])])

quiz('ex-b49apcqk', 'drill', 'hard',
     ('A team’s manager notices that one engineer runs every retrospective, writes every postmortem and onboards every new hire, while her promotion case keeps failing for “not enough technical depth”. What does this lesson suggest first?',
      'A gestora de um time percebe que uma engenheira conduz toda retrospectiva, escreve todo postmortem e integra toda pessoa nova, enquanto o caso de promoção dela continua falhando por “falta de profundidade técnica”. O que esta aula sugere primeiro?'),
     ('Rotate, record, map.', 'Rodízio, registro, ligação.'),
     [(1, 'Rotate the glue work, and record what she did with its effect against the ladder',
       'Right: spread the tax, and describe the work so it counts as evidence of influence.',
       'Fazer rodízio do trabalho de cola, e registrar o que ela fez com o efeito contra a escada',
       'Isso: espalhar o imposto, e descrever o trabalho para que conte como evidência de influência.'),
      (0, 'Tell her to stop doing glue work immediately',
       'The team still needs it done; the fix is to share it and count it.',
       'Dizer a ela que pare imediatamente com o trabalho de cola',
       'O time ainda precisa que seja feito; a correção é dividir e contar.'),
      (0, 'Agree with the panel',
       'The panel may be right about depth, but the record is missing half the picture.',
       'Concordar com o comitê',
       'O comitê pode ter razão sobre profundidade, mas falta metade do quadro no registro.'),
      (0, 'Move her into management, since glue work is what managers do',
       'Some people want that path; it should not be the default for being good at glue.',
       'Passá-la para a gestão, já que trabalho de cola é o que gestoras fazem',
       'Algumas pessoas querem esse caminho; não deveria ser o padrão para quem é boa em cola.')])
