"""Lesson 14: the job description, the funnel and the time it takes."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-9qncttjv')

quiz('ex-de1yshy3', 'the-job-description', 'easy',
     ('What did Renata write before any requirement in the job description?',
      'O que a Renata escreveu antes de qualquer requisito na descrição da vaga?'),
     ('Six months.', 'Seis meses.'),
     [(1, 'What the person will actually do in their first six months',
       'Right: every requirement then had to trace back to that paragraph.',
       'O que a pessoa vai de fato fazer nos primeiros seis meses',
       'Isso: todo requisito depois precisava se ligar a esse parágrafo.'),
      (0, 'The salary range',
       'A good thing to include, but not what came first.',
       'A faixa salarial',
       'Uma boa coisa a incluir, mas não foi o que veio primeiro.'),
      (0, 'A copy of the last description, trimmed',
       'She started again rather than editing the fourteen-requirement page.',
       'Uma cópia da última descrição, enxugada',
       'Ela recomeçou em vez de editar a página de catorze requisitos.'),
      (0, 'A list of the technologies the team uses, so candidates know what to expect on day one',
       'Technologies went into the not-required list, after the paragraph.',
       'Uma lista das tecnologias que o time usa, para as candidatas saberem o que esperar no primeiro dia',
       'Tecnologias foram para a lista de não obrigatórios, depois do parágrafo.')])

quiz('ex-08cfn7z1', 'the-job-description', 'medium',
     ('Which of these belongs in the must list for Agenda’s E2, by the lesson’s test?',
      'Qual destes pertence à lista de obrigatórios da vaga E2 do Agenda, pelo teste da aula?'),
     ('Could somebody without it do the work, with help?', 'Alguém sem isso conseguiria fazer o trabalho, com ajuda?'),
     [(1, 'Has built and run a backend service in production',
       'Right: the job is owning one, so somebody without it could not do the work.',
       'Já construiu e operou um serviço de backend em produção',
       'Isso: o trabalho é ser dona de um, então alguém sem isso não conseguiria.'),
      (0, '5+ years of Python',
       'Years of a technology predict little, and Python went in the not-required list.',
       '5+ anos de Python',
       'Anos de uma tecnologia preveem pouco, e Python foi para a lista de não obrigatórios.'),
      (0, 'Experience with time zones',
       'Useful, and learnable on the job; it was listed as not required.',
       'Experiência com fusos horários',
       'Útil, e aprendível no trabalho; foi listado como não obrigatório.'),
      (0, 'A degree in computer science or a related field from a recognised university',
       'The lesson lists a degree, when the job does not need one, as a requirement that predicts little.',
       'Um diploma em computação ou área afim de uma universidade reconhecida',
       'A aula lista o diploma, quando o trabalho não precisa dele, como requisito que prevê pouco.')])

quiz('ex-xd4msnny', 'the-job-description', 'medium',
     ('What did Gaucher, Friesen and Kay find in 2011?',
      'O que Gaucher, Friesen e Kay descobriram em 2011?'),
     ('The words change the pool.', 'As palavras mudam o grupo.'),
     [(1, 'Masculine-coded wording made jobs less appealing to women, without changing how qualified they felt',
       'Right: the wording alone changed who would apply.',
       'Linguagem de conotação masculina tornava as vagas menos atraentes para mulheres, sem mudar quão qualificadas elas se sentiam',
       'Isso: só a redação mudava quem se candidataria.'),
      (0, 'Women apply only when they meet every requirement',
       'That is the disputed HP figure, not this study.',
       'Mulheres só se candidatam quando atendem a todos os requisitos',
       'Esse é o número contestado da HP, não este estudo.'),
      (0, 'Shorter adverts get more applications',
       'Not what this study measured.',
       'Anúncios mais curtos recebem mais candidaturas',
       'Não foi o que esse estudo mediu.'),
      (0, 'Salary ranges increase applications from everyone',
       'Not this study.',
       'Faixas salariais aumentam candidaturas de todo mundo',
       'Não é esse estudo.')])

quiz('ex-mdnc7z4a', 'the-job-description', 'hard',
     ('A requirement is in the job description and no interviewer assesses it. What does the lesson call it?',
      'Um requisito está na descrição da vaga e nenhuma pessoa entrevistadora o avalia. Como a aula o chama?'),
     ('The description is the scorecard.', 'A descrição é a ficha de avaliação.'),
     [(1, 'Decoration',
       'Right: and one assessed but not in the description is a surprise to the candidate.',
       'Enfeite',
       'Isso: e um avaliado mas que não está na descrição é uma surpresa para a candidata.'),
      (0, 'A must',
       'A must is assessed; that is what makes it one.',
       'Um obrigatório',
       'Um obrigatório é avaliado; é isso que o torna um.'),
      (0, 'A filter that works before the interviews, so it does not need to be assessed again later on',
       'Nothing filters on a requirement nobody checks.',
       'Um filtro que age antes das entrevistas, então não precisa ser avaliado de novo depois',
       'Nada filtra por um requisito que ninguém confere.'),
      (0, 'Culture fit',
       'Culture fit is a different problem: an unstated criterion.',
       'Fit cultural',
       'Fit cultural é outro problema: um critério não declarado.')])

num('ex-gjhexm1q', 'the-funnel', 'easy',
    ('In Agenda’s funnel, 15 people reached the technical interview and 6 passed. What percentage passed?',
     'No funil do Agenda, 15 pessoas chegaram à entrevista técnica e 6 passaram. Que porcentagem passou?'),
    ('6 divided by 15.', '6 dividido por 15.'),
    40, 0, ('percent', 'por cento'), (['%'], ['%']))

num('ex-6wz7e835', 'the-funnel', 'medium',
    ('Agenda’s funnel started with 240 applications and ended with 1 accepted offer. How many applications per hire is that?',
     'O funil do Agenda começou com 240 candidaturas e terminou com 1 proposta aceita. Quantas candidaturas por contratação isso dá?'),
    ('Top over bottom.', 'Topo sobre base.'),
    240, 0, ('applications', 'candidaturas'), (['application'], ['candidatura']))

quiz('ex-bh5b6ne5', 'the-funnel', 'medium',
     ('Why did Caju lose one of its two offers?',
      'Por que a Caju perdeu uma das duas propostas?'),
     ('A week.', 'Uma semana.'),
     [(1, 'The candidate accepted elsewhere while Caju took a week to decide',
       'Right: a slow end to the process loses people all the earlier effort was spent on.',
       'A candidata aceitou outra proposta enquanto a Caju levava uma semana para decidir',
       'Isso: um fim de processo lento perde pessoas em quem todo o esforço anterior foi gasto.'),
      (0, 'The salary was too low',
       'The lesson gives the delay as the reason.',
       'O salário era baixo demais',
       'A aula dá a demora como motivo.'),
      (0, 'She failed a reference check',
       'Not in the story.',
       'Ela não passou na checagem de referências',
       'Não está na história.'),
      (0, 'Renata changed her mind after a second look at the candidate’s technical interview notes',
       'Nothing like that happened.',
       'A Renata mudou de ideia depois de olhar de novo as notas da entrevista técnica da candidata',
       'Nada disso aconteceu.')])

quiz('ex-zzpn89d1', 'the-funnel', 'medium',
     ('What does the lesson say a funnel that relies on referrals ends up doing?',
      'O que a aula diz que um funil que depende de indicações acaba fazendo?'),
     ('Who refers whom?', 'Quem indica quem?'),
     [(1, 'Hiring the same team again',
       'Right: referrals resemble the existing team, which is efficient and narrows the pool.',
       'Contratar o mesmo time de novo',
       'Isso: indicações se parecem com o time atual, o que é eficiente e estreita o grupo.'),
      (0, 'Hiring faster and better, which is why Renata dropped the public advert for later roles',
       'She kept the advert and widened where it went.',
       'Contratar mais rápido e melhor, por isso a Renata largou o anúncio público nas vagas seguintes',
       'Ela manteve o anúncio e ampliou para onde ele ia.'),
      (0, 'Breaking employment law',
       'Nothing illegal is suggested.',
       'Violar a lei trabalhista',
       'Nada ilegal é sugerido.'),
      (0, 'Paying referral bonuses that cost more than recruiters',
       'Cost is not the point made.',
       'Pagar bônus de indicação que custam mais que o recrutamento',
       'Custo não é o ponto levantado.')])

mc('ex-c5h7t7zy', 'the-funnel', 'medium',
   ('Which habits does the lesson give for the candidates who are not hired? Choose all that apply.',
    'Que hábitos a aula dá para as candidatas que não são contratadas? Marque todos que se aplicam.'),
   ('239 opinions of Caju.', '239 opiniões sobre a Caju.'),
   [(1, 'Everybody who spoke to somebody gets an answer', 'Yes: a short message within a week of each stage.',
     'Toda pessoa que falou com alguém recebe uma resposta', 'Sim: uma mensagem curta até uma semana depois de cada etapa.'),
    (1, 'Nobody waits more than a week between stages', 'Yes: good candidates are interviewing elsewhere.',
     'Ninguém espera mais de uma semana entre etapas', 'Sim: candidatas boas estão fazendo entrevistas em outros lugares.'),
    (1, 'A call, not a message, after the final interviews', 'Yes.',
     'Uma ligação, e não uma mensagem, depois das entrevistas finais', 'Sim.'),
    (0, 'Detailed written feedback on every interview', 'Not one of the habits in the lesson.',
     'Feedback escrito detalhado sobre cada entrevista', 'Não é um dos hábitos da aula.'),
    (0, 'A guaranteed interview for the next opening', 'Not in the lesson.',
     'Uma entrevista garantida na próxima vaga', 'Não está na aula.')])

num('ex-x3x5xnem', 'the-time-it-takes', 'medium',
    ('Six candidates reached the final interviews, each met by four interviewers for 1.5 hours including the write-up. How many interviewer hours is that?',
     'Seis candidatas chegaram às entrevistas finais, cada uma com quatro entrevistadoras por 1,5 hora incluindo o registro. Quantas horas de entrevistadoras isso dá?'),
    ('6 × 4 × 1.5.', '6 × 4 × 1,5.'),
    36, 0, ('hours', 'horas'), (['hour', 'h'], ['hora', 'h']))

quiz('ex-1m5kay0a', 'the-time-it-takes', 'easy',
     ('About how long was it from opening Agenda’s E2 role to Lucas’s first day?',
      'Quanto tempo, aproximadamente, passou entre a abertura da vaga E2 do Agenda e o primeiro dia do Lucas?'),
     ('Nine weeks plus a month of notice.', 'Nove semanas mais um mês de aviso prévio.'),
     [(1, 'Thirteen weeks',
       'Right: nine to an accepted offer, then thirty days’ notice.',
       'Treze semanas',
       'Isso: nove até a proposta aceita, depois trinta dias de aviso prévio.'),
      (0, 'Four weeks',
       'That is roughly the notice period alone.',
       'Quatro semanas',
       'Isso é mais ou menos só o aviso prévio.'),
      (0, 'Nine weeks',
       'That was to the accepted offer; the notice period came after.',
       'Nove semanas',
       'Isso foi até a proposta aceita; o aviso prévio veio depois.'),
      (0, 'Six months, counting the time for Lucas to become fully productive on the team',
       'Ramp-up came after his first day; the question is about the first day.',
       'Seis meses, contando o tempo até o Lucas ficar produtivo de vez no time',
       'O tempo de pegar ritmo veio depois do primeiro dia; a pergunta é sobre o primeiro dia.')])

quiz('ex-g984kwqy', 'the-time-it-takes', 'medium',
     ('What should Renata’s plan have assumed for a new engineer, by the lesson?',
      'O que o plano da Renata deveria ter suposto para uma pessoa engenheira nova, pela aula?'),
     ('Pessimistic-sounding, and accurate.', 'Soa pessimista, e é certo.'),
     [(1, 'A quarter to hire and a quarter to ramp up',
       'Right: by the time Lucas contributed fully, the quarter in the plan was over.',
       'Um trimestre para contratar e um trimestre para pegar ritmo',
       'Isso: quando o Lucas contribuiu por inteiro, o trimestre do plano tinha acabado.'),
      (0, 'Help from the new person in the same quarter',
       'That was the July promise to Helena, and it did not hold.',
       'Ajuda da pessoa nova no mesmo trimestre',
       'Essa foi a promessa de julho à Helena, e não se cumpriu.'),
      (0, 'Nothing, since hiring is the recruiter’s job and does not touch the team’s plans',
       'It cost the team more than two weeks of engineering hours.',
       'Nada, já que contratar é trabalho do recrutamento e não toca os planos do time',
       'Custou ao time mais de duas semanas de horas de engenharia.'),
      (0, 'Two weeks of onboarding, then full speed',
       'Lesson 18 shows ramp-up takes far longer than two weeks.',
       'Duas semanas de integração, depois velocidade total',
       'A aula 18 mostra que pegar ritmo leva muito mais que duas semanas.')])

quiz('ex-z2twzhcq', 'drill', 'hard',
     ('In week six, a candidate is strong in three interviews and weak in the one on a must. The team is behind. What reasoning does Renata use?',
      'Na sexta semana, um candidato vai bem em três entrevistas e mal na que trata de um obrigatório. O time está atrasado. Que raciocínio a Renata usa?'),
     ('Asymmetry.', 'Assimetria.'),
     [(1, 'An empty seat costs a month; a hire who cannot do the job costs far more, so the must list holds',
       'Right: the bar was written before the pressure so that a tired manager compares against a document.',
       'Uma cadeira vazia custa um mês; uma contratação que não dá conta custa muito mais, então a lista de obrigatórios vale',
       'Isso: a régua foi escrita antes da pressão para uma gestora cansada comparar com um documento.'),
      (0, 'Three of four is good enough under pressure',
       'The weak interview was on a must, which by definition he needs.',
       'Três de quatro basta sob pressão',
       'A entrevista fraca era sobre um obrigatório, que por definição ele precisa ter.'),
      (0, 'Hire him and plan an improvement plan if needed',
       'Hiring with a plan for failure is the cost the lesson warns about.',
       'Contratá-lo e planejar um plano de melhoria se precisar',
       'Contratar já com um plano para o fracasso é o custo contra o qual a aula alerta.'),
      (0, 'Ask Helena to decide',
       'The offer is Renata’s decision, per lesson 2’s page.',
       'Pedir à Helena que decida',
       'A proposta é decisão da Renata, pela página da aula 2.')])
