"""Lesson 15: structured interviews."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-a8t05jg4')

mc('ex-gbtf98fe', 'what-structure-means', 'easy',
   ('Which are the four parts of a structured interview, by the lesson? Choose all that apply.',
    'Quais são as quatro partes de uma entrevista estruturada, pela aula? Marque todas que se aplicam.'),
   ('Questions, sameness, a scale, and an order.', 'Perguntas, igualdade, uma escala e uma ordem.'),
   [(1, 'Questions come from the job', 'Yes.', 'As perguntas vêm do cargo', 'Sim.'),
    (1, 'Every candidate gets the same questions', 'Yes.', 'Toda candidata recebe as mesmas perguntas', 'Sim.'),
    (1, 'Answers are scored against an anchored scale', 'Yes.', 'As respostas são pontuadas contra uma escala ancorada', 'Sim.'),
    (1, 'Each interviewer scores alone before discussing', 'Yes.', 'Cada pessoa pontua sozinha antes de discutir', 'Sim.'),
    (0, 'The candidate chooses which questions to answer', 'No: that would make candidates incomparable.',
     'A candidata escolhe que perguntas responder', 'Não: isso tornaria as candidatas incomparáveis.')])

quiz('ex-y5jadhcj', 'what-structure-means', 'medium',
     ('Why does each of Caju’s four interviewers own one area instead of asking a bit of everything?',
      'Por que cada uma das quatro pessoas entrevistadoras da Caju é dona de uma área, em vez de perguntar um pouco de tudo?'),
     ('Impressions or evidence.', 'Impressões ou evidência.'),
     [(1, 'Four deep interviews produce four pieces of evidence; four shallow ones, overlapping impressions',
       'Right: depth on one must gives evidence that the others do not duplicate.',
       'Quatro entrevistas profundas produzem quatro evidências; quatro rasas, impressões sobrepostas',
       'Isso: profundidade num obrigatório dá evidência que as outras não duplicam.'),
      (0, 'To save time',
       'The total time is the same; what changes is what it produces.',
       'Para economizar tempo',
       'O tempo total é o mesmo; o que muda é o que ele produz.'),
      (0, 'Because interviewers are only qualified in one area',
       'Qualification is part of who gets which area, not the reason for splitting them.',
       'Porque cada pessoa só é qualificada numa área',
       'Qualificação faz parte de quem pega qual área, não do motivo para dividir.'),
      (0, 'So candidates do not get bored',
       'Not the reason given.',
       'Para as candidatas não ficarem entediadas',
       'Não é o motivo dado.')])

quiz('ex-kpf7e401', 'what-structure-means', 'medium',
     ('When does the lesson say situational questions work better than behavioural ones?',
      'Quando a aula diz que perguntas situacionais funcionam melhor que as comportamentais?'),
     ('Who may not have a past example?', 'Quem pode não ter um exemplo passado?'),
     [(1, 'For less experienced candidates',
       'Right: they may not have a past example, though the answers need a scale even more.',
       'Para candidatas com menos experiência',
       'Isso: elas podem não ter um exemplo passado, mas as respostas precisam ainda mais de uma escala.'),
      (0, 'For senior candidates, who have so many past examples that choosing one becomes a distraction',
       'Senior candidates are usually the ones with good past examples to draw on.',
       'Para candidatas sêniores, que têm tantos exemplos passados que escolher um vira distração',
       'Pessoas sêniores costumam ser justamente as que têm bons exemplos passados.'),
      (0, 'Always',
       'Behavioural questions are the premise of the method; situational ones are for a particular case.',
       'Sempre',
       'Perguntas comportamentais são a premissa do método; as situacionais servem a um caso específico.'),
      (0, 'When no scale has been written',
       'Situational questions need a scale more, not less.',
       'Quando nenhuma escala foi escrita',
       'Perguntas situacionais precisam mais de escala, não menos.')])

quiz('ex-mbjqp6pv', 'what-structure-means', 'hard',
     ('Why does Helena, the product manager, interview on the trade-off conversation?',
      'Por que a Helena, gerente de produto, entrevista na conversa sobre trade-off?'),
     ('Who receives those explanations?', 'Quem recebe essas explicações?'),
     [(1, 'She will be on the receiving end of them',
       'Right: the person the must serves is well placed to assess it.',
       'Ela vai estar do lado de quem as recebe',
       'Isso: a pessoa a quem o obrigatório serve está bem posicionada para avaliá-lo.'),
      (0, 'Product managers must be on every panel',
       'No such rule is given.',
       'Gerentes de produto precisam estar em toda banca',
       'Essa regra não aparece.'),
      (0, 'To balance the panel with somebody who is not an engineer, which candidates find reassuring',
       'Balance may be a side effect; the reason given is that she receives the explanations.',
       'Para equilibrar a banca com alguém que não é da engenharia, o que tranquiliza as candidatas',
       'Equilíbrio pode ser um efeito colateral; o motivo dado é que ela recebe as explicações.'),
      (0, 'Because Renata was busy',
       'Renata runs the fourth conversation.',
       'Porque a Renata estava ocupada',
       'A Renata conduz a quarta conversa.')])

quiz('ex-0esw9802', 'the-evidence', 'easy',
     ('What does a validity of 0 mean for a hiring method?',
      'O que uma validade de 0 significa para um método de contratação?'),
     ('A correlation.', 'Uma correlação.'),
     [(1, 'It predicts nothing',
       'Right: 1 would be perfect; the best methods sit between about 0.3 and 0.5.',
       'Não prevê nada',
       'Isso: 1 seria perfeito; os melhores métodos ficam entre cerca de 0,3 e 0,5.'),
      (0, 'It predicts perfectly',
       'That would be 1.',
       'Prevê com perfeição',
       'Isso seria 1.'),
      (0, 'It is illegal',
       'Validity is a statistical measure, not a legal status.',
       'É ilegal',
       'Validade é uma medida estatística, não um status jurídico.'),
      (0, 'It has never been studied by anybody, so nothing at all is known about how well it works',
       'A measured validity of 0 is a finding, not an absence of study.',
       'Nunca foi estudado por ninguém, então nada se sabe sobre quão bem funciona',
       'Uma validade medida de 0 é um resultado, não ausência de estudo.')])

match('ex-yxcx98j2', 'the-evidence', 'medium',
      ('Match each estimate with its source.',
       'Ligue cada estimativa à sua fonte.'),
      ('1998 and 2022.', '1998 e 2022.'),
      [('structured interviews, 0.51', 'Schmidt and Hunter, 1998',
        'entrevistas estruturadas, 0,51', 'Schmidt e Hunter, 1998'),
       ('structured interviews, about 0.42', 'Sackett and colleagues, 2022',
        'entrevistas estruturadas, cerca de 0,42', 'Sackett e colegas, 2022'),
       ('unstructured interviews, about 0.19', 'Sackett and colleagues, 2022, too',
        'entrevistas não estruturadas, cerca de 0,19', 'Sackett e colegas, 2022, também'),
       ('unstructured interviews, 0.38', 'Schmidt and Hunter, 1998, too',
        'entrevistas não estruturadas, 0,38', 'Schmidt e Hunter, 1998, também')])

quiz('ex-s2gvdd85', 'the-evidence', 'medium',
     ('An experienced interviewer says they can tell within five minutes whether a candidate is good. What does the lesson say about that?',
      'Uma pessoa experiente diz que consegue saber em cinco minutos se uma candidata é boa. O que a aula diz sobre isso?'),
     ('What does research on unstructured interviews measure?', 'O que a pesquisa sobre entrevistas não estruturadas mede?'),
     [(1, 'Research on unstructured interviews measures that intuition, and it comes out well below structure',
       'Right: the confidence is common and the evidence does not support it.',
       'A pesquisa sobre entrevistas não estruturadas mede essa intuição, e ela fica bem abaixo da estrutura',
       'Isso: a confiança é comum e a evidência não a sustenta.'),
      (0, 'Experience makes intuition reliable',
       'The research does not find that.',
       'A experiência torna a intuição confiável',
       'A pesquisa não encontra isso.'),
      (0, 'Five minutes is enough for most roles',
       'Not a claim the lesson makes.',
       'Cinco minutos bastam para a maioria dos cargos',
       'Não é uma afirmação da aula.'),
      (0, 'It is true for senior interviewers',
       'Renata’s own reaction, that the research applied to others, is the trap.',
       'É verdade para quem é sênior',
       'A reação da própria Renata, de que a pesquisa valia para os outros, é a armadilha.')])

quiz('ex-a93gec02', 'the-evidence', 'hard',
     ('A structured interview has a validity of about 0.42. What follows, by the lesson?',
      'Uma entrevista estruturada tem validade de cerca de 0,42. O que decorre disso, pela aula?'),
     ('Evidence, not a verdict.', 'Evidência, não veredito.'),
     [(1, 'Many who interview well will not perform well, so the decision needs humility',
       'Right: the best method is still noisy.',
       'Muitas que vão bem na entrevista não vão bem no trabalho, então a decisão precisa de humildade',
       'Isso: o melhor método continua ruidoso.'),
      (0, 'It predicts 42% of hires correctly',
       'A correlation is not a hit rate.',
       'Acerta 42% das contratações',
       'Uma correlação não é uma taxa de acerto.'),
      (0, 'It is worse than an unstructured interview',
       'Unstructured came out at about 0.19 in the same review.',
       'É pior que uma entrevista não estruturada',
       'A não estruturada ficou em cerca de 0,19 na mesma revisão.'),
      (0, 'It guarantees that the company’s own interview works as well as the average in the research',
       'The figures are averages; a particular interview works only if it reflects the job.',
       'Garante que a entrevista da própria empresa funciona tão bem quanto a média da pesquisa',
       'Os números são médias; uma entrevista específica só funciona se refletir o cargo.')])

quiz('ex-5xhn63tm', 'questions-that-predict-nothing', 'easy',
     ('What did Laszlo Bock say Google had found about brainteasers?',
      'O que Laszlo Bock disse que o Google tinha concluído sobre charadas?'),
     ('2013.', '2013.'),
     [(1, 'A complete waste of time',
       'Right: and that their main function was to make the interviewer feel smart.',
       'Uma completa perda de tempo',
       'Isso: e que a principal função delas era fazer quem entrevista se sentir inteligente.'),
      (0, 'The best predictor of engineering skill',
       'The opposite of what he said.',
       'O melhor preditor de habilidade de engenharia',
       'O contrário do que ele disse.'),
      (0, 'Useful only for senior roles',
       'Not what he said.',
       'Úteis só para cargos sêniores',
       'Não foi o que ele disse.'),
      (0, 'Good for measuring how candidates think under pressure, which every engineering job involves',
       'Pressure at a puzzle is not what the job asks for, which is the lesson’s point.',
       'Boas para medir como as candidatas pensam sob pressão, o que todo cargo de engenharia envolve',
       'Pressão diante de uma charada não é o que o trabalho pede, que é o ponto da aula.')])

quiz('ex-d99k12xr', 'questions-that-predict-nothing', 'medium',
     ('At the coffee machine, an interviewer asks a candidate, “Do you have kids?” What does the lesson say?',
      'Na máquina de café, um entrevistador pergunta a uma candidata: “Você tem filhos?” O que a aula diz?'),
     ('If it would not be on the sheet…', 'Se não estaria na folha…'),
     [(1, 'It must not be asked, coffee or not',
       'Right: the candidate may reasonably think it was part of the interview, and it is a discriminatory question.',
       'Não pode ser perguntado, com café ou sem',
       'Isso: a candidata pode, com razão, achar que fazia parte da entrevista, e é uma pergunta discriminatória.'),
      (0, 'It is small talk and does not count',
       'Small talk is exactly where these questions slip in.',
       'É conversa informal e não conta',
       'A conversa informal é justamente por onde essas perguntas escapam.'),
      (0, 'It is fine if asked of every candidate equally',
       'Asking everybody does not make it relevant or lawful.',
       'Tudo bem se for perguntado igualmente a toda candidata',
       'Perguntar a todas não torna relevante nem legal.'),
      (0, 'It is useful context for whether the person will be able to cover on-call weeks and holidays',
       'That is exactly the kind of inference the law forbids basing a decision on.',
       'É contexto útil para saber se a pessoa vai conseguir cobrir semanas de plantão e feriados',
       'Esse é exatamente o tipo de inferência em que a lei proíbe basear uma decisão.')])

quiz('ex-dya7v386', 'questions-that-predict-nothing', 'medium',
     ('Why does “What is your greatest weakness?” tell an interviewer little?',
      'Por que “Qual é o seu maior defeito?” diz pouco a quem entrevista?'),
     ('Prepared in advance.', 'Preparada de antemão.'),
     [(1, 'A rehearsed strength',
       'Right: candidates prepare it, and it measures preparation rather than the must list.',
       'Uma qualidade ensaiada',
       'Isso: as candidatas preparam, e ela mede preparação, não a lista de obrigatórios.'),
      (0, 'It is illegal in Brazil',
       'It is not illegal; it is uninformative.',
       'É ilegal no Brasil',
       'Não é ilegal; é pouco informativa.'),
      (0, 'Candidates refuse to answer it',
       'They answer it readily, with something prepared.',
       'As candidatas se recusam a responder',
       'Elas respondem de pronto, com algo preparado.'),
      (0, 'Because weaknesses do not matter for engineering roles as long as the code works',
       'Weaknesses matter; this question does not reveal them.',
       'Porque defeitos não importam em cargos de engenharia desde que o código funcione',
       'Defeitos importam; esta pergunta não os revela.')])

order('ex-hsq47gmq', 'writing-a-rubric', 'easy',
      ('Put the levels of Helena’s scale in order, from 1 to 4.',
       'Ponha os níveis da escala da Helena em ordem, de 1 a 4.'),
      ('Each adds one observable thing.', 'Cada um acrescenta uma coisa observável.'),
      [('No real example, or technical terms', 'Sem exemplo real, ou em termos técnicos'),
       ('A real example, still technical, unchecked', 'Um exemplo real, ainda técnico, sem checagem'),
       ('Clear, in the listener’s terms, trade-off as outcomes', 'Claro, nos termos de quem ouve, trade-off como resultados'),
       ('Adapted when not followed, knows what was decided', 'Adaptou quando não entenderam, sabe o que foi decidido')])

quiz('ex-5j2e3z4n', 'writing-a-rubric', 'medium',
     ('What makes Helena’s scale usable by two different interviewers?',
      'O que torna a escala da Helena utilizável por duas pessoas diferentes?'),
     ('Content, not feeling.', 'Conteúdo, não sensação.'),
     [(1, 'Each level describes what is in the answer, and levels differ by observable steps',
       'Right: so two people hearing the same answer land on the same number, or one apart.',
       'Cada nível descreve o que há na resposta, e os níveis diferem por passos observáveis',
       'Isso: assim duas pessoas ouvindo a mesma resposta chegam ao mesmo número, ou a um de distância.'),
      (0, 'It has four levels instead of ten',
       'The number of levels matters less than what each describes.',
       'Tem quatro níveis em vez de dez',
       'O número de níveis importa menos do que o que cada um descreve.'),
      (0, 'Helena trains every interviewer on it personally before each round',
       'A briefing helps, but the descriptions are what make it shared.',
       'A Helena treina pessoalmente cada entrevistadora antes de cada rodada',
       'Uma orientação ajuda, mas as descrições é que a tornam comum.'),
      (0, 'It uses adjectives like “strong” and “weak”',
       'Adjectives are what an anchored scale replaces.',
       'Usa adjetivos como “forte” e “fraco”',
       'Adjetivos são o que uma escala ancorada substitui.')])

quiz('ex-km4fe7w2', 'writing-a-rubric', 'medium',
     ('Halfway through the round, Helena notices many candidates misunderstand her question. What is her rule?',
      'No meio da rodada, a Helena percebe que muitas candidatas entendem a pergunta errado. Qual é a regra dela?'),
     ('Same test for everybody in a round.', 'A mesma prova para todas numa rodada.'),
     [(1, 'For the next role',
       'Right: changing it now would give later candidates a different test.',
       'Na próxima vaga',
       'Isso: mudar agora daria às candidatas seguintes uma prova diferente.'),
      (0, 'Rewrite it before the next candidate',
       'That breaks the sameness the structure depends on.',
       'Reescrever antes da próxima candidata',
       'Isso quebra a igualdade de que a estrutura depende.'),
      (0, 'Drop the question from the round entirely and score the remaining three conversations only',
       'Dropping it loses the must it assesses.',
       'Tirar a pergunta da rodada e pontuar só as três conversas restantes',
       'Tirá-la perde o obrigatório que ela avalia.'),
      (0, 'Give everybody a 3',
       'That would make the scores meaningless.',
       'Dar 3 para todo mundo',
       'Isso tornaria as notas sem sentido.')])

quiz('ex-2nkcrzhp', 'drill', 'hard',
     ('An interviewer’s note says: “4. Great communicator, really impressive, would love to work with her.” What is wrong with it?',
      'A nota de uma entrevistadora diz: “4. Ótima comunicadora, impressionante, adoraria trabalhar com ela.” O que há de errado nisso?'),
     ('A score nobody can check.', 'Uma nota que ninguém consegue conferir.'),
     [(1, 'It records impressions instead of what she said, so nobody is able to check the 4 against the scale',
       'Right: the evidence should be close to the candidate’s words, mapped to the level’s description.',
       'Registra impressões em vez do que ela disse, então ninguém consegue conferir o 4 contra a escala',
       'Isso: a evidência deveria estar perto das palavras da candidata, ligada à descrição do nível.'),
      (0, 'A 4 is never justified',
       'A 4 is fine when the answer meets the level’s description.',
       'Um 4 nunca se justifica',
       'Um 4 está bem quando a resposta cumpre a descrição do nível.'),
      (0, 'It is too short',
       'Short is fine; Helena’s note is two lines. The problem is what it contains.',
       'É curta demais',
       'Curta tudo bem; a nota da Helena tem duas linhas. O problema é o conteúdo.'),
      (0, 'It should have been written after the debrief, once the others had shared their views',
       'Scoring before the debrief is one of the four parts of structure.',
       'Deveria ter sido escrita depois da conversa de decisão, quando os outros já tivessem opinado',
       'Pontuar antes da conversa de decisão é uma das quatro partes da estrutura.')])
