"""Lesson 16: take-home, pairing or live coding."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-09z4twxg')

match('ex-gy1pc8tv', 'three-formats', 'easy',
      ('Match each format with the incidental thing it also measures.',
       'Ligue cada formato à coisa acidental que ele também mede.'),
      ('What else, besides the job?', 'O que mais, além do trabalho?'),
      [('take-home', 'how much free time the candidate has',
        'desafio em casa', 'quanto tempo livre a candidata tem'),
       ('pairing', 'comfort with being observed',
        'pareamento', 'conforto em ser observada'),
       ('live coding', 'performance under pressure, and practice at that style of problem',
        'live coding', 'desempenho sob pressão, e prática nesse estilo de problema')],
      [('how well they know the company', 'quão bem ela conhece a empresa')])

quiz('ex-51e7znbs', 'three-formats', 'easy',
     ('Which format does the lesson say is furthest from how the job is done?',
      'Que formato a aula diz que é o mais distante de como o trabalho é feito?'),
     ('A bare editor, against the clock.', 'Um editor sem nada, contra o relógio.'),
     [(1, 'Live coding',
       'Right: it has the largest incidental measurements.',
       'Live coding',
       'Isso: é o que tem as medições acidentais maiores.'),
      (0, 'The take-home, since it is done at home where nobody can see how the person really works',
       'It is the closest to how most engineering work is done.',
       'O desafio em casa, já que é feito em casa, onde ninguém vê como a pessoa trabalha de verdade',
       'É o mais próximo de como a maior parte do trabalho de engenharia é feita.'),
      (0, 'Pairing',
       'Much of the job is working on code with somebody else.',
       'Pareamento',
       'Boa parte do trabalho é trabalhar em código com outra pessoa.'),
      (0, 'They are equally far from it',
       'The lesson ranks live coding furthest.',
       'Os três estão igualmente distantes',
       'A aula põe o live coding como o mais distante.')])

quiz('ex-cw7yf107', 'three-formats', 'medium',
     ('Why does a “two-hour” take-home often become a competition in unpaid work?',
      'Por que um desafio em casa “de duas horas” muitas vezes vira uma competição de trabalho não pago?'),
     ('What candidates expect of each other.', 'O que as candidatas esperam umas das outras.'),
     [(1, 'Candidates spend longer because they know others will',
       'Right: the suggested limit stops meaning anything when everybody exceeds it.',
       'As candidatas passam do tempo porque sabem que outras vão passar',
       'Isso: o limite sugerido deixa de significar algo quando todo mundo passa dele.'),
      (0, 'Companies hide the real time limit',
       'Not the mechanism described.',
       'As empresas escondem o limite real',
       'Não é o mecanismo descrito.'),
      (0, 'Because the problems are deliberately too hard to finish in the suggested time',
       'Some are mis-sized, which the next sections address, but the lesson’s point is the competition.',
       'Porque os problemas são, de propósito, difíceis demais para terminar no tempo sugerido',
       'Alguns são mal dimensionados, o que as próximas seções tratam, mas o ponto da aula é a competição.'),
      (0, 'Interviewers ask for extra features',
       'Not mentioned.',
       'Quem entrevista pede funcionalidades extras',
       'Não é mencionado.')])

quiz('ex-f301pwrh', 'three-formats', 'medium',
     ('What does pairing depend on more than the other formats?',
      'Do que o pareamento depende mais que os outros formatos?'),
     ('The person across the screen.', 'A pessoa do outro lado da tela.'),
     [(1, 'The interviewer',
       'Right: the same hour can be collaborative or a test with an audience.',
       'De quem entrevista',
       'Isso: a mesma hora pode ser colaborativa ou uma prova com plateia.'),
      (0, 'The candidate’s home internet connection',
       'Not the lesson’s point.',
       'Da conexão de internet da candidata',
       'Não é o ponto da aula.'),
      (0, 'The language chosen',
       'Not the point either.',
       'Da linguagem escolhida',
       'Também não é o ponto.'),
      (0, 'How many hours the candidate is willing to spend preparing over the weekend before the session',
       'That is the take-home’s incidental measurement.',
       'De quantas horas a candidata se dispõe a gastar se preparando no fim de semana antes da sessão',
       'Essa é a medição acidental do desafio em casa.')])

quiz('ex-dv6s59d4', 'choosing', 'easy',
     ('Where does the lesson say the choice of format should start?',
      'Por onde a aula diz que a escolha do formato deveria começar?'),
     ('Not from habit.', 'Não pelo hábito.'),
     [(1, 'From the job',
       'Right: what the role needs to show decides which incidental measurement matters least.',
       'Pelo cargo',
       'Isso: o que o cargo precisa mostrar decide qual medição acidental importa menos.'),
      (0, 'From what the company has always used',
       'That is how most are chosen, and what the lesson argues against.',
       'Pelo que a empresa sempre usou',
       'É assim que a maioria é escolhida, e é contra isso que a aula argumenta.'),
      (0, 'From what candidates prefer',
       'Candidates’ costs matter, but the starting point is the job.',
       'Pelo que as candidatas preferem',
       'O custo para as candidatas importa, mas o ponto de partida é o cargo.'),
      (0, 'From whatever the large technology companies are currently using for similar roles',
       'Copying another company’s format is habit at one remove.',
       'Pelo que as grandes empresas de tecnologia estão usando agora para cargos parecidos',
       'Copiar o formato de outra empresa é hábito com um passo a mais.')])

mc('ex-62sa30sp', 'choosing', 'medium',
   ('What did Renata need Agenda’s technical interview to show? Choose all that apply.',
    'O que a Renata precisava que a entrevista técnica do Agenda mostrasse? Marque todas que se aplicam.'),
   ('Three things.', 'Três coisas.'),
   [(1, 'How the person approaches an unfamiliar codebase', 'Yes.', 'Como a pessoa aborda um código desconhecido', 'Sim.'),
    (1, 'Whether they write tests without being asked', 'Yes.', 'Se ela escreve testes sem que peçam', 'Sim.'),
    (1, 'How they talk through a decision with a colleague', 'Yes.', 'Como conversa sobre uma decisão com uma colega', 'Sim.'),
    (0, 'How fast they can solve an algorithm puzzle', 'No: that is what live coding shows, and the job did not need it.',
     'Quão rápido resolve um quebra-cabeça de algoritmo', 'Não: é o que o live coding mostra, e o cargo não precisava disso.'),
    (0, 'Whether they already know Python', 'No: Python was on the not-required list.',
     'Se já sabe Python', 'Não: Python estava na lista de não obrigatórios.')])

quiz('ex-cqdf82nz', 'choosing', 'medium',
     ('Why is “fixed the bug” not a row in Yara’s rubric?',
      'Por que “corrigiu o bug” não é uma linha na escala da Yara?'),
     ('Silently, without a test.', 'Em silêncio, sem teste.'),
     [(1, 'A silent fix without a test shows less of the job than a test written first and no time left to fix',
       'Right: the rubric scores approach, testing and collaboration, which is what the job needs.',
       'Uma correção silenciosa e sem teste mostra menos do cargo do que um teste escrito primeiro e sem tempo para corrigir',
       'Isso: a escala pontua abordagem, testes e colaboração, que é o que o cargo precisa.'),
      (0, 'The bug is too easy',
       'Difficulty is not the reason.',
       'O bug é fácil demais',
       'Dificuldade não é o motivo.'),
      (0, 'Because Yara fixes it herself during the session',
       'She pairs and suggests; she does not do the work.',
       'Porque a Yara mesma corrige durante a sessão',
       'Ela pareia e sugere; não faz o trabalho.'),
      (0, 'Fixing bugs is not part of the job',
       'Fixing time-zone bugs is in the first-six-months paragraph.',
       'Corrigir bugs não faz parte do cargo',
       'Corrigir bugs de fuso horário está no parágrafo dos primeiros seis meses.')])

quiz('ex-7axybp4x', 'choosing', 'hard',
     ('Why did Renata not add a take-home on top of the pairing session?',
      'Por que a Renata não acrescentou um desafio em casa além da sessão de pareamento?'),
     ('Each stage has to earn its cost.', 'Cada etapa precisa justificar o custo.'),
     [(1, 'Pairing already showed what it would add, and it would cost fifteen candidates hours of unpaid work',
       'Right: an extra stage has to earn its cost to candidates, not only to the company.',
       'O pareamento já mostrava o que ele acrescentaria, e ele custaria a quinze candidatas horas de trabalho não pago',
       'Isso: uma etapa a mais precisa justificar o custo para as candidatas, não só para a empresa.'),
      (0, 'Take-homes are illegal',
       'They are not; paying for them is one way to make them fairer.',
       'Desafios em casa são ilegais',
       'Não são; pagar por eles é um jeito de torná-los mais justos.'),
      (0, 'Yara refused to mark them',
       'Not in the lesson.',
       'A Yara se recusou a corrigi-los',
       'Não está na aula.'),
      (0, 'They cannot show anything a pairing session cannot',
       'For a role of solitary long problems, the lesson says a short paid take-home might serve better.',
       'Eles não mostram nada que uma sessão de pareamento não mostre',
       'Para um cargo de problemas longos e solitários, a aula diz que um desafio curto e pago poderia servir melhor.')])

quiz('ex-g4q85gqd', 'making-it-fair', 'easy',
     ('How does the lesson suggest checking that a take-home really takes two hours?',
      'Como a aula sugere conferir que um desafio em casa leva mesmo duas horas?'),
     ('Before it is sent out.', 'Antes de ser enviado.'),
     [(1, 'Have somebody on the team do it first',
       'Right: if the team’s engineers need four, it is a four-hour exercise.',
       'Pedir a alguém do time para fazê-lo antes',
       'Isso: se as pessoas do time precisam de quatro, é um exercício de quatro horas.'),
      (0, 'Ask candidates afterwards how long it took them',
       'Afterwards is too late, and candidates under-report.',
       'Perguntar às candidatas depois quanto tempo levaram',
       'Depois é tarde demais, e as candidatas informam a menos.'),
      (0, 'Put a timer in the repository that stops the candidate from committing after two hours',
       'Nothing like this is in the lesson.',
       'Pôr um cronômetro no repositório que impede a candidata de fazer commit depois de duas horas',
       'Nada disso está na aula.'),
      (0, 'Trust the label',
       'The label is exactly what the check is for.',
       'Confiar no rótulo',
       'O rótulo é justamente o que a checagem confere.')])

quiz('ex-p6zx38ef', 'making-it-fair', 'medium',
     ('Why does Caju say “it is fine to think aloud, be silent, look things up and ask” to every candidate?',
      'Por que a Caju diz a toda candidata que “tudo bem pensar em voz alta, ficar em silêncio, consultar e perguntar”?'),
     ('Part of the conditions.', 'Parte das condições.'),
     [(1, 'So it is part of the conditions, not a kindness some candidates get',
       'Right: the same conditions for everybody is the point.',
       'Para fazer parte das condições, e não ser uma gentileza que só algumas recebem',
       'Isso: as mesmas condições para todas é o ponto.'),
      (0, 'Lawyers require the sentence',
       'No legal requirement is mentioned.',
       'Os advogados exigem a frase',
       'Nenhuma exigência legal é mencionada.'),
      (0, 'To shorten the session',
       'Not the reason.',
       'Para encurtar a sessão',
       'Não é o motivo.'),
      (0, 'Because nervous candidates are usually the strongest engineers once they settle into the work',
       'The lesson makes no such claim; it is about equal conditions.',
       'Porque candidatas nervosas costumam ser as engenheiras mais fortes quando se acomodam no trabalho',
       'A aula não afirma nada parecido; é sobre condições iguais.')])

quiz('ex-6kkk20rh', 'making-it-fair', 'medium',
     ('A candidate with dyslexia needs more time. How does Caju’s process handle it?',
      'Uma candidata com dislexia precisa de mais tempo. Como o processo da Caju lida com isso?'),
     ('Without the interviewers needing to know why.', 'Sem que quem entrevista precise saber por quê.'),
     [(1, 'The recruiter arranges it, and interviewers do not need the reason',
       'Right: the invitation asks about adjustments, and the request goes through the recruiter.',
       'O recrutamento cuida, sem que quem entrevista saiba o motivo',
       'Isso: o convite pergunta sobre ajustes, e o pedido passa pelo recrutamento.'),
      (0, 'The candidate explains the diagnosis to the interviewer at the start of the session',
       'The process deliberately avoids that.',
       'A candidata explica o diagnóstico a quem entrevista no começo da sessão',
       'O processo evita isso de propósito.'),
      (0, 'No adjustment, for fairness to others',
       'An interview some people cannot take on equal terms measures something else; adjustments are required.',
       'Nenhum ajuste, por justiça com as outras',
       'Uma entrevista que algumas pessoas não conseguem fazer em condições iguais mede outra coisa; ajustes são exigidos.'),
      (0, 'A different, shorter problem',
       'More time on the same problem keeps the comparison fair.',
       'Um problema diferente e mais curto',
       'Mais tempo no mesmo problema mantém a comparação justa.')])

cloze('ex-a1yg33rd', 'making-it-fair', 'easy',
      ('Giving the problem in advance removes most of the cold-start ___ that live coding measures.',
       'Dar o problema antes tira quase toda a ___ de partir do zero que o live coding mede.'),
      ('What a stranger watching adds.', 'O que um estranho olhando acrescenta.'),
      [(['pressure'], ['pressão', 'pressao'])])

quiz('ex-06sewdbz', 'drill', 'hard',
     ('A company’s technical interview is a 45-minute whiteboard algorithm problem with no references, the same for every role from front-end to data. What would this lesson question first?',
      'A entrevista técnica de uma empresa é um problema de algoritmo de 45 minutos no quadro, sem consulta, igual para todo cargo, de front-end a dados. O que esta aula questionaria primeiro?'),
     ('Format follows the job.', 'O formato segue o cargo.'),
     [(1, 'Whether any of those roles needs what live coding shows more than what it measures by accident',
       'Right: the format was chosen by habit, not from what each job needs to show.',
       'Se algum desses cargos precisa do que o live coding mostra mais do que daquilo que ele mede sem querer',
       'Isso: o formato foi escolhido por hábito, não pelo que cada cargo precisa mostrar.'),
      (0, 'Whether 45 minutes is long enough',
       'The length is secondary to whether the format fits the job at all.',
       'Se 45 minutos são tempo suficiente',
       'A duração é secundária a se o formato serve ao cargo.'),
      (0, 'Whether the interviewers are senior enough',
       'Briefing matters, but the format choice comes first.',
       'Se quem entrevista é sênior o bastante',
       'A orientação importa, mas a escolha do formato vem antes.'),
      (0, 'Whether the problems are hard enough to separate strong candidates from weak ones',
       'Harder problems widen the incidental measurement, not the relevant one.',
       'Se os problemas são difíceis o bastante para separar candidatas fortes das fracas',
       'Problemas mais difíceis aumentam a medição acidental, não a relevante.')])
