"""Lesson 17: calibration and bias."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-2jjntv48')

quiz('ex-6fbx5an2', 'independent-first', 'easy',
     ('What happens in a debrief where the first speaker says “strong hire” before anybody has written anything?',
      'O que acontece numa conversa de decisão em que a primeira pessoa diz “contrataria com certeza” antes de alguém ter escrito qualquer coisa?'),
     ('Anchoring.', 'Ancoragem.'),
     [(1, 'They drift towards it',
       'Right: four interviews become one opinion held four times.',
       'Vão na direção dela',
       'Isso: quatro entrevistas viram uma opinião repetida quatro vezes.'),
      (0, 'The others argue harder against it',
       'The research on anchoring finds the opposite tendency.',
       'Os outros argumentam com mais força contra ela',
       'A pesquisa sobre ancoragem encontra a tendência oposta.'),
      (0, 'Nothing, if the interviewers are experienced and have run many debriefs together before',
       'Experience does not remove anchoring; process does.',
       'Nada, se as pessoas forem experientes e já tiverem feito muitas conversas juntas',
       'Experiência não remove a ancoragem; o processo remove.'),
      (0, 'The decision is delayed',
       'Usually it is reached faster, which is part of the problem.',
       'A decisão atrasa',
       'Em geral ela sai mais rápido, o que é parte do problema.')])

quiz('ex-neye008y', 'independent-first', 'medium',
     ('Why does Renata, the hiring manager, speak last in the debrief?',
      'Por que a Renata, a gestora que contrata, fala por último na conversa de decisão?'),
     ('Whose opinion anchors hardest?', 'A opinião de quem ancora com mais força?'),
     [(1, 'Hers is the opinion most likely to anchor the room',
       'Right: she makes the decision, so hearing her first would pull everybody towards it.',
       'A dela é a opinião que mais provavelmente ancora a sala',
       'Isso: é ela quem decide, então ouvi-la primeiro puxaria todo mundo.'),
      (0, 'Out of politeness',
       'The reason is structural, not manners.',
       'Por educação',
       'O motivo é estrutural, não de boas maneiras.'),
      (0, 'Because Caju’s hiring tool only reveals her feedback once everybody else has spoken aloud',
       'The tool hides feedback until each person submits; speaking order is Renata’s own rule.',
       'Porque a ferramenta da Caju só mostra o registro dela depois que todos falaram em voz alta',
       'A ferramenta esconde os registros até cada pessoa enviar o seu; a ordem de fala é regra da própria Renata.'),
      (0, 'She has the least evidence',
       'She interviewed too; the issue is her power over the decision.',
       'Ela tem menos evidência',
       'Ela também entrevistou; a questão é o poder dela sobre a decisão.')])

quiz('ex-a5p5zt08', 'independent-first', 'medium',
     ('Why may nobody change their written score during the debrief?',
      'Por que ninguém pode mudar a nota escrita durante a conversa de decisão?'),
     ('What would later scores measure?', 'O que notas posteriores mediriam?'),
     [(1, 'The original records what each of them thought before hearing anybody, which calibration needs',
       'Right: scores written after a discussion measure the discussion.',
       'A original registra o que pensavam antes de ouvir alguém, e a calibragem precisa disso',
       'Isso: notas escritas depois de uma discussão medem a discussão.'),
      (0, 'Changing your mind is not allowed',
       'They can say they now see it differently, and it goes in the notes.',
       'Mudar de ideia não é permitido',
       'A pessoa pode dizer que agora vê diferente, e isso vai para as notas.'),
      (0, 'The tool locks the score',
       'The rule is Renata’s, for a reason.',
       'A ferramenta trava a nota',
       'A regra é da Renata, por um motivo.'),
      (0, 'To stop the debrief from running over the thirty minutes the calendar invitation allowed',
       'Time is not the reason.',
       'Para a conversa não passar dos trinta minutos do convite na agenda',
       'Tempo não é o motivo.')])

match('ex-c4v0pr1e', 'the-biases', 'easy',
      ('Match each bias with what it does in an interview.',
       'Ligue cada viés ao que ele faz numa entrevista.'),
      ('Five effects.', 'Cinco efeitos.'),
      [('halo', 'one strong impression spreads to everything else',
        'halo', 'uma impressão forte se espalha para todo o resto'),
       ('similarity', 'people who resemble the interviewer are rated higher',
        'semelhança', 'quem se parece com quem entrevista é avaliado melhor'),
       ('confirmation', 'evidence for a first impression is sought, and evidence against discounted',
        'confirmação', 'busca-se evidência para a primeira impressão, e a contrária é descontada'),
       ('contrast', 'a candidate looks stronger after a weak one',
        'contraste', 'uma candidata parece mais forte depois de uma fraca')])

quiz('ex-y826qzb1', 'the-biases', 'medium',
     ('In Bertrand and Mullainathan’s 2004 study, what differed between the CVs?',
      'No estudo de 2004 de Bertrand e Mullainathan, o que diferia entre os currículos?'),
     ('Identical, except…', 'Idênticos, exceto…'),
     [(1, 'Only the name',
       'Right: names perceived as white got about 50% more callbacks for the same CV.',
       'Só o nome',
       'Isso: nomes percebidos como brancos receberam cerca de 50% mais retornos pelo mesmo currículo.'),
      (0, 'The university attended',
       'Everything but the name was the same.',
       'A universidade cursada',
       'Tudo menos o nome era igual.'),
      (0, 'The years of experience listed on each one, which varied from one to ten years',
       'Experience was held constant.',
       'Os anos de experiência listados em cada um, que variavam de um a dez',
       'A experiência foi mantida constante.'),
      (0, 'The photograph',
       'There were no photographs; the name was the only difference.',
       'A fotografia',
       'Não havia fotografias; o nome era a única diferença.')])

quiz('ex-6q9g4rwg', 'the-biases', 'medium',
     ('Why does the lesson say resolving to be more careful does little against bias?',
      'Por que a aula diz que decidir tomar mais cuidado faz pouco contra o viés?'),
     ('A blind spot.', 'Um ponto cego.'),
     [(1, 'They are not choices',
       'Right: nobody sees their own halo from inside it; changing the conditions works better.',
       'Não são escolhas',
       'Isso: ninguém vê o próprio halo de dentro; mudar as condições funciona melhor.'),
      (0, 'Interviewers do not care about fairness',
       'The lesson assumes good intentions and explains why they are not enough.',
       'Quem entrevista não se importa com justiça',
       'A aula supõe boas intenções e explica por que não bastam.'),
      (0, 'Because bias is rare among experienced interviewers, so there is little left for care to fix',
       'The research is mostly on people who believed they were fair.',
       'Porque o viés é raro entre pessoas experientes, então sobra pouco para o cuidado corrigir',
       'A pesquisa é sobretudo com pessoas que se achavam justas.'),
      (0, 'Care takes too long',
       'Time is not the argument.',
       'Cuidado leva tempo demais',
       'Tempo não é o argumento.')])

quiz('ex-8c6qztap', 'the-biases', 'hard',
     ('Which of the lesson’s countermeasures targets the halo effect?',
      'Qual das contramedidas da aula mira o efeito halo?'),
     ('Separate rows, before an overall view.', 'Linhas separadas, antes de uma visão geral.'),
     [(1, 'Scoring each rubric row separately, with its own evidence, before forming an overall view',
       'Right: separating the rows stops one strong impression spreading across all of them.',
       'Pontuar cada linha da escala separadamente, com a sua evidência, antes de formar uma visão geral',
       'Isso: separar as linhas impede que uma impressão forte se espalhe por todas.'),
      (0, 'Removing names from CVs',
       'That targets name-based bias at the screen.',
       'Tirar nomes dos currículos',
       'Isso mira o viés de nome na triagem.'),
      (0, 'Asking every candidate the same questions',
       'That targets confirmation.',
       'Fazer a toda candidata as mesmas perguntas',
       'Isso mira a confirmação.'),
      (0, 'Scoring against the scale',
       'That targets contrast.',
       'Pontuar contra a escala',
       'Isso mira o contraste.')])

order('ex-s22dssqq', 'the-debrief', 'medium',
      ('Put the steps of Renata’s debrief in order.',
       'Ponha em ordem os passos da conversa de decisão da Renata.'),
      ('Disagreement first, her voice last.', 'Discordância primeiro, a voz dela por último.'),
      [('Start with the score that disagrees most', 'Começar pela nota que mais discorda'),
       ('Ask for the evidence behind it', 'Pedir a evidência por trás dela'),
       ('Ask whether others saw evidence on the same point', 'Perguntar se outras pessoas viram evidência sobre o mesmo ponto'),
       ('Hear whether each person agrees', 'Ouvir se cada pessoa concorda'),
       ('Decide, and record the reasons and any dissent', 'Decidir, e registrar os motivos e as discordâncias')])

quiz('ex-v8cmmth5', 'the-debrief', 'easy',
     ('Why did Renata start Lucas’s debrief with Helena’s 2 rather than Yara’s 4?',
      'Por que a Renata começou a conversa sobre o Lucas pelo 2 da Helena, e não pelo 4 da Yara?'),
     ('Where could the decision turn?', 'Onde a decisão podia virar?'),
     [(1, 'Lowest, on a must',
       'Right: the room did not need to discuss what nobody doubted.',
       'A mais baixa',
       'Isso: a sala não precisava discutir o que ninguém duvidava.'),
      (0, 'Helena is the most senior person in the room, so her opinion should be settled first',
       'Seniority is a reason to speak later, not first.',
       'A Helena é a pessoa mais sênior da sala, então a opinião dela deveria ser resolvida primeiro',
       'Senioridade é motivo para falar depois, não primeiro.'),
      (0, 'Alphabetical order',
       'The order was chosen by where the disagreement was.',
       'Ordem alfabética',
       'A ordem foi escolhida por onde estava a discordância.'),
      (0, 'To reject Lucas quickly',
       'Lucas got the offer.',
       'Para recusar o Lucas depressa',
       'O Lucas recebeu a proposta.')])

quiz('ex-bx9xfacc', 'the-debrief', 'medium',
     ('Helena still disagreed when Renata decided to make Lucas an offer. What happened to her view?',
      'A Helena ainda discordava quando a Renata decidiu fazer a proposta ao Lucas. O que aconteceu com a opinião dela?'),
     ('More honest than unanimous.', 'Mais honesto que unânime.'),
     [(1, 'It went into the decision record',
       'Right: a recorded dissent is more honest than a unanimity reached by anchoring.',
       'Foi para o registro da decisão',
       'Isso: uma discordância registrada é mais honesta que uma unanimidade alcançada por ancoragem.'),
      (0, 'Renata asked her to change her score to a 3 so the record matched the decision',
       'Scores may not be changed in the debrief, and the dissent was kept.',
       'A Renata pediu que ela mudasse a nota para 3 para o registro bater com a decisão',
       'Notas não podem ser mudadas na conversa, e a discordância foi mantida.'),
      (0, 'It was dropped once the decision was made',
       'It was recorded, and fed the onboarding plan.',
       'Foi descartada quando a decisão foi tomada',
       'Foi registrada, e alimentou o plano de integração.'),
      (0, 'It blocked the offer',
       'The rule needed a 3 on two musts and no 1; a 2 did not block.',
       'Ela bloqueou a proposta',
       'A regra pedia 3 em dois obrigatórios e nenhum 1; um 2 não bloqueava.')])

num('ex-6x3dq4z2', 'the-debrief', 'easy',
    ('In the calibration chart, for how many of the six candidates was Diego’s score higher than everybody else’s?',
     'No gráfico de calibragem, para quantos dos seis candidatos a nota do Diego foi mais alta que a de todo mundo?'),
    ('All but one.', 'Todos menos um.'),
    5, 0, ('candidates', 'candidatos'), (['candidate'], ['candidato']))

quiz('ex-dtj2dcp1', 'the-debrief', 'medium',
     ('What did Diego find when he reread his write-ups after seeing the chart?',
      'O que o Diego descobriu ao reler os próprios registros depois de ver o gráfico?'),
     ('Liking, scored.', 'Gostar, pontuado.'),
     [(1, 'He had been scoring how much he liked talking to the candidate',
       'Right: nobody can see their own leniency without the numbers beside everybody else’s.',
       'Ele vinha pontuando o quanto tinha gostado de conversar com a pessoa',
       'Isso: ninguém enxerga a própria leniência sem os números ao lado dos de todo mundo.'),
      (0, 'His scores were accurate and the others were too harsh',
       'He agreed with the reading of the chart.',
       'As notas dele estavam certas e as dos outros eram duras demais',
       'Ele concordou com a leitura do gráfico.'),
      (0, 'The scale was badly written',
       'That is what calibration sessions find; Diego’s finding was about himself.',
       'A escala estava mal escrita',
       'Isso é o que sessões de calibragem encontram; o achado do Diego era sobre ele.'),
      (0, 'He had interviewed the strongest candidates by chance, which explained his higher scores',
       'Across six candidates, the same pattern each time is not chance in his favour.',
       'Ele tinha entrevistado por acaso as candidatas mais fortes, o que explicava as notas altas dele',
       'Em seis candidatas, o mesmo padrão toda vez não é acaso a favor dele.')])

quiz('ex-06ke96mm', 'drill', 'hard',
     ('A team’s debriefs always end in agreement within ten minutes, and the engineering director, who sits in on all of them, speaks first. What does this lesson suggest checking first?',
      'As conversas de decisão de um time sempre terminam em acordo em dez minutos, e o diretor de engenharia, que participa de todas, fala primeiro. O que esta aula sugere conferir primeiro?'),
     ('Fast agreement is not always good news.', 'Acordo rápido nem sempre é boa notícia.'),
     [(1, 'Whether the scores are written down before the debrief starts, and in what order people speak, starting with the director',
       'Right: quick unanimity behind the most senior voice is the shape of anchoring.',
       'Se as notas são escritas antes de a conversa começar, e em que ordem as pessoas falam, a começar pelo diretor',
       'Isso: unanimidade rápida atrás da voz mais sênior é o formato da ancoragem.'),
      (0, 'Nothing: quick agreement means a well-calibrated panel',
       'It may, or it may mean everybody moved to the first opinion.',
       'Nada: acordo rápido quer dizer uma banca bem calibrada',
       'Pode querer, ou pode querer dizer que todos foram para a primeira opinião.'),
      (0, 'Whether the director has enough time',
       'His time is not what the lesson points at.',
       'Se o diretor tem tempo suficiente',
       'O tempo dele não é o que a aula aponta.'),
      (0, 'Whether the debriefs should be longer, so that each interviewer gets at least fifteen minutes',
       'Length does not fix anchoring; order and written scores do.',
       'Se as conversas deveriam ser mais longas, para cada pessoa ter pelo menos quinze minutos',
       'Duração não corrige ancoragem; ordem e notas escritas corrigem.')])
