"""Lesson 18: onboarding."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-2kz31pf4')

order('ex-8qk79drq', 'before-day-one', 'easy',
      ('Put Renata’s pre-arrival list in order, from acceptance to day one.',
       'Ponha em ordem a lista da Renata antes da chegada, do aceite ao primeiro dia.'),
      ('Welcome first, everything working last.', 'Boas-vindas primeiro, tudo funcionando por último.'),
      [('A welcome message saying what the first week looks like', 'Uma mensagem de boas-vindas dizendo como é a primeira semana'),
       ('Laptop ordered and accounts requested', 'Notebook pedido e contas solicitadas'),
       ('Buddy chosen and first task written up', 'Pessoa de referência escolhida e primeira tarefa descrita'),
       ('A short message from the buddy', 'Uma mensagem curta da pessoa de referência'),
       ('Everything working before 9:00 on day one', 'Tudo funcionando antes das 9:00 do primeiro dia')])

quiz('ex-xwmy7cbm', 'before-day-one', 'medium',
     ('Why did Renata take a third of Paula’s planned work out of the sprint for Lucas’s first two weeks?',
      'Por que a Renata tirou um terço do trabalho planejado da Paula da sprint nas duas primeiras semanas do Lucas?'),
     ('A buddy in the gaps.', 'Uma referência nos buracos.'),
     [(1, 'Otherwise the new person stops asking',
       'Right: being a buddy is work, and it needs time set aside.',
       'Senão a pessoa nova para de perguntar',
       'Isso: ser referência é trabalho, e precisa de tempo reservado.'),
      (0, 'Paula was behind',
       'Nothing says so; the time was for Lucas.',
       'A Paula estava atrasada',
       'Nada diz isso; o tempo era para o Lucas.'),
      (0, 'Because Paula would be handing over the reminder service to Lucas anyway during those two weeks',
       'The handover was a reason to choose Paula, not the reason to free her time.',
       'Porque a Paula ia passar o serviço de lembretes ao Lucas de qualquer jeito naquelas duas semanas',
       'A passagem foi motivo para escolher a Paula, não para liberar o tempo dela.'),
      (0, 'Company policy',
       'Not mentioned.',
       'Política da empresa',
       'Não é mencionado.')])

mc('ex-nc22awgd', 'before-day-one', 'medium',
   ('Which properties did Renata’s choice of first task have? Choose all that apply.',
    'Que propriedades tinha a primeira tarefa escolhida pela Renata? Marque todas que se aplicam.'),
   ('Four.', 'Quatro.'),
   [(1, 'Real: finishing it would matter to somebody', 'Yes: a clinic had reported it.',
     'Real: terminá-la importaria para alguém', 'Sim: uma clínica tinha relatado.'),
    (1, 'Small enough to reach production in the first week', 'Yes.',
     'Pequena o bastante para chegar à produção na primeira semana', 'Sim.'),
    (1, 'In the area he would own', 'Yes: the reminder service.',
     'Na área que ele ia assumir', 'Sim: o serviço de lembretes.'),
    (1, 'Written up, so he could start without a briefing', 'Yes.',
     'Descrita, para ele começar sem explicação', 'Sim.'),
    (0, 'Hard enough to test whether the hire was right', 'No: the first task is not a test.',
     'Difícil o bastante para testar se a contratação foi certa', 'Não: a primeira tarefa não é uma prova.')])

quiz('ex-zrrehs8g', 'first-week', 'easy',
     ('What is the one goal of a new engineer’s first week, by the lesson?',
      'Qual é o único objetivo da primeira semana de uma pessoa engenheira nova, pela aula?'),
     ('Visitor or member.', 'Visita ou parte do time.'),
     [(1, 'A small, real change of theirs reaches production',
       'Right: it proves the setup end to end, teaches the real process and makes them part of the team.',
       'Uma mudança pequena e real dela chega à produção',
       'Isso: prova o ambiente de ponta a ponta, ensina o processo real e a torna parte do time.'),
      (0, 'Reading all the documentation',
       'Reading supports the goal; it is not the goal.',
       'Ler toda a documentação',
       'Ler apoia o objetivo; não é o objetivo.'),
      (0, 'Meeting everybody in the company, including the other teams the person will depend on later',
       'Introductions support the goal too.',
       'Conhecer as pessoas da empresa, inclusive os outros times de que a pessoa vai depender depois',
       'Apresentações também apoiam o objetivo.'),
      (0, 'Passing a technical assessment',
       'That happened before the offer.',
       'Passar numa avaliação técnica',
       'Isso aconteceu antes da proposta.')])

num('ex-zetd7vx7', 'first-week', 'easy',
    ('On which day of his first week did Lucas’s first change reach production?',
     'Em que dia da primeira semana a primeira mudança do Lucas chegou à produção?'),
    ('Monday is day one.', 'Segunda é o dia um.'),
    4, 0, ('day', 'dia'), (['days'], ['dias']))

quiz('ex-zb62n8fm', 'first-week', 'medium',
     ('Why did Renata tell Lucas, in his first week, which area the hiring panel had flagged?',
      'Por que a Renata contou ao Lucas, na primeira semana, que área a banca tinha apontado?'),
     ('Explicit from the start, with support.', 'Explícito desde o começo, com apoio.'),
     [(1, 'So the expectation was explicit and came with support, instead of surfacing in a review later',
       'Right: it avoids the surprise lesson 8 warned about.',
       'Para a expectativa ficar explícita e vir com apoio, em vez de aparecer numa avaliação depois',
       'Isso: evita a surpresa contra a qual a aula 8 alertou.'),
      (0, 'To warn him that he was on probation',
       'Nothing about probation; it came with a plan to help.',
       'Para avisar que ele estava em período de experiência',
       'Nada sobre experiência; veio com um plano de ajuda.'),
      (0, 'Because the law requires interview feedback',
       'No legal requirement is mentioned.',
       'Porque a lei exige devolutiva da entrevista',
       'Nenhuma exigência legal é mencionada.'),
      (0, 'To lower his expectations of how fast he could expect to be promoted at Caju',
       'Promotion is not part of it.',
       'Para baixar as expectativas dele sobre quão rápido poderia ser promovido na Caju',
       'Promoção não faz parte disso.')])

quiz('ex-qn9eq8ac', 'first-week', 'medium',
     ('A new hire has stopped asking questions in their third week. What does the lesson suggest?',
      'Uma pessoa recém-contratada parou de fazer perguntas na terceira semana. O que a aula sugere?'),
     ('A reason to ask, not to confront.', 'Motivo para perguntar, não para confrontar.'),
     [(1, 'Ask a question with edges in the one-to-one',
       'Right: for example, the most confusing part of the codebase so far.',
       'Fazer uma pergunta com contornos na 1:1',
       'Isso: por exemplo, a parte mais confusa do código até agora.'),
      (0, 'Assume they are settled',
       'Silence usually means they asked and felt slow.',
       'Supor que já se ambientou',
       'Silêncio em geral quer dizer que perguntou e se sentiu lenta.'),
      (0, 'Tell them to ask more questions, in front of the team, so that everybody hears it is welcome',
       'A public instruction adds pressure; the lesson suggests a question in private.',
       'Dizer, na frente do time, que pergunte mais, para o time inteiro ouvir que é bem-vindo',
       'Uma instrução pública acrescenta pressão; a aula sugere uma pergunta em particular.'),
      (0, 'Start a performance conversation',
       'Far too early, and not what the sign means.',
       'Começar uma conversa de desempenho',
       'Cedo demais, e não é o que o sinal quer dizer.')])

quiz('ex-nh0cfytr', 'thirty-sixty-ninety', 'easy',
     ('What does each row of Lucas’s three-month plan include besides what is expected?',
      'O que cada linha do plano de três meses do Lucas inclui além do que se espera?'),
     ('Without either person guessing.', 'Sem nenhum dos dois adivinhar.'),
     [(1, 'How anybody will know',
       'Right: a measurable outcome lets a check-in say on track or behind.',
       'Como alguém vai saber',
       'Isso: um resultado mensurável deixa a conversa dizer no caminho ou atrasado.'),
      (0, 'A salary review date',
       'Not part of the plan.',
       'Uma data de revisão salarial',
       'Não faz parte do plano.'),
      (0, 'The name of the person who will replace him if he falls behind',
       'Nothing like that.',
       'O nome de quem vai substituí-lo se ele atrasar',
       'Nada disso.'),
      (0, 'A list of the courses he should complete in his own time to keep up with the team',
       'Not in the plan.',
       'Uma lista de cursos que ele deveria fazer no próprio tempo para acompanhar o time',
       'Não está no plano.')])

match('ex-snwffw96', 'thirty-sixty-ninety', 'medium',
      ('Match each stage of Lucas’s plan with what was expected by then.',
       'Ligue cada etapa do plano do Lucas ao que se esperava até então.'),
      ('Fixes, ownership, leading.', 'Correções, responsabilidade, liderança.'),
      [('30 days', 'several fixes shipped; knows the deploy and the alerts',
        '30 dias', 'várias correções entregues; conhece o deploy e os alertas'),
       ('60 days', 'owns the reminder service day to day; shadowed one on-call week',
        '60 dias', 'é dono do serviço de lembretes; acompanhou uma semana de plantão'),
       ('90 days', 'led a small piece of the confirmations work; on the on-call rota',
        '90 dias', 'liderou uma parte das confirmações; está na escala de plantão')],
      [('promoted to E3', 'promovido a E3')])

quiz('ex-17c9ezzn', 'thirty-sixty-ninety', 'medium',
     ('At thirty days, Lucas was behind on alerts because there had been no incident to learn from. What did they do?',
      'Aos trinta dias, o Lucas estava atrasado nos alertas porque não tinha havido incidente para aprender. O que fizeram?'),
     ('Changing a plan is not a failure.', 'Mudar um plano não é fracasso.'),
     [(1, 'Moved it to the shadow week',
       'Right: the plan adapted to what happened, rather than inventing an exercise.',
       'Levaram para a semana de sombra',
       'Isso: o plano se adaptou ao que aconteceu, em vez de inventar um exercício.'),
      (0, 'Recorded it as a performance concern',
       'Nothing about it was a performance problem.',
       'Registraram como preocupação de desempenho',
       'Nada ali era problema de desempenho.'),
      (0, 'Triggered a fake incident in production so he could practise responding to a real alert',
       'Not what they did; they used the shadow week.',
       'Provocaram um incidente falso em produção para ele treinar a resposta a um alerta real',
       'Não foi o que fizeram; usaram a semana de sombra.'),
      (0, 'Dropped alerts from the plan',
       'They moved it, not dropped it.',
       'Tiraram os alertas do plano',
       'Mudaram de lugar, não tiraram.')])

quiz('ex-6d94b7b3', 'thirty-sixty-ninety', 'hard',
     ('A manager sees at thirty days that a new hire is well behind for reasons unrelated to onboarding, and decides to “give them time to settle in” before saying anything. What does the lesson say?',
      'Uma gestora vê aos trinta dias que uma pessoa nova está bem atrasada por motivos sem relação com a integração, e decide “dar tempo de ela se ambientar” antes de dizer qualquer coisa. O que a aula diz?'),
     ('The kindest-sounding version of a failure.', 'A versão mais gentil na aparência de uma falha.'),
     [(1, 'It is lesson 10’s failure in a kind disguise; new people are the ones who most need to hear it plainly',
       'Right: they have the least context to notice it themselves.',
       'É a falha da aula 10 com disfarce gentil; pessoas novas são as que mais precisam ouvir com clareza',
       'Isso: elas têm menos contexto para perceber sozinhas.'),
      (0, 'Waiting is right during the first ninety days, which exist precisely so that people can adjust',
       'The plan exists to make problems visible early, not to postpone them.',
       'Esperar é certo nos primeiros noventa dias, que existem justamente para as pessoas se ajustarem',
       'O plano existe para tornar problemas visíveis cedo, não para adiá-los.'),
      (0, 'The hire was a mistake and should be reversed',
       'That is a decision lessons 19 to 21 approach carefully, not at thirty days on instinct.',
       'A contratação foi um erro e deveria ser desfeita',
       'Essa é uma decisão que as aulas 19 a 21 tratam com cuidado, não aos trinta dias por instinto.'),
      (0, 'HR should handle it',
       'The manager has the conversation; HR may support.',
       'O RH deveria cuidar disso',
       'A gestora tem a conversa; o RH pode apoiar.')])

order('ex-p6vczexd', 'first-on-call', 'easy',
      ('Put the three steps of the first on-call shift in order.',
       'Ponha em ordem os três degraus do primeiro plantão.'),
      ('Watch, act with a net, act alone with a backup.', 'Observar, agir com rede, agir sozinho com apoio.'),
      [('Shadow', 'Sombra'), ('Reverse shadow', 'Sombra invertida'),
       ('Primary, with a named backup', 'Titular, com apoio nomeado')],
      ('Going straight to primary is how Thiago ended up alone at 3 a.m. with an alert nobody had explained.',
       'Ir direto para titular é como o Thiago acabou sozinho às 3 da manhã com um alerta que ninguém tinha explicado.'))

quiz('ex-pg1p4fep', 'first-on-call', 'medium',
     ('In a reverse-shadow week, who acts on a page?',
      'Numa semana de sombra invertida, quem age num chamado?'),
     ('The roles are reversed from shadowing.', 'Os papéis são invertidos em relação à sombra.'),
     [(1, 'The new person makes the calls, while the experienced engineer watches and stays ready to step in',
       'Right: the new person makes the decisions, with a safety net.',
       'A pessoa nova toma as decisões, enquanto a experiente observa e fica pronta para entrar',
       'Isso: a pessoa nova toma as decisões, com rede de segurança.'),
      (0, 'The experienced engineer',
       'That is shadowing.',
       'A pessoa experiente',
       'Isso é a sombra.'),
      (0, 'Whoever answers the page first, since both people are paged at the same moment in that week',
       'The roles are defined in advance; the new person acts.',
       'Quem atender primeiro, já que as duas são acionadas no mesmo momento naquela semana',
       'Os papéis são definidos antes; a pessoa nova age.'),
      (0, 'The manager',
       'The manager is not on the rota for this.',
       'A gestora',
       'A gestora não está na escala para isso.')])

quiz('ex-w4x3x5zc', 'first-on-call', 'medium',
     ('What has to be true of every alert before a new person can be on call alone?',
      'O que precisa ser verdade sobre todo alerta antes de uma pessoa nova poder ficar de plantão sozinha?'),
     ('What woke Thiago lacked.', 'O que faltava no alerta que acordou o Thiago.'),
     [(1, 'It has a runbook page saying what it means and what to try first',
       'Right: the team now refuses to turn on an alert without one.',
       'Tem uma página de runbook dizendo o que significa e o que tentar primeiro',
       'Isso: o time agora se recusa a ligar um alerta sem uma.'),
      (0, 'It fires at least once a week',
       'Frequency is not the requirement.',
       'Dispara pelo menos uma vez por semana',
       'Frequência não é o requisito.'),
      (0, 'It pages two people at once',
       'Only in shadow and reverse shadow.',
       'Aciona duas pessoas ao mesmo tempo',
       'Só na sombra e na sombra invertida.'),
      (0, 'It has been approved by the platform team and the director of engineering in writing',
       'Not the requirement in the lesson.',
       'Foi aprovado por escrito pelo time de plataforma e pela diretoria de engenharia',
       'Não é o requisito da aula.')])

cloze('ex-encd7tjf', 'first-on-call', 'easy',
      ('In Lucas’s first primary week, Diego was his named ___.',
       'Na primeira semana do Lucas como titular, o Diego era o ___ nomeado dele.'),
      ('Somebody who agreed to answer at any hour.', 'Alguém que aceitou atender a qualquer hora.'),
      [(['backup'], ['apoio'])])

quiz('ex-atka0cyc', 'drill', 'hard',
     ('A new hire’s first week at a company: two days without a laptop, a list of documents to read, and a first task “to be decided once you know the code”. Which single change from this lesson would help most?',
      'A primeira semana de uma pessoa nova numa empresa: dois dias sem notebook, uma lista de documentos para ler e uma primeira tarefa “a decidir quando você conhecer o código”. Que mudança desta aula, sozinha, mais ajudaria?'),
     ('The week has one goal.', 'A semana tem um objetivo.'),
     [(1, 'Pick a small, real first task before day one, so that a change of theirs reaches production that week',
       'Right: the first change is the goal the rest of the week supports, and it needs to be chosen before day one.',
       'Definir antes do primeiro dia um bug pequeno e real, para algo dele chegar à produção logo',
       'Isso: a primeira mudança é o objetivo que o resto da semana apoia, e precisa ser escolhida antes do primeiro dia.'),
      (0, 'Add more documents to the list',
       'Reading supports the goal; more of it does not replace the first change.',
       'Acrescentar mais documentos à lista',
       'Ler apoia o objetivo; ler mais não substitui a primeira mudança.'),
      (0, 'Put the new hire on the on-call rota at once, so they learn the system quickly',
       'That skips the three steps the lesson says are needed.',
       'Pôr a pessoa nova na escala de plantão de imediato, para aprender o sistema depressa',
       'Isso pula os três degraus que a aula diz serem necessários.'),
      (0, 'Shorten the first week',
       'The problem is what the week contains.',
       'Encurtar a primeira semana',
       'O problema é o que a semana contém.')])
