"""Lesson 19: diagnosing underperformance."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-wbf23vbp')

quiz('ex-qf1vtmk1', 'symptom-and-cause', 'easy',
     ('Why does the lesson compare going straight from symptom to action with treating a cough?',
      'Por que a aula compara ir direto do sintoma à ação com tratar uma tosse?'),
     ('Cold or pneumonia.', 'Resfriado ou pneumonia.'),
     [(1, 'One symptom, many causes',
       'Right: a missed estimate can come from six different places.',
       'Um sintoma, muitas causas',
       'Isso: uma estimativa estourada pode vir de seis lugares diferentes.'),
      (0, 'Because most performance problems are caused by illness',
       'Illness is one of six causes, not most of them.',
       'Porque a maioria dos problemas de desempenho é causada por doença',
       'Doença é uma de seis causas, não a maioria.'),
      (0, 'Because the manager should send the person to a doctor before any conversation about the work',
       'The comparison is about diagnosis before action, not medical referral.',
       'Porque a gestora deveria mandar a pessoa ao médico antes de qualquer conversa sobre o trabalho',
       'A comparação é sobre diagnosticar antes de agir, não sobre encaminhamento médico.'),
      (0, 'Because symptoms disappear on their own',
       'Nothing suggests waiting it out.',
       'Porque sintomas somem sozinhos',
       'Nada sugere esperar passar.')])

quiz('ex-419pb4rf', 'symptom-and-cause', 'medium',
     ('Of the six possible causes of a missed estimate, why does the lesson say managers jump to effort and ability first?',
      'Das seis causas possíveis de uma estimativa estourada, por que a aula diz que gestoras pulam primeiro para esforço e capacidade?'),
     ('Whose problem do they make it?', 'De quem eles tornam o problema?'),
     [(1, 'They are the two that make the problem the person’s',
       'Right: the other four involve the manager, the work or circumstances.',
       'São as duas que fazem do problema algo da pessoa',
       'Isso: as outras quatro envolvem a gestora, o trabalho ou as circunstâncias.'),
      (0, 'They are the most common causes, according to the research',
       'The lesson cites no frequency; it explains the jump by whose problem it becomes.',
       'São as causas mais comuns, segundo a pesquisa',
       'A aula não cita frequência; explica o salto por de quem o problema passa a ser.'),
      (0, 'They are the easiest to fix, so a manager naturally starts with them',
       'They are often the hardest to fix, and the least likely to be right.',
       'São as mais fáceis de resolver, então a gestora naturalmente começa por elas',
       'Muitas vezes são as mais difíceis, e as menos prováveis de estarem certas.'),
      (0, 'HR requires them to be considered first',
       'No such requirement.',
       'O RH exige que sejam consideradas primeiro',
       'Não existe essa exigência.')])

order('ex-0vavjzas', 'symptom-and-cause', 'easy',
      ('Put the three parts of what comes after naming the pattern in order.',
       'Ponha em ordem as três partes do que vem depois de nomear o padrão.'),
      ('Look, ask, decide.', 'Olhar, perguntar, decidir.'),
      [('Look at the causes systematically', 'Olhar as causas de forma sistemática'),
       ('Ask the person', 'Perguntar à pessoa'),
       ('Only then decide what to do', 'Só então decidir o que fazer')])

quiz('ex-0hb6amkj', 'the-diagnostic', 'easy',
     ('What is Mager and Pipe’s most famous question?',
      'Qual é a pergunta mais famosa de Mager e Pipe?'),
     ('A blunt one.', 'Uma direta.'),
     [(1, 'Could they do it if their life depended on it?',
       'Right: if yes, it is not skill; if no, encouragement will not help.',
       'Conseguiria fazer se a vida dependesse disso?',
       'Isso: se sim, não é habilidade; se não, incentivo não vai ajudar.'),
      (0, 'Do they want to do it?',
       'Motivation comes last in the sequence.',
       'A pessoa quer fazer?',
       'Motivação vem por último na sequência.'),
      (0, 'Have they been trained for it, formally, by somebody qualified to teach it?',
       'Training is a response to a skill gap, not the diagnostic question.',
       'A pessoa foi treinada para isso, formalmente, por alguém qualificado para ensinar?',
       'Treinamento é resposta a uma lacuna de habilidade, não a pergunta de diagnóstico.'),
      (0, 'Who else could do it?',
       'Not the question.',
       'Quem mais poderia fazer?',
       'Não é a pergunta.')])

quiz('ex-fpjtrc28', 'the-diagnostic', 'medium',
     ('Why are expectations and environment the first two questions in the sequence?',
      'Por que expectativas e ambiente são as duas primeiras perguntas da sequência?'),
     ('Whose responsibility?', 'Responsabilidade de quem?'),
     [(1, 'The manager’s own part',
       'Right: putting them first stops the manager skipping straight to the person.',
       'A parte da própria gestora',
       'Isso: pô-las primeiro impede a gestora de pular direto para a pessoa.'),
      (0, 'They are the quickest to check',
       'Speed is not the reason for the order.',
       'São as mais rápidas de conferir',
       'Velocidade não é o motivo da ordem.'),
      (0, 'Mager and Pipe put them in that order in their original flowchart, and the lesson copies it exactly',
       'The lesson adapts their idea, and explains its own ordering.',
       'Mager e Pipe as puseram nessa ordem no fluxograma original, e a aula copia exatamente',
       'A aula adapta a ideia deles, e explica a própria ordem.'),
      (0, 'They are the most common causes',
       'The reason given is whose responsibility they are.',
       'São as causas mais comuns',
       'O motivo dado é de quem é a responsabilidade.')])

quiz('ex-mf21d8jc', 'the-diagnostic', 'medium',
     ('An engineer who finishes quickly always gets handed more work, and has started finishing slowly. Which question in the sequence does that fit?',
      'Um engenheiro que termina rápido sempre recebe mais trabalho, e começou a terminar devagar. Em que pergunta da sequência isso se encaixa?'),
     ('Consequences teach.', 'Consequências ensinam.'),
     [(1, 'Something makes doing it well unrewarding',
       'Right: the consequence of finishing quickly was more work, so he learnt to finish slowly.',
       'Algo torna desagradável fazer bem',
       'Isso: a consequência de terminar rápido era mais trabalho, então ele aprendeu a terminar devagar.'),
      (0, 'Skill',
       'He could do it quickly; he has shown it.',
       'Habilidade',
       'Ele conseguia fazer rápido; já mostrou.'),
      (0, 'Motivation, since he is choosing to work more slowly than he is able to',
       'The lesson would ask why first, and the answer is a consequence, not a lack of will.',
       'Motivação, já que ele escolhe trabalhar mais devagar do que consegue',
       'A aula perguntaria por quê primeiro, e a resposta é uma consequência, não falta de vontade.'),
      (0, 'Something outside work',
       'Nothing suggests that.',
       'Algo fora do trabalho',
       'Nada sugere isso.')])

match('ex-5ew4br1g', 'the-diagnostic', 'medium',
      ('Match each finding with the question of the sequence it answers.',
       'Ligue cada achado à pergunta da sequência que ele responde.'),
      ('Expectations, environment, skill, outside work.', 'Expectativas, ambiente, habilidade, fora do trabalho.'),
      [('nobody told him the team wants to hear about being stuck', 'are the expectations clear?',
        'ninguém disse a ele que o time quer saber de travamentos', 'as expectativas estão claras?'),
       ('the library was undocumented and its author had left', 'do they have what they need?',
        'a biblioteca não tinha documentação e o autor tinha saído', 'a pessoa tem o que precisa?'),
       ('he had written good code in the area before', 'could they do it if their life depended on it?',
        'ele já tinha escrito bom código naquela área', 'conseguiria se a vida dependesse disso?'),
       ('his father was in hospital', 'is something outside work in the way?',
        'o pai dele estava internado', 'algo fora do trabalho atrapalha?')])

quiz('ex-5xe8f69n', 'the-diagnostic', 'hard',
     ('Why does motivation come last in the sequence, by the lesson?',
      'Por que a motivação vem por último na sequência, pela aula?'),
     ('Not because it never matters.', 'Não porque nunca importe.'),
     [(1, 'It is the first conclusion managers reach, it is wrong more than it is right, and it hides an earlier cause',
       'Right: even when it seems to be will, “why?” leads back to one of the first five.',
       'É a primeira conclusão a que se chega, erra mais do que acerta, e esconde uma causa anterior',
       'Isso: mesmo quando parece vontade, o “por quê?” leva de volta a uma das cinco primeiras.'),
      (0, 'It is impossible to measure',
       'Measurability is not the reason given.',
       'É impossível medir',
       'Mensurabilidade não é o motivo dado.'),
      (0, 'Because managers are not allowed to discuss motivation with the people who report to them',
       'Nothing forbids it; it is a matter of order.',
       'Porque gestoras não podem discutir motivação com quem se reporta a elas',
       'Nada proíbe; é uma questão de ordem.'),
      (0, 'It never matters',
       'The lesson says explicitly that it can matter.',
       'Ela nunca importa',
       'A aula diz explicitamente que ela pode importar.')])

quiz('ex-qwqvqc4w', 'the-conversation', 'easy',
     ('How did Renata open the diagnostic conversation with Marcos?',
      'Como a Renata abriu a conversa de diagnóstico com o Marcos?'),
     ('Her own part first.', 'A parte dela primeiro.'),
     [(1, 'With what she had got wrong herself',
       'Right: starting with the manager’s part changes what the person is willing to say.',
       'Com o que ela mesma tinha errado',
       'Isso: começar pela parte da gestora muda o que a pessoa está disposta a dizer.'),
      (0, 'By repeating the three examples from the first conversation',
       'That conversation had already named the pattern; this one was for learning why.',
       'Repetindo os três exemplos da primeira conversa',
       'Aquela conversa já tinha nomeado o padrão; esta era para aprender por quê.'),
      (0, 'By asking whether he still cared about the work, since that was the question on everybody’s mind',
       'She deliberately did not ask that.',
       'Perguntando se ele ainda se importava com o trabalho, já que essa era a pergunta na cabeça de todos',
       'Ela deliberadamente não perguntou isso.'),
      (0, 'With the improvement plan',
       'There was no plan yet.',
       'Com o plano de melhoria',
       'Ainda não havia plano.')])

quiz('ex-kwdhktj0', 'the-conversation', 'medium',
     ('What did Marcos believe a good engineer does, that explained part of the pattern?',
      'O que o Marcos acreditava que um bom engenheiro faz, que explicava parte do padrão?'),
     ('Saying “I’m stuck”.', 'Dizer “estou travado”.'),
     [(1, 'Solves problems alone',
       'Right: asking for help felt like admitting he was not good enough.',
       'Resolve problemas sozinho',
       'Isso: pedir ajuda parecia admitir que não era bom o bastante.'),
      (0, 'Writes no tests, to move faster',
       'Nothing like that came up.',
       'Não escreve testes, para ir mais rápido',
       'Nada parecido apareceu.'),
      (0, 'Never revises an estimate once it has been given to the team and to the product manager',
       'He was embarrassed to revise, but that came from the same belief about asking for help.',
       'Nunca revisa uma estimativa depois de ela ter sido dada ao time e à gerente de produto',
       'Ele teve vergonha de revisar, mas isso vinha da mesma crença sobre pedir ajuda.'),
      (0, 'Works long hours',
       'Not what he said.',
       'Trabalha muitas horas',
       'Não foi o que ele disse.')])

mc('ex-d3zjxc8e', 'the-conversation', 'medium',
   ('Which responses followed the diagnostic conversation? Choose all that apply.',
    'Quais respostas vieram depois da conversa de diagnóstico? Marque todas que se aplicam.'),
   ('One per cause.', 'Uma por causa.'),
   [(1, 'Written expectations about raising problems and revising estimates', 'Yes: for the expectations cause.',
     'Expectativas escritas sobre levantar problemas e revisar estimativas', 'Sim: para a causa das expectativas.'),
    (1, 'Documenting the notification library with Yara', 'Yes: for the environment cause.',
     'Documentar a biblioteca de notificações com a Yara', 'Sim: para a causa do ambiente.'),
    (1, 'Two on-call weeks off the rota, arranged with Sônia', 'Yes: for the cause outside work.',
     'Duas semanas fora da escala de plantão, combinadas com a Sônia', 'Sim: para a causa fora do trabalho.'),
    (0, 'Moving him down a level', 'No: skill on the code was not the problem.',
     'Rebaixá-lo de nível', 'Não: habilidade no código não era o problema.'),
    (0, 'An immediate improvement plan', 'No: that came a month later, only where things had not changed.',
     'Um plano de melhoria imediato', 'Não: isso veio um mês depois, só onde as coisas não mudaram.')])

cloze('ex-yp9wtn4q', 'the-conversation', 'easy',
      ('Renata told Marcos he did not need to say what the problem outside work was; she only wanted to know whether it was a ___.',
       'A Renata disse ao Marcos que ele não precisava dizer qual era o problema fora do trabalho; ela só queria saber se era um ___.'),
      ('Something that affects the result.', 'Algo que afeta o resultado.'),
      [(['factor'], ['fator'])])

quiz('ex-v25ryg6r', 'drill', 'hard',
     ('A manager says: “She’s been missing deadlines for a month. She clearly doesn’t care any more.” Using this lesson, what is the strongest objection?',
      'Um gestor diz: “Ela está perdendo prazos há um mês. Claramente não se importa mais.” Usando esta aula, qual é a objeção mais forte?'),
     ('Where does that conclusion sit in the sequence?', 'Onde essa conclusão fica na sequência?'),
     [(1, 'He has jumped to the last question without checking the five before it',
       'Right: motivation is the conclusion reached first and often wrongly.',
       'Ele pulou para a última pergunta sem conferir as cinco anteriores',
       'Isso: motivação é a conclusão a que se chega primeiro e muitas vezes errado.'),
      (0, 'A month is too short to notice anything',
       'A month is long enough to notice; the problem is the conclusion.',
       'Um mês é pouco para perceber qualquer coisa',
       'Um mês basta para perceber; o problema é a conclusão.'),
      (0, 'He should start an improvement plan straight away rather than keep waiting for things to change',
       'A plan before a diagnosis is acting on a guess.',
       'Ele deveria começar um plano de melhoria logo, em vez de continuar esperando as coisas mudarem',
       'Um plano antes de um diagnóstico é agir sobre um palpite.'),
      (0, 'He should ask her colleagues',
       'Not the lesson’s method; the first step is the sequence and then her.',
       'Ele deveria perguntar aos colegas dela',
       'Não é o método da aula; o primeiro passo é a sequência e depois ela.')])
