"""Lesson 20: the improvement plan, written honestly."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-adevywj0')

quiz('ex-ry7qqpyv', 'what-a-plan-is-for', 'easy',
     ('What are the two honest outcomes of an improvement plan that the person has to be told?',
      'Quais são os dois desfechos honestos de um plano de melhoria que a pessoa precisa ouvir?'),
     ('Both, not one.', 'Os dois, não um.'),
     [(1, 'Closing the gap, or leaving',
       'Right: hiding either outcome is a form of dishonesty.',
       'Fechar a lacuna, ou sair',
       'Isso: esconder qualquer um dos dois é uma forma de desonestidade.'),
      (0, 'Promotion or no promotion',
       'A plan is about a gap in the current role, not promotion.',
       'Promoção ou não promoção',
       'Um plano é sobre uma lacuna no cargo atual, não sobre promoção.'),
      (0, 'A pay rise if it goes well, and a pay cut if it does not, adjusted at the end of the period',
       'Pay is not one of the outcomes the lesson names.',
       'Um aumento se der certo, e uma redução se não der, ajustados no fim do período',
       'Salário não é um dos desfechos que a aula nomeia.'),
      (0, 'A transfer to another team, or staying',
       'Not the outcomes the lesson names.',
       'Uma transferência para outro time, ou ficar',
       'Não são os desfechos que a aula nomeia.')])

quiz('ex-n3gcvs8e', 'what-a-plan-is-for', 'medium',
     ('A manager has already decided somebody must leave. What does the lesson say is the honest course?',
      'Uma gestora já decidiu que alguém precisa sair. O que a aula diz que é o caminho honesto?'),
     ('Not a staged plan.', 'Não um plano encenado.'),
     [(1, 'Say so, and use the real process',
       'Right: a plan nobody expects to be passed harms everybody, including the next person put on one.',
       'Dizer isso, e usar o processo de verdade',
       'Isso: um plano que ninguém espera que seja cumprido faz mal a todos, inclusive à próxima pessoa posta num.'),
      (0, 'Write a plan anyway, as a record that a chance was given',
       'That is the dishonest version the lesson describes.',
       'Escrever um plano mesmo assim, como registro de que houve uma chance',
       'Essa é a versão desonesta que a aula descreve.'),
      (0, 'Wait for the person to resign',
       'Waiting is not honest either, and it can take months.',
       'Esperar a pessoa pedir demissão',
       'Esperar também não é honesto, e pode levar meses.'),
      (0, 'Make the plan’s expectations impossible to meet, so the outcome is certain and nobody wastes time',
       'That is the dishonest version with the cruelty made explicit.',
       'Tornar as expectativas do plano impossíveis de cumprir, para o resultado ser certo e ninguém perder tempo',
       'Essa é a versão desonesta com a crueldade explícita.')])

quiz('ex-7b5zaxwn', 'what-a-plan-is-for', 'medium',
     ('Why did Renata believe Marcos could close the gap in six weeks?',
      'Por que a Renata acreditava que o Marcos conseguiria fechar a lacuna em seis semanas?'),
     ('Habit or ability.', 'Hábito ou capacidade.'),
     [(1, 'The gap was a habit, and he had already changed one habit in a month',
       'Right: and if she had not believed it, she would not have written a plan.',
       'A lacuna era um hábito, e ele já tinha mudado um hábito em um mês',
       'Isso: e se ela não acreditasse, não teria escrito um plano.'),
      (0, 'Plans always work if the support is good',
       'Marcos’s did not fully work, despite the support.',
       'Planos sempre funcionam se o apoio for bom',
       'O do Marcos não funcionou por completo, apesar do apoio.'),
      (0, 'Because Sônia told her it would be fine',
       'Sônia checked the plan; the belief was Renata’s own judgement.',
       'Porque a Sônia disse que daria certo',
       'A Sônia conferiu o plano; a crença era julgamento da própria Renata.'),
      (0, 'Because his father was out of hospital by then and the other problems outside work had passed',
       'That mattered, but the reason given is that the gap was a habit he had shown he could change.',
       'Porque o pai dele já tinha saído do hospital e os outros problemas fora do trabalho tinham passado',
       'Isso importava, mas o motivo dado é que a lacuna era um hábito que ele mostrou conseguir mudar.')])

match('ex-0yt61n7z', 'writing-it', 'easy',
      ('Match each part of a plan with the failure that ruins it.',
       'Ligue cada parte de um plano à falha que o estraga.'),
      ('Five parts, five failures; four here.', 'Cinco partes, cinco falhas; quatro aqui.'),
      [('the gap', 'judgements such as “unreliable”', 'a lacuna', 'julgamentos como “pouco confiável”'),
       ('the expectation', 'vague goals such as “communicate better”', 'a expectativa', 'metas vagas como “comunicar melhor”'),
       ('the support', 'support promised that never arrives', 'o apoio', 'apoio prometido que nunca chega'),
       ('the consequences', 'softened, or left unsaid', 'as consequências', 'amaciadas, ou não ditas')])

quiz('ex-17gby0yv', 'writing-it', 'medium',
     ('Why does Marcos’s plan ask for four of six tickets, not six of six?',
      'Por que o plano do Marcos pede quatro de seis tickets, e não seis de seis?'),
     ('Perfection.', 'Perfeição.'),
     [(1, 'Estimates go wrong for everybody now and then, and a plan that demands perfection is designed to fail',
       'Right: the expectation has to be achievable as well as measurable.',
       'Estimativas dão errado para todo mundo de vez em quando, e um plano que exige perfeição é feito para falhar',
       'Isso: a expectativa precisa ser alcançável além de mensurável.'),
      (0, 'Four is the company standard',
       'No standard is mentioned.',
       'Quatro é o padrão da empresa',
       'Nenhum padrão é mencionado.'),
      (0, 'To make it easier',
       'It is set to be fair, not easy.',
       'Para facilitar',
       'Ela é definida para ser justa, não fácil.'),
      (0, 'Because the other two tickets would be paired with Yara',
       'Pairing covers the first three, and they count like the others.',
       'Porque os outros dois tickets seriam pareados com a Yara',
       'O pareamento cobre os três primeiros, e eles contam como os outros.')])

quiz('ex-vjb7qc5w', 'writing-it', 'medium',
     ('Why six weeks, by the lesson?',
      'Por que seis semanas, pela aula?'),
     ('Luck on one side, suspense on the other.', 'Sorte de um lado, suspense do outro.'),
     [(1, 'Long enough to see a habit change, and short enough not to leave the team and Marcos in suspense for months',
       'Right: two weeks would measure luck; six months would be too long for the team and for Marcos.',
       'Tempo para ver um hábito mudar, curto o bastante para não deixar todos em suspense',
       'Isso: duas semanas mediriam sorte; seis meses seria tempo demais para o time e para o Marcos.'),
      (0, 'The law requires six weeks',
       'No such legal requirement is given.',
       'A lei exige seis semanas',
       'Essa exigência legal não aparece.'),
      (0, 'It matched the length of the sprint',
       'Sprints are not mentioned.',
       'Batia com a duração da sprint',
       'Sprints não são mencionadas.'),
      (0, 'Because that is how long Yara had available for pairing before her own deadline came up',
       'Yara paired on three tickets; the period was chosen for the habit.',
       'Porque esse era o tempo que a Yara tinha para parear antes do próprio prazo dela',
       'A Yara pareou em três tickets; o período foi escolhido pelo hábito.')])

quiz('ex-hnkamyfc', 'writing-it', 'hard',
     ('Which sentence belongs in the expectation part of a plan, by the lesson’s standard?',
      'Qual frase pertence à parte da expectativa de um plano, pelo padrão da aula?'),
     ('Could somebody else tell, at the end?', 'Outra pessoa conseguiria dizer, no fim?'),
     [(1, '“When a ticket will exceed its estimate by more than half, say so within one working day.”',
       'Right: measurable, specific, and somebody else could check it.',
       '“Quando um ticket for passar da estimativa em mais da metade, avise em até um dia útil.”',
       'Isso: mensurável, específica, e outra pessoa conseguiria conferir.'),
      (0, '“Be more reliable with estimates.”',
       'Vague: nobody could say at the end whether it was met.',
       '“Ser mais confiável nas estimativas.”',
       'Vaga: ninguém conseguiria dizer no fim se foi cumprida.'),
      (0, '“Show more ownership.”',
       'A judgement dressed as a goal.',
       '“Mostrar mais senso de dono.”',
       'Um julgamento vestido de meta.'),
      (0, '“Stop being careless.”',
       'An adjective about the person, which belongs nowhere in a plan.',
       '“Parar de ser descuidado.”',
       'Um adjetivo sobre a pessoa, que não pertence a lugar nenhum num plano.')])

quiz('ex-2y6dn65y', 'during-the-plan', 'easy',
     ('In week four, a ticket went to twice its estimate without a word. What did Renata’s weekly summary say?',
      'Na quarta semana, um ticket chegou ao dobro da estimativa sem uma palavra. O que disse o resumo semanal da Renata?'),
     ('The truth, both ways.', 'A verdade, nos dois sentidos.'),
     [(1, 'Exactly that',
       'Right: a summary that says “good progress” in a bad week removes the evidence and misleads the person.',
       'Exatamente isso',
       'Isso: um resumo que diz “bom progresso” numa semana ruim remove a evidência e engana a pessoa.'),
      (0, 'Good progress overall, to keep him motivated through the second half of the plan',
       'That is the failure the lesson warns about.',
       'Bom progresso no geral, para mantê-lo motivado na segunda metade do plano',
       'Essa é a falha contra a qual a aula alerta.'),
      (0, 'Nothing; only good weeks are summarised',
       'Every week is summarised, good and bad.',
       'Nada; só semanas boas são resumidas',
       'Toda semana é resumida, boa ou ruim.'),
      (0, 'That the plan was over',
       'It ran its six weeks.',
       'Que o plano tinha acabado',
       'Ele correu as seis semanas.')])

quiz('ex-v44153sy', 'during-the-plan', 'medium',
     ('If Yara had not paired on the first three estimates, what would the lesson say about the plan?',
      'Se a Yara não tivesse pareado nas três primeiras estimativas, o que a aula diria sobre o plano?'),
     ('A plan binds the manager too.', 'Um plano também obriga a gestora.'),
     [(1, 'It failed on Caju’s side, and could not fairly be held against Marcos',
       'Right: support promised and not given voids the plan.',
       'Falhou do lado da Caju, e não poderia ser usado com justiça contra o Marcos',
       'Isso: apoio prometido e não dado anula o plano.'),
      (0, 'It still stands, since the expectation was clear',
       'The support was part of the agreement.',
       'Continua valendo, já que a expectativa estava clara',
       'O apoio fazia parte do acordo.'),
      (0, 'Marcos should have asked somebody else to pair with him instead',
       'The support was Caju’s to provide.',
       'O Marcos deveria ter pedido a outra pessoa para parear com ele',
       'O apoio era da Caju para oferecer.'),
      (0, 'It should be ended early, since the support had already broken down and could not be recovered',
       'The honest response is to say so and extend or restart, not to end it.',
       'Deveria ser encerrado antes, já que o apoio já tinha falhado e não havia como recuperar',
       'A resposta honesta é dizer isso e prorrogar ou recomeçar, não encerrar.')])

order('ex-6n9kh6kb', 'during-the-plan', 'easy',
      ('Put the three lines of each weekly summary in the order the lesson gives them.',
       'Ponha as três linhas de cada resumo semanal na ordem em que a aula as dá.'),
      ('What happened, what was given, what next.', 'O que aconteceu, o que foi dado, o que vem.'),
      [('What happened against the expectation', 'O que aconteceu em relação à expectativa'),
       ('What support was given', 'Que apoio foi dado'),
       ('What was agreed for next week', 'O que foi combinado para a próxima semana')])

quiz('ex-k8aznpwt', 'during-the-plan', 'medium',
     ('When does the lesson consider extending a partly met plan honest?',
      'Quando a aula considera honesto prorrogar um plano cumprido em parte?'),
     ('Once, with a specific reason.', 'Uma vez, com um motivo específico.'),
     [(1, 'Once, with a specific reason to think more time would close the gap',
       'Right: for example support that arrived late; not to avoid the decision.',
       'Uma vez, com um motivo específico para achar que mais tempo fecharia a lacuna',
       'Isso: por exemplo, apoio que chegou tarde; não para evitar a decisão.'),
      (0, 'Whenever the manager is unsure',
       'Extending to avoid the decision is the dishonest version again.',
       'Sempre que a gestora estiver em dúvida',
       'Prorrogar para evitar a decisão é a versão desonesta de novo.'),
      (0, 'Never',
       'The lesson allows one extension with a reason.',
       'Nunca',
       'A aula permite uma prorrogação com motivo.'),
      (0, 'As many times as needed, as long as the person agrees each time',
       'Repeated extensions leave everybody in suspense and avoid the decision.',
       'Quantas vezes for preciso, desde que a pessoa concorde a cada vez',
       'Prorrogações repetidas deixam todos em suspense e evitam a decisão.')])

num('ex-kspas30f', 'during-the-plan', 'easy',
    ('Marcos’s plan required at least four of six tickets within one and a half times their estimate. He managed three. By how many tickets did he fall short?',
     'O plano do Marcos exigia pelo menos quatro de seis tickets em até uma vez e meia a estimativa. Ele conseguiu três. Faltaram quantos tickets?'),
    ('Four minus three.', 'Quatro menos três.'),
    1, 0, ('ticket', 'ticket'), (['tickets'], ['tickets']))

cloze('ex-fwry76pb', 'during-the-plan', 'easy',
      ('Support promised and not given ___ the plan.',
       'Apoio prometido e não dado ___ o plano.'),
      ('It no longer counts.', 'Ele deixa de valer.'),
      [(['voids', 'invalidates', 'cancels'], ['anula', 'invalida', 'cancela'])])

quiz('ex-c0qtx3br', 'drill', 'hard',
     ('At the end of a plan, a manager says: “It went fine, let’s just keep an eye on things for a while,” without closing it formally. What does the lesson say is wrong?',
      'No fim de um plano, um gestor diz: “Foi tudo bem, vamos só ficar de olho por um tempo”, sem fechá-lo formalmente. O que a aula diz que está errado?'),
     ('Met plans should be closed.', 'Planos cumpridos devem ser fechados.'),
     [(1, 'The person is left wondering whether they are still on it',
       'Right: a met plan should be closed clearly, in a conversation and in writing.',
       'A pessoa fica se perguntando se ainda está nele',
       'Isso: um plano cumprido deveria ser fechado com clareza, numa conversa e por escrito.'),
      (0, 'Nothing; caution is sensible after a plan',
       'Caution that leaves the plan hanging is the failure named.',
       'Nada; cautela é sensata depois de um plano',
       'Cautela que deixa o plano pendurado é a falha nomeada.'),
      (0, 'He should have extended it formally',
       'If it was met, there is nothing to extend.',
       'Ele deveria ter prorrogado formalmente',
       'Se foi cumprido, não há o que prorrogar.'),
      (0, 'He should have started a new plan on a different area to keep the momentum going',
       'Nothing in the lesson suggests a new plan after a met one.',
       'Ele deveria ter começado um novo plano em outra área para manter o ritmo',
       'Nada na aula sugere um novo plano depois de um cumprido.')])
