"""Lesson 21: letting someone go."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-nc01trya')

mc('ex-m1hmfyn7', 'the-process', 'easy',
   ('Which questions does Sônia ask before any dismissal at Caju? Choose all that apply.',
    'Quais perguntas a Sônia faz antes de qualquer demissão na Caju? Marque todas que se aplicam.'),
   ('Three, each answered with evidence.', 'Três, cada uma respondida com evidência.'),
   [(1, 'Was the expectation clear, and when was it set?', 'Yes.', 'A expectativa estava clara, e quando foi definida?', 'Sim.'),
    (1, 'Was the support given?', 'Yes.', 'O apoio foi dado?', 'Sim.'),
    (1, 'Is the person treated as others in the same situation would be?', 'Yes.',
     'A pessoa está sendo tratada como outras na mesma situação seriam?', 'Sim.'),
    (0, 'Does the team want them to leave?', 'No: the team’s preference is not one of the questions.',
     'O time quer que a pessoa saia?', 'Não: a preferência do time não é uma das perguntas.'),
    (0, 'Is the manager sure?', 'No: conviction is exactly what the questions replace with evidence.',
     'A gestora tem certeza?', 'Não: convicção é justamente o que as perguntas trocam por evidência.')])

quiz('ex-1a5s48y4', 'the-process', 'medium',
     ('Under Brazil’s Law 12.506 of 2011, what notice does an employer owe on dismissal without cause?',
      'Pela Lei 12.506, de 2011, que aviso prévio o empregador deve numa demissão sem justa causa?'),
     ('Thirty, plus a little per year, with a ceiling.', 'Trinta, mais um pouco por ano, com teto.'),
     [(1, 'Thirty days plus three per year of service, up to ninety in total',
       'Right: and the people team, not the manager, explains what it means for the person.',
       'Trinta dias mais três por ano de serviço, até noventa no total',
       'Isso: e quem explica o que isso significa para a pessoa é o time de pessoas, não a gestora.'),
      (0, 'Exactly thirty days',
       'Thirty is the base; the law adds three days per year of service.',
       'Exatamente trinta dias',
       'Trinta é a base; a lei acrescenta três dias por ano de serviço.'),
      (0, 'Ninety days in every case, whatever the length of service',
       'Ninety is the ceiling, not the rule.',
       'Noventa dias em todo caso, seja qual for o tempo de casa',
       'Noventa é o teto, não a regra.'),
      (0, 'None',
       'Notice is owed on dismissal without cause.',
       'Nenhum',
       'Aviso prévio é devido na demissão sem justa causa.')])

num('ex-z5gmgqs0', 'the-process', 'medium',
    ('Marcos had worked at Caju for three years. Under the rule of thirty days plus three per year of service, how many days of notice is that?',
     'O Marcos trabalhava na Caju havia três anos. Pela regra de trinta dias mais três por ano de serviço, quantos dias de aviso prévio dá?'),
    ('30 + 3 × 3.', '30 + 3 × 3.'),
    39, 0, ('days', 'dias'), (['day'], ['dia']))

quiz('ex-chksnbrd', 'the-process', 'medium',
     ('Why was Marcos’s access changed after the conversation rather than during it?',
      'Por que os acessos do Marcos foram mudados depois da conversa, e não durante?'),
     ('A matter of dignity.', 'Questão de dignidade.'),
     [(1, 'To spare him a locked laptop',
       'Right: the order of access and conversation is a matter of dignity.',
       'Para poupá-lo de um notebook bloqueado',
       'Isso: a ordem entre acessos e conversa é questão de dignidade.'),
      (0, 'Because the systems team was busy that morning',
       'It was planned that way on Sônia’s checklist.',
       'Porque o time de sistemas estava ocupado naquela manhã',
       'Foi planejado assim na lista da Sônia.'),
      (0, 'So he could finish his last ticket',
       'Not the reason given.',
       'Para ele terminar o último ticket',
       'Não é o motivo dado.'),
      (0, 'Because the law requires access to remain open until the notice period has been fully worked',
       'The lesson gives dignity as the reason, not a legal rule.',
       'Porque a lei exige que os acessos fiquem abertos até o aviso prévio ser trabalhado por inteiro',
       'A aula dá a dignidade como motivo, não uma regra legal.')])

quiz('ex-h2qaks5b', 'the-process', 'hard',
     ('Which of these is the manager’s to do, by the lesson?',
      'Qual destes cabe à gestora fazer, pela aula?'),
     ('Not the terms, not the law.', 'Nem as condições, nem a lei.'),
     [(1, 'The conversation',
       'Right: the decision is shared and the terms belong to the people team; the conversation is the manager’s.',
       'A conversa',
       'Isso: a decisão é compartilhada e as condições são do time de pessoas; a conversa é da gestora.'),
      (0, 'Negotiating the severance terms with the person in the meeting',
       'The manager does not negotiate the terms.',
       'Negociar as condições do desligamento com a pessoa na reunião',
       'A gestora não negocia as condições.'),
      (0, 'Explaining the FGTS penalty',
       'The people team explains money, dates and rights.',
       'Explicar a multa do FGTS',
       'O time de pessoas explica dinheiro, datas e direitos.'),
      (0, 'Deciding alone',
       'The decision was Renata’s, Sônia’s and Otávio’s together.',
       'Decidir sozinha',
       'A decisão foi da Renata, da Sônia e do Otávio juntos.')])

quiz('ex-n156rvs1', 'the-conversation', 'easy',
     ('Where does the decision come in the conversation, by the lesson?',
      'Em que ponto da conversa vem a decisão, pela aula?'),
     ('The second sentence.', 'A segunda frase.'),
     [(1, 'In the first minute',
       'Right: not after five minutes about the plan, and not phrased as a question.',
       'No primeiro minuto',
       'Isso: não depois de cinco minutos sobre o plano, e não formulada como pergunta.'),
      (0, 'After a review of everything that went wrong, so the person understands why',
       'Over-explaining is for the manager’s comfort; the person already knows.',
       'Depois de repassar tudo o que deu errado, para a pessoa entender por quê',
       'Explicar demais é para o conforto da gestora; a pessoa já sabe.'),
      (0, 'At the end',
       'Leaving it to the end is burying it.',
       'No fim',
       'Deixar para o fim é enterrá-la.'),
      (0, 'In a message the day before',
       'The day before, Renata only said there would be a meeting.',
       'Numa mensagem no dia anterior',
       'No dia anterior, a Renata só disse que haveria uma reunião.')])

quiz('ex-zcday1p2', 'the-conversation', 'medium',
     ('Marcos says the last ticket was late because of a dependency on Payments. What does Renata do?',
      'O Marcos diz que o último ticket atrasou por causa de uma dependência de Pagamentos. O que a Renata faz?'),
     ('Not a debate.', 'Não é um debate.'),
     [(1, 'Says the decision is made, without arguing about the ticket',
       'Right: arguing implies the decision is open; Sônia explains how to raise unfairness.',
       'Diz que a decisão está tomada, sem discutir o ticket',
       'Isso: discutir sugere que a decisão está aberta; a Sônia explica como contestar.'),
      (0, 'Goes through the ticket’s history to show him he was responsible for the delay',
       'That is debating the decision, which the lesson says to avoid.',
       'Repassa o histórico do ticket para mostrar que ele foi o responsável pelo atraso',
       'Isso é debater a decisão, o que a aula diz para evitar.'),
      (0, 'Reconsiders',
       'The decision was made through the process before the meeting.',
       'Reconsidera',
       'A decisão foi tomada pelo processo antes da reunião.'),
      (0, 'Ends the meeting',
       'The rest of the time belongs to him.',
       'Encerra a reunião',
       'O resto do tempo pertence a ele.')])

match('ex-nqnm66ah', 'the-conversation', 'medium',
      ('Match each thing to avoid in the conversation with why it harms.',
       'Ligue cada coisa a evitar na conversa ao motivo de ela fazer mal.'),
      ('Debate, over-explaining, false comfort.', 'Debate, explicação demais, falso conforto.'),
      [('debating the decision', 'implies the decision is still open',
        'debater a decisão', 'sugere que a decisão ainda está aberta'),
       ('over-explaining', 'serves the manager’s comfort, not the person',
        'explicar demais', 'serve ao conforto da gestora, não à pessoa'),
       ('false comfort', 'is heard as dismissive',
        'falso conforto', 'é ouvido como descaso')],
      [('stating the decision first', 'dizer a decisão primeiro')])

quiz('ex-x3bxnca8', 'the-conversation', 'medium',
     ('Instead of “this might be the best thing for you”, what did Renata say?',
      'Em vez de “talvez isso seja o melhor para você”, o que a Renata disse?'),
     ('True and specific.', 'Verdadeiro e específico.'),
     [(1, 'That his library documentation was good, and she would give a factual reference',
       'Right: specific, true, and useful to him.',
       'Que a documentação dele da biblioteca foi boa, e que daria uma referência factual',
       'Isso: específico, verdadeiro e útil para ele.'),
      (0, 'That she was sure he would find something better soon',
       'That is the false comfort the lesson warns about.',
       'Que tinha certeza de que ele ia encontrar algo melhor logo',
       'Esse é o falso conforto contra o qual a aula alerta.'),
      (0, 'That she had fought hard for him with Otávio and Sônia but had been overruled in the end',
       'That would blame the others and imply disagreement with the decision.',
       'Que tinha brigado muito por ele com o Otávio e a Sônia, mas foi voto vencido',
       'Isso culparia os outros e sugeriria discordância da decisão.'),
      (0, 'Nothing',
       'She said something true and specific.',
       'Nada',
       'Ela disse algo verdadeiro e específico.')])

quiz('ex-a43yagaq', 'the-team', 'easy',
     ('What did Renata tell the team about why Marcos left?',
      'O que a Renata disse ao time sobre por que o Marcos saiu?'),
     ('The details are his.', 'Os detalhes são dele.'),
     [(1, 'Nothing',
       'Right: sharing them would publish something private about somebody not there to respond.',
       'Nada',
       'Isso: compartilhá-los publicaria algo privado sobre alguém que não está lá para responder.'),
      (0, 'The plan and its result, so that the team would see that the process had been fair',
       'Seeing a fair process comes from months of experience, not from publishing his plan.',
       'O plano e o resultado, para o time ver que o processo foi justo',
       'Ver um processo justo vem de meses de experiência, não de publicar o plano dele.'),
      (0, 'That he had resigned',
       'That would be untrue.',
       'Que ele tinha pedido demissão',
       'Isso seria falso.'),
      (0, 'That he was not a good fit',
       'A judgement about him, which she did not share.',
       'Que ele não se encaixava',
       'Um julgamento sobre ele, que ela não compartilhou.')])

order('ex-d22g63sa', 'the-team', 'medium',
      ('Put what Renata did with the team in order.',
       'Ponha em ordem o que a Renata fez com o time.'),
      ('Same day, then the week after.', 'No mesmo dia, depois na semana seguinte.'),
      [('Told them in person, the same day, before systems showed the change', 'Contou pessoalmente, no mesmo dia, antes de os sistemas mostrarem a mudança'),
       ('Answered the practical questions about work and on-call', 'Respondeu às perguntas práticas sobre trabalho e plantão'),
       ('Raised the unspoken worry in each one-to-one that week', 'Levantou a preocupação não dita em cada 1:1 daquela semana')])

quiz('ex-agzaemby', 'the-team', 'medium',
     ('Why could Renata honestly tell Thiago he had nothing to worry about?',
      'Por que a Renata pôde dizer com honestidade ao Thiago que ele não tinha com o que se preocupar?'),
     ('What warning looks like.', 'Como é um aviso.'),
     [(1, 'The team had seen that nobody is dismissed without months of clear warning',
       'Right: a fair process makes the reassurance true rather than merely kind.',
       'O time tinha visto que ninguém é demitido sem meses de aviso claro',
       'Isso: um processo justo torna o consolo verdadeiro, e não só gentil.'),
      (0, 'Because he was too junior to be dismissed',
       'Seniority does not protect anybody; the process does.',
       'Porque ele era júnior demais para ser demitido',
       'Senioridade não protege ninguém; o processo protege.'),
      (0, 'Because she would never let it happen again on her team, whatever the circumstances',
       'That would be a promise she cannot make.',
       'Porque ela nunca deixaria isso acontecer de novo no time dela, fossem quais fossem as circunstâncias',
       'Isso seria uma promessa que ela não pode fazer.'),
      (0, 'Because Otávio said so',
       'The reason is what the team has seen.',
       'Porque o Otávio disse',
       'O motivo é o que o time viu.')])

cloze('ex-j1dghp2w', 'the-team', 'easy',
      ('When somebody is dismissed, the question in most people’s heads is “am I ___?”',
       'Quando alguém é demitido, a pergunta na cabeça de quase todos é “eu sou o ___?”'),
      ('The one after.', 'O seguinte.'),
      [(['next'], ['próximo', 'proximo'])])

quiz('ex-6pyd95pj', 'drill', 'hard',
     ('A manager plans to tell an engineer on a Friday at 17:30, by video call, that their employment is ending, after their accounts have been disabled so nothing can be deleted. What would this lesson change first?',
      'Um gestor planeja contar a uma engenheira numa sexta às 17:30, por videochamada, que o vínculo dela vai terminar, depois de os acessos dela terem sido desativados para nada ser apagado. O que esta aula mudaria primeiro?'),
     ('Order, day and place.', 'Ordem, dia e lugar.'),
     [(1, 'The order: tell her first and change access afterwards, early in the week, and in person if that is possible',
       'Right: learning the news from a disabled account is the indignity Sônia’s checklist exists to prevent.',
       'A sequência: a conversa antes do bloqueio, logo no começo da semana e, se der, ao vivo',
       'Isso: saber da notícia por uma conta desativada é a indignidade que a lista da Sônia existe para evitar.'),
      (0, 'Nothing, since disabling access first protects the company',
       'The lesson puts dignity first and changes access right after the conversation.',
       'Nada, já que desativar os acessos antes protege a empresa',
       'A aula põe a dignidade primeiro e muda os acessos logo depois da conversa.'),
      (0, 'Only the time, moving it to the morning',
       'The morning helps, but the order of access and conversation matters more.',
       'Só o horário, passando para a manhã',
       'A manhã ajuda, mas a ordem entre acessos e conversa importa mais.'),
      (0, 'Sending a written letter instead of a call, so that she has everything in front of her at once',
       'A letter goes with the conversation; it does not replace it.',
       'Mandar uma carta escrita em vez de ligar, para ela ter tudo na frente de uma vez',
       'A carta acompanha a conversa; não a substitui.')])
