"""Lesson 22: conflict."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-hmd90qs2')

quiz('ex-k50y288d', 'between-people', 'easy',
     ('What does Jehn’s distinction separate?',
      'O que a distinção de Jehn separa?'),
     ('About the work, or about each other.', 'Sobre o trabalho, ou sobre o outro.'),
     [(1, 'Task conflict from relationship conflict',
       'Right: disagreement about the work, against friction between the people.',
       'Conflito de tarefa de conflito de relacionamento',
       'Isso: discordância sobre o trabalho, contra atrito entre as pessoas.'),
      (0, 'Conflict in small teams from conflict in large ones',
       'Size is not the distinction.',
       'Conflito em times pequenos de conflito em times grandes',
       'Tamanho não é a distinção.'),
      (0, 'Conflict between engineers from conflict between engineers and the product managers they work with',
       'The distinction is about what the conflict concerns, not who is in it.',
       'Conflito entre engenheiros de conflito entre engenheiros e as gerentes de produto com quem trabalham',
       'A distinção é sobre o que o conflito envolve, não sobre quem está nele.'),
      (0, 'Open conflict from hidden conflict',
       'Not Jehn’s distinction.',
       'Conflito aberto de conflito escondido',
       'Não é a distinção de Jehn.')])

quiz('ex-pyb5451x', 'between-people', 'medium',
     ('Why did Renata talk to Diego and Paula separately before bringing them together?',
      'Por que a Renata conversou com o Diego e a Paula separadamente antes de reuni-los?'),
     ('To find something under the grievance.', 'Para achar algo sob a queixa.'),
     [(1, 'To find the task conflict',
       'Right: asked separately, each could describe the task conflict without performing for the other.',
       'Para achar o conflito de tarefa',
       'Isso: perguntados separadamente, cada um conseguiu descrever o conflito de tarefa sem atuar para o outro.'),
      (0, 'To decide who was right before the joint meeting, so the meeting could be used to announce it',
       'She deliberately did not decide from either account.',
       'Para decidir quem tinha razão antes da reunião conjunta, e usar a reunião para anunciar',
       'Ela deliberadamente não decidiu a partir de nenhum dos relatos.'),
      (0, 'Because they refused to meet',
       'Nothing says they refused.',
       'Porque eles se recusaram a se encontrar',
       'Nada diz que se recusaram.'),
      (0, 'To collect evidence for HR',
       'Nothing suggests an HR matter.',
       'Para juntar evidência para o RH',
       'Nada sugere um assunto de RH.')])

quiz('ex-g76czbtz', 'between-people', 'medium',
     ('What did the task conflict between Diego and Paula turn out to be?',
      'O que acabou sendo o conflito de tarefa entre o Diego e a Paula?'),
     ('Something documented nowhere.', 'Algo não documentado em lugar nenhum.'),
     [(1, 'A failure mode only Diego knew about',
       'Right: once it was written down, the design disagreement could be settled.',
       'Uma falha que só o Diego conhecia',
       'Isso: uma vez escrita, a discordância de design pôde ser resolvida.'),
      (0, 'Paula’s code was badly written',
       'That was Diego’s first account, not what the conversation found.',
       'O código da Paula estava mal escrito',
       'Esse foi o primeiro relato do Diego, não o que a conversa encontrou.'),
      (0, 'Diego wanted the service back',
       'That was Paula’s first account.',
       'O Diego queria o serviço de volta',
       'Esse foi o primeiro relato da Paula.'),
      (0, 'A disagreement about which programming language the service should be rewritten in',
       'Nothing like that came up.',
       'Uma discordância sobre em que linguagem o serviço deveria ser reescrito',
       'Nada disso apareceu.')])

match('ex-3dk675z9', 'between-people', 'medium',
      ('Match each Thomas–Kilmann mode with where it sits on the two axes.',
       'Ligue cada modo de Thomas e Kilmann a onde ele fica nos dois eixos.'),
      ('Own concern, other’s concern.', 'Preocupação própria, preocupação da outra pessoa.'),
      [('competing', 'high on own, low on the other’s', 'competir', 'alto na própria, baixo na da outra'),
       ('collaborating', 'high on both', 'colaborar', 'alto nas duas'),
       ('avoiding', 'low on both', 'evitar', 'baixo nas duas'),
       ('accommodating', 'low on own, high on the other’s', 'acomodar', 'baixo na própria, alto na da outra')],
      [('outside both axes', 'fora dos dois eixos')])

quiz('ex-0388dakj', 'between-people', 'hard',
     ('Paula’s remark in planning, “some people find it hard to let go of their code”, was dealt with how?',
      'O comentário da Paula no planejamento, “tem gente que tem dificuldade de largar o próprio código”, foi tratado como?'),
     ('Separately, with a structure from lesson 8.', 'Separadamente, com uma estrutura da aula 8.'),
     [(1, 'In her own one-to-one, as feedback in the shape of lesson 8, with the impact the remark had on the whole team',
       'Right: whoever was right about the code, pointing at a colleague in planning affected the whole team.',
       'Na 1:1 dela, como feedback no formato da aula 8',
       'Isso: quem quer que tivesse razão sobre o código, apontar um colega no planejamento afetou o time inteiro.'),
      (0, 'It was ignored, since she was partly right about Diego’s reviews and he had provoked her',
       'Being partly right did not change the effect of the remark.',
       'Foi ignorado, já que ela tinha alguma razão sobre as revisões do Diego e ele a tinha provocado',
       'Ter alguma razão não mudou o efeito do comentário.'),
      (0, 'In front of the team, at the next planning',
       'Corrective feedback goes in private.',
       'Na frente do time, no planejamento seguinte',
       'Feedback corretivo é em particular.'),
      (0, 'In the joint meeting with Diego',
       'The joint meeting was about the shared problem, not grievances.',
       'Na reunião conjunta com o Diego',
       'A reunião conjunta era sobre o problema comum, não sobre queixas.')])

quiz('ex-j5dryp6g', 'between-teams', 'easy',
     ('Why was Payments moving the date of Agenda’s endpoint?',
      'Por que Pagamentos estava mudando a data do endpoint do Agenda?'),
     ('The only fixed thing on their roadmap.', 'A única coisa fixa no roadmap deles.'),
     [(1, 'A legal deadline',
       'Right: from inside Payments, Agenda’s request was one of six, and the law was fixed.',
       'Um prazo legal',
       'Isso: de dentro de Pagamentos, o pedido do Agenda era um de seis, e a lei era fixa.'),
      (0, 'They did not care about other teams',
       'That was the Agenda team’s assumption, which turned out to be wrong.',
       'Eles não ligavam para outros times',
       'Essa era a suposição do time do Agenda, que se mostrou errada.'),
      (0, 'Because Bia had been told by her director to deprioritise every request coming from the clinic product',
       'Nothing like that; the reason was the legal date.',
       'Porque a Bia tinha recebido da diretora a ordem de despriorizar todo pedido vindo do produto para clínicas',
       'Nada disso; o motivo era a data legal.'),
      (0, 'The endpoint was technically impossible',
       'It was possible; the question was when.',
       'O endpoint era tecnicamente impossível',
       'Era possível; a questão era quando.')])

quiz('ex-5hcgjqr4', 'between-teams', 'medium',
     ('Why does a dispute escalated by one side arrive as an accusation?',
      'Por que uma disputa escalada por um lado só chega como acusação?'),
     ('Whose version is heard first?', 'A versão de quem é ouvida primeiro?'),
     [(1, 'The people above hear one version first and the other second, defensively',
       'Right: escalating together, with one page, lets them decide on the facts.',
       'Quem está acima ouve uma versão primeiro e a outra depois, na defensiva',
       'Isso: escalar juntos, com uma página, deixa que decidam pelos fatos.'),
      (0, 'Because directors dislike escalations',
       'The problem is the order of information, not directors’ taste.',
       'Porque diretores não gostam de escaladas',
       'O problema é a ordem da informação, não o gosto dos diretores.'),
      (0, 'Because escalating is always a sign of failure by the manager who does it',
       'The lesson says escalation between teams is often correct.',
       'Porque escalar é sempre sinal de fracasso de quem escala',
       'A aula diz que escalar entre times muitas vezes é o certo.'),
      (0, 'Because it goes by email',
       'The medium is not the issue.',
       'Porque vai por e-mail',
       'O meio não é a questão.')])

mc('ex-pfvm1c4h', 'between-teams', 'medium',
   ('What did Renata and Bia’s one-page document contain? Choose all that apply.',
    'O que continha o documento de uma página da Renata e da Bia? Marque todas que se aplicam.'),
   ('Both constraints, options, both recommendations.', 'As duas restrições, opções, as duas recomendações.'),
   [(1, 'The decision needed', 'Yes.', 'A decisão necessária', 'Sim.'),
    (1, 'Each team’s constraint', 'Yes: the March promise and the February legal date.', 'A restrição de cada time', 'Sim: a promessa de março e a data legal de fevereiro.'),
    (1, 'The options', 'Yes: three of them.', 'As opções', 'Sim: três.'),
    (1, 'What each of them recommended', 'Yes, and they differed.', 'O que cada uma recomendava', 'Sim, e eram diferentes.'),
    (0, 'Which team was at fault', 'No: it described a shared problem, not blame.', 'Qual time tinha culpa', 'Não: descrevia um problema comum, não culpa.')])

quiz('ex-npsrt76q', 'between-teams', 'hard',
     ('Why did Renata not have an Agenda engineer read the Payments database directly?',
      'Por que a Renata não pediu a alguém do Agenda que lesse direto o banco de dados de Pagamentos?'),
     ('A month, then the migration.', 'Um mês, depois a migração.'),
     [(1, 'It would break as soon as the migration changed the schema, and it would damage the relationship between the teams for a year',
       'Right: working around a team creates a hidden dependency and distrust.',
       'Quebraria assim que a migração mudasse o esquema, e estragaria a relação entre os times por um ano',
       'Isso: contornar um time cria uma dependência escondida e desconfiança.'),
      (0, 'It was against the law',
       'The reason given is technical and relational, not legal.',
       'Era contra a lei',
       'O motivo dado é técnico e de relação, não legal.'),
      (0, 'Agenda had no engineers free',
       'Not the reason given.',
       'O Agenda não tinha ninguém livre',
       'Não é o motivo dado.'),
      (0, 'Because the database was in a different cloud region and could not be reached from Agenda’s services',
       'Nothing like that is in the lesson.',
       'Porque o banco estava em outra região de nuvem e não era acessível pelos serviços do Agenda',
       'Nada disso está na aula.')])

quiz('ex-5asyvxdv', 'with-product', 'easy',
     ('What does “disagree and commit” ask of somebody once a decision is made?',
      'O que “discordar e se comprometer” pede de alguém depois de tomada a decisão?'),
     ('The second half.', 'A segunda metade.'),
     [(1, 'Commit fully anyway',
       'Right: argue fully while it is open, then support it fully.',
       'Se comprometer mesmo assim',
       'Isso: defender por inteiro enquanto está aberta, depois apoiar por inteiro.'),
      (0, 'To keep raising objections until it is reversed',
       'That is the passive sabotage the lesson warns about.',
       'Que continue levantando objeções até ela ser revertida',
       'Essa é a sabotagem passiva contra a qual a aula alerta.'),
      (0, 'To say yes in the meeting and then do the work at whatever pace feels right',
       'That is not committing.',
       'Que diga sim na reunião e depois faça o trabalho no ritmo que achar certo',
       'Isso não é se comprometer.'),
      (0, 'To tell the team it was a bad call',
       'That turns the decision into something the team can resist.',
       'Que diga ao time que foi uma má decisão',
       'Isso transforma a decisão em algo a que o time pode resistir.')])

quiz('ex-nzn9azp5', 'with-product', 'medium',
     ('What changed the conversation between Helena and Diego?',
      'O que mudou a conversa entre a Helena e o Diego?'),
     ('One page, in numbers.', 'Uma página, em números.'),
     [(1, 'Both concerns on one page, in numbers, plus the standing maintenance agreement',
       'Right: each could then see the other’s concern as legitimate.',
       'As duas preocupações numa página, em números, mais o acordo de manutenção',
       'Isso: cada um passou a ver a preocupação do outro como legítima.'),
      (0, 'Renata deciding for them',
       'They agreed a version themselves once the trade-off was visible.',
       'A Renata decidir por eles',
       'Eles combinaram uma versão sozinhos quando o trade-off ficou visível.'),
      (0, 'Otávio overruling Diego, which settled the argument before the trade-off had to be discussed',
       'Otávio was not involved in this one.',
       'O Otávio passar por cima do Diego, o que encerrou a discussão antes de o trade-off precisar ser debatido',
       'O Otávio não se envolveu nesta.'),
      (0, 'Sales dropping the deal',
       'The deal went ahead, two weeks later.',
       'Vendas desistir do negócio',
       'O negócio seguiu, duas semanas depois.')])

order('ex-8b9epe7p', 'with-product', 'medium',
      ('Put what happened between Helena and Diego in order.',
       'Ponha em ordem o que aconteceu entre a Helena e o Diego.'),
      ('Concerns, page, version, commitment.', 'Preocupações, página, versão, compromisso.'),
      [('Each states a legitimate concern', 'Cada um declara uma preocupação legítima'),
       ('Both concerns go on one page, in numbers', 'As duas preocupações vão para uma página, em números'),
       ('They agree two weeks of refactoring, then four of feature work', 'Combinam duas semanas de refatoração, depois quatro da funcionalidade'),
       ('Diego commits, and raises the larger refactoring at next quarter’s planning', 'O Diego se compromete, e leva a refatoração maior ao planejamento do trimestre seguinte')])

cloze('ex-k5bpzbjj', 'with-product', 'easy',
      ('Saying yes in the meeting and then raising objections at every step is passive ___.',
       'Dizer sim na reunião e depois levantar objeções a cada passo é ___ passiva.'),
      ('Worse than open disagreement.', 'Pior que discordância aberta.'),
      [(['sabotage'], ['sabotagem'])])

quiz('ex-ds22e3jh', 'drill', 'hard',
     ('Two teams have been arguing in their channels for a month about who should fix a shared library. Each manager has privately complained to their own director. What does this lesson suggest?',
      'Dois times discutem nos próprios canais há um mês sobre quem deveria consertar uma biblioteca compartilhada. Cada gestora reclamou em particular com a própria diretora. O que esta aula sugere?'),
     ('Together, on one page.', 'Juntas, numa página.'),
     [(1, 'The two managers write the disagreement on one page, with both constraints, and escalate together',
       'Right: escalation is healthy when both sides do it together, with the disagreement written fairly.',
       'As duas gestoras escrevem a discordância numa página, com as duas restrições, e escalam juntas',
       'Isso: escalar é saudável quando os dois lados fazem juntos, com a discordância escrita de forma justa.'),
      (0, 'Whichever team cares more should fix it, since arguing costs more than the fix',
       'That rewards whoever gives in first and leaves the real priority question unanswered.',
       'O time que mais se importa deveria consertar, já que discutir custa mais que o conserto',
       'Isso recompensa quem cede primeiro e deixa sem resposta a questão de prioridade.'),
      (0, 'Wait for the directors to notice',
       'They have each heard one version, which is the problem.',
       'Esperar as diretoras perceberem',
       'Cada uma ouviu uma versão, que é o problema.'),
      (0, 'Each team works around the library',
       'Working around creates hidden dependencies and distrust.',
       'Cada time contorna a biblioteca',
       'Contornar cria dependências escondidas e desconfiança.')])
