"""Lesson 23: why people leave."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-p5ep7ccn')

quiz('ex-n9e2ehcc', 'the-reasons', 'easy',
     ('Camila said she was leaving for more pay and a shorter commute. What did her one-to-one notes show?',
      'A Camila disse que estava saindo por salário maior e trajeto mais curto. O que as notas de 1:1 dela mostravam?'),
     ('Three other things.', 'Outras três coisas.'),
     [(1, 'Requests for front-end work put off twice, a growth section empty since the autumn, and two holidays on call in a row',
       'Right: all visible for months, and none would appear in an exit survey.',
       'Pedidos de front-end adiados duas vezes, uma seção de crescimento vazia desde o outono, e dois feriados seguidos de plantão',
       'Isso: tudo visível havia meses, e nada apareceria numa pesquisa de saída.'),
      (0, 'Nothing beyond what she said',
       'Rereading the notes found three earlier causes.',
       'Nada além do que ela disse',
       'Reler as notas revelou três causas anteriores.'),
      (0, 'A conflict with Diego',
       'Nothing like that is in her notes.',
       'Um conflito com o Diego',
       'Nada disso está nas notas dela.'),
      (0, 'That she had been on an improvement plan earlier in the year, which nobody had mentioned to Renata',
       'She was steady and well liked; there was no plan.',
       'Que ela tinha estado num plano de melhoria no começo do ano, que ninguém mencionou à Renata',
       'Ela era constante e querida; não houve plano.')])

match('ex-wmp5zycm', 'the-reasons', 'medium',
      ('Match each reason for leaving with who has most control over it, by the lesson’s table.',
       'Ligue cada motivo de saída a quem tem mais controle sobre ele, pela tabela da aula.'),
      ('The manager, the company, nobody.', 'A gestora, a empresa, ninguém.'),
      [('no path to new work', 'the manager', 'nenhum caminho para trabalho novo', 'a gestora'),
       ('pay below the market', 'the company, with the manager’s advocacy', 'salário abaixo do mercado', 'a empresa, com a defesa da gestora'),
       ('moving city for family', 'nobody at work', 'mudar de cidade pela família', 'ninguém no trabalho')],
      [('the team’s product manager', 'a gerente de produto do time')])

quiz('ex-6xnjzvpr', 'the-reasons', 'medium',
     ('In Herzberg’s terms, which of these is a motivator rather than a hygiene factor?',
      'Nos termos de Herzberg, qual destes é um fator motivador, e não higiênico?'),
     ('Bad hygiene dissatisfies; good hygiene motivates little.', 'Higiene ruim insatisfaz; higiene boa motiva pouco.'),
     [(1, 'Recognition for work done',
       'Right: achievement, recognition, responsibility and growth are what motivate.',
       'Reconhecimento pelo trabalho feito',
       'Isso: realização, reconhecimento, responsabilidade e crescimento são o que motiva.'),
      (0, 'Salary',
       'A hygiene factor: its absence dissatisfies, its presence motivates little.',
       'Salário',
       'Um fator higiênico: a falta insatisfaz, a presença motiva pouco.'),
      (0, 'Company policies on working hours, leave and expenses',
       'Policies are hygiene factors.',
       'Políticas da empresa sobre horário, férias e despesas',
       'Políticas são fatores higiênicos.'),
      (0, 'Office conditions',
       'Conditions are a hygiene factor.',
       'Condições do escritório',
       'Condições são um fator higiênico.')])

quiz('ex-c7f3wv7v', 'the-reasons', 'hard',
     ('Renata could not have matched Camila’s new salary. What does the lesson say was within her reach?',
      'A Renata não teria conseguido igualar o novo salário da Camila. O que a aula diz que estava ao alcance dela?'),
     ('Three things.', 'Três coisas.'),
     [(1, 'A real answer on front-end work, noticing the empty growth section, and asking about leaving earlier',
       'Right: each was a reason within her control, visible months before the resignation.',
       'Uma resposta de verdade sobre front-end, perceber a seção de crescimento vazia, e perguntar sobre sair antes',
       'Isso: cada um era um motivo sob o controle dela, visível meses antes do pedido de demissão.'),
      (0, 'A counter-offer',
       'Caju made none, because her reasons were not mainly money.',
       'Uma contraproposta',
       'A Caju não fez, porque os motivos dela não eram sobretudo dinheiro.'),
      (0, 'Nothing: a better offer is outside a manager’s control',
       'The offer was, the earlier reasons were not.',
       'Nada: uma proposta melhor está fora do controle de uma gestora',
       'A proposta estava, os motivos anteriores não.'),
      (0, 'A promotion to senior, which would have come with a salary close to the other company’s',
       'Promotion follows evidence on the ladder, not retention.',
       'Uma promoção a sênior, que viria com um salário próximo ao da outra empresa',
       'Promoção segue evidência na escada, não retenção.')])

num('ex-9yrwm20b', 'measuring', 'easy',
    ('A team of 20, on average over the year, lost 3 people. What is its attrition rate, as a percentage?',
     'Um time com média de 20 pessoas no ano perdeu 3. Qual é a taxa de rotatividade, em porcentagem?'),
    ('3 divided by 20.', '3 dividido por 20.'),
    15, 0, ('percent', 'por cento'), (['%'], ['%']))

num('ex-5zxh1sed', 'measuring', 'medium',
    ('Agenda averaged 7 people over the year and lost 2, one of them regretted. What was the regretted attrition rate, to one decimal place?',
     'O Agenda teve média de 7 pessoas no ano e perdeu 2, uma delas lamentada. Qual foi a taxa de saídas lamentadas, com uma casa decimal?'),
    ('1 divided by 7.', '1 dividido por 7.'),
    14.3, 0.05, ('percent', 'por cento'), (['%'], ['%']))

quiz('ex-x611ctsh', 'measuring', 'medium',
     ('Why does the lesson say a rate for a team of seven says little on its own?',
      'Por que a aula diz que a taxa de um time de sete diz pouco sozinha?'),
     ('Two people.', 'Duas pessoas.'),
     [(1, 'Single events',
       'Right: almost 29% was two people.',
       'Casos isolados',
       'Isso: quase 29% eram duas pessoas.'),
      (0, 'Small teams have no attrition',
       'Agenda lost two people.',
       'Times pequenos não têm rotatividade',
       'O Agenda perdeu duas pessoas.'),
      (0, 'Because only the company-wide rate is calculated correctly, with the average headcount',
       'Any team’s rate can be calculated correctly; small teams are just noisy.',
       'Porque só a taxa da empresa inteira é calculada direito, com a média de pessoas',
       'A taxa de qualquer time pode ser calculada direito; times pequenos só são ruidosos.'),
      (0, 'Seven is below the legal minimum for reporting',
       'No legal minimum is mentioned.',
       'Sete está abaixo do mínimo legal para reportar',
       'Nenhum mínimo legal é mencionado.')])

quiz('ex-pn2pdps0', 'measuring', 'medium',
     ('Which line does the lesson say is always the question for a manager?',
      'Que linha a aula diz que é sempre a pergunta para uma gestora?'),
     ('And then: why.', 'E depois: por quê.'),
     [(1, 'Regretted departures',
       'Right: losing the people the team most needs matters whatever the total says.',
       'As saídas lamentadas',
       'Isso: perder as pessoas de que o time mais precisa importa, diga o total o que disser.'),
      (0, 'The total attrition rate, since it is what the company compares across teams',
       'The total hides whether the people lost were the ones the team wanted.',
       'A taxa total de rotatividade, já que é ela que a empresa compara entre times',
       'O total esconde se as pessoas perdidas eram as que o time queria.'),
      (0, 'Involuntary departures',
       'A different split, and not the one the lesson singles out.',
       'As saídas involuntárias',
       'Outra separação, e não a que a aula destaca.'),
      (0, 'Unregretted departures',
       'These may mean performance is handled honestly.',
       'As saídas não lamentadas',
       'Estas podem indicar que o desempenho está sendo tratado com honestidade.')])

quiz('ex-3vt9vhpz', 'stay-conversations', 'easy',
     ('What makes a stay conversation more useful than an exit interview?',
      'O que torna uma conversa de permanência mais útil que uma entrevista de saída?'),
     ('Timing.', 'Momento.'),
     [(1, 'It comes while the person has not decided, and their answer still has a chance to change something',
       'Right: an exit interview asks when nothing can change and the person has every reason to be polite.',
       'Vem enquanto a pessoa não decidiu, e a resposta dela ainda tem chance de mudar alguma coisa',
       'Isso: a entrevista de saída pergunta quando nada pode mudar e a pessoa tem todo motivo para ser educada.'),
      (0, 'It is anonymous',
       'It is a one-to-one, not anonymous.',
       'É anônima',
       'É uma 1:1, não é anônima.'),
      (0, 'It is shorter',
       'Length is not the point.',
       'É mais curta',
       'Duração não é o ponto.'),
      (0, 'Because HR runs it, so people are more honest than they would be with their own manager',
       'The manager runs it, in a one-to-one.',
       'Porque o RH conduz, então as pessoas são mais honestas do que seriam com a própria gestora',
       'Quem conduz é a gestora, numa 1:1.')])

quiz('ex-xkn7q6pa', 'stay-conversations', 'medium',
     ('Why is “When was the last time you thought about leaving?” the most useful of the five questions?',
      'Por que “Quando foi a última vez que você pensou em sair?” é a mais útil das cinco perguntas?'),
     ('A moment, not a state.', 'Um momento, não um estado.'),
     [(1, 'It treats thinking about leaving as normal and asks for a specific moment',
       'Right: a specific moment points at a specific cause.',
       'Trata pensar em sair como normal e pede um momento específico',
       'Isso: um momento específico aponta para uma causa específica.'),
      (0, 'It catches people who are about to resign',
       'It is not a trap; it surfaces causes.',
       'Pega quem está prestes a pedir demissão',
       'Não é armadilha; faz as causas aparecerem.'),
      (0, 'Because people answer it with a yes or no, which makes it easy to compare across the team',
       'It asks for a moment, not yes or no.',
       'Porque as pessoas respondem com sim ou não, o que facilita comparar no time',
       'Ela pede um momento, não sim ou não.'),
      (0, 'Because it is the hardest to answer',
       'People hesitate over it, but that is not why it is useful.',
       'Porque é a mais difícil de responder',
       'As pessoas hesitam, mas não é por isso que é útil.')])

mc('ex-6wzg47rf', 'stay-conversations', 'medium',
   ('Which of these did people on Agenda name as moments they had thought about leaving? Choose all that apply.',
    'Quais destes as pessoas do Agenda nomearam como momentos em que pensaram em sair? Marque todos que se aplicam.'),
   ('Three of five named one.', 'Três de cinco nomearam um.'),
   [(1, 'Diego: a staff case refused without explanation', 'Yes, under the previous manager.',
     'Diego: um caso para staff recusado sem explicação', 'Sim, com o gestor anterior.'),
    (1, 'Paula: the year nobody noticed her glue work', 'Yes.',
     'Paula: o ano em que ninguém percebia o trabalho de cola dela', 'Sim.'),
    (1, 'Yara: the risk of being pulled back to work on Agenda alone', 'Yes: what would make her leave.',
     'Yara: o risco de ser puxada de volta para trabalhar só no Agenda', 'Sim: o que a faria sair.'),
    (0, 'Thiago: on-call', 'No: Thiago said he had not thought about it.',
     'Thiago: o plantão', 'Não: o Thiago disse que não tinha pensado nisso.'),
    (0, 'Lucas: the onboarding', 'No: the question had never occurred to him.',
     'Lucas: a integração', 'Não: a pergunta nunca tinha lhe ocorrido.')])

cloze('ex-ma2zs0ca', 'stay-conversations', 'easy',
      ('Money offered to stay after a resignation is called a ___-offer.',
       'Dinheiro oferecido para ficar depois de um pedido de demissão se chama ___.'),
      ('Against an offer.', 'Contra uma proposta.'),
      [(['counter'], ['contraproposta'])])

quiz('ex-tjp3hwcp', 'drill', 'hard',
     ('A strong engineer resigns citing salary. The manager wants to counter-offer. The engineer’s notes show two years without new work and repeated, unanswered requests to change teams. What does this lesson suggest?',
      'Uma engenheira forte pede demissão citando salário. O gestor quer fazer uma contraproposta. As notas dela mostram dois anos sem trabalho novo e pedidos repetidos, sem resposta, para mudar de time. O que esta aula sugere?'),
     ('After the raise, what is still there?', 'Depois do aumento, o que continua lá?'),
     [(1, 'The real reasons stay after a raise',
       'Right: growth and the unanswered requests remain after a raise.',
       'Os motivos de verdade ficam depois do aumento',
       'Isso: o crescimento e os pedidos sem resposta continuam depois de um aumento.'),
      (0, 'Counter-offer at once, since salary was the reason she gave in the exit conversation',
       'The reason given is the safest one; the notes show others.',
       'Fazer a contraproposta de imediato, já que salário foi o motivo que ela deu na conversa de saída',
       'O motivo dado é o mais seguro; as notas mostram outros.'),
      (0, 'Promote her to keep her',
       'Promotion follows the ladder, and does not fix the lack of new work.',
       'Promovê-la para mantê-la',
       'Promoção segue a escada, e não resolve a falta de trabalho novo.'),
      (0, 'Ask her colleagues why she is leaving',
       'Her own notes already say much of it.',
       'Perguntar aos colegas dela por que está saindo',
       'As próprias notas dela já dizem boa parte.')])
