"""Lesson 24: managing up."""
from questions import lesson, quiz, mc, order, match, cloze, num

lesson('le-2ryz2ah2')

mc('ex-vtmhrw3d', 'your-manager', 'easy',
   ('Which three things did Otávio say he needed from Renata?',
    'Quais três coisas o Otávio disse que precisava da Renata?'),
   ('Three of the five.', 'Três das cinco.'),
   [(1, 'No surprises', 'Right: bad news from her before anybody else.',
     'Nenhuma surpresa', 'Isso: as más notícias por ela, antes de qualquer outra pessoa.'),
    (1, 'Problems that come with options', 'Right: with a recommendation, decided in five minutes.',
     'Problemas que chegam com opções', 'Isso: com uma recomendação, decididos em cinco minutos.'),
    (1, 'Her honest read of the team', 'Right: including what was going badly.',
     'A leitura honesta dela sobre o time', 'Isso: inclusive o que ia mal.'),
    (0, 'A weekly report of every ticket the team closed', 'He had eleven teams; status was not what he asked for.',
     'Um relatório semanal de cada ticket que o time fechou', 'Ele tinha onze times; status não foi o que pediu.'),
    (0, 'That she solve problems without involving him', 'He wanted problems brought to him, with options.',
     'Que ela resolvesse problemas sem envolvê-lo', 'Ele queria os problemas levados a ele, com opções.')])

quiz('ex-k1sentkx', 'your-manager', 'medium',
     ('Why does bad news that reaches a manager’s manager from somebody else cost so much?',
      'Por que uma má notícia que chega ao gestor da gestora por outra pessoa custa tanto?'),
     ('A question it raises.', 'Uma pergunta que ela levanta.'),
     [(1, 'It raises the question of what else has not been told',
       'Right: the cost is to trust, not to the news itself.',
       'Levanta a pergunta do que mais não foi contado',
       'Isso: o custo é na confiança, não na notícia em si.'),
      (0, 'The news is worse when it comes second-hand',
       'The news is the same; what changes is what the silence implies.',
       'A notícia fica pior quando chega de segunda mão',
       'A notícia é a mesma; o que muda é o que o silêncio sugere.'),
      (0, 'Company policy requires managers to report incidents within a day',
       'The lesson names no policy; the argument is about trust.',
       'A política da empresa exige que gestoras reportem incidentes em um dia',
       'A aula não cita política nenhuma; o argumento é sobre confiança.'),
      (0, 'He will then have to escalate it himself, to his own director, the same day',
       'Not the reason given.',
       'Ele vai ter de escalar o assunto ele mesmo, ao próprio diretor, no mesmo dia',
       'Não é o motivo dado.')])

match('ex-cgyev1t3', 'your-manager', 'medium',
      ('Match each item from Renata’s one-to-one with Otávio to its kind.',
       'Ligue cada item da 1:1 da Renata com o Otávio ao seu tipo.'),
      ('Inform, decide, help.', 'Informar, decidir, ajudar.'),
      [('"The confirmations work slips two weeks."', 'something he needs to know',
        '"O trabalho de confirmações atrasa duas semanas."', 'algo que ele precisa saber'),
       ('"Two options for the Payments dependency; I recommend the second."', 'a decision she needs from him',
        '"Duas opções para a dependência com Pagamentos; recomendo a segunda."', 'uma decisão que ela precisa dele'),
       ('"I’d like your view on how I handled the debrief."', 'help she wants',
        '"Queria a sua opinião sobre como conduzi a conversa de decisão."', 'ajuda que ela quer')],
      [('a status report', 'um relatório de status')])

quiz('ex-pzffsyfp', 'your-manager', 'hard',
     ('Otávio twice committed Agenda to dates without asking Renata. What did she do?',
      'O Otávio comprometeu o Agenda duas vezes com datas sem perguntar à Renata. O que ela fez?'),
     ('Lesson 8, upwards.', 'A aula 8, para cima.'),
     [(1, 'Gave him feedback in private: the meetings, the effect, and what he would need to check first',
       'Right: the same structure as feedback downwards, and they agreed he would say he would confirm with her.',
       'Deu feedback em particular: as reuniões, o efeito, e do que ele precisaria para checar antes',
       'Isso: a mesma estrutura do feedback para baixo, e combinaram que ele diria que ia confirmar com ela.'),
      (0, 'Raised it with his manager',
       'She went to him first, privately.',
       'Levou o assunto ao gestor dele',
       'Ela foi a ele primeiro, em particular.'),
      (0, 'Told the team the dates were his and not hers',
       'That turns a decision into a grievance, which the lesson warns against.',
       'Disse ao time que as datas eram dele e não dela',
       'Isso transforma uma decisão em queixa, o que a aula desaconselha.'),
      (0, 'Accepted it as part of the job',
       'Saying nothing teaches the team that feedback runs one way.',
       'Aceitou como parte do trabalho',
       'Calar ensina ao time que feedback só anda num sentido.')])

quiz('ex-f67wpvs5', 'peers', 'easy',
     ('In Lencioni’s argument, who is a leader’s first team?',
      'No argumento de Lencioni, quem é o primeiro time de uma liderança?'),
     ('Not the people who report to them.', 'Não as pessoas que se reportam a ela.'),
     [(1, 'Their peers, the other managers reporting to the same person',
       'Right: because most problems a manager cannot solve alone are between teams.',
       'Os pares, as outras gestoras que se reportam à mesma pessoa',
       'Isso: porque a maioria dos problemas que uma gestora não resolve sozinha é entre times.'),
      (0, 'The people who report to them',
       'That is the natural view; Lencioni argues against it.',
       'As pessoas que se reportam a ela',
       'Essa é a visão natural; Lencioni argumenta contra ela.'),
      (0, 'Their own manager, and the directors above that manager, who set the priorities',
       'Not the claim.',
       'O próprio gestor, e os diretores acima dele, que definem as prioridades',
       'Não é a afirmação.'),
      (0, 'The product manager and designer working with the team',
       'Close collaborators, but not the claim.',
       'A gerente de produto e a designer que trabalham com o time',
       'Colaboradoras próximas, mas não é a afirmação.')])

quiz('ex-p13mkqkc', 'peers', 'medium',
     ('What did the monthly coffee between Renata and Bia have on its agenda?',
      'O que estava na pauta do café mensal entre a Renata e a Bia?'),
     ('Lesson text.', 'Texto da aula.'),
     [(1, 'Nothing: it had no agenda',
       'Right: and it paid off in ways neither planned.',
       'Nada: não tinha pauta',
       'Isso: e rendeu de formas que nenhuma das duas planejou.'),
      (0, 'The open items of the Payments dependency, reviewed in order',
       'The dependency was what led to it, not its agenda.',
       'Os pontos abertos da dependência com Pagamentos, revistos em ordem',
       'A dependência foi o que levou ao café, não a pauta dele.'),
      (0, 'Each team’s incidents from the month',
       'Not described.',
       'Os incidentes do mês de cada time',
       'Não é o descrito.'),
      (0, 'Headcount requests for the next quarter',
       'Not described.',
       'Pedidos de vagas para o próximo trimestre',
       'Não é o descrito.')])

quiz('ex-d7wkb26x', 'peers', 'medium',
     ('What changed in the fortnightly meeting of Otávio’s managers after Renata’s suggestion?',
      'O que mudou na reunião quinzenal das gestoras do Otávio depois da sugestão da Renata?'),
     ('Status went somewhere else.', 'O status foi para outro lugar.'),
     [(1, 'It opened with problems crossing teams, and status became a written update read beforehand',
       'Right: the time together went on what needed the others in the room.',
       'Passou a abrir com problemas entre times, e o status virou uma atualização escrita lida antes',
       'Isso: o tempo juntas foi para o que precisava das outras na sala.'),
      (0, 'It moved from fortnightly to weekly',
       'The cadence was not the problem.',
       'Passou de quinzenal para semanal',
       'A cadência não era o problema.'),
      (0, 'Each manager got a fixed five minutes to report',
       'That is the status format it replaced.',
       'Cada gestora ganhou cinco minutos fixos para reportar',
       'Esse é o formato de status que foi substituído.'),
      (0, 'Otávio stopped attending',
       'Not described.',
       'O Otávio parou de participar',
       'Não é o descrito.')])

quiz('ex-v5fgmtxv', 'the-promise', 'easy',
     ('Yara asked whether she would definitely be promoted if she led the migration. Why could Renata not promise it?',
      'A Yara perguntou se seria promovida com certeza se liderasse a migração. Por que a Renata não podia prometer?'),
     ('Whose decision.', 'De quem é a decisão.'),
     [(1, 'The decision belonged to the panel',
       'Right: a promise would have been about somebody else’s decision.',
       'A decisão era do comitê',
       'Isso: a promessa seria sobre a decisão de outras pessoas.'),
      (0, 'She thought Yara was not ready',
       'She believed Yara probably would be promoted.',
       'Ela achava que a Yara não estava pronta',
       'Ela achava que a Yara provavelmente seria promovida.'),
      (0, 'Caju forbids managers from discussing promotions with their reports',
       'She discussed it openly, just without a promise.',
       'A Caju proíbe gestoras de discutir promoções com quem se reporta a elas',
       'Ela discutiu abertamente, só sem prometer.'),
      (0, 'The migration was not yet approved',
       'Not the reason given.',
       'A migração ainda não tinha sido aprovada',
       'Não é o motivo dado.')])

order('ex-w0agkc8r', 'the-promise', 'medium',
      ('Put in order the shape of what Renata said instead of a promise.',
       'Ponha em ordem a forma do que a Renata disse no lugar de uma promessa.'),
      ('Four parts.', 'Quatro partes.'),
      [('what she knew', 'o que ela sabia'),
       ('what she did not know', 'o que não sabia'),
       ('what she would do', 'o que ia fazer'),
       ('when she would come back', 'quando voltaria a falar')],
      trap=('Ending on the action without a date leaves the person waiting with no end.',
            'Terminar na ação sem data deixa a pessoa esperando sem fim.'))

quiz('ex-h72zy004', 'the-promise', 'medium',
     ('Somebody asks directly about a reorganisation you know of and cannot discuss. What does the lesson recommend?',
      'Alguém pergunta diretamente sobre uma reorganização de que você sabe e não pode discutir. O que a aula recomenda?'),
     ('Do not lie.', 'Não minta.'),
     [(1, '"That’s not something I’m able to discuss."',
       'Right: honest, and respected more than people expect.',
       '"Não posso falar sobre isso."',
       'Isso: honesto, e mais respeitado do que as pessoas esperam.'),
      (0, '"There’s nothing going on."',
       'A lie that will be remembered, and every later reassurance discounted.',
       '"Não está acontecendo nada."',
       'Uma mentira que vai ser lembrada, e toda tranquilização futura descontada.'),
      (0, 'Change the subject without answering, and raise it with your own manager afterwards',
       'Avoiding the question reads as an answer; say plainly you cannot discuss it.',
       'Mudar de assunto sem responder, e levar ao seu gestor depois',
       'Fugir da pergunta soa como resposta; diga claramente que não pode discutir.'),
      (0, 'Share what you know in confidence',
       'You were asked not to; push for it to be shared early instead.',
       'Contar o que sabe em confiança',
       'Pediram que você não contasse; insista para que seja compartilhado cedo.')])

cloze('ex-4zdrz0sh', 'the-promise', 'medium',
      ('Each of Renata’s answers promises the manager’s own ____, which can be kept, and refuses to promise somebody else’s decision.',
       'Cada resposta da Renata promete uma ____ da própria gestora, que dá para cumprir, e se recusa a prometer a decisão de outra pessoa.'),
      ('What she will do.', 'O que ela vai fazer.'),
      [(['action', 'actions'], ['ação', 'acao'])])

quiz('ex-50qbnbp2', 'drill', 'hard',
     ('Fábio asks for a raise to match a friend’s offer. Which reply follows the lesson?',
      'O Fábio pede um aumento para igualar a oferta de um amigo. Qual resposta segue a aula?'),
     ('An action of hers, with a date.', 'Uma ação dela, com data.'),
     [(1, '"Pay bands are set by the company. I’ll check where you sit and tell you what I find by the end of the month."',
       'Right: it promises her own action and a date, not the company’s decision.',
       '"As faixas são definidas pela empresa. Vou ver onde você está e te digo o que encontrei até o fim do mês."',
       'Isso: promete uma ação dela e uma data, não a decisão da empresa.'),
      (0, '"I’ll get you the raise."',
       'Not hers to give.',
       '"Vou conseguir o aumento para você."',
       'Não cabe a ela dar.'),
      (0, '"That isn’t something managers deal with."',
       'True of the bands, but it offers nothing she can do.',
       '"Isso não é assunto de gestora."',
       'Verdade sobre as faixas, mas não oferece nada que ela possa fazer.'),
      (0, '"Your friend’s company pays more because it is riskier."',
       'Argues with the request instead of answering it.',
       '"A empresa do seu amigo paga mais porque é mais arriscada."',
       'Discute com o pedido em vez de respondê-lo.')])

quiz('ex-3013mxzs', 'drill', 'hard',
     ('Renata argued against a decision from above, and it went the other way. How does the lesson say she carries it to the team?',
      'A Renata argumentou contra uma decisão de cima, e ela foi para o outro lado. Como a aula diz que ela a leva ao time?'),
     ('Not dishonest, not a grievance.', 'Nem desonesta, nem queixa.'),
     [(1, 'As the team’s decision, acknowledging her disagreement if asked',
       'Right: "I argued for something different, it went the other way, and here’s what we’re going to do."',
       'Como decisão do time, reconhecendo a discordância se perguntarem',
       'Isso: "Eu defendi outra coisa, foi para o outro lado, e é isto que vamos fazer."'),
      (0, 'Presenting it as her own idea',
       'That is dishonest about the disagreement.',
       'Apresentando como ideia dela',
       'Isso é desonesto sobre a discordância.'),
      (0, 'Explaining that it came from Otávio and that she disagreed, so the team knows whom to blame',
       'That turns it into a grievance, and leaves a team trusting nobody above.',
       'Explicando que veio do Otávio e que ela discordou, para o time saber de quem é a culpa',
       'Isso a transforma em queixa, e deixa um time que não confia em ninguém acima.'),
      (0, 'Holding it back from the team until she has had one more chance to change Otávio’s mind',
       'Not what the lesson describes.',
       'Segurando a decisão longe do time até ter mais uma chance de mudar a cabeça do Otávio',
       'Não é o que a aula descreve.')])

quiz('ex-x5zvd798', 'drill', 'medium',
     ('Why does the lesson say a manager who never asks their own manager for help is not handling everything alone?',
      'Por que a aula diz que uma gestora que nunca pede ajuda a quem está acima não está dando conta de tudo sozinha?'),
     ('What she is doing alone instead.', 'O que ela está fazendo sozinha no lugar.'),
     [(1, 'She is making the mistakes alone, and her manager finds out later',
       'Right: the third kind of item is the one new managers leave out.',
       'Está errando sozinha, e quem está acima descobre depois',
       'Isso: o terceiro tipo de item é o que gestoras novas deixam de fora.'),
      (0, 'Her manager is quietly handling the hard parts for her without ever telling her about it',
       'Not the argument.',
       'O gestor dela está cuidando em silêncio das partes difíceis por ela, sem nunca contar',
       'Não é o argumento.'),
      (0, 'Her team carries the load',
       'Not the argument.',
       'O time dela carrega o peso',
       'Não é o argumento.'),
      (0, 'Asking for help is part of the formal review',
       'Nothing in the lesson says so.',
       'Pedir ajuda faz parte da avaliação formal',
       'Nada na aula diz isso.')])
