#!/usr/bin/env bash
# The terminal sessions quoted in lesson 2 of deep-learning, as a script that
# produces them. THE AUTHOR'S, NOT THE STUDENT'S: the lesson shows every command
# and every program, and nothing here names a file the student does not have.
#
# THE SCRIPT IS THE SOURCE AND ITS OUTPUT IS NOT COMMITTED. Every transcript in
# this lesson was copied from running it.
#
#   sudo bash ../../lab.sh up        # once
#   sudo LAB_SH=../../lab.sh bash captures.sh
#
# Every program comes out of the lesson's own sections through lab/shown.py, so
# what ran is what the page shows. NumPy only: nothing here imports torch.
# Recorded on Ubuntu 24.04, Python 3.12.3, four processors and no graphics card,
# TZ=America/Sao_Paulo, on 2026-10-10.
#
# STAGED: nothing. Every file the programs read is written by `use` from the
# lesson, and the ten points are generated by points.py, which the lesson shows.
. "$(dirname "${LAB_SH:-../../lab.sh}")/lab/capture.sh"
L=le-e4mqh2vm
lab reset

use points.py forward.py
block forward
on 'python forward.py 2'

use loss.py
block loss
on 'python loss.py'

use slope.py
block slope
on 'python slope.py'

use descent.py
block descent
on 'python descent.py'

use rates.py
block rates
on 'python rates.py'

use surface.py
block surface
on 'python surface.py 0.5'

block surface-diverge
on 'python surface.py 1.0 | head -4'
