global(localHostname="gw" workDirectory="/var/spool/rsyslog-gw")
module(load="imfile")
input(type="imfile" file="/var/log/soclab/gw-auth.log" tag="gw-auth:")
action(type="omfwd" target="192.168.99.10" port="514" protocol="tcp"
       template="RSYSLOG_SyslogProtocol23Format"
       queue.type="LinkedList" queue.filename="to-soc" queue.saveOnShutdown="on"
       action.resumeRetryCount="-1")
