module(load="imtcp")
template(name="perhost" type="string" string="/var/log/remote/%HOSTNAME%.log")
ruleset(name="remote") {
  action(type="omfile" dynaFile="perhost"
         fileCreateMode="0640" fileOwner="syslog" fileGroup="adm")
}
input(type="imtcp" address="192.168.99.10" port="514" ruleset="remote")
