S1="three-clocks"; S2="skew"; S3="out-of-order"; S4="counting-by-arrival"; S5="clocks-lie"; S6="which-time"; S7="timestamps-in-kafka"; D="drill"

Q(S1,"easy",("A sale is rung up at 10:21, stored by Kafka at 14:00 and read by a report next week. Which of its times never changes, however often it is read?","Uma venda é registrada às 10:21, gravada pelo Kafka às 14:00 e lida por um relatório na semana que vem. Qual dos horários dela nunca muda, por mais que ela seja lida?"),[
 ("The time Kafka stored it, because the log never rewrites a record","A hora em que o Kafka a gravou, porque o log nunca reescreve um registro",False,"Ingestion time is fixed too once written, but it is the log's time, not the sale's; send the sale again and it changes.","O tempo de ingestão também fica fixo depois de gravado, mas é o tempo do log, não da venda; mande a venda de novo e ele muda."),
 ("Its event time","O tempo do evento",True,"Right. 10:21 belongs to the sale; the other two belong to the machinery.","Isso. 10:21 pertence à venda; os outros dois pertencem à maquinaria."),
 ("Its processing time, once the first reader has handled it","O tempo de processamento, depois que o primeiro leitor a tratou",False,"Processing time is every moment anybody reads it; next week's report gives it another.","O tempo de processamento é cada momento em que alguém a lê; o relatório da semana que vem dá outro."),
 ("None of them, since every clock drifts","Nenhum deles, já que todo relógio deriva",False,"Drift makes a clock wrong, not a recorded time mutable.","Deriva deixa um relógio errado, não torna mutável um horário registrado."),
])
Q(S1,"medium",("A topic has `message.timestamp.type=LogAppendTime`. A producer passes `timestamp=` with 2 March 2026 on a record it sends today. What timestamp does the record carry?","Um tópico tem `message.timestamp.type=LogAppendTime`. Um produtor passa `timestamp=` com 2 de março de 2026 num registro que envia hoje. Que timestamp o registro carrega?"),[
 ("2 March 2026, because the producer set it","2 de março de 2026, porque o produtor definiu",False,"That is CreateTime's behaviour. LogAppendTime throws the producer's value away.","Esse é o comportamento de CreateTime. LogAppendTime descarta o valor do produtor."),
 ("Both, in two fields of the record","Os dois, em dois campos do registro",False,"A record has one timestamp field; the topic decides what goes in it.","Um registro tem um único campo de timestamp; o tópico decide o que vai nele."),
 ("Today's date, from the clock of the consumer that reads it","A data de hoje, do relógio do consumidor que o lê",False,"The consumer's clock is processing time, and it is never written into the record.","O relógio do consumidor é o tempo de processamento, e ele nunca é escrito no registro."),
 ("The broker's clock at the moment it appended the record","O relógio do broker no momento em que anexou o registro",True,"Right. The console consumer then labels it LogAppendTime.","Isso. O consumidor de console então o rotula como LogAppendTime."),
])
C(S1,"easy",("With the default `message.timestamp.type`, which is ___, a record keeps whatever timestamp the producer gave it.","Com o `message.timestamp.type` padrão, que é ___, um registro guarda o timestamp que o produtor deu a ele."),[(["CreateTime"],["CreateTime"])])
Q(S1,"hard",("`tills.py` sends a sale whose `at` says 2 March, and the consumer prints `CreateTime:` with a number that decodes to the day you ran it. What explains the gap?","O `tills.py` manda uma venda cujo `at` diz 2 de março, e o consumidor imprime `CreateTime:` com um número que decodifica para o dia em que você o rodou. O que explica a diferença?"),[
 ("The broker overwrote the producer's value, as it does on every topic","O broker sobrescreveu o valor do produtor, como faz em todo tópico",False,"Only a LogAppendTime topic does that, and `clocks` keeps CreateTime.","Só um tópico com LogAppendTime faz isso, e `clocks` guarda CreateTime."),
 ("The till's clock is invented; the client stamped the machine's real one","O relógio do caixa é inventado; o cliente carimbou o real da máquina",True,"Right. `tills.py` sets no timestamp, so the client writes its own present.","Isso. O `tills.py` não define timestamp, então o cliente escreve o próprio presente."),
 ("The consumer converted the time to its own time zone, which moved the date","O consumidor converteu a hora para o próprio fuso, o que mudou a data",False,"A time zone moves a time by hours, not by seven months.","Um fuso muda a hora em horas, não em sete meses."),
 ("A wrong clock in the virtual machine","Um relógio errado na máquina virtual",False,"The machine's clock was right; it was the shop clock that was made up.","O relógio da máquina estava certo; o relógio da loja é que foi inventado."),
])
N(S2,"easy",("A sale happened at 10:45:00 and reached Kafka at 14:00:00. What is its skew, in minutes?","Uma venda aconteceu às 10:45:00 e chegou ao Kafka às 14:00:00. Qual é o skew dela, em minutos?"),195,0,("minutes","minutos"),hint=("Arrival minus event.","Chegada menos evento."))
Q(S2,"medium",("Why does `late_tills.py` pass `timestamp=` to `produce` instead of leaving it out?","Por que o `late_tills.py` passa `timestamp=` para o `produce` em vez de deixá-lo de fora?"),[
 ("Kafka refuses a record with no timestamp","O Kafka recusa um registro sem timestamp",False,"A producer that sets none gets its own present stamped by the client.","Um produtor que não define nenhum recebe o próprio presente, carimbado pelo cliente."),
 ("It sends a whole day in seconds, so the present would be wrong","Ele envia um dia inteiro em segundos, então o presente estaria errado",True,"Right. It writes the time each sale would have been sent, which a live till gets for free.","Isso. Ele escreve a hora em que cada venda teria sido enviada, o que um caixa ao vivo tem de graça."),
 ("To make the topic delete each record seven days after its sale, as retention would","Para fazer o tópico apagar cada registro sete dias depois da venda, como faria a retenção",False,"Retention is the opposite worry: March stamps would be deleted at once, hence retention.ms=-1.","A retenção é a preocupação oposta: carimbos de março seriam apagados logo, daí o retention.ms=-1."),
 ("So that the console consumer prints the sales in event order","Para que o consumidor de console imprima as vendas na ordem dos eventos",False,"The consumer prints in log order whatever the stamps say.","O consumidor imprime na ordem do log, digam os carimbos o que disserem."),
])
Q(S2,"hard",("A delivery company's vans send their scans over the phone network, and the skew plot shows a thin band near the diagonal plus a few rows of points far above it. What are the rows most likely to be?","As vans de uma transportadora mandam as leituras pela rede de celular, e o gráfico de skew mostra uma faixa fina perto da diagonal e algumas linhas de pontos bem acima dela. O que essas linhas provavelmente são?"),[
 ("Scans that were made twice","Leituras que foram feitas duas vezes",False,"A duplicate is a second dot, not a dot moved up; height is the delay.","Uma duplicata é um segundo ponto, não um ponto deslocado para cima; a altura é o atraso."),
 ("Vans whose clocks run slow","Vans cujo relógio está atrasado",False,"A slow clock moves dots consistently by a fixed amount; a flat row means many events arriving at one moment.","Um relógio atrasado desloca os pontos sempre pelo mesmo tanto; uma linha horizontal são muitos eventos chegando num momento."),
 ("Vans that lost signal and sent what they held on reconnecting","Vans que perderam sinal e mandaram o que guardaram ao reconectar",True,"Right. Like Natal's till: many events from a span of time, one arrival time.","Isso. Como o caixa de Natal: muitos eventos de um intervalo de tempo, um só horário de chegada."),
 ("Scans that arrived before they were made","Leituras que chegaram antes de serem feitas",False,"Those would sit below the diagonal, and only a lying clock puts them there.","Essas ficariam abaixo da diagonal, e só um relógio mentiroso as põe ali."),
])
N(S3,"medium",("In arrival order, five sales have event times 09:00:10, 09:00:40, 09:00:25, 09:01:30, 09:00:50. How far out of order, in seconds, is the last one?","Na ordem de chegada, cinco vendas têm tempos do evento 09:00:10, 09:00:40, 09:00:25, 09:01:30, 09:00:50. Quão fora de ordem, em segundos, está a última?"),40,0,("seconds","segundos"),hint=("Compare it with the latest event time seen before it.","Compare com o maior tempo do evento visto antes dela."))
N(S3,"medium",("In the same five sales, 09:00:10, 09:00:40, 09:00:25, 09:01:30, 09:00:50 in arrival order, how many arrived out of order?","Nas mesmas cinco vendas, 09:00:10, 09:00:40, 09:00:25, 09:01:30, 09:00:50 na ordem de chegada, quantas chegaram fora de ordem?"),2,0,("sales","vendas"))
Q(S3,"medium",("68 of the 360 sales arrived out of order. Why is that not the same as the 38 Natal held back?","68 das 360 vendas chegaram fora de ordem. Por que isso não é o mesmo que as 38 que Natal reteve?"),[
 ("Thirty were ordinary sales slowed by seconds on the way","Trinta eram vendas comuns atrasadas por segundos no caminho",True,"Right. Slow deliveries from every shop, up to 92 seconds behind.","Isso. Entregas lentas de todas as lojas, até 92 segundos atrás."),
 ("The awk count is wrong, because it compares strings instead of times","A contagem do awk está errada, porque compara strings em vez de horários",False,"jq turns each `at` into seconds first; awk compares numbers.","O jq transforma cada `at` em segundos antes; o awk compara números."),
 ("Natal's sales were counted twice, once when held and once when sent","As vendas de Natal foram contadas duas vezes, uma quando retidas e outra quando enviadas",False,"Each sale is one record, counted once.","Cada venda é um registro, contado uma vez."),
 ("The other thirty came from a second partition read in parallel","As outras trinta vieram de uma segunda partição lida em paralelo",False,"The `late` topic has one partition, chosen so that arrival order is one order.","O tópico `late` tem uma partição, escolhida para que a ordem de chegada seja uma só."),
])
Q(S3,"hard",("Why would waiting two minutes before counting fix one group of out-of-order sales and not the other?","Por que esperar dois minutos antes de contar resolveria um grupo de vendas fora de ordem e não o outro?"),[
 ("Two minutes is longer than the slow deliveries and nowhere near Natal's hours","Dois minutos é mais que as entregas lentas e nem perto das horas de Natal",True,"Right. The distribution has two populations, and one wait cannot serve both.","Isso. A distribuição tem duas populações, e uma só espera não serve às duas."),
 ("Natal's sales are in another partition, which no wait can reach","As vendas de Natal estão em outra partição, que nenhuma espera alcança",False,"They are in the same single partition; the problem is how late they are.","Elas estão na mesma partição única; o problema é o quanto estão atrasadas."),
 ("Waiting only helps sales from the same shop, because each key keeps a wait of its own","Esperar só ajuda vendas da mesma loja, porque cada chave mantém uma espera própria",False,"The slow deliveries come from every shop, and a wait helps all of them.","As entregas lentas vêm de todas as lojas, e uma espera ajuda todas elas."),
 ("A wait reorders events by key, and Natal has no key","Uma espera reordena os eventos por chave, e Natal não tem chave",False,"Every sale is keyed by its shop, Natal's included.","Toda venda tem a loja como chave, inclusive as de Natal."),
])
Q(S4,"easy",("Counted by arrival, the 14:00 hour has 93 sales; by event time, 54. Which number belongs in the manager's report of sales per hour?","Contada pela chegada, a hora das 14:00 tem 93 vendas; pelo tempo do evento, 54. Qual número vai no relatório de vendas por hora do gerente?"),[
 ("93, because those are the sales the system received in that hour","93, porque essas são as vendas que o sistema recebeu naquela hora",False,"That answers a question about the pipeline, not about the shops.","Isso responde uma pergunta sobre o pipeline, não sobre as lojas."),
 ("54","54",True,"Right. The hour belongs to the sale, and 39 of those 93 happened earlier.","Isso. A hora pertence à venda, e 39 daquelas 93 aconteceram antes."),
 ("Their average, 73.5, to split the difference","A média delas, 73,5, para dividir a diferença",False,"An average of two answers to two questions answers neither.","Uma média de duas respostas a duas perguntas não responde nenhuma."),
 ("Neither, until the till in Natal is replaced","Nenhum dos dois, até trocarem o caixa de Natal",False,"The till did nothing wrong; it was offline.","O caixa não fez nada errado; ficou sem conexão."),
])
N(S4,"medium",("Event times, in arrival order: 10:58, 11:02, 10:59, 11:05, 10:57, 11:10. All arrive between 11:00 and 11:15. Counted by event time, how many fall in the 10:00 hour?","Tempos do evento, na ordem de chegada: 10:58, 11:02, 10:59, 11:05, 10:57, 11:10. Todos chegam entre 11:00 e 11:15. Contados pelo tempo do evento, quantos caem na hora das 10:00?"),3,0,("sales","vendas"))
Q(S4,"medium",("Why does `per_minute.py` use the record's timestamp as processing time instead of its own clock?","Por que o `per_minute.py` usa o timestamp do registro como tempo de processamento em vez do próprio relógio?"),[
 ("Reading after the fact, its own clock would put every sale in one minute","Lendo depois do fato, o próprio relógio poria toda venda num minuto só",True,"Right. The record's timestamp is when a reader keeping up would have seen it.","Isso. O timestamp do registro é quando um leitor em dia a teria visto."),
 ("Python cannot read the system clock inside a Kafka consumer","Python não consegue ler o relógio do sistema dentro de um consumidor Kafka",False,"It can; doing so would just measure the moment of the rerun.","Consegue; fazer isso só mediria o momento da reexecução."),
 ("The record's timestamp is the event time","O timestamp do registro é o tempo do evento",False,"In `late` it is the time of sending; the event time is `at`.","Em `late` ele é a hora do envio; o tempo do evento é o `at`."),
 ("The broker's clock is more accurate than the virtual machine's","O relógio do broker é mais preciso que o da máquina virtual",False,"They are the same machine here; accuracy is not the reason.","Aqui é a mesma máquina; precisão não é o motivo."),
])
Q(S4,"hard",("At 11:00, a processor reports the 10:00 hour by event time as 55 sales. At 14:30 it reports the same hour as 62. Which statement is right?","Às 11:00, um processador informa a hora das 10:00 pelo tempo do evento como 55 vendas. Às 14:30 ele informa a mesma hora como 62. Qual afirmação está certa?"),[
 ("The second report is a duplicate count of seven sales","O segundo relatório conta sete vendas em dobro",False,"Nothing was counted twice; seven sales of that hour had not arrived yet.","Nada foi contado em dobro; sete vendas daquela hora ainda não tinham chegado."),
 ("The processor should have counted by arrival to avoid changing its answer","O processador deveria ter contado pela chegada para não mudar a resposta",False,"By arrival the answer never changes and is wrong for good.","Pela chegada a resposta nunca muda e fica errada para sempre."),
 ("Event-time counts are only final once late events are in","Contagens por evento só ficam finais quando os atrasados chegam",True,"Right. The processor cannot know when that is, which is lesson 11's subject.","Isso. O processador não tem como saber quando isso acontece, que é o assunto da lição 11."),
 ("The first report was wrong because the clock in Natal was wrong","O primeiro relatório estava errado porque o relógio de Natal estava errado",False,"Natal's clock was right; its sales were late.","O relógio de Natal estava certo; as vendas é que estavam atrasadas."),
])
Q(S5,"easy",("Since Kafka 4.0, what happens by default to a record on a `CreateTime` topic stamped two hours in the future?","Desde o Kafka 4.0, o que acontece por padrão com um registro num tópico `CreateTime` carimbado duas horas no futuro?"),[
 ("It is stored, and its timestamp is replaced by the broker's","Ele é gravado, e o timestamp é trocado pelo do broker",False,"That is what a LogAppendTime topic does.","Isso é o que um tópico LogAppendTime faz."),
 ("It is stored unchanged, as every timestamp is","Ele é gravado sem mudança, como todo timestamp",False,"before Kafka 4.0 that was the default; now the limit is an hour ahead.","Antes do Kafka 4.0 esse era o padrão; agora o limite é uma hora à frente."),
 ("It is refused","Ele é recusado",True,"Right. `message.timestamp.after.max.ms` is an hour, and the producer gets `Invalid timestamp`.","Isso. `message.timestamp.after.max.ms` é uma hora, e o produtor recebe `Invalid timestamp`."),
 ("It is stored and moved to the end of the partition","Ele é gravado e movido para o fim da partição",False,"A log appends at the end anyway; nothing is moved.","Um log anexa no fim de qualquer jeito; nada é movido."),
])
N(S5,"easy",("By default, how many minutes ahead of the broker's clock may a record's timestamp be before a `CreateTime` topic refuses it?","Por padrão, quantos minutos à frente do relógio do broker o timestamp de um registro pode estar antes de um tópico `CreateTime` recusá-lo?"),60,0,("minutes","minutos"))
Q(S5,"hard",("One till's clock is an hour fast. Why is that worse for an event-time pipeline than a till an hour slow?","O relógio de um caixa está uma hora adiantado. Por que isso é pior para um pipeline por tempo do evento do que um caixa uma hora atrasado?"),[
 ("A fast clock's sales are refused by the broker and lost","As vendas de um relógio adiantado são recusadas pelo broker e perdidas",False,"An hour is inside the broker's tolerance, so they are stored.","Uma hora está dentro da tolerância do broker, então elas são gravadas."),
 ("A slow clock is corrected by NTP and a fast one is not, since NTP only moves clocks forward","Um relógio atrasado é corrigido pelo NTP e um adiantado não, já que o NTP só move relógios para a frente",False,"NTP corrects either direction.","O NTP corrige nas duas direções."),
 ("Its sales push the latest time seen forward, so honest sales look late","As vendas dele empurram o tempo mais recente visto, e as honestas parecem atrasadas",True,"Right. One fast source moves everybody's sense of time; a slow one only makes its own sales late.","Isso. Uma fonte adiantada move a noção de tempo de todos; uma atrasada só atrasa as próprias vendas."),
 ("Fast clocks make the sales arrive sooner","Relógios adiantados fazem as vendas chegarem antes",False,"The clock changes the stamp, not the network.","O relógio muda o carimbo, não a rede."),
])
Q(S5,"medium",("A sale's `at` is 15:20 and the broker appended it at 15:02. What can a pipeline conclude?","O `at` de uma venda é 15:20 e o broker a anexou às 15:02. O que um pipeline pode concluir?"),[
 ("The sale is late by eighteen minutes","A venda está dezoito minutos atrasada",False,"Late means arriving after it happened; this arrived before.","Atrasada é chegar depois de acontecer; esta chegou antes."),
 ("The till's clock is wrong, since nothing arrives before it happens","O relógio do caixa está errado, já que nada chega antes de acontecer",True,"Right. Keeping both clocks is what makes this visible.","Isso. Guardar os dois relógios é o que torna isso visível."),
 ("The broker's clock is wrong, since the till is closer to the sale","O relógio do broker está errado, já que o caixa está mais perto da venda",False,"Either could be wrong, but the broker's is the one you run and sync.","Qualquer um poderia estar errado, mas o do broker é o que você administra e sincroniza."),
 ("Kafka will refuse the record, because its event time is later than its arrival","O Kafka vai recusar o registro, porque o tempo do evento dele é posterior à chegada",False,"Kafka never reads `at`; and eighteen minutes is inside its tolerance anyway.","O Kafka nunca lê o `at`; e dezoito minutos estão dentro da tolerância de qualquer jeito."),
])
M(S6,"medium",("Match each question to the clock it should be answered with.","Ligue cada pergunta ao relógio com que ela deve ser respondida."),[
 ("Sales per hour for the manager","Vendas por hora para o gerente","event time","tempo do evento"),
 ("Sales the pipeline handles per second","Vendas que o pipeline trata por segundo","processing time","tempo de processamento"),
 ("How far behind the consumer is","Quão atrasado está o consumidor","both, subtracted","os dois, subtraídos"),
 ("A card used in two cities ten minutes apart","Um cartão usado em duas cidades com dez minutos de diferença","event time, between two purchases","tempo do evento, entre duas compras"),
],[("ingestion time, because it never changes","tempo de ingestão, porque nunca muda")])
Q(S6,"medium",("When is `LogAppendTime` a reasonable stand-in for event time?","Quando `LogAppendTime` é um substituto razoável para o tempo do evento?"),[
 ("When the sources have no clock worth trusting","Quando as origens não têm relógio em que dê para confiar",True,"Right. It is stamped by a clock you run, and in a well-behaved stream close to the event.","Isso. Ele é carimbado por um relógio que você administra e, num stream bem-comportado, fica perto do evento."),
 ("When some sources go offline for hours","Quando algumas origens ficam horas sem conexão",False,"Then it is hours wrong: Natal's sales were appended at 14:00.","Aí ele fica horas errado: as vendas de Natal foram anexadas às 14:00."),
 ("When results must be the same in every replay and match event time exactly","Quando os resultados precisam ser iguais em toda releitura e bater exatamente com o tempo do evento",False,"It is the same in every replay, but it never matches event time exactly.","Ele é igual em toda releitura, mas nunca bate exatamente com o tempo do evento."),
 ("Never: it is processing time under another name","Nunca: é tempo de processamento com outro nome",False,"Processing time changes with every read; ingestion time is fixed once appended.","O tempo de processamento muda a cada leitura; o de ingestão fica fixo depois de anexado."),
])
MC(S6,"hard",("Which of these are costs of counting by event time rather than processing time? Choose all that apply.","Quais destes são custos de contar pelo tempo do evento em vez do tempo de processamento? Escolha todos que se aplicam."),[
 ("Results are not final at the end of their period","Os resultados não estão finais no fim do período",True,"Yes: they wait until the processor decides nothing more will come.","Sim: eles esperam até o processador decidir que nada mais virá."),
 ("Open counts are kept as state, per key","Contagens abertas ficam guardadas como estado, por chave",True,"Yes: an open hour's running count has to live somewhere.","Sim: a contagem parcial de uma hora aberta precisa ficar em algum lugar."),
 ("Each event needs a trustworthy time inside it","Cada evento precisa de um horário confiável dentro dele",True,"Yes: a lying device clock becomes a wrong result.","Sim: um relógio de aparelho mentiroso vira um resultado errado."),
 ("Kafka refuses records whose event time is old","O Kafka recusa registros cujo tempo do evento é antigo",False,"Kafka never reads the event time inside the value, and before.max allows any age by default.","O Kafka nunca lê o tempo do evento dentro do valor, e o before.max aceita qualquer idade por padrão."),
 ("Replays give different answers","Releituras dão respostas diferentes",False,"That is processing time's flaw; event time gives the same answer every replay.","Esse é o defeito do tempo de processamento; o tempo do evento dá a mesma resposta em toda releitura."),
])
Q(S7,"medium",("`kafka-get-offsets.sh --time` for 13:00 on `late` returns an offset. What does replaying from it give you?","`kafka-get-offsets.sh --time` para as 13:00 em `late` devolve um offset. O que reler a partir dele entrega?"),[
 ("Every sale that happened after 13:00, and nothing earlier","Toda venda que aconteceu depois das 13:00, e nada anterior",False,"Natal's morning sales arrived at 14:00, after that offset.","As vendas da manhã de Natal chegaram às 14:00, depois desse offset."),
 ("Exactly the sales of the 13:00 hour","Exatamente as vendas da hora das 13:00",False,"A search finds a starting position, not a set of events, and reading goes on past 14:00.","Uma busca acha uma posição de início, não um conjunto de eventos, e a leitura continua depois das 14:00."),
 ("Only the records whose timestamp is after 13:00, skipping the rest","Só os registros com timestamp depois das 13:00, pulando o resto",False,"A consumer reads every record from the position on; it does not filter by timestamp.","Um consumidor lê todo registro a partir da posição; ele não filtra por timestamp."),
 ("Everything that arrived from 13:00 on","Tudo o que chegou a partir das 13:00",True,"Right. In `late` the stamp is the time of sending, so the search is by arrival.","Isso. Em `late` o carimbo é a hora do envio, então a busca é pela chegada."),
])
Q(S7,"hard",("A topic keeps the default seven-day retention, and a producer stamps each record with the sale's event time. A batch of sales from three weeks ago arrives. What happens to them?","Um tópico mantém a retenção padrão de sete dias, e um produtor carimba cada registro com o tempo do evento da venda. Chega um lote de vendas de três semanas atrás. O que acontece com elas?"),[
 ("They are kept for seven days from now","Elas ficam guardadas por sete dias a partir de agora",False,"Retention is measured with the record's timestamp, not with the time it was written.","A retenção é medida com o timestamp do registro, não com a hora em que foi gravado."),
 ("They are refused by the broker","Elas são recusadas pelo broker",False,"before.max allows any age by default.","O before.max aceita qualquer idade por padrão."),
 ("They are deleted at the next retention check","Elas são apagadas na próxima verificação de retenção",True,"Right, if they are alone in their segment: its newest stamp is already past the limit.","Isso, se estiverem sozinhas no segmento: o carimbo mais novo dele já passou do limite."),
 ("They are moved to the start of the partition","Elas são movidas para o início da partição",False,"A log appends; nothing moves to the start.","Um log anexa; nada é movido para o início."),
])
C(S7,"medium",("Each segment of a partition has a `.log` file and, beside it, a `.___` file that maps timestamps to offsets.","Cada segmento de uma partição tem um arquivo `.log` e, ao lado dele, um arquivo `.___` que mapeia timestamps para offsets."),[(["timeindex"],["timeindex"])])
O(D,"medium",("One of Natal's held sales: put its times in the order they occur.","Uma das vendas retidas de Natal: ponha os horários dela na ordem em que acontecem."),[
 ("The customer pays at the till in Natal","O cliente paga no caixa de Natal"),
 ("The till's line comes back and it sends the sale","A linha do caixa volta e ele envia a venda"),
 ("The broker appends the record to the partition","O broker anexa o registro à partição"),
 ("A consumer keeping up handles it","Um consumidor em dia a trata"),
 ("An analyst replays the topic the next month","Um analista relê o tópico no mês seguinte"),
])
Q(D,"hard",("Ponto Final wants an alert when a shop sells nothing for an hour. Which design avoids the false alarm of 2 March?","A Ponto Final quer um alerta quando uma loja não vender nada por uma hora. Qual desenho evita o alarme falso de 2 de março?"),[
 ("Count by event time and alert as soon as an hour has no sales","Contar pelo tempo do evento e alertar assim que uma hora ficar sem vendas",False,"At 11:20 the event-time hour is just as empty: the sales are still in the till.","Às 11:20 a hora pelo tempo do evento está igualmente vazia: as vendas ainda estão no caixa."),
 ("Count by arrival and raise the threshold to two hours","Contar pela chegada e subir o limite para duas horas",False,"Natal was quiet for three hours and forty minutes; the alarm still fires, later.","Natal ficou quieta por três horas e quarenta minutos; o alarme dispara do mesmo jeito, mais tarde."),
 ("Alert on silence from the till itself, which is a pipeline question, separate from sales per hour","Alertar sobre o silêncio do próprio caixa, uma pergunta sobre o pipeline, separada das vendas por hora",True,"Right. Nothing arrived from Natal, which is true and worth knowing; whether it sold is a different question.","Isso. Nada chegou de Natal, o que é verdade e vale saber; se vendeu é outra pergunta."),
 ("Switch the topic to LogAppendTime","Mudar o tópico para LogAppendTime",False,"Ingestion time also says 14:00 for Natal's sales.","O tempo de ingestão também diz 14:00 para as vendas de Natal."),
])
