S1="when-is-it-complete"; S2="watermarks"; S3="watermark-in-action"; S4="allowed-lateness"; S5="late-data-elsewhere"; S6="choosing-the-bound"; S7="idle-sources"; D="drill"

Q(S1,"medium",("A processor emits each window two minutes after it ends by its own clock. What goes wrong when the topic is replayed the next day?","Um processador emite cada janela dois minutos depois do fim dela pelo próprio relógio. O que dá errado quando o tópico é relido no dia seguinte?"),[
 ("Nothing, as long as the processor's clock is synchronised with NTP","Nada, desde que o relógio do processador esteja sincronizado com NTP",False,"A correct clock still measures the replay's moment, which has nothing to do with the events.","Um relógio certo ainda mede o momento da releitura, que não tem nada a ver com os eventos."),
 ("The windows close at moments unrelated to the events, so results differ","As janelas fecham em momentos sem relação com os eventos, e os resultados mudam",True,"Right. That is processing time, with lesson 9's flaw: the answer depends on when it ran.","Isso. É tempo de processamento, com o defeito da lição 9: a resposta depende de quando rodou."),
 ("Every window is emitted twice, once for the original run and once for the replay","Toda janela é emitida duas vezes, uma na execução original e outra na releitura",False,"A replay starts fresh; the problem is which events each window contains.","Uma releitura começa do zero; o problema é quais eventos cada janela contém."),
 ("The replay is refused by Kafka","A releitura é recusada pelo Kafka",False,"Kafka is glad to be read again; that is what a log is for.","O Kafka aceita ser lido de novo; é para isso que serve um log."),
])
Q(S1,"easy",("What does a processor actually know that lets it estimate how far time has got?","O que um processador de fato sabe que permite estimar até onde o tempo chegou?"),[
 ("The time of the wall clock where it runs","O horário do relógio de parede onde ele roda",False,"That is processing time, which says nothing about the events.","Isso é tempo de processamento, que não diz nada sobre os eventos."),
 ("How many events each partition will send","Quantos eventos cada partição vai mandar",False,"Nothing tells it that in advance.","Nada diz isso a ele de antemão."),
 ("The event times it has already seen","Os tempos de evento que já viu",True,"Right. They move forward, unevenly, and they are the raw material of the watermark.","Isso. Eles andam para a frente, de forma irregular, e são a matéria-prima do watermark."),
 ("A signal each till sends when it has finished a minute","Um sinal que cada caixa manda quando termina um minuto",False,"No till sends one; Natal's did not even say it was holding sales.","Nenhum caixa manda isso; o de Natal nem avisou que estava segurando vendas."),
])
C(S1,"easy",("A processor's assertion \"I do not expect any more events older than this time\" is called a ___.","A afirmação de um processador \"não espero mais nenhum evento mais antigo que este horário\" se chama ___."),[(["watermark"],["watermark","marca d'agua"])])
N(S2,"easy",("The latest event time seen is 09:12:30 and the bound is 2 minutes. How many seconds after 09:10:00 is the watermark?","O tempo de evento mais recente visto é 09:12:30 e o limite é de 2 minutos. Quantos segundos depois das 09:10:00 está o watermark?"),30,0,("seconds","segundos"))
N(S2,"medium",("Bound 3 minutes. Event times arrive in this order: 10:00:00, 10:04:00, 10:02:00, 10:06:30, 10:05:00. How many minutes after 10:00 is the watermark after the last one?","Limite de 3 minutos. Os tempos de evento chegam nesta ordem: 10:00:00, 10:04:00, 10:02:00, 10:06:30, 10:05:00. Quantos minutos depois das 10:00 está o watermark depois do último?"),3.5,0,("minutes","minutos"),hint=("The latest seen is not the last to arrive.","O mais recente visto não é o último a chegar."))
Q(S2,"medium",("A sale from 09:08:50 arrives after one from 09:13:05. Why does the watermark not move back?","Uma venda das 09:08:50 chega depois de uma das 09:13:05. Por que o watermark não volta?"),[
 ("Old sales are discarded before the watermark sees them","Vendas antigas são descartadas antes de o watermark vê-las",False,"Whether it is discarded depends on the watermark; the watermark comes first.","Se ela é descartada depende do watermark; o watermark vem antes."),
 ("It would reopen windows already emitted","Reabriria janelas já emitidas",True,"Right. It is the latest time seen, and that is still 09:13:05.","Isso. É o horário mais recente visto, e ele continua sendo 09:13:05."),
 ("The watermark only uses the first event of each window","O watermark só usa o primeiro evento de cada janela",False,"It uses the latest event time seen, whatever its window.","Ele usa o tempo de evento mais recente visto, seja qual for a janela."),
 ("Kafka sorts the partition before the processor reads it","O Kafka ordena a partição antes de o processador lê-la",False,"A partition is in arrival order; nothing sorts it.","Uma partição está em ordem de chegada; nada a ordena."),
])
Q(S2,"hard",("When is a perfect watermark, one that is never wrong, possible?","Quando é possível um watermark perfeito, que nunca erra?"),[
 ("When the bound is larger than the longest delay any event has ever had","Quando o limite é maior que o maior atraso que algum evento já teve",False,"Any bound can be beaten by a source that holds events longer, as Natal did.","Qualquer limite pode ser vencido por uma origem que segure eventos por mais tempo, como fez Natal."),
 ("When the topic uses LogAppendTime","Quando o tópico usa LogAppendTime",False,"That makes the stamp the broker's, but the event time inside can still be out of order.","Isso torna o carimbo do broker, mas o tempo do evento dentro ainda pode vir fora de ordem."),
 ("When the processor runs on the same machine as the broker","Quando o processador roda na mesma máquina que o broker",False,"Where it runs says nothing about the order of the events.","Onde ele roda não diz nada sobre a ordem dos eventos."),
 ("When a source writes its events in order, with no buffering","Quando uma origem escreve os eventos em ordem, sem guardar nada",True,"Right. Then it knows how far it has got; real systems almost never are like that.","Isso. Aí ela sabe até onde chegou; sistemas reais quase nunca são assim."),
])
N(S3,"medium",("In `watermark.py` with a 2-minute bound, after which sale number are the windows 09:00 and 09:05 emitted?","No `watermark.py` com limite de 2 minutos, depois de qual número de venda as janelas das 09:00 e das 09:05 são emitidas?"),6,0,("sale","venda"))
Q(S3,"medium",("With no lateness, sale 8 (09:08:50) is dropped. The watermark when it arrived was 09:11:05. Why is it too late?","Sem atraso permitido, a venda 8 (09:08:50) é descartada. O watermark quando ela chegou era 09:11:05. Por que ela está atrasada demais?"),[
 ("It happened more than two minutes before the latest sale","Ela aconteceu mais de dois minutos antes da venda mais recente que o processador viu",False,"That alone would not drop it; what matters is whether its window has been passed.","Isso sozinho não a descartaria; o que importa é se a janela dela já foi passada."),
 ("Its window ended at 09:10, and the watermark had passed that","A janela dela terminou às 09:10, e o watermark já tinha passado disso",True,"Right. The window was emitted and, with no lateness, forgotten.","Isso. A janela foi emitida e, sem atraso permitido, esquecida."),
 ("Natal's sales go to the late topic, whatever the watermark says","As vendas de Natal vão para o tópico de atrasadas, diga o watermark o que disser",False,"Natal's sales 2 and 5 were counted normally.","As vendas 2 e 5 de Natal foram contadas normalmente."),
 ("The watermark moved back when it arrived","O watermark voltou quando ela chegou",False,"It never moves back.","Ele nunca volta."),
])
N(S3,"hard",("With a 2-minute bound and no lateness, how many cents does the program report for the window 09:05 to 09:10?","Com limite de 2 minutos e sem atraso permitido, quantos centavos o programa informa para a janela das 09:05 às 09:10?"),12390,0,("cents","centavos"),hint=("Sales 4 and 5; sale 8 is dropped.","Vendas 4 e 5; a venda 8 é descartada."))
Q(S3,"easy",("Why does sale 6 make the program emit two windows at once?","Por que a venda 6 faz o programa emitir duas janelas de uma vez?"),[
 ("It belongs to both windows","Ela pertence às duas janelas",False,"Tumbling windows do not overlap; sale 6 is in 09:10 to 09:15.","Janelas tumbling não se sobrepõem; a venda 6 está em 09:10 às 09:15."),
 ("The program emits windows in pairs, the earlier of the two first","O programa emite janelas em pares, a mais antiga das duas primeiro",False,"Sale 10 emits one.","A venda 10 emite uma."),
 ("It moves the watermark six minutes, past two windows' ends","Ela leva o watermark seis minutos à frente, além do fim de duas janelas",True,"Right. From 09:04:20 to 09:10:30.","Isso. De 09:04:20 para 09:10:30."),
 ("It is the first sale of a new hour, so every open window is closed","É a primeira venda de uma hora nova, então toda janela aberta é fechada",False,"It is from 09:12; the hour has nothing to do with it.","Ela é das 09:12; a hora não tem nada a ver."),
])
Q(S4,"medium",("With 5 minutes of lateness, sale 8 updates the 09:05 window. Sale 11 (09:04:30) is still dropped. Why?","Com 5 minutos de atraso permitido, a venda 8 atualiza a janela das 09:05. A venda 11 (09:04:30) continua descartada. Por quê?"),[
 ("Its window ended at 09:05, so it was forgotten when the watermark passed 09:10","A janela dela terminou às 09:05, então foi esquecida quando o watermark passou de 09:10",True,"Right. When it arrived the watermark was 09:19:00.","Isso. Quando ela chegou o watermark estava em 09:19:00."),
 ("Lateness applies only to the window being emitted at that moment","O atraso permitido só vale para a janela sendo emitida naquele momento",False,"It applies to every window, counted from each one's end.","Vale para toda janela, contado do fim de cada uma."),
 ("A window can be updated only once","Uma janela só pode ser atualizada uma vez",False,"There is no such limit; any number of late sales may update a kept window.","Não existe esse limite; quantas vendas atrasadas forem podem atualizar uma janela guardada."),
 ("Natal's sales are excluded from late updates","As vendas de Natal ficam fora das atualizações atrasadas",False,"Sale 8 is also Natal's, and it was counted.","A venda 8 também é de Natal, e foi contada."),
])
Q(S4,"hard",("Late updates go to a reader that appends each result as a new row and sums the column. What happens to the 09:05 window?","Atualizações atrasadas vão para um leitor que anexa cada resultado como linha nova e soma a coluna. O que acontece com a janela das 09:05?"),[
 ("Nothing, because the second result replaces the first","Nada, porque o segundo resultado substitui o primeiro",False,"Replacing is what an upsert does; an append keeps both.","Substituir é o que um upsert faz; um anexo guarda os dois."),
 ("Sales 4 and 5 are counted twice","As vendas 4 e 5 são contadas duas vezes",True,"Right. There are two rows for one window, and the sum adds both.","Isso. Há duas linhas para uma janela, e a soma junta as duas."),
 ("Sale 8 is lost","A venda 8 se perde",False,"It is in the second row; the trouble is the first row is still there too.","Ela está na segunda linha; o problema é que a primeira também continua lá."),
 ("The processor refuses to emit an update to an appending reader","O processador se recusa a emitir uma atualização para um leitor que anexa",False,"The processor does not know how its output is read.","O processador não sabe como a saída dele é lida."),
])
N(S4,"medium",("Five-minute tumbling windows and 30 minutes of allowed lateness. How many extra windows per key are kept open at any moment because of the lateness?","Janelas tumbling de cinco minutos e 30 minutos de atraso permitido. Quantas janelas a mais por chave ficam abertas a cada momento por causa do atraso permitido?"),6,0,("windows","janelas"))
M(S4,"hard",("Match each engine's setting to what it decides.","Ligue cada configuração de motor ao que ela decide."),[
 ("Flink's bounded out-of-orderness","A desordem limitada do Flink","when a window is first emitted","quando uma janela é emitida pela primeira vez"),
 ("Flink's allowedLateness","O allowedLateness do Flink","how long an emitted window is kept for updates","por quanto tempo uma janela emitida é guardada para atualizações"),
 ("Kafka Streams' grace period","O grace period do Kafka Streams","both: the window accepts records until stream time passes end plus grace","os dois: a janela aceita registros até o stream time passar do fim mais o grace"),
 ("Flink's sideOutputLateData","O sideOutputLateData do Flink","where events too late for any window go","para onde vão os eventos atrasados demais para qualquer janela"),
],[("how many partitions a topic has","quantas partições um tópico tem")])
Q(S5,"medium",("What does sending late sales to their own topic give you that dropping them does not?","O que mandar vendas atrasadas para um tópico próprio dá que descartá-las não dá?"),[
 ("They are counted in the window after all","Elas acabam contadas na janela",False,"The window is gone; the topic is a record, not a way back in.","A janela não existe mais; o tópico é um registro, não um jeito de voltar."),
 ("The processor runs faster","O processador roda mais rápido, sem ter de descartar nada",False,"Producing a record costs about the same as dropping it.","Produzir um registro custa quase o mesmo que descartá-lo."),
 ("The watermark moves back to include them","O watermark volta para incluí-las",False,"It never moves back.","Ele nunca volta."),
 ("A trail of them, to count and inspect","Um rastro delas, para contar e inspecionar",True,"Right. Late data stops being invisible.","Isso. O dado atrasado deixa de ser invisível."),
])
Q(S5,"hard",("The number of late events per hour on the late topic jumps a hundredfold one afternoon. What is the most likely reading?","O número de eventos atrasados por hora no tópico de atrasadas salta cem vezes numa tarde. Qual é a leitura mais provável?"),[
 ("The bound is too large and should be shortened","O limite está grande demais e deveria diminuir",False,"A bound too large produces fewer late events, not more.","Um limite grande demais produz menos eventos atrasados, não mais."),
 ("Kafka lost the watermark","O Kafka perdeu o watermark",False,"Kafka does not hold the watermark; the processor computes it.","O Kafka não guarda o watermark; o processador o calcula."),
 ("A till, a network or a clock went wrong","Um caixa, uma rede ou um relógio deu errado",True,"Right. A bound that fits produces a steady trickle; a jump is a change in the stream.","Isso. Um limite que combina produz um fio constante; um salto é uma mudança no stream."),
 ("Sales doubled that afternoon","As vendas dobraram naquela tarde",False,"Twice the sales would give twice the late events, not a hundred times.","O dobro de vendas daria o dobro de atrasadas, não cem vezes."),
])
N(S6,"medium",("In the measured day, 292 of 360 sales had a distance of 0, 311 were within 60 seconds and 322 within 120. How many sales does raising the bound from 1 minute to 2 minutes save from being late?","No dia medido, 292 de 360 vendas tinham distância 0, 311 estavam a até 60 segundos e 322 a até 120. Quantas vendas subir o limite de 1 para 2 minutos salva de chegar atrasada?"),11,0,("sales","vendas"))
Q(S6,"hard",("p85 of the distance is 40 seconds and p90 is 1,847 seconds. What does the jump say about choosing the bound?","O p85 da distância é 40 segundos e o p90 é 1.847 segundos. O que o salto diz sobre escolher o limite?"),[
 ("Use the p90, half an hour, since 90% is the usual target","Usar o p90, meia hora, já que 90% é a meta usual",False,"That makes every result wait half an hour to catch a few of Natal's held sales.","Isso faz todo resultado esperar meia hora para pegar algumas vendas retidas de Natal."),
 ("Use the average distance","Usar a distância média",False,"The average mixes the two populations and fits neither.","A média mistura as duas populações e não serve a nenhuma."),
 ("Pick a bound just past the first group; the gap means the second needs other tools","Um limite logo depois do primeiro grupo; o vão mostra que o segundo pede outras ferramentas",True,"Right. Lateness, a late topic and the nightly batch handle the hours-late group.","Isso. Atraso permitido, tópico de atrasadas e batch noturno cuidam do grupo de horas."),
 ("Use no bound at all, since most sales arrive in order","Não usar limite nenhum, já que a maioria das vendas chega em ordem",False,"With no bound, every slow delivery of seconds becomes late.","Sem limite, toda entrega lenta de segundos vira atrasada."),
])
Q(S6,"medium",("With a 6-minute bound instead of 2, what did the twelve sales gain and lose?","Com limite de 6 minutos em vez de 2, o que as doze vendas ganharam e perderam?"),[
 ("Gained nothing, lost latency","Não ganharam nada, perderam latência",False,"Sale 8 was counted, which it was not with 2 minutes.","A venda 8 foi contada, o que não aconteceu com 2 minutos."),
 ("Sale 8 counted; the 09:05 window emitted four sales later","Venda 8 contada; janela das 09:05 emitida quatro vendas depois",True,"Right. Completeness bought with latency.","Isso. Completude comprada com latência."),
 ("Both late sales were counted, and the windows were emitted at the same moments","As duas vendas atrasadas foram contadas, e as janelas foram emitidas nos mesmos momentos",False,"Sale 11 was still dropped, and the windows waited longer.","A venda 11 continuou descartada, e as janelas esperaram mais."),
 ("Lost sale 8, gained speed","Perderam a venda 8, ganharam velocidade",False,"It is the other way round: a larger bound waits longer and loses less.","É o contrário: um limite maior espera mais e perde menos."),
])
Q(S7,"medium",("Why does a processor take the LOWEST of its partitions' watermarks?","Por que um processador usa o MENOR dos watermarks das partições?"),[
 ("A lagging partition still has earlier events to deliver","Uma partição atrasada ainda tem eventos anteriores a entregar",True,"Right. There is no order between partitions, so time has only got as far as the slowest.","Isso. Não há ordem entre partições, então o tempo só chegou até onde a mais lenta chegou."),
 ("The lowest is cheaper to compute","O menor é mais barato de calcular",False,"Any of them is one comparison; the reason is correctness.","Qualquer um é uma comparação; o motivo é correção."),
 ("Kafka requires it","O Kafka exige isso",False,"Kafka has no watermark; the processor chooses the rule.","O Kafka não tem watermark; o processador escolhe a regra."),
 ("To emit results as early as possible","Para emitir resultados o mais cedo possível",False,"The lowest is the latest to emit, not the earliest.","O menor é o que emite mais tarde, não mais cedo."),
])
N(S7,"easy",("Three partitions have latest event times 09:21:00, 09:12:30 and 09:17:45. With a 2-minute bound, how many minutes after 09:00 is the watermark?","Três partições têm tempos de evento mais recentes 09:21:00, 09:12:30 e 09:17:45. Com limite de 2 minutos, quantos minutos depois das 09:00 está o watermark?"),10.5,0,("minutes","minutos"))
Q(S7,"hard",("A topic has 12 partitions and Ponto Final's five shops as keys. A Flink job with no idleness setting reads it and never emits a window. What is the likeliest cause?","Um tópico tem 12 partições e as cinco lojas da Ponto Final como chaves. Um job Flink sem configuração de ociosidade o lê e nunca emite uma janela. Qual a causa mais provável?"),[
 ("The bound is too small for the shops, so every sale is dropped as late","O limite é pequeno demais para as lojas, então toda venda é descartada como atrasada",False,"A small bound emits early and drops more; it does not stop emission.","Um limite pequeno emite cedo e descarta mais; não impede a emissão."),
 ("Partitions with no key hold the minimum watermark at nothing","Partições sem chave seguram o watermark mínimo em nada",True,"Right. Five keys reach at most five of twelve partitions; the rest are empty.","Isso. Cinco chaves chegam a no máximo cinco das doze partições; o resto fica vazio."),
 ("Twelve partitions are too many for Flink to track one watermark each","Doze partições são demais para o Flink acompanhar um watermark em cada",False,"Flink reads thousands; the trouble is that some are empty.","O Flink lê milhares; o problema é que algumas estão vazias."),
 ("The shops' clocks are wrong","Os relógios das lojas estão errados",False,"Wrong clocks give wrong windows, not none at all.","Relógios errados dão janelas erradas, não nenhuma."),
])
O(D,"medium",("Put what happens to the 09:05 to 09:10 window (bound 2 minutes, lateness 5) in order.","Ponha em ordem o que acontece com a janela das 09:05 às 09:10 (limite de 2 minutos, atraso permitido de 5)."),[
 ("Sales 4 and 5 are counted in it","As vendas 4 e 5 são contadas nela"),
 ("Sale 6 moves the watermark past 09:10, and it is emitted with two sales","A venda 6 leva o watermark além das 09:10, e ela é emitida com duas vendas"),
 ("Sale 8 arrives late and updates it to three sales","A venda 8 chega atrasada e a atualiza para três vendas"),
 ("Sale 10 moves the watermark past 09:15, and it is forgotten","A venda 10 leva o watermark além das 09:15, e ela é esquecida"),
])
Q(D,"hard",("Ponto Final wants sales per five minutes on a dashboard that upserts, plus exact daily totals for accounting. Which design fits the lesson?","A Ponto Final quer vendas a cada cinco minutos num painel que faz upsert, mais totais diários exatos para a contabilidade. Qual desenho combina com a lição?"),[
 ("A bound of four hours, so that every number on the dashboard is exact and no batch is needed","Um limite de quatro horas, para os números do painel ficarem exatos sem precisar do batch",False,"Every window would wait four hours; that is the batch, without its completeness.","Toda janela esperaria quatro horas; isso é o batch, sem a completude dele."),
 ("No watermark, and the dashboard reads the topic by arrival time","Sem watermark, e o painel lê o tópico pelo tempo de chegada",False,"That is lesson 9's wrong column.","Essa é a coluna errada da lição 9."),
 ("A short bound with lateness, late sales to a topic, and the nightly batch for the totals","Limite curto com atraso permitido, atrasadas num tópico e o batch noturno para os totais",True,"Right. Fast and nearly right on the dashboard, exact the next morning in the books.","Isso. Rápido e quase certo no painel, exato na manhã seguinte nos livros."),
 ("Emit each window once and drop late sales silently","Emitir cada janela uma vez e descartar as atrasadas em silêncio",False,"Silent drops make the accounting wrong with no trail.","Descartes silenciosos deixam a contabilidade errada sem rastro."),
])
