# Lesson 1: supervised, unsupervised and reinforcement learning.
# python3 lab/tools/exb.py lab/exercises/l01.py lessons/le-xpaf8cg8

Q("ex-rwkh2qnd", "what-learning-is", "easy",
  "What does a learning algorithm produce when it reads Ponto Final's members and their outcomes?",
  "O que um algoritmo de aprendizado produz quando lê os membros da Ponto Final e os seus desfechos?",
  [("A model: a set of fitted weights",
    "Um modelo: um conjunto de pesos ajustados", True,
    "Right. The program that reads the examples is ordinary; what it fills in is the model.",
    "Isso. O programa que lê os exemplos é comum; o que ele preenche é o modelo."),
   ("A rule like recency_days > 120, written out as SQL",
    "Uma regra como recency_days > 120, escrita em SQL", False,
    "That is the rule a person writes. A learned model is weights nobody wrote.",
    "Essa é a regra que uma pessoa escreve. Um modelo aprendido são pesos que ninguém escreveu."),
   ("A copy of the members table with a lapsed column filled in",
    "Uma cópia da tabela de membros com a coluna lapsed preenchida", False,
    "The label is computed before training; the model is what training produces from it.",
    "O rótulo é calculado antes do treino; o modelo é o que o treino produz a partir dele."),
   ("A new learning algorithm, tuned to this shop",
    "Um novo algoritmo de aprendizado, ajustado a esta loja", False,
    "The algorithm stays the library's. What changes is the weights it fits.",
    "O algoritmo continua sendo o da biblioteca. O que muda são os pesos que ele ajusta.")])

P("ex-6a4e5e2d", "what-learning-is", "easy",
  "Match each word to what it means in this course.",
  "Associe cada palavra ao que ela significa neste curso.",
  [("feature", "one of the numbers describing an example", "um dos números que descrevem um exemplo"),
   ("label", "the answer written beside an example", "a resposta escrita ao lado de um exemplo"),
   ("training", "fitting the model to the examples", "ajustar o modelo aos exemplos"),
   ("inference", "the model answering for an unseen example", "o modelo respondendo sobre um exemplo não visto")],
  [("the library that holds the algorithms", "a biblioteca que guarda os algoritmos")])

Q("ex-spqv4hr6", "what-learning-is", "medium",
  "In this course's view, which of these is the data engineer's job rather than the modeller's?",
  "Na visão deste curso, qual destas é tarefa do engenheiro de dados e não de quem modela?",
  [("Choosing between logistic regression and gradient boosting",
    "Escolher entre regressão logística e gradient boosting", False,
    "That is the modeller's choice of algorithm.",
    "Essa é a escolha de algoritmo de quem modela."),
   ("Attaching the label without leaking the future into the features",
    "Anexar o rótulo sem vazar o futuro para os atributos", True,
    "Right. Which rows become examples, and how features and labels are computed, is the platform's.",
    "Isso. Quais linhas viram exemplos, e como atributos e rótulos são calculados, é da plataforma."),
   ("Deciding whether 0.79 is a good enough score to ship",
    "Decidir se 0,79 é uma nota boa o bastante para publicar", False,
    "Judging the result is the modeller's half of the work.",
    "Julgar o resultado é a metade do trabalho de quem modela."),
   ("Writing a new learning algorithm in Python",
    "Escrever um novo algoritmo de aprendizado em Python", False,
    "Nobody here writes one; they come from scikit-learn, as a database engine comes from PostgreSQL.",
    "Ninguém aqui escreve um; eles vêm do scikit-learn, como um motor de banco vem do PostgreSQL.")])

Q("ex-eqvhy6cb", "your-machine", "easy",
  "Why does the course recommend installing the lab on your own computer?",
  "Por que o curso recomenda instalar o laboratório no seu próprio computador?",
  [("It is light, and deleting two directories removes it",
    "Ele é leve, e apagar dois diretórios o remove", True,
    "Right. ~/mlenv and ~/ml hold everything, and no service or graphics card is needed.",
    "Isso. ~/mlenv e ~/ml guardam tudo, e não é preciso serviço nem placa de vídeo."),
   ("The models need a graphics card that a virtual machine cannot see",
    "Os modelos precisam de uma placa de vídeo que uma máquina virtual não enxerga", False,
    "Every model in the course trains on a processor in seconds.",
    "Todo modelo do curso treina num processador em segundos."),
   ("Online providers cannot run Python 3.12",
    "Provedores online não rodam Python 3.12", False,
    "The online path works for the whole course; the difference is port forwarding.",
    "O caminho online funciona para o curso inteiro; a diferença é o encaminhamento de portas."),
   ("MLflow refuses to start inside a virtual machine",
    "O MLflow se recusa a iniciar dentro de uma máquina virtual", False,
    "The VM path runs the same steps, exactly as written.",
    "O caminho da VM roda os mesmos passos, exatamente como estão escritos.")])

Q("ex-kbpkbhq6", "your-machine", "medium",
  "On the online path, what is different about lessons 7 and 8?",
  "No caminho online, o que muda nas lições 7 e 8?",
  [("They cannot be done, because the programs need 127.0.0.1",
    "Elas não podem ser feitas, porque os programas precisam de 127.0.0.1", False,
    "They can; the provider forwards the port to a link of its own.",
    "Podem; o provedor encaminha a porta para um link próprio."),
   ("Their pages open through the provider's link",
    "As páginas delas abrem pelo link do provedor", True,
    "Right. On your own computer the address is 127.0.0.1; elsewhere the provider gives you one.",
    "Isso. No seu computador o endereço é 127.0.0.1; em outro lugar o provedor lhe dá um."),
   ("They need a paid plan, because the free allowance stops servers",
    "Elas exigem um plano pago, porque a cota gratuita derruba servidores", False,
    "No lesson depends on a provider's allowance either way.",
    "Nenhuma lição depende da cota de um provedor, para um lado ou para o outro."),
   ("They run DVC instead of MLflow",
    "Elas rodam DVC em vez de MLflow", False,
    "Both paths run the same programs.",
    "Os dois caminhos rodam os mesmos programas.")])

O("ex-ge6jg0be", "installing", "easy",
  "Put the first-time setup in the order the lesson runs it.",
  "Coloque a primeira instalação na ordem em que a lição a executa.",
  [("sudo apt install -y python3-venv git sqlite3", "sudo apt install -y python3-venv git sqlite3"),
   ("python3 -m venv ~/mlenv", "python3 -m venv ~/mlenv"),
   ("source ~/mlenv/bin/activate", "source ~/mlenv/bin/activate"),
   ("pip install numpy==2.5.3 pandas==3.0.6 …", "pip install numpy==2.5.3 pandas==3.0.6 …")])

Q("ex-db94v7h1", "installing", "medium",
  "Why does the course pin every library to an exact version?",
  "Por que o curso fixa cada biblioteca numa versão exata?",
  [("Newer versions are slower to install over a proxy",
    "Versões novas demoram mais para instalar por um proxy", False,
    "Speed has nothing to do with it.",
    "A velocidade não tem nada a ver com isso."),
   ("pip refuses to install a library without a version number",
    "O pip se recusa a instalar uma biblioteca sem número de versão", False,
    "pip installs the newest version when none is given.",
    "O pip instala a versão mais nova quando nenhuma é dada."),
   ("Another version prints other numbers, or fails",
    "Outra versão imprime outros números, ou falha", True,
    "Right. A lesson's numbers are readings of one version.",
    "Isso. Os números de uma lição são leituras de uma versão."),
   ("Ubuntu marks unpinned packages as externally managed",
    "O Ubuntu marca pacotes sem versão como gerenciados externamente", False,
    "That error is about installing outside an environment, pinned or not.",
    "Esse erro é sobre instalar fora de um ambiente, com versão fixada ou não.")])

C("ex-va3rw39x", "installing", "easy",
  "Every new terminal starts with source ~/mlenv/bin/___ before running the course's programs.",
  "Todo terminal novo começa com source ~/mlenv/bin/___ antes de rodar os programas do curso.",
  ["activate"], ["activate"])

N("ex-89dpcd6n", "the-shop", "easy",
  "How many members does generate.py write with no argument, on 28 February 2026?",
  "Quantos membros o generate.py grava sem argumento, em 28 de fevereiro de 2026?",
  4558, 0, "members", "membros")

Q("ex-8k4f7906", "the-shop", "medium",
  "Where in shop.db is it recorded that a member has left the card?",
  "Onde, no shop.db, fica registrado que um membro deixou o cartão?",
  [("In members.channel, which turns to 'gone'",
    "Em members.channel, que vira 'gone'", False,
    "channel is how they signed up, and it never changes.",
    "channel é como ele se cadastrou, e nunca muda."),
   ("Nowhere: leaving is computed from visits after a chosen day",
    "Em lugar nenhum: a saída é calculada a partir das visitas depois de um dia escolhido", True,
    "Right. The shop only sees visits, so every label in the course is computed.",
    "Isso. A loja só vê visitas, então todo rótulo do curso é calculado."),
   ("In a row of purchases with no lines",
    "Numa linha de purchases sem nenhuma linha em lines", False,
    "Every purchase has at least one book.",
    "Toda compra tem pelo menos um livro."),
   ("In a leaves column the generator writes",
    "Numa coluna leaves que o gerador grava", False,
    "The generator draws that date and never writes it: no column records it.",
    "O gerador sorteia essa data e nunca a grava: nenhuma coluna a registra.")])

Q("ex-1w2h8jkf", "the-shop", "medium",
  "In lesson 10 you run generate.py --until 2026-06-30. What happens to the purchases up to February?",
  "Na lição 10 você roda generate.py --until 2026-06-30. O que acontece com as compras até fevereiro?",
  [("Identical, with four months added",
    "Idênticas, com quatro meses a mais", True,
    "Right. The whole two years are always drawn from one seed; --until only decides what is written.",
    "Isso. Os dois anos inteiros são sempre sorteados com uma semente; --until só decide o que é gravado."),
   ("They are drawn again and differ slightly, because the seed moves",
    "Elas são sorteadas de novo e mudam um pouco, porque a semente se move", False,
    "The seed is fixed at 2026 and the draw does not depend on the date.",
    "A semente é fixa em 2026 e o sorteio não depende da data."),
   ("They are kept, and the new months are appended without rewriting the tables",
    "Elas são mantidas, e os meses novos são anexados sem reescrever as tabelas", False,
    "The tables are dropped and rewritten every run; the rows just come out the same.",
    "As tabelas são apagadas e reescritas a cada rodada; as linhas só saem iguais."),
   ("They are deleted, because only the new months are written",
    "Elas são apagadas, porque só os meses novos são gravados", False,
    "Everything up to --until is written.",
    "Tudo até --until é gravado.")])

Q("ex-tmn422kd", "when-setup-fails", "easy",
  "pip prints error: externally-managed-environment. What does it mean?",
  "O pip imprime error: externally-managed-environment. O que isso quer dizer?",
  [("The environment is not active in this terminal",
    "O ambiente não está ativo neste terminal", True,
    "Right. pip is trying to write into the system's Python. Activate ~/mlenv and run it again.",
    "Isso. O pip está tentando escrever no Python do sistema. Ative o ~/mlenv e rode de novo."),
   ("You must pass --break-system-packages",
    "Você precisa passar --break-system-packages", False,
    "That would write into the system's own Python, which is what Ubuntu is protecting.",
    "Isso escreveria no Python do próprio sistema, que é o que o Ubuntu está protegendo."),
   ("python3-venv is missing, and apt has to install it first",
    "Falta o python3-venv, e o apt precisa instalá-lo primeiro", False,
    "That one is ensurepip is not available, when the environment is made.",
    "Esse é o ensurepip is not available, na criação do ambiente."),
   ("The package index cannot be reached from your network",
    "O índice de pacotes não pode ser alcançado da sua rede", False,
    "A network failure mentions a timeout, a certificate or a proxy.",
    "Uma falha de rede menciona um tempo esgotado, um certificado ou um proxy.")])

Q("ex-5ym0mxr6", "when-setup-fails", "hard",
  "python ml/supervised.py, run from your home directory, fails with no such table: members. What else did it do?",
  "python ml/supervised.py, rodado da sua pasta pessoal, falha com no such table: members. O que mais ele fez?",
  [("Nothing: SQLite refused to open a file that does not exist",
    "Nada: o SQLite se recusou a abrir um arquivo que não existe", False,
    "SQLite does not refuse; that is the trap.",
    "O SQLite não se recusa; essa é a armadilha."),
   ("It created an empty shop.db in your home directory",
    "Criou um shop.db vazio na sua pasta pessoal", True,
    "Right. Asked to open a missing file, SQLite creates it, zero bytes, and the query then fails.",
    "Isso. Pedido para abrir um arquivo que falta, o SQLite o cria, com zero bytes, e a consulta falha."),
   ("It emptied the members table of ~/ml/shop.db",
    "Esvaziou a tabela members de ~/ml/shop.db", False,
    "It never opened ~/ml/shop.db: the relative name pointed at the home directory.",
    "Ele nunca abriu ~/ml/shop.db: o nome relativo apontou para a pasta pessoal."),
   ("It ran generate.py to rebuild the database",
    "Rodou o generate.py para reconstruir o banco", False,
    "Nothing in features.py runs the generator.",
    "Nada em features.py roda o gerador.")])

Q("ex-xsf47vyp", "supervised", "easy",
  "What makes the learning in supervised.py supervised?",
  "O que faz o aprendizado em supervised.py ser supervisionado?",
  [("A person checks the predictions before they are used",
    "Uma pessoa confere as predições antes de serem usadas", False,
    "The supervisor is the past, not a person.",
    "O supervisor é o passado, não uma pessoa."),
   ("Every example arrives with the outcome that followed it",
    "Cada exemplo chega com o desfecho que veio depois dele", True,
    "Right. lapsed is known for every member as of 30 September.",
    "Isso. lapsed é conhecido para todo membro em 30 de setembro."),
   ("The algorithm is told in advance how many groups it must find",
    "O algoritmo é informado de antemão de quantos grupos deve encontrar", False,
    "That is k in k-means, which is unsupervised.",
    "Esse é o k do k-means, que é não supervisionado."),
   ("It is rewarded each time it predicts right",
    "Ele é recompensado cada vez que acerta", False,
    "Reward after acting is reinforcement learning.",
    "Recompensa depois de agir é aprendizado por reforço.")])

Q("ex-81v06ev5", "supervised", "medium",
  "supervised.py trains on the cutoff 2025-09-30. Why not on 2026-02-01?",
  "O supervised.py treina com o corte 2025-09-30. Por que não com 2026-02-01?",
  [("Fewer members were active on 1 February",
    "Havia menos membros ativos em 1º de fevereiro", False,
    "The active population grows over time; size is not the problem.",
    "A população ativa cresce com o tempo; tamanho não é o problema."),
   ("The model would learn from the app, which did not exist in September",
    "O modelo aprenderia com o aplicativo, que ainda não existia em setembro de 2025", False,
    "supervised.py does not even read channel.",
    "O supervised.py nem lê channel."),
   ("Its labels are unfinished: the 90 days end after 28 February",
    "Os rótulos não estão prontos: os 90 dias acabam depois de 28 de fevereiro", True,
    "Right. A member who has not had time to come back would be labelled lapsed.",
    "Isso. Um membro que não teve tempo de voltar seria rotulado como afastado."),
   ("LogisticRegression cannot read dates after the turn of a year",
    "LogisticRegression não lê datas depois de uma virada de ano", False,
    "The model never sees a date, only the numbers computed as of it.",
    "O modelo nunca vê uma data, só os números calculados em relação a ela.")])

N("ex-e3evhcrg", "supervised", "easy",
  "What probability of lapsing did the model give member 1670?",
  "Que probabilidade de afastamento o modelo deu ao membro 1670?",
  0.86, 0, "", "")

Q("ex-ygpg0tq1", "supervised", "medium",
  "Which kind of supervised learning would predict how much a member spends next month?",
  "Que tipo de aprendizado supervisionado preveria quanto um membro gasta no mês que vem?",
  [("Regression, because the answer is a quantity",
    "Regressão, porque a resposta é uma quantidade", True,
    "Right. Classification answers with a category; regression with a number.",
    "Isso. Classificação responde com uma categoria; regressão, com um número."),
   ("Classification, because spending is a yes or no",
    "Classificação, porque gastar é sim ou não", False,
    "How much is a quantity, not a category.",
    "Quanto é uma quantidade, não uma categoria."),
   ("Clustering, because spenders form groups",
    "Agrupamento, porque quem gasta forma grupos", False,
    "Clustering has no answer to learn; next month's spending is an answer.",
    "Agrupamento não tem resposta para aprender; o gasto do mês que vem é uma resposta."),
   ("A bandit, because spending responds to vouchers",
    "Um bandit, porque o gasto responde a vouchers", False,
    "Nothing is being chosen and rewarded here; there is a past to learn from.",
    "Nada está sendo escolhido e recompensado aqui; há um passado de onde aprender.")])

Q("ex-tsc82h1n", "unsupervised", "easy",
  "Why does unsupervised.py scale the columns before k-means?",
  "Por que o unsupervised.py coloca as colunas na mesma escala antes do k-means?",
  [("k-means only accepts numbers between 0 and 1",
    "O k-means só aceita números entre 0 e 1", False,
    "It accepts any numbers; scaling changes what distance means.",
    "Ele aceita qualquer número; a escala muda o que distância significa."),
   ("Spend in cents would outweigh visits",
    "O gasto em centavos pesaria mais que as visitas", True,
    "Right. k-means measures distance, and an unscaled six-figure column dominates it.",
    "Isso. O k-means mede distância, e uma coluna de seis dígitos sem escala a domina."),
   ("Scaling removes the members who lapsed from the table",
    "A escala remove da tabela os membros que se afastaram", False,
    "No row is removed; the label is not even used.",
    "Nenhuma linha é removida; o rótulo nem é usado."),
   ("To hide the label column from the algorithm",
    "Para esconder do algoritmo a coluna do rótulo", False,
    "The label is kept out by never passing it, not by scaling.",
    "O rótulo fica de fora por nunca ser passado, não pela escala.")])

Q("ex-k0078v2d", "unsupervised", "medium",
  "The lapsed column beside the four groups was never shown to k-means. What does it tell you?",
  "A coluna lapsed ao lado dos quatro grupos nunca foi mostrada ao k-means. O que ela lhe diz?",
  [("That k-means has learned how to predict which members lapse",
    "Que o k-means aprendeu a prever quais membros se afastam", False,
    "It never saw lapsed; it cannot have learned to predict it.",
    "Ele nunca viu lapsed; não pode ter aprendido a prevê-lo."),
   ("That four is the right number of groups for this shop",
    "Que quatro é o número certo de grupos para esta loja", False,
    "There is no right k; another number would also give readable groups.",
    "Não há k certo; outro número também daria grupos legíveis."),
   ("That the groups found something real about the members",
    "Que os grupos acharam algo real sobre os membros", True,
    "Right. 53% of group 1 lapsed against 5% of group 0. Most unsupervised work has no such check.",
    "Isso. 53% do grupo 1 se afastou contra 5% do grupo 0. A maior parte do trabalho não supervisionado não tem essa verificação."),
   ("That group 1 should be deleted from the shop",
    "Que o grupo 1 deve ser apagado da loja", False,
    "It is a group to act on, with a voucher, not to delete.",
    "É um grupo para agir, com um voucher, não para apagar.")])

N("ex-8cfhd1s9", "unsupervised", "easy",
  "How many members did k-means put in group 0, the regulars?",
  "Quantos membros o k-means pôs no grupo 0, os frequentes?",
  382, 0, "members", "membros")

P("ex-7m2c31re", "reinforcement", "easy",
  "Match each word of reinforcement learning to its part in bandit.py.",
  "Associe cada palavra do aprendizado por reforço à sua parte no bandit.py.",
  [("agent", "agente", "the loop that picks a voucher", "o laço que escolhe um voucher"),
   ("action", "ação", "sending one of the three vouchers", "mandar um dos três vouchers"),
   ("reward", "recompensa", "whether the member came back", "se o membro voltou"),
   ("environment", "ambiente", "TRUE_RATE, which the learner never reads", "TRUE_RATE, que o aprendiz nunca lê")],
  [("the label column of shop.db", "a coluna de rótulo do shop.db")])

Q("ex-g4yp06cy", "reinforcement", "medium",
  "Why did bandit.py send 1,799 of the worst voucher?",
  "Por que o bandit.py mandou 1.799 do pior voucher?",
  [("It explores at random every single time",
    "Ele experimenta ao acaso todas as vezes", False,
    "It explores one time in ten; the rest it exploits.",
    "Ele experimenta uma vez em dez; no resto, aproveita o conhecido."),
   ("Early luck made 10% off look best",
    "Sorte no começo fez os 10% parecerem melhores", True,
    "Right. After 43 sends it had a rate of 0.116 for the worst voucher.",
    "Isso. Depois de 43 envios ele tinha uma taxa de 0,116 para o pior voucher."),
   ("TRUE_RATE told it to",
    "TRUE_RATE mandou", False,
    "The learner never reads TRUE_RATE.",
    "O aprendiz nunca lê TRUE_RATE."),
   ("10% off was the best voucher in the simulated shop",
    "10% de desconto era o melhor voucher da loja simulada", False,
    "Its true rate was 0.04, the lowest of the three.",
    "A taxa real dele era 0,04, a menor das três.")])

Q("ex-0hkq02m2", "reinforcement", "hard",
  "Why can't Ponto Final train a voucher bandit on last year's purchases table alone?",
  "Por que a Ponto Final não pode treinar um bandit de vouchers só com a tabela de compras do ano passado?",
  [("The table is too small for reinforcement learning",
    "A tabela é pequena demais para aprendizado por reforço", False,
    "Size is not the issue; what is missing is the actions.",
    "O tamanho não é a questão; o que falta são as ações."),
   ("Reinforcement learning cannot read SQLite",
    "Aprendizado por reforço não lê SQLite", False,
    "Storage has nothing to do with it.",
    "O armazenamento não tem nada a ver."),
   ("No voucher was ever sent",
    "Nenhum voucher foi mandado", True,
    "Right. Without a log of actions and their rewards, there is nothing to learn from but a simulator.",
    "Isso. Sem um registro de ações e recompensas, não há do que aprender além de um simulador."),
   ("The purchases table has no label column",
    "A tabela de compras não tem coluna de rótulo", False,
    "Neither does it for lapsing, and supervised.py computes one; a bandit needs actions, not labels.",
    "Para afastamento também não tem, e o supervised.py calcula um; um bandit precisa de ações, não de rótulos.")])

P("ex-53x2dng2", "choosing", "medium",
  "Match each question at Ponto Final to what answers it.",
  "Associe cada pergunta na Ponto Final ao que a responde.",
  [("Which members are about to stop coming?", "Quais membros estão prestes a parar de vir?",
    "classification", "classificação"),
   ("How much will this member spend next month?", "Quanto este membro vai gastar no mês que vem?",
    "regression", "regressão"),
   ("What kinds of reader does the shop have?", "Que tipos de leitor a loja tem?",
    "clustering", "agrupamento"),
   ("How many members bought crime novels last month?", "Quantos membros compraram romance policial no mês passado?",
    "a query", "uma consulta")],
  [("a bandit", "um bandit")])

Q("ex-zkt3pcmy", "choosing", "medium",
  "When does a model earn its place over a rule written by hand?",
  "Quando um modelo merece o seu lugar em vez de uma regra escrita à mão?",
  [("Whenever the data is large enough to train one",
    "Sempre que os dados são grandes o bastante para treinar um", False,
    "Size alone does not justify one; a query with a known answer stays a query.",
    "Só o tamanho não justifica um; uma consulta com resposta conhecida continua sendo consulta."),
   ("When the answer is not in the data yet",
    "Quando a resposta ainda não está nos dados", True,
    "Right. The future and a member's taste are not in any column, and a hand rule gets them wrong.",
    "Isso. O futuro e o gosto de um membro não estão em nenhuma coluna."),
   ("When the rule would need more than one line of SQL",
    "Quando a regra precisaria de mais de uma linha de SQL", False,
    "A long rule can still be the right one; length is not the test.",
    "Uma regra longa ainda pode ser a certa; tamanho não é o critério."),
   ("When everybody agrees on the rule",
    "Quando todos concordam com a regra", False,
    "Then the rule is the better choice: cheap, readable and right.",
    "Então a regra é a melhor escolha: barata, legível e certa.")])

Q("ex-fst9ae6f", "choosing", "hard",
  "Marketing can send a hundred vouchers a month. What should the lapse model be good at?",
  "O marketing pode mandar cem vouchers por mês. Em que o modelo de afastamento deve ser bom?",
  [("Getting every member's probability exactly right",
    "Acertar exatamente a probabilidade de cada membro", False,
    "Only the order of the top hundred is acted on.",
    "Só a ordem dos cem primeiros vira ação."),
   ("Ranking the hundred likeliest at the top",
    "Pôr os cem mais prováveis no topo", True,
    "Right. Lesson 4 shows how that changes which score to look at.",
    "Isso. A lição 4 mostra como isso muda qual nota olhar."),
   ("Being right about the members who will stay",
    "Acertar sobre os membros que vão ficar", False,
    "Nobody acts on them; the vouchers go to the top of the list.",
    "Ninguém age sobre eles; os vouchers vão para o topo da lista."),
   ("Predicting exactly a hundred lapses a month",
    "Prever exatamente cem afastamentos por mês", False,
    "The budget limits the vouchers, not how many members lapse.",
    "O orçamento limita os vouchers, não quantos membros se afastam.")])

Q("ex-7jrhw727", "drill", "hard",
  "A colleague trains a model with the cutoff 2026-01-15 and reports that 31% of members lapsed. What is the likeliest cause?",
  "Um colega treina um modelo com o corte 2026-01-15 e relata que 31% dos membros se afastaram. Qual a causa mais provável?",
  [("The members who joined on the app lapse more often",
    "Os membros que entraram pelo aplicativo se afastam mais", False,
    "They do leave sooner, but that would not explain a sudden jump.",
    "Eles saem antes, mas isso não explicaria um salto repentino."),
   ("Its 90-day window runs past 28 February",
    "A janela de 90 dias passa de 28 de fevereiro", True,
    "Right. Members with no time to return count as lapsed; lesson 3 measures it.",
    "Isso. Quem não teve tempo de voltar conta como afastado; a lição 3 mede isso."),
   ("January is a slow month for bookshops",
    "Janeiro é um mês fraco para livrarias", False,
    "The generator has no seasons.",
    "O gerador não tem estações."),
   ("K-means put too many members in the fading group",
    "O k-means pôs membros demais no grupo dos que estão sumindo", False,
    "The label is computed by features.py, not by any clustering.",
    "O rótulo é calculado pelo features.py, não por agrupamento nenhum.")])

M("ex-jmv28j1h", "drill", "medium",
  "Which of these does features.py compute only from days on or before the cutoff? Choose every one that applies.",
  "Quais destes o features.py calcula só com dias até o corte? Escolha todos os que se aplicam.",
  [("recency_days", "recency_days", True, "Right.", "Isso."),
   ("visits_180d", "visits_180d", True, "Right.", "Isso."),
   ("online_share", "online_share", True, "Right.", "Isso."),
   ("lapsed", "lapsed", False, "The label is the one column that reads the 90 days after.",
    "O rótulo é a única coluna que lê os 90 dias depois.")])

O("ex-ev020885", "drill", "medium",
  "Put the life of the lapse model in supervised.py in order.",
  "Coloque em ordem a vida do modelo de afastamento em supervised.py.",
  [("build the examples as of 30 September", "montar os exemplos em 30 de setembro"),
   ("fit LogisticRegression on them", "ajustar a LogisticRegression a eles"),
   ("build the members as of 30 November", "montar os membros em 30 de novembro"),
   ("predict a probability for each", "prever uma probabilidade para cada um")])
