# Lesson 2: common tasks.
# python3 lab/tools/exb.py lab/exercises/l02.py lessons/le-mk4sta32 -v

P("ex-259ebswe", "four-answers", "easy",
  "Match each task to the shape of its answer.",
  "Associe cada tarefa à forma da sua resposta.",
  [("classification", "classificação", "a category, with a probability", "uma categoria, com uma probabilidade"),
   ("regression", "regressão", "an amount on a scale", "uma quantia numa escala"),
   ("clustering", "agrupamento", "a group number with no name", "um número de grupo sem nome"),
   ("recommendation", "recomendação", "a ranked list of other things", "uma lista ordenada de outras coisas")],
  [("a yes from a person who checked", "um sim de uma pessoa que conferiu")])

Q("ex-ejncrcpx", "four-answers", "medium",
  "A report stored each member's k-means group last month and compares it with this month's. What goes wrong?",
  "Um relatório guardou o grupo do k-means de cada membro no mês passado e o compara com o deste mês. O que dá errado?",
  [("k-means refuses to run twice on the same members",
    "O k-means se recusa a rodar duas vezes sobre os mesmos membros", False,
    "It runs as often as you like; the trouble is what its numbers mean.",
    "Ele roda quantas vezes você quiser; o problema é o que os números dele significam."),
   ("Group numbers are not stable across runs",
    "Números de grupo não são estáveis entre rodadas", True,
    "Right. Group 6 last month and group 6 this month can be different readers. Store the run beside the id.",
    "Isso. O grupo 6 do mês passado e o grupo 6 deste mês podem ser leitores diferentes. Guarde a rodada ao lado do id."),
   ("The silhouette falls every month, so the groups get worse",
    "A silhueta cai todo mês, então os grupos pioram", False,
    "Nothing says the silhouette falls; the problem is the ids, whatever the score.",
    "Nada diz que a silhueta cai; o problema são os ids, seja qual for a nota."),
   ("The report needs a label to compare clusters",
    "O relatório precisa de um rótulo para comparar grupos", False,
    "Clustering has no label at all; the ids are the problem.",
    "Agrupamento não tem rótulo nenhum; o problema são os ids.")])

Q("ex-5mqs3nv5", "four-answers", "medium",
  "Why is a recommendation keyed by a pair rather than by a member?",
  "Por que uma recomendação é guardada por um par e não por um membro?",
  [("Each member has one score per title they might be shown",
    "Cada membro tem uma nota por título que poderia lhe ser mostrado", True,
    "Right. Eighty titles means up to eighty scores a member.",
    "Isso. Oitenta títulos significam até oitenta notas por membro."),
   ("Two members share every recommendation",
    "Dois membros compartilham cada recomendação", False,
    "Each member gets their own list.",
    "Cada membro recebe a sua própria lista."),
   ("The pair is the member and the cutoff, the same as for lapsing",
    "O par é o membro e o corte, o mesmo que para o afastamento", False,
    "The cutoff is there too, but the pair that makes it big is member and title.",
    "O corte também está lá, mas o par que a torna grande é membro e título."),
   ("Recommendations are computed for pairs of titles, never for people",
    "Recomendações são calculadas para pares de títulos, nunca para pessoas", False,
    "Pairs of titles are counted, but the answer is a list for a person.",
    "Pares de títulos são contados, mas a resposta é uma lista para uma pessoa.")])

Q("ex-zq4q063r", "classification", "easy",
  "In classify.py, what does make_pipeline give you?",
  "No classify.py, o que o make_pipeline lhe dá?",
  [("One object that scales, encodes and predicts, fitted together",
    "Um objeto só que põe em escala, codifica e prevê, ajustado junto", True,
    "Right. The scaling learned in September is the one applied in November.",
    "Isso. A escala aprendida em setembro é a aplicada em novembro."),
   ("A faster logistic regression",
    "Uma regressão logística mais rápida", False,
    "The algorithm is unchanged; the pipeline joins the steps.",
    "O algoritmo não muda; o pipeline junta os passos."),
   ("A way to train on several cutoffs at once",
    "Um jeito de treinar com vários cortes de uma vez", False,
    "It trains on whatever rows fit is given, here one cutoff.",
    "Ele treina com as linhas que o fit recebe, aqui um corte."),
   ("A scheduled job that retrains the model",
    "Um job agendado que treina o modelo de novo", False,
    "Nothing in it is scheduled; that is the platform's job in later lessons.",
    "Nada nele é agendado; isso é trabalho da plataforma em lições seguintes.")])

Q("ex-d3kpmbs5", "classification", "medium",
  "At the default threshold the model calls 248 members lapsed and 530 lapsed. Why does the platform store probabilities rather than classes?",
  "No limiar padrão o modelo chama 248 membros de afastados e 530 se afastaram. Por que a plataforma guarda probabilidades e não classes?",
  [("Classes take more disk than probabilities",
    "Classes ocupam mais disco do que probabilidades", False,
    "A 0 or 1 is smaller, if anything.",
    "Um 0 ou 1 é menor, se for o caso."),
   ("A stored class freezes the threshold into every row",
    "Uma classe guardada congela o limiar em cada linha", True,
    "Right. With probabilities, the threshold is a parameter of whoever reads the table.",
    "Isso. Com probabilidades, o limiar é um parâmetro de quem lê a tabela."),
   ("predict_proba is the only one scikit-learn can save to a file",
    "predict_proba é a única que o scikit-learn consegue salvar num arquivo", False,
    "Both are just numbers; the reason is the threshold.",
    "As duas são só números; o motivo é o limiar."),
   ("Probabilities are always right, and classes are guesses",
    "Probabilidades sempre acertam, e classes são palpites", False,
    "Both come from the same model; one has a threshold baked in.",
    "As duas vêm do mesmo modelo; uma tem um limiar embutido.")])

N("ex-wvvmwfj8", "classification", "easy",
  "What threshold does scikit-learn's predict compare the probability with, for two classes?",
  "Com que limiar o predict do scikit-learn compara a probabilidade, para duas classes?",
  0.5, 0, "", "")

Q("ex-2dn5nx0f", "classification", "medium",
  "A model reads support tickets and answers delivery, payment or refund. What changes compared with the lapse model?",
  "Um modelo lê chamados de suporte e responde entrega, pagamento ou reembolso. O que muda em relação ao modelo de afastamento?",
  [("It becomes regression, because there are more than two answers",
    "Vira regressão, porque há mais de duas respostas", False,
    "Three categories are still categories.",
    "Três categorias continuam sendo categorias."),
   ("It needs clustering first to find the three classes",
    "Precisa de agrupamento antes para achar as três classes", False,
    "The classes are known and labelled; nothing has to be found.",
    "As classes são conhecidas e rotuladas; nada precisa ser achado."),
   ("Three probabilities instead of two",
    "Três probabilidades em vez de duas", True,
    "Right. It is multi-class classification, and nothing else changes.",
    "Isso. É classificação multiclasse, e nada mais muda."),
   ("predict_proba stops working with more than two classes",
    "predict_proba para de funcionar com mais de duas classes", False,
    "It returns one probability per class.",
    "Ele devolve uma probabilidade por classe.")])

Q("ex-0affs3b8", "encoding", "easy",
  "Why not encode home_shop as Paulista 0, Pinheiros 1, Cambuí 2 and so on?",
  "Por que não codificar home_shop como Paulista 0, Pinheiros 1, Cambuí 2 e assim por diante?",
  [("The model would treat the shops as an order with distances",
    "O modelo trataria as lojas como uma ordem com distâncias", True,
    "Right. Cambuí would be twice Pinheiros, an order that does not exist.",
    "Isso. Cambuí seria o dobro de Pinheiros, uma ordem que não existe."),
   ("scikit-learn raises an error on integer categories",
    "O scikit-learn levanta um erro com categorias inteiras", False,
    "It does not; that is why the mistake is silent.",
    "Não levanta; é por isso que o erro é silencioso."),
   ("Seven numbers take more memory than seven columns",
    "Sete números ocupam mais memória que sete colunas", False,
    "It is the other way round, and memory is not the issue.",
    "É o contrário, e memória não é a questão."),
   ("SQLite cannot store a shop as a number",
    "O SQLite não consegue guardar uma loja como número", False,
    "It can; the problem is what the model reads into the number.",
    "Consegue; o problema é o que o modelo lê no número.")])

N("ex-1f24vce6", "encoding", "easy",
  "Into how many columns did encode.py turn channel, age_band and home_shop?",
  "Em quantas colunas o encode.py transformou channel, age_band e home_shop?",
  16, 0, "columns", "colunas")

Q("ex-hpe5yreq", "encoding", "hard",
  "A model trained before September 2025 meets a member whose channel is app. What does handle_unknown=\"ignore\" do?",
  "Um modelo treinado antes de setembro de 2025 encontra um membro cujo channel é app. O que handle_unknown=\"ignore\" faz?",
  [("It retrains the encoder with the new value",
    "Treina o codificador de novo com o valor novo", False,
    "Nothing retrains at prediction time.",
    "Nada é treinado de novo na hora da predição."),
   ("It encodes the channel as all zeros",
    "Codifica o canal como tudo zero", True,
    "Right. The model then knows nothing about the channel, and keeps answering.",
    "Isso. O modelo então não sabe nada do canal, e continua respondendo."),
   ("It raises an error on the first app member",
    "Levanta um erro no primeiro membro do aplicativo", False,
    "That is what happens without it.",
    "Isso é o que acontece sem ele."),
   ("It treats app as store, the most common channel",
    "Trata app como store, o canal mais comum", False,
    "It maps the unknown value to no channel at all, not to the commonest.",
    "Ele leva o valor desconhecido a nenhum canal, não ao mais comum.")])

M("ex-9q0pbjv9", "encoding", "medium",
  "Which of these are true of one-hot encoding in encode.py? Choose every one that applies.",
  "Quais destas são verdade sobre o one-hot no encode.py? Escolha todas as que se aplicam.",
  [("Each value of a category gets its own column", "Cada valor de uma categoria ganha uma coluna própria", True, "Right.", "Isso."),
   ("Exactly one column of each group holds a 1", "Exatamente uma coluna de cada grupo tem um 1", True, "Right.", "Isso."),
   ("The columns are learned from the rows it was fitted on", "As colunas são aprendidas com as linhas em que foi ajustado", True, "Right. A later value has no column.", "Isso. Um valor posterior não tem coluna."),
   ("Larger shops get larger numbers", "Lojas maiores ganham números maiores", False, "No column is bigger than another; that is the point.", "Nenhuma coluna é maior que outra; esse é o ponto.")])

Q("ex-x0chmpek", "regression", "easy",
  "Why does regress.py fill a missing spend_next_90d with 0?",
  "Por que o regress.py preenche um spend_next_90d faltante com 0?",
  [("LinearRegression cannot read missing values, so any number would do",
    "LinearRegression não lê valores faltantes, então qualquer número serviria", False,
    "The number matters: zero is chosen because it is true here.",
    "O número importa: zero é escolhido porque é verdade aqui."),
   ("A member with no visit in the 90 days spent nothing",
    "Um membro sem visita nos 90 dias não gastou nada", True,
    "Right. In another dataset missing means unknown, and zero would teach something false.",
    "Isso. Em outro conjunto faltante quer dizer desconhecido, e zero ensinaria algo falso."),
   ("To remove those members from the training rows",
    "Para tirar esses membros das linhas de treino", False,
    "They stay, with a label of 0.",
    "Eles ficam, com rótulo 0."),
   ("Because the query only returns members who lapsed",
    "Porque a consulta só devolve membros que se afastaram", False,
    "It returns members who spent something after the cutoff.",
    "Ela devolve membros que gastaram algo depois do corte.")])

N("ex-pj91hbw3", "regression", "easy",
  "What was regress.py's mean absolute error, in reais?",
  "Qual foi o erro absoluto médio do regress.py, em reais?",
  179.49, 0.01, "R$", "R$")

Q("ex-8a6w8wk8", "regression", "hard",
  "Members 2 and 3 had identical histories and spent R$ 39.90 and R$ 229.60 afterwards. What does that say about the model?",
  "Os membros 2 e 3 tinham histórias idênticas e gastaram R$ 39,90 e R$ 229,60 depois. O que isso diz sobre o modelo?",
  [("That it is broken, since it predicted almost the same for both",
    "Que ele está quebrado, já que previu quase o mesmo para os dois", False,
    "Identical inputs give near-identical outputs; that is correct behaviour.",
    "Entradas idênticas dão saídas quase idênticas; esse é o comportamento correto."),
   ("Nothing it sees tells them apart",
    "Nada do que ele vê consegue distinguir os dois", True,
    "Right. The error spreads around the truth; the useful question is how wide.",
    "Isso. O erro se espalha em volta da verdade; a pergunta útil é o quão largo."),
   ("That it needs to be a classifier instead",
    "Que ele precisa ser um classificador", False,
    "The answer is still an amount.",
    "A resposta continua sendo uma quantia."),
   ("That members 2 and 3 should be removed as outliers",
    "Que os membros 2 e 3 devem ser removidos como discrepantes", False,
    "They are ordinary members; the future is just not in their history.",
    "Eles são membros comuns; o futuro só não está na história deles.")])

Q("ex-81x4paze", "baselines", "easy",
  "What is the baseline for a regression?",
  "Qual é a linha de base de uma regressão?",
  [("The previous version of the model",
    "A versão anterior do modelo", False,
    "That is a comparison worth making too, but it is not the baseline.",
    "Essa também é uma comparação que vale fazer, mas não é a linha de base."),
   ("The training label's average, predicted for everybody",
    "A média do rótulo de treino, prevista para todos", True,
    "Right. It uses no features at all.",
    "Isso. Ela não usa atributo nenhum."),
   ("A regression with only the most important feature",
    "Uma regressão só com o atributo mais importante", False,
    "Any feature makes it more than the dumbest prediction.",
    "Qualquer atributo a torna mais que a predição mais boba."),
   ("Zero, because spending nothing is the commonest outcome",
    "Zero, porque não gastar nada é o desfecho mais comum", False,
    "For regression the baseline is the mean; the commonest class is the classifier's baseline.",
    "Para regressão a linha de base é a média; a classe mais comum é a do classificador.")])

N("ex-tgmmy3z5", "baselines", "medium",
  "By how many reais per member did the regression beat everybody spends the average?",
  "Por quantos reais por membro a regressão venceu todo mundo gasta a média?",
  34.27, 0.01, "R$", "R$")

Q("ex-wvqwe17z", "baselines", "medium",
  "Why does the platform keep computing the baseline after the model ships?",
  "Por que a plataforma continua calculando a linha de base depois que o modelo vai ao ar?",
  [("Because scikit-learn deletes the dummy models after training",
    "Porque o scikit-learn apaga os modelos dummy depois do treino", False,
    "Nothing is deleted; the baseline moves with the data.",
    "Nada é apagado; a linha de base se move com os dados."),
   ("The baseline moves, and a model looks better while knowing less",
    "A linha de base se move, e um modelo parece melhor sabendo menos", True,
    "Right. Lesson 9 tracks the model and the baseline on the same rows.",
    "Isso. A lição 9 acompanha o modelo e a linha de base nas mesmas linhas."),
   ("The baseline replaces the model when the model fails",
    "A linha de base substitui o modelo quando ele falha", False,
    "It is a yardstick, not a fallback.",
    "Ela é uma régua, não um substituto."),
   ("Regulators ask for one in every report",
    "Reguladores pedem uma em todo relatório", False,
    "Nothing in the lesson is about regulation.",
    "Nada na lição é sobre regulação.")])

Q("ex-dbewr2fy", "clustering", "easy",
  "What does the silhouette score need that k-means does not have?",
  "Do que a silhueta precisa que o k-means não tem?",
  [("A label for each member",
    "Um rótulo para cada membro", False,
    "It needs no label, which is why it is used to compare values of k.",
    "Ela não precisa de rótulo, e por isso é usada para comparar valores de k."),
   ("A second run with a different seed",
    "Uma segunda rodada com outra semente", False,
    "One run is enough.",
    "Uma rodada basta."),
   ("Nothing more than the rows and their groups",
    "Nada além das linhas e dos seus grupos", True,
    "Right. It compares each member's distance to its own group and to the next one.",
    "Isso. Ela compara a distância de cada membro ao próprio grupo e ao seguinte."),
   ("The number of categories in the shop",
    "O número de categorias da loja", False,
    "It knows nothing about categories, only distances.",
    "Ela não sabe nada de categorias, só de distâncias.")])

N("ex-nqw0rh9s", "clustering", "easy",
  "At which k did the silhouette peak in cluster.py?",
  "Em qual k a silhueta teve o pico no cluster.py?",
  8, 0, "groups", "grupos")

Q("ex-9pk2fa5y", "clustering", "hard",
  "Every member has two favourite categories, yet the eight groups each centre on one. What does that show?",
  "Todo membro tem duas categorias favoritas, mas os oito grupos se centram em uma cada. O que isso mostra?",
  [("That the generator gives each member only one favourite",
    "Que o gerador dá a cada membro só uma favorita", False,
    "It gives two; the second is drawn for fewer books.",
    "Ele dá duas; a segunda é sorteada para menos livros."),
   ("The silhouette found what it could see, not everything there",
    "A silhueta achou o que conseguia ver, não tudo o que existe", True,
    "Right. The second favourite is spread at 7 or 8% across every group.",
    "Isso. A segunda favorita fica espalhada em 7 ou 8% por todos os grupos."),
   ("That k = 28 would have given a silhouette of 1",
    "Que k = 28 teria dado silhueta 1", False,
    "Nothing measured says so; the peak was at 8.",
    "Nada medido diz isso; o pico foi em 8."),
   ("That clustering on shares cannot work at all",
    "Que agrupar por frações não funciona de jeito nenhum", False,
    "It found a real structure: the first favourite.",
    "Achou uma estrutura real: a primeira favorita.")])

Q("ex-1w8td2w5", "recommendation", "medium",
  "Why does recommend.py divide each co-purchase count by the recommended title's popularity?",
  "Por que o recommend.py divide cada contagem de compra conjunta pela popularidade do título recomendado?",
  [("To keep the scores between 0 and 1",
    "Para manter as notas entre 0 e 1", False,
    "They are not kept in any range; the point is what they compare.",
    "Elas não ficam em faixa nenhuma; o ponto é o que comparam."),
   ("Otherwise everybody gets the same bestsellers",
    "Senão todo mundo recebe os mesmos best-sellers", True,
    "Right. It asks whether B goes with A more than B sells anyway.",
    "Isso. Pergunta se B anda com A mais do que B vende de qualquer jeito."),
   ("Popular titles are out of stock more often",
    "Títulos populares ficam sem estoque com mais frequência", False,
    "The shop has no stock in it.",
    "A loja não tem estoque nenhum."),
   ("To recommend only titles nobody has bought",
    "Para recomendar só títulos que ninguém comprou", False,
    "A title nobody bought has no count to divide.",
    "Um título que ninguém comprou não tem contagem para dividir.")])

N("ex-d9wg3ykr", "recommendation", "easy",
  "What hit rate at 5 did the co-purchase recommender reach, in percent?",
  "Que taxa de acerto em 5 o recomendador de compra conjunta atingiu, em porcentagem?",
  67.1, 0.05, "%", "%")

Q("ex-zgkqjama", "recommendation", "hard",
  "The co-purchase list hit 67.1% against 21.0% for popularity. Which conclusion does that NOT support?",
  "A lista de compra conjunta acertou 67,1% contra 21,0% da popularidade. Que conclusão isso NÃO sustenta?",
  [("That it ranks members' next titles better than popularity",
    "Que ela ordena os próximos títulos dos membros melhor que a popularidade", False,
    "That is exactly what hit rate measures.",
    "É exatamente isso que a taxa de acerto mede."),
   ("That showing the list would cause those sales",
    "Que mostrar a lista causaria essas vendas", True,
    "Right. Nobody was shown it; only an experiment says whether it changes anything.",
    "Isso. Ninguém viu a lista; só um experimento diz se ela muda alguma coisa."),
   ("That the shop's members have regular taste",
    "Que os membros da loja têm gosto regular", False,
    "The lesson says so, and it helps the number.",
    "A lição diz isso, e isso ajuda o número."),
   ("That the test used only purchases after 30 November",
    "Que o teste usou só as compras depois de 30 de novembro", False,
    "That is how it was built: count before, judge after.",
    "É assim que ele foi montado: contar antes, julgar depois.")])

O("ex-h30gatx8", "recommendation", "medium",
  "Put the steps of recommend.py's test in order.",
  "Coloque em ordem os passos do teste do recommend.py.",
  [("split each member's titles at 30 November", "separar os títulos de cada membro em 30 de novembro"),
   ("count pairs of titles bought before the cut", "contar pares de títulos comprados antes do corte"),
   ("recommend five titles each member did not own", "recomendar cinco títulos que cada membro não tinha"),
   ("check them against what they bought after", "conferir com o que compraram depois")])

P("ex-pyh05sha", "what-each-needs", "medium",
  "Match each task at Ponto Final to when its right answer is known.",
  "Associe cada tarefa da Ponto Final a quando a sua resposta certa fica conhecida.",
  [("lapse", "afastamento", "90 days after the prediction", "90 dias depois da predição"),
   ("kinds of reader", "tipos de leitor", "never: there is no right answer", "nunca: não há resposta certa"),
   ("next title", "próximo título", "when the member next buys, if ever", "quando o membro compra de novo, se comprar")],
  [("the moment the model is trained", "no momento em que o modelo é treinado")])

Q("ex-7ae8s684", "what-each-needs", "medium",
  "Which task needs features that are minutes old rather than a day old?",
  "Que tarefa precisa de atributos com minutos de idade e não um dia?",
  [("The lapse model, because members leave suddenly",
    "O modelo de afastamento, porque os membros saem de repente", False,
    "Lapsing plays out over 90 days; a day-old feature is fine.",
    "O afastamento se desenrola em 90 dias; um atributo de um dia serve."),
   ("The recommender",
    "O recomendador", True,
    "Right. A purchase at 10:02 should change what the site shows at 10:05.",
    "Isso. Uma compra às 10h02 deveria mudar o que o site mostra às 10h05."),
   ("Clustering, because group numbers change every run",
    "O agrupamento, porque os números de grupo mudam a cada rodada", False,
    "A month-old grouping is fine; unstable ids are a different problem.",
    "Um agrupamento de um mês serve; ids instáveis são outro problema."),
   ("The spend regression, because money is involved",
    "A regressão de gasto, porque envolve dinheiro", False,
    "It works on 90-day windows, like lapsing.",
    "Ela trabalha com janelas de 90 dias, como o afastamento.")])

Q("ex-r0yw7df4", "drill", "hard",
  "A lapse score table has member_id and p_lapse and nothing else. What can it never be used for?",
  "Uma tabela de notas de afastamento tem member_id e p_lapse e mais nada. Para que ela nunca pode ser usada?",
  [("Sending vouchers to the top hundred",
    "Mandar vouchers para os cem primeiros", False,
    "Ranking needs only the scores.",
    "Ordenar só precisa das notas."),
   ("Comparing the scores with the outcomes 90 days later",
    "Comparar as notas com os desfechos 90 dias depois", True,
    "Right. Without the cutoff, nobody knows which 90 days to compare with.",
    "Isso. Sem o corte, ninguém sabe com quais 90 dias comparar."),
   ("Choosing a threshold other than 0.5",
    "Escolher um limiar diferente de 0,5", False,
    "Probabilities are exactly what makes that possible.",
    "Probabilidades são justamente o que torna isso possível."),
   ("Joining the scores to the members table",
    "Juntar as notas à tabela de membros", False,
    "member_id joins it.",
    "member_id faz a junção.")])

Q("ex-kz6h1rtr", "drill", "medium",
  "A lapse model reaches 82% on some measure. What is the first thing to ask?",
  "Um modelo de afastamento atinge 82% em alguma medida. Qual a primeira coisa a perguntar?",
  [("Which algorithm produced it",
    "Qual algoritmo o produziu", False,
    "The algorithm matters less than what the number is compared with.",
    "O algoritmo importa menos do que aquilo com que o número é comparado."),
   ("What the baseline scores on the same rows",
    "Quanto a linha de base tira nas mesmas linhas", True,
    "Right. Always stays already scores 83% on the most common measure.",
    "Isso. Sempre fica já tira 83% na medida mais comum."),
   ("Whether it was trained on more than 3,000 members",
    "Se ele foi treinado com mais de 3.000 membros", False,
    "Size does not make a number meaningful.",
    "Tamanho não dá sentido a um número."),
   ("Whether 82% rounds up to 85%",
    "Se 82% arredonda para 85%", False,
    "Rounding changes nothing about what it means.",
    "Arredondar não muda nada do que ele significa.")])
