# Lesson 3: splits and leakage.
# python3 lab/tools/exb.py lab/exercises/l03.py lessons/le-mxa5a0m1 -v

Q("ex-arxz8gsr", "the-score-that-lies", "easy",
  "The tree with no depth limit scores 1.000 on its training rows. What does that show?",
  "A árvore sem limite de profundidade tira 1,000 nas linhas de treino. O que isso mostra?",
  [("That it is the best of the six trees",
    "Que ela é a melhor das seis árvores", False,
    "On the validation rows it is the worst, 0.636.",
    "Nas linhas de validação ela é a pior, 0,636."),
   ("That it memorised them",
    "Que ela as decorou", True,
    "Right. Remembering rows is not learning about members.",
    "Isso. Lembrar linhas não é aprender sobre membros."),
   ("That the training rows contain a leak of the label into the features",
    "Que as linhas de treino têm um vazamento do rótulo para os atributos", False,
    "No leak is needed: an unlimited tree can fit any rows perfectly.",
    "Nenhum vazamento é necessário: uma árvore sem limite ajusta quaisquer linhas perfeitamente."),
   ("That AUC is the wrong score for trees",
    "Que AUC é a nota errada para árvores", False,
    "AUC is fine; it was computed on the wrong rows.",
    "A AUC serve; ela foi calculada nas linhas erradas.")])

N("ex-x03kga77", "the-score-that-lies", "easy",
  "Which maximum depth had the best validation AUC in overfit.py?",
  "Qual profundidade máxima teve a melhor AUC de validação no overfit.py?",
  4, 0, "", "")

Q("ex-mfbr76rt", "the-score-that-lies", "medium",
  "What does an AUC of 0.5 mean for the lapse model?",
  "O que uma AUC de 0,5 significa para o modelo de afastamento?",
  [("No better than a coin at ranking pairs",
    "Ordena pares tão bem quanto uma moeda", True,
    "Right. AUC is that pairwise chance, from 0.5 to 1.",
    "Isso. A AUC é essa chance entre pares, de 0,5 a 1."),
   ("Half the members are predicted to lapse",
    "Metade dos membros é prevista como afastada", False,
    "AUC says nothing about how many are flagged.",
    "A AUC não diz nada sobre quantos são apontados."),
   ("It is right about half the members and wrong about the rest",
    "Ele acerta metade dos membros e erra o resto", False,
    "That would be accuracy, not AUC, and lesson 4 shows why it misleads.",
    "Isso seria acurácia, não AUC, e a lição 4 mostra por que ela engana."),
   ("The model was trained on half the rows",
    "O modelo foi treinado com metade das linhas", False,
    "AUC does not describe the training set.",
    "A AUC não descreve o conjunto de treino.")])

P("ex-pccdbmcs", "three-sets", "easy",
  "Match each set to its job.",
  "Associe cada conjunto ao seu trabalho.",
  [("training", "treino", "the rows fit reads", "as linhas que o fit lê"),
   ("validation", "validação", "choosing between models", "escolher entre modelos"),
   ("test", "teste", "one honest estimate, at the end", "uma estimativa honesta, no fim")],
  [("the rows the model is used on in production", "as linhas em que o modelo é usado em produção")])

Q("ex-gzysmdjt", "three-sets", "medium",
  "After seeing a disappointing test score, a colleague tries another depth and checks the test again. What has happened?",
  "Depois de ver uma nota de teste decepcionante, um colega testa outra profundidade e confere o teste de novo. O que aconteceu?",
  [("Nothing, as long as the test rows were not used for training",
    "Nada, desde que as linhas de teste não tenham sido usadas no treino", False,
    "They were used for choosing, which is a kind of learning.",
    "Elas foram usadas para escolher, o que é um tipo de aprendizado."),
   ("The test set became a validation set",
    "O conjunto de teste virou um conjunto de validação", True,
    "Right. There is no honest number left until fresh rows are held back.",
    "Isso. Não sobra número honesto até que linhas novas sejam separadas."),
   ("The model now overfits the training rows",
    "O modelo agora se sobreajusta às linhas de treino", False,
    "The problem is with the test rows, not the training rows.",
    "O problema está nas linhas de teste, não nas de treino."),
   ("The score will be lower, because each look costs accuracy",
    "A nota vai ser menor, porque cada olhada custa acurácia", False,
    "Looking costs nothing in the score; it costs its honesty.",
    "Olhar não custa nada na nota; custa a honestidade dela.")])

Q("ex-p4yd0chb", "three-sets", "medium",
  "In a platform, who should compute the score on the test rows?",
  "Numa plataforma, quem deve calcular a nota nas linhas de teste?",
  [("The person tuning the model, as often as they need",
    "Quem está ajustando o modelo, quantas vezes precisar", False,
    "Then the test rows become part of the tuning.",
    "Então as linhas de teste viram parte do ajuste."),
   ("The release step",
    "A etapa de publicação", True,
    "Right. Training jobs do not read the test rows at all.",
    "Isso. Os jobs de treino nem leem as linhas de teste."),
   ("Nobody: a held-out test is too small to matter",
    "Ninguém: um teste separado é pequeno demais para importar", False,
    "3,130 members is enough to tell 0.76 from 0.79.",
    "3.130 membros bastam para distinguir 0,76 de 0,79."),
   ("Whoever trained the previous version of the model",
    "Quem treinou a versão anterior do modelo", False,
    "Who it is matters less than that nobody choosing uses it.",
    "Quem é importa menos do que ninguém que esteja escolhendo o usar.")])

Q("ex-pt1qpm4f", "what-leakage-is", "easy",
  "What is leakage?",
  "O que é vazamento?",
  [("A test set smaller than the training set",
    "Um conjunto de teste menor que o de treino", False,
    "That is normal and harmless.",
    "Isso é normal e inofensivo."),
   ("Rows lost between the warehouse and the training job",
    "Linhas perdidas entre o warehouse e o job de treino", False,
    "Losing rows is a different problem; leakage adds information.",
    "Perder linhas é outro problema; vazamento acrescenta informação."),
   ("Information in the rows that will not exist when the model is used",
    "Informação nas linhas que não vai existir quando o modelo for usado", True,
    "Right. Both scores look excellent, and production does something nobody measured.",
    "Isso. As duas notas parecem excelentes, e a produção faz algo que ninguém mediu."),
   ("A model that leaks members' personal data in the predictions it serves",
    "Um modelo que vaza dados pessoais dos membros nas predições que serve", False,
    "That is a privacy problem; leakage here is about time.",
    "Isso é um problema de privacidade; vazamento aqui é sobre tempo.")])

Q("ex-k72xkpck", "what-leakage-is", "medium",
  "For the lapse model, what is the moment of prediction?",
  "Para o modelo de afastamento, qual é o momento da predição?",
  [("The cutoff, the night the scores are computed",
    "O corte, a noite em que as notas são calculadas", True,
    "Right. What is known by then may be a feature.",
    "Isso. O que se sabe até lá pode ser atributo."),
   ("The day the member's 90-day window closes",
    "O dia em que a janela de 90 dias do membro fecha", False,
    "That is when the label becomes known, after the prediction.",
    "É quando o rótulo fica conhecido, depois da predição."),
   ("The member's first purchase",
    "A primeira compra do membro", False,
    "That only starts their history.",
    "Isso só começa a história dele."),
   ("The day the model was trained, whenever that was",
    "O dia em que o modelo foi treinado, qualquer que tenha sido", False,
    "A model trained once is used at many later cutoffs.",
    "Um modelo treinado uma vez é usado em muitos cortes posteriores.")])

Q("ex-adx09440", "the-summary-table", "medium",
  "In leak.py, member 1's recency is -14 days. What does the negative value give away?",
  "No leak.py, a recência do membro 1 é de -14 dias. O que o valor negativo entrega?",
  [("That the member joined after the cutoff",
    "Que o membro aderiu depois do corte", False,
    "Joining is tenure; a negative recency is a visit after the cutoff.",
    "Aderir é tempo de casa; uma recência negativa é uma visita depois do corte."),
   ("That the purchases table has a wrong date",
    "Que a tabela de compras tem uma data errada", False,
    "The date is right; it is read from the wrong moment.",
    "A data está certa; ela é lida do momento errado."),
   ("That they came back after the cutoff, which is the label itself",
    "Que ele voltou depois do corte, que é o próprio rótulo", True,
    "Right. The model learned to read the answer.",
    "Isso. O modelo aprendeu a ler a resposta."),
   ("That pandas subtracted the dates in the wrong order",
    "Que o pandas subtraiu as datas na ordem errada", False,
    "The order is right; the later date is from after the cutoff.",
    "A ordem está certa; a data posterior é de depois do corte.")])

N("ex-ewx59d1a", "the-summary-table", "medium",
  "Trained on the summary table and used in production, how many of 3,130 members did the model predict would lapse?",
  "Treinado com a tabela de resumo e usado em produção, quantos de 3.130 membros o modelo previu que se afastariam?",
  2450, 0, "members", "membros")

Q("ex-3jfn5sp6", "the-summary-table", "hard",
  "The leaky model still ranks members with AUC 0.787 in production. Why is it still unusable?",
  "O modelo com vazamento ainda ordena os membros com AUC 0,787 em produção. Por que ele continua inutilizável?",
  [("Its probabilities are off by a factor of four",
    "As probabilidades dele estão erradas por um fator de quatro", True,
    "Right. Any threshold, budget or forecast built on them is wrong.",
    "Isso. Qualquer limiar, orçamento ou previsão em cima delas está errado."),
   ("Because 0.787 is below the 0.8 every model needs to reach production",
    "Porque 0,787 está abaixo dos 0,8 que todo modelo precisa para ir a produção", False,
    "There is no such rule; the honest model scores 0.790 too.",
    "Não existe essa regra; o modelo honesto também tira 0,790."),
   ("Because it was trained on fewer members than the honest one",
    "Porque foi treinado com menos membros que o honesto", False,
    "Both trained on the same members.",
    "Os dois treinaram com os mesmos membros."),
   ("Because the summary table is deleted every night",
    "Porque a tabela de resumo é apagada toda noite", False,
    "It is rebuilt, and that is exactly why it only holds the present.",
    "Ela é reconstruída, e é justamente por isso que só guarda o presente.")])

Q("ex-22xz8qj5", "the-summary-table", "medium",
  "What lets the platform compute a feature as it stood on a past cutoff?",
  "O que permite à plataforma calcular um atributo como ele estava num corte passado?",
  [("Rebuilding the summary table more often",
    "Reconstruir a tabela de resumo com mais frequência", False,
    "More often still only holds the present.",
    "Com mais frequência ela continua guardando só o presente."),
   ("The history, or snapshots kept rather than overwritten",
    "O histórico, ou fotografias guardadas em vez de sobrescritas", True,
    "Right. Lesson 6 builds the point-in-time join on top of that.",
    "Isso. A lição 6 constrói a junção no ponto do tempo em cima disso."),
   ("Dropping recency from the features altogether",
    "Tirar a recência dos atributos de vez", False,
    "Recency is the most useful feature; it just has to be computed as of the cutoff.",
    "A recência é o atributo mais útil; ela só precisa ser calculada em relação ao corte."),
   ("Training on the summary table but testing on purchases",
    "Treinar com a tabela de resumo mas testar com as compras", False,
    "That is what production would do, and it gave 2,450 false alarms' worth of nonsense.",
    "É o que a produção faria, e deu um absurdo de 2.450 alertas.")])

Q("ex-6qtrmz3w", "stacked-cutoffs", "medium",
  "Why does a random split of nine stacked cutoffs flatter the model?",
  "Por que uma divisão aleatória de nove cortes empilhados lisonjeia o modelo?",
  [("The same members end up in training and test",
    "Os mesmos membros acabam no treino e no teste", True,
    "Right. The test is partly people the model met a month earlier or later.",
    "Isso. O teste é em parte gente que o modelo conheceu um mês antes ou depois."),
   ("Random splits always put the easier rows in the test set",
    "Divisões aleatórias sempre põem as linhas mais fáceis no teste", False,
    "Chance has no preference for easy rows.",
    "O acaso não prefere linhas fáceis."),
   ("Nine cutoffs are too many rows for a random forest",
    "Nove cortes são linhas demais para uma floresta aleatória", False,
    "25,000 rows is small for a forest.",
    "25.000 linhas é pouco para uma floresta."),
   ("The newest cutoff's labels are unfinished",
    "Os rótulos do corte mais novo estão inacabados", False,
    "The newest is 30 November, whose window closed on 28 February.",
    "O mais novo é 30 de novembro, cuja janela fechou em 28 de fevereiro.")])

N("ex-azd9fnsc", "stacked-cutoffs", "easy",
  "What AUC did the random split report in splits.py?",
  "Que AUC a divisão aleatória relatou no splits.py?",
  0.766, 0, "", "")

Q("ex-r7cz6n67", "stacked-cutoffs", "hard",
  "A model will score customers of a shop that opens next year and has never sold anything. Which split tests it honestly?",
  "Um modelo vai pontuar clientes de uma loja que abre no ano que vem e nunca vendeu nada. Que divisão o testa com honestidade?",
  [("A random split of rows, since the shop has no history",
    "Uma divisão aleatória das linhas, já que a loja não tem histórico", False,
    "That would test it on people it has already met.",
    "Isso o testaria com gente que ele já conheceu."),
   ("One that keeps whole members on one side",
    "Uma que mantém membros inteiros de um lado só", True,
    "Right. In production every customer is new, so the test has to be too.",
    "Isso. Em produção todo cliente é novo, então o teste também precisa ser."),
   ("Training on the newest cutoff only",
    "Treinar só com o corte mais novo", False,
    "Newness of the date does not make the people new.",
    "A data ser nova não torna as pessoas novas."),
   ("No split: score it on all the rows",
    "Nenhuma divisão: pontuar em todas as linhas", False,
    "That is the score that lies.",
    "Essa é a nota que mente.")])

O("ex-tey185m3", "splitting-by-time", "medium",
  "Put these dates for the lapse model in calendar order.",
  "Coloque estas datas do modelo de afastamento em ordem de calendário.",
  [("the newest training cutoff, 31 August", "o corte de treino mais novo, 31 de agosto"),
   ("its label window closes, 29 November", "a janela do rótulo dele fecha, 29 de novembro"),
   ("the test cutoff, 30 November", "o corte de teste, 30 de novembro"),
   ("the test labels are known, 28 February", "os rótulos de teste ficam conhecidos, 28 de fevereiro")])

C("ex-avxxbdfr", "splitting-by-time", "medium",
  "For a model with a 90-day label window used on date T, the newest training cutoff is T minus ___ days or earlier.",
  "Para um modelo com janela de rótulo de 90 dias usado na data T, o corte de treino mais novo é T menos ___ dias ou antes.",
  ["90", "ninety"], ["90", "noventa"])

Q("ex-8rjaspm2", "splitting-by-time", "hard",
  "A nightly job retrains the lapse model on every cutoff up to yesterday. What is wrong with its training set?",
  "Um job noturno treina o modelo de afastamento com todos os cortes até ontem. O que há de errado no conjunto de treino dele?",
  [("Nothing: more recent rows are more relevant",
    "Nada: linhas mais recentes são mais relevantes", False,
    "Recent, and with labels still being written.",
    "Recentes, e com rótulos ainda sendo escritos."),
   ("It has too many rows to train overnight",
    "Tem linhas demais para conseguir treinar de madrugada", False,
    "Size is not the issue.",
    "Tamanho não é a questão."),
   ("Its newest labels are still being written",
    "Os rótulos mais novos ainda estão sendo escritos", True,
    "Right. Members with no time to return are counted as lapsed.",
    "Isso. Membros sem tempo de voltar são contados como afastados."),
   ("It forgets the older cutoffs",
    "Ele esquece os cortes mais antigos", False,
    "Every cutoff is in it; the newest ones are the problem.",
    "Todo corte está nele; os mais novos é que são o problema.")])

N("ex-g94z2st8", "unfinished-labels", "easy",
  "What share of members was labelled lapsed for the cutoff 2026-02-15, in percent?",
  "Que fração dos membros foi rotulada como afastada no corte 2026-02-15, em porcentagem?",
  65.5, 0.05, "%", "%")

Q("ex-3s8p604m", "unfinished-labels", "medium",
  "Where does the fix for unfinished labels belong?",
  "Onde fica a correção para rótulos inacabados?",
  [("In the modeller's notebook, as a filter before fitting",
    "No notebook de quem modela, como filtro antes do ajuste", False,
    "It is a property of when the data landed, so it belongs where the data is built.",
    "É uma propriedade de quando os dados chegaram, então fica onde os dados são montados."),
   ("In the pipeline that builds the training set",
    "No pipeline que monta o conjunto de treino", True,
    "Right. One condition: cutoff plus 90 days on or before the last complete day.",
    "Isso. Uma condição: corte mais 90 dias até o último dia completo."),
   ("In the model, which learns to ignore recent rows",
    "No modelo, que aprende a ignorar as linhas recentes", False,
    "A model cannot tell an unfinished label from a real one.",
    "Um modelo não distingue um rótulo inacabado de um real."),
   ("In the dashboard, which hides the newest cutoffs",
    "No painel, que esconde os cortes mais novos", False,
    "The damage is in the training, not in what anybody sees.",
    "O estrago está no treino, não no que alguém vê.")])

M("ex-s2mmdtth", "unfinished-labels", "medium",
  "Which of these labels need a maturity before they can be trusted? Choose every one that applies.",
  "Quais destes rótulos precisam de um tempo de maturação antes de serem confiáveis? Escolha todos os que se aplicam.",
  [("a member lapsing within 90 days", "um membro se afastar em até 90 dias", True, "Right.", "Isso."),
   ("a purchase returned within thirty days", "uma compra devolvida em até trinta dias", True, "Right.", "Isso."),
   ("a fraud reported by a chargeback", "uma fraude informada por um estorno", True, "Right. It can take weeks.", "Isso. Pode levar semanas."),
   ("the category of a book bought today", "a categoria de um livro comprado hoje", False,
    "That is known the moment it is bought.", "Isso é conhecido no momento da compra.")])

Q("ex-ce7v7aj7", "fitted-on-everything", "medium",
  "Why does target encoding fitted on all rows leak so badly?",
  "Por que um target encoding ajustado em todas as linhas vaza tanto?",
  [("It writes the test rows' labels into their features",
    "Ele escreve os rótulos das linhas de teste nos atributos delas", True,
    "Right. Each category becomes the average label, test rows included.",
    "Isso. Cada categoria vira o rótulo médio, linhas de teste inclusive."),
   ("It creates too many columns for the model",
    "Ele cria colunas demais para o modelo", False,
    "It creates one column per category, not many.",
    "Ele cria uma coluna por categoria, não muitas."),
   ("It changes the order of the rows",
    "Ele muda a ordem das linhas", False,
    "Order has nothing to do with it.",
    "A ordem não tem nada a ver."),
   ("Its averages are computed in floating point",
    "As médias dele são calculadas em ponto flutuante", False,
    "Precision is not the issue; what it averages is.",
    "A precisão não é a questão; o que ele faz a média é.")])

Q("ex-gcfj9b0g", "fitted-on-everything", "hard",
  "You are handed a model plus a separate scaler that was fitted in a notebook on the whole dataset. What is the risk for production?",
  "Você recebe um modelo e um scaler separado que foi ajustado num notebook sobre todo o conjunto. Qual o risco para produção?",
  [("The scaler will be too slow at prediction time",
    "O scaler vai ser lento demais na hora da predição", False,
    "Applying a scaler costs nothing; the problem is how it was fitted.",
    "Aplicar um scaler não custa nada; o problema é como ele foi ajustado."),
   ("It saw the test rows and lives outside the model",
    "Ele viu as linhas de teste e vive fora do modelo", True,
    "Right. Inside a pipeline, fit fits both on the training rows only, the same way every time.",
    "Isso. Dentro de um pipeline, o fit ajusta os dois só nas linhas de treino."),
   ("Scalers cannot be saved to a file next to the model",
    "Scalers não podem ser salvos num arquivo", False,
    "They can; that is not the problem.",
    "Podem; esse não é o problema."),
   ("It will reorder the categories of home_shop",
    "Ele vai reordenar as categorias de home_shop", False,
    "A scaler touches the numeric columns, not the categories.",
    "Um scaler mexe nas colunas numéricas, não nas categorias.")])

Q("ex-t8wqp8wx", "a-checklist", "easy",
  "A lapse model suddenly scores 0.994. What is the first suspect?",
  "Um modelo de afastamento de repente tira 0,994. Qual o primeiro suspeito?",
  [("The algorithm, which must be a better one",
    "O algoritmo, que deve ser melhor", False,
    "Predicting people 90 days ahead is not that easy for any algorithm.",
    "Prever pessoas 90 dias à frente não é tão fácil para nenhum algoritmo."),
   ("The random seed",
    "A semente aleatória", False,
    "A seed moves a score by a little, not to nearly perfect.",
    "Uma semente move uma nota um pouco, não para quase perfeita."),
   ("The data",
    "Os dados", True,
    "Right. A score that good is a symptom: look for a leak.",
    "Isso. Uma nota tão boa é um sintoma: procure um vazamento."),
   ("The test set, which must be too small to trust",
    "O conjunto de teste, que deve ser pequeno demais para confiar", False,
    "A small set is noisy in both directions, not suspiciously perfect.",
    "Um conjunto pequeno é ruidoso nas duas direções, não perfeito demais.")])

P("ex-bmx5e764", "a-checklist", "medium",
  "Match each question to the leak it catches.",
  "Associe cada pergunta ao vazamento que ela pega.",
  [("Could the value have been computed on the cutoff date?", "O valor poderia ter sido calculado na data do corte?",
    "a column from today's table", "uma coluna da tabela de hoje"),
   ("Is any member on both sides?", "Algum membro está dos dois lados?",
    "the same member twice", "o mesmo membro duas vezes"),
   ("Has every label's window closed?", "A janela de todo rótulo fechou?",
    "unfinished labels", "rótulos inacabados"),
   ("Was anything fitted before the split?", "Algo foi ajustado antes da divisão?",
    "preprocessing that saw the test", "pré-processamento que viu o teste")],
  [("a model with too many features", "um modelo com atributos demais")])

Q("ex-9f5k1zrm", "drill", "hard",
  "A churn feature is called orders_total and comes from the customer summary rebuilt nightly. How would you check it for leakage in one query?",
  "Um atributo de evasão se chama orders_total e vem do resumo de clientes reconstruído toda noite. Como você o checaria quanto a vazamento numa consulta?",
  [("Count how many rows have a null orders_total",
    "Contar quantas linhas têm orders_total nulo", False,
    "Nulls are a different problem.",
    "Nulos são outro problema."),
   ("Compare it with the orders on or before each row's cutoff",
    "Compará-lo com os pedidos até o corte de cada linha", True,
    "Right. Any row where it is larger counts orders from the future.",
    "Isso. Qualquer linha em que ele seja maior conta pedidos do futuro."),
   ("Check that its average is the same in training and test",
    "Conferir se a média dele é a mesma no treino e no teste", False,
    "A leaky column can have the same average in both.",
    "Uma coluna com vazamento pode ter a mesma média nos dois."),
   ("Drop it and see whether the score falls",
    "Tirá-lo e ver se a nota cai", False,
    "Any useful feature lowers the score when dropped; that proves nothing.",
    "Qualquer atributo útil baixa a nota ao sair; isso não prova nada.")])

O("ex-tn4yz9zr", "drill", "medium",
  "Put the steps of an honest evaluation in order.",
  "Coloque em ordem os passos de uma avaliação honesta.",
  [("build features as of each cutoff", "montar os atributos em cada corte"),
   ("drop rows whose label window is open", "tirar as linhas com janela de rótulo aberta"),
   ("choose the model on the validation cutoff", "escolher o modelo no corte de validação"),
   ("score it once on the later test cutoff", "pontuá-lo uma vez no corte de teste posterior")])

Q("ex-zgq5ey81", "drill", "medium",
  "Which leak in this lesson is the one a data engineer causes most often?",
  "Qual vazamento desta lição é o que um engenheiro de dados mais causa?",
  [("Overfitting a deep tree",
    "Sobreajustar uma árvore funda", False,
    "Overfitting is a modelling problem, and not a leak.",
    "Sobreajuste é um problema de modelagem, e não um vazamento."),
   ("A feature read from a table as it is today",
    "Um atributo lido de uma tabela como ela está hoje", True,
    "Right. Warehouse tables are built for the present.",
    "Isso. Tabelas de warehouse são feitas para o presente."),
   ("Looking at the test set twice",
    "Olhar o conjunto de teste duas vezes", False,
    "That is the tuner's habit, not the platform's.",
    "Esse é um hábito de quem ajusta, não da plataforma."),
   ("Choosing four groups for k-means",
    "Escolher quatro grupos para o k-means", False,
    "That is a choice, not a leak.",
    "Isso é uma escolha, não um vazamento.")])
