# Lesson 4: evaluation metrics and the accuracy trap.
# python3 lab/tools/exb.py lab/exercises/l04.py lessons/le-fcd08ha8 -v

Q("ex-j45wjncp", "the-trap", "easy",
  "The lapse model's accuracy is 86.0%. Why is that not evidence of a good model?",
  "A acurácia do modelo de afastamento é 86,0%. Por que isso não é prova de um bom modelo?",
  [("Accuracy cannot be computed for logistic regression",
    "A acurácia não pode ser calculada para regressão logística", False,
    "It can, and it was: 86.0%.",
    "Pode, e foi: 86,0%."),
   ("Saying nobody lapses already scores 83.1%",
    "Dizer que ninguém se afasta já tira 83,1%", True,
    "Right. Most members stay, so accuracy mostly measures that.",
    "Isso. A maioria dos membros fica, então a acurácia mede sobretudo isso."),
   ("86% is below the 90% a production model is expected to reach",
    "86% está abaixo dos 90% que se espera de um modelo em produção", False,
    "There is no such bar; the problem is what the number compares with.",
    "Não existe essa barra; o problema é com o que o número se compara."),
   ("The test month had unfinished labels",
    "O mês de teste tinha rótulos inacabados", False,
    "30 November's window closed on 28 February.",
    "A janela de 30 de novembro fechou em 28 de fevereiro.")])

N("ex-8s79zdqv", "the-trap", "easy",
  "What accuracy does the model that says nobody lapses reach on 30 November, in percent?",
  "Que acurácia o modelo que diz que ninguém se afasta atinge em 30 de novembro, em porcentagem?",
  83.1, 0.05, "%", "%")

Q("ex-an65ytv5", "the-trap", "medium",
  "A fraud model never flags anything and scores 99.9% accuracy. What does that tell you about fraud in the data?",
  "Um modelo de fraude nunca aponta nada e tira 99,9% de acurácia. O que isso diz sobre a fraude nos dados?",
  [("That it is about one payment in a thousand",
    "Que ela é cerca de um pagamento em mil", True,
    "Right. The score is the share of the common outcome.",
    "Isso. A nota é a fração do desfecho comum."),
   ("That the model catches 99.9% of the fraud",
    "Que o modelo pega 99,9% das fraudes", False,
    "It catches none: it never flags anything.",
    "Ele não pega nenhuma: nunca aponta nada."),
   ("That fraud is too rare to model at all",
    "Que a fraude é rara demais para ser modelada", False,
    "Rare outcomes are modelled every day; they need other scores.",
    "Desfechos raros são modelados todo dia; precisam de outras notas."),
   ("That the payments data has leaked the label",
    "Que os dados de pagamento vazaram o rótulo", False,
    "No leak is needed to score that; ignoring the rare class does it.",
    "Nenhum vazamento é preciso para tirar isso; ignorar a classe rara basta.")])

Q("ex-hyjh721r", "the-trap", "medium",
  "Why does lesson 4 put the lapse model's definition in model.py?",
  "Por que a lição 4 escreve o modelo de afastamento num arquivo, o model.py?",
  [("Because scikit-learn requires models to live in their own file",
    "Porque o scikit-learn exige que modelos fiquem num arquivo próprio", False,
    "It requires nothing of the kind.",
    "Ele não exige nada disso."),
   ("To make the model train faster",
    "Para o modelo treinar mais rápido", False,
    "Where it is defined changes nothing about speed.",
    "Onde ele é definido não muda nada na velocidade."),
   ("So the model has one definition in the project",
    "Para ele existir uma só vez no projeto", True,
    "Right. Every program that needs it imports it, and lesson 5 depends on that.",
    "Isso. Todo programa que precisa dele o importa, e a lição 5 depende disso."),
   ("To hide the threshold from the other programs",
    "Para esconder o limiar dos outros programas", False,
    "There is no threshold in it; the probabilities come out whole.",
    "Não há limiar nele; as probabilidades saem inteiras.")])

P("ex-wnywdzmz", "four-kinds-of-answer", "easy",
  "Match each cell of the confusion matrix to its count at 0.5.",
  "Associe cada célula da matriz de confusão à sua contagem em 0,5.",
  [("true negative", "verdadeiro negativo", "2,522", "2.522"),
   ("false alarm", "alarme falso", "78", "78"),
   ("miss", "perdido", "360", "360"),
   ("catch", "acerto", "170", "170")],
  [("530", "530")])

Q("ex-d3dvm006", "four-kinds-of-answer", "medium",
  "What does a false alarm cost Ponto Final?",
  "Quanto custa um alarme falso para a Ponto Final?",
  [("A member who leaves without anybody trying",
    "Um membro que vai embora sem ninguém tentar", False,
    "That is a miss, the other kind of error.",
    "Isso é um perdido, o outro tipo de erro."),
   ("A voucher sent to somebody who was coming back anyway",
    "Um voucher mandado a alguém que ia voltar de qualquer jeito", True,
    "Right. The two errors cost different amounts, which is why they are counted apart.",
    "Isso. Os dois erros custam valores diferentes, e por isso são contados separados."),
   ("Nothing, because the member stays",
    "Nada, porque o membro fica", False,
    "The voucher was still paid for.",
    "O voucher foi pago mesmo assim."),
   ("A retraining of the model",
    "Um novo treino do modelo", False,
    "One wrong prediction retrains nothing.",
    "Uma predição errada não treina nada de novo.")])

N("ex-rat17fa0", "precision-and-recall", "easy",
  "At the 0.5 threshold, what is the model's recall?",
  "No limiar de 0,5, qual é a revocação do modelo?",
  0.321, 0.001, "", "")

Q("ex-d3901m7s", "precision-and-recall", "medium",
  "Lowering the threshold from 0.5 to 0.2 does what to precision and recall?",
  "Baixar o limiar de 0,5 para 0,2 faz o que com a precisão e a revocação?",
  [("Both rise, because more members are flagged",
    "As duas sobem, porque mais membros são apontados", False,
    "More flags catch more lapses and also more members who were staying.",
    "Mais apontamentos pegam mais afastamentos e também mais membros que iam ficar."),
   ("Recall rises and precision falls",
    "A revocação sobe e a precisão cai", True,
    "Right. 0.321 to 0.608, and 0.685 to 0.434.",
    "Isso. 0,321 para 0,608, e 0,685 para 0,434."),
   ("Precision rises and recall falls",
    "A precisão sobe e a revocação cai", False,
    "That is raising the threshold.",
    "Isso é subir o limiar."),
   ("Neither moves; they are properties of the model",
    "Nenhuma se move; são propriedades do modelo", False,
    "A model has a precision at every threshold.",
    "Um modelo tem uma precisão em cada limiar.")])

Q("ex-6gheebsa", "precision-and-recall", "medium",
  "Why does F1 not help choose a threshold?",
  "Por que o F1 não ajuda a escolher um limiar?",
  [("It is only defined at 0.5",
    "Ele só é definido em 0,5", False,
    "It can be computed at any threshold.",
    "Ele pode ser calculado em qualquer limiar."),
   ("It weighs precision and recall equally, hiding the trade",
    "Ele pesa precisão e revocação igualmente, escondendo a troca", True,
    "Right. A voucher and a lost member are never the same amount of money.",
    "Isso. Um voucher e um membro perdido nunca são a mesma quantia de dinheiro."),
   ("It ignores the false alarms entirely",
    "Ele ignora completamente os alarmes falsos", False,
    "False alarms enter through precision.",
    "Os alarmes falsos entram pela precisão."),
   ("It is the same number as accuracy",
    "Ele é o mesmo número que a acurácia", False,
    "It is built from precision and recall, not from the four cells equally.",
    "Ele é feito de precisão e revocação, não das quatro células igualmente.")])

Q("ex-q2vk9s1e", "choosing-a-threshold", "medium",
  "At R$ 10.00 a voucher and R$ 60.00 a member kept, which threshold gave the most net value?",
  "A R$ 10,00 por voucher e R$ 60,00 por membro mantido, qual limiar deu o maior valor líquido?",
  [("0.5, scikit-learn's default",
    "0,5, o padrão do scikit-learn", False,
    "It was worth R$ 7,720.00, well below the best.",
    "Ele valeu R$ 7.720,00, bem abaixo do melhor."),
   ("0.2",
    "0,2", True,
    "Right. R$ 11,900.00, with 742 vouchers.",
    "Isso. R$ 11.900,00, com 742 vouchers."),
   ("0.1, because it catches the most lapses",
    "0,1, porque pega mais afastamentos", False,
    "It catches more and pays for 1,688 vouchers.",
    "Pega mais e paga por 1.688 vouchers."),
   ("0.6, because its precision is highest",
    "0,6, porque a precisão dele é a mais alta", False,
    "High precision on 180 vouchers leaves most lapses uncaught.",
    "Precisão alta em 180 vouchers deixa a maioria dos afastamentos sem pegar.")])

N("ex-7ef4dqhq", "choosing-a-threshold", "medium",
  "By the rule of thumb, a voucher pays for itself above what probability, with a R$ 10 voucher and a R$ 60 member? Give two decimals.",
  "Pela regra prática, um voucher se paga acima de qual probabilidade, com um voucher de R$ 10 e um membro de R$ 60? Dê duas casas.",
  0.17, 0.005, "", "")

Q("ex-cr8qdknf", "choosing-a-threshold", "hard",
  "Marketing says: we can send exactly 300 vouchers this month. What changes?",
  "O marketing diz: podemos mandar exatamente 300 vouchers este mês. O que muda?",
  [("The threshold must be recomputed from the new costs",
    "O limiar precisa ser recalculado com os novos custos", False,
    "There are no new costs, only a limit.",
    "Não há custos novos, só um limite."),
   ("There is no threshold to choose: sort and take the top 300",
    "Não há limiar a escolher: ordene e pegue os 300 primeiros", True,
    "Right. The score is then how many of those 300 lapse.",
    "Isso. A nota passa a ser quantos desses 300 se afastam."),
   ("The model must be retrained on 300 members",
    "O modelo precisa ser treinado de novo com 300 membros", False,
    "The budget changes how the output is used, not the model.",
    "O orçamento muda como a saída é usada, não o modelo."),
   ("Accuracy becomes the right score again",
    "A acurácia volta a ser a nota certa", False,
    "Nothing about a budget rescues accuracy.",
    "Nada num orçamento salva a acurácia.")])

Q("ex-cd4n9rx0", "scores-for-a-ranking", "easy",
  "What does a model that flags members at random score on average precision here?",
  "Quanto um modelo que aponta membros ao acaso tira em precisão média aqui?",
  [("0.5, like a coin on AUC",
    "0,5, como uma moeda na AUC", False,
    "That is AUC's coin; average precision's is the base rate.",
    "Essa é a moeda da AUC; a da precisão média é a taxa de base."),
   ("0.169, the share who lapse",
    "0,169, a fração que se afasta", True,
    "Right. Random flags hit lapsers at the rate they occur.",
    "Isso. Apontamentos ao acaso acertam afastados na taxa em que eles ocorrem."),
   ("Zero, since it learned nothing",
    "Zero, já que não aprendeu nada", False,
    "Random flags still hit some lapsing members.",
    "Apontamentos ao acaso ainda acertam alguns afastados."),
   ("0.522, the same as the model",
    "0,522, o mesmo que o modelo", False,
    "0.522 is the model's lift over 0.169.",
    "0,522 é o ganho do modelo sobre 0,169.")])

N("ex-5nktsb5e", "scores-for-a-ranking", "easy",
  "Of the top 300 members by probability, how many lapsed?",
  "Dos 300 primeiros membros pela probabilidade, quantos se afastaram?",
  195, 0, "members", "membros")

P("ex-t9w64n90", "scores-for-a-ranking", "medium",
  "Match each question to the score that answers it.",
  "Associe cada pergunta à nota que a responde.",
  [("Does the model order members well, in general?", "O modelo ordena bem os membros, em geral?",
    "ROC AUC", "ROC AUC"),
   ("How much better than chance at a rare outcome?", "Quão melhor que o acaso num desfecho raro?",
    "average precision", "precisão média"),
   ("How good is the list we can afford?", "Quão boa é a lista que podemos pagar?",
    "precision at k", "precisão em k")],
  [("accuracy", "acurácia")])

Q("ex-n8415vta", "scores-for-a-ranking", "hard",
  "Why is ROC AUC blind to how rare the positive class is?",
  "Por que a ROC AUC é cega para o quão rara é a classe positiva?",
  [("It only compares pairs of one lapsed and one staying member",
    "Ela só compara pares de um membro afastado e um que ficou", True,
    "Right. How many of each there are never enters the number.",
    "Isso. Quantos há de cada nunca entra no número."),
   ("It uses a threshold of 0.5",
    "Ela usa um limiar de 0,5", False,
    "It uses every threshold at once.",
    "Ela usa todos os limiares de uma vez."),
   ("It is computed on the training rows",
    "Ela é calculada nas linhas de treino", False,
    "ranking.py computes it on the test month.",
    "O ranking.py a calcula no mês de teste."),
   ("It ignores the members who stayed",
    "Ela ignora os membros que ficaram", False,
    "Every pair has one member who stayed.",
    "Todo par tem um membro que ficou.")])

Q("ex-w4f6nta5", "calibration", "easy",
  "What does it mean for the lapse model to be calibrated?",
  "O que significa o modelo de afastamento estar calibrado?",
  [("It ranks every lapsed member above every staying one",
    "Ele põe todo membro afastado acima de todo membro que ficou", False,
    "That is a perfect AUC, a different property.",
    "Isso é uma AUC perfeita, outra propriedade."),
   ("Its 0.3 really means a 30% chance",
    "O 0,3 dele quer mesmo dizer 30% de chance", True,
    "Right. Then its probabilities can be multiplied by costs.",
    "Isso. Então as probabilidades dele podem ser multiplicadas por custos."),
   ("It was retrained this month",
    "Ele foi treinado de novo este mês", False,
    "Freshness and calibration are different things.",
    "Atualidade e calibração são coisas diferentes."),
   ("Its threshold was set at the cost ratio",
    "O limiar dele foi posto na razão de custos", False,
    "That rule relies on calibration; it does not create it.",
    "Essa regra depende da calibração; não a cria.")])

N("ex-6gyxp3sm", "calibration", "easy",
  "Over all members on 30 November, what average probability of lapsing did the model give? Three decimals.",
  "Sobre todos os membros em 30 de novembro, que probabilidade média de afastamento o modelo deu? Três casas.",
  0.176, 0.0005, "", "")

Q("ex-8rvpdgda", "calibration", "hard",
  "If the share of members who lapse doubles next quarter, which score notices first, once the labels arrive?",
  "Se a fração de membros que se afastam dobrar no próximo trimestre, qual nota percebe primeiro, quando os rótulos chegarem?",
  [("ROC AUC, because the order of members changes",
    "A ROC AUC, porque a ordem dos membros muda", False,
    "The order can stay roughly right while every probability is wrong.",
    "A ordem pode continuar mais ou menos certa enquanto toda probabilidade erra."),
   ("Precision at 100, because the top hundred move",
    "A precisão em 100, porque os cem primeiros mudam", False,
    "The top of the list can stay full of lapsers.",
    "O topo da lista pode continuar cheio de afastados."),
   ("The calibration table",
    "A tabela de calibração", True,
    "Right. Said and happened drift apart in every band.",
    "Isso. O dito e o acontecido se afastam em toda faixa."),
   ("Accuracy, because more members lapse",
    "A acurácia, porque mais membros se afastam", False,
    "Accuracy mixes the change with everything else.",
    "A acurácia mistura a mudança com todo o resto.")])

Q("ex-7xgpvfdt", "regression-errors", "medium",
  "Why is RMSE about R$ 50 larger than MAE for the spend regression?",
  "Por que o RMSE é uns R$ 50 maior que o MAE na regressão de gasto?",
  [("A few members spent far more than predicted, and squaring weighs them heavily",
    "Uns poucos membros gastaram muito mais que o previsto, e elevar ao quadrado pesa muito sobre eles", True,
    "Right. R$ 1,637.20 against a prediction near R$ 300.",
    "Isso. R$ 1.637,20 contra uma predição perto de R$ 300."),
   ("RMSE is in cents and MAE in reais",
    "O RMSE está em centavos e o MAE em reais", False,
    "errors.py puts both in reais.",
    "O errors.py põe os dois em reais."),
   ("The regression overfits its training rows",
    "A regressão se sobreajusta às linhas de treino", False,
    "The baseline shows the same gap, and it fits nothing.",
    "A linha de base mostra a mesma diferença, e não ajusta nada."),
   ("Because MAE ignores members who spent nothing",
    "Porque o MAE ignora membros que não gastaram nada", False,
    "Those members count, with a label of 0.",
    "Esses membros contam, com rótulo 0.")])

P("ex-d66q99w4", "regression-errors", "medium",
  "Match each score to what it is sensitive to.",
  "Associe cada nota àquilo a que ela é sensível.",
  [("MAE", "MAE", "every error equally", "a todo erro igualmente"),
   ("RMSE", "RMSE", "large errors much more than small", "a erros grandes muito mais que pequenos"),
   ("median absolute error", "erro absoluto mediano", "almost nothing about the largest", "a quase nada sobre os maiores")],
  [("the share of members who lapse", "à fração de membros que se afastam")])

Q("ex-ea1qj14d", "regression-errors", "hard",
  "A shop runs out of a book when the forecast is too low, and that costs far more than a few extra copies. Which score fits?",
  "Uma loja fica sem um livro quando a previsão é baixa demais, e isso custa muito mais que alguns exemplares a mais. Que nota combina?",
  [("The median absolute error, because it describes the typical day",
    "O erro absoluto mediano, porque descreve o dia típico", False,
    "It ignores exactly the large misses that cost most.",
    "Ele ignora justamente os erros grandes que mais custam."),
   ("Accuracy",
    "Acurácia", False,
    "An amount has no accuracy; it is near or far.",
    "Uma quantia não tem acurácia; ela está perto ou longe."),
   ("RMSE",
    "RMSE", True,
    "Right. It weighs a large miss much more than a small one.",
    "Isso. Ele pesa um erro grande muito mais que um pequeno."),
   ("Average precision, because stock-outs are rare",
    "Precisão média, porque faltas de estoque são raras", False,
    "That scores a ranking of yes-or-no answers, not an amount.",
    "Essa nota julga uma ordenação de respostas sim ou não, não uma quantia.")])

Q("ex-sgsxghtb", "which-score", "medium",
  "What should be logged beside every score, according to the lesson?",
  "O que deve ser registrado ao lado de toda nota, segundo a lição?",
  [("The name of the person who computed it",
    "O nome de quem a calculou", False,
    "Useful, but it does not make the number comparable.",
    "Útil, mas não torna o número comparável."),
   ("Its baseline and the rows it was computed on",
    "A linha de base dela e as linhas em que foi calculada", True,
    "Right. AUC 0.790 means nothing without the month and the 530 of 3,130.",
    "Isso. AUC 0,790 não quer dizer nada sem o mês e os 530 de 3.130."),
   ("The threshold of 0.5",
    "O limiar de 0,5", False,
    "Several of the scores need no threshold at all.",
    "Várias das notas nem precisam de limiar."),
   ("Only the deciding score; the others are noise",
    "Só a nota que decide; as outras são ruído", False,
    "The others are watched, because calibration breaks quietly.",
    "As outras são acompanhadas, porque a calibração quebra em silêncio.")])

Q("ex-j57fv2dx", "which-score", "medium",
  "In this lesson's division of work, what does the platform guarantee about scores?",
  "Na divisão de trabalho desta lição, o que a plataforma garante sobre as notas?",
  [("That they are always above the previous model's",
    "Que elas sempre fiquem acima das do modelo anterior", False,
    "Nothing can guarantee that.",
    "Nada consegue garantir isso."),
   ("Computed the same way, on rows not used for choosing, and stored",
    "Calculadas do mesmo jeito, em linhas não usadas para escolher, e guardadas", True,
    "Right. The modeller chooses which scores make sense.",
    "Isso. Quem modela escolhe quais notas fazem sentido."),
   ("Which score decides the release",
    "Qual nota decide a publicação", False,
    "That is agreed with the people who use the model.",
    "Isso é combinado com quem usa o modelo."),
   ("That accuracy is never computed",
    "Que a acurácia nunca seja calculada", False,
    "It can be computed; it just must not decide.",
    "Ela pode ser calculada; só não pode decidir.")])

Q("ex-5r0fta8d", "drill", "hard",
  "Two lapse models: A has AUC 0.80 and is badly calibrated, B has AUC 0.78 and is calibrated. Marketing will set the threshold from costs. Which should ship?",
  "Dois modelos de afastamento: A tem AUC 0,80 e é mal calibrado, B tem AUC 0,78 e é calibrado. O marketing vai pôr o limiar pelos custos. Qual deve ir ao ar?",
  [("A, because AUC is the deciding score for a ranking",
    "A, porque AUC é a nota que decide para uma ordenação", False,
    "Here the use multiplies probabilities by costs, so they must be right.",
    "Aqui o uso multiplica probabilidades por custos, então elas precisam estar certas."),
   ("B",
    "B", True,
    "Right. A cost-based threshold needs believable probabilities; A would need recalibrating first.",
    "Isso. Um limiar por custos precisa de probabilidades críveis; A precisaria ser recalibrado antes."),
   ("Neither, since both are below 0.9",
    "Nenhum, já que os dois estão abaixo de 0,9", False,
    "No such bar exists.",
    "Essa barra não existe."),
   ("Whichever has the higher accuracy",
    "O que tiver a acurácia maior", False,
    "Accuracy is the trap this lesson is named for.",
    "A acurácia é a armadilha que dá nome a esta lição.")])

O("ex-ms9yfwvf", "drill", "medium",
  "Put the steps for choosing a threshold from costs in order.",
  "Coloque em ordem os passos para escolher um limiar pelos custos.",
  [("agree what a voucher costs and a kept member is worth", "combinar quanto custa um voucher e quanto vale um membro mantido"),
   ("check the probabilities are calibrated", "verificar se as probabilidades estão calibradas"),
   ("compute net value at each threshold", "calcular o valor líquido em cada limiar"),
   ("pick the threshold with the most value", "escolher o limiar de maior valor")])

M("ex-eav964e8", "drill", "medium",
  "Which of these scores need a threshold before they can be computed? Choose every one that applies.",
  "Quais destas notas precisam de um limiar antes de serem calculadas? Escolha todas as que se aplicam.",
  [("accuracy", "acurácia", True, "Right.", "Isso."),
   ("precision", "precisão", True, "Right.", "Isso."),
   ("recall", "revocação", True, "Right.", "Isso."),
   ("ROC AUC", "ROC AUC", False, "It judges every threshold at once.", "Ela julga todos os limiares de uma vez."),
   ("average precision", "precisão média", False, "It averages over every threshold.", "Ela tira a média sobre todos os limiares.")])
