# Lesson 5: the data engineer's role in the model lifecycle.
# python3 lab/tools/exb.py lab/exercises/l05.py lessons/le-d2vqq7mj -v

O("ex-2vsc6vdx", "the-lifecycle", "easy",
  "Put the stages of the model lifecycle in order, starting from data.",
  "Coloque as etapas do ciclo de vida do modelo em ordem, começando pelos dados.",
  [("features and labels", "atributos e rótulos"),
   ("training", "treino"),
   ("evaluation", "avaliação"),
   ("registration", "registro"),
   ("deployment", "publicação")])

Q("ex-qxqkpqmp", "the-lifecycle", "medium",
  "Which decision in the lifecycle belongs to the modeller rather than the platform?",
  "Qual decisão do ciclo de vida pertence a quem modela e não à plataforma?",
  [("Which algorithm to fit",
    "Qual algoritmo ajustar", True,
    "Right. The platform runs the fitting the same way every time.",
    "Isso. A plataforma roda o ajuste do mesmo jeito toda vez."),
   ("Where the trained model is stored, and under which version",
    "Onde o modelo treinado é guardado, e com qual versão", False,
    "Registration is the platform's.",
    "O registro é da plataforma."),
   ("How the model answers requests from the website",
    "Como o modelo responde aos pedidos do site", False,
    "Deployment is the platform's.",
    "A publicação é da plataforma."),
   ("How the tables land each night before features are built",
    "Como as tabelas chegam toda noite antes dos atributos serem montados", False,
    "That is data engineering before any model exists.",
    "Isso é engenharia de dados antes de qualquer modelo existir.")])

Q("ex-sssvz6x1", "the-lifecycle", "medium",
  "Where do model projects fail most often, according to the lesson?",
  "Onde projetos de modelo mais falham, segundo a lição?",
  [("In choosing the algorithm",
    "Na escolha do algoritmo", False,
    "Algorithms are the part libraries already solved.",
    "Algoritmos são a parte que as bibliotecas já resolveram."),
   ("A notebook model nobody rebuilds",
    "Um modelo de notebook que ninguém refaz", True,
    "Right. The person who made it moves on, and the data they gathered by hand goes with them.",
    "Isso. A pessoa que o fez muda de função, e os dados juntados à mão vão com ela."),
   ("In training, because it needs a graphics card",
    "No treino, porque precisa de placa de vídeo", False,
    "Every model in this course trains on a processor in seconds.",
    "Todo modelo deste curso treina num processador em segundos."),
   ("In evaluation, because scores are hard to compute",
    "Na avaliação, porque notas são difíceis de calcular", False,
    "They are one function call; agreeing which one matters is the hard part.",
    "São uma chamada de função; o difícil é combinar qual importa.")])

Q("ex-g9w3b9j3", "from-scripts-to-steps", "easy",
  "What does project.py's SHOP give every step?",
  "O que o SHOP do project.py dá a cada etapa?",
  [("A copy of the database for each step",
    "Uma cópia do banco para cada etapa", False,
    "It is a path, not a copy.",
    "É um caminho, não uma cópia."),
   ("Its full path, from any directory",
    "O caminho completo, de qualquer diretório", True,
    "Right. No more empty shop.db created by a run from the wrong place.",
    "Isso. Nada mais de shop.db vazio criado por uma execução do lugar errado."),
   ("A lock so two steps cannot read it at once",
    "Uma trava para duas etapas não lerem ao mesmo tempo", False,
    "Nothing in it locks anything.",
    "Nada nele trava coisa alguma."),
   ("The cutoff the step should use",
    "O corte que a etapa deve usar", False,
    "Cutoffs are arguments now, written in pipeline.sh.",
    "Cortes agora são argumentos, escritos no pipeline.sh.")])

M("ex-yxaggdmh", "from-scripts-to-steps", "medium",
  "Which problems of the earlier scripts does splitting into steps fix? Choose every one that applies.",
  "Quais problemas dos scripts anteriores a divisão em etapas corrige? Escolha todos os que se aplicam.",
  [("files found relative to wherever the program started", "arquivos achados relativos a onde o programa foi iniciado", True, "Right. project.py names them in full.", "Isso. O project.py os nomeia por inteiro."),
   ("dates hidden inside the code", "datas escondidas dentro do código", True, "Right. They are arguments now.", "Isso. Agora são argumentos."),
   ("nothing checking the rows", "nada verificando as linhas", True, "Right. validate.py does.", "Isso. O validate.py verifica."),
   ("a model that ranks badly", "um modelo que ordena mal", False, "Steps change how a model is made, not how good it is.", "Etapas mudam como um modelo é feito, não quão bom ele é.")])

Q("ex-txkeqet7", "building-the-dataset", "medium",
  "build_dataset.py refuses 2026-01-31. What does it compare to decide?",
  "O build_dataset.py recusa 2026-01-31. O que ele compara para decidir?",
  [("The cutoff with today's date on the computer",
    "O corte com a data de hoje no computador", False,
    "It reads the data, so a late load is caught too.",
    "Ele lê os dados, então uma carga atrasada também é pega."),
   ("The cutoff plus 90 days with the last day of purchases",
    "O corte mais 90 dias com o último dia de compras", True,
    "Right. 1 May against 28 February.",
    "Isso. 1º de maio contra 28 de fevereiro."),
   ("The number of members against 1,000",
    "O número de membros contra 1.000", False,
    "That check is validate.py's.",
    "Essa verificação é do validate.py."),
   ("The cutoff against the newest model's training date",
    "O corte contra a data de treino do modelo mais novo", False,
    "It knows nothing about models.",
    "Ele não sabe nada de modelos.")])

N("ex-ngm2rdge", "building-the-dataset", "easy",
  "How many members are in data/train.csv, as of 2025-08-31?",
  "Quantos membros há em data/train.csv, em 2025-08-31?",
  2863, 0, "members", "membros")

Q("ex-y8btegh6", "building-the-dataset", "hard",
  "Why does it matter that a refused step exits with status 1 rather than printing a warning and carrying on?",
  "Por que importa que uma etapa recusada saia com status 1 em vez de imprimir um aviso e seguir?",
  [("Status 1 deletes the files the step wrote",
    "O status 1 apaga os arquivos que a etapa gravou", False,
    "The step wrote nothing; the status itself deletes nothing.",
    "A etapa não gravou nada; o status em si não apaga nada."),
   ("It is how a pipeline sees a failure",
    "É como um pipeline enxerga uma falha", True,
    "Right. A pipeline knows a step failed only from its exit status, and with set -e the steps after it never run.",
    "Isso. Um pipeline só sabe que uma etapa falhou pelo status de saída, e com set -e as etapas seguintes nunca rodam."),
   ("Because Python cannot print to a terminal from a pipeline",
    "Porque o Python não consegue imprimir num terminal a partir de um pipeline", False,
    "It prints fine; a printed warning just stops nothing.",
    "Ele imprime normalmente; um aviso impresso só não para nada."),
   ("Warnings are hidden by the orchestrator",
    "Avisos são escondidos pelo orquestrador", False,
    "They may be logged; what stops the next task is the status.",
    "Eles podem ser registrados; o que para a próxima tarefa é o status.")])

P("ex-n1b15zy6", "a-data-contract", "medium",
  "Match each check in validate.py to what it would catch.",
  "Associe cada verificação do validate.py ao que ela pegaria.",
  [("one row per member", "uma linha por membro", "a join that fanned out", "uma junção que multiplicou linhas"),
   ("no negative numbers", "nenhum número negativo", "a column from today's table", "uma coluna da tabela de hoje"),
   ("5% to 35% lapsed", "5% a 35% afastados", "unfinished labels", "rótulos inacabados"),
   ("one cutoff per file", "um corte por arquivo", "two months concatenated", "dois meses concatenados")],
  [("a model that overfits", "um modelo sobreajustado")])

Q("ex-736tvcfw", "a-data-contract", "medium",
  "A contract check starts failing every night. What is the wrong first fix?",
  "Uma verificação do contrato começa a falhar toda noite. Qual é a primeira correção errada?",
  [("Find out what changed in the data",
    "Descobrir o que mudou nos dados", False,
    "That is the right first step.",
    "Esse é o primeiro passo certo."),
   ("Widen the range until the rows pass",
    "Alargar a faixa até as linhas passarem", True,
    "Right. It silences the one check that noticed.",
    "Isso. Silencia a única verificação que percebeu."),
   ("Ask the modeller whether the range still makes sense",
    "Perguntar a quem modela se a faixa ainda faz sentido", False,
    "That is a reasonable second step, once the cause is known.",
    "É um segundo passo razoável, uma vez conhecida a causa."),
   ("Read the rows the check refused",
    "Ler as linhas que a verificação recusou", False,
    "That is how the cause is found.",
    "É assim que a causa é achada.")])

N("ex-3rdznv77", "a-data-contract", "easy",
  "For how many members did validate.py report a negative recency in data/broken.csv?",
  "Para quantos membros o validate.py relatou recência negativa em data/broken.csv?",
  15, 0, "members", "membros")

Q("ex-42amkyt6", "training-as-a-step", "easy",
  "What does data_sha256 in the training record let you say about two models?",
  "O que o data_sha256 no registro de treino permite dizer sobre dois modelos?",
  [("That they will score the same on any test",
    "Que vão tirar a mesma nota em qualquer teste", False,
    "Same data is not same code or same settings.",
    "Mesmos dados não são mesmo código nem mesmos ajustes."),
   ("Same fingerprint, same training rows",
    "Mesma impressão digital, mesmas linhas de treino", True,
    "Right. Whatever the files were called.",
    "Isso. Seja qual for o nome dos arquivos."),
   ("Which version of features.py built them",
    "Qual versão do features.py os montou", False,
    "It names the data, not the code; lesson 7 adds the code.",
    "Ele nomeia os dados, não o código; a lição 7 acrescenta o código."),
   ("That they used the same scikit-learn",
    "Que usaram o mesmo scikit-learn", False,
    "That is another field of the record.",
    "Esse é outro campo do registro.")])

Q("ex-sg7czakw", "training-as-a-step", "medium",
  "Why does the record keep the scikit-learn version?",
  "Por que o registro guarda a versão do scikit-learn?",
  [("To bill the library's authors",
    "Para cobrar dos autores da biblioteca", False,
    "scikit-learn is free.",
    "O scikit-learn é gratuito."),
   ("It only loads reliably in that version",
    "Ele só carrega com segurança nessa versão", True,
    "Right. Upgrading the library is then a decision with a record.",
    "Isso. Atualizar a biblioteca passa a ser uma decisão com registro."),
   ("Newer versions train better models",
    "Versões mais novas treinam modelos melhores", False,
    "Not necessarily, and that is not why it is recorded.",
    "Não necessariamente, e não é por isso que é registrada."),
   ("joblib refuses to save without it",
    "O joblib se recusa a salvar sem ela", False,
    "joblib saves without being told.",
    "O joblib salva sem ser informado.")])

Q("ex-mg9pzwe0", "evaluating-as-a-step", "medium",
  "Why does evaluate.py load the model from disk instead of using the one train.py had in memory?",
  "Por que o evaluate.py carrega o modelo do disco em vez de usar o que o train.py tinha na memória?",
  [("Loading from disk is faster",
    "Carregar do disco é mais rápido", False,
    "Speed is not the reason.",
    "Velocidade não é o motivo."),
   ("It scores the file that would be deployed",
    "Ele pontua o arquivo que seria publicado", True,
    "Right. Not an object that existed only while training ran.",
    "Isso. Não um objeto que só existiu enquanto o treino rodava."),
   ("Python cannot pass a model between programs any other way",
    "O Python não consegue passar um modelo entre programas de outro jeito", False,
    "The point is which artefact gets scored, not how.",
    "O ponto é qual artefato é pontuado, não como."),
   ("The model in memory had seen the test rows",
    "O modelo na memória tinha visto as linhas de teste", False,
    "It had not; train.py never reads test.csv.",
    "Não tinha; o train.py nunca lê test.csv.")])

Q("ex-25a22a1m", "evaluating-as-a-step", "hard",
  "The pipeline's model scores 0.793 AUC and 190 in the top 300; lesson 4's scored 0.790 and 195. What should you conclude?",
  "O modelo do pipeline tira AUC 0,793 e 190 nos 300 primeiros; o da lição 4 tirou 0,790 e 195. O que concluir?",
  [("The pipeline made the model better",
    "O pipeline melhorou o modelo", False,
    "Three thousandths of AUC is noise here.",
    "Três milésimos de AUC é ruído aqui."),
   ("The pipeline made the model worse",
    "O pipeline piorou o modelo", False,
    "Five members in three hundred is noise too.",
    "Cinco membros em trezentos também é ruído."),
   ("Nothing: it is noise",
    "Nada: é ruído", True,
    "Right. Training on a different month moves scores this much; worth knowing before celebrating the next small change.",
    "Isso. Treinar com outro mês move as notas desse tanto; vale saber antes de comemorar a próxima pequena mudança."),
   ("That one of the two has a leak",
    "Que um dos dois tem um vazamento", False,
    "A leak shows as a score too good, not a tiny difference.",
    "Um vazamento aparece como nota boa demais, não como uma diferença mínima.")])

Q("ex-m1r7cjfx", "running-the-pipeline", "easy",
  "What does set -e do in pipeline.sh?",
  "O que o set -e faz no pipeline.sh?",
  [("Stops the script at the first command that fails",
    "Para o script no primeiro comando que falha", True,
    "Right. A refused dataset never reaches train.py.",
    "Isso. Um conjunto recusado nunca chega ao train.py."),
   ("Makes every command print what it runs",
    "Faz cada comando imprimir o que roda", False,
    "That is set -x.",
    "Isso é o set -x."),
   ("Runs the steps in parallel",
    "Roda as etapas em paralelo", False,
    "They run one after another.",
    "Elas rodam uma depois da outra."),
   ("Exports the environment to the Python steps",
    "Exporta o ambiente para as etapas em Python", False,
    "Exporting is a different command.",
    "Exportar é outro comando.")])

Q("ex-19gthkra", "running-the-pipeline", "medium",
  "What does an orchestrator such as Airflow add to pipeline.sh, and what does it leave unchanged?",
  "O que um orquestrador como o Airflow acrescenta ao pipeline.sh, e o que ele deixa igual?",
  [("It replaces the four steps with one task",
    "Ele substitui as quatro etapas por uma tarefa", False,
    "Each step stays a task of its own.",
    "Cada etapa continua sendo uma tarefa própria."),
   ("It rewrites the steps in its own language",
    "Ele reescreve as etapas na sua própria linguagem", False,
    "It runs the same programs.",
    "Ele roda os mesmos programas."),
   ("Retries, history and alerts; same steps",
    "Tentativas, histórico, alertas; etapas iguais", True,
    "Right. A file in and a file out is exactly the shape it expects.",
    "Isso. Um arquivo de entrada e um de saída é exatamente a forma que ele espera."),
   ("It makes the dataset step unnecessary",
    "Ele torna a etapa do conjunto de dados desnecessária", False,
    "Someone still has to build the examples.",
    "Alguém ainda precisa montar os exemplos.")])

Q("ex-msjm2vtc", "training-serving-skew", "easy",
  "What is training-serving skew?",
  "O que é a diferença entre treino e serviço?",
  [("A model served faster than it was trained",
    "Um modelo servido mais rápido do que foi treinado", False,
    "Speed has nothing to do with it.",
    "Velocidade não tem nada a ver."),
   ("The same feature, computed two ways",
    "O mesmo atributo, calculado de dois jeitos", True,
    "Right. The model gets numbers that mean something else.",
    "Isso. O modelo recebe números que significam outra coisa."),
   ("A test set from a later month than the training set",
    "Um conjunto de teste de um mês posterior ao de treino", False,
    "That is the honest split, not a skew.",
    "Essa é a divisão honesta, não uma diferença."),
   ("Training on more members than are served",
    "Treinar com mais membros do que são servidos", False,
    "Numbers of members are not the issue.",
    "O número de membros não é a questão.")])

N("ex-2v2a3vt3", "training-serving-skew", "easy",
  "With the website's features, how many members' probabilities moved by more than 0.1?",
  "Com os atributos do site, quantos membros tiveram a probabilidade mexida em mais de 0,1?",
  160, 0, "members", "membros")

Q("ex-pj9dtrqr", "training-serving-skew", "hard",
  "Why did nothing raise an error when the website sent spend in reais?",
  "Por que nada levantou erro quando o site mandou o gasto em reais?",
  [("scikit-learn ignores columns it does not recognise",
    "O scikit-learn ignora colunas que não reconhece", False,
    "It recognised them: the names were right.",
    "Ele as reconheceu: os nomes estavam certos."),
   ("Valid numbers, right names",
    "Números válidos, nomes certos", True,
    "Right. Only the meaning changed, and no type check sees meaning.",
    "Isso. Só o significado mudou, e nenhuma verificação de tipo vê significado."),
   ("The model had been trained on reais as well",
    "O modelo também tinha sido treinado em reais", False,
    "It learned cents; that is the skew.",
    "Ele aprendeu centavos; essa é a diferença."),
   ("Because AUC only fell to 0.770",
    "Porque a AUC só caiu para 0,770", False,
    "A score falling raises no error either.",
    "Uma nota caindo também não levanta erro.")])

Q("ex-tfk3a6t5", "training-serving-skew", "medium",
  "What is the defence the lesson recommends against skew?",
  "Qual a defesa que a lição recomenda contra essa diferença?",
  [("Asking every team to be more careful with units",
    "Pedir a todo time mais cuidado com unidades", False,
    "Everybody was careful; care is not a mechanism.",
    "Todo mundo foi cuidadoso; cuidado não é um mecanismo."),
   ("One implementation of the features, used by training and serving",
    "Uma implementação só dos atributos, usada pelo treino e pelo serviço", True,
    "Right. Lesson 6 turns it into a feature store.",
    "Isso. A lição 6 a transforma numa feature store."),
   ("Retraining the model on the website's features",
    "Treinar o modelo de novo com os atributos do site", False,
    "Then the batch scores would be skewed instead.",
    "Aí as notas em lote é que ficariam diferentes."),
   ("Rounding every feature to whole numbers",
    "Arredondar todo atributo para inteiro", False,
    "Rounding does not convert reais into cents.",
    "Arredondar não converte reais em centavos.")])

Q("ex-zpndgy65", "the-handoff", "medium",
  "Why ask for the label defined in code rather than in a sentence?",
  "Por que pedir o rótulo definido em código e não numa frase?",
  [("Sentences cannot be stored in Git",
    "Frases não podem ser guardadas no Git", False,
    "They can; the problem is reimplementing them.",
    "Podem; o problema é reimplementá-las."),
   ("A sentence is two implementations waiting to differ",
    "Uma frase são duas implementações esperando para divergir", True,
    "Right. Is lapsed 90 days or three months? The code says.",
    "Isso. Afastado é 90 dias ou três meses? O código diz."),
   ("Code runs faster than a sentence",
    "Código roda mais rápido que uma frase", False,
    "A sentence does not run at all.",
    "Uma frase nem roda."),
   ("Modellers do not write sentences",
    "Quem modela não escreve frases", False,
    "They do; the point is which one is authoritative.",
    "Escreve; o ponto é qual delas vale.")])

M("ex-d4gh7c76", "the-handoff", "medium",
  "Which of these should come with a model before a data engineer takes it on? Choose every one that applies.",
  "Quais destes devem vir com um modelo antes de um engenheiro de dados assumi-lo? Escolha todos os que se aplicam.",
  [("the label's maturity", "o tempo de maturação do rótulo", True, "Right.", "Isso."),
   ("the deciding score and its baseline", "a nota que decide e a sua linha de base", True, "Right.", "Isso."),
   ("who uses the output, and how", "quem usa a saída, e como", True, "Right.", "Isso."),
   ("the modeller's notebook, with its outputs", "o notebook de quem modela, com as saídas", False,
    "The definitions belong in code that runs; a notebook's outputs are a record of one run.",
    "As definições pertencem a código que roda; as saídas de um notebook são o registro de uma execução.")])

Q("ex-fjc0nnw9", "drill", "hard",
  "The nightly training run starts producing a model whose said is 0.31 while the test's lapse share is 0.17. Which step should have stopped it?",
  "O treino noturno começa a produzir um modelo cujo said é 0,31 enquanto a fração afastada do teste é 0,17. Qual etapa deveria tê-lo parado?",
  [("evaluate.py, which should refuse low AUC",
    "O evaluate.py, que deveria recusar AUC baixa", False,
    "A calibration problem can come with a fine AUC.",
    "Um problema de calibração pode vir com uma AUC boa."),
   ("build_dataset.py or validate.py",
    "O build_dataset.py ou o validate.py", True,
    "Right. A model saying 0.31 learned a lapse rate near that: look for unfinished labels.",
    "Isso. Um modelo que diz 0,31 aprendeu uma taxa perto disso: procure rótulos inacabados."),
   ("train.py, which should use more iterations",
    "O train.py, que deveria usar mais iterações", False,
    "More iterations fit the same wrong labels more closely.",
    "Mais iterações ajustam os mesmos rótulos errados com mais precisão."),
   ("pipeline.sh, which should run less often",
    "O pipeline.sh, que deveria rodar menos vezes", False,
    "How often it runs does not decide what it learns.",
    "Quantas vezes roda não decide o que ele aprende.")])

O("ex-0barg4a4", "drill", "medium",
  "Put the steps of pipeline.sh in the order it runs them.",
  "Coloque as etapas do pipeline.sh na ordem em que ele as roda.",
  [("build_dataset.py", "build_dataset.py"),
   ("validate.py", "validate.py"),
   ("train.py", "train.py"),
   ("evaluate.py", "evaluate.py")])

C("ex-t4s4nba3", "drill", "medium",
  "A model is a data product whose output is a guess about the ___.",
  "Um modelo é um produto de dados cuja saída é um palpite sobre o ___.",
  ["future"], ["futuro"])
