# Lesson 6: feature stores and reproducible features.
# python3 lab/tools/exb.py lab/exercises/l06.py lessons/le-9amgywjz -v

Q("ex-a3gjqs7w", "two-problems", "easy",
  "What single cause do lesson 3's summary-table leak and lesson 5's skew share?",
  "Que causa única o vazamento da tabela de resumo da lição 3 e a diferença da lição 5 compartilham?",
  [("Both used logistic regression",
    "Os dois usaram regressão logística", False,
    "Any algorithm would have failed the same way.",
    "Qualquer algoritmo teria falhado do mesmo jeito."),
   ("A feature computed badly",
    "Um atributo mal calculado", True,
    "Right. Computed in two places, or for the wrong moment; a feature store is built to prevent both.",
    "Isso. Calculado em dois lugares, ou para o momento errado; uma feature store é feita para impedir as duas coisas."),
   ("Both trained on too few members to be stable",
    "Os dois treinaram com membros de menos para serem estáveis", False,
    "Both had thousands of rows; size was not the issue.",
    "Os dois tinham milhares de linhas; tamanho não era a questão."),
   ("Both forgot to scale the numeric columns",
    "Os dois esqueceram de pôr as colunas numéricas em escala", False,
    "The pipeline scaled them both times.",
    "O pipeline pôs em escala nas duas vezes.")])

P("ex-qj82pv9a", "two-problems", "easy",
  "Match each face of the feature store to what it answers.",
  "Associe cada face da feature store ao que ela responde.",
  [("offline store", "armazenamento offline", "what members looked like on past days", "como os membros estavam em dias passados"),
   ("online store", "armazenamento online", "what one member looks like now", "como um membro está agora")],
  [("which members will lapse next month", "quais membros vão se afastar no mês que vem"),
   ("what the label of each member is", "qual é o rótulo de cada membro")])

Q("ex-twr8gqk9", "two-problems", "medium",
  "Does a feature store compute the features?",
  "Uma feature store calcula os atributos?",
  [("Yes, it replaces features.py",
    "Sim, ela substitui o features.py", False,
    "features.py still does the computing.",
    "O features.py continua fazendo o cálculo."),
   ("No: it runs, keeps and serves the code's output",
    "Não: ela roda, guarda e serve a saída do código", True,
    "Right. The computation stays in one piece of code.",
    "Isso. O cálculo fica num código só."),
   ("Only for the online store",
    "Só para o armazenamento online", False,
    "The online store is built from the offline one; neither computes.",
    "O online é montado a partir do offline; nenhum dos dois calcula."),
   ("Only when the model asks for a feature it has never seen",
    "Só quando o modelo pede um atributo que nunca viu", False,
    "Nothing is computed on demand here.",
    "Nada é calculado sob demanda aqui.")])

P("ex-q9x663jm", "the-parts", "medium",
  "Match each part of a feature store to what it is in this lesson.",
  "Associe cada parte de uma feature store ao que ela é nesta lição.",
  [("entity", "entidade", "a member, member_id", "um membro, member_id"),
   ("event timestamp", "carimbo de tempo do evento", "as_of, the snapshot day", "as_of, o dia da fotografia"),
   ("materialisation", "materialização", "snapshot and backfill", "snapshot e backfill"),
   ("time to live", "tempo de vida", "MAX_AGE, seven days", "MAX_AGE, sete dias")],
  [("lapsed, the label", "lapsed, o rótulo")])

Q("ex-2wfs7aw1", "the-parts", "medium",
  "Why does the event timestamp matter more than anything else in the store?",
  "Por que o carimbo de tempo do evento importa mais que qualquer outra coisa no armazenamento?",
  [("It makes the online store faster",
    "Ele torna o armazenamento online mais rápido", False,
    "Speed comes from the index, not the timestamp.",
    "A velocidade vem do índice, não do carimbo."),
   ("It makes the table a history",
    "Ele torna a tabela uma história", True,
    "Right. Without it the store is lesson 3's summary table.",
    "Isso. Sem ele o armazenamento é a tabela de resumo da lição 3."),
   ("It is the key the model is trained on",
    "Ele é a chave com que o modelo é treinado", False,
    "The model never sees a date.",
    "O modelo nunca vê uma data."),
   ("It decides which members are active",
    "Ele decide quais membros estão ativos", False,
    "features.py decides that, as of each day.",
    "O features.py decide isso, em relação a cada dia.")])

Q("ex-ehydf95j", "the-store", "medium",
  "Why does snapshot drop the lapsed column before writing?",
  "Por que o snapshot descarta a coluna lapsed antes de gravar?",
  [("It is too large to store",
    "Ela é grande demais para guardar", False,
    "It is one small number per row.",
    "É um número pequeno por linha."),
   ("It is learned after the day",
    "Ele é descoberto depois do dia", True,
    "Right. The store keeps what was known on the day; a label kept beside features is a leak waiting for a query.",
    "Isso. O armazenamento guarda o que se sabia no dia; um rótulo ao lado dos atributos é um vazamento esperando uma consulta."),
   ("SQLite cannot store booleans",
    "O SQLite não guarda booleanos", False,
    "It stores 0 and 1 happily.",
    "Ele guarda 0 e 1 sem problema."),
   ("The online store has no room for it",
    "O armazenamento online não tem espaço para ela", False,
    "Room is not the reason.",
    "Espaço não é o motivo.")])

Q("ex-02a5ppaf", "the-store", "hard",
  "historical uses merge_asof with direction=\"backward\" and a tolerance of seven days. What would direction=\"nearest\" do?",
  "O historical usa merge_asof com direction=\"backward\" e tolerância de sete dias. O que direction=\"nearest\" faria?",
  [("Nothing different, since snapshots are weekly",
    "Nada diferente, já que as fotografias são semanais", False,
    "A nearer snapshot after the moment would now be chosen.",
    "Uma fotografia mais próxima depois do momento passaria a ser escolhida."),
   ("Pick later snapshots too",
    "Pegar fotografias posteriores também", True,
    "Right. A Thursday question would get the following Sunday's values.",
    "Isso. Uma pergunta de quinta receberia os valores do domingo seguinte."),
   ("Make the join faster",
    "Deixar a junção mais rápida", False,
    "Speed is not what direction changes.",
    "Velocidade não é o que a direção muda."),
   ("Drop every member who has no snapshot that day",
    "Descartar todo membro sem fotografia naquele dia", False,
    "It would find more matches, not fewer.",
    "Ela acharia mais correspondências, não menos.")])

N("ex-mbtmr6gc", "filling-it", "easy",
  "How many weekly snapshots did the backfill from 2025-06-01 to 2026-02-22 take?",
  "Quantas fotografias semanais o backfill de 2025-06-01 a 2026-02-22 tirou?",
  39, 0, "snapshots", "fotografias")

Q("ex-xrgsk9r3", "filling-it", "medium",
  "Why is a backfill only correct because features.py computes as of its cutoff?",
  "Por que um backfill só está certo porque o features.py calcula em relação ao corte?",
  [("Because the backfill runs faster that way",
    "Porque o backfill roda mais rápido assim", False,
    "Correctness, not speed, is the point.",
    "O ponto é correção, não velocidade."),
   ("So the past is not refilled from today",
    "Para o passado não ser preenchido com hoje", True,
    "Right. From a summary table, the past would be filled with today's values.",
    "Isso. A partir de uma tabela de resumo, o passado seria enchido com os valores de hoje."),
   ("Because the offline store refuses rows from the past",
    "Porque o armazenamento offline recusa linhas do passado", False,
    "It accepts any day it is given.",
    "Ele aceita qualquer dia que receber."),
   ("Because labels are computed during the backfill",
    "Porque os rótulos são calculados durante o backfill", False,
    "Labels are dropped before anything is stored.",
    "Os rótulos são descartados antes de qualquer gravação.")])

Q("ex-qyymsyb2", "filling-it", "hard",
  "A team wants training rows for any day of the past, not only Sundays. What does that cost?",
  "Um time quer linhas de treino para qualquer dia do passado, não só domingos. Quanto isso custa?",
  [("Nothing, merge_asof already handles any day",
    "Nada, o merge_asof já trata qualquer dia", False,
    "It handles any day, with up to six days of staleness.",
    "Ele trata qualquer dia, com até seis dias de atraso."),
   ("Seven times the rows",
    "Sete vezes as linhas", True,
    "Right. Cadence is how stale a training row may be, bought with storage.",
    "Isso. A cadência é quão velha uma linha de treino pode ser, paga com armazenamento."),
   ("A different algorithm for the lapse model",
    "Outro algoritmo para o modelo de afastamento", False,
    "The model is unaffected.",
    "O modelo não é afetado."),
   ("Dropping the online store",
    "Abrir mão do armazenamento online", False,
    "The two are independent.",
    "Os dois são independentes.")])

Q("ex-7p5spesy", "as-of-a-moment", "easy",
  "Asked about member 2 on Thursday 27 November, which snapshot answers?",
  "Perguntado sobre o membro 2 na quinta, 27 de novembro, qual fotografia responde?",
  [("Sunday 30 November, the nearest",
    "O domingo, 30 de novembro, a mais próxima", False,
    "That is after the moment, so it is never used.",
    "Ela é posterior ao momento, então nunca é usada."),
   ("Sunday 23 November",
    "O domingo, 23 de novembro", True,
    "Right. The newest on or before the moment, four days stale.",
    "Isso. A mais nova até o momento, com quatro dias de atraso."),
   ("Saturday 28 February, the newest in the store",
    "O sábado, 28 de fevereiro, a mais nova do armazenamento", False,
    "That is the summary-table mistake.",
    "Esse é o erro da tabela de resumo."),
   ("None: there is no snapshot on that day",
    "Nenhuma: não há fotografia naquele dia", False,
    "The as-of join takes the latest before it.",
    "A junção pega a mais recente antes dele.")])

N("ex-jahvezc2", "as-of-a-moment", "easy",
  "What recency did the store give for member 2 as of 2025-11-27?",
  "Que recência o armazenamento deu ao membro 2 em 2025-11-27?",
  15, 0, "days", "dias")

Q("ex-x2mvea40", "as-of-a-moment", "medium",
  "How is the staleness on the Thursday different from a leak?",
  "Em que o atraso da quinta difere de um vazamento?",
  [("It is known, and bounded by MAX_AGE",
    "Ele é conhecido, e limitado pelo MAX_AGE", True,
    "Right. At most six days, written as MAX_AGE; a leak has no bound and no name.",
    "Isso. No máximo seis dias, escrito como MAX_AGE; um vazamento não tem limite nem nome."),
   ("It is not different; both read the wrong day",
    "Não difere; os dois leem o dia errado", False,
    "Staleness reads an earlier day, which was knowable then.",
    "O atraso lê um dia anterior, que era conhecível na época."),
   ("Staleness only happens online",
    "Atraso só acontece no online", False,
    "It happened here in a historical join.",
    "Ele aconteceu aqui numa junção histórica."),
   ("A leak is always smaller",
    "Um vazamento é sempre menor", False,
    "Lesson 3's was large enough to take AUC to 0.994.",
    "O da lição 3 foi grande o bastante para levar a AUC a 0,994.")])

Q("ex-86yyepwt", "the-online-store", "medium",
  "Why does online() leave out 466 members?",
  "Por que o online() deixa 466 membros de fora?",
  [("They were never active",
    "Eles nunca estiveram ativos", False,
    "They were, on some Sunday since June.",
    "Estiveram, em algum domingo desde junho."),
   ("Their newest row is too old",
    "A linha mais nova é velha demais", True,
    "Right. Served, it would describe a member who is gone as if they visited yesterday.",
    "Isso. Servida, descreveria um membro que foi embora como se tivesse visitado ontem."),
   ("They lapsed, so their label excludes them",
    "Eles se afastaram, então o rótulo os exclui", False,
    "The store holds no labels at all.",
    "O armazenamento não guarda rótulo nenhum."),
   ("SQLite has a limit on rows per table",
    "O SQLite tem um limite de linhas por tabela", False,
    "Not one this store comes near.",
    "Nenhum de que este armazenamento chegue perto.")])

N("ex-jzq19tr1", "the-online-store", "easy",
  "How many members did the online store keep on 28 February?",
  "Quantos membros o armazenamento online manteve em 28 de fevereiro?",
  3372, 0, "members", "membros")

Q("ex-ehd1g5vd", "the-online-store", "hard",
  "get(8) returns None. What should the scoring service do?",
  "get(8) devolve None. O que o serviço de pontuação deve fazer?",
  [("Whatever the platform decided in advance and wrote down",
    "O que a plataforma decidiu antes e deixou escrito", True,
    "Right. Refuse, use defaults or fall back to a rule: each is defensible if it is chosen.",
    "Isso. Recusar, usar valores padrão ou cair para uma regra: cada uma é defensável se for escolhida."),
   ("Compute member 8's features from the purchases table on the spot",
    "Calcular na hora os atributos do membro 8 a partir das compras", False,
    "That is a second implementation, lesson 5's skew.",
    "Isso é uma segunda implementação, a diferença da lição 5."),
   ("Use member 8's last row from the offline store, however old",
    "Usar a última linha do membro 8 do offline, por mais velha que seja", False,
    "That serves a stale member as if current.",
    "Isso serve um membro velho como se fosse atual."),
   ("Crash, so somebody notices",
    "Quebrar, para alguém perceber", False,
    "A crash on every forgotten member is not a decision.",
    "Quebrar em todo membro esquecido não é uma decisão.")])

Q("ex-vqv2cygm", "asking-for-one", "medium",
  "Why is features.build a poor way to answer for one member in a web request?",
  "Por que o features.build é um jeito ruim de responder sobre um membro numa requisição web?",
  [("It computes all of them each time",
    "Ele calcula todos eles a cada vez", True,
    "Right. It computes every active member to answer one, because it was written for training.",
    "Isso. Ele calcula todos os membros ativos para responder sobre um, porque foi escrito para o treino."),
   ("It returns the label as well",
    "Ele devolve o rótulo também", False,
    "True, but the problem in a request is time.",
    "É verdade, mas o problema numa requisição é tempo."),
   ("It cannot read SQLite from a web server",
    "Ele não lê SQLite de um servidor web", False,
    "It can; it is just slow for one member.",
    "Lê; só é lento para um membro."),
   ("It uses a different scaler",
    "Ele usa outro scaler", False,
    "Scaling is inside the model, not in features.build.",
    "A escala fica dentro do modelo, não no features.build.")])

Q("ex-btj6snbt", "asking-for-one", "hard",
  "lookup.py prints 0.17 ms on one run and 0.15 ms on another. What should a reader take from the numbers?",
  "O lookup.py imprime 0,17 ms numa rodada e 0,15 ms em outra. O que um leitor deve tirar dos números?",
  [("That the online store got faster",
    "Que o armazenamento online ficou mais rápido", False,
    "Run-to-run noise, not a change.",
    "Ruído de uma rodada para outra, não uma mudança."),
   ("The gap of two or three orders of magnitude",
    "A distância de duas ou três ordens de grandeza", True,
    "Right. The digits move; the gap between the two ways does not.",
    "Isso. Os dígitos mudam; a distância entre os dois jeitos não."),
   ("That SQLite is the right online store for any size",
    "Que o SQLite é o armazenamento online certo para qualquer tamanho", False,
    "At a hundred times the members, other things change.",
    "Com cem vezes os membros, outras coisas mudam."),
   ("That the timing is wrong, since it changed",
    "Que a medição está errada, já que mudou", False,
    "Timings always vary a little; that is not an error.",
    "Medições variam um pouco; isso não é um erro.")])

Q("ex-pmbkxcfz", "reproducible", "easy",
  "What does reproduce.py's True show?",
  "O que o True do reproduce.py mostra?",
  [("The store matches features.py",
    "O armazenamento bate com o features.py", True,
    "Right. Same rows, then same model and the same 0.793.",
    "Isso. Mesmas linhas, depois mesmo modelo e o mesmo 0,793."),
   ("The model's predictions are correct",
    "As predições do modelo estão certas", False,
    "It compares features, not predictions.",
    "Ele compara atributos, não predições."),
   ("The online store is up to date",
    "O armazenamento online está atualizado", False,
    "The comparison uses the offline store.",
    "A comparação usa o offline."),
   ("No member lapsed",
    "Nenhum membro se afastou", False,
    "530 did.",
    "530 se afastaram.")])

N("ex-yb1dvf43", "reproducible", "medium",
  "What test AUC did the model trained on the latest values reach?",
  "Que AUC de teste o modelo treinado com os valores mais novos atingiu?",
  0.645, 0, "", "")

Q("ex-00bw9g8f", "reproducible", "medium",
  "Joining 31 August labels to the online store lost 327 members. Why?",
  "Juntar os rótulos de 31 de agosto ao armazenamento online perdeu 327 membros. Por quê?",
  [("They are not active tonight",
    "Eles não estão ativos hoje", True,
    "Right. The online store had nothing for them, and the shortcut also mixed February's features with August's outcomes.",
    "Isso. O online não tinha nada para eles, e o atalho também misturou atributos de fevereiro com desfechos de agosto."),
   ("Their labels were unfinished",
    "Os rótulos deles estavam inacabados", False,
    "31 August's labels closed in November.",
    "Os rótulos de 31 de agosto fecharam em novembro."),
   ("They had duplicate rows",
    "Eles tinham linhas duplicadas", False,
    "The online store has one row per member.",
    "O online tem uma linha por membro."),
   ("The merge was an inner join by mistake on the cutoff",
    "A junção foi por engano pelo corte", False,
    "It joined on member_id only.",
    "Ela juntou só pelo member_id.")])

Q("ex-8dyb7z9y", "build-or-adopt", "medium",
  "Which is the signal the lesson says to watch for before adopting a feature store?",
  "Qual o sinal que a lição diz para vigiar antes de adotar uma feature store?",
  [("A model scoring below 0.8",
    "Um modelo tirando menos de 0,8", False,
    "Score has nothing to do with it.",
    "A nota não tem nada a ver."),
   ("Two teams computing the same feature in two places",
    "Dois times calculando o mesmo atributo em dois lugares", True,
    "Right. It is lesson 5's skew arriving through the organisation.",
    "Isso. É a diferença da lição 5 chegando pela organização."),
   ("The offline store passing ten megabytes",
    "O armazenamento offline passar de dez megabytes", False,
    "Size alone is no reason.",
    "Só o tamanho não é motivo."),
   ("A new version of scikit-learn",
    "Uma versão nova do scikit-learn", False,
    "Libraries change; that is not this decision.",
    "Bibliotecas mudam; essa não é esta decisão.")])

M("ex-kzsnsvdk", "build-or-adopt", "medium",
  "What does a product such as Feast add over featurestore.py? Choose every one that applies.",
  "O que um produto como o Feast acrescenta ao featurestore.py? Escolha todos os que se aplicam.",
  [("a registry of feature views with owners", "um registro de visões de atributos com donos", True, "Right.", "Isso."),
   ("scheduled materialisation with alerts", "materialização agendada com alertas", True, "Right.", "Isso."),
   ("freshness monitoring", "monitoramento de atualidade", True, "Right.", "Isso."),
   ("the point-in-time join itself", "a própria junção no ponto do tempo", False,
    "featurestore.py already does that; the idea is the same.", "O featurestore.py já faz isso; a ideia é a mesma.")])

O("ex-a0m4yn1g", "drill", "medium",
  "Put a night at Ponto Final in order, from the shop's load to a service answering.",
  "Coloque uma noite na Ponto Final em ordem, da carga da loja até um serviço respondendo.",
  [("the purchases table finishes loading", "a tabela de compras termina de carregar"),
   ("snapshot writes tonight's features offline", "o snapshot grava os atributos de hoje no offline"),
   ("online rebuilds the latest values", "o online reconstrói os valores mais novos"),
   ("a service calls get for one member", "um serviço chama get para um membro")])

Q("ex-geeecg8f", "drill", "hard",
  "A colleague builds a training set by joining labels to a nightly members summary with no as_of column. Which part of a feature store would have prevented it?",
  "Um colega monta um conjunto de treino juntando rótulos a um resumo noturno de membros sem coluna as_of. Que parte de uma feature store teria impedido isso?",
  [("The online store's index",
    "O índice do armazenamento online", False,
    "Indexes make it fast, not correct.",
    "Índices o deixam rápido, não correto."),
   ("Event timestamps and the point-in-time join",
    "Os carimbos de tempo e a junção no ponto do tempo", True,
    "Right. Without them, today's values meet last year's labels.",
    "Isso. Sem eles, os valores de hoje encontram os rótulos do ano passado."),
   ("The time to live",
    "O tempo de vida", False,
    "It would hide stale rows, not stop the future joining the past.",
    "Ele esconderia linhas velhas, não impediria o futuro de se juntar ao passado."),
   ("A registry of owners",
    "Um registro de donos", False,
    "Knowing the owner does not change the join.",
    "Saber o dono não muda a junção.")])
