#!/usr/bin/env bash
# The terminal sessions quoted in lesson 12 of warehouse-modeling, as a script
# that produces them.
#
# THE SCRIPT IS THE SOURCE AND ITS OUTPUT IS NOT COMMITTED. Every transcript in
# this lesson was copied from running it.
#
#   sudo bash ../../lab.sh up        # once
#   sudo LAB_SH=../../lab.sh bash captures.sh
#
# STAGED, and not typed in the lesson: ~/wh/wh.duckdb and ~/wh/extract, the
# warehouse and the extract of lessons 2 to 5, made here by `lab.sh
# warehouse`. The descriptions, the classification and the two programs are
# the course's own files, in lab/catalog/, copied into ~/wh by `put` and shown
# in the lesson as they are. Customer 19 and every name in the data are
# generated by lab/generate.py; nobody real is in them.
#
# Recorded on Ubuntu 24.04, DuckDB 1.5.6, Python 3.12 with the duckdb module
# 1.5.6, TZ=America/Sao_Paulo, on 2026-10-06.
set -uo pipefail
export TZ=America/Sao_Paulo LC_ALL=C.UTF-8
LAB_SH=${LAB_SH:-../../lab.sh}
COURSE=$(cd "$(dirname "$LAB_SH")" && pwd)
lab() { bash "$LAB_SH" "$@"; }
on() { printf 'ana@lab:~/wh$ %s\n' "$*"; timeout 120 bash "$LAB_SH" exec "$*" 2>&1 || true; }
put() { lab exec "cat > '$1'"; }
code() { printf '##### %s\n' "$1"; lab exec "cat '$2'"; }
block() { printf '##### %s\n' "$1"; }
exec 9>/var/tmp/wh-capture.lock; flock 9
lab reset >/dev/null
lab warehouse >/dev/null
for f in comments.sql classification.csv check_docs.py dictionary.py; do
  put $f < "$COURSE/lab/catalog/$f"
done

block one-comment
on "duckdb wh.duckdb -c \"COMMENT ON COLUMN fact_sales.net_cents IS 'Net sales: gross_cents minus discount_cents, in centavos, without shipping. Additive.'\""
on "duckdb -readonly wh.duckdb -c \"SELECT column_name, comment FROM duckdb_columns() WHERE table_name = 'fact_sales' AND column_name LIKE '%cents'\""

code check-py check_docs.py
block before
on 'python3 check_docs.py; echo "exit status $?"'

printf '##### comments-head\n'
lab exec "sed -n 1,9p comments.sql"
block comments
on 'grep -c "^COMMENT ON" comments.sql'
on 'duckdb wh.duckdb < comments.sql'
on 'python3 check_docs.py; echo "exit status $?"'

code dictionary-py dictionary.py
block dictionary
on 'python3 dictionary.py > dictionary.md && wc -l dictionary.md'
on "awk '/^## fact_sales/ {p = 1} /^## / && !/fact_sales/ {p = 0} p' dictionary.md"

block drift
on "duckdb wh.duckdb -c \"ALTER TABLE fact_sales ADD COLUMN gift_wrap BOOLEAN DEFAULT false\""
on 'python3 check_docs.py; echo "exit status $?"'

printf '##### classification-head\n'
lab exec "head -6 classification.csv"
block personal
on "duckdb -c \"SELECT class, count(*) AS columns FROM read_csv('classification.csv') GROUP BY class ORDER BY columns DESC\""
on "duckdb -c \"SELECT table_name, string_agg(column_name, ', ') AS personal FROM read_csv('classification.csv') WHERE class = 'personal' GROUP BY table_name ORDER BY table_name\""

put erase.sql <<'SQL'
-- Customer 19 asked to be erased. Every version loses what identifies the
-- person; the keys stay, so the sales still add up and point at nobody.
UPDATE dim_customer
SET customer_id = NULL, name = 'Erased on request', tier = 'erased',
    city = 'Erased', state = '--'
WHERE customer_id = 19;
SQL
block erase
on "duckdb -readonly wh.duckdb -c \"SELECT customer_key, customer_id, name, tier, city, state, valid_from FROM dim_customer WHERE customer_id = 19\""
on "duckdb -readonly wh.duckdb -c \"SELECT count(*) AS lines, sum(net_cents) AS net_cents FROM fact_sales WHERE customer_key IN (SELECT customer_key FROM dim_customer WHERE customer_id = 19)\""
code erase-sql erase.sql
block erased
on 'duckdb wh.duckdb < erase.sql'
on "duckdb -readonly wh.duckdb -c \"SELECT customer_key, customer_id, name, tier, city, state, valid_from FROM dim_customer WHERE customer_key IN (SELECT DISTINCT customer_key FROM dim_customer WHERE name = 'Erased on request')\""
on "duckdb -readonly wh.duckdb -c \"SELECT sum(net_cents) AS net_cents FROM fact_sales\""
