from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
Q('ex-7zg7eqey', 'this-course', 'easy',
  ('Which course in the track teaches equivalence partitioning and boundary values?',
   'Que curso da trilha ensina partição de equivalência e valor-limite?'),
  ('This course names its edges.', 'Este curso diz onde ficam suas bordas.'),
  C('manual-testing', 'manual-testing',
    'Right: the next course in the track, and the one that requires this one.', 'Isso: o próximo curso da trilha, e o que exige este.', ok=True),
  C('qa-fundamentals, in its lessons on black-box testing', 'qa-fundamentals, nas aulas de caixa preta',
    'Lesson 6 names those techniques and leaves them to the next course.', 'A aula 6 cita essas técnicas e as deixa para o próximo curso.'),
  C('testing-cicd', 'testing-cicd',
    'That course is about running tests in a pipeline.', 'Esse curso é sobre rodar testes num pipeline.'),
  C('web-automation', 'web-automation',
    'That one automates a browser; choosing the cases comes first.', 'Esse automatiza um navegador; escolher os casos vem antes.')),

Q('ex-1awynhsk', 'this-course', 'easy',
  ('At Cine Aurora, who decides what the ticket shop does and writes its rules down?',
   'No Cine Aurora, quem decide o que a bilheteria online faz e escreve as regras?'),
  ('The product owner.', 'A dona do produto.'),
  C('Joana', 'Joana', 'Right: she is the product owner.', 'Isso: ela é a dona do produto.', ok=True),
  C('Célia, who has sold tickets for twenty years', 'Célia, que vende ingresso há vinte anos',
    'Célia knows every rule, and runs the box office; she does not write the shop’s rules.', 'Célia conhece toda regra e comanda a bilheteria física; não escreve as regras da loja.'),
  C('Rafael, since he wrote the code that applies them', 'Rafael, já que ele escreveu o código que as aplica',
    'He turns the rules into code, which is where a reading of a rule becomes a decision.', 'Ele transforma as regras em código, que é onde uma leitura da regra vira uma decisão.'),
  C('Lia, who tests them', 'Lia, que as testa',
    'Lia checks the rules and questions them; she does not own them.', 'Lia verifica as regras e as questiona; não é dona delas.')),

Q('ex-4ggyeasx', 'prevent-and-detect', 'easy',
  ('What does quality assurance look at, in the sense this lesson uses?',
   'Para o que a garantia de qualidade olha, no sentido que esta aula usa?'),
  ('Process or product?', 'Processo ou produto?'),
  C('The process: how the work gets done', 'O processo: como o trabalho é feito',
    'Right: assurance is process-oriented and preventive.', 'Isso: garantia é orientada a processo e preventiva.', ok=True),
  C('The product, once there is a product to examine', 'O produto, quando existe um produto para examinar',
    'That is quality control, the detecting half.', 'Isso é controle de qualidade, a metade que detecta.'),
  C('The test results', 'Os resultados de teste',
    'Results are what detection produces; assurance works before there are any.', 'Resultados são o que a detecção produz; a garantia trabalha antes de haver algum.'),
  C('The customers’ complaints after release', 'As reclamações dos clientes depois da entrega',
    'Those are the latest evidence there is, and still evidence about the product.', 'São a evidência mais tardia que existe, e ainda é evidência sobre o produto.')),

Q('ex-fwbyrt5t', 'prevent-and-detect', 'medium',
  ('A team reads every new requirement aloud and asks, for each sentence, whether it could mean two things. What is this?',
   'Um time lê em voz alta todo requisito novo e pergunta, para cada frase, se ela pode querer dizer duas coisas. O que é isso?'),
  ('Does anything run?', 'Alguma coisa roda?'),
  C('Static testing, and prevention', 'Teste estático, e prevenção',
    'Right: nothing runs, and the defect is stopped before it is written.', 'Isso: nada roda, e o defeito é parado antes de ser escrito.', ok=True),
  C('Dynamic testing, because the team is examining something', 'Teste dinâmico, porque o time está examinando algo',
    'Dynamic means the program runs; here there is no program yet.', 'Dinâmico quer dizer que o programa roda; aqui ainda não há programa.'),
  C('Quality control of the product', 'Controle de qualidade do produto',
    'There is no product yet; it is the plan being examined.', 'Ainda não há produto; é o plano que está sendo examinado.'),
  C('Detection, since a defect in the sentence is being found', 'Detecção, já que um defeito na frase está sendo achado',
    'The ambiguity is found, and the defect in the code never happens: that is prevention.', 'A ambiguidade é achada, e o defeito no código nunca acontece: isso é prevenção.')),

Q('ex-6zxmvxs6', 'prevent-and-detect', 'medium',
  ('Dijkstra said testing can show the presence of defects, never their absence. What follows for a tester?',
   'Dijkstra disse que o teste pode mostrar a presença de defeitos, nunca a ausência. O que decorre disso para quem testa?'),
  ('Four correct answers, and a fifth input.', 'Quatro respostas certas, e uma quinta entrada.'),
  C('Choosing the inputs is the skill', 'Escolher as entradas é a habilidade',
    'Right: that is why lessons 6, 19 and 20 are about choosing.', 'Isso: é por isso que as aulas 6, 19 e 20 tratam de escolher.', ok=True),
  C('Testing is pointless, so prevention should replace it', 'Testar não adianta, então a prevenção deve substituí-lo',
    'Prevention cannot catch what nobody thought to ask; the two feed each other.', 'A prevenção não pega o que ninguém pensou em perguntar; as duas se alimentam.'),
  C('Enough passing tests eventually prove a program correct', 'Testes suficientes que passam acabam provando que um programa está certo',
    'That is exactly what the sentence denies.', 'É exatamente o que a frase nega.'),
  C('Only automated tests prove absence, because they run thousands of inputs', 'Só testes automatizados provam a ausência, porque rodam milhares de entradas',
    'Automation runs more inputs, and still only the inputs it runs.', 'A automação roda mais entradas, e ainda assim só as que roda.')),

Q('ex-f4jksned', 'prevent-and-detect', 'hard',
  ('After the sixty-year-old’s ticket, the team fixes `age > 60`. In the terms of this lesson, what has not been done yet?',
   'Depois do ingresso da pessoa de sessenta anos, o time corrige `age > 60`. Nos termos desta aula, o que ainda não foi feito?'),
  ('One defect, or a class of them?', 'Um defeito, ou uma classe deles?'),
  C('Asking why the sentence made it possible', 'Perguntar por que a frase o tornou possível',
    'Right: fixing the code repairs one defect; changing the process repairs a class.', 'Isso: corrigir o código conserta um defeito; mudar o processo conserta uma classe.', ok=True),
  C('Detection, since the code has only been corrected', 'A detecção, já que o código só foi corrigido',
    'Detection already happened: that is how the defect was found.', 'A detecção já aconteceu: foi assim que o defeito foi achado.'),
  C('A second test of the same age, run after the fix to confirm it holds', 'Um segundo teste da mesma idade, rodado depois da correção para confirmar que ela vale',
    'Re-running the check confirms the fix; it does not stop the next ambiguous sentence.', 'Rodar de novo a verificação confirma a correção; não impede a próxima frase ambígua.'),
  C('Nothing: the defect is repaired, so quality is assured', 'Nada: o defeito foi consertado, então a qualidade está garantida',
    'The cause, words that allow two readings, is still there.', 'A causa, palavras que permitem duas leituras, continua lá.')),

M('ex-qhkjfx5n', 'prevent-and-detect', 'medium',
  ('Match each activity to the half of quality assurance it belongs to, and whether anything runs.',
   'Associe cada atividade à metade da garantia de qualidade a que pertence, e se algo roda.'),
  ('Static means nothing runs.', 'Estático quer dizer que nada roda.'),
  [(('reviewing a design', 'revisar um projeto'), ('prevention, static', 'prevenção, estático')),
   (('running a program with chosen inputs', 'rodar um programa com entradas escolhidas'), ('detection, dynamic', 'detecção, dinâmico')),
   (('watching the system in production', 'observar o sistema em produção'), ('detection, after release', 'detecção, depois da entrega')),
   (('adopting a rule after a defect', 'adotar uma regra depois de um defeito'), ('prevention of the same kind of defect', 'prevenção do mesmo tipo de defeito'))]),

Q('ex-xm2ha6vd', 'the-lab', 'easy',
  ('Which path to a lab does this course recommend?', 'Que caminho para o laboratório este curso recomenda?'),
  ('It costs the least and changes nothing else.', 'Custa menos e não muda mais nada.'),
  C('Installed on the computer you already use', 'Instalado no computador que você já usa',
    'Right: a directory and a virtual environment, nothing running in the background.', 'Isso: um diretório e um ambiente virtual, nada rodando em segundo plano.', ok=True),
  C('A virtual machine with Ubuntu 24.04', 'Uma máquina virtual com Ubuntu 24.04',
    'A good path if you would rather not touch your own system; it costs gigabytes, and it is the second choice.', 'Um bom caminho se você prefere não mexer no seu sistema; custa gigabytes, e é a segunda opção.'),
  C('An online machine such as GitHub Codespaces', 'Uma máquina online como o GitHub Codespaces',
    'It works, on a free allowance its owner can change; the course does not depend on it.', 'Funciona, numa cota gratuita que o dono pode mudar; o curso não depende dela.'),
  C('A lab the platform provides', 'Um laboratório que a plataforma fornece',
    'The platform runs nothing for you: the lab is yours.', 'A plataforma não roda nada por você: o laboratório é seu.')),

Q('ex-pkb8xt7x', 'the-lab', 'medium',
  ('Why is behave installed inside `~/aurora/.venv` rather than for the whole system?',
   'Por que o behave é instalado dentro de `~/aurora/.venv` e não para o sistema todo?'),
  ('What does deleting `~/aurora` remove?', 'O que apagar `~/aurora` remove?'),
  C('So the lab is one directory that changes nothing else and is thrown away whole', 'Para o laboratório ser um diretório que não muda mais nada e se joga fora inteiro',
    'Right: deleting `~/aurora` removes every trace of the course.', 'Isso: apagar `~/aurora` remove todo rastro do curso.', ok=True),
  C('Because behave refuses to run outside a virtual environment', 'Porque o behave se recusa a rodar fora de um ambiente virtual',
    'It would run anywhere; the environment is about keeping the computer clean.', 'Ele rodaria em qualquer lugar; o ambiente serve para manter o computador limpo.'),
  C('Because the system Python is too old for it', 'Porque o Python do sistema é velho demais para ele',
    'The environment uses the system’s Python; it only keeps the packages apart.', 'O ambiente usa o Python do sistema; só mantém os pacotes separados.'),
  C('To make it faster', 'Para deixá-lo mais rápido',
    'A virtual environment changes where packages live, not how fast they run.', 'Um ambiente virtual muda onde os pacotes ficam, não a velocidade deles.')),

N('ex-mb7j1jpg', 'the-lab', 'easy',
  ('How many megabytes did `~/aurora/.venv` take on the recording machine?',
   'Quantos megabytes o `~/aurora/.venv` ocupou na máquina da gravação?'),
  ('`du -sh .venv`.', '`du -sh .venv`.'), 19, 0, 'MB'),

Z('ex-5wm2xhmp', 'the-lab', 'easy',
  ('Before `pip` installs into the environment in a new terminal, the environment has to be ___.',
   'Antes de o `pip` instalar no ambiente num terminal novo, o ambiente precisa estar ___.'),
  ('`source .venv/bin/activate` does it.', '`source .venv/bin/activate` faz isso.'),
  ['activated', 'active'], ['ativado', 'ativo']),

Q('ex-xd6bkt9t', 'when-it-fails', 'medium',
  ('In a new terminal, `python3 -c "import behave"` answers `ModuleNotFoundError`, although the setup finished. What is the likeliest cause?',
   'Num terminal novo, `python3 -c "import behave"` responde `ModuleNotFoundError`, embora a instalação tenha terminado. Qual a causa mais provável?'),
  ('Whose `python3` is that?', 'De quem é esse `python3`?'),
  C('The environment is not active in that terminal', 'O ambiente não está ativo naquele terminal',
    'Right: the system’s Python has never heard of behave.', 'Isso: o Python do sistema nunca ouviu falar do behave.', ok=True),
  C('The installation failed without saying so, and has to be redone from the start', 'A instalação falhou sem avisar, e precisa ser refeita do começo',
    'Activating the environment makes the same line work; nothing has to be reinstalled.', 'Ativar o ambiente faz a mesma linha funcionar; nada precisa ser reinstalado.'),
  C('`python3-venv` is missing, so pip installed behave nowhere', 'Falta o `python3-venv`, então o pip instalou o behave em lugar nenhum',
    'Without it the environment would never have been created at all.', 'Sem ele o ambiente nem teria sido criado.'),
  C('behave 1.3.3 does not exist', 'O behave 1.3.3 não existe',
    'It exists; the failure for a missing version comes from `pip`, with a list.', 'Ele existe; a falha de versão inexistente vem do `pip`, com uma lista.')),

Q('ex-racr6a1r', 'when-it-fails', 'medium',
  ('`pip install behave==1.3.9` fails with a list of versions. What is that list for?',
   '`pip install behave==1.3.9` falha com uma lista de versões. Para que serve essa lista?'),
  ('Compare what you asked for with what exists.', 'Compare o que você pediu com o que existe.'),
  C('It shows what exists, so a mistyped version is visible at a glance', 'Mostra o que existe, então uma versão digitada errado aparece de relance',
    'Right: 1.3.9 is not in it and 1.3.3 is.', 'Isso: a 1.3.9 não está nela e a 1.3.3 está.', ok=True),
  C('It lists the versions already installed', 'Lista as versões já instaladas',
    'It lists what the package index offers, installed or not.', 'Lista o que o índice de pacotes oferece, instalado ou não.'),
  C('It is the order in which pip will try them', 'É a ordem em que o pip vai tentá-las',
    'pip tries nothing else: the exact version was asked for.', 'O pip não tenta nada além: a versão exata foi pedida.'),
  C('It is noise, and only the last line matters', 'É ruído, e só a última linha importa',
    'Here the list is the part that tells you what to type.', 'Aqui a lista é a parte que diz o que digitar.')),

Q('ex-gvdwp5v5', 'when-it-fails', 'easy',
  ('A setup error prints twenty lines. Which one do you read first?',
   'Um erro de instalação imprime vinte linhas. Qual você lê primeiro?'),
  ('The rest are its consequences.', 'O resto são consequências.'),
  C('The first error', 'O primeiro erro',
    'Right: the lines after it are usually its consequences.', 'Isso: as linhas depois dele costumam ser consequências.', ok=True),
  C('The last line, always, because it sums the rest up', 'A última linha, sempre, porque ela resume o resto',
    'The last line is what to search for; the first error is what to understand.', 'A última linha é a que se busca; o primeiro erro é o que se entende.'),
  C('Whichever line mentions your file', 'A linha que cita o seu arquivo',
    'Your file may appear only as a consequence.', 'O seu arquivo pode aparecer só como consequência.'),
  C('None: reinstall first, then read', 'Nenhuma: reinstale primeiro, depois leia',
    'Evidence is read before guessing.', 'Evidência se lê antes de chutar.')),

Q('ex-zqk09dvt', 'a-first-look', 'easy',
  ('What does `python tickets.py 60 no thu 20:00` print, and what should it print by the rule?',
   'O que `python tickets.py 60 no thu 20:00` imprime, e o que deveria imprimir pela regra?'),
  ('Run the edges of the age.', 'Rode as bordas da idade.'),
  C('R$ 36,00, and it should be R$ 18,00', 'R$ 36,00, e deveria ser R$ 18,00',
    'Right: sixty pays full price, one year short of the half-price ticket.', 'Isso: sessenta paga inteira, um ano antes da meia.', ok=True),
  C('R$ 18,00, which is correct', 'R$ 18,00, o que está certo',
    'That is what sixty-one gets.', 'É o que sessenta e um recebe.'),
  C('R$ 14,00, and it should be R$ 18,00', 'R$ 14,00, e deveria ser R$ 18,00',
    'R$ 14,00 is a half-price matinée.', 'R$ 14,00 é a meia da matinê.'),
  C('An error, because the age is out of range', 'Um erro, porque a idade está fora da faixa',
    'The program prints a price for any whole number.', 'O programa imprime um preço para qualquer número inteiro.')),

Q('ex-nem2x1h8', 'a-first-look', 'medium',
  ('Where was the sixty-year-old’s defect first, before it was in `tickets.py`?',
   'Onde o defeito da pessoa de sessenta anos esteve primeiro, antes de estar no `tickets.py`?'),
  ('Read the rule again.', 'Leia a regra de novo.'),
  C('In the requirement, whose words allowed two readings', 'No requisito, cujas palavras permitiam duas leituras',
    'Right: "over-60s" can include sixty or not.', 'Isso: "maiores de 60" pode incluir sessenta ou não.', ok=True),
  C('In Rafael’s carelessness', 'No descuido do Rafael',
    'His reading was reasonable; the sentence allowed it. Lesson 18 is about asking why, not who.', 'A leitura dele era razoável; a frase permitia. A aula 18 é sobre perguntar por quê, não quem.'),
  C('In the law, which changed after the rule was written', 'Na lei, que mudou depois de a regra ser escrita',
    'The law grants the half price from sixty, and the box office always sold it that way.', 'A lei garante a meia a partir dos sessenta, e a bilheteria sempre vendeu assim.'),
  C('Nowhere: it appeared when the program ran', 'Em lugar nenhum: apareceu quando o programa rodou',
    'Running exposed it; it was written before.', 'Rodar o expôs; ele foi escrito antes.')),

Q('ex-xcr154g8', 'a-first-look', 'hard',
  ('Lia’s first four runs all agreed with the rule. Why did she keep going?',
   'As quatro primeiras execuções da Lia bateram com a regra. Por que ela continuou?'),
  ('What do four agreeing answers say about the fifth input?', 'O que quatro respostas que batem dizem sobre a quinta entrada?'),
  C('Four agreeing answers say nothing about untried inputs', 'Quatro respostas certas não dizem nada sobre entradas não tentadas',
    'Right: the rule names three ages, and an edge is where a reading differs.', 'Isso: a regra cita três idades, e uma borda é onde as leituras diferem.', ok=True),
  C('Four is below the minimum number of tests a release needs', 'Quatro está abaixo do número mínimo de testes que uma entrega exige',
    'There is no such number; the choice of input mattered, not the count.', 'Não existe esse número; importou a escolha da entrada, não a quantidade.'),
  C('She suspected Rafael', 'Ela desconfiava do Rafael',
    'Doubt is about the program and the sentence, not a person; lesson 4 makes that distinction.', 'A dúvida é sobre o programa e a frase, não sobre uma pessoa; a aula 4 faz essa distinção.'),
  C('A test has to fail before it counts', 'Um teste precisa falhar para contar',
    'A passing test counts; it just says less than people think.', 'Um teste que passa conta; só diz menos do que as pessoas acham.')),

Q('ex-9cpwh8k1', 'drill', 'hard',
  ('A team prides itself on catching every defect in its test stage, and fixes each one fast. Nothing about how it writes requirements has changed in two years. What is it missing?',
   'Um time se orgulha de pegar todo defeito na etapa de teste, e corrige cada um rápido. Nada no jeito de escrever requisitos mudou em dois anos. O que falta a ele?'),
  ('Which half is it doing?', 'Que metade ele está fazendo?'),
  C('Prevention, the half that learns from each defect', 'Prevenção, a metade que aprende com cada defeito',
    'Right: it pays for every mistake twice and never asks why it was possible.', 'Isso: paga cada erro duas vezes e nunca pergunta por que foi possível.', ok=True),
  C('More testers in the test stage, so that defects are found sooner', 'Mais gente na etapa de teste, para os defeitos serem achados mais cedo',
    'More detection finds more of the same defects, later and at the same cost.', 'Mais detecção acha mais dos mesmos defeitos, tarde e pelo mesmo custo.'),
  C('Nothing, if no defect escapes', 'Nada, se nenhum defeito escapa',
    'Even caught in time, every defect cost the making and the finding.', 'Mesmo pego a tempo, cada defeito custou o fazer e o achar.'),
  C('Dynamic testing', 'Teste dinâmico',
    'That is the half it already does.', 'É a metade que ele já faz.')),

O('ex-170y50jh', 'drill', 'medium',
  ('Put what happened to the sixty-year-old’s defect in order, from the earliest.',
   'Ponha em ordem o que aconteceu com o defeito da pessoa de sessenta anos, do mais cedo.'),
  ('The sentence came first.', 'A frase veio primeiro.'),
  [('the rule says "over-60s"', 'a regra diz "maiores de 60"'),
   ('the code says `age > 60`', 'o código diz `age > 60`'),
   ('a run with the age 60 prints full price', 'uma execução com a idade 60 imprime inteira'),
   ('the team asks why the sentence allowed two readings', 'o time pergunta por que a frase permitia duas leituras')],
  ('The question that prevents the next one comes after the defect that prompted it.',
   'A pergunta que previne o próximo vem depois do defeito que a provocou.')),
]
