from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
Q('ex-f3q1wpeg', 'the-gatekeeper', 'easy',
  ('Under a gate at the end, what happens to how carefully developers check their own work?',
   'Sob um portão no fim, o que acontece com o cuidado com que os desenvolvedores conferem o próprio trabalho?'),
  ('Somebody downstream will check everything.', 'Alguém mais adiante vai conferir tudo.'),
  C('It drops', 'Diminui', 'Right: each person lowers their bar by the height of the next one.', 'Isso: cada pessoa baixa a própria régua na altura da seguinte.', ok=True),
  C('It rises, because a tester will catch any mistake and report it to everybody', 'Aumenta, porque quem testa vai pegar qualquer erro e contar para todo mundo',
    'The fear of being caught does not survive a deadline.', 'O medo de ser pego não sobrevive a um prazo.'),
  C('It stays exactly the same as before the gate', 'Continua exatamente igual a antes do portão',
    'The lesson shows Rafael trying four inputs because Lia will try the rest.', 'A aula mostra o Rafael tentando quatro entradas porque a Lia vai tentar o resto.'),
  C('Developers stop writing code until QA approves the design', 'Desenvolvedores param de escrever código até o QA aprovar o projeto',
    'Nothing in the gate changes when code is written.', 'Nada no portão muda quando o código é escrito.')),

Q('ex-q0610962', 'the-gatekeeper', 'medium',
  ('When a defect escapes a team that runs a gate, what does the lesson say the gate turns out to have provided?',
   'Quando um defeito escapa de um time que usa um portão, o que a aula diz que o portão acaba tendo fornecido?'),
  ('A signature on the release.', 'Uma assinatura na entrega.'),
  C('Somebody to blame, since no tester guarantees a release has no defects', 'Alguém para culpar, já que ninguém que testa garante que uma entrega não tem defeitos',
    'Right: the promise was never keepable.', 'Isso: a promessa nunca foi cumprível.', ok=True),
  C('A guarantee that the defect was minor', 'Uma garantia de que o defeito era pequeno',
    'A gate says nothing about severity.', 'Um portão não diz nada sobre gravidade.'),
  C('Faster releases', 'Entregas mais rápidas', 'The gate is a bottleneck at the end.', 'O portão é um gargalo no fim.'),
  C('Proof that the process worked', 'Prova de que o processo funcionou',
    'A defect escaped through it.', 'Um defeito escapou por ele.')),

Q('ex-xfq3b9sq', 'the-gatekeeper', 'medium',
  ('What is "throwing it over the wall"?', 'O que é "jogar por cima do muro"?'),
  ('Finished, handed across, forgotten.', 'Pronto, passado adiante, esquecido.'),
  C('Handing finished work across and forgetting it', 'Passar o trabalho pronto adiante e esquecê-lo',
    'Right: whatever comes back is treated as a new problem.', 'Isso: o que volta é tratado como um problema novo.', ok=True),
  C('Releasing to production without any testing at all', 'Entregar em produção sem teste nenhum',
    'There may be plenty of testing; the wall is about the hand-off.', 'Pode haver muito teste; o muro é sobre a passagem.'),
  C('A tester rejecting a build', 'Quem testa rejeitando um build',
    'That is the gate’s side; the wall is the posture that feeds it.', 'Esse é o lado do portão; o muro é a postura que o alimenta.'),
  C('Moving a feature to a later sprint because the team ran out of time', 'Passar uma funcionalidade para uma sprint posterior porque o tempo acabou',
    'That is rescheduling, not a hand-off between people.', 'Isso é remarcar, não uma passagem entre pessoas.')),

Q('ex-4s5dr5qs', 'the-gatekeeper', 'hard',
  ('Why is the gate at its weakest exactly when it matters most?',
   'Por que o portão é mais fraco justamente quando mais importa?'),
  ('When does the work arrive?', 'Quando o trabalho chega?'),
  C('Work reaches the tester at the end, so the pressure to approve peaks when there has been least time', 'O trabalho chega no fim, então a pressão para aprovar é máxima quando houve menos tempo',
    'Right: the bottleneck and the deadline coincide.', 'Isso: o gargalo e o prazo coincidem.', ok=True),
  C('Testers are tired at the end of the week', 'Quem testa está cansado no fim da semana',
    'The cause is structural, not fatigue.', 'A causa é estrutural, não cansaço.'),
  C('Developers refuse to fix defects found by testers they consider adversaries', 'Desenvolvedores se recusam a corrigir defeitos achados por quem consideram adversário',
    'The adversarial tone is real; refusing fixes is not the argument made.', 'O tom adversário é real; recusar correções não é o argumento da aula.'),
  C('Releases happen at night', 'Entregas acontecem à noite', 'Timing of day is beside the point.', 'A hora do dia não vem ao caso.')),

Q('ex-k8kdmdcx', 'information-not-permission', 'easy',
  ('At Cine Aurora, who decides whether to ship?', 'No Cine Aurora, quem decide se entrega?'),
  ('Who owns the product?', 'Quem é dono do produto?'),
  C('Joana', 'A Joana', 'Right: the product owner, weighing the tester’s information.', 'Isso: a dona do produto, pesando a informação de quem testa.', ok=True),
  C('Lia, because she tested the release', 'A Lia, porque testou a entrega',
    'She informs the decision; she does not own it.', 'Ela informa a decisão; não é dona dela.'),
  C('Rafael, who wrote most of the code being released', 'O Rafael, que escreveu a maior parte do código entregue',
    'Writing it does not make the release decision his.', 'Escrever o código não torna a decisão dele.'),
  C('Célia, who will hear the complaints first at the counter', 'A Célia, que vai ouvir as reclamações primeiro no balcão',
    'Her view is valuable information; the decision is Joana’s.', 'A visão dela é informação valiosa; a decisão é da Joana.')),

O('ex-58znv78y', 'information-not-permission', 'easy',
  ('Put the four things Lia gave Joana in the order she gave them.', 'Ponha as quatro coisas que a Lia deu à Joana na ordem em que ela deu.'),
  ('Known, cost, unknown, options.', 'Conhecido, custo, desconhecido, opções.'),
  [('what is known', 'o que se sabe'), ('what it costs if it ships', 'quanto custa se for para produção'),
   ('what is not known', 'o que não se sabe'), ('what could reduce the risk', 'o que poderia reduzir o risco')],
  ('The options come last because they answer the risk the first three describe.', 'As opções vêm por último porque respondem ao risco que as três primeiras descrevem.')),

Q('ex-4tfbbcd2', 'information-not-permission', 'medium',
  ('Which of Lia’s four items is the one testers most often leave out?',
   'Qual dos quatro itens da Lia é o que quem testa mais deixa de fora?'),
  ('Unknowns.', 'Incógnitas.'),
  C('What was not tested', 'O que não foi testado',
    'Right: it shows the decision-maker where the unknowns are.', 'Isso: mostra a quem decide onde estão as incógnitas.', ok=True),
  C('The defect itself, with its exact reproduction in two commands', 'O defeito em si, com a reprodução exata em dois comandos',
    'That is what every report has.', 'Isso todo relato tem.'),
  C('The cost of shipping', 'O custo de entregar', 'Often given, and Lia gave it.', 'Costuma ser dado, e a Lia deu.'),
  C('A workaround for the defect that the team could apply today', 'Um contorno para o defeito que o time poderia aplicar hoje',
    'Useful, but not the one the lesson singles out.', 'Útil, mas não o que a aula destaca.')),

Q('ex-wrrpmy0g', 'information-not-permission', 'medium',
  ('Kaner defined testing as an investigation that provides stakeholders with what?',
   'Kaner definiu o teste como uma investigação que dá às partes interessadas o quê?'),
  ('Not approval.', 'Não aprovação.'),
  C('Information about the quality of the product', 'Informação sobre a qualidade do produto',
    'Right: for somebody else to decide with.', 'Isso: para outra pessoa decidir com ela.', ok=True),
  C('Approval to release', 'Aprovação para entregar', 'That is the gate, which the definition avoids.', 'Isso é o portão, que a definição evita.'),
  C('A guarantee that no defects remain in what is about to be released', 'Uma garantia de que não restam defeitos no que está para ser entregue',
    'No testing can give that.', 'Nenhum teste pode dar isso.'),
  C('A count of test cases run', 'Uma contagem de casos de teste rodados',
    'Counts are not the point; lesson 22 says why they mislead.', 'Contagens não são o ponto; a aula 22 diz por que enganam.')),

Q('ex-k1b6hmvc', 'information-not-permission', 'hard',
  ('Lia believes a defect should hold the release. Which sentence fits this lesson best?',
   'A Lia acredita que um defeito deveria segurar a entrega. Que frase combina melhor com esta aula?'),
  ('Advocacy without a veto.', 'Defender sem vetar.'),
  C('"I would not ship this: every Sunday morning customer pays too much."', '"Eu não entregaria isto: todo cliente da manhã de domingo paga a mais."',
    'Right: a plain recommendation with the evidence behind it.', 'Isso: uma recomendação clara com a evidência por trás.', ok=True),
  C('"QA has failed this build."', '"O QA reprovou este build."', 'A verdict with nothing to weigh.', 'Uma sentença sem nada para pesar.'),
  C('Nothing: a tester must stay neutral and only list defects', 'Nada: quem testa deve ficar neutro e só listar defeitos',
    'Giving information is not being neutral; a view is welcome.', 'Dar informação não é ser neutro; uma opinião é bem-vinda.'),
  C('"This cannot ship."', '"Isto não pode subir."', 'A standoff, inviting the question of who outranks whom.', 'Um impasse, que convida a pergunta de quem manda em quem.')),

M('ex-hqcbh6tt', 'information-not-permission', 'medium',
  ('Match each of Bolton’s three stories to what it tells.', 'Associe cada uma das três histórias de Bolton ao que ela conta.'),
  ('Product, testing, quality of the testing.', 'Produto, teste, qualidade do teste.'),
  [(('the product', 'o produto'), ('what you found', 'o que você achou')),
   (('the testing', 'o teste'), ('how you looked, and how well', 'como você olhou, e quão bem')),
   (('the quality of the testing', 'a qualidade do teste'), ('what you could not reach', 'o que você não alcançou'))]),

Q('ex-gq6sfhmh', 'whole-team-quality', 'easy',
  ('Whose book gave the whole-team approach its name?', 'De quem é o livro que deu nome à abordagem do time todo?'),
  ('Agile Testing, 2009.', 'Agile Testing, 2009.'),
  C('Lisa Crispin and Janet Gregory', 'Lisa Crispin e Janet Gregory', 'Right.', 'Isso.', ok=True),
  C('Cem Kaner', 'Cem Kaner', 'Kaner’s is the definition of testing as information.', 'A de Kaner é a definição de teste como informação.'),
  C('Michael Bolton, who wrote about the three stories a report tells', 'Michael Bolton, que escreveu sobre as três histórias de um relato',
    'Bolton’s is the three stories.', 'O de Bolton são as três histórias.'),
  C('W. Edwards Deming', 'W. Edwards Deming', 'Deming argued about process in manufacturing.', 'Deming falava de processo na indústria.')),

Q('ex-ja8v797g', 'whole-team-quality', 'medium',
  ('In Lia’s third week, what was most of the value she created?',
   'Na terceira semana da Lia, de onde veio a maior parte do valor que ela criou?'),
  ('Count the hours spent checking finished work.', 'Conte as horas gastas conferindo trabalho pronto.'),
  C('Work done before or while code was written, and teaching others to see problems', 'Trabalho feito antes ou durante a escrita do código, e ensinar outros a ver problemas',
    'Right: that is what makes a tester a multiplier.', 'Isso: é o que faz de quem testa um multiplicador.', ok=True),
  C('Approving the release on Thursday', 'Aprovar a entrega na quinta',
    'She wrote information for Joana; she approved nothing.', 'Ela escreveu informação para a Joana; não aprovou nada.'),
  C('Checking finished features', 'Conferir funcionalidades prontas', 'A minority of the week.', 'Uma minoria da semana.'),
  C('Writing automated tests for every feature', 'Escrever testes automatizados para toda funcionalidade',
    'Rafael writes the tests in the pairing session; Lia suggests inputs.', 'É o Rafael quem escreve os testes no pareamento; a Lia sugere entradas.')),

Q('ex-7eb91gjf', 'whole-team-quality', 'medium',
  ('What does "tester as a coach" mean in this lesson?', 'O que quer dizer "quem testa como treinador" nesta aula?'),
  ('Spread through the team.', 'Espalhado pelo time.'),
  C('Their testing knowledge spreads through the team', 'O conhecimento de teste se espalha pelo time',
    'Right: developers asking about sixty exactly without being prompted.', 'Isso: desenvolvedores perguntando de sessenta exatos sem ninguém lembrar.', ok=True),
  C('A tester who no longer tests', 'Alguém que não testa mais', 'The lesson says that is the misunderstanding.', 'A aula diz que esse é o mal-entendido.'),
  C('A tester who manages the developers and assigns their work every morning', 'Alguém que testa e gerencia os desenvolvedores, distribuindo o trabalho toda manhã',
    'Coaching is not managing.', 'Treinar não é gerenciar.'),
  C('Making the tester unnecessary within a year', 'Tornar quem testa desnecessário em um ano',
    'The goal is to point their attention at harder problems.', 'O objetivo é apontar a atenção para problemas mais difíceis.')),

Q('ex-wathhzt2', 'the-hard-cases', 'medium',
  ('Which risk is not the product owner’s alone to accept, by this lesson?',
   'Que risco não cabe só à dona do produto aceitar, por esta aula?'),
  ('The law.', 'A lei.'),
  C('Charging people over sixty full price, against the statute', 'Cobrar inteira de quem tem mais de sessenta, contra a lei',
    'Right: a team cannot choose to break a statute.', 'Isso: um time não pode escolher descumprir uma lei.', ok=True),
  C('A typo on the help page', 'Um erro de digitação na ajuda', 'A team can choose to ship a typo.', 'Um time pode escolher entregar um erro de digitação.'),
  C('Shipping a feature a week later', 'Entregar uma funcionalidade uma semana depois', 'A commercial trade-off: hers.', 'Uma troca comercial: dela.'),
  C('A slow seat map on old phones', 'Um mapa de assentos lento em celulares antigos', 'Commercial, and hers to weigh.', 'Comercial, e dela para pesar.')),

Q('ex-b6txa83n', 'the-hard-cases', 'hard',
  ('What separates a tester’s view from a veto, by the lesson’s four steps?',
   'O que separa a opinião de quem testa de um veto, pelos quatro passos da aula?'),
  ('The fourth step.', 'O quarto passo.'),
  C('Saying what would change your mind', 'Dizer o que mudaria sua opinião',
    'Right: it hands the decision-maker a way forward.', 'Isso: dá a quem decide um caminho.', ok=True),
  C('Stating the recommendation in the first sentence of the report, in bold', 'Dizer a recomendação na primeira frase do relato, em negrito',
    'Step one; a veto also comes first.', 'É o passo um; um veto também vem primeiro.'),
  C('Including a reproduction', 'Incluir uma reprodução', 'Step two; evidence supports either.', 'É o passo dois; evidência apoia os dois.'),
  C('Copying the report to the whole company', 'Copiar o relato para a empresa inteira',
    'Not one of the steps, and not how disagreement works.', 'Não é um dos passos, nem como se discorda.')),

Q('ex-xzfd8thc', 'the-hard-cases', 'medium',
  ('Joana ships against Lia’s recommendation. What does the lesson say Lia should do first?',
   'A Joana entrega contra a recomendação da Lia. O que a aula diz que a Lia deve fazer primeiro?'),
  ('Neutral, short, in the tracker.', 'Neutro, curto, no sistema do time.'),
  C('Record what was known, recommended and decided', 'Registrar o que se sabia, se recomendou e se decidiu',
    'Right: then help reduce the accepted risk.', 'Isso: depois, ajudar a reduzir o risco aceito.', ok=True),
  C('Escalate to the company’s directors', 'Escalar para a diretoria', 'Escalation is for risks beyond the team, like the law.', 'Escalar é para riscos além do time, como a lei.'),
  C('Keep a list of decisions that went wrong, to show later', 'Manter uma lista de decisões que deram errado, para mostrar depois',
    'That is keeping score.', 'Isso é fazer placar.'),
  C('Refuse to test the next release', 'Recusar testar a próxima entrega', 'That is a gate by other means.', 'Isso é um portão por outros meios.')),

Q('ex-km54c2y3', 'drill', 'hard',
  ('A developer, unsure whether a change works, says "I’ll send it to QA and see". What does that tell you about the team, by the lesson’s test?',
   'Um desenvolvedor, sem certeza de que uma mudança funciona, diz "vou mandar para o QA e ver". O que isso diz sobre o time, pelo teste da aula?'),
  ('Gate or borrowed thinking?', 'Portão ou pensamento emprestado?'),
  C('The tester is working as a gate, whatever the job title says', 'Quem testa está funcionando como portão, diga o cargo o que disser',
    'Right: the other answer is "ask Lia what she would try".', 'Isso: a outra resposta é "perguntar à Lia o que ela tentaria".', ok=True),
  C('The team trusts its tester', 'O time confia em quem testa', 'It relies on them as a gate, which is different.', 'Depende dessa pessoa como portão, o que é diferente.'),
  C('The developer is careless', 'O desenvolvedor é descuidado', 'The arrangement produces the habit.', 'O arranjo produz o hábito.'),
  C('The whole-team approach is working', 'A abordagem do time todo está funcionando', 'It is the opposite sign.', 'É o sinal oposto.')),
]
