from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
Q('ex-4hxgjy26', 'doubt-not-suspicion', 'easy',
  ('What does a tester doubt, in this lesson’s sense of systematic doubt?',
   'De que quem testa duvida, no sentido de dúvida sistemática desta aula?'),
  ('Claims or people?', 'Afirmações ou pessoas?'),
  C('Claims about the software', 'Afirmações sobre o software',
    'Right: "it works" is a claim about the inputs tried.', 'Isso: "funciona" é uma afirmação sobre as entradas tentadas.', ok=True),
  C('The competence of the developers who wrote it', 'A competência dos desenvolvedores que o escreveram',
    'That is suspicion, and it makes developers stop showing their work early.', 'Isso é desconfiança, e faz os desenvolvedores pararem de mostrar o trabalho cedo.'),
  C('Nothing until a test has failed', 'Nada até um teste falhar',
    'The doubt comes before the failure; it is what finds it.', 'A dúvida vem antes da falha; é ela que a acha.'),
  C('The product owner’s priorities for the sprint', 'As prioridades da dona do produto para a sprint',
    'Priorities are hers to set; the doubt is about what has been checked.', 'Prioridades são dela; a dúvida é sobre o que foi conferido.')),

Q('ex-f877mgy2', 'doubt-not-suspicion', 'medium',
  ('Which question asks what is known rather than asking somebody to defend themselves?',
   'Que pergunta pergunta o que se sabe, em vez de pedir que alguém se defenda?'),
  ('One question everybody can help answer.', 'Uma pergunta que todo mundo pode ajudar a responder.'),
  C('What has this been checked against, and what has not?', 'Isso foi conferido contra o quê, e contra o que não foi?',
    'Right: it is about evidence, not about a person.', 'Isso: é sobre evidência, não sobre uma pessoa.', ok=True),
  C('Did you make a mistake?', 'Você errou?', 'That asks a person to defend themselves.', 'Isso pede que alguém se defenda.'),
  C('Why did you not test this properly before handing it over?', 'Por que você não testou isso direito antes de entregar?',
    'Blame dressed as a question.', 'Culpa vestida de pergunta.'),
  C('Who reviewed it?', 'Quem revisou?', 'A name, not a fact about the software.', 'Um nome, não um fato sobre o software.')),

Q('ex-xa314jyb', 'doubt-not-suspicion', 'medium',
  ('Why does a second person find defects the author missed, according to this lesson?',
   'Por que uma segunda pessoa acha defeitos que o autor deixou passar, segundo esta aula?'),
  ('Confirmation bias.', 'Viés de confirmação.'),
  C('Distance: they do not believe it yet', 'A distância: ainda não acreditam que o código está certo',
    'Right: the author chooses inputs they expect to pass.', 'Isso: o autor escolhe entradas que espera que passem.', ok=True),
  C('Testers are better at reading code than developers', 'Quem testa lê código melhor que quem desenvolve',
    'The lesson says it is not skill: the same tester has the same blind spot on their own work.', 'A aula diz que não é habilidade: quem testa tem o mesmo ponto cego no próprio trabalho.'),
  C('Developers are careless', 'Desenvolvedores são descuidados',
    'Rafael’s claim was honest; the bias is human, not careless.', 'A afirmação do Rafael era honesta; o viés é humano, não descuido.'),
  C('A second person runs more tests in total, and more tests always find more defects', 'Uma segunda pessoa roda mais testes no total, e mais testes sempre acham mais defeitos',
    'It is which inputs are chosen, not how many.', 'É quais entradas se escolhem, não quantas.')),

Q('ex-qajw9cm0', 'doubt-not-suspicion', 'hard',
  ('Which of these is a hypothesis in the lesson’s sense?',
   'Qual destas é uma hipótese no sentido da aula?'),
  ('It must be capable of being wrong.', 'Precisa ser capaz de estar errada.'),
  C('A time written without a leading zero is charged as evening', 'Um horário sem zero à esquerda é cobrado como noite',
    'Right: one run of `09:30` against `9:30` can refute it.', 'Isso: uma execução de `09:30` contra `9:30` pode refutá-la.', ok=True),
  C('The shop has some kind of problem with the session times on its pages', 'A loja tem algum tipo de problema com os horários de sessão das páginas',
    'No run could refute it, so it is not a hypothesis.', 'Nenhuma execução poderia refutá-la, então não é hipótese.'),
  C('Something is wrong on Sundays, probably', 'Algo está errado aos domingos, provavelmente',
    'Vague, and hedged: nothing would count against it.', 'Vaga, e cheia de ressalva: nada contaria contra ela.'),
  C('Rafael’s code has a bug somewhere in the part that handles times', 'O código do Rafael tem um bug em algum lugar da parte que trata horários',
    'About a person and unfalsifiable as stated.', 'Sobre uma pessoa, e irrefutável do jeito que está.')),

M('ex-2mangc58', 'doubt-not-suspicion', 'easy',
  ('Match each word to what it was in the Sunday investigation.',
   'Associe cada palavra ao que ela foi na investigação do domingo.'),
  ('The table in the first section.', 'A tabela da primeira seção.'),
  [(('hypothesis', 'hipótese'), ('the time reached the rule in a form it does not handle', 'o horário chegou à regra numa forma que ela não trata')),
   (('experiment', 'experimento'), ('run `9:30` and `09:30` for the same adult', 'rodar `9:30` e `09:30` para o mesmo adulto')),
   (('evidence', 'evidência'), ('R$ 36,00 and R$ 28,00, as printed', 'R$ 36,00 e R$ 28,00, como impressos')),
   (('reproduction', 'reprodução'), ('two commands anybody can run', 'dois comandos que qualquer um pode rodar'))]),

N('ex-d8jc5jyh', 'a-report-from-the-counter', 'easy',
  ('How many reais did the website overcharge the family of four?',
   'Quantos reais o site cobrou a mais da família de quatro pessoas?'),
  ('R$ 108,00 against R$ 84,00.', 'R$ 108,00 contra R$ 84,00.'), 24, 0, 'R$'),

Q('ex-d1ekrdgg', 'a-report-from-the-counter', 'medium',
  ('R$ 108,00 is two times R$ 36,00 plus two times R$ 18,00. What did that arithmetic rule out before any run?',
   'R$ 108,00 é duas vezes R$ 36,00 mais duas vezes R$ 18,00. O que essa conta descartou antes de qualquer execução?'),
  ('The children were charged half of something.', 'As crianças pagaram metade de alguma coisa.'),
  C('The children’s discount', 'Um problema com o desconto das crianças',
    'Right: half of the evening price is a working discount on the wrong session price.', 'Isso: metade do preço da noite é um desconto funcionando sobre o preço errado de sessão.', ok=True),
  C('A problem with the session price', 'Um problema com o preço da sessão',
    'That is what it pointed at, not what it ruled out.', 'É para isso que ela apontou, não o que descartou.'),
  C('The possibility that the family was wrong', 'A possibilidade de a família estar errada',
    'The order record ruled that out, not the arithmetic.', 'Quem descartou isso foi o registro do pedido, não a conta.'),
  C('Nothing: arithmetic is not evidence', 'Nada: conta não é evidência',
    'The lesson says the arithmetic is evidence too.', 'A aula diz que a conta também é evidência.')),

Q('ex-n8ygjjgk', 'a-report-from-the-counter', 'medium',
  ('Why did Lia list four hypotheses before testing any of them?',
   'Por que a Lia listou quatro hipóteses antes de testar qualquer uma?'),
  ('What happens when you test the first idea and it looks plausible?', 'O que acontece quando você testa a primeira ideia e ela parece plausível?'),
  C('The first idea that fits tempts you to stop', 'Testar a primeira ideia que encaixa tenta você a parar nela',
    'Right: confirmation bias, from the tester’s side.', 'Isso: viés de confirmação, do lado de quem testa.', ok=True),
  C('Four is the number a defect report requires', 'Quatro é o número que um relato de defeito exige',
    'There is no such number.', 'Não existe esse número.'),
  C('To be able to blame the right person', 'Para poder culpar a pessoa certa',
    'None of the hypotheses is about a person.', 'Nenhuma das hipóteses é sobre uma pessoa.'),
  C('Because running the program is expensive and she wanted to run it only once, at the end', 'Porque rodar o programa é caro e ela queria rodá-lo uma vez só, no fim',
    'Runs are cheap; listing first is about not stopping too early.', 'Execuções são baratas; listar primeiro é para não parar cedo demais.')),

Q('ex-xs4jrmy5', 'a-report-from-the-counter', 'hard',
  ('Of several hypotheses, which should be tested first?',
   'De várias hipóteses, qual deve ser testada primeiro?'),
  ('Cost and how much it rules out.', 'Custo e quanto descarta.'),
  C('Cheapest, ruling out most', 'A mais barata que descarta mais',
    'Right: the family’s order record settled the fourth for nothing.', 'Isso: o registro do pedido decidiu a quarta de graça.', ok=True),
  C('The most likely one, whatever it costs to check', 'A mais provável, custe o que custar conferir',
    'Likelihood matters, and so does cost; the lesson weighs both.', 'A probabilidade importa, e o custo também; a aula pesa os dois.'),
  C('The one the developer suggests', 'A que o desenvolvedor sugerir',
    'Lia had not told Rafael anything yet.', 'A Lia ainda não tinha dito nada ao Rafael.'),
  C('The last one on the list', 'A última da lista', 'Order of writing decides nothing.', 'A ordem em que se escreve não decide nada.')),

Q('ex-fyqfwamp', 'testing-the-hypotheses', 'easy',
  ('Which run ruled out Sunday as the cause?',
   'Que execução descartou o domingo como causa?'),
  ('An adult, on a Sunday, in the afternoon.', 'Um adulto, num domingo, à tarde.'),
  C('The adult at 15:00 on Sunday', 'A do adulto às 15:00 de domingo',
    'Right: a Sunday matinée charged as a matinée.', 'Isso: uma matinê de domingo cobrada como matinê.', ok=True),
  C('`python tickets.py 35 no sun 9:30`', '`python tickets.py 35 no sun 9:30`',
    'That run shows the defect; it does not separate Sunday from the time.', 'Essa mostra o defeito; não separa o domingo do horário.'),
  C('`python tickets.py 35 no wed 20:00`', '`python tickets.py 35 no wed 20:00`',
    'A Wednesday says nothing about Sunday.', 'Uma quarta não diz nada sobre o domingo.'),
  C('Re-running the family’s purchase', 'Rodar de novo a compra da família',
    'It confirms the complaint and separates nothing.', 'Confirma a reclamação e não separa nada.')),

Q('ex-4brm03tg', 'testing-the-hypotheses', 'medium',
  ('`9:30` costs R$ 36,00 and `09:30` costs R$ 28,00. What does that separate?',
   '`9:30` custa R$ 36,00 e `09:30` custa R$ 28,00. O que isso separa?'),
  ('Same moment, two spellings.', 'Mesmo momento, duas grafias.'),
  C('How the time is written, from the hour', 'Como se escreve o horário, da hora',
    'Right: the same moment gives two prices.', 'Isso: o mesmo momento dá dois preços.', ok=True),
  C('Sunday from the other days of the week', 'O domingo dos outros dias da semana',
    'Both runs are on Sunday.', 'As duas execuções são no domingo.'),
  C('Adults from children', 'Adultos de crianças', 'Both are the same adult.', 'As duas são o mesmo adulto.'),
  C('The website from the program', 'O site do programa', 'Both runs are the program.', 'As duas execuções são o programa.')),

Z('ex-0a5neewt', 'testing-the-hypotheses', 'medium',
  ('`tickets.py` compares the session time as ___, character by character, so "9:30" sorts after "17:00".',
   'O `tickets.py` compara o horário da sessão como ___, caractere por caractere, então "9:30" fica depois de "17:00".'),
  ('Not as a time of day.', 'Não como hora do dia.'),
  ['text', 'a string', 'string', 'strings'], ['texto', 'string', 'uma string']),

Q('ex-jyyb6r10', 'testing-the-hypotheses', 'hard',
  ('The defect was in `tickets.py` from the first day. Why did nobody see it until the Sunday?',
   'O defeito estava no `tickets.py` desde o primeiro dia. Por que ninguém o viu até o domingo?'),
  ('What shape did every earlier time have?', 'Que formato todo horário anterior tinha?'),
  C('No session time before had a single digit before the colon', 'Nenhum horário anterior tinha um só dígito antes dos dois-pontos',
    'Right: no input had ever been of the shape that reaches the defect.', 'Isso: nenhuma entrada jamais tinha o formato que chega no defeito.', ok=True),
  C('It was introduced on the Saturday by a change Rafael made', 'Foi introduzido no sábado por uma mudança do Rafael',
    'The line was the same from the start.', 'A linha era a mesma desde o começo.'),
  C('A Python update changed the way two pieces of text are compared', 'Uma atualização do Python mudou o jeito de comparar dois textos',
    'Text has compared that way all along.', 'Texto sempre se comparou assim.'),
  C('Nobody had tested on a Sunday', 'Ninguém tinha testado num domingo',
    'Sunday is not the cause; the afternoon run showed it.', 'O domingo não é a causa; a execução da tarde mostrou.')),

Q('ex-8mc1g9ws', 'testing-the-hypotheses', 'medium',
  ('What does the lesson say is wrong with "change something, try again, repeat until it goes away"?',
   'O que a aula diz que há de errado em "mudar algo, tentar de novo, repetir até sumir"?'),
  ('Fix versus cause.', 'Correção contra causa.'),
  C('No cause, no evidence', 'Sem causa, sem evidência',
    'Right: a problem that vanishes unexplained comes back.', 'Isso: um problema que some sem explicação volta.', ok=True),
  C('It never finds a fix', 'Nunca acha uma correção', 'It does find one, sometimes.', 'Às vezes acha uma.'),
  C('It takes more commands than the method does', 'Leva mais comandos que o método',
    'The objection is what it leaves behind, not the count.', 'A objeção é o que fica para trás, não a contagem.'),
  C('It is only allowed for developers', 'Só desenvolvedores podem fazer isso', 'Nothing about permission.', 'Nada a ver com permissão.')),

Q('ex-wwkkp9v7', 'the-smallest-reproduction', 'easy',
  ('What makes a reproduction good, by this lesson’s test?',
   'O que torna uma reprodução boa, pelo teste desta aula?'),
  ('Somebody who never heard of the problem.', 'Alguém que nunca ouviu falar do problema.'),
  C('A newcomer runs it and sees the defect without asking you', 'Alguém de fora a roda e vê o defeito sem te perguntar nada',
    'Right: Rafael could, with two commands.', 'Isso: o Rafael conseguiu, com dois comandos.', ok=True),
  C('It retells the customer’s whole story', 'Reconta a história inteira do cliente',
    'The story starts a conversation; the reproduction ends one.', 'A história começa uma conversa; a reprodução termina uma.'),
  C('It is long enough to cover every detail', 'É longa o bastante para cobrir todo detalhe',
    'Smaller is better: each removed detail is a ruled-out hypothesis.', 'Menor é melhor: cada detalhe removido é uma hipótese descartada.'),
  C('It includes a fix', 'Inclui uma correção', 'The fix is the developer’s next step.', 'A correção é o próximo passo do desenvolvedor.')),

Q('ex-pvjza3pa', 'the-smallest-reproduction', 'medium',
  ('Lia’s reproduction left out the children, the Sunday and the family. What does each removal tell the reader?',
   'A reprodução da Lia deixou de fora as crianças, o domingo e a família. O que cada remoção diz a quem lê?'),
  ('Ruled out.', 'Descartado.'),
  C('That detail was checked and found irrelevant', 'Aquele detalhe foi conferido e é irrelevante',
    'Right: each removal is a hypothesis ruled out.', 'Isso: cada remoção é uma hipótese descartada.', ok=True),
  C('That detail was forgotten', 'Aquele detalhe foi esquecido',
    'A forgotten detail and a ruled-out one look the same; the evidence is what tells them apart.', 'Um detalhe esquecido e um descartado parecem iguais; é a evidência que os distingue.'),
  C('Nothing; reproductions are short by convention', 'Nada; reproduções são curtas por convenção',
    'They are short because of what was ruled out.', 'São curtas por causa do que foi descartado.'),
  C('That the family’s story was not true', 'Que a história da família não era verdadeira',
    'The family was right; the order record showed it.', 'A família tinha razão; o registro do pedido mostrou.')),

Q('ex-683nw2wn', 'the-smallest-reproduction', 'hard',
  ('A defect happens now and then and you cannot make it happen on demand. What is the first useful change in how you report it?',
   'Um defeito acontece de vez em quando e você não consegue provocá-lo quando quer. Qual a primeira mudança útil no jeito de relatá-lo?'),
  ('Describe, or count?', 'Descrever, ou contar?'),
  C('Count: "failed 3 times in 50 runs"', 'Contar: "falhou 3 vezes em 50"',
    'Right: a rate can show later whether a change made it rarer.', 'Isso: uma taxa mostra depois se uma mudança o tornou mais raro.', ok=True),
  C('Close it as not reproducible', 'Fechar como não reproduzível',
    'Not reproducing yet means a condition has not been found.', 'Ainda não reproduzir quer dizer que uma condição não foi achada.'),
  C('Report it only once it reproduces every time', 'Relatar só quando reproduzir toda vez',
    'The evidence so far, and what was ruled out, are worth reporting now.', 'A evidência até aqui, e o que foi descartado, já valem ser relatados.'),
  C('Run the same steps faster', 'Rodar os mesmos passos mais rápido',
    'Speed is not evidence; differences between runs are.', 'Velocidade não é evidência; as diferenças entre execuções são.')),

O('ex-9nd38pe8', 'drill', 'medium',
  ('Put the steps of Lia’s investigation in order.', 'Ponha os passos da investigação da Lia em ordem.'),
  ('Evidence first, code last.', 'Evidência primeiro, código por último.'),
  [('write down what was observed', 'anotar o que foi observado'),
   ('list the hypotheses that fit it', 'listar as hipóteses que batem com ele'),
   ('run experiments that could refute them', 'rodar experimentos que possam refutá-las'),
   ('open the code where the survivor points', 'abrir o código onde a sobrevivente aponta'),
   ('hand over the smallest reproduction', 'entregar a menor reprodução')],
  ('Opening the code before the experiments is guessing at a line.', 'Abrir o código antes dos experimentos é chutar uma linha.')),
]
