from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
Q('ex-6z2crp05', 'the-framework', 'easy',
  ('Which role does the Scrum Guide give the person who tests?', 'Que papel o Guia do Scrum dá a quem testa?'),
  ('Look at the third row of the table.', 'Olhe a terceira linha da tabela.'),
  C('Developer', 'Developer',
    'Right: everyone who builds the increment is a Developer, whatever their specialism.',
    'Isso: todo mundo que constrói o incremento é um Developer, seja qual for a especialidade.', ok=True),
  C('Tester', 'Tester', 'The Guide names no such role.', 'O Guia não tem esse papel.'),
  C('Quality owner', 'Dono da qualidade', 'There are three accountabilities and this is not one of them.',
    'São três responsabilidades e essa não é uma delas.'),
  C('A fourth accountability beside the Scrum Master', 'Uma quarta responsabilidade ao lado do Scrum Master',
    'There are three, and the Guide keeps it that way on purpose.', 'São três, e o Guia mantém assim de propósito.')),

Q('ex-qca72t5p', 'the-framework', 'medium',
  ('Why does the Scrum Guide leave out a separate testing role?', 'Por que o Guia do Scrum deixa de fora um papel separado de teste?'),
  ('Who answers for the increment?', 'Quem responde pelo incremento?'),
  C('The team answers for the increment together', 'O time responde pelo incremento junto',
    'Right: no sub-group can be accountable for "the testing" of it.',
    'Isso: nenhum subgrupo pode responder sozinho pelo "teste" dele.', ok=True),
  C('Scrum teams do not test', 'Times Scrum não testam', 'They test; the Guide just gives testing no separate owner.',
    'Testam; o Guia só não dá ao teste um dono separado.'),
  C('Testing is the Scrum Master’s job', 'Testar é trabalho do Scrum Master',
    'The Scrum Master answers for the team’s effectiveness, not for testing.',
    'O Scrum Master responde pela eficácia do time, não pelo teste.'),
  C('The Guide was written before testing was a profession of its own, in 1985', 'O Guia foi escrito antes de o teste ser uma profissão própria, em 1985',
    'The first Guide is from 2010, and testing was a profession long before.',
    'O primeiro Guia é de 2010, e o teste era profissão muito antes.')),

M('ex-k7yzq48a', 'the-framework', 'easy',
  ('Match each artefact to its commitment.', 'Associe cada artefato ao seu compromisso.'),
  ('Each artefact has exactly one.', 'Cada artefato tem exatamente um.'),
  [(('product backlog', 'backlog do produto'), ('product goal', 'meta do produto')),
   (('sprint backlog', 'backlog da sprint'), ('sprint goal', 'meta da sprint')),
   (('increment', 'incremento'), ('definition of done', 'definição de pronto'))]),

N('ex-j7g3vjng', 'the-framework', 'easy',
  ('How many events does Scrum have, counting the sprint itself?', 'Quantos eventos o Scrum tem, contando a própria sprint?'),
  ('The sprint contains the other four.', 'A sprint contém os outros quatro.'), 5, 0, ('events', 'eventos')),

Q('ex-xqqt2dhk', 'the-framework', 'medium',
  ('A team follows every rule of the Scrum Guide and still ships the Wednesday defect. How is that possible?',
   'Um time segue todas as regras do Guia do Scrum e ainda entrega o defeito da quarta. Como isso é possível?'),
  ('What does the Guide say about how to test?', 'O que o Guia diz sobre como testar?'),
  C('Scrum says nothing about how to test', 'O Scrum não diz nada sobre como testar',
    'Right: it is a frame for inspecting work, and it helps as much as the team is honest.',
    'Isso: é uma moldura para inspecionar o trabalho, e ajuda o quanto o time é honesto.', ok=True),
  C('The team must have skipped the daily scrum', 'O time deve ter pulado a daily',
    'The question says every rule was followed.', 'A pergunta diz que todas as regras foram seguidas.'),
  C('Scrum forbids testing combinations of discounts', 'O Scrum proíbe testar combinações de descontos', 'It forbids nothing of the kind.',
    'Não proíbe nada disso.'),
  C('The sprint was longer than a month, which the Guide does not allow for any team', 'A sprint passou de um mês, o que o Guia não permite a time nenhum',
    'Nothing in the question says so.', 'Nada na pergunta diz isso.')),

Q('ex-bkskbdg0', 'testing-in-each-event', 'easy',
  ('At planning for coupons, Lia asked whether a coupon combines with the Wednesday discount. Nobody knew. What did the team do?',
   'No planejamento dos cupons, a Lia perguntou se um cupom se combina com o desconto de quarta. Ninguém sabia. O que o time fez?'),
  ('The story changed shape.', 'A história mudou de forma.'),
  C('Split the story and left the combination for Joana to decide', 'Dividiu a história e deixou a combinação para a Joana decidir',
    'Right: coupons alone now, the combination next sprint.', 'Isso: cupons sozinhos agora, a combinação na próxima sprint.', ok=True),
  C('Built both and tested later', 'Construiu tudo e testou depois', 'That is how the question would have become a defect.',
    'É assim que a pergunta teria virado defeito.'),
  C('Asked Lia to decide', 'Pediu à Lia para decidir', 'A price rule is the product owner’s decision.',
    'Uma regra de preço é decisão da dona do produto.'),
  C('Dropped coupons', 'Desistiu dos cupons', 'Coupons went ahead, on their own.', 'Os cupons seguiram, sozinhos.')),

MC('ex-w3yyf7cs', 'testing-in-each-event', 'medium',
  ('What does the tester bring to sprint planning, by this lesson? Choose all that apply.',
   'O que quem testa leva ao planejamento da sprint, por esta aula? Escolha todos os que se aplicam.'),
  ('Three habits from earlier lessons.', 'Três hábitos de aulas anteriores.'),
  C('the four questions of lesson 2', 'as quatro perguntas da aula 2', 'Yes.', 'Sim.', ok=True),
  C('how the story will be tested', 'como a história vai ser testada', 'Yes: it can change the estimate.', 'Sim: pode mudar a estimativa.', ok=True),
  C('the combinations with stories already built', 'as combinações com histórias já construídas', 'Yes.', 'Sim.', ok=True),
  C('a list of the defects each developer caused last sprint', 'uma lista dos defeitos que cada pessoa causou na última sprint',
    'No: that is blame, and planning looks forward.', 'Não: isso é culpa, e o planejamento olha para a frente.')),

Q('ex-q4pdzxmn', 'testing-in-each-event', 'medium',
  ('On day seven three stories are waiting for Lia. Which event is where the team should notice?',
   'No dia sete, três histórias estão esperando a Lia. Em que evento o time deveria perceber?'),
  ('Fifteen minutes, every day.', 'Quinze minutos, todo dia.'),
  C('The daily scrum', 'A daily',
    'Right: saying what waits for testing shows the mini-waterfall forming.',
    'Isso: dizer o que espera teste mostra a minicascata se formando.', ok=True),
  C('The sprint review, when the stories are shown', 'A revisão da sprint, quando as histórias são mostradas',
    'By then the sprint is over.', 'Aí a sprint já acabou.'),
  C('The retrospective', 'A retrospectiva', 'Useful afterwards; the daily catches it while it can still change.',
    'Útil depois; a daily percebe enquanto ainda dá para mudar.'),
  C('Planning for the next sprint', 'O planejamento da próxima sprint', 'Too late for these three stories.',
    'Tarde demais para estas três histórias.')),

Q('ex-vaatpzg4', 'testing-in-each-event', 'medium',
  ('In the quadrants of lesson 11, where does the sprint review sit?', 'Nos quadrantes da aula 11, onde fica a revisão da sprint?'),
  ('Business-facing, critiquing the product.', 'Voltada ao negócio, criticando o produto.'),
  C('Q3', 'Q3', 'Right: people trying the product and reacting to it.', 'Isso: pessoas experimentando o produto e reagindo.', ok=True),
  C('Q1', 'Q1', 'Q1 is unit checks that support the team.', 'Q1 são verificações de unidade que apoiam o time.'),
  C('Q2', 'Q2', 'Q2 supports the team with examples before the code.', 'Q2 apoia o time com exemplos antes do código.'),
  C('Q4', 'Q4', 'Q4 is the technology-facing critique: speed, load, security.',
    'Q4 é a crítica voltada à tecnologia: velocidade, carga, segurança.')),

Q('ex-73jzqmfh', 'testing-in-each-event', 'hard',
  ('After the 9:30 Sunday, which question did the retrospective ask?', 'Depois do domingo das 9:30, que pergunta a retrospectiva fez?'),
  ('Lesson 2, about the process.', 'Aula 2, sobre o processo.'),
  C('Why was it possible?', 'Por que isso foi possível?',
    'Right: the answer was that nobody asked who types the session times.',
    'Isso: a resposta foi que ninguém perguntou quem digita os horários das sessões.', ok=True),
  C('Who wrote the line that compared the time as text?', 'Quem escreveu a linha que comparou o horário como texto?',
    'That finds somebody to blame and changes nothing.', 'Isso acha um culpado e não muda nada.'),
  C('How many customers were overcharged?', 'Quantos clientes pagaram a mais?',
    'Worth knowing, and it says nothing about the process.', 'Vale saber, e não diz nada sobre o processo.'),
  C('Should Lia have tested more?', 'A Lia deveria ter testado mais?', 'The defect was possible before testing began.',
    'O defeito já era possível antes de o teste começar.')),

Q('ex-gs79pt7w', 'the-definition-of-done', 'easy',
  ('Rafael says "done" and means the code is written. Lia says "done" and means she tested it. What fixes this?',
   'O Rafael diz "pronto" e quer dizer que o código está escrito. A Lia diz "pronto" e quer dizer que testou. O que resolve isso?'),
  ('One bar, written down.', 'Uma régua, escrita.'),
  C('A shared definition of done', 'Uma definição de pronto compartilhada',
    'Right: the same written bar for every story.', 'Isso: a mesma régua escrita para toda história.', ok=True),
  C('Letting the Scrum Master decide case by case', 'Deixar o Scrum Master decidir caso a caso',
    'Then "done" means what one person thinks that day.', 'Aí "pronto" quer dizer o que uma pessoa acha naquele dia.'),
  C('More detailed acceptance criteria', 'Critérios de aceitação mais detalhados',
    'Those are per story; this disagreement is about every story.', 'Esses são por história; o desacordo é sobre toda história.'),
  C('A longer sprint', 'Uma sprint mais longa', 'Length does not settle what "done" means.', 'Duração não decide o que "pronto" quer dizer.')),

Q('ex-826ae2q9', 'the-definition-of-done', 'medium',
  ('What separates the definition of done from acceptance criteria?', 'O que separa a definição de pronto dos critérios de aceitação?'),
  ('Every story, or one story?', 'Toda história, ou uma história?'),
  C('The definition applies to every story; criteria to one', 'A definição vale para toda história; os critérios, para uma',
    'Right: one bar for all, and what this story has to do.', 'Isso: uma régua para todas, e o que esta história precisa fazer.', ok=True),
  C('They are the same thing with two names', 'São a mesma coisa com dois nomes', 'They are often confused, and they differ.',
    'São muito confundidos, e são diferentes.'),
  C('Criteria are written by testers', 'Os critérios são escritos por quem testa',
    'They are usually written by the product owner, often with the team.',
    'Em geral são escritos pela dona do produto, muitas vezes com o time.'),
  C('The definition is written by the product owner and the criteria by the developers who build the story',
    'A definição é escrita pela dona do produto e os critérios por quem constrói a história',
    'The definition belongs to the team.', 'A definição é do time.')),

Q('ex-4td8c3cj', 'the-definition-of-done', 'medium',
  ('A story passes all its acceptance criteria. Nobody explored it, and an old check now fails. Is it done?',
   'Uma história passa todos os critérios de aceitação. Ninguém a explorou, e uma conferência antiga agora falha. Está pronta?'),
  ('Both bars.', 'As duas réguas.'),
  C('No', 'Não', 'Right: lines 3 and 4 of the definition are not met.', 'Isso: as linhas 3 e 4 da definição não foram cumpridas.', ok=True),
  C('Yes: the criteria are what the story has to do', 'Sim: os critérios são o que a história precisa fazer',
    'A story meets both, or it is not done.', 'Uma história cumpre os dois, ou não está pronta.'),
  C('Yes, if the product owner accepts it in the review', 'Sim, se a dona do produto aceitar na revisão',
    'The definition of done comes before the review.', 'A definição de pronto vem antes da revisão.'),
  C('Only if the failing check is fixed next sprint', 'Só se a conferência que falha for corrigida na próxima sprint',
    'That is lesson 11’s test debt.', 'Isso é a dívida de teste da aula 11.')),

Q('ex-ey6hjwnn', 'the-definition-of-done', 'hard',
  ('A story fails the definition of done on the last day. What is the honest outcome?',
   'Uma história não passa a definição de pronto no último dia. Qual é o resultado honesto?'),
  ('It is not shown as finished.', 'Ela não é mostrada como terminada.'),
  C('It is not done, and goes back to the backlog or stays in progress', 'Não está pronta, e volta ao backlog ou continua em andamento',
    'Right: and it is not shown at the review as finished.', 'Isso: e não é mostrada na revisão como terminada.', ok=True),
  C('Call it done and fix it next sprint', 'Chamá-la de pronta e corrigir na próxima sprint',
    'That is the dishonest outcome, and test debt.', 'Esse é o resultado desonesto, e dívida de teste.'),
  C('Remove the failing line from the definition', 'Tirar da definição a linha que falha',
    'That can be discussed at the retrospective, not on the last day to pass one story.',
    'Isso pode ser discutido na retrospectiva, não no último dia para passar uma história.'),
  C('Ask Lia to sign it off', 'Pedir à Lia para aprovar', 'Her job is to keep the definition honest, not to waive it.',
    'O trabalho dela é manter a definição honesta, não dispensá-la.')),

O('ex-rerjvtr1', 'the-definition-of-done', 'medium',
  ('Put the lines of the Cine Aurora definition of done in the order the team wrote them.',
   'Ponha as linhas da definição de pronto do Cine Aurora na ordem em que o time as escreveu.'),
  ('Reviewed first, releasable last.', 'Revisada primeiro, entregável por último.'),
  [('reviewed by another developer', 'revisada por outro desenvolvedor'),
   ('each acceptance criterion has a passing test', 'cada critério de aceitação tem um teste que passa'),
   ('the old automated checks still pass', 'as verificações automatizadas antigas ainda passam'),
   ('explored for half an hour', 'explorada por meia hora'),
   ('every question has a written answer', 'toda pergunta tem uma resposta escrita'),
   ('in a version that could ship today', 'numa versão que poderia ser entregue hoje')],
  ('Each line exists because something went wrong; the order follows the work.',
   'Cada linha existe porque algo deu errado; a ordem segue o trabalho.')),

Q('ex-ze1neby9', 'acceptance-criteria', 'easy',
  ('Which version of the criterion for older customers can a tester use?',
   'Que versão do critério para idosos quem testa consegue usar?'),
  ('Prices and both sides of the line.', 'Preços e os dois lados da linha.'),
  C('59 pays R$ 36,00; 60 and 61 pay R$ 18,00, evening', '59 paga R$ 36,00; 60 e 61 pagam R$ 18,00, noite',
    'Right: three checks with their expected results.', 'Isso: três conferências com os resultados esperados.', ok=True),
  C('Customers over 60 pay half', 'Clientes maiores de 60 pagam meia',
    'Exactly the sentence that hid the defect.', 'Exatamente a frase que escondeu o defeito.'),
  C('The discount works correctly', 'O desconto funciona corretamente', 'Correct according to what?', 'Correto segundo o quê?'),
  C('Older customers are happy', 'Os idosos ficam satisfeitos', 'Nobody can check that before release.',
    'Ninguém consegue conferir isso antes da entrega.')),

Q('ex-a2p1595v', 'acceptance-criteria', 'medium',
  ('Why does writing a criterion as examples help the product owner as much as the tester?',
   'Por que escrever um critério como exemplos ajuda a dona do produto tanto quanto quem testa?'),
  ('Can Joana write "60 pays R$ 18,00" without deciding?', 'A Joana consegue escrever "60 paga R$ 18,00" sem decidir?'),
  C('An example forces each ambiguity into the open', 'Um exemplo força cada ambiguidade para a luz',
    'Right: she has to decide whether sixty counts.', 'Isso: ela precisa decidir se sessenta conta.', ok=True),
  C('Examples are shorter', 'Exemplos são mais curtos', 'The examples version was the longest of the three.',
    'A versão com exemplos era a mais longa das três.'),
  C('Examples replace the definition of done', 'Exemplos substituem a definição de pronto', 'They are per story; the definition is for all.',
    'Eles são por história; a definição é para todas.'),
  C('Examples let the developers skip writing tests for the story', 'Exemplos deixam quem desenvolve pular os testes da história',
    'Each example becomes a test.', 'Cada exemplo vira um teste.')),

Z('ex-5acfwmra', 'acceptance-criteria', 'easy',
  ('Given a customer aged 60 at a Thursday evening session, when they buy a ticket, ___ they pay R$ 18,00.',
   'Dado um cliente de 60 anos numa sessão da noite de quinta, quando ele compra um ingresso, ___ paga R$ 18,00.'),
  ('Given, when, …', 'Dado, quando, …'),
  ['then'], ['então', 'entao']),

Q('ex-0d3jybrn', 'acceptance-criteria', 'medium',
  ('Which part of Given/When/Then does a tester need most?', 'De que parte do Dado/Quando/Então quem testa mais precisa?'),
  ('The expected result.', 'O resultado esperado.'),
  C('Then', 'Então', 'Right: the format makes it hard to leave out.', 'Isso: o formato torna difícil deixá-lo de fora.', ok=True),
  C('Given', 'Dado', 'It sets up the situation; the expected result is elsewhere.', 'Monta a situação; o resultado esperado está em outra parte.'),
  C('When', 'Quando', 'It is the action.', 'É a ação.'),
  C('The title of the story', 'O título da história', 'Not part of the format.', 'Não faz parte do formato.')),

MC('ex-n1h4s3y3', 'acceptance-criteria', 'hard',
  ('Joana has written criteria for "older customers pay half". Which of these is the tester adding? Choose all that apply.',
   'A Joana escreveu critérios para "idosos pagam meia". Quais destes quem testa está acrescentando? Escolha todos os que se aplicam.'),
  ('Edges, combinations, inputs, what happens after.', 'Bordas, combinações, entradas, o que acontece depois.'),
  C('a customer aged 59 and one aged 60', 'um cliente de 59 e um de 60', 'Yes: both sides of the line.', 'Sim: os dois lados da linha.', ok=True),
  C('an older customer on a Wednesday', 'um idoso numa quarta', 'Yes: a combination.', 'Sim: uma combinação.', ok=True),
  C('an age typed as a word', 'uma idade digitada como palavra', 'Yes: an input nobody mentioned.', 'Sim: uma entrada que ninguém mencionou.', ok=True),
  C('a criterion that the code be written in Python', 'um critério de que o código seja escrito em Python',
    'No: that says nothing about what the story has to do.', 'Não: isso não diz nada sobre o que a história precisa fazer.')),

Q('ex-y74metsv', 'drill', 'medium',
  ('The team keeps calling stories done that break old checks. Where does the tester take the gap?',
   'O time continua chamando de prontas histórias que quebram conferências antigas. Para onde quem testa leva a lacuna?'),
  ('The event that looks at how the team works.', 'O evento que olha como o time trabalha.'),
  C('The retrospective', 'A retrospectiva',
    'Right: the team decides whether the definition or the sprint was wrong.',
    'Isso: o time decide se a definição estava errada ou se a sprint é que estava.', ok=True),
  C('The daily scrum', 'A daily', 'Fifteen minutes about progress toward the goal.', 'Quinze minutos sobre o avanço rumo à meta.'),
  C('Straight to the product owner, in private', 'Direto à dona do produto, em particular',
    'The definition belongs to the whole team.', 'A definição é do time todo.'),
  C('A defect report against each developer who called a story done', 'Um relato de defeito contra cada pessoa que chamou uma história de pronta',
    'That is policing, and the lesson asks for honesty instead.', 'Isso é policiar, e a aula pede honestidade.')),
]
