from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
O('ex-72qwpety', 'the-spiral', 'easy',
  ('Put the four quadrants of a spiral turn in order.', 'Ponha os quatro quadrantes de uma volta da espiral em ordem.'),
  ('Objectives first.', 'Objetivos primeiro.'),
  [('determine objectives', 'definir objetivos'), ('identify and resolve risks', 'identificar e resolver riscos'),
   ('develop and test', 'desenvolver e testar'), ('plan the next iteration', 'planejar a próxima iteração')],
  ('Risk comes before building, which is the point of the model.', 'O risco vem antes de construir, que é o ponto do modelo.')),

Q('ex-dxnc0hgp', 'the-spiral', 'easy',
  ('What chooses what each turn of the spiral is about?', 'O que escolhe do que trata cada volta da espiral?'),
  ('The second quadrant.', 'O segundo quadrante.'),
  C('Risk', 'O risco', 'Right: the biggest uncertainty goes first.', 'Isso: a maior incerteza vai primeiro.', ok=True),
  C('The next feature on the product owner’s list, in the order she wrote it down', 'A próxima funcionalidade da lista da dona do produto, na ordem em que ela anotou',
    'That is a backlog order; the spiral orders by risk.', 'Essa é uma ordem de backlog; a espiral ordena por risco.'),
  C('Whichever part is easiest', 'A parte mais fácil', 'Easy is not the criterion.', 'Fácil não é o critério.'),
  C('A fixed schedule of phases', 'Um cronograma fixo de fases', 'That is the waterfall.', 'Isso é a cascata.')),

Q('ex-fsajzzxx', 'the-spiral', 'medium',
  ('Why does the lesson call identifying and resolving risks "a testing activity in all but name"?',
   'Por que a aula chama identificar e resolver riscos de "atividade de teste em tudo menos no nome"?'),
  ('A prototype is an experiment.', 'Um protótipo é um experimento.'),
  C('It designs experiments able to refute a belief, like a prototype', 'Desenha experimentos capazes de refutar uma crença, como um protótipo',
    'Right: lesson 4’s definition of testing.', 'Isso: a definição de teste da aula 4.', ok=True),
  C('Because testers run that quadrant alone', 'Porque quem testa conduz esse quadrante sozinho', 'The team does it.', 'O time faz.'),
  C('It produces test cases', 'Produz casos de teste', 'It produces knowledge about risk.', 'Produz conhecimento sobre risco.'),
  C('Because it happens after the code is written, like testing in the waterfall', 'Porque acontece depois de o código ser escrito, como o teste na cascata',
    'It happens before building.', 'Acontece antes de construir.')),

Q('ex-49smh843', 'the-spiral', 'hard',
  ('Boehm described the spiral as a meta-model. What does that mean?', 'Boehm descreveu a espiral como um metamodelo. O que isso quer dizer?'),
  ('The risk decides the shape.', 'O risco decide o formato.'),
  C('Each turn takes the shape the risk calls for', 'Cada volta toma o formato que o risco pede',
    'Right: a small waterfall, an experiment, a piece of a V.', 'Isso: uma pequena cascata, um experimento, um pedaço de V.', ok=True),
  C('It is a model about meetings', 'É um modelo sobre reuniões', 'No.', 'Não.'),
  C('It has no testing', 'Não tem teste', 'Testing is in every turn.', 'O teste está em toda volta.'),
  C('It replaces all other models and makes them obsolete for any kind of project', 'Substitui todos os outros modelos e os torna obsoletos para qualquer projeto',
    'It contains them; it does not abolish them.', 'Contém os outros; não os abole.')),

Q('ex-vexg83z9', 'risk-chooses-the-turn', 'medium',
  ('Why did the price rule sit third on Cine Aurora’s risk list, though the course spends eight lessons on it?',
   'Por que a regra de preço ficou em terceiro na lista de riscos do Cine Aurora, embora o curso dedique oito aulas a ela?'),
  ('Lesson 3’s four costs.', 'Os quatro custos da aula 3.'),
  C('It is the cheapest to fix late', 'É a mais barata de corrigir tarde',
    'Right: one function, nothing built on it.', 'Isso: uma função, nada construído em cima.', ok=True),
  C('It does not matter to customers', 'Não importa para os clientes', 'It matters: it is money.', 'Importa: é dinheiro.'),
  C('Prices cannot be tested early', 'Preços não podem ser testados cedo', 'A review with Célia is early and cheap.', 'Uma revisão com a Célia é cedo e barata.'),
  C('Because Rafael had already tested it thoroughly with dozens of inputs before the list was made', 'Porque o Rafael já a tinha testado a fundo com dezenas de entradas antes da lista',
    'Nothing says so, and lesson 1 shows otherwise.', 'Nada diz isso, e a aula 1 mostra o contrário.')),

M('ex-e62mqk8s', 'risk-chooses-the-turn', 'medium',
  ('Match each risk to the cheapest way of finding out, from Cine Aurora’s list.',
   'Associe cada risco ao jeito mais barato de descobrir, da lista do Cine Aurora.'),
  ('The table.', 'A tabela.'),
  [(('customers do not understand the seat map', 'clientes não entendem o mapa de assentos'), ('a paper prototype shown to five regulars', 'um protótipo de papel mostrado a cinco clientes fiéis')),
   (('two buyers get the same seat', 'dois compradores levam o mesmo assento'), ('a program that tries it a thousand times', 'um programa que tenta isso mil vezes')),
   (('the price rule is wrong', 'a regra de preço está errada'), ('a review with Célia', 'uma revisão com a Célia')),
   (('payment is slow on opening nights', 'o pagamento fica lento em estreias'), ('ask the provider for their numbers', 'pedir os números ao provedor'))]),

Q('ex-thffahsc', 'risk-chooses-the-turn', 'medium',
  ('On which two things was each risk judged?', 'Por quais duas coisas cada risco foi julgado?'),
  ('Two axes.', 'Dois eixos.'),
  C('How likely, and how bad', 'Quão provável, e quão grave', 'Right: the basis of lesson 20.', 'Isso: a base da aula 20.', ok=True),
  C('Who reported it and when it was reported to the team', 'Quem o relatou e quando foi relatado ao time', 'Not on the list.', 'Não está na lista.'),
  C('Cost and speed', 'Custo e velocidade', 'Not the two axes.', 'Não são os dois eixos.'),
  C('How many testers it needs', 'Quantas pessoas de teste ele exige', 'Not a column.', 'Não é uma coluna.')),

Q('ex-hk5j073x', 'risk-chooses-the-turn', 'hard',
  ('Lia’s program tried to double-sell a seat a thousand times and never succeeded. What should she say about it?',
   'O programa da Lia tentou vender um assento duas vezes mil vezes e nunca conseguiu. O que ela deveria dizer sobre isso?'),
  ('What an experiment did not show.', 'O que um experimento não mostrou.'),
  C('A thousand tries found nothing, which proves nothing about ten thousand', 'Mil tentativas não acharam nada, o que não prova nada sobre dez mil',
    'Right: honesty about the limits of the experiment.', 'Isso: honestidade sobre os limites do experimento.', ok=True),
  C('Double-selling is impossible', 'Vender duas vezes é impossível', 'Dijkstra, from lesson 1, again.', 'Dijkstra, da aula 1, de novo.'),
  C('The risk can be removed from the list', 'O risco pode sair da lista', 'Reduced, perhaps; not removed.', 'Reduzido, talvez; não removido.'),
  C('Nothing', 'Nada', 'The result is worth reporting, with its limit.', 'O resultado vale ser relatado, com seu limite.')),

Q('ex-wqzx423s', 'iterative-and-incremental', 'easy',
  ('Which describes incremental development?', 'O que descreve o desenvolvimento incremental?'),
  ('A piece at a time.', 'Um pedaço por vez.'),
  C('Each piece finished before the next is built', 'Cada pedaço pronto antes do próximo',
    'Right: part complete, part missing.', 'Isso: parte pronta, parte faltando.', ok=True),
  C('The whole system, rough, then better, then good', 'O sistema inteiro, tosco, depois melhor, depois bom', 'That is iterative.', 'Isso é iterativo.'),
  C('One long pass through the phases', 'Uma longa passagem pelas fases', 'That is the waterfall.', 'Isso é a cascata.'),
  C('No planning at all, with features chosen each morning by whoever arrives first', 'Nenhum planejamento, com funcionalidades escolhidas toda manhã por quem chega primeiro',
    'Not a model.', 'Não é um modelo.')),

Q('ex-t1e3fyx5', 'iterative-and-incremental', 'medium',
  ('Built incrementally, when would Cine Aurora have met the refused orders inflating the seats report?',
   'Construído incrementalmente, quando o Cine Aurora teria encontrado os pedidos recusados inflando o relatório?'),
  ('Integration risk.', 'Risco de integração.'),
  C('Late, at integration', 'Tarde, na integração',
    'Right: each piece tested alone, integration last.', 'Isso: cada pedaço testado sozinho, a integração por último.', ok=True),
  C('In the first week', 'Na primeira semana', 'The report did not exist yet.', 'O relatório ainda não existia.'),
  C('Never', 'Nunca', 'At integration it shows.', 'Na integração aparece.'),
  C('Before the price rule', 'Antes da regra de preço', 'Prices came first.', 'Os preços vieram primeiro.')),

Q('ex-8yxptyxe', 'iterative-and-incremental', 'medium',
  ('What is the testing risk of purely iterative delivery?', 'Qual o risco de teste da entrega puramente iterativa?'),
  ('"It is only a draft."', '"É só um rascunho."'),
  C('Nothing finished enough to test thoroughly, and defects dismissed as drafts', 'Nada pronto o bastante para testar a fundo, e defeitos descartados como rascunho',
    'Right: its strength is early feedback from Célia.', 'Isso: a força dele é o retorno cedo da Célia.', ok=True),
  C('Integration happens too late', 'A integração acontece tarde demais', 'That is incremental’s risk.', 'Esse é o risco do incremental.'),
  C('Too much documentation', 'Documentação demais', 'Not the risk named.', 'Não é o risco citado.'),
  C('Customers see too much', 'Os clientes veem demais', 'Seeing early is the benefit.', 'Ver cedo é o benefício.')),

Q('ex-2sdscyw9', 'iterative-and-incremental', 'hard',
  ('Most modern teams combine both. How, by this lesson?', 'A maioria dos times modernos combina os dois. Como, por esta aula?'),
  ('Thin slices.', 'Fatias finas.'),
  C('Thin end-to-end slices, each grown iteratively', 'Fatias finas de ponta a ponta, cada uma crescida iterativamente',
    'Right: one kind of ticket through the whole shop, then wider.', 'Isso: um tipo de ingresso pela loja inteira, depois mais largo.', ok=True),
  C('Alternating months', 'Alternando meses', 'Not the combination described.', 'Não é a combinação descrita.'),
  C('One team does incremental work while another team works iteratively on a copy', 'Um time trabalha incrementalmente enquanto outro trabalha iterativamente numa cópia',
    'No.', 'Não.'),
  C('Using the Rational Unified Process exactly as published', 'Usando o Rational Unified Process exatamente como publicado',
    'RUP was one form; the lesson describes the general combination.', 'O RUP foi uma forma; a aula descreve a combinação em geral.')),

Z('ex-kmyxzcp1', 'testing-in-a-loop', 'easy',
  ('Checking that what worked before still works after a change is called ___ testing.',
   'Conferir que o que funcionava antes ainda funciona depois de uma mudança se chama teste de ___.'),
  ('It grows every turn.', 'Cresce a cada volta.'),
  ['regression'], ['regressão', 'regressao']),

Q('ex-6f5h59xs', 'testing-in-a-loop', 'medium',
  ('The sixty-year-old fix changes `>` to `>=`. Which case does a regression test protect against breaking?',
   'A correção dos sessenta troca `>` por `>=`. Que caso um teste de regressão protege de quebrar?'),
  ('Still full price.', 'Ainda inteira.'),
  C('Fifty-nine still paying full price', 'Cinquenta e nove ainda pagando inteira',
    'Right: a fix that broke fifty-nine would be a new defect.', 'Isso: uma correção que quebrasse cinquenta e nove seria um defeito novo.', ok=True),
  C('Sixty paying half', 'Sessenta pagando meia', 'That is what the fix adds, not what it might break.', 'É o que a correção acrescenta, não o que pode quebrar.'),
  C('Nothing: one character cannot break anything', 'Nada: um caractere não quebra nada', 'One character is a change.', 'Um caractere é uma mudança.'),
  C('The Wednesday price for adults at evening sessions on the cheapest day', 'O preço de quarta para adultos nas sessões da noite do dia mais barato',
    'Possible, and unrelated to this line.', 'Possível, e sem relação com esta linha.')),

Q('ex-qt9yx50b', 'testing-in-a-loop', 'medium',
  ('Why does regression testing become the strongest argument for automation?',
   'Por que o teste de regressão vira o argumento mais forte para automatizar?'),
  ('Turn 1’s checks run every turn.', 'As conferências da volta 1 rodam toda volta.'),
  C('It grows every turn until, by hand, it is most of the testing time', 'Cresce a cada volta até ser, à mão, a maior parte do tempo de teste',
    'Right: `cases.py` runs six cases in a second.', 'Isso: o `cases.py` roda seis casos em um segundo.', ok=True),
  C('It finds the most defects', 'Acha mais defeitos', 'Not the argument made.', 'Não é o argumento.'),
  C('Automation is required by law', 'A lei exige automação', 'No.', 'Não.'),
  C('Manual testers cannot repeat a test', 'Quem testa à mão não consegue repetir um teste', 'They can; it costs time.', 'Conseguem; custa tempo.')),

Q('ex-xfgp60w8', 'drill', 'hard',
  ('"Every defect found should leave a test behind." What does the lesson say those tests become over time?',
   '"Todo defeito achado deveria deixar um teste para trás." O que a aula diz que esses testes viram com o tempo?'),
  ('A record.', 'Um registro.'),
  C('A record of where the system is most likely to break again', 'Um registro de onde o sistema tem mais chance de quebrar de novo',
    'Right: everything it ever got wrong.', 'Isso: tudo o que ele já errou.', ok=True),
  C('A burden to delete each year', 'Um peso a apagar todo ano', 'The lesson argues for keeping them.', 'A aula defende mantê-los.'),
  C('Proof the system is correct', 'Prova de que o sistema está certo', 'Lesson 1’s Dijkstra again.', 'O Dijkstra da aula 1 de novo.'),
  C('The specification that replaces the requirements Joana wrote', 'A especificação que substitui os requisitos que a Joana escreveu',
    'They check against requirements; they do not replace them.', 'Conferem contra os requisitos; não os substituem.')),
]
