from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
Q('ex-bgtnztef', 'outside-in', 'easy',
  ('What does a black-box tester compare?', 'O que quem testa como caixa preta compara?'),
  ('Should and does.', 'Deveria e faz.'),
  C('What it does with what it should do', 'O que faz com o que deveria fazer',
    'Right: from inputs and outputs, against the specification.', 'Isso: por entradas e saídas, contra a especificação.', ok=True),
  C('The code with the specification, line by line, before running anything at all', 'O código com a especificação, linha por linha, antes de rodar qualquer coisa',
    'That needs the code, which black box does not read.', 'Isso exige o código, que a caixa preta não lê.'),
  C('Two versions of the code', 'Duas versões do código', 'Black box sees no code.', 'A caixa preta não vê código.'),
  C('How long the program takes on each input', 'Quanto tempo o programa leva em cada entrada',
    'Timing can be observed from outside, but it is not the definition.', 'O tempo pode ser observado de fora, mas não é a definição.')),

Q('ex-tqbpk1n2', 'outside-in', 'medium',
  ('Why does a black-box test of `tickets.py` survive Rafael rewriting it from scratch?',
   'Por que um teste caixa preta do `tickets.py` sobrevive ao Rafael reescrevê-lo do zero?'),
  ('What did not change?', 'O que não mudou?'),
  C('It was written against the rule, and the rule did not change', 'Foi escrito contra a regra, e a regra não mudou',
    'Right: tests against code structure may have to be rewritten with it.', 'Isso: testes contra a estrutura do código podem precisar ser reescritos junto.', ok=True),
  C('Black-box tests never fail', 'Testes caixa preta nunca falham', 'They fail whenever behaviour departs from the rule.', 'Falham sempre que o comportamento se afasta da regra.'),
  C('Because it tests each line of the code exactly once', 'Porque testa cada linha do código exatamente uma vez',
    'That is a white-box idea, and lines change in a rewrite.', 'Essa é uma ideia de caixa branca, e linhas mudam numa reescrita.'),
  C('Python keeps old tests', 'O Python guarda testes antigos', 'Nothing of the sort.', 'Nada disso.')),

Q('ex-mx2vk89e', 'outside-in', 'hard',
  ('Suppose `tickets.py` secretly gave a discount on one particular date. Why would black-box testing from Joana’s rule not find it?',
   'Suponha que o `tickets.py` desse em segredo um desconto numa data específica. Por que o teste caixa preta a partir da regra da Joana não o acharia?'),
  ('What points a tester at that date?', 'O que aponta quem testa para essa data?'),
  C('Nothing in the rule points at that date', 'Nada na regra aponta para essa data',
    'Right: you only test the behaviours you thought of.', 'Isso: você só testa os comportamentos em que pensou.', ok=True),
  C('Black box cannot run the program on a specific date', 'A caixa preta não consegue rodar o programa numa data específica',
    'It could, if something told the tester which one.', 'Conseguiria, se algo dissesse a quem testa qual.'),
  C('Dates are a white-box concept that only the code itself can reveal to a tester', 'Datas são um conceito de caixa branca que só o próprio código revela a quem testa',
    'Dates are ordinary inputs; the problem is which one to try.', 'Datas são entradas comuns; o problema é qual tentar.'),
  C('It would find it on the first run', 'Acharia na primeira execução', 'Only if the first run happened to use that date.', 'Só se a primeira execução usasse essa data por acaso.')),

M('ex-1qpwtwcd', 'outside-in', 'medium',
  ('Match each technique to what it does. The techniques are taught in manual-testing.',
   'Associe cada técnica ao que ela faz. As técnicas são ensinadas em manual-testing.'),
  ('Names only, here.', 'Só os nomes, aqui.'),
  [(('equivalence partitioning', 'partição de equivalência'), ('test one input from each group that should behave alike', 'testar uma entrada de cada grupo que deveria se comportar igual')),
   (('boundary value analysis', 'análise de valor-limite'), ('test at the edges of the groups', 'testar nas bordas dos grupos')),
   (('decision tables', 'tabelas de decisão'), ('cover rules that combine conditions', 'cobrir regras que combinam condições')),
   (('state transition', 'transição de estados'), ('test answers that depend on what happened before', 'testar respostas que dependem do que aconteceu antes'))]),

Q('ex-m4t2v2v4', 'cases-from-the-rule', 'easy',
  ('Why did Lia test 16:59 and 17:00, and 11 and 12?',
   'Por que a Lia testou 16:59 e 17:00, e 11 e 12?'),
  ('A line has two sides.', 'Uma linha tem dois lados.'),
  C('Each is the last value on one side of a line and the first on the other', 'Cada par é o último valor de um lado de uma linha e o primeiro do outro',
    'Right: that is where readings differ, as at sixty.', 'Isso: é onde as leituras divergem, como nos sessenta.', ok=True),
  C('They are the most common inputs', 'São as entradas mais comuns', 'Common is not the reason; edges are.', 'Comum não é o motivo; bordas são.'),
  C('The program crashes at those values', 'O programa quebra nesses valores', 'All six passed.', 'Os seis passaram.'),
  C('Joana asked for them', 'A Joana pediu', 'Lia chose them from the rule.', 'A Lia os escolheu a partir da regra.')),

Q('ex-zgz9v3d7', 'cases-from-the-rule', 'medium',
  ('Why did Lia write the expected result before running each case?',
   'Por que a Lia escreveu o resultado esperado antes de rodar cada caso?'),
  ('After seeing the output…', 'Depois de ver a saída…'),
  C('One written afterwards agrees with the output it has seen', 'Uma escrita depois concorda com a saída que já viu',
    'Right: confirmation bias, again.', 'Isso: viés de confirmação, de novo.', ok=True),
  C('The test tool requires it', 'A ferramenta de teste exige', 'There is no tool here; it is a habit.', 'Não há ferramenta aqui; é um hábito.'),
  C('To save time', 'Para poupar tempo', 'It costs a little time, and buys honesty.', 'Custa um pouco de tempo, e compra honestidade.'),
  C('Because the output is unreadable without a prepared answer to compare it with', 'Porque a saída é ilegível sem uma resposta preparada para comparar',
    'The output is a plain price.', 'A saída é um preço simples.')),

N('ex-78jqmpkr', 'cases-from-the-rule', 'easy',
  ('How many of Lia’s six cases from the rule passed?', 'Quantos dos seis casos da Lia a partir da regra passaram?'),
  ('Six for…', 'Seis de…'), 6, 0, ('cases', 'casos')),

Q('ex-2a6htc9s', 'cases-from-the-rule', 'hard',
  ('All six cases passed. What kind of input did none of them exercise?',
   'Os seis casos passaram. Que tipo de entrada nenhum deles exercitou?'),
  ('One sentence at a time.', 'Uma frase por vez.'),
  C('Combinations of two sentences', 'Combinações de duas frases',
    'Right: a student on a Wednesday is in no row.', 'Isso: um estudante numa quarta não está em nenhuma linha.', ok=True),
  C('Boundaries', 'Bordas', 'Four of the six were boundary cases.', 'Quatro dos seis eram casos de borda.'),
  C('Evening sessions on days other than Wednesday', 'Sessões da noite em dias que não são quarta',
    'Several cases were Thursday evenings.', 'Vários casos eram noites de quinta.'),
  C('Children younger than twelve at a matinée on a Saturday', 'Crianças com menos de doze numa matinê de sábado',
    'A combination too, but not the one the lesson runs; the general answer is combinations.', 'Também uma combinação, mas não a que a aula roda; a resposta geral é combinações.')),

N('ex-wypp1qg1', 'what-the-rule-does-not-say', 'easy',
  ('How many reais does `tickets.py` charge a student on a Wednesday evening?',
   'Quantos reais o `tickets.py` cobra de um estudante numa quarta à noite?'),
  ('A quarter of the full price.', 'Um quarto do preço cheio.'), 9, 0, 'R$'),

Q('ex-8aa4fp7t', 'what-the-rule-does-not-say', 'medium',
  ('Before Joana answered, why could Lia not decide by testing whether R$ 9,00 was a defect?',
   'Antes de a Joana responder, por que a Lia não podia decidir testando se R$ 9,00 era um defeito?'),
  ('Where is the expected result written?', 'Onde está escrito o resultado esperado?'),
  C('The expected result for that input was written nowhere', 'O resultado esperado para essa entrada não estava escrito em lugar nenhum',
    'Right: no run can say what Joana meant.', 'Isso: nenhuma execução diz o que a Joana quis dizer.', ok=True),
  C('The program crashed', 'O programa quebrou', 'It printed a confident R$ 9,00.', 'Imprimiu um R$ 9,00 confiante.'),
  C('Wednesday tests are forbidden', 'Testes de quarta são proibidos', 'Nothing forbids them.', 'Nada os proíbe.'),
  C('She needed to read the code first', 'Ela precisava ler o código primeiro',
    'The code shows what it does, which she already knew; not what it should do.', 'O código mostra o que ele faz, que ela já sabia; não o que deveria fazer.')),

Q('ex-yxg1qxbe', 'what-the-rule-does-not-say', 'medium',
  ('What was Joana’s answer, which became the rule’s fifth sentence?',
   'Qual foi a resposta da Joana, que virou a quinta frase da regra?'),
  ('Half is…', 'Meia é…'),
  C('Half price is the most any ticket is reduced', 'Meia é o maior desconto que um ingresso recebe',
    'Right: so the student on Wednesday pays R$ 18,00.', 'Isso: então o estudante na quarta paga R$ 18,00.', ok=True),
  C('Reductions add up', 'Os descontos se somam', 'That is the reading she rejected.', 'Essa é a leitura que ela rejeitou.'),
  C('Students pay half every day except Wednesday, when they pay full price like everybody', 'Estudantes pagam meia todo dia menos quarta, quando pagam inteira como todo mundo',
    'On Wednesday everybody pays half.', 'Na quarta todo mundo paga meia.'),
  C('Wednesday discount is cancelled', 'O desconto de quarta foi cancelado', 'Wednesday stayed half price.', 'A quarta continuou com meia.')),

Q('ex-r61yhpzt', 'what-the-rule-does-not-say', 'hard',
  ('Rafael implemented exactly what was written. Where was the Wednesday defect, then?',
   'O Rafael implementou exatamente o que estava escrito. Onde estava o defeito da quarta, então?'),
  ('Written, or not written?', 'Escrito, ou não escrito?'),
  C('In what the requirement did not say', 'No que o requisito não dizia',
    'Right: two reductions, and no sentence for both at once.', 'Isso: dois descontos, e nenhuma frase para os dois ao mesmo tempo.', ok=True),
  C('In Rafael’s use of the `//` operator for division', 'No uso que o Rafael fez do operador `//` para dividir',
    'The division is correct; applying it twice is the issue.', 'A divisão está certa; aplicá-la duas vezes é o problema.'),
  C('In the test table', 'Na tabela de teste', 'The table found nothing wrong because it had no combinations.', 'A tabela não achou nada porque não tinha combinações.'),
  C('Nowhere: R$ 9,00 is the right price for a student on Wednesday', 'Em lugar nenhum: R$ 9,00 é o preço certo para estudante na quarta',
    'Joana’s answer makes it R$ 18,00.', 'A resposta da Joana o torna R$ 18,00.')),

Q('ex-1m9rr9z3', 'the-inputs-nobody-mentioned', 'easy',
  ('Why is a crash the easiest failure to judge?', 'Por que uma quebra é a falha mais fácil de julgar?'),
  ('Implicit.', 'Implícito.'),
  C('No requirement has to mention it', 'Nenhum requisito precisa mencioná-la',
    'Right: some outcomes are wrong whatever the rule says.', 'Isso: alguns resultados estão errados diga a regra o que disser.', ok=True),
  C('Crashes are rare', 'Quebras são raras', 'Rarity has nothing to do with judging.', 'Raridade não tem nada a ver com julgar.'),
  C('Tracebacks show the expected result for the input that caused them', 'Tracebacks mostram o resultado esperado para a entrada que os causou',
    'They show where it stopped, not what was expected.', 'Mostram onde parou, não o que se esperava.'),
  C('Customers report them politely', 'Clientes os relatam com educação', 'Not the argument.', 'Não é o argumento.')),

Q('ex-w8wfhg5k', 'the-inputs-nobody-mentioned', 'medium',
  ('Why does the lesson call the quiet failures worse than the crashes?',
   'Por que a aula chama as falhas silenciosas de piores que as quebras?'),
  ('A crash gets reported.', 'Uma quebra é relatada.'),
  C('Nothing on the screen says anything went wrong, so a wrong price gets paid', 'Nada na tela diz que algo deu errado, então um preço errado é pago',
    'Right: `Wed` charges full price with confidence.', 'Isso: `Wed` cobra inteira com confiança.', ok=True),
  C('They are more common', 'São mais comuns', 'The lesson does not count them.', 'A aula não as conta.'),
  C('They take longer to run', 'Demoram mais para rodar', 'Speed is not the issue.', 'Velocidade não é a questão.'),
  C('They only happen in production', 'Só acontecem em produção', 'Lia produced them in the lab.', 'A Lia as produziu no laboratório.')),

MC('ex-g76havyw', 'the-inputs-nobody-mentioned', 'medium',
  ('Which of these inputs did `tickets.py` accept and charge a price for, without complaint? Choose all that apply.',
   'Quais destas entradas o `tickets.py` aceitou e cobrou um preço, sem reclamar? Escolha todas as que se aplicam.'),
  ('Four quiet ones.', 'Quatro silenciosas.'),
  C('an age of `-5`', 'uma idade de `-5`', 'Yes: charged as a child.', 'Sim: cobrada como criança.', ok=True),
  C('`Wed` with a capital W', '`Wed` com W maiúsculo', 'Yes: full price on a Wednesday.', 'Sim: inteira numa quarta.', ok=True),
  C('an age of `sixty`', 'uma idade `sixty`', 'No: that one crashed.', 'Não: essa quebrou.'),
  C('a time of `25:00`', 'um horário `25:00`', 'Yes: charged as evening.', 'Sim: cobrado como noite.', ok=True),
  C('three words instead of four', 'três palavras em vez de quatro', 'No: that one crashed.', 'Não: essa quebrou.')),

Q('ex-na7gwsqf', 'the-inputs-nobody-mentioned', 'hard',
  ('The website sends the day from a set of buttons that always send `wed` in lower case. How much does the `Wed` defect matter there?',
   'O site manda o dia por um conjunto de botões que sempre mandam `wed` em minúsculas. Quanto o defeito do `Wed` importa ali?'),
  ('Who produces the input?', 'Quem produz a entrada?'),
  C('Little on the website, since `Wed` cannot arrive from there; it matters wherever someone types the day', 'Pouco no site, já que `Wed` não chega por lá; importa onde alguém digita o dia',
    'Right: ask who produces each input and what they could send.', 'Isso: pergunte quem produz cada entrada e o que poderia mandar.', ok=True),
  C('Not at all, anywhere', 'Nada, em lugar nenhum', 'The box office types days.', 'A bilheteria digita dias.'),
  C('It matters as much as a crash', 'Importa tanto quanto uma quebra', 'Whether it matters depends on the producer.', 'Se importa depende de quem produz.'),
  C('More than anything else', 'Mais que qualquer coisa', 'There is nothing to rank it on here.', 'Não há com o que classificá-lo aqui.')),

O('ex-wmd67wbc', 'drill', 'medium',
  ('Order the steps that turned the Wednesday combination into a fixable defect.',
   'Ordene os passos que transformaram a combinação da quarta num defeito corrigível.'),
  ('From a missing sentence to a test.', 'De uma frase que falta a um teste.'),
  [('run a student on a Wednesday', 'rodar um estudante numa quarta'),
   ('notice the rule has no expected result for it', 'perceber que a regra não tem resultado esperado para isso'),
   ('ask Joana, with the command that shows it', 'perguntar à Joana, com o comando que o mostra'),
   ('Joana answers: half is the most', 'a Joana responde: meia é o máximo'),
   ('the case becomes a test with an expected price', 'o caso vira um teste com preço esperado')],
  ('The answer comes before the test, because the answer is what the test checks against.', 'A resposta vem antes do teste, porque é contra ela que o teste confere.')),
]
