from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
Q('ex-jr47qz08', 'the-middle-ground', 'easy',
  ('What is grey-box testing?', 'O que é teste caixa cinza?'),
  ('Through the outside, with some knowledge of the inside.', 'Por fora, com algum conhecimento de dentro.'),
  C('Outside testing, inside knowledge', 'Teste por fora, saber de dentro',
    'Right: act like a user, check like an insider.', 'Isso: agir como cliente, conferir como quem conhece o sistema.', ok=True),
  C('Reading every line of the code before testing any of it, so nothing is missed', 'Ler cada linha do código antes de testar qualquer parte, para não perder nada',
    'That is white box.', 'Isso é caixa branca.'),
  C('Testing only from the written rule', 'Testar só pela regra escrita', 'That is black box.', 'Isso é caixa preta.'),
  C('Testing half the features', 'Testar metade das funcionalidades', 'Grey is about knowledge, not quantity.', 'Cinza é sobre conhecimento, não quantidade.')),

MC('ex-gmfxq7aq', 'the-middle-ground', 'medium',
  ('Which of these count as the partial knowledge grey box uses? Choose all that apply.',
   'Quais destes contam como o conhecimento parcial que a caixa cinza usa? Escolha todos os que se aplicam.'),
  ('A whiteboard, not the source.', 'Um quadro, não o código-fonte.'),
  C('which table an order is stored in', 'em que tabela um pedido fica guardado', 'Yes: the data.', 'Sim: os dados.', ok=True),
  C('that `orders.py` asks `tickets.py` for prices', 'que o `orders.py` pede preços ao `tickets.py`', 'Yes: the architecture.', 'Sim: a arquitetura.', ok=True),
  C('the exact order of every statement in `place`', 'a ordem exata de cada comando no `place`',
    'No: that is reading the code line by line, white box.', 'Não: isso é ler o código linha por linha, caixa branca.'),
  C('that a nightly report reads the `tickets` column', 'que um relatório da noite lê a coluna `tickets`', 'Yes: who reads the data.', 'Sim: quem lê os dados.', ok=True)),

Q('ex-k60are45', 'the-middle-ground', 'medium',
  ('Which grey-box check is worth making, by the lesson’s rule "look inside to see consequences"?',
   'Que conferência de caixa cinza vale a pena fazer, pela regra da aula "olhe por dentro para ver consequências"?'),
  ('What matters to somebody outside?', 'O que importa a alguém de fora?'),
  C('That a refused order leaves nothing the seats report will count', 'Que um pedido recusado não deixe nada que o relatório de assentos vá contar',
    'Right: the consequence is a person reading a wrong number.', 'Isso: a consequência é uma pessoa lendo um número errado.', ok=True),
  C('That the table has exactly four columns with exactly these names', 'Que a tabela tenha exatamente quatro colunas com exatamente estes nomes',
    'That breaks on a harmless rename; it pins down a detail.', 'Isso quebra numa renomeação inofensiva; fixa um detalhe.'),
  C('That the database file is under 1 MB', 'Que o arquivo do banco tenha menos de 1 MB', 'Nobody outside is affected by it here.', 'Ninguém de fora é afetado por isso aqui.'),
  C('That the code uses `isolation_level=None`', 'Que o código use `isolation_level=None`', 'A line of code, not a consequence.', 'Uma linha de código, não uma consequência.')),

Q('ex-76nxha3q', 'the-order-program', 'easy',
  ('What does `python -m sqlite3 aurora.db "SELECT * FROM orders"` do?',
   'O que faz `python -m sqlite3 aurora.db "SELECT * FROM orders"`?'),
  ('Python’s own database tool.', 'A ferramenta de banco do próprio Python.'),
  C('Prints every row of the `orders` table', 'Imprime toda linha da tabela `orders`',
    'Right: one query against the database file.', 'Isso: uma consulta contra o arquivo do banco.', ok=True),
  C('Places a new order with the default ages', 'Faz um pedido novo com as idades padrão', 'It only reads.', 'Só lê.'),
  C('Deletes the orders table and creates it again, empty', 'Apaga a tabela orders e a cria de novo, vazia',
    'SELECT changes nothing.', 'SELECT não muda nada.'),
  C('Installs SQLite', 'Instala o SQLite', 'It comes with Python.', 'Vem com o Python.')),

N('ex-w3xrh0am', 'the-order-program', 'easy',
  ('In centavos, what total did the database store for the Thursday family order of two adults and a child?',
   'Em centavos, que total o banco guardou para o pedido da família de quinta, dois adultos e uma criança?'),
  ('R$ 90,00.', 'R$ 90,00.'), 9000, 0, ('centavos', 'centavos')),

Q('ex-vjhpptav', 'the-order-program', 'medium',
  ('The screen said R$ 90,00 and the table says 9000. What did checking both establish?',
   'A tela disse R$ 90,00 e a tabela diz 9000. O que conferir os dois estabeleceu?'),
  ('Printing and storing are separate lines.', 'Imprimir e guardar são linhas separadas.'),
  C('That what the user was told is what the system recorded', 'Que o que foi dito ao usuário é o que o sistema registrou',
    'Right: two places that could have disagreed did not.', 'Isso: dois lugares que podiam discordar não discordaram.', ok=True),
  C('Nothing: they always agree', 'Nada: sempre concordam', 'They can disagree; that is why it is checked.', 'Podem discordar; é por isso que se confere.'),
  C('That the price rule is correct', 'Que a regra de preço está certa', 'Adults and a child on Thursday; the rule’s defects are elsewhere.', 'Adultos e criança na quinta; os defeitos da regra estão em outro lugar.'),
  C('That the order was paid for by card', 'Que o pedido foi pago no cartão', 'There is no payment here.', 'Não há pagamento aqui.')),

Q('ex-chzznnqh', 'what-the-screen-did-not-say', 'easy',
  ('What did the screen say when Lia ordered seven tickets?', 'O que a tela disse quando a Lia pediu sete ingressos?'),
  ('One too many.', 'Um a mais.'),
  C('Refused', 'Recusado',
    'Right: correct by the rule, on the screen.', 'Isso: certo pela regra, na tela.', ok=True),
  C('That the order was accepted at full price', 'Que o pedido foi aceito pelo preço cheio', 'It refused.', 'Recusou.'),
  C('An error trace from Python', 'Um traceback do Python', 'A clear message, no crash.', 'Uma mensagem clara, sem quebra.'),
  C('Nothing at all', 'Nada', 'It printed a refusal.', 'Imprimiu uma recusa.')),

Q('ex-w8jqpcvs', 'what-the-screen-did-not-say', 'medium',
  ('Why did the refused orders stay in the table?', 'Por que os pedidos recusados ficaram na tabela?'),
  ('What does `place` do first?', 'O que o `place` faz primeiro?'),
  C('The row is written before the check, and nothing removes it when the check refuses', 'A linha é gravada antes da conferência, e nada a remove quando a conferência recusa',
    'Right: every statement saves at once, so the row stays.', 'Isso: todo comando é salvo na hora, então a linha fica.', ok=True),
  C('SQLite ignores refusals', 'O SQLite ignora recusas', 'SQLite stores what it is told to.', 'O SQLite guarda o que mandam.'),
  C('The check is wrong about the limit of six', 'A conferência erra o limite de seis', 'The check refused correctly.', 'A conferência recusou corretamente.'),
  C('The report creates rows of its own when it adds up the tickets for each session', 'O relatório cria linhas próprias quando soma os ingressos de cada sessão',
    'The report only reads.', 'O relatório só lê.')),

N('ex-8retjf59', 'what-the-screen-did-not-say', 'easy',
  ('How many seats did the report show as sold for the Saturday matinée?', 'Quantos assentos o relatório mostrou vendidos para a matinê de sábado?'),
  ('Two real, seven refused.', 'Dois reais, sete recusados.'), 9, 0, ('seats', 'assentos')),

Q('ex-vwpabd4g', 'what-the-screen-did-not-say', 'hard',
  ('Which two facts about the architecture did Lia need to find this defect?',
   'De que dois fatos de arquitetura a Lia precisou para achar este defeito?'),
  ('Store and reader.', 'Armazém e leitor.'),
  C('Orders are stored in a table, and a report reads it', 'Os pedidos ficam guardados numa tabela, e um relatório a lê',
    'Right: the defect lives between the two.', 'Isso: o defeito mora entre os dois.', ok=True),
  C('The price rule is in another file', 'A regra de preço está em outro arquivo', 'True, and irrelevant to this defect.', 'Verdade, e irrelevante para este defeito.'),
  C('Python 3.12 can query SQLite from the command line with its own module', 'O Python 3.12 consulta o SQLite pela linha de comando com um módulo próprio',
    'A tool, not a fact about the system.', 'Uma ferramenta, não um fato sobre o sistema.'),
  C('Joana wrote the rule', 'A Joana escreveu a regra', 'Not architecture.', 'Não é arquitetura.')),

Q('ex-x3287h03', 'what-the-screen-did-not-say', 'hard',
  ('Why could black-box testing alone not have found the stored refused orders?',
   'Por que o teste caixa preta sozinho não acharia os pedidos recusados guardados?'),
  ('The screen was right both times.', 'A tela estava certa as duas vezes.'),
  C('Everything the user sees was correct', 'Tudo o que o usuário vê estava certo',
    'Right: the defect was in what was kept, not what was shown.', 'Isso: o defeito estava no que foi guardado, não no que foi mostrado.', ok=True),
  C('Black-box testers may not place orders', 'Quem testa como caixa preta não pode fazer pedidos', 'They placed them, and saw refusals.', 'Fizeram, e viram recusas.'),
  C('Seven tickets is not a boundary', 'Sete ingressos não é borda', 'It is exactly the boundary, one over six.', 'É exatamente a borda, um acima de seis.'),
  C('The program crashed before printing anything', 'O programa quebrou antes de imprimir', 'It printed a clear message.', 'Imprimiu uma mensagem clara.')),

Q('ex-v491ecks', 'choosing-with-a-map', 'medium',
  ('`orders.py` asks `tickets.py` for every price. What follows for the defects of `tickets.py`?',
   'O `orders.py` pede todo preço ao `tickets.py`. O que decorre para os defeitos do `tickets.py`?'),
  ('Defects travel along arrows.', 'Defeitos viajam pelas setas.'),
  C('Each is also a defect in an order', 'Cada um também é um defeito num pedido',
    'Right: a child on Wednesday costs R$ 9,00 in an order too.', 'Isso: uma criança na quarta custa R$ 9,00 num pedido também.', ok=True),
  C('Orders are immune to them, because orders add up the prices and round the total', 'Pedidos são imunes a eles, porque pedidos somam os preços e arredondam o total',
    'Adding wrong prices gives a wrong total.', 'Somar preços errados dá total errado.'),
  C('Every price case must be run again through `orders.py`', 'Todo caso de preço precisa rodar de novo pelo `orders.py`',
    'One or two confirm the arrow; the rest follow.', 'Um ou dois confirmam a seta; o resto segue.'),
  C('They cancel out', 'Eles se anulam', 'Nothing cancels; they add up.', 'Nada se anula; eles se somam.')),

M('ex-9z26qsda', 'choosing-with-a-map', 'medium',
  ('Match each part of the map to the question to ask there.', 'Associe cada parte do mapa à pergunta a fazer ali.'),
  ('Three questions.', 'Três perguntas.'),
  [(('an arrow', 'uma seta'), ('is the information in the same form on both sides?', 'a informação está no mesmo formato dos dois lados?')),
   (('a store', 'um armazém'), ('is it kept only when it should be?', 'fica guardada só quando deve?')),
   (('a reader', 'um leitor'), ('does it read the data with the meaning it was written with?', 'lê o dado com o sentido com que ele foi escrito?'))]),

M('ex-gnxpwmgx', 'choosing-with-a-map', 'hard',
  ('Match each defect of this course to the approach that found it here.', 'Associe cada defeito deste curso à abordagem que o achou aqui.'),
  ('The table at the end.', 'A tabela do fim.'),
  [(('the Wednesday stacking', 'a soma de descontos da quarta'), ('black box', 'caixa preta')),
   (('refused orders counted as seats sold', 'pedidos recusados contados como vendidos'), ('grey box', 'caixa cinza')),
   (('the line for over-sixties that no case ran', 'a linha dos maiores de sessenta que nenhum caso rodou'), ('white box', 'caixa branca'))]),

Q('ex-qnj41tm9', 'choosing-with-a-map', 'hard',
  ('As systems grow, where does the lesson say more and more defects live?', 'Conforme os sistemas crescem, onde a aula diz que cada vez mais defeitos moram?'),
  ('Between.', 'Entre.'),
  C('Between parts that each work', 'Entre partes que funcionam cada uma',
    'Right: the boxes disagree about what they hand each other.', 'Isso: as caixas discordam sobre o que entregam umas às outras.', ok=True),
  C('Inside the biggest file', 'Dentro do maior arquivo', 'Size is not the argument.', 'Tamanho não é o argumento.'),
  C('In the database engine', 'No motor do banco', 'SQLite did what it was told.', 'O SQLite fez o que mandaram.'),
  C('In the user interface, which changes more often than any other part of a system', 'Na interface, que muda mais do que qualquer outra parte de um sistema',
    'Not what the lesson argues.', 'Não é o que a aula defende.')),

O('ex-yrp2zspz', 'drill', 'medium',
  ('Order the steps of the grey-box test that found the refused orders.', 'Ordene os passos do teste caixa cinza que achou os pedidos recusados.'),
  ('Act, look, follow the consequence.', 'Agir, olhar, seguir a consequência.'),
  [('order seven tickets', 'pedir sete ingressos'), ('see the screen refuse', 'ver a tela recusar'),
   ('query the orders table', 'consultar a tabela orders'), ('find the refused order stored', 'achar o pedido recusado guardado'),
   ('run the report that reads it', 'rodar o relatório que a lê')],
  ('The report comes last because it shows who the stored row harms.', 'O relatório vem por último porque mostra a quem a linha guardada prejudica.')),
]
