from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
Q('ex-spk7p0rg', 'the-famous-curve', 'easy',
  ('Whose book of 1981 is the best-known source of the cost-of-defect curve?',
   'De quem é o livro de 1981 que é a fonte mais conhecida da curva de custo do defeito?'),
  ('Software Engineering Economics.', 'Software Engineering Economics.'),
  C('Barry Boehm', 'Barry Boehm', 'Right: data from large projects of the 1970s.', 'Isso: dados de grandes projetos dos anos 1970.', ok=True),
  C('Laurent Bossavit, who studied where the chart came from', 'Laurent Bossavit, que estudou de onde veio o gráfico',
    'Bossavit is the critic who traced the citations.', 'Bossavit é o crítico que rastreou as citações.'),
  C('Larry Smith', 'Larry Smith', 'He coined "shift left", in 2001.', 'Ele cunhou "shift left", em 2001.'),
  C('Edsger Dijkstra', 'Edsger Dijkstra', 'Dijkstra’s sentence is about presence and absence.', 'A frase de Dijkstra é sobre presença e ausência.')),

Q('ex-59q24v4d', 'the-famous-curve', 'medium',
  ('In Boehm and Basili’s list of 2001, what ratio did they give for small, non-critical systems?',
   'Na lista de Boehm e Basili de 2001, que razão eles deram para sistemas pequenos e não críticos?'),
  ('The sentence nobody quotes.', 'A frase que ninguém cita.'),
  C('About 5 to 1', 'Cerca de 5 para 1', 'Right: against "often 100" for the large ones.', 'Isso: contra "muitas vezes 100" para os grandes.', ok=True),
  C('Often 100 to 1, the same as for large systems', 'Muitas vezes 100 para 1, o mesmo que para os grandes',
    'That is the large, critical case.', 'Esse é o caso grande e crítico.'),
  C('1 to 1: no difference at all', '1 para 1: nenhuma diferença',
    'The paper still found late fixes dearer; less so.', 'O artigo ainda achou correções tardias mais caras; menos.'),
  C('Around 1000 to 1, because they ship more often', 'Por volta de 1000 para 1, porque entregam mais vezes',
    'Shipping often flattens the curve, if anything.', 'Entregar com frequência achata a curva, se é que muda algo.')),

Q('ex-1wgpz1am', 'the-famous-curve', 'medium',
  ('What did Laurent Bossavit find when he traced the chart back to its sources?',
   'O que Laurent Bossavit achou quando rastreou o gráfico até as fontes?'),
  ('Follow the citations.', 'Siga as citações.'),
  C('A chain of citations whose numbers drifted, some with no data behind them', 'Uma corrente de citações cujos números mudavam, algumas sem dado por trás',
    'Right: a book quoting a paper quoting a talk.', 'Isso: um livro citando um artigo citando uma palestra.', ok=True),
  C('A large modern study confirming 100 to 1', 'Um grande estudo moderno confirmando 100 para 1',
    'Later studies of short-cycle projects found flatter curves.', 'Estudos posteriores de projetos em ciclo curto acharam curvas mais planas.'),
  C('That the curve runs the other way', 'Que a curva vai ao contrário',
    'Nothing says a late defect is cheaper.', 'Nada diz que um defeito tardio é mais barato.'),
  C('Proof that Boehm made his data up', 'Prova de que Boehm inventou os dados',
    'Boehm’s data was real; the trouble is how it was copied and generalised.', 'Os dados de Boehm eram reais; o problema é como foram copiados e generalizados.')),

Q('ex-d0p8z419', 'the-famous-curve', 'hard',
  ('A manager who ships every day says "the hundred-times rule is nonsense here". What is the strongest reply this lesson gives you?',
   'Um gerente que entrega todo dia diz "a regra das cem vezes não vale aqui". Qual a resposta mais forte que esta aula te dá?'),
  ('Mechanism, not multiplier.', 'Mecanismo, não multiplicador.'),
  C('Argue from what this defect would cost if it shipped', 'Argumentar pelo que este defeito custaria em produção',
    'Right: the ratio depends on the project; refunds and Célia’s evening do not need one.', 'Isso: a razão depende do projeto; os reembolsos e a noite da Célia não precisam de uma.', ok=True),
  C('Quote Boehm’s 1981 book', 'Citar o livro de Boehm de 1981',
    'That invites a debate about a chart, and on his project the manager may be right.', 'Isso convida um debate sobre um gráfico, e no projeto dele o gerente pode ter razão.'),
  C('Say testing should then stop', 'Dizer que então o teste deve parar',
    'A flatter curve does not mean defects are free.', 'Uma curva mais plana não quer dizer que defeitos são de graça.'),
  C('Show the curve again, in log scale', 'Mostrar a curva de novo, em escala log',
    'Same chart, same debate.', 'Mesmo gráfico, mesmo debate.')),

M('ex-kgcyfbpr', 'what-grows', 'medium',
  ('Match each thing that grows to an example of it at Cine Aurora.',
   'Associe cada coisa que cresce a um exemplo dela no Cine Aurora.'),
  ('Four reasons, four examples.', 'Quatro motivos, quatro exemplos.'),
  [(('what is built on top', 'o que é construído em cima'), ('the seat map built on a wrong idea of a reservation', 'o mapa de assentos construído sobre uma ideia errada de reserva')),
   (('who has met it', 'quem topou com ele'), ('a pensioner refunded at the counter', 'um aposentado reembolsado no balcão')),
   (('who remembers why', 'quem lembra por quê'), ('Rafael, six months after writing the line', 'o Rafael, seis meses depois de escrever a linha')),
   (('steps a fix goes through', 'passos por que a correção passa'), ('report, triage, fix, review, retest, release', 'relato, triagem, correção, revisão, reteste, entrega'))]),

Q('ex-91vw76mz', 'what-grows', 'medium',
  ('Why do defects in requirements and design grow fastest?',
   'Por que os defeitos de requisito e de projeto crescem mais rápido?'),
  ('What gets built on them?', 'O que se constrói sobre eles?'),
  C('Everything after them is built on top', 'Tudo depois deles é construído em cima',
    'Right: the defect does not grow, its dependants do.', 'Isso: o defeito não cresce, o que depende dele cresce.', ok=True),
  C('They are harder to see in a running program than a wrong price is', 'São mais difíceis de ver num programa rodando do que um preço errado',
    'Visibility is a separate matter; growth comes from what depends on them.', 'Visibilidade é outra questão; o crescimento vem do que depende deles.'),
  C('Because testers are not allowed to read requirements', 'Porque quem testa não pode ler requisitos',
    'Reading requirements is exactly what prevents them.', 'Ler requisitos é justamente o que os previne.'),
  C('Requirements change every week', 'Requisitos mudam toda semana',
    'Change rate is not the mechanism named.', 'A taxa de mudança não é o mecanismo citado.')),

Q('ex-19y9c45d', 'what-grows', 'medium',
  ('Which of the four costs can be cut without finding any defect earlier?',
   'Qual dos quatro custos pode ser reduzido sem achar defeito nenhum mais cedo?'),
  ('Tests and requirements kept beside the code.', 'Testes e requisitos guardados ao lado do código.'),
  C('The lost context', 'O contexto perdido',
    'Right: tests that say what the code is for are context that does not decay.', 'Isso: testes que dizem para que o código serve são contexto que não se perde.', ok=True),
  C('What has been built on top of the defect by the time it is found', 'O que foi construído em cima do defeito até ele ser achado',
    'That only shrinks if the defect is found sooner.', 'Isso só diminui se o defeito for achado mais cedo.'),
  C('Who has met it', 'Quem topou com ele', 'Only finding it before release keeps that to the team.', 'Só achá-lo antes da entrega mantém isso dentro do time.'),
  C('None of them', 'Nenhum deles', 'One of them can.', 'Um deles pode.')),

Q('ex-q8smxfqv', 'what-grows', 'hard',
  ('Before release, a defect is a technical problem. What does the lesson say it becomes after release?',
   'Antes da entrega, um defeito é um problema técnico. O que a aula diz que ele vira depois?'),
  ('Customers, Célia, sometimes a regulator.', 'Clientes, a Célia, às vezes um regulador.'),
  C('A commercial problem, and in some domains a legal one', 'Um problema comercial, e em alguns domínios jurídico',
    'Right: the fix in the code is the same; everything around it is not.', 'Isso: a correção no código é a mesma; tudo em volta dela não é.', ok=True),
  C('A bigger technical problem, since the code fix is harder after release', 'Um problema técnico maior, já que a correção no código fica mais difícil',
    'The fix may be the same character; the cost moved elsewhere.', 'A correção pode ser o mesmo caractere; o custo foi para outro lugar.'),
  C('The customer’s problem, no longer the team’s', 'Problema do cliente, não mais do time',
    'It is very much the team’s, with more people involved.', 'É muito do time, com mais gente envolvida.'),
  C('Nothing different', 'Nada diferente', 'Refunds and conversations are new costs.', 'Reembolsos e conversas são custos novos.')),

N('ex-309hc9yg', 'a-month-of-sales', 'easy',
  ('How many tickets did `overcharge.py` find sold to a sixty-year-old outside a Wednesday?',
   'Quantos ingressos o `overcharge.py` achou vendidos a alguém de sessenta anos fora da quarta?'),
  ('The second line of its output.', 'A segunda linha da saída.'), 41, 0, ('tickets', 'ingressos')),

N('ex-x963eh74', 'a-month-of-sales', 'easy',
  ('How many reais did `overcharge.py` find charged too much in the month?',
   'Quantos reais o `overcharge.py` achou cobrados a mais no mês?'),
  ('The last line.', 'A última linha.'), 658, 0, 'R$'),

Q('ex-vcbhznkf', 'a-month-of-sales', 'medium',
  ('Why does `overcharge.py` skip Wednesdays?',
   'Por que o `overcharge.py` pula as quartas?'),
  ('What does everybody pay on a Wednesday?', 'Quanto todo mundo paga na quarta?'),
  C('Everyone pays half then, so a sixty-year-old loses nothing', 'Todos pagam meia nesse dia, então quem tem sessenta anos não perde nada',
    'Right: the Wednesday rule masks the defect that day.', 'Isso: a regra da quarta esconde o defeito nesse dia.', ok=True),
  C('The cinema is closed on Wednesdays', 'O cinema fecha às quartas',
    'Wednesday is the half-price day, not a closed one.', 'Quarta é o dia da meia, não de fechar.'),
  C('`tickets.py` crashes for "wed"', 'O `tickets.py` quebra com "wed"',
    'It prints a price for Wednesday; lesson 1 ran one.', 'Imprime um preço para quarta; a aula 1 rodou um.'),
  C('Sales on Wednesdays are generated without a seed and change every run', 'As vendas de quarta são geradas sem semente e mudam a cada execução',
    'One seed makes the whole month.', 'Uma semente produz o mês inteiro.')),

Q('ex-9w8pzp2s', 'a-month-of-sales', 'hard',
  ('The count says R$ 658,00. Why does the lesson call that number the floor of the cost?',
   'A conta diz R$ 658,00. Por que a aula chama esse número de piso do custo?'),
  ('What is not in the output?', 'O que não está na saída?'),
  C('Everything it does not count comes on top', 'Tudo o que ela não conta vem por cima',
    'Right: finding the customers, refund fees and Célia’s evenings are all extra.', 'Isso: achar os clientes, as tarifas de estorno e as noites da Célia vêm por cima.', ok=True),
  C('Because the sales are invented', 'Porque as vendas são inventadas',
    'The prices are the shop’s own; the invented month is a plausible stand-in.', 'Os preços são da própria loja; o mês inventado é um substituto plausível.'),
  C('Because the program contains an error', 'Porque o programa contém um erro',
    'The program counts correctly what it says it counts.', 'O programa conta corretamente o que diz contar.'),
  C('It is the lowest price a ticket can have', 'É o menor preço que um ingresso pode ter',
    'It is a total, not a price.', 'É um total, não um preço.')),

Q('ex-kr4sy2bt', 'shift-left', 'easy',
  ('What does "shift left" mean?', 'O que quer dizer "shift left"?'),
  ('Draw the lifecycle left to right.', 'Desenhe o ciclo da esquerda para a direita.'),
  C('Doing quality work earlier', 'Fazer o trabalho de qualidade mais cedo',
    'Right: reviewing requirements, testing as code is written.', 'Isso: revisar requisitos, testar enquanto se escreve o código.', ok=True),
  C('Removing the testing that used to happen at the end', 'Tirar o teste que ficava no fim do projeto',
    'That is stopping detection, not shifting anything.', 'Isso é parar de detectar, não deslocar nada.'),
  C('Moving testers to another team', 'Mover quem testa para outro time',
    'It is about when, not where people sit.', 'É sobre quando, não onde as pessoas ficam.'),
  C('Testing in production', 'Testar em produção', 'That is shift right.', 'Isso é shift right.')),

Q('ex-cn0vp2a4', 'shift-left', 'medium',
  ('Which of these is shift right rather than shift left?',
   'Qual destes é shift right, e não shift left?'),
  ('After release.', 'Depois da entrega.'),
  C('Releasing a change to a few customers first and watching what happens', 'Liberar uma mudança para poucos clientes primeiro e observar o que acontece',
    'Right: it finds what only real use can show, quickly.', 'Isso: acha o que só o uso real mostra, rápido.', ok=True),
  C('Reviewing the requirement with the product owner before the sprint starts', 'Revisar o requisito com a dona do produto antes de a sprint começar',
    'That is as far left as it goes.', 'Isso é o mais à esquerda possível.'),
  C('Writing a test before the code', 'Escrever um teste antes do código', 'Left, and lesson 15.', 'Esquerda, e aula 15.'),
  C('Asking "over 60, or 60 and over?"', 'Perguntar "maiores de 60, ou a partir de 60?"', 'Prevention in a sentence: left.', 'Prevenção numa frase: esquerda.')),

Q('ex-1m24skc2', 'shift-left', 'hard',
  ('A tester proposes three people review every requirement for an hour, including a one-line label change. What question does the lesson say to ask?',
   'Alguém que testa propõe que três pessoas revisem todo requisito por uma hora, inclusive a troca de um rótulo de uma linha. Que pergunta a aula diz para fazer?'),
  ('Can we, or should we?', 'Dá para, ou vale a pena?'),
  C('Is it worth finding this earlier?', 'Vale a pena achar isto mais cedo?',
    'Right: a label has nothing built on it; a reservation model does.', 'Isso: um rótulo não tem nada construído em cima; um modelo de reserva tem.', ok=True),
  C('Can it be found earlier?', 'Dá para achar mais cedo?', 'Almost always yes, so it decides nothing.', 'Quase sempre sim, então não decide nada.'),
  C('Is the hundred-times rule true for labels?', 'A regra das cem vezes vale para rótulos?',
    'The ratio is not how to decide.', 'A razão não é como se decide.'),
  C('Who is to blame for the label?', 'Quem é culpado pelo rótulo?', 'Blame is lesson 18’s non-question.', 'Culpa é a não-pergunta da aula 18.')),

O('ex-vwqez3hp', 'drill', 'medium',
  ('Order these moments for finding the sixty-year-old’s defect from cheapest to dearest.',
   'Ordene estes momentos de achar o defeito da pessoa de sessenta anos, do mais barato ao mais caro.'),
  ('Count what has grown at each.', 'Conte o que cresceu em cada um.'),
  [('reading the requirement', 'lendo o requisito'), ('reviewing the code', 'revisando o código'),
   ('testing the release', 'testando a entrega'), ('a month after release', 'um mês depois da entrega')],
  ('The order of the lifecycle and the order of cost coincide for this defect.',
   'A ordem do ciclo e a ordem do custo coincidem para este defeito.')),

Q('ex-3rehggb3', 'drill', 'hard',
  ('A misspelt word on the help page and a wrong rule for holding seats are both found a month after release. Which statement fits this lesson?',
   'Uma palavra com erro na página de ajuda e uma regra errada de reserva de assentos são achadas um mês depois da entrega. Que afirmação combina com esta aula?'),
  ('The ratio depends on the defect.', 'A razão depende do defeito.'),
  C('The seat rule cost far more for the wait', 'A regra dos assentos custou muito mais pela espera',
    'Right: what grew depends on what was built on it and who met it.', 'Isso: o que cresceu depende do que foi construído em cima e de quem topou com ele.', ok=True),
  C('Both cost a hundred times more than if found in the requirement', 'Os dois custaram cem vezes mais do que se achados no requisito',
    'A fixed multiplier is exactly the claim the lesson questions.', 'Um multiplicador fixo é exatamente a afirmação que a aula questiona.'),
  C('Neither matters once the month is over', 'Nenhum importa passado o mês',
    'The seat rule has a month of reservations built on it.', 'A regra de reserva tem um mês de reservas construídas em cima.'),
  C('The typo cost more, because more people read the help page than reserve seats', 'O erro de grafia custou mais, porque mais gente lê a ajuda do que reserva assentos',
    'Being read is not the same as being harmed by it.', 'Ser lido não é o mesmo que causar dano.')),
]
