from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
Q('ex-4we5txbj', 'what-quality-means', 'easy',
  ('Whose definition of quality is "conformance to requirements"?',
   'De quem é a definição de qualidade como "conformidade com os requisitos"?'),
  ('Manufacturing, 1979.', 'Indústria, 1979.'),
  C('Philip Crosby', 'Philip Crosby', 'Right: in 1979, writing about manufacturing.', 'Isso: em 1979, escrevendo sobre indústria.', ok=True),
  C('Joseph Juran, in his handbook', 'Joseph Juran, no seu manual',
    'Juran’s is fitness for use, from 1951.', 'A de Juran é adequação ao uso, de 1951.'),
  C('Gerald Weinberg', 'Gerald Weinberg',
    'Weinberg’s is value to some person.', 'A de Weinberg é valor para alguém.'),
  C('W. Edwards Deming, who argued for building quality into the process', 'W. Edwards Deming, que defendia pôr a qualidade dentro do processo',
    'Deming argued about process; the phrase is Crosby’s.', 'Deming falava de processo; a frase é de Crosby.')),

Q('ex-nqc8rscs', 'what-quality-means', 'medium',
  ('`tickets.py` conforms to one reading of "over-60s" and still overcharges a sixty-year-old. What does that show about conformance as a definition?',
   'O `tickets.py` está conforme uma leitura de "maiores de 60" e mesmo assim cobra a mais de quem tem sessenta. O que isso mostra sobre a conformidade como definição?'),
  ('Conformance to what?', 'Conformidade com o quê?'),
  C('It is only as good as the requirement it conforms to', 'Ela só é tão boa quanto o requisito com que se conforma',
    'Right: the code met the words and the words allowed the wrong thing.', 'Isso: o código cumpriu as palavras e as palavras permitiam a coisa errada.', ok=True),
  C('It cannot be checked', 'Ela não pode ser verificada',
    'Its great strength is that it can: the output is compared with the rule.', 'A grande força dela é justamente poder: a saída é comparada com a regra.'),
  C('It only applies to manufacturing and not to software', 'Ela só se aplica à indústria e não ao software',
    'Testers use it every time they compare an output with a written rule.', 'Quem testa a usa toda vez que compara uma saída com uma regra escrita.'),
  C('It is the same thing as fitness for use', 'É a mesma coisa que adequação ao uso',
    'The case shows exactly where the two part company.', 'O caso mostra exatamente onde as duas se separam.')),

Q('ex-mmjmp8zy', 'what-quality-means', 'medium',
  ('Weinberg defined quality as value to some person. Which question does that definition force that the others skip?',
   'Weinberg definiu qualidade como valor para alguém. Que pergunta essa definição obriga a fazer, que as outras pulam?'),
  ('The last two words.', 'As duas últimas palavras.'),
  C('Valuable to whom?', 'Valor para quem?',
    'Right: the customer, the accountant and the next developer value different things.', 'Isso: o cliente, o contador e o próximo desenvolvedor valorizam coisas diferentes.', ok=True),
  C('Does the output match the written rule?', 'A saída bate com a regra escrita?',
    'That is conformance’s question, and the one the others already ask.', 'Essa é a pergunta da conformidade, e a que as outras já fazem.'),
  C('How many defects are left in the product at release?', 'Quantos defeitos restam no produto na entrega?',
    'A count of defects is no definition’s question here; the first sentence of the section rejects it.', 'Uma contagem de defeitos não é a pergunta de nenhuma definição aqui; a primeira frase da seção a rejeita.'),
  C('How fast is the product?', 'Quão rápido é o produto?',
    'Speed is one characteristic, which the next section splits out.', 'Velocidade é uma característica, que a próxima seção separa.')),

Q('ex-bfhqspc8', 'what-quality-means', 'hard',
  ('A report screen shows every sale correctly, as specified, and the accountant still exports everything to a spreadsheet to add a column the screen lacks. Which definition does the screen fail?',
   'Uma tela de relatório mostra toda venda corretamente, como especificado, e o contador ainda exporta tudo para uma planilha para acrescentar uma coluna que a tela não tem. Em que definição a tela falha?'),
  ('It meets the specification.', 'Ela cumpre a especificação.'),
  C('Fitness for use, and value to the accountant', 'Adequação ao uso, e valor para o contador',
    'Right: it conforms, and the person using it cannot do what they came to do.', 'Isso: está conforme, e quem a usa não consegue fazer o que veio fazer.', ok=True),
  C('Conformance to requirements', 'Conformidade com os requisitos',
    'It shows every sale as specified, so it conforms.', 'Mostra toda venda como especificado, então está conforme.'),
  C('None: correct output means good quality', 'Nenhuma: saída correta quer dizer boa qualidade',
    'Correct output is conformance, one definition of three.', 'Saída correta é conformidade, uma definição de três.'),
  C('All three, since it has a defect in its calculations', 'As três, já que tem um defeito nos cálculos',
    'Nothing says the calculations are wrong; a column is missing.', 'Nada diz que os cálculos estão errados; falta uma coluna.')),

Q('ex-r452cadv', 'iso-25010', 'easy',
  ('How many characteristics does the 2023 product quality model of ISO/IEC 25010 name?',
   'Quantas características o modelo de qualidade de produto da ISO/IEC 25010 de 2023 cita?'),
  ('Safety was added.', 'A proteção foi acrescentada.'),
  C('Nine', 'Nove', 'Right: from functional suitability to safety.', 'Isso: da adequação funcional à proteção.', ok=True),
  C('Eight, the same as in 2011', 'Oito, as mesmas de 2011',
    'Eight was 2011; 2023 added safety.', 'Oito era 2011; 2023 acrescentou proteção.'),
  C('Five, the levels of maturity it defines', 'Cinco, os níveis de maturidade que ela define',
    'Five maturity levels are CMMI’s, a process model.', 'Cinco níveis de maturidade são do CMMI, um modelo de processo.'),
  C('Three: conformance, fitness for use and value', 'Três: conformidade, adequação ao uso e valor',
    'Those are three definitions of quality, not the standard’s characteristics.', 'Essas são três definições de qualidade, não as características da norma.')),

M('ex-bs8k1ahs', 'iso-25010', 'medium',
  ('Match each Cine Aurora concern to the ISO/IEC 25010 characteristic it belongs to.',
   'Associe cada preocupação do Cine Aurora à característica da ISO/IEC 25010 a que ela pertence.'),
  ('One question per characteristic.', 'Uma pergunta por característica.'),
  [(('a blind customer buying with a screen reader', 'um cliente cego comprando com leitor de tela'), ('interaction capability', 'capacidade de interação')),
   (('sales on the night a blockbuster opens', 'as vendas na noite de estreia de um sucesso'), ('reliability', 'confiabilidade')),
   (('a new price rule added without breaking the old ones', 'uma regra de preço nova sem quebrar as antigas'), ('maintainability', 'manutenibilidade')),
   (('nobody reading another customer’s orders', 'ninguém lendo o pedido de outro cliente'), ('security', 'segurança')),
   (('the right price for every customer', 'o preço certo para todo cliente'), ('functional suitability', 'adequação funcional'))]),

Q('ex-ctb94hyy', 'iso-25010', 'medium',
  ('What is the ISO/IEC 25010 product model most useful for, according to this lesson?',
   'Para que o modelo de produto da ISO/IEC 25010 é mais útil, segundo esta aula?'),
  ('"We never thought of it."', '"Nunca pensamos nisso."'),
  C('A checklist against forgetting a characteristic', 'Uma lista contra esquecer uma característica',
    'Right: it turns "we never thought of it" into "we decided not to".', 'Isso: transforma "nunca pensamos nisso" em "decidimos não fazer".', ok=True),
  C('A procedure saying how to test each characteristic', 'Um procedimento dizendo como testar cada característica',
    'It is a vocabulary: it says what to ask about, not how.', 'É um vocabulário: diz sobre o que perguntar, não como.'),
  C('Proof that every characteristic has been tested equally, for an auditor', 'Prova de que toda característica foi testada por igual, para um auditor',
    'Equal testing is not the aim; which ones matter is a choice.', 'Testar por igual não é o objetivo; quais importam é uma escolha.'),
  C('Certifying the company', 'Certificar a empresa',
    'Certifying an organisation is ISO 9001’s business, and it is about process.', 'Certificar uma organização é coisa da ISO 9001, e é sobre processo.')),

Q('ex-xap8c38h', 'iso-25010', 'hard',
  ('A team tests functions every sprint and leaves "non-functional testing for the big release". What does the lesson say is wrong with that?',
   'Um time testa funções a cada sprint e deixa "o teste não funcional para a grande entrega". O que a aula diz que está errado nisso?'),
  ('What does a customer call a forty-second seat map?', 'Como um cliente chama um mapa de assentos de quarenta segundos?'),
  C('The split makes eight characteristics look like extras, which in practice go untested', 'A divisão faz oito características parecerem extras, que na prática ficam sem teste',
    'Right: "before the big release" in practice means never, and a customer does not make the distinction.', 'Isso: "antes da grande entrega" na prática quer dizer nunca, e o cliente não faz a distinção.', ok=True),
  C('Non-functional testing is illegal before a release', 'Teste não funcional é proibido antes de uma entrega',
    'Nothing forbids it; the problem is the opposite.', 'Nada o proíbe; o problema é o contrário.'),
  C('Nothing: the other eight belong to a later course', 'Nada: as outras oito são de um curso posterior',
    'Testing them in depth is a later course; asking about them early belongs here.', 'Testá-las a fundo é de um curso posterior; perguntar por elas cedo é daqui.'),
  C('Functions change less often than performance', 'Funções mudam menos que desempenho',
    'The lesson says nothing of the sort; the issue is when the questions are asked.', 'A aula não diz nada disso; a questão é quando as perguntas são feitas.')),

Q('ex-7ryta186', 'a-requirement-you-can-check', 'easy',
  ('"The shop must be fast." What is wrong with it as a requirement?',
   '"A loja precisa ser rápida." O que há de errado nisso como requisito?'),
  ('When would a tester be finished?', 'Quando quem testa terminaria?'),
  C('Nobody can say what would count as failing it', 'Ninguém consegue dizer o que contaria como falhar',
    'Right: "compared with what?", and no tester can say when they have finished.', 'Isso: "comparada com o quê?", e ninguém que testa consegue dizer quando terminou.', ok=True),
  C('Speed is not a quality characteristic', 'Velocidade não é uma característica de qualidade',
    'It is: performance efficiency.', 'É sim: eficiência de desempenho.'),
  C('It belongs in the code and not in a requirement', 'Isso pertence ao código e não a um requisito',
    'A quality requirement is exactly where it belongs, once it is checkable.', 'Um requisito de qualidade é exatamente o lugar, quando ele é verificável.'),
  C('A product owner may not write requirements about performance', 'Uma dona do produto não pode escrever requisitos de desempenho',
    'She is the one who should choose the numbers.', 'É ela quem deve escolher os números.')),

O('ex-1hny1mtm', 'a-requirement-you-can-check', 'easy',
  ('Put the four questions that make a quality requirement checkable in the order the lesson asks them.',
   'Ponha as quatro perguntas que tornam um requisito de qualidade verificável na ordem em que a aula as faz.'),
  ('Start with the actor.', 'Comece pelo ator.'),
  [('who is doing something?', 'quem está fazendo algo?'),
   ('doing what?', 'fazendo o quê?'),
   ('under what conditions?', 'em que condições?'),
   ('how much is enough?', 'quanto basta?')],
  ('The number comes last, once the task and the conditions say what it is a number of.',
   'O número vem por último, quando a tarefa e as condições dizem do que ele é número.')),

Q('ex-fa9k7w3p', 'a-requirement-you-can-check', 'medium',
  ('Lia turns "easy to use" into "five regular customers each buy two tickets without help in under three minutes". Who should choose the five and the three?',
   'A Lia transforma "fácil de usar" em "cinco clientes fiéis compram dois ingressos cada um sem ajuda em menos de três minutos". Quem deve escolher o cinco e o três?'),
  ('Who knows what the cinema can afford?', 'Quem sabe o que o cinema pode pagar?'),
  C('Joana, the product owner', 'A Joana, a dona do produto',
    'Right: the numbers are decisions, and she knows what customers put up with.', 'Isso: os números são decisões, e ela sabe o que os clientes aguentam.', ok=True),
  C('Lia, since she wrote the sentence', 'A Lia, já que ela escreveu a frase',
    'Her job was to make the choice visible, not to make it.', 'O trabalho dela era tornar a escolha visível, não fazê-la.'),
  C('Rafael, who will have to build the shop to meet them', 'O Rafael, que vai ter de construir a loja para cumpri-los',
    'He can say what they cost; deciding is the product owner’s.', 'Ele pode dizer quanto custam; decidir é da dona do produto.'),
  C('The standard ISO/IEC 25010', 'A norma ISO/IEC 25010',
    'The standard names characteristics and sets no numbers.', 'A norma dá nome às características e não fixa números.')),

Q('ex-h31etz3b', 'a-requirement-you-can-check', 'hard',
  ('Asking what "must not lose sales" meant made Joana and Rafael disagree. What did the question achieve?',
   'Perguntar o que "não pode perder vendas" queria dizer fez a Joana e o Rafael discordarem. O que a pergunta conseguiu?'),
  ('Before or after the code?', 'Antes ou depois do código?'),
  C('It exposed the disagreement before anything was built', 'Expôs o desacordo antes de qualquer coisa ser construída',
    'Right: otherwise the first to find the difference is a customer.', 'Isso: senão o primeiro a achar a diferença é um cliente.', ok=True),
  C('It caused a conflict that a tester should avoid', 'Causou um conflito que quem testa deveria evitar',
    'The conflict was already there, hidden in four words.', 'O conflito já estava lá, escondido em quatro palavras.'),
  C('It proved the payment provider is unreliable', 'Provou que o provedor de pagamento não é confiável',
    'Rafael’s figure about failures is a constraint the requirement had to accept, not the point.', 'O número do Rafael sobre falhas é uma restrição que o requisito precisou aceitar, não o ponto.'),
  C('It detected a defect in the payment code that had been there since launch', 'Detectou um defeito no código de pagamento que estava lá desde o lançamento',
    'Nothing had been built; this is prevention, not detection.', 'Nada tinha sido construído; isso é prevenção, não detecção.')),

Q('ex-ccrz5btf', 'process-quality', 'easy',
  ('What did Deming say inspection at the end does?',
   'O que Deming dizia que a inspeção no fim faz?'),
  ('Sorting.', 'Separar.'),
  C('Sorts good from bad, after the cost of the bad is paid', 'Separa o bom do ruim, depois de o custo do ruim já ter sido pago',
    'Right: it does not improve quality.', 'Isso: não melhora a qualidade.', ok=True),
  C('Guarantees quality', 'Garante a qualidade',
    'His point was the opposite.', 'O ponto dele era o contrário.'),
  C('Replaces the need for a process', 'Dispensa a necessidade de um processo',
    'He argued for building quality into the process.', 'Ele defendia pôr a qualidade dentro do processo.'),
  C('Prevents defects', 'Previne defeitos',
    'At the end, the defects already exist.', 'No fim, os defeitos já existem.')),

Q('ex-257rse0j', 'process-quality', 'medium',
  ('Tomás reviewed `age > 60`, compared it with "over-60s" and approved it. Why did the process not catch the defect?',
   'O Tomás revisou `age > 60`, comparou com "maiores de 60" e aprovou. Por que o processo não pegou o defeito?'),
  ('What did the review compare with what?', 'A revisão comparava o quê com o quê?'),
  C('It checked code against the requirement, and nothing checked the requirement against the world', 'Comparava o código com o requisito, e nada comparava o requisito com o mundo',
    'Right: every step did what it said, and none looked where the mistake was.', 'Isso: cada passo fez o que dizia, e nenhum olhou onde estava o erro.', ok=True),
  C('Tomás skipped the review', 'O Tomás pulou a revisão',
    'The review happened; the process was followed.', 'A revisão aconteceu; o processo foi seguido.'),
  C('Code reviews do not work', 'Revisão de código não funciona',
    'They catch many things; this one looked at the wrong pair.', 'Pega muita coisa; esta olhou para o par errado.'),
  C('The team had no ISO 9001 certificate', 'O time não tinha certificado ISO 9001',
    'A certificate says steps exist and are followed, which they were.', 'Um certificado diz que os passos existem e são seguidos, e eles eram.')),

M('ex-wcjxs7sk', 'process-quality', 'medium',
  ('Match each measure to what it looks at.', 'Associe cada medida àquilo para que ela olha.'),
  ('The thing, or the work?', 'A coisa, ou o trabalho?'),
  [(('defects customers found after release', 'defeitos que clientes acharam depois da entrega'), ('the product', 'o produto')),
   (('how long a change waits for a tester', 'quanto tempo uma mudança espera por quem testa'), ('the process', 'o processo')),
   (('how many users finish a purchase', 'quantos usuários terminam uma compra'), ('the product in use', 'o produto em uso')),
   (('CMMI maturity level', 'nível de maturidade do CMMI'), ('the organisation’s process', 'o processo da organização'))]),

Q('ex-kjfpwmna', 'process-quality', 'hard',
  ('"100% of changes were reviewed this quarter." What would make that process measure useful, by this lesson’s argument?',
   '"100% das mudanças foram revisadas neste trimestre." O que tornaria essa medida de processo útil, pelo argumento desta aula?'),
  ('Join it to the product.', 'Junte-a ao produto.'),
  C('Knowing how many defects customers found had passed a review', 'Saber quantos defeitos que os clientes acharam tinham passado por uma revisão',
    'Right: that joins the process measure to a product measure somebody cares about.', 'Isso: junta a medida de processo a uma medida de produto que importa a alguém.', ok=True),
  C('Raising it above 100%', 'Subir acima de 100%',
    'There is nowhere to go, and a higher count would not say more.', 'Não há para onde ir, e uma contagem maior não diria mais.'),
  C('Nothing: a full review rate proves the process works', 'Nada: uma taxa de revisão completa prova que o processo funciona',
    'It was true of `age > 60` too.', 'Era verdade também para `age > 60`.'),
  C('Reporting it every week instead of every quarter', 'Informá-la toda semana em vez de todo trimestre',
    'More often is not more meaningful.', 'Com mais frequência não é com mais significado.')),

Q('ex-61v0sg1f', 'drill', 'hard',
  ('A CMMI level 5 supplier delivers a ticket shop that meets every written requirement, and customers abandon half of their purchases. Which statement fits this lesson?',
   'Um fornecedor de nível 5 do CMMI entrega uma bilheteria que cumpre todo requisito escrito, e os clientes abandonam metade das compras. Que afirmação combina com esta aula?'),
  ('A good process makes good products more likely.', 'Um bom processo torna bons produtos mais prováveis.'),
  C('A mature process and conformance did not make it fit for use', 'Processo maduro e conformidade não o tornaram adequado ao uso',
    'Right: process quality raises the odds, conformance is one definition, and quality in use is where it failed.', 'Isso: qualidade de processo melhora as chances, conformidade é uma definição, e foi na qualidade em uso que falhou.', ok=True),
  C('This cannot happen at level 5', 'Isso não pode acontecer no nível 5',
    'A process can be followed perfectly while producing the wrong thing.', 'Um processo pode ser seguido à perfeição produzindo a coisa errada.'),
  C('The supplier conformed, so the product is of high quality, and the customers are wrong', 'O fornecedor estava conforme, então o produto tem alta qualidade, e os clientes estão errados',
    'Conformance is one definition of three, and the customers are the "some person".', 'Conformidade é uma definição de três, e os clientes são o "alguém".'),
  C('The requirements were checkable, so nothing failed', 'Os requisitos eram verificáveis, então nada falhou',
    'Checkable requirements can still be the wrong requirements.', 'Requisitos verificáveis ainda podem ser os requisitos errados.')),
]
