from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
N('ex-ctykabx6', 'the-manifesto', 'easy',
  ('How many people wrote the Agile Manifesto in 2001?', 'Quantas pessoas escreveram o Manifesto Ágil em 2001?'),
  ('A ski resort in Utah.', 'Uma estação de esqui em Utah.'), 17, 0, ('people', 'pessoas')),

Q('ex-wq8959aw', 'the-manifesto', 'medium',
  ('"Working software over comprehensive documentation." What does the manifesto say about the documentation?',
   '"Software em funcionamento mais que documentação abrangente." O que o manifesto diz sobre a documentação?'),
  ('The sentence after the values.', 'A frase depois dos valores.'),
  C('It has value', 'Tem valor',
    'Right: the manifesto ranks, it does not reject.', 'Isso: o manifesto ordena, não rejeita.', ok=True),
  C('It should be abolished', 'Precisa ser abolida', 'A misreading the lesson names.', 'Uma leitura errada que a aula cita.'),
  C('Only testers may write it', 'Só quem testa pode escrevê-la', 'No.', 'Não.'),
  C('It must be written before any code, in full detail, and signed by the customer', 'Deve ser escrita antes de qualquer código, em detalhe completo, e assinada pelo cliente',
    'That is closer to the waterfall.', 'Isso está mais perto da cascata.')),

Q('ex-8m66gjfj', 'the-manifesto', 'medium',
  ('"Working software is the primary measure of progress." What does that imply for testing?',
   '"Software funcionando é a medida primária de progresso." O que isso implica para o teste?'),
  ('Somebody has to know it works.', 'Alguém precisa saber que funciona.'),
  C('It shows progress', 'Mostra o progresso',
    'Right: every couple of weeks, somebody establishes it works.', 'Isso: a cada duas semanas, alguém estabelece que funciona.', ok=True),
  C('Testing becomes unnecessary', 'O teste vira desnecessário', 'The opposite.', 'O contrário.'),
  C('Only the final release is tested', 'Só a entrega final é testada', 'Progress is measured every cycle.', 'O progresso é medido a cada ciclo.'),
  C('Progress is measured by how many test cases have been written so far in the cycle', 'O progresso é medido por quantos casos de teste foram escritos até agora no ciclo',
    'Software, not test cases.', 'Software, não casos de teste.')),

Q('ex-r1wr5ms6', 'the-manifesto', 'hard',
  ('Why does "responding to change" have a cost the testing side pays?', 'Por que "responder a mudanças" tem um custo que o lado do teste paga?'),
  ('Last month’s requirement.', 'O requisito do mês passado.'),
  C('Tests must change as fast as the requirements they check', 'Os testes precisam mudar tão rápido quanto os requisitos que conferem',
    'Right: a team that cannot change its tests has stopped being able to change.', 'Isso: um time que não muda seus testes deixou de conseguir mudar.', ok=True),
  C('Testers are paid by the change', 'Quem testa ganha por mudança', 'No.', 'Não.'),
  C('Change is forbidden in testing', 'Mudança é proibida no teste', 'No.', 'Não.'),
  C('Each change requires a new tester to be hired for the team', 'Cada mudança exige contratar mais alguém para testar no time', 'No.', 'Não.')),

Q('ex-pbfpsysa', 'a-short-cycle', 'easy',
  ('What is a mini-waterfall?', 'O que é uma minicascata?'),
  ('Build eight days, test on the ninth.', 'Construir oito dias, testar no nono.'),
  C('A sprint where building fills eight days and testing is squeezed into the last two', 'Uma sprint em que construir ocupa oito dias e o teste é espremido nos dois últimos',
    'Right: the waterfall shrunk to two weeks.', 'Isso: a cascata encolhida para duas semanas.', ok=True),
  C('A small waterfall project', 'Um projeto em cascata pequeno', 'It is about sprints in agile teams.', 'É sobre sprints em times ágeis.'),
  C('A sprint of one day', 'Uma sprint de um dia', 'Length is not the issue.', 'Duração não é a questão.'),
  C('Testing on each day of the sprint, beginning with questions on day one', 'Testar em cada dia da sprint, começando com perguntas no dia um',
    'That is the version that works.', 'Essa é a versão que funciona.')),

MC('ex-4w40ba0s', 'a-short-cycle', 'medium',
  ('Which habits make continuous testing possible, by this lesson? Choose all that apply.',
   'Quais hábitos tornam o teste contínuo possível, por esta aula? Escolha todos os que se aplicam.'),
  ('Three habits.', 'Três hábitos.'),
  C('small stories', 'histórias pequenas', 'Yes.', 'Sim.', ok=True),
  C('a shared definition of done', 'uma definição de pronto compartilhada', 'Yes.', 'Sim.', ok=True),
  C('automated regression checks', 'verificações de regressão automatizadas', 'Yes.', 'Sim.', ok=True),
  C('a testing phase at the end of each sprint', 'uma fase de teste no fim de cada sprint', 'No: that is the mini-waterfall.', 'Não: isso é a minicascata.')),

Q('ex-82yrctam', 'a-short-cycle', 'medium',
  ('"The whole price rule" is too big for a story. Why does size matter to testing?',
   '"A regra de preço inteira" é grande demais para uma história. Por que o tamanho importa para o teste?'),
  ('Arrives early, alone.', 'Chega cedo, sozinha.'),
  C('A small story reaches testing early, alone, while its author remembers it', 'Uma história pequena chega cedo ao teste, sozinha, enquanto o autor lembra dela',
    'Right: "students pay half" is a story.', 'Isso: "estudantes pagam meia" é uma história.', ok=True),
  C('Big stories cannot be tested', 'Histórias grandes não podem ser testadas', 'They can, late.', 'Podem, tarde.'),
  C('Small stories need no testing', 'Histórias pequenas não precisam de teste', 'They still need it.', 'Ainda precisam.'),
  C('Size decides how much the team charges the cinema for it', 'O tamanho decide quanto o time cobra do cinema por ela', 'Unrelated.', 'Sem relação.')),

Q('ex-1gnmj23h', 'a-short-cycle', 'hard',
  ('"Short cycles make every defect a young defect." Why is that only true if testing keeps pace?',
   '"Ciclos curtos fazem de todo defeito um defeito novo." Por que isso só vale se o teste acompanha?'),
  ('Lesson 3.', 'Aula 3.'),
  C('A defect waiting untested until the cycle ends ages like any other', 'Um defeito esperando sem teste até o fim do ciclo envelhece como qualquer outro',
    'Right: the mini-waterfall throws away the benefit.', 'Isso: a minicascata joga fora o benefício.', ok=True),
  C('Defects age faster in sprints than in a waterfall, whatever testing does', 'Defeitos envelhecem mais rápido em sprints que na cascata, faça o teste o que fizer', 'Not the argument.', 'Não é o argumento.'),
  C('Young defects are harder to find', 'Defeitos novos são mais difíceis de achar', 'They are cheaper to fix.', 'São mais baratos de corrigir.'),
  C('It is true either way', 'Vale de qualquer jeito', 'Not if testing waits for the end.', 'Não se o teste esperar o fim.')),

M('ex-e80xdrcm', 'the-quadrants', 'medium',
  ('Match each Cine Aurora test to its quadrant.', 'Associe cada teste do Cine Aurora ao seu quadrante.'),
  ('Support or critique; business or technology.', 'Apoiar ou criticar; negócio ou tecnologia.'),
  [(('`price(60, …)` is 1800, on every change', '`price(60, …)` é 1800, a cada mudança'), ('Q1', 'Q1')),
   (('"a student on Wednesday pays R$ 18,00", written with Joana', '"estudante na quarta paga R$ 18,00", escrito com a Joana'), ('Q2', 'Q2')),
   (('Lia exploring the seat map', 'a Lia explorando o mapa de assentos'), ('Q3', 'Q3')),
   (('three hundred buyers on opening night', 'trezentos compradores na estreia'), ('Q4', 'Q4'))]),

Q('ex-3zxvg06d', 'the-quadrants', 'easy',
  ('What are the two axes of the agile testing quadrants?', 'Quais são os dois eixos dos quadrantes do teste ágil?'),
  ('Left/right, top/bottom.', 'Esquerda/direita, cima/baixo.'),
  C('Support or critique; business or technology', 'Apoiar ou criticar; negócio ou tecnologia',
    'Right.', 'Isso.', ok=True),
  C('Manual or automated; fast or slow', 'Manual ou automatizado; rápido ou lento', 'Not the axes.', 'Não são os eixos.'),
  C('Developer or tester, depending on who runs each of the tests on the team', 'Desenvolvedor ou quem testa, conforme quem roda cada teste no time',
    'The lesson says the map is not about who.', 'A aula diz que o mapa não é sobre quem.'),
  C('Before release or after', 'Antes ou depois da entrega', 'Not the axes.', 'Não são os eixos.')),

Q('ex-pkdz97mn', 'the-quadrants', 'medium',
  ('A heavily automated team has full Q1 and Q2 and nothing in Q3. Why is that typical?',
   'Um time muito automatizado tem Q1 e Q2 cheios e nada em Q3. Por que isso é típico?'),
  ('What does exploring not produce?', 'O que explorar não produz?'),
  C('Exploring produces no green tick', 'Explorar não produz sinal verde',
    'Right: the map exists to show that empty corner.', 'Isso: o mapa existe para mostrar esse canto vazio.', ok=True),
  C('Q3 is not allowed in agile', 'Q3 não é permitido no ágil', 'It is part of the map.', 'Faz parte do mapa.'),
  C('Automation covers Q3 automatically', 'A automação cobre Q3 automaticamente', 'It does not.', 'Não cobre.'),
  C('Q3 can only be done by the customer at the very end of the project, after release', 'Q3 só pode ser feito pelo cliente no fim do projeto, depois da entrega',
    'Lia explores every cycle.', 'A Lia explora a cada ciclo.')),

Q('ex-acm08a29', 'the-quadrants', 'hard',
  ('The Wednesday stacking was found by exploring and then written as an example with Joana. Which quadrants did it move between?',
   'A soma de descontos da quarta foi achada explorando e depois escrita como exemplo com a Joana. Entre que quadrantes ela passou?'),
  ('Found by exploring, kept by automating.', 'Achada explorando, mantida automatizando.'),
  C('From Q3 to Q2', 'De Q3 para Q2', 'Right: born critiquing, kept supporting.', 'Isso: nasceu criticando, ficou apoiando.', ok=True),
  C('From Q1 to Q4, as it was automated', 'De Q1 para Q4, ao ser automatizada', 'Neither is about examples or exploring.', 'Nenhum dos dois é sobre exemplos ou explorar.'),
  C('From Q2 to Q3', 'De Q2 para Q3', 'The other way round.', 'Ao contrário.'),
  C('It stayed in Q3', 'Ficou em Q3', 'Written as an example, it moved.', 'Escrita como exemplo, mudou.')),

Q('ex-762r33aw', 'what-agile-does-not-solve', 'easy',
  ('What is testing debt?', 'O que é dívida de teste?'),
  ('Built and never properly checked.', 'Construído e nunca conferido direito.'),
  C('Unchecked work', 'Trabalho sem teste',
    'Right: it compounds like technical debt.', 'Isso: cresce como dívida técnica.', ok=True),
  C('Money owed to testers', 'Dinheiro devido a quem testa', 'No.', 'Não.'),
  C('Tests that fail', 'Testes que falham', 'Those are findings.', 'Isso são achados.'),
  C('The licence cost of a testing tool, paid in instalments', 'O custo de licença de uma ferramenta de teste, pago em parcelas', 'No.', 'Não.')),

Q('ex-456w4p0t', 'what-agile-does-not-solve', 'medium',
  ('What usually happens to teams that never automate regression checks, by the lesson?',
   'O que costuma acontecer com times que nunca automatizam as verificações de regressão, pela aula?'),
  ('Around the sixth month.', 'Por volta do sexto mês.'),
  C('They hit a wall', 'Batem num muro',
    'Right: re-testing by hand outgrows a cycle.', 'Isso: retestar à mão fica maior que um ciclo.', ok=True),
  C('Nothing changes', 'Nada muda', 'Regression grows every cycle.', 'A regressão cresce a cada ciclo.'),
  C('They hire one more tester every sprint until the regression pile shrinks again', 'Contratam mais alguém para testar a cada sprint até a pilha diminuir',
    'Not the lesson’s description.', 'Não é a descrição da aula.'),
  C('They become a waterfall team by choice', 'Viram um time em cascata por escolha', 'Not the description.', 'Não é a descrição.')),

Q('ex-79766g03', 'what-agile-does-not-solve', 'hard',
  ('A tester learns what a story means on the day it is handed over. What is the team running, by this lesson?',
   'Quem testa descobre o que uma história quer dizer no dia em que ela é entregue. O que o time está rodando, por esta aula?'),
  ('Agile vocabulary.', 'Vocabulário ágil.'),
  C('A mini-waterfall wearing agile vocabulary, with the tester left out of the first conversation', 'Uma minicascata vestida de vocabulário ágil, com quem testa fora da primeira conversa',
    'Right: lesson 5’s gate with new furniture.', 'Isso: o portão da aula 5 com móveis novos.', ok=True),
  C('Proper Scrum', 'Scrum de verdade', 'The tester belongs in the first conversation.', 'Quem testa pertence à primeira conversa.'),
  C('A spiral', 'Uma espiral', 'Nothing about risk here.', 'Nada sobre risco aqui.'),
  C('Behaviour-driven development, where examples come after the code has been written', 'Desenvolvimento guiado por comportamento, com exemplos depois do código',
    'BDD writes the examples first.', 'O BDD escreve os exemplos primeiro.')),

Q('ex-z56ym2j4', 'drill', 'medium',
  ('A rule changes three times in a cycle. What defence does the lesson recommend?',
   'Uma regra muda três vezes num ciclo. Que defesa a aula recomenda?'),
  ('Lesson 6.', 'Aula 6.'),
  C('Write each answer as an example', 'Escrever cada resposta como exemplo',
    'Right: then change is deliberate and visible.', 'Isso: aí a mudança é deliberada e visível.', ok=True),
  C('Refuse to test until it settles', 'Recusar testar até assentar', 'A gate, again.', 'Um portão, de novo.'),
  C('Ignore the changes', 'Ignorar as mudanças', 'The tests would check the wrong rule.', 'Os testes confeririam a regra errada.'),
  C('Ask for a longer cycle so that the rule has time to stop changing', 'Pedir um ciclo mais longo para a regra ter tempo de parar de mudar', 'Not the defence named.', 'Não é a defesa citada.')),
]
