from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
O('ex-mjhvt49y', 'waterfall', 'easy',
  ('Put the waterfall’s phases in order.', 'Ponha as fases da cascata em ordem.'),
  ('Downhill.', 'Ladeira abaixo.'),
  [('requirements', 'requisitos'), ('design', 'projeto'), ('implementation', 'implementação'),
   ('testing', 'teste'), ('operation', 'operação')],
  ('Testing comes after every line is written, which is the model’s weakness.', 'O teste vem depois de toda linha escrita, que é a fraqueza do modelo.')),

Q('ex-6eavejkj', 'waterfall', 'medium',
  ('What did Winston Royce say, in 1970, about the sequential approach his paper drew?',
   'O que Winston Royce disse, em 1970, sobre a abordagem sequencial que o artigo dele desenhou?'),
  ('The sentence under the diagram.', 'A frase sob o diagrama.'),
  C('That it was risky and invited failure', 'Que era arriscada e um convite ao fracasso',
    'Right: testing at the end is the first contact with reality.', 'Isso: o teste no fim é o primeiro contato com a realidade.', ok=True),
  C('That it was the only correct way to build large systems', 'Que era o único jeito certo de construir sistemas grandes',
    'He proposed fixes to it.', 'Ele propôs correções a ela.'),
  C('That testing should be skipped on large projects to save time for the design phase', 'Que o teste devia ser pulado em projetos grandes para poupar tempo do projeto',
    'Nothing of the sort.', 'Nada disso.'),
  C('That it came from manufacturing', 'Que vinha da indústria', 'Not his point.', 'Não era o ponto dele.')),

Q('ex-qdscagdj', 'waterfall', 'medium',
  ('Where does the waterfall still fit, by this lesson?', 'Onde a cascata ainda cabe, por esta aula?'),
  ('Auditors, contracts, hardware.', 'Auditores, contratos, hardware.'),
  C('Regulated and fixed-price work', 'Trabalho regulado e de preço fechado',
    'Right: places where order and records matter more than speed.', 'Isso: lugares onde ordem e registros importam mais que velocidade.', ok=True),
  C('Start-ups that change direction every week', 'Startups que mudam de direção toda semana',
    'The opposite: requirements change constantly there.', 'O contrário: os requisitos mudam o tempo todo ali.'),
  C('Nowhere', 'Em lugar nenhum', 'The lesson names three places.', 'A aula cita três lugares.'),
  C('Websites', 'Sites', 'A website can be released again in minutes.', 'Um site pode ser publicado de novo em minutos.')),

Q('ex-ybxwmdxe', 'waterfall', 'hard',
  ('Inside a waterfall project, what is a tester’s best move, by this lesson?',
   'Dentro de um projeto em cascata, qual o melhor movimento de quem testa, por esta aula?'),
  ('Before the testing phase.', 'Antes da fase de teste.'),
  C('Get involved early: read requirements, write tests from them', 'Envolver-se cedo: ler os requisitos, escrever testes a partir deles',
    'Right: testing can start the day code arrives.', 'Isso: o teste pode começar no dia em que o código chega.', ok=True),
  C('Wait for the testing phase, as the model says', 'Esperar a fase de teste, como o modelo diz',
    'That is where the trouble starts.', 'É aí que o problema começa.'),
  C('Refuse to sign off until the project switches to agile', 'Recusar aprovar até o projeto mudar para ágil',
    'A gate, and not the tester’s decision.', 'Um portão, e não é decisão de quem testa.'),
  C('Write the code instead, so that it reaches testing sooner and with fewer defects in it', 'Escrever o código no lugar, para chegar mais cedo ao teste e com menos defeitos',
    'Not the role.', 'Não é o papel.')),

M('ex-f08a1zw3', 'the-v-model', 'easy',
  ('Match each description on the V’s left side to the test level on the right that checks it.',
   'Associe cada descrição do lado esquerdo do V ao nível de teste da direita que a confere.'),
  ('Each horizontal line.', 'Cada linha horizontal.'),
  [(('requirements', 'requisitos'), ('acceptance testing', 'teste de aceitação')),
   (('system design', 'projeto do sistema'), ('system testing', 'teste de sistema')),
   (('architecture', 'arquitetura'), ('integration testing', 'teste de integração')),
   (('module design', 'projeto do módulo'), ('unit testing', 'teste de unidade'))]),

Z('ex-b7g90mrq', 'the-v-model', 'medium',
  ('The document a test level’s expected results come from is called its test ___.',
   'O documento de onde vêm os resultados esperados de um nível de teste se chama sua ___ de teste.'),
  ('Unit tests: the module design.', 'Teste de unidade: o projeto do módulo.'),
  ['basis'], ['base']),

Q('ex-z0epz0zw', 'the-v-model', 'medium',
  ('What does the V model improve over the waterfall, and what does it not?',
   'O que o modelo V melhora em relação à cascata, e o que não melhora?'),
  ('Designed versus happens.', 'Projetado contra acontece.'),
  C('Where tests are designed', 'Onde os testes são projetados',
    'Right: thinking moves earlier, running does not.', 'Isso: o pensar vai mais cedo, o rodar não.', ok=True),
  C('It removes the sequence altogether, so testing happens alongside development', 'Remove a sequência, então o teste acontece junto com o desenvolvimento',
    'It keeps the sequence.', 'Mantém a sequência.'),
  C('Nothing; it is the same drawing', 'Nada; é o mesmo desenho', 'The pairing of levels is new.', 'O pareamento de níveis é novo.'),
  C('It makes acceptance testing unnecessary', 'Torna o teste de aceitação desnecessário', 'It is the top of the right side.', 'É o topo do lado direito.')),

Q('ex-7xyyewpb', 'the-v-model', 'hard',
  ('Lia writes the acceptance tests for the price rule the week Joana drafts it. Why is that prevention, in a sequential project?',
   'A Lia escreve os testes de aceitação da regra de preço na semana em que a Joana a rascunha. Por que isso é prevenção, num projeto sequencial?'),
  ('What surfaces when you design a test?', 'O que aparece quando você projeta um teste?'),
  C('Designing a test surfaces ambiguities before code is written', 'Projetar um teste revela ambiguidades antes de o código ser escrito',
    'Right: "over-60s" would have met its question that week.', 'Isso: "maiores de 60" teria encontrado sua pergunta naquela semana.', ok=True),
  C('Because the tests run earlier', 'Porque os testes rodam mais cedo', 'There is no code to run them on.', 'Não há código para rodá-los.'),
  C('It is not; it is detection', 'Não é; é detecção', 'Nothing has been detected; a defect was avoided.', 'Nada foi detectado; um defeito foi evitado.'),
  C('Because acceptance tests replace the requirement', 'Porque os testes de aceitação substituem o requisito',
    'They check against it; they do not replace it.', 'Conferem contra ele; não o substituem.')),

Q('ex-byqc888q', 'a-mirror-at-cine-aurora', 'easy',
  ('At which level is "`price(60, False, "thu", "20:00")` should be 1800" a test?',
   'Em que nível "`price(60, False, "thu", "20:00")` deveria dar 1800" é um teste?'),
  ('One piece, alone.', 'Um pedaço, sozinho.'),
  C('Unit', 'Unidade', 'Right: one function, alone.', 'Isso: uma função, sozinha.', ok=True),
  C('Integration, because it calls a function', 'Integração, porque chama uma função', 'One piece, nothing it talks to.', 'Um pedaço, nada com que ele converse.'),
  C('System', 'Sistema', 'The whole shop is not involved.', 'A loja inteira não está envolvida.'),
  C('Acceptance, since it checks the law', 'Aceitação, já que confere a lei',
    'Acceptance is the shop as users need it.', 'Aceitação é a loja como os usuários precisam.')),

Q('ex-7vdsncwp', 'a-mirror-at-cine-aurora', 'medium',
  ('At which level would the refused orders stored in the database most naturally be found?',
   'Em que nível os pedidos recusados guardados no banco seriam achados mais naturalmente?'),
  ('Where two pieces meet.', 'Onde dois pedaços se encontram.'),
  C('Integration', 'Integração',
    'Right: each piece works alone.', 'Isso: cada pedaço funciona sozinho.', ok=True),
  C('Unit, in `price`', 'Unidade, no `price`', 'The price rule is not involved.', 'A regra de preço não está envolvida.'),
  C('Acceptance only, by Célia', 'Só na aceitação, pela Célia', 'Possible, and later than needed.', 'Possível, e mais tarde que o necessário.'),
  C('None: the database is not tested', 'Nenhum: o banco não é testado', 'Lesson 8 tested it.', 'A aula 8 o testou.')),

Q('ex-6see1514', 'a-mirror-at-cine-aurora', 'medium',
  ('Why could the 9:30 defect only be expected at the acceptance level?',
   'Por que o defeito das 9:30 só seria esperado no nível de aceitação?'),
  ('Who typed the time?', 'Quem digitou o horário?'),
  C('Only there does a real session time typed by a person reach the rule', 'Só ali um horário real digitado por uma pessoa chega à regra',
    'Right: the shape of the input came from real use.', 'Isso: o formato da entrada veio do uso real.', ok=True),
  C('Unit tests cannot test times', 'Testes de unidade não testam horários', 'They can; nobody chose `9:30`.', 'Testam; ninguém escolheu `9:30`.'),
  C('It is a performance defect', 'É um defeito de desempenho', 'It is a wrong price.', 'É um preço errado.'),
  C('Because acceptance tests run on Sundays', 'Porque testes de aceitação rodam aos domingos', 'Sunday was ruled out in lesson 4.', 'O domingo foi descartado na aula 4.')),

Q('ex-0z3cd9bj', 'a-mirror-at-cine-aurora', 'hard',
  ('In a traceability matrix, a test traces to no requirement. What does the lesson say that means?',
   'Numa matriz de rastreabilidade, um teste não leva a requisito nenhum. O que a aula diz que isso quer dizer?'),
  ('Read down a column.', 'Leia descendo uma coluna.'),
  C('Untraced: worth a question', 'Sem rastro: merece uma pergunta',
    'Right: both are worth a question.', 'Isso: os dois merecem uma pergunta.', ok=True),
  C('The test must be deleted', 'O teste deve ser apagado', 'Asking comes before deleting.', 'Perguntar vem antes de apagar.'),
  C('The matrix is wrong', 'A matriz está errada', 'The matrix is what showed it.', 'Foi a matriz que mostrou.'),
  C('The requirement is fully covered', 'O requisito está totalmente coberto', 'There is no requirement to cover.', 'Não há requisito para cobrir.')),

Q('ex-yy8m5s5d', 'where-it-breaks', 'easy',
  ('Which assumption do the waterfall and the V model share?', 'Que suposição a cascata e o modelo V compartilham?'),
  ('Known at the start.', 'Conhecidos no começo.'),
  C('Fixed requirements, known up front', 'Requisitos fixos, conhecidos de saída',
    'Right: when it fails, every change is a trip back up.', 'Isso: quando falha, cada mudança é uma volta ao topo.', ok=True),
  C('Testing is unnecessary', 'O teste é desnecessário', 'Both include testing.', 'Os dois incluem teste.'),
  C('The customer writes the code', 'O cliente escreve o código', 'No.', 'Não.'),
  C('Releases happen every week', 'Entregas acontecem toda semana', 'One release, at the end.', 'Uma entrega, no fim.')),

Q('ex-yrc4xzs5', 'where-it-breaks', 'medium',
  ('Why is testing the phase that gets squeezed in a sequential project?',
   'Por que o teste é a fase espremida num projeto sequencial?'),
  ('The last phase before a fixed date.', 'A última fase antes de uma data fixa.'),
  C('It is last, so every earlier delay comes out of its time', 'É a última, então todo atraso anterior sai do tempo dela',
    'Right: the phase that says whether the rest worked is the one cut.', 'Isso: a fase que diz se o resto funcionou é a cortada.', ok=True),
  C('Testers are slower than developers', 'Quem testa é mais lento que quem desenvolve', 'Speed is not the reason.', 'Velocidade não é o motivo.'),
  C('Testing is optional in the model', 'O teste é opcional no modelo', 'It is a phase.', 'É uma fase.'),
  C('Because the V model moves it to the start, leaving nothing for the end of the project', 'Porque o modelo V o leva para o começo, sem deixar nada para o fim do projeto',
    'The V moves design, not running.', 'O V leva o projeto, não a execução.')),

Q('ex-ppgjd739', 'where-it-breaks', 'medium',
  ('What does the W model add?', 'O que o modelo W acrescenta?'),
  ('A second V.', 'Um segundo V.'),
  C('Testing in parallel with each phase', 'Teste em paralelo a cada fase',
    'Right: Spillner’s second V of testing.', 'Isso: o segundo V de teste de Spillner.', ok=True),
  C('A third test level', 'Um terceiro nível de teste', 'Not the idea.', 'Não é a ideia.'),
  C('Weekly releases', 'Entregas semanais', 'That is agile, not W.', 'Isso é ágil, não W.'),
  C('Removing documents', 'Tirar documentos', 'It reviews them.', 'Ele os revisa.')),

MC('ex-bmcjmqxy', 'drill', 'hard',
  ('Which of these soften the sequence’s problems while keeping the sequence? Choose all that apply.',
   'Quais destes amenizam os problemas da sequência mantendo a sequência? Escolha todos os que se aplicam.'),
  ('Prevention bolted on.', 'Prevenção parafusada.'),
  C('designing tests on the way down', 'projetar testes na descida', 'Yes.', 'Sim.', ok=True),
  C('the W model', 'o modelo W', 'Yes.', 'Sim.', ok=True),
  C('reviews and inspections at every phase', 'revisões e inspeções em cada fase', 'Yes: static testing.', 'Sim: teste estático.', ok=True),
  C('building a small part, showing it, and building the next', 'construir uma parte pequena, mostrar, e construir a próxima',
    'No: that abandons the sequence; it is the next lessons.', 'Não: isso abandona a sequência; são as próximas aulas.')),
]
