from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
Q('ex-gh1yhtd9', 'the-board', 'easy',
  ('Why does Cine Aurora handle Célia’s requests on a Kanban board rather than in sprints?',
   'Por que o Cine Aurora cuida dos pedidos da Célia num quadro Kanban em vez de em sprints?'),
  ('When do they arrive?', 'Quando eles chegam?'),
  C('They arrive any day, and some cannot wait two weeks', 'Chegam em qualquer dia, e alguns não podem esperar duas semanas',
    'Right: a stream of small, unplanned work fits flow better than a fixed cycle.',
    'Isso: um fluxo de trabalho pequeno e não planejado cabe melhor num fluxo que num ciclo fixo.', ok=True),
  C('Kanban needs no testing', 'O Kanban não precisa de teste', 'Testing is a column on the board.', 'Testar é uma coluna do quadro.'),
  C('Célia’s requests are too large to fit into a two-week sprint', 'Os pedidos da Célia são grandes demais para caber numa sprint de duas semanas',
    'Most of them are small.', 'A maioria é pequena.'),
  C('Scrum forbids fixing defects', 'O Scrum proíbe corrigir defeitos', 'It forbids nothing of the kind.', 'Não proíbe nada disso.')),

Q('ex-4z4m3q2w', 'the-board', 'medium',
  ('Why is "waiting for test" drawn as a column of its own?', 'Por que "esperando teste" é desenhado como uma coluna própria?'),
  ('Who is working on a card there?', 'Quem está trabalhando num cartão ali?'),
  C('It makes the wait visible', 'Torna a espera visível',
    'Right: nobody works on a card there, and the column shows the queue.',
    'Isso: ninguém trabalha num cartão ali, e a coluna mostra a fila.', ok=True),
  C('It is where testing happens', 'É onde o teste acontece', 'Testing has its own column next to it.', 'O teste tem a coluna dele, ao lado.'),
  C('Kanban requires exactly five columns', 'O Kanban exige exatamente cinco colunas', 'A team draws whatever steps it has.',
    'Um time desenha as etapas que tiver.'),
  C('It holds the cards a tester has rejected and sent back to the developer who built them',
    'Guarda os cartões que quem testa recusou e devolveu a quem os construiu',
    'It holds cards that are built and not yet tested.', 'Guarda cartões construídos e ainda não testados.')),

Q('ex-zeq1nrxn', 'the-board', 'easy',
  ('What does the word kanban mean in Japanese?', 'O que a palavra kanban quer dizer em japonês?'),
  ('Toyota used them to control production.', 'A Toyota os usava para controlar a produção.'),
  C('A card', 'Um cartão', 'Right: a signboard or card.', 'Isso: uma placa ou cartão.', ok=True),
  C('Continuous flow', 'Fluxo contínuo', 'That is what it is used for, not what the word means.', 'Isso é para que serve, não o que a palavra quer dizer.'),
  C('Stop the line', 'Pare a linha', 'That idea is jidoka.', 'Essa ideia é o jidoka.'),
  C('A production line in a car factory', 'Uma linha de produção numa fábrica de carros', 'No.', 'Não.')),

MC('ex-btvhewj9', 'the-board', 'medium',
  ('Which of these are core practices of the Kanban method? Choose all that apply.',
   'Quais destas são práticas centrais do método Kanban? Escolha todas as que se aplicam.'),
  ('Six of them, in Anderson’s list.', 'Seis, na lista de Anderson.'),
  C('visualise the work', 'visualizar o trabalho', 'Yes.', 'Sim.', ok=True),
  C('limit work in progress', 'limitar o trabalho em andamento', 'Yes.', 'Sim.', ok=True),
  C('make policies explicit', 'tornar as políticas explícitas', 'Yes.', 'Sim.', ok=True),
  C('fixed two-week sprints', 'sprints fixas de duas semanas', 'No: Kanban has no sprints.', 'Não: o Kanban não tem sprints.')),

N('ex-nqk9rpaq', 'wip-limits', 'easy',
  ('A board holds 9 cards on average and 3 cards a week reach done. On average, how many weeks does a card spend on the board?',
   'Um quadro tem em média 9 cartões e 3 cartões por semana chegam a pronto. Em média, quantas semanas um cartão passa no quadro?'),
  ('Little’s law.', 'A lei de Little.'), 3, 0, ('weeks', 'semanas')),

N('ex-4cn6zhps', 'wip-limits', 'medium',
  ('The team cuts the board to 6 cards on average. Throughput stays at 3 a week. What is the new average time on the board, in weeks?',
   'O time reduz o quadro a 6 cartões em média. A vazão continua 3 por semana. Qual é o novo tempo médio no quadro, em semanas?'),
  ('Same throughput, fewer cards.', 'Mesma vazão, menos cartões.'), 2, 0, ('weeks', 'semanas')),

N('ex-fwd16w0w', 'wip-limits', 'hard',
  ('Another team finishes 4 cards a week and its cards spend 2 weeks on the board on average. How many cards are on its board on average?',
   'Outro time termina 4 cartões por semana e seus cartões passam em média 2 semanas no quadro. Quantos cartões há no quadro dele em média?'),
  ('Turn the law around: work in progress = time × throughput.', 'Inverta a lei: trabalho em andamento = tempo × vazão.'),
  8, 0, ('cards', 'cartões')),

Q('ex-6pfsv543', 'wip-limits', 'medium',
  ('"Waiting for test" is full at its limit of two, and Rafael has just finished building a card. What should he do?',
   '"Esperando teste" está cheia no limite de dois, e o Rafael acabou de construir um cartão. O que ele deveria fazer?'),
  ('Stop starting, start finishing.', 'Pare de começar, comece a terminar.'),
  C('Help a card in testing move, by pairing with Lia', 'Ajudar um cartão em teste a andar, fazendo par com a Lia',
    'Right: the limit turns testing into the whole team’s problem.',
    'Isso: o limite faz do teste um problema do time todo.', ok=True),
  C('Start the next card in "ready"', 'Começar o próximo cartão em "a fazer"',
    'That is the starting the limit exists to stop.', 'Esse é o começar que o limite existe para impedir.'),
  C('Move his card into "waiting for test" anyway', 'Mover o cartão dele para "esperando teste" mesmo assim',
    'The column is full; the rule says no.', 'A coluna está cheia; a regra diz que não.'),
  C('Raise the limit on "waiting for test" to three, just for this week', 'Subir o limite de "esperando teste" para três, só nesta semana', 'A limit that moves whenever it bites is a decoration.',
    'Um limite que sobe sempre que aperta é enfeite.')),

Q('ex-1j6nc6t4', 'wip-limits', 'medium',
  ('By Little’s law, which is usually the faster way to shorten the time a card spends on the board?',
   'Pela lei de Little, qual costuma ser o jeito mais rápido de encurtar o tempo que um cartão passa no quadro?'),
  ('One of them is a decision the team can take tomorrow.', 'Um deles é uma decisão que o time pode tomar amanhã.'),
  C('Hold fewer cards in progress', 'Ter menos cartões em andamento',
    'Right: nobody has to work faster.', 'Isso: ninguém precisa trabalhar mais rápido.', ok=True),
  C('Hire more people', 'Contratar mais gente', 'That raises throughput, slowly and expensively.', 'Isso aumenta a vazão, devagar e caro.'),
  C('Add more columns to the board', 'Pôr mais colunas no quadro', 'More columns do not change the arithmetic.',
    'Mais colunas não mudam a aritmética.'),
  C('Ask everybody to work longer hours every week until the queue is gone', 'Pedir a todos que trabalhem mais horas toda semana até a fila acabar',
    'The law points at the cards, not the hours.', 'A lei aponta para os cartões, não para as horas.')),

Q('ex-0av5d34p', 'wip-limits', 'hard',
  ('The testing column is full every single day for a month. What does that tell the team?',
   'A coluna de teste fica cheia todos os dias durante um mês. O que isso diz ao time?'),
  ('Where is the system slowest?', 'Onde o sistema é mais lento?'),
  C('Testing is where the flow is slowest', 'O teste é onde o fluxo é mais lento',
    'Right: automate more checks, make cards smaller, or share the testing.',
    'Isso: automatizar mais verificações, fazer cartões menores ou dividir o teste.', ok=True),
  C('Lia works too slowly', 'A Lia trabalha devagar demais', 'A queue is a property of how work is organised.',
    'Uma fila é uma propriedade de como o trabalho está organizado.'),
  C('The limit is working, so nothing needs to change', 'O limite está funcionando, então nada precisa mudar',
    'The limit has done its job: it has shown where to act.', 'O limite fez seu trabalho: mostrou onde agir.'),
  C('The column should be removed', 'A coluna deveria ser removida', 'That would hide the queue again.', 'Isso esconderia a fila de novo.')),

M('ex-7vvadnt2', 'measuring-flow', 'easy',
  ('Match each flow measure to what it counts.', 'Associe cada medida de fluxo ao que ela conta.'),
  ('Who experiences it?', 'Quem a vive?'),
  [(('lead time', 'lead time'), ('from the request to done', 'do pedido até pronto')),
   (('cycle time', 'tempo de ciclo'), ('from the start of work to done', 'do começo do trabalho até pronto')),
   (('throughput', 'vazão'), ('cards reaching done per week', 'cartões que chegam a pronto por semana'))]),

N('ex-6grwxr9r', 'measuring-flow', 'medium',
  ('A card spends 2 days building, 5 waiting for test, 1 testing and 1 waiting to be released. What is its flow efficiency, as a percentage, to the nearest whole number?',
   'Um cartão passa 2 dias construindo, 5 esperando teste, 1 testando e 1 esperando a entrega. Qual é a eficiência de fluxo dele, em porcentagem, arredondada ao inteiro?'),
  ('Days worked on ÷ total days.', 'Dias trabalhados ÷ dias totais.'), 33, 1, ('%', '%')),

Q('ex-6gp31vht', 'measuring-flow', 'medium',
  ('In March everybody said "testing is slow". What did counting the days show?', 'Em março todo mundo dizia "o teste é lento". O que contar os dias mostrou?'),
  ('One day, and five before it.', 'Um dia, e cinco antes dele.'),
  C('Testing took one day; the five before it were a queue', 'O teste levou um dia; os cinco antes dele eram fila',
    'Right: a queue is about organisation, not speed.', 'Isso: uma fila é questão de organização, não de velocidade.', ok=True),
  C('Testing took five days', 'O teste levou cinco dias', 'Those were the days waiting for test.', 'Esses foram os dias esperando teste.'),
  C('Building was the slowest step, at five days for every card', 'Construir era a etapa mais lenta, com cinco dias para cada cartão', 'Building took two days.', 'Construir levou dois dias.'),
  C('Lia had been testing each card three or four times over', 'A Lia vinha testando cada cartão três ou quatro vezes',
    'Testing took one day per card.', 'O teste levou um dia por cartão.')),

Q('ex-nfmv9q7w', 'measuring-flow', 'medium',
  ('On a cumulative flow diagram, one band keeps getting thicker while its neighbours stay thin. What does it mean?',
   'Num diagrama de fluxo cumulativo, uma faixa fica cada vez mais grossa enquanto as vizinhas continuam finas. O que isso quer dizer?'),
  ('Thickness is how many cards are in the column.', 'A espessura é quantos cartões estão na coluna.'),
  C('A queue is growing in that column', 'Uma fila está crescendo naquela coluna',
    'Right: cards come in faster than they go out.', 'Isso: os cartões entram mais rápido do que saem.', ok=True),
  C('That column is the fastest', 'Aquela coluna é a mais rápida', 'The opposite.', 'O contrário.'),
  C('The team is finishing more work than it starts', 'O time está terminando mais trabalho do que começa', 'Finished work is the bottom band.',
    'O trabalho terminado é a faixa de baixo.'),
  C('The diagram was drawn with the wrong scale on its vertical axis', 'O diagrama foi desenhado com a escala errada no eixo vertical',
    'Nothing is wrong with the drawing.', 'Não há nada errado com o desenho.')),

Q('ex-rghmmdpx', 'measuring-flow', 'hard',
  ('A manager tells the team to halve its lead time by next month. What is the danger this lesson names?',
   'Uma gerente manda o time cortar o lead time pela metade até o mês que vem. Qual é o perigo que esta aula cita?'),
  ('Lesson 22.', 'Aula 22.'),
  C('Cards are moved to done before they are tested', 'Cartões são movidos para pronto antes de serem testados',
    'Right: the diagram looks wonderful and says nothing about quality.',
    'Isso: o diagrama fica lindo e não diz nada sobre qualidade.', ok=True),
  C('The team will work too fast', 'O time vai trabalhar rápido demais', 'Speed is not the danger named.', 'Velocidade não é o perigo citado.'),
  C('Lead time cannot be measured on a board that has no sprints', 'Lead time não pode ser medido num quadro que não tem sprints', 'It can; the table measures it.', 'Pode; a tabela o mede.'),
  C('Throughput will rise too high', 'A vazão vai subir demais', 'No.', 'Não.')),

Q('ex-49a2jv96', 'quality-in-the-flow', 'easy',
  ('What is a policy on a Kanban board?', 'O que é uma política num quadro Kanban?'),
  ('Written at the top of the column.', 'Escrita no topo da coluna.'),
  C('The rule for leaving a column', 'A regra para sair de uma coluna',
    'Right: the definition of done, split by column.', 'Isso: a definição de pronto, dividida por coluna.', ok=True),
  C('The number of cards allowed in a column', 'O número de cartões permitidos numa coluna', 'That is the limit.', 'Isso é o limite.'),
  C('The order of the columns', 'A ordem das colunas', 'No.', 'Não.'),
  C('A document describing the company’s attitude to quality, kept by the manager', 'Um documento descrevendo a atitude da empresa sobre qualidade, guardado pela gerência',
    'It is on the board, where everybody sees it.', 'Está no quadro, onde todos veem.')),

Q('ex-t82y0d3r', 'quality-in-the-flow', 'medium',
  ('Rafael asks whether a one-line fix may skip "testing". How does the board answer?',
   'O Rafael pergunta se uma correção de uma linha pode pular "testando". Como o quadro responde?'),
  ('Read the policies.', 'Leia as políticas.'),
  C('No: no column says "unless it is small"', 'Não: nenhuma coluna diz "a não ser que seja pequeno"',
    'Right: the policy settled the argument before it started.', 'Isso: a política resolveu a discussão antes de começar.', ok=True),
  C('Yes, if Lia agrees', 'Sim, se a Lia concordar', 'The policies have no exception for that.', 'As políticas não têm essa exceção.'),
  C('Yes: small changes are the exception', 'Sim: mudanças pequenas são a exceção', 'Nothing on the board says so.', 'Nada no quadro diz isso.'),
  C('Only through the expedite lane, which is meant for small fixes', 'Só pela faixa urgente, que é feita para correções pequenas', 'The expedite lane still goes through testing.', 'A faixa urgente também passa por teste.')),

Q('ex-mjg6nex4', 'quality-in-the-flow', 'medium',
  ('What is jidoka?', 'O que é o jidoka?'),
  ('Toyota, and a cord.', 'Toyota, e uma corda.'),
  C('Stopping the line where a defect appears', 'Parar a linha onde um defeito aparece',
    'Right: fixed where it appears, not passed down the line.', 'Isso: corrigido onde aparece, não passado adiante.', ok=True),
  C('A card that asks the previous station for more parts', 'Um cartão que pede mais peças à estação anterior', 'That is the kanban card.', 'Esse é o cartão kanban.'),
  C('A limit on work in progress', 'Um limite de trabalho em andamento', 'A different idea.', 'Outra ideia.'),
  C('A report of the defects found at the end of each month on the line', 'Um relatório dos defeitos achados no fim de cada mês na linha',
    'The point is not to wait for the end.', 'O ponto é não esperar o fim.')),

Q('ex-8mg4qg6z', 'quality-in-the-flow', 'hard',
  ('Why does a blocked card stay in its column and count against the limit?', 'Por que um cartão bloqueado fica na coluna e conta no limite?'),
  ('What happens to the column?', 'O que acontece com a coluna?'),
  C('So the column fills and the problem becomes everybody’s', 'Para a coluna encher e o problema virar de todos',
    'Right: that is stopping the line, on a board.', 'Isso: é parar a linha, num quadro.', ok=True),
  C('So that it can be forgotten', 'Para poder ser esquecido', 'The opposite.', 'O contrário.'),
  C('Because blocked cards are moved to done', 'Porque cartões bloqueados vão para pronto', 'No.', 'Não.'),
  C('Because the board has nowhere else to put it', 'Porque o quadro não tem outro lugar para ele',
    'A board could have a column for it; staying put is deliberate.', 'Um quadro poderia ter uma coluna para ele; ficar é de propósito.')),

Q('ex-q70mfk3d', 'quality-in-the-flow', 'medium',
  ('Cine Aurora’s expedite lane allows one card at a time. Why does that second rule matter?',
   'A faixa urgente do Cine Aurora aceita um cartão de cada vez. Por que essa segunda regra importa?'),
  ('What if everything is urgent?', 'E se tudo for urgente?'),
  C('Without it, the lane becomes the board', 'Sem ela, a faixa vira o quadro',
    'Right: everything becomes urgent.', 'Isso: tudo vira urgente.', ok=True),
  C('Only one person can test urgent cards', 'Só uma pessoa pode testar cartões urgentes', 'Not the reason.', 'Não é o motivo.'),
  C('Urgent cards skip testing', 'Cartões urgentes pulam o teste', 'They do not.', 'Não pulam.'),
  C('The board is too narrow to draw a second card in the lane', 'O quadro é estreito demais para desenhar um segundo cartão na faixa',
    'No.', 'Não.')),

O('ex-0r9d4xf7', 'quality-in-the-flow', 'easy',
  ('At the morning stand-up, the team walks the board in a set order. Put the columns in that order.',
   'Na conversa da manhã, o time percorre o quadro numa ordem fixa. Ponha as colunas nessa ordem.'),
  ('Right to left: finishing before starting.', 'Da direita para a esquerda: terminar antes de começar.'),
  [('testing', 'testando'), ('waiting for test', 'esperando teste'), ('building', 'construindo'), ('ready', 'a fazer')],
  ('The cards nearest done come first.', 'Os cartões mais perto do pronto vêm primeiro.')),

Q('ex-zjc478h8', 'drill', 'medium',
  ('A team has a board, columns and nothing else. Which change does this lesson say will make the most difference to testing?',
   'Um time tem um quadro, colunas e nada mais. Que mudança esta aula diz que fará mais diferença para o teste?'),
  ('Visualising on its own changes little.', 'Visualizar sozinho muda pouco.'),
  C('A limit on each column, so queues cannot grow', 'Um limite em cada coluna, para as filas não crescerem',
    'Right: the limit is what makes the board a method.', 'Isso: o limite é o que faz do quadro um método.', ok=True),
  C('More colours for the cards', 'Mais cores para os cartões', 'Still only visualising.', 'Ainda é só visualizar.'),
  C('Two-week sprints', 'Sprints de duas semanas', 'That is Scrum, not Kanban.', 'Isso é Scrum, não Kanban.'),
  C('A bigger board', 'Um quadro maior', 'No.', 'Não.')),
]
