from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
Q('ex-2y3kp1ny', 'inside', 'easy',
  ('What does white-box testing use to choose its tests?', 'O que o teste caixa branca usa para escolher seus testes?'),
  ('Glass box.', 'Caixa de vidro.'),
  C('The code’s structure', 'A estrutura do código',
    'Right: its decisions, branches and paths.', 'Isso: suas decisões, desvios e caminhos.', ok=True),
  C('The requirement, read one sentence at a time and turned into a table of cases', 'O requisito, lido uma frase por vez e transformado numa tabela de casos',
    'That is lesson 6’s black-box method.', 'Esse é o método de caixa preta da aula 6.'),
  C('Customer complaints from the counter', 'Reclamações de clientes no balcão', 'That is where lesson 4 started.', 'É de onde a aula 4 partiu.'),
  C('A random sample of inputs', 'Uma amostra aleatória de entradas', 'Random inputs ignore the structure.', 'Entradas aleatórias ignoram a estrutura.')),

Q('ex-hrakn3kr', 'inside', 'medium',
  ('Which defect can white-box testing find that black-box testing from the rule cannot?',
   'Que defeito o teste caixa branca consegue achar e o teste caixa preta a partir da regra não?'),
  ('Behaviour nobody thought of.', 'Comportamento em que ninguém pensou.'),
  C('A line that gives a discount on one date no rule mentions', 'Uma linha que dá desconto numa data que nenhuma regra cita',
    'Right: the line exists, so reading or coverage finds it.', 'Isso: a linha existe, então ler ou medir cobertura a acha.', ok=True),
  C('A time without a leading zero being mispriced', 'Um horário sem zero à esquerda cobrado errado',
    'Lesson 4 found that from outside.', 'A aula 4 achou isso de fora.'),
  C('A missing check that would refuse a negative age, which the rule never asked for', 'Uma verificação que falta para recusar idade negativa, que a regra nunca pediu',
    'Missing code is what white box cannot see.', 'Código que falta é o que a caixa branca não enxerga.'),
  C('A sixty-year-old charged full price', 'Quem tem sessenta cobrado inteira', 'Lesson 1 found that from the rule.', 'A aula 1 achou isso pela regra.')),

M('ex-a58vt14k', 'inside', 'medium',
  ('Match each coverage criterion to when it is satisfied.', 'Associe cada critério de cobertura a quando ele é satisfeito.'),
  ('From least strict to most.', 'Do menos ao mais rigoroso.'),
  [(('statement', 'comando'), ('every line has run', 'toda linha rodou')),
   (('branch', 'desvio'), ('every decision went both ways', 'toda decisão foi para os dois lados')),
   (('condition', 'condição'), ('every part of a combined decision was true and false', 'toda parte de uma decisão composta foi verdadeira e falsa')),
   (('path', 'caminho'), ('every route to a return has been taken', 'toda rota até um return foi percorrida'))]),

Q('ex-x971wsg8', 'inside', 'hard',
  ('A tester who cannot program is asked to do white-box testing of `tickets.py`. By this lesson, what do they need?',
   'Alguém que testa e não programa precisa fazer teste caixa branca do `tickets.py`. Por esta aula, do que precisa?'),
  ('Read, and watch it run.', 'Ler, e observá-lo rodar.'),
  C('To read the code well enough to ask the questions, and a tool that records what ran', 'Ler o código o bastante para fazer as perguntas, e uma ferramenta que registre o que rodou',
    'Right: nobody has to change a line.', 'Isso: ninguém precisa mudar uma linha.', ok=True),
  C('To rewrite it first, in a language they already know well enough', 'Reescrevê-lo primeiro, numa linguagem que já conheça bem o bastante', 'Reading is enough.', 'Ler basta.'),
  C('Nothing: white box is only for developers', 'Nada: caixa branca é só para desenvolvedores',
    'The lesson argues the reading part is a tester’s skill.', 'A aula defende que a parte de ler é habilidade de quem testa.'),
  C('A paid tool', 'Uma ferramenta paga', 'Python’s own trace module does it.', 'O próprio módulo trace do Python faz isso.')),

N('ex-g0v380mk', 'measuring-what-ran', 'easy',
  ('With the six cases, what percentage of `tickets.py`’s lines did trace report as run?',
   'Com os seis casos, que porcentagem das linhas do `tickets.py` o trace informou como rodadas?'),
  ('The summary line.', 'A linha do resumo.'), 83, 0, '%'),

Q('ex-gb7psak4', 'measuring-what-ran', 'easy',
  ('What does `>>>>>>` mean in front of a line of the `.cover` file?',
   'O que quer dizer `>>>>>>` na frente de uma linha do arquivo `.cover`?'),
  ('`--missing`.', '`--missing`.'),
  C('The line never ran', 'A linha nunca rodou',
    'Right: `--missing` marks it.', 'Isso: o `--missing` a marca.', ok=True),
  C('The line ran more than a hundred times during the tests', 'A linha rodou mais de cem vezes durante os testes',
    'Counts are written as numbers.', 'Contagens são escritas como números.'),
  C('The line failed', 'A linha falhou', 'Coverage does not check results.', 'Cobertura não confere resultados.'),
  C('The line is a comment', 'A linha é um comentário', 'Comments carry no mark.', 'Comentários não levam marca.')),

Q('ex-4qf5vnn6', 'measuring-what-ran', 'medium',
  ('`brl` and the last two lines of `tickets.py` never ran under `cases.py`. Why is that not a gap in the testing?',
   'O `brl` e as duas últimas linhas do `tickets.py` nunca rodaram sob o `cases.py`. Por que isso não é uma lacuna no teste?'),
  ('`cases.py` calls `price` directly.', 'O `cases.py` chama o `price` diretamente.'),
  C('They are the command-line part, which lesson 6 already ran from outside', 'São a parte da linha de comando, que a aula 6 já rodou de fora',
    'Right: not every unrun line is a gap; the report needs reading.', 'Isso: nem toda linha não rodada é lacuna; o relatório precisa ser lido.', ok=True),
  C('Those lines cannot contain defects', 'Essas linhas não podem ter defeitos',
    'Any line can; these were tested another way.', 'Qualquer linha pode; essas foram testadas de outro jeito.'),
  C('trace ignores functions', 'O trace ignora funções', 'It counted `price`, a function.', 'Ele contou o `price`, uma função.'),
  C('Because 83% is above the industry’s accepted minimum for coverage', 'Porque 83% está acima do mínimo aceito pelo setor para cobertura',
    'There is no such minimum, and the number is not the argument.', 'Não existe esse mínimo, e o número não é o argumento.')),

Q('ex-w3ydha58', 'measuring-what-ran', 'medium',
  ('Which line of `price` did the six cases from lesson 6 never run?', 'Que linha do `price` os seis casos da aula 6 nunca rodaram?'),
  ('Three reductions, two tested.', 'Três descontos, dois testados.'),
  C('The reduction for people over sixty', 'O desconto para quem já passou dos sessenta anos de idade',
    'Right: no case was over sixty.', 'Isso: nenhum caso tinha mais de sessenta.', ok=True),
  C('The student reduction', 'O desconto de estudante', 'The student of 20 ran it.', 'O estudante de 20 o rodou.'),
  C('The Wednesday half, which runs just on the cheapest day of the week', 'A meia de quarta, que roda apenas no dia mais barato da semana',
    'The Wednesday adult ran it.', 'O adulto de quarta a rodou.'),
  C('The matinée price', 'O preço da matinê', 'The 16:59 case ran it.', 'O caso das 16:59 o rodou.')),

Q('ex-7rjv9rdv', 'measuring-what-ran', 'hard',
  ('After the sixty-one-year-old is added, every line of `price` has run and all seven cases pass. What does that prove about the sixty-year-old?',
   'Depois de acrescentado o de sessenta e um, toda linha do `price` rodou e os sete casos passam. O que isso prova sobre quem tem sessenta?'),
  ('Ran is not right.', 'Rodou não é estar certo.'),
  C('Nothing: sixty was never tried', 'Nada: sessenta nunca foi tentado',
    'Right: the defect is still there with full statement coverage.', 'Isso: o defeito continua lá com cobertura de comandos completa.', ok=True),
  C('That sixty is charged half, because the line that gives the reduction ran', 'Que sessenta paga meia, porque a linha que dá o desconto rodou',
    'It ran for sixty-one; for sixty it is skipped.', 'Rodou para sessenta e um; para sessenta é pulada.'),
  C('That the defect was fixed', 'Que o defeito foi corrigido', 'No code changed.', 'Nenhum código mudou.'),
  C('That coverage tools are broken', 'Que ferramentas de cobertura estão quebradas', 'The tool reported exactly what ran.', 'A ferramenta informou exatamente o que rodou.')),

Q('ex-8xnbvr0k', 'branches-and-paths', 'medium',
  ('With seven cases, every decision in `price` went both ways. What is still untested?',
   'Com sete casos, toda decisão do `price` foi para os dois lados. O que continua sem teste?'),
  ('Combinations.', 'Combinações.'),
  C('Combinations of decisions', 'Combinações de decisões',
    'Right: full branch coverage, and the stacking path never taken.', 'Isso: cobertura de desvios completa, e o caminho da soma nunca percorrido.', ok=True),
  C('Nothing', 'Nada', 'Both defects are still in the code.', 'Os dois defeitos continuam no código.'),
  C('The `else` of the session decision', 'O `else` da decisão da sessão', 'Five cases took it.', 'Cinco casos o percorreram.'),
  C('Each decision on its false side', 'Cada decisão pelo lado falso', 'Every decision was false at least once.', 'Toda decisão foi falsa pelo menos uma vez.')),

N('ex-8q0nawpp', 'branches-and-paths', 'medium',
  ('How many combinations of session, student, age group and Wednesday does the lesson count for `price`?',
   'Quantas combinações de sessão, estudante, faixa de idade e quarta a aula conta para o `price`?'),
  ('Two times two times three times two.', 'Duas vezes duas vezes três vezes duas.'), 24, 0, ('combinations', 'combinações')),

Q('ex-hd2c5xgy', 'branches-and-paths', 'hard',
  ('Why does nobody aim for full path coverage in real programs?', 'Por que ninguém busca cobertura completa de caminhos em programas reais?'),
  ('Each independent decision doubles the count.', 'Cada decisão independente dobra a conta.'),
  C('Paths multiply too fast to cover', 'Os caminhos se multiplicam rápido demais',
    'Right: twenty independent decisions already give over a million.', 'Isso: vinte decisões independentes já dão mais de um milhão.', ok=True),
  C('Paths are irrelevant to defects', 'Caminhos são irrelevantes para defeitos',
    'The stacking defect lived in an untaken path.', 'O defeito da soma morava num caminho não percorrido.'),
  C('Branch coverage already includes every path', 'Cobertura de desvios já inclui todo caminho',
    'Full branch coverage left both defects in place.', 'Cobertura de desvios completa deixou os dois defeitos no lugar.'),
  C('Tools cannot measure paths', 'Ferramentas não medem caminhos', 'The objection is the count, not the tooling.', 'A objeção é a conta, não a ferramenta.')),

Q('ex-hpxejrsy', 'branches-and-paths', 'medium',
  ('What does path thinking give a tester instead of a target?', 'O que o raciocínio por caminhos dá a quem testa em vez de uma meta?'),
  ('Which `if`s touch the same value?', 'Que `if`s mexem no mesmo valor?'),
  C('A way of asking where to look', 'Um jeito de perguntar onde olhar',
    'Right: which decisions interact, and which combinations nobody tried.', 'Isso: que decisões interagem, e que combinações ninguém tentou.', ok=True),
  C('A complete list of tests to write', 'Uma lista completa de testes para escrever', 'The list is too long to write.', 'A lista é longa demais para escrever.'),
  C('A percentage to report each sprint to the product owner, alongside the defects found', 'Uma porcentagem para informar a cada sprint à dona do produto, ao lado dos defeitos achados',
    'Exactly what it is not.', 'Exatamente o que ele não é.'),
  C('A reason to skip black box', 'Um motivo para pular a caixa preta', 'The two are used together.', 'As duas são usadas juntas.')),

Q('ex-yevzxtm1', 'what-coverage-cannot-say', 'easy',
  ('In which direction does a coverage report never lie?', 'Em que sentido um relatório de cobertura nunca mente?'),
  ('Unrun lines.', 'Linhas não rodadas.'),
  C('A line that never ran is a line nobody tested', 'Uma linha que nunca rodou é, com certeza, uma linha que ninguém testou',
    'Right: use it to find what has not been tested.', 'Isso: use-o para achar o que não foi testado.', ok=True),
  C('100% means the code is correct', '100% quer dizer que o código está certo', 'The other direction, and false.', 'O outro sentido, e falso.'),
  C('A line that ran is a line that was checked', 'Uma linha que rodou é uma linha conferida', 'Running is not checking.', 'Rodar não é conferir.'),
  C('A higher number always means better tests than a lower one', 'Um número maior sempre quer dizer testes melhores que um menor',
    'Assertions and inputs are invisible to the number.', 'Afirmações e entradas são invisíveis para o número.')),

MC('ex-tpkc2dak', 'what-coverage-cannot-say', 'medium',
  ('Which of these can a coverage report not tell you? Choose all that apply.',
   'Quais destas um relatório de cobertura não consegue te dizer? Escolha todas as que se aplicam.'),
  ('Three blind spots.', 'Três pontos cegos.'),
  C('whether the result of a line was checked', 'se o resultado de uma linha foi conferido', 'Yes: execution, not checking.', 'Sim: execução, não conferência.', ok=True),
  C('whether a line ran', 'se uma linha rodou', 'No: that is exactly what it tells.', 'Não: é exatamente o que ele diz.'),
  C('whether the values at the edges were tried', 'se os valores das bordas foram tentados', 'Yes: sixty-one ran the line, sixty was never asked for.', 'Sim: sessenta e um rodou a linha, sessenta nunca foi pedido.', ok=True),
  C('whether code is missing', 'se falta código', 'Yes: it measures only lines that exist.', 'Sim: mede só linhas que existem.', ok=True)),

Q('ex-2dxrq9mc', 'what-coverage-cannot-say', 'hard',
  ('Why is the leading-zero defect invisible to every coverage criterion?',
   'Por que o defeito do zero à esquerda é invisível para todo critério de cobertura?'),
  ('What line would be uncovered?', 'Que linha ficaria descoberta?'),
  C('No line handles the format', 'Nenhuma linha trata o formato',
    'Right: missing code leaves no trace in the structure.', 'Isso: código que falta não deixa rastro na estrutura.', ok=True),
  C('It only happens on Sundays', 'Só acontece aos domingos', 'Lesson 4 ruled Sunday out.', 'A aula 4 descartou o domingo.'),
  C('trace skips lines that contain strings', 'O trace pula linhas que contêm strings', 'It counts lines whatever they contain.', 'Ele conta linhas seja o que for que contenham.'),
  C('The line `if time < "17:00"` never ran', 'A linha `if time < "17:00"` nunca rodou', 'It ran in every case.', 'Rodou em todo caso.')),

O('ex-ptfg93s2', 'drill', 'easy',
  ('Order the coverage criteria from least strict to most strict.', 'Ordene os critérios de cobertura do menos ao mais rigoroso.'),
  ('Lines first, routes last.', 'Linhas primeiro, rotas por último.'),
  [('statement', 'comando'), ('branch', 'desvio'), ('condition', 'condição'), ('path', 'caminho')],
  ('Each is satisfied by more tests than the one before it.', 'Cada um é satisfeito por mais testes que o anterior.')),
]
