"""Lesson 1: object orientation, and the lab."""

EXERCISES = [
    # ---- the-language
    dict(id='ex-1sdx2wyz', section='the-language', type='quiz', difficulty='easy',
         prompt=('Why does this course show its programs in one language rather than in all four of the backend track?',
                 'Por que este curso mostra seus programas numa só linguagem em vez das quatro da trilha backend?'),
         choices=[
             (False, ('Because the patterns only exist in Python', 'Porque os padrões só existem em Python'),
              ('A strategy or an aggregate is the same idea in every language; the course says so in its first reading section.',
               'Uma strategy ou um agregado é a mesma ideia em qualquer linguagem; o curso diz isso na primeira seção de leitura.')),
             (True, ('Four versions would bury the design under syntax, and pseudocode runs nowhere',
                     'Quatro versões enterrariam o projeto na sintaxe, e pseudocódigo não roda em lugar nenhum'),
              ('Right. One runnable language was the option left once the other two were weighed.',
               'Isso. Uma linguagem que roda foi a opção que sobrou depois de pesar as outras duas.')),
             (False, ('Because Go and Java cannot express polymorphism', 'Porque Go e Java não conseguem expressar polimorfismo'),
              ('Both can, through interfaces; the table in the section shows how each one writes it.',
               'Os dois conseguem, por interfaces; a tabela da seção mostra como cada um escreve.')),
             (False, ('Because the platform runs Python programs for the student', 'Porque a plataforma roda programas Python para o aluno'),
              ('The platform runs nothing; every program runs on your own machine.',
               'A plataforma não roda nada; todo programa roda na sua própria máquina.')),
         ]),
    dict(id='ex-05bqw31b', section='the-language', type='matching', difficulty='medium',
         prompt=('Match the Python construct to what Java calls it.', 'Associe a construção em Python ao nome que ela tem em Java.'),
         pairs=[
             (('self', 'self'), ('this', 'this')),
             (('class Channel(Protocol)', 'class Channel(Protocol)'), ('interface Channel', 'interface Channel')),
             (('@dataclass(frozen=True)', '@dataclass(frozen=True)'), ('record', 'record')),
             (('a leading underscore, _due', 'um sublinhado na frente, _due'), ('private', 'private')),
         ]),
    # ---- the-lab
    dict(id='ex-5mff8kc5', section='the-lab', type='quiz', difficulty='easy',
         prompt=('What does the lab for this course need on your machine?', 'Do que o laboratório deste curso precisa na sua máquina?'),
         choices=[
             (False, ('Python, a database server and a web framework', 'Python, um servidor de banco de dados e um framework web'),
              ('No lesson uses a server; lesson 10 uses SQLite, which comes inside Python.',
               'Nenhuma lição usa servidor; a lição 10 usa SQLite, que já vem dentro do Python.')),
             (True, ('Python 3.12+, a terminal and an editor', 'Python 3.12 ou mais novo, um terminal e um editor'),
              ('Right. Nothing outside the standard library, in any lesson.',
               'Isso. Nada fora da biblioteca padrão, em nenhuma lição.')),
             (False, ('A virtual machine the platform provides', 'Uma máquina virtual fornecida pela plataforma'),
              ('The platform provides no machine; the lab is yours.', 'A plataforma não fornece máquina nenhuma; o laboratório é seu.')),
             (False, ('Python plus the four languages of the backend track', 'Python mais as quatro linguagens da trilha backend'),
              ('Your own language is welcome for rewriting the programs, and not needed to run them.',
               'A sua linguagem serve para reescrever os programas, e não é necessária para rodá-los.')),
         ]),
    dict(id='ex-kqve5pjh', section='the-lab', type='quiz', difficulty='medium',
         prompt=('Your work laptop does not let you install software. Which path does the lab section point you to?',
                 'O notebook do trabalho não deixa você instalar programas. Que caminho a seção do laboratório indica?'),
         choices=[
             (False, ('Install Python anyway, with administrator rights borrowed from IT', 'Instalar o Python com uma senha de administrador da TI'),
              ('The section does not suggest working round your employer; it names the paths that need no install.',
               'A seção não sugere contornar o empregador; ela cita os caminhos que não precisam de instalação.')),
             (False, ('Skip the lab and read the transcripts', 'Pular o laboratório e ler as transcrições'),
              ('Every lesson asks you to run its programs; reading alone is the thing the lab exists to avoid.',
               'Toda lição pede que você rode os programas; só ler é justamente o que o laboratório existe para evitar.')),
             (True, ('A virtual machine, or an online environment if that is not possible either', 'Uma máquina virtual, ou um ambiente online se nem isso for possível'),
              ('Right. The VM is the choice for a computer that is not yours to install on, and online costs the computer nothing.',
               'Isso. A VM é a escolha para um computador em que você não pode instalar, e o online não custa nada ao computador.')),
         ]),
    # ---- first-run
    dict(id='ex-senqnpdh', section='first-run', type='cloze', difficulty='easy',
         prompt=('On Ubuntu 24.04, the command that runs Python is ___ .', 'No Ubuntu 24.04, o comando que roda o Python é ___ .'),
         blanks=[dict(en=['python3'], pt=['python3'])]),
    dict(id='ex-7zh15kcm', section='first-run', type='quiz', difficulty='medium',
         prompt=('Why does each lesson keep its programs in its own directory under ~/patterns?',
                 'Por que cada lição guarda seus programas num diretório próprio dentro de ~/patterns?'),
         choices=[
             (True, ('So two lessons never overwrite each other\'s files', 'Para duas lições nunca sobrescreverem os arquivos uma da outra'),
              ('Right. Several lessons have a main.py or a test file of the same name.',
               'Isso. Várias lições têm um main.py ou um arquivo de teste com o mesmo nome.')),
             (False, ('Because Python refuses to run a file outside a directory called patterns', 'Porque o Python só roda arquivos dentro de patterns'),
              ('Python runs a file from anywhere; the directory is an arrangement for you.',
               'O Python roda um arquivo de qualquer lugar; o diretório é uma arrumação para você.')),
             (False, ('So the platform can collect them at the end of each lesson', 'Para a plataforma recolhê-los no fim de cada lição'),
              ('Nothing is collected; your programs stay on your machine.', 'Nada é recolhido; seus programas ficam na sua máquina.')),
         ]),
    # ---- when-setup-fails
    dict(id='ex-xzr7m4n0', section='when-setup-fails', type='quiz', difficulty='medium',
         prompt=("Python answers can't open file '/home/ana/check.py'. What is the likely cause?",
                 "O Python responde can't open file '/home/ana/check.py'. Qual é a causa provável?"),
         choices=[
             (False, ('The file has an indentation error', 'O arquivo tem um erro de indentação'),
              ('An indentation error is reported from inside the file; this one never opened it.',
               'Um erro de indentação é relatado de dentro do arquivo; este nem chegou a abri-lo.')),
             (True, ('The terminal is in the home directory, not in ~/patterns/oo', 'O terminal está no diretório pessoal, não em ~/patterns/oo'),
              ('Right. The path in the message shows where Python looked.', 'Isso. O caminho na mensagem mostra onde o Python procurou.')),
             (False, ('The Python installed on this machine is older than the 3.12 the course needs', 'O Python instalado é mais velho que 3.12'),
              ('An old Python would open the file and refuse later, with check.py\'s own sentence.',
               'Um Python velho abriria o arquivo e recusaria depois, com a frase do próprio check.py.')),
             (False, ('The file was saved with Windows line endings', 'O arquivo foi salvo com finais de linha do Windows'),
              ('Line endings do not stop a file being found; the message is about the path.',
               'Finais de linha não impedem que o arquivo seja encontrado; a mensagem é sobre o caminho.')),
         ]),
    dict(id='ex-r7hg6g8w', section='when-setup-fails', type='quiz', difficulty='easy',
         prompt=('A traceback ends in ModuleNotFoundError: No module named \'notices\'. What fixes it?',
                 'Um traceback termina em ModuleNotFoundError: No module named \'notices\'. O que resolve?'),
         choices=[
             (False, ('Installing notices from the internet with pip', 'Instalar notices da internet com pip'),
              ('notices.py is a file from the lesson, not a published package.', 'notices.py é um arquivo da lição, não um pacote publicado.')),
             (False, ('Renaming member.py to notices.py, so the import finds a file of that name', 'Renomear member.py para notices.py, para o import achar um arquivo com esse nome'),
              ('Then member.py would be gone, and the import would find a file without the classes it needs.',
               'Aí member.py sumiria, e o import acharia um arquivo sem as classes de que precisa.')),
             (True, ('Saving notices.py in the same directory as member.py', 'Salvar notices.py no mesmo diretório que member.py'),
              ('Right. Python looks first in the directory of the program it runs.', 'Isso. O Python procura primeiro no diretório do programa que está rodando.')),
         ]),
    dict(id='ex-8wcxfjz3', section='when-setup-fails', type='ordering', difficulty='medium',
         prompt=('Put the steps for reading a Python error in the order the section gives them.',
                 'Ponha em ordem os passos para ler um erro do Python, como a seção os apresenta.'),
         items=[('Read the last line: the kind of error and its message', 'Ler a última linha: o tipo de erro e a mensagem'),
                ('Find the file and line number just above it', 'Achar o arquivo e o número da linha logo acima'),
                ('Compare that line with the lesson\'s, character by character', 'Comparar essa linha com a da lição, caractere por caractere'),
                ('Check the line before it for a missing colon or bracket', 'Conferir a linha anterior atrás de dois-pontos ou parêntese faltando')],
         trap=('Starting from the top of a traceback reads the route before the cause.',
               'Começar pelo alto de um traceback é ler o caminho antes da causa.')),
    # ---- encapsulation
    dict(id='ex-rwvng0b2', section='encapsulation', type='quiz', difficulty='medium',
         prompt=('What is encapsulation for, in the sense this lesson uses?', 'Para que serve o encapsulamento, no sentido que esta lição usa?'),
         choices=[
             (False, ('Hiding the fields so other programmers cannot read the code', 'Esconder os campos para outros programadores não lerem o código'),
              ('The code stays readable; what is protected is the state, from being set to something the rules forbid.',
               'O código continua legível; o que se protege é o estado, de ser posto num valor que as regras proíbem.')),
             (True, ('Keeping state and the rules about it together, so nothing outside breaks the rules',
                     'Manter o estado e as regras sobre ele juntos, para nada de fora conseguir quebrar as regras'),
              ('Right. Private fields are one mechanism; the promise is the idea.', 'Isso. Campos privados são um mecanismo; a promessa é a ideia.')),
             (False, ('Giving every field a getter and a setter', 'Dar a todo campo um getter e um setter'),
              ('That has the syntax and none of the promise: every rule is still kept by whoever calls the setters.',
               'Isso tem a sintaxe e nada da promessa: toda regra continua nas mãos de quem chama os setters.')),
             (False, ('Making the program run faster by caching values', 'Fazer o programa rodar mais rápido guardando valores em cache'),
              ('Speed is not the point; the fine in loan.py is computed every time on purpose.',
               'Velocidade não é a questão; a multa em loan.py é calculada toda vez de propósito.')),
         ]),
    dict(id='ex-19qz97n4', section='encapsulation', type='numeric', difficulty='medium',
         prompt=('A loan of 14 days starts on 2 March 2026. The fine is 50 cents a day. The book comes back on 21 March. What is the fine, in cents?',
                 'Um empréstimo de 14 dias começa em 2 de março de 2026. A multa é de 50 centavos por dia. O livro volta em 21 de março. Qual é a multa, em centavos?'),
         hint=('The due date is 16 March.', 'A data de devolução é 16 de março.'),
         value=250, tolerance=0, unit=('cents', 'centavos')),
    dict(id='ex-gmm25b0s', section='encapsulation', type='quiz', difficulty='hard',
         prompt=('Why does Loan compute the fine every time instead of storing it in a field?',
                 'Por que Loan calcula a multa toda vez em vez de guardá-la num campo?'),
         choices=[
             (False, ('Python cannot store an integer in an object\'s field', 'O Python não consegue guardar um inteiro no campo de um objeto'),
              ('It can; _due and _returned_on are fields.', 'Consegue; _due e _returned_on são campos.')),
             (False, ('A stored fine would be faster, and the lesson wants to show the slow way first',
                      'Uma multa guardada seria mais rápida, e a lição quer mostrar o jeito lento primeiro'),
              ('The lesson does not come back to a faster version; computing it is the design.',
               'A lição não volta a uma versão mais rápida; calcular é o projeto.')),
             (True, ('A stored fine is a second copy of the dates, and copies drift apart', 'Uma multa guardada é uma segunda cópia das datas, e cópias se desencontram'),
              ('Right. One source of truth, and the fine follows from it.', 'Isso. Uma fonte de verdade, e a multa decorre dela.')),
         ]),
    dict(id='ex-41dbrd4k', section='encapsulation', type='quiz', difficulty='medium',
         prompt=('Some code writes loan._returned_on = None directly. What does Python do?',
                 'Um trecho de código escreve loan._returned_on = None diretamente. O que o Python faz?'),
         choices=[
             (True, ('Lets it: the underscore is a convention, not a lock', 'Deixa: o sublinhado é uma convenção, não uma tranca'),
              ('Right. The line is for readers and reviewers; the interpreter does not enforce it.',
               'Isso. A linha é para quem lê e revisa; o interpretador não a impõe.')),
             (False, ('Raises AttributeError, because the field is private', 'Lança AttributeError, porque o campo é privado'),
              ('That is closer to Java or TypeScript\'s #field; Python has no private keyword.',
               'Isso está mais perto de Java ou do #field do TypeScript; o Python não tem palavra-chave private.')),
             (False, ('Refuses to run the file at all', 'Recusa-se a rodar o arquivo'),
              ('Nothing about the underscore is checked before running.', 'Nada no sublinhado é verificado antes de rodar.')),
             (False, ('Calls give_back automatically to keep the rules', 'Chama give_back automaticamente para manter as regras'),
              ('Assignment never calls a method on its own here; the write bypasses the rule entirely.',
               'A atribuição não chama método nenhum por conta própria aqui; a escrita passa por cima da regra.')),
         ]),
    # ---- inheritance
    dict(id='ex-fxykqh5x', section='inheritance', type='quiz', difficulty='easy',
         prompt=('In items.py, what does Film\'s describe() do with super().describe()?',
                 'Em items.py, o que o describe() de Film faz com super().describe()?'),
         choices=[
             (False, ('Ignores it and writes a description from nothing', 'Ignora e escreve uma descrição do zero'),
              ('That is what ReferenceBook does.', 'Isso é o que ReferenceBook faz.')),
             (True, ('Takes the parent\'s description and adds the running time to it', 'Pega a descrição do pai e acrescenta a duração'),
              ('Right. It extends rather than replaces.', 'Isso. Ele estende em vez de substituir.')),
             (False, ('Calls Book\'s version of describe, because Book is defined first in the file', 'Chama a versão de Book, porque Book vem primeiro'),
              ('Book is a sibling, not a parent; super() follows Film\'s own chain.',
               'Book é um irmão, não um pai; super() segue a cadeia do próprio Film.')),
         ]),
    dict(id='ex-kjwd5959', section='inheritance', type='ordering', difficulty='medium',
         prompt=('A call to describe() on a Film. Put the places Python looks in order.',
                 'Uma chamada a describe() num Film. Ponha em ordem os lugares onde o Python procura.'),
         items=[('Film', 'Film'), ('Item', 'Item'), ('object', 'object')],
         trap=('The child is searched first; that is what lets it override.', 'O filho é procurado primeiro; é isso que permite sobrescrever.')),
    dict(id='ex-45n1abcq', section='inheritance', type='quiz', difficulty='hard',
         prompt=('Somebody adds a required argument, branch, to Item.__init__. Which classes in items.py break?',
                 'Alguém acrescenta um argumento obrigatório, branch, ao Item.__init__. Quais classes de items.py quebram?'),
         choices=[
             (False, ('Only Item, because the children have constructors of their own', 'Só Item, porque os filhos têm construtores próprios'),
              ('Only Film has one, and it calls super().__init__ with two arguments.',
               'Só Film tem um, e ele chama super().__init__ com dois argumentos.')),
             (False, ('Only Film, because it is the one that calls super().__init__', 'Só Film, porque é ele que chama super().__init__'),
              ('Book and ReferenceBook use Item\'s constructor directly, so their callers break too.',
               'Book e ReferenceBook usam o construtor de Item diretamente, então quem os cria também quebra.')),
             (True, ('All three children, plus every line that creates one', 'Os três filhos, mais toda linha que cria um deles'),
              ('Right. The parent\'s constructor is part of every child\'s contract.',
               'Isso. O construtor do pai faz parte do contrato de todo filho.')),
             (False, ('None, as long as branch has no default value', 'Nenhuma, desde que branch não tenha valor padrão'),
              ('No default is exactly what makes it required, and every call without it fails.',
               'Não ter padrão é justamente o que o torna obrigatório, e toda chamada sem ele falha.')),
         ]),
    # ---- polymorphism
    dict(id='ex-dqqsdb1n', section='polymorphism', type='quiz', difficulty='medium',
         prompt=('A fourth channel, WhatsApp, is added to notices.py. What has to change in remind()?',
                 'Um quarto canal, WhatsApp, entra em notices.py. O que precisa mudar em remind()?'),
         choices=[
             (True, ('Nothing', 'Nada'),
              ('Right. remind() knows one method, deliver, and the new class has it.',
               'Isso. remind() conhece um método, deliver, e a classe nova tem esse método.')),
             (False, ('A new elif branch for the new channel', 'Um novo ramo elif para o canal novo'),
              ('That is the version without polymorphism the section starts from.', 'Essa é a versão sem polimorfismo de onde a seção parte.')),
             (False, ('Its type annotation, to list the new class', 'A anotação de tipo, para listar a classe nova'),
              ('The annotation says Channel, which the new class satisfies by having deliver.',
               'A anotação diz Channel, que a classe nova satisfaz por ter deliver.')),
         ]),
    dict(id='ex-srtv5h2g', section='polymorphism', type='matching', difficulty='hard',
         prompt=('Match each language to how it decides that Email is a Channel.',
                 'Associe cada linguagem a como ela decide que Email é um Channel.'),
         pairs=[
             (('Java', 'Java'), ('The class must declare implements Channel', 'A classe precisa declarar implements Channel')),
             (('Go', 'Go'), ('Having the method is enough, checked at compile time', 'Ter o método basta, verificado na compilação')),
             (('Python without a checker', 'Python sem verificador'), ('Nothing is checked until the call runs', 'Nada é verificado até a chamada rodar')),
         ]),
    dict(id='ex-v89a4gje', section='polymorphism', type='cloze', difficulty='easy',
         prompt=('Calling a method because an object has it, without checking its class, is called ___ typing.',
                 'Chamar um método porque o objeto o tem, sem verificar a classe, se chama ___ typing.'),
         blanks=[dict(en=['duck'], pt=['duck'])]),
    # ---- composition
    dict(id='ex-xrgqz95p', section='composition', type='numeric', difficulty='medium',
         prompt=('With inheritance, a member class exists for every combination of status and channel. With 2 statuses and 4 channels, how many classes below Member?',
                 'Com herança, existe uma classe de membro para cada combinação de categoria e canal. Com 2 categorias e 4 canais, quantas classes abaixo de Member?'),
         value=8, tolerance=0, unit=('classes', 'classes')),
    dict(id='ex-0rd67gvz', section='composition', type='quiz', difficulty='medium',
         prompt=('Bia switches from e-mail to SMS. In member.py, what happens to her Member object?',
                 'Bia troca o e-mail por SMS. Em member.py, o que acontece com o objeto Member dela?'),
         choices=[
             (False, ('It is replaced by a new SmsMember object', 'É substituído por um novo objeto SmsMember'),
              ('That is what inheritance would force. Here the same object keeps its identity.',
               'É o que a herança obrigaria. Aqui o mesmo objeto mantém a identidade.')),
             (True, ('The same object, with another channel', 'Continua o mesmo, com outro canal'),
              ('Right. Composition lets a part change at run time.', 'Isso. A composição deixa uma parte mudar em tempo de execução.')),
             (False, ('Python raises an error, because channel was set in the constructor', 'O Python lança erro, porque channel foi definido no construtor'),
              ('A field set in the constructor can be reassigned later; nothing here forbids it.',
               'Um campo definido no construtor pode ser reatribuído depois; nada aqui proíbe.')),
         ]),
    # ---- drill
    dict(id='ex-66px7vk2', section='drill', type='matching', difficulty='medium',
         prompt=('Match each sentence to the idea it describes.', 'Associe cada frase à ideia que ela descreve.'),
         pairs=[
             (('A loan refuses a second return', 'Um empréstimo recusa uma segunda devolução'), ('encapsulation', 'encapsulamento')),
             (('Film is an Item with a shorter loan', 'Film é um Item com empréstimo mais curto'), ('inheritance', 'herança')),
             (('remind() calls deliver on whatever it is given', 'remind() chama deliver em qualquer coisa que receba'), ('polymorphism', 'polimorfismo')),
             (('A member holds the channel it is reached by', 'Um membro guarda o canal pelo qual é avisado'), ('composition', 'composição')),
         ]),
    dict(id='ex-ecd6hmqp', section='drill', type='multiple-choice', difficulty='hard',
         prompt=('Which of these are signs that a design needs composition rather than another subclass? Choose all that apply.',
                 'Quais destes são sinais de que um projeto precisa de composição em vez de mais uma subclasse? Marque todos que se aplicam.'),
         choices=[
             (True, ('Two independent things vary, and each combination would need a class', 'Duas coisas variam independentemente, e cada combinação pediria uma classe'),
              ('Right. That is the multiplication the composition section counts.', 'Isso. É a multiplicação que a seção de composição conta.')),
             (True, ('The part has to change while the object lives', 'A parte precisa mudar enquanto o objeto existe'),
              ('Right. A class is fixed when the object is made; a field is not.', 'Isso. A classe é fixada quando o objeto nasce; um campo não.')),
             (False, ('The child really is a kind of the parent and keeps all its promises', 'O filho é de fato um tipo do pai e cumpre todas as promessas dele'),
              ('That is the case where inheritance fits; lesson 2 says when.', 'Esse é o caso em que a herança cabe; a lição 2 diz quando.')),
             (True, ('Saying it aloud gives "has a" rather than "is a"', 'Dita em voz alta, a frase sai "tem um" em vez de "é um"'),
              ('Right. A member has a channel; it is not one.', 'Isso. Um membro tem um canal; ele não é um canal.')),
         ]),
    dict(id='ex-n8ww6byf', section='drill', type='quiz', difficulty='hard',
         prompt=('ReferenceBook inherits from Item but cannot be lent. Which later idea of the course is that a warning about?',
                 'ReferenceBook herda de Item mas não pode ser emprestado. De qual ideia posterior do curso isso é um aviso?'),
         choices=[
             (False, ('The singleton, because only one reference book exists', 'O singleton, porque só existe um livro de referência'),
              ('Several reference books exist; the problem is a promise the child cannot keep.',
               'Existem vários livros de referência; o problema é uma promessa que o filho não cumpre.')),
             (True, ('Liskov substitution: a child must keep the promises its parent makes', 'Substituição de Liskov: um filho precisa cumprir as promessas do pai'),
              ('Right. Lesson 3 comes back to exactly this class.', 'Isso. A lição 3 volta exatamente a esta classe.')),
             (False, ('Event sourcing, because the loans should be stored as events', 'Event sourcing, porque os empréstimos deviam ser guardados como eventos'),
              ('Storage is a different question; this one is about what a subclass promises.',
               'Armazenamento é outra questão; esta é sobre o que uma subclasse promete.')),
             (False, ('Dependency injection, because the loan length should be passed in from outside the class', 'Injeção de dependência, porque a duração devia vir de fora'),
              ('Passing the number in would not make a reading-room book lendable.', 'Passar o número de fora não tornaria um livro de sala de leitura emprestável.')),
         ]),
]
