"""Lesson 2: composition over inheritance."""

EXERCISES = [
    # ---- fragile-base-class
    dict(id='ex-ygfg5zbk', section='fragile-base-class', type='quiz', difficulty='medium',
         prompt=('The first counting.py put four titles on the shelf and printed counted: 7. Where did the extra three come from?',
                 'O primeiro counting.py pôs quatro títulos na prateleira e imprimiu counted: 7. De onde vieram os três a mais?'),
         choices=[
             (False, ('super() ran both the parent\'s add_all and the child\'s', 'super() rodou o add_all do pai e o do filho'),
              ('super() runs the parent\'s version only; the child\'s add_all ran once, because main called it once.',
               'super() roda só a versão do pai; o add_all do filho rodou uma vez, porque o programa o chamou uma vez.')),
             (True, ('Shelf.add_all calls self.add, and self is the child', 'Shelf.add_all chama self.add, e self é o filho'),
              ('Right. Each of the three self-calls landed in CountingShelf.add, which counted the titles a second time.',
               'Isso. Cada uma das três chamadas a self caiu em CountingShelf.add, que contou os títulos uma segunda vez.')),
             (False, ('The counter was also incremented by __len__ each time the program asked how many titles there were',
                      'O contador também era incrementado por __len__ cada vez que o programa perguntava quantos títulos havia'),
              ('__len__ only reads the list; nothing in it touches added.',
               '__len__ só lê a lista; nada nele mexe em added.')),
             (False, ('Python called __init__ a second time, once for each class in the hierarchy', 'O Python chamou __init__ uma segunda vez, uma para cada classe da hierarquia'),
              ('__init__ ran once per object, and it sets the counter to zero rather than adding to it.',
               '__init__ rodou uma vez por objeto, e ele zera o contador em vez de somar.')),
         ]),
    dict(id='ex-se5azpam', section='fragile-base-class', type='numeric', difficulty='medium',
         prompt=('With the second shelf.py (add_all extends the list) and the second counting.py (only add is overridden), a program adds 2 titles one at a time with add, then 5 at once with add_all. What does counted print?',
                 'Com o segundo shelf.py (add_all estende a lista) e o segundo counting.py (só add é sobrescrito), um programa acrescenta 2 títulos um a um com add, depois 5 de uma vez com add_all. O que counted imprime?'),
         hint=('Which of the two calls still passes through the child\'s add?', 'Qual das duas chamadas ainda passa pelo add do filho?'),
         value=2, tolerance=0, unit=('titles', 'títulos')),
    dict(id='ex-32s1a1kj', section='fragile-base-class', type='quiz', difficulty='hard',
         prompt=('CountingShelf overrides only add and relies on Shelf.add_all looping over self.add. Which change to Shelf leaves its count right?',
                 'CountingShelf sobrescreve só add e conta com Shelf.add_all fazendo um laço sobre self.add. Qual mudança em Shelf mantém a contagem certa?'),
         choices=[
             (False, ('add_all calls a new add_many, which extends the list', 'add_all chama um novo add_many, que estende a lista'),
              ('Then batch titles never pass through add, and the child stops counting them, as in the third run.',
               'Aí os títulos em lote nunca passam por add, e o filho para de contá-los, como na terceira execução.')),
             (True, ('Renaming the private list _titles to _items', 'Renomear a lista privada _titles para _items, e mais nada'),
              ('Right. The child never touches the list, and the self-call it depends on is unchanged.',
               'Isso. O filho nunca mexe na lista, e a chamada a self de que ele depende continua igual.')),
             (False, ('Making add call self.add_all([title]), so all storing goes through one method',
                      'Fazer add chamar self.add_all([title]), para todo armazenamento passar por um método só'),
              ('add_all loops back into add, which calls add_all again: the child\'s first add never returns.',
               'add_all volta para add, que chama add_all de novo: o primeiro add do filho nunca termina.')),
         ]),
    # ---- class-explosion
    dict(id='ex-fqgxr3e7', section='class-explosion', type='numeric', difficulty='medium',
         prompt=('explosion.py ends at 36 subclasses for four axes. A fifth axis arrives: the loan can be ordinary or express, two options. How many subclasses does one-class-per-combination need now?',
                 'explosion.py termina em 36 subclasses para quatro eixos. Chega um quinto eixo: o empréstimo pode ser comum ou expresso, duas opções. De quantas subclasses o projeto de uma classe por combinação precisa agora?'),
         value=72, tolerance=0, unit=('classes', 'classes')),
    dict(id='ex-zj3mg5xk', section='class-explosion', type='quiz', difficulty='medium',
         prompt=('Why does the class explosion go unnoticed in the early life of a design?',
                 'Por que a explosão de classes passa despercebida no começo da vida de um projeto?'),
         choices=[
             (False, ('Because Python generates the combined classes on its own until there are more than ten',
                      'Porque o Python gera as classes combinadas sozinho até passarem de dez'),
              ('Python generates nothing; every class in that design is written by somebody.',
               'O Python não gera nada; toda classe desse projeto é escrita por alguém.')),
             (False, ('Because the first axis is always added with composition', 'Porque o primeiro eixo sempre entra por composição'),
              ('In the program the first axis is a hierarchy too; the two designs simply cost the same at that size.',
               'No programa o primeiro eixo também é uma hierarquia; os dois projetos só custam o mesmo nesse tamanho.')),
             (True, ('With two axes of two options, both designs cost four', 'Com dois eixos de duas opções, os dois projetos custam quatro'),
              ('Right. A product and a sum agree at 2 × 2 and 2 + 2; they part at the third axis, twelve against seven.',
               'Isso. Um produto e uma soma coincidem em 2 × 2 e 2 + 2; eles se separam no terceiro eixo, doze contra sete.')),
             (False, ('Because a class only becomes expensive once it has more than one method', 'Porque uma classe só fica cara quando tem mais de um método'),
              ('The cost counted here is the number of classes and where a change has to be made, whatever their size.',
               'O custo contado aqui é o número de classes e onde uma mudança tem de ser feita, seja qual for o tamanho delas.')),
         ]),
    dict(id='ex-ssx4yg6w', section='class-explosion', type='quiz', difficulty='hard',
         prompt=('The catalogue team wants Book and Film at the top of the loan classes; the fines office wants the fine rule there. How does a composed design settle it?',
                 'O time do catálogo quer Book e Film no alto das classes de empréstimo; o setor de multas quer a regra de multa lá. Como um projeto por composição resolve?'),
         choices=[
             (True, ('Neither goes on top: item and fine rule each become a field', 'Nenhum fica no alto: o item e a regra de multa viram campos'),
              ('Right. A loan has an item and has a fine rule, and neither axis has to be nested inside the other.',
               'Isso. Um empréstimo tem um item e tem uma regra de multa, e nenhum eixo precisa ficar dentro do outro.')),
             (False, ('The team that owns more classes wins, since its axis multiplies less', 'Vence o time dono de mais classes, já que o eixo dele multiplica menos'),
              ('Which axis is on top does not change the product; composition removes the choice instead of making it.',
               'Qual eixo fica no alto não muda o produto; a composição elimina a escolha em vez de fazê-la.')),
             (False, ('It uses two hierarchies and multiple inheritance to join them', 'Usa duas hierarquias e herança múltipla para juntá-las'),
              ('That still declares one class per combination, which is the explosion again with more parents.',
               'Isso continua declarando uma classe por combinação, que é a explosão de novo com mais pais.')),
         ]),
    # ---- delegation
    dict(id='ex-qj58rwkq', section='delegation', type='quiz', difficulty='medium',
         prompt=('CountedShelf counted 4 with both versions of shelf.py. What protects it from the self-call in the first version?',
                 'CountedShelf contou 4 com as duas versões de shelf.py. O que o protege da chamada a self da primeira versão?'),
         choices=[
             (False, ('It overrides add_all, which stops the parent\'s version from running', 'Ele sobrescreve add_all, o que impede a versão do pai de rodar'),
              ('Its add_all does run the inner shelf\'s add_all; what matters is whose add that one then calls.',
               'O add_all dele roda, sim, o add_all da prateleira de dentro; o que importa é de quem é o add que este chama depois.')),
             (True, ('Inside the held shelf, self is that Shelf, so its self.add never reaches the wrapper',
                     'Dentro da prateleira guardada, self é aquele Shelf, então o self.add dele nunca chega ao invólucro'),
              ('Right. A held object calls its own methods on itself, never on the object holding it.',
               'Isso. Um objeto guardado chama os próprios métodos em si mesmo, nunca no objeto que o guarda.')),
             (False, ('Python skips method lookup for objects stored in fields', 'O Python pula a busca de métodos para objetos guardados em campos'),
              ('Lookup happens as usual; it starts from the inner object\'s class, which is Shelf.',
               'A busca acontece normalmente; ela começa pela classe do objeto de dentro, que é Shelf.')),
         ]),
    dict(id='ex-cjhvrhpz', section='delegation', type='quiz', difficulty='hard',
         prompt=('A CountedShelf forwards with __getattr__ instead of writing its methods out. Shelf later gains add_many. What happens to titles added through it?',
                 'Um CountedShelf repassa com __getattr__ em vez de escrever os métodos. Mais tarde Shelf ganha add_many. O que acontece com os títulos acrescentados por ele?'),
         choices=[
             (False, ('They raise AttributeError, since the wrapper never defined add_many', 'Levantam AttributeError, já que o invólucro nunca definiu add_many'),
              ('__getattr__ exists precisely to answer for attributes the wrapper lacks, so the call goes through.',
               '__getattr__ existe justamente para responder por atributos que o invólucro não tem, então a chamada passa.')),
             (False, ('They are counted twice, as in the first counting.py', 'São contados duas vezes, como no primeiro counting.py'),
              ('Nothing in the wrapper counts them at all; the inner shelf never calls back into it.',
               'Nada no invólucro os conta; a prateleira de dentro nunca chama o invólucro de volta.')),
             (True, ('They are shelved and never counted, with no error anywhere', 'Vão para a prateleira e nunca são contados, sem erro nenhum'),
              ('Right. Automatic forwarding offers every new method without anybody deciding, and that one bypasses the counter.',
               'Isso. O repasse automático oferece todo método novo sem ninguém decidir, e esse passa por fora do contador.')),
             (False, ('Python refuses to load counted.py until add_many is written out by hand', 'O Python se recusa a carregar counted.py até add_many ser escrito à mão'),
              ('Python checks nothing of the kind; the program runs and the report is quietly wrong.',
               'O Python não verifica nada disso; o programa roda e o relatório fica errado em silêncio.')),
         ]),
    dict(id='ex-e280j5v5', section='delegation', type='cloze', difficulty='easy',
         prompt=('An object that holds another and forwards calls to it, adding what it needs on the way, is using ___ .',
                 'Um objeto que guarda outro e repassa chamadas a ele, acrescentando no caminho o que precisa, está usando ___ .'),
         blanks=[dict(en=['delegation'], pt=['delegação', 'delegacao', 'delegation'])]),
    # ---- swapping-behaviour
    dict(id='ex-rws6ss79', section='swapping-behaviour', type='quiz', difficulty='easy',
         prompt=('During the amnesty week every open loan must stop charging. Why is that one loop of assignments in fines.py?',
                 'Na semana de anistia todo empréstimo aberto tem de parar de cobrar. Por que isso é um laço de atribuições em fines.py?'),
         choices=[
             (True, ('Each loan holds its fine rule in a field, and a field can be reassigned', 'Cada empréstimo guarda sua regra num campo, e um campo aceita outro valor'),
              ('Right. Replacing the part changes the behaviour of an object that already exists.',
               'Isso. Trocar a parte muda o comportamento de um objeto que já existe.')),
             (False, ('Amnesty is a subclass of Loan, so the loans become amnesty loans', 'Amnesty é subclasse de Loan, então os empréstimos viram empréstimos de anistia'),
              ('Amnesty is a fine rule with no parent at all; the loans stay Loan objects.',
               'Amnesty é uma regra de multa sem pai nenhum; os empréstimos continuam sendo objetos Loan.')),
             (False, ('Python can change an object\'s class, and the program does that for each loan',
                      'O Python consegue mudar a classe de um objeto, e o programa faz isso para cada empréstimo'),
              ('Assigning __class__ is possible and the section advises against it; fines.py assigns a policy instead.',
               'Atribuir __class__ é possível e a seção desaconselha; fines.py atribui uma regra em vez disso.')),
         ]),
    dict(id='ex-72aqepgd', section='swapping-behaviour', type='numeric', difficulty='medium',
         prompt=('A student\'s loan is due on 16 March and holds GraceDays(3, PerDay(75)). It comes back on 23 March. What is the fine, in cents?',
                 'O empréstimo de um estudante vence em 16 de março e guarda GraceDays(3, PerDay(75)). Ele volta em 23 de março. Qual é a multa, em centavos?'),
         hint=('Seven days late, before the grace days.', 'Sete dias de atraso, antes da carência.'),
         value=300, tolerance=0, unit=('cents', 'centavos')),
    dict(id='ex-1qzjvpgk', section='swapping-behaviour', type='quiz', difficulty='medium',
         prompt=('In test_fines.py the Recording rule answers 999 cents, which no real rule would. What does that number let the test check?',
                 'Em test_fines.py a regra Recording responde 999 centavos, o que nenhuma regra de verdade responderia. O que esse número deixa o teste verificar?'),
         choices=[
             (False, ('That the loan rejects implausible fines from its policy', 'Que o empréstimo rejeita multas implausíveis da regra'),
              ('The loan rejects nothing; the test asserts that 999 comes straight back.',
               'O empréstimo não rejeita nada; o teste afirma que 999 volta direto.')),
             (True, ('That the loan returns its policy\'s answer instead of computing its own', 'Que o empréstimo devolve a resposta da regra em vez de calcular a sua'),
              ('Right. A value no real computation produces can only have come from the double.',
               'Isso. Um valor que nenhum cálculo real produz só pode ter vindo do dublê.')),
             (False, ('That fines above 900 cents trigger the library\'s maximum', 'Que multas acima de 900 centavos acionam o teto da biblioteca'),
              ('No maximum exists in fines.py; the number was chosen for being impossible, not meaningful.',
               'Não existe teto em fines.py; o número foi escolhido por ser impossível, não por significar algo.')),
             (False, ('That unittest can compare integers of three digits', 'Que o unittest consegue comparar inteiros de três dígitos'),
              ('assertEqual compares any integers; the size of this one is about telling sources apart.',
               'assertEqual compara quaisquer inteiros; o tamanho deste serve para distinguir de onde veio.')),
         ]),
    # ---- when-inheritance-fits
    dict(id='ex-c00set4x', section='when-inheritance-fits', type='multiple-choice', difficulty='medium',
         prompt=('Which of these are inheritance in the places the lesson says it fits? Choose every one that applies.',
                 'Quais destes são herança nos lugares em que a lição diz que ela serve? Escolha todos os que se aplicam.'),
         choices=[
             (True, ('class ReservationExpired(LibraryError)', 'class ReservationExpired(LibraryError)'),
              ('Yes. One axis, and anywhere that catches LibraryError should catch this too.',
               'Sim. Um eixo, e qualquer lugar que captura LibraryError deve capturar esta também.')),
             (True, ('class ReadyNotice(Notice), filling in the abstract body', 'class ReadyNotice(Notice), preenchendo o body abstrato'),
              ('Yes. The parent declared the hole and owns the algorithm around it.',
               'Sim. O pai declarou o buraco e é dono do algoritmo em volta dele.')),
             (True, ('class LoanTest(unittest.TestCase)', 'class LoanTest(unittest.TestCase)'),
              ('Yes. A framework designed for thousands of children, with documented hooks.',
               'Sim. Um framework projetado para milhares de filhos, com ganchos documentados.')),
             (False, ('class CountingShelf(Shelf), overriding add and add_all', 'class CountingShelf(Shelf), sobrescrevendo add e add_all'),
              ('Shelf was not written to be extended and never documented its self-calls; that is the fragile base class.',
               'Shelf não foi escrito para ser estendido e nunca documentou suas chamadas a self; essa é a classe base frágil.')),
             (False, ('class StudentFilmLoan(FilmLoan), overriding fine', 'class StudentFilmLoan(FilmLoan), sobrescrevendo fine'),
              ('Two axes vary there, which is why its fine had to be copied from StudentLoan.',
               'Ali variam dois eixos, e é por isso que o fine dela teve de ser copiado de StudentLoan.')),
         ]),
    dict(id='ex-wr9g4033', section='when-inheritance-fits', type='quiz', difficulty='medium',
         prompt=('Notice.render calls self.body, and Shelf.add_all called self.add. Why is the first safe for children and the second was not?',
                 'Notice.render chama self.body, e Shelf.add_all chamava self.add. Por que a primeira é segura para os filhos e a segunda não era?'),
         choices=[
             (False, ('Because body returns a string and add returns nothing', 'Porque body devolve um texto e add não devolve nada'),
              ('The return type has nothing to do with it; a hidden self-call is fragile whatever it returns.',
               'O tipo de retorno não tem nada a ver; uma chamada a self escondida é frágil seja o que for que devolva.')),
             (False, ('Because an ABC can only ever have one child class', 'Porque uma ABC só pode ter uma classe filha'),
              ('Notice has two children in fits.py, and an ABC can have any number.',
               'Notice tem dois filhos em fits.py, e uma ABC pode ter quantos quiser.')),
             (True, ('That self-call is the declared and enforced contract', 'Essa chamada a self é o contrato declarado e cobrado'),
              ('Right. A self-call is dangerous when it is an accident of implementation and safe when it is documented.',
               'Isso. Uma chamada a self é perigosa quando é acidente de implementação e segura quando é documentada.')),
         ]),
    dict(id='ex-qravgbj6', section='when-inheritance-fits', type='matching', difficulty='medium',
         prompt=('Match each language to how a class is kept from being subclassed.',
                 'Associe cada linguagem ao jeito de impedir que uma classe ganhe subclasses.'),
         pairs=[
             (('Java', 'Java'), ('final on the class, refused by the compiler', 'final na classe, recusado pelo compilador')),
             (('Kotlin', 'Kotlin'), ('closed by default unless marked open', 'fechada por padrão a menos que marcada open')),
             (('Python', 'Python'), ('typing.final, enforced by a type checker only', 'typing.final, cobrado só por um verificador de tipos')),
             (('TypeScript', 'TypeScript'), ('no way to forbid it', 'não há como proibir')),
         ]),
    # ---- mixins
    dict(id='ex-k8tyzhz4', section='mixins', type='quiz', difficulty='medium',
         prompt=('Book and Film in mixins.py inherit the same four mixins, yet one prints a shelf label and the other a barcode. Why?',
                 'Book e Film em mixins.py herdam os mesmos quatro mixins, e ainda assim um imprime a etiqueta de estante e o outro o código de barras. Por quê?'),
         choices=[
             (True, ('Their parents are listed in a different order, and Python runs the first label in the method resolution order',
                     'Os pais estão listados em ordem diferente, e o Python roda o primeiro label na ordem de resolução de métodos'),
              ('Right. Swapping two names in the parentheses changed what the class does, and nothing warned.',
               'Isso. Trocar dois nomes de lugar entre os parênteses mudou o que a classe faz, e nada avisou.')),
             (False, ('Film overrides label itself', 'Film sobrescreve label ele mesmo'),
              ('Film defines only __init__; both labels come from mixins.', 'Film só define __init__; os dois labels vêm de mixins.')),
             (False, ('Python picks the mixin whose label uses fields the object has', 'O Python escolhe o mixin cujo label usa campos que o objeto tem'),
              ('Python never looks inside a method to choose it; both objects have title, shelf and code anyway.',
               'O Python nunca olha dentro de um método para escolhê-lo; e os dois objetos têm title, shelf e code.')),
         ]),
    dict(id='ex-fceq48ky', section='mixins', type='quiz', difficulty='medium',
         prompt=("Member(JsonMixin) fails with 'Member' object has no attribute 'as_dict'. What does that error show about the mixins?",
                 "Member(JsonMixin) falha com 'Member' object has no attribute 'as_dict'. O que esse erro mostra sobre os mixins?"),
         choices=[
             (False, ('That json.dumps cannot serialise objects with a name field', 'Que json.dumps não consegue serializar objetos com um campo name'),
              ('json.dumps was never reached; the call failed one step earlier, looking for as_dict.',
               'json.dumps nem foi alcançado; a chamada falhou um passo antes, procurando as_dict.')),
             (False, ('That a mixin may only be used by a class with an __init__ of its own', 'Que um mixin só pode ser usado por uma classe com __init__ próprio'),
              ('Member has an __init__; what it lacks is a method another mixin was supposed to bring.',
               'Member tem __init__; o que falta é um método que outro mixin deveria trazer.')),
             (True, ('JsonMixin relies on a method that only a different parent provides', 'JsonMixin depende de um método que só outro pai fornece'),
              ('Right. It is the fragile base class between siblings, found only when the method is first called.',
               'Isso. É a classe base frágil entre irmãos, descoberta só quando o método é chamado pela primeira vez.')),
             (False, ('That Member needed to inherit from Book as well', 'Que Member precisava herdar de Book também'),
              ('A member is not a book; what it needed was the as_dict ability, from AsDictMixin.',
               'Um membro não é um livro; o que ele precisava era a capacidade as_dict, de AsDictMixin.')),
         ]),
    dict(id='ex-cm8c8888', section='mixins', type='quiz', difficulty='hard',
         prompt=('In Go, a struct embeds two types that both have a Label method, and code calls s.Label(). What happens?',
                 'Em Go, uma struct embute dois tipos que têm, os dois, um método Label, e o código chama s.Label(). O que acontece?'),
         choices=[
             (False, ('The type embedded first wins, as in Python\'s method resolution order', 'Vence o tipo embutido primeiro, como na ordem de resolução de métodos do Python'),
              ('Go has no resolution order for this case; it refuses to guess.', 'Go não tem ordem de resolução para esse caso; ele se recusa a adivinhar.')),
             (False, ('The type embedded last wins, as with TypeScript mixin functions', 'Vence o tipo embutido por último, como nas funções de mixin do TypeScript'),
              ('That is TypeScript\'s rule; Go treats the clash as an error.', 'Essa é a regra do TypeScript; Go trata o conflito como erro.')),
             (True, ('The compiler refuses the call as an ambiguous selector', 'O compilador recusa a chamada como seletor ambíguo, antes de rodar'),
              ('Right. The clash that Python resolved silently in mixins.py cannot compile in Go.',
               'Isso. O conflito que o Python resolveu em silêncio em mixins.py não compila em Go.')),
             (False, ('The program panics at run time the first time Label is called', 'O programa entra em pânico em tempo de execução na primeira chamada a Label'),
              ('Go catches it earlier, at compile time, when the call is written.', 'Go pega isso antes, na compilação, quando a chamada é escrita.')),
         ]),
    # ---- refactor-to-composition
    dict(id='ex-sdyfe7m6', section='refactor-to-composition', type='ordering', difficulty='medium',
         prompt=('Put the steps of turning the loan hierarchy into composition in the order the section takes them.',
                 'Ponha em ordem os passos para transformar a hierarquia de empréstimos em composição, como a seção os faz.'),
         items=[('Pin the behaviour with tests that go through open_loan', 'Fixar o comportamento com testes que passam por open_loan'),
                ('Name what varies between the subclasses', 'Dar nome ao que varia entre as subclasses'),
                ('Give the parent a field for each varying thing', 'Dar ao pai um campo para cada coisa que varia'),
                ('Make open_loan pass parts instead of picking a class', 'Fazer open_loan passar partes em vez de escolher uma classe'),
                ('Delete the subclasses nothing constructs any more', 'Apagar as subclasses que nada mais constrói')],
         trap=('Deleting the subclasses before the factory stops naming them breaks every caller at once; they go last.',
               'Apagar as subclasses antes de a fábrica parar de citá-las quebra todo mundo de uma vez; elas saem por último.')),
    dict(id='ex-9jbv5fet', section='refactor-to-composition', type='quiz', difficulty='medium',
         prompt=('Why do the tests in test_loans.py go through open_loan instead of constructing StudentLoan and FilmLoan directly?',
                 'Por que os testes de test_loans.py passam por open_loan em vez de construir StudentLoan e FilmLoan diretamente?'),
         choices=[
             (False, ('Because unittest cannot import classes, only functions', 'Porque o unittest não consegue importar classes, só funções'),
              ('unittest imports anything Python can; test_fines.py imports the Loan class.',
               'O unittest importa qualquer coisa que o Python importe; test_fines.py importa a classe Loan.')),
             (True, ('So that they never name the classes the refactoring deletes', 'Para nunca citarem as classes que a refatoração apaga'),
              ('Right. Tests written against the door every caller uses survive a change behind it.',
               'Isso. Testes escritos contra a porta que todo mundo usa sobrevivem a uma mudança atrás dela.')),
             (False, ('Because open_loan is faster than calling a constructor', 'Porque open_loan é mais rápido que chamar um construtor'),
              ('It is slightly slower, if anything; speed was not the reason.', 'Se tanto, é um pouco mais lento; velocidade não foi o motivo.')),
         ]),
    # ---- drill
    dict(id='ex-hgh11k53', section='drill', type='quiz', difficulty='hard',
         prompt=('A teammate wants an AuditedShelf that writes a log line for every title added. Shelf comes from a published package. Which design does this lesson argue for?',
                 'Um colega quer um AuditedShelf que escreva uma linha de log para cada título acrescentado. Shelf vem de um pacote publicado. Que projeto esta lição defende?'),
         choices=[
             (False, ('Subclass Shelf and override only add, since add_all calls it', 'Herdar de Shelf e sobrescrever só add, já que add_all o chama'),
              ('That relies on an undocumented self-call; the second shelf.py removed exactly that and the count went to 1.',
               'Isso depende de uma chamada a self não documentada; o segundo shelf.py removeu exatamente isso e a contagem foi para 1.')),
             (False, ('Hold a Shelf and forward everything with __getattr__, so new methods keep working',
                      'Guardar um Shelf e repassar tudo com __getattr__, para métodos novos continuarem funcionando'),
              ('New methods would keep working and go unlogged, which is the failure the audit exists to prevent.',
               'Métodos novos continuariam funcionando e sem log, que é a falha que a auditoria existe para evitar.')),
             (True, ('Hold a Shelf and write out each method it offers, logging in each one', 'Guardar um Shelf e escrever cada método que oferece, com log em cada um'),
              ('Right. It depends only on what Shelf\'s methods do, and a new method is something the wrapper decides to offer.',
               'Isso. Depende só do que os métodos de Shelf fazem, e um método novo é algo que o invólucro decide oferecer.')),
             (False, ('Copy Shelf\'s source into the project and add the logging to it', 'Copiar o código de Shelf para o projeto e acrescentar o log nele'),
              ('That forks the package: every fix upstream has to be copied by hand from then on.',
               'Isso cria uma cópia divergente do pacote: toda correção feita lá tem de ser copiada à mão dali em diante.')),
         ]),
    dict(id='ex-0r20zbp2', section='drill', type='quiz', difficulty='hard',
         prompt=('The library starts lending e-readers for 21 days, with the student grace days as usual. In the composed loans.py, what has to change?',
                 'A biblioteca começa a emprestar leitores digitais por 21 dias, com a carência de estudante de sempre. No loans.py por composição, o que precisa mudar?'),
         choices=[
             (True, ('open_loan learns one more loan length, and nothing else changes', 'open_loan aprende mais uma duração de empréstimo, e só'),
              ('Right. Length and fine rule are separate parts, so the new item reuses GraceDays unchanged.',
               'Isso. Duração e regra de multa são partes separadas, então o item novo reaproveita GraceDays sem mudança.')),
             (False, ('Two new classes, EReaderLoan and StudentEReaderLoan', 'Duas classes novas, EReaderLoan e StudentEReaderLoan'),
              ('That is what the old hierarchy would have needed; the composed one has no class per kind of loan.',
               'É disso que a hierarquia antiga precisaria; a por composição não tem classe por tipo de empréstimo.')),
             (False, ('A subclass of GraceDays that knows about e-readers', 'Uma subclasse de GraceDays que saiba de leitores digitais'),
              ('The grace rule does not care what was lent; it only sees days late.',
               'A regra de carência não liga para o que foi emprestado; ela só vê dias de atraso.')),
             (False, ('A rewrite of test_loans.py, because every one of its tests names a loan class',
                      'Reescrever test_loans.py, porque cada um dos testes cita uma classe de empréstimo'),
              ('None of them names a class; they all go through open_loan, which is why they survived the refactoring.',
               'Nenhum deles cita uma classe; todos passam por open_loan, e é por isso que sobreviveram à refatoração.')),
         ]),
    dict(id='ex-e1pckp59', section='drill', type='cloze', difficulty='medium',
         prompt=('A correct change inside a parent breaks a subclass that relied on the parent calling its own methods. This is called the fragile ___ class problem.',
                 'Uma mudança correta dentro de um pai quebra uma subclasse que contava com o pai chamando os próprios métodos. Isso se chama problema da classe ___ frágil.'),
         blanks=[dict(en=['base'], pt=['base'])]),
]
