"""Lesson 3: SOLID, single responsibility, open/closed, Liskov substitution."""

EXERCISES = [
    # ---- why-principles
    dict(id='ex-skfzd43x', section='why-principles', type='quiz', difficulty='easy',
         prompt=('What does the lesson say a design principle is?', 'O que a lição diz que um princípio de projeto é?'),
         choices=[
             (False, ('A law: code that breaks it is wrong', 'Uma lei: código que a quebra está errado'),
              ('Treating principles as laws is the misreading the section warns against; it ends in over-built code.',
               'Tratar princípios como leis é a leitura errada contra a qual a seção alerta; termina em código superconstruído.')),
             (True, ('A rule of thumb about where change will hurt', 'Uma regra prática sobre onde a mudança vai doer'),
              ('Right. It is a question to ask when something is hard to change.',
               'Isso. É uma pergunta a fazer quando algo está difícil de mudar.')),
             (False, ('A named solution with a known shape, such as an adapter', 'Uma solução com nome e formato conhecido, como um adapter'),
              ('That is a pattern; a principle is the reason a pattern has its shape.',
               'Isso é um padrão; um princípio é o motivo de um padrão ter o formato que tem.')),
             (False, ('A checklist to run before writing a class', 'Uma lista de verificação para rodar antes de escrever uma classe'),
              ('Before anything exists there is no change to protect against, which is what a principle is for.',
               'Antes de algo existir não há mudança contra a qual proteger, que é para o que um princípio serve.')),
         ]),
    dict(id='ex-ha60d0s5', section='why-principles', type='matching', difficulty='easy',
         prompt=('Match each SOLID principle to the question it asks.', 'Associe cada princípio SOLID à pergunta que ele faz.'),
         pairs=[
             (('single responsibility', 'responsabilidade única'), ('who will ask for this code to change?', 'quem vai pedir que este código mude?')),
             (('open/closed', 'aberto/fechado'), ('can a new case be added without editing working code?', 'dá para acrescentar um caso novo sem editar código que funciona?')),
             (('Liskov substitution', 'substituição de Liskov'), ('can every child be used where its parent is expected?', 'todo filho pode ser usado onde se espera o pai?')),
             (('dependency inversion', 'inversão de dependência'), ('does the policy depend on the detail, or the other way round?', 'a regra depende do detalhe, ou o contrário?')),
         ]),
    dict(id='ex-9dvmxmxp', section='why-principles', type='quiz', difficulty='medium',
         prompt=('What do all five SOLID principles have in common, according to the lesson?',
                 'O que os cinco princípios SOLID têm em comum, segundo a lição?'),
         choices=[
             (False, ('They were all written by Robert C. Martin around 2000', 'Todos foram escritos por Robert C. Martin por volta de 2000'),
              ('Martin collected them; open/closed is Meyer\'s and substitution is Liskov\'s.',
               'Martin os reuniu; aberto/fechado é de Meyer e a substituição é de Liskov.')),
             (True, ('They are all about dependencies', 'Todos tratam de dependências'),
              ('Right. Lesson 2\'s fragile base class and class explosion were the same subject.',
               'Isso. A classe base frágil e a explosão de classes da lição 2 eram o mesmo assunto.')),
             (False, ('They each require an interface for every class', 'Cada um exige uma interface para cada classe'),
              ('That is the over-built reading the section warns about.', 'Essa é a leitura superconstruída contra a qual a seção alerta.')),
         ]),
    # ---- srp
    dict(id='ex-6p19kynk', section='srp', type='quiz', difficulty='medium',
         prompt=('In the single responsibility principle, what counts as a reason to change?',
                 'No princípio da responsabilidade única, o que conta como motivo para mudar?'),
         choices=[
             (False, ('Each method the class has', 'Cada método que a classe tem'),
              ('A class with six methods owned by one actor has one responsibility.',
               'Uma classe com seis métodos de um mesmo ator tem uma responsabilidade.')),
             (True, ('An actor: a person or group who asks for changes', 'Um ator: uma pessoa ou grupo que pede mudanças'),
              ('Right. Martin\'s later wording says a module is responsible to one actor.',
               'Isso. A formulação posterior de Martin diz que um módulo responde a um ator.')),
             (False, ('Each verb in the class\'s description, since a class should do one thing',
                      'Cada verbo na descrição da classe, já que uma classe deve fazer uma coisa só'),
              ('Doing one thing is advice for functions; split classes by verb and you get dozens of one-method classes.',
               'Fazer uma coisa só é conselho para funções; divida classes por verbo e você terá dezenas de classes de um método.')),
             (False, ('A bug report filed against the class', 'Um relato de bug aberto contra a classe'),
              ('Bugs are fixed wherever they are; the principle is about who requests changes in behaviour.',
               'Bugs se corrigem onde estiverem; o princípio é sobre quem pede mudanças de comportamento.')),
         ]),
    dict(id='ex-1px0hfq3', section='srp', type='numeric', difficulty='medium',
         prompt=('With the Sunday-skipping desk.py, a book lent on Monday 2 March 2026 comes back on Saturday 21 March. Two Sundays fall in between. How many cents is the fine?',
                 'Com o desk.py que pula domingos, um livro emprestado na segunda, 2 de março de 2026, volta no sábado, 21 de março. Caem dois domingos no meio. Quantos centavos é a multa?'),
         hint=('19 calendar days, minus the Sundays, minus the 14 free days.', '19 dias de calendário, menos os domingos, menos os 14 dias grátis.'),
         value=150, tolerance=0, unit=('cents', 'centavos')),
    dict(id='ex-51nn4gkm', section='srp', type='quiz', difficulty='hard',
         prompt=('fine_days and calendar_days start out as identical functions. Why does the section keep both?',
                 'fine_days e calendar_days começam como funções idênticas. Por que a seção mantém as duas?'),
         choices=[
             (False, ('Python cannot call one function from two methods of different classes', 'O Python não consegue chamar uma função a partir de métodos de classes diferentes'),
              ('It can; that sharing is exactly what desk.py did.', 'Consegue; esse compartilhamento é exatamente o que desk.py fez.')),
             (False, ('Duplicated code is always better than shared code', 'Código duplicado é sempre melhor que código compartilhado'),
              ('The section defends this particular duplication, not duplication in general.',
               'A seção defende esta duplicação específica, não a duplicação em geral.')),
             (True, ('They answer to different actors', 'Respondem a atores diferentes'),
              ('Right. Alike by accident is not the same thing; sharing them let one team\'s change leak into the other\'s.',
               'Isso. Iguais por acaso não é a mesma coisa; compartilhá-las deixou a mudança de um time vazar para o outro.')),
         ]),
    # ---- srp-in-code
    dict(id='ex-0rqyp4ej', section='srp-in-code', type='matching', difficulty='medium',
         prompt=('Match each piece of report.py to the actor who would ask for it to change.',
                 'Associe cada parte de report.py ao ator que pediria que ela mudasse.'),
         pairs=[
             (('FineCalculator', 'FineCalculator'), ('the fines office', 'o setor de multas')),
             (('TextReport', 'TextReport'), ('the desk coordinator who reads it', 'a coordenadora do balcão, que o lê')),
             (('ConsoleMailer', 'ConsoleMailer'), ('IT', 'a TI')),
         ],
         right_distractors=[('the statistics team', 'o time de estatística')]),
    dict(id='ex-qjktjy8q', section='srp-in-code', type='quiz', difficulty='medium',
         prompt=('Adding csv_report.py did not touch report.py. What does that guarantee?',
                 'Acrescentar csv_report.py não mexeu em report.py. O que isso garante?'),
         choices=[
             (True, ('The fine rules and the mail code cannot have been broken by the change',
                     'Que as regras de multa e o código de e-mail seguem intactos'),
              ('Right. A request from one actor reached only that actor\'s code.',
               'Isso. O pedido de um ator chegou só ao código desse ator.')),
             (False, ('The CSV output is correct, since it reuses tested code', 'A saída em CSV está correta, já que reaproveita código testado'),
              ('The new class itself still needs checking; what is guaranteed is that the old code is unchanged.',
               'A classe nova ainda precisa ser verificada; o que se garante é que o código antigo não mudou.')),
             (False, ('The report will now be sent through a real mail server', 'O relatório agora vai ser enviado por um servidor de e-mail de verdade'),
              ('ConsoleMailer still prints; replacing it is IT\'s change, not this one.',
               'ConsoleMailer continua imprimindo; trocá-lo é mudança da TI, não esta.')),
         ]),
    dict(id='ex-th44cwam', section='srp-in-code', type='quiz', difficulty='hard',
         prompt=('A colleague proposes splitting TextReport further, into one class per column and one for the total line. What does the section say?',
                 'Um colega propõe dividir TextReport mais ainda, numa classe por coluna e uma para a linha de total. O que a seção diz?'),
         choices=[
             (False, ('Do it: smaller classes are always closer to the principle', 'Faça: classes menores sempre estão mais perto do princípio'),
              ('Size is not the measure; the section warns against splitting by size.',
               'Tamanho não é a medida; a seção alerta contra dividir por tamanho.')),
             (True, ('Don\'t: they would answer to the same coordinator', 'Não faça: responderiam à mesma coordenadora'),
              ('Right. Code that changes together for one actor belongs together.',
               'Isso. Código que muda junto para um ator fica junto.')),
             (False, ('Do it, but only in Java or Go, where each class needs its own file', 'Faça, mas só em Java ou Go, onde cada classe precisa de um arquivo'),
              ('Files are not the point; the principle cares about which code changes together.',
               'Arquivos não são a questão; o princípio liga para que código muda junto.')),
             (False, ('Don\'t: the principle only applies to classes over a hundred lines long', 'Não faça: o princípio só vale para classes com mais de cem linhas'),
              ('ReportService had under twenty lines and three actors; length is not the test.',
               'ReportService tinha menos de vinte linhas e três atores; tamanho não é o teste.')),
         ]),
    # ---- ocp
    dict(id='ex-fg8j796d', section='ocp', type='quiz', difficulty='easy',
         prompt=('by_kind.py printed child: None cents. Why None?', 'by_kind.py imprimiu child: None cents. Por que None?'),
         choices=[
             (False, ('The child membership charges nothing by law', 'A categoria infantil não cobra nada por lei'),
              ('Nothing in the program says so; no rule for children existed at all.',
               'Nada no programa diz isso; não existia regra nenhuma para crianças.')),
             (True, ('The chain had no branch for it, so the function ended', 'A cadeia não tinha ramo para ela, e a função chegou ao fim'),
              ('Right. A Python function that reaches its last line returns None.',
               'Isso. Uma função Python que chega à última linha devolve None.')),
             (False, ('days_late was 40, and Python returns None for numbers over 30', 'days_late era 40, e o Python devolve None para números acima de 30'),
              ('The adult line in the same run handled 40 days without trouble.',
               'A linha de adulto da mesma execução lidou com 40 dias sem problema.')),
         ]),
    dict(id='ex-2nfsre14', section='ocp', type='quiz', difficulty='medium',
         prompt=('How does Martin\'s statement of the open/closed principle differ from Meyer\'s of 1988?',
                 'Em que a formulação de Martin do princípio aberto/fechado difere da de Meyer, de 1988?'),
         choices=[
             (False, ('Martin forbids editing any file once it is committed', 'Martin proíbe editar qualquer arquivo depois do commit'),
              ('Nobody means that; bugs are fixed by editing in either version.',
               'Ninguém quer dizer isso; bugs se corrigem editando nas duas versões.')),
             (False, ('Meyer extends through an abstraction; Martin through subclasses', 'Meyer estende por uma abstração; Martin por subclasses'),
              ('It is the other way round: Meyer had inheritance in mind.', 'É o contrário: Meyer pensava em herança.')),
             (True, ("Martin's opening is an abstraction; Meyer's was subclassing", 'A abertura de Martin é uma abstração; a de Meyer, subclasses'),
              ('Right. The closed code then knows the protocol and never the new case\'s name.',
               'Isso. O código fechado então conhece o protocolo e nunca o nome do caso novo.')),
             (False, ('They are the same principle with a different name', 'São o mesmo princípio com outro nome'),
              ('The name is the same; where the opening goes is what changed.', 'O nome é o mesmo; o que mudou foi onde fica a abertura.')),
         ]),
    dict(id='ex-ma5ba2vx', section='ocp', type='quiz', difficulty='hard',
         prompt=('A function has one if/elif on the kind of member, and no other function asks that question. A new kind arrives. What does the section suggest?',
                 'Uma função tem um if/elif sobre o tipo de membro, e nenhuma outra função faz essa pergunta. Chega um tipo novo. O que a seção sugere?'),
         choices=[
             (True, ('Add the elif for now; the axis has not shown itself yet', 'Acrescentar o elif por enquanto; o eixo ainda não se mostrou'),
              ('Right. The opening goes in once the chain repeats or each new kind means a hunt.',
               'Isso. A abertura entra quando a cadeia se repete ou cada tipo novo vira uma caçada.')),
             (False, ('Introduce a protocol at once, since every if chain breaks the principle',
                      'Introduzir um protocolo de imediato, já que toda cadeia de if quebra o princípio'),
              ('Opening code along every axis puts an indirection on every line; the section says to wait for the axis.',
               'Abrir o código em todos os eixos põe uma indireção em cada linha; a seção diz para esperar o eixo.')),
             (False, ('Subclass the function\'s module for the new kind', 'Criar uma subclasse do módulo da função para o tipo novo'),
              ('Modules are not subclassed, and inheritance as extension is the version lesson 2 measured.',
               'Módulos não ganham subclasses, e herança como extensão é a versão que a lição 2 mediu.')),
         ]),
    # ---- ocp-in-code
    dict(id='ex-f0dgtq5p', section='ocp-in-code', type='multiple-choice', difficulty='medium',
         prompt=('Which files changed when the capped child rule was added? Choose every one that applies.',
                 'Que arquivos mudaram quando a regra com teto para crianças entrou? Escolha todos os que se aplicam.'),
         choices=[
             (True, ('capped.py, which is new', 'capped.py, que é novo'), ('Yes. The new rule lives there.', 'Sim. A regra nova mora ali.')),
             (True, ('main.py, the wiring', 'main.py, as ligações'), ('Yes. Something has to say the new case exists: one import, one entry, one loan.',
                                                                     'Sim. Algo tem de dizer que o caso novo existe: um import, uma entrada, um empréstimo.')),
             (False, ('charges.py', 'charges.py'), ('No. It depends on the protocol and never learnt the new rule\'s name.',
                                                    'Não. Depende do protocolo e nunca aprendeu o nome da regra nova.')),
             (False, ('policies.py', 'policies.py'), ('No. Capped was written in its own file, importing only the protocol.',
                                                      'Não. Capped foi escrito no próprio arquivo, importando só o protocolo.')),
         ]),
    dict(id='ex-aq6c44sr', section='ocp-in-code', type='numeric', difficulty='medium',
         prompt=('A child returns a book 15 days late under Capped(1000, PerDay(50)). What is the fine, in cents?',
                 'Uma criança devolve um livro com 15 dias de atraso sob Capped(1000, PerDay(50)). Qual é a multa, em centavos?'),
         value=750, tolerance=0, unit=('cents', 'centavos')),
    dict(id='ex-8tkx2mzf', section='ocp-in-code', type='quiz', difficulty='medium',
         prompt=('A loan arrives with the kind "staff", which has no entry in rules. What does charge_sheet do?',
                 'Chega um empréstimo da categoria "staff", que não tem entrada em rules. O que charge_sheet faz?'),
         choices=[
             (False, ('Prints None cents, like by_kind.py', 'Imprime None cents, como by_kind.py'),
              ('That was the if chain falling off its end; a dictionary lookup does not fall through.',
               'Isso era a cadeia de if chegando ao fim; uma consulta a dicionário não passa direto.')),
             (True, ('Raises KeyError at the lookup', 'Levanta KeyError na consulta'),
              ('Right. A missing rule fails loudly at the line that is wrong.', 'Isso. Uma regra que falta falha em voz alta na linha errada.')),
             (False, ('Charges the adult rate, the first entry in the table', 'Cobra a tarifa de adulto, a primeira entrada da tabela'),
              ('Nothing in the function falls back to a default; it asks for exactly the kind it was given.',
               'Nada na função recorre a um padrão; ela pede exatamente a categoria que recebeu.')),
         ]),
    # ---- lsp
    dict(id='ex-bsjes9vk', section='lsp', type='quiz', difficulty='medium',
         prompt=('ReferenceBook.lend has the same name, argument and return type as Item.lend. Why does it still break the principle?',
                 'ReferenceBook.lend tem o mesmo nome, argumento e tipo de retorno que Item.lend. Por que ainda quebra o princípio?'),
         choices=[
             (False, ('Because it raises an exception, and a child must never raise one', 'Porque levanta uma exceção, e um filho nunca deve levantar uma'),
              ('A child may raise what the parent\'s contract allows; this one refuses input the parent accepted.',
               'Um filho pode levantar o que o contrato do pai permite; este recusa uma entrada que o pai aceitava.')),
             (True, ('Callers rely on behaviour, and it refuses a day the parent accepts',
                     'Quem chama confia no comportamento, e ele recusa um dia aceito pelo pai'),
              ('Right. A strengthened precondition; matching signatures do not make a substitute.',
               'Isso. Uma pré-condição fortalecida; assinaturas iguais não fazem um substituto.')),
             (False, ('Because Python checks behaviour at import time and finds a difference', 'Porque o Python verifica comportamento na importação e acha uma diferença'),
              ('Python checks nothing; the failure appeared only when check_out called it.',
               'O Python não verifica nada; a falha só apareceu quando check_out o chamou.')),
         ]),
    dict(id='ex-96mm0xp9', section='lsp', type='quiz', difficulty='hard',
         prompt=('Which change to a child of Item would still keep the substitution principle?',
                 'Qual mudança num filho de Item ainda respeitaria o princípio da substituição?'),
         choices=[
             (False, ('lend refuses any date that falls on a Sunday', 'lend recusa qualquer data que caia num domingo'),
              ('That accepts less than the parent, a strengthened precondition.', 'Isso aceita menos que o pai, uma pré-condição fortalecida.')),
             (False, ('lend returns None when the item is out of stock', 'lend devolve None quando o item está esgotado'),
              ('That promises less than a later date, a weakened postcondition.', 'Isso promete menos que uma data posterior, uma pós-condição enfraquecida.')),
             (True, ('The due date it returns is never a Sunday', 'O vencimento devolvido nunca é um domingo'),
              ('Right. Promising more than the parent is allowed; every caller\'s expectation still holds.',
               'Isso. Prometer mais que o pai é permitido; a expectativa de todo mundo que chama continua valendo.')),
             (False, ('lend changes the title of the item it lends', 'lend muda o título do item que empresta'),
              ('Callers expect the title to stay put; that breaks an invariant they rely on.',
               'Quem chama espera que o título fique igual; isso quebra uma invariante em que confiam.')),
         ]),
    dict(id='ex-zfbzwdv3', section='lsp', type='cloze', difficulty='easy',
         prompt=('A child may not strengthen the parent\'s preconditions, and it may not weaken the parent\'s ___ .',
                 'Um filho não pode fortalecer as pré-condições do pai, nem enfraquecer as ___ do pai.'),
         blanks=[dict(en=['postconditions', 'postcondition', 'post-conditions'],
                      pt=['pós-condições', 'pos-condicoes', 'pós-condição', 'postconditions'])]),
    # ---- lsp-violations
    dict(id='ex-bhrvmv52', section='lsp-violations', type='quiz', difficulty='medium',
         prompt=('Square(3) handed to widen came out with height 10. Which promise did Square break?',
                 'Square(3) entregue a widen saiu com altura 10. Que promessa Square quebrou?'),
         choices=[
             (True, ('Its width and its height move independently of each other', 'A largura e a altura mudam de forma independente uma da outra'),
              ('Right. To keep its own invariant the square had to break its parent\'s.',
               'Isso. Para manter a própria invariante, o quadrado teve de quebrar a do pai.')),
             (False, ('A rectangle\'s area is always width times height', 'A área de um retângulo é sempre largura vezes altura'),
              ('100 is 10 × 10; the area was computed correctly from the sides it had.',
               '100 é 10 × 10; a área foi calculada corretamente com os lados que ele tinha.')),
             (False, ('A rectangle cannot be created with equal sides', 'Um retângulo não pode ser criado com lados iguais'),
              ('Nothing forbids that; Rectangle(3, 3) is fine.', 'Nada proíbe isso; Rectangle(3, 3) funciona.')),
         ]),
    dict(id='ex-wqbw2adp', section='lsp-violations', type='ordering', difficulty='medium',
         prompt=('Put the steps of writing a contract test for Item in order.', 'Ponha em ordem os passos para escrever um teste de contrato para Item.'),
         items=[('Write down what Item.lend accepts and promises', 'Escrever o que Item.lend aceita e promete'),
                ('Turn the promise into an assertion against one object', 'Transformar a promessa numa asserção contra um objeto'),
                ('Loop over every class that claims to be an Item, in a subTest', 'Percorrer cada classe que diz ser um Item, num subTest'),
                ('Add each new child\'s name to the tuple the day it is written', 'Acrescentar o nome de cada filho novo à tupla no dia em que é escrito')],
         trap=('The promise has to be stated before it can be tested; the children come after it, not before.',
               'A promessa tem de ser enunciada antes de poder ser testada; os filhos vêm depois dela, não antes.')),
    # ---- drill
    dict(id='ex-4h50d2es', section='drill', type='quiz', difficulty='hard',
         prompt=('A MemberService registers members, prints their library cards and computes their reading statistics for the acquisitions team. Which principle does it strain, and how?',
                 'Um MemberService cadastra membros, imprime as carteirinhas e calcula estatísticas de leitura para o time de aquisições. Que princípio ele força, e como?'),
         choices=[
             (False, ('Liskov substitution: a service cannot have three methods', 'Substituição de Liskov: um serviço não pode ter três métodos'),
              ('Substitution is about children and parents; there is no hierarchy here.',
               'A substituição trata de filhos e pais; aqui não há hierarquia.')),
             (True, ('Single responsibility: three different actors ask it for changes', 'Responsabilidade única: três atores diferentes pedem mudanças nele'),
              ('Right. Count the actors, not the methods: three actors, three reasons to change.',
               'Isso. Conte os atores, não os métodos: três atores, três motivos para mudar.')),
             (False, ('Open/closed: registering a member edits the database', 'Aberto/fechado: cadastrar um membro edita o banco de dados'),
              ('Writing data is not modifying code; the principle is about editing source for a new case.',
               'Gravar dados não é modificar código; o princípio é sobre editar o código-fonte para um caso novo.')),
         ]),
    dict(id='ex-jp7df2cm', section='drill', type='quiz', difficulty='hard',
         prompt=('A team fixes a Liskov violation by adding if isinstance(item, ReferenceBook) to check_out. What does the lesson say about that fix?',
                 'Um time conserta uma violação de Liskov acrescentando if isinstance(item, ReferenceBook) em check_out. O que a lição diz desse conserto?'),
         choices=[
             (False, ('It is the standard repair, since the caller knows its own needs best', 'É o conserto padrão, já que quem chama conhece melhor o que precisa'),
              ('The caller was correct; the lie is in the class that claims to be an Item.',
               'Quem chama estava certo; a mentira está na classe que diz ser um Item.')),
             (False, ('It is fine as long as a contract test also covers check_out', 'Tudo bem, desde que um teste de contrato cubra check_out'),
              ('A contract test covers the children, and would still fail for ReferenceBook.',
               'Um teste de contrato cobre os filhos, e continuaria falhando para ReferenceBook.')),
             (True, ('It treats the symptom and reopens the lending function for each new child',
                     'Trata o sintoma e reabre a função de empréstimo a cada filho novo'),
              ('Right. Every lending function needs the check, and each new refusing child needs another branch.',
               'Isso. Toda função que empresta precisa do teste, e cada filho novo que recusa precisa de outro ramo.')),
             (False, ('It is needed because Python has no interfaces', 'É necessário porque o Python não tem interfaces'),
              ('Java callers would need the same check; the problem is the hierarchy, in any language.',
               'Quem chama em Java precisaria do mesmo teste; o problema é a hierarquia, em qualquer linguagem.')),
         ]),
    dict(id='ex-p65ghf1m', section='drill', type='quiz', difficulty='hard',
         prompt=('Same-day laptop loans turn out to be a permanent part of the library. What is the right response to the failing contract test?',
                 'Os empréstimos de notebook no mesmo dia viram parte permanente da biblioteca. Qual é a resposta certa para o teste de contrato falhando?'),
         choices=[
             (False, ('Delete Laptop from the tuple so that the contract test passes again', 'Tirar Laptop da tupla para o teste de contrato voltar a passar'),
              ('That hides the violation; callers still trust a later due date.', 'Isso esconde a violação; quem chama continua confiando num vencimento posterior.')),
             (True, ('Change Item\'s promise to "not earlier", then reread every caller of lend', 'Mudar a promessa de Item para "não anterior" e reler quem chama lend'),
              ('Right. The parent\'s contract is a decision too; it may be weakened on purpose, never quietly by a child.',
               'Isso. O contrato do pai também é uma decisão; pode ser enfraquecido de propósito, nunca em silêncio por um filho.')),
             (False, ('Give Laptop a loan_days of 1 and let it come back a day late', 'Dar a Laptop um loan_days de 1 e deixá-lo voltar um dia atrasado'),
              ('That makes the test pass by recording a due date that is false: laptops are due the same day.',
               'Isso faz o teste passar registrando um vencimento falso: os notebooks vencem no mesmo dia.')),
         ]),
]
