"""Lesson 4: SOLID, interface segregation and dependency inversion."""

EXERCISES = [
    # ---- isp
    dict(id='ex-q1jj3th6', section='isp', type='quiz', difficulty='easy',
         prompt=('What does the interface segregation principle say?', 'O que diz o princípio da segregação de interfaces?'),
         choices=[
             (False, ('Every interface must have exactly one method', 'Toda interface deve ter exatamente um método'),
              ('Size is not the measure; five methods every client calls is well segregated.',
               'Tamanho não é a medida; cinco métodos que todo cliente chama estão bem segregados.')),
             (True, ('No client should depend on methods it does not use', 'Nenhum cliente deve depender de métodos que não usa'),
              ('Right. The question is who uses an interface, asked per kind of client.',
               'Isso. A pergunta é quem usa uma interface, feita para cada tipo de cliente.')),
             (False, ('A class should implement at most one interface so its purpose stays clear',
                      'Uma classe deve implementar no máximo uma interface para seu propósito ficar claro'),
              ('The Library class plays three roles at once, and that is the point of role interfaces.',
               'A classe Library faz três papéis ao mesmo tempo, e esse é o objetivo das interfaces de papel.')),
         ]),
    dict(id='ex-bf2sjck0', section='isp', type='numeric', difficulty='easy',
         prompt=('The OneTitle stand-in implemented search and Python refused to create it. How many abstract methods did the error message name?',
                 'O substituto OneTitle implementou search e o Python se recusou a criá-lo. Quantos métodos abstratos a mensagem de erro citou?'),
         value=5, tolerance=0, unit=('methods', 'métodos')),
    dict(id='ex-0te6e0js', section='isp', type='quiz', difficulty='medium',
         prompt=('In production the kiosk works fine with the fat Catalogue. Where does the cost of the fat interface show first?',
                 'Em produção o quiosque funciona bem com o Catalogue gordo. Onde o custo da interface gorda aparece primeiro?'),
         choices=[
             (False, ('In slower searches, since six methods are loaded', 'Em buscas mais lentas, já que seis métodos são carregados'),
              ('Unused methods cost nothing at run time; the cost is in what has to be written and changed.',
               'Métodos não usados não custam nada em execução; o custo está no que precisa ser escrito e mudado.')),
             (True, ('In a test double for the kiosk', 'Num dublê de teste para o quiosque'),
              ('Right. And every later change to those methods means editing that double too.',
               'Isso. E toda mudança posterior nesses métodos significa editar esse dublê também.')),
             (False, ('In the kiosk\'s output', 'Na saída do quiosque'),
              ('The output is correct; nothing the kiosk prints depends on the other methods.',
               'A saída está correta; nada que o quiosque imprime depende dos outros métodos.')),
             (False, ('In the database, which needs one table per interface method', 'No banco de dados, que precisa de uma tabela por método da interface'),
              ('No database is involved; interfaces say nothing about storage.', 'Não há banco envolvido; interfaces não dizem nada sobre armazenamento.')),
         ]),
    # ---- fat-interfaces
    dict(id='ex-emsw8x3w', section='fat-interfaces', type='quiz', difficulty='medium',
         prompt=('How does the lesson fix ReferenceBook without any class refusing anything?',
                 'Como a lição conserta ReferenceBook sem nenhuma classe recusar nada?'),
         choices=[
             (True, ('Lending becomes a separate Lendable protocol that only some items satisfy',
                     'O empréstimo vira um protocolo Lendable separado, que só alguns itens satisfazem'),
              ('Right. The reference book stops claiming a capability it does not have.',
               'Isso. O livro de referência para de afirmar uma capacidade que não tem.')),
             (False, ('ReferenceBook.lend returns None instead of raising', 'ReferenceBook.lend devolve None em vez de levantar exceção'),
              ('That weakens the postcondition; it is lesson 3\'s Laptop problem in another form.',
               'Isso enfraquece a pós-condição; é o problema do Laptop da lição 3 de outra forma.')),
             (False, ('check_out skips reference books with an isinstance test', 'check_out pula livros de referência com um teste isinstance'),
              ('That puts the fix in every caller, the symptom lesson 3 warned about.',
               'Isso põe o conserto em cada código que chama, o sintoma contra o qual a lição 3 alertou.')),
         ]),
    dict(id='ex-7b2e73s6', section='fat-interfaces', type='matching', difficulty='medium',
         prompt=('Match each symptom of a fat interface to where the course showed it.',
                 'Associe cada sintoma de uma interface gorda a onde o curso o mostrou.'),
         pairs=[
             (('an implementer refuses a method', 'um implementador recusa um método'), ('ReferenceBook.lend', 'ReferenceBook.lend')),
             (('a test double stubs methods the test never touches', 'um dublê simula métodos que o teste nunca toca'), ('OneTitle', 'OneTitle')),
             (('a change to one method rebuilds unrelated clients', 'uma mudança num método recompila clientes sem relação'),
              ('the printer at Xerox', 'a impressora da Xerox')),
         ],
         right_distractors=[('the square and the rectangle', 'o quadrado e o retângulo')]),
    dict(id='ex-byrye5yp', section='fat-interfaces', type='quiz', difficulty='hard',
         prompt=('A team has a class with fifteen methods and needs an interface for testing. They lift all fifteen into it. What does the section predict?',
                 'Um time tem uma classe com quinze métodos e precisa de uma interface para testes. Levanta os quinze nela. O que a seção prevê?'),
         choices=[
             (False, ('Nothing bad: the interface matches the class exactly, so it is always correct',
                      'Nada de ruim: a interface bate exatamente com a classe, então está sempre correta'),
              ('Matching the class is the problem: it describes the implementer, not what any client needs.',
               'Bater com a classe é o problema: descreve o implementador, não o que algum cliente precisa.')),
             (True, ('Every client inherits the class\'s whole surface', 'Todo cliente herda a superfície inteira da classe'),
              ('Right. The interface was shaped by the implementer; asking each client what it calls gives the better names.',
               'Isso. A interface ganhou o formato do implementador; perguntar a cada cliente o que ele chama dá os nomes melhores.')),
             (False, ('Python will refuse an interface with more than ten methods', 'O Python vai recusar uma interface com mais de dez métodos'),
              ('Python sets no such limit; the cost is in dependencies, not in a rule of the language.',
               'O Python não tem esse limite; o custo está nas dependências, não numa regra da linguagem.')),
             (False, ('The class will have to be split into fifteen classes', 'A classe vai ter de ser dividida em quinze classes'),
              ('Segregating interfaces splits declarations; the class can stay whole.',
               'Segregar interfaces divide declarações; a classe pode continuar inteira.')),
         ]),
    # ---- roles-as-protocols
    dict(id='ex-1qqf89cr', section='roles-as-protocols', type='quiz', difficulty='medium',
         prompt=('In roles.py, Library plays three roles but names none of the protocols. Why does that work?',
                 'Em roles.py, Library faz três papéis mas não cita nenhum dos protocolos. Por que isso funciona?'),
         choices=[
             (False, ('Because Protocol classes register every class automatically', 'Porque classes Protocol registram toda classe automaticamente'),
              ('Nothing is registered; a protocol describes a shape and checks nothing at run time.',
               'Nada é registrado; um protocolo descreve um formato e não verifica nada em execução.')),
             (False, ('Because Library inherits from all three through object', 'Porque Library herda dos três por meio de object'),
              ('object is the parent of every class and knows nothing of these protocols.',
               'object é o pai de toda classe e não sabe nada desses protocolos.')),
             (True, ('Python matches by shape: having the methods is enough', 'O Python compara pelo formato: ter os métodos basta'),
              ('Right. Java is the exception, where the class must say implements for each role.',
               'Isso. Java é a exceção, onde a classe precisa dizer implements para cada papel.')),
         ]),
    dict(id='ex-q9pqt34h', section='roles-as-protocols', type='quiz', difficulty='hard',
         prompt=('The desk starts taking books back as well as lending them. Where does give_back go?',
                 'O balcão passa a receber livros de volta além de emprestá-los. Onde entra give_back?'),
         choices=[
             (True, ('Into Lending, since the same client calls both and they change together',
                     'Em Lending, já que o mesmo cliente chama os dois e eles mudam juntos'),
              ('Right. A role is the set of methods one kind of client uses, whatever its size.',
               'Isso. Um papel é o conjunto de métodos que um tipo de cliente usa, seja qual for o tamanho.')),
             (False, ('Into a new GivingBack protocol, since a role must have one method', 'Num protocolo novo GivingBack, já que um papel deve ter um método'),
              ('Two names for one client\'s needs buy nothing; one method per role is not the rule.',
               'Dois nomes para as necessidades de um cliente não compram nada; um método por papel não é a regra.')),
             (False, ('Into Searching, the kiosk\'s role', 'Em Searching, o papel do quiosque'),
              ('The kiosk never takes books back; putting it there would fatten the kiosk\'s interface.',
               'O quiosque nunca recebe livros; pô-lo ali engordaria a interface do quiosque.')),
             (False, ('Nowhere: give_back stays outside every protocol', 'Em lugar nenhum: give_back fica fora de todo protocolo'),
              ('Then the desk could not ask for it through its role.', 'Aí o balcão não poderia pedi-lo pelo seu papel.')),
         ]),
    dict(id='ex-v8pa1t3w', section='roles-as-protocols', type='cloze', difficulty='medium',
         prompt=('In Go, small interfaces such as io.Reader are usually declared in the package of the ___ that uses them, not beside the type that implements them.',
                 'Em Go, interfaces pequenas como io.Reader costumam ser declaradas no pacote do ___ que as usa, e não ao lado do tipo que as implementa.'),
         blanks=[dict(en=['client', 'consumer', 'caller'], pt=['cliente', 'consumidor', 'client'])]),
    # ---- dip
    dict(id='ex-5jvammkd', section='dip', type='quiz', difficulty='medium',
         prompt=('What, according to the section, decides whether dependencies have been inverted?',
                 'O que, segundo a seção, decide se as dependências foram invertidas?'),
         choices=[
             (False, ('Whether objects are passed in rather than built inside', 'Se os objetos são passados em vez de construídos dentro'),
              ('That is dependency injection; you can inject a concrete mail class and invert nothing.',
               'Isso é injeção de dependência; dá para injetar uma classe de e-mail concreta e não inverter nada.')),
             (True, ('Who owns the abstraction, and which way the imports point',
                     'Quem é dono da abstração, e para que lado vão os imports'),
              ('Right. The rules own the port, and the detail imports it.', 'Isso. As regras são donas da porta, e o detalhe a importa.')),
             (False, ('Whether there is an interface anywhere between the two classes', 'Se existe uma interface em algum lugar entre as duas classes'),
              ('An interface beside the mail code, mirroring its methods, still leaves the rules depending on the mail package.',
               'Uma interface ao lado do código de e-mail, espelhando seus métodos, ainda deixa as regras dependendo do pacote de e-mail.')),
         ]),
    dict(id='ex-fwtpt37p', section='dip', type='quiz', difficulty='hard',
         prompt=('A team adds IMailer with send_mail(address, subject, body), in the mail package, and has the rules use it. Why is the inversion still missing?',
                 'Um time cria IMailer com send_mail(address, subject, body), no pacote de e-mail, e faz as regras usarem. Por que a inversão ainda falta?'),
         choices=[
             (False, ('The name starts with I, which Python does not allow for classes', 'O nome começa com I, o que o Python não permite em classes'),
              ('Python forbids no names; the problem is whose words the abstraction uses and where it lives.',
               'O Python não proíbe nome nenhum; o problema é de quem são as palavras da abstração e onde ela mora.')),
             (False, ('It has three parameters, and a port must have exactly one', 'Tem três parâmetros, e uma porta deve ter exatamente um'),
              ('The parameter count is not the issue; notify itself has two.', 'O número de parâmetros não é a questão; o próprio notify tem dois.')),
             (True, ("It is the detail's vocabulary, in the detail's package", 'É o vocabulário do detalhe, no pacote do detalhe'),
              ('Right. Switching to SMS would still mean changing it; a Notifier in the rules\' module would not.',
               'Isso. Trocar para SMS ainda exigiria mudá-la; um Notifier no módulo das regras não.')),
         ]),
    dict(id='ex-s4cy82rd', section='dip', type='cloze', difficulty='easy',
         prompt=('Dependency inversion: high-level modules should not depend on low-level modules; both should depend on ___ .',
                 'Inversão de dependência: módulos de alto nível não devem depender de módulos de baixo nível; os dois devem depender de ___ .'),
         blanks=[dict(en=['abstractions', 'an abstraction', 'abstraction'], pt=['abstrações', 'abstracoes', 'uma abstração', 'abstração'])]),
    # ---- dip-in-code
    dict(id='ex-vcdts9pt', section='dip-in-code', type='quiz', difficulty='medium',
         prompt=('The grep over the imports showed adapters.py importing from notices.py. What does that line prove?',
                 'O grep nos imports mostrou adapters.py importando de notices.py. O que essa linha prova?'),
         choices=[
             (False, ('That the adapters cannot run without a mail server', 'Que os adaptadores não rodam sem servidor de e-mail'),
              ('They print; the line is about which code knows which.', 'Eles imprimem; a linha trata de que código conhece qual.')),
             (True, ('The detail depends on the policy', 'O detalhe depende da regra'),
              ('Right. That is the inversion, read off the file rather than a diagram.',
               'Isso. Essa é a inversão, lida no arquivo e não num diagrama.')),
             (False, ('That notices.py imports the adapters indirectly through main.py', 'Que notices.py importa os adaptadores indiretamente por main.py'),
              ('notices.py imports only standard modules; main.py imports both, which is its job.',
               'notices.py importa só módulos padrão; main.py importa os dois, que é o trabalho dele.')),
             (False, ('That Python requires a Protocol to be imported before it is used', 'Que o Python exige importar um Protocol antes de usá-lo'),
              ('The adapters would fit by shape without the import; naming it makes the direction visible.',
               'Os adaptadores se encaixariam pelo formato sem o import; citá-lo deixa a direção visível.')),
         ]),
    dict(id='ex-3xsmh3yx', section='dip-in-code', type='numeric', difficulty='medium',
         prompt=('OverdueNotices runs on 1 April 2026. A loan was lent on 9 March 2026. How many cents does its notice say?',
                 'OverdueNotices roda em 1º de abril de 2026. Um empréstimo saiu em 9 de março de 2026. Quantos centavos diz o aviso?'),
         hint=('It is due 14 days after lending.', 'Ele vence 14 dias depois do empréstimo.'),
         value=450, tolerance=0, unit=('cents', 'centavos')),
    dict(id='ex-6wed48xg', section='dip-in-code', type='multiple-choice', difficulty='medium',
         prompt=('Every notice is to go by SMS from now on. Which files change? Choose every one that applies.',
                 'Todo aviso passa a ir por SMS. Que arquivos mudam? Escolha todos os que se aplicam.'),
         choices=[
             (True, ('main.py', 'main.py'), ('Yes. Deciding which adapter the rules get is the wiring\'s job.',
                                           'Sim. Decidir que adaptador as regras recebem é trabalho das ligações.')),
             (False, ('notices.py', 'notices.py'), ('No. The rules name only Notifier and never learn which one they were given.',
                                                    'Não. As regras citam só Notifier e nunca sabem qual receberam.')),
             (False, ('test_notices.py', 'test_notices.py'), ('No. The test uses its own Recording double and imports no adapter.',
                                                              'Não. O teste usa o próprio dublê Recording e não importa adaptador nenhum.')),
             (False, ('adapters.py', 'adapters.py'), ('No. SmsNotifier is already there.', 'Não. SmsNotifier já está lá.')),
         ]),
    # ---- ports-and-adapters
    dict(id='ex-w41m2a4s', section='ports-and-adapters', type='matching', difficulty='medium',
         prompt=('Match each piece of the notices program to its place in ports and adapters.',
                 'Associe cada peça do programa de avisos ao seu lugar em portas e adaptadores.'),
         pairs=[
             (('Notifier', 'Notifier'), ('a driven port', 'uma porta conduzida')),
             (('SmsNotifier', 'SmsNotifier'), ('a driven adapter', 'um adaptador conduzido')),
             (('cli.py', 'cli.py'), ('a driving adapter', 'um adaptador que conduz')),
             (('OverdueNotices', 'OverdueNotices'), ('the rules in the middle', 'as regras no meio')),
         ]),
    dict(id='ex-0yk457st', section='ports-and-adapters', type='quiz', difficulty='medium',
         prompt=('What is the one rule the section says the architecture comes down to?',
                 'Qual é a única regra a que, segundo a seção, a arquitetura se resume?'),
         choices=[
             (False, ('The project has folders called domain, ports and adapters', 'O projeto tem pastas chamadas domain, ports e adapters'),
              ('The folders are optional; a project can have them and break the rule.', 'As pastas são opcionais; um projeto pode tê-las e quebrar a regra.')),
             (False, ('Every class is drawn inside a hexagon', 'Toda classe é desenhada dentro de um hexágono'),
              ('The hexagon only leaves room to draw several ports; it means nothing else.',
               'O hexágono só deixa espaço para desenhar várias portas; não significa mais nada.')),
             (True, ('Nothing in the middle imports anything at the edge', 'Nada no meio importa coisa alguma da borda'),
              ('Right. The same rule the grep checked in the previous section.', 'Isso. A mesma regra que o grep verificou na seção anterior.')),
         ]),
    # ---- solid-overdone
    dict(id='ex-hz8wr0yw', section='solid-overdone', type='quiz', difficulty='easy',
         prompt=('Why does the section call every abstraction in overdone.py speculative?',
                 'Por que a seção chama toda abstração de overdone.py de especulativa?'),
         choices=[
             (False, ('Because abstract classes are slower than functions', 'Porque classes abstratas são mais lentas que funções'),
              ('Speed is not the argument; both programs print 250 instantly.', 'Velocidade não é o argumento; os dois programas imprimem 250 na hora.')),
             (True, ('Because each one has exactly one implementation', 'Porque cada uma tem exatamente uma implementação'),
              ('Right. An abstraction with one implementation separates nothing from anything.',
               'Isso. Uma abstração com uma implementação não separa nada de nada.')),
             (False, ('Because Python has no interfaces, so ABCs in Python are always a mistake',
                      'Porque o Python não tem interfaces, então ABCs em Python são sempre um erro'),
              ('Lesson 2 used an ABC well for Notice; the problem is a seam nobody uses.',
               'A lição 2 usou bem uma ABC em Notice; o problema é uma emenda que ninguém usa.')),
         ]),
    dict(id='ex-zcrp5bdw', section='solid-overdone', type='numeric', difficulty='easy',
         prompt=('wc -l counted the two versions of the fine. How many more lines did overdone.py have than plain.py?',
                 'wc -l contou as duas versões da multa. Quantas linhas overdone.py tinha a mais que plain.py?'),
         value=27, tolerance=0, unit=('lines', 'linhas')),
    dict(id='ex-vf890yvx', section='solid-overdone', type='ordering', difficulty='medium',
         prompt=('Put the life of the fine rule in the order the section describes, from today to later.',
                 'Ponha a vida da regra de multa na ordem que a seção descreve, de hoje para depois.'),
         items=[('A plain function with one constant', 'Uma função simples com uma constante'),
                ('Students get grace days: PerDay and GraceDays parts', 'Estudantes ganham carência: as partes PerDay e GraceDays'),
                ('The rules need testing without mail: a Notifier port', 'As regras precisam de teste sem e-mail: uma porta Notifier'),
                ('Each seam named after the change that brought it', 'Cada emenda com o nome da mudança que a trouxe')],
         trap=('The ports come after the change that needs them, never before; starting with the interfaces is overdone.py.',
               'As portas vêm depois da mudança que precisa delas, nunca antes; começar pelas interfaces é o overdone.py.')),
    # ---- drill
    dict(id='ex-pdz8s1vf', section='drill', type='quiz', difficulty='hard',
         prompt=('A ReminderService needs only to look up a member\'s phone. It is given the whole MemberRepository, with eleven methods. Which principle does that strain, and what is the fix?',
                 'Um ReminderService só precisa consultar o telefone de um membro. Recebe o MemberRepository inteiro, com onze métodos. Que princípio isso força, e qual é o conserto?'),
         choices=[
             (True, ('Interface segregation: a small PhoneLookup role, declared by the reminders', 'Segregação de interfaces: um papel pequeno PhoneLookup, declarado pelos lembretes'),
              ('Right. The repository can still be the object passed in; the reminders just ask for less.',
               'Isso. O repositório ainda pode ser o objeto passado; os lembretes só pedem menos.')),
             (False, ('Liskov substitution: the repository cannot be replaced', 'Substituição de Liskov: o repositório não pode ser trocado'),
              ('No child breaks a parent\'s promise here; the issue is how much the client depends on.',
               'Nenhum filho quebra promessa do pai aqui; a questão é de quanto o cliente depende.')),
             (False, ('Single responsibility: split MemberRepository into eleven classes', 'Responsabilidade única: dividir MemberRepository em onze classes'),
              ('Splitting by method is splitting by size; the client\'s declaration is what should shrink.',
               'Dividir por método é dividir por tamanho; o que deve encolher é a declaração do cliente.')),
         ]),
    dict(id='ex-cyt7a4w5', section='drill', type='quiz', difficulty='hard',
         prompt=('A colleague says: "We use dependency injection everywhere, so our code follows dependency inversion." The rules receive an SmtpMailer through their constructor. Is the colleague right?',
                 'Um colega diz: "Usamos injeção de dependência em todo lugar, então nosso código segue a inversão de dependência." As regras recebem um SmtpMailer pelo construtor. O colega tem razão?'),
         choices=[
             (False, ('Yes: passing the object in is what inversion means', 'Sim: passar o objeto de fora é o que inversão significa'),
              ('Passing in is injection; what the rules are typed against still belongs to the mail code.',
               'Passar de fora é injeção; aquilo contra o que as regras são tipadas ainda é do código de e-mail.')),
             (True, ('No: the rules still depend on a mail class; they need a port of their own',
                     'Não: as regras ainda dependem de uma classe concreta de e-mail'),
              ('Right. Injection is a technique; inversion is about who owns the abstraction and which way imports point.',
               'Isso. Injeção é uma técnica; inversão é sobre quem é dono da abstração e para que lado apontam os imports.')),
             (False, ('Yes, as long as SmtpMailer has an interface somewhere', 'Sim, desde que SmtpMailer tenha uma interface em algum lugar'),
              ('An interface owned by the mail package, in its vocabulary, inverts nothing.',
               'Uma interface do pacote de e-mail, no vocabulário dele, não inverte nada.')),
             (False, ('No: inversion is impossible in Python, which has no interfaces', 'Não: inversão é impossível em Python, que não tem interfaces'),
              ('notices.py did it with a Protocol; every language in the course can.',
               'notices.py fez isso com um Protocol; toda linguagem do curso consegue.')),
         ]),
    dict(id='ex-fhtpyw4j', section='drill', type='quiz', difficulty='hard',
         prompt=('A new project starts with IBookRepository, BookRepositoryImpl and a BookRepositoryFactory, though one storage is planned and no test uses a double. What does this lesson advise?',
                 'Um projeto novo começa com IBookRepository, BookRepositoryImpl e um BookRepositoryFactory, embora só um armazenamento esteja planejado e nenhum teste use dublê. O que esta lição aconselha?'),
         choices=[
             (False, ('Keep them: SOLID requires an interface for every repository', 'Mantê-los: SOLID exige uma interface para todo repositório'),
              ('No principle says that; each is conditional on a change.', 'Nenhum princípio diz isso; cada um depende de uma mudança.')),
             (False, ('Add a second implementation so the interface is justified', 'Acrescentar uma segunda implementação para justificar a interface'),
              ('That builds more code to excuse the first speculation.', 'Isso constrói mais código para desculpar a primeira especulação.')),
             (True, ('Start plain, and add the port when a real change asks for it', 'Começar simples e pôr a porta quando uma mudança real pedir'),
              ('Right. A seam arrives with the change that justifies it, and takes its name from that change.',
               'Isso. Uma emenda chega com a mudança que a justifica, e ganha o nome dessa mudança.')),
         ]),
]
