"""Lesson 5: dependency injection and inversion of control."""

EXERCISES = [
    # ---- inversion-of-control
    dict(id='ex-6td77mfz', section='inversion-of-control', type='quiz', difficulty='easy',
         prompt=('What separates a framework from a library, in the sense the lesson uses?',
                 'O que separa um framework de uma biblioteca, no sentido que a lição usa?'),
         choices=[
             (False, ('A framework is larger and has more modules', 'Um framework é maior e tem bem mais módulos'),
              ('Size decides nothing: desk.py is a framework of a dozen lines.',
               'Tamanho não decide nada: desk.py é um framework de uma dúzia de linhas.')),
             (True, ('A framework calls you; you call a library', 'Ele chama você; a biblioteca, você chama'),
              ('Right. Who holds the loop is the whole difference.', 'Isso. Quem segura o laço é a diferença inteira.')),
             (False, ('A library has to be installed, while a framework ships with the language',
                      'Uma biblioteca precisa ser instalada, e um framework vem com a linguagem'),
              ('unittest ships with Python and is a framework; textwrap ships with it too and is a library.',
               'O unittest vem com o Python e é um framework; o textwrap também vem e é uma biblioteca.')),
             (False, ('A framework only exists for web applications', 'Um framework só existe para aplicações web'),
              ('unittest and tkinter are frameworks with no web in them.',
               'unittest e tkinter são frameworks sem nada de web.')),
         ]),
    dict(id='ex-w7ph7y3e', section='inversion-of-control', type='quiz', difficulty='medium',
         prompt=('In desk.py, the request to renew Vidas Secas was skipped. Which code made that decision?',
                 'Em desk.py, o pedido de renovar Vidas Secas foi pulado. Que código tomou essa decisão?'),
         choices=[
             (False, ('The lend handler, which saw a title it did not expect', 'O tratador lend, que viu um título inesperado'),
              ('lend was never called for that request; no handler was registered for renew.',
               'lend nunca foi chamado para esse pedido; nenhum tratador estava registrado para renew.')),
             (False, ('Python, because the dictionary lookup raised an error', 'O Python, porque a busca no dicionário levantou um erro'),
              ('Desk.run uses get, which returns None instead of raising; the skip is a branch in run.',
               'Desk.run usa get, que devolve None em vez de levantar erro; o pulo é um desvio em run.')),
             (True, ('Desk.run, the loop of the framework', 'Desk.run, o laço do framework'),
              ('Right. The framework owns the loop, so it decides what happens to a request nobody handles.',
               'Isso. O framework é dono do laço, então decide o que acontece com um pedido que ninguém trata.')),
         ]),
    dict(id='ex-q6ywh1k1', section='inversion-of-control', type='cloze', difficulty='easy',
         prompt=('"Don\'t call us, we\'ll call you" is the old name for inversion of control: the ___ principle.',
                 '"Não nos ligue, nós ligamos para você" é o nome antigo da inversão de controle: o princípio de ___.'),
         blanks=[dict(en=['Hollywood'], pt=['Hollywood'])]),
    # ---- constructor-injection
    dict(id='ex-tk5kj9bm', section='constructor-injection', type='quiz', difficulty='medium',
         prompt=('Why does OverdueNotices receive a Clock instead of calling date.today() itself?',
                 'Por que OverdueNotices recebe um Clock em vez de chamar date.today() sozinha?'),
         choices=[
             (False, ('date.today() is slow, and a clock object caches the answer', 'date.today() é lento, e um objeto relógio guarda a resposta'),
              ('Speed has nothing to do with it; FixedClock exists so the day can be chosen.',
               'Velocidade não tem nada a ver; FixedClock existe para o dia poder ser escolhido.')),
             (True, ('So the caller decides which day it is', 'Para quem chama decidir que dia é'),
              ('Right. "What day is it" is a dependency, and the most often forgotten one.',
               'Isso. "Que dia é hoje" é uma dependência, e a mais esquecida.')),
             (False, ('Python forbids calling date.today() inside a method', 'O Python proíbe chamar date.today() dentro de um método'),
              ('It allows it; the first draft did exactly that, and it worked until somebody needed 20 March.',
               'Permite; o primeiro rascunho fez exatamente isso, e funcionou até alguém precisar do dia 20 de março.')),
             (False, ('Every class must take a clock, as a rule of SOLID', 'Toda classe deve receber um relógio, por uma regra do SOLID'),
              ('No principle says so; only classes whose behaviour depends on the date need one.',
               'Nenhum princípio diz isso; só as classes cujo comportamento depende da data precisam de um.')),
         ]),
    dict(id='ex-gv16b94z', section='constructor-injection', type='numeric', difficulty='medium',
         prompt=('OverdueNotices is built with FixedClock(date(2026, 3, 20)). A loan was due on 9 March 2026. What fine, in cents, does its notice quote?',
                 'OverdueNotices é construída com FixedClock(date(2026, 3, 20)). Um empréstimo vencia em 9 de março de 2026. Que multa, em centavos, o aviso cita?'),
         hint=('50 cents for each day after the due date.', '50 centavos por dia depois do vencimento.'),
         value=550, tolerance=0, unit=('cents', 'centavos')),
    dict(id='ex-y9t8jex1', section='constructor-injection', type='quiz', difficulty='hard',
         prompt=('A class you are reviewing takes seven collaborators in its constructor. What does the lesson read into that?',
                 'Uma classe que você revisa recebe sete colaboradores no construtor. O que a lição enxerga nisso?'),
         choices=[
             (False, ('Constructor injection has hit its limit and a container is needed',
                      'A injeção pelo construtor chegou ao limite e é preciso um contêiner'),
              ('A container would hide the seven, not remove them; the class would still do seven things.',
               'Um contêiner esconderia os sete, sem removê-los; a classe continuaria fazendo sete coisas.')),
             (False, ('Half of them should move to setters so the constructor reads shorter',
                      'Metade deles devia ir para setters para o construtor ficar mais curto'),
              ('That only hides them and loses the guarantee that each one is present.',
               'Isso só os esconde e perde a garantia de que cada um está presente.')),
             (True, ('The class is probably doing several jobs, and the long list is just being honest about it',
                     'A classe provavelmente faz vários trabalhos, e a lista longa só está sendo honesta sobre isso'),
              ('Right. Lesson 3\'s single responsibility principle is the conversation to have about it.',
               'Isso. O princípio da responsabilidade única da lição 3 é a conversa a ter sobre ela.')),
         ]),
    # ---- other-forms
    dict(id='ex-meg7zmxs', section='other-forms', type='matching', difficulty='medium',
         prompt=('Match each form of injection to the moment a missing dependency is noticed.',
                 'Associe cada forma de injeção ao momento em que a falta de uma dependência é percebida.'),
         pairs=[
             (('constructor', 'construtor'), ('when the object is built', 'quando o objeto é construído')),
             (('setter', 'setter'), ('at the first use, possibly much later', 'no primeiro uso, talvez bem depois')),
             (('method', 'método'), ('at the call that should have passed it', 'na chamada que devia tê-la passado')),
         ]),
    dict(id='ex-r6f6mbn4', section='other-forms', type='quiz', difficulty='medium',
         prompt=('In forms.py, Reminder() succeeded and the first remind() failed with \'NoneType\' object has no attribute \'send\'. What does that show?',
                 'Em forms.py, Reminder() funcionou e o primeiro remind() falhou com \'NoneType\' object has no attribute \'send\'. O que isso mostra?'),
         choices=[
             (True, ('Setter injection lets an object exist without what it needs', 'A injeção por setter deixa um objeto existir sem o que ele precisa'),
              ('Right. Between construction and the assignment the object is broken, and nothing says so until it is used.',
               'Isso. Entre a construção e a atribuição o objeto está quebrado, e nada avisa até ele ser usado.')),
             (False, ('PrintNotifier has a bug in its send method', 'PrintNotifier tem um bug no método send'),
              ('PrintNotifier was never reached; the attribute was still None.',
               'PrintNotifier nem foi alcançado; o atributo ainda era None.')),
             (False, ('Python cannot assign an attribute after an object is built, so the notifier is lost',
                      'O Python não consegue atribuir um atributo depois que o objeto é construído, e o notificador se perde'),
              ('It can; the third line of output came from a Reminder whose notifier was assigned afterwards.',
               'Consegue; a terceira linha da saída veio de um Reminder cujo notificador foi atribuído depois.')),
         ]),
    dict(id='ex-zfxdj5py', section='other-forms', type='quiz', difficulty='hard',
         prompt=('The desk prints a receipt for one member and texts it to the next, using the same Receipt object. Which form fits?',
                 'O balcão imprime o recibo de um membro e manda o do próximo por SMS, usando o mesmo objeto Receipt. Que forma serve?'),
         choices=[
             (False, ('Constructor injection, with one Receipt per channel kept for the day',
                      'Injeção pelo construtor, com um Receipt por canal guardado para o dia'),
              ('It works, but it builds objects to carry a choice that changes with every call.',
               'Funciona, mas constrói objetos para carregar uma escolha que muda a cada chamada.')),
             (True, ('Method injection', 'Injeção por método'),
              ('Right. The dependency changes from call to call, so each call passes it.',
               'Isso. A dependência muda de uma chamada para outra, então cada chamada a passa.')),
             (False, ('A service locator that the desk updates before each receipt', 'Um service locator que o balcão atualiza antes de cada recibo'),
              ('That is global state changing under the receipt, and the call no longer shows which channel it uses.',
               'Isso é estado global mudando por baixo do recibo, e a chamada deixa de mostrar que canal usa.')),
             (False, ('Setter injection, setting the notifier before every receipt', 'Injeção por setter, definindo o notificador antes de cada recibo'),
              ('Possible, and one forgotten assignment sends a receipt down the previous member\'s channel.',
               'Possível, e uma atribuição esquecida manda o recibo pelo canal do membro anterior.')),
         ]),
    # ---- composition-root
    dict(id='ex-7m3f15wz', section='composition-root', type='quiz', difficulty='easy',
         prompt=('What is the composition root of a program?', 'O que é a raiz de composição de um programa?'),
         choices=[
             (False, ('The base class every service of the program inherits its wiring from',
                      'A classe base da qual todo serviço do programa herda a sua ligação às outras'),
              ('Nothing inherits from it; it is the place where objects are built and connected.',
               'Nada herda dela; ela é o lugar onde os objetos são construídos e conectados.')),
             (True, ('The place near the entry point that builds and wires every object',
                     'O lugar perto do ponto de entrada que constrói e liga todos os objetos'),
              ('Right. In main.py it is build.', 'Isso. Em main.py, é o build.')),
             (False, ('The top directory of the repository, where main.py is kept', 'O diretório mais alto do repositório, onde fica o main.py'),
              ('It is code, not a folder: the root of the object graph.', 'É código, não pasta: a raiz do grafo de objetos.')),
         ]),
    dict(id='ex-rt1bmct1', section='composition-root', type='quiz', difficulty='medium',
         prompt=('A colleague adds a helper inside OverdueNotices that writes SmsNotifier() for urgent notices. What has changed?',
                 'Um colega acrescenta uma função auxiliar dentro de OverdueNotices que escreve SmsNotifier() para avisos urgentes. O que mudou?'),
         choices=[
             (False, ('Nothing important, since SmsNotifier still matches the Notifier protocol',
                      'Nada importante, já que SmsNotifier continua seguindo o protocolo Notifier'),
              ('Matching the protocol is not the issue; the job now chooses a concrete class, which only main.py was meant to do.',
               'Seguir o protocolo não é a questão; a tarefa agora escolhe uma classe concreta, o que só main.py devia fazer.')),
             (True, ('A choice that belonged to the composition root is back inside the job',
                     'Uma escolha que pertencia à raiz de composição voltou para dentro da tarefa'),
              ('Right. Changing how urgent notices go out now means finding that helper.',
               'Isso. Mudar como os avisos urgentes saem agora significa achar essa função.')),
             (False, ('The program will no longer run, because OverdueNotices may not import anything',
                      'O programa deixa de rodar, porque OverdueNotices não pode importar nada'),
              ('It still runs; the cost is in design, and it shows the day somebody wants e-mail instead.',
               'Continua rodando; o custo é de projeto, e aparece no dia em que alguém quiser e-mail.')),
             (False, ('The job becomes a service locator', 'A tarefa vira um service locator'),
              ('Nothing is fetched from a registry; the class is constructed directly, which is the original problem.',
               'Nada é buscado num registro; a classe é construída diretamente, que é o problema original.')),
         ]),
    dict(id='ex-ts3rpa9c', section='composition-root', type='ordering', difficulty='medium',
         prompt=('Put what happens when main.py runs in order.', 'Ponha em ordem o que acontece quando main.py roda.'),
         items=[('Read the channel from the arguments and LIBRARY_TODAY from the environment',
                 'Ler o canal dos argumentos e LIBRARY_TODAY do ambiente'),
                ('Build the store, the notifier and the clock', 'Construir o repositório, o notificador e o relógio'),
                ('Build OverdueNotices with those three', 'Construir OverdueNotices com esses três'),
                ('Call send_all and print how many were sent', 'Chamar send_all e imprimir quantos saíram')],
         trap=('Building the job before its collaborators is impossible with constructor injection: it needs them as arguments.',
               'Construir a tarefa antes dos colaboradores é impossível com injeção pelo construtor: ela precisa deles como argumentos.')),
    # ---- containers
    dict(id='ex-wj09kkb0', section='containers', type='quiz', difficulty='medium',
         prompt=('How does the container in container.py know that OverdueNotices needs a Clock?',
                 'Como o contêiner de container.py sabe que OverdueNotices precisa de um Clock?'),
         choices=[
             (False, ('Clock was registered before OverdueNotices', 'Clock foi registrado antes de OverdueNotices'),
              ('Order of registration plays no part; the bare container refused even though everything else was registered.',
               'A ordem de registro não conta; o contêiner vazio recusou mesmo com todo o resto registrado.')),
             (True, ('It reads the type hints on __init__', 'Ele lê as anotações de tipo de __init__'),
              ('Right. get_type_hints is the autowiring; without the hints it would know nothing.',
               'Isso. get_type_hints é o autowiring; sem as anotações ele não saberia nada.')),
             (False, ('It calls the constructor with no arguments and studies the error it gets back',
                      'Ele chama o construtor sem argumentos e estuda o erro que recebe de volta'),
              ('It never calls a constructor without arguments; it resolves every hinted parameter first.',
               'Ele nunca chama um construtor sem argumentos; resolve antes cada parâmetro anotado.')),
             (False, ('OverdueNotices registers its own needs when it is imported', 'OverdueNotices registra as próprias necessidades ao ser importada'),
              ('OverdueNotices knows nothing about the container, and that is what keeps it reusable.',
               'OverdueNotices não sabe nada do contêiner, e é isso que a mantém reutilizável.')),
         ]),
    dict(id='ex-bmmvg4tr', section='containers', type='quiz', difficulty='medium',
         prompt=('wired.py printed same notifier: True and same clock: False. Why the difference?',
                 'wired.py imprimiu same notifier: True e same clock: False. Por que a diferença?'),
         choices=[
             (False, ('A clock holds a date, and objects holding dates are always rebuilt',
                      'Um relógio guarda uma data, e objetos com datas são sempre reconstruídos'),
              ('The container knows nothing about dates; it follows what was registered.',
               'O contêiner não sabe nada de datas; ele segue o que foi registrado.')),
             (False, ('The clock was registered as a lambda, and lambdas cannot be compared with is',
                      'O relógio foi registrado como lambda, e lambdas não podem ser comparadas com is'),
              ('The comparison is between the objects resolve returned, and any two objects can be compared with is.',
               'A comparação é entre os objetos que resolve devolveu, e quaisquer dois objetos podem ser comparados com is.')),
             (True, ('Only the notifier was registered with shared=True', 'Só o notificador foi registrado com shared=True'),
              ('Right. That is a lifetime: one shared instance, or a new one per request.',
               'Isso. Isso é um tempo de vida: uma instância compartilhada, ou uma nova a cada pedido.')),
         ]),
    dict(id='ex-p1w9x98y', section='containers', type='quiz', difficulty='hard',
         prompt=('A command-line tool of twelve classes is wired by hand in main. A teammate proposes adding a container. What does the lesson say?',
                 'Uma ferramenta de linha de comando com doze classes é ligada à mão no main. Um colega propõe acrescentar um contêiner. O que a lição diz?'),
         choices=[
             (True, ('Keep the hand wiring; at this size a container costs more than it saves',
                     'Manter a ligação à mão; nesse tamanho um contêiner custa mais do que poupa'),
              ('Right. The trade pays when the wiring is large, repetitive or per request, and none of that is true here.',
               'Isso. A troca compensa quando a ligação é grande, repetitiva ou por requisição, e nada disso vale aqui.')),
             (False, ('Add it, because constructor injection does not work without one', 'Acrescentar, porque injeção pelo construtor não funciona sem um'),
              ('main.py injects by hand and works; the container automates what build already does.',
               'main.py injeta à mão e funciona; o contêiner automatiza o que build já faz.')),
             (False, ('Add it, since a container finds missing dependencies before the program even starts',
                      'Acrescentar, já que um contêiner acha dependências faltando antes mesmo de o programa começar'),
              ('A runtime container finds them at resolve; hand wiring in main fails at least as early.',
               'Um contêiner em tempo de execução as acha no resolve; a ligação à mão no main falha no mínimo tão cedo.')),
         ]),
    # ---- service-locator
    dict(id='ex-y4a6gxbz', section='service-locator', type='quiz', difficulty='medium',
         prompt=('Injection and a service locator both keep SmtpNotifier() out of the job. What is the difference?',
                 'Injeção e service locator mantêm SmtpNotifier() fora da tarefa. Qual é a diferença?'),
         choices=[
             (False, ('A locator is faster, because nothing has to be passed through every constructor on the way',
                      'Um locator é mais rápido, porque nada precisa passar por cada construtor no caminho'),
              ('Passing an argument costs nothing worth measuring; the difference is in what a reader and a test can see.',
               'Passar um argumento não custa nada que valha medir; a diferença está no que um leitor e um teste conseguem ver.')),
             (True, ('With injection the object is handed its collaborators; with a locator it fetches them',
                     'Com injeção o objeto recebe os colaboradores; com um locator ele vai buscá-los'),
              ('Right. The direction is the difference, and it decides whether the constructor tells the truth.',
               'Isso. A direção é a diferença, e decide se o construtor diz a verdade.')),
             (False, ('A locator works with protocols, and injection with concrete classes',
                      'Um locator funciona com protocolos, e a injeção com classes concretas'),
              ('Both work with either; OverdueNotices is injected with protocols.',
               'Os dois funcionam com ambos; OverdueNotices é injetada com protocolos.')),
         ]),
    dict(id='ex-brqvhfxy', section='service-locator', type='quiz', difficulty='hard',
         prompt=('A team imports its container into every class and calls container.resolve(Notifier) inside methods. What have they built?',
                 'Uma equipe importa o contêiner em toda classe e chama container.resolve(Notifier) dentro dos métodos. O que ela construiu?'),
         choices=[
             (False, ('Dependency injection, since a container is doing the work', 'Injeção de dependência, já que um contêiner faz o trabalho'),
              ('A container used this way is asked from inside, which is fetching, not being handed.',
               'Um contêiner usado assim é consultado de dentro, o que é buscar, não receber.')),
             (False, ('A composition root spread across the files', 'Uma raiz de composição espalhada pelos arquivos'),
              ('A root is one place by definition; spread out, it is the scattering the root exists to end.',
               'Uma raiz é um lugar só, por definição; espalhada, ela é a dispersão que a raiz existe para acabar.')),
             (True, ('A service locator, whatever the container is called', 'Um service locator, diga a documentação o que disser'),
              ('Right. The tool is the same; asking it from inside methods makes it a locator.',
               'Isso. A ferramenta é a mesma; consultá-la de dentro dos métodos faz dela um locator.')),
             (False, ('Inversion of control, because no class constructs its own notifier',
                      'Inversão de controle, porque nenhuma classe constrói o próprio notificador'),
              ('Each class still decides when to get its notifier and from where; nothing is handed to it.',
               'Cada classe ainda decide quando pegar o notificador e de onde; nada é entregue a ela.')),
         ]),
    dict(id='ex-dc5qcmnt', section='service-locator', type='multiple-choice', difficulty='hard',
         prompt=('Which of these does the service locator in locator.py hide or cause? Choose all that apply.',
                 'Quais destas coisas o service locator de locator.py esconde ou causa? Marque todas que se aplicam.'),
         choices=[
             (True, ('The constructor claims the class needs nothing', 'O construtor afirma que a classe não precisa de nada'),
              ('Right. LocatedNotices() takes no arguments and uses three services.',
               'Isso. LocatedNotices() não recebe argumentos e usa três serviços.')),
             (True, ('A missing clock is found inside the loop rather than at construction',
                     'Um relógio que falta é descoberto dentro do laço, não na construção'),
              ('Right. The object was built and announced before the KeyError.',
               'Isso. O objeto foi construído e anunciado antes do KeyError.')),
             (True, ('One test\'s fake can leak into the next test', 'O fake de um teste pode vazar para o teste seguinte'),
              ('Right. The registry is global, so what one test provides stays for the next.',
               'Isso. O registro é global, então o que um teste fornece fica para o próximo.')),
             (False, ('The job sends notices to the wrong members', 'A tarefa manda avisos para os membros errados'),
              ('The rule is the same as in OverdueNotices; what changed is how the collaborators arrive.',
               'A regra é a mesma de OverdueNotices; o que mudou é como os colaboradores chegam.')),
         ]),
    # ---- testing-with-fakes
    dict(id='ex-ae91r631', section='testing-with-fakes', type='quiz', difficulty='medium',
         prompt=('Why does test_overdue.py need no unittest.mock.patch at all?',
                 'Por que test_overdue.py não precisa de nenhum unittest.mock.patch?'),
         choices=[
             (False, ('Because unittest refuses patches in a class that has setUp', 'Porque o unittest recusa patches numa classe que tem setUp'),
              ('setUp and patch work together fine; there is simply nothing to patch.',
               'setUp e patch convivem bem; simplesmente não há nada para substituir.')),
             (True, ('The job is handed its clock and notifier, so the test hands it fakes',
                     'A tarefa recebe o relógio e o notificador, então o teste entrega fakes'),
              ('Right. A class that builds nothing has nothing to reach into.',
               'Isso. Uma classe que não constrói nada não tem nada onde mexer por dentro.')),
             (False, ('PrintNotifier never sends anything real, so it needs no replacing',
                      'PrintNotifier nunca manda nada de verdade, então não precisa ser trocado'),
              ('The test does not use PrintNotifier at all; it passes a RecordingNotifier.',
               'O teste nem usa PrintNotifier; ele passa um RecordingNotifier.')),
         ]),
    dict(id='ex-e4shrwhp', section='testing-with-fakes', type='quiz', difficulty='hard',
         prompt=('A test patches "overdue_draft.SmtpNotifier". The job is then moved to a file called jobs.py and the test is left alone. What happens?',
                 'Um teste faz patch de "overdue_draft.SmtpNotifier". A tarefa é então movida para um arquivo chamado jobs.py, e o teste fica como estava. O que acontece?'),
         choices=[
             (False, ('Python updates the patch target to follow the moved class', 'O Python atualiza o alvo do patch para seguir a classe movida'),
              ('A patch target is a string; nothing rewrites it.', 'O alvo de um patch é uma string; nada a reescreve.')),
             (True, ('The patch misses, and the real mail server is called',
                     'O patch erra o alvo, e o servidor de e-mail real é chamado'),
              ('Right. The patch was coupled to an import name, not to what the job needs.',
               'Isso. O patch estava amarrado a um nome de importação, não ao que a tarefa precisa.')),
             (False, ('The test keeps working exactly as before', 'O teste continua funcionando exatamente como antes'),
              ('jobs.py looks up its own SmtpNotifier; the patch replaced the name in the old module.',
               'jobs.py busca o próprio SmtpNotifier; o patch trocou o nome no módulo antigo.')),
             (False, ('Every test in the file fails to import', 'Todos os testes do arquivo falham ao importar'),
              ('Only the moved job changes; whether the test notices at all is the danger.',
               'Só a tarefa movida muda; o perigo é justamente se o teste vai perceber.')),
         ]),
    dict(id='ex-264xtp5h', section='testing-with-fakes', type='quiz', difficulty='medium',
         prompt=('In test_overdue.py, Loan and ListedLoans are the real classes. Why are they not faked?',
                 'Em test_overdue.py, Loan e ListedLoans são as classes reais. Por que não são falsificadas?'),
         choices=[
             (True, ('They are fast, deterministic and ours, so faking them would test nothing',
                     'São rápidas, determinísticas e nossas, então falsificá-las não testaria nada'),
              ('Right. Fake what is slow, non-deterministic or outside the process.',
               'Isso. Falsifique o que é lento, não determinístico ou fica fora do processo.')),
             (False, ('A frozen dataclass cannot be replaced by a double', 'Uma dataclass congelada não pode ser trocada por um dublê'),
              ('It could; any object with the same fields would do. It is just pointless.',
               'Poderia; qualquer objeto com os mesmos campos serviria. Só não tem sentido.')),
             (False, ('Faking every collaborator is the rule, and these two were forgotten',
                      'Falsificar todo colaborador é a regra, e estes dois foram esquecidos'),
              ('A test that fakes everything checks only call order and breaks on every refactor.',
               'Um teste que falsifica tudo confere só a ordem das chamadas e quebra a cada refatoração.')),
         ]),
    # ---- drill
    dict(id='ex-njtr1xz0', section='drill', type='matching', difficulty='medium',
         prompt=('Match each line of this lesson\'s code to the idea it shows.',
                 'Associe cada linha do código desta lição à ideia que ela mostra.'),
         pairs=[
             (('desk.run(queue) calling each handler', 'desk.run(queue) chamando cada tratador'),
              ('inversion of control', 'inversão de controle')),
             (('def __init__(self, loans, notifier, clock)', 'def __init__(self, loans, notifier, clock)'),
              ('constructor injection', 'injeção pelo construtor')),
             (('Services.get("clock") inside send_all', 'Services.get("clock") dentro de send_all'),
              ('service locator', 'service locator')),
             (('get_type_hints(provider.__init__)', 'get_type_hints(provider.__init__)'),
              ('autowiring', 'autowiring')),
         ],
         right_distractors=[('setter injection', 'injeção por setter')]),
    dict(id='ex-p6a98vpg', section='drill', type='quiz', difficulty='hard',
         prompt=('Deep inside a mailer class, a method reads os.environ["SMTP_HOST"] and builds a connection. Which change does this lesson point to?',
                 'Lá no fundo de uma classe de e-mail, um método lê os.environ["SMTP_HOST"] e constrói uma conexão. Que mudança esta lição indica?'),
         choices=[
             (False, ('Register the host in a global Services registry so every class can read it',
                      'Registrar o host num registro global Services para toda classe poder lê-lo'),
              ('That swaps one hidden dependency for another; the method would still fetch.',
               'Isso troca uma dependência escondida por outra; o método continuaria buscando.')),
             (False, ('Read the variable in a setter that the mailer calls on itself', 'Ler a variável num setter que a própria classe chama'),
              ('The class would still decide where its configuration comes from.',
               'A classe continuaria decidindo de onde vem a sua configuração.')),
             (True, ('Read it in main and pass the connection in', 'Lê-la no main e passar a conexão para dentro'),
              ('Right. Configuration is read once, near the entry point, and the class receives what it needs.',
               'Isso. A configuração é lida uma vez, perto do ponto de entrada, e a classe recebe o que precisa.')),
         ]),
    dict(id='ex-2pbmacw7', section='drill', type='quiz', difficulty='hard',
         prompt=('A test passes when run alone and fails when run after another test in the same file. Which design from this lesson is the usual suspect?',
                 'Um teste passa quando roda sozinho e falha quando roda depois de outro teste do mesmo arquivo. Que projeto desta lição é o suspeito de sempre?'),
         choices=[
             (False, ('Constructor injection, because setUp builds a new object each time',
                      'Injeção pelo construtor, porque setUp constrói um objeto novo a cada vez'),
              ('A fresh object per test is what keeps tests independent.',
               'Um objeto novo por teste é justamente o que mantém os testes independentes.')),
             (True, ('A service locator, whose global registry keeps what the first test provided',
                     'Um service locator, cujo registro global guarda o que o primeiro teste forneceu'),
              ('Right. Order-dependent tests are the signature of shared global state.',
               'Isso. Testes que dependem da ordem são a assinatura de estado global compartilhado.')),
             (False, ('Method injection, which passes a different notifier on every call',
                      'Injeção por método, que passa um notificador diferente a cada chamada'),
              ('Each call names its notifier, so nothing carries over between tests.',
               'Cada chamada diz qual notificador usa, então nada passa de um teste para outro.')),
             (False, ('A composition root, since main.py runs before the tests', 'Uma raiz de composição, já que main.py roda antes dos testes'),
              ('The tests never import main.py; the root is not part of what is tested.',
               'Os testes nem importam main.py; a raiz não faz parte do que é testado.')),
         ]),
]
