"""Lesson 6: the GoF patterns in practice."""

EXERCISES = [
    # ---- the-catalogue
    dict(id='ex-ahbrax1m', section='the-catalogue', type='quiz', difficulty='easy',
         prompt=('Every pattern in the 1994 book ends with its consequences. What is that part for?',
                 'Todo padrão do livro de 1994 termina com as consequências. Para que serve essa parte?'),
         choices=[
             (False, ('It lists the programs that already use the pattern, as proof that it works',
                      'Lista os programas que já usam o padrão, como prova de que ele funciona'),
              ('The book gives known uses elsewhere; the consequences are about costs.',
               'O livro cita usos conhecidos em outra parte; as consequências tratam de custos.')),
             (True, ('Saying what the pattern costs', 'Dizer quanto o padrão custa'),
              ('Right. Every pattern adds indirection, and this part says when that pays.',
               'Isso. Todo padrão acrescenta indireção, e esta parte diz quando isso compensa.')),
             (False, ('Giving the C++ code to copy into your program', 'Dar o código C++ para copiar no seu programa'),
              ('A pattern is a shape, not code to copy; the code differs in every program.',
               'Um padrão é uma forma, não código para copiar; o código muda em cada programa.')),
         ]),
    dict(id='ex-96x7wr50', section='the-catalogue', type='cloze', difficulty='easy',
         prompt=('The book\'s introduction says: program to an interface, and favour object ___ over class inheritance.',
                 'A introdução do livro diz: programe para uma interface, e prefira a ___ de objetos à herança de classes.'),
         blanks=[dict(en=['composition'], pt=['composição', 'composicao', 'composition'])]),
    # ---- factory-and-builder
    dict(id='ex-aqkhgx96', section='factory-and-builder', type='quiz', difficulty='easy',
         prompt=('The library starts lending board games. With the factory in factory.py, what has to change besides the new class?',
                 'A biblioteca passa a emprestar jogos de tabuleiro. Com a factory de factory.py, o que precisa mudar além da classe nova?'),
         choices=[
             (False, ('Every function that reads rows, to add a branch for games', 'Toda função que lê linhas, para ganhar um desvio para jogos'),
              ('That is the scattered if the factory exists to remove.',
               'Esse é o if espalhado que a factory existe para remover.')),
             (True, ('One entry in KINDS', 'Uma entrada em KINDS'),
              ('Right. The string-to-class decision lives in one dictionary.',
               'Isso. A decisão de string para classe mora num dicionário só.')),
             (False, ('Loan.for_item, so that it knows how long a game is lent for', 'Loan.for_item, para saber por quanto tempo um jogo é emprestado'),
              ('for_item reads loan_days from the item, whatever its class.',
               'for_item lê loan_days do item, seja qual for a classe.')),
             (False, ('Nothing at all, because the factory discovers new classes on its own',
                      'Nada, porque a factory descobre classes novas sozinha'),
              ('It discovers nothing; an unknown kind is refused by name, as vinyl was.',
               'Ela não descobre nada; um tipo desconhecido é recusado pelo nome, como o vinil.')),
         ]),
    dict(id='ex-akjr9wdq', section='factory-and-builder', type='quiz', difficulty='medium',
         prompt=('Why does QueryBuilder check the column in order_by rather than leaving it to build?',
                 'Por que QueryBuilder confere a coluna em order_by em vez de deixar para build?'),
         choices=[
             (True, ('A step refuses bad input as it arrives, before any SQL',
                     'Um passo recusa a entrada ruim assim que chega, antes do SQL'),
              ('Right. That validation is one of the reasons a builder earns its place.',
               'Isso. Essa validação é um dos motivos de um builder merecer o lugar.')),
             (False, ('build is unable to raise exceptions in Python', 'build não consegue levantar exceções em Python'),
              ('Any method can raise; checking early is a choice about where errors show up.',
               'Qualquer método pode levantar; conferir cedo é uma escolha sobre onde os erros aparecem.')),
             (False, ('SQLite refuses ORDER BY on a column it was not told about first',
                      'O SQLite recusa ORDER BY numa coluna que não lhe foi informada antes'),
              ('The column is pasted into the text, so only the builder\'s list stands between a caller and arbitrary SQL there.',
               'A coluna é colada no texto, então só a lista do builder separa quem chama de um SQL arbitrário ali.')),
         ]),
    dict(id='ex-47s1t1m1', section='factory-and-builder', type='quiz', difficulty='hard',
         prompt=('A Python dataclass has nine fields, seven of them optional with sensible defaults, all set in one place. A colleague proposes a builder. What does the lesson suggest?',
                 'Uma dataclass Python tem nove campos, sete opcionais com padrões razoáveis, todos definidos num lugar só. Um colega propõe um builder. O que a lição sugere?'),
         choices=[
             (False, ('A builder, since Java code uses one in the same situation', 'Um builder, já que código Java usa um na mesma situação'),
              ('Java uses builders because it lacks keyword arguments; Python has them.',
               'O Java usa builders porque não tem argumentos nomeados; o Python tem.')),
             (False, ('A factory dictionary keyed by the combination of fields', 'Um dicionário de factory indexado pela combinação de campos'),
              ('A factory chooses a class; here there is one class and many optional values.',
               'Uma factory escolhe uma classe; aqui há uma classe e muitos valores opcionais.')),
             (True, ('Named parameters with fallback values, which it already has',
                     'Parâmetros nomeados com valores de reserva, que ela já tem'),
              ('Right. A builder pays when steps validate or the object is assembled in several places.',
               'Isso. Um builder compensa quando os passos validam ou o objeto é montado em vários lugares.')),
             (False, ('A singleton holding the default values shared by every instance of the class',
                      'Um singleton guardando os valores padrão de todas as instâncias'),
              ('Defaults belong to the fields; a global object would add shared state and nothing else.',
               'Padrões pertencem aos campos; um objeto global só acrescentaria estado compartilhado.')),
         ]),
    # ---- singleton
    dict(id='ex-jc3y305v', section='singleton', type='quiz', difficulty='medium',
         prompt=('In singleton.py, desk_b printed a fine of 75 although it never set one. Why?',
                 'Em singleton.py, desk_b imprimiu uma multa de 75 embora nunca a tenha definido. Por quê?'),
         choices=[
             (False, ('Settings reads the fine from a file that desk_a wrote', 'Settings lê a multa de um arquivo que desk_a escreveu'),
              ('Nothing touches a file; the value lives on the one shared instance.',
               'Nada mexe em arquivo; o valor mora na única instância compartilhada.')),
             (True, ('desk_a changed the one Settings object, which is the same object desk_b got',
                     'desk_a mudou o único objeto Settings, que é exatamente o mesmo objeto que desk_b recebeu'),
              ('Right. Global access means a change anywhere is seen everywhere, by code that never asked.',
               'Isso. Acesso global quer dizer que uma mudança em qualquer lugar é vista em todo lugar.')),
             (False, ('Python caches function results, so desk_b repeated desk_a\'s answer',
                      'O Python guarda resultados de funções, então desk_b repetiu a resposta de desk_a'),
              ('Python caches nothing here unless asked; the shared object is the cause.',
               'O Python não guarda nada aqui sem pedirem; a causa é o objeto compartilhado.')),
         ]),
    dict(id='ex-x7j1g98e', section='singleton', type='quiz', difficulty='easy',
         prompt=('Why is an object created at module level in Python already a singleton?',
                 'Por que um objeto criado no nível do módulo em Python já é um singleton?'),
         choices=[
             (False, ('Python forbids creating a second instance of any class defined in a module',
                      'O Python proíbe criar uma segunda instância de qualquer classe definida num módulo'),
              ('You can create as many Catalogue objects as you like; only shared is created once.',
               'Você pode criar quantos Catalogue quiser; só shared é criado uma vez.')),
             (False, ('Module-level names are copied into every importing file', 'Nomes do módulo são copiados em todo arquivo que importa'),
              ('If they were copies, shared is catalogue.shared would be False; it printed True.',
               'Se fossem cópias, shared is catalogue.shared daria False; deu True.')),
             (True, ('A module runs once and is cached, so every import gets the same object',
                     'Um módulo roda uma vez e fica guardado, então toda importação recebe o mesmo objeto'),
              ('Right. Two imports under two names printed True.', 'Isso. Duas importações com dois nomes imprimiram True.')),
         ]),
    dict(id='ex-4j0s1f2r', section='singleton', type='quiz', difficulty='hard',
         prompt=('The library needs exactly one catalogue in memory, and its tests keep interfering with each other. Which design does the lesson recommend?',
                 'A biblioteca precisa de exatamente um catálogo em memória, e os testes vivem interferindo uns nos outros. Que projeto a lição recomenda?'),
         choices=[
             (False, ('Keep the singleton and add a reset() method called by every test',
                      'Manter o singleton e acrescentar um reset() chamado por todo teste'),
              ('That is a method that exists only to undo the pattern, and a forgotten call brings the leak back.',
               'É um método que existe só para desfazer o padrão, e uma chamada esquecida traz o vazamento de volta.')),
             (True, ('Create one in the composition root and pass it in', 'Criar um na raiz de composição e passá-lo adiante'),
              ('Right. Still exactly one, without access from everywhere, and each test can hand in a fresh one.',
               'Isso. Continua sendo um só, sem acesso de todo lugar, e cada teste pode entregar um novo.')),
             (False, ('Make the singleton thread-safe with a lock around __new__', 'Tornar o singleton seguro para threads com um lock em volta de __new__'),
              ('A lock fixes double creation under threads; the tests still share one instance.',
               'Um lock resolve a criação dupla com threads; os testes continuam compartilhando uma instância.')),
         ]),
    # ---- adapter-and-facade
    dict(id='ex-bzz1yfe6', section='adapter-and-facade', type='quiz', difficulty='medium',
         prompt=('The national catalogue renames its field ttl to title. With OpenShelfCatalogue in place, what changes?',
                 'O catálogo nacional renomeia o campo ttl para title. Com OpenShelfCatalogue no lugar, o que muda?'),
         choices=[
             (False, ('Every function that shows a book, wherever it reads the field', 'Toda função que mostra um livro, onde quer que leia o campo'),
              ('Those functions read Book.title; they never saw ttl.', 'Essas funções leem Book.title; nunca viram ttl.')),
             (False, ('Book, which gains a ttl field so both names work', 'Book, que ganha um campo ttl para os dois nomes funcionarem'),
              ('Our model does not follow theirs; that is the point of the border.',
               'O nosso modelo não segue o deles; é esse o sentido da fronteira.')),
             (True, ('One line in the adapter\'s find method', 'Uma linha no método find do adapter'),
              ('Right. The adapter is where the foreign model stops.', 'Isso. O adapter é onde o modelo estrangeiro para.')),
             (False, ('LendingDesk, because the facade sits in front of the catalogue',
                      'LendingDesk, porque a facade fica na frente do catálogo'),
              ('The facade asks a Catalogue for a Book and is untouched by the service\'s format.',
               'A facade pede um Book a um Catalogue e não é afetada pelo formato do serviço.')),
         ]),
    dict(id='ex-g37fj3dc', section='adapter-and-facade', type='quiz', difficulty='medium',
         prompt=('What does LendingDesk do that makes it a facade rather than an adapter?',
                 'O que LendingDesk faz que a torna uma facade e não um adapter?'),
         choices=[
             (True, ('It gives several objects one simpler door', 'Dá a vários objetos uma porta mais simples'),
              ('Right. Catalogue, reservations, ledger and printer, behind one lend.',
               'Isso. Catálogo, reservas, registro e impressora, atrás de um lend.')),
             (False, ('It translates the service\'s record format into a Book', 'Traduz o formato de registro do serviço para um Book'),
              ('That is what OpenShelfCatalogue does, the adapter it is handed.',
               'Isso é o que OpenShelfCatalogue faz, o adapter que ela recebe.')),
             (False, ('It hides the Ledger so that no other code may ever read the loans',
                      'Esconde o Ledger para nenhum outro código jamais ler os empréstimos'),
              ('A facade adds a door; the monthly report can still use Ledger directly.',
               'Uma facade acrescenta uma porta; o relatório mensal ainda pode usar o Ledger direto.')),
         ]),
    dict(id='ex-5m54425p', section='adapter-and-facade', type='quiz', difficulty='hard',
         prompt=('Your code expects a Notifier with send(member, text). A new SMS company\'s library offers dispatch(phone_number, body, sender_id). What do you write?',
                 'O seu código espera um Notifier com send(member, text). A biblioteca de uma nova empresa de SMS oferece dispatch(phone_number, body, sender_id). O que você escreve?'),
         choices=[
             (False, ('A facade over the SMS library and the e-mail library together', 'Uma facade sobre a biblioteca de SMS e a de e-mail juntas'),
              ('Nothing here asks for one door to several things; one interface needs to look like another.',
               'Nada aqui pede uma porta para várias coisas; uma interface precisa parecer outra.')),
             (True, ('An adapter, translating each call into the other', 'Um adapter, que traduz cada chamada para a outra'),
              ('Right. It does what you need and speaks the wrong language, which is the adapter\'s question.',
               'Isso. Ela faz o que você precisa e fala a língua errada, que é a pergunta do adapter.')),
             (False, ('A proxy, because the SMS company is another process', 'Um proxy, porque a empresa de SMS é outro processo'),
              ('A proxy keeps the same interface; here the interfaces differ.',
               'Um proxy mantém a mesma interface; aqui as interfaces diferem.')),
             (False, ('Rename send to dispatch everywhere in your code', 'Renomear send para dispatch em todo o seu código'),
              ('That lets a vendor\'s names into your whole program, and the next vendor renames them again.',
               'Isso deixa os nomes de um fornecedor entrarem no programa inteiro, e o próximo fornecedor renomeia de novo.')),
         ]),
    # ---- decorator-and-proxy
    dict(id='ex-rmqnyeen', section='decorator-and-proxy', type='numeric', difficulty='medium',
         prompt=('student = Capped(GraceDays(DailyFine(50), days=2), cap=1000). What does student.fine(5) return, in cents?',
                 'student = Capped(GraceDays(DailyFine(50), days=2), cap=1000). Quanto student.fine(5) devolve, em centavos?'),
         hint=('Follow the call inwards, then the value back out.', 'Siga a chamada para dentro, depois o valor de volta.'),
         value=150, tolerance=0, unit=('cents', 'centavos')),
    dict(id='ex-9899jbn3', section='decorator-and-proxy', type='quiz', difficulty='medium',
         prompt=('GraceDays and CachingCatalogue are built the same way. What makes one a decorator and the other a proxy?',
                 'GraceDays e CachingCatalogue são construídas do mesmo jeito. O que faz de uma um decorator e da outra um proxy?'),
         choices=[
             (False, ('A decorator must change the interface, and a proxy must keep it',
                      'Um decorator deve mudar a interface, e um proxy deve mantê-la'),
              ('Both keep the interface; that is what lets them stand in for the wrapped object.',
               'Os dois mantêm a interface; é isso que permite que substituam o objeto embrulhado.')),
             (True, ('The intent: one adds behaviour, the other controls access', 'A intenção: um acrescenta comportamento, o outro controla o acesso'),
              ('Right. The structure is identical, and the name tells the reader which job it does.',
               'Isso. A estrutura é idêntica, e o nome diz a quem lê que trabalho ele faz.')),
             (False, ('A proxy has to talk to another process over the network', 'Um proxy precisa falar com outro processo pela rede'),
              ('That is one kind, the remote proxy; CachingCatalogue is in the same process.',
               'Esse é um tipo, o proxy remoto; CachingCatalogue está no mesmo processo.')),
         ]),
    dict(id='ex-arbsqq44', section='decorator-and-proxy', type='quiz', difficulty='hard',
         prompt=('An ORM returns a loan whose member is loaded from the database only when code first touches loan.member. Which kind of proxy is that?',
                 'Um ORM devolve um empréstimo cujo membro só é carregado do banco quando o código toca loan.member pela primeira vez. Que tipo de proxy é esse?'),
         choices=[
             (False, ('A protection proxy, since it decides who may read the member', 'Um proxy de proteção, já que decide quem pode ler o membro'),
              ('Nothing is checked; everybody gets the member, just later.', 'Nada é conferido; todo mundo recebe o membro, só que depois.')),
             (False, ('A decorator, since it adds loading to the member', 'Um decorator, já que acrescenta carregamento ao membro'),
              ('Loading is access, not added behaviour the caller chose; the caller does not even know it is there.',
               'Carregar é acesso, não um comportamento escolhido por quem chama; quem chama nem sabe que ele está ali.')),
             (True, ('A virtual proxy, delaying the load until it is needed', 'Um proxy virtual, que adia a carga até ela ser necessária'),
              ('Right. It delays creating something expensive until it is used.', 'Isso. Ele adia criar algo caro até ser usado.')),
             (False, ('A remote proxy, because the database runs in another process', 'Um proxy remoto, porque o banco roda em outro processo'),
              ('The defining trait here is the delay, not where the data lives.',
               'O traço que define aqui é o adiamento, não onde os dados moram.')),
         ]),
    # ---- strategy-and-observer
    dict(id='ex-r4snx3gh', section='strategy-and-observer', type='quiz', difficulty='medium',
         prompt=('The committee wants a third rule: members who have waited longest on any list go first. What changes in strategy.py?',
                 'A comissão quer uma terceira regra: quem esperou mais em qualquer lista vai primeiro. O que muda em strategy.py?'),
         choices=[
             (True, ('A new class with an order method, handed to WaitingList', 'Uma classe nova com um método order, entregue a WaitingList'),
              ('Right. WaitingList delegates the decision and stays as it is.', 'Isso. WaitingList delega a decisão e fica como está.')),
             (False, ('An if inside WaitingList.queue that checks which rule is active',
                      'Um if dentro de WaitingList.queue que confere qual regra está ativa'),
              ('That puts the decision back in the context, which is what the strategy removed.',
               'Isso devolve a decisão ao contexto, que é o que a strategy removeu.')),
             (False, ('A subclass of WaitingList for each rule the committee tries',
                      'Uma subclasse de WaitingList para cada regra que a comissão tentar'),
              ('Then the rule could not change while the list lives, as ordering did in the run.',
               'Aí a regra não poderia mudar enquanto a lista existe, como ordering mudou na execução.')),
         ]),
    dict(id='ex-n3tcbaaf', section='strategy-and-observer', type='quiz', difficulty='medium',
         prompt=('In observer.py, ReservationAlert raises an exception. What happens to ReturnCount, subscribed after it?',
                 'Em observer.py, ReservationAlert levanta uma exceção. O que acontece com ReturnCount, inscrita depois dela?'),
         choices=[
             (False, ('It is told anyway, because each listener runs in its own thread',
                      'É avisada mesmo assim, porque cada ouvinte roda na sua própria thread'),
              ('give_back calls listeners one after another in the same thread.',
               'give_back chama os ouvintes um depois do outro, na mesma thread.')),
             (True, ('It is never told: the exception stops the loop', 'Nunca é avisada: a exceção interrompe o laço'),
              ('Right. Production code catches per listener, and then has to decide what a failed listener means.',
               'Isso. Código de produção captura por ouvinte, e depois precisa decidir o que um ouvinte que falhou significa.')),
             (False, ('ReturnsDesk unsubscribes the failing listener and carries on with the next',
                      'ReturnsDesk cancela a inscrição do ouvinte que falhou e segue para o próximo'),
              ('Nothing in give_back catches anything; that would have to be written.',
               'Nada em give_back captura coisa alguma; isso teria de ser escrito.')),
             (False, ('Python retries the alert until it succeeds, then tells the count',
                      'O Python tenta o aviso de novo até dar certo, e então avisa a contagem'),
              ('Python retries nothing on its own.', 'O Python não tenta nada de novo sozinho.')),
         ]),
    dict(id='ex-j9txgn3s', section='strategy-and-observer', type='quiz', difficulty='hard',
         prompt=('Reading ReturnsDesk.give_back, a new developer cannot tell that returns trigger reservation alerts. Is that a defect of this code?',
                 'Lendo ReturnsDesk.give_back, um desenvolvedor novo não consegue saber que devoluções disparam avisos de reserva. Isso é um defeito deste código?'),
         choices=[
             (False, ('Yes: the alert belongs inside give_back, where everybody can see it',
                      'Sim: o aviso pertence a give_back, onde todo mundo o vê'),
              ('Then the desk would grow a line for every reaction, which is what observer avoids.',
               'Aí o balcão ganharia uma linha para cada reação, que é o que o observer evita.')),
             (True, ('It is the known price of observer: the desk stops knowing what follows a return',
                     'É o preço conhecido do observer: o balcão deixa de saber o que vem depois de uma devolução'),
              ('Right. Decoupling the subject is the point and also the cost; the answer lives with whoever subscribed.',
               'Isso. Desacoplar o sujeito é o objetivo e também o custo; a resposta mora com quem se inscreveu.')),
             (False, ('Yes: the listeners should be passed to give_back on every call',
                      'Sim: os ouvintes deviam ser passados a give_back a cada chamada'),
              ('Every caller would then have to know every reaction, which moves the coupling rather than removing it.',
               'Aí todo chamador teria de conhecer todas as reações, o que muda o acoplamento de lugar sem removê-lo.')),
         ]),
    # ---- command-and-state
    dict(id='ex-qkp14whm', section='command-and-state', type='ordering', difficulty='medium',
         prompt=('Put the states of the copy in state.py in the order the run went through them.',
                 'Ponha os estados do exemplar de state.py na ordem em que a execução passou por eles.'),
         items=[('available', 'available'),
                ('on loan to Bia', 'on loan to Bia'),
                ('on loan to Bia, Caio waiting', 'on loan to Bia, Caio waiting'),
                ('on hold for Caio', 'on hold for Caio'),
                ('on loan to Caio', 'on loan to Caio')],
         trap=('Duda\'s requests changed nothing: a refusal leaves the state where it was.',
               'Os pedidos de Duda não mudaram nada: uma recusa deixa o estado onde estava.')),
    dict(id='ex-m4vzhc8z', section='command-and-state', type='quiz', difficulty='medium',
         prompt=('Why does Return set self.member inside execute rather than take it in its constructor?',
                 'Por que Return define self.member dentro de execute em vez de recebê-lo no construtor?'),
         choices=[
             (False, ('Commands are not allowed to take arguments in their constructors, by the pattern\'s rules',
                      'Comandos não podem receber argumentos no próprio construtor, por regra do padrão'),
              ('Lend takes three; Return takes two.', 'Lend recebe três; Return recebe dois.')),
             (True, ('Who had the book is known only once it runs; undo needs it',
                     'Só ao rodar ele sabe com quem estava o livro; o undo precisa disso'),
              ('Right. A command keeps whatever it needs to reverse itself.', 'Isso. Um comando guarda o que precisa para se reverter.')),
             (False, ('So that the desk can print the member in its history', 'Para o balcão imprimir o membro no histórico'),
              ('__str__ for Return prints only the title.', 'O __str__ de Return imprime só o título.')),
         ]),
    dict(id='ex-2ww3ap2e', section='command-and-state', type='quiz', difficulty='hard',
         prompt=('WaitingList holds an Ordering and Copy holds a state, both behind an interface. What tells the two patterns apart?',
                 'WaitingList guarda um Ordering e Copy guarda um estado, os dois atrás de uma interface. O que distingue os dois padrões?'),
         choices=[
             (False, ('State has three methods, while a strategy has exactly one method by definition',
                      'State tem três métodos, enquanto uma strategy tem exatamente um método, por definição'),
              ('A strategy may have several methods; the count is not the difference.',
               'Uma strategy pode ter vários métodos; a contagem não é a diferença.')),
             (False, ('A strategy may be a function, while a state is a class',
                      'Uma strategy pode ser uma função, e um state é uma classe'),
              ('A dictionary of transitions or a match can stand in for state classes; the lesson says so.',
               'Um dicionário de transições ou um match podem substituir as classes de estado; a lição diz isso.')),
             (True, ('Who replaces the object: a caller swaps a strategy, a state replaces itself',
                     'Quem troca o objeto: quem chama troca a strategy, o state se troca sozinho'),
              ('Right. Copy never has its state set from outside; WaitingList never changes its own ordering.',
               'Isso. Copy nunca tem o estado definido de fora; WaitingList nunca muda a própria ordenação.')),
         ]),
    # ---- template-method-and-iterator
    dict(id='ex-yyskrraj', section='template-method-and-iterator', type='quiz', difficulty='medium',
         prompt=('In template.py, which part of a report can a subclass not change?',
                 'Em template.py, que parte de um relatório uma subclasse não consegue mudar?'),
         choices=[
             (False, ('The footer', 'O rodapé'), ('OverdueReport overrides it.', 'OverdueReport o sobrescreve.')),
             (False, ('How each row is formatted, which only the base class decides',
                      'Como cada linha é formatada, que só a classe base decide'),
              ('format_row is a hook with a default; any subclass may override it.',
               'format_row é um gancho com padrão; qualquer subclasse pode sobrescrevê-lo.')),
             (True, ('The order in which render calls the steps, fixed by the base class',
                     'A ordem em que render chama os passos, fixada pela classe base'),
              ('Right. The base class owns the outline and calls the subclass\'s steps.',
               'Isso. A classe base é dona do roteiro e chama os passos da subclasse.')),
         ]),
    dict(id='ex-82fc5zc5', section='template-method-and-iterator', type='quiz', difficulty='medium',
         prompt=('Shelf.__iter__ contains a yield. What does that give the method?',
                 'Shelf.__iter__ contém um yield. O que isso dá ao método?'),
         choices=[
             (False, ('It makes the shelf return a list of every book', 'Faz a estante devolver uma lista de todos os livros'),
              ('Nothing is collected into a list; one pair is produced per request.',
               'Nada é juntado numa lista; um par é produzido por pedido.')),
             (True, ('Calling it now returns an iterator object, with __next__ already written for you',
                     'Chamá-lo passa a devolver um objeto iterador, com o __next__ já escrito por você'),
              ('Right. A generator is the GoF iterator that Python writes for you, what MarkWalker spells out.',
               'Isso. Um gerador é o iterator do GoF que o Python escreve por você, o que MarkWalker escreve por extenso.')),
             (False, ('It runs the loop on another thread, so the shelf stays responsive',
                      'Roda o laço em outra thread, para a estante continuar respondendo'),
              ('A generator runs in the caller\'s thread, a step at a time.',
               'Um gerador roda na thread de quem chama, um passo por vez.')),
             (False, ('It sorts the shelf marks, which a plain return would not', 'Ordena as classificações, o que um return simples não faria'),
              ('The sorting is done by MarkWalker; yield only hands out each pair.',
               'Quem ordena é MarkWalker; o yield só entrega cada par.')),
         ]),
    # ---- built-into-the-language
    dict(id='ex-6f5nd1v8', section='built-into-the-language', type='quiz', difficulty='medium',
         prompt=('What did Peter Norvig\'s 1996 talk find about the 23 patterns in Lisp and Dylan?',
                 'O que a palestra de Peter Norvig de 1996 concluiu sobre os 23 padrões em Lisp e Dylan?'),
         choices=[
             (False, ('That every one of them was wrong and should be abandoned', 'Que todos eles estavam errados e deviam ser abandonados'),
              ('He found many simpler or invisible there, not wrong; the ideas survive.',
               'Ele achou muitos mais simples ou invisíveis ali, não errados; as ideias sobrevivem.')),
             (True, ('That 16 were simpler or invisible there', 'Que 16 eram mais simples ou invisíveis ali'),
              ('Right. First-class functions, classes as objects and macros did their work.',
               'Isso. Funções de primeira classe, classes como objetos e macros faziam o trabalho deles.')),
             (False, ('That those languages needed more patterns than C++, being dynamic',
                      'Que essas linguagens precisavam de mais padrões que o C++, por serem dinâmicas'),
              ('The finding went the other way: features made patterns shrink.',
               'A conclusão foi a oposta: os recursos fizeram os padrões encolher.')),
         ]),
    dict(id='ex-eps1mhgc', section='built-into-the-language', type='multiple-choice', difficulty='hard',
         prompt=('Which of these patterns shrink to a language feature in Python? Choose all that apply.',
                 'Quais destes padrões encolhem para um recurso da linguagem em Python? Marque todos que se aplicam.'),
         choices=[
             (True, ('Strategy, as a function passed to sorted', 'Strategy, como uma função passada a sorted'),
              ('Right. key= has been the strategy pattern all along.', 'Isso. key= sempre foi o padrão strategy.')),
             (True, ('Iterator, as a generator with yield', 'Iterator, como um gerador com yield'),
              ('Right. yield writes the __next__ for you.', 'Isso. yield escreve o __next__ por você.')),
             (False, ('Facade, as a built-in keyword', 'Facade, como uma palavra-chave da linguagem'),
              ('Facade is about dividing responsibilities, and stays a class in every language.',
               'Facade trata de dividir responsabilidades, e continua sendo uma classe em toda linguagem.')),
             (True, ('Command with undo, as partial saved in a list', 'Command com desfazer, como partial guardado numa lista'),
              ('Right. vanish.py undid a loan with one saved function.', 'Isso. vanish.py desfez um empréstimo com uma função guardada.')),
         ]),
    # ---- drill
    dict(id='ex-nj295p3b', section='drill', type='matching', difficulty='medium',
         prompt=('Match each problem at the library to the pattern that answers it.',
                 'Associe cada problema da biblioteca ao padrão que o resolve.'),
         pairs=[
             (('The rule for who gets a reserved book changes every term', 'A regra de quem recebe um livro reservado muda todo semestre'),
              ('Strategy', 'Strategy')),
             (('The desk must undo its last actions', 'O balcão precisa desfazer as últimas ações'), ('Command', 'Command')),
             (('A copy must refuse a loan while it is held for somebody', 'Um exemplar precisa recusar empréstimo enquanto está guardado para alguém'),
              ('State', 'State')),
             (('A slow outside catalogue is asked the same question all day', 'Um catálogo externo lento recebe a mesma pergunta o dia todo'),
              ('Proxy', 'Proxy')),
         ],
         right_distractors=[('Singleton', 'Singleton')]),
    dict(id='ex-p6xfwvj0', section='drill', type='quiz', difficulty='hard',
         prompt=('A payment library returns its own Charge objects, and three screens need to start a loan with a fine paid first. Which pair of patterns fits?',
                 'Uma biblioteca de pagamentos devolve os próprios objetos Charge, e três telas precisam começar um empréstimo com a multa paga antes. Que par de padrões serve?'),
         choices=[
             (False, ('Two singletons, one for payments and one for loans', 'Dois singletons, um para pagamentos e um para empréstimos'),
              ('One instance each solves nothing here, and adds global state.',
               'Uma instância de cada não resolve nada aqui, e acrescenta estado global.')),
             (True, ('An adapter for the payment library and a facade for the three screens',
                     'Um adapter para a biblioteca de pagamentos e uma facade para as três telas'),
              ('Right. The adapter stops their model at the border; the facade gives the screens one door.',
               'Isso. O adapter para o modelo deles na fronteira; a facade dá uma porta às telas.')),
             (False, ('Observer and decorator', 'Observer e decorator'),
              ('Nothing needs announcing and nothing needs layering; the problems are a foreign model and a multi-step flow.',
               'Nada precisa ser anunciado nem empilhado; os problemas são um modelo estrangeiro e um fluxo de vários passos.')),
             (False, ('A builder for the Charge objects and an iterator over the screens',
                      'Um builder para os objetos Charge e um iterator sobre as telas'),
              ('Charges come built by the library; what is missing is translation and coordination.',
               'Os Charges já vêm prontos da biblioteca; o que falta é tradução e coordenação.')),
         ]),
    dict(id='ex-wpr483b0', section='drill', type='quiz', difficulty='hard',
         prompt=('A Go colleague says their service uses no strategy pattern, yet it sorts with sort.Slice(loans, func(i, j int) bool {...}). What is the fairest reply?',
                 'Uma colega de Go diz que o serviço dela não usa o padrão strategy, mas ordena com sort.Slice(loans, func(i, j int) bool {...}). Qual é a resposta mais justa?'),
         choices=[
             (True, ('The function passed in is a strategy; Go simply needs no class to hold it',
                     'A função passada é uma strategy; o Go só não precisa de uma classe para guardá-la'),
              ('Right. The idea survives the language: a decision separated from the code that uses it.',
               'Isso. A ideia sobrevive à linguagem: uma decisão separada do código que a usa.')),
             (False, ('She is right, because Go has no classes and so cannot have patterns',
                      'Ela tem razão, porque o Go não tem classes e por isso não pode ter padrões'),
              ('Patterns are shapes of a design, not classes; Go code is full of them.',
               'Padrões são formas de projeto, não classes; código Go está cheio deles.')),
             (False, ('It is a template method, since sort.Slice fixes the outline', 'É um template method, já que sort.Slice fixa o roteiro'),
              ('Template method fills steps by subclassing; here the step is passed in, which is strategy.',
               'Template method preenche passos por herança; aqui o passo é passado, o que é strategy.')),
         ]),
]
