"""Lesson 7: MVC, MVP and MVVM."""

EXERCISES = [
    # ---- separating-presentation
    dict(id='ex-nf4e906q', section='separating-presentation', type='quiz', difficulty='easy',
         prompt=('What do the three patterns of this lesson all do first?',
                 'O que os três padrões desta lição fazem primeiro, todos eles?'),
         choices=[
             (False, ('Create three folders: models, views and controllers', 'Criar três pastas: models, views e controllers'),
              ('Folders are a consequence some frameworks impose; a single file can follow the pattern.',
               'Pastas são uma consequência que alguns frameworks impõem; um único arquivo pode seguir o padrão.')),
             (True, ('Move the rules into a model that knows nothing of screens', 'Levar as regras para um modelo que não sabe nada de telas'),
              ('Right. Fowler calls it separated presentation, and every pattern here starts with it.',
               'Isso. Fowler chama de apresentação separada, e todo padrão daqui começa por ela.')),
             (False, ('Make the view observe the model and redraw itself when it changes', 'Fazer a view observar o modelo e se redesenhar quando ele muda'),
              ('That is MVC\'s particular move; MVP\'s view never sees the model at all.',
               'Esse é o movimento próprio do MVC; a view do MVP nem chega a ver o modelo.')),
             (False, ('Replace the keyboard with a web page', 'Trocar o teclado por uma página web'),
              ('The input device is one of the things that changes; the patterns let it change without touching the rules.',
               'O dispositivo de entrada é uma das coisas que mudam; os padrões deixam que ele mude sem mexer nas regras.')),
         ]),
    dict(id='ex-vathyp3f', section='separating-presentation', type='quiz', difficulty='medium',
         prompt=('The library raises the loan limit from two to five. In tangled.py plus a web page written later, what is the likely result?',
                 'A biblioteca sobe o limite de empréstimos de dois para cinco. Com tangled.py e uma página web escrita depois, qual é o resultado provável?'),
         choices=[
             (False, ('Both update together, because they run on the same machine', 'As duas se atualizam juntas, porque rodam na mesma máquina'),
              ('Running on one machine shares nothing; each has its own copy of the check.',
               'Rodar na mesma máquina não compartilha nada; cada uma tem sua cópia da verificação.')),
             (True, ('One copy of the check is changed and the other is missed', 'Uma cópia da verificação muda e a outra fica esquecida'),
              ('Right. The web page could not reuse the loop, so it copied the rule, and two copies drift.',
               'Isso. A página web não podia reaproveitar o laço, então copiou a regra, e duas cópias se desencontram.')),
             (False, ('The web page refuses to start until the terminal program is stopped', 'A página web se recusa a iniciar até o programa de terminal parar'),
              ('Nothing ties the two processes together; that is exactly why the rule ends up written twice.',
               'Nada amarra os dois processos; é justamente por isso que a regra acaba escrita duas vezes.')),
         ]),
    dict(id='ex-wf6fs3c9', section='separating-presentation', type='matching', difficulty='easy',
         prompt=('Match each change to the job of the program it touches.', 'Associe cada mudança à tarefa do programa que ela afeta.'),
         pairs=[
             (('A late return now costs 75 cents a day', 'Uma devolução atrasada passa a custar 75 centavos por dia'), ('the rules', 'as regras')),
             (('The shelf list moves into a table with two columns', 'A lista da estante vai para uma tabela de duas colunas'), ('the presentation', 'a apresentação')),
             (('The desk is used from a phone instead of a keyboard', 'O balcão passa a ser usado pelo celular em vez do teclado'), ('the input', 'a entrada')),
         ]),
    # ---- mvc
    dict(id='ex-qr10atav', section='mvc', type='ordering', difficulty='medium',
         prompt=('In mvc.py, the line lend B1 bia arrives. Put what happens in order.',
                 'Em mvc.py, chega a linha lend B1 bia. Ponha em ordem o que acontece.'),
         items=[('The controller calls desk.lend', 'O controller chama desk.lend'),
                ('The desk runs _changed', 'O balcão roda _changed'),
                ('The view prints the shelf line', 'A view imprime a linha da estante'),
                ('The controller has the view say when B1 is due', 'O controller manda a view dizer quando o B1 vence')],
         trap=('The controller does not draw the shelf: the view redraws inside the model\'s call, before lend returns.',
               'O controller não desenha a estante: a view se redesenha dentro da chamada ao modelo, antes de lend retornar.')),
    dict(id='ex-d3cfe941', section='mvc', type='quiz', difficulty='medium',
         prompt=('Why does the model in desk_model.py raise ValueError instead of printing a message?',
                 'Por que o modelo em desk_model.py lança ValueError em vez de imprimir uma mensagem?'),
         choices=[
             (False, ('Python forbids print inside a class method', 'O Python proíbe print dentro de um método de classe'),
              ('It does not; ShelfView.render prints from a method.', 'Não proíbe; ShelfView.render imprime de dentro de um método.')),
             (False, ('An exception is faster than writing to the terminal', 'Uma exceção é mais rápida que escrever no terminal'),
              ('Speed has nothing to do with it; the point is who decides what the person sees.',
               'Velocidade não tem nada a ver; a questão é quem decide o que a pessoa vê.')),
             (True, ('It cannot know where its words will be shown, or if they will be', 'Ele não tem como saber onde suas palavras vão aparecer, nem se vão'),
              ('Right. A terminal, a web page and a test each show a refusal differently, and the same model serves all three.',
               'Isso. Um terminal, uma página web e um teste mostram uma recusa de jeitos diferentes, e o mesmo modelo serve os três.')),
             (False, ('So that the program stops when a loan is refused', 'Para o programa parar quando um empréstimo é recusado'),
              ('The controller catches it and the desk carries on with the next line, as the transcript shows.',
               'O controller a captura e o balcão segue para a próxima linha, como a transcrição mostra.')),
         ]),
    dict(id='ex-hn8wj0rb', section='mvc', type='quiz', difficulty='hard',
         prompt=('A second view, a log that writes every change to a file, is added to mvc.py. What has to change in desk_model.py?',
                 'Uma segunda view, um log que grava cada mudança num arquivo, entra em mvc.py. O que precisa mudar em desk_model.py?'),
         choices=[
             (True, ('Nothing at all: the log subscribes, like ShelfView', 'Nada: o log se inscreve, como ShelfView'),
              ('Right. The desk calls whatever subscribed and does not know what it is.',
               'Isso. O balcão chama o que se inscreveu e não sabe o que é.')),
             (False, ('A call to the log inside lend and give_back', 'Uma chamada ao log dentro de lend e give_back'),
              ('That would make the model point at a view, which is the one arrow MVC never draws.',
               'Isso faria o modelo apontar para uma view, que é a única seta que o MVC nunca desenha.')),
             (False, ('A second list of watchers, one per kind of view', 'Uma segunda lista de observadores, uma por tipo de view'),
              ('One list holds any callable; the desk does not sort them by kind.',
               'Uma lista guarda qualquer função; o balcão não as separa por tipo.')),
             (False, ('An import of the log class, so the model can construct it', 'Um import da classe de log, para o modelo poder construí-la'),
              ('The model never builds its observers; the main block does the wiring.',
               'O modelo nunca constrói seus observadores; o bloco principal faz a montagem.')),
         ]),
    # ---- mvc-on-the-server
    dict(id='ex-dckpm8gs', section='mvc-on-the-server', type='quiz', difficulty='easy',
         prompt=('In web.py, which part plays the controller?', 'Em web.py, que parte faz o papel de controller?'),
         choices=[
             (False, ('shelf_page and message_page', 'shelf_page e message_page'),
              ('Those turn values into HTML; they are the views.', 'Essas transformam valores em HTML; são as views.')),
             (True, ('show_shelf and lend, reached through ROUTES', 'show_shelf e lend, que ROUTES alcança'),
              ('Right. Each reads the request, calls the model, and picks a view and a status.',
               'Isso. Cada uma lê a requisição, chama o modelo e escolhe uma view e um status.')),
             (False, ('The Desk class, because it decides whether to lend', 'A classe Desk, porque decide se empresta'),
              ('Deciding the rules is the model\'s job, on the server as on the terminal.',
               'Decidir as regras é tarefa do modelo, no servidor como no terminal.')),
         ]),
    dict(id='ex-gxps9ty7', section='mvc-on-the-server', type='quiz', difficulty='medium',
         prompt=('Why does web.py never call desk.subscribe?', 'Por que web.py nunca chama desk.subscribe?'),
         choices=[
             (False, ('WSGI applications are not allowed to hold Python objects between requests',
                      'Aplicações WSGI não podem guardar objetos Python entre requisições'),
              ('They can; the desk object itself survives between requests, which is how the shelf remembers the loan.',
               'Podem; o próprio objeto desk sobrevive entre requisições, e é assim que a estante lembra o empréstimo.')),
             (True, ('A page already sent cannot be redrawn by the server', 'Uma página já enviada não pode ser redesenhada pelo servidor'),
              ('Right. Each request renders from scratch; nothing is left to notify.',
               'Isso. Cada requisição renderiza do zero; não sobra nada para avisar.')),
             (False, ('The controllers are functions, and only classes may subscribe', 'Os controllers são funções, e só classes podem se inscrever'),
              ('subscribe takes any callable; ShelfView passed a bound method.',
               'subscribe aceita qualquer função; ShelfView passou um método.')),
             (False, ('The desk only notifies when it runs inside a terminal', 'O balcão só avisa quando roda num terminal'),
              ('The model knows nothing of terminals; it would call subscribers anywhere.',
               'O modelo não sabe nada de terminais; ele chamaria inscritos em qualquer lugar.')),
         ]),
    dict(id='ex-99v3e93n', section='mvc-on-the-server', type='numeric', difficulty='easy',
         prompt=('In the transcript of web.py, what HTTP status code did Caio\'s request for B1 receive?',
                 'Na transcrição de web.py, que código de status HTTP recebeu o pedido do Caio pelo B1?'),
         value=409, tolerance=0),
    # ---- mvp
    dict(id='ex-vbsqdbcn', section='mvp', type='quiz', difficulty='medium',
         prompt=('In mvp.py, which class decides that a late return is shown as R$ 2,00?',
                 'Em mvp.py, que classe decide que uma devolução atrasada aparece como R$ 2,00?'),
         choices=[
             (False, ('ConsoleView, because it is the class that prints', 'ConsoleView, porque é a classe que imprime'),
              ('ConsoleView prints the string it is given and formats nothing.', 'ConsoleView imprime a string que recebe e não formata nada.')),
             (False, ('Desk, because the fine is a rule of the library', 'Desk, porque a multa é uma regra da biblioteca'),
              ('The amount is a rule; how 200 cents looks is presentation, and the model hands back a number.',
               'O valor é uma regra; a aparência de 200 centavos é apresentação, e o modelo devolve um número.')),
             (True, ('DeskPresenter', 'DeskPresenter'),
              ('Right. It calls money() and picks the alarm flag; the view only displays.',
               'Isso. Ele chama money() e escolhe o alarme; a view só exibe.')),
         ]),
    dict(id='ex-900dv7rw', section='mvp', type='quiz', difficulty='hard',
         prompt=('A new rule for the screen: a member\'s name is shown in capitals in every message. Where does the test for it go, in the MVP version?',
                 'Uma regra nova para a tela: o nome do membro aparece em maiúsculas em toda mensagem. Onde fica o teste dela, na versão MVP?'),
         choices=[
             (False, ('In a test that runs mvp.py and searches its printed output', 'Num teste que roda mvp.py e procura na saída impressa'),
              ('That is the MVC-style test the pattern exists to avoid; the decision lives where a fake view can see it.',
               'Esse é o teste ao estilo MVC que o padrão existe para evitar; a decisão mora onde uma view falsa enxerga.')),
             (True, ('Beside the others in test_presenter.py, reading FakeView.messages', 'Junto dos outros em test_presenter.py, lendo FakeView.messages'),
              ('Right. Capitalising is a decision about what the person sees, so it is the presenter\'s and its fake view records it.',
               'Isso. Pôr em maiúsculas é decidir o que a pessoa vê, então é do presenter, e a view falsa grava.')),
             (False, ('In a test of ConsoleView, since the view prints the name', 'Num teste de ConsoleView, já que a view imprime o nome'),
              ('A passive view receives the finished text; if it capitalised, it would no longer be passive.',
               'Uma view passiva recebe o texto pronto; se ela pusesse em maiúsculas, deixaria de ser passiva.')),
             (False, ('In desk_model.py, since names belong to members', 'Em desk_model.py, já que nomes pertencem a membros'),
              ('Upper case is not a rule of the library; the model would then be deciding about screens.',
               'Maiúsculas não são regra da biblioteca; o modelo passaria a decidir sobre telas.')),
         ]),
    dict(id='ex-m3198c96', section='mvp', type='cloze', difficulty='easy',
         prompt=('In the form of MVP this lesson builds, Fowler\'s name for a view that only forwards events and shows what it is told is a ___ view.',
                 'Na forma de MVP que esta lição constrói, o nome de Fowler para uma view que só repassa eventos e mostra o que lhe mandam é ___ view.'),
         blanks=[dict(en=['passive'], pt=['passive', 'passiva'])]),
    # ---- mvvm
    dict(id='ex-n5a2ytv9', section='mvvm', type='quiz', difficulty='medium',
         prompt=('What is the difference between a presenter and a view-model, in this lesson\'s programs?',
                 'Qual é a diferença entre um presenter e um view-model, nos programas desta lição?'),
         choices=[
             (True, ('The presenter calls the view; the view-model does not know it exists', 'O presenter chama a view; o view-model não sabe que ela existe'),
              ('Right. A view-model only exposes properties, and bindings carry them to the screen.',
               'Isso. Um view-model só expõe propriedades, e os bindings as levam até a tela.')),
             (False, ('Only the presenter can be tested without a screen', 'Só o presenter pode ser testado sem tela'),
              ('The view-model is tested even more directly, with no fake view at all.',
               'O view-model se testa de forma ainda mais direta, sem view falsa nenhuma.')),
             (False, ('The view-model reads the model and the presenter does not', 'O view-model lê o modelo e o presenter não'),
              ('Both hold the model; DeskPresenter calls desk.lend just as LendViewModel does.',
               'Os dois guardam o modelo; DeskPresenter chama desk.lend como LendViewModel chama.')),
             (False, ('It is the same object, renamed by Microsoft for WPF', 'É o mesmo objeto, renomeado pela Microsoft para o WPF'),
              ('The arrows differ: one pushes into a view interface, the other is pulled by bindings.',
               'As setas são diferentes: um empurra para uma interface de view, o outro é puxado pelos bindings.')),
         ]),
    dict(id='ex-mfw2p7sj', section='mvvm', type='quiz', difficulty='hard',
         prompt=('In mvvm.py, typing B1 into the code box printed nothing at all. Why?',
                 'Em mvvm.py, digitar B1 na caixa de código não imprimiu nada. Por quê?'),
         choices=[
             (False, ('The code box was not bound to the view-model yet when the typing happened', 'A caixa de código ainda não estava ligada ao view-model quando a digitação aconteceu'),
              ('It was bound before anybody typed; the value did reach vm.code.', 'Ela foi ligada antes de qualquer digitação; o valor chegou a vm.code.')),
             (True, ('Nothing changed, so nothing was notified', 'Nada mudou, então ninguém foi avisado'),
              ('Right. With no member typed, the status stayed "type a code and a member", so Observable.set did nothing.',
               'Isso. Sem membro digitado, o status continuou "type a code and a member", então Observable.set não fez nada.')),
             (False, ('The view-model ignores the code until a member is typed', 'O view-model ignora o código até um membro ser digitado'),
              ('It recomputed at once; the result happened to be the same as before.',
               'Ele recalculou na hora; o resultado só calhou de ser igual ao anterior.')),
         ]),
    dict(id='ex-hn2c136a', section='mvvm', type='quiz', difficulty='medium',
         prompt=('Which cost of MVVM does the section name first?', 'Que custo do MVVM a seção cita primeiro?'),
         choices=[
             (False, ('Every widget needs a method in a view interface', 'Todo widget precisa de um método numa interface de view'),
              ('That is MVP\'s cost, the one bindings remove.', 'Esse é o custo do MVP, o que os bindings eliminam.')),
             (False, ('The model has to import the view-model', 'O modelo precisa importar o view-model'),
              ('The model imports nothing of the screen; the view-model subscribes to it.',
               'O modelo não importa nada da tela; o view-model é que se inscreve nele.')),
             (True, ('The flow of updates is hard to follow', 'O fluxo das atualizações é difícil de seguir'),
              ('Right. Why a button greyed out is answered by tracing subscriptions, not by reading one method.',
               'Isso. Por que um botão ficou cinza se responde seguindo inscrições, não lendo um método.')),
             (False, ('It needs a platform from Microsoft', 'Precisa de uma plataforma da Microsoft'),
              ('It began in WPF and lives in Android, Vue and Angular; mvvm.py runs on plain Python.',
               'Começou no WPF e vive no Android, no Vue e no Angular; mvvm.py roda em Python puro.')),
         ]),
    # ---- comparing
    dict(id='ex-x1zq3mrd', section='comparing', type='matching', difficulty='medium',
         prompt=('Match each pattern to who updates the screen.', 'Associe cada padrão a quem atualiza a tela.'),
         pairs=[
             (('MVC on the desktop', 'MVC no desktop'), ('the view, when the model notifies it', 'a view, quando o modelo a avisa')),
             (('MVC on the web', 'MVC na web'), ('the controller, rendering a view per request', 'o controller, renderizando uma view por requisição')),
             (('MVP', 'MVP'), ('the presenter, by calling the view', 'o presenter, chamando a view')),
             (('MVVM', 'MVVM'), ('the bindings, when a property changes', 'os bindings, quando uma propriedade muda')),
         ]),
    dict(id='ex-8m51pc34', section='comparing', type='quiz', difficulty='hard',
         prompt=('A class you have never seen exposes is_valid and error_text as properties, and nothing in it refers to any widget. Which pattern is it most likely part of?',
                 'Uma classe que você nunca viu expõe is_valid e error_text como propriedades, e nada nela se refere a widget nenhum. De que padrão ela provavelmente faz parte?'),
         choices=[
             (False, ('MVP, because it has no reference to the model', 'MVP, porque não guarda referência ao modelo'),
              ('A presenter would call the view, through methods like show_error; this class calls nobody.',
               'Um presenter chamaria a view, por métodos como show_error; esta classe não chama ninguém.')),
             (False, ('The original MVC, as its view', 'O MVC original, como a view'),
              ('A view draws; this class only holds state and knows no screen.', 'Uma view desenha; esta classe só guarda estado e não conhece tela.')),
             (True, ('MVVM, as a view-model', 'MVVM, como view-model'),
              ('Right. Properties for a screen to bind to, and no knowledge of the screen, is the shape of a view-model.',
               'Isso. Propriedades para uma tela se ligar, e nenhum conhecimento da tela, é a forma de um view-model.')),
         ]),
    dict(id='ex-hcddfytd', section='comparing', type='numeric', difficulty='easy',
         prompt=('In the comparing section, how many times does grep -c find the word print in desk_model.py?',
                 'Na seção de comparação, quantas vezes o grep -c encontra a palavra print em desk_model.py?'),
         value=0, tolerance=0, unit=('times', 'vezes')),
    # ---- choosing
    dict(id='ex-87w7f047', section='choosing', type='quiz', difficulty='medium',
         prompt=('You are writing a desk application in Tkinter, which has no data binding worth the name, and the screen logic needs tests. What does the section suggest?',
                 'Você está escrevendo um aplicativo de balcão em Tkinter, que não tem data binding digno do nome, e a lógica da tela precisa de testes. O que a seção sugere?'),
         choices=[
             (False, ('MVVM, after writing a binding library first', 'MVVM, depois de escrever primeiro uma biblioteca de binding'),
              ('Possible, and then the binding library is a framework you maintain; the section points the other way.',
               'Possível, e aí a biblioteca de binding vira um framework que você mantém; a seção aponta para o outro lado.')),
             (True, ('MVP, with a fake view in the tests', 'MVP, com uma view falsa nos testes'),
              ('Right. Two ordinary classes give testable screen logic where nothing binds.',
               'Isso. Duas classes comuns dão lógica de tela testável onde nada faz binding.')),
             (False, ('The web\'s MVC, with one route and one handler for each button on the form', 'O MVC da web, com uma rota e um handler para cada botão do formulário'),
              ('Routes answer HTTP requests; a desktop window has none.', 'Rotas respondem a requisições HTTP; uma janela de desktop não tem nenhuma.')),
         ]),
    dict(id='ex-9qbyj5z9', section='choosing', type='quiz', difficulty='medium',
         prompt=('When is tangled.py, with no separation at all, a reasonable design?',
                 'Quando tangled.py, sem separação nenhuma, é um projeto razoável?'),
         choices=[
             (False, ('Never: every program with output should separate presentation', 'Nunca: todo programa com saída deve separar a apresentação'),
              ('The section says the opposite for a script with one screen; separation before a second screen is speculation.',
               'A seção diz o contrário para um script de uma tela; separar antes de existir uma segunda tela é especulação.')),
             (False, ('When it is shorter than a hundred lines', 'Quando tem menos de cem linhas'),
              ('Size is not the test; a short script with two screens already pays the cost.',
               'Tamanho não é o critério; um script curto com duas telas já paga o custo.')),
             (True, ('While no second screen, test or redesign is actually coming', 'Enquanto nenhuma segunda tela, teste ou redesenho está de fato vindo'),
              ('Right. Those three are what the tangle costs, and until one is real it costs nothing.',
               'Isso. Esses três são o que o emaranhado custa, e enquanto nenhum é real ele não custa nada.')),
             (False, ('When the program runs only in a terminal', 'Quando o programa roda só num terminal'),
              ('mvc.py and mvp.py are terminal programs too, and earn their separation through tests.',
               'mvc.py e mvp.py também são programas de terminal, e ganham com a separação por causa dos testes.')),
         ]),
    # ---- drill
    dict(id='ex-esfw4rzw', section='drill', type='multiple-choice', difficulty='hard',
         prompt=('Which of these are screen logic rather than rules of the library? Choose all that apply.',
                 'Quais destes são lógica de tela, e não regras da biblioteca? Marque todos que se aplicam.'),
         choices=[
             (True, ('Showing 150 cents as R$ 1,50', 'Mostrar 150 centavos como R$ 1,50'),
              ('Right. The amount is the library\'s; the way it reads on screen is presentation.',
               'Isso. O valor é da biblioteca; o jeito como ele se lê na tela é apresentação.')),
             (False, ('A member may hold at most five loans', 'Um membro pode ter no máximo cinco empréstimos'),
              ('That is a rule, and it lives in Desk.lend whichever screen asks.', 'Isso é uma regra, e mora em Desk.lend seja qual for a tela que pergunte.')),
             (True, ('Greying out the Lend button while the member is at the limit', 'Deixar o botão Lend cinza enquanto o membro está no limite'),
              ('Right. The limit is a rule; what the button looks like because of it is screen logic, held by the view-model.',
               'Isso. O limite é uma regra; a aparência do botão por causa dele é lógica de tela, guardada pelo view-model.')),
             (False, ('A late return costs 50 cents a day', 'Uma devolução atrasada custa 50 centavos por dia'),
              ('A rule; give_back computes it and returns a number.', 'Uma regra; give_back a calcula e devolve um número.')),
             (True, ('Marking a refusal as an alarm', 'Marcar uma recusa como alarme'),
              ('Right. The presenter decides it; the refusal itself came from the model.',
               'Isso. O presenter decide isso; a recusa em si veio do modelo.')),
         ]),
    dict(id='ex-4x0wyzwv', section='drill', type='quiz', difficulty='hard',
         prompt=('A Django project\'s views.py functions each open the database, check the loan limit and build the reply. What is wrong, in this lesson\'s terms?',
                 'Num projeto Django, cada função de views.py abre o banco, confere o limite de empréstimos e monta a resposta. O que está errado, nos termos desta lição?'),
         choices=[
             (False, ('Django\'s views should be templates; the logic belongs in HTML', 'As views do Django deviam ser templates; a lógica pertence ao HTML'),
              ('Templates are the views of the table; putting the limit there would tangle it with the drawing instead.',
               'Templates são as views da tabela; pôr o limite ali o emaranharia com o desenho em vez disso.')),
             (True, ('The controllers are doing the model\'s work, so the rule cannot be reused', 'Os controllers fazem o trabalho do modelo, e a regra fica presa a eles'),
              ('Right. Django\'s views are controllers; the limit belongs in a model a script or a test could call.',
               'Isso. As views do Django são controllers; o limite pertence a um modelo que um script ou um teste conseguiria chamar.')),
             (False, ('Nothing: in Django the view is supposed to do everything', 'Nada: no Django a view deve fazer tudo'),
              ('Django calls them views, but the arrows are a controller\'s, and a controller should be three lines.',
               'O Django as chama de views, mas as setas são de controller, e um controller deveria ter três linhas.')),
             (False, ('It should be rewritten as MVVM, so that the screen binds straight to the database tables', 'Devia ser reescrito em MVVM, para a tela se ligar direto às tabelas do banco'),
              ('A server-rendered page has no live screen to bind; the fix is a thin controller over a model.',
               'Uma página renderizada no servidor não tem tela viva para ligar; a correção é um controller fino sobre um modelo.')),
         ]),
    dict(id='ex-3jxxs4r3', section='drill', type='cloze', difficulty='medium',
         prompt=('In all four programs of the lesson, the one file that never changed and never printed held the rules: it was the ___ .',
                 'Nos quatro programas da lição, o único arquivo que nunca mudou e nunca imprimiu guardava as regras: era o ___ .'),
         blanks=[dict(en=['model'], pt=['modelo', 'model'])]),
]
