"""Lesson 8: CQRS."""

EXERCISES = [
    # ---- one-model-strains
    dict(id='ex-qrgwy1c7', section='one-model-strains', type='quiz', difficulty='easy',
         prompt=('In strained.py, which data do the three command methods never read?',
                 'Em strained.py, que dados os três métodos de comando nunca leem?'),
         choices=[
             (False, ('holder, who has each copy and until when', 'holder, quem está com cada exemplar e até quando'),
              ('lend reads holder to refuse a copy that is out and to count a member\'s loans.',
               'lend lê holder para recusar um exemplar emprestado e contar os empréstimos de um membro.')),
             (True, ('titles: the names and authors', 'titles: os nomes e os autores'),
              ('Right. No rule needs a name; only the screens do, which is the first sign of two models in one class.',
               'Isso. Nenhuma regra precisa de nome; só as telas, e esse é o primeiro sinal de dois modelos numa classe.')),
             (False, ('waiting, the queue of members per title', 'waiting, a fila de membros por título'),
              ('The reservation rule reads it: a reserved title goes to the first member in the queue.',
               'A regra de reserva lê: um título reservado vai para o primeiro membro da fila.')),
         ]),
    dict(id='ex-72gbmyvv', section='one-model-strains', type='numeric', difficulty='medium',
         prompt=('The availability screen of strained.py visits every copy record once per title. With 40 titles and 100 copies, how many visits does one page view make?',
                 'A tela de disponibilidade de strained.py visita cada registro de exemplar uma vez por título. Com 40 títulos e 100 exemplares, quantas visitas faz uma exibição da página?'),
         value=4000, tolerance=0, unit=('visits', 'visitas')),
    dict(id='ex-5frhsews', section='one-model-strains', type='quiz', difficulty='medium',
         prompt=('The website wants "most borrowed this year". What happens to the single Library class?',
                 'O site quer "mais emprestados do ano". O que acontece com a classe Library única?'),
         choices=[
             (False, ('Nothing, because a query never changes a class', 'Nada, porque uma consulta nunca muda uma classe'),
              ('The query needs a counter that something must keep, and the only place loans happen is lend.',
               'A consulta precisa de um contador que alguém mantenha, e o único lugar onde empréstimos acontecem é lend.')),
             (True, ('lend gains a counter that no rule reads', 'lend ganha um contador que nenhuma regra lê'),
              ('Right. The rule method starts carrying screen data, which is the widening the section describes.',
               'Isso. O método de regra passa a carregar dado de tela, que é o alargamento que a seção descreve.')),
             (False, ('The class has to be split into one class per screen before the count can be kept anywhere',
                      'A classe precisa ser dividida numa classe por tela antes que a contagem possa ficar em algum lugar'),
              ('It can be kept in the one class, and usually is at first; the cost is that the class widens.',
               'Ela pode ficar na classe única, e no começo costuma ficar; o custo é a classe alargar.')),
         ]),
    # ---- cqs
    dict(id='ex-6pzjpqmt', section='cqs', type='quiz', difficulty='medium',
         prompt=('In cqs.py, why did the first shelf lend C2 instead of C1?',
                 'Em cqs.py, por que a primeira estante emprestou o C2 em vez do C1?'),
         choices=[
             (True, ('The debugging line called take, which removed C1', 'A linha de depuração chamou take, que removeu o C1'),
              ('Right. Asking a question that is also a command performs the command.',
               'Isso. Fazer uma pergunta que também é um comando executa o comando.')),
             (False, ('The list was sorted in reverse by pop', 'A lista foi ordenada ao contrário pelo pop'),
              ('pop(0) takes from the front and sorts nothing; C1 was simply gone already.',
               'pop(0) tira da frente e não ordena nada; o C1 só já tinha saído.')),
             (False, ('print runs its arguments twice', 'print avalia os argumentos duas vezes'),
              ('print evaluates each argument once; once was enough to take a copy.',
               'print avalia cada argumento uma vez; uma vez bastou para levar um exemplar.')),
         ]),
    dict(id='ex-t3e4mqke', section='cqs', type='cloze', difficulty='easy',
         prompt=('Meyer\'s rule: a method is either a command, which changes state, or a ___, which only answers.',
                 'A regra de Meyer: um método ou é um comando, que muda o estado, ou é uma ___, que só responde.'),
         blanks=[dict(en=['query'], pt=['consulta', 'query'])]),
    dict(id='ex-6rra7b77', section='cqs', type='quiz', difficulty='hard',
         prompt=('Two requests run if shelf.next_copy() == "C1": shelf.remove("C1") at the same moment. What is the right design?',
                 'Duas requisições rodam if shelf.next_copy() == "C1": shelf.remove("C1") no mesmo instante. Qual é o projeto certo?'),
         choices=[
             (False, ('Keep the two calls, as the rule asks', 'Manter as duas chamadas, como a regra pede'),
              ('Both requests can see C1 free between the two calls; the rule bends exactly here.',
               'As duas requisições podem ver o C1 livre entre as duas chamadas; a regra se dobra exatamente aqui.')),
             (True, ('One atomic method that takes the copy and returns it', 'Um método atômico que pega o exemplar e o devolve'),
              ('Right. When answer and change must happen together, combining them is correct, as with LoadOrStore or INSERT … RETURNING.',
               'Isso. Quando resposta e mudança precisam acontecer juntas, combiná-las é o certo, como em LoadOrStore ou INSERT … RETURNING.')),
             (False, ('Call next_copy twice before removing, to be sure', 'Chamar next_copy duas vezes antes de remover, para ter certeza'),
              ('Asking twice narrows nothing; the other request can still act between the last question and the removal.',
               'Perguntar duas vezes não estreita nada; a outra requisição ainda pode agir entre a última pergunta e a remoção.')),
             (False, ('Log every call to remove so the double loan can be undone', 'Registrar toda chamada a remove para o empréstimo duplo poder ser desfeito'),
              ('A log finds the problem afterwards; the design should make it impossible.',
               'Um log acha o problema depois; o projeto deveria torná-lo impossível.')),
         ]),
    # ---- the-split
    dict(id='ex-tz0nd6jx', section='the-split', type='quiz', difficulty='easy',
         prompt=('Which of these does CQRS itself require?', 'Qual destes o CQRS em si exige?'),
         choices=[
             (False, ('Two databases and a message bus between them', 'Dois bancos de dados e um barramento de mensagens entre eles'),
              ('Those are one way to place the models; the smallest version runs in one process on one file.',
               'Esses são um jeito de posicionar os modelos; a versão menor roda num processo sobre um arquivo.')),
             (False, ('Event sourcing on the write side', 'Event sourcing no lado da escrita'),
              ('Often paired with it, never required; lesson 9 is a separate decision.', 'Muitas vezes vem junto, nunca é exigido; a lição 9 é uma decisão separada.')),
             (True, ('One model for commands and another for queries', 'Um modelo para comandos e outro para consultas'),
              ('Right. Where they live and how the second is kept current are further choices.',
               'Isso. Onde eles moram e como o segundo é mantido em dia são escolhas a mais.')),
         ]),
    dict(id='ex-p7j2947v', section='the-split', type='quiz', difficulty='medium',
         prompt=('Why is it acceptable to copy the author\'s name into every row of the read model?',
                 'Por que é aceitável copiar o nome do autor em toda linha do modelo de leitura?'),
         choices=[
             (False, ('SQLite stores repeated text only once, so nothing is really duplicated', 'O SQLite guarda texto repetido uma vez só, então nada é duplicado de fato'),
              ('It stores each row\'s value; the duplication is real and deliberate.', 'Ele guarda o valor de cada linha; a duplicação é real e deliberada.')),
             (True, ('The read model is derived, so a drift is repaired by rebuilding it', 'É um dado derivado, e um desencontro se conserta reconstruindo'),
              ('Right. Nothing the library knows lives only there.', 'Isso. Nada do que a biblioteca sabe mora só ali.')),
             (False, ('Authors rarely change their names', 'Autores raramente mudam de nome'),
              ('Rarely is not never, and titles get corrected; the copy is safe because it can be recomputed, not because it stays put.',
               'Podem mudar, e títulos são corrigidos; a cópia é segura porque pode ser recalculada, não porque nunca muda.')),
             (False, ('Normalisation is a rule for write models in Python, not for read models', 'Normalização é regra para modelos de escrita em Python, não para os de leitura'),
              ('Language has nothing to do with it; the difference is between source data and derived data.',
               'A linguagem não tem nada a ver; a diferença é entre dado de origem e dado derivado.')),
         ]),
    dict(id='ex-ksgyz5k3', section='the-split', type='ordering', difficulty='medium',
         prompt=('Put the three levels of separation in order, from the least to the most separated.',
                 'Ponha os três níveis de separação em ordem, do menos ao mais separado.'),
         items=[('Separate code over the same tables', 'Código separado sobre as mesmas tabelas'),
                ('Separate read tables, updated in the same transaction', 'Tabelas de leitura separadas, atualizadas na mesma transação'),
                ('A separate store, updated after the write commits', 'Um armazenamento separado, atualizado depois que a escrita é confirmada')],
         trap=('Staleness appears only at the third level; the second already has its own tables and is never stale.',
               'A desatualização só aparece no terceiro nível; o segundo já tem tabelas próprias e nunca está desatualizado.')),
    # ---- commands-and-handlers
    dict(id='ex-84aj2w5k', section='commands-and-handlers', type='matching', difficulty='easy',
         prompt=('Match each name from commands.py to what it is.', 'Associe cada nome de commands.py ao que ele é.'),
         pairs=[
             (('LendCopy', 'LendCopy'), ('a command: a request that may be refused', 'um comando: um pedido que pode ser recusado')),
             (('CopyLent', 'CopyLent'), ('an event: a fact that is already true', 'um evento: um fato que já é verdade')),
             (('Lending.lend', 'Lending.lend'), ('a handler: checks the rules and makes the change', 'um handler: confere as regras e faz a mudança')),
             (('HANDLERS', 'HANDLERS'), ('the dispatch from a command\'s type to its handler', 'o despacho do tipo de um comando para o seu handler')),
         ]),
    dict(id='ex-d6kqxcwj', section='commands-and-handlers', type='quiz', difficulty='medium',
         prompt=('Dani\'s LendCopy is refused. What do the listeners receive?',
                 'O LendCopy da Dani é recusado. O que os ouvintes recebem?'),
         choices=[
             (False, ('A CopyLent with member set to None', 'Um CopyLent com member igual a None'),
              ('No event is built at all: the refusal raises before the change and before _publish.',
               'Nenhum evento chega a ser criado: a recusa é lançada antes da mudança e antes de _publish.')),
             (True, ('Nothing', 'Nada'),
              ('Right. A refused command changes nothing and tells nobody.', 'Isso. Um comando recusado não muda nada e não conta nada a ninguém.')),
             (False, ('An event named LendRefused, so the screens can show it', 'Um evento chamado LendRefused, para as telas mostrarem'),
              ('commands.py defines no such event; the refusal reaches only the caller, as an exception.',
               'commands.py não define esse evento; a recusa chega só a quem chamou, como exceção.')),
         ]),
    dict(id='ex-3j6h5qed', section='commands-and-handlers', type='quiz', difficulty='hard',
         prompt=('A new rule: a member with an unpaid fine cannot borrow. In the split version, where does the change go?',
                 'Uma regra nova: um membro com multa em aberto não pode pegar livros. Na versão dividida, onde fica a mudança?'),
         choices=[
             (False, ('Into Availability, which hides copies from that member', 'Em Availability, que esconde exemplares desse membro'),
              ('A read model must never enforce a rule; it may be stale and it is not consulted by the handler.',
               'Um modelo de leitura nunca deve aplicar uma regra; ele pode estar desatualizado e o handler não o consulta.')),
             (False, ('Into every screen that offers a Lend button', 'Em toda tela que oferece um botão Lend'),
              ('Screens may grey out a button, and a client that skips the screen would still borrow.',
               'Telas podem deixar um botão cinza, e um cliente que pule a tela ainda pegaria o livro.')),
             (True, ('Into Lending.lend and its tests, with what it needs to know about fines', 'Em Lending.lend e nos testes dele, com o que ele precisa saber de multas'),
              ('Right. Rules live on the write side, and no screen\'s code is near the change.',
               'Isso. Regras moram no lado da escrita, e o código de nenhuma tela fica perto da mudança.')),
         ]),
    # ---- read-models
    dict(id='ex-kjh21kj1', section='read-models', type='quiz', difficulty='medium',
         prompt=('Why does CopyLent carry was_reserved?', 'Por que CopyLent carrega was_reserved?'),
         choices=[
             (True, ('So the waiting count drops without reading the queue', 'Para a contagem de espera poder descer sem ler a fila'),
              ('Right. A read model can show only what the events say, and the queue lives on the write side.',
               'Isso. Um modelo de leitura só mostra o que os eventos dizem, e a fila mora no lado da escrita.')),
             (False, ('Because Lending uses it later to decide the next loan', 'Porque Lending o usa depois para decidir o próximo empréstimo'),
              ('Lending has the queue itself; the field exists for readers.', 'Lending tem a própria fila; o campo existe para os leitores.')),
             (False, ('Because a frozen dataclass needs at least five fields', 'Porque uma dataclass congelada precisa de pelo menos cinco campos'),
              ('A frozen dataclass can have any number of fields, including none.', 'Uma dataclass congelada pode ter qualquer número de campos, inclusive nenhum.')),
             (False, ('To let the projector call Lending and ask about the queue', 'Para o projetor poder chamar Lending e perguntar pela fila'),
              ('That call is exactly what the field avoids; a projector reading the write model rebuilds the coupling.',
               'Essa chamada é justamente o que o campo evita; um projetor que lê o modelo de escrita reconstrói o acoplamento.')),
         ]),
    dict(id='ex-r1a0w89j', section='read-models', type='quiz', difficulty='medium',
         prompt=('A third screen, "most borrowed this year", is wanted. What changes in Lending?',
                 'Quer-se uma terceira tela, "mais emprestados do ano". O que muda em Lending?'),
         choices=[
             (False, ('A counter in lend, as in the strained class', 'Um contador em lend, como na classe tensionada'),
              ('That was the cost before the split; now a projector counts the CopyLent events.',
               'Esse era o custo antes da divisão; agora um projetor conta os eventos CopyLent.')),
             (False, ('A new event, BookPopular, published on every tenth loan of a title',
                      'Um evento novo, BookPopular, publicado a cada décimo empréstimo de um título'),
              ('Popularity is a reading of loans, not a fact the rules decide; CopyLent already says everything needed.',
               'Popularidade é uma leitura dos empréstimos, não um fato que as regras decidem; CopyLent já diz tudo o que precisa.')),
             (True, ('Nothing; a new projector counts CopyLent', 'Nada; um projetor novo conta CopyLent'),
              ('Right. A new read model is added without touching the write side.', 'Isso. Um modelo de leitura novo entra sem tocar no lado da escrita.')),
         ]),
    dict(id='ex-dk9fgbzj', section='read-models', type='numeric', difficulty='easy',
         prompt=('In the last line of the read_model.py transcript, what is the waiting count for T2 after Dani borrows the copy?',
                 'Na última linha da transcrição de read_model.py, qual é a contagem de espera do T2 depois que a Dani leva o exemplar?'),
         value=0, tolerance=0),
    # ---- sync-and-async-projection
    dict(id='ex-whqxzb5q', section='sync-and-async-projection', type='quiz', difficulty='medium',
         prompt=('In the asynchronous run of lag.py, the screen says 2 copies while both are out. Can the desk lend C2 a second time?',
                 'Na execução assíncrona de lag.py, a tela diz 2 exemplares enquanto os dois estão emprestados. O balcão consegue emprestar o C2 uma segunda vez?'),
         choices=[
             (False, ('Yes, because the screen is what the desk trusts when it decides to lend', 'Sim, porque a tela é aquilo em que o balcão confia na hora de emprestar'),
              ('The desk may be misled, but the command goes to Lending, which knew at once.',
               'O balcão pode ser enganado, mas o comando vai para Lending, que soube na hora.')),
             (True, ('No: Lending refuses, because the rule reads the write model', 'Não: Lending recusa, porque a regra lê o modelo de escrita'),
              ('Right. Stale reads waste trips; they break nothing as long as no rule reads a read model.',
               'Isso. Leituras desatualizadas fazem perder viagens; não quebram nada enquanto nenhuma regra ler um modelo de leitura.')),
             (False, ('Only if the worker runs between the two loans', 'Só se o worker rodar entre os dois empréstimos'),
              ('The worker affects only the screen; the refusal does not depend on it.', 'O worker só afeta a tela; a recusa não depende dele.')),
             (False, ('It depends on how many events are queued in the outbox', 'Depende de quantos eventos estão na fila de saída'),
              ('The outbox feeds the read model and is never consulted by a handler.', 'A fila de saída alimenta o modelo de leitura e nunca é consultada por um handler.')),
         ]),
    dict(id='ex-vkqrpa7b', section='sync-and-async-projection', type='matching', difficulty='hard',
         prompt=('Bia borrows a book and the next page does not show it. Match each remedy to how it works.',
                 'A Bia pega um livro e a página seguinte não o mostra. Associe cada remédio a como ele funciona.'),
         pairs=[
             (('Show the command\'s result', 'Mostrar o resultado do comando'), ('the screen prints what it sent, and refreshes later', 'a tela imprime o que mandou, e atualiza depois')),
             (('Wait for the position', 'Esperar pela posição'), ('the screen waits until the projection has applied the event count it was given', 'a tela espera a projeção aplicar a contagem de eventos que recebeu')),
             (('Project synchronously for one screen', 'Projetar de forma síncrona para uma tela'), ('her own loans are updated inside the command', 'os empréstimos dela são atualizados dentro do comando')),
         ]),
    dict(id='ex-8s25fbyk', section='sync-and-async-projection', type='quiz', difficulty='hard',
         prompt=('A search index of all loans takes seconds to update and sometimes goes down. How should it be projected?',
                 'Um índice de busca de todos os empréstimos leva segundos para atualizar e às vezes cai. Como ele deve ser projetado?'),
         choices=[
             (True, ('Asynchronously, so writes do not wait for it or fail with it', 'Assíncrona, para as escritas não esperarem nem falharem junto com ele'),
              ('Right. A slow or fragile read model is the case for running the projection later.',
               'Isso. Um modelo de leitura lento ou frágil é o caso para rodar a projeção depois.')),
             (False, ('Synchronously, so that it stays current', 'De forma síncrona, para ficar em dia a cada escrita'),
              ('Then every loan waits seconds and fails whenever the index is down.', 'Aí todo empréstimo espera segundos e falha sempre que o índice cai.')),
             (False, ('Neither: the handler should query the write model for searches', 'Nem um nem outro: o handler devia consultar o modelo de escrita nas buscas'),
              ('That puts the screens back into the write model, the strain the lesson started from.',
               'Isso devolve as telas ao modelo de escrita, a tensão de onde a lição partiu.')),
         ]),
    # ---- when-not-to
    dict(id='ex-vwmve4hn', section='when-not-to', type='quiz', difficulty='medium',
         prompt=('Which of these is the clearest case for leaving CQRS out?', 'Qual destes é o caso mais claro para deixar o CQRS de fora?'),
         choices=[
             (False, ('A screen that reads facts in a shape the rules never use', 'Uma tela que lê fatos numa forma que as regras nunca usam'),
              ('That is one of the signs for it.', 'Esse é um dos sinais a favor.')),
             (True, ('A profile page that edits a record and then shows that same record', 'Uma página de perfil que edita um registro e depois mostra esse mesmo registro'),
              ('Right. Both models would have the same shape, so the split doubles the code for nothing.',
               'Isso. Os dois modelos teriam a mesma forma, então a divisão dobra o código à toa.')),
             (False, ('A catalogue read thousands of times for every loan', 'Um catálogo lido milhares de vezes para cada empréstimo'),
              ('Reads far outnumbering writes, and scaling apart, is a reason to split.', 'Leituras muito mais numerosas que escritas, escalando à parte, é motivo para dividir.')),
             (False, ('Several screens wanting the same loans, each in a different shape of its own', 'Várias telas querendo os mesmos empréstimos, cada uma numa forma diferente e só sua'),
              ('That is Availability and MemberLoans, the case the read models were built for.',
               'Esse é o caso de Availability e MemberLoans, para o qual os modelos de leitura foram feitos.')),
         ]),
    dict(id='ex-447dy49s', section='when-not-to', type='numeric', difficulty='easy',
         prompt=('From the wc -l transcript, how many lines do commands.py and read_model.py have together?',
                 'Pela transcrição do wc -l, quantas linhas commands.py e read_model.py têm juntos?'),
         value=183, tolerance=0, unit=('lines', 'linhas')),
    # ---- drill
    dict(id='ex-yhnr3e7b', section='drill', type='multiple-choice', difficulty='hard',
         prompt=('Which of these break the lesson\'s rules? Choose all that apply.',
                 'Quais destes quebram as regras da lição? Marque todos que se aplicam.'),
         choices=[
             (True, ('A handler that checks availability by querying the read model', 'Um handler que confere a disponibilidade consultando o modelo de leitura'),
              ('Right. A rule reading a possibly stale model turns lag into a correctness bug.',
               'Isso. Uma regra que lê um modelo possivelmente desatualizado transforma atraso em bug de correção.')),
             (True, ('A projector that calls Lending to find out who was waiting', 'Um projetor que chama Lending para descobrir quem estava esperando'),
              ('Right. If a reader needs the fact, the event should carry it.', 'Isso. Se um leitor precisa do fato, o evento deveria carregá-lo.')),
             (False, ('A read model that repeats the author in every row', 'Um modelo de leitura que repete o autor em toda linha'),
              ('That is normal: read models are derived and denormalised on purpose.', 'Isso é normal: modelos de leitura são derivados e desnormalizados de propósito.')),
             (False, ('A command that returns the id of the loan it created', 'Um comando que devolve o id do empréstimo que criou'),
              ('A bend the cqs section allows; returning the next screen is what it forbids.',
               'Uma dobra que a seção de cqs permite; devolver a próxima tela é o que ela proíbe.')),
             (True, ('A method that both returns the next copy and removes it, used in a debug print', 'Um método que devolve o próximo exemplar e o remove, usado num print de depuração'),
              ('Right. That is take from cqs.py, and the print lent a book.', 'Isso. É o take de cqs.py, e o print emprestou um livro.')),
         ]),
    dict(id='ex-qsgrbamq', section='drill', type='ordering', difficulty='medium',
         prompt=('Bia lends a copy in the asynchronous arrangement. Put the steps in order.',
                 'A Bia empresta um exemplar no arranjo assíncrono. Ponha os passos em ordem.'),
         items=[('handle passes LendCopy to Lending.lend', 'handle passa LendCopy para Lending.lend'),
                ('Lending checks the rules and records the loan', 'Lending confere as regras e registra o empréstimo'),
                ('CopyLent is appended to the outbox', 'CopyLent é acrescentado à fila de saída'),
                ('The worker applies CopyLent to the availability table', 'O worker aplica CopyLent à tabela de disponibilidade')],
         trap=('The event is published only after the rules pass and the change is made; the read model is last.',
               'O evento só é publicado depois que as regras passam e a mudança é feita; o modelo de leitura vem por último.')),
    dict(id='ex-y02czhnf', section='drill', type='quiz', difficulty='hard',
         prompt=('A team adds CQRS with asynchronous projection to a small admin app whose screens each edit one record. What should they expect?',
                 'Uma equipe põe CQRS com projeção assíncrona num pequeno app administrativo em que cada tela edita um registro. O que ela deve esperar?'),
         choices=[
             (False, ('Faster screens, since each read now comes from a table built for that one screen', 'Telas mais rápidas, já que cada leitura agora vem de uma tabela feita para aquela tela específica'),
              ('The reads were already of one record; a table per screen of the same shape buys no speed.',
               'As leituras já eram de um registro; uma tabela por tela com a mesma forma não compra velocidade.')),
             (True, ('More code, and edits that vanish from the screen for a moment after saving', 'Mais código, e edições que somem da tela por um instante depois de salvar'),
              ('Right. They pay for events, projectors and the stale window, and get nothing back on screens that mirror their writes.',
               'Isso. Pagam por eventos, projetores e a janela de atraso, e não ganham nada em telas que espelham as escritas.')),
             (False, ('No real change, since CQRS is a naming convention', 'Pouca coisa muda, já que CQRS é uma convenção de nomes'),
              ('It is two models and the machinery between them; the costs are real.', 'São dois modelos e a maquinaria entre eles; os custos são reais.')),
         ]),
]
