"""Lesson 10: ACID and the CAP theorem."""

EXERCISES = [
    # ---- acid
    dict(id='ex-fe7nszmh', section='acid', type='quiz', difficulty='easy',
         prompt=('In reserve.py, why did move_hold leave Bia with no place in the queue?',
                 'Em reserve.py, por que move_hold deixou Bia sem lugar na fila?'),
         choices=[
             (False, ('The foreign key deleted her hold when the insert named a member who does not exist',
                      'A chave estrangeira apagou a reserva dela quando o insert citou um sócio que não existe'),
              ('A foreign key refuses the bad row; it deleted nothing. The delete was the program\'s own statement.',
               'Uma chave estrangeira recusa a linha ruim; ela não apagou nada. O delete era um comando do próprio programa.')),
             (True, ('The delete was committed before the insert failed', 'O delete já estava gravado quando o insert falhou'),
              ('Right. With no transaction around them, each statement is committed on its own, so the failure could only undo itself.',
               'Isso. Sem transação em volta, cada comando é gravado sozinho, então a falha só conseguia desfazer a si mesma.')),
             (False, ('SQLite does not support transactions in a database held in memory', 'O SQLite não suporta transações num banco em memória'),
              ('It does: move_hold_atomically ran against the same kind of database and rolled back.',
               'Suporta: move_hold_atomically rodou no mesmo tipo de banco e desfez tudo.')),
             (False, ('The CHECK on place refused her place number', 'O CHECK de place recusou o número do lugar dela'),
              ('Her place was 1, which the CHECK accepts; the error printed was about the foreign key.',
               'O lugar dela era 1, que o CHECK aceita; o erro impresso foi o da chave estrangeira.')),
         ]),
    dict(id='ex-sz4yxnqa', section='acid', type='matching', difficulty='medium',
         prompt=('Match each ACID letter to where the section finds it, or misses it, in reserve.py.',
                 'Associe cada letra do ACID a onde a seção a encontra, ou não, em reserve.py.'),
         pairs=[
             (('Atomicity', 'Atomicidade'), ('ROLLBACK put the delete back', 'o ROLLBACK devolveu o delete')),
             (('Consistency', 'Consistência'), ('the foreign key refused m-009', 'a chave estrangeira recusou m-009')),
             (('Durability', 'Durabilidade'), ('absent, because the database lives in memory', 'ausente, porque o banco vive na memória')),
             (('Isolation', 'Isolamento'), ('not shown until the next section', 'só aparece na próxima seção')),
         ]),
    dict(id='ex-fd22yh02', section='acid', type='quiz', difficulty='hard',
         prompt=('A Go function calls db.Exec("BEGIN"), then the delete and the insert, then db.Exec("COMMIT"), all on a *sql.DB. What is wrong?',
                 'Uma função em Go chama db.Exec("BEGIN"), depois o delete e o insert, depois db.Exec("COMMIT"), tudo num *sql.DB. O que está errado?'),
         choices=[
             (False, ('Nothing; database/sql notices the BEGIN and keeps the following calls inside it',
                      'Nada; o database/sql percebe o BEGIN e mantém as chamadas seguintes dentro dele'),
              ('It does not parse your SQL; it hands each call whatever connection the pool has free.',
               'Ele não lê o seu SQL; entrega a cada chamada a conexão que o pool tiver livre.')),
             (True, ('Each call gets whichever pooled connection is free, outside the transaction',
                     'Cada chamada pega a conexão livre do pool, fora da transação'),
              ('Right. A transaction belongs to one connection, which is why BeginTx returns a Tx to run the statements on.',
               'Isso. Uma transação pertence a uma conexão, e é por isso que BeginTx devolve um Tx para rodar os comandos.')),
             (False, ('Go has no way to run BEGIN as SQL', 'O Go não tem como rodar BEGIN como SQL'),
              ('Exec will send it; the problem is which connection receives it and which receives the next call.',
               'O Exec envia; o problema é qual conexão recebe e qual recebe a chamada seguinte.')),
         ]),
    # ---- isolation
    dict(id='ex-bydsxajq', section='isolation', type='quiz', difficulty='medium',
         prompt=('The first run of desks.py ends with available=0 and loans=2. What happened?',
                 'A primeira execução de desks.py termina com available=0 e loans=2. O que aconteceu?'),
         choices=[
             (True, ('Desk B wrote a count worked out from a value desk A had already changed',
                     'O balcão B gravou uma contagem calculada a partir de um valor que o balcão A já tinha mudado'),
              ('Right. Both read 1 and both wrote 1 - 1; the second write replaced the first. That is the lost update.',
               'Isso. Os dois leram 1 e os dois gravaram 1 - 1; a segunda gravação substituiu a primeira. É a atualização perdida.')),
             (False, ('SQLite dropped desk A\'s UPDATE because two connections wrote at once',
                      'O SQLite descartou o UPDATE do balcão A porque duas conexões gravaram ao mesmo tempo'),
              ('Both UPDATEs ran in turn, in one thread. Nothing was dropped; desk B simply wrote the same 0.',
               'Os dois UPDATE rodaram um depois do outro, numa thread. Nada foi descartado; o balcão B só gravou o mesmo 0.')),
             (False, ('An insert into loans failed silently', 'Um insert em loans falhou em silêncio'),
              ('Both inserts succeeded; that is why there are two loans.', 'Os dois inserts deram certo; é por isso que há dois empréstimos.')),
         ]),
    dict(id='ex-1rvp82bn', section='isolation', type='numeric', difficulty='medium',
         prompt=('Three desks follow the no_transaction pattern on a title with 2 copies: all three read first, then each writes seen - 1 and records a loan. What does available say at the end?',
                 'Três balcões seguem o padrão de no_transaction num título com 2 exemplares: os três leem primeiro, depois cada um grava seen - 1 e registra um empréstimo. Quanto diz available no fim?'),
         hint=('Every desk saw the same number.', 'Todo balcão viu o mesmo número.'),
         value=1, tolerance=0, unit=('copies', 'exemplares')),
    dict(id='ex-hetp26ba', section='isolation', type='quiz', difficulty='hard',
         prompt=('The lend of desks.py, read then write, runs inside one transaction on a PostgreSQL left at its default level. Two desks overlap. What happens?',
                 'O lend de desks.py, ler e depois gravar, roda dentro de uma transação num PostgreSQL deixado no nível padrão. Dois balcões se sobrepõem. O que acontece?'),
         choices=[
             (False, ('The second desk gets database is locked, as in the plain_begin run',
                      'O segundo balcão recebe database is locked, como na execução plain_begin'),
              ('That is SQLite, which is serializable. PostgreSQL defaults to read committed.',
               'Isso é o SQLite, que é serializável. O PostgreSQL vem em read committed.')),
             (False, ('PostgreSQL aborts the second transaction with a serialization error',
                      'O PostgreSQL aborta a segunda transação com um erro de serialização'),
              ('That needs REPEATABLE READ or higher; the default level lets the second UPDATE through.',
               'Isso exige REPEATABLE READ ou acima; o nível padrão deixa o segundo UPDATE passar.')),
             (True, ('The update is lost, unless the read says FOR UPDATE', 'A atualização se perde, a menos que a leitura diga FOR UPDATE'),
              ('Right. Read committed waits for the first UPDATE and then applies the second over it.',
               'Isso. O read committed espera o primeiro UPDATE e depois aplica o segundo por cima.')),
             (False, ('Nothing goes wrong: any transaction serialises its own reads and writes',
                      'Nada dá errado: toda transação serializa as próprias leituras e escritas'),
              ('A transaction groups its own statements; whether it is shielded from another one is the isolation level\'s business.',
               'Uma transação agrupa os próprios comandos; se ela fica protegida de outra é assunto do nível de isolamento.')),
         ]),
    # ---- unit-of-work
    dict(id='ex-6nsy9nbz', section='unit-of-work', type='quiz', difficulty='easy',
         prompt=("Caio's first visit in uow.py calls uow.lend and leaves the with block. Why is nothing written?",
                 'A primeira visita de Caio em uow.py chama uow.lend e sai do bloco with. Por que nada é gravado?'),
         choices=[
             (False, ('SQLite refused the loan because the basket held a single title', 'O SQLite recusou o empréstimo porque a cesta tinha um título só'),
              ('No SQL ran at all: lend only appends to a list.', 'Nenhum SQL rodou: lend só acrescenta a uma lista.')),
             (True, ('Only commit writes, and __exit__ throws away what was never committed',
                     'Só o commit grava, e o __exit__ descarta o que nunca foi gravado'),
              ('Right. Forgetting commit writes nothing, which is the safe way round to forget.',
               'Isso. Esquecer o commit não grava nada, que é o lado seguro de esquecer.')),
             (False, ('Dom Casmurro had no copy left by then', 'Dom Casmurro já não tinha exemplar a essa altura'),
              ('The stock still showed 2 after Bia\'s refused basket.', 'O estoque ainda mostrava 2 depois da cesta recusada de Bia.')),
         ]),
    dict(id='ex-7tsyb96e', section='unit-of-work', type='ordering', difficulty='medium',
         prompt=("Put in order what happens inside commit for Bia's basket of Dom Casmurro, Vidas Secas and Iracema.",
                 'Ponha em ordem o que acontece dentro de commit para a cesta de Bia com Dom Casmurro, Vidas Secas e Iracema.'),
         items=[('BEGIN IMMEDIATE takes the write lock', 'BEGIN IMMEDIATE pega a trava de escrita'),
                ('Dom Casmurro and Vidas Secas are counted down and their loans inserted', 'Dom Casmurro e Vidas Secas têm a contagem baixada e os empréstimos inseridos'),
                ('The UPDATE for Iracema changes zero rows', 'O UPDATE de Iracema muda zero linhas'),
                ('NoCopyLeft is raised', 'NoCopyLeft é levantada'),
                ('ROLLBACK undoes the two loans already applied', 'ROLLBACK desfaz os dois empréstimos já aplicados')],
         trap=('The first two loans do reach the database inside the transaction; the rollback is what keeps them from being seen.',
               'Os dois primeiros empréstimos chegam sim ao banco dentro da transação; é o rollback que impede que sejam vistos.')),
    dict(id='ex-tj3qmgj6', section='unit-of-work', type='quiz', difficulty='hard',
         prompt=('Instead of a unit of work, checkout calls a lend_one helper that commits after each title. Bia asks for three titles and the third has no copy. What does she leave with?',
                 'Em vez de uma unidade de trabalho, checkout chama um auxiliar lend_one que faz commit a cada título. Bia pede três títulos e o terceiro não tem exemplar. Com o que ela sai?'),
         choices=[
             (False, ('Nothing, because the error rolls the whole checkout back', 'Nada, porque o erro desfaz o empréstimo inteiro'),
              ('There is nothing left to roll back: each of the first two was committed when lend_one finished.',
               'Não sobra nada para desfazer: cada um dos dois primeiros foi gravado quando lend_one terminou.')),
             (True, ('The first two titles', 'Os dois primeiros títulos'),
              ('Right. Each commit ended its own transaction, so the basket was lent in pieces.',
               'Isso. Cada commit encerrou a própria transação, então a cesta foi emprestada aos pedaços.')),
             (False, ('All three, with the stock of the third going below zero', 'Os três, com o estoque do terceiro abaixo de zero'),
              ('The conditional UPDATE refuses when no copy is left; that part still works.',
               'O UPDATE condicional recusa quando não sobra exemplar; essa parte continua funcionando.')),
             (False, ('Only the third, which the database kept as the latest change', 'Só o terceiro, que o banco guardou como a mudança mais recente'),
              ('The third is the one that failed; it is the only title she cannot have.',
               'O terceiro é o que falhou; é o único título que ela não pode levar.')),
         ]),
    # ---- cap
    dict(id='ex-8t6ddgz6', section='cap', type='quiz', difficulty='medium',
         prompt=('In the CP run of branches.py, the link is down. Why does Centro still lend the copy to Bia?',
                 'Na execução CP de branches.py, o link está fora. Por que Centro ainda empresta o exemplar a Bia?'),
         choices=[
             (True, ('It is the primary, so its count is the truth',
                     'É a primária, e a contagem dela é a verdade'),
              ('Right. CP refuses on the side that cannot be sure, and the primary can be.',
               'Isso. O CP recusa do lado que não tem certeza, e a primária tem.')),
             (False, ('CP mode only refuses after the link has been down for some time', 'O modo CP só recusa depois de o link ficar fora por um tempo'),
              ('There is no timer in the program; Vila Madalena refuses at once.', 'Não há temporizador no programa; a Vila Madalena recusa na hora.')),
             (False, ('Bia asked first, and the first request in a partition is always accepted',
                      'Bia pediu primeiro, e o primeiro pedido numa partição é sempre aceito'),
              ('Order is not the rule. Had Caio asked at Vila Madalena first, he would still have been refused.',
               'A ordem não é a regra. Se Caio tivesse pedido primeiro na Vila Madalena, ainda seria recusado.')),
         ]),
    dict(id='ex-v3tewjep', section='cap', type='quiz', difficulty='medium',
         prompt=('Somebody sums up CAP as "pick two of the three". What does the section say is wrong with that?',
                 'Alguém resume o CAP como "escolha dois dos três". O que a seção diz que está errado nisso?'),
         choices=[
             (False, ('There are four properties, not three', 'São quatro propriedades, não três'),
              ('CAP has three letters; the misreading is about what choosing means.', 'O CAP tem três letras; o erro está no que escolher significa.')),
             (False, ('Every real system must give up availability', 'Todo sistema real precisa abrir mão da disponibilidade'),
              ('The AP run gives up consistency instead; both answers exist.', 'A execução AP abre mão da consistência; as duas respostas existem.')),
             (True, ('A partition is not optional; the choice exists only while one is happening',
                     'Partição não é opcional; a escolha só existe enquanto uma está acontecendo'),
              ('Right. You cannot choose to skip partitions, so the real choice is what each side does during one.',
               'Isso. Não dá para escolher pular partições, então a escolha de verdade é o que cada lado faz durante uma.')),
             (False, ('It is right, but only for databases with more than two nodes', 'Está certo, mas só para bancos com mais de dois nós'),
              ('The library has two branches and the choice is just as real there.', 'A biblioteca tem duas filiais e a escolha é igualmente real ali.')),
         ]),
    dict(id='ex-5avzcq65', section='cap', type='cloze', difficulty='easy',
         prompt=("The literature's name for CAP's C, every read seeing the most recent write as if there were one copy, is ___ .",
                 'O nome que a literatura dá ao C do CAP, toda leitura vendo a escrita mais recente como se houvesse uma cópia só, é ___ .'),
         blanks=[dict(en=['linearizability', 'linearisability'], pt=['linearizabilidade', 'linearizability'])]),
    # ---- pacelc
    dict(id='ex-t6gvavsh', section='pacelc', type='numeric', difficulty='medium',
         prompt=('In latency.py, ONE_WAY_MS is changed to 80 and LOCAL_MS stays 3. How long does Bia wait in sync mode, in milliseconds?',
                 'Em latency.py, ONE_WAY_MS passa a 80 e LOCAL_MS continua 3. Quanto Bia espera no modo sync, em milissegundos?'),
         hint=('The confirmation has to come back as well.', 'A confirmação também precisa voltar.'),
         value=163, tolerance=0, unit=('ms', 'ms')),
    dict(id='ex-6ef2ew87', section='pacelc', type='quiz', difficulty='medium',
         prompt=('In the async run, a read from the replica at 40 ms says 16 March. What is that?',
                 'Na execução async, uma leitura da réplica aos 40 ms diz 16 de março. O que é isso?'),
         choices=[
             (False, ('A partition: the replica cannot be reached', 'Uma partição: a réplica está inalcançável'),
              ('Nothing is broken in the program; the change is simply still on its way.', 'Nada está quebrado no programa; a mudança só ainda está a caminho.')),
             (True, ('Eventual consistency: a stale read with no failure anywhere', 'Consistência eventual: uma leitura velha sem falha nenhuma'),
              ('Right. It is the everyday price of telling Bia "done" after 3 ms.', 'Isso. É o preço de todo dia de dizer "pronto" a Bia aos 3 ms.')),
             (False, ('A lost update, like the first run of desks.py', 'Uma atualização perdida, como a primeira execução de desks.py'),
              ('Nothing was overwritten: at 80 ms the replica shows 30 March.', 'Nada foi sobrescrito: aos 80 ms a réplica mostra 30 de março.')),
             (False, ('A bug in the replica, which should have applied the change first', 'Um defeito na réplica, que devia ter aplicado a mudança antes'),
              ('The replica cannot have a change that has not reached it; 55 ms of travel is the design.',
               'A réplica não pode ter uma mudança que ainda não chegou; 55 ms de viagem fazem parte do projeto.')),
         ]),
    dict(id='ex-k8ev9kcy', section='pacelc', type='quiz', difficulty='hard',
         prompt=('A store answers reads from the nearest replica when the network is healthy, and refuses writes on the side cut off from the primary during a partition. Which PACELC label fits?',
                 'Um banco responde leituras da réplica mais próxima quando a rede está saudável, e recusa escritas no lado isolado da primária durante uma partição. Que rótulo PACELC serve?'),
         choices=[
             (False, ('PA/EL', 'PA/EL'),
              ('Refusing on the cut-off side is choosing C during a partition, not A.', 'Recusar no lado isolado é escolher C durante a partição, não A.')),
             (True, ('PC/EL', 'PC/EL'),
              ('Right. C when partitioned, latency otherwise: the two halves of the tree are chosen separately.',
               'Isso. C na partição, latência no resto: as duas metades da árvore são escolhidas separadamente.')),
             (False, ('PC/EC', 'PC/EC'),
              ('Answering from the nearest replica, without waiting, is the L side of Else.', 'Responder da réplica mais próxima, sem esperar, é o lado L do Else.')),
             (False, ('PA/EC', 'PA/EC'),
              ('Both halves are the other way round.', 'As duas metades estão ao contrário.')),
         ]),
    # ---- choosing
    dict(id='ex-ap8e89b6', section='choosing', type='quiz', difficulty='medium',
         prompt=('Which library operation does the section accept at any branch while the link is down?',
                 'Que operação da biblioteca a seção aceita em qualquer filial enquanto o link está fora?'),
         choices=[
             (False, ('Lending the last copy, as long as each branch keeps a record', 'Emprestar o último exemplar, desde que cada filial guarde registro'),
              ('Keeping a record is what led to two loans for one copy in the AP run.', 'Guardar registro é o que levou a dois empréstimos para um exemplar na execução AP.')),
             (True, ('Placing a hold', 'Fazer uma reserva'),
              ('Right. A queue ordered by arrival time settles the conflict by rule, without a person.',
               'Isso. Uma fila ordenada por horário de chegada resolve o conflito por regra, sem uma pessoa.')),
             (False, ('Paying a fine, since the amount is known in advance', 'Pagar uma multa, já que o valor é conhecido de antemão'),
              ('Money taken twice needs a refund, which is a person repairing it; fines go to the primary.',
               'Dinheiro cobrado duas vezes pede estorno, que é uma pessoa consertando; multas vão para a primária.')),
         ]),
    dict(id='ex-sw5vksah', section='choosing', type='multiple-choice', difficulty='medium',
         prompt=('Which of these operations does the section send to the primary and pay for consistency? Choose all that apply.',
                 'Quais destas operações a seção manda para a primária, pagando pela consistência? Marque todas as que se aplicam.'),
         choices=[
             (True, ('Lending the last copy', 'Emprestar o último exemplar'),
              ('Right. Two members promised one book is a mistake a person has to repair.', 'Isso. Dois sócios com a promessa de um livro é um erro que uma pessoa precisa consertar.')),
             (False, ('Showing "available" in the online catalogue', 'Mostrar "disponível" no catálogo online'),
              ('A few seconds stale harms nobody; it reads from a replica or lesson 8\'s read model.',
               'Alguns segundos de atraso não prejudicam ninguém; a leitura vai a uma réplica ou ao modelo de leitura da lição 8.')),
             (True, ('Paying a fine', 'Pagar uma multa'),
              ('Right. Money, and every ACID letter with it.', 'Isso. Dinheiro, e todas as letras do ACID junto.')),
             (False, ('Counting "popular this week"', 'Contar os "mais procurados da semana"'),
              ('A count off by a few is harmless; the section gives it no transaction at all.', 'Uma contagem errada por pouco é inofensiva; a seção não lhe dá transação nenhuma.')),
         ]),
    dict(id='ex-ddytv14w', section='choosing', type='quiz', difficulty='hard',
         prompt=('A new operation: a member rates a book from 1 to 5, and the page shows the average. The link between branches goes down. What does the section\'s test suggest?',
                 'Uma operação nova: um sócio dá nota de 1 a 5 a um livro, e a página mostra a média. O link entre as filiais cai. O que o teste da seção sugere?'),
         choices=[
             (True, ('Accept at both branches and merge the ratings when the link returns',
                     'Aceitar nas duas filiais e somar as notas quando o link voltar a funcionar'),
              ('Right. Every rating counts once whichever branch heard it, so a rule settles it and nobody has to be phoned.',
               'Isso. Toda nota conta uma vez, seja qual for a filial que a ouviu, então uma regra resolve e ninguém precisa receber telefonema.')),
             (False, ('Refuse at Vila Madalena, as for lending the last copy', 'Recusar na Vila Madalena, como no empréstimo do último exemplar'),
              ('Lending is refused because only a person can repair two loans for one copy; two ratings conflict with nothing.',
               'O empréstimo é recusado porque só uma pessoa conserta dois empréstimos para um exemplar; duas notas não conflitam com nada.')),
             (False, ('Run every rating inside BEGIN IMMEDIATE at the primary, so no rating is lost',
                      'Rodar toda nota dentro de BEGIN IMMEDIATE na primária, para nenhuma se perder'),
              ('That buys consistency nobody needs and makes every rating wait behind the loans.',
               'Isso compra uma consistência de que ninguém precisa e faz toda nota esperar atrás dos empréstimos.')),
         ]),
    # ---- drill
    dict(id='ex-0zf7x972', section='drill', type='matching', difficulty='medium',
         prompt=('Match each problem from this lesson to the tool that answered it.',
                 'Associe cada problema desta lição à ferramenta que o resolveu.'),
         pairs=[
             (('A hold moved halfway and lost', 'Uma reserva movida pela metade e perdida'), ('a transaction with ROLLBACK', 'uma transação com ROLLBACK')),
             (('Two desks lend one copy', 'Dois balcões emprestam um exemplar'), ('the conditional UPDATE', 'o UPDATE condicional')),
             (('A helper commits in the middle of a checkout', 'Um auxiliar faz commit no meio de um empréstimo'), ('a unit of work', 'uma unidade de trabalho')),
             (('A replica shows the old due date after "done"', 'Uma réplica mostra a data antiga depois do "pronto"'), ('synchronous replication', 'replicação síncrona')),
         ]),
    dict(id='ex-cvfy0gev', section='drill', type='quiz', difficulty='hard',
         prompt=('Each branch in the AP run has data that satisfies every constraint, yet the two disagree. Which statement is true?',
                 'Cada filial na execução AP tem dados que satisfazem todas as restrições, e mesmo assim as duas discordam. Que afirmação é verdadeira?'),
         choices=[
             (False, ('The run breaks ACID, because two loans exist for one copy', 'A execução quebra o ACID, porque existem dois empréstimos para um exemplar'),
              ('Each branch\'s own transactions were valid; no single database broke a rule it was given.',
               'As transações de cada filial foram válidas; nenhum banco quebrou uma regra que recebeu.')),
             (False, ('Both Cs fail, since they are the same property seen from two sides', 'Os dois Cs falham, já que são a mesma propriedade vista de dois lados'),
              ('They are different properties; the section tables them apart for this reason.', 'São propriedades diferentes; a seção as põe em colunas separadas por isso.')),
             (True, ("ACID's C holds on each node; CAP's C fails between them", 'O C do ACID vale em cada nó; o do CAP falha entre eles'),
              ('Right. Valid data per node, and copies that disagree: the two letters measure different things.',
               'Isso. Dados válidos por nó, e cópias que discordam: as duas letras medem coisas diferentes.')),
             (False, ('Neither C applies, because the network was down', 'Nenhum C se aplica, porque a rede estava fora'),
              ('A partition is exactly when CAP\'s C is decided, and ACID applies on each node regardless.',
               'Uma partição é justamente quando o C do CAP se decide, e o ACID vale em cada nó de qualquer jeito.')),
         ]),
    dict(id='ex-r3e5hm75', section='drill', type='quiz', difficulty='hard',
         prompt=('The online catalogue reads "available: 1" from a replica. A member sees it, walks to the desk, and the copy has just gone out. What should the library do about it?',
                 'O catálogo online lê "disponível: 1" de uma réplica. Um sócio vê, vai até o balcão, e o exemplar acabou de sair. O que a biblioteca deve fazer?'),
         choices=[
             (False, ('Move the catalogue to synchronous reads from the primary', 'Passar o catálogo para leituras síncronas na primária'),
              ('Even a current page goes stale the moment the member stands up; the cost would buy nothing at the desk.',
               'Até uma página atual fica velha no instante em que o sócio se levanta; o custo não compraria nada no balcão.')),
             (True, ('Nothing: the page traded consistency for latency, and the desk still checks at the primary',
                     'Nada: a página trocou consistência por latência, e o balcão continua conferindo na primária'),
              ('Right. The lend itself is where consistency is paid for, and it refused correctly.',
               'Isso. O empréstimo em si é onde a consistência é paga, e ele recusou corretamente.')),
             (False, ('Treat it as a lost update and add BEGIN IMMEDIATE to the page', 'Tratar como atualização perdida e pôr BEGIN IMMEDIATE na página'),
              ('Nothing was overwritten; a read was simply old. A lock on a read path would make every page view queue.',
               'Nada foi sobrescrito; uma leitura só estava velha. Uma trava no caminho de leitura faria toda visita esperar na fila.')),
             (False, ('Hold the copy for anyone who has the page open', 'Segurar o exemplar para quem estiver com a página aberta'),
              ('That turns every page view into a write at the primary, the most expensive choice in the table.',
               'Isso transforma toda visita numa escrita na primária, a escolha mais cara da tabela.')),
         ]),
    dict(id='ex-rh0rs4b4', section='drill', type='cloze', difficulty='medium',
         prompt=('After the conditional UPDATE, the program reads the cursor\'s ___ to learn whether a copy was actually taken.',
                 'Depois do UPDATE condicional, o programa lê o ___ do cursor para saber se um exemplar foi mesmo retirado.'),
         blanks=[dict(en=['rowcount', 'cursor.rowcount', 'cur.rowcount'], pt=['rowcount', 'cursor.rowcount', 'cur.rowcount'])]),
]
