"""Lesson 11: Domain-Driven Design, strategic."""

EXERCISES = [
    # ---- why-ddd
    dict(id='ex-jncg9efv', section='why-ddd', type='quiz', difficulty='easy',
         prompt=('Where does the section say Domain-Driven Design earns its cost?',
                 'Onde a seção diz que o Domain-Driven Design paga o que custa?'),
         choices=[
             (False, ('Wherever there is a database', 'Onde quer que haja um banco de dados'),
              ('The phone-number page has a database and is better as plain CRUD.', 'A página do telefone tem banco e fica melhor como CRUD simples.')),
             (True, ('Where the hard part is rules that interact', 'Onde a parte difícil são regras que interagem'),
              ('Right. Lending\'s rules are each simple; the trouble is where they meet.', 'Isso. Cada regra do empréstimo é simples; o problema é onde elas se encontram.')),
             (False, ('In systems that have to handle a very high volume of requests', 'Em sistemas que precisam aguentar um volume muito alto de requisições'),
              ('Throughput is listed among the difficulties DDD has little to offer for.', 'A vazão está entre as dificuldades para as quais o DDD tem pouco a oferecer.')),
             (False, ('In a short prototype, to get the design right from the start', 'Num protótipo curto, para acertar o projeto desde o começo'),
              ('A system that lives for a campaign is in the "probably not" column.', 'Um sistema que vive uma campanha está na coluna do "provavelmente não".')),
         ]),
    dict(id='ex-jbe039tb', section='why-ddd', type='quiz', difficulty='medium',
         prompt=('A team has entities/, value_objects/ and repositories/ folders but never talks to the librarians. What does the section say they have?',
                 'Uma equipe tem pastas entities/, value_objects/ e repositories/ mas nunca conversa com as bibliotecárias. O que a seção diz que ela tem?'),
         choices=[
             (False, ('Complete DDD, since the folders follow the book', 'DDD completo, já que as pastas seguem o livro'),
              ('The folders are the tactical half; the section calls the strategic half the larger one.',
               'As pastas são a metade tática; a seção chama a metade estratégica de maior.')),
             (False, ('Strategic DDD without the tactical patterns', 'DDD estratégico sem os padrões táticos'),
              ('It is the other way round: the folders are tactical, and the conversations are what is missing.',
               'É o contrário: as pastas são táticas, e o que falta são as conversas.')),
             (True, ('The tactical half only, and possibly the same tangle in more files',
                     'Só a metade tática, e possivelmente o mesmo emaranhado em mais arquivos'),
              ('Right. Without agreed words and boundaries, the patterns rearrange the problem without solving it.',
               'Isso. Sem palavras e fronteiras combinadas, os padrões rearrumam o problema sem resolvê-lo.')),
         ]),
    dict(id='ex-217eawsy', section='why-ddd', type='multiple-choice', difficulty='medium',
         prompt=('Which of these are signs, from the section\'s table, that DDD is probably worth it? Choose all that apply.',
                 'Quais destes são sinais, pela tabela da seção, de que o DDD provavelmente vale? Marque todos que se aplicam.'),
         choices=[
             (True, ('Only people outside the team can explain the rules', 'Só gente de fora da equipe sabe explicar as regras'),
              ('Right. The knowledge is in the business, and the code has to learn its words.', 'Isso. O conhecimento está no negócio, e o código precisa aprender as palavras dele.')),
             (True, ('The rules change every few months, after arguments', 'As regras mudam a cada poucos meses, depois de discussões'),
              ('Right. A model in the business\'s words is what makes those changes cheap.', 'Isso. Um modelo com as palavras do negócio é o que barateia essas mudanças.')),
             (False, ('The hardest part is the screens', 'A parte mais difícil são as telas'),
              ('Screens are in the "probably not" column.', 'Telas estão na coluna do "provavelmente não".')),
             (True, ('The system will live for years', 'O sistema vai viver por anos'),
              ('Right. The conversations pay back over a long life.', 'Isso. As conversas se pagam ao longo de uma vida longa.')),
         ]),
    # ---- ubiquitous-language
    dict(id='ex-pq2bq2e1', section='ubiquitous-language', type='quiz', difficulty='easy',
         prompt=('Why does the section object to code that writes r["st"] = 4 for a lapsed hold?',
                 'Por que a seção critica um código que escreve r["st"] = 4 para uma reserva caducada?'),
         choices=[
             (True, ('Every conversation then goes through someone who knows what 4 means',
                     'Toda conversa passa então por alguém que sabe o que 4 quer dizer'),
              ('Right. Translation is where meaning leaks, as the status 5 story shows.', 'Isso. A tradução é por onde o significado vaza, como mostra a história do status 5.')),
             (False, ('A dictionary lookup is slower than reading an attribute on an object', 'Uma consulta em dicionário é mais lenta que ler um atributo de objeto'),
              ('Speed never comes up; the cost is in understanding.', 'Velocidade nem aparece; o custo está no entendimento.')),
             (False, ('Python forbids numbers as status values', 'O Python proíbe números como valores de status'),
              ('Python allows it; the objection is about language, not the interpreter.', 'O Python permite; a objeção é sobre linguagem, não sobre o interpretador.')),
         ]),
    dict(id='ex-6ax2ecq5', section='ubiquitous-language', type='numeric', difficulty='medium',
         prompt=('In holds.py, a copy is shelved on 3 June 2026. On which day of June does has_lapsed first answer True?',
                 'Em holds.py, um exemplar vai para a estante em 3 de junho de 2026. Em que dia de junho has_lapsed responde True pela primeira vez?'),
         hint=('The deadline itself is still allowed.', 'O próprio prazo ainda é permitido.'),
         value=11, tolerance=0, unit=('June', 'de junho')),
    dict(id='ex-14naprct', section='ubiquitous-language', type='quiz', difficulty='hard',
         prompt=('The librarians coin a name, in a meeting, for giving a lapsed hold one more day. What does the section recommend for the code?',
                 'As bibliotecárias inventam numa reunião um nome para dar mais um dia a uma reserva caducada. O que a seção recomenda para o código?'),
         choices=[
             (False, ('A flag named retry_lapsed, so the code stays technical and the business words stay out of it', 'Uma flag chamada retry_lapsed, para o código continuar técnico e as palavras do negócio ficarem de fora'),
              ('That is the section\'s example of how the two languages drift apart again.', 'Esse é o exemplo da seção de como as duas línguas voltam a se afastar.')),
             (False, ('Nothing until the glossary is approved by everyone, in a later release', 'Nada até o glossário ser aprovado por todos, numa versão futura'),
              ('The section asks for the rename in the same week, while the word is fresh.', 'A seção pede a renomeação na mesma semana, enquanto a palavra está fresca.')),
             (True, ('A second_chance method, a test named after it, and the word in the glossary',
                     'Um método second_chance, um teste com esse nome e a palavra no glossário'),
              ('Right. The language changed, so the code changes with it.', 'Isso. A linguagem mudou, então o código muda junto.')),
         ]),
    # ---- subdomains
    dict(id='ex-vwdrzhj6', section='subdomains', type='quiz', difficulty='easy',
         prompt=('Which of the library\'s subdomains does the section call core?',
                 'Qual subdomínio da biblioteca a seção chama de central?'),
         choices=[
             (False, ('Card and Pix payments, because money is involved', 'Pagamento por cartão e Pix, porque envolve dinheiro'),
              ('Payments are generic: every organisation has them and providers do them better.', 'Pagamentos são genéricos: toda organização tem e os provedores fazem melhor.')),
             (False, ('The catalogue, because it holds the most data', 'O catálogo, porque guarda mais dados'),
              ('Size does not decide it; the catalogue is supporting, the same work every library does.', 'O tamanho não decide; o catálogo é de suporte, o mesmo trabalho que toda biblioteca faz.')),
             (True, ('Lending', 'O empréstimo'),
              ('Right. Its rules are what the library decides about itself and why members come.', 'Isso. As regras dele são o que a biblioteca decide sobre si mesma e o motivo de os sócios virem.')),
             (False, ('Acquisitions, because buying books is how the collection grows', 'Aquisições, porque comprar livros é como o acervo cresce'),
              ('A few orders a month: supporting, and small.', 'Poucos pedidos por mês: de suporte, e pequeno.')),
         ]),
    dict(id='ex-s57ebm9f', section='subdomains', type='quiz', difficulty='medium',
         prompt=('The library wants to write its own handling of card payments for fines. What does the section say about that?',
                 'A biblioteca quer escrever o próprio tratamento de pagamentos com cartão para multas. O que a seção diz disso?'),
         choices=[
             (True, ('Effort spent on a generic subdomain, done worse than by a provider',
                     'Esforço gasto num subdomínio genérico, feito pior do que por um provedor'),
              ('Right. Generic means somebody else\'s core.', 'Isso. Genérico é o central de outra pessoa.')),
             (False, ('Good practice, because fines are part of lending, the core', 'Boa prática, porque multas fazem parte do empréstimo, o central'),
              ('The fine rules are core; taking the payment is not.', 'As regras de multa são centrais; receber o pagamento não é.')),
             (False, ('Acceptable as long as it uses every pattern of lesson 12', 'Aceitável desde que use todos os padrões da lição 12'),
              ('More care on the wrong subdomain is still care in the wrong place.', 'Mais cuidado no subdomínio errado continua sendo cuidado no lugar errado.')),
         ]),
    dict(id='ex-7brenhnj', section='subdomains', type='quiz', difficulty='hard',
         prompt=('The city offers every library a shared catalogue for free. What happens to the library\'s catalogue subdomain?',
                 'A prefeitura oferece a todas as bibliotecas um catálogo compartilhado de graça. O que acontece com o subdomínio de catálogo da biblioteca?'),
         choices=[
             (False, ('It becomes core, because the library must now integrate with the city', 'Vira central, porque a biblioteca agora precisa se integrar com a prefeitura'),
              ('Integration work does not make a subdomain a differentiator.', 'Trabalho de integração não torna um subdomínio um diferencial.')),
             (True, ('It becomes generic, and adopting the city\'s is the right move', 'Vira genérico, e adotar o da prefeitura é o movimento certo'),
              ('Right. Somebody now does it well for everyone, so it leaves the library\'s own care.',
               'Isso. Agora alguém faz bem para todos, então ele sai do cuidado próprio da biblioteca.')),
             (False, ('Nothing, since subdomains are fixed once they are sorted', 'Nada, já que subdomínios ficam fixos depois de separados'),
              ('The section has a part called "Subdomains move" for this case.', 'A seção tem uma parte chamada "Subdomínios mudam de lugar" para este caso.')),
             (False, ('It splits into two bounded contexts', 'Ele se divide em dois contextos delimitados'),
              ('Contexts are the solution side; the question is about what kind of problem it is now.',
               'Contextos são o lado da solução; a pergunta é sobre que tipo de problema ele é agora.')),
         ]),
    # ---- bounded-contexts
    dict(id='ex-x69ks2fp', section='bounded-contexts', type='quiz', difficulty='medium',
         prompt=('In tour.py, what connects acquisitions.Book, catalogue.Book and lending.Book?',
                 'Em tour.py, o que liga acquisitions.Book, catalogue.Book e lending.Book?'),
         choices=[
             (False, ('A shared parent class Book that all three inherit from', 'Uma classe-mãe Book que os três herdam'),
              ('There is no shared class at all; that would be the enterprise model again.', 'Não há classe compartilhada nenhuma; isso seria o modelo corporativo de novo.')),
             (True, ('The ISBN string they all carry, nothing else', 'A string do ISBN, e nada mais'),
              ('Right. The last line prints one ISBN for all three.', 'Isso. A última linha imprime um ISBN só para os três.')),
             (False, ('The title, same in every context', 'O título, que é o mesmo em todo contexto'),
              ('Only the catalogue\'s Book has a title; the others never mention it.', 'Só o Book do catálogo tem título; os outros nem o mencionam.')),
         ]),
    dict(id='ex-jzemassw', section='bounded-contexts', type='quiz', difficulty='hard',
         prompt=('A developer proposes renaming lending.Book to Copy, since it is really a copy. What does the section say?',
                 'Um desenvolvedor propõe renomear lending.Book para Copy, já que é de fato um exemplar. O que a seção diz?'),
         choices=[
             (False, ('Yes, because a word should mean the same thing across the whole library',
                      'Sim, porque uma palavra deveria querer dizer a mesma coisa na biblioteca inteira'),
              ('That is the one-model belief; inside lending, "book" is the desk\'s own word.',
               'Essa é a crença do modelo único; dentro do empréstimo, "livro" é a palavra do próprio balcão.')),
             (True, ('No: the lending desk calls it a book, and lending\'s code should speak the desk\'s language',
                     'Não: o balcão chama de livro, e o código do empréstimo deve falar a língua do balcão'),
              ('Right. A bounded context lets each meaning keep its own word.', 'Isso. Um contexto delimitado deixa cada significado ficar com a sua palavra.')),
             (False, ('Yes, but only if the catalogue renames its class to Work at the same time', 'Sim, mas só se o catálogo renomear a classe para Work ao mesmo tempo'),
              ('That couples two contexts\' naming, which the boundary exists to avoid.', 'Isso amarra os nomes de dois contextos, o que a fronteira existe para evitar.')),
         ]),
    dict(id='ex-rze912e0', section='bounded-contexts', type='matching', difficulty='medium',
         prompt=('Match each language to its usual boundary for a context inside one program.',
                 'Associe cada linguagem à fronteira usual de um contexto dentro de um só programa.'),
         pairs=[
             (('Go', 'Go'), ('an internal/ directory the compiler protects', 'um diretório internal/ que o compilador protege')),
             (('Java', 'Java'), ('a module-info.java that exports one package', 'um module-info.java que exporta um pacote')),
             (('Python', 'Python'), ('a package exposing what its __init__.py lists', 'um pacote que expõe o que o __init__.py lista')),
             (('TypeScript', 'TypeScript'), ('a folder others reach through one index.ts', 'uma pasta que os outros acessam por um index.ts')),
         ]),
    # ---- context-maps
    dict(id='ex-r25jmqzm', section='context-maps', type='matching', difficulty='medium',
         prompt=('Match each relationship on the library\'s map to the pair it joins.',
                 'Associe cada relação do mapa da biblioteca ao par que ela liga.'),
         pairs=[
             (('customer/supplier', 'cliente/fornecedor'), ('catalogue to lending', 'catálogo para empréstimo')),
             (('shared kernel', 'núcleo compartilhado'), ('catalogue and acquisitions', 'catálogo e aquisições')),
             (('conformist', 'conformista'), ('payment provider to lending', 'provedor de pagamentos para empréstimo')),
             (('anticorruption layer', 'camada anticorrupção'), ('bibliographic service to catalogue', 'serviço bibliográfico para catálogo')),
         ]),
    dict(id='ex-w5xxpzq2', section='context-maps', type='quiz', difficulty='medium',
         prompt=('Lending uses the payment provider\'s own names for payment states. Why does the section call that acceptable?',
                 'O empréstimo usa os nomes do próprio provedor para os estados de pagamento. Por que a seção chama isso de aceitável?'),
         choices=[
             (False, ('Because a downstream must always adopt the upstream\'s model', 'Porque um downstream sempre deve adotar o modelo do upstream'),
              ('The catalogue does the opposite with the bibliographic service; conforming is a choice.', 'O catálogo faz o contrário com o serviço bibliográfico; conformar-se é uma escolha.')),
             (True, ('The provider will not change for one library, and its model is reasonable',
                     'O provedor não vai mudar por uma biblioteca, e o modelo dele é razoável'),
              ('Right. Conforming to a good model saves a translation nobody needs.', 'Isso. Conformar-se a um bom modelo economiza uma tradução de que ninguém precisa.')),
             (False, ('Because payments are core, so lending must own them', 'Porque pagamentos são centrais, então o empréstimo precisa ser dono deles'),
              ('Payments are generic, and owning them is exactly what lending avoids.', 'Pagamentos são genéricos, e ser dono deles é justamente o que o empréstimo evita.')),
             (False, ('Because the two teams plan their releases together', 'Porque as duas equipes planejam os lançamentos juntas'),
              ('That would be a partnership; the library is one customer among thousands.', 'Isso seria uma parceria; a biblioteca é um cliente entre milhares.')),
         ]),
    dict(id='ex-vdv7e4mz', section='context-maps', type='quiz', difficulty='hard',
         prompt=('The shared ISBN kernel between catalogue and acquisitions grows a Book class "to save duplication". What has happened?',
                 'O núcleo compartilhado do ISBN entre catálogo e aquisições ganha uma classe Book "para evitar duplicação". O que aconteceu?'),
         choices=[
             (True, ('The kernel has become the one enterprise model again', 'O núcleo virou de novo o modelo corporativo único'),
              ('Right. A shared kernel works while it stays small; a shared Book is what the contexts were drawn to avoid.',
               'Isso. Um núcleo compartilhado funciona enquanto fica pequeno; um Book compartilhado é o que os contextos foram traçados para evitar.')),
             (False, ('Nothing important; a shared kernel can hold any code both teams use',
                      'Nada importante; um núcleo compartilhado pode guardar qualquer código que as duas equipes usem'),
              ('Every addition needs both teams to agree, so a large kernel couples them on everything.',
               'Toda adição exige o acordo das duas equipes, então um núcleo grande as amarra em tudo.')),
             (False, ('The relationship has turned into an anticorruption layer', 'A relação virou uma camada anticorrupção'),
              ('An ACL translates between two models; this merged them.', 'Uma camada anticorrupção traduz entre dois modelos; isto os fundiu.')),
         ]),
    # ---- anti-corruption-layer
    dict(id='ex-h292mjf5', section='anti-corruption-layer', type='quiz', difficulty='easy',
         prompt=('In the ddd-strategic directory, which file is the only one that names the service\'s fields, such as ttl and aut?',
                 'No diretório ddd-strategic, qual arquivo é o único que cita os campos do serviço, como ttl e aut?'),
         choices=[
             (False, ('catalogue.py', 'catalogue.py'),
              ('catalogue.py knows only its own Book; it has never heard of the feed.', 'catalogue.py só conhece o próprio Book; nunca ouviu falar do feed.')),
             (True, ('acl.py', 'acl.py'),
              ('Right. When the service renames a field, one file changes.', 'Isso. Quando o serviço renomeia um campo, um arquivo muda.')),
             (False, ('tour.py', 'tour.py'),
              ('tour.py walks one title through the three contexts and never sees the feed.', 'tour.py leva um título pelos três contextos e nunca vê o feed.')),
         ]),
    dict(id='ex-zemj9kk5', section='anti-corruption-layer', type='quiz', difficulty='medium',
         prompt=('The fourth record has status D. Why does acl.py refuse it instead of adding a withdrawn flag to Book?',
                 'O quarto registro tem status D. Por que acl.py o recusa em vez de acrescentar uma flag withdrawn ao Book?'),
         choices=[
             (False, ('Python dataclasses cannot hold a boolean field', 'Dataclasses do Python não conseguem ter um campo booleano'),
              ('They can; the choice is about the model, not the tool.', 'Conseguem; a escolha é sobre o modelo, não sobre a ferramenta.')),
             (False, ('Because the service will send the record again later with status A', 'Porque o serviço vai mandar o registro de novo depois com status A'),
              ('Nothing says it will; withdrawn means withdrawn.', 'Nada diz que vai; retirado quer dizer retirado.')),
             (True, ('A flag would bring a concept the catalogue does not need into its model',
                     'Uma flag traria para o modelo do catálogo um conceito de que ele não precisa'),
              ('Right. The layer decides what is not accepted, and keeps the inside simpler.', 'Isso. A camada decide o que não é aceito, e mantém o lado de dentro mais simples.')),
         ]),
    dict(id='ex-ey87ntbq', section='anti-corruption-layer', type='quiz', difficulty='hard',
         prompt=('A new upstream, the city\'s events calendar, sends JSON whose fields already match the library\'s model almost exactly, and it is happy to take requests. What fits?',
                 'Um novo upstream, a agenda cultural da prefeitura, manda um JSON cujos campos já batem quase exatamente com o modelo da biblioteca, e aceita pedidos. O que serve?'),
         choices=[
             (False, ('An anticorruption layer, because every external model must be translated',
                      'Uma camada anticorrupção, porque todo modelo externo precisa ser traduzido'),
              ('A layer is for an upstream that will not change and would damage your model; this one fails both tests.',
               'A camada é para um upstream que não muda e estragaria o seu modelo; este falha nos dois testes.')),
             (True, ('Customer/supplier, or conforming, without a layer', 'Cliente/fornecedor, ou conformar-se, sem camada'),
              ('Right. The model is close and the upstream listens, so translation would be code for nothing.',
               'Isso. O modelo é parecido e o upstream escuta, então a tradução seria código para nada.')),
             (False, ('Separate ways, because external data is never worth integrating', 'Caminhos separados, porque dados externos nunca valem a integração'),
              ('Separate ways fits when connecting costs more than it gives; nothing here says so.', 'Caminhos separados servem quando ligar custa mais do que dá; nada aqui diz isso.')),
         ]),
    # ---- event-storming
    dict(id='ex-2xekzf0n', section='event-storming', type='ordering', difficulty='medium',
         prompt=('Put the steps of a first event-storming session in the order the section gives.',
                 'Ponha em ordem os passos de uma primeira sessão de event storming, como a seção os dá.'),
         items=[('Everybody writes orange events at once', 'Todo mundo escreve eventos laranja ao mesmo tempo'),
                ('The room arranges them into one timeline', 'A sala os arruma numa só linha do tempo'),
                ('Pink notes mark disagreements and questions', 'Post-its rosa marcam discordâncias e perguntas'),
                ('Commands, actors and policies are added', 'Comandos, atores e políticas são acrescentados'),
                ('Lines are drawn where the language changes', 'Linhas são traçadas onde a linguagem muda')],
         trap=('Drawing boundaries first would decide the model before the wall has shown where the words change.',
               'Traçar fronteiras primeiro decidiria o modelo antes de a parede mostrar onde as palavras mudam.')),
    dict(id='ex-z3t7g0xa', section='event-storming', type='cloze', difficulty='easy',
         prompt=('An orange note is a domain event, written in the ___ tense, such as "Hold lapsed".',
                 'Um post-it laranja é um evento de domínio, escrito no tempo ___, como "Hold lapsed".'),
         blanks=[dict(en=['past'], pt=['passado', 'pretérito'])]),
    # ---- drill
    dict(id='ex-xa4f4se2', section='drill', type='quiz', difficulty='hard',
         prompt=('On the wall, the notes change from "Copy received" to "Title catalogued" to "Hold placed", and the people saying them change too. What is that evidence of?',
                 'Na parede, os post-its passam de "Copy received" para "Title catalogued" e para "Hold placed", e as pessoas que os dizem também mudam. Isso é evidência de quê?'),
         choices=[
             (False, ('Three subdomains that must all be core', 'Três subdomínios que precisam ser todos centrais'),
              ('Whether a part is core is a question of difference; the wall shows where words change.', 'Se uma parte é central é questão de diferença; a parede mostra onde as palavras mudam.')),
             (True, ('Candidate boundaries between bounded contexts', 'Fronteiras candidatas entre contextos delimitados'),
              ('Right. The library\'s three contexts came off exactly those shifts.', 'Isso. Os três contextos da biblioteca saíram exatamente dessas mudanças.')),
             (False, ('Inconsistent naming that a glossary should merge into one word', 'Nomes inconsistentes que um glossário deveria fundir numa palavra só'),
              ('Different words for different work are the point; merging them builds the one enterprise model.',
               'Palavras diferentes para trabalhos diferentes são o ponto; fundi-las constrói o modelo corporativo único.')),
             (False, ('A missing anticorruption layer between the three teams', 'Uma camada anticorrupção faltando entre as três equipes'),
              ('An ACL is chosen per relationship later; the wall first finds the contexts.', 'A camada é escolhida por relação depois; a parede primeiro acha os contextos.')),
         ]),
    dict(id='ex-thw25maw', section='drill', type='quiz', difficulty='hard',
         prompt=('The bibliographic service starts sending authors as "Given Surname" instead of "SURNAME, Given". Which code in the library has to change?',
                 'O serviço bibliográfico passa a mandar autores como "Nome Sobrenome" em vez de "SOBRENOME, Nome". Que código da biblioteca precisa mudar?'),
         choices=[
             (False, ('catalogue.py, the search, the desk screen and the overdue letters', 'catalogue.py, a busca, a tela do balcão e as cartas de atraso'),
              ('That would be the case without a layer; with one, none of them ever saw the service\'s format.',
               'Seria o caso sem camada; com ela, nenhum deles chegou a ver o formato do serviço.')),
             (False, ('Nothing, because author() already handles every format', 'Nada, porque author() já trata qualquer formato'),
              ('author() splits on ", " and would title-case the whole name; it handles their old format.',
               'author() divide em ", " e poria o nome inteiro em maiúsculas iniciais; ele trata o formato antigo deles.')),
             (True, ('Only the author function in acl.py', 'Só a função author de acl.py'),
              ('Right. The translation of their format lives in one place.', 'Isso. A tradução do formato deles mora num lugar só.')),
         ]),
    dict(id='ex-qh24c7p4', section='drill', type='matching', difficulty='medium',
         prompt=('Match each problem to the strategic tool from this lesson that addresses it.',
                 'Associe cada problema à ferramenta estratégica desta lição que trata dele.'),
         pairs=[
             (('Status 4 means lapsed, and only one developer knows', 'Status 4 quer dizer caducada, e só um desenvolvedor sabe'), ('ubiquitous language', 'linguagem ubíqua')),
             (('One Book class with half its fields empty', 'Uma classe Book com metade dos campos vazios'), ('bounded contexts', 'contextos delimitados')),
             (('Care spent on the password screen', 'Cuidado gasto na tela de senha'), ('subdomains', 'subdomínios')),
             (('ttl appears in the search code', 'ttl aparece no código da busca'), ('an anticorruption layer', 'uma camada anticorrupção')),
         ]),
]
