"""Lesson 12: entities, aggregates, value objects and repositories."""

EXERCISES = [
    # ---- entities
    dict(id='ex-xhch4g45', section='entities', type='quiz', difficulty='easy',
         prompt=('In entities.py, why are the two members called Ana Souza not equal?',
                 'Em entities.py, por que as duas sócias chamadas Ana Souza não são iguais?'),
         choices=[
             (False, ('Their phone numbers differ', 'Os telefones são diferentes'),
              ('Both have +55 11 5550-0114; the program makes them identical on purpose.', 'As duas têm +55 11 5550-0114; o programa as faz idênticas de propósito.')),
             (True, ('Their ids differ', 'Os ids são diferentes'),
              ('Right. m-014 and m-203 are two members whatever their attributes say.', 'Isso. m-014 e m-203 são duas sócias, digam o que disserem os atributos.')),
             (False, ('Python compares the two objects by their addresses in memory', 'O Python compara os dois objetos pelos endereços na memória'),
              ('That is the default, and Member overrides it with __eq__.', 'Esse é o padrão, e Member o sobrescreve com __eq__.')),
         ]),
    dict(id='ex-q3a6cb0y', section='entities', type='numeric', difficulty='medium',
         prompt=('entities.py puts ana, before and other_ana in a set. If Member had no __eq__ and __hash__ of its own, how many elements would the set hold?',
                 'entities.py põe ana, before e other_ana num conjunto. Se Member não tivesse __eq__ e __hash__ próprios, quantos elementos o conjunto teria?'),
         hint=('Without them, Python compares objects by identity in memory.', 'Sem eles, o Python compara objetos pela identidade na memória.'),
         value=3, tolerance=0, unit=('elements', 'elementos')),
    dict(id='ex-bfnwcctr', section='entities', type='quiz', difficulty='hard',
         prompt=('A team lets the database assign each member\'s id on INSERT. What problem does the section point out?',
                 'Uma equipe deixa o banco atribuir o id de cada sócio no INSERT. Que problema a seção aponta?'),
         choices=[
             (False, ('Sequences run out after a few million rows', 'As sequências acabam depois de alguns milhões de linhas'),
              ('Exhaustion is not the issue raised; timing is.', 'Esgotamento não é a questão levantada; o momento é.')),
             (False, ('Two members could end up with the same id', 'Dois sócios poderiam acabar com o mesmo id'),
              ('A sequence does not repeat; the trouble is before it has been asked at all.', 'Uma sequência não repete; o problema é antes de ela ser consultada.')),
             (True, ('Until it is saved, the member has no identity to compare or refer to',
                     'Até ser salvo, o sócio não tem identidade para comparar nem para ser referido'),
              ('Right. An entity needs its id from the moment it exists.', 'Isso. Uma entidade precisa do id desde o momento em que existe.')),
             (False, ('Nothing, as long as every entity is saved immediately after it is made', 'Nada, desde que toda entidade seja salva logo depois de criada'),
              ('Even saved at once, it cannot go in a set or be named by another aggregate before the INSERT returns.',
               'Mesmo salva na hora, ela não entra num conjunto nem é citada por outro agregado antes de o INSERT voltar.')),
         ]),
    # ---- value-objects
    dict(id='ex-mek9t88j', section='value-objects', type='quiz', difficulty='easy',
         prompt=('money.py prints True and then False for fine == Money(175) and fine is Money(175). Why is the False harmless?',
                 'money.py imprime True e depois False para fine == Money(175) e fine is Money(175). Por que o False é inofensivo?'),
         choices=[
             (True, ('For a value, which object it is never matters', 'Para um valor, qual objeto ele é nunca importa'),
              ('Right. Equal values are interchangeable; only an entity cares about identity.', 'Isso. Valores iguais são intercambiáveis; só uma entidade se importa com identidade.')),
             (False, ('It is a bug in the frozen dataclass that Python will fix', 'É um defeito da dataclass congelada que o Python vai corrigir'),
              ('is compares identity, and two separately made objects are two objects. Nothing is broken.',
               'is compara identidade, e dois objetos criados à parte são dois objetos. Nada está quebrado.')),
             (False, ('Because the second Money has a different currency', 'Porque o segundo Money tem outra moeda'),
              ('Both are BRL, the default; the == just above is True.', 'Os dois são BRL, o padrão; o == logo acima é True.')),
         ]),
    dict(id='ex-yy9yeq48', section='value-objects', type='quiz', difficulty='medium',
         prompt=('Why does the section give money a type instead of passing ints around?',
                 'Por que a seção dá um tipo ao dinheiro em vez de passar ints por aí?'),
         choices=[
             (False, ('An int cannot hold amounts above a few million cents', 'Um int não guarda quantias acima de alguns milhões de centavos'),
              ('Python\'s int has no such limit; the reason is where the rules live.', 'O int do Python não tem esse limite; o motivo é onde as regras moram.')),
             (True, ("So money's rules live in one place", 'Para as regras do dinheiro morarem num lugar só'),
              ('Right. Currency mixing and half cents are refused once, in Money.', 'Isso. Misturar moedas e meio centavo são recusados uma vez, em Money.')),
             (False, ('Dataclasses make arithmetic faster than plain ints', 'Dataclasses deixam a aritmética mais rápida que ints simples'),
              ('They make it slower, if anything; speed is not the point.', 'Deixam mais lenta, se for o caso; velocidade não é a questão.')),
             (False, ('Because a database column cannot store an integer amount', 'Porque uma coluna de banco não guarda uma quantia inteira'),
              ('SqliteMembers stores owed as an INTEGER without trouble.', 'SqliteMembers guarda owed como INTEGER sem problema.')),
         ]),
    dict(id='ex-q2edj23d', section='value-objects', type='matching', difficulty='medium',
         prompt=('Match each language to how it usually writes a value object.',
                 'Associe cada linguagem a como ela costuma escrever um objeto de valor.'),
         pairs=[
             (('Python', 'Python'), ('@dataclass(frozen=True)', '@dataclass(frozen=True)')),
             (('Java', 'Java'), ('a record', 'um record')),
             (('Go', 'Go'), ('a small struct passed by value', 'uma struct pequena passada por valor')),
             (('TypeScript', 'TypeScript'), ('readonly fields plus an equals method', 'campos readonly mais um método equals')),
         ]),
    # ---- aggregates
    dict(id='ex-m3rdedwa', section='aggregates', type='quiz', difficulty='medium',
         prompt=('Why does Member.loans return a tuple rather than the list itself?',
                 'Por que Member.loans devolve uma tupla em vez da própria lista?'),
         choices=[
             (False, ('Tuples use less memory, and members are loaded often', 'Tuplas usam menos memória, e sócios são carregados com frequência'),
              ('Memory is not the reason; the tuple closes a door.', 'Memória não é o motivo; a tupla fecha uma porta.')),
             (True, ('So no code can add a loan except through borrow', 'Para nenhum código acrescentar empréstimo sem passar por borrow'),
              ('Right. A tuple has no append, so the five-loan rule cannot be bypassed that way.', 'Isso. Tupla não tem append, então a regra dos cinco empréstimos não pode ser contornada por ali.')),
             (False, ('Because a dataclass cannot contain a list', 'Porque uma dataclass não pode conter uma lista'),
              ('Member is not a dataclass, and dataclasses can hold lists.', 'Member não é uma dataclass, e dataclasses podem ter listas.')),
         ]),
    dict(id='ex-p6fya9x9', section='aggregates', type='numeric', difficulty='medium',
         prompt=('A film is lent on 2 March 2026 and comes back on 20 March. Using member.py\'s rules, what fine is charged, in cents?',
                 'Um filme é emprestado em 2 de março de 2026 e volta em 20 de março. Pelas regras de member.py, que multa é cobrada, em centavos?'),
         hint=('A film goes out for 7 days.', 'Um filme sai por 7 dias.'),
         value=550, tolerance=0, unit=('cents', 'centavos')),
    dict(id='ex-4zhnf3yz', section='aggregates', type='quiz', difficulty='hard',
         prompt=('A migration script needs to import old loans. It writes them straight into member._loans. What does the section\'s reasoning say about that?',
                 'Um script de migração precisa importar empréstimos antigos. Ele os escreve direto em member._loans. O que o raciocínio da seção diz disso?'),
         choices=[
             (False, ('Fine, because migrations run only once', 'Tudo bem, porque migrações rodam uma vez só'),
              ('Running once is enough to load a member with seven loans, and the root never sees it.',
               'Rodar uma vez basta para carregar um sócio com sete empréstimos, e a raiz nunca vê.')),
             (True, ('It must go through the root, like every other path', 'Ele deve passar pela raiz, como qualquer outro caminho'),
              ('Right. Going through borrow, or a factory, is what keeps five loans the maximum.',
               'Isso. Passar por borrow, ou por uma fábrica, é o que mantém cinco empréstimos como máximo.')),
             (False, ('Python will raise an error because _loans is private', 'O Python vai levantar erro porque _loans é privado'),
              ('The underscore is a convention; the write will succeed silently.', 'O sublinhado é uma convenção; a escrita vai dar certo em silêncio.')),
         ]),
    # ---- invariants-and-boundaries
    dict(id='ex-74z0jfs4', section='invariants-and-boundaries', type='quiz', difficulty='medium',
         prompt=('In copies.py, Bia is offered the extra copy while already holding five loans. What happens to the copy?',
                 'Em copies.py, o exemplar extra é oferecido a Bia quando ela já tem cinco empréstimos. O que acontece com o exemplar?'),
         choices=[
             (False, ('It is never touched, because lend checks the member first', 'Ele nem é tocado, porque lend confere o sócio primeiro'),
              ('lend changes the copy first and the member second.', 'lend muda o exemplar primeiro e o sócio depois.')),
             (False, ('It stays out to Bia, and Caio is refused', 'Ele fica com Bia, e Caio é recusado'),
              ('The transcript shows on loan to: None, and Caio gets it.', 'A transcrição mostra on loan to: None, e Caio fica com ele.')),
             (True, ('It is checked out to her, then checked back in when she is refused',
                     'Ele sai no nome dela e volta quando ela é recusada'),
              ('Right. A correction made by code after the first change had already happened.', 'Isso. Uma correção feita por código depois de a primeira mudança já ter acontecido.')),
         ]),
    dict(id='ex-r3yt5zqc', section='invariants-and-boundaries', type='cloze', difficulty='easy',
         prompt=('Copy.on_loan_to holds the member\'s ___ , a string such as m-002, and never the Member object.',
                 'Copy.on_loan_to guarda o ___ do sócio, uma string como m-002, e nunca o objeto Member.'),
         blanks=[dict(en=['id', 'identifier', 'identity'], pt=['id', 'identificador'])]),
    dict(id='ex-8q15czjk', section='invariants-and-boundaries', type='quiz', difficulty='hard',
         prompt=('A new rule: a member\'s holds and loans together may not exceed eight. Holds are their own aggregate. What does the section suggest asking first?',
                 'Uma regra nova: as reservas e os empréstimos de um sócio juntos não podem passar de oito. Reservas são um agregado próprio. O que a seção sugere perguntar primeiro?'),
         choices=[
             (True, ('Must it hold at every instant, or soon?', 'Ela precisa valer a cada instante, ou logo?'),
              ('Right. Most cross-boundary rules turn out to be "soon", and then an event and a handler will do.',
               'Isso. A maioria das regras entre fronteiras acaba sendo de "logo", e aí um evento e um handler resolvem.')),
             (False, ('How to merge holds into the Member aggregate straight away', 'Como fundir as reservas no agregado Member imediatamente'),
              ('That is one answer if the rule must hold at every instant, and it makes the aggregate bigger; ask first.',
               'Essa é uma resposta se a regra precisar valer a cada instante, e deixa o agregado maior; pergunte antes.')),
             (False, ('Which of the two aggregates should hold a reference to the other object', 'Qual dos dois agregados deveria guardar uma referência ao outro objeto'),
              ('Aggregates refer to each other by id; holding the object is the second door.', 'Agregados se referem uns aos outros pelo id; guardar o objeto é a segunda porta.')),
         ]),
    # ---- repositories
    dict(id='ex-62z5ytyh', section='repositories', type='quiz', difficulty='easy',
         prompt=('Why is there a MemberRepository and no LoanRepository?',
                 'Por que existe um MemberRepository e nenhum LoanRepository?'),
         choices=[
             (False, ('Loans are stored in a file rather than the database', 'Empréstimos ficam num arquivo em vez do banco'),
              ('Loans have a table of their own in SqliteMembers.', 'Empréstimos têm uma tabela própria em SqliteMembers.')),
             (False, ('Nobody has written it yet', 'Ninguém o escreveu ainda'),
              ('Its absence is deliberate, and the section argues for it.', 'A ausência é deliberada, e a seção argumenta a favor dela.')),
             (True, ('A loan never loads without its member', 'Um empréstimo nunca vem sem o seu sócio'),
              ('Right. Repositories exist per aggregate root.', 'Isso. Repositórios existem por raiz de agregado.')),
         ]),
    dict(id='ex-d9rtjwdr', section='repositories', type='quiz', difficulty='medium',
         prompt=('Why does InMemoryMembers keep deep copies instead of the members it is given?',
                 'Por que InMemoryMembers guarda cópias profundas em vez dos sócios que recebe?'),
         choices=[
             (True, ('So a change counts only once it has been saved, as in a database', 'Para uma mudança só contar depois de salva, como num banco'),
              ('Right. Otherwise a test would pass for code that forgot to call save.', 'Isso. Senão um teste passaria para um código que esqueceu de chamar save.')),
             (False, ('Deep copies make the tests run faster', 'Cópias profundas fazem os testes rodarem mais rápido'),
              ('Copying is slower; the copies buy realism.', 'Copiar é mais lento; as cópias compram realismo.')),
             (False, ('Python dictionaries cannot hold objects that change later', 'Dicionários do Python não guardam objetos que mudam depois'),
              ('They can; that is exactly what would make the fake too forgiving.', 'Guardam; é exatamente isso que deixaria o dublê tolerante demais.')),
             (False, ('Because SqliteMembers does the same with its rows', 'Porque SqliteMembers faz o mesmo com as linhas'),
              ('SQLite stores rows, not objects; the copies imitate that behaviour.', 'O SQLite guarda linhas, não objetos; as cópias imitam esse comportamento.')),
         ]),
    dict(id='ex-czp5azed', section='repositories', type='quiz', difficulty='hard',
         prompt=('A teammate adds a method lend_directly(member_id, copy_id) to SqliteMembers that inserts a loan row. What is wrong with it?',
                 'Um colega acrescenta a SqliteMembers um método lend_directly(member_id, copy_id) que insere uma linha de empréstimo. O que está errado?'),
         choices=[
             (False, ('It is fine; it is faster than loading the member', 'Tudo bem; é mais rápido do que carregar o sócio'),
              ('Faster, and it skips both of the member\'s rules.', 'Mais rápido, e pula as duas regras do sócio.')),
             (True, ('It changes the aggregate behind its root, skipping both limits', 'Muda o agregado pelas costas da raiz, pulando os dois limites'),
              ('Right. A repository gets and saves whole aggregates; it does not make business changes.',
               'Isso. Um repositório busca e salva agregados inteiros; ele não faz mudanças de negócio.')),
             (False, ('It should be on InMemoryMembers too, so both classes match the protocol', 'Devia estar em InMemoryMembers também, para as duas classes baterem com o protocolo'),
              ('Adding it to both would put the second door in both places.', 'Acrescentá-lo às duas poria a segunda porta nos dois lugares.')),
         ]),
    # ---- domain-events
    dict(id='ex-v351x2e8', section='domain-events', type='quiz', difficulty='medium',
         prompt=('Why does Member record LoanStarted instead of sending the SMS receipt itself?',
                 'Por que Member registra LoanStarted em vez de mandar ele mesmo o SMS de recibo?'),
         choices=[
             (False, ('The SMS gateway does not accept messages from objects', 'O gateway de SMS não aceita mensagens de objetos'),
              ('The gateway is not the issue; the member\'s dependencies are.', 'O gateway não é a questão; as dependências do sócio são.')),
             (False, ('Events are faster to send than SMS messages', 'Eventos são mais rápidos de enviar que SMS'),
              ('The SMS is still sent, by a handler; speed does not change.', 'O SMS continua sendo enviado, por um handler; a velocidade não muda.')),
             (True, ('The member says what happened; reactions belong elsewhere', 'O sócio diz o que aconteceu; as reações ficam em outro lugar'),
              ('Right. Adding a reaction is a line in HANDLERS, and member.py does not change.', 'Isso. Acrescentar uma reação é uma linha em HANDLERS, e member.py não muda.')),
         ]),
    dict(id='ex-wnrpzdxf', section='domain-events', type='ordering', difficulty='medium',
         prompt=('Put the steps of handlers.run in order.', 'Ponha em ordem os passos de handlers.run.'),
         items=[('Load the member from the repository', 'Carregar o sócio do repositório'),
                ('Ask the member to borrow or give back', 'Pedir ao sócio para pegar ou devolver'),
                ('Pull the events out of the member', 'Retirar os eventos do sócio'),
                ('Save the member', 'Salvar o sócio'),
                ('Publish the events to the handlers', 'Publicar os eventos para os handlers')],
         trap=('Saving before pulling would store the events in the in-memory copy and hand them out again on the next get.',
               'Salvar antes de retirar guardaria os eventos na cópia em memória e os entregaria de novo no próximo get.')),
    dict(id='ex-t3zdr211', section='domain-events', type='quiz', difficulty='hard',
         prompt=('Publishing after saving can fail and leave a saved loan with no event sent. When does the section say that is not acceptable, and what does it offer?',
                 'Publicar depois de salvar pode falhar e deixar um empréstimo salvo sem evento enviado. Quando a seção diz que isso não é aceitável, e o que oferece?'),
         choices=[
             (False, ('In any case; publish before saving instead', 'Em qualquer caso; publique antes de salvar'),
              ('Publishing first sends receipts for loans a failed save then loses.', 'Publicar primeiro manda recibos de empréstimos que um salvamento fracassado perde.')),
             (True, ('When another aggregate depends on it: write it to an outbox in the same transaction', 'Quando outro agregado depende dele: gravá-lo num outbox na mesma transação'),
              ('Right. A separate job publishes from the outbox and marks events sent.', 'Isso. Uma tarefa separada publica a partir do outbox e marca os eventos como enviados.')),
             (False, ('When the event is a receipt: retry the SMS three times', 'Quando o evento é um recibo: tentar o SMS três vezes'),
              ('A lost receipt is the case the section calls acceptable.', 'Um recibo perdido é o caso que a seção chama de aceitável.')),
         ]),
    # ---- domain-services
    dict(id='ex-aj36ank9', section='domain-services', type='numeric', difficulty='medium',
         prompt=('With FinePolicy and Carnaval closed on 16 and 17 February 2026, a book due on 15 February comes back on 18 February. What is the fine, in cents?',
                 'Com FinePolicy e o Carnaval fechado em 16 e 17 de fevereiro de 2026, um livro com devolução em 15 de fevereiro volta em 18 de fevereiro. Qual é a multa, em centavos?'),
         hint=('Count the days after the due date the library was open.', 'Conte os dias depois da devolução em que a biblioteca abriu.'),
         value=50, tolerance=0, unit=('cents', 'centavos')),
    dict(id='ex-d748qjhr', section='domain-services', type='quiz', difficulty='medium',
         prompt=('Why does the closed-days rule get a FinePolicy of its own instead of a method on Loan?',
                 'Por que a regra dos dias fechados ganha um FinePolicy próprio em vez de um método em Loan?'),
         choices=[
             (True, ('It needs the library\'s calendar, which no single loan or member should hold',
                     'Ela precisa do calendário da biblioteca, que nenhum empréstimo ou sócio sozinho deveria guardar'),
              ('Right. A rule with no natural owner gets a home of its own.', 'Isso. Uma regra sem dono natural ganha casa própria.')),
             (False, ('Services are always better than methods on entities', 'Serviços são sempre melhores que métodos em entidades'),
              ('That belief is the anaemic domain model the section warns against.', 'Essa crença é o modelo de domínio anêmico contra o qual a seção alerta.')),
             (False, ('Loan is a dataclass, and dataclasses cannot have methods', 'Loan é uma dataclass, e dataclasses não podem ter métodos'),
              ('Money is a dataclass with several methods.', 'Money é uma dataclass com vários métodos.')),
         ]),
    dict(id='ex-a0atq3me', section='domain-services', type='multiple-choice', difficulty='hard',
         prompt=('Which of these are application services rather than domain services, in the section\'s terms? Choose all that apply.',
                 'Quais destes são serviços de aplicação, e não de domínio, nos termos da seção? Marque todos que se aplicam.'),
         choices=[
             (True, ('lend_copy in repositories.py', 'lend_copy em repositories.py'),
              ('Right. Load, ask, save: it coordinates and decides nothing.', 'Isso. Carregar, pedir, salvar: ele coordena e não decide nada.')),
             (False, ('FinePolicy.fine_for in closures.py', 'FinePolicy.fine_for em closures.py'),
              ('It decides something a librarian would recognise: a domain service.', 'Ele decide algo que uma bibliotecária reconheceria: um serviço de domínio.')),
             (True, ('run in handlers.py', 'run em handlers.py'),
              ('Right. It loads, saves and publishes; every decision is the member\'s.', 'Isso. Ele carrega, salva e publica; toda decisão é do sócio.')),
             (False, ('Member.borrow in member.py', 'Member.borrow em member.py'),
              ('That is a method of the aggregate root, not a service of either kind.', 'Esse é um método da raiz do agregado, não um serviço de tipo nenhum.')),
         ]),
    # ---- drill
    dict(id='ex-1z691mgv', section='drill', type='matching', difficulty='medium',
         prompt=('Match each piece of lending to the tactical pattern it is.',
                 'Associe cada peça do empréstimo ao padrão tático que ela é.'),
         pairs=[
             (('Money(175)', 'Money(175)'), ('value object', 'objeto de valor')),
             (('Member with its loans', 'Member com seus empréstimos'), ('aggregate', 'agregado')),
             (('SqliteMembers', 'SqliteMembers'), ('repository', 'repositório')),
             (('FineCharged', 'FineCharged'), ('domain event', 'evento de domínio')),
             (('FinePolicy', 'FinePolicy'), ('domain service', 'serviço de domínio')),
         ]),
    dict(id='ex-bkzznrx7', section='drill', type='quiz', difficulty='hard',
         prompt=('Acquisitions records "2 copies of ISBN 978-65-5555-001-6 at BRL 49.90". In lending, copy C-0107 is out to Bia. How should each be modelled?',
                 'As aquisições registram "2 exemplares do ISBN 978-65-5555-001-6 a BRL 49.90". No empréstimo, o exemplar C-0107 está com Bia. Como modelar cada um?'),
         choices=[
             (False, ('Both copies are entities everywhere, since a copy is a physical thing', 'Os dois são entidades em todo lugar, já que um exemplar é uma coisa física'),
              ('Physical or not, acquisitions cares about a quantity, not which copy is which.', 'Física ou não, as aquisições se importam com uma quantidade, não com qual exemplar é qual.')),
             (True, ("The desk's one is an entity; the order's 2 is only a value", 'O do balcão é entidade; o 2 do pedido é só um valor'),
              ('Right. The same concept is either, depending on the context.', 'Isso. O mesmo conceito pode ser um ou outro, dependendo do contexto.')),
             (False, ('Both are values, because each has an ISBN that identifies it', 'Os dois são valores, porque cada um tem um ISBN que o identifica'),
              ('Two copies share one ISBN; C-0107 and C-0108 are not interchangeable at the desk.', 'Dois exemplares dividem um ISBN; C-0107 e C-0108 não são intercambiáveis no balcão.')),
         ]),
    dict(id='ex-fmdv4dd4', section='drill', type='quiz', difficulty='hard',
         prompt=('Lending a copy changes the Copy and the Member. Which design follows both of the section\'s rules about boundaries?',
                 'Emprestar um exemplar muda o Copy e o Member. Que projeto segue as duas regras da seção sobre fronteiras?'),
         choices=[
             (False, ('Put each Copy inside the Member who holds it, so one transaction covers both', 'Pôr cada Copy dentro do Member que o tem, para uma transação cobrir os dois'),
              ('Then a copy has to be found inside whichever member holds it, and the aggregate grows without limit.',
               'Aí um exemplar precisa ser procurado dentro de quem o tiver, e o agregado cresce sem limite.')),
             (False, ('Give Copy a reference to the Member object, so it can call borrow directly', 'Dar ao Copy uma referência ao objeto Member, para ele chamar borrow direto'),
              ('Holding the object is the second door; the rule is to refer by id.', 'Guardar o objeto é a segunda porta; a regra é referir pelo id.')),
             (True, ('Own transactions, joined by ids, repaired by events', 'Transações próprias, ligadas por ids, consertadas por eventos'),
              ('Right. One aggregate per transaction, by id, and "soon" rather than "instant" between them.',
               'Isso. Um agregado por transação, pelo id, e "logo" em vez de "a cada instante" entre eles.')),
             (False, ('Lock both tables for the whole lend, every time', 'Travar as duas tabelas durante todo o empréstimo, sempre'),
              ('That is the larger lock the section keeps for rules that must hold at every instant; lending is not one.',
               'Essa é a trava maior que a seção reserva para regras que precisam valer a cada instante; emprestar não é uma delas.')),
         ]),
]
