"""Lesson 13: test-driven development."""

EXERCISES = [
    # ---- red-green-refactor
    dict(id='ex-3vjwd2w1', section='red-green-refactor', type='quiz', difficulty='easy',
         prompt=('A team has 4,000 tests, all written after the features they cover. Does it practise TDD?',
                 'Uma equipe tem 4.000 testes, todos escritos depois das funcionalidades que cobrem. Ela pratica TDD?'),
         choices=[
             (False, ('Yes: a suite that large is what TDD means', 'Sim: uma suíte desse tamanho é o que TDD quer dizer'),
              ('The suite is a by-product of TDD, not its definition. A large suite written afterwards is test-last.',
               'A suíte é um subproduto do TDD, não a definição dele. Uma suíte grande escrita depois é teste por último.')),
             (True, ('No: in TDD each test is written before the code it drives', 'Não: no TDD cada teste é escrito antes do código que ele guia'),
              ('Right. TDD is a way of writing the code, with the failing test first; the count of tests says nothing about the order.',
               'Isso. TDD é um jeito de escrever o código, com o teste que falha primeiro; a quantidade de testes não diz nada sobre a ordem.')),
             (False, ('Only if the coverage report shows 100 per cent of lines run', 'Só se o relatório de cobertura mostrar 100 por cento das linhas executadas'),
              ('Coverage measures what the tests run, not when they were written. Test-last suites reach full coverage too.',
               'Cobertura mede o que os testes executam, não quando foram escritos. Suítes de teste por último também chegam à cobertura total.')),
         ]),
    dict(id='ex-40rrf69d', section='red-green-refactor', type='ordering', difficulty='easy',
         prompt=('Put one turn of the cycle in order.', 'Ponha uma volta do ciclo em ordem.'),
         items=[('Write one test for the next behaviour', 'Escrever um teste para o próximo comportamento'),
                ('Run it and see it fail for the expected reason', 'Rodá-lo e vê-lo falhar pelo motivo esperado'),
                ('Write the least code that makes it pass', 'Escrever o mínimo de código que o faz passar'),
                ('Improve names and structure with every test green', 'Melhorar nomes e estrutura com todos os testes verdes')],
         trap=('Tidying before the test passes mixes two questions; the refactor step comes only after green.',
               'Arrumar antes de o teste passar mistura duas perguntas; o passo de refatorar só vem depois do verde.')),
    dict(id='ex-x1vdmhc4', section='red-green-refactor', type='quiz', difficulty='medium',
         prompt=('Why does the method insist on watching a new test fail before writing any code for it?',
                 'Por que o método insiste em ver um teste novo falhar antes de escrever qualquer código para ele?'),
         choices=[
             (False, ('Because a failing run is faster than a passing one', 'Porque uma execução que falha é mais rápida do que uma que passa'),
              ('Speed has nothing to do with it; both runs take a fraction of a second.',
               'A velocidade não tem nada a ver; as duas execuções levam uma fração de segundo.')),
             (True, ('A test never seen failing might not be testing anything at all', 'Um teste que nunca falhou talvez não esteja testando nada'),
              ('Right. Until it has been red, there is no evidence it can tell working code from broken code.',
               'Isso. Até ter ficado vermelho, não há evidência de que ele distingue código que funciona de código quebrado.')),
             (False, ('Because unittest refuses to run a test that has never failed before', 'Porque o unittest se recusa a rodar um teste que nunca falhou antes'),
              ('unittest keeps no history of runs; it runs whatever it collects.',
               'O unittest não guarda histórico de execuções; ele roda o que recolhe.')),
             (False, ('So that the commit history shows a red build before every green one', 'Para o histórico de commits mostrar um build vermelho antes de cada verde'),
              ('The red run happens on your machine, in seconds; nobody commits it.',
               'A execução vermelha acontece na sua máquina, em segundos; ninguém faz commit dela.')),
         ]),
    # ---- first-cycle
    dict(id='ex-2bhybj9f', section='first-cycle', type='quiz', difficulty='medium',
         prompt=('The first green version of fines.py is return 150. What has it already achieved?',
                 'A primeira versão verde de fines.py é return 150. O que ela já conseguiu?'),
         choices=[
             (False, ('Nothing; it is a placeholder to delete before the real work', 'Nada; é um tapa-buraco para apagar antes do trabalho de verdade'),
              ('It has done real work: the test is known to run and the interface is decided.',
               'Ela fez trabalho de verdade: sabe-se que o teste roda e a interface está decidida.')),
             (False, ('It computes the fine correctly for every book returned three days late', 'Ela calcula a multa certa para qualquer livro devolvido com três dias de atraso'),
              ('True of three days late and of nothing else, which is why the next test exists.',
               'Vale para três dias de atraso e para mais nada, e é por isso que o próximo teste existe.')),
             (True, ('The test is proved to run, and the name and arguments are fixed', 'O teste roda comprovadamente, e o nome e os argumentos estão fixados'),
              ('Right. Seen red then green, the test is known to run, and the call shape is decided before the formula.',
               'Isso. Visto vermelho e depois verde, sabe-se que o teste roda, e a forma da chamada é decidida antes da fórmula.')),
         ]),
    dict(id='ex-f6d1g4mt', section='first-cycle', type='quiz', difficulty='medium',
         prompt=('The first run ends in ModuleNotFoundError: No module named \'fines\'. How does the lesson read that?',
                 'A primeira execução termina em ModuleNotFoundError: No module named \'fines\'. Como a lição lê isso?'),
         choices=[
             (True, ('As a red run that fails for exactly the reason the test expected', 'Como uma execução vermelha que falha exatamente pelo motivo que o teste esperava'),
              ('Right. The test describes code that does not exist yet; Beck counts this as a failing test, as Java would count a compile error.',
               'Isso. O teste descreve código que ainda não existe; Beck conta isso como teste falhando, como Java contaria um erro de compilação.')),
             (False, ('As a broken setup to repair before the cycle can start', 'Como uma instalação quebrada a consertar antes de o ciclo começar'),
              ('Python and unittest worked perfectly; the missing module is the point of the test.',
               'O Python e o unittest funcionaram perfeitamente; o módulo faltando é o objetivo do teste.')),
             (False, ('As a sign the test was written too early, before the module', 'Como sinal de que o teste foi escrito cedo demais, antes do módulo'),
              ('Before the module is exactly when TDD writes it.', 'Antes do módulo é exatamente quando o TDD o escreve.')),
         ]),
    dict(id='ex-zs0rvnsx', section='first-cycle', type='cloze', difficulty='easy',
         prompt=('unittest skipped a method called three_days_late_costs_150_cents, because its name lacks the prefix ___ .',
                 'O unittest ignorou um método chamado three_days_late_costs_150_cents, porque falta no nome dele o prefixo ___ .'),
         blanks=[dict(en=['test', 'test_'], pt=['test', 'test_'])]),
    # ---- triangulation
    dict(id='ex-d7zp0bgn', section='triangulation', type='quiz', difficulty='medium',
         prompt=('In the lesson, what made return 150 give way to a formula?', 'Na lição, o que fez return 150 dar lugar a uma fórmula?'),
         choices=[
             (False, ('A code review that rejected the constant', 'Uma revisão de código que rejeitou a constante'),
              ('No reviewer was needed; a test did the rejecting.', 'Nenhum revisor foi necessário; um teste fez a rejeição.')),
             (True, ('A second test the constant could not pass', 'Um segundo teste que a constante não passava'),
              ('Right. 150 and 50 cannot both come from one constant, so the simplest code passing both is the general rule.',
               'Isso. 150 e 50 não podem vir os dois de uma constante, então o código mais simples que passa nos dois é a regra geral.')),
             (False, ('The refactor step, which replaces every fake with real code', 'O passo de refatorar, que troca todo fingimento por código real'),
              ('Refactoring changes structure, never behaviour; turning 150 into a formula changed what fine returns for one day late.',
               'Refatorar muda estrutura, nunca comportamento; trocar 150 por uma fórmula mudou o que fine devolve para um dia de atraso.')),
             (False, ('The first test, run a second time with -v so it names the case', 'O primeiro teste, rodado uma segunda vez com -v para dar nome ao caso'),
              ('Running the same test again cannot fail a constant that already passed it.',
               'Rodar o mesmo teste de novo não reprova uma constante que já passou nele.')),
         ]),
    dict(id='ex-pszmek2j', section='triangulation', type='numeric', difficulty='medium',
         prompt=('With the second version, return (returned - due).days * 50, what does fine return for a book brought back 4 days before its due date?',
                 'Com a segunda versão, return (returned - due).days * 50, o que fine devolve para um livro trazido 4 dias antes do vencimento?'),
         hint=('Count the days with their sign.', 'Conte os dias com o sinal.'),
         value=-200, tolerance=0, unit=('cents', 'centavos')),
    dict(id='ex-q51q2b7e', section='triangulation', type='matching', difficulty='medium',
         prompt=('Match each way to green to the situation it fits.', 'Associe cada jeito de chegar ao verde à situação em que cabe.'),
         pairs=[
             (('fake it', 'fingir (fake it)'), ('You are unsure what the general code is', 'Você não tem certeza de qual é o código geral')),
             (('triangulate', 'triangular'), ('One example does not reveal the generalisation', 'Um exemplo não revela a generalização')),
             (('obvious implementation', 'implementação óbvia'), ('You know exactly what to type, and are right', 'Você sabe exatamente o que digitar, e acerta')),
         ]),
    dict(id='ex-fycysq85', section='triangulation', type='quiz', difficulty='hard',
         prompt=('You add a test for a return on the due date and it passes the first time it runs. What does that tell you?',
                 'Você acrescenta um teste para devolução na data de vencimento e ele passa na primeira vez que roda. O que isso diz?'),
         choices=[
             (False, ('That the test is broken and must be deleted', 'Que o teste está quebrado e deve ser apagado'),
              ('It may be perfectly correct; it just drove no new code. Keep it if the boundary is worth recording.',
               'Ele pode estar perfeitamente certo; só não guiou código novo. Mantenha se a fronteira merece registro.')),
             (True, ('It drove no code, so it was not a TDD step', 'Não guiou código, então não foi um passo de TDD'),
              ('Right. The existing code already covered it; it may stay as documentation of the boundary, not as a step.',
               'Isso. O código existente já cobria o caso; ele pode ficar como documentação da fronteira, não como passo.')),
             (False, ('That the previous step was too small and should have included it', 'Que o passo anterior foi pequeno demais e devia tê-lo incluído'),
              ('Step size is about how much code changes between greens, and this test changed none.',
               'O tamanho do passo é sobre quanto código muda entre dois verdes, e este teste não mudou nenhum.')),
             (False, ('That the max() call in fines.py has no effect and can go', 'Que a chamada max() em fines.py não tem efeito e pode sair'),
              ('Zero days gives zero with or without max; the early-return test is what needs it.',
               'Zero dias dá zero com ou sem max; é o teste de devolução antecipada que precisa dela.')),
         ]),
    # ---- the-refactor-step
    dict(id='ex-gs2kv7g4', section='the-refactor-step', type='quiz', difficulty='easy',
         prompt=('Which change belongs in the refactor step?', 'Qual mudança pertence ao passo de refatorar?'),
         choices=[
             (True, ('Naming the 50 as DAILY_FINE', 'Dar ao 50 o nome DAILY_FINE'),
              ('Right. Structure and names change, and every test answers as before.',
               'Isso. Estrutura e nomes mudam, e todo teste responde como antes.')),
             (False, ('Making films cost 100 cents a day instead of 50', 'Fazer filmes custarem 100 centavos por dia em vez de 50'),
              ('That is new behaviour: a new test and a new red, on the next turn.',
               'Isso é comportamento novo: um teste novo e um vermelho novo, na próxima volta.')),
             (False, ('Fixing the failing early-return test by adding max()', 'Corrigir o teste de devolução antecipada que falha acrescentando max()'),
              ('That is the green step: refactoring only starts once every test passes.',
               'Isso é o passo verde: a refatoração só começa quando todos os testes passam.')),
         ]),
    dict(id='ex-rvkt7e45', section='the-refactor-step', type='quiz', difficulty='medium',
         prompt=('While extracting days_late you reverse the subtraction, and all three tests go red. What does the lesson tell you to do?',
                 'Ao extrair days_late você inverte a subtração, e os três testes ficam vermelhos. O que a lição manda fazer?'),
         choices=[
             (False, ('Read each failure and reason out which sign is right before touching the code',
                      'Ler cada falha e raciocinar qual sinal está certo antes de mexer no código'),
              ('Reasoning works, and is slower than undoing a one-line change you know caused it.',
               'Raciocinar funciona, e é mais lento do que desfazer uma mudança de uma linha que você sabe que causou o problema.')),
             (True, ('Undo the edit and redo it', 'Desfazer a edição e refazê-la'),
              ('Right. The only thing that changed is the cause; going back to green is one undo away.',
               'Isso. A única coisa que mudou é a causa; voltar ao verde está a um desfazer de distância.')),
             (False, ('Update the three tests to expect what the new code returns', 'Atualizar os três testes para esperarem o que o código novo devolve'),
              ('That would make the tests agree with a bug; in a refactor the tests are the fixed point.',
               'Isso faria os testes concordarem com um bug; numa refatoração os testes são o ponto fixo.')),
             (False, ('Make four more moves, then run again to see the whole picture', 'Fazer mais quatro movimentos e rodar de novo para ver o quadro todo'),
              ('More moves before a run turn one known cause into a puzzle.',
               'Mais movimentos antes de rodar transformam uma causa conhecida num quebra-cabeça.')),
         ]),
    dict(id='ex-3sj9rc80', section='the-refactor-step', type='quiz', difficulty='hard',
         prompt=('Why not refactor fines.py and test_fines.py in the same move?', 'Por que não refatorar fines.py e test_fines.py no mesmo movimento?'),
         choices=[
             (False, ('Because Python cannot reload two modules in one run', 'Porque o Python não consegue recarregar dois módulos numa execução'),
              ('Each run starts a fresh interpreter, which loads both files.', 'Cada execução começa um interpretador novo, que carrega os dois arquivos.')),
             (False, ('Because unittest only reports one changed file per run', 'Porque o unittest só relata um arquivo alterado por execução'),
              ('unittest knows nothing about which files changed.', 'O unittest não sabe nada sobre quais arquivos mudaram.')),
             (True, ('If both changed and the run is green, nothing checked either change',
                     'Se os dois mudaram e a execução está verde, nada conferiu nenhuma das mudanças'),
              ('Right. Each side is the check on the other; moving both at once leaves the green with no meaning.',
               'Isso. Cada lado é a conferência do outro; mexer nos dois de uma vez deixa o verde sem significado.')),
         ]),
    # ---- tdd-and-design
    dict(id='ex-02crt4wb', section='tdd-and-design', type='quiz', difficulty='medium',
         prompt=('Why does overdue take today as an argument instead of calling date.today() inside?',
                 'Por que overdue recebe today como argumento em vez de chamar date.today() por dentro?'),
         choices=[
             (False, ('date.today() is too slow to call once per loan', 'date.today() é lento demais para chamar uma vez por empréstimo'),
              ('Speed was never the issue; it returns in microseconds.', 'Velocidade nunca foi a questão; ela responde em microssegundos.')),
             (True, ('A test has to choose the day, or its verdict changes with the calendar',
                     'O teste precisa fixar o dia, ou o veredito muda com o calendário'),
              ('Right. A test passing on 20 March would fail on 1 April; the argument lets the test fix the day.',
               'Isso. Um teste que passa em 20 de março falharia em 1º de abril; o argumento deixa o teste fixar o dia.')),
             (False, ('So the reminders can be sent for dates in the past', 'Para os lembretes poderem ser enviados para datas no passado'),
              ('Production passes the real date; the argument exists for the caller that is a test.',
               'A produção passa a data real; o argumento existe para quem chama sendo um teste.')),
             (False, ('Python forbids reading the clock inside a list comprehension', 'O Python proíbe ler o relógio de dentro de uma compreensão de lista'),
              ('Nothing forbids it; it would just make the function untestable without patching.',
               'Nada proíbe; só tornaria a função impossível de testar sem remendos.')),
         ]),
    dict(id='ex-0mz38cmt', section='tdd-and-design', type='multiple-choice', difficulty='medium',
         prompt=('Which changes did writing the tests first push into reminders.py? Choose all that apply.',
                 'Que mudanças escrever os testes primeiro empurrou para reminders.py? Marque todas que se aplicam.'),
         choices=[
             (True, ('The clock became an argument', 'O relógio virou argumento'),
              ('Right: today is passed in.', 'Isso: today é passado de fora.')),
             (True, ('The decision split from the sending', 'A decisão se separou do envio'),
              ('Right: overdue is pure, and remind is a thin effect around it.', 'Isso: overdue é pura, e remind é um efeito fino em volta dela.')),
             (True, ('The sender is passed in as a function', 'Quem envia é passado como função'),
              ('Right: send is injected, a lambda in the test and the mail server in production.',
               'Isso: send é injetado, uma lambda no teste e o servidor de correio em produção.')),
             (False, ('An interface was added in front of overdue so a test could replace it', 'Uma interface foi posta na frente de overdue para um teste poder substituí-la'),
              ('overdue takes a list and a date and calls nothing; it needed no injection, and adding one would be the damage the section warns about.',
               'overdue recebe uma lista e uma data e não chama nada; não precisou de injeção, e acrescentar uma seria o dano que a seção aponta.')),
         ]),
    dict(id='ex-9dejkv5r', section='tdd-and-design', type='quiz', difficulty='hard',
         prompt=('Which of these is test-induced design damage rather than a healthy pressure from the tests?',
                 'Qual destas é dano ao projeto induzido por teste, e não uma pressão saudável dos testes?'),
         choices=[
             (False, ('Passing the clock into a function that decides what is overdue', 'Passar o relógio para uma função que decide o que está atrasado'),
              ('The clock is genuinely awkward in a test; injecting it is the counterweight the section recommends.',
               'O relógio é de fato incômodo num teste; injetá-lo é o contrapeso que a seção recomenda.')),
             (True, ('A FineCalculator interface with one implementation, added only for a test to swap the arithmetic',
                     'Uma interface FineCalculator com uma implementação, criada para um teste trocar a aritmética'),
              ('Right. Arithmetic is cheap and deterministic; an interface in front of it adds indirection for the tests alone.',
               'Isso. Aritmética é barata e determinística; uma interface na frente dela acrescenta indireção só por causa dos testes.')),
             (False, ('Passing the mail sender into remind', 'Passar quem envia e-mail para remind'),
              ('The network is one of the awkward things worth injecting.', 'A rede é uma das coisas incômodas que vale injetar.')),
         ]),
    # ---- doubles-in-tdd
    dict(id='ex-1wrepz0v', section='doubles-in-tdd', type='quiz', difficulty='medium',
         prompt=('remind calls notifier.send, but the real Notifier only has deliver. Why is the bare Mock() test green?',
                 'remind chama notifier.send, mas o Notifier real só tem deliver. Por que o teste com Mock() puro está verde?'),
         choices=[
             (True, ('A bare Mock() creates any attribute the code asks it for', 'Um Mock() puro cria qualquer atributo que o código lhe pede'),
              ('Right. The test checked remind against its own assumption, not against Notifier.',
               'Isso. O teste conferiu remind contra a própria suposição, não contra o Notifier.')),
             (False, ('Mock() copies the methods of the class it replaces, including old names', 'Mock() copia os métodos da classe que substitui, inclusive os nomes antigos'),
              ('A bare Mock knows no class at all; that is what spec= adds.', 'Um Mock puro não conhece classe nenhuma; é isso que spec= acrescenta.')),
             (False, ('unittest skips assertions on methods that do not exist', 'O unittest pula asserções sobre métodos que não existem'),
              ('The assertion ran and passed, because send was called on the mock.',
               'A asserção rodou e passou, porque send foi chamado no mock.')),
         ]),
    dict(id='ex-kmddvf0t', section='doubles-in-tdd', type='matching', difficulty='medium',
         prompt=('Match each double to what it checks.', 'Associe cada dublê ao que ele confere.'),
         pairs=[
             (('Mock()', 'Mock()'), ('Nothing about the real class', 'Nada sobre a classe real')),
             (('Mock(spec=Notifier)', 'Mock(spec=Notifier)'), ('That each attribute exists on Notifier', 'Que cada atributo existe em Notifier')),
             (('create_autospec(Notifier)', 'create_autospec(Notifier)'), ('Attributes, and the arguments of each call', 'Atributos, e os argumentos de cada chamada')),
             (('a lambda appending to a list', 'uma lambda que acrescenta numa lista'), ('Only what the test reads back afterwards', 'Só o que o teste lê depois')),
         ]),
    dict(id='ex-dd1q0b49', section='doubles-in-tdd', type='quiz', difficulty='hard',
         prompt=('Which assertion is most likely to break on a harmless refactor?', 'Qual asserção tem mais chance de quebrar numa refatoração inofensiva?'),
         choices=[
             (False, ('send was called once with the overdue member\'s address', 'send foi chamado uma vez com o endereço do membro atrasado'),
              ('Sending is a command with an effect somebody cares about; asserting it checks behaviour.',
               'Enviar é um comando com um efeito que importa a alguém; afirmar isso confere comportamento.')),
             (False, ('remind returned 1 for one overdue loan', 'remind devolveu 1 para um empréstimo atrasado'),
              ('A result is what state-based tests check, and a refactor keeps it.', 'Um resultado é o que testes baseados em estado conferem, e uma refatoração o mantém.')),
             (True, ('A catalogue lookup was called exactly twice', 'Uma consulta ao catálogo foi chamada exatamente duas vezes'),
              ('Right. A query\'s call count is how the code works today; caching or batching it changes the count and nothing else.',
               'Isso. A contagem de chamadas de uma consulta é como o código funciona hoje; um cache ou um lote muda a contagem e nada mais.')),
             (False, ('The message text was "\'Dom Casmurro\' was due on 2026-03-16"', 'O texto da mensagem foi "\'Dom Casmurro\' was due on 2026-03-16"'),
              ('The text is what the member reads; changing it is a change of behaviour, not a refactor.',
               'O texto é o que o membro lê; mudá-lo é mudança de comportamento, não refatoração.')),
         ]),
    # ---- where-tdd-struggles
    dict(id='ex-2k540r7k', section='where-tdd-struggles', type='quiz', difficulty='medium',
         prompt=('What did Nagappan and colleagues report in 2008 for four teams at Microsoft and IBM?',
                 'O que Nagappan e colegas relataram em 2008 sobre quatro equipes da Microsoft e da IBM?'),
         choices=[
             (False, ('Fewer defects and shorter development time, both by about half', 'Menos defeitos e desenvolvimento mais curto, os dois pela metade'),
              ('Defects fell, but development took longer by the managers\' estimates, not shorter.',
               'Os defeitos caíram, mas o desenvolvimento levou mais tempo pela estimativa dos gerentes, não menos.')),
             (True, ('Defect density down 40 to 90 per cent, time up 15 to 35', 'Densidade de defeitos 40 a 90 por cento menor, tempo 15 a 35 maior'),
              ('Right. A large quality gain bought with extra time, which is why the trade is argued about.',
               'Isso. Um ganho grande de qualidade comprado com tempo extra, e é por isso que a troca é discutida.')),
             (False, ('No measurable difference in defects, and no change in time', 'Nenhuma diferença mensurável em defeitos, e nenhuma mudança de tempo'),
              ('Some student studies found little effect; this industrial one found a large drop in defects.',
               'Alguns estudos com estudantes acharam pouco efeito; este, na indústria, achou uma queda grande de defeitos.')),
         ]),
    dict(id='ex-naahc1ts', section='where-tdd-struggles', type='quiz', difficulty='medium',
         prompt=('Fucci and colleagues (2017) looked for what explained differences in quality and productivity among professionals. What did they find?',
                 'Fucci e colegas (2017) procuraram o que explicava diferenças de qualidade e produtividade entre profissionais. O que acharam?'),
         choices=[
             (False, ('Writing the test before the code', 'Escrever o teste antes do código'),
              ('The order turned out not to explain the differences.', 'A ordem acabou não explicando as diferenças.')),
             (False, ('The number of tests each person had written by the end of the task', 'O número de testes que cada pessoa tinha escrito no fim da tarefa'),
              ('The study looked at the process, and the rhythm of steps was what mattered.',
               'O estudo olhou para o processo, e o ritmo dos passos foi o que importou.')),
             (True, ('Working in short, steady steps', 'Trabalhar em passos curtos e constantes'),
              ('Right. Granularity and steadiness explained more than test-first order did.',
               'Isso. Granularidade e constância explicaram mais do que a ordem do teste primeiro.')),
             (False, ('Using mocks for every collaborator from the outset', 'Usar mocks para todo colaborador desde o começo'),
              ('Mocking style was not what the study measured.', 'O estilo de mock não foi o que o estudo mediu.')),
         ]),
    # ---- drill
    dict(id='ex-n479ay7q', section='drill', type='quiz', difficulty='hard',
         prompt=('You must find out whether the library\'s old barcode scanner can be read from Python at all. How does the lesson suggest you start?',
                 'Você precisa descobrir se o leitor de código de barras antigo da biblioteca pode ser lido pelo Python. Como a lição sugere começar?'),
         choices=[
             (False, ('Write a failing test for read_barcode() and make it pass', 'Escrever um teste que falha para read_barcode() e fazê-lo passar'),
              ('You do not yet know what read_barcode should return, so there is nothing true to assert.',
               'Você ainda não sabe o que read_barcode deve devolver, então não há nada verdadeiro para afirmar.')),
             (True, ('A throwaway spike, then delete it and test-drive the real code', 'Um spike descartável, depois apagá-lo e guiar o código real por testes'),
              ('Right. The question is what the device does; learn it untested, then start again test-first.',
               'Isso. A pergunta é o que o aparelho faz; aprenda sem testes, depois recomece com o teste primeiro.')),
             (False, ('Mock the scanner and write the code against the mock', 'Fazer mock do leitor e escrever o código contra o mock'),
              ('A mock of a device you have never read encodes guesses, like the bare Mock that agreed with a missing method.',
               'Um mock de um aparelho que você nunca leu codifica palpites, como o Mock puro que concordou com um método inexistente.')),
         ]),
    dict(id='ex-0p4ep56f', section='drill', type='quiz', difficulty='hard',
         prompt=('A colleague types the full fine formula with max() straight away and the test passes. Was that wrong?',
                 'Uma colega digita a fórmula completa da multa com max() de cara e o teste passa. Isso foi errado?'),
         choices=[
             (False, ('Yes: TDD requires a constant first', 'Sim: o TDD exige uma constante primeiro'),
              ('Faking it is one of three strategies, used when unsure; it is not a rule.',
               'Fingir é uma das três estratégias, usada quando há dúvida; não é regra.')),
             (False, ('Yes, because the early-return case now has no test of its own', 'Sim, porque o caso de devolução antecipada agora não tem teste próprio'),
              ('That is a reason to add the test; it does not make the obvious implementation wrong.',
               'Isso é motivo para acrescentar o teste; não torna errada a implementação óbvia.')),
             (True, ('No, if she knew it; a surprising red would mean smaller steps', 'Não, se ela sabia; um vermelho surpreendente pediria passos menores'),
              ('Right. Obvious implementation is allowed, and the step size drops when the runs start surprising you.',
               'Isso. A implementação óbvia é permitida, e o tamanho do passo cai quando as execuções começam a surpreender.')),
             (False, ('No: once the formula is known, tests are not needed for it any more', 'Não: quando a fórmula é conhecida, os testes não são mais necessários'),
              ('The tests stay; they are what the later refactors rely on.', 'Os testes ficam; são eles que as refatorações seguintes usam.')),
         ]),
    dict(id='ex-9ax6ds7z', section='drill', type='quiz', difficulty='hard',
         prompt=('A suite of 300 tests goes red in 40 places every time somebody moves a private helper, though no feature changed. What is the most likely cause?',
                 'Uma suíte de 300 testes fica vermelha em 40 lugares toda vez que alguém move um auxiliar privado, embora nenhuma funcionalidade mude. Qual a causa mais provável?'),
         choices=[
             (True, ('The tests assert how the code works rather than what it does', 'Os testes afirmam como o código funciona, e não o que ele faz'),
              ('Right. Tests welded to the implementation turn every structural change red, which makes refactoring slower rather than safer.',
               'Isso. Testes soldados à implementação deixam toda mudança estrutural vermelha, o que torna a refatoração mais lenta em vez de mais segura.')),
             (False, ('Too few tests: 300 cannot cover a codebase that size', 'Testes de menos: 300 não cobrem uma base desse tamanho'),
              ('Adding more tests of the same kind would add more red, not less.', 'Acrescentar mais testes do mesmo tipo traria mais vermelho, não menos.')),
             (False, ('The team skipped the red step when writing them', 'A equipe pulou o passo vermelho ao escrevê-los'),
              ('Skipping red risks tests that never fail; these fail too readily, for structural reasons.',
               'Pular o vermelho arrisca testes que nunca falham; estes falham com facilidade demais, por motivos estruturais.')),
         ]),
]
