"""Lesson 16: reactive programming."""

EXERCISES = [
    # ---- push-and-pull
    dict(id='ex-4e65g8xg', section='push-and-pull', type='quiz', difficulty='easy',
         prompt=('In pull_push.py, why does the line "Iracema is back" never appear in the pull half?',
                 'Em pull_push.py, por que a linha "Iracema is back" nunca aparece na metade pull?'),
         choices=[
             (False, ('The generator raised an error on the third title and the loop swallowed it',
                      'O gerador lançou um erro no terceiro título e o laço o engoliu'),
              ('Nothing raised; the transcript shows no error, and a for loop does not swallow exceptions.',
               'Nada foi lançado; a transcrição não mostra erro, e um laço for não engole exceções.')),
             (True, ('Nobody asked for a third book',
                     'Ninguém pediu um terceiro livro'),
              ('Right. A generator runs only as far as the next value somebody requests, and islice stopped after two.',
               'Isso. Um gerador só roda até o próximo valor que alguém pede, e o islice parou depois de dois.')),
             (False, ('The desk printed it, but after the push half had started, so it scrolled away',
                      'O balcão imprimiu, mas depois que a metade push começou, e a linha sumiu'),
              ('The output is in order and complete; the push half prints its own three lines about the desk.',
               'A saída está em ordem e completa; a metade push imprime as próprias três linhas sobre o balcão.')),
         ]),
    dict(id='ex-dnh4b6qa', section='push-and-pull', type='matching', difficulty='medium',
         prompt=('Match each way of getting values to what gives you them.',
                 'Associe cada jeito de obter valores ao que os entrega.'),
         pairs=[
             (('one value, pulled', 'um valor, puxado'), ('a function call', 'uma chamada de função')),
             (('many values, pulled', 'muitos valores, puxados'), ('a generator', 'um gerador')),
             (('one value, pushed later', 'um valor, empurrado depois'), ('a promise or future', 'uma promise ou future')),
             (('many values, pushed', 'muitos valores, empurrados'), ('an observable', 'um observable')),
         ]),
    dict(id='ex-fed7kqsq', section='push-and-pull', type='quiz', difficulty='hard',
         prompt=('Which of these sources is a poor fit for pulling, so that a reactive design suits it?',
                 'Qual destas fontes combina mal com pull, de modo que um projeto reativo serve melhor?'),
         choices=[
             (False, ('A CSV file of last year\'s loans, read row by row', 'Um arquivo CSV com os empréstimos do ano passado, lido linha a linha'),
              ('A file waits for the next read; an ordinary loop over it is simpler and never holds more than it asked for.',
               'Um arquivo espera a próxima leitura; um laço comum sobre ele é mais simples e nunca guarda mais do que pediu.')),
             (False, ('A database cursor over the members table', 'Um cursor de banco de dados sobre a tabela de membros'),
              ('A cursor fetches when asked, so the consumer can set the pace, which is the strength of pull.',
               'Um cursor busca quando pedido, então o consumidor dita o ritmo, que é a força do pull.')),
             (True, ('Messages arriving on a socket from the self-service kiosks', 'Mensagens chegando num socket, vindas dos totens de autoatendimento da biblioteca'),
              ('Right. The kiosks send when a member uses them; the program cannot ask them to wait, which is the case push exists for.',
               'Isso. Os totens mandam quando um membro os usa; o programa não pode pedir que esperem, que é o caso para o qual o push existe.')),
             (False, ('A list of titles already in memory', 'Uma lista de títulos já na memória'),
              ('Everything is there before you start; looping over it is pull at its simplest.',
               'Está tudo ali antes de começar; percorrê-la é o pull na forma mais simples.')),
         ]),
    # ---- observables
    dict(id='ex-99cna1fx', section='observables', type='quiz', difficulty='easy',
         prompt=('returns = of("Dom Casmurro", "Vidas Secas") runs, and nothing else yet. What has been printed by the observable?',
                 'returns = of("Dom Casmurro", "Vidas Secas") roda, e mais nada por enquanto. O que o observable imprimiu?'),
         choices=[
             (True, ('Nothing: no one has subscribed', 'Nada: ninguém se inscreveu'),
              ('Right. An observable is a description; the producer runs inside subscribe.',
               'Isso. Um observable é uma descrição; o produtor roda dentro de subscribe.')),
             (False, ('Both titles, because of() pushes its values as soon as it is called',
                      'Os dois títulos, porque of() empurra os valores assim que é chamado'),
              ('of() only builds an Observable around a producer; the transcript prints "built; nothing has happened yet" first.',
               'of() só monta um Observable em volta de um produtor; a transcrição imprime "built; nothing has happened yet" primeiro.')),
             (False, ('The first title, held until a subscriber arrives', 'O primeiro título, guardado até chegar um inscrito'),
              ('Nothing is held: there is no buffer in Observable, only a function waiting to be called.',
               'Nada é guardado: não há buffer em Observable, só uma função esperando ser chamada.')),
         ]),
    dict(id='ex-vj6n35rp', section='observables', type='quiz', difficulty='medium',
         prompt=('The careless producer calls on_next("O Cortiço") after on_complete(). Why does the subscriber never see it?',
                 'O produtor descuidado chama on_next("O Cortiço") depois de on_complete(). Por que quem se inscreveu nunca o vê?'),
         choices=[
             (False, ('Python stops a function at the first call to a method named on_complete',
                      'O Python interrompe uma função na primeira chamada a um método chamado on_complete'),
              ('The producer keeps running; the call happens and the sink decides what to do with it.',
               'O produtor continua rodando; a chamada acontece e o sink decide o que fazer com ela.')),
             (True, ('The sink closed at the completion and ignores every later signal',
                     'O sink fechou na conclusão e passou a ignorar todo sinal posterior'),
              ('Right. The rule about endings is kept by Sink for every producer, so no producer has to remember it.',
               'Isso. A regra sobre o fim é mantida pelo Sink para todo produtor, então nenhum produtor precisa lembrar dela.')),
             (False, ('Titles are deduplicated, and O Cortiço was already sent', 'Títulos são deduplicados, e O Cortiço já tinha sido enviado'),
              ('Nothing deduplicates, and O Cortiço had not been sent; the producer sent Iracema before completing.',
               'Nada deduplica, e O Cortiço não tinha sido enviado; o produtor mandou Iracema antes de concluir.')),
             (False, ('subscribe returned before the producer could send it', 'subscribe retornou antes de o produtor conseguir enviá-lo'),
              ('The producer runs entirely inside subscribe, synchronously; it did send it, to a closed sink.',
               'O produtor roda inteiro dentro de subscribe, de forma síncrona; ele enviou, para um sink fechado.')),
         ]),
    dict(id='ex-va7eqpw6', section='observables', type='cloze', difficulty='easy',
         prompt=('A stream sends any number of values, then at most one ending: on_error or on____ , never both.',
                 'Um fluxo manda qualquer número de valores, depois no máximo um fim: on_error ou on____ , nunca os dois.'),
         blanks=[dict(en=['_complete'], pt=['_complete'])]),
    # ---- operators
    dict(id='ex-w8gybjmx', section='operators', type='quiz', difficulty='medium',
         prompt=('In the run of operators.py, what is printed immediately after "source: Vidas Secas, 3 days late"?',
                 'Na execução de operators.py, o que é impresso logo depois de "source: Vidas Secas, 3 days late"?'),
         choices=[
             (False, ('"source: Iracema, 0 days late", because the source sends all four before the operators run',
                      '"source: Iracema, 0 days late", porque a fonte manda as quatro antes de os operadores rodarem'),
              ('That is how three list comprehensions would behave. A stream sends each value down the whole chain first.',
               'É assim que três list comprehensions se comportariam. Um fluxo manda cada valor pela cadeia inteira primeiro.')),
             (True, ('"fines so far: 150 cents"', '"fines so far: 150 cents"'),
              ('Right. The value goes through filter_, map_ and scan before the source moves on.',
               'Isso. O valor passa por filter_, map_ e scan antes de a fonte seguir adiante.')),
             (False, ('"fines so far: 3 cents", because scan runs before map_', '"fines so far: 3 cents", porque scan roda antes de map_'),
              ('The operators run in the order written in pipe: filter_, then map_, then scan.',
               'Os operadores rodam na ordem escrita no pipe: filter_, depois map_, depois scan.')),
         ]),
    dict(id='ex-ea7ksfxk', section='operators', type='numeric', difficulty='medium',
         prompt=('A fifth return is added to operators.py after O Cortiço: ("Senhora", 2). What is the last running total printed, in cents?',
                 'Uma quinta devolução entra em operators.py depois de O Cortiço: ("Senhora", 2). Qual é o último total acumulado impresso, em centavos?'),
         hint=('The total before it was 400.', 'O total antes dela era 400.'),
         value=500, tolerance=0, unit=('cents', 'centavos')),
    dict(id='ex-nxd0yfab', section='operators', type='quiz', difficulty='medium',
         prompt=('fines = Observable(produce).pipe(filter_(...), map_(...), scan(...)) runs. What has happened to the source?',
                 'fines = Observable(produce).pipe(filter_(...), map_(...), scan(...)) roda. O que aconteceu com a fonte?'),
         choices=[
             (False, ('It ran once, and the results are cached for the first subscriber', 'Rodou uma vez, e os resultados ficam guardados para o primeiro inscrito'),
              ('There is no cache anywhere in the chain; each subscription runs the source again.',
               'Não há cache em lugar nenhum da cadeia; cada inscrição roda a fonte de novo.')),
             (False, ('It ran as far as filter_ and is waiting', 'Rodou até o filter_ e está esperando'),
              ('Nothing ran at all, not even the source; pipe only nests one description in another.',
               'Nada rodou, nem a fonte; o pipe só aninha uma descrição dentro de outra.')),
             (True, ('Nothing has run yet; pipe only built a description', 'Nada rodou ainda; o pipe só montou uma descrição'),
              ('Right. Subscribing to fines is what runs the subscriptions upstream and starts the source.',
               'Isso. Inscrever-se em fines é o que faz as inscrições correrem rio acima e dá a partida na fonte.')),
         ]),
    # ---- hot-and-cold
    dict(id='ex-r0n693ze', section='hot-and-cold', type='quiz', difficulty='easy',
         prompt=('In the hot half of hot_cold.py, what is the first title Bia sees?',
                 'Na metade quente de hot_cold.py, qual é o primeiro título que Bia vê?'),
         choices=[
             (False, ('Dom Casmurro, replayed to her when she subscribes', 'Dom Casmurro, repetido para ela quando se inscreve'),
              ('A plain Subject keeps no history; replaying is what ReplaySubject adds.',
               'Um Subject simples não guarda histórico; repetir é o que o ReplaySubject acrescenta.')),
             (True, ('Vidas Secas, the next title after she joined', 'Vidas Secas, o título logo após a entrada de Bia'),
              ('Right. She joined after Dom Casmurro went past, and a hot stream sends only what happens from then on.',
               'Isso. Ela entrou depois que Dom Casmurro passou, e um fluxo quente só manda o que acontece dali em diante.')),
             (False, ('None: a subscriber that joins late receives nothing at all', 'Nenhum: quem se inscreve tarde não recebe nada'),
              ('Joining late costs only what was already sent; Bia receives the next two titles.',
               'Entrar tarde só custa o que já foi enviado; Bia recebe os dois títulos seguintes.')),
         ]),
    dict(id='ex-g18btcgk', section='hot-and-cold', type='multiple-choice', difficulty='medium',
         prompt=('Which of these sources are hot? Choose all that apply.',
                 'Quais destas fontes são quentes? Marque todas que se aplicam.'),
         choices=[
             (True, ('Key presses in the search box of the catalogue page', 'Teclas digitadas na caixa de busca da página do catálogo'),
              ('Right. The user types whether or not anything is listening.', 'Isso. O usuário digita esteja algo ouvindo ou não.')),
             (False, ('An HTTP request for the list of new acquisitions', 'Uma requisição HTTP pela lista de aquisições novas'),
              ('Each subscription sends its own request, which is the cold behaviour that surprises people who subscribe twice.',
               'Cada inscrição manda a própria requisição, que é o comportamento frio que surpreende quem se inscreve duas vezes.')),
             (True, ('Scans from the barcode reader at the returns desk', 'Leituras do leitor de código de barras no balcão de devoluções'),
              ('Right. Books pass under the reader on their own schedule.', 'Isso. Os livros passam pelo leitor no horário deles.')),
             (False, ('of("Dom Casmurro", "Iracema")', 'of("Dom Casmurro", "Iracema")'),
              ('of() runs its producer for every subscriber from the first value, which is the definition of cold.',
               'of() roda o produtor para cada inscrito desde o primeiro valor, que é a definição de frio.')),
         ]),
    dict(id='ex-6bfk7a8d', section='hot-and-cold', type='quiz', difficulty='hard',
         prompt=('A page shows the member\'s loans in two places, and the server log shows two identical requests per page view. What is the likely fix?',
                 'Uma página mostra os empréstimos do membro em dois lugares, e o log do servidor mostra duas requisições idênticas por visita. Qual é a correção provável?'),
         choices=[
             (False, ('Make the server answer faster, so that the second request finds the first one\'s cache',
                      'Fazer o servidor responder mais rápido, para a segunda requisição achar o cache da primeira'),
              ('Speed does not change how many times a cold observable runs; there would still be two requests.',
               'Velocidade não muda quantas vezes um observable frio roda; continuariam sendo duas requisições.')),
             (True, ('Share one subscription to the request between both places on that page', 'Fazer as duas partes da tela dividirem uma única inscrição'),
              ('Right. The request is cold, so each subscriber starts its own; an operator such as share makes it one run with two listeners.',
               'Isso. A requisição é fria, então cada inscrito dá a própria partida; um operador como share a transforma numa execução com dois ouvintes.')),
             (False, ('Turn the request into a Subject that the page pushes values into', 'Transformar a requisição num Subject em que a página empurra valores'),
              ('A Subject is hot, but somebody still has to make the request and push the answer; share does that wiring for you.',
               'Um Subject é quente, mas alguém ainda precisa fazer a requisição e empurrar a resposta; o share faz essa ligação por você.')),
             (False, ('Unsubscribe the second place as soon as the first one gets its answer', 'Cancelar a inscrição do segundo lugar assim que o primeiro receber a resposta'),
              ('By then both requests have been sent; the second place would also show nothing.',
               'A essa altura as duas requisições já foram enviadas; e o segundo lugar não mostraria nada.')),
         ]),
    # ---- backpressure
    dict(id='ex-sf43x27w', section='backpressure', type='quiz', difficulty='medium',
         prompt=('Values arrive faster than they are handled, on average, all day, and an unbounded queue sits between. What happens?',
                 'Os valores chegam mais depressa do que são tratados, em média, o dia todo, com uma fila sem limite no meio. O que acontece?'),
         choices=[
             (True, ('The queue and each value\'s wait keep growing until memory runs out',
                     'A fila e a espera de cada valor continuam crescendo até a memória acabar'),
              ('Right. A queue absorbs a burst, never a rate; flood.py\'s oldest scan was already five seconds old after ten.',
               'Isso. Uma fila absorve uma rajada, nunca uma taxa; a leitura mais antiga do flood.py já tinha cinco segundos de idade depois de dez.')),
             (False, ('The queue smooths the rate out, so values are handled late but the backlog stays level',
                      'A fila suaviza a taxa, então os valores são tratados com atraso mas o acúmulo fica estável'),
              ('It stays level only if the average rate in equals the rate out; flood.py grows by three every second.',
               'Só fica estável se a taxa média de entrada for igual à de saída; o flood.py cresce três por segundo.')),
             (False, ('Python raises queue.Full once the queue reaches its default size', 'O Python lança queue.Full quando a fila chega ao tamanho padrão'),
              ('An unbounded queue has no size to reach; queue.Full exists only when maxsize is set.',
               'Uma fila sem limite não tem tamanho a atingir; queue.Full só existe quando maxsize está definido.')),
         ]),
    dict(id='ex-466qa7mp', section='backpressure', type='numeric', difficulty='easy',
         prompt=('In flood.py, scans arrive at 5 a second and the catalogue handles 2. How many scans are waiting after 20 seconds?',
                 'No flood.py, as leituras chegam a 5 por segundo e o catálogo trata 2. Quantas leituras estão esperando depois de 20 segundos?'),
         value=60, tolerance=0, unit=('scans', 'leituras')),
    dict(id='ex-mr2v9n54', section='backpressure', type='quiz', difficulty='hard',
         prompt=('A Reactive Streams subscriber calls request(1) after handling each value. What does that give it that blocking.py gets by blocking a thread?',
                 'Um inscrito de Reactive Streams chama request(1) depois de tratar cada valor. O que isso lhe dá que o blocking.py consegue bloqueando uma thread?'),
         choices=[
             (False, ('Values in a guaranteed order, which a queue cannot promise', 'Valores numa ordem garantida, que uma fila não pode prometer'),
              ('queue.Queue is first in, first out; blocking.py handled all twelve in order.',
               'A queue.Queue é a primeira a entrar, a primeira a sair; o blocking.py tratou as doze em ordem.')),
             (True, ('A producer that never sends more than the subscriber said it could take',
                     'Um produtor que nunca manda mais do que o inscrito disse que aguenta'),
              ('Right. Demand is the same backpressure without a waiting thread: the publisher holds its next value until a request arrives.',
               'Isso. A demanda é o mesmo backpressure sem uma thread esperando: o publicador segura o próximo valor até chegar um pedido.')),
             (False, ('A way to make the barcode scanner at the desk read more slowly', 'Um jeito de fazer o leitor do balcão ler mais devagar'),
              ('Demand works only when the producer can hold back; the scanner cannot, which is why section 07 exists.',
               'A demanda só funciona quando o produtor consegue se segurar; o leitor não consegue, e é por isso que a seção 07 existe.')),
             (False, ('Lost values counted automatically by the library', 'Valores perdidos contados automaticamente pela biblioteca'),
              ('With demand nothing is lost; counting losses belongs to the drop and latest strategies.',
               'Com demanda nada se perde; contar perdas é coisa das estratégias drop e latest.')),
         ]),
    # ---- strategies
    dict(id='ex-q32p73mg', section='strategies', type='matching', difficulty='medium',
         prompt=('Match each kind of data to the strategy the section recommends for a full queue.',
                 'Associe cada tipo de dado à estratégia que a seção recomenda para uma fila cheia.'),
         pairs=[
             (('loans being returned at the desk', 'empréstimos sendo devolvidos no balcão'), ('block, or a bounded buffer with an alarm', 'block, ou buffer com limite e alarme')),
             (('copies of a book on the shelf, sent on every change', 'exemplares de um livro na estante, enviados a cada mudança'), ('latest', 'latest')),
             (('page views for a weekly report', 'visualizações de página para um relatório semanal'), ('drop, with the drops counted', 'drop, com os descartes contados')),
         ]),
    dict(id='ex-9tyhvgz2', section='strategies', type='quiz', difficulty='medium',
         prompt=('In strategies.py, drop and latest each handled about a third of the scans. What does latest give that drop does not?',
                 'No strategies.py, drop e latest trataram cada um cerca de um terço das leituras. O que latest dá que drop não dá?'),
         choices=[
             (False, ('It loses fewer scans', 'Perde menos leituras'),
              ('It loses more: eight against drop\'s seven.', 'Perde mais: oito contra sete do drop.')),
             (True, ('The catalogue always works on the newest scan, ending with scan 12', 'O catálogo sempre trabalha na leitura mais nova, terminando na 12'),
              ('Right. Drop keeps the old scans and throws the new ones away, so its last handled scan is 10 and scan 12 is lost.',
               'Isso. O drop fica com as antigas e joga fora as novas, então a última que ele tratou foi a 10 e a 12 se perdeu.')),
             (False, ('A queue that can hold more than two scans when it needs to', 'Uma fila que guarda mais de duas leituras quando precisa'),
              ('Latest holds one at most; growing past the capacity is what buffer does.',
               'Latest guarda no máximo uma; crescer além da capacidade é o que o buffer faz.')),
         ]),
    dict(id='ex-g0cwygxh', section='strategies', type='quiz', difficulty='hard',
         prompt=('Block and buffer both handled all twelve scans and finished at tick 36. Where did block put the cost that buffer kept in memory?',
                 'Block e buffer trataram as doze leituras e terminaram no tick 36. Onde block pôs o custo que buffer guardou na memória?'),
         choices=[
             (False, ('Nowhere: block is simply the better strategy', 'Em lugar nenhum: block é simplesmente a estratégia melhor'),
              ('The difference between the rates has to go somewhere, and block only works on a producer that can wait.',
               'A diferença entre as taxas precisa ir para algum lugar, e block só funciona com um produtor que pode esperar.')),
             (False, ('In lost scans, counted in the lost column', 'Em leituras perdidas, contadas na coluna lost'),
              ('Block lost none; its lost column is 0, like buffer\'s.', 'Block não perdeu nenhuma; a coluna lost dele é 0, como a do buffer.')),
             (True, ('In the producer\'s time: the scanner finished at tick 31 instead of 12', 'No tempo do produtor: o leitor terminou no tick 31 em vez do 12'),
              ('Right. The difference between the two rates has to live somewhere: in a growing queue, or in a producer that waits.',
               'Isso. A diferença entre as duas taxas precisa ficar em algum lugar: numa fila que cresce, ou num produtor que espera.')),
         ]),
    # ---- in-your-language
    dict(id='ex-pmzpwwpx', section='in-your-language', type='quiz', difficulty='medium',
         prompt=('Why does RxJS have no request(n), when Reactor builds everything on it?',
                 'Por que o RxJS não tem request(n), quando o Reactor constrói tudo sobre ele?'),
         choices=[
             (False, ('JavaScript is single-threaded, so a producer can never be faster than its consumer',
                      'JavaScript tem uma thread só, então um produtor nunca pode ser mais rápido que o consumidor'),
              ('One thread does not stop events piling up; that is why RxJS ships throttleTime and sampleTime.',
               'Uma thread só não impede eventos de se acumularem; é por isso que o RxJS traz throttleTime e sampleTime.')),
             (True, ('Most browser sources are hot and cannot be slowed, so it offers lossy operators instead',
                     'A maioria das fontes do navegador é quente e não pode ser desacelerada, então ele oferece operadores com perda'),
              ('Right. A user does not click more slowly because a handler is busy.', 'Isso. Um usuário não clica mais devagar porque um tratador está ocupado.')),
             (False, ('It was written before Reactive Streams existed and has not caught up', 'Foi escrito antes de Reactive Streams existir e não se atualizou'),
              ('The section says it was decided on purpose: demand would have little to slow down in a browser.',
               'A seção diz que foi decidido de propósito: a demanda teria pouco o que desacelerar num navegador.')),
         ]),
    dict(id='ex-zc8kyxzx', section='in-your-language', type='quiz', difficulty='medium',
         prompt=('In Go, a send to a buffered channel is wrapped in select with a default case that increments dropped. Which strategy is that?',
                 'Em Go, um envio para um canal com buffer fica dentro de um select com um caso default que incrementa dropped. Que estratégia é essa?'),
         choices=[
             (False, ('block, because channels always block', 'block, porque canais sempre bloqueiam'),
              ('A plain send blocks; default runs exactly when the send would have to wait.',
               'Um envio simples bloqueia; o default roda justamente quando o envio teria de esperar.')),
             (False, ('latest, because the newest scan replaces the one in the channel', 'latest, porque a leitura mais nova substitui a que está no canal'),
              ('Nothing is taken out of the channel; the new scan is the one that goes.',
               'Nada é tirado do canal; a leitura nova é que vai embora.')),
             (True, ('drop, counted', 'drop, com contagem'),
              ('Right. When the channel is full, the new scan is discarded, and the counter makes the loss visible.',
               'Isso. Quando o canal está cheio, a leitura nova é descartada, e o contador torna a perda visível.')),
             (False, ('buffer, because the channel was made with a capacity', 'buffer, porque o canal foi criado com capacidade'),
              ('The capacity is a bound; an unbounded buffer would never reach the default case.',
               'A capacidade é um limite; um buffer sem limite nunca chegaria ao caso default.')),
         ]),
    # ---- drill
    dict(id='ex-r5afz6yn', section='drill', type='ordering', difficulty='hard',
         prompt=('fines.subscribe(...) is called in operators.py. Put what happens in order.',
                 'fines.subscribe(...) é chamado em operators.py. Ponha em ordem o que acontece.'),
         items=[('scan\'s producer subscribes to the observable map_ returned', 'O produtor de scan se inscreve no observable que map_ devolveu'),
                ('map_\'s producer subscribes to filter_\'s observable', 'O produtor de map_ se inscreve no observable de filter_'),
                ('filter_\'s producer subscribes to the source', 'O produtor de filter_ se inscreve na fonte'),
                ('The source pushes Dom Casmurro into filter_\'s callback', 'A fonte empurra Dom Casmurro no callback de filter_'),
                ('Vidas Secas reaches the subscriber as 150', 'Vidas Secas chega a quem se inscreveu como 150')],
         trap=('Subscriptions run upstream, from the end of the chain to the source, before any value comes down.',
               'As inscrições correm rio acima, do fim da cadeia até a fonte, antes de qualquer valor descer.')),
    dict(id='ex-vww6ec8q', section='drill', type='quiz', difficulty='hard',
         prompt=('A screen in the reading room shows how many study desks are free, from a sensor stream that changes many times a minute. Screens are switched on at any time of day. Which design fits?',
                 'Uma tela na sala de leitura mostra quantas mesas de estudo estão livres, a partir de um fluxo de sensores que muda muitas vezes por minuto. As telas são ligadas a qualquer hora do dia. Que projeto serve?'),
         choices=[
             (False, ('A cold observable that reads the sensors from the start for every screen, with a buffer so no change is lost',
                      'Um observable frio que lê os sensores desde o começo para cada tela, com buffer para nenhuma mudança se perder'),
              ('The sensors are hot and the past is worthless here; buffering every change only makes the screen show old counts.',
               'Os sensores são quentes e o passado não vale nada aqui; guardar cada mudança só faz a tela mostrar contagens velhas.')),
             (True, ('Hot, holding the current value for any newcomer, and latest for anyone who falls behind',
                     'Quente, guardando o valor atual para quem chega, e latest para quem fica para trás'),
              ('Right. Like a BehaviorSubject: a screen switched on at noon needs the count now, and only the newest count matters.',
               'Isso. Como um BehaviorSubject: uma tela ligada ao meio-dia precisa da contagem agora, e só a contagem mais nova importa.')),
             (False, ('A plain Subject, and block so that the sensors wait for the slowest screen',
                      'Um Subject simples, e block para os sensores esperarem a tela mais lenta'),
              ('A plain Subject gives a late screen nothing until the next change, and sensors cannot be made to wait.',
               'Um Subject simples não dá nada a uma tela atrasada até a próxima mudança, e sensores não podem ser obrigados a esperar.')),
         ]),
    dict(id='ex-93w5ajzn', section='drill', type='quiz', difficulty='hard',
         prompt=('Fine payments arrive from the bank as events, sometimes in bursts of hundreds. The handler records each one in the database. Which choice is wrong here?',
                 'Pagamentos de multa chegam do banco como eventos, às vezes em rajadas de centenas. O tratador registra cada um no banco de dados. Que escolha é errada aqui?'),
         choices=[
             (True, ('Latest, so the handler always works on the newest payment', 'Latest, para o tratador sempre trabalhar no pagamento mais novo'),
              ('Right, that is the wrong one. A payment is a fact: replacing one with the next loses money a member really paid.',
               'Isso, essa é a errada. Um pagamento é um fato: substituir um pelo próximo perde dinheiro que um membro pagou de verdade.')),
             (False, ('A bounded buffer with an alarm when it fills', 'Um buffer com limite e um alarme quando ele enche'),
              ('That one is sound: bursts end, nothing is lost, and the alarm says when they do not.',
               'Essa é sensata: rajadas acabam, nada se perde, e o alarme avisa quando não acabam.')),
             (False, ('Demand, if the bank\'s interface lets the handler ask for payments in batches',
                      'Demanda, se a interface do banco deixar o tratador pedir pagamentos em lotes'),
              ('That one is sound too: when the producer can hold back, letting the consumer set the pace loses nothing.',
               'Essa também é sensata: quando o produtor consegue se segurar, deixar o consumidor ditar o ritmo não perde nada.')),
         ]),
]
