"""Lesson 17: the actor model."""

EXERCISES = [
    # ---- the-shared-state-problem
    dict(id='ex-dvbjdf5d', section='the-shared-state-problem', type='quiz', difficulty='easy',
         prompt=('shared.py ends with minus one copy of Iracema. Which line of lend is wrong?',
                 'O shared.py termina com menos um exemplar de Iracema. Que linha de lend está errada?'),
         choices=[
             (False, ('The check, because it should test for more than one copy', 'A verificação, porque devia testar mais de um exemplar'),
              ('With one copy on the shelf, testing for more than one would refuse a loan that is allowed.',
               'Com um exemplar na estante, testar mais de um recusaria um empréstimo permitido.')),
             (True, ('None of them: the bug lives in the whole gap between the check and the act', 'Nenhuma: o bug está na brecha entre a verificação e a ação'),
              ('Right. Each line is correct; a second thread ran between them.', 'Isso. Cada linha está correta; uma segunda thread rodou entre elas.')),
             (False, ('The decrement, because -= on a dictionary is not allowed from a thread', 'O decremento, porque -= num dicionário não é permitido numa thread'),
              ('Any thread may write to the dictionary; that freedom is the problem, not a refusal.',
               'Qualquer thread pode escrever no dicionário; essa liberdade é o problema, não uma recusa.')),
         ]),
    dict(id='ex-23cccd47', section='the-shared-state-problem', type='matching', difficulty='medium',
         prompt=('Match each way out of the shared-state problem to what it does.',
                 'Associe cada saída do problema do estado compartilhado ao que ela faz.'),
         pairs=[
             (('a lock', 'um lock'), ('lets one thread at a time into the check-and-act', 'deixa uma thread de cada vez entrar no verificar-e-agir')),
             (('immutability', 'imutabilidade'), ('never changes shared data, only builds new values', 'nunca muda dados compartilhados, só constrói valores novos')),
             (('isolation', 'isolamento'), ('gives the data one owner that others send messages to', 'dá aos dados um dono a quem os outros mandam mensagens')),
         ]),
    dict(id='ex-erhxax4h', section='the-shared-state-problem', type='quiz', difficulty='hard',
         prompt=('Without the sleep, shared.py prints one lend and one refusal on every run you try. What does that tell you?',
                 'Sem o sleep, o shared.py imprime um empréstimo e uma recusa em toda execução que você tenta. O que isso diz?'),
         choices=[
             (False, ('The race only exists because of the sleep, so removing it fixes the program',
                      'A corrida só existe por causa do sleep, então tirá-lo conserta o programa'),
              ('The sleep only widens the gap; the operating system can switch threads at the same point without it.',
               'O sleep só alarga a brecha; o sistema operacional pode trocar de thread no mesmo ponto sem ele.')),
             (True, ('Little: the bad interleaving is rare, and rare per run is frequent per day of use',
                     'Pouco: a intercalação ruim é rara, e rara por execução é frequente por dia'),
              ('Right. A test that passes here proves nothing, which is why the fix is a design rule.',
               'Isso. Um teste que passa aqui não prova nada, e é por isso que a correção é uma regra de projeto.')),
             (False, ('Python runs threads one after the other, so they never overlap', 'O Python roda threads uma depois da outra, então elas nunca se sobrepõem'),
              ('The run with the sleep shows them overlapping; the interpreter switches threads between steps.',
               'A execução com o sleep mostra as duas se sobrepondo; o interpretador troca de thread entre passos.')),
         ]),
    # ---- actors
    dict(id='ex-gnh33qhh', section='actors', type='quiz', difficulty='medium',
         prompt=('A system holds a million actors on a machine with eight threads. How is that possible?',
                 'Um sistema tem um milhão de atores numa máquina com oito threads. Como isso é possível?'),
         choices=[
             (False, ('It is not: each actor needs a thread of its own', 'Não é: cada ator precisa de uma thread própria'),
              ('That confuses running code with owning state; an actor needs a thread only while it has messages.',
               'Isso confunde rodar código com ser dono de estado; um ator só precisa de thread enquanto tem mensagens.')),
             (False, ('The actors share their state, so one thread can serve many at once', 'Os atores dividem o estado, então uma thread atende muitos ao mesmo tempo'),
              ('Sharing state is exactly what actors never do; the threads are shared, the state is not.',
               'Dividir estado é justamente o que atores nunca fazem; as threads são divididas, o estado não.')),
             (True, ('Most actors are idle; a thread is lent only while one has work',
                     'A maioria fica parada; só ganha thread quem tem trabalho'),
              ('Right. An actor is a way of owning state; the runtime lends it a thread when there is work.',
               'Isso. Um ator é um jeito de ser dono de estado; o runtime lhe empresta uma thread quando há trabalho.')),
         ]),
    dict(id='ex-7srvya44', section='actors', type='multiple-choice', difficulty='medium',
         prompt=('While handling a message, which of these may an actor do? Choose all that apply.',
                 'Ao tratar uma mensagem, quais destas coisas um ator pode fazer? Marque todas que se aplicam.'),
         choices=[
             (True, ('Send messages to actors whose address it knows', 'Mandar mensagens a atores cujo endereço conhece'),
              ('Right. That is the first of Hewitt\'s three.', 'Isso. É a primeira das três de Hewitt.')),
             (True, ('Create new actors', 'Criar atores novos'),
              ('Right. That is the second.', 'Isso. É a segunda.')),
             (False, ('Read another actor\'s state directly, if it only reads', 'Ler o estado de outro ator diretamente, se só ler'),
              ('Reading is still access; the other actor may be changing it at that instant.',
               'Ler ainda é acesso; o outro ator pode estar mudando o estado naquele instante.')),
             (True, ('Decide how it will handle the next message', 'Decidir como vai tratar a próxima mensagem'),
              ('Right. That is how an actor\'s state changes.', 'Isso. É assim que o estado de um ator muda.')),
         ]),
    dict(id='ex-tmm03jg0', section='actors', type='cloze', difficulty='easy',
         prompt=('Messages for an actor wait in its ___ until it takes them out one at a time.',
                 'As mensagens para um ator esperam na sua ___ até ele tirá-las uma de cada vez.'),
         blanks=[dict(en=['mailbox', 'mail box', 'inbox'], pt=['caixa de correio', 'caixa postal', 'mailbox'])]),
    # ---- building-one
    dict(id='ex-tzhezqtd', section='building-one', type='quiz', difficulty='medium',
         prompt=('actor.py keeps the same time.sleep between check and act as shared.py. Why does the shelf no longer go below zero?',
                 'O actor.py mantém o mesmo time.sleep entre verificar e agir que o shared.py. Por que a estante não fica mais abaixo de zero?'),
         choices=[
             (True, ('The second Lend waits its turn in the mailbox', 'O segundo Lend espera a vez na caixa de correio'),
              ('Right. Only the actor\'s thread runs the check-and-act, one message at a time.',
               'Isso. Só a thread do ator roda o verificar-e-agir, uma mensagem de cada vez.')),
             (False, ('queue.Queue takes a lock around the whole of receive', 'A queue.Queue trava em volta do receive inteiro, do começo ao fim'),
              ('The queue locks only its own put and get; receive is safe because a single thread runs it.',
               'A fila trava só o próprio put e get; o receive é seguro porque uma thread só o roda.')),
             (False, ('The desks run one after the other in actor.py, not together', 'Os balcões rodam um depois do outro no actor.py, não juntos'),
              ('They still run at the same moment; what they do at once is put a message in the queue.',
               'Eles continuam rodando no mesmo instante; o que fazem ao mesmo tempo é pôr uma mensagem na fila.')),
         ]),
    dict(id='ex-apytgdah', section='building-one', type='quiz', difficulty='hard',
         prompt=('In Shelf.__init__, why is super().__init__() the last line rather than the first?',
                 'No Shelf.__init__, por que super().__init__() é a última linha e não a primeira?'),
         choices=[
             (False, ('Python requires the parent constructor to be called last', 'O Python exige que o construtor do pai seja chamado por último'),
              ('Python allows it anywhere; the order here is a choice with a reason.', 'O Python permite em qualquer lugar; a ordem aqui é uma escolha com motivo.')),
             (True, ('It starts the thread, and the state has to exist before that',
                     'Ele inicia a thread, e o estado tem de existir antes disso'),
              ('Right. Started first, the thread could take a message before _copies exists.',
               'Isso. Iniciada antes, a thread poderia pegar uma mensagem antes de _copies existir.')),
             (False, ('So that the mailbox is empty when the copies are set', 'Para a caixa de correio estar vazia quando os exemplares são definidos'),
              ('The mailbox is made by the parent; the risk is the thread, not the queue.', 'A caixa de correio é criada pelo pai; o risco é a thread, não a fila.')),
             (False, ('To let the subclass replace the mailbox with a bounded one', 'Para a subclasse poder trocar a caixa de correio por uma com limite'),
              ('Nothing in Shelf touches the mailbox.', 'Nada em Shelf toca a caixa de correio.')),
         ]),
    dict(id='ex-sbx4v3r2', section='building-one', type='quiz', difficulty='medium',
         prompt=('The north desk sends Lend and the south desk sends GiveBack at the same moment. In which order does the shelf receive them?',
                 'O balcão norte manda Lend e o balcão sul manda GiveBack no mesmo instante. Em que ordem a estante os recebe?'),
         choices=[
             (False, ('Lend first, because commands to take come before commands to return', 'Lend primeiro, porque pegar vem antes de devolver'),
              ('The mailbox knows nothing about meaning; it keeps arrival order.', 'A caixa de correio não sabe nada de significado; ela guarda a ordem de chegada.')),
             (False, ('Alphabetically by desk, because the queue sorts its senders', 'Em ordem alfabética de balcão, porque a fila ordena os remetentes'),
              ('A queue never sorts; it is first in, first out.', 'Uma fila nunca ordena; é a primeira a entrar, a primeira a sair.')),
             (True, ('Whichever arrives first; order is only promised per sender', 'O que chegar primeiro; a ordem só é prometida por remetente'),
              ('Right. A design needing that order makes one sender wait for the other.', 'Isso. Um projeto que precisa dessa ordem faz um remetente esperar o outro.')),
         ]),
    # ---- tell-and-ask
    dict(id='ex-mwdydvcg', section='tell-and-ask', type='quiz', difficulty='medium',
         prompt=('Why does the shelf not simply get a method available(title) that returns the count?',
                 'Por que a estante não ganha simplesmente um método available(title) que devolve a contagem?'),
         choices=[
             (True, ('It would read _copies from the caller\'s thread, the wrong one', 'Ele leria _copies na thread de quem chama, que é a errada'),
              ('Right. The answer has to come from the actor\'s own thread, so it comes back as a message.',
               'Isso. A resposta tem de vir da própria thread do ator, então volta como mensagem.')),
             (False, ('Methods cannot return values from a class that inherits from Actor', 'Métodos não podem devolver valores numa classe que herda de Actor'),
              ('They can; the problem is which thread runs the method.', 'Podem; o problema é qual thread roda o método.')),
             (False, ('A method call would be slower than sending a message', 'Uma chamada de método seria mais lenta que uma mensagem'),
              ('A call is faster; it is unsafe, which matters more.', 'Uma chamada é mais rápida; ela é insegura, o que pesa mais.')),
         ]),
    dict(id='ex-8hyvvc85', section='tell-and-ask', type='quiz', difficulty='hard',
         prompt=('Handling Recount, the shelf asks itself and times out after 0.5 s. Why would no answer ever come?',
                 'Ao tratar Recount, a estante pergunta a si mesma e desiste depois de 0,5 s. Por que resposta nenhuma viria?'),
         choices=[
             (False, ('Available is not a message the shelf knows how to handle', 'Available não é uma mensagem que a estante sabe tratar'),
              ('CountingShelf handles Available; the main thread\'s asks were answered.', 'O CountingShelf trata Available; os asks da thread principal foram respondidos.')),
             (True, ('Only the shelf\'s thread answers, and that thread is the one waiting',
                     'Só a thread da estante responde, e essa thread é a que está esperando'),
              ('Right. The question sits in the mailbox behind the message being handled.',
               'Isso. A pergunta fica na caixa de correio atrás da mensagem que está sendo tratada.')),
             (False, ('Futures cannot be passed inside a frozen dataclass', 'Futures não podem ir dentro de uma dataclass congelada'),
              ('Frozen means the field cannot be reassigned; the future inside still works, as the first asks show.',
               'Congelada quer dizer que o campo não pode ser reatribuído; o future dentro dela funciona, como os primeiros asks mostram.')),
         ]),
    dict(id='ex-ra3btppj', section='tell-and-ask', type='ordering', difficulty='medium',
         prompt=('A desk lends a book by telling, with no ask. Put the steps in order.',
                 'Um balcão empresta um livro só com tell, sem ask. Ponha os passos em ordem.'),
         items=[('The desk tells the shelf: lend Iracema to Bia, and reply to me', 'O balcão diz à estante: empreste Iracema à Bia, e me responda'),
                ('The shelf checks and takes a copy in one step', 'A estante verifica e pega um exemplar num passo só'),
                ('The shelf tells the desk Lent or Refused', 'A estante diz ao balcão Lent ou Refused'),
                ('The desk handles the reply as its next message', 'O balcão trata a resposta como sua próxima mensagem')],
         trap=('Asking first whether a copy is free and then telling the shelf to lend reopens the gap between check and act.',
               'Perguntar primeiro se há exemplar livre e depois mandar emprestar reabre a brecha entre verificar e agir.')),
    # ---- supervision
    dict(id='ex-73nm62c8', section='supervision', type='numeric', difficulty='medium',
         prompt=('In supervision.py, Iracema starts with 2 copies and is lent twice, with a crash and restart in between. How many copies does the shelf report after the second loan?',
                 'No supervision.py, Iracema começa com 2 exemplares e é emprestado duas vezes, com uma queda e um reinício no meio. Quantos exemplares a estante informa depois do segundo empréstimo?'),
         value=1, tolerance=0, unit=('copies', 'exemplares')),
    dict(id='ex-6wb5acjt', section='supervision', type='quiz', difficulty='medium',
         prompt=('A restarted shelf forgot a loan. What does the section say should change?',
                 'Uma estante reiniciada esqueceu um empréstimo. O que a seção diz que deveria mudar?'),
         choices=[
             (False, ('The supervisor should copy the old shelf\'s state into the new one', 'O supervisor devia copiar o estado da estante antiga para a nova'),
              ('The old state is the state that led to the crash; restarting clean is the point.',
               'O estado antigo é o que levou à queda; recomeçar limpo é o objetivo.')),
             (True, ('State that must survive a crash belongs somewhere durable', 'Estado que precisa sobreviver a uma queda deve ficar num lugar durável'),
              ('Right. A database or an event log the new instance replays, as in lesson 9.',
               'Isso. Um banco de dados ou um log de eventos que a instância nova reexecuta, como na lição 9.')),
             (False, ('The shelf should catch every exception so that it never needs a restart',
                      'A estante devia capturar toda exceção para nunca precisar de reinício'),
              ('That is the defensive code the section argues against: running on in states nobody designed.',
               'Esse é o código defensivo contra o qual a seção argumenta: seguir rodando em estados que ninguém projetou.')),
         ]),
    dict(id='ex-67t5vwy8', section='supervision', type='quiz', difficulty='hard',
         prompt=('A member types a title the library does not hold. How should the shelf actor respond?',
                 'Um membro digita um título que a biblioteca não tem. Como o ator da estante deve responder?'),
         choices=[
             (False, ('Crash, so that the supervisor restarts it with a clean state', 'Cair, para o supervisor o reiniciar com estado limpo'),
              ('A typo is expected input; crashing would spend a restart and lose state for nothing.',
               'Um erro de digitação é entrada esperada; cair gastaria um reinício e perderia estado à toa.')),
             (False, ('Ignore the message, since it cannot be handled', 'Ignorar a mensagem, já que não dá para tratá-la'),
              ('Ignoring it is a silent failure: the member waits for an answer that never comes.',
               'Ignorar é uma falha silenciosa: o membro espera uma resposta que nunca vem.')),
             (True, ('With an ordinary reply saying there is no such title', 'Com uma resposta comum dizendo que o título não existe'),
              ('Right. Validate expected problems at the edge; let the inside crash on the impossible.',
               'Isso. Valide os problemas esperados na borda; deixe o interior cair diante do impossível.')),
         ]),
    # ---- location-transparency
    dict(id='ex-knspagyk', section='location-transparency', type='quiz', difficulty='medium',
         prompt=('In location.py, ref.tell(threading.Lock()) raises TypeError at once. What does that show?',
                 'No location.py, ref.tell(threading.Lock()) lança TypeError na hora. O que isso mostra?'),
         choices=[
             (True, ('A message must become bytes, so shared state cannot travel',
                     'Uma mensagem precisa virar bytes, e estado compartilhado não viaja'),
              ('Right. The rule that messages are values becomes something the transport enforces.',
               'Isso. A regra de que mensagens são valores vira algo que o transporte impõe.')),
             (False, ('The shelf process refused the lock because it already holds one', 'O processo da estante recusou o lock porque já segura outro lock'),
              ('The shelf never saw it: the error came from pickling on the sending side.',
               'A estante nem viu: o erro veio do pickle, do lado de quem envia.')),
             (False, ('Ref.tell only accepts frozen dataclasses', 'O Ref.tell só aceita dataclasses congeladas'),
              ('Ref.tell sends whatever it is given; None goes through at the end.',
               'O Ref.tell manda o que receber; o None passa no final.')),
         ]),
    dict(id='ex-x6vckksj', section='location-transparency', type='quiz', difficulty='medium',
         prompt=('Why does an ask without a timeout become more dangerous once the actor runs on another machine?',
                 'Por que um ask sem timeout fica mais perigoso quando o ator roda em outra máquina?'),
         choices=[
             (False, ('Remote actors answer more slowly, so the default wait is too short', 'Atores remotos respondem mais devagar, então a espera padrão é curta demais'),
              ('There is no wait limit at all without a timeout; that is the danger.', 'Sem timeout não há limite de espera nenhum; esse é o perigo.')),
             (True, ('A lost reply now makes it hang, not just a bug', 'Uma resposta perdida agora o trava, não só um bug'),
              ('Right. Networks lose messages, and a silent machine looks like a slow one.',
               'Isso. Redes perdem mensagens, e uma máquina calada parece uma lenta.')),
             (False, ('Futures cannot cross a network, so the ask fails at once', 'Futures não atravessam a rede, então o ask falha na hora'),
              ('Remote systems use a reply address that can cross; the failure is the wait, not the send.',
               'Sistemas remotos usam um endereço de resposta que atravessa; a falha é a espera, não o envio.')),
             (False, ('The remote supervisor cancels every ask when it restarts the actor', 'O supervisor remoto cancela todo ask quando reinicia o ator'),
              ('Nothing cancels the ask; the caller just waits for a reply that will not come.',
               'Nada cancela o ask; quem chamou só espera uma resposta que não vem.')),
         ]),
    dict(id='ex-e49csqnt', section='location-transparency', type='quiz', difficulty='hard',
         prompt=('A desk retries GiveBack when no acknowledgement arrives in two seconds. What must the shelf\'s handler be?',
                 'Um balcão reenvia GiveBack quando nenhuma confirmação chega em dois segundos. O que o tratador da estante precisa ser?'),
         choices=[
             (False, ('Faster than two seconds, so the retry never happens', 'Mais rápido que dois segundos, para o reenvio nunca acontecer'),
              ('A lost acknowledgement triggers the retry however fast the handler was.', 'Uma confirmação perdida dispara o reenvio por mais rápido que o tratador tenha sido.')),
             (False, ('Supervised by the desk, so that the desk can restart it', 'Supervisionado pelo balcão, para o balcão poder reiniciá-lo'),
              ('Supervision handles crashes; it does nothing about a message arriving twice.', 'A supervisão trata quedas; não faz nada quanto a uma mensagem chegando duas vezes.')),
             (True, ('Idempotent: the same return handled twice must count once', 'Idempotente: a mesma devolução tratada duas vezes conta só uma'),
              ('Right. A retry after a lost acknowledgement delivers the message twice.', 'Isso. Um reenvio depois de uma confirmação perdida entrega a mensagem duas vezes.')),
         ]),
    # ---- in-your-language
    dict(id='ex-gxxcfze9', section='in-your-language', type='quiz', difficulty='medium',
         prompt=('What separates a goroutine reading a channel from an actor with a mailbox?',
                 'O que separa uma goroutine lendo um canal de um ator com caixa de correio?'),
         choices=[
             (False, ('A goroutine cannot hold state between messages', 'Uma goroutine não consegue guardar estado entre mensagens'),
              ('The shelf goroutine keeps its map across requests; that is what makes it actor-like.',
               'A goroutine da estante mantém o map entre pedidos; é isso que a deixa parecida com um ator.')),
             (True, ('The channel is shared, and a send waits for a receiver',
                     'O canal é compartilhado, e um envio espera um receptor'),
              ('Right. An actor has the address, and its tell never waits.', 'Isso. Um ator tem o endereço, e o tell dele nunca espera.')),
             (False, ('Goroutines run in separate processes with separate memory', 'Goroutines rodam em processos separados com memória separada'),
              ('Goroutines share one process\'s memory; Erlang\'s processes are the ones with separate memory.',
               'Goroutines dividem a memória de um processo; os processos do Erlang é que têm memória separada.')),
         ]),
    dict(id='ex-895mn7m5', section='in-your-language', type='quiz', difficulty='hard',
         prompt=('In the Akka example, the Lend handler returns shelf(withOneLess(copies, ...)) instead of changing a field. Which idea is that?',
                 'No exemplo do Akka, o tratador de Lend devolve shelf(withOneLess(copies, ...)) em vez de mudar um campo. Que ideia é essa?'),
         choices=[
             (True, ('Choosing the behaviour for the next message, with the state built new', 'Escolher o comportamento da próxima mensagem, com estado novo'),
              ('Right. Hewitt\'s third rule, written literally, with lesson 15\'s immutability.',
               'Isso. A terceira regra de Hewitt, escrita ao pé da letra, com a imutabilidade da lição 15.')),
             (False, ('Restarting the actor after every message, as a supervisor would', 'Reiniciar o ator depois de toda mensagem, como um supervisor faria'),
              ('Nothing failed; returning a behaviour is the normal path, and the new state carries the loan.',
               'Nada falhou; devolver um comportamento é o caminho normal, e o estado novo carrega o empréstimo.')),
             (False, ('Recursion that grows the stack with each message until it overflows', 'Recursão que cresce a pilha a cada mensagem até estourar'),
              ('The function returns a description of the next behaviour; Akka calls it later, so no stack builds up.',
               'A função devolve uma descrição do próximo comportamento; o Akka a chama depois, então nenhuma pilha se acumula.')),
         ]),
    # ---- drill
    dict(id='ex-fxv7zsry', section='drill', type='numeric', difficulty='hard',
         prompt=('supervision.py is run again with max_restarts=3 and the same six messages. How many of them change the shelf\'s copies?',
                 'O supervision.py roda de novo com max_restarts=3 e as mesmas seis mensagens. Quantas delas mudam os exemplares da estante?'),
         hint=('The three GiveBacks of unknown titles crash; now none of them exhausts the limit.',
               'Os três GiveBack de títulos desconhecidos derrubam a estante; agora nenhum deles esgota o limite.'),
         value=3, tolerance=0, unit=('messages', 'mensagens')),
    dict(id='ex-1rjan35c', section='drill', type='quiz', difficulty='hard',
         prompt=('A loans actor asks the members actor whether a member may borrow, and the members actor asks the loans actor how many books she holds. What happens under load?',
                 'Um ator de empréstimos pergunta ao ator de membros se um membro pode pegar livro, e o ator de membros pergunta ao de empréstimos quantos livros ela tem. O que acontece sob carga?'),
         choices=[
             (False, ('Nothing bad: each actor handles one message at a time, so no race is possible',
                      'Nada de ruim: cada ator trata uma mensagem de cada vez, então nenhuma corrida é possível'),
              ('No race inside each actor, but each can block waiting on the other: that is a deadlock, not a race.',
               'Nenhuma corrida dentro de cada ator, mas cada um pode bloquear esperando o outro: isso é deadlock, não corrida.')),
             (True, ('Each one waits on the other, and both stop handling their mailboxes',
                     'Cada um espera o outro, e os dois param de tratar as caixas de correio'),
              ('Right. Two actors asking each other deadlock; tell with a reply address avoids it.',
               'Isso. Dois atores que perguntam um ao outro travam; tell com endereço de resposta evita isso.')),
             (False, ('The supervisor notices the slow replies and restarts both actors', 'O supervisor percebe as respostas lentas e reinicia os dois atores'),
              ('A supervisor reacts to crashes; a blocked actor has not crashed, unless a timeout turns the hang into an error.',
               'Um supervisor reage a quedas; um ator bloqueado não caiu, a não ser que um timeout transforme o travamento em erro.')),
             (False, ('Messages are dropped once each mailbox reaches its default size', 'Mensagens são descartadas quando cada caixa de correio chega ao tamanho padrão'),
              ('The default mailboxes here are unbounded; they grow while both actors wait.',
               'As caixas de correio padrão aqui não têm limite; elas crescem enquanto os dois atores esperam.')),
         ]),
    dict(id='ex-f35fwckn', section='drill', type='quiz', difficulty='hard',
         prompt=('The kiosks and both desks update a count of visitors today, and it comes out too low at closing time. Which fix matches this lesson?',
                 'Os totens e os dois balcões atualizam uma contagem de visitantes do dia, e ela sai baixa demais no fechamento. Que correção corresponde a esta lição?'),
         choices=[
             (False, ('Read the count twice before writing it, to check that nobody changed it', 'Ler a contagem duas vezes antes de escrever, para conferir que ninguém mudou'),
              ('Another writer can still run between the second read and the write; the gap only moves.',
               'Outro escritor ainda pode rodar entre a segunda leitura e a escrita; a brecha só muda de lugar.')),
             (True, ('One counter actor owns the count, and everyone tells it Visited', 'Um ator contador é dono da contagem, e todos lhe dizem Visited'),
              ('Right. Only one thread changes the count, so no update is lost.', 'Isso. Só uma thread muda a contagem, então nenhuma atualização se perde.')),
             (False, ('Give each kiosk its own copy of the count and let them overwrite the total', 'Dar a cada totem a própria cópia da contagem e deixar que sobrescrevam o total'),
              ('Overwriting the total loses every other writer\'s increments, which is the bug itself.',
               'Sobrescrever o total perde os incrementos de todos os outros, que é o próprio bug.')),
         ]),
]
