"""Lesson 18: concurrency and parallelism."""

EXERCISES = [
    # ---- concurrency-and-parallelism
    dict(id='ex-58fbfgxn', section='concurrency-and-parallelism', type='quiz', difficulty='easy',
         prompt=('In models.py, four threads built the four overdue reports. Why were they no faster than one thread?',
                 'Em models.py, quatro threads montaram os quatro relatórios de atraso. Por que não foram mais rápidas que uma thread?'),
         choices=[
             (False, ('Creating four threads cost more than the reports themselves', 'Criar quatro threads custou mais que os próprios relatórios'),
              ('Starting a thread takes microseconds; the reports took over a second.',
               'Iniciar uma thread leva microssegundos; os relatórios levaram mais de um segundo.')),
             (True, ('The GIL let one of them run Python at a time', 'A GIL deixou uma delas rodar Python por vez'),
              ('Right. Arithmetic holds the interpreter lock, so the threads took turns on one core.',
               'Isso. Aritmética segura a trava do interpretador, então as threads se revezaram num núcleo.')),
             (False, ('The laptop had only one core for the four of them to share', 'O notebook tinha um núcleo só para as quatro dividirem'),
              ('It had four, and the four processes used them: the same work took about a third of the time.',
               'Tinha quatro, e os quatro processos os usaram: o mesmo trabalho levou cerca de um terço do tempo.')),
             (False, ('ThreadPoolExecutor runs the jobs one after another unless told otherwise', 'O ThreadPoolExecutor roda os trabalhos em sequência a menos que alguém diga o contrário'),
              ('The same pool overlapped the four lookups, finishing them in a quarter of the time.',
               'O mesmo pool sobrepôs as quatro consultas e terminou em um quarto do tempo.')),
         ]),
    dict(id='ex-kq5xt033', section='concurrency-and-parallelism', type='cloze', difficulty='easy',
         prompt=('On the ordinary CPython build, only one thread at a time runs Python bytecode, because of the global interpreter ___ .',
                 'Na versão comum do CPython, só uma thread por vez executa bytecode Python, por causa da trava global do ___ .'),
         blanks=[dict(en=['lock'], pt=['interpretador', 'interpreter'])]),
    dict(id='ex-yqx795na', section='concurrency-and-parallelism', type='quiz', difficulty='medium',
         prompt=('In asyncio, where can another task start running in the middle of your coroutine?',
                 'No asyncio, em que ponto outra tarefa pode começar a rodar no meio da sua corrotina?'),
         choices=[
             (False, ('Between any two bytecodes, as with threads', 'Entre quaisquer dois bytecodes, como com threads'),
              ('That is the threading row of the table; asyncio has one thread and does not preempt it.',
               'Essa é a linha de threading da tabela; o asyncio tem uma thread e não a interrompe.')),
             (False, ('Every few milliseconds, when the event loop decides the coroutine has run for long enough', 'A cada poucos milissegundos, quando o event loop decide que a corrotina já rodou bastante'),
              ('The loop never takes control back by itself; a coroutine that never awaits blocks everything else.',
               'O loop nunca retoma o controle sozinho; uma corrotina que nunca faz await bloqueia todo o resto.')),
             (True, ('Only at an await', 'Só num await'),
              ('Right. The switch points are written in the code, which is what makes asyncio cooperative.',
               'Isso. Os pontos de troca estão escritos no código, e é isso que torna o asyncio cooperativo.')),
         ]),
    # ---- race-conditions
    dict(id='ex-wbyhht4q', section='race-conditions', type='numeric', difficulty='medium',
         prompt=('The counter stands at 10. Three desks each run record() from race.py, and all three read the counter before any of them writes. How many of the three loans are lost?',
                 'O contador está em 10. Três balcões rodam o record() de race.py, e os três leem o contador antes de qualquer um escrever. Quantos dos três empréstimos se perdem?'),
         hint=('Each desk writes the value it read, plus one.', 'Cada balcão escreve o valor que leu, mais um.'),
         value=2, tolerance=0, unit=('loans', 'empréstimos')),
    dict(id='ex-198zdrx7', section='race-conditions', type='quiz', difficulty='medium',
         prompt=('plus_equals.py lost no updates in four million. What does that run show about counter.issued += 1?',
                 'plus_equals.py não perdeu nenhuma atualização em quatro milhões. O que essa execução mostra sobre counter.issued += 1?'),
         choices=[
             (False, ('That += is a single atomic operation in Python', 'Que += é uma operação atômica única em Python'),
              ('It is still a read, an addition and a write; 3.12 happens not to switch between them.',
               'Continua sendo uma leitura, uma soma e uma escrita; o 3.12 calha de não trocar no meio delas.')),
             (True, ('Only that the window was not hit in that run on 3.12', 'Só que o vão não foi atingido naquela execução no 3.12'),
              ('Right. Nothing in the language promises it, and the free-threaded build or an extra call reopens it.',
               'Isso. Nada na linguagem promete isso, e a versão free-threaded ou uma chamada a mais o reabre.')),
             (False, ('That the GIL protects any program\'s shared data from races', 'Que a GIL protege de corridas os dados compartilhados de qualquer programa'),
              ('race.py ran under the same GIL and lost three quarters of its updates.',
               'race.py rodou sob a mesma GIL e perdeu três quartos das atualizações.')),
             (False, ('That a million iterations is too few to show a race', 'Que um milhão de iterações é pouco demais para mostrar uma corrida'),
              ('race.py showed one in four thousand; the count of iterations is not what decides it.',
               'race.py mostrou uma em quatro mil; o número de iterações não é o que decide.')),
         ]),
    dict(id='ex-9qnxh7ea', section='race-conditions', type='quiz', difficulty='hard',
         prompt=('Two threads read the same list of loans, and neither ever changes it. Is there a race?',
                 'Duas threads leem a mesma lista de empréstimos, e nenhuma a muda nunca. Existe corrida?'),
         choices=[
             (True, ('No: with no writer, there is nothing to interleave badly', 'Não: sem escritor, não há nada a intercalar mal'),
              ('Right. A race needs shared state, at least one writer and a non-atomic step; this has no writer.',
               'Isso. Uma corrida precisa de estado compartilhado, pelo menos um escritor e um passo não atômico; aqui não há escritor.')),
             (False, ('Yes, because the list is shared between two threads', 'Sim, porque a lista é compartilhada entre duas threads'),
              ('Sharing alone is not enough; reading the same unchanging list in any order gives the same answer.',
               'Compartilhar sozinho não basta; ler a mesma lista que não muda, em qualquer ordem, dá a mesma resposta.')),
             (False, ('Yes, unless each thread is given its own copy of the list before it starts', 'Sim, a menos que cada thread receba sua própria cópia da lista antes de começar'),
              ('Copies would also be safe, and they are not needed; the list already cannot change under either reader.',
               'Cópias também seriam seguras, e não são necessárias; a lista já não muda debaixo de nenhum dos leitores.')),
         ]),
    # ---- locks
    dict(id='ex-atdjwayv', section='locks', type='quiz', difficulty='medium',
         prompt=('Why does locks.py create the lock inside LoanCounter rather than asking each desk to take one?',
                 'Por que locks.py cria a trava dentro de LoanCounter em vez de pedir que cada balcão pegue uma?'),
         choices=[
             (False, ('A lock created outside a class cannot be used with a with statement', 'Uma trava criada fora de uma classe não pode ser usada num with'),
              ('Any Lock works with with, wherever it was made.', 'Qualquer Lock funciona com with, onde quer que tenha sido criada.')),
             (True, ('So taking it is not something a caller has to remember', 'Para nenhum chamador ter de lembrar da trava'),
              ('Right. The lock sits next to the state it guards, which is lesson 1\'s encapsulation doing a new job.',
               'Isso. A trava fica ao lado do estado que protege, o encapsulamento da lição 1 fazendo um trabalho novo.')),
             (False, ('Inside the class it makes record() run in parallel on all four cores', 'Dentro da classe ela faz record() rodar em paralelo nos quatro núcleos'),
              ('A lock does the opposite: it lets one thread at a time through those steps.',
               'Uma trava faz o contrário: deixa uma thread por vez passar por aqueles passos.')),
         ]),
    dict(id='ex-qwcf1ekn', section='locks', type='quiz', difficulty='medium',
         prompt=('What makes the second deadlock.py unable to deadlock?',
                 'O que torna o segundo deadlock.py incapaz de entrar em deadlock?'),
         choices=[
             (False, ('The timeout on the second lock, which breaks the wait after a second', 'O timeout na segunda trava, que quebra a espera depois de um segundo'),
              ('The first version had the same timeout and still deadlocked until it fired.',
               'A primeira versão tinha o mesmo timeout e ainda assim travou até ele disparar.')),
             (False, ('Using an RLock, so each thread can take its own lock twice', 'Usar uma RLock, para cada thread poder pegar a própria trava duas vezes'),
              ('Both versions use a plain Lock, and the deadlock was between two threads, not one thread and itself.',
               'As duas versões usam Lock comum, e o deadlock era entre duas threads, não entre uma thread e ela mesma.')),
             (True, ('Both swaps take the locks in member-number order', 'As duas trocas pegam as travas na ordem do número do membro'),
              ('Right. With one agreed order the cycle of waiting cannot form.',
               'Isso. Com uma ordem combinada, o ciclo de espera não tem como se formar.')),
             (False, ('Sorting the log, so the lines no longer depend on which thread wrote first', 'Ordenar o log, para as linhas não dependerem de qual thread escreveu primeiro'),
              ('Both versions sort the log; that only fixes the order of the printed lines.',
               'As duas versões ordenam o log; isso só fixa a ordem das linhas impressas.')),
         ]),
    dict(id='ex-mnn0egsm', section='locks', type='quiz', difficulty='easy',
         prompt=('In the first deadlock.py, what would have happened without timeout=1?',
                 'No primeiro deadlock.py, o que teria acontecido sem timeout=1?'),
         choices=[
             (False, ('Python would raise a DeadlockError after a few seconds', 'O Python lançaria um DeadlockError depois de alguns segundos'),
              ('Python has no such error; nothing notices a cycle of plain locks.',
               'O Python não tem esse erro; nada percebe um ciclo de travas comuns.')),
             (True, ('Both threads would wait forever, printing nothing', 'As duas threads esperariam para sempre, sem imprimir nada'),
              ('Right. A deadlocked program uses no processor and looks exactly like one that is thinking.',
               'Isso. Um programa em deadlock não usa processador e parece exatamente um programa pensando.')),
             (False, ('One swap would finish and the other would be cancelled', 'Uma troca terminaria e a outra seria cancelada'),
              ('That is what the timeout made happen; without it, nothing lets go.',
               'Isso é o que o timeout fez acontecer; sem ele, ninguém solta nada.')),
         ]),
    # ---- singleton-under-threads
    dict(id='ex-njrtjjgm', section='singleton-under-threads', type='quiz', difficulty='medium',
         prompt=('The first catalogue.py created four catalogues. What let that happen?',
                 'O primeiro catalogue.py criou quatro catálogos. O que permitiu isso?'),
         choices=[
             (False, ('Each thread imported its own copy of the module', 'Cada thread importou sua própria cópia do módulo'),
              ('A module is executed once per process; all four threads shared one _instance.',
               'Um módulo é executado uma vez por processo; as quatro threads compartilharam um _instance.')),
             (False, ('The global statement gives every thread a private _instance variable', 'O comando global dá a cada thread uma variável _instance privada'),
              ('global means the module\'s variable, the same one for every thread.',
               'global quer dizer a variável do módulo, a mesma para toda thread.')),
             (True, ('All four checked _instance before any constructor finished', 'As quatro olharam _instance antes de um construtor acabar'),
              ('Right. Check-then-act, with the whole slow constructor inside the gap.',
               'Isso. Verificar-depois-agir, com o construtor lento inteiro dentro do vão.')),
         ]),
    dict(id='ex-831a09vj', section='singleton-under-threads', type='quiz', difficulty='hard',
         prompt=('In the fixed get_catalogue, why is _instance checked a second time inside the lock?',
                 'No get_catalogue corrigido, por que _instance é verificado uma segunda vez dentro da trava?'),
         choices=[
             (True, ('A thread that waited at the lock may find a winner already built it', 'Quem esperou na trava talvez ache o objeto já pronto por outro'),
              ('Right. Without the second check, each waiting thread would build its own after the first one left.',
               'Isso. Sem a segunda verificação, cada thread que esperava construiria o seu depois que a primeira saísse.')),
             (False, ('The first check could raise an error if _instance was never assigned', 'A primeira verificação poderia lançar erro se _instance nunca tivesse sido atribuído'),
              ('_instance is set to None at import, so the first check always has something to read.',
               '_instance recebe None na importação, então a primeira verificação sempre tem o que ler.')),
             (False, ('To make the first check unnecessary, so it can be removed later', 'Para tornar a primeira verificação desnecessária e poder removê-la depois'),
              ('The first check is what spares every later caller the cost of locking; both stay.',
               'A primeira verificação é o que poupa todo chamador posterior do custo da trava; as duas ficam.')),
             (False, ('Python reloads global variables each time a lock is acquired', 'O Python recarrega as variáveis globais toda vez que uma trava é pega'),
              ('Nothing is reloaded; the value may simply have changed while the thread waited.',
               'Nada é recarregado; o valor pode simplesmente ter mudado enquanto a thread esperava.')),
         ]),
    dict(id='ex-j29mg2wh', section='singleton-under-threads', type='quiz', difficulty='medium',
         prompt=('Why is CATALOGUE = Catalogue() at the top of a module safe however many threads import it?',
                 'Por que CATALOGUE = Catalogue() no topo de um módulo é seguro não importa quantas threads o importem?'),
         choices=[
             (False, ('Module-level objects are frozen by Python after the import finishes', 'Objetos no nível do módulo são congelados pelo Python depois da importação'),
              ('Nothing is frozen; the object can still be changed. What is guaranteed is that it is built once.',
               'Nada é congelado; o objeto ainda pode mudar. O que é garantido é que ele é construído uma vez.')),
             (True, ('The module body runs once, under the import system\'s own lock, before anyone gets it', 'O corpo do módulo roda uma vez, sob a trava do próprio sistema de importação, antes de alguém recebê-lo'),
              ('Right. A second importer waits for the first and then gets the finished module.',
               'Isso. Um segundo importador espera o primeiro e então recebe o módulo pronto.')),
             (False, ('The GIL stops other threads from running during any constructor', 'A GIL impede outras threads de rodar durante qualquer construtor'),
              ('The first catalogue.py had four constructors running at once under the same GIL.',
               'O primeiro catalogue.py teve quatro construtores rodando juntos sob a mesma GIL.')),
         ]),
    # ---- observer-under-threads
    dict(id='ex-bpkhhv42', section='observer-under-threads', type='quiz', difficulty='medium',
         prompt=('In the first observers.py, the statistics listener never received the event. Why?',
                 'No primeiro observers.py, o ouvinte das estatísticas nunca recebeu o evento. Por quê?'),
         choices=[
             (False, ('The e-mail listener raised an exception that stopped the loop', 'O ouvinte do e-mail lançou uma exceção que parou o laço'),
              ('Nothing raised; the e-mail was recorded and the program ended normally.',
               'Nada lançou erro; o e-mail foi anotado e o programa terminou normalmente.')),
             (True, ('A removal shifted the list under the loop, which then ran off its end', 'Uma remoção deslocou a lista debaixo do laço, que então passou do fim'),
              ('Right. The loop keeps a position; the statistics slid to position 1, which it had already passed.',
               'Isso. O laço guarda uma posição; as estatísticas escorregaram para a posição 1, que ele já tinha passado.')),
             (False, ('Unsubscribing the fines desk also removed every listener after it', 'Desinscrever o balcão de multas removeu também todo ouvinte depois dele'),
              ('remove takes out one item; the e-mail and statistics listeners were still in the list.',
               'remove tira um item; os ouvintes do e-mail e das estatísticas continuavam na lista.')),
         ]),
    dict(id='ex-r46rk7f9', section='observer-under-threads', type='quiz', difficulty='hard',
         prompt=('Why does the fixed publish copy the list under the lock and call the listeners after releasing it?',
                 'Por que o publish corrigido copia a lista dentro da trava e chama os ouvintes depois de soltá-la?'),
         choices=[
             (False, ('Calling a function while holding a lock is forbidden by Python', 'Chamar uma função segurando uma trava é proibido pelo Python'),
              ('Python allows it; the copy is a design choice, not a rule of the language.',
               'O Python permite; a cópia é uma escolha de projeto, não uma regra da linguagem.')),
             (False, ('Copying makes the listeners run in parallel on several cores', 'Copiar faz os ouvintes rodarem em paralelo em vários núcleos'),
              ('They still run one after another on the publisher\'s thread.',
               'Eles continuam rodando um depois do outro na thread de quem publica.')),
             (True, ('A listener could be slow, or subscribe from inside its callback and deadlock', 'Um ouvinte lento seguraria todos, e um que se inscreve no callback travaria'),
              ('Right. Hold a lock around your own data, never around a call into code you do not control.',
               'Isso. Segure uma trava em volta dos seus dados, nunca em volta de uma chamada a código que você não controla.')),
             (False, ('The copy is faster to walk than the original list', 'A cópia é mais rápida de percorrer que a lista original'),
              ('Walking either list costs the same; the point is that nobody can change the copy.',
               'Percorrer qualquer uma das listas custa o mesmo; o ponto é que ninguém consegue mudar a cópia.')),
         ]),
    dict(id='ex-1559ewnd', section='observer-under-threads', type='quiz', difficulty='hard',
         prompt=('With the snapshot fix, a listener is unsubscribed while an event is being published. What can happen?',
                 'Com a correção do retrato, um ouvinte é desinscrito enquanto um evento está sendo publicado. O que pode acontecer?'),
         choices=[
             (True, ('It still receives that one event, since it was in the copy', 'Ele ainda recebe aquele evento, porque estava na cópia'),
              ('Right. It was in the copy; the section names this cost, and only the listener can guard against it.',
               'Isso. Ele estava na cópia; a seção cita esse custo, e só o ouvinte consegue se proteger dele.')),
             (False, ('The publish raises RuntimeError, because the list changed size', 'O publish lança RuntimeError, porque a lista mudou de tamanho'),
              ('The loop walks the copy, which did not change; that error belongs to dictionaries and sets.',
               'O laço percorre a cópia, que não mudou; esse erro é de dicionários e conjuntos.')),
             (False, ('The unsubscribe waits until every listener has been called', 'O unsubscribe espera até todo ouvinte ter sido chamado'),
              ('The lock is released before the calls, so unsubscribe goes through at once.',
               'A trava é solta antes das chamadas, então o unsubscribe passa na hora.')),
         ]),
    # ---- immutability-helps
    dict(id='ex-m39vgdrn', section='immutability-helps', type='quiz', difficulty='medium',
         prompt=('The rules change from 50 cents a day with no grace to 100 cents with 2 days\' grace. A reader of the mutable dictionary sees the price changed and the grace not yet. What does it charge for 4 days late?',
                 'As regras mudam de 50 centavos por dia sem carência para 100 centavos com 2 dias de carência. Um leitor do dicionário mutável vê o preço já mudado e a carência ainda não. Quanto ele cobra por 4 dias de atraso?'),
         choices=[
             (False, ('200 cents, as under the old rules', '200 centavos, como pelas regras antigas'),
              ('The old rules would charge 200, but this reader is using the new price.',
               'As regras antigas cobrariam 200, mas este leitor está usando o preço novo.')),
             (False, ('Nothing: reading a dictionary while another thread writes it raises an error', 'Nada: ler um dicionário enquanto outra thread o escreve lança um erro'),
              ('Only iterating over a dictionary while its size changes raises; reading two keys does not.',
               'Só percorrer um dicionário enquanto o tamanho muda lança erro; ler duas chaves não.')),
             (True, ('400 cents, which neither set of rules would charge', '400 centavos, que nenhum dos dois conjuntos cobraria'),
              ('Right. 4 x 100 with no grace: a torn read, built from half of each rule set.',
               'Isso. 4 x 100 sem carência: uma leitura rasgada, feita de metade de cada conjunto.')),
         ]),
    dict(id='ex-mksaeyk3', section='immutability-helps', type='quiz', difficulty='hard',
         prompt=('A frozen dataclass Shelf holds a field books: list[str]. Two threads share one Shelf. What does frozen=True guarantee?',
                 'Uma dataclass congelada Shelf tem um campo books: list[str]. Duas threads compartilham um Shelf. O que frozen=True garante?'),
         choices=[
             (False, ('Nothing about the Shelf can change after it is built', 'Nada no Shelf pode mudar depois de construído'),
              ('Frozen is only as deep as the fields: the list inside can still be appended to.',
               'Congelado só vai até a profundidade dos campos: a lista de dentro ainda aceita append.')),
             (True, ('The field cannot point at another list; the list itself can still change', 'O campo não pode apontar para outra lista; a própria lista ainda pode mudar'),
              ('Right. Use a tuple all the way down, or the lock comes back through the side door.',
               'Isso. Use uma tupla até o fim, ou a trava volta pela porta dos fundos.')),
             (False, ('Appends to the list are made atomic by the dataclass', 'Os appends na lista são tornados atômicos pela dataclass'),
              ('The dataclass does nothing to the list\'s methods; it only refuses assignment to its own fields.',
               'A dataclass não faz nada com os métodos da lista; ela só recusa atribuição aos próprios campos.')),
             (False, ('Each thread gets its own copy of the list when it reads the field', 'Cada thread ganha sua própria cópia da lista quando lê o campo'),
              ('Reading a field hands over the same list object to every reader.',
               'Ler um campo entrega o mesmo objeto lista a todo leitor.')),
         ]),
    dict(id='ex-14vym9tw', section='immutability-helps', type='quiz', difficulty='medium',
         prompt=('In Java, a thread publishes new frozen rules by assigning them to a plain field. What can go wrong?',
                 'Em Java, uma thread publica regras congeladas novas atribuindo-as a um campo comum. O que pode dar errado?'),
         choices=[
             (True, ('Another thread may keep reading the old rules and never see the new ones', 'Outra thread pode continuar lendo as regras antigas e nunca ver as novas'),
              ('Right. Java needs volatile or an AtomicReference to make the publication visible.',
               'Isso. Java precisa de volatile ou de uma AtomicReference para tornar a publicação visível.')),
             (False, ('The rules object can be changed by the reading thread', 'O objeto de regras pode ser mudado pela thread que lê'),
              ('The object is immutable in either language; the question is whether the new reference is seen.',
               'O objeto é imutável em qualquer linguagem; a questão é se a referência nova é vista.')),
             (False, ('The compiler rejects assignment to a field shared between threads', 'O compilador recusa atribuição a um campo compartilhado entre threads'),
              ('Java compiles it without complaint, which is exactly why the mistake is easy to make.',
               'Java compila sem reclamar, e é exatamente por isso que o erro é fácil de cometer.')),
         ]),
    # ---- choosing-a-model
    dict(id='ex-0eh0pxc5', section='choosing-a-model', type='ordering', difficulty='medium',
         prompt=('Put the ways of handling shared state in the order the section says to try them.',
                 'Ponha as formas de lidar com estado compartilhado na ordem em que a seção diz para tentá-las.'),
         items=[('Share nothing: each task has its own data', 'Não compartilhar nada: cada tarefa tem seus próprios dados'),
                ('Share only immutable values, swapping a reference to publish', 'Compartilhar só valores imutáveis, trocando uma referência para publicar'),
                ('Confine each mutable thing to one owner and send it messages', 'Confinar cada coisa mutável a um dono e mandar mensagens a ele'),
                ('Lock around your own data, briefly, in one agreed order', 'Travar em volta dos seus dados, por pouco tempo, numa ordem combinada')],
         trap=('Reaching for the lock first is the habit the section argues against: it is the only one whose correctness depends on every caller.',
               'Pegar a trava primeiro é o hábito contra o qual a seção argumenta: é a única cuja correção depende de todo chamador.')),
    dict(id='ex-7m21gz15', section='choosing-a-model', type='matching', difficulty='medium',
         prompt=('Match each kind of work to the Python model the section suggests for it.',
                 'Associe cada tipo de trabalho ao modelo em Python que a seção sugere para ele.'),
         pairs=[
             (('Thousands of open connections, mostly waiting', 'Milhares de conexões abertas, quase sempre esperando'), ('asyncio', 'asyncio')),
             (('Waiting through a library that blocks and has no async version', 'Esperar por meio de uma biblioteca que bloqueia e não tem versão async'), ('ThreadPoolExecutor', 'ThreadPoolExecutor')),
             (('Independent pieces of heavy arithmetic', 'Partes independentes de aritmética pesada'), ('ProcessPoolExecutor', 'ProcessPoolExecutor')),
             (('Long-lived state that many callers change', 'Estado duradouro que muitos chamadores mudam'), ('an actor that owns it', 'um ator que é dono dele')),
         ]),
    dict(id='ex-a2360s6g', section='choosing-a-model', type='quiz', difficulty='hard',
         prompt=('An asyncio handler reads a member\'s loan count, awaits a database call, then writes count + 1. Two requests for the same member arrive together. What happens?',
                 'Um handler asyncio lê a contagem de empréstimos de um membro, faz await numa chamada ao banco e escreve contagem + 1. Chegam juntas duas requisições do mesmo membro. O que acontece?'),
         choices=[
             (False, ('Nothing can go wrong: asyncio runs on one thread', 'Nada pode dar errado: o asyncio roda numa thread só'),
              ('One thread removes the gaps you did not write, not the ones you did; the await is one.',
               'Uma thread remove os vãos que você não escreveu, não os que escreveu; o await é um deles.')),
             (True, ('One update can be lost, because the await is a gap between read and write', 'Uma atualização pode se perder, porque o await é um vão entre ler e escrever'),
              ('Right. It is race.py again, with the await in place of sleep(0).',
               'Isso. É o race.py de novo, com o await no lugar do sleep(0).')),
             (False, ('The event loop runs the second request after the first one finishes', 'O event loop roda a segunda requisição depois que a primeira termina'),
              ('The loop starts the second as soon as the first awaits; that is what await is for.',
               'O loop inicia a segunda assim que a primeira faz await; é para isso que o await existe.')),
             (False, ('asyncio raises an error because two tasks touched the same value', 'O asyncio lança um erro porque duas tarefas mexeram no mesmo valor'),
              ('Nothing watches for that; the lost update is as silent as it was with threads.',
               'Nada vigia isso; a atualização perdida é tão silenciosa quanto era com threads.')),
         ]),
    # ---- drill
    dict(id='ex-3drf4ykn', section='drill', type='multiple-choice', difficulty='hard',
         prompt=('Which of these can lose or corrupt data when run by several threads at once? Choose all that apply.',
                 'Quais destes podem perder ou corromper dados quando rodados por várias threads ao mesmo tempo? Marque todos que se aplicam.'),
         choices=[
             (True, ('if isbn not in cache: cache[isbn] = fetch(isbn), with a slow fetch', 'if isbn not in cache: cache[isbn] = fetch(isbn), com um fetch lento'),
              ('Right. Check-then-act: two threads can both miss and both fetch, like the four catalogues.',
               'Isso. Verificar-depois-agir: duas threads podem errar as duas e buscar as duas, como os quatro catálogos.')),
             (False, ('Several threads reading one frozen FineRules object', 'Várias threads lendo um único objeto FineRules congelado'),
              ('No writer, nothing to race on: every reader sees the same complete value.',
               'Sem escritor, nada sobre o que correr: todo leitor vê o mesmo valor completo.')),
             (True, ('Updating a total by reading it, calling a function, and writing it back', 'Atualizar um total lendo, chamando uma função e escrevendo de volta'),
              ('Right. Read-modify-write with a gap in the middle, which is race.py.',
               'Isso. Ler-modificar-escrever com um vão no meio, que é o race.py.')),
             (True, ('Walking a list of listeners while another thread removes one', 'Percorrer uma lista de ouvintes enquanto outra thread remove um'),
              ('Right. A listener is skipped silently, as the statistics were.',
               'Isso. Um ouvinte é pulado em silêncio, como as estatísticas foram.')),
         ]),
    dict(id='ex-54ehbhap', section='drill', type='quiz', difficulty='hard',
         prompt=('A team moves its Python service to the free-threaded build. Which program from this lesson is the most likely to start behaving differently?',
                 'Uma equipe passa seu serviço Python para a versão free-threaded. Que programa desta lição tem mais chance de começar a se comportar diferente?'),
         choices=[
             (False, ('rules.py, because frozen dataclasses rely on the GIL', 'rules.py, porque dataclasses congeladas dependem da GIL'),
              ('Frozen dataclasses refuse assignment in any build; immutability never needed the GIL.',
               'Dataclasses congeladas recusam atribuição em qualquer versão; a imutabilidade nunca precisou da GIL.')),
             (False, ('locks.py, because a Lock no longer works without the GIL', 'locks.py, porque uma Lock deixa de funcionar sem a GIL'),
              ('A Lock is the tool that works the same in both builds; it never leaned on the GIL.',
               'Uma Lock é a ferramenta que funciona igual nas duas versões; ela nunca se apoiou na GIL.')),
             (True, ('plus_equals.py', 'plus_equals.py'),
              ('Right. Its safety was an accident of when 3.12 switches threads, and threads that truly run at once remove the accident.',
               'Isso. A segurança dele era um acaso de quando o 3.12 troca de thread, e threads rodando de fato juntas removem o acaso.')),
             (False, ('models.py\'s waiting half, which would stop overlapping the lookups', 'a metade de espera de models.py, que pararia de sobrepor as consultas'),
              ('Waiting overlapped under the GIL already; without it, the computing half is what changes.',
               'A espera já se sobrepunha sob a GIL; sem ela, o que muda é a metade de cálculo.')),
         ]),
    dict(id='ex-dy4zbarm', section='drill', type='quiz', difficulty='hard',
         prompt=('A swap must lock a member and a book, and other code locks a book and then a member. What is the simplest change that rules out a deadlock between them?',
                 'Uma troca precisa travar um membro e um livro, e outro código trava um livro e depois um membro. Qual é a mudança mais simples que elimina um deadlock entre eles?'),
         choices=[
             (False, ('Give every lock a timeout of one second', 'Dar a toda trava um timeout de um segundo'),
              ('A timeout turns a permanent deadlock into a failed operation; the cycle can still form.',
               'Um timeout transforma um deadlock permanente numa operação que falha; o ciclo ainda pode se formar.')),
             (True, ('Agree that every code path takes the member\'s lock before the book\'s', 'Fixar uma ordem única para as duas travas e segui-la em todo lugar'),
              ('Right. The same rule as sorting by member number: one order, so no cycle.',
               'Isso. A mesma regra de ordenar pelo número do membro: uma ordem, então nenhum ciclo.')),
             (False, ('Replace both locks with RLocks', 'Trocar as duas travas por RLocks'),
              ('An RLock lets one thread take it twice; it does nothing for two threads waiting on each other.',
               'Uma RLock deixa uma thread pegá-la duas vezes; não faz nada por duas threads esperando uma pela outra.')),
         ]),
]
