"""Lesson 19: choosing the pattern for the problem, not for your CV."""

EXERCISES = [
    # ---- problem-first
    dict(id='ex-fyng5p8n', section='problem-first', type='quiz', difficulty='easy',
         prompt=('Which of these is a force, in the sense this lesson uses?',
                 'Qual destas é uma força, no sentido que esta lição usa?'),
         choices=[
             (False, ('This code would be cleaner with a factory', 'Este código ficaria mais limpo com uma factory'),
              ('That names a pattern and a feeling; nothing in it can be checked against the code or its history.',
               'Isso nomeia um padrão e uma impressão; nada ali pode ser conferido contra o código ou o histórico dele.')),
             (True, ('Each new member category means editing the fine function', 'Cada categoria nova de membro obriga a editar a função de multa'),
              ('Right. Something changes and the change is expensive, said in one checkable sentence.',
               'Isso. Algo muda e a mudança sai cara, dito numa frase que dá para conferir.')),
             (False, ('We should use the strategy pattern here', 'Devíamos usar o padrão strategy aqui'),
              ('That is an answer looking for a question, the habit the section opens with.',
               'Isso é uma resposta procurando uma pergunta, o hábito com que a seção começa.')),
             (False, ('Every good codebase uses at least three patterns', 'Toda boa base de código usa pelo menos três padrões'),
              ('A count of patterns says nothing about any pressure on this code.',
               'Uma contagem de padrões não diz nada sobre pressão nenhuma neste código.')),
         ]),
    dict(id='ex-3jw7meft', section='problem-first', type='quiz', difficulty='medium',
         prompt=('The fine function\'s if/elif has been edited twice in three years, and no change is planned. What does the section recommend?',
                 'O if/elif da função de multa foi editado duas vezes em três anos, e nenhuma mudança está planejada. O que a seção recomenda?'),
         choices=[
             (False, ('A strategy class per category, so the next change is cheap', 'Uma classe strategy por categoria, para a próxima mudança sair barata'),
              ('There is no next change in sight; that is building for a force that has not arrived.',
               'Não há próxima mudança à vista; isso é construir para uma força que não chegou.')),
             (True, ('Leave it', 'Deixar como está'),
              ('Right. No force, so the right change is none: three branches anybody reads in ten seconds.',
               'Isso. Sem força, a mudança certa é nenhuma: três ramos que qualquer um lê em dez segundos.')),
             (False, ('A dictionary of rates, since a table reads better than an if statement', 'Um dicionário de taxas, já que uma tabela se lê melhor que um if'),
              ('The table is the answer when categories keep arriving; here none are arriving.',
               'A tabela é a resposta quando categorias vivem chegando; aqui nada está chegando.')),
         ]),
    dict(id='ex-ypt75x4x', section='problem-first', type='quiz', difficulty='hard',
         prompt=('Two pieces of code are identical. In one repository the function changes every month; in the other it has not changed in four years. What follows?',
                 'Dois trechos de código são idênticos. Num repositório a função muda todo mês; no outro, não muda há quatro anos. O que se conclui?'),
         choices=[
             (True, ('Each deserves its own design', 'Cada um merece seu próprio projeto'),
              ('Right. The force lives in the history and the plan, not in the text of the code.',
               'Isso. A força mora no histórico e no plano, não no texto do código.')),
             (False, ('They need the same design, because the code is the same', 'Precisam do mesmo projeto, porque o código é o mesmo'),
              ('The section showed one function with three right answers, decided by facts outside it.',
               'A seção mostrou uma função com três respostas certas, decididas por fatos de fora dela.')),
             (False, ('The stable one should get the pattern first, because it is safer to change', 'A estável deve ganhar o padrão primeiro, porque é mais segura de mudar'),
              ('Safety to change is not a reason to change; the stable one has no force pushing on it.',
               'Ser segura de mudar não é motivo para mudar; a estável não tem força empurrando.')),
         ]),
    # ---- the-cost-of-a-pattern
    dict(id='ex-zzmxkts6', section='the-cost-of-a-pattern', type='numeric', difficulty='easy',
         prompt=('In the hops.py run, how many function calls did layered.py make to write one notice?',
                 'Na execução de hops.py, quantas chamadas de função layered.py fez para escrever um aviso?'),
         value=9, tolerance=0, unit=('calls', 'chamadas')),
    dict(id='ex-tv9nvnfc', section='the-cost-of-a-pattern', type='quiz', difficulty='medium',
         prompt=('Where does the section say most of a pattern\'s cost falls?',
                 'Onde a seção diz que cai a maior parte do custo de um padrão?'),
         choices=[
             (False, ('On the machine, which runs the extra calls', 'Na máquina, que roda as chamadas extras'),
              ('Nine calls instead of one cost microseconds; the section does not measure speed.',
               'Nove chamadas em vez de uma custam microssegundos; a seção não mede velocidade.')),
             (False, ('On the author, once, when the classes are first written', 'No autor, uma vez, quando as classes são escritas'),
              ('That is the small part, according to the section.', 'Essa é a parte pequena, segundo a seção.')),
             (True, ('On every reader, every time', 'Em todo leitor, toda vez'),
              ('Right. The hops recur on every reading for as long as the code lives.',
               'Isso. Os saltos se repetem a cada leitura enquanto o código existir.')),
         ]),
    dict(id='ex-1ma8p9e1', section='the-cost-of-a-pattern', type='quiz', difficulty='hard',
         prompt=('A rule changes every week in code that is read about once a month. By the section\'s measure, how much indirection has it earned?',
                 'Uma regra muda toda semana num código lido mais ou menos uma vez por mês. Pela medida da seção, quanta indireção ela merece?'),
         choices=[
             (False, ('Little: indirection pays in code that seldom changes', 'Pouca: indireção compensa em código que raramente muda'),
              ('That is backwards; indirection pays by absorbing change.', 'Isso está invertido; a indireção paga absorvendo mudança.')),
             (True, ('A lot: frequent change, rare reading', 'Bastante: mudança frequente, leitura rara'),
              ('Right. The change costs more than the readers\' extra hops, so the pattern earns its place.',
               'Isso. A mudança custa mais que os saltos extras dos leitores, então o padrão merece seu lugar.')),
             (False, ('Exactly one layer, whatever the rates are', 'Exatamente uma camada, sejam quais forem as frequências'),
              ('The section gives a comparison of two rates, not a fixed allowance.',
               'A seção dá uma comparação entre duas frequências, não uma cota fixa.')),
             (False, ('It cannot be judged until the code has a second implementation', 'Não dá para julgar até o código ter uma segunda implementação'),
              ('The rates of change and of reading are known here, and they are what the measure uses.',
               'As frequências de mudança e de leitura são conhecidas aqui, e são o que a medida usa.')),
         ]),
    # ---- over-design-signs
    dict(id='ex-b24x8cnm', section='over-design-signs', type='cloze', difficulty='easy',
         prompt=('Fowler\'s name for hooks and abstractions built for a future nobody can point to is speculative ___ .',
                 'O nome de Fowler para ganchos e abstrações construídos para um futuro que ninguém aponta é generalidade ___ .'),
         blanks=[dict(en=['generality'], pt=['especulativa', 'speculative'])]),
    dict(id='ex-6x4efb2q', section='over-design-signs', type='quiz', difficulty='medium',
         prompt=('smells.py reports a protocol with one implementation. When is that structure still right?',
                 'smells.py relata um protocolo com uma implementação. Quando essa estrutura ainda está certa?'),
         choices=[
             (False, ('It is not; a protocol with one implementation is a class with a second name', 'Não está; um protocolo com uma implementação é uma classe com um segundo nome'),
              ('The section says to read each line as a question, and names the case below.',
               'A seção manda ler cada linha como pergunta, e cita o caso ao lado.')),
             (False, ('When the protocol has more than one method', 'Quando o protocolo tem mais de um método'),
              ('The number of methods does not change whether anything else can stand in that place.',
               'O número de métodos não muda se outra coisa pode ocupar aquele lugar.')),
             (True, ('When the tests hold a fake as the second one', 'Quando os testes guardam uma falsa como a segunda'),
              ('Right. The program never opened the test file, which is why it reports a question and not a verdict.',
               'Isso. O programa nunca abriu o arquivo de teste, e por isso relata uma pergunta e não um veredito.')),
         ]),
    dict(id='ex-56jek14f', section='over-design-signs', type='quiz', difficulty='medium',
         prompt=('Which of these is a sign of UNDER-design rather than over-design?',
                 'Qual destes é um sinal de FALTA de projeto em vez de excesso?'),
         choices=[
             (True, ('The same if over categories appears in five places', 'O mesmo if sobre categorias aparece em cinco lugares'),
              ('Right. A force has arrived, and every new category means finding all five.',
               'Isso. Uma força chegou, e toda categoria nova obriga a achar os cinco.')),
             (False, ('A parameter that every caller passes and no method reads', 'Um parâmetro que todo chamador passa e nenhum método lê'),
              ('That is speculative generality: structure for a change that has not come.',
               'Isso é generalidade especulativa: estrutura para uma mudança que não veio.')),
             (False, ('A factory that only ever builds one class', 'Uma factory que só constrói uma classe'),
              ('That is over-design, one of the four signs in the section.', 'Isso é excesso de projeto, um dos quatro sinais da seção.')),
             (False, ('A service method that only hands the call on to another object', 'Um método de serviço que só repassa a chamada a outro objeto'),
              ('A forwarding layer is listed among the signs of over-design.', 'Uma camada que repassa está entre os sinais de excesso.')),
         ]),
    # ---- worked-decisions
    dict(id='ex-q0958y9w', section='worked-decisions', type='quiz', difficulty='medium',
         prompt=('In case 1, why is the member category put in a dictionary of rates and not in a strategy class per category?',
                 'No caso 1, por que a categoria do membro vai num dicionário de taxas e não numa classe strategy por categoria?'),
         choices=[
             (False, ('Dictionaries are faster to look up than classes', 'Dicionários são mais rápidos de consultar que classes'),
              ('Speed is not part of the argument in any of the three cases.', 'Velocidade não faz parte do argumento em nenhum dos três casos.')),
             (True, ('The category changes a number, and a number is data', 'A categoria muda um número, e número é dado'),
              ('Right. A new category is one line of data and no new code.', 'Isso. Uma categoria nova é uma linha de dados e nenhum código novo.')),
             (False, ('Python cannot store classes as values in a dictionary', 'O Python não consegue guardar classes como valores num dicionário'),
              ('It can; RULES stores functions, and classes are objects too.', 'Consegue; RULES guarda funções, e classes também são objetos.')),
         ]),
    dict(id='ex-8kmmabg7', section='worked-decisions', type='quiz', difficulty='hard',
         prompt=('In case 2, what would turn the in-process list of listeners into a queue between processes?',
                 'No caso 2, o que transformaria a lista de ouvintes no mesmo processo numa fila entre processos?'),
         choices=[
             (False, ('A fourth listener, the reservations desk, being added next year', 'Um quarto ouvinte, o balcão de reservas, entrar no ano que vem'),
              ('One more listener is one more entry in the list; the observer already absorbs that.',
               'Um ouvinte a mais é uma entrada a mais na lista; o observer já absorve isso.')),
             (True, ('The e-mail moving to another service, or no return being allowed to be lost in a crash', 'O e-mail ir para outro serviço, ou nenhuma devolução poder se perder numa queda'),
              ('Right. Those are the forces a broker answers, and the section names them as the reopening condition.',
               'Isso. Essas são as forças que um broker responde, e a seção as cita como condição de reabertura.')),
             (False, ('The listeners taking more than a second to run', 'Os ouvintes levarem mais de um segundo para rodar'),
              ('Slowness is lesson 18\'s question about threads, not a reason given for a broker.',
               'Lentidão é a pergunta da lição 18 sobre threads, não um motivo dado para um broker.')),
         ]),
    dict(id='ex-pr9wcv2b', section='worked-decisions', type='quiz', difficulty='hard',
         prompt=('Case 3 needed to prove when a book was returned. Why was full event sourcing rejected?',
                 'O caso 3 precisava provar quando um livro foi devolvido. Por que o event sourcing completo foi rejeitado?'),
         choices=[
             (False, ('Event sourcing cannot record the time an event happened', 'Event sourcing não consegue registrar quando um evento aconteceu'),
              ('It records exactly that; the problem is everything else it brings.', 'Ele registra exatamente isso; o problema é tudo o mais que ele traz.')),
             (False, ('Two columns, returned_by and returned_at, answer every dispute', 'Duas colunas, returned_by e returned_at, respondem a toda contestação'),
              ('They lose the earlier value when a return is corrected, which the section points out.',
               'Elas perdem o valor anterior quando uma devolução é corrigida, como a seção aponta.')),
             (True, ('Nothing asked to rebuild state from history', 'Nada pedia reconstruir o estado a partir do histórico'),
              ('Right. An append-only table answers the audit without making the log the source of truth.',
               'Isso. Uma tabela só de acréscimo responde a auditoria sem fazer do log a fonte da verdade.')),
         ]),
    # ---- reading-a-codebase
    dict(id='ex-7fpknw0x', section='reading-a-codebase', type='matching', difficulty='medium',
         prompt=('Match each shape found in code to the pattern it usually is.',
                 'Associe cada formato encontrado no código ao padrão que ele costuma ser.'),
         pairs=[
             (('Holds an object of its own interface and forwards to it, adding something', 'Guarda um objeto da própria interface e repassa, acrescentando algo'), ('decorator', 'decorator')),
             (('Holds an object of another interface and offers yours', 'Guarda um objeto de outra interface e oferece a sua'), ('adapter', 'adapter')),
             (('A dictionary from names to constructors', 'Um dicionário de nomes para construtores'), ('factory', 'factory')),
             (('Holds one of a family and delegates one step to it', 'Guarda um de uma família e delega um passo a ele'), ('strategy', 'strategy')),
         ]),
    dict(id='ex-31k8hr97', section='reading-a-codebase', type='quiz', difficulty='medium',
         prompt=('In mystery.py, what makes PartnerCatalogue an adapter rather than a decorator?',
                 'Em mystery.py, o que faz de PartnerCatalogue um adapter e não um decorator?'),
         choices=[
             (True, ('What it holds is not a Catalogue', 'O que ela guarda não é um Catalogue'),
              ('Right. It offers Catalogue over nested dictionaries in another library\'s format.',
               'Isso. Ela oferece Catalogue sobre dicionários aninhados no formato de outra biblioteca.')),
             (False, ('It is created through the SOURCES dictionary', 'Ela é criada pelo dicionário SOURCES'),
              ('ShelfCatalogue is created the same way and is no adapter; how it is built is the factory\'s shape.',
               'ShelfCatalogue é criada do mesmo jeito e não é adapter; como se constrói é o formato da factory.')),
             (False, ('Its name contains Partner, which marks an external system', 'O nome dela contém Partner, que marca um sistema externo'),
              ('The section says to read structure first; a name proves nothing either way.',
               'A seção manda ler a estrutura primeiro; um nome não prova nada em nenhum sentido.')),
             (False, ('It counts nothing, while CountingCatalogue counts every lookup made', 'Ela não conta nada, enquanto CountingCatalogue conta toda consulta feita'),
              ('Counting is what this decorator adds; a decorator could add anything. The difference is what is held.',
               'Contar é o que este decorator acrescenta; um decorator poderia acrescentar qualquer coisa. A diferença é o que se guarda.')),
         ]),
    dict(id='ex-p60yzvp6', section='reading-a-codebase', type='quiz', difficulty='hard',
         prompt=('A class holds an object of its own interface and forwards to it, adding a cache. Is it a proxy or a decorator?',
                 'Uma classe guarda um objeto da própria interface e repassa para ele, acrescentando um cache. É proxy ou decorator?'),
         choices=[
             (False, ('A decorator, because a proxy cannot hold an object of its own interface', 'Decorator, porque um proxy não pode guardar um objeto da própria interface'),
              ('A proxy holds exactly that; the two have the same structure.', 'Um proxy guarda exatamente isso; os dois têm a mesma estrutura.')),
             (True, ('The structure cannot settle it; the two differ only in intent', 'A estrutura não decide; os dois diferem só na intenção'),
              ('Right. Caching leans towards proxy, but only the commit message or the author can say what was meant.',
               'Isso. Cache puxa para proxy, mas só a mensagem do commit ou o autor dizem o que se pretendia.')),
             (False, ('A proxy, because only proxies are allowed to cache', 'Proxy, porque só proxies podem fazer cache'),
              ('No rule restricts caching to one pattern; the table says caching usually signals a proxy.',
               'Nenhuma regra restringe cache a um padrão; a tabela diz que cache costuma indicar proxy.')),
         ]),
    # ---- recording-the-choice
    dict(id='ex-ff0h34mf', section='recording-the-choice', type='quiz', difficulty='easy',
         prompt=('What happens to an ADR when its decision changes?',
                 'O que acontece com um ADR quando a decisão dele muda?'),
         choices=[
             (False, ('It is edited to describe the new decision', 'É editado para descrever a nova decisão'),
              ('Editing it erases the history of why the code took each shape.', 'Editá-lo apaga a história de por que o código tomou cada forma.')),
             (False, ('It is deleted, since it no longer applies', 'É apagado, já que não se aplica mais'),
              ('A deleted record takes the old argument with it, which is what records exist to keep.',
               'Um registro apagado leva o argumento antigo junto, que é o que os registros existem para guardar.')),
             (True, ('A new one is written, and the old one is marked superseded', 'Um novo é escrito, e o antigo é marcado como substituído'),
              ('Right. The history then reads in order, which a commit log tells badly.',
               'Isso. A história passa a ser lida em ordem, que um log de commits conta mal.')),
         ]),
    dict(id='ex-85p7gvfj', section='recording-the-choice', type='quiz', difficulty='medium',
         prompt=('Which part of a pattern decision record does the section say is most often left out?',
                 'Que parte do registro de uma decisão de padrão a seção diz que é mais esquecida?'),
         choices=[
             (False, ('The date', 'A data'),
              ('Every record in the format carries a status line with a date.', 'Todo registro no formato tem uma linha de status com data.')),
             (True, ('The condition that would reopen the decision', 'A condição que reabriria a decisão'),
              ('Right. Without it the reader has to guess whether the choice still applies.',
               'Isso. Sem ela quem lê precisa adivinhar se a escolha ainda vale.')),
             (False, ('A description of the code that implements the decision', 'Uma descrição do código que implementa a decisão'),
              ('The section says the record should not describe the code, which the code already does.',
               'A seção diz que o registro não deve descrever o código, que o próprio código já descreve.')),
         ]),
    dict(id='ex-2m0xczhq', section='recording-the-choice', type='quiz', difficulty='hard',
         prompt=('A reviewer finds a protocol with one implementation and proposes removing it. An ADR beside it says a second implementation is planned for June. What did the ADR save?',
                 'Um revisor encontra um protocolo com uma implementação e propõe removê-lo. Um ADR ao lado diz que uma segunda implementação está planejada para junho. O que o ADR poupou?'),
         choices=[
             (True, ('Undoing a deliberate choice, and making it again in June', 'Desfazer uma escolha deliberada, e refazê-la em junho'),
              ('Right. Without the record the "fix" loses the argument and someone rebuilds the protocol later.',
               'Isso. Sem o registro o "conserto" perde o argumento e alguém reconstrói o protocolo depois.')),
             (False, ('Little, since a protocol with one implementation is over-design whatever is planned', 'Pouco, já que um protocolo com uma implementação é excesso de projeto seja qual for o plano'),
              ('A planned second implementation is a stated force with a date; that is the case the record exists for.',
               'Uma segunda implementação planejada é uma força declarada com data; é o caso para o qual o registro existe.')),
             (False, ('The test that would otherwise fail', 'O teste que senão falharia'),
              ('Removing an unused protocol breaks no test; what is lost is the reason for it.',
               'Remover um protocolo sem uso não quebra teste nenhum; o que se perde é o motivo dele.')),
         ]),
    # ---- a-checklist
    dict(id='ex-wt1jfzej', section='a-checklist', type='ordering', difficulty='medium',
         prompt=('Put the first four checklist questions in the order the section asks them.',
                 'Ponha as quatro primeiras perguntas da lista na ordem em que a seção as faz.'),
         items=[('What is the force, in one sentence?', 'Qual é a força, numa frase?'),
                ('Is the force real today?', 'A força é real hoje?'),
                ('What is the smallest answer?', 'Qual é a menor resposta?'),
                ('What does it cost a reader?', 'Quanto custa para quem lê?')],
         trap=('Starting from the answer, or from its cost, skips the question that can stop the whole thing early.',
               'Começar pela resposta, ou pelo custo dela, pula a pergunta que pode parar tudo logo no início.')),
    dict(id='ex-fabt96vc', section='a-checklist', type='quiz', difficulty='medium',
         prompt=('Before collapsing a layer that seems to only forward calls, what does the section say to look for?',
                 'Antes de achatar uma camada que parece só repassar chamadas, o que a seção manda procurar?'),
         choices=[
             (False, ('Whether the layer\'s file is longer than fifty lines', 'Se o arquivo da camada tem mais de cinquenta linhas'),
              ('Length is not one of the questions; what the layer does is.', 'Tamanho não é uma das perguntas; o que a camada faz é.')),
             (True, ('A rule or a translation the layer performs', 'Uma regra ou uma tradução que a camada faz'),
              ('Right. Removing a pattern deserves the same evidence as adding one.',
               'Isso. Remover um padrão merece as mesmas evidências que acrescentar um.')),
             (False, ('Whether a design patterns book names the layer', 'Se algum livro de padrões dá nome à camada'),
              ('A name in a book is not a force in this code.', 'Um nome num livro não é uma força neste código.')),
             (False, ('Whether the original author still works on the team and can approve the change', 'Se o autor original ainda está na equipe e pode aprovar a mudança'),
              ('The evidence is in the code and its records, which is why the section asks for both.',
               'A evidência está no código e nos registros, e por isso a seção pede os dois.')),
         ]),
    dict(id='ex-qkx6rrk1', section='a-checklist', type='quiz', difficulty='easy',
         prompt=('Which checklist question comes from lesson 18?', 'Que pergunta da lista vem da lição 18?'),
         choices=[
             (False, ('What would reopen the decision?', 'O que reabriria a decisão?'),
              ('That comes from the worked decisions and the ADR section of this lesson.',
               'Essa vem das decisões argumentadas e da seção de ADR desta lição.')),
             (False, ('What is the smallest answer?', 'Qual é a menor resposta?'),
              ('That leans on lesson 6\'s point about patterns built into the language.',
               'Essa se apoia no argumento da lição 6 sobre padrões embutidos na linguagem.')),
             (True, ('Who else might be here at the same time?', 'Quem mais estaria aqui ao mesmo tempo?'),
              ('Right. A lazy singleton or a changing observer list is a new bug under threads.',
               'Isso. Um singleton preguiçoso ou uma lista de observers que muda é um defeito novo com threads.')),
         ]),
    # ---- drill
    dict(id='ex-22jb19q7', section='drill', type='multiple-choice', difficulty='hard',
         prompt=('A pull request adds NotifierFactory, Notifier (a protocol), EmailNotifier and NotifierConfig, for the one way the library sends notices. Which questions should the review ask? Choose all that apply.',
                 'Um pull request acrescenta NotifierFactory, Notifier (um protocolo), EmailNotifier e NotifierConfig, para o único jeito de a biblioteca mandar avisos. Que perguntas a revisão deve fazer? Marque todas que se aplicam.'),
         choices=[
             (True, ('Which force do these answer, in one sentence?', 'A que força isto responde, numa frase?'),
              ('Right. The first checklist question, and the one that can end the review early.',
               'Isso. A primeira pergunta da lista, e a que pode encerrar a revisão cedo.')),
             (True, ('Is there a second Notifier, even a fake in the tests?', 'Existe um segundo Notifier, nem que seja um falso nos testes?'),
              ('Right. A protocol with one implementation and no double is the first sign of over-design.',
               'Isso. Um protocolo com uma implementação e nenhum dublê é o primeiro sinal de excesso.')),
             (False, ('Does each class follow the naming convention of the pattern it implements?', 'Cada classe segue a convenção de nomes do padrão que implementa?'),
              ('Names are the poorest guide to a pattern; tidy names on unneeded classes are still unneeded.',
               'Nomes são o pior guia para um padrão; nomes caprichados em classes desnecessárias continuam desnecessários.')),
             (True, ('Can the factory build anything other than EmailNotifier?', 'A factory consegue construir algo além de EmailNotifier?'),
              ('Right. A factory that can only make one thing is one of the four signs.',
               'Isso. Uma factory que só sabe fazer uma coisa é um dos quatro sinais.')),
         ]),
    dict(id='ex-c1hd0azm', section='drill', type='quiz', difficulty='hard',
         prompt=('The library adds a fourth and a fifth way to fine items, each with its own configuration that staff edit. Case 1 chose a dictionary of functions. What now?',
                 'A biblioteca acrescenta um quarto e um quinto jeito de multar itens, cada um com configuração própria que a equipe edita. O caso 1 escolheu um dicionário de funções. E agora?'),
         choices=[
             (False, ('Keep the functions; the decision was recorded and records are final', 'Manter as funções; a decisão foi registrada e registros são definitivos'),
              ('A record is never edited, but it is superseded when its reopening condition arrives.',
               'Um registro nunca é editado, mas é substituído quando a condição de reabertura chega.')),
             (True, ('The reopening condition has arrived: a small class per rule, recorded in a new ADR', 'A condição de reabertura chegou: uma classe pequena por regra, registrada num ADR novo'),
              ('Right. Rules with their own configuration were exactly what the record said would change the choice.',
               'Isso. Regras com configuração própria eram exatamente o que o registro disse que mudaria a escolha.')),
             (False, ('Move to event sourcing, since the rules now change over time', 'Passar para event sourcing, já que as regras agora mudam com o tempo'),
              ('Nothing asks to rebuild state from history; this is the strategy question, not the audit one.',
               'Nada pede reconstruir estado a partir do histórico; esta é a pergunta da strategy, não a da auditoria.')),
         ]),
    dict(id='ex-0fwpcg9d', section='drill', type='quiz', difficulty='hard',
         prompt=('A colleague says layered.py is better design than plain.py because it follows more principles from this course. What is the strongest answer?',
                 'Um colega diz que layered.py é um projeto melhor que plain.py porque segue mais princípios deste curso. Qual é a resposta mais forte?'),
         choices=[
             (False, ('Principles do not matter in Python', 'Princípios não importam em Python'),
              ('The course applies them in Python throughout; the point is when they pay.',
               'O curso os aplica em Python o tempo todo; a questão é quando eles compensam.')),
             (False, ('plain.py is faster, and speed is what matters most', 'plain.py é mais rápido, e velocidade é o que mais importa'),
              ('The lesson never argued from speed; nine calls cost microseconds.', 'A lição nunca argumentou por velocidade; nove chamadas custam microssegundos.')),
             (True, ('Ask which force each layer answers here', 'Perguntar a que força cada camada responde aqui'),
              ('Right. Each class is a sound pattern answering a force this program does not have.',
               'Isso. Cada classe é um padrão correto respondendo a uma força que este programa não tem.')),
             (False, ('layered.py has more lines, so it is harder to test', 'layered.py tem mais linhas, então é mais difícil de testar'),
              ('Line count is not testability; the layers would make a fake policy easy, if anybody needed one.',
               'Contagem de linhas não é testabilidade; as camadas facilitariam uma política falsa, se alguém precisasse.')),
         ]),
]
