#!/usr/bin/env bash
# The terminal sessions quoted in lesson 5 of llm-observability, as a script
# that produces them.
#
# THE SCRIPT IS THE SOURCE AND ITS OUTPUT IS NOT COMMITTED. Every transcript in
# this lesson was copied from running it.
#
#   sudo bash ../../lab.sh up        # once
#   sudo bash captures.sh
#
# What is STAGED rather than typed, and not shown in the lesson: the lab
# (lab.sh reset), copying the course's programs into ~/obs from
# ../../lab/code, and the replay of the week, which lesson 3 shows. The
# programs this lesson writes are put below and shown in full.
#
# THE WEEK AND THE PEOPLE IN IT ARE SIMULATED. The requests are
# data/traffic.jsonl, generated by ../../lab/traffic.py, and every thumb, every
# rephrasing and every request for a person in feedback.jsonl was decided by
# the rules written at the top of ../../lab/code/replay.py, which the lesson
# quotes. They are not a measurement of how people behave; what IS measured is
# what the assistant answered, and every count and rate below is real
# arithmetic on the files.
#
# Recorded on Ubuntu 24.04, Python 3.11, TZ=America/Sao_Paulo, on 2026-10-06.
set -uo pipefail
export TZ=America/Sao_Paulo LC_ALL=C.UTF-8
cd "$(dirname "$0")"
LAB_SH=${LAB_SH:-../../lab.sh}
CODE=$(cd "$(dirname "$LAB_SH")" && pwd)/lab/code
lab() { bash "$LAB_SH" "$@"; }
on() { printf 'ana@lab:~/obs$ %s\n' "$*"; lab exec "$*" 2>&1 || true; }
put() { lab exec "mkdir -p \"\$(dirname '$1')\" && cat > '$1'"; }
use() { for f in "$@"; do put "$f" < "$CODE/$f"; done; }
block() { printf '##### %s\n' "$1"; }
exec 9>/var/tmp/llmobs-capture.lock; flock 9
lab reset >/dev/null
use telemetry.py redact.py assistant.py replay.py tree.py costs.py
lab exec 'python assistant.py "warm up" >/dev/null; rm -f spans.jsonl; python replay.py >/dev/null'

put volume.py <<'PY'
"""volume.py: requests per day, and per hour of the day across the week, as bars."""
from collections import Counter

import costs

rows = costs.requests()
days = Counter(r["at"].strftime("%a %d") for r in rows)
hours = Counter(r["at"].hour for r in rows)
for day, n in days.items():
    print(f"{day}  {n:4}  {'#' * (n // 5)}")
print()
for h in range(24):
    print(f"{h:02}h  {hours[h]:4}  {'#' * (hours[h] // 3)}")
PY

put outcomes.py <<'PY'
"""outcomes.py: what the requests ended as, per feature and release."""
import json
from collections import Counter, defaultdict

import costs

rows = costs.requests()
dangling = {s["trace"] for s in map(json.loads, open("spans.jsonl"))
            if s["name"] == "check_citations" and s["attributes"]["app.citations.dangling"]}
by = defaultdict(Counter)
for r in rows:
    by[r["feature"], r["release"]][r["outcome"] or "error"] += 1
    by[r["feature"], r["release"]]["dangling"] += r["trace"] in dangling
print(f"{'feature':8} {'release':10} {'requests':>8} {'answered':>9} {'refused':>8} {'refused %':>9} {'dangling':>8}")
for (feature, release), c in sorted(by.items()):
    n = sum(v for k, v in c.items() if k != "dangling")
    print(f"{feature:8} {release:10} {n:8} {c['answered'] + c['summarised']:9} {c['refused']:8} "
          f"{c['refused'] / n:9.0%} {c['dangling']:8}")
PY

put signals.py <<'PY'
"""signals.py: feedback joined to its trace by id, and counted per release."""
import json
from collections import Counter, defaultdict

import costs

release = {r["trace"]: r["release"] for r in costs.requests()}
asked = Counter(r["release"] for r in costs.requests() if r["feature"] != "summary")
seen = defaultdict(Counter)
for f in map(json.loads, open("feedback.jsonl")):
    seen[release[f["trace"]]][f["kind"] if f["kind"] != "thumbs" else "thumbs " + f["value"]] += 1
print(f"{'release':10} {'requests':>8} {'rated':>6} {'down':>5} {'down %':>7} {'rephrased':>9} {'person':>7}  per 100 requests")
for rel, c in sorted(seen.items()):
    rated = c["thumbs up"] + c["thumbs down"]
    print(f"{rel:10} {asked[rel]:8} {rated:6} {c['thumbs down']:5} {c['thumbs down'] / rated:7.0%} "
          f"{c['rephrase'] / asked[rel] * 100:9.1f} {c['escalate'] / asked[rel] * 100:7.1f}")
PY

put daily.py <<'PY'
"""daily.py: one line a day of the numbers that say how the assistant is doing."""
import json
from collections import Counter, defaultdict

import costs

rows = [r for r in costs.requests() if r["feature"] != "summary"]
day = {r["trace"]: r["at"].strftime("%a %d") for r in rows}
n, refused, releases = Counter(), Counter(), defaultdict(set)
for r in rows:
    d = day[r["trace"]]
    n[d] += 1
    refused[d] += r["outcome"] == "refused"
    releases[d].add(r["release"])
fb = defaultdict(Counter)
for f in map(json.loads, open("feedback.jsonl")):
    if f["trace"] in day:
        fb[day[f["trace"]]][f["kind"] + ("-" + f["value"] if f["kind"] == "thumbs" else "")] += 1
print(f"{'day':7} {'requests':>8} {'refused':>8} {'down/rated':>11} {'rephrased':>9} {'person':>7}  release")
for d in n:
    c = fb[d]
    rated = c["thumbs-up"] + c["thumbs-down"]
    print(f"{d:7} {n[d]:8} {refused[d] / n[d]:8.0%} {c['thumbs-down']:5}/{rated:<5} {c['rephrase'] / n[d]:9.0%} "
          f"{c['escalate'] / n[d]:7.0%}  {' '.join(sorted(releases[d]))}")
PY

block volume
on 'python volume.py'

block outcomes
on 'python outcomes.py'

block feedback
on 'head -3 feedback.jsonl'
on 'python signals.py'

block daily
on 'python daily.py'

block why-order
on 'python assistant.py --feature order "Hi, I am Joana Prado (joana.prado@example.com). My order MG-20481937 has not arrived after 12 working days. Is it lost?" > /dev/null; python tree.py --attrs | grep -E "top_score|kept"'
on 'python assistant.py "My order has not arrived after 12 working days. Is it lost?" > /dev/null; python tree.py --attrs | grep -E "top_score|kept"'
