#!/usr/bin/env bash
# The terminal sessions quoted in lesson 5 of llm-observability, as a script
# that produces them.
#
# THE SCRIPT IS THE SOURCE AND ITS OUTPUT IS NOT COMMITTED. Every transcript in
# this lesson was copied from running it.
#
#   sudo bash ../../lab.sh up        # once
#   sudo bash captures.sh
#
# What is STAGED rather than typed, and not shown: ~/obs rebuilt as lesson 1
# leaves it (lab.sh reset), the programs lessons 1 to 5 show, read out of the
# lessons that show them whole (stage), and the week lesson 3 replayed (lab.sh
# week, which replays it again if anything that decides it changed).
#
# THE WEEK AND THE PEOPLE IN IT ARE SIMULATED. The requests are
# data/traffic.jsonl, generated by lesson 2's traffic.py, and every thumb,
# every rephrasing and every request for a person in feedback.jsonl was
# decided by the rules written at the top of replay.py, which the lesson
# quotes. They are not a measurement of how people behave; what IS measured is
# what the assistant answered, llama3.2:3b (a80c4f17acd5) through Ollama
# 0.40.0 at temperature 0, taken 2026-10-08, and every count and rate below is
# real arithmetic on the files.
#
# Recorded on Ubuntu 24.04, TZ=America/Sao_Paulo.
set -uo pipefail
cd "$(dirname "$0")"
. ../../lab/capture.sh
exec 9>/var/tmp/llmobs-capture.lock; flock 9

quiet lab reset
stage telemetry.py le-6wxafmfh/the-chain.md
stage assistant.py le-6wxafmfh/the-chain.md
stage tree.py le-6wxafmfh/the-chain.md
stage traffic.py le-pdj3wk00/what-customers-type.md
stage replay.py le-3s3pd3qk/replaying-a-week.md
stage costs.py le-3s3pd3qk/tokens-to-money.md
python3 "$COURSE/lab/fences.py" block "$COURSE/lessons/le-3s3pd3qk/tokens-to-money.md" '{' | put prices.json
stage volume.py le-dmtaqkde/volume.md
stage outcomes.py le-dmtaqkde/quiet-failures.md
stage signals.py le-dmtaqkde/explicit-feedback.md
stage daily.py le-dmtaqkde/the-daily-view.md
quiet lab exec 'python traffic.py data/traffic.jsonl'
quiet lab week

block volume
on 'python volume.py'

block outcomes
on 'python outcomes.py'

block feedback
on 'head -3 feedback.jsonl'
on 'python signals.py'

block daily
on 'python daily.py'

block why-order
on 'python assistant.py --feature order "Hi, I am Joana Prado (joana.prado@example.com). My order MG-20481937 has not arrived after 12 working days. Is it lost?" > /dev/null; python tree.py --attrs | grep -E "top_score|kept"'
on 'python assistant.py "My order has not arrived after 12 working days. Is it lost?" > /dev/null; python tree.py --attrs | grep -E "top_score|kept"'
