from ex import C, Q, MC, N, Z, O, M


def L(n):
    return (f'Lesson {n}.', f'Aula {n}.')


QUESTIONS = [
# ==== lesson 1
Q('ex-atmnscyy', '', 'medium',
  ('A new analyst plans to answer "which stations ran out last week" by querying the dock sensors’ server every Monday. What goes wrong?',
   'Uma analista nova pretende responder "quais estações esvaziaram na semana passada" consultando o servidor dos sensores das docas toda segunda. O que dá errado?'),
  L(1),
  C('The server answers no SQL, so there is no query to send it', 'O servidor não responde a SQL, então não há consulta para mandar a ele',
    'How it is asked is a detail; what it still holds is the problem.', 'Como se pergunta é detalhe; o problema é o que ele ainda guarda.'),
  C('Five of the seven days she wants were deleted before she asks for them', 'Cinco dos sete dias que ela quer foram apagados antes de ela perguntar',
    'Right: the server keeps two days, so a week needs a copy kept elsewhere.', 'Isso: o servidor guarda dois dias, então uma semana exige uma cópia guardada em outro lugar.', ok=True),
  C('The readings are in UTC, so the week comes out three hours shifted', 'As leituras estão em UTC, então a semana sai deslocada em três horas',
    'A clock can be converted; a reading that was deleted cannot be brought back.', 'Um relógio se converte; uma leitura apagada não volta.'),
  C('A reading a minute is too coarse to say when a station emptied', 'Uma leitura por minuto é grossa demais para dizer quando uma estação esvaziou',
    'A minute is fine enough for "for how long"; the history is what is missing.', 'Um minuto é fino o bastante para "por quanto tempo"; o que falta é a história.')),
Q('ex-yn0gfw0w', '', 'hard',
  ('The mechanics rename a column of their spreadsheet. The next load fills that column with empty values and reports success. In this course’s terms, what is that?',
   'Os mecânicos renomeiam uma coluna da planilha. A carga seguinte preenche essa coluna com valores vazios e informa sucesso. Nos termos deste curso, o que é isso?'),
  L(1),
  C('A loud failure, since the empty column is plain to see', 'Uma falha barulhenta, já que a coluna vazia está à vista',
    'Nothing stopped and nothing complained; somebody has to go and look to see it.', 'Nada parou e nada reclamou; alguém precisa ir olhar para ver.'),
  C('A freshness problem: right data, arriving late', 'Um problema de atualidade: dado certo, chegando tarde',
    'The data arrived on time; what arrived is wrong.', 'O dado chegou na hora; o que chegou está errado.'),
  C('The quiet kind of failure, which nobody notices until a number is wrong', 'O tipo silencioso de falha, que ninguém nota até um número sair errado',
    'Right: every dock now reads as unbroken and the load said it worked.', 'Isso: toda doca agora parece inteira e a carga disse que funcionou.', ok=True),
  C('The app team’s schema change, and so no failure of the load', 'Uma mudança de esquema do time do app, e por isso não uma falha da carga',
    'The spreadsheet is the mechanics’, and a load that reports success on a wrong result has failed.', 'A planilha é dos mecânicos, e uma carga que informa sucesso com um resultado errado falhou.')),
Q('ex-b56n4247', '', 'medium',
  ('Marta asks whether the price change in August made people ride less. In the table of roles, whose question is that?',
   'Marta pergunta se a mudança de preço em agosto fez as pessoas pedalarem menos. Na tabela de cargos, de quem é essa pergunta?'),
  L(1),
  C('The analyst’s, since it is a question that has been asked', 'Da analista, já que é uma pergunta que foi feita',
    'The analyst answers with a number or a chart; whether a change caused a drop is an estimate of cause.', 'A analista responde com um número ou um gráfico; se uma mudança causou uma queda é uma estimativa de causa.'),
  C('The analytics engineer’s, who defines what a ride is', 'Do engenheiro de analytics, que define o que é uma viagem',
    'The definition is needed first, and it does not answer the question.', 'A definição é necessária antes, e não responde a pergunta.'),
  C('The data engineer’s, who has the rides', 'Do engenheiro de dados, que tem as viagens',
    'He makes it answerable; somebody else answers it.', 'Ele a torna respondível; outra pessoa responde.'),
  C('The data scientist’s', 'Do cientista de dados',
    'Right: an estimate of what caused what, as in "did the new pricing work".', 'Isso: uma estimativa do que causou o quê, como em "o preço novo funcionou".', ok=True)),
Q('ex-573j26ak', '', 'medium',
  ('A company collects and stores its data reliably, has no cleaned tables, and wants to run experiments on prices. Which level of Rogati’s pyramid has to be built next?',
   'Uma empresa coleta e guarda seus dados com confiabilidade, não tem tabelas limpas, e quer fazer experimentos com preços. Que nível da pirâmide de Rogati precisa ser construído em seguida?'),
  L(1),
  C('aggregate and label', 'agregar e rotular',
    'That level rests on the one that has to come first.', 'Esse nível se apoia no que precisa vir antes.'),
  C('explore and transform', 'explorar e transformar',
    'Right: the third level, the last of the data engineer’s three.', 'Isso: o terceiro nível, o último dos três do engenheiro de dados.', ok=True),
  C('move and store', 'mover e guardar',
    'The company already does that reliably.', 'A empresa já faz isso com confiabilidade.'),
  C('learn and optimise', 'aprender e otimizar',
    'Experiments are this level: what they want, two levels above what they have.', 'Experimentos são este nível: o que eles querem, dois níveis acima do que têm.')),
Q('ex-rtmqpdp1', '', 'medium',
  ('A stream processor in 2025 reports seven rides on a morning that had six. Which of the four questions that have not changed in thirty years did it fail?',
   'Um processador de fluxo em 2025 informa sete viagens numa manhã que teve seis. Qual das quatro perguntas que não mudaram em trinta anos ele não respondeu?'),
  L(1),
  C('Did all of it arrive?', 'Chegou tudo?',
    'Nothing is missing; there is one too many.', 'Não falta nada; sobra um.'),
  C('Is it what the source meant?', 'É o que a fonte quis dizer?',
    'Each ride is what the source said; one of them is there twice.', 'Cada viagem é o que a fonte disse; uma delas está lá duas vezes.'),
  C('Is it here in time?', 'Chegou a tempo?',
    'It arrived; it arrived too often.', 'Chegou; chegou vezes demais.'),
  C('Did any of it arrive twice?', 'Alguma coisa chegou duas vezes?',
    'Right: one ride counted twice, the `twice.py` failure.', 'Isso: uma viagem contada duas vezes, a falha do `twice.py`.', ok=True)),
Q('ex-am2zbvfj', '', 'hard',
  ('By mistake, `first.py` is given the export for 13 September instead of the 14th. Its columns and rows are in order. What does it print?',
   'Por engano, o `first.py` recebe a exportação de 13 de setembro em vez da do dia 14. As colunas e as linhas estão em ordem. O que ele imprime?'),
  L(1),
  C('A `KeyError`, because the dates do not match the program', 'Um `KeyError`, porque as datas não batem com o programa',
    'A `KeyError` needs a missing column; the dates are values, and nothing reads them.', 'Um `KeyError` precisa de uma coluna faltando; as datas são valores, e nada as lê.'),
  C('Counts headed "on 14 September", printed with no complaint', 'Contagens com o título "on 14 September", impressas sem reclamar',
    'Right: the day is in the program’s text, not checked against the data. Nobody checked it was the right day.', 'Isso: o dia está no texto do programa, sem conferência com o dado. Ninguém conferiu se era o dia certo.', ok=True),
  C('Zero rides, since none of them started on the 14th', 'Zero viagens, já que nenhuma começou no dia 14',
    'The program counts every row it is given, whatever its date.', 'O programa conta cada linha que recebe, qualquer que seja a data.'),
  C('A refusal, since `started_at` disagrees with the title', 'Uma recusa, já que `started_at` discorda do título',
    'Nothing in it compares the two.', 'Nada nele compara os dois.')),
Q('ex-v752jn5b', '', 'medium',
  ('Why does lesson 1 say a pipeline is never finished, where an analysis is?',
   'Por que a aula 1 diz que um pipeline nunca está terminado, e uma análise está?'),
  L(1),
  C('Its code is too long to complete within one sprint', 'O código dele é longo demais para ficar pronto numa sprint',
    'Length has nothing to do with it; a ten-line pipeline runs tonight too.', 'O tamanho não tem nada a ver; um pipeline de dez linhas também roda hoje à noite.'),
  C('It runs again tonight, against a source that changes', 'Ele roda de novo hoje à noite, contra uma fonte que muda',
    'Right: it is software that runs every day.', 'Isso: é software que roda todo dia.', ok=True),
  C('Its users keep asking it for new charts', 'Os usuários ficam pedindo gráficos novos a ele',
    'Charts are the analyst’s delivery, and each one is finished when delivered.', 'Gráficos são a entrega da analista, e cada um está terminado quando entregue.'),
  C('Its tests are run in production', 'Os testes dele rodam em produção',
    'That is not what the lesson says, nor a good habit.', 'Não é o que a aula diz, nem um bom hábito.')),
Q('ex-2ygvkcv6', '', 'medium',
  ('Roda Livre’s data team is two people. Who does the analytics engineer’s work there?',
   'O time de dados da Roda Livre tem duas pessoas. Quem faz o trabalho de engenheiro de analytics ali?'),
  L(1),
  C('Nobody, since a team of two has no room for the role', 'Ninguém, já que um time de dois não tem espaço para o cargo',
    'The work still has to be done, and somebody does it.', 'O trabalho continua precisando ser feito, e alguém o faz.'),
  C('Marta, because she asks the questions', 'Marta, porque é ela quem faz as perguntas',
    'She asks; the definitions are written by the data team.', 'Ela pergunta; as definições são escritas pelo time de dados.'),
  C('A third hire, since the role needs a person of its own', 'Uma terceira contratação, já que o cargo precisa de uma pessoa própria',
    'The roles name the work, not the people.', 'Os cargos nomeiam o trabalho, não as pessoas.'),
  C('Davi, who writes the SQL that defines a ride as well as the pipelines', 'Davi, que escreve o SQL que define uma viagem além dos pipelines',
    'Right: the roles name the work, and in a team of two one person does several.', 'Isso: os cargos nomeiam o trabalho, e num time de dois uma pessoa faz vários.', ok=True)),
Q('ex-d1ragnqv', '', 'hard',
  ('A job advert says the data engineer will "write the SQL the analysts need". What does lesson 1 say that picture leaves out?',
   'Um anúncio de vaga diz que o engenheiro de dados vai "escrever o SQL de que os analistas precisam". O que a aula 1 diz que essa imagem deixa de fora?'),
  L(1),
  C('The system around the SQL', 'O sistema em volta do SQL',
    'Right: SQL is a skill the job uses; the job is what makes the tables be there.', 'Isso: SQL é uma habilidade que o trabalho usa; o trabalho é o que faz as tabelas estarem lá.', ok=True),
  C('The dashboards those queries feed', 'Os dashboards que essas consultas alimentam',
    'Dashboards are the analyst’s delivery, further from the engineer than the SQL is.', 'Dashboards são a entrega da analista, mais longe do engenheiro que o SQL.'),
  C('Python, which takes over where SQL stops', 'Python, que assume onde o SQL para',
    'Python is a skill too; the advert is wrong about the job, not about a language.', 'Python também é uma habilidade; o anúncio erra sobre o trabalho, não sobre uma linguagem.'),
  C('Keeping one database fast and safe for its users', 'Manter um banco de dados rápido e seguro para os usuários',
    'That is a database administrator’s work, which the lesson separates from this one.', 'Esse é o trabalho de um administrador de banco, que a aula separa deste.')),
Q('ex-wrnz927q', '', 'easy',
  ('Marta never sees Davi’s work. When, according to lesson 1, does she notice it?',
   'Marta nunca vê o trabalho de Davi. Quando, segundo a aula 1, ela o percebe?'),
  L(1),
  C('When she reads the documentation of each table', 'Quando lê a documentação de cada tabela',
    'Documentation matters, and it is not where she meets his work.', 'Documentação importa, e não é onde ela encontra o trabalho dele.'),
  C('When the morning check sends her its summary', 'Quando a verificação da manhã manda o resumo para ela',
    'That check is for the data team, not for Marta.', 'Essa verificação é para o time de dados, não para Marta.'),
  C('When it is absent: a report that is late or wrong', 'Quando ele falta: um relatório atrasado ou errado',
    'Right: she sees only its absence.', 'Isso: ela só vê a falta dele.', ok=True),
  C('When she approves a new source for the platform', 'Quando aprova uma fonte nova para a plataforma',
    'She asks questions; she does not approve sources.', 'Ela faz perguntas; não aprova fontes.')),

# ==== lesson 2
Q('ex-xn8tegys', '', 'hard',
  ('Payments last landed at 06:50. The team’s objective is two hours, and the agreement with the city is four hours at 09:00. What is the state at 09:00?',
   'Os pagamentos chegaram pela última vez às 06:50. O objetivo do time é de duas horas, e o acordo com a prefeitura é de quatro horas às 09:00. Qual é a situação às 09:00?'),
  L(2),
  C('Both are met, since 2.2 hours rounds down to 2', 'Os dois são cumpridos, já que 2,2 horas arredonda para 2',
    'The check compares the age as measured; 2.2 is over 2.', 'A verificação compara a idade medida; 2,2 passa de 2.'),
  C('An SLA breach, so the city earns a discount', 'Uma violação de SLA, então a prefeitura ganha um desconto',
    'The agreement allows four hours, and 2.2 is inside it.', 'O acordo permite quatro horas, e 2,2 está dentro.'),
  C('An SLO breach, while the promise made outside the team still holds', 'Uma violação de SLO, enquanto a promessa feita fora do time continua de pé',
    'Right: the team hears about it with time left to fix it.', 'Isso: o time fica sabendo com tempo para consertar.', ok=True),
  C('Neither applies, since the city is promised rides and not payments', 'Nenhum se aplica, já que à prefeitura se prometem viagens, não pagamentos',
    'The question is about the state of the payments feed against its own two numbers.', 'A pergunta é sobre a situação do feed de pagamentos diante dos seus dois números.')),
Q('ex-24etqvx5', '', 'medium',
  ('A matrix gives 36 to one option and 35 to another. What is the honest output?',
   'Uma matriz dá 36 a uma opção e 35 a outra. Qual é a saída honesta?'),
  L(2),
  C('These two are equivalent on our criteria', 'Essas duas são equivalentes nos critérios que temos',
    'Right: the choice then goes to something the matrix does not hold.', 'Isso: a escolha vai então para algo que a matriz não contém.', ok=True),
  C('The first option, by a point', 'A primeira opção, por um ponto',
    'One point is less than the doubt in any single score.', 'Um ponto é menos que a dúvida em qualquer nota isolada.'),
  C('Another round of scoring, until one leads by five', 'Outra rodada de notas, até uma liderar por cinco',
    'That is scoring until the numbers agree with somebody, which launders a preference.', 'Isso é dar notas até os números concordarem com alguém, o que disfarça uma preferência.'),
  C('More criteria, until the tie is broken', 'Mais critérios, até o empate se desfazer',
    'Criteria added to break a tie are chosen for the result they give.', 'Critérios acrescentados para desempatar são escolhidos pelo resultado que dão.')),
Q('ex-dmwgs645', '', 'hard',
  ('A matrix scores four options on "bill", "upkeep", "licence" and "support contract", and on one criterion for everything else. What is wrong with it?',
   'Uma matriz dá notas a quatro opções em "fatura", "manutenção", "licença" e "contrato de suporte", e num critério para todo o resto. O que há de errado nela?'),
  L(2),
  C('Four options are too many to compare in one matrix', 'Quatro opções são demais para comparar numa matriz',
    'The number of options is not the trouble here.', 'O número de opções não é o problema aqui.'),
  C('The weights were not shown to add up to ten', 'Não se mostrou que os pesos somam dez',
    'Weights summing to ten was a convenience in `matrix.py`, not a rule.', 'Pesos somando dez foi uma conveniência do `matrix.py`, não uma regra.'),
  C('A scale of one to five is too coarse to separate them', 'Uma escala de um a cinco é grossa demais para separá-las',
    'A finer scale would decide the same thing more precisely.', 'Uma escala mais fina decidiria a mesma coisa com mais precisão.'),
  C('Cost is counted four times', 'O custo é contado quatro vezes',
    'Right: the matrix decided for the cheapest before anybody scored.', 'Isso: a matriz decidiu pela mais barata antes de alguém dar nota.', ok=True)),
Q('ex-74af1e21', '', 'medium',
  ('A colleague wants to move the rides into a new kind of database because "PostgreSQL will not scale". What does lesson 2 ask for before a token is spent?',
   'Um colega quer levar as viagens para um tipo novo de banco porque "o PostgreSQL não vai escalar". O que a aula 2 pede antes de gastar uma ficha?'),
  L(2),
  C('A measured fact about today, not a forecast about next year', 'Um fato medido sobre hoje, não uma previsão sobre o ano que vem',
    'Right: "it took ten minutes this morning" is evidence; "it will not scale" is not.', 'Isso: "levou dez minutos hoje de manhã" é evidência; "não vai escalar" não é.', ok=True),
  C('A benchmark published by the new database’s vendor', 'Um benchmark publicado pelo fornecedor do banco novo',
    'That measures the vendor’s case, not Roda Livre’s.', 'Isso mede o caso do fornecedor, não o da Roda Livre.'),
  C('The agreement of the two most senior engineers', 'A concordância dos dois engenheiros mais sêniores',
    'Seniority is not evidence about this workload.', 'Senioridade não é evidência sobre esta carga.'),
  C('A scoring matrix on which the new database wins', 'Uma matriz de notas em que o banco novo ganha',
    'A matrix built to win is the habit that spoils matrices.', 'Uma matriz feita para ganhar é o hábito que estraga matrizes.')),
Q('ex-0k08kta4', '', 'medium',
  ('A team builds its pipeline now and schedules "the security phase" for next quarter. What does lesson 2’s word "undercurrent" say about that?',
   'Um time constrói o pipeline agora e marca "a fase de segurança" para o próximo trimestre. O que a palavra "corrente subterrânea" da aula 2 diz sobre isso?'),
  L(2),
  C('It is the right order once the pipeline works', 'É a ordem certa, quando o pipeline estiver funcionando',
    'By then every copy has whatever the first stage let in, and it has to be found.', 'Até lá cada cópia tem o que a primeira etapa deixou entrar, e isso precisa ser encontrado.'),
  C('Security is the question asked at each stage', 'Segurança é a pergunta feita em cada etapa',
    'Right: it runs under every stage, not after them.', 'Isso: ela corre por baixo de cada etapa, não depois delas.', ok=True),
  C('It is enough if the raw zone is encrypted', 'Basta a zona bruta estar criptografada',
    'Who can read each table, at each stage, is the question; encryption at one place does not answer it.', 'Quem pode ler cada tabela, em cada etapa, é a pergunta; criptografia num lugar não a responde.'),
  C('Security belongs to the cloud provider in a managed service', 'Num serviço gerenciado, a segurança é do provedor de nuvem',
    'The provider runs the software; who may read the payments is still the team’s decision.', 'O provedor roda o software; quem pode ler os pagamentos continua sendo decisão do time.')),
Q('ex-73b4j35v', '', 'hard',
  ('In `cost.py`, "managed, every 5 min" pays 1226.12 a month in queries, each refresh reading the whole year. If each refresh read only the previous day instead, about what would that line become?',
   'No `cost.py`, "managed, every 5 min" paga 1.226,12 por mês em consultas, cada atualização lendo o ano inteiro. Se cada atualização lesse só o dia anterior, mais ou menos quanto essa linha passaria a ser?'),
  L(2),
  C('About 0.01, like the plan that runs once a day', 'Cerca de 0,01, como o plano que roda uma vez por dia',
    'That plan reads one day thirty times a month; this one reads one day 8,640 times.', 'Aquele plano lê um dia trinta vezes por mês; este lê um dia 8.640 vezes.'),
  C('About 613, half as much', 'Cerca de 613, a metade',
    'The bytes read fall by a factor of 365, not 2.', 'Os bytes lidos caem por um fator de 365, não de 2.'),
  C('About 3.36', 'Cerca de 3,36',
    'Right: the same refreshes, each reading a 365th of the bytes.', 'Isso: as mesmas atualizações, cada uma lendo 1/365 dos bytes.', ok=True),
  C('About 1226.12, since the number of refreshes is the same', 'Cerca de 1.226,12, já que o número de atualizações é o mesmo',
    'The engine charges for the bytes it reads, not for the refreshes.', 'O motor cobra pelos bytes que lê, não pelas atualizações.')),
N('ex-q82xwrrf', '', 'medium',
  ('In `cost.py`, how many reais a month more does "our own server" cost than "managed, once a day"?',
   'No `cost.py`, quantos reais por mês "our own server" custa a mais que "managed, once a day"?'),
  L(2),
  1391.99, 0.05, ('reais', 'reais')),
O('ex-cd9z9yg2', '', 'medium',
  ('Put the three promises about the rides’ freshness in order, from the one each of the others rests on.',
   'Ponha as três promessas sobre a atualidade das viagens em ordem, começando por aquela em que as outras se apoiam.'),
  L(2),
  [('the age of the newest ride at 09:00, measured', 'a idade da viagem mais nova às 09:00, medida'),
   ('at most two hours old on 95% of mornings, a target the team sets itself', 'no máximo duas horas em 95% das manhãs, um alvo que o time se dá'),
   ('at most four hours old for the city, with a discount when broken', 'no máximo quatro horas para a prefeitura, com desconto quando falha')],
  ('An SLA rests on an SLO, which rests on an SLI.', 'Um SLA se apoia num SLO, que se apoia num SLI.')),
Z('ex-0mccjtn3', '', 'medium',
  ('Choosing a technology for what it does for the chooser’s career rather than for the problem is called ___-driven development.',
   'Escolher uma tecnologia pelo que ela faz pela carreira de quem escolhe, e não pelo problema, se chama desenvolvimento orientado a ___.'),
  L(2),
  ['résumé', 'resume'], ['currículo']),
M('ex-1w2y473d', '', 'medium',
  ('Match each criterion for choosing a technology to the question that tests it.',
   'Associe cada critério de escolha de tecnologia à pergunta que o testa.'),
  L(2),
  [(('the team', 'o time'), ('who here can fix it at three in the morning?', 'quem aqui consegue consertar às três da manhã?')),
   (('lock-in', 'aprisionamento'), ('what would leaving it cost?', 'quanto custaria sair dela?')),
   (('maturity', 'maturidade'), ('has somebody already hit this error?', 'alguém já topou com este erro?')),
   (('reversibility', 'reversibilidade'), ('can it be undone at modest cost?', 'dá para desfazer a um custo modesto?'))]),

# ==== lesson 3
Q('ex-r6a1epe3', '', 'hard',
  ('Marta moves the false-start rule from two minutes to one. Raw files were deleted after thirty days. Which days can be rebuilt under the new rule?',
   'Marta muda a regra de partida falsa de dois minutos para um. Os arquivos brutos eram apagados depois de trinta dias. Que dias podem ser refeitos com a regra nova?'),
  L(3),
  C('The last thirty', 'Os últimos trinta',
    'Right: only raw holds the rides the old rule dropped.', 'Isso: só a zona bruta guarda as viagens que a regra antiga descartou.', ok=True),
  C('Every day, from the cleaned zone', 'Todos os dias, a partir da zona limpa',
    'The cleaned zone lost the rides between one and two minutes when it dropped them.', 'A zona limpa perdeu as viagens entre um e dois minutos quando as descartou.'),
  C('Every day, by asking the app’s database again', 'Todos os dias, consultando de novo o banco do aplicativo',
    'The app keeps the present; a refunded ride has already been changed in place.', 'O app guarda o presente; uma viagem reembolsada já foi alterada no lugar.'),
  C('Every day, from the curated counts', 'Todos os dias, a partir das contagens curadas',
    'Counts are made after the rule; they cannot be unmade into rides.', 'As contagens são feitas depois da regra; não dá para desfazê-las em viagens.')),
Q('ex-xjvxrwq5', '', 'hard',
  ('An analyst wants rides per station including false starts. Where should she get them?',
   'Uma analista quer as viagens por estação incluindo as partidas falsas. De onde ela deve tirá-las?'),
  L(3),
  C('From the raw zone, since it holds every ride', 'Da zona bruta, já que ela guarda todas as viagens',
    'Raw is read by the transformation and nobody else.', 'A zona bruta é lida pela transformação e por mais ninguém.'),
  C('From a new curated table built from raw', 'De uma tabela curada nova, feita a partir da bruta',
    'Right: one definition, written once, that every reader can share.', 'Isso: uma definição, escrita uma vez, que qualquer leitor pode usar.', ok=True),
  C('From the app’s database, since it is the source', 'Do banco do aplicativo, já que ele é a fonte',
    'Delivery never reads the app’s database, and it would slow the app.', 'A entrega nunca lê o banco do aplicativo, e isso deixaria o app lento.'),
  C('From the cleaned zone, after undoing the rule', 'Da zona limpa, depois de desfazer a regra',
    'The cleaned zone no longer has the rides the rule dropped.', 'A zona limpa não tem mais as viagens que a regra descartou.')),
Q('ex-hhx03dvq', '', 'medium',
  ('The payments provider calls Roda Livre’s address each time a charge succeeds. The receiver was down for an hour. What happened to that hour’s charges?',
   'O provedor de pagamentos chama um endereço da Roda Livre a cada cobrança bem-sucedida. O receptor ficou fora do ar por uma hora. O que aconteceu com as cobranças dessa hora?'),
  L(3),
  C('They are picked up by the next nightly pull', 'Elas são apanhadas pela próxima coleta noturna',
    'Nothing pulls payments here; they are pushed.', 'Nada coleta pagamentos aqui; eles são empurrados.'),
  C('They wait in the raw zone until the receiver returns', 'Elas esperam na zona bruta até o receptor voltar',
    'The raw zone is written by the receiver; with it down, nothing lands.', 'A zona bruta é escrita pelo receptor; com ele fora, nada chega.'),
  C('Lost, unless the provider sends them again', 'Perdidas, a não ser que o provedor as mande de novo',
    'Right: with push, the source decides when, and the receiver must be listening.', 'Isso: com push, quem decide quando é a fonte, e o receptor precisa estar ouvindo.', ok=True),
  C('Recorded by ingestion with a gap marker', 'Registradas pela ingestão com uma marca de lacuna',
    'Ingestion cannot mark what never reached it.', 'A ingestão não marca o que nunca chegou a ela.')),
Q('ex-516ak9br', '', 'hard',
  ('Suppose `trace.py` had printed curated 29, clean 29, raw 29 and app.db 31 for Rua XV. Which stage is suspected?',
   'Suponha que o `trace.py` tivesse impresso curated 29, clean 29, raw 29 e app.db 31 para a Rua XV. Que etapa fica sob suspeita?'),
  L(3),
  C('Transformation', 'Transformação',
    'Clean and raw agree; the rule dropped nothing.', 'Limpa e bruta concordam; a regra não descartou nada.'),
  C('Delivery', 'Entrega',
    'The report matches curated.', 'O relatório bate com a curada.'),
  C('Generation', 'Geração',
    'The app holds 31; generation did its part.', 'O app tem 31; a geração fez sua parte.'),
  C('Ingestion', 'Ingestão',
    'Right: the copy should hold what the source held, and two rides are missing between them.', 'Isso: a cópia deveria ter o que a fonte tinha, e faltam duas viagens entre elas.', ok=True)),
Q('ex-npyc80pd', '', 'hard',
  ('The app writes a ride when the bicycle is docked again, and `ingest.py` copies a day by `started_at` at 00:05. What becomes of a ride that starts on Monday at 23:50 and ends at 00:20?',
   'O app grava uma viagem quando a bicicleta é devolvida, e o `ingest.py` copia um dia pelo `started_at` às 00:05. O que acontece com uma viagem que começa na segunda às 23:50 e termina às 00:20?'),
  L(3),
  C('It is copied as an open ride with no end', 'É copiada como viagem aberta, sem fim',
    'At 00:05 there is no row yet to copy.', 'Às 00:05 ainda não há linha para copiar.'),
  C('It is missed unless Monday is copied again', 'Fica de fora, a menos que segunda seja copiada de novo',
    'Right: Monday’s copy ran before the row existed, and Tuesday’s copies Tuesday’s starts.', 'Isso: a cópia de segunda rodou antes de a linha existir, e a de terça copia as partidas de terça.', ok=True),
  C('It goes into Tuesday’s partition, when it ends', 'Vai para a partição de terça, quando termina',
    'The copy selects by when the ride started, and it started on Monday.', 'A cópia seleciona pelo início da viagem, e ela começou na segunda.'),
  C('It is copied twice, once into each day', 'É copiada duas vezes, uma em cada dia',
    'Neither day’s copy takes it.', 'Nenhuma das cópias a pega.')),
Q('ex-gjdvrps8', '', 'medium',
  ('Caio’s model wants one row per station per hour, with the rides and the weather. Which form of delivery is that?',
   'O modelo de Caio quer uma linha por estação por hora, com as viagens e o clima. Que forma de entrega é essa?'),
  L(3),
  C('Reverse ETL', 'ETL reverso',
    'That pushes a result into an operational tool, like the van drivers’ app.', 'Isso empurra um resultado para uma ferramenta operacional, como o app dos motoristas da van.'),
  C('A report', 'Um relatório',
    'A report is read by a person at a fixed time.', 'Um relatório é lido por uma pessoa num horário fixo.'),
  C('An API', 'Uma API',
    'An API answers a program on request, one question at a time.', 'Uma API responde a um programa sob demanda, uma pergunta por vez.'),
  C('A feature table', 'Uma tabela de features',
    'Right: its reader is a model.', 'Isso: quem a lê é um modelo.', ok=True)),
Q('ex-gepqtev3', '', 'medium',
  ('Personal data arrives in the raw zone untouched. What does that make the decision of how long raw is kept?',
   'Dados pessoais chegam intactos à zona bruta. O que isso faz da decisão de por quanto tempo a zona bruta é guardada?'),
  L(3),
  C('A cost decision, since raw is the cheapest zone to keep', 'Uma decisão de custo, já que a bruta é a zona mais barata de guardar',
    'Cost is half of it; who is described in those rows is the other half.', 'O custo é metade; quem está descrito nessas linhas é a outra metade.'),
  C('A decision for the source’s owner, who sent the data', 'Uma decisão do dono da fonte, que mandou o dado',
    'Keeping the copy is the data team’s decision.', 'Guardar a cópia é decisão do time de dados.'),
  C('A decision about privacy, as much as one about cost and rebuilding', 'Uma decisão de privacidade, tanto quanto de custo e de reconstrução',
    'Right: raw is kept as long as somebody may need to rebuild, and not longer.', 'Isso: a bruta é guardada enquanto alguém puder precisar refazer, e não mais.', ok=True),
  C('No decision at all, since raw is kept for good by rule', 'Decisão nenhuma, já que por regra a bruta é guardada para sempre',
    'The rule is to keep it while somebody may need to rebuild from it.', 'A regra é guardar enquanto alguém puder precisar refazer a partir dela.')),
N('ex-pnxctfns', '', 'medium',
  ('After `ingest.py` ran a second time for 2025-09-15, what total did `report.py` print?',
   'Depois de o `ingest.py` rodar pela segunda vez para 2025-09-15, que total o `report.py` imprimiu?'),
  L(3),
  352, 0, ('rides', 'viagens')),
O('ex-2r11yx0v', '', 'medium',
  ('Put the steps of an ELT pipeline in order.', 'Ponha os passos de um pipeline ELT em ordem.'),
  L(3),
  [('extract the rows from the app’s database', 'extrair as linhas do banco do aplicativo'),
   ('load them unchanged where the data team keeps data', 'carregá-las sem mudança onde o time de dados guarda os dados'),
   ('transform them where they now are', 'transformá-las onde elas agora estão'),
   ('deliver the curated table to its readers', 'entregar a tabela curada a quem a lê')],
  ('In ELT the raw rows are loaded before the transformation runs.', 'No ELT as linhas brutas são carregadas antes de a transformação rodar.')),
MC('ex-y84jxb3y', '', 'medium',
  ('Raw is kept. Which of these can be produced again by running programs? Choose all that apply.',
   'A zona bruta é guardada. Quais destes podem ser produzidos de novo rodando programas? Marque todos os que se aplicam.'),
  L(3),
  C('the cleaned zone', 'a zona limpa',
    'Yes: it is the output of the transformation.', 'Sim: é a saída da transformação.', ok=True),
  C('the curated tables', 'as tabelas curadas',
    'Yes: also a program’s output.', 'Sim: também saída de um programa.', ok=True),
  C('the morning report', 'o relatório da manhã',
    'Yes: `report.py` reads curated, which can be rebuilt.', 'Sim: o `report.py` lê a curada, que pode ser refeita.', ok=True),
  C('the raw zone itself', 'a própria zona bruta',
    'Raw is the output of a moment that has passed.', 'A bruta é a saída de um momento que passou.'),
  C('a night of dock readings the copy missed', 'uma noite de leituras das docas que a cópia perdeu',
    'The sensors keep two days; past that, it is gone.', 'Os sensores guardam dois dias; depois disso, já era.')),

# ==== lesson 4
Q('ex-mh2kxm5c', '', 'medium',
  ('The app team stops deleting cancelled rides and instead sets `status` to "cancelled" and moves `updated_at`. What changes for the incremental copy?',
   'O time do app para de apagar viagens canceladas e passa a pôr `status` como "cancelled" e mexer no `updated_at`. O que muda para a cópia incremental?'),
  L(4),
  C('Cancellations now reach the copy', 'Os cancelamentos agora chegam à cópia',
    'Right: a delete became an update the watermark can see.', 'Isso: uma remoção virou uma atualização que a marca d’água enxerga.', ok=True),
  C('Cancelled rides vanish from the copy too', 'As viagens canceladas somem da cópia também',
    'The copy writes rows over older versions; it does not remove them.', 'A cópia grava linhas por cima das versões antigas; não as remove.'),
  C('The copy has to become a full load to see them', 'A cópia precisa virar carga completa para enxergá-los',
    'An update with a newer `updated_at` is exactly what an incremental copy reads.', 'Uma atualização com `updated_at` mais novo é exatamente o que uma cópia incremental lê.'),
  C('The copy needs change data capture to see them', 'A cópia precisa de captura de mudanças para enxergá-los',
    'CDC was one way out for deletes; this change makes it unnecessary for cancellations.', 'CDC era uma saída para remoções; esta mudança a dispensa para cancelamentos.')),
Q('ex-x4exsk37', '', 'medium',
  ('A log parser skips any line its pattern does not match. Overnight the web server’s log format changes. What does the next morning’s count of requests show?',
   'Um parser de log pula toda linha que o padrão dele não casa. De madrugada o formato do log do servidor web muda. O que mostra a contagem de requisições da manhã seguinte?'),
  L(4),
  C('A traceback naming the first line it could not read', 'Um traceback com a primeira linha que ele não conseguiu ler',
    'A parser that skips raises nothing.', 'Um parser que pula não levanta nada.'),
  C('The same counts, since the fields are still in each line', 'As mesmas contagens, já que os campos ainda estão em cada linha',
    'The pattern no longer matches, so no field is found.', 'O padrão não casa mais, então nenhum campo é encontrado.'),
  C('Half the requests, those still in the old format', 'Metade das requisições, as que ainda estão no formato antigo',
    'After the change, every line is in the new format.', 'Depois da mudança, toda linha está no formato novo.'),
  C('A day with no requests, and no error', 'Um dia sem requisições, e sem erro',
    'Right: that is why `parse_log.py` names the lines it could not read.', 'Isso: é por isso que o `parse_log.py` nomeia as linhas que não conseguiu ler.', ok=True)),
Q('ex-4zxt8scg', '', 'medium',
  ('An application event carries `occurred_at` from the phone, and the collector adds the time it arrived. How does lesson 4 say the two are used?',
   'Um evento do aplicativo traz `occurred_at`, do celular, e o coletor acrescenta a hora em que ele chegou. Como a aula 4 diz que os dois são usados?'),
  L(4),
  C('Trust the phone’s, and ask about the collector’s', 'Confiar no do celular, e perguntar pelo do coletor',
    'The phone’s clock belongs to the customer, who can set it to 2031.', 'O relógio do celular é do cliente, que pode acertá-lo para 2031.'),
  C('Trust the collector’s; the question is about the phone’s', 'Confiar no do coletor; a pergunta é sobre o do celular',
    'Right: keep both, because each answers something the other cannot.', 'Isso: guarde os dois, porque cada um responde algo que o outro não responde.', ok=True),
  C('Keep the collector’s and drop the phone’s as noise', 'Guardar o do coletor e descartar o do celular como ruído',
    'An event made in a tunnel happened before it arrived; dropping that time loses when it happened.', 'Um evento feito num túnel aconteceu antes de chegar; descartar esse horário perde quando ele aconteceu.'),
  C('Either, since the two differ by a second or two', 'Qualquer um, já que os dois diferem por um ou dois segundos',
    'An offline phone sends minutes or days later.', 'Um celular sem rede manda minutos ou dias depois.')),
Q('ex-vsqhny8s', '', 'hard',
  ('A dock’s readings reach the server with sequence numbers 11, 12, 14, 13, 13. What does a loader keyed on sensor and sequence number count?',
   'As leituras de uma doca chegam ao servidor com os números de sequência 11, 12, 14, 13, 13. O que conta um carregador com chave no sensor e no número de sequência?'),
  L(4),
  C('One missing, one duplicate', 'Uma faltando, uma duplicada',
    '13 arrived; it was late, not missing.', 'A 13 chegou; atrasada, não faltando.'),
  C('One late, one duplicate, none missing', 'Uma atrasada, uma duplicada, nenhuma faltando',
    'Right: 13 came after 14, then came again.', 'Isso: a 13 veio depois da 14, e depois veio de novo.', ok=True),
  C('Two duplicates', 'Duas duplicadas',
    'Only 13 is seen twice.', 'Só a 13 aparece duas vezes.'),
  C('One late, one missing, no duplicate', 'Uma atrasada e uma faltando, sem duplicada',
    'The second 13 is a key already seen.', 'O segundo 13 é uma chave já vista.')),
Q('ex-95sc1tt3', '', 'medium',
  ('A partner drops its export in object storage, which has no rename. Which convention tells the reader the delivery is complete?',
   'Um parceiro deixa a exportação num object storage, que não tem renomear. Que convenção diz ao leitor que a entrega está completa?'),
  L(4),
  C('Write under a temporary name, then rename', 'Gravar com um nome temporário, depois renomear',
    'That works on one filesystem; object storage has no rename to do it with.', 'Isso funciona num sistema de arquivos; object storage não tem renomear para isso.'),
  C('Wait until the file has stopped growing for a while', 'Esperar até o arquivo parar de crescer por um tempo',
    'A writer that died halfway also stops growing.', 'Um escritor que morreu no meio também para de crescer.'),
  C('A marker the writer adds last, like `_SUCCESS`', 'Um marcador gravado por último, como `_SUCCESS`',
    'Right: the reader touches nothing until it exists; a manifest also carries the rows and a checksum.', 'Isso: o leitor não toca em nada até ele existir; um manifesto também traz as linhas e um checksum.', ok=True),
  C('Read the file twice and compare the two sizes', 'Ler o arquivo duas vezes e comparar os dois tamanhos',
    'Two equal sizes say nothing about whether the writer finished.', 'Dois tamanhos iguais não dizem se o escritor terminou.')),
Q('ex-xr7npmep', '', 'hard',
  ('The sensor vendor delivers at least once. Which line of the dock readings’ contract lets the data team remove the duplicates?',
   'O fornecedor dos sensores entrega pelo menos uma vez. Que linha do contrato das leituras das docas permite ao time de dados remover as duplicatas?'),
  L(4),
  C('"expected": one reading per sensor per minute', '"expected": uma leitura por sensor por minuto',
    'That line is what counts the gaps.', 'Essa linha é o que conta as lacunas.'),
  C('"changes": announced thirty days ahead', '"changes": avisadas com trinta dias de antecedência',
    'That one is the warning before a change.', 'Essa é o aviso antes de uma mudança.'),
  C('"personal_data": none', '"personal_data": none',
    'It says what is sensitive, not what repeats.', 'Ela diz o que é sensível, não o que se repete.'),
  C('"key": sensor_id and seq', '"key": sensor_id e seq',
    'Right: two readings with one key are one reading.', 'Isso: duas leituras com uma chave só são uma leitura.', ok=True)),
N('ex-1hjqv5g2', '', 'medium',
  ('`docks.py` reported 185 readings arrived, 11 of them twice. How many distinct readings arrived?',
   'O `docks.py` informou 185 leituras chegadas, 11 delas duas vezes. Quantas leituras distintas chegaram?'),
  L(4),
  174, 0, ('readings', 'leituras')),
O('ex-hwdbay2g', '', 'medium',
  ('Change data capture is switched on today for the rides table. Put its first steps in order.',
   'A captura de mudanças é ligada hoje para a tabela de viagens. Ponha os primeiros passos dela em ordem.'),
  L(4),
  [('take one full copy of the table', 'tirar uma cópia completa da tabela'),
   ('read the log from the moment that copy was taken', 'ler o log a partir do momento em que a cópia foi tirada'),
   ('apply each change to the copy, in log order', 'aplicar cada mudança à cópia, na ordem do log')],
  ('The log holds recent changes only, so the full copy has to come first.', 'O log guarda só as mudanças recentes, então a cópia completa vem primeiro.')),
MC('ex-ar143qv1', '', 'medium',
  ('Which of these produce a table that looks complete, with no error anywhere? Choose all that apply.',
   'Quais destes produzem uma tabela que parece completa, sem erro em lugar nenhum? Marque todos os que se aplicam.'),
  L(4),
  C('an incremental copy meeting a deleted row', 'uma cópia incremental diante de uma linha apagada',
    'Yes: the copy keeps the row for good.', 'Sim: a cópia guarda a linha para sempre.', ok=True),
  C('a file loaded while its writer was still writing it', 'um arquivo carregado enquanto quem escrevia ainda escrevia',
    'Yes: 718 rows of a thousand, and no error.', 'Sim: 718 linhas de mil, e nenhum erro.', ok=True),
  C('a reading sent again after a lost acknowledgement', 'uma leitura reenviada depois de uma confirmação perdida',
    'Yes: one more row, perfectly well formed.', 'Sim: uma linha a mais, perfeitamente bem formada.', ok=True),
  C('a client calling the API with a wrong token', 'um cliente chamando a API com um token errado',
    'That is a `401`, and the program stops.', 'Isso é um `401`, e o programa para.'),
  C('a careful load finding no manifest beside the file', 'uma carga cuidadosa sem encontrar manifesto ao lado do arquivo',
    'It loads nothing and says so.', 'Ela não carrega nada e avisa.')),
Z('ex-njmh2eza', '', 'medium',
  ('Marking a cancelled ride with a `deleted_at` column, instead of removing its row, is called a ___ delete.',
   'Marcar uma viagem cancelada com uma coluna `deleted_at`, em vez de remover a linha, se chama remoção ___.'),
  L(4),
  ['soft'], ['lógica', 'soft']),

# ==== lesson 5
Q('ex-qx7tpgxm', '', 'medium',
  ('A vendor sends CSV files with a separate document listing each column’s type. Nothing checks the files against it. Where is a value of the wrong type caught?',
   'Um fornecedor manda arquivos CSV com um documento à parte listando o tipo de cada coluna. Nada confere os arquivos com ele. Onde um valor do tipo errado é pego?'),
  L(5),
  C('By the CSV format, which keeps the header’s types', 'Pelo formato CSV, que guarda os tipos do cabeçalho',
    'A CSV header holds names and no types.', 'O cabeçalho de um CSV tem nomes e nenhum tipo.'),
  C('At the vendor, when the file is exported', 'No fornecedor, quando o arquivo é exportado',
    'Nothing there checks it either.', 'Nada ali confere também.'),
  C('When the file lands in the raw zone', 'Quando o arquivo chega à zona bruta',
    'Landing raw changes nothing and checks nothing.', 'Chegar à zona bruta não muda nada e não confere nada.'),
  C('By whichever reader uses the value', 'Por qualquer leitor que for usar o valor',
    'Right: a document nobody enforces leaves the schema on read.', 'Isso: um documento que ninguém impõe deixa o esquema na leitura.', ok=True)),
Q('ex-44pwks9g', '', 'medium',
  ('Why did lesson 5 explode `charges` into a table of its own rather than writing columns `charges.0`, `charges.1` and `charges.2`?',
   'Por que a aula 5 explodiu `charges` numa tabela própria em vez de escrever as colunas `charges.0`, `charges.1` e `charges.2`?'),
  L(5),
  C('Positions make one question look in many columns', 'Posições fazem uma pergunta procurar em várias colunas',
    'Right: "how much did unlock fees bring in" would search every position.', 'Isso: "quanto rendeu a taxa de desbloqueio" procuraria em todas as posições.', ok=True),
  C('Python cannot read an array out of a JSON file', 'Python não consegue ler um array de um arquivo JSON',
    '`json.loads` reads arrays as lists.', 'O `json.loads` lê arrays como listas.'),
  C('Three columns would lose the ride each charge came from', 'Três colunas perderiam a viagem de onde cada cobrança veio',
    'They would sit on the ride’s own row; that was not the trouble.', 'Elas ficariam na própria linha da viagem; o problema não era esse.'),
  C('A table column cannot hold a number in cents', 'Uma coluna de tabela não consegue guardar um número em centavos',
    'It can; `cents` is an ordinary integer column in the exploded table.', 'Consegue; `cents` é uma coluna inteira comum na tabela explodida.')),
Q('ex-pjeas4mh', '', 'hard',
  ('App 4.3 starts sending `end.minutes` as the text "26" instead of the number 26. How does `drift.py` report it?',
   'O app 4.3 passa a mandar `end.minutes` como o texto "26" em vez do número 26. Como o `drift.py` informa isso?'),
  L(5),
  C('As a type change, int to str', 'Como uma mudança de tipo, int para str',
    'Right: the dangerous kind, the same as `bike.battery`.', 'Isso: o tipo perigoso, o mesmo do `bike.battery`.', ok=True),
  C('As a new field', 'Como um campo novo',
    'The name is the same; only its type moved.', 'O nome é o mesmo; só o tipo mudou.'),
  C('It does not, since the value is still 26', 'Não informa, já que o valor continua 26',
    'It compares the names of types, and `"26"` is a `str`.', 'Ele compara nomes de tipos, e `"26"` é `str`.'),
  C('As a field gone and another one added', 'Como um campo sumido e outro acrescentado',
    'The dotted name is present in both batches.', 'O nome pontuado está presente nos dois lotes.')),
Q('ex-xet1324m', '', 'medium',
  ('Customers attach photos of damaged bicycles, stored with their metadata. Which question can be answered from the metadata alone?',
   'Clientes anexam fotos de bicicletas danificadas, guardadas com seus metadados. Que pergunta dá para responder só com os metadados?'),
  L(5),
  C('Which photos show a flat tyre', 'Quais fotos mostram um pneu furado',
    'That is in the pixels, and needs a person or a classifier.', 'Isso está nos pixels, e exige uma pessoa ou um classificador.'),
  C('Which bicycle each photo shows', 'Que bicicleta cada foto mostra',
    'The bicycle is in the image, not in the file’s fields.', 'A bicicleta está na imagem, não nos campos do arquivo.'),
  C('How many photos one customer sent last week', 'Quantas fotos um cliente mandou na semana passada',
    'Right: who sent it and when are ordinary fields.', 'Isso: quem mandou e quando são campos comuns.', ok=True),
  C('Which station appears in the background', 'Que estação aparece no fundo',
    'That too is content to interpret.', 'Isso também é conteúdo a interpretar.')),
Q('ex-vgnagd0v', '', 'hard',
  ('Why does a data platform land data with schema on read and serve it with schema on write, in that order?',
   'Por que uma plataforma de dados recebe os dados com esquema na leitura e os serve com esquema na escrita, nessa ordem?'),
  L(5),
  C('So the sources do not have to declare their types', 'Para as fontes não precisarem declarar seus tipos',
    'Sources do as they like either way; the order is about the data team’s copies.', 'As fontes fazem o que quiserem de qualquer jeito; a ordem é sobre as cópias do time de dados.'),
  C('Nothing is lost at the door, and readers agree', 'Nada se perde na porta, e os leitores concordam',
    'Right: raw keeps everything sent; curated gives one answer.', 'Isso: a bruta guarda tudo o que foi mandado; a curada dá uma resposta só.', ok=True),
  C('So each analyst keeps a reader of their own', 'Para cada analista manter um leitor próprio',
    'That is the cost the curated tables exist to remove.', 'Esse é o custo que as tabelas curadas existem para eliminar.'),
  C('So drift is found by the dashboards that read it', 'Para a deriva ser achada pelos dashboards que leem',
    'Drift belongs at the job in the middle, before any dashboard.', 'A deriva deve ser notada no job do meio, antes de qualquer dashboard.')),
Q('ex-2pqks7s3', '', 'medium',
  ('Which of these is true of object storage, as lesson 5 describes it?',
   'Qual destas é verdadeira sobre o object storage, como a aula 5 o descreve?'),
  L(5),
  C('It enforces a schema per bucket', 'Ele impõe um esquema por bucket',
    'It looks inside nothing it stores.', 'Ele não olha dentro de nada do que guarda.'),
  C('It keeps unstructured data and refuses tables', 'Ele guarda dado não estruturado e recusa tabelas',
    'A Parquet file is as welcome there as a photo.', 'Um arquivo Parquet é tão bem-vindo ali quanto uma foto.'),
  C('It is a document store for files', 'Ele é um banco de documentos para arquivos',
    'A document store can search inside a document; object storage cannot.', 'Um banco de documentos consegue buscar dentro de um documento; object storage não.'),
  C('It cannot say what is inside an object', 'Ele não sabe dizer o que há dentro de um objeto',
    'Right: that is the job of whatever reads it.', 'Isso: esse é o trabalho de quem o lê.', ok=True)),
Q('ex-r6yrhgcy', '', 'medium',
  ('A sender writes the battery as `82.0` on Monday and as `82` on Tuesday. What does JSON make of the difference?',
   'Um remetente escreve a bateria como `82.0` na segunda e como `82` na terça. O que o JSON faz da diferença?'),
  L(5),
  C('Monday’s is a string', 'A de segunda é uma string',
    'There are no quotes around it.', 'Não há aspas em volta.'),
  C('Tuesday’s is a new type, an integer', 'A de terça é um tipo novo, inteiro',
    'JSON has no integer type apart from number.', 'O JSON não tem tipo inteiro separado de número.'),
  C('Both are the one JSON type, number', 'As duas são o mesmo tipo JSON, número',
    'Right: whether it is a float or an integer is up to the sender and the reader.', 'Isso: se é decimal ou inteiro fica com quem manda e quem lê.', ok=True),
  C('Monday’s is refused as invalid JSON', 'A de segunda é recusada como JSON inválido',
    '`82.0` is valid JSON.', '`82.0` é JSON válido.')),
Q('ex-x4pegpwg', '', 'medium',
  ('A reader meets a ride event with no `end` and fills `end.minutes` with 0. What follows downstream?',
   'Um leitor encontra um evento de viagem sem `end` e preenche `end.minutes` com 0. O que acontece depois?'),
  L(5),
  C('An unfinished ride counts as a short finished one', 'Uma viagem não terminada conta como uma terminada curta',
    'Right: a default turned "not over yet" into a fact that is false.', 'Isso: um padrão transformou "ainda não acabou" num fato falso.', ok=True),
  C('The reader raises a `KeyError` on the next ride', 'O leitor levanta um `KeyError` na viagem seguinte',
    'Filling a default is exactly what avoids the error.', 'Preencher um padrão é exatamente o que evita o erro.'),
  C('The ride disappears from the flat table', 'A viagem some da tabela plana',
    'It stays, with a zero where it should have nothing.', 'Ela fica, com zero onde não deveria ter nada.'),
  C('Nothing, because 0 is read everywhere as "unknown"', 'Nada, porque 0 é lido como "desconhecido"',
    'A zero is a number, and averages and sums treat it as one.', 'Zero é um número, e médias e somas o tratam como tal.')),
MC('ex-cshvtp02', '', 'medium',
  ('Which of these are semi-structured at Roda Livre, in lesson 5’s table? Choose all that apply.',
   'Quais destes são semiestruturados na Roda Livre, na tabela da aula 5? Marque todos os que se aplicam.'),
  L(5),
  C('the app’s events', 'os eventos do aplicativo',
    'Yes: names travel beside the values in each record.', 'Sim: os nomes viajam ao lado dos valores em cada registro.', ok=True),
  C('API responses', 'as respostas de API',
    'Yes: JSON, checked only if a reader checks it.', 'Sim: JSON, conferido só se um leitor conferir.', ok=True),
  C('sensor messages', 'as mensagens dos sensores',
    'Yes: the same shape as the events.', 'Sim: a mesma forma dos eventos.', ok=True),
  C('the rides table', 'a tabela de viagens',
    'Structured: its schema was declared before any ride.', 'Estruturada: o esquema foi declarado antes de qualquer viagem.'),
  C('the body of a support email', 'o corpo de um e-mail de suporte',
    'Unstructured: the meaning is in the words.', 'Não estruturado: o sentido está nas palavras.')),
Z('ex-87nbd311', '', 'medium',
  ('A platform lands raw data with schema on read and serves its curated tables with schema on ___.',
   'Uma plataforma recebe o dado bruto com esquema na leitura e serve as tabelas curadas com esquema na ___.'),
  L(5),
  ['write'], ['escrita']),

# ==== lesson 6
Q('ex-c3bf57rb', '', 'medium',
  ('What does it cost to add one ride to the end of a Parquet file?',
   'O que custa acrescentar uma viagem ao fim de um arquivo Parquet?'),
  L(6),
  C('Rewriting a row group, column chunk by column chunk', 'Reescrever um grupo de linhas, fragmento de coluna por fragmento',
    'Right: each column chunk has to take the new value.', 'Isso: cada fragmento de coluna precisa receber o valor novo.', ok=True),
  C('One write at the end of the file', 'Uma escrita no fim do arquivo',
    'That is a row format’s append; a Parquet file ends with its footer.', 'Isso é o acréscimo de um formato de linhas; um arquivo Parquet termina no rodapé.'),
  C('A new line, as in a CSV file', 'Uma linha nova, como num arquivo CSV',
    'There are no lines; values sit by column.', 'Não há linhas; os valores ficam por coluna.'),
  C('A new entry in the footer and nothing more', 'Uma entrada nova no rodapé e mais nada',
    'The footer describes data that has to be written somewhere first.', 'O rodapé descreve dados que precisam ser escritos em algum lugar antes.')),
Q('ex-fvbhes9b', '', 'hard',
  ('Rides are written to Parquet ordered by time. In every row group, `start_station` has the statistics min ST01, max ST12. A query asks for the rides from ST05. How many row groups can it skip?',
   'As viagens são gravadas em Parquet ordenadas por tempo. Em todo grupo de linhas, `start_station` tem as estatísticas min ST01, max ST12. Uma consulta pede as viagens de ST05. Quantos grupos de linhas ela pode pular?'),
  L(6),
  C('All but the one holding ST05', 'Todos menos o que guarda a ST05',
    'ST05 is inside every group’s range.', 'A ST05 está dentro do intervalo de todos os grupos.'),
  C('Two of the three', 'Dois dos três',
    'That is what happened for dates, which were in order.', 'Isso foi o que aconteceu com as datas, que estavam em ordem.'),
  C('None', 'Nenhum',
    'Right: every range contains ST05, so the statistics rule nothing out.', 'Isso: todo intervalo contém ST05, então as estatísticas não descartam nada.', ok=True),
  C('The last one, which is the smallest', 'O último, que é o menor',
    'Size does not matter to pushdown; the range does.', 'O tamanho não importa para o pushdown; o intervalo sim.')),
Q('ex-ctqyvtxh', '', 'medium',
  ('A spreadsheet set to Portuguese saves the list of stations and their names as "CSV", and a reader expecting commas opens it. What does the reader get?',
   'Uma planilha configurada em português salva a lista de estações e seus nomes como "CSV", e um leitor que espera vírgulas o abre. O que o leitor obtém?'),
  L(6),
  C('An encoding error on the first accented letter', 'Um erro de codificação na primeira letra acentuada',
    'Encoding is a separate trap; the delimiter is the one here.', 'Codificação é outra armadilha; aqui é o delimitador.'),
  C('A `KeyError` when it reads the header', 'Um `KeyError` quando lê o cabeçalho',
    'The header is read; it is one field.', 'O cabeçalho é lido; é um campo só.'),
  C('The right columns, since the csv module detects the delimiter', 'As colunas certas, já que o módulo csv detecta o delimitador',
    '`csv.reader` splits on commas unless it is told otherwise.', 'O `csv.reader` divide nas vírgulas, a não ser que lhe digam outra coisa.'),
  C('One field per line', 'Um campo por linha',
    'Right: semicolons are not commas, so nothing splits.', 'Isso: ponto e vírgula não é vírgula, então nada se divide.', ok=True)),
Q('ex-2gejdv5m', '', 'hard',
  ('A ride starts at 22:30 on 30 September in Curitiba (UTC−3) and is written to Avro as `timestamp-millis`. Read back as fastavro returns it, what does it say?',
   'Uma viagem começa às 22:30 de 30 de setembro em Curitiba (UTC−3) e é gravada em Avro como `timestamp-millis`. Lida de volta como o fastavro a devolve, o que ela diz?'),
  L(6),
  C('30 September, 19:30', '30 de setembro, 19:30',
    'UTC is ahead of Curitiba, not behind.', 'O UTC está à frente de Curitiba, não atrás.'),
  C('1 October, 01:30 in UTC', '1º de outubro, 01:30 em UTC',
    'Right: the same instant, in UTC, on the next day.', 'Isso: o mesmo instante, em UTC, no dia seguinte.', ok=True),
  C('30 September, 22:30, with Curitiba’s zone', '30 de setembro, 22:30, com o fuso de Curitiba',
    'The zone it was written in is not part of the value.', 'O fuso em que foi gravado não faz parte do valor.'),
  C('1 October, 22:30', '1º de outubro, 22:30',
    'That is a whole day later, not three hours.', 'Isso é um dia inteiro depois, não três horas.')),
Q('ex-k81bmq15', '', 'medium',
  ('A partner downloads one monthly file and reads it whole, once. What does lesson 6 suggest?',
   'Um parceiro baixa um arquivo por mês e o lê inteiro, uma vez. O que a aula 6 sugere?'),
  L(6),
  C('Parquet with Snappy, the fast default', 'Parquet com Snappy, o padrão rápido',
    'That is for files programs read again and again.', 'Isso é para arquivos que programas leem de novo e de novo.'),
  C('JSON Lines, uncompressed', 'JSON Lines, sem compressão',
    'Eight megabytes for what a gzip makes half a megabyte.', 'Oito megabytes para o que um gzip faz em meio.'),
  C('A gzipped CSV', 'Um CSV com gzip',
    'Right: read whole once, so not being splittable costs nothing.', 'Isso: lido inteiro uma vez, então não ser divisível não custa nada.', ok=True),
  C('Avro with the null codec, for its schema', 'Avro com o codec null, pelo esquema',
    'A partner’s spreadsheet does not read Avro.', 'A planilha de um parceiro não lê Avro.')),
Q('ex-fgkevxx6', '', 'hard',
  ('A new platform keeps its tables in Delta Lake. In which file format are they stored?',
   'Uma plataforma nova guarda as tabelas no Delta Lake. Em que formato de arquivo elas ficam?'),
  L(6),
  C('ORC, for its row index', 'ORC, pelo índice de linhas',
    'Hive’s transactional tables need ORC; Delta does not use it.', 'As tabelas transacionais do Hive precisam de ORC; o Delta não o usa.'),
  C('Avro, so the schema can evolve', 'Avro, para o esquema poder evoluir',
    'Avro suits messages; Delta keeps its tables in another format.', 'Avro serve a mensagens; o Delta guarda tabelas em outro formato.'),
  C('Whichever of the three each table chooses', 'O que cada tabela escolher, dos três',
    'That is Iceberg’s freedom, not Delta’s.', 'Essa é a liberdade do Iceberg, não do Delta.'),
  C('Parquet', 'Parquet',
    'Right: Delta Lake stores its tables only as Parquet.', 'Isso: o Delta Lake guarda as tabelas só como Parquet.', ok=True)),
N('ex-21xhazgh', '', 'easy',
  ('`shifted.py` printed 72.5 for October. What was October’s real average ride length, in minutes?',
   'O `shifted.py` imprimiu 72.5 para outubro. Qual era a duração média real das viagens de outubro, em minutos?'),
  L(6),
  35, 0, ('minutes', 'minutos')),
O('ex-z7mnpbdf', '', 'medium',
  ('Put the pieces of a Parquet file in order, from the largest to the smallest.',
   'Ponha as partes de um arquivo Parquet em ordem, da maior para a menor.'),
  L(6),
  [('the file', 'o arquivo'), ('a row group', 'um grupo de linhas'),
   ('a column chunk', 'um fragmento de coluna'), ('a page', 'uma página')],
  ('A page is the unit that is encoded and compressed.', 'A página é a unidade que é codificada e comprimida.')),
M('ex-2cstxwvc', '', 'medium',
  ('Match each codec to the trade it makes.', 'Associe cada codec à troca que ele faz.'),
  L(6),
  [(('Snappy', 'Snappy'), ('built to be fast rather than small', 'feito para ser rápido em vez de pequeno')),
   (('gzip', 'gzip'), ('older and slower, and squeezes hard', 'mais antigo e lento, e aperta bastante')),
   (('zstd', 'zstd'), ('near gzip’s size, far quicker to decompress', 'perto do tamanho do gzip, bem mais rápido de descomprimir')),
   (('bzip2', 'bzip2'), ('splittable even on a plain text file', 'divisível mesmo num arquivo de texto puro'))]),
Z('ex-1scpynk7', '', 'medium',
  ('In ORC, a slice of the rows stored column by column, the nearest thing to a Parquet row group, is called a ___.',
   'No ORC, uma fatia das linhas guardada coluna por coluna, o mais próximo de um grupo de linhas do Parquet, se chama ___.'),
  L(6),
  ['stripe'], ['faixa', 'stripe']),

# ==== lesson 7
Q('ex-4m232qn0', '', 'medium',
  ('Rides crowd into two rush hours; the sensors report at the same rate all day. A stream processor will take the rides as they arrive. Which number sizes it?',
   'As viagens se concentram em dois horários de pico; os sensores reportam no mesmo ritmo o dia todo. Um processador de fluxo vai receber as viagens à medida que chegam. Que número o dimensiona?'),
  L(7),
  C('The number of rides in the busiest rush hour', 'Quantas viagens há na hora mais cheia do dia',
    'Right: for data processed as it arrives, the peak is the number.', 'Isso: para dado processado à medida que chega, o pico é o número.', ok=True),
  C('The rides’ daily average', 'A média diária das viagens',
    'A system sized for the average is too small twice a day.', 'Um sistema dimensionado pela média é pequeno demais duas vezes por dia.'),
  C('The sensors’ total for a day', 'O total diário dos sensores',
    'The question is about the rides, and the sensors’ peak is their average anyway.', 'A pergunta é sobre as viagens, e o pico dos sensores é a própria média.'),
  C('The gigabytes kept after a year', 'Os gigabytes guardados depois de um ano',
    'That sizes storage, not a process handling rides as they come.', 'Isso dimensiona armazenamento, não um processo que trata viagens à medida que chegam.')),
Q('ex-9p0hes64', '', 'medium',
  ('An incremental run copies its rows, commits them, and dies before it saves the new watermark. What does the next run do?',
   'Uma execução incremental copia as linhas, faz commit, e morre antes de salvar a nova marca d’água. O que faz a execução seguinte?'),
  L(7),
  C('Skips those rows, which are marked as done', 'Pula essas linhas, que estão marcadas como feitas',
    'Nothing marks them; the old watermark is still the one on file.', 'Nada as marca; a marca d’água antiga continua no arquivo.'),
  C('Writes them a second time as extra rows', 'Grava essas linhas uma segunda vez como linhas extras',
    'The copy is keyed on `ride_id`, so a row written again replaces itself.', 'A cópia tem chave em `ride_id`, então uma linha gravada de novo se substitui.'),
  C('Reads the same rows again, and no harm is done', 'Lê as mesmas linhas de novo, sem estrago',
    'Right: the old watermark, and a keyed write.', 'Isso: a marca d’água antiga, e uma escrita com chave.', ok=True),
  C('Falls back to a full load of the table', 'Volta para uma carga completa da tabela',
    'Only a missing watermark file starts from the beginning.', 'Só a falta do arquivo de marca d’água começa do início.')),
Q('ex-xyggcyxw', '', 'hard',
  ('A delivery has the right columns and the promised count, but every `started_at` is on the day before. What does `door.py` do with it?',
   'Uma entrega tem as colunas certas e a contagem prometida, mas todo `started_at` é do dia anterior. O que o `door.py` faz com ela?'),
  L(7),
  C('Refuses the file before judging a row', 'Recusa o arquivo antes de julgar uma linha',
    'Both checks on the whole file pass.', 'As duas verificações do arquivo inteiro passam.'),
  C('Accepts it, since the count matches', 'Aceita, já que a contagem bate',
    'The count is a file check; each row still meets the row checks.', 'A contagem é verificação de arquivo; cada linha ainda passa pelas verificações de linha.'),
  C('Drops the rows without a word', 'Descarta as linhas sem dizer nada',
    'A row that fails is set aside with its reason, never dropped in silence.', 'Uma linha que falha é separada com o motivo, nunca descartada em silêncio.'),
  C('Quarantines every row', 'Põe toda linha em quarentena',
    'Right: each row fails "started_at empty or not on" the day, and is set aside with that reason.', 'Isso: cada linha falha em "started_at empty or not on" o dia, e é separada com esse motivo.', ok=True)),
Q('ex-nfna0e0d', '', 'medium',
  ('In `cost.py`, copying the year to a laptop every week costs more than keeping it. Why?',
   'No `cost.py`, copiar o ano para um notebook toda semana custa mais do que guardá-lo. Por quê?'),
  L(7),
  C('Transfer is paid on each copy', 'A transferência é paga de novo a cada cópia',
    'Right: stored once, moved four times a month.', 'Isso: guardado uma vez, movido quatro vezes por mês.', ok=True),
  C('A laptop stores a gigabyte at a higher price', 'Um notebook guarda um gigabyte por um preço maior',
    'The laptop is not billed; leaving the provider’s network is.', 'O notebook não é cobrado; sair da rede do provedor é.'),
  C('The copy leaves uncompressed and grows', 'A cópia sai sem compressão e cresce',
    'The program prices the same 8.1 GB either way.', 'O programa precifica os mesmos 8,1 GB de qualquer jeito.'),
  C('Storage is billed by the read, not the month', 'O armazenamento é cobrado por leitura, não por mês',
    'Storage is the gigabyte per month in the program.', 'Armazenamento é o gigabyte por mês no programa.')),
Q('ex-tcgjwj7k', '', 'hard',
  ('Customer ids are pseudonymised with HMAC, and the key is changed in January. What happens?',
   'Os ids de clientes são pseudonimizados com HMAC, e a chave é trocada em janeiro. O que acontece?'),
  L(7),
  C('The copy stops being personal data', 'A cópia deixa de ser dado pessoal',
    'Pseudonyms stay personal data, whatever the key.', 'Pseudônimos continuam dado pessoal, seja qual for a chave.'),
  C('Last year’s pseudonyms read back under the new key', 'Os pseudônimos do ano passado são lidos com a chave nova',
    'A keyed hash is not decrypted; each key gives other stand-ins.', 'Um hash com chave não se decifra; cada chave dá outros substitutos.'),
  C('This year’s customers stop joining last year’s', 'Os clientes deste ano deixam de casar com os do ano passado',
    'Right: every stand-in changes with the key.', 'Isso: cada substituto muda com a chave.', ok=True),
  C('Nothing, since the hash does not depend on the key', 'Nada, já que o hash não depende da chave',
    'That is a plain hash; HMAC mixes the key in.', 'Isso é um hash simples; o HMAC mistura a chave.')),
Q('ex-3tdn8b5z', '', 'medium',
  ('Caio’s model needs each customer’s age in bands of ten years, not their date of birth. Which of the three ways to need less is that?',
   'O modelo de Caio precisa da idade de cada cliente em faixas de dez anos, não da data de nascimento. Qual das três formas de precisar de menos é essa?'),
  L(7),
  C('Leave it out', 'Deixar de fora',
    'The model needs the age, so something is kept.', 'O modelo precisa da idade, então algo é guardado.'),
  C('Pseudonymise it', 'Pseudonimizar',
    'That is for telling people apart, not for an age.', 'Isso é para distinguir pessoas, não para uma idade.'),
  C('Anonymise it with a plain hash', 'Anonimizar com um hash simples',
    'A plain hash of a birth date is the date in disguise.', 'Um hash simples de uma data de nascimento é a data disfarçada.'),
  C('Coarsen it', 'Engrossar',
    'Right: the band, not the day.', 'Isso: a faixa, não o dia.', ok=True)),
N('ex-y3sx7r5h', '', 'medium',
  ('The eight new stations of twelve docks each join today’s 150 docks. By what percentage do they raise the sensors’ daily volume?',
   'As oito estações novas de doze docas cada se juntam às 150 docas de hoje. Em que porcentagem elas aumentam o volume diário dos sensores?'),
  L(7),
  64, 0.5, ('%', '%')),
O('ex-fz5d8njs', '', 'hard',
  ('Put the lines of `cost.py` in order, from the cheapest a month to the dearest.',
   'Ponha as linhas do `cost.py` em ordem, da mais barata por mês para a mais cara.'),
  L(7),
  [('polling an API every minute', 'consultar uma API a cada minuto'),
   ('keeping a year of it', 'guardar um ano disso'),
   ('a dashboard reading only today', 'um dashboard lendo só o dia de hoje'),
   ('copying the year out weekly', 'copiar o ano para fora toda semana'),
   ('a dashboard reading the year', 'um dashboard lendo o ano')],
  ('The bill grows with what is read and moved, not with what is kept.', 'A conta cresce com o que é lido e movido, não com o que é guardado.')),
MC('ex-80kdve01', '', 'hard',
  ('A delivery has the promised number of rows, but one ride is doubled and another is missing. Which checks reveal it? Choose all that apply.',
   'Uma entrega tem o número prometido de linhas, mas uma viagem está duplicada e outra está faltando. Quais verificações revelam isso? Marque todas as que se aplicam.'),
  L(7),
  C('a uniqueness check on `ride_id` at the door', 'uma verificação de unicidade em `ride_id` na porta',
    'Yes: it sees the double.', 'Sim: ela vê a duplicata.', ok=True),
  C('comparing ride ids with the source’s list', 'comparar os ids das viagens com a lista da fonte',
    'Yes: it names both rides.', 'Sim: ela nomeia as duas viagens.', ok=True),
  C('comparing row counts with the source', 'comparar a contagem de linhas com a fonte',
    'The count is right; that is the blind spot.', 'A contagem está certa; esse é o ponto cego.'),
  C('checking the header against the expected columns', 'conferir o cabeçalho com as colunas esperadas',
    'The columns are fine.', 'As colunas estão certas.'),
  C('a range check on `minutes`', 'uma verificação de faixa em `minutes`',
    'Both rides have ordinary minutes.', 'As duas viagens têm minutos comuns.')),
Z('ex-38jpta77', '', 'medium',
  ('Comparing a copy with the source’s own count, total or list of keys is called ___.',
   'Comparar uma cópia com a contagem, o total ou a lista de chaves da própria fonte se chama ___.'),
  L(7),
  ['reconciliation', 'reconciling'], ['reconciliação', 'conciliação']),

# ==== lesson 8
Q('ex-a8evw14y', '', 'hard',
  ('A team’s stream processor is set to wait 24 hours before sending any window. By lesson 8’s definition, is it batch or stream?',
   'O processador de fluxo de um time está configurado para esperar 24 horas antes de mandar qualquer janela. Pela definição da aula 8, é lote ou fluxo?'),
  L(8),
  C('Stream, since its input has no end', 'Fluxo, já que a entrada não tem fim',
    'Right: bounded or unbounded is the question.', 'Isso: limitado ou ilimitado é a pergunta.', ok=True),
  C('Batch, since its answers come a day late', 'Lote, já que as respostas chegam um dia depois',
    'Speed follows from the difference; it is not the difference.', 'A velocidade decorre da diferença; não é a diferença.'),
  C('Batch, since its windows are a day long', 'Lote, já que as janelas têm um dia',
    'A window’s length does not make the input end.', 'O tamanho de uma janela não faz a entrada acabar.'),
  C('A micro-batch', 'Um micro-lote',
    'A micro-batch runs batch jobs every few seconds; this is one process reading a log.', 'Um micro-lote roda jobs em lote a cada poucos segundos; isto é um processo lendo um log.')),
Q('ex-k0yef1ty', '', 'medium',
  ('The live dock map and the van alert read the same log. What lets them read at different paces?',
   'O mapa ao vivo das docas e o alerta da van leem o mesmo log. O que os deixa ler em ritmos diferentes?'),
  L(8),
  C('Each keeps its own offset, saved between runs', 'Cada um guarda o próprio offset entre execuções',
    'Right: nothing is removed by being read.', 'Isso: nada é removido por ser lido.', ok=True),
  C('The log keeps one copy of each event per reader', 'O log guarda uma cópia de cada evento por leitor',
    'There is one copy; each reader has a position in it.', 'Há uma cópia; cada leitor tem uma posição nela.'),
  C('Reading takes events out, so each gets its share', 'Ler tira os eventos, então cada um fica com sua parte',
    'That is a queue; a log keeps every event for every reader.', 'Isso é uma fila; um log guarda cada evento para cada leitor.'),
  C('A scheduler lets them take turns', 'Um agendador os deixa revezar',
    'Each reads when it likes, from its own position.', 'Cada um lê quando quer, da própria posição.')),
Q('ex-a4dnjspa', '', 'hard',
  ('A sensor holds its readings during an outage and, when the link returns, stamps them with the time it sends them. What does a stream counting by event time do with them?',
   'Um sensor guarda as leituras durante uma queda e, quando o link volta, carimba-as com a hora em que as manda. O que um fluxo que conta por tempo do evento faz com elas?'),
  L(8),
  C('Drops them as late', 'Descarta como atrasadas',
    'Their stamps are fresh; nothing marks them as late.', 'Os carimbos são novos; nada as marca como atrasadas.'),
  C('Counts them in the right windows, since it uses event time', 'Conta nas janelas certas, já que usa o tempo do evento',
    'Event time is only as good as the clock that wrote it.', 'O tempo do evento só é tão bom quanto o relógio que o escreveu.'),
  C('Files them in the wrong windows, with no error', 'Arquiva nas janelas erradas, sem erro',
    'Right: the stamp says when they were sent, and that has no cure downstream.', 'Isso: o carimbo diz quando foram mandadas, e isso não tem cura depois.', ok=True),
  C('Rejects them as duplicates of later readings', 'Rejeita como duplicatas de leituras posteriores',
    'Each has its own id; nothing repeats.', 'Cada uma tem seu id; nada se repete.')),
Q('ex-ygajacnb', '', 'hard',
  ('Rides are counted in sliding windows of 30 minutes that start every 5 minutes. In how many windows is one ride counted?',
   'As viagens são contadas em janelas deslizantes de 30 minutos que começam a cada 5 minutos. Em quantas janelas uma viagem é contada?'),
  L(8),
  C('One', 'Uma',
    'That is a tumbling window.', 'Isso é janela fixa.'),
  C('Six of them', 'Seis delas',
    'Right: thirty divided by five.', 'Isso: trinta dividido por cinco.', ok=True),
  C('Two', 'Duas',
    'That would be windows starting every 15 minutes.', 'Isso seriam janelas começando a cada 15 minutos.'),
  C('Thirty', 'Trinta',
    'The windows start every five minutes, not every minute.', 'As janelas começam a cada cinco minutos, não a cada minuto.')),
Q('ex-4pbhyzvb', '', 'hard',
  ('Windows are quarters of an hour from 08:00. The newest event seen happened at 09:10, and the allowed lateness is five minutes. Which windows have been sent?',
   'As janelas são quartos de hora a partir das 08:00. O evento mais novo visto aconteceu às 09:10, e a tolerância a atraso é de cinco minutos. Que janelas já foram mandadas?'),
  L(8),
  C('Those ending at or before 09:10', 'As que terminam até 09:10',
    'The watermark is the newest event time minus the lateness.', 'A marca d’água é o tempo do evento mais novo menos a tolerância.'),
  C('Those ending at or before 09:05, through 08:45', 'As que terminam até 09:05, a de 08:45 inclusive',
    'Right: the watermark is 09:05, so 08:00 to 08:45 have gone.', 'Isso: a marca d’água é 09:05, então de 08:00 a 08:45 já foram.', ok=True),
  C('Those ending at or before 09:15', 'As que terminam até 09:15',
    'Lateness moves the watermark back, not forward.', 'A tolerância empurra a marca d’água para trás, não para a frente.'),
  C('None, until each window’s last event arrives', 'Nenhuma, até chegar o último evento de cada janela',
    'Nobody can know which event is the last; that is why there is a watermark.', 'Ninguém sabe qual evento é o último; é por isso que existe a marca d’água.')),
Q('ex-e9pp3tqe', '', 'hard',
  ('A payments consumer must lose no charge and must count none twice. Which design meets both?',
   'Um consumidor de pagamentos não pode perder nenhuma cobrança nem contar nenhuma duas vezes. Que desenho atende às duas coisas?'),
  L(8),
  C('At most once, with the offset committed quickly', 'No máximo uma vez, com o offset confirmado rápido',
    'A crash between the two steps loses the batch.', 'Uma queda entre os dois passos perde o lote.'),
  C('Exactly-once delivery from the network', 'Entrega exatamente uma vez pela rede',
    'No network promises that about delivery.', 'Nenhuma rede promete isso sobre a entrega.'),
  C('At least once, adding one to a counter per event', 'Pelo menos uma vez, somando um a um contador por evento',
    'That is the design that ended with 515 rides on mornings that had 360.', 'Esse é o desenho que terminou com 515 viagens em manhãs que tiveram 360.'),
  C('At least once, with each charge written under its payment id', 'Pelo menos uma vez, com cada cobrança gravada pelo id do pagamento',
    'Right: a repeat writes the same key, so the effect happens once.', 'Isso: uma repetição grava a mesma chave, então o efeito acontece uma vez.', ok=True)),
Q('ex-f7kcwkmt', '', 'medium',
  ('Spark Structured Streaming, by default, runs a small batch job every few seconds over what has arrived. What does lesson 8 call that?',
   'O Spark Structured Streaming, por padrão, roda um pequeno job em lote a cada poucos segundos sobre o que chegou. Como a aula 8 chama isso?'),
  L(8),
  C('A Lambda speed layer', 'Uma camada de velocidade do Lambda',
    'That is one half of an architecture, which may or may not use micro-batches.', 'Isso é metade de uma arquitetura, que pode usar micro-lotes ou não.'),
  C('A Kappa replay', 'Um replay do Kappa',
    'A replay rereads the log from the start after a change.', 'Um replay relê o log desde o começo depois de uma mudança.'),
  C('A session window', 'Uma janela de sessão',
    'A session window closes after a gap; it is about grouping, not running.', 'Uma janela de sessão fecha depois de um intervalo; é sobre agrupar, não sobre rodar.'),
  C('A micro-batch', 'Um micro-lote',
    'Right: a stream’s freshness with a batch job’s simplicity.', 'Isso: a atualidade de um fluxo com a simplicidade de um job em lote.', ok=True)),
N('ex-tn6hf57n', '', 'medium',
  ('With an allowed lateness of 25 minutes, the 08:00 window, which closed at 08:15, was sent at 08:40:08. About how many minutes after it closed?',
   'Com tolerância a atraso de 25 minutos, a janela das 08:00, que fechou às 08:15, foi mandada às 08:40:08. Mais ou menos quantos minutos depois de fechar?'),
  L(8),
  25, 1, ('minutes', 'minutos')),
O('ex-4yscj9e8', '', 'hard',
  ('Allowed lateness is two minutes. Put what happens to a ride that undocks at Parque Barigui at 08:25 on Monday in order.',
   'A tolerância a atraso é de dois minutos. Ponha em ordem o que acontece com uma viagem que sai do Parque Barigui às 08:25 de segunda.'),
  L(8),
  [('the ride undocks while the station’s link is down', 'a viagem sai da doca enquanto o link da estação está fora'),
   ('the 08:15 window is sent', 'a janela das 08:15 é mandada'),
   ('the held events reach the server at 08:51:30', 'os eventos retidos chegam ao servidor às 08:51:30'),
   ('the ride is dropped as late', 'a viagem é descartada como atrasada')],
  ('The window went out before the event arrived, so the event found it closed.', 'A janela saiu antes de o evento chegar, então o evento a encontrou fechada.')),
M('ex-nfbmahej', '', 'medium',
  ('Match each part of Lambda and Kappa to what it does.', 'Associe cada parte do Lambda e do Kappa ao que ela faz.'),
  L(8),
  [(('batch layer', 'camada de lote'), ('recomputes from the whole history each night', 'recalcula a partir da história inteira toda noite')),
   (('speed layer', 'camada de velocidade'), ('covers the hours since the last batch run', 'cobre as horas desde a última execução em lote')),
   (('serving layer', 'camada de serviço'), ('merges the two answers', 'junta as duas respostas')),
   (('Kappa', 'Kappa'), ('reprocesses by replaying the log', 'reprocessa reproduzindo o log'))]),

# ==== lesson 9
Q('ex-rahny57z', '', 'hard',
  ('A customers table is range-partitioned by customer id, and ids are given out in order of sign-up. A campaign brings 10,000 new customers today. Where do their writes go?',
   'Uma tabela de clientes é particionada por faixa de id do cliente, e os ids são dados na ordem de cadastro. Uma campanha traz 10.000 clientes novos hoje. Para onde vão as escritas deles?'),
  L(9),
  C('Spread evenly over the ranges', 'Espalhadas por igual entre as faixas',
    'New ids are consecutive, so they share a range.', 'Ids novos são consecutivos, então caem na mesma faixa.'),
  C('Wherever the hash of each id sends them', 'Para onde o hash de cada id mandar',
    'The table is partitioned by range, not by hash.', 'A tabela é particionada por faixa, não por hash.'),
  C('To the one partition holding the newest ids', 'Para a única partição dos ids mais novos',
    'Right: like today’s dates, every new key lands at one end.', 'Isso: como as datas de hoje, cada chave nova cai numa ponta.', ok=True),
  C('To the partition with the fewest rows', 'Para a partição com menos linhas',
    'The key decides, not the size of the partition.', 'Quem decide é a chave, não o tamanho da partição.')),
Q('ex-dc2gz53f', '', 'medium',
  ('`skew.py` hashes keys with MD5 rather than Python’s own `hash()`. Why?',
   'O `skew.py` faz hash das chaves com MD5 em vez do `hash()` do próprio Python. Por quê?'),
  L(9),
  C('`hash()` is slower than MD5 on short strings', 'O `hash()` é mais lento que o MD5 em strings curtas',
    'Speed is not the reason given.', 'A velocidade não é o motivo dado.'),
  C('`hash()` cannot take a string as its argument', 'O `hash()` não aceita uma string como argumento',
    'It can; the trouble is what it returns.', 'Aceita; o problema é o que ele devolve.'),
  C('For a string, `hash()` gives a different number in each run of Python', 'Para uma string, o `hash()` dá um número diferente a cada execução do Python',
    'Right: a partitioner has to answer the same on every machine, every day.', 'Isso: um particionador precisa responder igual em toda máquina, todo dia.', ok=True),
  C('`hash()` returns negative numbers, which break `%`', 'O `hash()` devolve números negativos, que quebram o `%`',
    'Python’s `%` handles negatives; that is not the trouble.', 'O `%` do Python lida com negativos; o problema não é esse.')),
Q('ex-pgwyj1aa', '', 'hard',
  ('A store fixes 256 partitions when it is created, and moves whole partitions when a machine joins. What changes for a key then?',
   'Um banco fixa 256 partições ao ser criado, e move partições inteiras quando uma máquina entra. O que muda para uma chave nesse caso?'),
  L(9),
  C('Its machine, while its partition stays put', 'A máquina dela, enquanto a partição fica onde está',
    'Right: the key’s partition is fixed; where that partition lives moves.', 'Isso: a partição da chave é fixa; muda onde essa partição mora.', ok=True),
  C('Its partition, and not its machine', 'A partição dela, e não a máquina',
    'It is the other way round.', 'É o contrário.'),
  C('Both its partition and its machine', 'A partição e a máquina dela',
    'The partition count never moves, so the partition does not either.', 'O número de partições não muda, então a partição também não.'),
  C('Neither, since the number of partitions is fixed', 'Nenhuma das duas, já que o número de partições é fixo',
    'Some partitions go to the new machine, and their keys with them.', 'Algumas partições vão para a máquina nova, e as chaves delas junto.')),
Q('ex-55vn3b1h', '', 'medium',
  ('A leader replicates synchronously to one follower, and that follower stops answering. What happens to writes?',
   'Um líder replica de forma síncrona para um seguidor, e esse seguidor para de responder. O que acontece com as escritas?'),
  L(9),
  C('They continue, and the follower catches up later', 'Continuam, e o seguidor alcança depois',
    'That is asynchronous replication.', 'Isso é replicação assíncrona.'),
  C('They stop until it returns or is replaced', 'Param até ele voltar ou ser substituído',
    'Right: each write waits for that follower’s confirmation.', 'Isso: cada escrita espera a confirmação desse seguidor.', ok=True),
  C('They go to the follower instead of the leader', 'Vão para o seguidor em vez do líder',
    'Followers do not take writes in this arrangement.', 'Seguidores não recebem escritas nesse arranjo.'),
  C('Reads stop and writes go on as before', 'As leituras param e as escritas seguem como antes',
    'Reads can still go to the leader; writes are what wait.', 'As leituras ainda podem ir ao líder; as escritas é que esperam.')),
Q('ex-w0fj3584', '', 'hard',
  ('A leader’s disk starts failing and its replies slow down past the timeout, though it is still working. What follows?',
   'O disco de um líder começa a falhar e as respostas dele passam do timeout, embora ele continue funcionando. O que acontece?'),
  L(9),
  C('It keeps the lead, since its heartbeats still go out', 'Ele mantém a liderança, já que os heartbeats dele ainda saem',
    'A node replying past the timeout looks dead whatever it is doing.', 'Um nó que responde depois do timeout parece morto, faça o que fizer.'),
  C('Its clients retry until it answers in time', 'Os clientes dele tentam de novo até ele responder a tempo',
    'Retries add load to a slow node; the cluster acts first.', 'Novas tentativas somam carga a um nó lento; o cluster age antes.'),
  C('It is told to slow down by backoff', 'Ele recebe ordem de desacelerar pelo backoff',
    'Backoff is something a client does to itself.', 'Backoff é algo que o cliente faz consigo mesmo.'),
  C('It is presumed dead and replaced', 'Ele é dado como morto e substituído',
    'Right: a follower is promoted while the old leader still works.', 'Isso: um seguidor é promovido enquanto o líder antigo ainda trabalha.', ok=True)),
Q('ex-hfgqtb72', '', 'hard',
  ('A client makes up a new request id on every retry of one charge. Two replies are lost, the third gets through. What does a ledger that checks request ids hold?',
   'Um cliente inventa um id de requisição novo a cada nova tentativa de uma cobrança. Duas respostas se perdem, a terceira chega. O que guarda um livro-razão que confere ids de requisição?'),
  L(9),
  C('Three charges', 'Três cobranças',
    'Right: three different ids are three charges.', 'Isso: três ids diferentes são três cobranças.', ok=True),
  C('One charge, since the ledger checks ids', 'Uma cobrança, já que o livro confere ids',
    'Each attempt carried an id the ledger had never seen.', 'Cada tentativa trouxe um id que o livro nunca tinha visto.'),
  C('Two charges, the lost ones', 'Duas cobranças, as perdidas',
    'The third was recorded too, and its reply arrived.', 'A terceira também foi registrada, e a resposta dela chegou.'),
  C('No charge, since two of three replies were lost', 'Nenhuma cobrança, já que duas de três respostas se perderam',
    'Losing a reply does not undo the charge it reported.', 'Perder uma resposta não desfaz a cobrança que ela informava.')),
N('ex-q1r3qc38', '', 'hard',
  ('A leaderless store keeps N = 5 copies and confirms a write after W = 3. What is the smallest R that guarantees a read sees the write?',
   'Um banco sem líder mantém N = 5 cópias e confirma uma escrita depois de W = 3. Qual é o menor R que garante que uma leitura veja a escrita?'),
  L(9),
  3, 0, ('replicas', 'réplicas')),
O('ex-551aky14', '', 'medium',
  ('Put the steps of a split brain in order.', 'Ponha os passos de um cérebro dividido em ordem.'),
  L(9),
  [('the leader’s link to the others is cut', 'o link do líder com os outros é cortado'),
   ('the others stop hearing its heartbeats', 'os outros param de ouvir os heartbeats dele'),
   ('a follower is promoted in its place', 'um seguidor é promovido no lugar dele'),
   ('two machines accept writes for the same data', 'duas máquinas aceitam escritas para o mesmo dado')],
  ('The old leader is not dead, only unreachable, so it still believes it leads.', 'O líder antigo não morreu, só ficou inalcançável, então ainda acredita que lidera.')),
MC('ex-g0nr4zew', '', 'medium',
  ('Which of these does a replica protect against? Choose all that apply.',
   'Contra quais destes uma réplica protege? Marque todos os que se aplicam.'),
  L(9),
  C('a machine’s disk failing', 'o disco de uma máquina falhando',
    'Yes: another machine holds the data.', 'Sim: outra máquina guarda o dado.', ok=True),
  C('a power cut on the leader', 'uma queda de energia no líder',
    'Yes: a follower can be promoted.', 'Sim: um seguidor pode ser promovido.', ok=True),
  C('a `DELETE` run by mistake', 'um `DELETE` rodado por engano',
    'It reaches every replica within moments.', 'Ele chega a cada réplica em instantes.'),
  C('a bug that writes wrong values', 'um bug que grava valores errados',
    'The followers replay the wrong values faithfully.', 'Os seguidores reproduzem os valores errados fielmente.')),
Z('ex-vyxwqvcs', '', 'medium',
  ('Sending the computation to the machines that already hold the data is called data ___.',
   'Mandar o cálculo para as máquinas que já guardam os dados se chama ___ dos dados.'),
  L(9),
  ['locality'], ['localidade']),

# ==== lesson 10
Q('ex-16gtnzg5', '', 'hard',
  ('A system that chose consistency runs on four nodes, and a cut splits them two and two. What happens to writes?',
   'Um sistema que escolheu consistência roda em quatro nós, e um corte os divide em dois e dois. O que acontece com as escritas?'),
  L(10),
  C('The side holding the old leader accepts them', 'O lado com o líder antigo as aceita',
    'Two of four is not more than half, on either side.', 'Dois de quatro não é mais que a metade, de nenhum lado.'),
  C('Both sides accept them and merge later', 'Os dois lados as aceitam e combinam depois',
    'That is what a system that chose availability does.', 'Isso é o que faz um sistema que escolheu disponibilidade.'),
  C('Both sides refuse them, having no majority', 'Os dois lados as recusam, sem maioria',
    'Right: which is why such systems run three or five nodes.', 'Isso: e por isso esses sistemas rodam com três ou cinco nós.', ok=True),
  C('The side reached first by a client accepts them', 'O lado que um cliente alcança primeiro as aceita',
    'Arriving first gives no side a majority.', 'Chegar primeiro não dá maioria a nenhum lado.')),
Q('ex-8dcd69cg', '', 'hard',
  ('During a cut, `n1` records a bicycle taken (value 5) stamped 08:02, and `n3` a bicycle returned (value 7). `n3`’s clock runs five minutes slow, so its stamp says 08:00. Under last write wins, which value survives?',
   'Durante um corte, o `n1` registra uma bicicleta retirada (valor 5) com carimbo 08:02, e o `n3` uma devolvida (valor 7). O relógio do `n3` atrasa cinco minutos, então o carimbo dele diz 08:00. Com a última escrita vence, que valor sobrevive?'),
  L(10),
  C('5, the value from `n1`', '5, o valor do `n1`',
    'Right: its stamp is later, and the rule trusts the clocks.', 'Isso: o carimbo dele é mais tarde, e a regra confia nos relógios.', ok=True),
  C('7, from `n3`', '7, do `n3`',
    'That would be the result with correct clocks.', 'Esse seria o resultado com relógios certos.'),
  C('6, the true count', '6, a contagem verdadeira',
    'Last write wins keeps one value; the true count needs a merge.', 'A última escrita vence guarda um valor; a contagem verdadeira exige uma combinação.'),
  C('Neither, since the stamps disagree with the order', 'Nenhum, já que os carimbos discordam da ordem',
    'The rule has no way to notice that.', 'A regra não tem como perceber isso.')),
Q('ex-y8b009t5', '', 'hard',
  ('A store keeps a copy in another city and confirms a write only once that copy has it. On a day with no partition, what does it pay?',
   'Um banco mantém uma cópia em outra cidade e confirma uma escrita só quando essa cópia a tem. Num dia sem partição, o que ele paga?'),
  L(10),
  C('Nothing, since CAP only costs during a partition', 'Nada, já que o CAP só cobra durante uma partição',
    'CAP is silent then; PACELC is not.', 'O CAP fica em silêncio então; o PACELC não.'),
  C('Stale reads on the far copy', 'Leituras velhas na cópia distante',
    'Waiting for that copy is what keeps it current.', 'Esperar essa cópia é o que a mantém atual.'),
  C('A round trip to the other city on every write', 'Uma ida e volta pela rede a cada gravação',
    'Right: the E and C of PACELC, latency for consistency.', 'Isso: o E e o C do PACELC, latência por consistência.', ok=True),
  C('Errors on the side with fewer copies', 'Erros no lado com menos cópias',
    'There is no side without a partition.', 'Sem partição, não há lado.')),
Q('ex-jev7k0e1', '', 'hard',
  ('Writes to the dock map never stop. What does eventual consistency promise somebody reading it?',
   'As escritas no mapa das docas nunca param. O que a consistência eventual promete a quem o lê?'),
  L(10),
  C('The latest value, within a second or so', 'O valor mais recente, em um segundo ou pouco mais',
    'It names no time at all.', 'Ela não fala de tempo nenhum.'),
  C('Their own changes back on the next read', 'As próprias mudanças de volta na leitura seguinte',
    'That is read-your-writes, laid on top.', 'Isso é ler as próprias escritas, posto por cima.'),
  C('Values that never go backwards', 'Valores que nunca voltam atrás',
    'That is monotonic reads, another promise.', 'Isso são leituras monotônicas, outra promessa.'),
  C('Nothing about what they read meanwhile', 'Nada sobre o que se lê no meio tempo',
    'Right: copies converge if writes stop, and these do not stop.', 'Isso: as cópias convergem se as escritas pararem, e estas não param.', ok=True)),
Q('ex-pzravnvt', '', 'medium',
  ('A Kafka topic has `acks=all`, and too few copies of a partition are in sync to meet `min.insync.replicas`. What does a producer see?',
   'Um tópico do Kafka tem `acks=all`, e há poucas cópias de uma partição em sincronia para atender `min.insync.replicas`. O que um produtor vê?'),
  L(10),
  C('Its writes refused', 'As escritas dele recusadas',
    'Right: Kafka chose to refuse rather than to lose.', 'Isso: o Kafka escolheu recusar em vez de perder.', ok=True),
  C('Its writes accepted by the leader alone', 'As escritas dele aceitas só pelo líder',
    'That is what `acks=all` exists to prevent.', 'É isso que o `acks=all` existe para impedir.'),
  C('Its writes lost without a message', 'As escritas dele perdidas sem aviso',
    'Losing messages is the unclean election’s price, not this setting’s.', 'Perder mensagens é o preço da eleição suja, não desta configuração.'),
  C('Its writes promoted to a stale copy', 'As escritas dele levadas a uma cópia atrasada',
    'Promoting a stale copy is a leader election, switched off by default.', 'Promover uma cópia atrasada é uma eleição de líder, desligada por padrão.')),
Q('ex-rdqmt07f', '', 'medium',
  ('A pipeline written in 2019 keeps a table of which files it has written to S3, to work around stale reads. What is that table now?',
   'Um pipeline escrito em 2019 mantém uma tabela dos arquivos que gravou no S3, para contornar leituras velhas. O que é essa tabela hoje?'),
  L(10),
  C('Still needed for overwritten files', 'Ainda necessária para arquivos sobrescritos',
    'Overwrites are covered by strong read-after-write too.', 'Sobrescritas também têm leitura forte após escrita.'),
  C('Required by S3’s own interface', 'Exigida pela própria interface do S3',
    'It was always the pipeline’s own workaround.', 'Sempre foi um contorno do próprio pipeline.'),
  C('Dead weight', 'Peso morto',
    'Right: since December 2020 every read sees the last write.', 'Isso: desde dezembro de 2020 cada leitura vê a última escrita.', ok=True),
  C('What gives S3 its read-after-write today', 'O que dá ao S3 a leitura após escrita hoje',
    'S3 gives it itself.', 'O S3 dá isso sozinho.')),
N('ex-0f3969eh', '', 'hard',
  ('In `merge.py`’s counter, suppose `n1` had seen two bicycles taken and `n3` one returned during the cut, from a start of 6. What does the merged counter say?',
   'No contador do `merge.py`, suponha que o `n1` tivesse visto duas bicicletas retiradas e o `n3` uma devolvida durante o corte, partindo de 6. O que diz o contador combinado?'),
  L(10),
  5, 0, ('bicycles', 'bicicletas')),
MC('ex-d73yrb87', '', 'medium',
  ('Which of these are session guarantees, promised to one reader rather than to everybody? Choose all that apply.',
   'Quais destas são garantias de sessão, prometidas a um leitor e não a todos? Marque todas as que se aplicam.'),
  L(10),
  C('read-your-writes', 'ler as próprias escritas',
    'Yes: your reads see your write.', 'Sim: suas leituras veem sua escrita.', ok=True),
  C('monotonic reads', 'leituras monotônicas',
    'Yes: you never see an older value after a newer one.', 'Sim: você não vê um valor mais velho depois de um mais novo.', ok=True),
  C('strong consistency', 'consistência forte',
    'That is a promise to every reader at once.', 'Essa é uma promessa a todos os leitores ao mesmo tempo.'),
  C('eventual consistency', 'consistência eventual',
    'A promise about the copies, not about any reader.', 'Uma promessa sobre as cópias, não sobre algum leitor.')),
M('ex-qagarb0w', '', 'medium',
  ('Match each way of handling two copies that disagree to its cost.', 'Associe cada forma de tratar duas cópias que discordam ao custo dela.'),
  L(10),
  [(('last write wins', 'a última escrita vence'), ('the other write is thrown away', 'a outra escrita vai fora')),
   (('keep both and ask', 'guardar as duas e perguntar'), ('the application has to merge them', 'a aplicação precisa combiná-las')),
   (('merge by construction', 'combinar por construção'), ('only some data has that shape', 'só alguns dados têm esse formato')),
   (('refuse during the cut', 'recusar durante o corte'), ('the minority side returns errors', 'o lado minoritário devolve erros'))]),
Z('ex-q356pqh6', '', 'medium',
  ('Keeping a group of machines agreeing on the order of every write, through crashes and cut links, is called ___.',
   'Manter um grupo de máquinas de acordo sobre a ordem de cada escrita, passando por quedas e links cortados, se chama ___.'),
  L(10),
  ['consensus'], ['consenso']),
]
