from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
# ---- four-questions
Q('ex-g43kynkn', 'four-questions', 'easy',
  ('What is wrong with "storage is cheap, so collect everything now and decide what it is for later"?',
   'O que há de errado em "armazenamento é barato, então colete tudo agora e decida para que serve depois"?'),
  ('Storage is not the only thing a row costs.', 'Guardar não é a única coisa que uma linha custa.'),
  C('Every row must also be moved, checked, read and protected', 'Cada linha também precisa ser movida, conferida, lida e protegida',
    'Right: storage is the cheap part of a promise kept every day.', 'Isso: guardar é a parte barata de uma promessa cumprida todo dia.', ok=True),
  C('Storage is in fact expensive, and the phrase hides it', 'Armazenamento na verdade é caro, e a frase esconde isso',
    'Storage is cheap; the section agrees with that half.', 'Armazenamento é barato; a seção concorda com essa metade.'),
  C('Nothing, as long as the data is semi-structured', 'Nada, desde que o dado seja semiestruturado',
    'The shape of the data changes none of the costs around it.', 'O formato do dado não muda nenhum dos custos em volta dele.'),
  C('It only fails for data about bicycles and docks', 'Só falha para dados sobre bicicletas e docas',
    'It fails hardest for data about people, which also needs a purpose.', 'Falha mais ainda para dados sobre pessoas, que também precisam de finalidade.')),
Q('ex-bmfsj9eg', 'four-questions', 'medium',
  ('Caio asks for every dock\'s reading, every minute, kept for good. What does Davi ask him first?',
   'Caio pede a leitura de toda doca, todo minuto, guardada para sempre. O que Davi pergunta primeiro?'),
  ('Every other answer depends on it.', 'Todas as outras respostas dependem dela.'),
  C('Which file format he would like the readings in', 'Em que formato de arquivo ele quer as leituras',
    'A format is chosen once the use is known.', 'O formato é escolhido depois que se sabe o uso.'),
  C('How much free disk his laptop has for them', 'Quanto disco livre o notebook dele tem para elas',
    'Where they go comes after what they are for.', 'Para onde vão vem depois de para que servem.'),
  C('What the model is for', 'Para que serve o modelo',
    'Right: "how fresh" and "how much" mean nothing until that is said.', 'Isso: "quão fresco" e "quanto" não querem dizer nada até isso ser dito.', ok=True),
  C('Whether he can wait for a warehouse to be built', 'Se ele pode esperar até um warehouse ser construído',
    'That is a delivery question, and it comes after the purpose.', 'Essa é uma pergunta de entrega, e vem depois da finalidade.')),
Q('ex-w7ghvw19', 'four-questions', 'medium',
  ('Why are volume, frequency, quality and cost asked together, before the first copy?',
   'Por que volume, frequência, qualidade e custo são perguntados juntos, antes da primeira cópia?'),
  ('Change one answer and look at the others.', 'Mude uma resposta e olhe as outras.'),
  C('A regulator requires all four to be answered in writing', 'Um regulador exige que as quatro sejam respondidas por escrito',
    'Writing them down is good practice, not a regulation about these four.', 'Anotar é boa prática, não uma regra legal sobre essas quatro.'),
  C('The tools for all four are bought from one vendor together', 'As ferramentas das quatro são compradas juntas de um fornecedor',
    'No tool is being bought here; the questions come before tools.', 'Nenhuma ferramenta está sendo comprada; as perguntas vêm antes das ferramentas.'),
  C('Once data is personal, the privacy question replaces the four', 'Quando o dado é pessoal, a pergunta da privacidade substitui as quatro',
    'Privacy sits underneath the four; it replaces none of them.', 'A privacidade fica por baixo das quatro; não substitui nenhuma.'),
  C('Each answer moves the others, so none is settled on its own', 'Cada resposta mexe nas outras três, então nenhuma se decide sozinha',
    'Right: frequency multiplies runs, volume and reads multiply the bill.', 'Isso: a frequência multiplica execuções, volume e leituras multiplicam a conta.', ok=True)),
# ---- volume
N('ex-k68p57ns', 'volume', 'easy',
  ('How many bytes a row did the one-hour sample of dock readings measure, in JSON Lines?',
   'Quantos bytes por linha a amostra de uma hora de leituras mediu, em JSON Lines?'),
  ('The first line `volume.py` prints.', 'A primeira linha que o `volume.py` imprime.'),
  102.6, 0.05, ('bytes', 'bytes')),
Q('ex-f976d3n5', 'volume', 'medium',
  ('The values in one reading add up to 39 characters, yet a row measured more than twice that. Why?',
   'Os valores de uma leitura somam 39 caracteres, mas a linha mediu mais que o dobro disso. Por quê?'),
  ('Look at the first line of the sample.', 'Olhe a primeira linha da amostra.'),
  C('Python pads each value to a fixed width when writing JSON', 'O Python preenche cada valor até uma largura fixa ao escrever JSON',
    'JSON has no fixed widths; the line shows no padding.', 'JSON não tem largura fixa; a linha não mostra preenchimento.'),
  C('Every line repeats the key names, with their quotes and colons', 'Cada linha repete os nomes das chaves, com as aspas e os dois-pontos',
    'Right: names, quotes and colons, on every one of the 9000 lines.', 'Isso: nomes, aspas e dois-pontos, em cada uma das 9000 linhas.', ok=True),
  C('The voltage is stored with far more decimals than it shows', 'A tensão é guardada com muito mais casas decimais do que mostra',
    'It is rounded to two decimals before it is written.', 'Ela é arredondada para duas casas antes de ser escrita.'),
  C('The file starts with a header line that is far longer than the rows', 'O arquivo começa com uma linha de cabeçalho que é bem mais longa que as outras',
    'JSON Lines has no header; that is exactly why each line names its fields.', 'JSON Lines não tem cabeçalho; é justamente por isso que cada linha nomeia os campos.')),
Q('ex-sz0mbzh5', 'volume', 'easy',
  ('How should the bytes a row be estimated before collecting a source?',
   'Como estimar os bytes por linha antes de coletar uma origem?'),
  ('The guess is the number to distrust.', 'O palpite é o número de que se deve desconfiar.'),
  C('Add up the characters of the values each row carries', 'Somar os caracteres dos valores que cada linha carrega',
    'That was the guess of about forty, less than half the real size.', 'Esse foi o palpite de uns quarenta, menos da metade do tamanho real.'),
  C('Multiply the number of fields by a typical eight bytes', 'Multiplicar o número de campos por oito bytes típicos',
    'A rule of thumb ignores the format, which is most of the size.', 'Uma regra de bolso ignora o formato, que é a maior parte do tamanho.'),
  C('Ask the source for the typical size of its rows', 'Pedir à origem o tamanho típico das linhas dela',
    'The source knows its own format, not the one you will store.', 'A origem conhece o formato dela, não o que você vai guardar.'),
  C('Measure a sample written the way it will be stored', 'Medir uma amostra escrita como ela vai ser guardada',
    'Right: write it the way it will be kept, then divide.', 'Isso: escreva como vai ser guardado, depois divida.', ok=True)),
N('ex-crd5zcbn', 'volume', 'medium',
  ('With the eight new stations of twelve docks each, how many readings a day will the sensors send?',
   'Com as oito estações novas de doze docas cada, quantas leituras por dia os sensores vão enviar?'),
  ('246 docks, one reading a minute each.', '246 docas, uma leitura por minuto cada.'),
  354240, 0, ('readings', 'leituras')),
Q('ex-8gmyk0xn', 'volume', 'medium',
  ('What does an estimate of 8.1 GB a year tell Davi about the tools the sensor data needs?',
   'O que uma estimativa de 8,1 GB por ano diz a Davi sobre as ferramentas que os dados dos sensores pedem?'),
  ('Compare it with the disk of an ordinary laptop.', 'Compare com o disco de um notebook comum.'),
  C('A cluster is needed from the first day', 'Um cluster é necessário desde o primeiro dia',
    'A cluster is for data that no longer fits on one machine; lesson 9.', 'Um cluster é para dado que não cabe mais numa máquina; aula 9.'),
  C('One machine is enough', 'Uma máquina basta',
    'Right: it fits on a laptop, and the standard library handles it.', 'Isso: cabe num notebook, e a biblioteca padrão dá conta.', ok=True),
  C('Only a sample can be kept, never the whole year', 'Só uma amostra pode ser guardada, nunca o ano inteiro',
    'The whole year fits easily; nothing has to be thrown away.', 'O ano inteiro cabe com folga; nada precisa ser jogado fora.'),
  C('A columnar warehouse is the only place that can hold it', 'Um warehouse colunar é o único lugar que consegue guardá-lo',
    'A few gigabytes fit anywhere; the format is a separate choice.', 'Alguns gigabytes cabem em qualquer lugar; o formato é outra escolha.')),
# ---- frequency
Q('ex-x6tqmjem', 'frequency', 'easy',
  ('Caio needs readings minute by minute, delivered once a week. Which of the two words describes "minute by minute"?',
   'Caio precisa de leituras minuto a minuto, entregues uma vez por semana. Qual das duas palavras descreve "minuto a minuto"?'),
  ('One is how fine the record is; the other is how old it may be.', 'Uma é quão fino é o registro; a outra é quão velho ele pode estar.'),
  C('Freshness', 'Frescor',
    'Freshness is the once a week: how old the newest data may be.', 'O frescor é o uma vez por semana: quão velho o dado mais novo pode estar.'),
  C('Granularity', 'Granularidade',
    'Right: how finely the data records what happened.', 'Isso: o nível de detalhe com que o dado registra o que aconteceu.', ok=True),
  C('Both at once', 'As duas ao mesmo tempo',
    'They are different things, which is the point of the section.', 'São coisas diferentes, e esse é o ponto da seção.')),
N('ex-0ffqbrw3', 'frequency', 'easy',
  ('Polling every minute for a day makes 1,440 calls. How many came back empty in `poll.py`?',
   'Consultar a cada minuto por um dia faz 1.440 chamadas. Quantas voltaram vazias no `poll.py`?'),
  ('The `empty` column, first row.', 'A coluna `empty`, primeira linha.'),
  779, 0, ('calls', 'chamadas')),
Q('ex-ndpdjpe0', 'frequency', 'medium',
  ('What does polling cost that push avoids?', 'O que o polling custa e o push evita?'),
  ('Think about the night.', 'Pense na madrugada.'),
  C('Calls that find nothing, and the wait until the next one', 'Chamadas que não encontram nada, e a espera até a próxima',
    'Right: push sends each record when it happens, so neither exists.', 'Isso: o push envia cada registro quando ele acontece, então nenhum dos dois existe.', ok=True),
  C('A copy of the source kept on your side', 'Uma cópia da origem guardada do seu lado',
    'Both ways end with a copy; that is what collecting is.', 'Os dois jeitos terminam com uma cópia; coletar é isso.'),
  C('The need for the source to offer it', 'A necessidade de a origem oferecê-lo',
    'That is push\'s price, not polling\'s: polling needs only answers.', 'Esse é o preço do push, não do polling: o polling só precisa de respostas.'),
  C('Records lost while your side is down', 'Registros perdidos enquanto o seu lado está fora do ar',
    'That is push\'s risk; a poll simply asks again later.', 'Esse é o risco do push; um polling só pergunta de novo depois.')),
M('ex-dmknx0cd', 'frequency', 'easy',
  ('Match each reader to how fresh its data has to be.', 'Associe cada leitor a quão fresco o dado dele precisa ser.'),
  ('Ask what each one does with the data.', 'Pergunte o que cada um faz com o dado.'),
  [(('Marta\'s morning report', 'o relatório da manhã de Marta'), ('yesterday, complete, by 07:00', 'o dia anterior completo até as 07:00')),
   (('the app\'s map of free bicycles', 'o mapa de bicicletas livres do aplicativo'), ('a minute or two', 'um ou dois minutos')),
   (('Caio\'s demand model', 'o modelo de demanda de Caio'), ('the last full week, by Sunday night', 'a última semana completa, até domingo à noite'))]),
Q('ex-1yyd7ffn', 'frequency', 'medium',
  ('Why is "real time" the wrong first answer to "how fresh must it be"?',
   'Por que "tempo real" é a primeira resposta errada para "quão fresco precisa ser"?'),
  ('Ask what decision changes.', 'Pergunte que decisão muda.'),
  C('Real-time data is less accurate than data copied in batches', 'Dado em tempo real é menos exato que dado copiado em lotes',
    'Accuracy and freshness are separate; the issue is cost.', 'Exatidão e frescor são coisas separadas; o problema é o custo.'),
  C('No source in practice can send data within a minute of it happening', 'Na prática nenhuma origem consegue enviar o dado dentro de um minuto',
    'The sensors do, to the app. It can be had; the question is whether it is needed.', 'Os sensores enviam, para o aplicativo. Dá para ter; a questão é se é preciso.'),
  C('It is asked for before anyone checks what would change', 'É pedido antes de alguém ver o que mudaria',
    'Right: fresher costs more, and only a decision that changes pays for it.', 'Isso: mais fresco custa mais, e só uma decisão que muda paga por isso.', ok=True),
  C('The LGPD forbids collecting personal data as it happens', 'A LGPD proíbe coletar dado pessoal no momento em que acontece',
    'The law is about purpose and necessity, not about timing.', 'A lei trata de finalidade e necessidade, não de horário.')),
# ---- incremental-loads
Z('ex-91vm79km', 'incremental-loads', 'easy',
  ('In an incremental load, the newest change the previous run saw is stored as the ___.',
   'Numa carga incremental, a mudança mais recente que a execução anterior viu é guardada como a ___.'),
  ('A word borrowed from the mark a river leaves.', 'Uma palavra emprestada da marca que a água deixa.'),
  ['watermark', 'high watermark', 'high-water mark'],
  ["marca d'água", 'marca d’água', 'marca dagua', 'marca de agua', 'watermark']),
Q('ex-parcchth', 'incremental-loads', 'medium',
  ('Why did the copy with no overlap never get `R000041`?',
   'Por que a cópia sem sobreposição nunca recebeu a `R000041`?'),
  ('Compare its `updated_at` with the watermark.', 'Compare o `updated_at` dela com a marca d\'água.'),
  C('Its transaction failed and the source rolled it back', 'A transação dela falhou e a origem a desfez',
    'It committed at 10:01, and `compare.py` finds it in the source.', 'Ela foi confirmada às 10:01, e o `compare.py` a encontra na origem.'),
  C('Its stamp, 09:57, was below the watermark the first copy had saved', 'O carimbo dela, 09:57, estava abaixo da marca d\'água salva pela primeira cópia',
    'Right: it committed after the 10:00 copy, and later runs start above 09:59.', 'Isso: foi confirmada depois da cópia das 10:00, e as execuções seguintes começam acima de 09:59.', ok=True),
  C('`INSERT OR REPLACE` wrote the refund over it', '`INSERT OR REPLACE` gravou o estorno por cima dela',
    'The refund is `R000010`; a different key replaces nothing here.', 'O estorno é a `R000010`; uma chave diferente não substitui nada aqui.'),
  C('The copy ran before the morning rides existed', 'A cópia rodou antes de as viagens da manhã existirem',
    'The first run copied all forty morning rides.', 'A primeira execução copiou as quarenta viagens da manhã.')),
Q('ex-84580z15', 'incremental-loads', 'medium',
  ('Both copies picked up the refund of `R000010`, an old ride. Why?',
   'As duas cópias pegaram o estorno da `R000010`, uma viagem antiga. Por quê?'),
  ('What happens to `updated_at` when a row changes?', 'O que acontece com o `updated_at` quando uma linha muda?'),
  C('The refund moved its `updated_at` forward to 10:02, above the watermark', 'O estorno moveu o `updated_at` dela para 10:02, acima da marca d\'água',
    'Right: a change to an old row is a new time, above the watermark.', 'Isso: uma mudança numa linha antiga é um horário novo, acima da marca d\'água.', ok=True),
  C('Every run copies refunds in full, whatever their time', 'Toda execução copia os estornos inteiros, seja qual for o horário',
    'The query asks only for `updated_at` above `since`; it knows no refunds.', 'A consulta só pede `updated_at` acima de `since`; ela não conhece estornos.'),
  C('The overlap of ten minutes reached back to its ride at 08:29', 'A sobreposição de dez minutos voltou até a viagem dela às 08:29',
    'The copy with no overlap caught it too.', 'A cópia sem sobreposição também a pegou.'),
  C('`compare.py` repaired both copies after they had run', 'O `compare.py` consertou as duas cópias depois que rodaram',
    '`compare.py` only reads; it writes nothing.', 'O `compare.py` só lê; ele não escreve nada.')),
N('ex-m2m33b68', 'incremental-loads', 'easy',
  ('In its second run, how many rows did the copy with ten minutes of overlap read?',
   'Na segunda execução, quantas linhas a cópia com dez minutos de sobreposição leu?'),
  ('`read ... rows since 09:49`.', '`read ... rows since 09:49`.'),
  7, 0, ('rows', 'linhas')),
Q('ex-9bm9f2ra', 'incremental-loads', 'hard',
  ('The overlap reads some rows a second time. What keeps those rows from appearing twice in the copy?',
   'A sobreposição lê algumas linhas uma segunda vez. O que impede essas linhas de aparecerem duas vezes na cópia?'),
  ('Look at how the copy writes.', 'Veja como a cópia escreve.'),
  C('The watermark skipping the rows it has already seen once', 'A marca d\'água pulando as linhas que já viu uma vez',
    'The overlap exists precisely to read some of them again.', 'A sobreposição existe justamente para ler algumas delas de novo.'),
  C('SQLite refusing any row it has received before', 'O SQLite recusando qualquer linha que já recebeu antes',
    'SQLite stores what it is told; the program decides it replaces.', 'O SQLite guarda o que mandam; quem decide substituir é o programa.'),
  C('An overlap kept shorter than one hour', 'Uma sobreposição mantida abaixo de uma hora',
    'Any overlap re-reads rows; the length decides how many, not whether they double.', 'Toda sobreposição relê linhas; o tamanho decide quantas, não se duplicam.'),
  C('Writes keyed on `ride_id`, replacing the old', 'Escritas pela chave `ride_id`, por cima da antiga',
    'Right: `INSERT OR REPLACE` by key makes a second read harmless.', 'Isso: `INSERT OR REPLACE` pela chave torna inofensiva uma segunda leitura.', ok=True)),
MC('ex-fh354a6s', 'incremental-loads', 'hard',
  ('Which of these can a ten-minute overlap NOT catch? Choose all that apply.',
   'Quais destes uma sobreposição de dez minutos NÃO consegue pegar? Marque todos os que se aplicam.'),
  ('Think about what has an `updated_at` inside the window.', 'Pense no que tem um `updated_at` dentro da janela.'),
  C('A row deleted in the source', 'Uma linha apagada na origem',
    'Yes: a deleted row has no `updated_at` left to find.', 'Sim: uma linha apagada não tem mais `updated_at` para ser encontrada.', ok=True),
  C('A row stamped by a server whose clock is a day slow', 'Uma linha carimbada por um servidor com o relógio um dia atrasado',
    'Yes: a day is far outside ten minutes.', 'Sim: um dia está muito fora de dez minutos.', ok=True),
  C('A row whose commit was two minutes late', 'Uma linha cujo commit atrasou dois minutos',
    'No: that is the case the overlap is for.', 'Não: esse é o caso para o qual a sobreposição existe.'),
  C('A refund of a ride from last week', 'Um estorno de uma viagem da semana passada',
    'No: the refund moves `updated_at` to now.', 'Não: o estorno move o `updated_at` para agora.')),
O('ex-pekkxx9n', 'incremental-loads', 'medium',
  ('Put the steps of one incremental run in order.', 'Ponha em ordem os passos de uma execução incremental.'),
  ('The watermark is saved last.', 'A marca d\'água é salva por último.'),
  [('read the saved watermark', 'ler a marca d\'água salva'),
   ('ask for rows changed after it, minus the overlap', 'pedir as linhas alteradas depois dela, menos a sobreposição'),
   ('write them into the copy by key', 'gravá-las na cópia pela chave'),
   ('commit the copy', 'confirmar a cópia'),
   ('save the new watermark', 'salvar a nova marca d\'água')],
  ('Saving the watermark before the commit loses the rows of a run that dies halfway.',
   'Salvar a marca d\'água antes do commit perde as linhas de uma execução que morre no meio.')),
# ---- quality-at-the-door
Q('ex-37tmj4fz', 'quality-at-the-door', 'easy',
  ('The delivery for the 16th has 137 rows where the source says it sent 200. What does the door do?',
   'A entrega do dia 16 tem 137 linhas onde a origem diz que enviou 200. O que a porta faz?'),
  ('It is a check on the file.', 'É uma verificação do arquivo.'),
  C('Loads the 137, since each passes the row checks', 'Carrega as 137, que passam nas verificações de linha',
    'That makes the day look quiet: a wrong number, not a missing one.', 'Isso faz o dia parecer tranquilo: um número errado, não um faltando.'),
  C('Loads them and puts the 63 missing ones in quarantine', 'Carrega e põe as 63 que faltam na quarentena',
    'Missing rows cannot be quarantined; they are not there.', 'Linhas que faltam não vão para a quarentena; elas não estão lá.'),
  C('Refuses the whole file, and the program ends with an error', 'Recusa o arquivo inteiro, e o programa termina com um erro',
    'Right: nothing is loaded, and a scheduler sees the failure.', 'Isso: nada é carregado, e um agendador vê a falha.', ok=True),
  C('Loads the rows and flags the day as partial in a column', 'Carrega as linhas e marca o dia como parcial numa coluna',
    'Every reader would have to remember to check the flag.', 'Todo leitor teria de lembrar de olhar a marca.')),
M('ex-4mts75pd', 'quality-at-the-door', 'medium',
  ('Match each quarantined row of the 15th to the kind of check that caught it.',
   'Associe cada linha em quarentena do dia 15 ao tipo de verificação que a pegou.'),
  ('Four rows, four kinds.', 'Quatro linhas, quatro tipos.'),
  [(('start station `ST13`', 'estação de início `ST13`'), ('reference', 'referência')),
   (('a ride of -4 minutes', 'uma viagem de -4 minutos'), ('range', 'faixa')),
   (('an empty `started_at`', 'um `started_at` vazio'), ('missing value', 'valor ausente')),
   (('`R000150` a second time', '`R000150` uma segunda vez'), ('uniqueness', 'unicidade'))]),
Q('ex-r6bqjtsd', 'quality-at-the-door', 'medium',
  ('Why is a row that fails a check quarantined instead of dropped?',
   'Por que uma linha que falha numa verificação vai para a quarentena em vez de ser descartada?'),
  ('Who finds out it existed?', 'Quem fica sabendo que ela existiu?'),
  C('So it can be loaded automatically the next night', 'Para ser carregada automaticamente na noite seguinte',
    'Nothing in it is fixed by waiting a night.', 'Nada nela se conserta esperando uma noite.'),
  C('So somebody can see it, and why', 'Para alguém poder vê-la, e o motivo',
    'Right: a silent drop is invisible to every report.', 'Isso: um descarte silencioso é invisível para todo relatório.', ok=True),
  C('Because the LGPD forbids deleting any data that has arrived', 'Porque a LGPD proíbe apagar qualquer dado que chegou',
    'The LGPD in fact requires deleting personal data on request.', 'A LGPD na verdade exige apagar dado pessoal a pedido.'),
  C('Because the row count would no longer match the source', 'Porque a contagem de linhas não bateria mais com a origem',
    'The count is checked on the file before any row is judged.', 'A contagem é conferida no arquivo antes de qualquer linha ser julgada.')),
Q('ex-trpn0wva', 'quality-at-the-door', 'hard',
  ('The delivery of the 15th had 200 rows and passed the file checks, yet `R000151` was not in it. Which check at the door could have noticed?',
   'A entrega do dia 15 tinha 200 linhas e passou nas verificações do arquivo, mas a `R000151` não estava nela. Que verificação na porta poderia ter percebido?'),
  ('The file kept its promised count.', 'O arquivo manteve a contagem prometida.'),
  C('The uniqueness check, which flagged `R000150` instead', 'A de unicidade, que em vez disso marcou a `R000150`',
    'It saw the double, not what the double replaced.', 'Ela viu a repetição, não o que a repetição substituiu.'),
  C('The row count, compared with the 200 promised', 'A contagem de linhas, comparada às 200 prometidas',
    'The count was 200: one doubled, one missing.', 'A contagem deu 200: uma repetida, uma faltando.'),
  C('None of them: the file had all 200 rows it promised', 'Nenhuma: o total de 200 batia com o prometido',
    'Right: only the source\'s own list of rides shows it; that is reconciliation.', 'Isso: só a lista de viagens da própria origem mostra; isso é reconciliação.', ok=True),
  C('The reference check on the start station', 'A de referência sobre a estação de início',
    'It judges the rows that are there, not the ones that are not.', 'Ela julga as linhas que estão lá, não as que não estão.')),
Q('ex-ahs3fmxp', 'quality-at-the-door', 'hard',
  ('A quarantine file has grown by four hundred rows a day for a week, and nobody has opened it. What has happened, in effect?',
   'Um arquivo de quarentena cresceu quatrocentas linhas por dia durante uma semana, e ninguém o abriu. O que aconteceu, na prática?'),
  ('Where are those rows in Marta\'s report?', 'Onde estão essas linhas no relatório de Marta?'),
  C('A silent drop of rows, and a source that has changed', 'Um descarte silencioso de linhas, e uma origem que mudou',
    'Right: four hundred a day is a change, and an unread quarantine hides it.', 'Isso: quatrocentas por dia é uma mudança, e uma quarentena não lida a esconde.', ok=True),
  C('Quality improved, since the bad rows were kept out', 'A qualidade melhorou, já que as linhas ruins ficaram de fora',
    'Rows kept out with nobody looking are rows missing from every number.', 'Linhas deixadas de fora sem ninguém olhar são linhas faltando em todo número.'),
  C('Nothing yet: quarantined rows load once the source fixes them', 'Nada ainda: as linhas em quarentena carregam quando a origem as corrigir',
    'Nobody told the source; nothing will fix them.', 'Ninguém avisou a origem; nada vai corrigi-las.'),
  C('The whole delivery was refused each day, so nothing loaded', 'A entrega inteira foi recusada todo dia, então nada carregou',
    'Refusal is for file checks; quarantine means the rest did load.', 'A recusa é das verificações do arquivo; quarentena quer dizer que o resto carregou.')),
Z('ex-qtykzkgh', 'quality-at-the-door', 'easy',
  ('A row that fails a check at the door is set aside in ___, with its reason.',
   'Uma linha que falha numa verificação na porta é separada na ___, com o motivo.'),
  ('A word from medicine: kept apart until it is safe.', 'Uma palavra da medicina: mantido à parte até ser seguro.'),
  ['quarantine', 'a quarantine'], ['quarentena']),
# ---- reconciliation
Q('ex-48tc70xy', 'reconciliation', 'easy',
  ('Where must the second number in a reconciliation come from?',
   'De onde precisa vir o segundo número de uma reconciliação?'),
  ('A number that agrees by construction proves nothing.', 'Um número que concorda por construção não prova nada.'),
  C('The pipeline\'s own count of the copy it made', 'A contagem que o pipeline faz da cópia que ele fez',
    'That agrees with the copy whatever the copy holds.', 'Essa concorda com a cópia seja o que for que a cópia tenha.'),
  C('Yesterday\'s reconciliation, carried forward a day', 'A reconciliação de ontem, levada adiante um dia',
    'Yesterday says nothing about what arrived today.', 'Ontem não diz nada sobre o que chegou hoje.'),
  C('The number of lines in the quarantine file', 'O número de linhas do arquivo de quarentena',
    'Quarantine counts rejects, not what the source holds.', 'A quarentena conta rejeitadas, não o que a origem tem.'),
  C('The source, from its own record of what it holds', 'A origem, a partir do próprio registro do que tem',
    'Right: a statement, a count on a replica, the number beside a file.', 'Isso: um extrato, uma contagem numa réplica, o número ao lado de um arquivo.', ok=True)),
N('ex-99k83t4x', 'reconciliation', 'easy',
  ('On 2025-09-19, how many payments did each side count?',
   'Em 2025-09-19, quantos pagamentos cada lado contou?'),
  ('Both sides agree on it.', 'Os dois lados concordam nisso.'),
  105, 0, ('payments', 'pagamentos')),
Q('ex-24b3eyeh', 'reconciliation', 'medium',
  ('The 19th passed on count and failed on sum. What happened?',
   'O dia 19 passou na contagem e falhou na soma. O que aconteceu?'),
  ('The keys say it.', 'As chaves dizem.'),
  C('One payment arrived twice and another never did', 'Um pagamento chegou duas vezes e outro nunca chegou',
    'Right: `P19005` twice, `P19030` never, and their amounts differ.', 'Isso: `P19005` duas vezes, `P19030` nenhuma, e os valores são diferentes.', ok=True),
  C('The provider rounded its amounts to whole reais', 'O provedor arredondou os valores para reais inteiros',
    'Both sides are in centavos; nothing was rounded.', 'Os dois lados estão em centavos; nada foi arredondado.'),
  C('A payment\'s amount was altered on the way in', 'O valor de um pagamento foi alterado na chegada',
    'The keys show a double and a gap, not an edited amount.', 'As chaves mostram uma repetição e uma falta, não um valor editado.'),
  C('The two sides closed the day at different hours', 'Os dois lados fecharam o dia em horários diferentes',
    'That would shift payments every day, not only the 19th.', 'Isso deslocaria pagamentos todo dia, não só no 19.')),
O('ex-mjbjfrjx', 'reconciliation', 'easy',
  ('Put the three levels of reconciliation in order, from the cheapest to the most thorough.',
   'Ponha os três níveis de reconciliação em ordem, do mais barato ao mais completo.'),
  ('One number a day, then two, then every key.', 'Um número por dia, depois dois, depois todas as chaves.'),
  [('counts', 'contagens'), ('control totals', 'totais de controle'), ('keys', 'chaves')],
  ('Keys find exactly which rows, and need every key from both sides.',
   'As chaves acham exatamente quais linhas, e precisam de todas as chaves dos dois lados.')),
# ---- cost
N('ex-0hba7ekc', 'cost', 'easy',
  ('In `cost.py`, what does the dashboard reading the whole year cost a month, in reais?',
   'No `cost.py`, quanto custa por mês o painel que lê o ano inteiro, em reais?'),
  ('The fourth line of costs.', 'A quarta linha de custos.'),
  2100.30, 0.01, ('R$', 'R$')),
Q('ex-dk0t1pz8', 'cost', 'medium',
  ('The same dashboard costs R$ 5.75 a month when it reads only today. What made the difference?',
   'O mesmo painel custa R$ 5,75 por mês quando lê só o dia de hoje. O que fez a diferença?'),
  ('Nothing about the data changed.', 'Nada no dado mudou.'),
  C('Today\'s data compresses much better than a year of it', 'O dado de hoje comprime muito melhor que um ano dele',
    'The program applies no compression; it divides by 365.', 'O programa não aplica compressão; ele divide por 365.'),
  C('Query engines charge less for data written recently', 'Motores de consulta cobram menos por dado escrito há pouco',
    'One price per terabyte is used for both lines.', 'Um único preço por terabyte é usado nas duas linhas.'),
  C('It refreshes once a day instead of every five minutes', 'Ele atualiza uma vez por dia em vez de a cada cinco minutos',
    'Both lines use the same 8640 refreshes.', 'As duas linhas usam as mesmas 8640 atualizações.'),
  C('It reads one day, not 365', 'Ele lê um dia, não 365',
    'Right: same refreshes, one 365th of the bytes.', 'Isso: as mesmas atualizações, um 365 avos dos bytes.', ok=True)),
Q('ex-332sbt09', 'cost', 'hard',
  ('What decides whether a query for today can avoid reading the rest of the year?',
   'O que decide se uma consulta sobre hoje consegue evitar ler o resto do ano?'),
  ('Lesson 3 stored its raw rides in a particular way.', 'A aula 3 guardou as viagens brutas de um jeito específico.'),
  C('How the data was laid out when collected', 'Como o dado foi organizado ao ser coletado',
    'Right: one directory per day lets a query open one directory.', 'Isso: um diretório por dia deixa uma consulta abrir um diretório.', ok=True),
  C('The provider\'s price list for the region the data is in', 'A tabela de preços do provedor para a região onde o dado está',
    'Prices change what a read costs, not how much is read.', 'O preço muda quanto custa ler, não quanto se lê.'),
  C('How many people have the dashboard open at once', 'Quantas pessoas estão com o painel aberto ao mesmo tempo',
    'That multiplies the reads; it does not shrink each one.', 'Isso multiplica as leituras; não diminui cada uma.'),
  C('Whether the readings were pushed by the source or polled', 'Se as leituras foram empurradas pela origem ou consultadas',
    'How data arrives says nothing about how it is stored.', 'Como o dado chega não diz nada sobre como ele é guardado.')),
MC('ex-za5ef1bc', 'cost', 'medium',
  ('Which of these costs grow with how often the data is read or moved? Choose all that apply.',
   'Quais destes custos crescem com a frequência com que o dado é lido ou movido? Marque todos os que se aplicam.'),
  ('One grows with volume and time instead.', 'Um cresce com o volume e o tempo, em vez disso.'),
  C('compute, by the terabyte read', 'processamento, pelo terabyte lido',
    'Yes: every refresh reads again.', 'Sim: cada atualização lê de novo.', ok=True),
  C('transfer out of the provider', 'transferência para fora do provedor',
    'Yes: paid again on every copy.', 'Sim: paga de novo a cada cópia.', ok=True),
  C('calls to a paid API', 'chamadas a uma API paga',
    'Yes: one per poll.', 'Sim: uma por consulta.', ok=True),
  C('storage, by the gigabyte-month', 'armazenamento, pelo gigabyte-mês',
    'No: it grows with volume and with every month kept.', 'Não: cresce com o volume e com cada mês guardado.')),
# ---- privacy-and-minimisation
Q('ex-xranbejq', 'privacy-and-minimisation', 'easy',
  ('Which LGPD principle limits personal data to the minimum its purpose requires?',
   'Que princípio da LGPD limita o dado pessoal ao mínimo que a finalidade exige?'),
  ('Article 6 names it.', 'O artigo 6 o nomeia.'),
  C('Purpose', 'Finalidade',
    'Purpose says what the data is for; the other one limits how much.', 'A finalidade diz para que serve; o outro limita quanto.'),
  C('Necessity', 'Necessidade',
    'Right: no more than the purpose requires.', 'Isso: não mais do que a finalidade exige.', ok=True),
  C('Transparency', 'Transparência',
    'Transparency is about telling the person, not about how much is held.', 'Transparência é sobre informar o titular, não sobre quanto se guarda.'),
  C('Security', 'Segurança',
    'Security protects what is held; it does not limit it.', 'Segurança protege o que se guarda; não o limita.')),
Q('ex-m8155m4f', 'privacy-and-minimisation', 'medium',
  ('Why is a plain SHA-256 of a phone number not anonymous?',
   'Por que um SHA-256 simples de um número de telefone não é anônimo?'),
  ('What did the partner do?', 'O que o parceiro fez?'),
  C('SHA-256 can be decrypted with the right tool', 'O SHA-256 pode ser descriptografado com o programa certo',
    'A hash is not encryption; it is recomputed, not decrypted.', 'Hash não é criptografia; ele é recalculado, não descriptografado.'),
  C('Anyone can hash a list of numbers and compare', 'Qualquer um pode passar uma lista pelo hash e comparar',
    'Right: no secret, and only a hundred million Curitiba mobiles.', 'Isso: não há segredo, e são só cem milhões de celulares em Curitiba.', ok=True),
  C('The hash is longer than the phone number it hides', 'O hash é mais longo que o número de telefone que esconde',
    'Length has nothing to do with whether it can be linked.', 'O tamanho não tem nada a ver com poder ser religado.'),
  C('Two different phone numbers often share the same hash', 'Dois números de telefone diferentes costumam ter o mesmo hash',
    'Collisions are not the problem; matching is.', 'Colisões não são o problema; a comparação é.')),
N('ex-e7bv91fm', 'privacy-and-minimisation', 'easy',
  ('How many of the partner\'s three numbers were found among the plain hashes?',
   'Quantos dos três números do parceiro foram encontrados entre os hashes simples?'),
  ('The second-to-last line of `pseudo.py`.', 'A penúltima linha do `pseudo.py`.'),
  2, 0, ('numbers', 'números')),
Q('ex-j1sbmpht', 'privacy-and-minimisation', 'medium',
  ('Caio\'s model needs rides per station per hour. What should happen to the exact second each ride started?',
   'O modelo de Caio precisa de viagens por estação por hora. O que deve acontecer com o segundo exato em que cada viagem começou?'),
  ('Needed, but only roughly.', 'Necessário, mas só de forma aproximada.'),
  C('Pseudonymise it with a keyed hash before copying', 'Pseudonimizar com um hash com chave antes de copiar',
    'A pseudonym is for telling people apart, not for a time.', 'Um pseudônimo serve para distinguir pessoas, não para um horário.'),
  C('Leave the whole ride out of the copy', 'Deixar a viagem inteira fora da cópia',
    'The model counts rides; it needs them.', 'O modelo conta viagens; precisa delas.'),
  C('Keep it, since a time is never personal data', 'Mantê-lo, já que um horário nunca é dado pessoal',
    'Where somebody was, and when, describes that person.', 'Onde alguém estava, e quando, descreve essa pessoa.'),
  C('Coarsen it to the hour', 'Reduzir para a hora',
    'Right: the question needs the hour, not the second.', 'Isso: a pergunta precisa da hora, não do segundo.', ok=True)),
Z('ex-h8jdj3am', 'privacy-and-minimisation', 'medium',
  ('Replacing an identifier with a consistent stand-in that only a separately kept key can link back is called ___.',
   'Trocar um identificador por um substituto consistente que só uma chave guardada à parte consegue religar se chama ___.'),
  ('Not anonymisation.', 'Não é anonimização.'),
  ['pseudonymisation', 'pseudonymization', 'pseudonymising', 'pseudonymizing'],
  ['pseudonimização', 'pseudonimizacao', 'pseudonimizar']),
# ---- a-collection-checklist
Q('ex-x9r252ne', 'a-collection-checklist', 'easy',
  ('Why does "what is it for?" sit first on the checklist?',
   'Por que "para que serve?" fica em primeiro na lista?'),
  ('Try answering "how fresh?" without it.', 'Tente responder "quão fresco?" sem ela.'),
  C('Because the LGPD asks that it be written first in every document', 'Porque a LGPD pede que ela venha primeiro em todo documento',
    'The law asks for a purpose, not for an order on a page.', 'A lei pede uma finalidade, não uma ordem na página.'),
  C('Because it is the only question the owner can answer', 'Porque é a única pergunta que o dono sabe responder',
    'The owner answers several others; the purpose comes from the reader.', 'O dono responde várias outras; a finalidade vem do leitor.'),
  C('The other answers depend on it', 'As outras respostas dependem dela',
    'Right: freshness, volume and checks mean nothing without a use.', 'Isso: frescor, volume e verificações não querem dizer nada sem um uso.', ok=True),
  C('Because it is the quickest question on the list to answer', 'Porque é a pergunta mais rápida de responder da lista',
    'Speed has nothing to do with it; it comes first anyway.', 'A rapidez não tem nada a ver; ela vem primeiro mesmo assim.')),
Q('ex-6e23jvwj', 'a-collection-checklist', 'medium',
  ('The sensors\' server keeps readings for two days. What does that make the pipeline\'s outages?',
   'O servidor dos sensores guarda as leituras por dois dias. O que isso faz das paradas do pipeline?'),
  ('Think of a long weekend.', 'Pense num feriado prolongado.'),
  C('Harmless, since the copy can catch up whenever it restarts', 'Inofensivas, já que a cópia recupera quando reiniciar',
    'Only for two days; after that the readings are gone.', 'Só por dois dias; depois disso as leituras somem.'),
  C('A deadline: after two days down, those readings are lost for good', 'Um prazo: depois de dois dias parado, essas leituras se perdem de vez',
    'Right: those readings are gone, and nobody collects them again.', 'Isso: essas leituras somem, e ninguém as coleta de novo.', ok=True),
  C('A reason to poll the server every minute', 'Um motivo para consultar o servidor a cada minuto',
    'Polling more often does not help a pipeline that is down.', 'Consultar mais vezes não ajuda um pipeline que está parado.'),
  C('A matter for the sensors\' team alone to solve', 'Um assunto só do time dos sensores resolver',
    'It is a fact about the source the pipeline has to plan for.', 'É um fato da origem que o pipeline precisa prever.')),
# ---- drill
Q('ex-7vmhg4g8', 'drill', 'hard',
  ('A partner\'s API charges per call and can also push each event to an address you give it. Marta reads its data once a week. What fits?',
   'A API de um parceiro cobra por chamada e também pode empurrar cada evento para um endereço que você der. Marta lê esses dados uma vez por semana. O que serve?'),
  ('Who reads it, and how often?', 'Quem lê, e com que frequência?'),
  C('Polling every minute, so nothing is ever more than a minute old', 'Consultar a cada minuto, para nada ter mais de um minuto',
    'A minute of freshness that nobody reads, paid for in calls.', 'Um minuto de frescor que ninguém lê, pago em chamadas.'),
  C('Push, and a receiver running all week to listen for it', 'Push, e um receptor rodando a semana toda para escutar',
    'It works, and keeps a service up all week for a weekly reader.', 'Funciona, e mantém um serviço no ar a semana toda para uma leitora semanal.'),
  C('One pull a week, before she reads', 'Um pull por semana, antes de ela ler',
    'Right: the reader decides the freshness, and one call a week is the cheapest.', 'Isso: o leitor decide o frescor, e uma chamada por semana é o mais barato.', ok=True),
  C('Polling every hour, as a compromise between the two', 'Consultar a cada hora, como meio-termo entre os dois',
    'A compromise between answers nobody needed is still too fresh.', 'Um meio-termo entre respostas de que ninguém precisava ainda é fresco demais.')),
Q('ex-4cj3ncn7', 'drill', 'hard',
  ('One app server\'s clock runs three minutes slow, and it stamps `updated_at` with its own clock. What does an incremental load need?',
   'O relógio de um servidor do aplicativo está três minutos atrasado, e ele carimba o `updated_at` com esse relógio. Do que uma carga incremental precisa?'),
  ('Its rows arrive carrying a time three minutes in the past.', 'As linhas dele chegam com um horário três minutos no passado.'),
  C('An overlap longer than three minutes, so the window reaches its rows', 'Uma sobreposição maior que três minutos, para a janela alcançar as linhas dele',
    'Right: the window has to reach back past the slowest clock.', 'Isso: a janela precisa voltar além do relógio mais atrasado.', ok=True),
  C('No change, since a watermark ignores the clock of the source', 'Nenhuma mudança, já que a marca d\'água ignora o relógio da origem',
    'The watermark is made of the source\'s own stamps.', 'A marca d\'água é feita dos próprios carimbos da origem.'),
  C('A full load every night instead, whatever the size of the table', 'Uma carga completa toda noite, seja qual for o tamanho da tabela',
    'That works, at the price incremental loads exist to avoid.', 'Funciona, ao preço que as cargas incrementais existem para evitar.'),
  C('A uniqueness check at the door on `ride_id`', 'Uma verificação de unicidade na porta sobre `ride_id`',
    'The rows are missing, not doubled; nothing reaches the door.', 'As linhas faltam, não se repetem; nada chega à porta.')),
Q('ex-jmthy3pp', 'drill', 'hard',
  ('The provider closes its statement\'s day in UTC; the copy closes it in `America/Sao_Paulo`. What does a nightly count show?',
   'O provedor fecha o dia do extrato em UTC; a cópia o fecha em `America/Sao_Paulo`. O que mostra uma contagem noturna?'),
  ('Where does a payment at 22:30 in Curitiba fall?', 'Onde cai um pagamento às 22:30 em Curitiba?'),
  C('Agreement, since a count does not depend on a clock', 'Concordância, já que uma contagem não depende de relógio',
    'Which day a payment is counted on depends on the clock.', 'Em que dia um pagamento é contado depende do relógio.'),
  C('A gap only on the nights when the clocks change for summer', 'Uma diferença só nas noites em que o relógio muda para o verão',
    'The gap is three hours wide every night.', 'A diferença tem três horas de largura toda noite.'),
  C('A gap every night, from the last three hours of it', 'Uma diferença toda noite, das últimas três horas de cada dia',
    'Right: the last three hours of each local day fall on the next UTC day.', 'Isso: as últimas três horas de cada dia local caem no dia UTC seguinte.', ok=True),
  C('A gap of exactly one day\'s payments once a week', 'Uma diferença de exatamente um dia de pagamentos uma vez por semana',
    'The offset is three hours, not a day, and it repeats daily.', 'O deslocamento é de três horas, não um dia, e se repete diariamente.')),
Q('ex-ew0gkc4e', 'drill', 'hard',
  ('Roda Livre keeps the HMAC key in a secret store. Is the pseudonymised copy of the rides still personal data under the LGPD?',
   'A Roda Livre guarda a chave do HMAC num cofre de segredos. A cópia pseudonimizada das viagens continua sendo dado pessoal pela LGPD?'),
  ('Article 12, and who holds the key.', 'O artigo 12, e quem tem a chave.'),
  C('No: a hash cannot be reversed, so it is anonymised', 'Não: um hash não pode ser revertido, então está anonimizado',
    'Whoever has the key recomputes the stand-in and re-links it.', 'Quem tem a chave recalcula o substituto e religa.'),
  C('Yes: anyone holding the key links it back to the customer', 'Sim: quem tem a chave consegue ligá-la de volta à pessoa',
    'Right: re-identifiable by reasonable means is still personal.', 'Isso: reidentificável por meios razoáveis continua pessoal.', ok=True),
  C('No, once the phone column has been removed from the copy', 'Não, depois que a coluna de telefone sai da cópia',
    'The pseudonym still points at one person, through the key.', 'O pseudônimo ainda aponta para uma pessoa, pela chave.'),
  C('Only if the key is stored in the same database as the copy', 'Só se a chave for guardada no mesmo banco que a cópia',
    'Keeping it apart lowers the harm of a leak, not the law\'s reach.', 'Guardá-la à parte diminui o estrago de um vazamento, não o alcance da lei.')),
MC('ex-1m99f9sn', 'drill', 'medium',
  ('Which belong in the data contract with a source\'s owner? Choose all that apply.',
   'Quais pertencem ao contrato de dados com o dono de uma origem? Marque todas as que se aplicam.'),
  ('What a delivery can break.', 'O que uma entrega pode quebrar.'),
  C('the columns a delivery carries', 'as colunas que uma entrega traz',
    'Yes: a renamed column breaks the door.', 'Sim: uma coluna renomeada quebra a porta.', ok=True),
  C('the count sent beside each file', 'a contagem enviada ao lado de cada arquivo',
    'Yes: it is what the file check compares against.', 'Sim: é contra ela que a verificação do arquivo compara.', ok=True),
  C('the limits a value must sit inside', 'os limites dentro dos quais um valor deve ficar',
    'Yes: a rule the source does not know breaks when it changes.', 'Sim: uma regra que a origem não conhece quebra quando ela muda.', ok=True),
  C('how often Marta\'s dashboard refreshes', 'com que frequência o painel de Marta atualiza',
    'No: that is between the data team and its readers.', 'Não: isso é entre o time de dados e os leitores dele.')),
]
