from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
# ---- a-map-of-sources
Q('ex-nc0bk9eb', 'a-map-of-sources', 'easy',
  ('What is wrong with picturing a source as a shelf where finished data waits to be collected?',
   'O que há de errado em imaginar uma fonte como uma prateleira onde dados prontos esperam ser buscados?'),
  ('Ask what the system was built to do.', 'Pergunte para que o sistema foi feito.'),
  C('Shelves are for files, and most sources are databases', 'Prateleiras são para arquivos, e a maioria das fontes é banco de dados',
    'The kind of source is not the problem; every kind belongs to a busy system.', 'O tipo de fonte não é o problema; todo tipo pertence a um sistema ocupado.'),
  C('It belongs to a system busy with another job, whose owners change it', 'Pertence a um sistema ocupado com outro trabalho, que os donos mudam quando querem',
    'Right: you read it as a guest, and it changes when its owners decide.', 'Isso: você o lê como visita, e ele muda quando os donos decidem.', ok=True),
  C('The data on a shelf is already cleaned, which a source never is', 'O dado da prateleira já vem limpo, e o de uma fonte não',
    'Cleanliness is a later question; the picture fails on ownership first.', 'Limpeza é uma pergunta posterior; a imagem falha antes, na questão do dono.'),
  C('A shelf holds one copy, while a source keeps a backup of everything', 'Uma prateleira guarda uma cópia, e uma fonte guarda backup de tudo',
    'Backups have nothing to do with it; the source is doing another job.', 'Backup não tem nada a ver; a fonte está fazendo outro trabalho.')),
Q('ex-jk3xqzze', 'a-map-of-sources', 'medium',
  ('Which of these sources sends its data rather than waiting to be asked?',
   'Qual destas fontes envia os dados em vez de esperar ser consultada?'),
  ('Who decides when the data moves?', 'Quem decide quando o dado se mexe?'),
  C('The payments provider’s API, which answers each page you request', 'A API do provedor de pagamentos, que responde cada página pedida',
    'An API answers when asked: that is pull.', 'Uma API responde quando consultada: isso é pull.'),
  C('The contractor’s nightly CSV in a directory', 'O CSV noturno da oficina num diretório',
    'The file waits in its directory until Davi’s side reads it.', 'O arquivo espera no diretório até o lado de Davi lê-lo.'),
  C('The dock sensors, which report every minute on their own', 'Os sensores das docas, que falam a cada minuto sozinhos',
    'Right: the docks decide when to speak, and Roda Livre has to be listening.', 'Isso: as docas decidem quando falar, e a Roda Livre precisa estar escutando.', ok=True),
  C('A read replica of the app’s database', 'Uma réplica de leitura do banco do app',
    'A replica is queried, so it is pulled from.', 'Uma réplica é consultada, então é de pull.')),
Q('ex-4gj2ez8d', 'a-map-of-sources', 'medium',
  ('Why is a failed push harder to notice than a failed pull?',
   'Por que uma falha de push é mais difícil de perceber que uma falha de pull?'),
  ('In a pull, whose request fails?', 'Num pull, a requisição de quem falha?'),
  C('Push sources send data in binary formats that hide errors', 'Fontes de push mandam dados em formatos binários que escondem erros',
    'The format is not the reason; the absence of a request is.', 'O formato não é o motivo; a ausência de uma requisição é.'),
  C('Push failures are logged on the sender, which the data team cannot read', 'Falhas de push ficam no log de quem envia, que o time de dados não lê',
    'Even with the sender’s log, the receiving side sees nothing happen.', 'Mesmo com o log de quem envia, o lado que recebe não vê nada acontecer.'),
  C('Push sources retry forever, so a failure never ends', 'Fontes de push tentam de novo para sempre, então a falha não acaba',
    'Retries are not the issue; silence on the receiving side is.', 'Tentativas não são a questão; o silêncio do lado que recebe é.'),
  C('No request of yours failed, so nothing on your side errors', 'Nenhuma requisição sua falhou, então nada do lado de quem lê dá erro',
    'Right: the data just never comes, and only knowing what should have come shows it.', 'Isso: o dado só não chega, e só saber o que deveria ter vindo revela isso.', ok=True)),
M('ex-9sapjqw3', 'a-map-of-sources', 'easy',
  ('Match each kind of source to how Davi reads it.', 'Associe cada tipo de fonte ao jeito como Davi a lê.'),
  ('The table’s fourth column.', 'A quarta coluna da tabela.'),
  [(('the app’s database', 'o banco do app'), ('a query, a copy or its change log', 'uma consulta, uma cópia ou o log de mudanças')),
   (('the payments API', 'a API de pagamentos'), ('HTTP requests, page by page', 'requisições HTTP, página por página')),
   (('the contractor’s export', 'a exportação da oficina'), ('waiting for it in a directory or a bucket', 'esperar por ela num diretório ou num bucket')),
   (('the API server’s access log', 'o log de acesso do servidor da API'), ('parsing lines of text', 'analisar linhas de texto'))]),
# ---- databases
Q('ex-w8t3s9pj', 'databases', 'easy',
  ('Why does the data team at Roda Livre never run analytical queries on the primary database?',
   'Por que o time de dados da Roda Livre nunca roda consultas analíticas no banco primário?'),
  ('Who else is using that machine?', 'Quem mais está usando essa máquina?'),
  C('The primary does not allow SELECT statements from other teams', 'O primário não aceita comandos SELECT de outros times',
    'It accepts them; that is exactly the danger.', 'Ele aceita; esse é justamente o perigo.'),
  C('Reading every row takes disk, memory and processor the app needs', 'Ler todas as linhas toma disco, memória e processador de que o app precisa',
    'Right: the scan takes disk, memory and processor the app was using.', 'Isso: a varredura toma disco, memória e processador que o app usava.', ok=True),
  C('The primary holds only today’s rides, so history is elsewhere', 'O primário guarda só as viagens de hoje, então a história fica em outro lugar',
    'It holds the current state of everything; speed is the reason, not scope.', 'Ele guarda o estado atual de tudo; o motivo é velocidade, não alcance.'),
  C('Analytical queries change rows by accident', 'Consultas analíticas mudam linhas sem querer',
    'A read changes nothing, and still hurts the app.', 'Uma leitura não muda nada, e mesmo assim prejudica o app.')),
N('ex-7p59y9ke', 'databases', 'easy',
  ('After the second incremental copy, how many rides did `copy.db` hold?',
   'Depois da segunda cópia incremental, quantas viagens o `copy.db` tinha?'),
  ('The last line of the capture.', 'A última linha da captura.'),
  5, 0, ('rides', 'viagens')),
Q('ex-4cy9zhhs', 'databases', 'medium',
  ('Why did the incremental copy keep ride `R000104` after the app deleted it?',
   'Por que a cópia incremental manteve a viagem `R000104` depois que o app a apagou?'),
  ('What does the copy ask the source for?', 'O que a cópia pede à fonte?'),
  C('The copy ran before the delete was committed', 'A cópia rodou antes de a remoção ser gravada',
    'The second copy ran after `later.py` had committed everything.', 'A segunda cópia rodou depois de o `later.py` gravar tudo.'),
  C('`INSERT OR REPLACE` refuses to remove rows it has written', '`INSERT OR REPLACE` se recusa a remover linhas que gravou',
    'It replaces rows it is given; nobody gave it the deleted one.', 'Ele substitui as linhas que recebe; ninguém lhe passou a apagada.'),
  C('A deleted row has no newer `updated_at` to find', 'Uma linha apagada não tem `updated_at` novo para achar',
    'Right: it is simply not there to be selected.', 'Isso: ela simplesmente não está lá para ser selecionada.', ok=True),
  C('The watermark was set to the wrong time zone', 'A marca d’água estava no fuso errado',
    'The watermark worked: it found both changed rows.', 'A marca d’água funcionou: achou as duas linhas alteradas.')),
Q('ex-dcytk708', 'databases', 'hard',
  ('A new screen in the app lets staff move a ride to another station, but the code forgets to update `updated_at`. What does the incremental copy do?',
   'Uma tela nova do app deixa a equipe mudar uma viagem de estação, mas o código esquece de atualizar `updated_at`. O que a cópia incremental faz?'),
  ('The copy trusts one column.', 'A cópia confia numa coluna.'),
  C('Raises an error the next time it compares the two databases', 'Levanta um erro da próxima vez que compara os dois bancos',
    'The copy prints counts; it does not compare contents, and the counts still agree.', 'A cópia imprime contagens; não compara conteúdo, e as contagens continuam iguais.'),
  C('Keeps the old station, and says nothing about it', 'Mantém a estação antiga, sem dizer nada sobre isso',
    'Right: a change with no newer `updated_at` is invisible to it.', 'Isso: uma mudança sem `updated_at` mais novo é invisível para ela.', ok=True),
  C('Copies the ride twice, once per station', 'Copia a viagem duas vezes, uma por estação',
    'It never sees the change, so it copies nothing new.', 'Ela não vê a mudança, então não copia nada novo.'),
  C('Picks up the change on the next run, because the row is newer', 'Pega a mudança na execução seguinte, porque a linha é mais nova',
    'The row is only newer if `updated_at` says so, and here it does not.', 'A linha só é mais nova se o `updated_at` disser, e aqui ele não diz.')),
MC('ex-k32rhfak', 'databases', 'medium',
  ('Which of these would let the data team’s copy find out that ride `R000104` was cancelled? Choose all that apply.',
   'Quais destas fariam a cópia do time de dados descobrir que a viagem `R000104` foi cancelada? Marque todas as que se aplicam.'),
  ('Three were named in the section.', 'A seção citou três.'),
  C('The app marks cancelled rides with `deleted_at` instead of deleting them', 'O app marca viagens canceladas com `deleted_at` em vez de apagá-las',
    'Yes: a soft delete is an update the copy sees.', 'Sim: uma remoção lógica é uma atualização que a cópia vê.', ok=True),
  C('A weekly full copy, compared with the incremental one', 'Uma cópia completa semanal, comparada com a incremental',
    'Yes: the full copy holds what the source holds.', 'Sim: a cópia completa tem o que a fonte tem.', ok=True),
  C('Reading the database’s log of changes', 'Ler o log de mudanças do banco',
    'Yes: a delete is a change, and the log has it.', 'Sim: uma remoção é uma mudança, e o log a tem.', ok=True),
  C('Running the incremental copy every five minutes instead of every hour', 'Rodar a cópia incremental a cada cinco minutos em vez de a cada hora',
    'More often is still blind: the deleted row is never there to select.', 'Mais vezes continua cego: a linha apagada nunca está lá para ser selecionada.')),
Z('ex-cr9v329y', 'databases', 'easy',
  ('A database built to serve an application’s many small, fast reads and writes is called an ___ database.',
   'Um banco feito para atender as muitas leituras e escritas pequenas e rápidas de uma aplicação se chama banco ___.'),
  ('Online transaction processing.', 'Processamento de transações online, em inglês.'),
  ['OLTP'], ['OLTP']),
# ---- change-data-capture
Q('ex-8cr5vt1v', 'change-data-capture', 'easy',
  ('What does a change data capture reader read?', 'O que um leitor de captura de dados de mudança lê?'),
  ('Not the table.', 'Não é a tabela.'),
  C('The tables, every few seconds, looking for new rows', 'As tabelas, a cada poucos segundos, procurando linhas novas',
    'That is a fast incremental copy, with the same blind spot.', 'Isso é uma cópia incremental rápida, com o mesmo ponto cego.'),
  C('The log the database writes of every change', 'O log que o banco escreve de cada mudança',
    'Right: the record of every change, deletes included.', 'Isso: o registro de cada mudança, remoções inclusive.', ok=True),
  C('The app’s source code, to see which queries it runs', 'O código-fonte do app, para ver que consultas ele roda',
    'CDC reads what the database recorded, not the app’s code.', 'O CDC lê o que o banco registrou, não o código do app.'),
  C('A nightly backup of the whole database', 'Um backup noturno do banco inteiro',
    'A backup is a full copy of state, not a stream of changes.', 'Um backup é uma cópia completa do estado, não um fluxo de mudanças.')),
Q('ex-se5mgttt', 'change-data-capture', 'medium',
  ('Why does trigger-based CDC cost the app more than reading the database’s log?',
   'Por que o CDC com triggers custa mais ao app do que ler o log do banco?'),
  ('Where does a trigger run?', 'Onde um trigger roda?'),
  C('Triggers only work on tables with fewer than a million rows', 'Triggers só funcionam em tabelas com menos de um milhão de linhas',
    'There is no such limit; the cost is per change, not per table size.', 'Não existe esse limite; o custo é por mudança, não pelo tamanho da tabela.'),
  C('Triggers send every change over the network to the data team', 'Triggers mandam cada mudança pela rede para o time de dados',
    'The trigger writes to a table in the same database; the reader comes later.', 'O trigger grava numa tabela do mesmo banco; o leitor vem depois.'),
  C('Each trigger adds a write of its own inside the app’s transaction, on every ride', 'Cada trigger acrescenta uma escrita própria dentro da transação do app, a cada viagem',
    'Right: the log is written anyway, the trigger’s row is not.', 'Isso: o log é escrito de qualquer jeito, a linha do trigger não.', ok=True),
  C('Triggers lock the table until the data team has read the change', 'Triggers travam a tabela até o time de dados ler a mudança',
    'They do not wait for any reader.', 'Eles não esperam leitor nenhum.')),
Q('ex-8yft1yfa', 'change-data-capture', 'hard',
  ('A CDC reader on Roda Livre’s PostgreSQL stops on Friday night and nobody notices until Monday. What is the risk to the app?',
   'Um leitor de CDC no PostgreSQL da Roda Livre para na sexta à noite e ninguém percebe até segunda. Qual o risco para o app?'),
  ('The database keeps something until the reader takes it.', 'O banco guarda algo até o leitor buscar.'),
  C('The app’s tables are locked until the reader returns', 'As tabelas do app ficam travadas até o leitor voltar',
    'Writes go on; it is what they leave behind that piles up.', 'As escritas continuam; o que elas deixam para trás é que se acumula.'),
  C('The weekend’s rides are lost from the database', 'As viagens do fim de semana se perdem do banco',
    'The rides are safe in the tables; the log is what grows.', 'As viagens estão seguras nas tabelas; o que cresce é o log.'),
  C('The log piles up on the primary’s disk until it fills', 'O log se acumula no disco do primário até enchê-lo',
    'Right: the database keeps the log until the reader comes back.', 'Isso: o banco guarda o log para o leitor até ele voltar.', ok=True),
  C('The replicas stop receiving changes along with the reader', 'As réplicas param de receber mudanças junto com o leitor',
    'Replicas follow the log on their own; they are not waiting for the CDC reader.', 'As réplicas seguem o log por conta própria; não esperam o leitor de CDC.')),
Q('ex-met3ynwe', 'change-data-capture', 'medium',
  ('A CDC pipeline is switched on today. How does it get the rides that already existed last year?',
   'Um pipeline de CDC é ligado hoje. Como ele recebe as viagens que já existiam no ano passado?'),
  ('What does the log hold?', 'O que o log guarda?'),
  C('It reads the log back to the day the database was created', 'Lê o log de volta até o dia em que o banco foi criado',
    'The log holds recent changes, not the history of every row.', 'O log guarda mudanças recentes, não a história de cada linha.'),
  C('It starts from one full copy, then follows the log', 'Começa por uma cópia completa e depois segue o log',
    'Right, and follows the log from the moment that copy was taken.', 'Isso, e segue o log a partir do momento dessa cópia.', ok=True),
  C('It asks the app to update every old row so they appear as changes', 'Pede ao app para atualizar cada linha antiga para que apareçam como mudanças',
    'That would touch every row of the app’s tables for the data team’s sake.', 'Isso mexeria em cada linha das tabelas do app por causa do time de dados.'),
  C('It does not need them, because CDC is for new data', 'Não precisa delas, porque CDC é para dado novo',
    'A copy without the old rows answers no question about last year.', 'Uma cópia sem as linhas antigas não responde pergunta nenhuma sobre o ano passado.')),
O('ex-83b0xkww', 'change-data-capture', 'medium',
  ('Put in order what happens to the cancellation of ride `R000104`, from the app to the data team.',
   'Ponha em ordem o que acontece com o cancelamento da viagem `R000104`, do app até o time de dados.'),
  ('The log is written before the table changes.', 'O log é escrito antes de a tabela mudar.'),
  [('the app sends a DELETE', 'o app envia um DELETE'),
   ('the database writes the change to its log', 'o banco escreve a mudança no log'),
   ('the row leaves the rides table', 'a linha sai da tabela de viagens'),
   ('the CDC reader takes the log entry', 'o leitor de CDC pega a entrada do log')],
  ('The reader comes last, and it still sees the delete, because the log keeps it after the row is gone.',
   'O leitor vem por último e ainda vê a remoção, porque o log a guarda depois que a linha sumiu.')),
# ---- apis
Q('ex-a5zbbw8j', 'apis', 'easy',
  ('What does an answer with status `429` ask the client to do?', 'O que uma resposta com status `429` pede ao cliente?'),
  ('Too Many Requests.', 'Too Many Requests.'),
  C('Wait before asking again', 'Esperar antes de pedir de novo',
    'Right: often for the seconds `Retry-After` names.', 'Isso: muitas vezes pelos segundos que o `Retry-After` indica.', ok=True),
  C('Send a new token', 'Mandar um token novo',
    'A wrong token is `401`.', 'Um token errado é `401`.'),
  C('Skip that page', 'Pular aquela página',
    'Skipping would lose its rows without a word.', 'Pular perderia as linhas dela sem aviso.'),
  C('Ask for a bigger page', 'Pedir uma página maior',
    'A bigger page is a heavier request, not a slower one.', 'Uma página maior é uma requisição mais pesada, não mais lenta.')),
Q('ex-9w9dk7ry', 'apis', 'medium',
  ('In `walk.py`, why does the `continue` after a `429` leave `page` unchanged?',
   'No `walk.py`, por que o `continue` depois de um `429` deixa `page` sem mudar?'),
  ('Which page was refused?', 'Que página foi recusada?'),
  C('So the server can reset its request counter', 'Para o servidor poder zerar o contador de requisições',
    'The server counts on its own; the client is not managing it.', 'O servidor conta sozinho; o cliente não cuida disso.'),
  C('Because `page` is read-only inside a `try` block', 'Porque `page` é somente leitura dentro de um bloco `try`',
    'Variables are not read-only in a `try`; this is a choice.', 'Variáveis não são somente leitura num `try`; isso é uma escolha.'),
  C('So the page the server refused is asked for again rather than skipped', 'Para a página que o servidor recusou ser pedida de novo em vez de pulada',
    'Right: moving on would skip its rides and report six.', 'Isso: avançar pularia as viagens dela e relataria seis.', ok=True),
  C('To avoid asking for a page past the last one', 'Para não pedir uma página além da última',
    '`next` being empty is what stops the loop at the end.', 'É o `next` vazio que para o laço no fim.')),
Q('ex-ea9b5gpx', 'apis', 'easy',
  ('Where does `walk.py` take its API token from, and why?', 'De onde o `walk.py` tira o token da API, e por quê?'),
  ('Code is copied and committed.', 'Código é copiado e versionado.'),
  C('A constant at the top of the file, so it is easy to change', 'Uma constante no topo do arquivo, para ser fácil de trocar',
    'A token in code travels with every copy and commit of it.', 'Um token no código viaja com cada cópia e commit dele.'),
  C('The environment, so that it stays out of the code itself', 'O ambiente, para ele ficar fora do código e do git',
    'Right: in production, a secret store does the same job.', 'Isso: em produção, um cofre de segredos faz o mesmo papel.', ok=True),
  C('A file in the git repository, beside the program', 'Um arquivo no repositório git, ao lado do programa',
    'In the repository is exactly where a token is readable by anyone who has it.', 'No repositório é exatamente onde um token fica legível para qualquer um que o tenha.'),
  C('The server sends it on the first request', 'O servidor o envia na primeira requisição',
    'The client proves who it is; the server does not hand out its own key.', 'O cliente prova quem é; o servidor não entrega a própria chave.')),
N('ex-x9gnbfgx', 'apis', 'easy',
  ('How many requests did `walk.py` send to collect the three pages?', 'Quantas requisições o `walk.py` enviou para juntar as três páginas?'),
  ('Count the lines that start with `page`.', 'Conte as linhas que começam com `page`.'),
  4, 0, ('requests', 'requisições')),
Q('ex-vppns6x8', 'apis', 'hard',
  ('An API lists charges newest first, numbered by page. While a client walks the pages, two new charges are made. What happens to the client’s copy?',
   'Uma API lista cobranças da mais nova para a mais antiga, com páginas numeradas. Enquanto um cliente percorre as páginas, duas cobranças novas são feitas. O que acontece com a cópia do cliente?'),
  ('Every older charge moves two places down the list.', 'Toda cobrança mais antiga desce duas posições na lista.'),
  C('Two charges appear twice', 'Duas cobranças aparecem duas vezes',
    'Right: the end of one page slides onto the start of the next. A cursor would not.', 'Isso: o fim de uma página escorrega para o começo da seguinte. Um cursor não deixaria.', ok=True),
  C('The API refuses the walk with an error until it is restarted', 'A API recusa a leitura com erro até ela ser recomeçada',
    'Nothing errors; the pages just shift.', 'Nada dá erro; as páginas só deslocam.'),
  C('The two new charges are added at the end of the last page', 'As duas cobranças novas entram no fim da última página',
    'Newest first puts them on page 1, which the client has already read.', 'Da mais nova para a mais antiga, elas entram na página 1, que o cliente já leu.'),
  C('Nothing changes, because page numbers are fixed when the walk begins', 'Nada muda, porque os números de página são fixados no começo da leitura',
    'A page number is recomputed on every request; that is the problem.', 'Um número de página é recalculado a cada requisição; esse é o problema.')),
# ---- files
Q('ex-9gberdzt', 'files', 'easy',
  ('Why does the export write `manifest.json` last?', 'Por que a exportação escreve o `manifest.json` por último?'),
  ('What does its presence tell the reader?', 'O que a presença dele diz a quem lê?'),
  C('JSON files have to be written after CSV files on Linux', 'No Linux, arquivos JSON têm que ser escritos depois dos CSV',
    'There is no such rule; the order is an agreement between writer and reader.', 'Não existe essa regra; a ordem é um acordo entre quem escreve e quem lê.'),
  C('So its checksum includes its own bytes', 'Para o checksum incluir os próprios bytes',
    'The checksum is of `rides.csv`, not of the manifest.', 'O checksum é do `rides.csv`, não do manifesto.'),
  C('Because the manifest is the smallest file and the quickest to write', 'Porque o manifesto é o arquivo menor e o mais rápido de escrever',
    'Size is irrelevant; order is the signal.', 'O tamanho é irrelevante; a ordem é o sinal.'),
  C('Its presence says the data before it is complete', 'Sua presença diz que os dados anteriores estão completos',
    'Right: a reader touches nothing until it exists.', 'Isso: quem lê não toca em nada até ele existir.', ok=True)),
N('ex-5c91ns9m', 'files', 'easy',
  ('How many rows did the plain `load.py` take from the interrupted export?', 'Quantas linhas o `load.py` simples levou da exportação interrompida?'),
  ('The line after `python load.py`.', 'A linha depois de `python load.py`.'),
  718, 0, ('rows', 'linhas')),
Q('ex-xgg4kqkq', 'files', 'medium',
  ('Why did the plain load of the half-written file print no error?', 'Por que o carregamento simples do arquivo pela metade não mostrou erro?'),
  ('Look at the last row it printed.', 'Olhe a última linha que ele mostrou.'),
  C('Python catches CSV errors and hides them by default', 'O Python captura erros de CSV e os esconde por padrão',
    'There was no error to hide; the reader accepted the line.', 'Não havia erro para esconder; o leitor aceitou a linha.'),
  C('`csv.DictReader` filled the short row with `None`', 'O `csv.DictReader` completou a linha curta com `None`',
    'Right: a half row became a plausible-looking record.', 'Isso: meia linha virou um registro com cara de plausível.', ok=True),
  C('The export wrote a complete last row before it stopped', 'A exportação escreveu uma última linha completa antes de parar',
    'The last row has station `ST`: it was cut in the middle.', 'A última linha tem estação `ST`: foi cortada no meio.'),
  C('The manifest said 718 rows, and the load matched it', 'O manifesto dizia 718 linhas, e o carregamento bateu',
    'There was no manifest; that is why the careful load refused.', 'Não havia manifesto; por isso o carregamento cuidadoso recusou.')),
Q('ex-mzm1fxfk', 'files', 'hard',
  ('A reader polls a bucket and loads any file that has not grown for ten minutes, on the grounds that its writer must have finished. What is wrong with that rule?',
   'Um leitor olha um bucket e carrega qualquer arquivo que não cresce há dez minutos, supondo que quem escrevia terminou. O que há de errado nessa regra?'),
  ('What else stops a file from growing?', 'O que mais faz um arquivo parar de crescer?'),
  C('Ten minutes is too short; an hour would make it safe', 'Dez minutos é pouco; uma hora deixaria seguro',
    'No wait tells a finished writer from a dead one.', 'Nenhuma espera distingue quem terminou de quem morreu.'),
  C('Buckets do not report when a file last changed', 'Buckets não informam quando um arquivo mudou pela última vez',
    'They do; the trouble is what the time means.', 'Informam; o problema é o que o horário significa.'),
  C('A dead writer’s file stops growing too', 'O arquivo de quem morreu também deixa de crescer',
    'Right: only a marker written last says the writer finished.', 'Isso: só um marcador escrito por último diz que quem escrevia terminou.', ok=True),
  C('Polling a bucket costs more than reading a manifest', 'Olhar um bucket custa mais que ler um manifesto',
    'Cost is beside the point; the rule loads half files.', 'O custo não vem ao caso; a regra carrega arquivos pela metade.')),
# ---- logs
Q('ex-z6m98kqf', 'logs', 'easy',
  ('Why is every field `parse_log.py` prints a string, even the status code?',
   'Por que todo campo que o `parse_log.py` mostra é texto, até o código de status?'),
  ('What does a regular expression return?', 'O que uma expressão regular devolve?'),
  C('The log stores numbers as text to save space', 'O log guarda números como texto para economizar espaço',
    'Text is not smaller; a regular expression simply finds text.', 'Texto não é menor; uma expressão regular simplesmente acha texto.'),
  C('A regular expression finds text, and turning it into numbers is a later step', 'Uma expressão regular acha texto, e transformá-lo em número é um passo posterior',
    'Right: converting the types is a separate, later step.', 'Isso: converter os tipos é um passo separado, posterior.', ok=True),
  C('`groupdict` converts numbers back to strings for printing', '`groupdict` converte números de volta para texto para imprimir',
    'It never had numbers to convert.', 'Ele nunca teve números para converter.'),
  C('Status codes like `404` are not really numbers in HTTP', 'Códigos de status como `404` não são números de verdade no HTTP',
    'They are numbers; the parser just has not converted them.', 'Eles são números; o analisador só não os converteu.')),
Q('ex-djzvhc7k', 'logs', 'medium',
  ('Why does `parse_log.py` list the line numbers it could not parse instead of skipping them?',
   'Por que o `parse_log.py` lista os números das linhas que não conseguiu analisar em vez de pulá-las?'),
  ('Think of the day the log format changes.', 'Pense no dia em que o formato do log mudar.'),
  C('To delete them from the log afterwards', 'Para apagá-las do log depois',
    'The source is not edited; the reader reports.', 'A fonte não é editada; quem lê informa.'),
  C('Because Python’s `re` module requires it', 'Porque o módulo `re` do Python exige isso',
    'It requires nothing of the kind; this is a choice.', 'Ele não exige nada disso; é uma escolha.'),
  C('So that a broken format is noticed soon', 'Para que um formato quebrado seja notado logo',
    'Right: a skipping parser would drop every line just as quietly.', 'Isso: um analisador que pula descartaria todas as linhas com o mesmo silêncio.', ok=True),
  C('To count the broken lines as failed requests', 'Para contar as linhas quebradas como requisições que falharam',
    'A cut-off line is not a failed request; its status is unknown.', 'Uma linha cortada não é uma requisição que falhou; o status dela é desconhecido.')),
Q('ex-vpmdn3b5', 'logs', 'medium',
  ('The log has a `500` and then a `200` for `/v1/rides/R000301/end`, two seconds apart. What happened to the customer?',
   'O log tem um `500` e depois um `200` para `/v1/rides/R000301/end`, com dois segundos de diferença. O que aconteceu com o cliente?'),
  ('Read the two lines together.', 'Leia as duas linhas juntas.'),
  C('Two rides were ended, one with an error', 'Duas viagens foram encerradas, uma com erro',
    'Both lines name the same ride, `R000301`.', 'As duas linhas citam a mesma viagem, `R000301`.'),
  C('One ride, which ended when the app retried', 'Uma viagem, encerrada quando o app tentou de novo',
    'Right: one ride, ended two seconds late.', 'Isso: uma viagem, encerrada dois segundos atrasada.', ok=True),
  C('The ride is still open, because a `500` cancels the request', 'A viagem continua aberta, porque um `500` cancela a requisição',
    'The `200` after it says the second attempt worked.', 'O `200` depois dela diz que a segunda tentativa funcionou.'),
  C('Two different customers tried to end the same ride', 'Dois clientes diferentes tentaram encerrar a mesma viagem',
    'Both requests came from one address and one app.', 'As duas requisições vieram de um endereço e de um app.')),
Q('ex-8qrma6q4', 'logs', 'medium',
  ('Why does a web server’s access log count as personal data under the LGPD, though it holds no names?',
   'Por que o log de acesso de um servidor web conta como dado pessoal pela LGPD, mesmo sem nomes?'),
  ('Look at the first field of every line.', 'Olhe o primeiro campo de cada linha.'),
  C('It records every customer’s password in each request', 'Ele registra a senha de cada cliente em cada requisição',
    'The combined format holds no passwords.', 'O formato combined não guarda senhas.'),
  C('The LGPD covers every file a company stores', 'A LGPD cobre todo arquivo que uma empresa guarda',
    'It covers information that relates to a person, not files as such.', 'Ela cobre informação ligada a uma pessoa, não arquivos em si.'),
  C('Its first field is an address that identifies people', 'O primeiro campo é um endereço que identifica pessoas',
    'Right: information that identifies a person is personal data, named or not.', 'Isso: informação que identifica uma pessoa é dado pessoal, com nome ou sem.', ok=True),
  C('The user agent names the customer’s phone owner', 'O user agent dá o nome do dono do celular',
    'It names the app and the system, not the person.', 'Ele dá o nome do app e do sistema, não da pessoa.')),
Z('ex-az6pg51e', 'logs', 'easy',
  ('Writing each line of a log as a JSON object, so the fields arrive already named, is called ___ logging.',
   'Escrever cada linha de um log como objeto JSON, para os campos já chegarem com nome, se chama log ___.'),
  ('The opposite of a sentence for a person.', 'O oposto de uma frase para uma pessoa.'),
  ['structured'], ['estruturado']),
# ---- application-events
Q('ex-j5dsdrar', 'application-events', 'easy',
  ('What do application events record that the app’s database does not?',
   'O que os eventos de aplicação registram que o banco do app não registra?'),
  ('A customer looked at a station and closed the app.', 'Um cliente olhou uma estação e fechou o app.'),
  C('The current state of every ride and bicycle', 'O estado atual de cada viagem e bicicleta',
    'That is what the database keeps.', 'Isso é o que o banco guarda.'),
  C('The passwords customers sign in with', 'As senhas com que os clientes entram',
    'Events are about actions in the app, not credentials.', 'Eventos tratam de ações no app, não de credenciais.'),
  C('Actions that change no row', 'Ações que não mudam linha nenhuma',
    'Right: opening the map, looking, giving up.', 'Isso: abrir o mapa, olhar, desistir.', ok=True),
  C('The charges the payments provider has made', 'As cobranças que o provedor de pagamentos fez',
    'Those are at the provider, read through its API.', 'Elas ficam no provedor, lidas pela API dele.')),
Q('ex-ntwt988a', 'application-events', 'medium',
  ('Why does at-least-once delivery write some events twice?', 'Por que a entrega pelo menos uma vez anota alguns eventos duas vezes?'),
  ('What can the phone not tell apart?', 'O que o celular não consegue distinguir?'),
  C('The collector copies each event to two servers', 'O coletor copia cada evento para dois servidores',
    'Copies for safety are not duplicates in the data.', 'Cópias de segurança não são duplicatas nos dados.'),
  C('To the phone, a lost reply looks like a lost event', 'Para o celular, resposta perdida parece evento perdido',
    'Right: so the phone resends, and the collector already had it.', 'Isso: então o celular reenvia, e o coletor já o tinha.', ok=True),
  C('The app sends each event twice on purpose, as a check', 'O app manda cada evento duas vezes de propósito, como verificação',
    'It sends once and resends only when it hears nothing back.', 'Ele manda uma vez e só reenvia quando não ouve resposta.'),
  C('Two versions of the app are installed on each phone', 'Duas versões do app ficam instaladas em cada celular',
    'One app per phone; the duplicate comes from the network.', 'Um app por celular; a duplicata vem da rede.')),
Q('ex-sm45k04y', 'application-events', 'medium',
  ('Two `ride_started` events from one customer arrive a second apart, with the same `event_id`. What are they?',
   'Dois eventos `ride_started` de um cliente chegam com um segundo de diferença, com o mesmo `event_id`. O que eles são?'),
  ('The phone gave the id when it created the event.', 'O celular deu o id quando criou o evento.'),
  C('Two rides, started a second apart', 'Duas viagens, iniciadas com um segundo de diferença',
    'Two rides would carry two ids.', 'Duas viagens teriam dois ids.'),
  C('A customer who tapped the button twice', 'Um cliente que tocou o botão duas vezes',
    'Each tap creates an event with its own id.', 'Cada toque cria um evento com id próprio.'),
  C('A bug in the collector, to be reported to its vendor', 'Um bug no coletor, a ser relatado ao fornecedor',
    'It is the normal price of at-least-once delivery.', 'É o preço normal da entrega pelo menos uma vez.'),
  C('One event that the phone sent twice, having heard no answer the first time', 'Um evento que o celular mandou duas vezes, por não ouvir resposta da primeira',
    'Right: one id is one event, and the copy is removed.', 'Isso: um id é um evento, e a cópia é removida.', ok=True)),
Q('ex-g88yvmvk', 'application-events', 'hard',
  ('Without a tracking plan, app 3.3 sends `rideStarted` and app 3.4 sends `ride_started`. A dashboard counts `ride_started`. What does it show over the month after 3.4 ships?',
   'Sem plano de rastreamento, o app 3.3 envia `rideStarted` e o 3.4 envia `ride_started`. Um painel conta `ride_started`. O que ele mostra no mês depois que o 3.4 sai?'),
  ('Customers do not all update on the same day.', 'Os clientes não atualizam todos no mesmo dia.'),
  C('A count that is right from the day 3.4 is released', 'Uma contagem certa desde o dia em que o 3.4 sai',
    'Phones still on 3.3 send the other name.', 'Celulares ainda no 3.3 mandam o outro nome.'),
  C('Rides rising as phones update', 'Viagens subindo conforme os celulares atualizam',
    'Right: the growth is in the app version, not in the rides.', 'Isso: o crescimento é da versão do app, não das viagens.', ok=True),
  C('Every ride counted twice, once under each name', 'Toda viagem contada duas vezes, uma em cada nome',
    'Each phone sends one name, and only one is counted.', 'Cada celular manda um nome, e só um é contado.'),
  C('An error, because the dashboard refuses unknown event names', 'Um erro, porque o painel recusa nomes de evento desconhecidos',
    'Unknown names are ignored, not refused; that is the trouble.', 'Nomes desconhecidos são ignorados, não recusados; esse é o problema.')),
M('ex-c0v4syg4', 'application-events', 'medium',
  ('Match each field of an event to what it is for.', 'Associe cada campo de um evento ao que ele serve.'),
  ('One of them is the only defence against duplicates.', 'Um deles é a única defesa contra duplicatas.'),
  [(('`event_id`', '`event_id`'), ('telling a resend from a new event', 'distinguir um reenvio de um evento novo')),
   (('`occurred_at`', '`occurred_at`'), ('the phone’s clock, which the customer controls', 'o relógio do celular, que o cliente controla')),
   (('the collector’s time', 'o horário do coletor'), ('when it arrived, by a clock you trust', 'quando chegou, por um relógio confiável')),
   (('`app_version`', '`app_version`'), ('which build of the app sent it', 'qual versão do app o enviou'))]),
# ---- iot
N('ex-a5cakwek', 'iot', 'easy',
  ('How many readings arrived twice in the hour `docks.py` made?', 'Quantas leituras chegaram duas vezes na hora gerada pelo `docks.py`?'),
  ('The third line of output.', 'A terceira linha da saída.'),
  11, 0, ('readings', 'leituras')),
Q('ex-dmd1j6tv', 'iot', 'medium',
  ('185 readings arrived where 180 were due. Why is that not a sign that the hour is complete?',
   'Chegaram 185 leituras onde eram devidas 180. Por que isso não indica que a hora está completa?'),
  ('Remove the ones that came twice.', 'Tire as que vieram duas vezes.'),
  C('The sensors send extra readings when a bicycle is docked', 'Os sensores mandam leituras extras quando uma bicicleta é encaixada',
    'They send one a minute; the extra ones are resends.', 'Eles mandam uma por minuto; as extras são reenvios.'),
  C('Eleven came twice, which hides six readings that never came at all', 'Onze são repetidas, e elas escondem seis que nunca vieram',
    'Right: 185 minus 11 is 174, six short of 180.', 'Isso: 185 menos 11 dá 174, seis a menos que 180.', ok=True),
  C('The server counts each reading once per sensor and once per station', 'O servidor conta cada leitura uma vez por sensor e uma por estação',
    'There is one count; it includes resends.', 'Há uma contagem só; ela inclui reenvios.'),
  C('Five readings came from a fourth dock that was not in the list', 'Cinco leituras vieram de uma quarta doca que não estava na lista',
    'There are three docks; the surplus is duplicates.', 'São três docas; o excedente é de duplicatas.')),
Q('ex-mhv1ymqm', 'iot', 'medium',
  ('What does a sequence number on each reading make possible?', 'O que um número de sequência em cada leitura torna possível?'),
  ('It goes up by one every reading.', 'Ele sobe um a cada leitura.'),
  C('Correcting the sensor’s clock', 'Corrigir o relógio do sensor',
    'Clocks are corrected with NTP; the number says nothing about time.', 'Relógios se corrigem com NTP; o número não diz nada sobre horário.'),
  C('Counting the gaps and the duplicates', 'Contar as lacunas e as duplicatas',
    'Right: a missing number is a gap, a number seen twice a duplicate.', 'Isso: um número faltando é lacuna, um número visto duas vezes é duplicata.', ok=True),
  C('Sending readings without a network', 'Mandar leituras sem rede',
    'It is a label on the reading, not a way to send it.', 'É um rótulo na leitura, não um jeito de enviá-la.'),
  C('Encrypting the readings on the way', 'Criptografar as leituras no caminho',
    'Numbering is not encryption.', 'Numerar não é criptografar.')),
Q('ex-amv82q77', 'iot', 'hard',
  ('A program keeps, for each dock, whichever reading reached the server most recently, and calls it the dock’s current state. What goes wrong?',
   'Um programa guarda, para cada doca, a leitura que chegou ao servidor por último e a chama de estado atual da doca. O que dá errado?'),
  ('Six readings arrived after a later one.', 'Seis leituras chegaram depois de uma mais recente.'),
  C('Nothing, because readings arrive in the order they were taken', 'Nada, porque as leituras chegam na ordem em que foram feitas',
    'Six of them did not, in one hour of three docks.', 'Seis delas não chegaram, numa hora de três docas.'),
  C('It counts each duplicate as a second bicycle', 'Conta cada duplicata como uma segunda bicicleta',
    'Keeping one reading per dock counts no bicycles twice.', 'Guardar uma leitura por doca não conta bicicleta duas vezes.'),
  C('It crashes when two readings arrive in the same second', 'Quebra quando duas leituras chegam no mesmo segundo',
    'A tie in arrival time is not an error.', 'Um empate no horário de chegada não é erro.'),
  C('An old reading that was delayed replaces a newer one', 'Uma leitura antiga e atrasada substitui uma mais nova',
    'Right: order by sequence number, not by arrival.', 'Isso: ordene pelo número de sequência, não pela chegada.', ok=True)),
Q('ex-fakq83e3', 'iot', 'medium',
  ('57 readings from `ST02-D02` are stamped later than the moment they reached the server. What does that say?',
   '57 leituras da `ST02-D02` têm carimbo posterior ao momento em que chegaram ao servidor. O que isso diz?'),
  ('No reading arrives before it is taken.', 'Nenhuma leitura chega antes de ser feita.'),
  C('The network delivered them faster than light allows', 'A rede as entregou mais rápido do que a luz permite',
    'The network was ordinary; the stamp is wrong.', 'A rede era comum; o carimbo é que está errado.'),
  C('That sensor’s clock runs ahead of the real time', 'O relógio desse sensor está adiantado',
    'Right: by 47 seconds, which moves every empty spell it reports.', 'Isso: 47 segundos, o que desloca cada período vazio que ele informa.', ok=True),
  C('The server’s clock is in UTC and the sensor’s is in São Paulo time', 'O relógio do servidor está em UTC e o do sensor no horário de São Paulo',
    'That would be three hours, not 47 seconds, and on every dock.', 'Isso daria três horas, não 47 segundos, e em todas as docas.'),
  C('Those readings are duplicates and should be removed', 'Essas leituras são duplicatas e devem ser removidas',
    'Duplicates share a sequence number; these do not.', 'Duplicatas têm o mesmo número de sequência; estas não.')),
# ---- asking-the-owner
Q('ex-gf2agn24', 'asking-the-owner', 'medium',
  ('What turns a written list of a source owner’s answers into a data contract?',
   'O que transforma uma lista escrita das respostas do dono de uma fonte num contrato de dados?'),
  ('Look at the `key` and `expected` lines.', 'Olhe as linhas `key` e `expected`.'),
  C('A signature from the company’s legal team', 'Uma assinatura do jurídico da empresa',
    'It is not a legal document.', 'Não é um documento jurídico.'),
  C('Writing it in a standard format such as JSON', 'Escrevê-la num formato padrão como JSON',
    'There is no single standard format; YAML or a wiki page also serve.', 'Não existe formato padrão único; YAML ou uma página de wiki também servem.'),
  C('Both sides agree to it, and a program checks it', 'Os dois lados aceitam, e um programa confere',
    'Right: the checks are what make the promise hold.', 'Isso: as verificações é que fazem a promessa valer.', ok=True),
  C('The data team writes it without the owner, so it stays neutral', 'O time de dados a escreve sem o dono, para ficar neutra',
    'It is the producer’s promise; without the owner it promises nothing.', 'É a promessa de quem produz; sem o dono ela não promete nada.')),
Q('ex-4qpn4n2j', 'asking-the-owner', 'hard',
  ('The sensor vendor refuses to number its readings. What belongs in the dock readings’ contract?',
   'O fornecedor dos sensores se recusa a numerar as leituras. O que vai no contrato das leituras das docas?'),
  ('A contract also records what was not promised.', 'Um contrato também registra o que não foi prometido.'),
  C('The vendor’s refusal, written down as a known gap', 'A recusa do fornecedor, registrada como lacuna conhecida',
    'Right: next year’s engineer finds it written down.', 'Isso: o engenheiro do ano que vem a encontra escrita.', ok=True),
  C('A sequence number the data team adds on arrival', 'Um número de sequência que o time de dados acrescenta na chegada',
    'Numbering on arrival counts what arrived, so it shows no gaps.', 'Numerar na chegada conta o que chegou, então não mostra lacunas.'),
  C('Nothing about numbering, since the vendor would not agree to it', 'Nada sobre numeração, já que o fornecedor não aceitou',
    'Leaving it out is how the next person rediscovers the problem.', 'Deixar de fora é como a próxima pessoa redescobre o problema.'),
  C('A clause that ends the vendor’s contract if a reading goes missing', 'Uma cláusula que encerra o contrato do fornecedor se faltar uma leitura',
    'A data contract records behaviour; it is not a commercial agreement.', 'Um contrato de dados registra comportamento; não é acordo comercial.')),
# ---- drill
O('ex-z0yyt6sh', 'drill', 'medium',
  ('Put the careful loader’s steps in order.', 'Ponha os passos do carregador cuidadoso em ordem.'),
  ('Nothing is parsed until it is known to be whole.', 'Nada é analisado antes de se saber que está inteiro.'),
  [('see that `manifest.json` exists', 'ver que o `manifest.json` existe'),
   ('read the bytes of `rides.csv`', 'ler os bytes do `rides.csv`'),
   ('compare their SHA-256 with the manifest', 'comparar o SHA-256 deles com o do manifesto'),
   ('parse the rows', 'analisar as linhas')],
  ('The checksum can only be compared once the bytes are read, and parsing comes after both checks.',
   'O checksum só se compara depois de ler os bytes, e a análise vem depois das duas verificações.')),
M('ex-m93cnhsf', 'drill', 'medium',
  ('Match each quiet failure to what prevents it.', 'Associe cada falha silenciosa ao que a evita.'),
  ('One remedy per section of the lesson.', 'Um remédio por seção da aula.'),
  [(('a cancelled ride stays in the copy', 'uma viagem cancelada fica na cópia'), ('reading the change log', 'ler o log de mudanças')),
   (('half a file is loaded', 'metade de um arquivo é carregada'), ('a manifest written last', 'um manifesto escrito por último')),
   (('a resent event is counted twice', 'um evento reenviado é contado duas vezes'), ('removing duplicates by `event_id`', 'remover duplicatas pelo `event_id`')),
   (('a refused page is skipped', 'uma página recusada é pulada'), ('waiting and asking for it again', 'esperar e pedir de novo'))]),
Q('ex-3bkse1wq', 'drill', 'hard',
  ('Marta asks how many rides were cancelled in September. The data team has only the incremental copy of the rides table. What does the copy say?',
   'Marta pergunta quantas viagens foram canceladas em setembro. O time de dados só tem a cópia incremental da tabela de viagens. O que a cópia diz?'),
  ('The app deletes cancelled rides.', 'O app apaga as viagens canceladas.'),
  C('The right number, since each cancellation updates `updated_at`', 'O número certo, já que cada cancelamento atualiza `updated_at`',
    'A cancellation here is a delete, and a deleted row updates nothing.', 'Aqui um cancelamento é uma remoção, e uma linha apagada não atualiza nada.'),
  C('Zero, and the cancelled rides look open', 'Zero, e as que foram apagadas parecem abertas',
    'Right: the copy cannot answer, and does not know it cannot.', 'Isso: a cópia não sabe responder, e não sabe que não sabe.', ok=True),
  C('An error, because the cancelled rows are missing', 'Um erro, porque as linhas canceladas estão faltando',
    'Missing rows raise nothing; that is the trouble.', 'Linhas faltando não levantam nada; esse é o problema.'),
  C('Twice the real number, once for the ride and once for the delete', 'O dobro do número real, uma vez pela viagem e outra pela remoção',
    'The copy never receives the delete, so it cannot count it.', 'A cópia nunca recebe a remoção, então não tem como contá-la.')),
Q('ex-j8yeyx43', 'drill', 'hard',
  ('A partner sends payment records with at-least-once delivery and no identifier on each record. Two identical records arrive. What can nobody tell?',
   'Um parceiro manda registros de pagamento com entrega pelo menos uma vez e sem identificador em cada registro. Chegam dois registros idênticos. O que ninguém consegue dizer?'),
  ('Compare with `event_id`.', 'Compare com o `event_id`.'),
  C('Whether either record is a payment at all', 'Se algum dos dois é mesmo um pagamento',
    'The records say what they are; the question is how many.', 'Os registros dizem o que são; a questão é quantos.'),
  C('Which time zone the records were written in', 'Em que fuso os registros foram escritos',
    'Time zone is a separate question for the owner.', 'Fuso é outra pergunta para o dono.'),
  C('Whether the partner’s API has a rate limit', 'Se a API do parceiro tem limite de taxa',
    'Rate limits do not create identical records.', 'Limites de taxa não criam registros idênticos.'),
  C('Whether it is one payment resent or two payments', 'Se é um pagamento reenviado ou dois pagamentos',
    'Right: without an id they look the same, so ask for one first.', 'Isso: sem id eles são iguais, então peça um antes.', ok=True)),
]
