from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
# ---- five-stages
O('ex-3p2qv26a', 'five-stages', 'easy',
  ('Put the stages a ride passes through at Roda Livre in order, from the dock to Marta.',
   'Ponha em ordem as etapas pelas quais uma viagem passa na Roda Livre, da doca até Marta.'),
  ('The lesson’s title lists them in this order.', 'O título da aula as lista nesta ordem.'),
  [('generation', 'geração'), ('ingestion', 'ingestão'), ('storage', 'armazenamento'),
   ('transformation', 'transformação'), ('delivery', 'entrega')],
  ('Reis and Housley list storage second, because data is stored where it is born; this course follows the order a ride is handled in.',
   'Reis e Housley põem o armazenamento em segundo, porque o dado é guardado onde nasce; este curso segue a ordem em que a viagem é tratada.')),
Q('ex-xmnbxtr1', 'five-stages', 'easy',
  ('What is wrong with picturing the lifecycle as a conveyor belt?',
   'O que há de errado em imaginar o ciclo de vida como uma esteira?'),
  ('Think about Monday, Tuesday and a re-run.', 'Pense na segunda, na terça e numa nova execução.'),
  C('A belt has five stations and the lifecycle has four of them', 'Uma esteira tem cinco estações e o ciclo de vida tem quatro delas',
    'The count is not the problem; the lifecycle has five stages.', 'A contagem não é o problema; o ciclo de vida tem cinco etapas.'),
  C('It runs every day, it runs some days twice, and storage sits under every stage rather than in the row', 'Roda todo dia, roda alguns dias duas vezes, e o armazenamento fica embaixo de todas as etapas, e não na fileira',
    'Right: three ways the belt misleads.', 'Isso: três jeitos de a esteira enganar.', ok=True),
  C('A belt moves too slowly to stand for data that arrives each night', 'Uma esteira anda devagar demais para representar dado que chega toda noite',
    'Speed is not what the picture gets wrong.', 'Velocidade não é o que a imagem erra.'),
  C('Data moves right to left in a real pipeline, against the belt', 'Num pipeline real o dado anda da direita para a esquerda, contra a esteira',
    'The direction is fine; the once-only, single pass is not.', 'A direção está certa; o que está errado é a passada única.')),
Q('ex-np49yepe', 'five-stages', 'medium',
  ('Why does the lesson’s figure draw storage underneath the other stages instead of in the row?',
   'Por que a figura da aula desenha o armazenamento embaixo das outras etapas, e não na fileira?'),
  ('Which stages read or write a directory?', 'Que etapas leem ou gravam um diretório?'),
  C('Because it is the cheapest stage, and cheap things go at the bottom', 'Porque é a etapa mais barata, e coisas baratas ficam embaixo',
    'Cost has nothing to do with where it is drawn.', 'Custo não tem a ver com onde ela é desenhada.'),
  C('Because it happens last, after delivery', 'Porque acontece por último, depois da entrega',
    'It happens throughout, not after.', 'Ele acontece o tempo todo, não depois.'),
  C('Because every other stage reads it or writes it', 'Porque todo o resto lê dele ou grava nele',
    'Right: it is the floor under the others.', 'Isso: é o chão embaixo das outras.', ok=True),
  C('Because the undercurrents include it', 'Porque as correntes subjacentes o incluem',
    'Storage is a stage; the undercurrents are security, data management and the rest.', 'Armazenamento é uma etapa; as correntes subjacentes são segurança, gestão de dados e o resto.')),
MC('ex-fm6nbpvc', 'five-stages', 'medium',
  ('Which of these are undercurrents in Reis and Housley’s picture, rather than stages? Choose all that apply.',
   'Quais destas são correntes subjacentes na figura de Reis e Housley, e não etapas? Marque todas as que se aplicam.'),
  ('They apply to every stage at once.', 'Elas valem para todas as etapas ao mesmo tempo.'),
  C('Security', 'Segurança', 'Yes: who may read raw is a question at every stage.', 'Sim: quem lê o bruto é uma pergunta em toda etapa.', ok=True),
  C('Orchestration', 'Orquestração', 'Yes: what runs each program at 02:00.', 'Sim: o que roda cada programa às 02:00.', ok=True),
  C('Ingestion', 'Ingestão', 'No: a ride passes through ingestion; it is a stage.', 'Não: a viagem passa pela ingestão; é uma etapa.'),
  C('Data management', 'Gestão de dados', 'Yes: what the columns mean, everywhere.', 'Sim: o que as colunas significam, em todo lugar.', ok=True),
  C('Transformation', 'Transformação', 'No: it is the stage that cleans, joins and counts.', 'Não: é a etapa que limpa, junta e conta.')),
Q('ex-zsmzh4a0', 'five-stages', 'easy',
  ('What do Reis and Housley call the stage this course calls delivery?',
   'Como Reis e Housley chamam a etapa que este curso chama de entrega?'),
  ('It is one English word.', 'É uma palavra em inglês.'),
  C('Reporting', 'Reporting', 'A report is one form of delivery, not the stage’s name.', 'Um relatório é uma forma de entrega, não o nome da etapa.'),
  C('Serving', 'Serving', 'Right.', 'Isso.', ok=True),
  C('Publishing', 'Publishing', 'Not their word for it.', 'Não é a palavra deles.'),
  C('Consumption', 'Consumption', 'Not their word; it names the reader’s side.', 'Não é a palavra deles; ela nomeia o lado de quem lê.')),
# ---- generation
Q('ex-nkf8aktm', 'generation', 'easy',
  ('Why does the app’s rides table hold a price but no count of rides per station?',
   'Por que a tabela de viagens do aplicativo guarda o preço mas nenhuma contagem por estação?'),
  ('What was the app built to do?', 'Para que o aplicativo foi feito?'),
  C('It was built to charge customers for rides, and a count per station charges nobody', 'Ele foi feito para cobrar os clientes, e um número assim não serve para cobrar ninguém',
    'Right: it holds what charging needs, nothing a report alone would want.', 'Isso: ele guarda o que a cobrança precisa, nada que só um relatório quisesse.', ok=True),
  C('Counting per station would be too slow for a database to do', 'Contar por estação seria lento demais para um banco fazer',
    'A database counts quickly; it was simply never asked to.', 'Um banco conta rápido; só nunca pediram isso a ele.'),
  C('The LGPD forbids storing counts in an operational system', 'A LGPD proíbe guardar contagens num sistema operacional',
    'A count is not personal data, and the law says nothing of the kind.', 'Uma contagem não é dado pessoal, e a lei não diz nada disso.'),
  C('The data team asked the app team to leave counts out', 'O time de dados pediu ao time do aplicativo que deixasse as contagens de fora',
    'Nobody asked; the shape comes from the app’s own job.', 'Ninguém pediu; o formato vem do próprio trabalho do aplicativo.')),
Q('ex-f1bskyaj', 'generation', 'medium',
  ('A customer changes their e-mail in the app. What happens to the old address in the app’s database?',
   'Um cliente troca de e-mail no aplicativo. O que acontece com o endereço antigo no banco do aplicativo?'),
  ('Operational systems keep the present.', 'Sistemas operacionais guardam o presente.'),
  C('It moves to a history table the app keeps for analysts', 'Vai para uma tabela de histórico que o aplicativo mantém para analistas',
    'Nothing in the section says the app keeps history; it updates in place.', 'Nada na seção diz que o aplicativo guarda histórico; ele atualiza no lugar.'),
  C('It is overwritten by the new one, and the app keeps no record of what it was', 'É sobrescrito pelo novo, e o aplicativo não guarda registro de como era',
    'Right: unless a copy was taken first, it is gone.', 'Isso: se ninguém tirou uma cópia antes, ele se foi.', ok=True),
  C('It stays beside the new one, marked as old', 'Fica ao lado do novo, marcado como antigo',
    'That is what a history would do, and the app is not one.', 'Isso é o que um histórico faria, e o aplicativo não é um.'),
  C('It is sent to the raw zone automatically', 'É mandado para a zona bruta automaticamente',
    'Raw holds only what ingestion copied, when it copied it.', 'O bruto guarda só o que a ingestão copiou, quando copiou.')),
Q('ex-4xkyeea6', 'generation', 'medium',
  ('The app writes `started_at` as `2025-09-15 06:01`. What does every later reader need to know that the value does not say?',
   'O aplicativo grava `started_at` como `2025-09-15 06:01`. O que todo leitor seguinte precisa saber que o valor não diz?'),
  ('Lesson 1 had a Wednesday with 27 hours.', 'A aula 1 teve uma quarta-feira de 27 horas.'),
  C('The second the ride started, which was rounded away', 'O segundo em que a viagem começou, que foi arredondado',
    'Seconds would add precision, not meaning.', 'Os segundos dariam precisão, não significado.'),
  C('Which bicycle it was, since the value alone cannot say', 'Qual era a bicicleta, já que o valor sozinho não diz',
    'That is in another column, `bike_id`.', 'Isso está em outra coluna, `bike_id`.'),
  C('The date format, since it could be day-first', 'O formato da data, já que ela poderia vir com o dia primeiro',
    'The format is unambiguous here: year, month, day.', 'O formato aqui não é ambíguo: ano, mês, dia.'),
  C('The time zone the app wrote it in', 'O fuso horário em que o aplicativo o gravou',
    'Right: it is Curitiba’s clock, and nothing in the value says so.', 'Isso: é o relógio de Curitiba, e nada no valor diz isso.', ok=True)),
Q('ex-5rma6da7', 'generation', 'hard',
  ('The dock sensors keep two days of readings. The nightly copy fails on Friday and nobody notices until Tuesday. What is lost?',
   'Os sensores das docas guardam dois dias de leituras. A cópia noturna falha na sexta e ninguém percebe até terça. O que se perde?'),
  ('Count which days the sensors still hold on Tuesday.', 'Conte que dias os sensores ainda guardam na terça.'),
  C('Nothing, since the next successful copy brings the missed days along', 'Nada, já que a próxima cópia bem-sucedida traz os dias perdidos junto',
    'The next copy can only take what the source still has.', 'A próxima cópia só leva o que a origem ainda tem.'),
  C('Friday’s readings and whatever else fell outside the two days', 'As leituras de sexta e o que mais saiu dos dois dias',
    'Right: the first copy was the only history, and it was not taken.', 'Isso: a primeira cópia era a única história, e ela não foi tirada.', ok=True),
  C('Only the copy’s log, which says it failed', 'Só o log da cópia, que diz que ela falhou',
    'The log survives; the readings are what is gone.', 'O log sobrevive; as leituras é que se foram.'),
  C('Tuesday’s readings, because the copy is a day behind', 'As leituras de terça, porque a cópia está um dia atrasada',
    'Tuesday is still on the sensors’ server.', 'A terça ainda está no servidor dos sensores.')),
# ---- ingestion
Q('ex-9vtk622g', 'ingestion', 'easy',
  ('A row in the source looks wrong. What does ingestion do with it?',
   'Uma linha na origem parece errada. O que a ingestão faz com ela?'),
  ('The copy is the evidence.', 'A cópia é a prova.'),
  C('Fixes it on the way in, so that the warehouse receives clean rows from day one', 'Corrige no caminho, para o warehouse receber linhas limpas desde o primeiro dia',
    'Fixing is a later stage’s job, done where it can be undone.', 'Corrigir é trabalho de uma etapa posterior, feito onde dá para desfazer.'),
  C('Skips it and writes a warning to the log', 'Pula a linha e escreve um aviso no log',
    'Skipping it changes the evidence of what the source said.', 'Pular muda a prova do que a origem disse.'),
  C('Copies it as it is, and leaves the judging to a later stage', 'Copia como está, e deixa o julgamento para uma etapa posterior',
    'Right: decide what is wrong later, on a copy.', 'Isso: decidir o que está errado vem depois, numa cópia.', ok=True),
  C('Asks the app team to fix the source first', 'Pede ao time do aplicativo que corrija a origem primeiro',
    'Worth telling them, but the copy still takes what is there.', 'Vale avisar, mas a cópia leva o que está lá.')),
Q('ex-ppvmpp1b', 'ingestion', 'easy',
  ('Why does `ingest.py` open `app.db` with `mode=ro`?',
   'Por que o `ingest.py` abre o `app.db` com `mode=ro`?'),
  ('`ro` stands for two words.', '`ro` é a sigla de duas palavras.'),
  C('It makes the reading faster', 'Deixa a leitura mais rápida',
    'Speed is not the reason given.', 'Velocidade não é o motivo dado.'),
  C('So it cannot change the source', 'Para não conseguir mudar a origem',
    'Right: read-only, even by mistake.', 'Isso: só leitura, nem por engano.', ok=True),
  C('SQLite requires it when two programs share one file', 'O SQLite exige isso quando dois programas dividem um arquivo',
    'SQLite allows several readers without it.', 'O SQLite permite vários leitores sem isso.'),
  C('It returns rows as dictionaries', 'Devolve as linhas como dicionários',
    'That is `row_factory`, on the next line.', 'Isso é o `row_factory`, na linha seguinte.')),
M('ex-q3ywa8xx', 'ingestion', 'medium',
  ('Match each Roda Livre source to how its data reaches the data team.',
   'Associe cada origem da Roda Livre ao jeito como o dado dela chega ao time de dados.'),
  ('Who starts the copy, and how much does it take?', 'Quem começa a cópia, e quanto ela leva?'),
  [(('the rides table', 'a tabela de viagens'), ('pulled, one day at a time', 'puxada, um dia por vez')),
   (('the stations table', 'a tabela de estações'), ('pulled whole, every night', 'puxada inteira, toda noite')),
   (('the dock sensors', 'os sensores das docas'), ('pushed, reading by reading', 'empurrados, leitura a leitura')),
   (('the payments provider', 'o provedor de pagamentos'), ('pushed, a call per charge', 'empurrado, uma chamada por cobrança'))]),
Q('ex-fjza0w09', 'ingestion', 'medium',
  ('Why is the stations table copied whole every night while the rides table is copied one day at a time?',
   'Por que a tabela de estações é copiada inteira toda noite enquanto a de viagens é copiada um dia por vez?'),
  ('Compare twelve rows with millions.', 'Compare doze linhas com milhões.'),
  C('Stations are personal data, so they must be refreshed daily', 'Estações são dado pessoal, então precisam ser atualizadas diariamente',
    'Station names are not personal data.', 'Nomes de estação não são dado pessoal.'),
  C('Rides cannot be copied whole, because SQLite refuses large reads', 'Viagens não dão para copiar inteiras, porque o SQLite recusa leituras grandes',
    'It would read them; it would just copy the same rides again and again.', 'Ele as leria; só copiaria as mesmas viagens de novo e de novo.'),
  C('Twelve rows cost nothing to copy; millions do', 'Doze linhas não custam nada; milhões custam',
    'Right: full where it is cheap and never misses a change, incremental where it is not.', 'Isso: completa onde é barato e nunca perde mudança, incremental onde não é.', ok=True),
  C('The app deletes old rides each night, so only a day is left', 'O aplicativo apaga as viagens antigas toda noite, então só sobra um dia',
    'The app keeps its rides; the copy chooses to take one day.', 'O aplicativo guarda as viagens; a cópia é que escolhe levar um dia.')),
Q('ex-h3m98c9f', 'ingestion', 'hard',
  ('A ride that started on Monday is refunded on Wednesday, and the app sets its price to zero. What does the day-by-day ingestion of this lesson copy?',
   'Uma viagem que começou na segunda é estornada na quarta, e o aplicativo zera o preço. O que a ingestão dia a dia desta aula copia?'),
  ('Which day does `ingest.py` select, and by which column?', 'Que dia o `ingest.py` seleciona, e por qual coluna?'),
  C('The refund, in Wednesday’s partition, since the row changed then', 'O estorno, na partição de quarta, já que a linha mudou nesse dia',
    'It selects by `started_at`, and the ride started on Monday.', 'Ele seleciona por `started_at`, e a viagem começou na segunda.'),
  C('Both prices, side by side, in Monday’s partition', 'Os dois preços, lado a lado, na partição de segunda',
    'A day is copied once; nothing goes back to add the new price.', 'Um dia é copiado uma vez; nada volta para acrescentar o preço novo.'),
  C('The original price, and it misses the refund', 'O preço original, e perde o estorno',
    'Right: not new by date, so missed. Lesson 7 is about that.', 'Isso: não é nova pela data, então se perde. A aula 7 trata disso.', ok=True),
  C('An error, because a row changed after it was copied', 'Um erro, porque uma linha mudou depois de copiada',
    'Nothing notices; that is the trouble.', 'Nada percebe; esse é o problema.')),
# ---- storage
Q('ex-qwbeaj53', 'storage', 'easy',
  ('Which zone is the only one that cannot be rebuilt?',
   'Qual zona é a única que não dá para reconstruir?'),
  ('The others are the output of programs.', 'As outras são saída de programas.'),
  C('Curated, because people read it', 'A curada, porque pessoas a leem',
    'It is rebuilt from cleaned by running the transformation again.', 'Ela é reconstruída a partir da limpa rodando a transformação de novo.'),
  C('Raw, a copy of what the source said that day', 'A bruta, cópia do que a origem disse no dia',
    'Right: it is the output of a moment that has passed.', 'Isso: ela é a saída de um momento que passou.', ok=True),
  C('Cleaned, because its rules have changed since', 'A limpa, porque as regras mudaram desde então',
    'Changed rules are exactly why it gets rebuilt.', 'Regras mudadas são justamente o motivo de reconstruí-la.'),
  C('None: every zone is the output of a program', 'Nenhuma: toda zona é saída de um programa',
    'Raw is the output of a copy at a moment the source has moved past.', 'A bruta é a saída de uma cópia num momento que a origem já deixou para trás.')),
Q('ex-7nj5jmth', 'storage', 'medium',
  ('Marta decides a false start is under one minute, not two. With the raw zone kept, what is the fix?',
   'Marta decide que partida falsa é menos de um minuto, não dois. Com a zona bruta guardada, qual é a correção?'),
  ('Which zone still holds the rides between one and two minutes?', 'Que zona ainda tem as viagens entre um e dois minutos?'),
  C('Edit the curated counts by hand for the past months', 'Editar as contagens curadas à mão nos meses passados',
    'Hand edits are how two numbers for one question begin.', 'Edições à mão são como começam dois números para uma pergunta.'),
  C('Change the one number in the transformation and run it again over every day since the beginning', 'Mudar o número na transformação e rodá-la de novo sobre todos os dias desde o começo',
    'Right: raw still holds every ride, so the zones come out as if the rule had always been one.', 'Isso: o bruto ainda tem todas as viagens, então as zonas saem como se a regra sempre tivesse sido um.', ok=True),
  C('Ask the app for the dropped rides and add them to clean', 'Pedir ao aplicativo as viagens descartadas e somá-las à limpa',
    'Raw already holds them; the app may have changed them since.', 'O bruto já as tem; o aplicativo talvez as tenha mudado desde então.'),
  C('Apply the new rule from today and leave the past as it is', 'Aplicar a regra nova a partir de hoje e deixar o passado como está',
    'Then this week and last week count different things.', 'Aí esta semana e a passada contam coisas diferentes.')),
Z('ex-n6wvzv10', 'storage', 'easy',
  ('In the names Databricks made popular, the raw zone is called ___.', 'Nos nomes que a Databricks popularizou, a zona bruta se chama ___.'),
  ('The cheapest of the three metals.', 'O mais barato dos três metais.'),
  ['bronze'], ['bronze']),
Q('ex-1dy6tjg2', 'storage', 'medium',
  ('What does the directory name `date=2025-09-15` make easy?',
   'O que o nome de diretório `date=2025-09-15` facilita?'),
  ('It is called partitioning.', 'Isso se chama particionar.'),
  C('Sorting the rides by time inside the file', 'Ordenar as viagens por horário dentro do arquivo',
    'The directory says nothing about order inside a file.', 'O diretório não diz nada sobre ordem dentro do arquivo.'),
  C('Compressing the day so it takes less disk', 'Comprimir o dia para ocupar menos disco',
    'Compression is a format question, lesson 6.', 'Compressão é uma questão de formato, aula 6.'),
  C('Finding or replacing one day alone', 'Achar ou substituir um dia sozinho',
    'Right: a tool skips the other days, and a re-run replaces one directory.', 'Isso: uma ferramenta pula os outros dias, e uma nova execução substitui um diretório.', ok=True),
  C('Spreading the day over several machines', 'Espalhar o dia por várias máquinas',
    'That is the larger meaning of the word, in lesson 9.', 'Esse é o sentido maior da palavra, na aula 9.')),
MC('ex-j01wpzqm', 'storage', 'medium',
  ('Which of these are rules for the raw zone? Choose all that apply.',
   'Quais destas são regras da zona bruta? Marque todas as que se aplicam.'),
  ('Three were listed.', 'Foram listadas três.'),
  C('Ingestion is the one stage that writes to it', 'A ingestão é a única etapa que grava nela',
    'Yes.', 'Sim.', ok=True),
  C('A row in it is never patched by hand', 'Uma linha dela nunca é remendada à mão',
    'Yes: a whole day is replaced by copying it again.', 'Sim: um dia inteiro é substituído copiando de novo.', ok=True),
  C('It is kept for ever, whatever it holds', 'Ela é guardada para sempre, seja o que for',
    'No: as long as somebody may need to rebuild, and personal data is a reason not to keep it longer.', 'Não: enquanto alguém precisar reconstruir, e dado pessoal é motivo para não guardar mais.'),
  C('Delivery reads from it directly', 'A entrega lê dela diretamente',
    'No: delivery reads curated.', 'Não: a entrega lê o curado.'),
  C('It is kept as long as a rebuild needs it', 'É guardada enquanto uma reconstrução precisar dela',
    'Yes.', 'Sim.', ok=True)),
# ---- transformation
M('ex-gts32cwr', 'transformation', 'easy',
  ('Match each operation in `transform.py` to what it does there.',
   'Associe cada operação do `transform.py` ao que ela faz lá.'),
  ('Three operations, three lines of the program.', 'Três operações, três linhas do programa.'),
  [(('clean', 'limpar'), ('drop rides under 2 minutes', 'tirar viagens de menos de 2 minutos')),
   (('join', 'juntar'), ('give each ride its station’s name', 'dar a cada viagem o nome da estação')),
   (('aggregate', 'agregar'), ('one row per station', 'uma linha por estação'))]),
Q('ex-kam5cd0c', 'transformation', 'medium',
  ('"A ride under 2 minutes is a false start." What kind of statement is that?',
   '"Uma viagem de menos de 2 minutos é uma partida falsa." Que tipo de afirmação é essa?'),
  ('Would a different number be wrong, or just different?', 'Outro número estaria errado, ou só seria diferente?'),
  C('A fact measured from the dock sensors', 'Um fato medido pelos sensores das docas',
    'The sensors measure docks; nobody measured where a false start ends.', 'Os sensores medem docas; ninguém mediu onde termina uma partida falsa.'),
  C('A decision Marta and the team made, written down in code', 'Uma decisão de Marta e do time, escrita em código',
    'Right: another threshold gives another report.', 'Isso: outro limite dá outro relatório.', ok=True),
  C('A limit imposed by SQLite’s integer type', 'Um limite imposto pelo tipo inteiro do SQLite',
    'The type stores 0 and 1 happily.', 'O tipo guarda 0 e 1 sem problema.'),
  C('A rule the app enforces before it writes the ride to its database', 'Uma regra que o aplicativo impõe antes de gravar a viagem no banco',
    'The app writes rides of 0 and 1 minutes; the transformation drops them.', 'O aplicativo grava viagens de 0 e 1 minuto; a transformação é que as tira.')),
Q('ex-ph6ykbpt', 'transformation', 'medium',
  ('What is the difference between ETL and ELT?', 'Qual é a diferença entre ETL e ELT?'),
  ('Look at where the T sits in each name.', 'Veja onde o T fica em cada nome.'),
  C('ELT transforms less, because the warehouse does the cleaning by itself', 'O ELT transforma menos, porque o warehouse faz a limpeza sozinho',
    'Both transform the same amount.', 'Os dois transformam a mesma quantidade.'),
  C('ETL is for files and ELT is for databases', 'ETL é para arquivos e ELT é para bancos',
    'Both handle both.', 'Os dois lidam com os dois.'),
  C('Where the T runs, and whether raw is kept', 'Onde o T roda, e se o bruto fica',
    'Right.', 'Isso.', ok=True),
  C('ETL is the older name for exactly the same process', 'ETL é o nome antigo de exatamente o mesmo processo',
    'The order changed, and with it whether raw rows stay in the warehouse.', 'A ordem mudou, e com ela se as linhas brutas ficam no warehouse.')),
Q('ex-y9gkfa2t', 'transformation', 'hard',
  ('A company must not store customers’ phone numbers, but runs ELT for everything else. Where does the phone number go?',
   'Uma empresa não pode guardar o telefone dos clientes, mas usa ELT para todo o resto. Para onde vai o telefone?'),
  ('In ELT, raw rows land in the warehouse first.', 'No ELT, as linhas brutas pousam primeiro no warehouse.'),
  C('Into the raw zone, to be deleted the next night', 'Para a zona bruta, para ser apagado na noite seguinte',
    'Then it was stored, for a night, which is what was forbidden.', 'Aí ele foi guardado, por uma noite, que é o que era proibido.'),
  C('It is removed by a transformation on the way in, before anything is stored', 'É removido por uma transformação na entrada, antes de qualquer coisa ser guardada',
    'Right: a transformation on the way in, which is ETL for that column.', 'Isso: uma transformação na entrada, que é ETL para essa coluna.', ok=True),
  C('Into the curated zone, where analysts are trusted with it', 'Para a zona curada, onde os analistas são de confiança',
    'Curated is built from raw, so it was stored first.', 'O curado é feito a partir do bruto, então foi guardado antes.'),
  C('Into the warehouse, and hidden from every report', 'Para o warehouse, escondido de todo relatório',
    'Hidden is still stored.', 'Escondido continua guardado.')),
Q('ex-x4v7bsnh', 'transformation', 'medium',
  ('Why does `transform.py` open its output files with `"w"`?',
   'Por que o `transform.py` abre os arquivos de saída com `"w"`?'),
  ('What happens when it runs a second time?', 'O que acontece quando ele roda uma segunda vez?'),
  C('Because `"a"` is not allowed for CSV files', 'Porque `"a"` não é permitido para arquivos CSV',
    'Python appends to a CSV file without complaint.', 'O Python acrescenta a um CSV sem reclamar.'),
  C('So a second run writes the same files again', 'Para uma segunda execução gravar os mesmos arquivos de novo',
    'Right: same raw in, same files out.', 'Isso: mesmo bruto na entrada, mesmos arquivos na saída.', ok=True),
  C('To make the files smaller than appending would', 'Para os arquivos ficarem menores do que acrescentando',
    'The first run writes the same bytes either way.', 'A primeira execução grava os mesmos bytes de um jeito ou de outro.'),
  C('Because `"w"` checks the rows for duplicates as it writes', 'Porque o `"w"` confere as linhas em busca de duplicatas enquanto grava',
    'It checks nothing; it empties the file first.', 'Ele não confere nada; esvazia o arquivo antes.')),
# ---- delivery
M('ex-zwv276xg', 'delivery', 'easy',
  ('Match each form of delivery to who or what reads it at Roda Livre.',
   'Associe cada forma de entrega a quem ou o que a lê na Roda Livre.'),
  ('Not every reader is a person.', 'Nem todo leitor é uma pessoa.'),
  [(('a report', 'um relatório'), ('Marta, each morning', 'Marta, toda manhã')),
   (('a feature table', 'uma tabela de atributos'), ('Caio’s model', 'o modelo de Caio')),
   (('reverse ETL', 'ETL reverso'), ('the van drivers’ app', 'o aplicativo dos motoristas da van')),
   (('an API', 'uma API'), ('the app, on request', 'o aplicativo, quando pede'))]),
Q('ex-cyyprffd', 'delivery', 'medium',
  ('What makes reverse ETL "reverse"?', 'O que torna o ETL reverso "reverso"?'),
  ('Compare its direction with ingestion’s.', 'Compare a direção dele com a da ingestão.'),
  C('It reads the warehouse backwards, newest rows first', 'Ele lê o warehouse de trás para a frente, linhas novas primeiro',
    'Order of reading is not the point.', 'A ordem de leitura não é a questão.'),
  C('It undoes a transformation that went wrong', 'Ele desfaz uma transformação que deu errado',
    'That would be a re-run from raw.', 'Isso seria rodar de novo a partir do bruto.'),
  C('Curated data goes back into an operational tool', 'O dado curado volta para uma ferramenta operacional',
    'Right: the opposite direction to ingestion.', 'Isso: a direção oposta à da ingestão.', ok=True),
  C('It loads first and transforms afterwards', 'Ele carrega primeiro e transforma depois',
    'That is ELT, a different reordering.', 'Isso é ELT, outra troca de ordem.')),
Q('ex-490em7s5', 'delivery', 'medium',
  ('The dashboard counts rides from raw and the report counts them from curated. What does Marta see?',
   'O painel conta viagens a partir do bruto e o relatório a partir do curado. O que Marta vê?'),
  ('What does curated leave out that raw has?', 'O que o curado deixa de fora que o bruto tem?'),
  C('The same number twice, so nothing is wrong', 'O mesmo número duas vezes, então nada está errado',
    'Raw still holds the false starts.', 'O bruto ainda tem as partidas falsas.'),
  C('A bigger total on one screen than on the other, false starts and all', 'Um total maior numa tela do que na outra, com partidas falsas e tudo',
    'Right: two numbers for one question.', 'Isso: dois números para uma pergunta.', ok=True),
  C('An error on the dashboard, because raw is not readable', 'Um erro no painel, porque o bruto não é legível',
    'Raw is plain JSON Lines; it reads fine, and that is the trouble.', 'O bruto é JSON Lines simples; lê sem problema, e esse é o problema.'),
  C('A lower dashboard, because raw is a day behind', 'Um painel menor, porque o bruto está um dia atrasado',
    'Raw is written first, so it is never behind curated.', 'O bruto é gravado primeiro, então não fica atrás do curado.')),
Q('ex-kzfs102v', 'delivery', 'hard',
  ('The data team changes the false-start rule and tells nobody. The report arrives on time. Which promise was broken?',
   'O time de dados muda a regra da partida falsa e não avisa ninguém. O relatório chega na hora. Que promessa foi quebrada?'),
  ('The report promises two things.', 'O relatório promete duas coisas.'),
  C('None, because the report arrived by eight', 'Nenhuma, porque o relatório chegou até as oito',
    'Being on time is only one of the two promises.', 'Chegar na hora é uma das duas promessas.'),
  C('Freshness, because the old rule is stale', 'Atualidade, porque a regra antiga ficou velha',
    'Freshness is about when it arrives.', 'Atualidade é sobre quando ele chega.'),
  C('That "rides" means what it meant last week', 'Que "viagens" quer dizer o que queria semana passada',
    'Right: Marta compares two weeks and reads a difference the pipeline made up.', 'Isso: Marta compara duas semanas e lê uma diferença que o pipeline inventou.', ok=True),
  C('Privacy, because a rule about people changed', 'Privacidade, porque mudou uma regra sobre pessoas',
    'The rule is about ride length, not about people.', 'A regra é sobre duração de viagem, não sobre pessoas.')),
# ---- a-pipeline-you-can-read
N('ex-37a2djzj', 'a-pipeline-you-can-read', 'easy',
  ('How many rides did `ingest.py` copy for 2025-09-15?', 'Quantas viagens o `ingest.py` copiou para 2025-09-15?'),
  ('The first line it prints.', 'A primeira linha que ele imprime.'),
  187, 0, ('rides', 'viagens')),
N('ex-a8f6cs01', 'a-pipeline-you-can-read', 'easy',
  ('How many rides did `transform.py` drop as false starts on the first run?',
   'Quantas viagens o `transform.py` descartou como partidas falsas na primeira execução?'),
  ('raw minus kept.', 'bruto menos mantidas.'),
  11, 0, ('rides', 'viagens')),
Q('ex-pxg840q9', 'a-pipeline-you-can-read', 'medium',
  ('Which file does `report.py` read?', 'Que arquivo o `report.py` lê?'),
  ('Delivery reads one zone.', 'A entrega lê uma zona.'),
  C('`app.db`, to have the newest rides', '`app.db`, para ter as viagens mais novas',
    'Delivery never asks the source.', 'A entrega não consulta a origem.'),
  C('`raw/date=2025-09-15/rides.jsonl`', '`raw/date=2025-09-15/rides.jsonl`',
    'Raw still has the false starts in it.', 'O bruto ainda tem as partidas falsas.'),
  C('`curated/date=2025-09-15/rides_per_station.csv`', '`curated/date=2025-09-15/rides_per_station.csv`',
    'Right: the curated zone and nothing else.', 'Isso: a zona curada e mais nada.', ok=True),
  C('`clean/date=2025-09-15/rides.jsonl`', '`clean/date=2025-09-15/rides.jsonl`',
    'Clean has rides; the report wants counts, which curated holds.', 'O limpo tem viagens; o relatório quer contagens, que estão no curado.')),
Q('ex-1r0tt406', 'a-pipeline-you-can-read', 'medium',
  ('What makes this pipeline "readable" when the report looks wrong?',
   'O que torna este pipeline "legível" quando o relatório parece errado?'),
  ('Where does each stage write?', 'Onde cada etapa grava?'),
  C('Each stage’s output is a plain file on disk', 'A saída de cada etapa é um arquivo comum no disco',
    'Right: "which stage?" has an answer in a text editor.', 'Isso: "qual etapa?" tem resposta num editor de texto.', ok=True),
  C('The programs print a log line for each ride they handle', 'Os programas imprimem uma linha de log para cada viagem que tratam',
    'They print one summary line each.', 'Eles imprimem uma linha de resumo cada.'),
  C('Every program is written in one file of under ten lines', 'Cada programa é escrito num arquivo de menos de dez linhas',
    'They are under forty, and length is not the point.', 'Eles têm menos de quarenta, e tamanho não é a questão.'),
  C('The report prints which stage produced each of its numbers', 'O relatório imprime que etapa produziu cada número dele',
    'It prints counts; tracing them is section 10’s job.', 'Ele imprime contagens; rastreá-las é trabalho da seção 10.')),
# ---- run-it-twice
N('ex-12bvvc6d', 'run-it-twice', 'easy',
  ('After `ingest.py` ran a second time, how many lines did `raw/date=2025-09-15/rides.jsonl` hold?',
   'Depois que o `ingest.py` rodou uma segunda vez, quantas linhas o `raw/date=2025-09-15/rides.jsonl` tinha?'),
  ('`wc -l`.', '`wc -l`.'),
  374, 0, ('lines', 'linhas')),
Z('ex-af1yepq7', 'run-it-twice', 'easy',
  ('A step that gives the same result however many times it runs is called ___.',
   'Um passo que dá o mesmo resultado não importa quantas vezes rode se chama ___.'),
  ('A long word from mathematics.', 'Uma palavra comprida da matemática.'),
  ['idempotent'], ['idempotente']),
Q('ex-14m8q4fx', 'run-it-twice', 'medium',
  ('The second `ingest.py` run doubled the report. Which program was at fault?',
   'A segunda execução do `ingest.py` dobrou o relatório. Que programa tinha o defeito?'),
  ('Which one added to a file instead of replacing it?', 'Qual acrescentou a um arquivo em vez de substituí-lo?'),
  C('`transform.py`, which counted every row it was given without checking for repeats', '`transform.py`, que contou cada linha que recebeu sem procurar as repetidas',
    'It overwrote its output and counted faithfully what raw said.', 'Ele sobrescreveu a saída e contou fielmente o que o bruto dizia.'),
  C('`report.py`, which summed the counts', '`report.py`, que somou as contagens',
    'It read a curated file that was already doubled.', 'Ele leu um arquivo curado que já vinha dobrado.'),
  C('`ingest.py`, which opened raw with `"a"` and appended the day to itself', '`ingest.py`, que abriu o bruto com `"a"` e acrescentou o dia a ele mesmo',
    'Right: `"a"` appended Monday to Monday.', 'Isso: o `"a"` acrescentou a segunda à segunda.', ok=True),
  C('`app.py`, which generated the rides twice', '`app.py`, que gerou as viagens duas vezes',
    'It ran once; the app had 187 rides that day throughout.', 'Ele rodou uma vez; o aplicativo teve 187 viagens naquele dia o tempo todo.')),
Q('ex-tw1egwpn', 'run-it-twice', 'hard',
  ('Why did the station names come out right even though `stations.jsonl` held every station twice?',
   'Por que os nomes das estações saíram certos mesmo com o `stations.jsonl` tendo cada estação duas vezes?'),
  ('How does `transform.py` store the names?', 'Como o `transform.py` guarda os nomes?'),
  C('The second copy of each station was identical, so Python ignored it', 'A segunda cópia de cada estação era idêntica, então o Python a ignorou',
    'Python ignores nothing; the dictionary kept one value per key.', 'O Python não ignora nada; o dicionário guardou um valor por chave.'),
  C('`transform.py` keeps the names in a dictionary, one per id', 'O `transform.py` guarda os nomes num dicionário, um por id',
    'Right, and by luck: a join keeping every match would have counted four times.', 'Isso, e por sorte: uma junção que mantivesse todas as correspondências contaria quatro vezes.', ok=True),
  C('`ingest.py` copies stations in full, which removes duplicates', '`ingest.py` copia as estações inteiras, o que remove duplicatas',
    'A full copy appended twice is two full copies.', 'Uma cópia completa acrescentada duas vezes são duas cópias completas.'),
  C('The stations table has a primary key that refuses duplicates', 'A tabela de estações tem uma chave primária que recusa duplicatas',
    'That key lives in `app.db`; the JSON file has no keys at all.', 'Essa chave mora no `app.db`; o arquivo JSON não tem chave nenhuma.')),
Q('ex-50tftn6g', 'run-it-twice', 'medium',
  ('What makes `ingest_replace.py` idempotent?', 'O que torna o `ingest_replace.py` idempotente?'),
  ('Two lines changed.', 'Duas linhas mudaram.'),
  C('It checks each ride id against the raw file before writing it', 'Ele confere cada id de viagem contra o arquivo bruto antes de gravar',
    'That would be the unique-key approach; this one replaces the day.', 'Esse seria o jeito da chave única; este substitui o dia.'),
  C('It runs faster, so a retry never overlaps the first run', 'Ele roda mais rápido, então uma repetição não se sobrepõe à primeira',
    'Speed is not the reason; the second run replaces the first.', 'Velocidade não é o motivo; a segunda execução substitui a primeira.'),
  C('It reads the app’s database with `mode=ro`', 'Ele lê o banco do aplicativo com `mode=ro`',
    'So did `ingest.py`, which doubled.', 'O `ingest.py` também, e dobrou.'),
  C('It removes the day’s directory, creates it empty and writes each file with `"w"`', 'Ele remove o diretório do dia, o cria vazio e grava cada arquivo com `"w"`',
    'Right: removed, recreated, written with `"w"`.', 'Isso: removido, recriado, gravado com `"w"`.', ok=True)),
# ---- lineage
O('ex-waa8pzb0', 'lineage', 'easy',
  ('Put the layers in the order a trace walks them, starting from the number in the report.',
   'Ponha as camadas na ordem em que um rastreio as percorre, começando pelo número do relatório.'),
  ('Backwards through the lifecycle.', 'De trás para a frente no ciclo de vida.'),
  [('the report', 'o relatório'), ('curated', 'curado'), ('clean', 'limpo'), ('raw', 'bruto'), ('the app’s database', 'o banco do aplicativo')],
  ('Lineage is the lifecycle read in the other direction.', 'Linhagem é o ciclo de vida lido na outra direção.')),
N('ex-7t18e63d', 'lineage', 'medium',
  ('How many rides from Rua XV on 2025-09-15 does the app’s database hold, according to `trace.py`?',
   'Quantas viagens da Rua XV em 2025-09-15 o banco do aplicativo tem, segundo o `trace.py`?'),
  ('The bottom line of the counts.', 'A última linha das contagens.'),
  31, 0, ('rides', 'viagens')),
Q('ex-2jv3jy03', 'lineage', 'hard',
  ('The app team wants to rename `start_station`. Which use of lineage answers what that breaks?',
   'O time do aplicativo quer renomear `start_station`. Que uso da linhagem responde o que isso quebra?'),
  ('Read the path forwards.', 'Leia o caminho para a frente.'),
  C('Trust, because it lets Marta defend the number in a meeting', 'Confiança, porque deixa Marta defender o número numa reunião',
    'Trust reads the path backwards from one number.', 'Confiança lê o caminho para trás a partir de um número.'),
  C('Erasure, because it lists every zone a customer reached', 'Eliminação, porque lista todas as zonas a que um cliente chegou',
    'Erasure follows a person’s rows, not a column.', 'Eliminação segue as linhas de uma pessoa, não uma coluna.'),
  C('Impact: the path read forwards from the column', 'Impacto: o caminho lido para a frente a partir da coluna',
    'Right: from the source column forwards to every table and report.', 'Isso: da coluna na origem para a frente, até cada tabela e relatório.', ok=True),
  C('Freshness, because the rename delays the next copy', 'Atualidade, porque a mudança de nome atrasa a próxima cópia',
    'Freshness is a promise about time, not a use of lineage.', 'Atualidade é uma promessa sobre tempo, não um uso da linhagem.')),
# ---- drill
Q('ex-aznmsevf', 'drill', 'medium',
  ('Caio wants rides per station per hour for his model. Which zone should he read?',
   'Caio quer viagens por estação por hora para o modelo dele. Que zona ele deve ler?'),
  ('Every form of delivery reads the same zone.', 'Toda forma de entrega lê a mesma zona.'),
  C('Raw, so that no rule hides anything from the model', 'A bruta, para nenhuma regra esconder nada do modelo',
    'Then his model counts false starts and the report does not.', 'Aí o modelo conta partidas falsas e o relatório não.'),
  C('Curated, in a feature table built for his model from the same definitions as the report', 'A curada, numa tabela de atributos feita para o modelo com as mesmas definições do relatório',
    'Right: a feature table is one more curated table.', 'Isso: uma tabela de atributos é mais uma tabela curada.', ok=True),
  C('The app’s database, which has the freshest rides', 'O banco do aplicativo, que tem as viagens mais recentes',
    'Reading the source for analysis is what ingestion exists to avoid.', 'Ler a origem para análise é o que a ingestão existe para evitar.'),
  C('Cleaned, and he aggregates the rows himself', 'A limpa, e ele agrega as linhas sozinho',
    'Then his per-hour count is a second definition in a notebook.', 'Aí a contagem por hora dele é uma segunda definição num notebook.')),
Q('ex-chqj267k', 'drill', 'hard',
  ('A bug in `transform.py` is found three months after it shipped. What does the fix cost, with raw kept?',
   'Um erro no `transform.py` é achado três meses depois de entrar em produção. Quanto custa a correção, com o bruto guardado?'),
  ('Which zones are the output of a program?', 'Que zonas são saída de um programa?'),
  C('Re-ingesting three months from the app, which may have changed them', 'Reingerir três meses do aplicativo, que talvez os tenha mudado',
    'Raw already holds them as they were; the app holds them as they are now.', 'O bruto já os tem como eram; o aplicativo os tem como estão agora.'),
  C('Fix the code and re-run it over those days', 'Corrigir o código e rodar de novo sobre esses dias',
    'Right: cleaned and curated come out as though the bug never existed.', 'Isso: limpo e curado saem como se o erro nunca tivesse existido.', ok=True),
  C('Accept three wrong months and fix it from today', 'Aceitar três meses errados e corrigir a partir de hoje',
    'That is the cost without raw.', 'Esse é o custo sem o bruto.'),
  C('Edit the curated files for those months by hand', 'Editar à mão os arquivos curados desses meses',
    'A program wrote them; a program rewrites them.', 'Um programa os gravou; um programa os regrava.')),
Q('ex-j9sgecf3', 'drill', 'medium',
  ('A nightly job fails at 02:00, and the scheduler retries it at 02:30. What has to be true for the retry to be safe?',
   'Um job noturno falha às 02:00, e o agendador o repete às 02:30. O que precisa ser verdade para a repetição ser segura?'),
  ('Did the first try write anything before it failed?', 'A primeira tentativa gravou algo antes de falhar?'),
  C('The job gives the same result run twice', 'O job dar o mesmo resultado rodando duas vezes',
    'Right: the retry replaces whatever the first try left.', 'Isso: a repetição substitui o que a primeira tentativa deixou.', ok=True),
  C('The job finishes in under thirty minutes', 'O job terminar em menos de trinta minutos',
    'Duration is not what makes a second run harmless.', 'Duração não é o que torna uma segunda execução inofensiva.'),
  C('The first try wrote nothing at all before failing', 'A primeira tentativa não ter gravado nada antes de falhar',
    'Nobody can promise that; idempotence makes it not matter.', 'Ninguém consegue prometer isso; a idempotência faz isso não importar.'),
  C('The source has not changed between the two tries', 'A origem não ter mudado entre as duas tentativas',
    'A replaced day simply takes the newer state; that is not the danger.', 'Um dia substituído simplesmente leva o estado mais novo; esse não é o perigo.')),
Z('ex-6cth1w39', 'drill', 'medium',
  ('In `ingest.py`, the mode that adds to an existing file is `"___"`.', 'No `ingest.py`, o modo que acrescenta a um arquivo existente é `"___"`.'),
  ('Compare it with the mode `ingest_replace.py` uses.', 'Compare com o modo que o `ingest_replace.py` usa.'),
  ['a'], ['a'], ignore_case=False),
O('ex-dzxz4apq', 'drill', 'medium',
  ('Put the four programs of `~/roda/lifecycle` in the order the pipeline runs them.',
   'Ponha os quatro programas de `~/roda/lifecycle` na ordem em que o pipeline os roda.'),
  ('Each reads what the one before it wrote.', 'Cada um lê o que o anterior gravou.'),
  [('`app.py`', '`app.py`'), ('`ingest.py`', '`ingest.py`'), ('`transform.py`', '`transform.py`'), ('`report.py`', '`report.py`')],
  ('`trace.py` is not in the pipeline: it reads every layer after the fact.', 'O `trace.py` não está no pipeline: ele lê todas as camadas depois.')),
]

# Where each quiz key sits, so no position carries the answer: a fixed cycle
# over the quizzes in file order, applied after they are written.
_POS = [1, 3, 4, 2, 3, 1, 2, 4, 4, 2]
for _i, _q in enumerate(q for q in QUESTIONS if q['type'] == 'quiz'):
    _key = next(i for i, c in enumerate(_q['choices']) if c['ok'])
    _q['choices'].insert(_POS[_i % len(_POS)] - 1, _q['choices'].pop(_key))
