from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
# ---- what-the-job-owns
Q('ex-730f54gc', 'what-the-job-owns', 'easy',
  ('What is a data contract?', 'O que é um contrato de dados?'),
  ('It is between two teams.', 'Ele é entre dois times.'),
  C('A licence that lets the data team copy the app’s database', 'Uma licença que deixa o time de dados copiar o banco do aplicativo',
    'Permission to copy is access control; the contract is about what the data means and how it changes.', 'Permissão para copiar é controle de acesso; o contrato é sobre o que o dado quer dizer e como muda.'),
  C('A written agreement on the fields and how changes are announced', 'Um acordo escrito sobre os campos e como mudanças são avisadas',
    'Right: producer and reader agree on fields, meaning, types and notice.', 'Isso: quem produz e quem lê concordam sobre campos, sentido, tipos e aviso.', ok=True),
  C('A schema the database enforces so a column is never renamed', 'Um esquema que o banco impõe para uma coluna jamais ser renomeada',
    'A contract does not freeze the source; the app still has to evolve.', 'Um contrato não congela a fonte; o aplicativo continua precisando evoluir.'),
  C('The invoice a provider sends for storing the data', 'A fatura que um fornecedor manda por guardar o dado',
    'That is a bill, which is the cost row of the table, not the contract row.', 'Isso é uma conta, a linha de custo da tabela, não a de contrato.')),
Q('ex-5drm76gk', 'what-the-job-owns', 'medium',
  ('Under a contract, the app team announces two weeks ahead that `start_station` will be renamed. What has the contract changed?',
   'Com um contrato, o time do aplicativo avisa com duas semanas que `start_station` vai ser renomeada. O que o contrato mudou?'),
  ('Compare it with the rename in lesson 1.', 'Compare com a renomeação da aula 1.'),
  C('The rename is blocked until the data team agrees to it', 'A renomeação fica bloqueada até o time de dados concordar',
    'The contract gives notice, not a veto over how the app evolves.', 'O contrato dá aviso, não poder de veto sobre como o aplicativo evolui.'),
  C('The pipeline now reads columns by position rather than by name', 'O pipeline passa a ler as colunas pela posição em vez do nome',
    'Reading by position breaks on a reorder instead; it is not what the contract does.', 'Ler pela posição quebra numa reordenação; não é isso que o contrato faz.'),
  C('A surprise became a date that the pipeline could be ready for', 'Uma surpresa virou uma data para a qual o pipeline podia se preparar',
    'Right: the pipeline is ready on the day of the rename.', 'Isso: o pipeline está pronto no dia da renomeação.', ok=True),
  C('Nothing, since a rename breaks a pipeline whatever was agreed', 'Nada, já que uma renomeação quebra um pipeline seja qual for o acordo',
    'With notice, the pipeline is changed first and does not break.', 'Com aviso, o pipeline é mudado antes e não quebra.')),
Q('ex-j7p10vns', 'what-the-job-owns', 'easy',
  ('Which law governs the personal data Roda Livre keeps about its customers in Brazil?',
   'Que lei rege os dados pessoais que a Roda Livre guarda sobre os clientes no Brasil?'),
  ('Law 13.709 of 2018.', 'Lei 13.709, de 2018.'),
  C('The LGPD, enforced by the ANPD', 'A LGPD, fiscalizada pela ANPD',
    'Right: the Lei Geral de Proteção de Dados, enforced by the ANPD.', 'Isso: a Lei Geral de Proteção de Dados, fiscalizada pela ANPD.', ok=True),
  C('No law, as long as the data stays inside the company', 'Nenhuma, desde que o dado fique dentro da empresa',
    'Keeping it in-house does not take it out of the law; holding it is processing it.', 'Guardar internamente não tira o dado da lei; guardar já é tratar.'),
  C('The terms of use the customer accepted in the app', 'Os termos de uso que o cliente aceitou no aplicativo',
    'Terms of use sit beneath the law and cannot set it aside.', 'Os termos de uso ficam abaixo da lei e não a afastam.'),
  C('The GDPR, because the data lives in the cloud', 'O GDPR, porque o dado mora na nuvem',
    'The GDPR is the European regulation; Brazilian customers fall under the LGPD.', 'O GDPR é o regulamento europeu; clientes brasileiros estão sob a LGPD.')),
MC('ex-0nkn95yd', 'what-the-job-owns', 'medium',
  ('Which of these are among what a data engineer at Roda Livre is answerable for? Choose all that apply.',
   'Quais destas estão entre aquilo por que um engenheiro de dados da Roda Livre responde? Marque todas as que se aplicam.'),
  ('Seven were listed.', 'Foram listadas sete.'),
  C('How fresh the rides are at 09:00', 'Quão atuais estão as viagens às 09:00',
    'Yes: freshness is one of the seven.', 'Sim: atualidade é uma das sete.', ok=True),
  C('The price of a ride', 'O preço de uma viagem',
    'That is a business decision; the engineer delivers the data it is judged by.', 'Isso é decisão do negócio; o engenheiro entrega o dado com que ela é avaliada.'),
  C('A description of what each table means', 'Uma descrição do que cada tabela quer dizer',
    'Yes: documentation is one of the seven.', 'Sim: documentação é uma das sete.', ok=True),
  C('The monthly bill for storage and queries', 'A conta mensal de armazenamento e consultas',
    'Yes: cost is one of the seven.', 'Sim: custo é uma das sete.', ok=True),
  C('Which stations the van visits first', 'Que estações a van visita primeiro',
    'That is Marta’s call, made with the data the engineer delivers.', 'Essa decisão é de Marta, tomada com o dado que o engenheiro entrega.')),
# ---- the-undercurrents
Q('ex-hpgqfm8s', 'the-undercurrents', 'easy',
  ('What do Reis and Housley mean by the undercurrents?', 'O que Reis e Housley querem dizer com as correntes subterrâneas?'),
  ('Where in the lifecycle do they appear?', 'Onde no ciclo de vida elas aparecem?'),
  C('Phases done after the pipeline is built, such as securing it', 'Fases feitas depois que o pipeline está pronto, como protegê-lo',
    'That is the picture the section corrects: a stage that skipped them hands the gap on.', 'Essa é a imagem que a seção corrige: a etapa que as pulou passa o buraco adiante.'),
  C('Questions asked at every stage, from generation to delivery', 'Perguntas feitas em todas as etapas, da geração até a entrega',
    'Right: each is a question asked at every stage.', 'Isso: cada uma é uma pergunta feita em todas as etapas.', ok=True),
  C('The storage and compute that sit beneath a warehouse', 'O armazenamento e a computação que ficam sob um warehouse',
    'Those are layers of a product; the undercurrents are concerns of the work.', 'Isso são camadas de um produto; as correntes são preocupações do trabalho.'),
  C('Costs that do not show on the provider’s bill', 'Custos que não aparecem na conta do fornecedor',
    'Hidden costs are real, but they are what-it-costs, not this list.', 'Custos ocultos existem, mas são assunto do custo, não desta lista.')),
M('ex-d3bfjvx2', 'the-undercurrents', 'easy',
  ('Match each undercurrent to the question it asks at every stage.', 'Associe cada corrente à pergunta que ela faz em toda etapa.'),
  ('Read the question each one asks.', 'Leia a pergunta que cada uma faz.'),
  [(('security', 'segurança'), ('who can read and change this?', 'quem pode ler e alterar isto?')),
   (('data management', 'gestão de dados'), ('what does it mean, and who owns it?', 'o que isto quer dizer, e quem é o dono?')),
   (('DataOps', 'DataOps'), ('is it automated and watched?', 'está automatizado e vigiado?')),
   (('orchestration', 'orquestração'), ('what runs when, and in what order?', 'o que roda quando, e em que ordem?')),
   (('software engineering', 'engenharia de software'), ('is it versioned, reviewed and tested?', 'está versionado, revisado e testado?'))]),
Q('ex-18p7hadb', 'the-undercurrents', 'medium',
  ('The first copy of the rides keeps each customer’s phone number. Why is removing it later expensive?',
   'A primeira cópia das viagens guarda o telefone de cada cliente. Por que tirá-lo depois sai caro?'),
  ('Follow the number downstream.', 'Siga o número adiante.'),
  C('Phone numbers are stored encrypted and cannot be deleted', 'Telefones ficam criptografados e não podem ser apagados',
    'Encryption does not stop deletion; the trouble is how many places hold it.', 'Criptografia não impede apagar; o problema é quantos lugares o guardam.'),
  C('Every table, report and person downstream of it gets the number', 'Toda tabela, relatório e pessoa depois da cópia recebe o número',
    'Right: fixing it at the end means finding every copy.', 'Isso: corrigir no fim quer dizer encontrar cada cópia.', ok=True),
  C('The LGPD forbids changing data once it has been collected', 'A LGPD proíbe mudar um dado depois de coletado',
    'The law asks for the opposite: data kept no longer than its purpose needs.', 'A lei pede o contrário: dado guardado só enquanto a finalidade precisar.'),
  C('Orchestration has to be rebuilt for each change', 'A orquestração precisa ser refeita a cada mudança',
    'A schedule does not hold data; the copies do.', 'Um agendamento não guarda dado; as cópias guardam.')),
Q('ex-j25cj2bw', 'the-undercurrents', 'hard',
  ('Caio asks for read access to the payments table to try a new model. Which undercurrent’s question should be answered first?',
   'Caio pede acesso de leitura à tabela de pagamentos para testar um modelo novo. A pergunta de qual corrente deve ser respondida primeiro?'),
  ('Payments are readable by two people today.', 'Hoje os pagamentos são legíveis por duas pessoas.'),
  C('Orchestration', 'Orquestração',
    'Nothing has to run on a schedule yet; this is about who may read.', 'Nada precisa rodar num horário ainda; isto é sobre quem pode ler.'),
  C('Software engineering', 'Engenharia de software',
    'Version control matters for code; the request is for access to data.', 'Controle de versão importa para código; o pedido é de acesso a dado.'),
  C('Security', 'Segurança',
    'Right: who can read this, and is it the fewest people who need to?', 'Isso: quem pode ler isto, e é o mínimo de pessoas que precisam?', ok=True),
  C('DataOps', 'DataOps',
    'Automation and monitoring come after deciding whether he may read it.', 'Automação e monitoramento vêm depois de decidir se ele pode ler.')),
# ---- skills
Q('ex-17fjcm5m', 'skills', 'easy',
  ('Why does the list of six skills name no particular warehouse or scheduler?',
   'Por que a lista das seis habilidades não cita nenhum warehouse ou agendador em particular?'),
  ('What is each of those products?', 'O que é cada um desses produtos?'),
  C('Because those products are taught in this course instead', 'Porque esses produtos são ensinados neste curso',
    'This course names them; other courses teach them.', 'Este curso dá nome a eles; outros cursos os ensinam.'),
  C('Each one is a product doing one of the six jobs in its own way', 'Cada um é um produto que faz um dos seis trabalhos do seu jeito',
    'Right: learnt after the six, a product takes weeks.', 'Isso: aprendido depois das seis, um produto leva semanas.', ok=True),
  C('Because employers have stopped asking for them in adverts', 'Porque os empregadores pararam de pedi-los nos anúncios',
    'Adverts are full of them; the section says they rest on the six.', 'Os anúncios estão cheios deles; a seção diz que se apoiam nas seis.'),
  C('Because they change too fast to be worth learning', 'Porque mudam rápido demais para valer a pena aprender',
    'They are worth learning, one at a time, on top of the six.', 'Valem a pena, um de cada vez, sobre as seis.')),
Q('ex-awsg8qm7', 'skills', 'medium',
  ('Marta asked for a live map of bicycles per station. What did Ana’s question about its use reveal?',
   'Marta pediu um mapa ao vivo das bicicletas por estação. O que a pergunta de Ana sobre o uso revelou?'),
  ('Ask what she will do with it.', 'Pergunte o que ela vai fazer com ele.'),
  C('That the map had to update every second to be useful', 'Que o mapa precisava atualizar a cada segundo para servir',
    'The van leaves twice a day; seconds buy nothing.', 'A van sai duas vezes por dia; segundos não compram nada.'),
  C('A picture before each van run', 'Um retrato antes de cada saída da van',
    'Right: a batch job twice a day, with data an hour or two old.', 'Isso: um job em lote duas vezes por dia, com dado de uma ou duas horas.', ok=True),
  C('That the request was curiosity and could wait a year', 'Que o pedido era curiosidade e podia esperar um ano',
    'The van driver acts on it every day; it is not curiosity.', 'O motorista da van age com base nele todo dia; não é curiosidade.'),
  C('That Marta needed a stream of dock readings, as asked', 'Que Marta precisava de um fluxo de leituras das docas, como pediu',
    'That was the literal request, and the most expensive reading of it.', 'Esse era o pedido ao pé da letra, e a leitura mais cara dele.')),
Q('ex-9kzwyc3k', 'skills', 'hard',
  ('The finance manager asks Ana for "real-time revenue". Which question should she ask first?',
   'O gerente financeiro pede a Ana "receita em tempo real". Que pergunta ela deveria fazer primeiro?'),
  ('Before any tool.', 'Antes de qualquer ferramenta.'),
  C('Which stream processor would the finance team like us to use?', 'Que processador de fluxos o time financeiro gostaria que usássemos?',
    'That chooses a tool before anybody knows the need.', 'Isso escolhe uma ferramenta antes de alguém saber a necessidade.'),
  C('Should the data be stored as Parquet or as Avro files?', 'O dado deve ser guardado em arquivos Parquet ou Avro?',
    'A format question, asked before the problem is known.', 'Uma pergunta de formato, feita antes de conhecer o problema.'),
  C('How many dashboards does the finance team want?', 'Quantos painéis o time financeiro quer?',
    'A count of screens says nothing about how fresh the data must be.', 'Uma contagem de telas não diz nada sobre quão atual o dado precisa ser.'),
  C('What will you do differently with it?', 'O que você vai fazer de diferente com isso?',
    'Right: the answer decides what "real time" has to mean.', 'Isso: a resposta decide o que "tempo real" precisa querer dizer.', ok=True)),
# ---- promises-about-data
Q('ex-24v6f6hr', 'promises-about-data', 'easy',
  ('What is an SLI?', 'O que é um SLI?'),
  ('I is for indicator.', 'O I é de indicador.'),
  C('A target the team sets for itself', 'Uma meta que o time define para si',
    'That is the objective, the SLO.', 'Esse é o objetivo, o SLO.'),
  C('A measurement, such as the data’s age at 09:00', 'Uma medida, como a idade do dado às 09:00',
    'Right: the indicator is what is measured.', 'Isso: o indicador é o que se mede.', ok=True),
  C('A promise to a customer, with a penalty', 'Uma promessa a um cliente, com multa',
    'That is the agreement, the SLA.', 'Esse é o acordo, o SLA.'),
  C('A log of the incidents of the month', 'Um registro dos incidentes do mês',
    'A log records failures; the indicator measures every morning, good or bad.', 'Um registro guarda falhas; o indicador mede toda manhã, boa ou ruim.')),
Q('ex-g0r5x4q0', 'promises-about-data', 'medium',
  ('Why is Roda Livre’s two-hour objective tighter than the four-hour agreement with the city?',
   'Por que o objetivo de duas horas da Roda Livre é mais apertado que o acordo de quatro horas com a prefeitura?'),
  ('Who hears first?', 'Quem fica sabendo primeiro?'),
  C('Because the city checks the data twice as often as Marta does', 'Porque a prefeitura confere o dado com o dobro da frequência de Marta',
    'The difference is not about who checks more; it is about who hears first.', 'A diferença não é quem confere mais; é quem fica sabendo primeiro.'),
  C('Because objectives and agreements are measured in different units', 'Porque objetivos e acordos são medidos em unidades diferentes',
    'Both are hours of age; the same measurement sits under both.', 'Os dois são horas de idade; a mesma medida está sob os dois.'),
  C('So the team hears of trouble first', 'Para o time saber do problema primeiro',
    'Right: a breach of the objective leaves time to fix it before the promise breaks.', 'Isso: estourar o objetivo deixa tempo para consertar antes de a promessa quebrar.', ok=True),
  C('To pay a smaller discount', 'Para pagar um desconto menor',
    'The discount follows the agreement; the objective carries no money.', 'O desconto segue o acordo; o objetivo não envolve dinheiro.')),
Q('ex-6zew2jvd', 'promises-about-data', 'medium',
  ('`freshness.py` reports `repairs.csv` as BREACH at 63.5 hours on a Monday. What should change?',
   '`freshness.py` acusa `repairs.csv` como BREACH com 63,5 horas numa segunda. O que deveria mudar?'),
  ('When do the mechanics save the sheet?', 'Quando os mecânicos salvam a planilha?'),
  C('The mechanics should save their sheet every hour', 'Os mecânicos deveriam salvar a planilha toda hora',
    'Nobody reading repairs needs hourly data; the feed is fine.', 'Ninguém que lê consertos precisa de dado por hora; a fonte está boa.'),
  C('The objective for that feed', 'O objetivo daquela fonte',
    'Right: each feed gets an objective set by what its readers need.', 'Isso: cada fonte tem um objetivo definido pelo que os seus leitores precisam.', ok=True),
  C('The program, because `os.utime` set the wrong time', 'O programa, porque `os.utime` ajustou a hora errada',
    'The listing shows 17:30 on Friday, the time that was intended.', 'A listagem mostra 17:30 de sexta, a hora pretendida.'),
  C('The clock, because Friday was recorded in another time zone', 'O relógio, porque a sexta foi gravada em outro fuso',
    'Every time in the program carries the São Paulo zone.', 'Toda hora no programa leva o fuso de São Paulo.')),
N('ex-ccgb1cgq', 'promises-about-data', 'easy',
  ('In the freshness check, how many hours old was `payments.csv` at 09:00?', 'Na verificação de atualidade, quantas horas tinha `payments.csv` às 09:00?'),
  ('It last landed at 06:50.', 'Ele chegou pela última vez às 06:50.'),
  2.2, 0.05, ('h', 'h')),
N('ex-eykpa2yv', 'promises-about-data', 'easy',
  ('In the September simulation, on how many of the thirty mornings were the rides fresh?', 'Na simulação de setembro, em quantas das trinta manhãs as viagens estavam atuais?'),
  ('The SLI line of the output.', 'A linha SLI da saída.'),
  28, 0, ('mornings', 'manhãs')),
Q('ex-80ej1mt0', 'promises-about-data', 'hard',
  ('An objective says fresh on 95% of mornings, measured over a 30-morning month. How many bad mornings can the month have and still meet it?',
   'Um objetivo diz atual em 95% das manhãs, medido num mês de 30 manhãs. Quantas manhãs ruins o mês pode ter e ainda cumpri-lo?'),
  ('Work out 5% of 30.', 'Calcule 5% de 30.'),
  C('Two', 'Duas',
    'Two leaves 28 of 30, which is 93.3%: September missed with exactly two.', 'Duas deixam 28 de 30, que é 93,3%: setembro falhou com exatamente duas.'),
  C('One', 'Uma',
    'Right: 5% of 30 is one and a half, so in practice one.', 'Isso: 5% de 30 é uma e meia, então na prática uma.', ok=True),
  C('Zero', 'Zero',
    'That would be a 100% objective; 95% leaves some room.', 'Isso seria um objetivo de 100%; 95% deixa alguma folga.'),
  C('Five', 'Cinco',
    'Five of thirty is about 17%, far past 5%.', 'Cinco de trinta é cerca de 17%, muito além de 5%.')),
Q('ex-1bj30cwf', 'promises-about-data', 'medium',
  ('Besides freshness, which indicator covers most of what readers of a table care about?',
   'Além da atualidade, que indicador cobre quase tudo o que importa a quem lê uma tabela?'),
  ('Did it all arrive?', 'Chegou tudo?'),
  C('Completeness, whether every row of the day arrived', 'Completude: se todas as linhas do dia chegaram à tabela',
    'Right: yesterday’s rides counted against the count the source reports.', 'Isso: as viagens de ontem contadas contra a contagem que a fonte informa.', ok=True),
  C('The number of people who read it each week', 'O número de pessoas que a leem por semana',
    'Popularity says nothing about whether the data is whole.', 'Popularidade não diz nada sobre o dado estar inteiro.'),
  C('The size of the file on disk', 'O tamanho do arquivo em disco',
    'A file can be large and still miss a day of rides.', 'Um arquivo pode ser grande e ainda faltar um dia de viagens.'),
  C('How long the load took to run last night', 'Quanto tempo a carga levou para rodar ontem à noite',
    'Speed of a load is not whether everything arrived.', 'A velocidade de uma carga não diz se tudo chegou.')),
Z('ex-w72ef6qc', 'promises-about-data', 'easy',
  ('In SLO, the O stands for ___.', 'Em SLO, o O quer dizer ___.'),
  ('The target the team sets itself.', 'A meta que o time define para si.'),
  ['objective'], ['objetivo', 'objective']),
# ---- choosing-technology
Q('ex-v8m9abkh', 'choosing-technology', 'easy',
  ('What is a two-way door, in the sense of Amazon’s 2015 letter?', 'O que é uma porta de mão dupla, no sentido da carta da Amazon de 2015?'),
  ('You can walk back through it.', 'Dá para voltar por ela.'),
  C('A decision you undo at modest cost if it was wrong', 'Uma decisão que se desfaz a custo modesto se estava errada',
    'Right: make it quickly, close to where it matters.', 'Isso: tome rápido, perto de onde ela importa.', ok=True),
  C('A decision two teams have to approve before it is made', 'Uma decisão que dois times precisam aprovar antes',
    'Approval is about who decides, not about whether it can be undone.', 'Aprovação é sobre quem decide, não sobre se dá para desfazer.'),
  C('A system that both reads data and writes it', 'Um sistema que lê e também escreve dados',
    'The doors are kinds of decision, not kinds of system.', 'As portas são tipos de decisão, não de sistema.'),
  C('A choice that deserves weeks of careful thought', 'Uma escolha que merece semanas de reflexão cuidadosa',
    'That describes the one-way door.', 'Isso descreve a porta de mão única.')),
Q('ex-r1wn728e', 'choosing-technology', 'medium',
  ('Which of these Roda Livre decisions is a one-way door?', 'Qual destas decisões da Roda Livre é uma porta de mão única?'),
  ('Which one leaves nothing to go back to?', 'Qual delas não deixa nada para onde voltar?'),
  C('Moving the dashboards to another tool next quarter', 'Passar os painéis para outra ferramenta no próximo trimestre',
    'A week of rebuilding charts, and it can be done again.', 'Uma semana refazendo gráficos, e dá para fazer de novo.'),
  C('Renaming a column with two weeks’ notice', 'Renomear uma coluna com duas semanas de aviso',
    'A rename with notice can be renamed back.', 'Uma renomeação com aviso pode ser desfeita.'),
  C('Deleting raw files after 30 days', 'Apagar os arquivos brutos após 30 dias',
    'Right: once they are gone, no question about that period can be answered.', 'Isso: depois que somem, nenhuma pergunta sobre aquele período tem resposta.', ok=True),
  C('Trying a new chart library on one report', 'Testar uma biblioteca de gráficos nova num relatório',
    'One report on a trial is the model two-way door.', 'Um relatório em teste é a porta de mão dupla típica.')),
Q('ex-s7vfk37x', 'choosing-technology', 'medium',
  ('Which of these lowers lock-in?', 'Qual destas reduz o aprisionamento?'),
  ('What lets the engine change while the data stays?', 'O que deixa o motor mudar enquanto o dado fica?'),
  C('Writing every query in the provider’s own dialect of SQL', 'Escrever toda consulta no dialeto de SQL do próprio fornecedor',
    'Every function only one product has is a line to rewrite on leaving.', 'Cada função que só um produto tem é uma linha a reescrever ao sair.'),
  C('Signing a longer contract for a lower monthly price', 'Assinar um contrato mais longo por um preço mensal menor',
    'A longer contract raises the cost of leaving.', 'Um contrato mais longo aumenta o custo de sair.'),
  C('Keeping raw data in an open format that many engines read', 'Guardar o dado bruto num formato aberto que muitos motores leem',
    'Right: Parquet can be read by dozens of engines.', 'Isso: Parquet pode ser lido por dezenas de motores.', ok=True),
  C('Choosing whichever provider the biggest companies use', 'Escolher o fornecedor que as maiores empresas usam',
    'Popularity makes a tool mature, not easy to leave.', 'Popularidade torna uma ferramenta madura, não fácil de deixar.')),
Q('ex-h4fttvg1', 'choosing-technology', 'medium',
  ('Which statement about managed and self-hosted is the section’s?', 'Qual afirmação sobre gerenciado e hospedado por conta própria é a da seção?'),
  ('What does each one cost?', 'Quanto custa cada um?'),
  C('Self-hosted is cheaper in general, since there is no charge per use', 'Hospedar por conta própria é mais barato em geral, já que não há cobrança por uso',
    'The hours are the missing cost, and for a team of two they are the scarcer thing.', 'As horas são o custo que falta, e num time de dois são o recurso mais escasso.'),
  C('Managed means the provider owns the data from then on', 'Gerenciado quer dizer que o fornecedor passa a ser dono do dado',
    'The provider runs the software; the data stays yours.', 'O fornecedor roda o software; o dado continua seu.'),
  C('They differ in who runs the software, and that is all', 'Eles diferem em quem roda o software, e só',
    'Who runs it changes the bill, the hours and the control.', 'Quem roda muda a conta, as horas e o controle.'),
  C('Neither is cheaper in general', 'Nenhum é mais barato em geral',
    'Right: managed trades hours for a bill, and the balance depends on the team.', 'Isso: gerenciado troca horas por conta, e o equilíbrio depende do time.', ok=True)),
Q('ex-agmk83ep', 'choosing-technology', 'hard',
  ('A new database is at version 0.4, and searching its error messages finds nothing. Which criterion does this speak to?',
   'Um banco de dados novo está na versão 0.4, e buscar as mensagens de erro dele não encontra nada. A que critério isto se refere?'),
  ('Who has already hit the problems?', 'Quem já topou com os problemas?'),
  C('Lock-in', 'Aprisionamento',
    'Leaving it could be easy; the worry is running it.', 'Sair dele pode ser fácil; a preocupação é rodá-lo.'),
  C('Total cost', 'Custo total',
    'Nothing here is about money yet.', 'Nada aqui é sobre dinheiro ainda.'),
  C('Maturity', 'Maturidade',
    'Right: a small population has met its problems before you.', 'Isso: pouca gente topou com os problemas dele antes de você.', ok=True),
  C('Reversibility', 'Reversibilidade',
    'Reversibility is about the decision, not about how proven the tool is.', 'Reversibilidade é sobre a decisão, não sobre quão provada a ferramenta é.')),
# ---- a-scoring-matrix
N('ex-p3291jta', 'a-scoring-matrix', 'easy',
  ('With the weights for a team of two, what total did "PostgreSQL we run" get?', 'Com os pesos de um time de dois, que total "PostgreSQL we run" recebeu?'),
  ('The first ranking.', 'A primeira classificação.'),
  36, 0, ('points', 'pontos')),
Q('ex-khnsv9zx', 'a-scoring-matrix', 'medium',
  ('Between the two rankings `matrix.py` prints, the winner changes. What changed?', 'Entre as duas classificações que `matrix.py` imprime, o vencedor muda. O que mudou?'),
  ('Compare the two dictionaries printed.', 'Compare os dois dicionários impressos.'),
  C('The scores Davi gave each option on each criterion', 'As notas que Davi deu a cada opção em cada critério',
    'SCORES is the same for both rankings.', 'SCORES é o mesmo nas duas classificações.'),
  C('The weights, the priority given to each criterion', 'Os pesos, a prioridade dada a cada critério',
    'Right: the same scores under other priorities give another winner.', 'Isso: as mesmas notas com outras prioridades dão outro vencedor.', ok=True),
  C('The list of options being compared', 'A lista de opções comparadas',
    'The same three options appear in both.', 'As mesmas três opções aparecem nas duas.'),
  C('The criteria the options are scored on', 'Os critérios em que as opções recebem nota',
    'The five criteria are printed, identical, in both.', 'Os cinco critérios aparecem, idênticos, nas duas.')),
Q('ex-5tc930mc', 'a-scoring-matrix', 'medium',
  ('Raising one score by one point made the managed warehouse win, 38 to 36. What does that say about the first result?',
   'Subir uma nota em um ponto fez o warehouse gerenciado vencer, 38 a 36. O que isso diz sobre o primeiro resultado?'),
  ('Compare one point with the uncertainty of a score.', 'Compare um ponto com a incerteza de uma nota.'),
  C('That Caio’s scoring is more accurate than Davi’s', 'Que a nota de Caio é mais precisa que a de Davi',
    'Neither is shown to be more accurate; both are judgements.', 'Nenhuma se mostra mais precisa; as duas são julgamentos.'),
  C('That the matrix was built with a mistake', 'Que a matriz foi feita com um erro',
    'The arithmetic is right; the margin is small.', 'A aritmética está certa; a margem é que é pequena.'),
  C('That the managed warehouse is the better choice after all', 'Que o warehouse gerenciado é a melhor escolha, afinal',
    'One nudged cell does not make a winner either.', 'Uma célula mexida também não faz um vencedor.'),
  C('The two are equivalent on these criteria', 'As duas são equivalentes nesses critérios',
    'Right: the choice goes to something the matrix does not hold.', 'Isso: a escolha passa para algo que a matriz não contém.', ok=True)),
Q('ex-qmnxmwtr', 'a-scoring-matrix', 'hard',
  ('A colleague who already prefers one option adjusts the numbers until it comes out top. What is this?',
   'Um colega que já prefere uma opção ajusta os números até ela sair em primeiro. O que é isto?'),
  ('When were the scores written?', 'Quando as notas foram escritas?'),
  C('Counting one thing twice', 'Contar a mesma coisa duas vezes',
    'That is criteria that overlap, such as two kinds of cost.', 'Isso é critério repetido, como dois tipos de custo.'),
  C('Résumé-driven development', 'Desenvolvimento orientado a currículo',
    'That is about why a tool is wanted, not how a matrix is filled.', 'Isso é sobre por que uma ferramenta é desejada, não sobre como uma matriz é preenchida.'),
  C('Scoring after deciding', 'Dar as notas depois de decidir',
    'Right: the matrix launders a preference into a calculation.', 'Isso: a matriz lava uma preferência e a transforma em cálculo.', ok=True),
  C('Weighting for growth', 'Dar peso ao crescimento',
    'Choosing weights openly is the method; bending scores to an answer is not.', 'Escolher pesos às claras é o método; dobrar as notas até a resposta não é.')),
# ---- boring-technology
Q('ex-319g6x9n', 'boring-technology', 'easy',
  ('In McKinley’s sense, what makes a technology boring?', 'No sentido de McKinley, o que torna uma tecnologia chata?'),
  ('Think of its failures.', 'Pense nas falhas dela.'),
  C('It is old and slow, and chosen by habit', 'É velha e lenta, e escolhida por hábito',
    'That is the picture the section replaces.', 'Essa é a imagem que a seção substitui.'),
  C('Its failures are already known', 'As falhas dela já são conhecidas',
    'Right: a failure with a name, a search result and a fix.', 'Isso: uma falha com nome, resultado de busca e correção.', ok=True),
  C('It has stopped releasing new versions', 'Parou de lançar versões novas',
    'Boring tools keep being released; what matters is that they are well understood.', 'Ferramentas chatas continuam sendo lançadas; o que importa é serem bem conhecidas.'),
  C('Nobody puts it on a CV', 'Ninguém a põe no currículo',
    'CVs are about the chooser; boring is about the tool’s known failures.', 'Currículo é sobre quem escolhe; chato é sobre as falhas conhecidas da ferramenta.')),
Q('ex-07bs0pr6', 'boring-technology', 'medium',
  ('Where should Roda Livre spend an innovation token, if it spends one?', 'Onde a Roda Livre deveria gastar uma ficha de inovação, se gastar uma?'),
  ('What does the company compete on?', 'Em que a empresa compete?'),
  C('On a novel database for storing rides', 'Num banco de dados inovador para guardar viagens',
    'Storing rides well is not what wins customers.', 'Guardar viagens bem não é o que conquista clientes.'),
  C('On a new scheduler for the nightly copies', 'Num agendador novo para as cópias noturnas',
    'A schedule is plumbing; it should be boring.', 'Um agendamento é encanamento; deve ser chato.'),
  C('On the forecast of which stations will run dry before the van', 'Na previsão de quais estações vão esvaziar antes da van',
    'Right: that is close to having a bicycle where somebody wants one.', 'Isso: está perto de ter uma bicicleta onde alguém quer uma.', ok=True),
  C('On a stream processor for Marta’s van report', 'Num processador de fluxos para o relatório da van de Marta',
    'The van report needs data twice a day, not a stream.', 'O relatório da van precisa de dado duas vezes por dia, não de um fluxo.')),
Q('ex-w9jzb4tr', 'boring-technology', 'medium',
  ('Which of these is evidence for leaving a boring tool?', 'Qual destas é evidência para abandonar uma ferramenta chata?'),
  ('Measured or predicted?', 'Medida ou prevista?'),
  C('A forecast that it will not scale next year', 'Uma previsão de que não vai escalar ano que vem',
    'A forecast is the weaker kind of evidence the section warns about.', 'Uma previsão é o tipo mais fraco de evidência, de que a seção avisa.'),
  C('A conference talk about a faster tool', 'Uma palestra sobre uma ferramenta mais rápida',
    'A talk is about somebody else’s problem.', 'Uma palestra é sobre o problema de outra pessoa.'),
  C('A job advert that asks for a newer tool', 'Um anúncio de vaga que pede uma ferramenta mais nova',
    'That is the pull of résumé-driven development.', 'Isso é a atração do desenvolvimento orientado a currículo.'),
  C('A query Marta needs that took ten minutes this morning', 'Uma consulta de que Marta precisa e que levou dez minutos hoje de manhã',
    'Right: a measured fact, and a token is better spent on one.', 'Isso: um fato medido, e uma ficha é mais bem gasta num deles.', ok=True)),
# ---- a-decision-record
O('ex-rp6nkdh8', 'a-decision-record', 'easy',
  ('Put the parts of Davi and Ana’s decision record in the order they appear.', 'Ponha as partes do registro de decisão de Davi e Ana na ordem em que aparecem.'),
  ('From the title to the last line.', 'Do título à última linha.'),
  [('a numbered title stating the decision', 'um título numerado que enuncia a decisão'),
   ('status', 'situação'), ('context', 'contexto'), ('decision', 'decisão'),
   ('consequences', 'consequências'), ('when to revisit', 'quando revisitar')],
  ('The facts come before the decision they led to.', 'Os fatos vêm antes da decisão a que levaram.')),
Q('ex-fwzvs09r', 'a-decision-record', 'medium',
  ('The team later moves its tables to a managed warehouse. What happens to ADR 3?',
   'Mais tarde o time leva as tabelas para um warehouse gerenciado. O que acontece com o ADR 3?'),
  ('An accepted record is not edited.', 'Um registro aceito não é editado.'),
  C('It is edited to describe the new decision', 'É editado para descrever a decisão nova',
    'Editing it erases the reasoning that was true at the time.', 'Editá-lo apaga o raciocínio que valia na época.'),
  C('It is deleted, since it no longer applies', 'É apagado, já que não vale mais',
    'Deleting it loses the history the record exists to keep.', 'Apagá-lo perde a história que o registro existe para guardar.'),
  C('A new record supersedes it', 'Um registro novo o substitui',
    'Right: ADR 3 is marked superseded and stays readable.', 'Isso: o ADR 3 é marcado como substituído e continua legível.', ok=True),
  C('A comment is added to the code that reads the tables', 'Um comentário é acrescentado ao código que lê as tabelas',
    'A comment in code is not where the reasoning is looked for.', 'Um comentário no código não é onde se procura o raciocínio.')),
Q('ex-m0x0w554', 'a-decision-record', 'hard',
  ('Which "revisit when" condition is the most useful to write?', 'Que condição de "revisitar quando" é a mais útil de escrever?'),
  ('Which one can a person check?', 'Qual delas uma pessoa consegue conferir?'),
  C('When the team feels the database has become slow', 'Quando o time sentir que o banco ficou lento',
    'A feeling arrives late and argues; a measurement does not.', 'Uma sensação chega tarde e gera discussão; uma medida não.'),
  C('When a query Marta needs passes a minute', 'Quando uma consulta de Marta passar de um minuto',
    'Right: a measurement, so the question comes back by itself.', 'Isso: uma medida, então a pergunta volta sozinha.', ok=True),
  C('When a better database appears on the market', 'Quando aparecer um banco melhor no mercado',
    'Better tools appear every month; this would reopen it forever.', 'Ferramentas melhores aparecem todo mês; isso a reabriria para sempre.'),
  C('Some day, when there is time for it', 'Algum dia, quando houver tempo',
    'That is the "revisit some day" the line exists to replace.', 'Esse é o "revisitar algum dia" que a linha existe para substituir.')),
Q('ex-qfpj8dk8', 'a-decision-record', 'medium',
  ('Which part of an ADR ages, and is the reason to keep it?', 'Que parte de um ADR envelhece, e é o motivo de guardá-lo?'),
  ('Facts true at the time.', 'Fatos verdadeiros na época.'),
  C('The context of the decision', 'O contexto da decisão',
    'Right: a later reader can check whether those facts still hold.', 'Isso: quem lê depois confere se aqueles fatos ainda valem.', ok=True),
  C('The number in the title', 'O número no título',
    'The number is an identifier; it does not age.', 'O número é um identificador; não envelhece.'),
  C('The list of people who decided', 'A lista de quem decidiu',
    'Names say who to ask; they are not what a reader judges.', 'Os nomes dizem a quem perguntar; não são o que o leitor julga.'),
  C('The status line at the top of the record', 'A linha de situação no alto do registro',
    'Status changes when a record is superseded; it is not the facts.', 'A situação muda quando o registro é substituído; não são os fatos.')),
# ---- what-it-costs
N('ex-krbrtx61', 'what-it-costs', 'easy',
  ('How many gigabytes is a year of dock readings, according to `cost.py`?', 'Quantos gigabytes tem um ano de leituras das docas, segundo `cost.py`?'),
  ('The first line of the output.', 'A primeira linha da saída.'),
  3.78, 0.01, ('GB', 'GB')),
Q('ex-rd7qrvb1', 'what-it-costs', 'medium',
  ('What made the first managed plan cost 980.90 a month in queries?', 'O que fez o primeiro plano gerenciado custar 980,90 por mês em consultas?'),
  ('Same engine, same price, as the second plan.', 'Mesmo motor, mesmo preço, que o segundo plano.'),
  C('A higher price per terabyte than the second plan', 'Um preço por terabyte maior que o do segundo plano',
    'Both plans use the same invented price.', 'Os dois planos usam o mesmo preço inventado.'),
  C('Re-reading a whole year of readings every five minutes', 'Reler um ano inteiro de leituras a cada cinco minutos',
    'Right: how the engine is used moved the bill, not the tool.', 'Isso: o jeito de usar o motor mudou a conta, não a ferramenta.', ok=True),
  C('Keeping a full year of readings in storage', 'Guardar um ano inteiro de leituras',
    'Storage was 0.57 a month in every plan.', 'O armazenamento foi 0,57 por mês em todos os planos.'),
  C('The two hours of an engineer each month', 'As duas horas de um engenheiro por mês',
    'Those are the people line, 240.00, not queries.', 'Essas são a linha de pessoas, 240,00, não consultas.')),
Q('ex-xyp8qb84', 'what-it-costs', 'hard',
  ('"Our own server" has no charge per query, yet it is the most expensive plan. Why?', '"Our own server" não tem cobrança por consulta, e mesmo assim é o plano mais caro. Por quê?'),
  ('Look at the people column.', 'Olhe a coluna de pessoas.'),
  C('The server’s hourly price is the highest price in the program', 'O preço por hora do servidor é o maior preço do programa',
    'The server line is 432.00; the people line is larger.', 'A linha do servidor é 432,00; a de pessoas é maior.'),
  C('It stores the readings twice', 'Guarda as leituras duas vezes',
    'Storage is the same 0.57 in every plan.', 'O armazenamento é o mesmo 0,57 em todos os planos.'),
  C('Ten hours of upkeep a month, at an engineer’s price', 'Dez horas de manutenção por mês, ao preço de um engenheiro',
    'Right: 1200.00 of people, the largest line in any plan.', 'Isso: 1.200,00 de pessoas, a maior linha de todos os planos.', ok=True),
  C('It reads the whole year on every refresh', 'Lê o ano inteiro a cada atualização',
    'That is the first managed plan; this one charges nothing per read.', 'Esse é o primeiro plano gerenciado; este não cobra nada por leitura.')),
Q('ex-awnk6fxr', 'what-it-costs', 'medium',
  ('Deleting raw files to save on storage: what would it save at Roda Livre, by the program’s prices?',
   'Apagar arquivos brutos para economizar armazenamento: quanto isso economizaria na Roda Livre, pelos preços do programa?'),
  ('A year of readings cost 0.57 a month to keep.', 'Um ano de leituras custava 0,57 por mês para guardar.'),
  C('About a thousand reais a month', 'Cerca de mil reais por mês',
    'That was the queries of the five-minute plan, not storage.', 'Isso eram as consultas do plano de cinco minutos, não armazenamento.'),
  C('Less than one real a month', 'Menos de um real por mês',
    'Right: and the door it walks through is one-way.', 'Isso: e a porta que ela atravessa é de mão única.', ok=True),
  C('The cost of the server, 432.00 a month', 'O custo do servidor, 432,00 por mês',
    'The server runs whether the files exist or not.', 'O servidor roda existindo os arquivos ou não.'),
  C('Two hours of an engineer each month', 'Duas horas de um engenheiro por mês',
    'Deleting files does not remove the upkeep.', 'Apagar arquivos não tira a manutenção.')),
# ---- drill
M('ex-81sm1z80', 'drill', 'medium',
  ('Match each term to what it is.', 'Associe cada termo ao que ele é.'),
  ('Five terms from this lesson.', 'Cinco termos desta aula.'),
  [(('SLI', 'SLI'), ('a measurement of the data', 'uma medida do dado')),
   (('SLO', 'SLO'), ('the target the team sets itself', 'a meta que o time define para si')),
   (('SLA', 'SLA'), ('a promise outside, with a consequence', 'uma promessa externa, com consequência')),
   (('ADR', 'ADR'), ('a page recording one decision', 'uma página que registra uma decisão')),
   (('innovation token', 'ficha de inovação'), ('the budget for unfamiliar technology', 'o orçamento para tecnologia desconhecida'))]),
MC('ex-4awpkh4e', 'drill', 'medium',
  ('Which of these belong to the total cost of a technology? Choose all that apply.', 'Quais destas fazem parte do custo total de uma tecnologia? Marque todas as que se aplicam.'),
  ('Three terms.', 'Três termos.'),
  C('The provider’s bill', 'A conta do fornecedor',
    'Yes: the first term, and the only one on an invoice.', 'Sim: o primeiro termo, e o único que vem numa fatura.', ok=True),
  C('The hours of the people who run it', 'As horas das pessoas que a mantêm',
    'Yes: the largest line in two of the three plans.', 'Sim: a maior linha em dois dos três planos.', ok=True),
  C('Its place in a survey of popular tools', 'A posição dela numa pesquisa de ferramentas populares',
    'Popularity bears on maturity, not on cost.', 'Popularidade pesa na maturidade, não no custo.'),
  C('What it would cost to leave it', 'O que custaria deixá-la',
    'Yes: paid once and late, which is why it is left out.', 'Sim: pago uma vez e tarde, e por isso esquecido.', ok=True),
  C('The number of features it advertises', 'O número de recursos que ela anuncia',
    'Features are a reason to want it; they are not a cost.', 'Recursos são motivo para querê-la; não são custo.')),
Z('ex-zj5avgdk', 'drill', 'easy',
  ('A decision that cannot be undone is a ___-way door.', 'Uma decisão que não pode ser desfeita é uma porta de mão ___.'),
  ('The opposite of two-way.', 'O contrário de mão dupla.'),
  ['one'], ['única']),
Q('ex-y61c5ckr', 'drill', 'hard',
  ('A company with twenty engineers pays a large monthly bill for a managed warehouse and has spare hours on the team. How does the section’s reasoning apply?',
   'Uma empresa com vinte engenheiros paga uma conta mensal grande por um warehouse gerenciado e tem horas sobrando no time. Como o raciocínio da seção se aplica?'),
  ('Which resource is scarce here?', 'Que recurso é escasso aqui?'),
  C('Managed is cheaper whatever the size of the team', 'Gerenciado sai mais barato seja qual for o tamanho do time',
    'The section says neither is cheaper in general.', 'A seção diz que nenhum é mais barato em geral.'),
  C('With hours spare and a large bill, self-hosting is worth pricing', 'Com horas livres e uma conta alta, vale orçar hospedar por conta própria',
    'Right: with hours to spare and a big bill, the balance tips the other way.', 'Isso: com horas sobrando e uma conta grande, o equilíbrio pende para o outro lado.', ok=True),
  C('Lock-in rules out any change, so the question is closed', 'O aprisionamento impede qualquer mudança, então a questão está encerrada',
    'Lock-in is a price to know, not a wall.', 'Aprisionamento é um preço a conhecer, não um muro.'),
  C('The team should add a third option to the matrix and let its total decide', 'O time deveria pôr uma terceira opção na matriz e deixar o total decidir',
    'A matrix shows where people disagree; its total does not decide.', 'Uma matriz mostra onde as pessoas discordam; o total dela não decide.')),
Q('ex-e30mqfpw', 'drill', 'hard',
  ('Marta’s van report gets a new objective: at most one hour old at 09:00. Which part of the September run would you expect to change, and why?',
   'O relatório da van de Marta ganha um novo objetivo: no máximo uma hora às 09:00. Que parte da execução de setembro você esperaria mudar, e por quê?'),
  ('On 3 September the data was an hour and twenty minutes old.', 'Em 3 de setembro o dado tinha uma hora e vinte minutos.'),
  C('Nothing, since the objective is a target and not a measurement', 'Nada, já que o objetivo é uma meta e não uma medida',
    'The measurement stays; how many mornings pass it changes.', 'A medida fica; o que muda é quantas manhãs passam.'),
  C('The ages themselves, which would come out smaller', 'As próprias idades, que sairiam menores',
    'A target does not move the data; it moves the line.', 'Uma meta não mexe no dado; mexe na linha.'),
  C('Three breaches instead of two', 'Três violações em vez de duas',
    'Right: 3 September’s 1h20 now crosses the line as well.', 'Isso: o 1h20 de 3 de setembro agora também passa da linha.', ok=True),
  C('The agreement with the city, which has to tighten with it', 'O acordo com a prefeitura, que precisa apertar junto',
    'The agreement is a separate promise; the team tightens its own target alone.', 'O acordo é uma promessa separada; o time aperta a própria meta sozinho.')),
]
