from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
# ---- three-shapes
Q('ex-j0fakwrc', 'three-shapes', 'easy',
  ('What separates structured, semi-structured and unstructured data, according to this lesson?',
   'O que separa dado estruturado, semiestruturado e não estruturado, segundo esta aula?'),
  ('It is a question with one word in it: where.', 'É uma pergunta com uma palavra: onde.'),
  C('The file extension the data is saved with', 'A extensão do arquivo em que o dado é salvo',
    'The extension says how bytes are laid out, not whether anybody checked them.',
    'A extensão diz como os bytes estão dispostos, não se alguém os conferiu.'),
  C('How much of the data there is in total', 'Quanto dado existe no total',
    'A huge table is still structured, and one email is still unstructured.',
    'Uma tabela enorme continua estruturada, e um e-mail continua não estruturado.'),
  C('Where the schema lives', 'Onde mora o esquema',
    'Right: in the table, in each record, or nowhere.', 'Isso: na tabela, em cada registro, ou em lugar nenhum.', ok=True),
  C('Whether a person or a machine produced it', 'Se foi uma pessoa ou uma máquina que o produziu',
    'Machines write free text too, and people fill in tables.', 'Máquinas também escrevem texto livre, e pessoas preenchem tabelas.')),
Q('ex-35d974y0', 'three-shapes', 'medium',
  ('A CSV file has a header line naming its columns. Why is that not enough to make its data structured in this lesson’s sense?',
   'Um arquivo CSV tem uma linha de cabeçalho com os nomes das colunas. Por que isso não basta para o dado ser estruturado no sentido desta aula?'),
  ('Look at what the header leaves out.', 'Veja o que o cabeçalho deixa de fora.'),
  C('It names columns but declares no types', 'Dá nome às colunas, mas não declara tipos',
    'Right: `12` and `12 min` sit in one column without complaint.', 'Isso: `12` e `12 min` convivem numa coluna sem reclamação.', ok=True),
  C('The header is optional, so most CSV files leave it out', 'O cabeçalho é opcional, então a maioria dos CSV não o tem',
    'Whether it is there or not, it carries names only.', 'Esteja ele lá ou não, ele carrega só nomes.'),
  C('CSV cannot hold more than one table per file', 'O CSV não comporta mais de uma tabela por arquivo',
    'True, and irrelevant: one table can still be unchecked.', 'Verdade, e irrelevante: uma tabela só também pode não ser conferida.'),
  C('Commas inside values break the columns apart', 'Vírgulas dentro dos valores quebram as colunas',
    'Quoting handles that; lesson 6 shows it. The missing piece is types.', 'As aspas resolvem isso; a aula 6 mostra. O que falta são os tipos.')),
Q('ex-cmg9qcjw', 'three-shapes', 'medium',
  ('Roda Livre’s app events arrive as JSON, and a program checks each one against a strict description before storing it, refusing any that differ. Which shape does that data behave like?',
   'Os eventos do aplicativo da Roda Livre chegam como JSON, e um programa confere cada um contra uma descrição rígida antes de guardá-lo, recusando os que diferem. Com que forma esse dado se comporta?'),
  ('The format is one thing; the check is another.', 'O formato é uma coisa; a conferência é outra.'),
  C('Semi-structured, because the file is JSON', 'Semiestruturado, porque o arquivo é JSON',
    'That sorts by format. A check at the door is what makes data structured.', 'Isso separa pelo formato. A conferência na porta é o que torna o dado estruturado.'),
  C('Unstructured, since nothing in it is a table yet', 'Não estruturado, já que nada nele é tabela ainda',
    'Every field has a name; nothing has to be interpreted.', 'Todo campo tem nome; nada precisa ser interpretado.'),
  C('A fourth shape the lesson does not name', 'Uma quarta forma que a aula não cita',
    'The three cover it: the question is where the schema lives.', 'As três dão conta: a pergunta é onde mora o esquema.'),
  C('Structured, since it is checked on the way in', 'Estruturado, já que é conferido na entrada',
    'Right: declared first, checked on write, like a table.', 'Isso: declarado antes, conferido na escrita, como uma tabela.', ok=True)),
Q('ex-2f41tk3d', 'three-shapes', 'easy',
  ('Which of these is unstructured data at Roda Livre?', 'Qual destes é dado não estruturado na Roda Livre?'),
  ('Where is the meaning kept?', 'Onde fica o significado?'),
  C('The station list in the app’s database', 'A lista de estações no banco do aplicativo',
    'A table with declared columns: structured.', 'Uma tabela com colunas declaradas: estruturado.'),
  C('A recording of a customer’s call to the help line about a dock', 'A gravação da ligação de um cliente para a central sobre uma doca',
    'Right: the meaning is in the sound, and somebody has to interpret it.', 'Isso: o significado está no som, e alguém precisa interpretá-lo.', ok=True),
  C('The JSON event sent when a ride ends', 'O evento JSON enviado quando a viagem termina',
    'Names travel with the values: semi-structured.', 'Os nomes viajam com os valores: semiestruturado.'),
  C('A sensor message with a dock id and a time', 'Uma mensagem de sensor com id da doca e hora',
    'Named fields: semi-structured at worst.', 'Campos com nome: semiestruturado, no máximo.')),
M('ex-zv5ydtcx', 'three-shapes', 'easy',
  ('Match each shape to where its schema lives.', 'Associe cada forma ao lugar onde mora o seu esquema.'),
  ('One of them has no schema at all.', 'Uma delas não tem esquema nenhum.'),
  [(('structured', 'estruturado'), ('in the table, declared before the data', 'na tabela, declarado antes do dado')),
   (('semi-structured', 'semiestruturado'), ('in each record, beside the values', 'em cada registro, ao lado dos valores')),
   (('unstructured', 'não estruturado'), ('nowhere; the meaning is in the content', 'em lugar nenhum; o sentido está no conteúdo'))]),
# ---- structured
Q('ex-rxmkhxaq', 'structured', 'easy',
  ('In `structured.py`, what happened to the ride whose `minutes` was `"9 min"`?',
   'No `structured.py`, o que aconteceu com a viagem cujo `minutes` era `"9 min"`?'),
  ('Read the last line the program printed.', 'Leia a última linha que o programa imprimiu.'),
  C('It was stored with an empty value for `minutes`', 'Foi guardada com `minutes` vazio',
    'pyarrow did not fill anything in; it refused.', 'O pyarrow não preencheu nada; ele recusou.'),
  C('It was stored as the number 9, with the text dropped', 'Foi guardada como o número 9, e o texto foi descartado',
    'Nothing guessed at the number; the value was refused whole.', 'Nada adivinhou o número; o valor foi recusado inteiro.'),
  C('It was refused, and the call built no table at all', 'Foi recusada, e a chamada não montou tabela nenhuma',
    'Right: the call raised an error and built nothing.', 'Isso: a chamada levantou um erro e não montou nada.', ok=True),
  C('It was stored, and the error appeared when reading', 'Foi guardada, e o erro só apareceu na hora da leitura',
    'That is what `loose.py` did. Here the check ran on write.', 'Isso foi o `loose.py`. Aqui a conferência rodou na escrita.')),
Q('ex-wtjrr25p', 'structured', 'medium',
  ('`loose.py` and `structured.py` met the same `"9 min"`. What was different about the failure in `loose.py`?',
   'O `loose.py` e o `structured.py` encontraram o mesmo `"9 min"`. O que foi diferente na falha do `loose.py`?'),
  ('Who was running the program when it stopped?', 'Quem estava rodando o programa quando ele parou?'),
  C('It surfaced at the reader, after the file was stored', 'Apareceu para quem lê, depois de o arquivo ser guardado',
    'Right: the writer was never told.', 'Isso: quem escreveu nunca soube.', ok=True),
  C('It printed a wrong total and carried on', 'Imprimiu um total errado e seguiu em frente',
    'It stopped with a `ValueError`; it was loud, just late.', 'Ele parou com um `ValueError`; foi barulhento, só que tarde.'),
  C('It never failed, because CSV has a text type for every value', 'Nunca falhou, porque o CSV tem um tipo texto para todo valor',
    'The write succeeded, but the sum on line 17 failed.', 'A escrita deu certo, mas a soma da linha 17 falhou.'),
  C('It failed earlier, as soon as the file was opened', 'Falhou antes, assim que o arquivo foi aberto',
    'Opening and reading worked; adding up the minutes did not.', 'Abrir e ler funcionaram; somar os minutos não.')),
Z('ex-1w09czas', 'structured', 'easy',
  ('Checking every value against a declared schema at the moment it is stored is called schema on ___.',
   'Conferir cada valor contra um esquema declarado no momento em que ele é guardado se chama schema on ___.'),
  ('The opposite of reading.', 'O contrário de ler.'),
  ['write'], ['write', 'escrita']),
Q('ex-53bxbs9g', 'structured', 'medium',
  ('Why is `started_at` declared as a timestamp in `structured.py` rather than as a string?',
   'Por que `started_at` é declarado como timestamp no `structured.py` em vez de texto?'),
  ('Think about every reader after the writer.', 'Pense em todo leitor depois de quem escreve.'),
  C('A string column would make the table larger on disk', 'Uma coluna de texto deixaria a tabela maior no disco',
    'Size is not the reason given; meaning is.', 'Tamanho não é a razão dada; significado é.'),
  C('pyarrow cannot store dates written as text', 'O pyarrow não consegue guardar datas escritas como texto',
    'It can store any text; then it would be a string, not a time.', 'Ele guarda qualquer texto; aí seria um texto, não uma hora.'),
  C('Strings cannot carry the São Paulo time zone', 'Texto não consegue carregar o fuso de São Paulo',
    'The JSON events carry `-03:00` inside a string. What they lack is a type.', 'Os eventos JSON carregam `-03:00` dentro de um texto. O que falta é um tipo.'),
  C('So every reader gets a time, not text to parse', 'Para todo leitor receber uma hora, e não um texto',
    'Right: sorting and grouping by hour work directly.', 'Isso: ordenar e agrupar por hora funcionam direto.', ok=True)),
Q('ex-rhpezjm2', 'structured', 'hard',
  ('Marta asks for a new column, `helmet`, in the rides table. In a structured table, what does that take?',
   'Marta pede uma coluna nova, `helmet`, na tabela de viagens. Numa tabela estruturada, o que isso exige?'),
  ('What did the section call changing a schema later?', 'Como a seção chamou mudar um esquema depois?'),
  C('Nothing: the next rows can include it', 'Nada: as próximas linhas já podem trazê-la',
    'That is semi-structured data. A table refuses a field it does not have.', 'Isso é dado semiestruturado. Uma tabela recusa um campo que não tem.'),
  C('A deliberate change to the schema', 'Uma mudança deliberada no esquema',
    'Right: a migration, made on purpose and agreed with the readers.', 'Isso: uma migração, feita de propósito e combinada com os leitores.', ok=True),
  C('A new table, because tables can never change', 'Uma tabela nova, porque tabelas nunca mudam',
    'Tables change; the change is just deliberate.', 'Tabelas mudam; a mudança só é deliberada.'),
  C('Converting the whole table to JSON first', 'Converter a tabela inteira para JSON antes',
    'Changing the format would throw away the check that made the table worth having.', 'Mudar o formato jogaria fora a conferência que fazia a tabela valer a pena.')),
# ---- semi-structured
N('ex-2jv7262t', 'semi-structured', 'easy',
  ('How many of the six events of 15 September have an `end`?', 'Quantos dos seis eventos de 15 de setembro têm `end`?'),
  ('The `grep -c` count.', 'A contagem do `grep -c`.'),
  5, 0, ('events', 'eventos')),
Q('ex-0v0zx5ga', 'semi-structured', 'medium',
  ('Ride `R000104` has no `end` in its event. What does that mean?', 'A viagem `R000104` não tem `end` no evento. O que isso quer dizer?'),
  ('Look at what the generator does every fourth ride.', 'Veja o que o gerador faz a cada quarta viagem.'),
  C('The event was cut short in transit', 'O evento foi cortado no caminho',
    'The line is complete JSON; nothing was lost.', 'A linha é um JSON completo; nada se perdeu.'),
  C('The app has a bug that drops the field at random', 'O aplicativo tem um defeito que perde o campo ao acaso',
    'It is absent on purpose, every fourth ride.', 'Ele falta de propósito, a cada quarta viagem.'),
  C('The bicycle was returned to its own start station', 'A bicicleta foi devolvida na própria estação de partida',
    'Those rides do have an `end`: R000103 and R000105.', 'Essas viagens têm `end`: R000103 e R000105.'),
  C('It had not ended when the event was sent', 'Ela não tinha terminado quando o evento saiu',
    'Right, and a reader that fills in a default would report it finished.', 'Isso, e um leitor que preenche um padrão a daria por terminada.', ok=True)),
MC('ex-5p5f072g', 'semi-structured', 'medium',
  ('Which of these are types a JSON value can have? Choose all that apply.',
   'Quais destes são tipos que um valor JSON pode ter? Marque todos os que se aplicam.'),
  ('Six types, and one notable absence.', 'Seis tipos, e uma ausência notável.'),
  C('array', 'array', 'Yes: `charges` is one.', 'Sim: `charges` é um.', ok=True),
  C('timestamp', 'timestamp', 'No: `at` is a string that looks like a time.', 'Não: `at` é um texto que parece uma hora.'),
  C('object', 'objeto', 'Yes: `bike` is one.', 'Sim: `bike` é um.', ok=True),
  C('null', 'nulo', 'Yes, one of the six.', 'Sim, um dos seis.', ok=True)),
Q('ex-5hb3ztg9', 'semi-structured', 'easy',
  ('Why does `charges` not fit in a single table column?', 'Por que `charges` não cabe numa única coluna de tabela?'),
  ('Count the charges of two different rides.', 'Conte as cobranças de duas viagens diferentes.'),
  C('It is a list, and its length varies from one ride to the next', 'É uma lista, e o tamanho dela muda de uma viagem para outra',
    'Right: a cell holds one value, and a ride has one to three charges.', 'Isso: uma célula guarda um valor, e uma viagem tem de uma a três cobranças.', ok=True),
  C('Its items are objects, and tables only hold numbers', 'Os itens são objetos, e tabelas só guardam números',
    'Tables hold text and times too. The trouble is how many there are.', 'Tabelas guardam texto e horas também. O problema é quantos são.'),
  C('Its values are in cents rather than in reais', 'Os valores estão em centavos e não em reais',
    'The unit has nothing to do with the shape.', 'A unidade não tem nada a ver com a forma.'),
  C('It is nested two levels deeper than `bike` is', 'Está aninhado dois níveis mais fundo que `bike`',
    '`bike` is nested too, and flattens fine. Arrays are the problem.', '`bike` também é aninhado, e achata sem problema. O array é que é.')),
Q('ex-3wzrtpkv', 'semi-structured', 'medium',
  ('With schema on read, who decides what a missing `coupon` means?', 'Com esquema na leitura, quem decide o que quer dizer um `coupon` ausente?'),
  ('Nothing was declared at the door.', 'Nada foi declarado na porta.'),
  C('The JSON standard, which defines missing as null', 'O padrão JSON, que define ausente como nulo',
    'JSON says nothing about a key that is not there.', 'O JSON não diz nada sobre uma chave que não está lá.'),
  C('The app team, who sent the event', 'O time do aplicativo, que mandou o evento',
    'They decided to leave it out; what it means downstream is not theirs to enforce.', 'Eles decidiram omiti-lo; o que isso significa adiante não cabe a eles impor.'),
  C('Each program that reads the events', 'Cada programa que lê os eventos',
    'Right, which is why two readers can decide differently.', 'Isso, e é por isso que dois leitores podem decidir diferente.', ok=True),
  C('The file, through its first line', 'O arquivo, pela primeira linha',
    'JSON Lines has no header; each line stands alone.', 'O JSON Lines não tem cabeçalho; cada linha vale sozinha.')),
# ---- flattening
N('ex-qzgctk2q', 'flattening', 'easy',
  ('How many rows did exploding `charges` produce for the six rides of 15 September?',
   'Quantas linhas a explosão de `charges` produziu para as seis viagens de 15 de setembro?'),
  ('The line ending in `charge rows`.', 'A linha que termina em `charge rows`.'),
  12, 0, ('rows', 'linhas')),
Q('ex-e9ghsz25', 'flattening', 'medium',
  ('After the explode, somebody counts rows in the charges table to report how many rides there were. What do they get?',
   'Depois da explosão, alguém conta as linhas da tabela de cobranças para dizer quantas viagens houve. O que obtém?'),
  ('One row there is not one ride.', 'Uma linha ali não é uma viagem.'),
  C('Six, because every row carries a `ride_id`', 'Seis, porque toda linha leva um `ride_id`',
    'Carrying the id does not make the rows distinct; counting distinct ids would.', 'Levar o id não torna as linhas distintas; contar ids distintos tornaria.'),
  C('An error, because the table has no ride column', 'Um erro, porque a tabela não tem coluna de viagem',
    'It has `ride_id`, and nothing stops a count.', 'Ela tem `ride_id`, e nada impede uma contagem.'),
  C('Five, because the ride in progress has no charges', 'Cinco, porque a viagem em andamento não tem cobranças',
    'R000104 has its unlock charge.', 'A R000104 tem a taxa de desbloqueio.'),
  C('Twelve: one row per charge, which is not one row per ride', 'Doze: uma linha por cobrança, que não é uma linha por viagem',
    'Right: a quiet overcount, as trustworthy-looking as the right answer.', 'Isso: uma contagem a mais silenciosa, com cara de resposta certa.', ok=True)),
Q('ex-frvhdz8d', 'flattening', 'medium',
  ('What does flattening do to the nested object `bike`?', 'O que achatar faz com o objeto aninhado `bike`?'),
  ('The program joins names with a dot.', 'O programa junta nomes com um ponto.'),
  C('Moves it into a table of its own, one row per bicycle', 'Move para uma tabela própria, uma linha por bicicleta',
    'That is the explode, which the lesson keeps for arrays.', 'Isso é a explosão, que a aula reserva para arrays.'),
  C('Drops it, since only top-level fields become columns', 'Descarta, já que só campos do topo viram colunas',
    '`flat` walks into it; only lists are skipped.', 'O `flat` entra nele; só listas são puladas.'),
  C('Stores the whole object as one text column', 'Guarda o objeto inteiro numa coluna de texto',
    'Possible, but then every reader parses JSON again. The program does not.', 'Possível, mas aí todo leitor interpreta JSON de novo. O programa não faz isso.'),
  C('Makes columns `bike.id` and `bike.battery`', 'Cria as colunas `bike.id` e `bike.battery`',
    'Right: still one row per event, with longer names.', 'Isso: ainda uma linha por evento, com nomes mais longos.', ok=True)),
N('ex-pd6v47we', 'flattening', 'easy',
  ('How many columns did `flatten.py` discover in the events of 15 September?',
   'Quantas colunas o `flatten.py` descobriu nos eventos de 15 de setembro?'),
  ('The first line of its output.', 'A primeira linha da saída.'),
  9, 0, ('columns', 'colunas')),
Q('ex-j009dkrr', 'flattening', 'hard',
  ('The sum of cents across the exploded charges table, 3425, is correct. Summing `end.minutes` across the same table is not. Why the difference?',
   'A soma dos centavos na tabela de cobranças explodida, 3425, está certa. Somar `end.minutes` na mesma tabela não está. Por que a diferença?'),
  ('Ask what each number belongs to.', 'Pergunte a quem cada número pertence.'),
  C('Cents are whole numbers and minutes are not whole', 'Centavos são números inteiros e minutos não são inteiros',
    'Both are integers in the events. The difference is which table they belong to.', 'Os dois são inteiros nos eventos. A diferença é a que tabela pertencem.'),
  C('Minutes belong to the ride, and a ride repeats', 'Minutos pertencem à viagem, e a viagem se repete',
    'Right: each charge is there once; each ride is there two or three times.', 'Isso: cada cobrança está lá uma vez; cada viagem, duas ou três.', ok=True),
  C('The ride in progress has no minutes, which spoils the total', 'A viagem em andamento não tem minutos, o que estraga o total',
    'A missing value would make the sum smaller, not repeated.', 'Um valor ausente deixaria a soma menor, não repetida.'),
  C('The explode sorted the rows, and minutes depend on order', 'A explosão ordenou as linhas, e minutos dependem da ordem',
    'A sum does not depend on order.', 'Uma soma não depende da ordem.')),
# ---- schema-drift
Q('ex-8jcyyfg5', 'schema-drift', 'easy',
  ('What did version 4.2 of the app change in the events of 16 September?',
   'O que a versão 4.2 do aplicativo mudou nos eventos de 16 de setembro?'),
  ('The last two lines `drift.py` printed.', 'As duas últimas linhas que o `drift.py` imprimiu.'),
  C('It removed `coupon` and renamed `end` to `finish`', 'Tirou `coupon` e renomeou `end` para `finish`',
    'Nothing was reported gone; both are still there.', 'Nada foi dado como sumido; os dois continuam lá.'),
  C('It started sending every event twice over', 'Passou a mandar cada evento duas vezes',
    'That is a duplicate, not a change of shape.', 'Isso é duplicata, não mudança de forma.'),
  C('Battery became text; `helmet` was added', 'A bateria virou texto; `helmet` foi acrescentado',
    'Right: one type change and one new field.', 'Isso: uma mudança de tipo e um campo novo.', ok=True),
  C('It moved `station` out of `start` to the top level', 'Tirou `station` de dentro de `start` e levou para o topo',
    'The paths are unchanged; `drift.py` would have reported both.', 'Os caminhos não mudaram; o `drift.py` teria acusado os dois.')),
Q('ex-h2qj4e14', 'schema-drift', 'medium',
  ('Why is the changed type of `bike.battery` more dangerous than the new field `helmet`?',
   'Por que o tipo alterado de `bike.battery` é mais perigoso que o campo novo `helmet`?'),
  ('Which one does an existing reader touch?', 'Em qual deles um leitor que já existe mexe?'),
  C('Readers that already exist sum and average the battery', 'Leitores que já existem somam e tiram média da bateria',
    'Right: something already sums it, and now meets `"58%"`.', 'Isso: algo já soma esse campo, e agora encontra `"58%"`.', ok=True),
  C('New fields are refused by JSON, so `helmet` is dropped', 'O JSON recusa campos novos, então `helmet` se perde',
    'JSON refuses nothing; `helmet` arrived fine.', 'O JSON não recusa nada; `helmet` chegou sem problema.'),
  C('A boolean takes less space than a percentage string', 'Um booleano ocupa menos espaço que um texto de porcentagem',
    'Size is not the danger; what readers do with the value is.', 'Tamanho não é o perigo; o que os leitores fazem com o valor é.'),
  C('`helmet` is in a different file from the battery', '`helmet` fica num arquivo diferente da bateria',
    'Both are in every event of 16 September.', 'Os dois estão em todos os eventos de 16 de setembro.')),
Q('ex-46nyv9yj', 'schema-drift', 'hard',
  ('The battery values `"100%"` and `"58%"` are loaded into a text column. What happens when a chart sorts by battery?',
   'Os valores de bateria `"100%"` e `"58%"` são carregados numa coluna de texto. O que acontece quando um gráfico ordena por bateria?'),
  ('Text is compared one character at a time.', 'Texto é comparado um caractere por vez.'),
  C('The load fails, because text cannot be sorted', 'A carga falha, porque texto não pode ser ordenado',
    'Text sorts; it sorts by characters, not by value.', 'Texto se ordena; por caractere, não por valor.'),
  C('The database removes the `%` and sorts the numbers', 'O banco tira o `%` e ordena os números',
    'Nothing strips it; the column holds text.', 'Nada o tira; a coluna guarda texto.'),
  C('`"100%"` sorts before `"58%"`, and the chart is wrong without any error', '`"100%"` fica antes de `"58%"`, e o gráfico sai errado sem erro nenhum',
    'Right: `1` sorts before `5`, and nothing complains.', 'Isso: `1` vem antes de `5`, e nada reclama.', ok=True),
  C('A `TypeError` stops the chart from drawing', 'Um `TypeError` impede o gráfico de ser desenhado',
    'That is Python adding numbers to text. Sorting text raises nothing.', 'Isso é o Python somando número com texto. Ordenar texto não levanta nada.')),
Z('ex-v8465n7b', 'schema-drift', 'easy',
  ('The shape of incoming data changing without anybody downstream being told is called schema ___.',
   'A forma do dado que chega mudar sem ninguém adiante ser avisado se chama schema ___.'),
  ('A boat without an anchor does it.', 'Um barco sem âncora faz isso.'),
  ['drift'], ['drift', 'deriva']),
O('ex-xjmdvq37', 'schema-drift', 'medium',
  ('Order these places to notice drift, from the cheapest to the most expensive.',
   'Ordene estes lugares de perceber a deriva, do mais barato ao mais caro.'),
  ('The later it is noticed, the more data holds both shapes.', 'Quanto mais tarde percebida, mais dado tem as duas formas.'),
  [('a check on each batch, at the door', 'uma conferência em cada lote, na porta'),
   ('a report that breaks in a reader', 'um relatório que quebra num leitor'),
   ('a quiet conversion nobody notices', 'uma conversão silenciosa que ninguém percebe')],
  ('Never noticing is the most expensive, because every number built on it is wrong.',
   'Nunca perceber é o mais caro, porque todo número construído em cima está errado.')),
# ---- unstructured
Q('ex-g3bjwmjb', 'unstructured', 'easy',
  ('In a support email, which part is unstructured?', 'Num e-mail de suporte, que parte é não estruturada?'),
  ('Which part has no field names?', 'Que parte não tem nome de campo?'),
  C('The list of attachments and their sizes', 'A lista de anexos e seus tamanhos',
    'Named fields: metadata, structured.', 'Campos com nome: metadados, estruturado.'),
  C('The time it was received', 'A hora em que chegou',
    'A field with a name and a type.', 'Um campo com nome e tipo.'),
  C('The id of the customer who sent it', 'O id do cliente que o enviou',
    'Metadata again: `C0042` is a value in a named field.', 'Metadados de novo: `C0042` é um valor num campo com nome.'),
  C('The body the customer wrote', 'O corpo que o cliente escreveu',
    'Right: the meaning is in the words.', 'Isso: o significado está nas palavras.', ok=True)),
N('ex-w78nh1jh', 'unstructured', 'easy',
  ('Of the six emails, how many did the pattern in `emails.py` match to the right station?',
   'Dos seis e-mails, quantos o padrão do `emails.py` ligou à estação certa?'),
  ('Read the last column against the bodies.', 'Leia a última coluna contra os corpos.'),
  2, 0, ('emails', 'e-mails')),
Q('ex-fh1rp0k2', 'unstructured', 'medium',
  ('Why did email M05 produce `ST10` when it is not about a station?', 'Por que o e-mail M05 produziu `ST10` se ele não é sobre uma estação?'),
  ('The customer lives somewhere.', 'O cliente mora em algum lugar.'),
  C('Batel is also the neighbourhood the customer lives in, and the pattern cannot tell', 'Batel também é o bairro onde o cliente mora, e o padrão não distingue',
    'Right: the pattern matches the word, not the meaning.', 'Isso: o padrão casa a palavra, não o sentido.', ok=True),
  C('The customer’s id happens to contain the code ST10', 'O id do cliente por acaso contém o código ST10',
    'The pattern searches the body only, and C0019 is not ST10.', 'O padrão procura só no corpo, e C0019 não é ST10.'),
  C('Regular expressions guess when nothing matches exactly', 'Expressões regulares chutam quando nada casa exatamente',
    'A pattern never guesses; it found the exact word.', 'Um padrão nunca chuta; ele achou a palavra exata.'),
  C('The app attached the customer’s location to the body', 'O aplicativo anexou a localização do cliente ao corpo',
    'The body is what the customer wrote, word for word.', 'O corpo é o que o cliente escreveu, palavra por palavra.')),
MC('ex-0pc4tnv7', 'unstructured', 'medium',
  ('Which emails named a station that the pattern missed? Choose all that apply.',
   'Quais e-mails citavam uma estação que o padrão não achou? Marque todos os que se aplicam.'),
  ('Look for a `-` in the last column.', 'Procure um `-` na última coluna.'),
  C('M03, “the Botanical Garden”', 'M03, “the Botanical Garden”', 'Yes: the name in English.', 'Sim: o nome em inglês.', ok=True),
  C('M04, “Rua 15”', 'M04, “Rua 15”', 'Yes: XV written as a number.', 'Sim: XV escrito como número.', ok=True),
  C('M02, Largo da Ordem', 'M02, Largo da Ordem', 'No: found, as ST06.', 'Não: achado, como ST06.'),
  C('M06, “Opera de Arame”', 'M06, “Opera de Arame”', 'Yes: the accent was missing.', 'Sim: faltou o acento.', ok=True)),
Q('ex-873ekz65', 'unstructured', 'hard',
  ('A language model starts extracting stations from the emails. Which habit from the section matters most once it does?',
   'Um modelo de linguagem passa a extrair estações dos e-mails. Que hábito da seção mais importa a partir daí?'),
  ('Its output is a derived value.', 'A saída dele é um valor derivado.'),
  C('Deleting the email bodies once the station has been extracted', 'Apagar os corpos dos e-mails depois que a estação foi extraída',
    'The originals are what a better extractor runs on next year.', 'Os originais são o que um extrator melhor vai rodar no ano que vem.'),
  C('Trusting its answers, since it reads like a person does', 'Confiar nas respostas, já que ele lê como uma pessoa',
    'It is wrong some of the time too, in its own ways.', 'Ele também erra parte das vezes, do seu jeito.'),
  C('Recording which program made each value', 'Registrar qual programa fez cada valor',
    'Right, with the original kept beside it.', 'Isso, com o original guardado ao lado.', ok=True),
  C('Mixing its values into the column staff type by hand', 'Misturar os valores na coluna que a equipe digita à mão',
    'Then nobody can tell a guess from a fact.', 'Aí ninguém distingue palpite de fato.')),
Q('ex-19qnx97d', 'unstructured', 'medium',
  ('Marta asks how many complaints arrived on Monday and from how many customers. What does answering it need?',
   'Marta pergunta quantas reclamações chegaram na segunda e de quantos clientes. Do que a resposta precisa?'),
  ('Which part of an email holds the date and the sender?', 'Que parte de um e-mail guarda a data e o remetente?'),
  C('A model that reads every body', 'Um modelo que leia todos os corpos',
    'Nothing in the question is inside the body.', 'Nada da pergunta está dentro do corpo.'),
  C('The station pattern from `emails.py`, extended', 'O padrão de estações do `emails.py`, ampliado',
    'Stations are not part of the question.', 'Estações não fazem parte da pergunta.'),
  C('The photos attached to each complaint', 'As fotos anexadas a cada reclamação',
    'Counting them needs metadata, not pixels.', 'Contá-las precisa de metadados, não de pixels.'),
  C('Only the metadata of each email', 'Só os metadados de cada e-mail',
    'Right: time and customer are named fields.', 'Isso: hora e cliente são campos com nome.', ok=True)),
# ---- where-the-schema-lives
M('ex-hvz1m918', 'where-the-schema-lives', 'medium',
  ('Match each statement to the approach it describes.', 'Associe cada afirmação à abordagem que ela descreve.'),
  ('Ask when the check runs.', 'Pergunte quando a conferência roda.'),
  [(('stores everything that was sent', 'guarda tudo o que foi enviado'), ('schema on read', 'esquema na leitura')),
   (('stores only what fitted', 'guarda só o que coube'), ('schema on write', 'esquema na escrita')),
   (('the writer hears about a bad value', 'quem escreve fica sabendo de um valor ruim'), ('a check at the door', 'uma conferência na porta')),
   (('each reader repeats the same check', 'cada leitor repete a mesma conferência'), ('a check in every reader', 'uma conferência em cada leitor'))]),
Q('ex-bedm0h3s', 'where-the-schema-lives', 'medium',
  ('Caio strips the `%` from `bike.battery`, and an analyst skips the rows that have one. What follows?',
   'O Caio tira o `%` de `bike.battery`, e um analista pula as linhas que o têm. O que acontece?'),
  ('One file, two readers, two decisions.', 'Um arquivo, dois leitores, duas decisões.'),
  C('Both get the same average, since the data in the file is the same', 'Os dois chegam à mesma média, já que o dado no arquivo é o mesmo',
    'The data is the same; their checks are not.', 'O dado é o mesmo; as conferências não.'),
  C('Two different averages from one file, each of them confident', 'Duas médias diferentes de um arquivo só, cada uma confiante',
    'Right: the same check, written twice, disagreeing.', 'Isso: a mesma conferência, escrita duas vezes, discordando.', ok=True),
  C('The file refuses the second reader', 'O arquivo recusa o segundo leitor',
    'A stored file refuses no reader; only a write can be refused.', 'Um arquivo guardado não recusa leitor; só uma escrita pode ser recusada.'),
  C('An error in both programs, because JSON forbids `%`', 'Um erro nos dois programas, porque o JSON proíbe `%`',
    '`"58%"` is a valid JSON string.', '`"58%"` é um texto JSON válido.')),
Q('ex-6ds5nap7', 'where-the-schema-lives', 'hard',
  ('A batch is refused by a strict check at three in the morning. What is the cost that schema on write adds here and schema on read does not?',
   'Um lote é recusado por uma conferência rígida às três da manhã. Que custo o esquema na escrita acrescenta aqui e o esquema na leitura não?'),
  ('What was stored?', 'O que ficou guardado?'),
  C('Every reader must check the batch again later', 'Todo leitor precisa conferir o lote de novo depois',
    'That is schema on read’s cost, not this one.', 'Esse é o custo do esquema na leitura, não este.'),
  C('The bad values are stored and spread to readers', 'Os valores ruins são guardados e se espalham para os leitores',
    'The refusal is exactly what stopped them being stored.', 'A recusa é justamente o que impediu que fossem guardados.'),
  C('The refused batch is stored nowhere, and somebody has to fetch it again', 'O lote recusado não fica guardado em lugar nenhum, e alguém precisa buscá-lo de novo',
    'Right: somebody has to fetch it again.', 'Isso: alguém precisa buscá-lo de novo.', ok=True),
  C('The table loses the schema it had declared', 'A tabela perde o esquema que tinha declarado',
    'The schema is untouched; the batch is what is gone.', 'O esquema fica intacto; o que sumiu foi o lote.')),
O('ex-jexassq3', 'where-the-schema-lives', 'medium',
  ('Put the steps of Roda Livre’s app events in the order a platform runs them.',
   'Ponha os passos dos eventos do aplicativo da Roda Livre na ordem em que uma plataforma os executa.'),
  ('Land first, decide later.', 'Pousar primeiro, decidir depois.'),
  [('the app sends a JSON event', 'o aplicativo envia um evento JSON'),
   ('the event lands as it came in the raw zone', 'o evento pousa como veio na zona bruta'),
   ('a nightly job flattens and checks it', 'um job noturno o achata e confere'),
   ('analysts query the curated tables', 'os analistas consultam as tabelas curadas')],
  ('The raw zone comes before the check, so nothing is lost to a check that was too strict.',
   'A zona bruta vem antes da conferência, para nada se perder numa conferência rígida demais.')),
# ---- storing-each-shape
M('ex-j2tz6yjm', 'storing-each-shape', 'easy',
  ('Match each kind of storage to what it is built around.', 'Associe cada tipo de armazenamento àquilo em torno do que ele é construído.'),
  ('Tables, documents, bytes.', 'Tabelas, documentos, bytes.'),
  [(('relational database', 'banco de dados relacional'), ('tables with a declared schema', 'tabelas com esquema declarado')),
   (('document store', 'banco de documentos'), ('JSON documents that may differ', 'documentos JSON que podem diferir')),
   (('object storage', 'armazenamento de objetos'), ('files under keys, unread', 'arquivos sob chaves, sem ler o conteúdo'))]),
Q('ex-29z5282a', 'storing-each-shape', 'medium',
  ('Where do the photos customers attach of a damaged bicycle most naturally go?',
   'Onde vão, com mais naturalidade, as fotos de bicicleta danificada que os clientes anexam?'),
  ('The store does not need to look inside them.', 'O armazenamento não precisa olhar dentro delas.'),
  C('A column of the rides table, with one photo per ride', 'Uma coluna da tabela de viagens, uma foto por viagem',
    'A photo belongs to a complaint, and pixels in a table cell help no query.', 'Uma foto pertence a uma reclamação, e pixels numa célula não ajudam consulta nenhuma.'),
  C('A document store, so the pixels can be queried by field', 'Um banco de documentos, para consultar os pixels por campo',
    'Pixels have no fields to query.', 'Pixels não têm campos para consultar.'),
  C('Nowhere: unstructured data is not worth keeping', 'Em lugar nenhum: dado não estruturado não vale guardar',
    'The originals are what a better extractor will run on.', 'Os originais são o que um extrator melhor vai rodar.'),
  C('Object storage, metadata beside it', 'Armazenamento de objetos, com metadados ao lado',
    'Right: the bytes as they came, and rows that say what they are.', 'Isso: os bytes como vieram, e linhas dizendo o que são.', ok=True)),
Q('ex-5fybs0ta', 'storing-each-shape', 'medium',
  ('What does a document store let you do that this lesson’s `flatten.py` had to do by hand first?',
   'O que um banco de documentos permite fazer que o `flatten.py` desta aula teve de fazer à mão antes?'),
  ('Think of `bike.battery` below 20.', 'Pense em `bike.battery` abaixo de 20.'),
  C('Find documents by a field nested inside them, such as `bike.battery`', 'Achar documentos por um campo aninhado dentro deles, como `bike.battery`',
    'Right: no flattening first.', 'Isso: sem achatar antes.', ok=True),
  C('Refuse documents whose types differ from the first one', 'Recusar documentos cujos tipos diferem do primeiro',
    'It does not require documents to agree; that is the price.', 'Ele não exige que os documentos concordem; esse é o preço.'),
  C('Store photos and recordings beside the events', 'Guardar fotos e gravações ao lado dos eventos',
    'That is object storage’s job.', 'Esse é o trabalho do armazenamento de objetos.'),
  C('Turn `"58%"` back into the number 58 when reading', 'Transformar `"58%"` de novo no número 58 ao ler',
    'Every query still has to cope with it.', 'Toda consulta continua tendo de lidar com ele.')),
Q('ex-q9rv1sfy', 'storing-each-shape', 'hard',
  ('A table in SQLite has a column declared `INTEGER`, and the table is not `STRICT`. Somebody inserts `"9 min"`. What happens?',
   'Uma tabela no SQLite tem uma coluna declarada `INTEGER`, e a tabela não é `STRICT`. Alguém insere `"9 min"`. O que acontece?'),
  ('The section named SQLite’s one difference.', 'A seção citou a única diferença do SQLite.'),
  C('SQLite refuses the row, like any relational database', 'O SQLite recusa a linha, como qualquer banco relacional',
    'Only a `STRICT` table refuses it.', 'Só uma tabela `STRICT` a recusa.'),
  C('SQLite converts it to the number 9 and drops the text', 'O SQLite converte para o número 9 e descarta o texto',
    'It keeps the value as it came.', 'Ele mantém o valor como veio.'),
  C('The value is stored, wrong type and all', 'O valor é guardado, com tipo errado e tudo',
    'Right: the check a table usually gives is not there.', 'Isso: a conferência que uma tabela costuma dar não está lá.', ok=True),
  C('The whole database file becomes unreadable', 'O arquivo do banco inteiro fica ilegível',
    'Nothing is damaged; one value is simply the wrong type.', 'Nada se estraga; um valor só está com o tipo errado.')),
# ---- drill
Q('ex-re3k62fk', 'drill', 'medium',
  ('A sensor sends `{"dock": "ST03-07", "bike": null, "at": "2025-09-15T08:00:00-03:00"}` every minute, and the data team stores it as it arrives. Which shape is it?',
   'Um sensor manda `{"dock": "ST03-07", "bike": null, "at": "2025-09-15T08:00:00-03:00"}` a cada minuto, e o time de dados guarda como chega. Que forma é essa?'),
  ('Names beside values, nothing checked first.', 'Nomes ao lado dos valores, nada conferido antes.'),
  C('Structured, because every message has the same three fields every minute', 'Estruturado, porque toda mensagem tem os mesmos três campos a cada minuto',
    'Today they agree; nothing makes tomorrow’s agree.', 'Hoje elas concordam; nada obriga as de amanhã a concordar.'),
  C('Unstructured, because a sensor is not a person', 'Não estruturado, porque um sensor não é uma pessoa',
    'Who wrote it does not matter; the fields have names.', 'Quem escreveu não importa; os campos têm nome.'),
  C('Semi-structured: named fields, stored with nothing checked at the door', 'Semiestruturado: campos com nome, guardados sem conferência na porta',
    'Right: JSON stored as it came, schema on read.', 'Isso: JSON guardado como veio, esquema na leitura.', ok=True),
  C('None of the three, because `bike` is null', 'Nenhuma das três, porque `bike` é nulo',
    'null is a JSON value like any other.', 'null é um valor JSON como qualquer outro.')),
Q('ex-j3frxyrq', 'drill', 'hard',
  ('`drift.py` reported nothing between two batches, but every event in the second has `minutes` in seconds rather than minutes. Why did it stay silent?',
   'O `drift.py` não acusou nada entre dois lotes, mas todo evento do segundo traz `minutes` em segundos em vez de minutos. Por que ele ficou quieto?'),
  ('What does it compare?', 'O que ele compara?'),
  C('It only compares field names and types', 'Ele só compara nomes e tipos de campos',
    'Right: an int is still an int. Values need checks of their own, lesson 7’s.', 'Isso: um int continua int. Valores precisam de conferências próprias, as da aula 7.', ok=True),
  C('It reads only the first line of each file', 'Ele lê só a primeira linha de cada arquivo',
    'It reads every line; `infer` loops over the file.', 'Ele lê todas as linhas; o `infer` percorre o arquivo.'),
  C('Seconds and minutes are both stored as strings in JSON', 'Segundos e minutos são guardados como texto no JSON',
    'They are numbers; the type did not change.', 'São números; o tipo não mudou.'),
  C('It ignores fields nested inside `end`', 'Ele ignora campos aninhados dentro de `end`',
    'It walks into nested objects; `end.minutes` is in its report.', 'Ele entra nos objetos aninhados; `end.minutes` está no relatório.')),
N('ex-f8zts2pb', 'drill', 'medium',
  ('What was the sum of all the charges of 15 September, in cents?', 'Qual foi a soma de todas as cobranças de 15 de setembro, em centavos?'),
  ('The last line of `flatten.py`.', 'A última linha do `flatten.py`.'),
  3425, 0, ('cents', 'centavos')),
Z('ex-r4cwzer8', 'drill', 'medium',
  ('Turning an array into a second table, one row per item, each carrying the id of its parent, is called an ___.',
   'Transformar um array numa segunda tabela, uma linha por item, cada uma levando o id do pai, se chama ___.'),
  ('Spark’s name for it.', 'O nome que o Spark dá a isso.'),
  ['explode', 'unnest'], ['explosão', 'explodir', 'explode', 'unnest']),
Q('ex-1sqmgh3g', 'drill', 'hard',
  ('A new partner sends Roda Livre a nightly CSV whose columns change whenever their staff edit the spreadsheet. Which arrangement does this lesson argue for?',
   'Um parceiro novo manda à Roda Livre um CSV toda noite cujas colunas mudam sempre que a equipe dele edita a planilha. Que arranjo esta aula defende?'),
  ('Land first; decide in one place.', 'Pousar primeiro; decidir num lugar só.'),
  C('Refuse every file that differs, and keep only the ones that fit', 'Recusar todo arquivo que difere, e guardar só os que cabem',
    'Then a changed file is stored nowhere and has to be fetched again.', 'Aí um arquivo alterado não fica guardado em lugar nenhum e precisa ser buscado de novo.'),
  C('Keep the raw file, check it in one job', 'Guardar o bruto, conferir num job só',
    'Right: nothing lost, and one check feeding the curated tables.', 'Isso: nada perdido, e uma conferência alimentando as tabelas curadas.', ok=True),
  C('Let each analyst read the CSV and adapt as it changes', 'Deixar cada analista ler o CSV e se adaptar quando mudar',
    'The same check written by every reader, and they will disagree.', 'A mesma conferência escrita por cada leitor, e eles vão discordar.'),
  C('Convert it to JSON, since JSON copes with any shape', 'Converter para JSON, já que o JSON aguenta qualquer forma',
    'A new format moves the problem; nobody has checked anything yet.', 'Um formato novo muda o problema de lugar; ninguém conferiu nada ainda.')),
]
