from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
# ---- bounded-and-unbounded
Q('ex-3wd3qfev', 'bounded-and-unbounded', 'easy',
  ('What separates batch processing from stream processing, according to this lesson?',
   'O que separa o processamento em lote do processamento de fluxo, segundo esta aula?'),
  ('Look at the input, not the clock.', 'Olhe para a entrada, não para o relógio.'),
  C('How fast each one can produce a result', 'A rapidez com que cada um produz um resultado',
    'Speed follows from the difference; a five-minute batch job is still batch.', 'A velocidade decorre da diferença; um job em lote de cinco minutos continua sendo lote.'),
  C('Whether the data it reads has an end', 'Se o dado que ele lê tem fim',
    'Right: bounded data can be waited for, unbounded data cannot.', 'Isso: dado limitado pode ser esperado, dado ilimitado não.', ok=True),
  C('Which programming language and which product is used to write each one', 'Qual linguagem e qual produto são usados para escrever cada um',
    'Both shapes are written in Python in this lesson.', 'Os dois formatos são escritos em Python nesta aula.'),
  C('How many machines the processing is spread over', 'Em quantas máquinas o processamento é distribuído',
    'One machine runs both here; distribution is lesson 9’s subject.', 'Uma máquina roda os dois aqui; distribuição é assunto da aula 9.')),
Q('ex-eca32jh2', 'bounded-and-unbounded', 'medium',
  ('A job runs every five minutes and counts the rides that started in the previous five minutes. What is it?',
   'Um job roda a cada cinco minutos e conta as viagens que começaram nos cinco minutos anteriores. O que ele é?'),
  ('It waits for a piece to close, then reads all of it.', 'Ele espera um pedaço fechar e então lê tudo.'),
  C('A stream processor, because five minutes is close to real time', 'Um processador de fluxo, porque cinco minutos é quase tempo real',
    'Frequency does not make a stream; it still processes closed pieces.', 'Frequência não faz um fluxo; ele continua processando pedaços fechados.'),
  C('Neither, since a window that short is not a batch', 'Nenhum dos dois, já que uma janela tão curta não é um lote',
    'A batch can be any length, from a day to a few seconds.', 'Um lote pode ter qualquer tamanho, de um dia a poucos segundos.'),
  C('A batch job, run over short windows each of which has closed', 'Um job em lote, rodado sobre janelas curtas que já fecharam',
    'Right: bounded pieces, each processed once it is closed.', 'Isso: pedaços limitados, cada um processado depois de fechar.', ok=True),
  C('A stream processor that has been configured to wait five minutes', 'Um processador de fluxo configurado para esperar cinco minutos',
    'It reads nothing between runs; it is started on a schedule.', 'Ele não lê nada entre execuções; é iniciado por agendamento.')),
Q('ex-g1ffdvfw', 'bounded-and-unbounded', 'easy',
  ('Which of these is unbounded data?', 'Qual destes é um dado ilimitado?'),
  ('Ask whether you could ever wait for all of it.', 'Pergunte se daria para esperar por tudo.'),
  C('The September rides export', 'A exportação de viagens de setembro',
    'September ended; the export has a last row.', 'Setembro acabou; a exportação tem uma última linha.'),
  C('A file uploaded by the maintenance team yesterday', 'Um arquivo que a equipe de manutenção enviou ontem',
    'A file that has been uploaded is finished.', 'Um arquivo já enviado está terminado.'),
  C('The readings the dock sensors keep sending, day after day', 'As leituras que os sensores das docas não param de mandar',
    'Right: they go on for as long as the company exists.', 'Isso: elas continuam enquanto a empresa existir.', ok=True),
  C('The `docks.jsonl` file written by `sensors.py`', 'O arquivo `docks.jsonl` escrito pelo `sensors.py`',
    'The program stopped writing, so the file is bounded; the lesson reads it as if it were not.', 'O programa parou de escrever, então o arquivo é limitado; a aula o lê como se não fosse.')),
Z('ex-1evtasfr', 'bounded-and-unbounded', 'easy',
  ('Data that has an end, so that you can wait for all of it, is called ___ data.',
   'Dado que tem fim, de modo que dá para esperar por todo ele, se chama dado ___.'),
  ('Batch processing works on it.', 'É com ele que o processamento em lote trabalha.'),
  ['bounded'], ['limitado', 'bounded']),
# ---- batch
N('ex-8asyeb6f', 'batch', 'easy',
  ('How many rides did the job run "as of" 01:00 on Tuesday count for Monday?',
   'Quantas viagens o job rodado "como se fosse" 01:00 de terça contou para a segunda?'),
  ('The first run, before the backfill.', 'A primeira execução, antes do backfill.'),
  118, 0, ('rides', 'viagens')),
Q('ex-n3e6epfz', 'batch', 'medium',
  ('Why did the 01:00 job miss two of Monday’s rides?', 'Por que o job da 01:00 deixou de contar duas viagens de segunda?'),
  ('Compare when they happened with when they arrived.', 'Compare quando aconteceram com quando chegaram.'),
  C('The job filtered on `arrived` instead of on `event_time` by mistake', 'O job filtrou por `arrived` em vez de `event_time`, por engano',
    'It filters the day on `event_time`; `asof` only limits what had arrived.', 'Ele filtra o dia por `event_time`; o `asof` só limita o que já tinha chegado.'),
  C('They had not reached the server when the job ran at 01:00', 'Ainda não tinham chegado ao servidor quando o job rodou à 01:00',
    'Right: Passeio Público sent them at 07:02 on Tuesday.', 'Isso: o Passeio Público as mandou às 07:02 de terça.', ok=True),
  C('The two rides started after midnight and belong to Tuesday instead', 'As duas viagens começaram depois da meia-noite e são de terça',
    'They started on Monday morning, at 09:21 and 09:36.', 'Elas começaram na manhã de segunda, às 09:21 e às 09:36.'),
  C('The CSV was appended to, not replaced', 'O CSV foi acrescentado, não substituído',
    'Appending would add rides, not lose them; and it is replaced.', 'Acrescentar somaria viagens, não perderia; e ele é substituído.')),
Q('ex-2qccfg6y', 'batch', 'easy',
  ('What is a backfill?', 'O que é um backfill?'),
  ('It is about the past.', 'É sobre o passado.'),
  C('Running a batch job again for windows already processed', 'Rodar de novo um job em lote para janelas que já tinham sido processadas',
    'Right, for late data, a fixed bug or a new column.', 'Isso, por dado atrasado, bug corrigido ou coluna nova.', ok=True),
  C('Filling the gaps in a table with values guessed from the rows around them', 'Preencher os buracos de uma tabela com valores estimados a partir das linhas vizinhas',
    'That is imputation, a cleaning technique, and it invents data.', 'Isso é imputação, uma técnica de limpeza, e ela inventa dado.'),
  C('Copying a database to a second machine so it has a backup', 'Copiar um banco de dados para uma segunda máquina, como cópia de segurança',
    'That is a backup or a replica; nothing is recomputed.', 'Isso é backup ou réplica; nada é recalculado.'),
  C('Sending a stream’s late events to a separate file', 'Mandar os eventos atrasados de um fluxo para um arquivo separado',
    'That is one way of handling late data in a stream.', 'Esse é um jeito de tratar dado atrasado num fluxo.')),
MC('ex-bdg2qt9g', 'batch', 'medium',
  ('What made the backfill safe to run? Choose all that apply.', 'O que tornou o backfill seguro de rodar? Marque todas as que se aplicam.'),
  ('Two things, both from lesson 3.', 'Duas coisas, ambas da aula 3.'),
  C('The job replaces each day’s file instead of appending', 'O job substitui o arquivo de cada dia em vez de acrescentar',
    'Yes: running it twice leaves one answer.', 'Sim: rodar duas vezes deixa uma resposta.', ok=True),
  C('The raw events were kept after the first run', 'Os eventos brutos foram guardados depois da primeira execução',
    'Yes: a backfill reads the past again.', 'Sim: um backfill lê o passado de novo.', ok=True),
  C('The job ran in under a second', 'O job rodou em menos de um segundo',
    'Speed makes it quick, not safe.', 'Velocidade o torna rápido, não seguro.'),
  C('The job was started by an orchestrator', 'O job foi iniciado por um orquestrador',
    'Here it was started by hand, and it was still safe.', 'Aqui ele foi iniciado à mão, e ainda assim era seguro.')),
Q('ex-4b81t0qx', 'batch', 'hard',
  ('Monday’s count is first published at 01:00 on Tuesday. What is the shortest honest description of that delay?',
   'A contagem de segunda é publicada pela primeira vez à 01:00 de terça. Qual é a descrição honesta mais curta desse atraso?'),
  ('Would a faster machine shorten it?', 'Uma máquina mais rápida o encurtaria?'),
  C('It is caused by the job being slow, and a bigger machine would remove most of it', 'Ele vem de o job ser lento, e uma máquina maior tiraria quase todo ele',
    'The job takes moments; the wait is for the window to close.', 'O job leva instantes; a espera é pelo fechamento da janela.'),
  C('It is a mistake in the schedule that an orchestrator would correct', 'É um erro de agendamento que um orquestrador corrigiria',
    'The schedule is right: the job has to run after the day ends.', 'O agendamento está certo: o job precisa rodar depois de o dia acabar.'),
  C('It is caused by the late events from Passeio Público', 'Ele é causado pelos eventos atrasados do Passeio Público',
    'The delay exists on every night, outage or not.', 'O atraso existe toda noite, com queda ou sem.'),
  C('It is part of the design: the window has to close before it is counted', 'Faz parte do projeto: a janela precisa fechar antes de ser contada',
    'Right: a day-long window ends at midnight, and the answer comes after.', 'Isso: uma janela de um dia termina à meia-noite, e a resposta vem depois.', ok=True)),
# ---- stream
N('ex-wq9mjfn0', 'stream', 'easy',
  ('After two runs of `consumer.py 300`, what number did `offset.txt` hold?',
   'Depois de duas execuções de `consumer.py 300`, que número o `offset.txt` guardava?'),
  ('The position of the next event to read.', 'A posição do próximo evento a ler.'),
  600, 0, ('', '')),
Q('ex-x8q7he9v', 'stream', 'medium',
  ('A committed offset of 600 means what?', 'Um offset gravado de 600 quer dizer o quê?'),
  ('Offsets start at 0.', 'Os offsets começam em 0.'),
  C('Event 600 was the last one processed', 'O evento 600 foi o último processado',
    'The last one read was 599; 600 is where to start.', 'O último lido foi o 599; o 600 é onde começar.'),
  C('The next event to read is at position 600', 'O próximo evento a ler está na posição 600',
    'Right: the offset written is where the next run starts.', 'Isso: o offset gravado é onde a próxima execução começa.', ok=True),
  C('Events 0 to 599 were deleted', 'Os eventos de 0 a 599 foram apagados',
    'Reading removes nothing from a log.', 'Ler não remove nada de um log.'),
  C('600 events are left to read', 'Faltam 600 eventos para ler',
    'There were 120 left: the log held 720.', 'Faltavam 120: o log tinha 720.')),
Q('ex-c3847qhg', 'stream', 'medium',
  ('How is reading a log different from taking messages off a queue?', 'Em que ler um log difere de tirar mensagens de uma fila?'),
  ('What happens to an event after it is read?', 'O que acontece com um evento depois de lido?'),
  C('The event stays, so another reader can read it too', 'O evento continua lá, então outro leitor pode lê-lo também',
    'Right: each reader keeps its own offset.', 'Isso: cada leitor guarda o seu próprio offset.', ok=True),
  C('One consumer at a time can read a log', 'Um log é lido por um consumidor de cada vez',
    'The dock map and the van alert read the same log.', 'O mapa das docas e o alerta da van leem o mesmo log.'),
  C('Events in a log can be edited after reading', 'Eventos de um log podem ser editados após a leitura',
    'A log is append-only: events are never changed.', 'Um log é só de acréscimo: os eventos nunca mudam.'),
  C('A log keeps events sorted by when they happened, a queue does not', 'Um log guarda os eventos ordenados por quando aconteceram, e uma fila não',
    'A log keeps the order of arrival, which this lesson shows is different.', 'Um log guarda a ordem de chegada, que esta aula mostra ser diferente.')),
Z('ex-4cv1jdyz', 'stream', 'easy',
  ('The position a consumer has read up to, saved so a restart can continue, is its ___.',
   'A posição até onde um consumidor leu, gravada para que um reinício continue dali, é o seu ___.'),
  ('A word Kafka uses too.', 'Uma palavra que o Kafka também usa.'),
  ['offset'], ['offset', 'deslocamento']),
Q('ex-d1hk3ydj', 'stream', 'hard',
  ('A bug in the consumer’s counting is fixed. How is a log-based consumer made to recount everything?',
   'Um bug na contagem do consumidor é corrigido. Como um consumidor baseado em log é levado a recontar tudo?'),
  ('Where does reading start?', 'Onde a leitura começa?'),
  C('Ask the sensors to send every event again from the beginning', 'Pedir aos sensores que mandem todos os eventos de novo desde o início',
    'The log already holds them; nobody has to send anything.', 'O log já os tem; ninguém precisa mandar nada.'),
  C('Set its offset back to 0 and let it read everything again', 'Voltar o offset para 0 e deixar que ele leia tudo de novo',
    'Right: every event is read again by the fixed code.', 'Isso: todo evento é lido de novo pelo código corrigido.', ok=True),
  C('Delete the log and let it fill up again with new events', 'Apagar o log e deixá-lo encher de novo com eventos novos',
    'That throws away the past the recount needs.', 'Isso joga fora o passado de que a recontagem precisa.'),
  C('There is no way: a stream looks forward, not back', 'Não tem como: um fluxo olha para a frente, não para trás',
    'Replaying from an old offset is what a log is good at.', 'Reproduzir a partir de um offset antigo é no que um log é bom.')),
# ---- event-time-and-processing-time
M('ex-h9tt6d2b', 'event-time-and-processing-time', 'easy',
  ('Match each question to the clock it needs.', 'Associe cada pergunta ao relógio de que ela precisa.'),
  ('Is it about the world or about the system?', 'É sobre o mundo ou sobre o sistema?'),
  [(('rides that started between 08:15 and 08:30', 'viagens que começaram entre 08:15 e 08:30'), ('event time', 'tempo do evento')),
   (('how far behind the consumer is', 'quão atrasado está o consumidor'), ('processing time', 'tempo de processamento')),
   (('when the last bicycle left Rua XV', 'quando a última bicicleta saiu da Rua XV'), ('the sensor’s timestamp', 'o carimbo do sensor')),
   (('how many events reached the server last minute', 'quantos eventos chegaram ao servidor no último minuto'), ('the server’s clock', 'o relógio do servidor'))]),
Q('ex-spz185yn', 'event-time-and-processing-time', 'medium',
  ('`lateness.py` found events that arrived after a later one but less than five seconds late. What explains them?',
   'O `lateness.py` encontrou eventos que chegaram depois de um mais recente, mas com menos de cinco segundos de atraso. O que os explica?'),
  ('Out of order is not the same as late.', 'Fora de ordem não é o mesmo que atrasado.'),
  C('The Parque Barigui outage', 'A queda do Parque Barigui',
    'Those are more than a minute late.', 'Esses estão mais de um minuto atrasados.'),
  C('Two sensors whose readings crossed on the way', 'Dois sensores cujas leituras se cruzaram no caminho',
    'Right: one to four seconds of delay is enough to swap two events.', 'Isso: um a quatro segundos de atraso bastam para trocar dois eventos.', ok=True),
  C('A bug in how `sensors.py` sorted the file', 'Um bug no jeito como o `sensors.py` ordenou',
    'The file is sorted by arrival on purpose, which is what a server sees.', 'O arquivo é ordenado pela chegada de propósito, que é o que um servidor vê.'),
  C('Sensors whose clocks drifted', 'Sensores de relógio desregulado',
    'The generator gives every sensor a correct clock.', 'O gerador dá a todo sensor um relógio correto.')),
N('ex-n6aesavd', 'event-time-and-processing-time', 'easy',
  ('How many events did `lateness.py` find more than a minute late?', 'Quantos eventos o `lateness.py` encontrou com mais de um minuto de atraso?'),
  ('Both outages together.', 'As duas quedas juntas.'),
  16, 0, ('events', 'eventos')),
Q('ex-5pcgjg2b', 'event-time-and-processing-time', 'medium',
  ('What cost does event time bring that processing time does not?', 'Que custo o tempo do evento traz e o tempo de processamento não?'),
  ('An event from 08:20 can still be on its way.', 'Um evento das 08:20 ainda pode estar a caminho.'),
  C('Waiting', 'Esperar',
    'Right: the processor cannot know it has seen everything from 08:20.', 'Isso: o processador não sabe se já viu tudo das 08:20.', ok=True),
  C('Every event has to be stored twice, once for each of the two clocks', 'Cada evento precisa ser guardado duas vezes, uma para cada relógio',
    'One event carries both fields in one line.', 'Um evento leva os dois campos numa linha só.'),
  C('It has to be converted to UTC before it can be compared', 'Ele precisa ser convertido para UTC antes de ser comparado',
    'Both clocks here are Curitiba’s and compare fine.', 'Os dois relógios aqui são de Curitiba e se comparam bem.'),
  C('A sensor cannot write a timestamp of its own', 'Um sensor não consegue escrever um carimbo de tempo próprio',
    'It does: that is where event time comes from.', 'Consegue: é de lá que vem o tempo do evento.')),
Q('ex-278fdwh3', 'event-time-and-processing-time', 'hard',
  ('A dock sensor’s clock runs four minutes fast. What happens to its events downstream?',
   'O relógio de um sensor de doca está quatro minutos adiantado. O que acontece com os eventos dele mais adiante?'),
  ('Event time is only as good as the clock that wrote it.', 'O tempo do evento só é tão bom quanto o relógio que o escreveu.'),
  C('The watermark detects the drift and corrects each timestamp', 'A marca d’água detecta o desvio e corrige cada carimbo',
    'A watermark estimates progress; it does not know any clock is wrong.', 'A marca d’água estima o progresso; ela não sabe que algum relógio está errado.'),
  C('They are counted by processing time instead, automatically', 'Eles passam a ser contados pelo tempo de processamento, automaticamente',
    'Nothing switches clocks for you.', 'Nada troca de relógio por você.'),
  C('They land in the wrong windows, and nothing says so', 'Caem nas janelas erradas, e nada avisa',
    'Right: a wrong stamp is used with complete confidence.', 'Isso: um carimbo errado é usado com toda a confiança.', ok=True),
  C('They are dropped as late data by every window', 'São descartados como dado atrasado por toda janela',
    'Running fast makes them look early, not late.', 'Estar adiantado os faz parecer cedo, não atrasados.')),
# ---- windows
M('ex-1g8db43p', 'windows', 'easy',
  ('Match each window to what it is.', 'Associe cada janela ao que ela é.'),
  ('Overlap, no overlap, or no fixed length.', 'Sobreposição, sem sobreposição ou sem tamanho fixo.'),
  [(('tumbling', 'fixa (tumbling)'), ('fixed length, back to back', 'tamanho fixo, uma colada na outra')),
   (('sliding', 'deslizante (sliding)'), ('fixed length, overlapping', 'tamanho fixo, sobrepostas')),
   (('session', 'de sessão (session)'), ('closed by a gap with no events', 'fechada por um intervalo sem eventos'))]),
N('ex-f4p3stnt', 'windows', 'easy',
  ('Counted by arrival time, how many more rides did the 08:45 window hold than counted by event time?',
   'Contando pelo tempo de chegada, quantas viagens a mais a janela das 08:45 teve do que contando pelo tempo do evento?'),
  ('Compare the two columns of `windows.py`.', 'Compare as duas colunas do `windows.py`.'),
  3, 0, ('rides', 'viagens')),
Q('ex-c45kwva3', 'windows', 'medium',
  ('Both columns of `windows.py` total 64. Why is the arrival-time column still wrong?',
   'As duas colunas do `windows.py` somam 64. Por que a coluna do tempo de chegada continua errada?'),
  ('Where are the rides filed?', 'Onde as viagens são arquivadas?'),
  C('It counts some rides twice and leaves out others, which balances by chance', 'Ela conta umas viagens duas vezes e deixa outras de fora, o que se equilibra por acaso',
    'Each ride is counted once in each column.', 'Cada viagem é contada uma vez em cada coluna.'),
  C('It puts rides in the wrong quarter of an hour', 'Põe viagens no quarto de hora errado',
    'Right: the error is in which window, not in how many.', 'Isso: o erro está em qual janela, não em quantas.', ok=True),
  C('It is not wrong: when the totals agree, the columns agree', 'Não está errada: quando os totais batem, as colunas batem',
    '08:30 and 08:45 differ between the columns.', '08:30 e 08:45 diferem entre as colunas.'),
  C('It counts docks as well as undocks', 'Conta `dock` além de `undock`',
    'Both columns skip everything but undocks.', 'As duas colunas pulam tudo o que não é `undock`.')),
Q('ex-xq1vd8f9', 'windows', 'medium',
  ('Rides are counted in 30-minute windows that start every 15 minutes. Why do the counts not add up to the day’s total?',
   'Viagens são contadas em janelas de 30 minutos que começam a cada 15. Por que as contagens não somam o total do dia?'),
  ('In how many windows is one ride?', 'Em quantas janelas está uma viagem?'),
  C('Sliding windows drop the events that fall on a boundary', 'Janelas deslizantes descartam os eventos que caem numa borda',
    'Nothing is dropped; events are shared.', 'Nada é descartado; eventos são compartilhados.'),
  C('The windows are sessions, so they vary in length', 'As janelas são sessões, então variam de tamanho',
    'These have a fixed length and a fixed step.', 'Estas têm tamanho e passo fixos.'),
  C('Each ride falls inside two of the overlapping windows', 'Cada viagem cai dentro de duas das janelas sobrepostas',
    'Right: overlapping windows count each event once per window.', 'Isso: janelas sobrepostas contam cada evento uma vez por janela.', ok=True),
  C('Late rides are left out of the sliding windows', 'As viagens atrasadas ficam de fora das janelas deslizantes',
    'Lateness is a separate question from the window’s shape.', 'O atraso é uma questão separada do formato da janela.')),
Q('ex-tjvw9vb6', 'windows', 'hard',
  ('Marta wants to know how long customers keep the app open in one go. Which window fits?',
   'Marta quer saber por quanto tempo os clientes ficam com o aplicativo aberto de uma vez. Que janela serve?'),
  ('The length is what is being measured.', 'O tamanho é o que está sendo medido.'),
  C('Tumbling windows of ten minutes, one after another', 'Janelas fixas de dez minutos, uma depois da outra',
    'A fixed length cuts one use of the app into pieces.', 'Um tamanho fixo corta um uso do aplicativo em pedaços.'),
  C('A session window, one per customer visit', 'Uma janela de sessão, uma por visita do cliente',
    'Right: it follows the customer’s activity and ends after a quiet gap.', 'Isso: ela segue a atividade do cliente e fecha depois de um intervalo parado.', ok=True),
  C('A sliding window of an hour, updated every five minutes', 'Uma janela deslizante de uma hora, atualizada a cada cinco minutos',
    'It counts recent activity, not one use from start to end.', 'Ela conta atividade recente, não um uso do começo ao fim.'),
  C('A single window covering the whole day', 'Uma janela só, cobrindo o dia inteiro',
    'That merges every visit of the day into one.', 'Isso junta todas as visitas do dia numa só.')),
# ---- late-data-and-watermarks
N('ex-2qn67yyg', 'late-data-and-watermarks', 'easy',
  ('With an allowed lateness of two minutes, how many rides did `watermark.py` drop?',
   'Com um atraso permitido de dois minutos, quantas viagens o `watermark.py` descartou?'),
  ('Count the ids in the last line.', 'Conte os ids da última linha.'),
  3, 0, ('rides', 'viagens')),
Q('ex-wj6gc9cp', 'late-data-and-watermarks', 'easy',
  ('What does a watermark say?', 'O que uma marca d’água diz?'),
  ('It is the processor’s estimate.', 'É a estimativa do processador.'),
  C('That every event was delivered exactly once', 'Que todo evento foi entregue exatamente uma vez',
    'That is a delivery guarantee, a different question.', 'Isso é garantia de entrega, outra questão.'),
  C('That a window’s answer is final', 'Que a resposta de uma janela é final',
    'It is a bet; a late event can still prove it wrong.', 'É uma aposta; um evento atrasado ainda pode desmenti-la.'),
  C('The arrival time of the latest event', 'O horário de chegada do último evento',
    'It is built from event time, not arrival.', 'Ela é feita do tempo do evento, não da chegada.'),
  C('That no events older than it are expected any more', 'Que não se esperam mais eventos anteriores a ela',
    'Right: windows ending before it are sent.', 'Isso: janelas que terminam antes dela são enviadas.', ok=True)),
Q('ex-9x0b6c7r', 'late-data-and-watermarks', 'medium',
  ('Raising the allowed lateness from two to twenty-five minutes stopped the drops. What did it cost?',
   'Subir o atraso permitido de dois para vinte e cinco minutos acabou com os descartes. O que isso custou?'),
  ('Look at the times the windows were sent.', 'Olhe os horários em que as janelas foram enviadas.'),
  C('Some rides were counted twice in the 08:15 window', 'Algumas viagens foram contadas duas vezes na janela das 08:15',
    'The counts match the event-time column exactly.', 'As contagens batem exatamente com a coluna do tempo do evento.'),
  C('Each count was sent well after its window had closed', 'Cada contagem saiu bem depois de a sua janela fechar',
    'Right: the 08:00 window went out at 08:40 instead of 08:17.', 'Isso: a janela das 08:00 saiu às 08:40 em vez de 08:17.', ok=True),
  C('More memory, because every event of the morning had to be held', 'Mais memória, porque todo evento da manhã precisou ser guardado',
    'It holds four counters either way.', 'Ele guarda quatro contadores de qualquer jeito.'),
  C('Only the mornings with an outage were slower', 'Só as manhãs com queda ficaram mais lentas',
    'Every window waits, outage or not.', 'Toda janela espera, com queda ou sem.')),
Q('ex-d8ny3hxj', 'late-data-and-watermarks', 'medium',
  ('Which allowed lateness would have caught Passeio Público’s rides in a stream?',
   'Que atraso permitido teria pegado as viagens do Passeio Público num fluxo?'),
  ('They arrived the next morning.', 'Elas chegaram na manhã seguinte.'),
  C('Two minutes, if the processor had restarted', 'Dois minutos, se o processador tivesse reiniciado',
    'A restart changes nothing about how late they were.', 'Um reinício não muda o quanto elas atrasaram.'),
  C('Twenty-five minutes, as in the second run of `watermark.py`', 'Vinte e cinco minutos, como na segunda execução do `watermark.py`',
    'That caught Parque Barigui’s, which were half an hour late at most.', 'Isso pegou as do Parque Barigui, que atrasaram no máximo meia hora.'),
  C('A day or more: they came back the next morning', 'Um dia ou mais: elas voltaram na manhã seguinte',
    'Right: they were over twenty-one hours late.', 'Isso: elas atrasaram mais de vinte e uma horas.', ok=True),
  C('An hour, which is what streaming systems use by default', 'Uma hora, que é o que os sistemas de fluxo usam por padrão',
    'There is no such default, and an hour is too short.', 'Não existe esse padrão, e uma hora é pouco.')),
MC('ex-50vr1amm', 'late-data-and-watermarks', 'medium',
  ('Which of these are ways to handle an event that arrives for a window already sent? Choose all that apply.',
   'Quais destes são jeitos de tratar um evento que chega para uma janela já enviada? Marque todas as que se aplicam.'),
  ('Three were listed.', 'Foram listados três.'),
  C('Send a corrected count for the window', 'Enviar uma contagem corrigida da janela',
    'Yes, when the reader can take a correction.', 'Sim, quando quem lê aceita uma correção.', ok=True),
  C('Write it somewhere of its own', 'Gravá-lo num lugar só dele',
    'Yes: then somebody can see how many there were.', 'Sim: aí alguém pode ver quantos foram.', ok=True),
  C('Let the nightly batch job count it', 'Deixar o job em lote da madrugada contá-lo',
    'Yes: the batch reads a closed day from raw events.', 'Sim: o lote lê um dia fechado a partir dos eventos brutos.', ok=True),
  C('Change its event time to the current window', 'Trocar o tempo do evento dele pela janela atual',
    'That files a ride under a time it did not happen.', 'Isso arquiva uma viagem num horário em que ela não aconteceu.')),
# ---- delivery-guarantees
M('ex-8qp3xe70', 'delivery-guarantees', 'medium',
  ('Match each order of the two steps to what a crash between them causes.',
   'Associe cada ordem dos dois passos ao que uma queda entre eles causa.'),
  ('The step done first is the one that survives.', 'O passo feito primeiro é o que sobrevive.'),
  [(('commit the offset, then do the work', 'gravar o offset, depois fazer o trabalho'), ('events lost', 'eventos perdidos')),
   (('do the work, then commit the offset', 'fazer o trabalho, depois gravar o offset'), ('events repeated', 'eventos repetidos')),
   (('write the work and the offset together', 'gravar o trabalho e o offset juntos'), ('neither', 'nenhum dos dois'))]),
N('ex-y85qvcgj', 'delivery-guarantees', 'medium',
  ('After the crash, `consumer.py` ended with 515 rides on mornings that had 360. How many rides were counted twice?',
   'Depois da queda, o `consumer.py` terminou com 515 viagens em manhãs que tiveram 360. Quantas viagens foram contadas duas vezes?'),
  ('The batch from offset 300 to 599.', 'O lote do offset 300 ao 599.'),
  155, 0, ('rides', 'viagens')),
Q('ex-qvdq1fqy', 'delivery-guarantees', 'easy',
  ('`consumer.py` writes its result and then commits its offset. Which guarantee does it give?',
   'O `consumer.py` grava o resultado e depois o offset. Que garantia ele dá?'),
  ('What does a crash between the two cause?', 'O que uma queda entre os dois causa?'),
  C('At most once, because the offset is committed in the end', 'No máximo uma vez, porque o offset é gravado no final',
    'At most once commits first; this commits last.', 'No máximo uma vez grava primeiro; este grava por último.'),
  C('Exactly once, since the program never loses an event', 'Exatamente uma vez, já que o programa nunca perde um evento',
    'Never losing one is half; it repeats them.', 'Nunca perder é metade; ele repete.'),
  C('At least once, because a crash between the two repeats a batch', 'Pelo menos uma vez, porque uma queda entre os dois repete um lote',
    'Right: nothing is lost, and some events are counted twice.', 'Isso: nada se perde, e alguns eventos são contados duas vezes.', ok=True),
  C('Effectively once, since the work is written first', 'Efetivamente uma vez, já que o trabalho é gravado primeiro',
    'Its count went to 515: the repeat was not harmless.', 'A contagem foi a 515: a repetição não foi inofensiva.')),
Q('ex-5w1qcj0k', 'delivery-guarantees', 'medium',
  ('Why did the same crash leave `keyed.py` at the right count?', 'Por que a mesma queda deixou o `keyed.py` com a contagem certa?'),
  ('What is written for each ride?', 'O que é gravado para cada viagem?'),
  C('It commits its offset before writing its result, unlike `consumer.py`', 'Ele grava o offset antes do resultado, ao contrário do `consumer.py`',
    'The order is the same; the batch was still delivered twice.', 'A ordem é a mesma; o lote ainda foi entregue duas vezes.'),
  C('A ride delivered twice is written to the same key twice', 'Uma viagem entregue duas vezes é gravada na mesma chave duas vezes',
    'Right: the write is idempotent.', 'Isso: a escrita é idempotente.', ok=True),
  C('Its `--crash` flag stops the program at a different point', 'O `--crash` dele para o programa num ponto diferente',
    'It stops between the same two writes.', 'Ele para entre as mesmas duas escritas.'),
  C('It reads the log in smaller batches of events', 'Ele lê o log em lotes de eventos menores',
    'Both read 300 at a time.', 'Os dois leem 300 de cada vez.')),
Q('ex-zt4vb64t', 'delivery-guarantees', 'hard',
  ('Why can no network promise exactly-once delivery?', 'Por que nenhuma rede consegue prometer entrega exatamente uma vez?'),
  ('Think of a sender that hears nothing back.', 'Pense em quem envia e não recebe resposta.'),
  C('Networks are too slow for the receiver to confirm each message in time', 'As redes são lentas demais para o receptor confirmar cada mensagem a tempo',
    'Speed is not the problem; silence is.', 'Velocidade não é o problema; o silêncio é.'),
  C('A lost message and a lost reply look the same', 'Uma mensagem perdida e uma resposta perdida parecem iguais',
    'Right: so the sender must resend or risk a loss.', 'Isso: então quem envia tem de reenviar ou arriscar uma perda.', ok=True),
  C('Every protocol duplicates its messages on purpose, as a safety measure', 'Todo protocolo duplica as mensagens de propósito, por segurança',
    'Duplicates come from resending after silence, not from design.', 'Duplicatas vêm de reenviar depois do silêncio, não do projeto.'),
  C('Messages arrive out of order on the way', 'As mensagens chegam fora de ordem no caminho',
    'Order is a separate question from how many times.', 'A ordem é questão separada de quantas vezes.')),
O('ex-ex0hbcb1', 'delivery-guarantees', 'medium',
  ('Put the steps of the crash in `consumer.py` in order.', 'Ponha os passos da queda no `consumer.py` em ordem.'),
  ('The offset is the last thing written.', 'O offset é a última coisa gravada.'),
  [('read offsets 300 to 599', 'ler os offsets de 300 a 599'),
   ('write the count, now 311', 'gravar a contagem, agora 311'),
   ('crash before the offset is committed', 'cair antes de gravar o offset'),
   ('restart at offset 300', 'reiniciar no offset 300'),
   ('count offsets 300 to 599 a second time', 'contar os offsets de 300 a 599 uma segunda vez')],
  ('The count was written before the crash and the offset was not.', 'A contagem foi gravada antes da queda e o offset não.')),
# ---- lambda-and-kappa
Q('ex-7ymds2nj', 'lambda-and-kappa', 'easy',
  ('What is the main cost of the Lambda architecture?', 'Qual é o principal custo da arquitetura Lambda?'),
  ('Count the paths.', 'Conte os caminhos.'),
  C('The same logic is written, run and kept up twice', 'A mesma lógica é escrita, rodada e mantida duas vezes',
    'Right, and the two can disagree.', 'Isso, e as duas podem discordar.', ok=True),
  C('The log must keep every event for years', 'O log precisa guardar cada evento por anos',
    'That is Kappa’s cost.', 'Esse é o custo da Kappa.'),
  C('It cannot produce an answer until the nightly batch job has run', 'Ela não produz resposta até o job em lote da madrugada rodar',
    'The speed layer answers during the day.', 'A camada de velocidade responde durante o dia.'),
  C('Late events are lost for good', 'Eventos atrasados se perdem para sempre',
    'The batch layer recomputes with them included.', 'A camada de lote recalcula com eles incluídos.')),
Q('ex-trnj91xf', 'lambda-and-kappa', 'medium',
  ('In the Kappa architecture, how is a change to the logic applied to past data?',
   'Na arquitetura Kappa, como uma mudança na lógica é aplicada aos dados passados?'),
  ('There is no batch path.', 'Não há caminho de lote.'),
  C('A nightly batch job recomputes the history', 'Um job em lote da madrugada recalcula o histórico',
    'That is Lambda’s batch layer.', 'Essa é a camada de lote da Lambda.'),
  C('The new version replays the log from offset 0', 'A versão nova reproduz o log desde o offset 0',
    'Right, into a new output that readers then switch to.', 'Isso, numa saída nova para a qual os leitores passam.', ok=True),
  C('It is not: Kappa only processes new events', 'Não é: a Kappa só processa eventos novos',
    'Replaying the past is the whole idea.', 'Reproduzir o passado é a ideia inteira.'),
  C('The speed and serving layers are rebuilt', 'As camadas de velocidade e serviço são refeitas',
    'Kappa has no layers of that kind.', 'A Kappa não tem camadas desse tipo.')),
Q('ex-tkfssqwj', 'lambda-and-kappa', 'hard',
  ('Roda Livre’s log keeps events for seven days. Which architecture does that rule out for a change affecting last year?',
   'O log da Roda Livre guarda eventos por sete dias. Que arquitetura isso descarta para uma mudança que afete o ano passado?'),
  ('Which one depends on replaying the log?', 'Qual depende de reproduzir o log?'),
  C('Lambda, since its speed layer reads the same log', 'A Lambda, já que a camada de velocidade lê o mesmo log',
    'Lambda reprocesses from the batch layer’s raw copy.', 'A Lambda reprocessa a partir da cópia bruta da camada de lote.'),
  C('Neither, because a log can always be replayed', 'Nenhuma, porque um log sempre pode ser reproduzido',
    'Only what it still holds can be replayed.', 'Só dá para reproduzir o que ele ainda guarda.'),
  C('Both of them, because both depend on a log', 'As duas, porque as duas dependem de um log',
    'Lambda’s batch layer keeps all raw events.', 'A camada de lote da Lambda guarda todos os eventos brutos.'),
  C('Kappa', 'A Kappa',
    'Right: last year is no longer in the log.', 'Isso: o ano passado não está mais no log.', ok=True)),
# ---- choosing
Q('ex-p5vrzrpr', 'choosing', 'easy',
  ('Which Roda Livre question earns a stream?', 'Qual pergunta da Roda Livre justifica um fluxo?'),
  ('What is done with the answer, and how soon?', 'O que se faz com a resposta, e em quanto tempo?'),
  C('Rides per station last week, for planning next week’s van routes', 'Viagens por estação na semana passada, para planejar as rotas das vans',
    'A day-old answer is fine for next week’s plan.', 'Uma resposta de um dia serve para o plano da semana seguinte.'),
  C('Revenue per month, for the finance report', 'Receita por mês, para o relatório financeiro',
    'Nobody acts on it within minutes.', 'Ninguém age sobre ela em minutos.'),
  C('Which stations will be empty in the next half hour, for the van', 'Quais estações vão ficar vazias na próxima meia hora, para a van',
    'Right: the van has to move before it happens.', 'Isso: a van precisa se mover antes que aconteça.', ok=True),
  C('Today’s rides so far, shown on the office screen', 'As viagens de hoje até agora, na tela do escritório',
    'Looked at, not acted on: hourly batch is enough.', 'Olhada, não usada para agir: lote a cada hora basta.')),
Q('ex-98b8r960', 'choosing', 'medium',
  ('A manager asks for the office dashboard "in real time". What does the section suggest asking first?',
   'Um gestor pede o painel do escritório "em tempo real". O que a seção sugere perguntar primeiro?'),
  ('The test is about action.', 'O teste é sobre ação.'),
  C('Which streaming product the company already pays for', 'Qual produto de streaming a empresa já paga',
    'The tool comes after the need.', 'A ferramenta vem depois da necessidade.'),
  C('What decision it feeds, and how long that waits', 'Que decisão ele alimenta, e quanto tempo ela espera',
    'Right: "fresher than now" fits an hourly job.', 'Isso: "mais fresco que hoje" cabe num job a cada hora.', ok=True),
  C('How many events a second the data source can produce', 'Quantos eventos por segundo a fonte consegue produzir',
    'Volume matters later; the need comes first.', 'Volume importa depois; a necessidade vem primeiro.'),
  C('Whether the team prefers Lambda or Kappa', 'Se a equipe prefere Lambda ou Kappa',
    'That assumes a stream is needed at all.', 'Isso supõe que um fluxo seja necessário.')),
MC('ex-fd705kbq', 'choosing', 'medium',
  ('Which of these does a stream make a team pay for that an hourly batch job does not? Choose all that apply.',
   'Quais destes um fluxo faz a equipe pagar e um job em lote a cada hora não? Marque todas as que se aplicam.'),
  ('Everything this lesson showed.', 'Tudo o que esta aula mostrou.'),
  C('A process that never stops and must be watched', 'Um processo que nunca para e precisa ser vigiado',
    'Yes: somebody is woken when it stops.', 'Sim: alguém é acordado quando ele para.', ok=True),
  C('A watermark somebody has to choose', 'Uma marca d’água que alguém precisa escolher',
    'Yes: and a decision about late data.', 'Sim: e uma decisão sobre dado atrasado.', ok=True),
  C('State that must survive a crash', 'Um estado que precisa sobreviver a uma queda',
    'Yes: plus duplicates to make harmless.', 'Sim: além de duplicatas a tornar inofensivas.', ok=True),
  C('Storing the raw events', 'Guardar os eventos brutos',
    'Batch needs them kept too, for backfills.', 'O lote também precisa deles guardados, para backfills.')),
# ---- drill
O('ex-m3gqxksx', 'drill', 'medium',
  ('Put the steps of a stream window’s life in order.', 'Ponha em ordem os passos da vida de uma janela num fluxo.'),
  ('The watermark moves before the window is sent.', 'A marca d’água anda antes de a janela ser enviada.'),
  [('an event arrives with its event time', 'um evento chega com o seu tempo do evento'),
   ('it is added to the window it belongs to', 'ele é somado à janela a que pertence'),
   ('the watermark moves past the window’s end', 'a marca d’água passa do fim da janela'),
   ('the window’s count is sent', 'a contagem da janela é enviada'),
   ('a late event for it is dropped', 'um evento atrasado para ela é descartado')],
  ('Late means after the window was sent.', 'Atrasado quer dizer depois de a janela ter sido enviada.')),
Q('ex-rdsy0rdz', 'drill', 'hard',
  ('A payment provider retries a webhook when it hears nothing back, and Roda Livre adds each payment to the day’s revenue. What is the first fix?',
   'Um provedor de pagamentos repete um webhook quando não recebe resposta, e a Roda Livre soma cada pagamento à receita do dia. Qual é a primeira correção?'),
  ('The delivery is at least once.', 'A entrega é pelo menos uma vez.'),
  C('Ask the provider to stop retrying', 'Pedir ao provedor que pare de repetir',
    'Then a lost webhook is a payment nobody records.', 'Aí um webhook perdido vira um pagamento que ninguém registra.'),
  C('Record each payment under its own id, so a retry overwrites it', 'Registrar cada pagamento pelo próprio id, para a repetição sobrescrever',
    'Right: a retry writes the same key and changes nothing.', 'Isso: uma repetição grava a mesma chave e não muda nada.', ok=True),
  C('Add a watermark of one hour to the revenue', 'Pôr uma marca d’água de uma hora na receita',
    'Lateness is about time, not about repeats.', 'Atraso é sobre tempo, não sobre repetição.'),
  C('Move the revenue report to a nightly batch job', 'Passar o relatório de receita para um job em lote da madrugada',
    'A batch would add the duplicates too.', 'Um lote somaria as duplicatas também.')),
Q('ex-mtex1tge', 'drill', 'hard',
  ('A team counts rides per quarter of an hour by arrival time, and the chart shows a surge at 08:45 on Monday. What should they check first?',
   'Uma equipe conta viagens por quarto de hora pelo tempo de chegada, e o gráfico mostra um pico às 08:45 de segunda. O que ela deveria conferir primeiro?'),
  ('Which clock files the rides?', 'Qual relógio arquiva as viagens?'),
  C('Whether more bicycles were put into service that morning', 'Se mais bicicletas entraram em serviço naquela manhã',
    'That is the story the chart tells, and it may be false.', 'Essa é a história que o gráfico conta, e pode ser falsa.'),
  C('Whether the daily total for Monday is lower than usual', 'Se o total diário de segunda está abaixo do normal',
    'The total is the same by either clock.', 'O total é o mesmo pelos dois relógios.'),
  C('Whether a burst of old events arrived around 08:45', 'Se uma rajada de eventos antigos chegou perto das 08:45',
    'Right: a burst of old events lands in the window it arrives in.', 'Isso: uma rajada de eventos antigos cai na janela em que chega.', ok=True),
  C('Whether the consumer committed its offset correctly', 'Se o consumidor gravou o offset direito',
    'A repeat would raise many windows, not move rides between them.', 'Uma repetição subiria várias janelas, não moveria viagens entre elas.')),
Z('ex-my5zz63e', 'drill', 'easy',
  ('A write that leaves the same result whether it is done once or twice is ___.',
   'Uma escrita que deixa o mesmo resultado sendo feita uma ou duas vezes é ___.'),
  ('It is what made `keyed.py` survive the crash.', 'Foi o que fez o `keyed.py` sobreviver à queda.'),
  ['idempotent'], ['idempotente']),
]

# Where the key sits, so it does not settle on one position across the lesson:
# the choices above are written in the order they were thought of.
MOVE = {'ex-3wd3qfev': 3, 'ex-n3e6epfz': 0, 'ex-d1hk3ydj': 3, 'ex-c45kwva3': 0,
        'ex-9x0b6c7r': 3, 'ex-zt4vb64t': 3, 'ex-rdsy0rdz': 0}
for q in QUESTIONS:
    if q['id'] in MOVE:
        key = next(c for c in q['choices'] if c['ok'])
        q['choices'].remove(key)
        q['choices'].insert(MOVE[q['id']], key)
