from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
# ---- why-more-than-one
Q('ex-3fgq26zs', 'why-more-than-one', 'easy',
  ('Roda Livre’s database is slow at six in the evening, and Davi moves it to one machine with twice the cores and memory. What has he done?',
   'O banco da Roda Livre fica lento às seis da tarde, e Davi o muda para uma máquina com o dobro de núcleos e de memória. O que ele fez?'),
  ('One machine before, one machine after.', 'Uma máquina antes, uma máquina depois.'),
  C('Scaled out, because the capacity went up without the software changing', 'Escalou para os lados, porque a capacidade subiu sem o software mudar',
    'Out means more machines, and then the software has to know there are several.', 'Para os lados quer dizer mais máquinas, e aí o software precisa saber que são várias.'),
  C('Scaled up, keeping the software exactly as it was, on a larger computer', 'Escalou para cima, mantendo o software como estava, num computador maior',
    'Right: a bigger machine, and nothing in the software had to change.', 'Isso: uma máquina maior, e nada no software precisou mudar.', ok=True),
  C('Partitioned the database, since the data now has more room', 'Particionou o banco, já que os dados agora têm mais espaço',
    'Partitioning splits data over several machines; there is still one.', 'Particionar divide os dados entre várias máquinas; ainda há uma só.'),
  C('Replicated it, because the old machine still holds a copy', 'Replicou o banco, porque a máquina antiga ainda guarda uma cópia',
    'Nothing keeps the old machine in step; a replica receives every change.', 'Nada mantém a máquina antiga em dia; uma réplica recebe cada mudança.')),
Q('ex-30c8j54y', 'why-more-than-one', 'medium',
  ('Which of these problems arrives with a second machine, and did not exist with one?',
   'Qual destes problemas chega com a segunda máquina, e não existia com uma só?'),
  ('Think about what travels between them.', 'Pense no que viaja entre elas.'),
  C('A disk that fills up with data', 'Um disco que enche de dados',
    'One machine’s disk fills up just as well.', 'O disco de uma máquina sozinha enche do mesmo jeito.'),
  C('A slow query over a large table', 'Uma consulta lenta numa tabela grande',
    'A single machine has slow queries of its own.', 'Uma máquina sozinha tem as suas próprias consultas lentas.'),
  C('A request whose reply never comes, leaving the sender unsure whether it was done', 'Um pedido cuja resposta nunca chega, deixando quem pediu sem saber se foi feito',
    'Right: a function call returns or raises; a message over a network just goes quiet.', 'Isso: uma chamada de função retorna ou levanta erro; uma mensagem pela rede simplesmente silencia.', ok=True),
  C('A program with a bug in it', 'Um programa com um bug',
    'Bugs need no network.', 'Bugs não precisam de rede.')),
Q('ex-pk7kkcdn', 'why-more-than-one', 'medium',
  ('The dock sensor stamps a docking at 08:00:00.400, and the app’s server stamps the next unlock of the same bicycle at 08:00:00.100. What explains it?',
   'O sensor da doca carimba uma devolução às 08:00:00.400, e o servidor do aplicativo carimba a retirada seguinte da mesma bicicleta às 08:00:00.100. O que explica isso?'),
  ('Two stamps, two machines.', 'Dois carimbos, duas máquinas.'),
  C('The bicycle was unlocked before it was docked, and the data is right', 'A bicicleta foi retirada antes de ser devolvida, e os dados estão certos',
    'A bicycle has to arrive at a dock before it leaves it.', 'Uma bicicleta precisa chegar à doca antes de sair dela.'),
  C('The sensor’s clock and the server’s clock disagree', 'O relógio do sensor e o relógio do servidor discordam entre si',
    'Right: the sensor runs ahead of the server, and the order in the data is wrong.', 'Isso: o sensor está adiantado em relação ao servidor, e a ordem nos dados está errada.', ok=True),
  C('The network lost the docking message, and the sensor sent it again later', 'A rede perdeu a mensagem de devolução, e o sensor a mandou de novo depois',
    'A resent message keeps the time the sensor stamped on it.', 'Uma mensagem reenviada mantém a hora que o sensor carimbou nela.'),
  C('The sensor rounds its times to the nearest second', 'O sensor arredonda as horas para o segundo mais próximo',
    'Both stamps carry milliseconds.', 'Os dois carimbos têm milissegundos.')),
Q('ex-y334n0cv', 'why-more-than-one', 'easy',
  ('Roda Livre’s data fits on a laptop. Why does its data team still need to understand distributed systems?',
   'Os dados da Roda Livre cabem num notebook. Por que o time de dados ainda precisa entender sistemas distribuídos?'),
  ('Think about what the team rents.', 'Pense no que o time aluga.'),
  C('Because it will need a cluster within a year, as the number of bicycles grows', 'Porque vai precisar de um cluster em um ano, conforme o número de bicicletas cresce',
    'Davi’s rule is one machine until it hurts, and nothing says it will hurt.', 'A regra de Davi é uma máquina até doer, e nada diz que vai doer.'),
  C('Because a laptop is not allowed to hold customer data', 'Porque um notebook não tem permissão de guardar dados de clientes',
    'Where the data is kept is a question of security, not of distribution.', 'Onde os dados ficam é uma questão de segurança, não de distribuição.'),
  C('The services it rents, like the warehouse, are distributed underneath', 'Os serviços que ele aluga, como o warehouse, são distribuídos por baixo',
    'Right: the warehouse, object storage and a message log all are.', 'Isso: o data warehouse, o armazenamento de objetos e um log de mensagens são.', ok=True),
  C('Because every data engineering job involves running a cluster by hand', 'Porque todo trabalho de engenharia de dados envolve operar um cluster na mão',
    'Most teams rent the cluster and never touch a machine of it.', 'A maioria dos times aluga o cluster e nunca encosta numa máquina dele.')),
# ---- partitioning
Q('ex-a8302zzp', 'partitioning', 'easy',
  ('What decides which partition a row goes to?', 'O que decide para qual partição uma linha vai?'),
  ('It is a column.', 'É uma coluna.'),
  C('The order in which rows arrived, so that each partition fills in turn', 'A ordem em que as linhas chegaram, para que cada partição encha na sua vez',
    'That is the cake picture: every question would then ask every partition.', 'Essa é a imagem do bolo: toda pergunta teria então de consultar toda partição.'),
  C('The size of the row in bytes, so that partitions stay the same size', 'O tamanho da linha em bytes, para que as partições fiquem do mesmo tamanho',
    'Size says nothing about which questions the row answers.', 'O tamanho não diz nada sobre quais perguntas a linha responde.'),
  C('The machine with the most free disk at the moment of the write', 'A máquina com mais disco livre no momento da escrita',
    'Then nobody could find the row again without asking every machine.', 'Aí ninguém acharia a linha de novo sem consultar toda máquina.'),
  C('The value of its partition key', 'O valor da sua chave de partição',
    'Right: by its range, or by its hash.', 'Isso: pelo intervalo dele, ou pelo hash.', ok=True)),
Q('ex-t1v3mbxk', 'partitioning', 'medium',
  ('Rides are partitioned by date, one partition per day. At six on a busy Friday evening, which partition receives the writes?',
   'As viagens estão particionadas por data, uma partição por dia. Às seis de uma sexta movimentada, qual partição recebe as escritas?'),
  ('Every new ride has today’s date.', 'Toda viagem nova tem a data de hoje.'),
  C('All of them evenly, because a partition key spreads the writes', 'Todas por igual, porque uma chave de partição espalha as escritas',
    'A range key keeps neighbours together, and today’s rides are neighbours.', 'Uma chave por intervalo mantém as vizinhas juntas, e as viagens de hoje são vizinhas.'),
  C('Today’s alone, since every ride starting now carries today’s date', 'Só a de hoje, já que toda viagem que começa agora leva a data de hoje',
    'Right: that is the weakness of range partitioning on a date.', 'Isso: essa é a fraqueza do particionamento por intervalo numa data.', ok=True),
  C('The one with the fewest rows, since the database balances new writes', 'A que tem menos linhas, já que o banco equilibra as escritas novas',
    'The key decides, not the current size.', 'Quem decide é a chave, não o tamanho atual.'),
  C('Yesterday’s, until midnight creates today’s', 'A de ontem, até a meia-noite criar a de hoje',
    'A ride on Friday has Friday’s date.', 'Uma viagem na sexta tem a data de sexta.')),
Q('ex-dgx6js0w', 'partitioning', 'medium',
  ('Rides are hash-partitioned by ride id over four machines. Marta asks for every ride of the second week of September. How many partitions are read?',
   'As viagens estão particionadas por hash do id da viagem em quatro máquinas. Marta pede todas as viagens da segunda semana de setembro. Quantas partições são lidas?'),
  ('Where did the hash put that week’s rides?', 'Onde o hash pôs as viagens daquela semana?'),
  C('One, the partition that holds that week', 'Uma, a partição que guarda aquela semana',
    'That is range partitioning by date; a hash scatters the week.', 'Isso é particionamento por intervalo de data; um hash espalha a semana.'),
  C('Two, because a week spans two hash values', 'Duas, porque uma semana ocupa dois valores de hash',
    'Each ride id gets its own hash; the week is all over the place.', 'Cada id de viagem tem o próprio hash; a semana fica espalhada.'),
  C('All four: a hash scatters that week’s rides everywhere', 'As quatro: o hash espalha aqueles sete dias por toda parte',
    'Right: neighbouring keys are scattered, so a range question asks everybody.', 'Isso: chaves vizinhas ficam espalhadas, então uma pergunta por intervalo consulta todas.', ok=True),
  C('None, because an index on one machine answers it', 'Nenhuma, porque um índice numa máquina responde',
    'The rides themselves are on four machines.', 'As próprias viagens estão em quatro máquinas.')),
M('ex-p9tj590x', 'partitioning', 'easy',
  ('Match each term to what it means.', 'Associe cada termo ao que ele significa.'),
  ('Two are about how; two are about what.', 'Dois são sobre como; dois são sobre o quê.'),
  [(('partition key', 'chave de partição'), ('the column whose value picks the partition', 'a coluna cujo valor escolhe a partição')),
   (('shard', 'shard'), ('a database’s word for a partition', 'a palavra de um banco para partição')),
   (('range partitioning', 'particionamento por intervalo'), ('consecutive keys kept together', 'chaves consecutivas mantidas juntas')),
   (('hash partitioning', 'particionamento por hash'), ('neighbouring keys scattered evenly', 'chaves vizinhas espalhadas por igual'))]),
# ---- skew
N('ex-2xv6748n', 'skew', 'easy',
  ('In the capture of `skew.py`, how many rides did ST02 have?', 'Na captura do `skew.py`, quantas viagens a ST02 teve?'),
  ('The last line of the output.', 'A última linha da saída.'),
  3553, 0, ('rides', 'viagens')),
Q('ex-rda3r1fz', 'skew', 'medium',
  ('Partitioned by hash of the station, partition 3 held 4730 rides. Why did hashing not even it out?',
   'Particionando por hash da estação, a partição 3 ficou com 4730 viagens. Por que o hash não equilibrou isso?'),
  ('Look at what is being hashed.', 'Veja o que está passando pelo hash.'),
  C('MD5 is a weak hash function and sends too many keys to partition 3', 'O MD5 é uma função de hash fraca e manda chaves demais para a partição 3',
    'Partition 3 got three stations; the trouble is that one of them is ST02.', 'A partição 3 recebeu três estações; o problema é que uma delas é a ST02.'),
  C('Every ST02 ride carries the same key, so all of them share one partition', 'Toda viagem da ST02 tem a mesma chave, então todas dividem uma partição',
    'Right: the same key goes to the same partition, every time.', 'Isso: a mesma chave vai para a mesma partição, toda vez.', ok=True),
  C('Four partitions are too few; with eight, ST02’s rides would have been split', 'Quatro partições são poucas; com oito, as viagens da ST02 seriam divididas',
    'With eight, ST02 would still go to exactly one of them.', 'Com oito, a ST02 ainda iria para exatamente uma delas.'),
  C('That line of the program used range partitioning by mistake', 'Aquela linha do programa usou particionamento por intervalo por engano',
    'It calls `by_hash`; the range row is the one above it.', 'Ela chama `by_hash`; a linha por intervalo é a de cima.')),
Q('ex-z4fe96g1', 'skew', 'hard',
  ('Switching the partition key to the ride id evened the partitions out. What did it cost?',
   'Trocar a chave de partição pelo id da viagem equilibrou as partições. O que isso custou?'),
  ('Ask a question about one station.', 'Faça uma pergunta sobre uma estação.'),
  C('Nothing, since ride ids are unique and every question got cheaper', 'Nada, já que os ids de viagem são únicos e toda pergunta ficou mais barata',
    'A question per station got dearer: it now reads four partitions.', 'Uma pergunta por estação ficou mais cara: agora lê quatro partições.'),
  C('A question about one station now asks all four partitions', 'Uma pergunta sobre uma estação agora consulta as quatro partições',
    'Right: the even load moved the cost to the station question.', 'Isso: a carga equilibrada mudou o custo para a pergunta por estação.', ok=True),
  C('The rides of a station are lost when one partition fails', 'As viagens de uma estação se perdem quando uma partição falha',
    'Losing a partition is replication’s subject, and loses data whatever the key.', 'Perder uma partição é assunto da replicação, e perde dados seja qual for a chave.'),
  C('Ride ids take longer to hash than station ids', 'Ids de viagem demoram mais no hash do que ids de estação',
    'Both are short strings; the difference is not where the cost went.', 'Os dois são textos curtos; o custo não foi para aí.')),
Q('ex-ppqwmdkh', 'skew', 'medium',
  ('Twelve stations hashed into four partitions left partition 0 with a single station. What does that show?',
   'Doze estações passadas por hash em quatro partições deixaram a partição 0 com uma única estação. O que isso mostra?'),
  ('Count the keys.', 'Conte as chaves.'),
  C('ST10 is a hot station', 'A ST10 é uma estação quente',
    'Partition 0 held 544 rides, the fewest of the four.', 'A partição 0 ficou com 544 viagens, a menor das quatro.'),
  C('The hash function misbehaves on keys that start with the same letters', 'A função de hash se comporta mal com chaves que começam pelas mesmas letras',
    'MD5 scatters similar keys well; ride ids start alike too and came out even.', 'O MD5 espalha bem chaves parecidas; os ids de viagem também começam igual e ficaram equilibrados.'),
  C('Hash partitioning needs a number as its key, not text', 'O particionamento por hash precisa de um número como chave, não de texto',
    'The program hashes text, and it works for ride ids.', 'O programa passa texto pelo hash, e funciona com ids de viagem.'),
  C('Twelve keys are too few to share out evenly', 'Doze chaves são poucas para repartir por igual',
    'Right: a hash is even over thousands of keys, not over twelve.', 'Isso: um hash é uniforme sobre milhares de chaves, não sobre doze.', ok=True)),
Z('ex-mdtn5at3', 'skew', 'medium',
  ('Splitting a hot key into `ST02#0` to `ST02#3`, so that its rows land on several partitions, is called ___.',
   'Dividir uma chave quente em `ST02#0` a `ST02#3`, para que as linhas dela caiam em várias partições, se chama ___.'),
  ('A word from cooking.', 'Uma palavra da cozinha, em inglês.'),
  ['salting'], ['salting']),
# ---- rebalancing
N('ex-3ma1gydv', 'rebalancing', 'easy',
  ('By modulo, how many of the 10,000 rides changed node when the fifth node joined?',
   'Por módulo, quantas das 10.000 viagens mudaram de nó quando o quinto nó entrou?'),
  ('The `modulo` line of the capture.', 'A linha `modulo` da captura.'),
  7966, 0, ('rides', 'viagens')),
Q('ex-a1m53306', 'rebalancing', 'medium',
  ('With `hash % N`, why do about four keys in five move when N goes from 4 to 5?',
   'Com `hash % N`, por que cerca de quatro chaves em cinco mudam quando N passa de 4 para 5?'),
  ('Compare two remainders.', 'Compare dois restos.'),
  C('The new node copies four fifths of the data so that it starts balanced', 'O nó novo copia quatro quintos dos dados para começar equilibrado',
    'It ends up with a fifth; the rest moved between old nodes.', 'Ele acaba com um quinto; o resto mudou entre nós antigos.'),
  C('It stays only where the remainder after dividing by 4 equals the one after dividing by 5', 'Uma chave só fica onde o resto da divisão por 4 é igual ao resto da divisão por 5',
    'Right: that happens for four numbers in twenty.', 'Isso: acontece com quatro números em vinte.', ok=True),
  C('The hash of every key changes when the number of nodes changes', 'O hash de toda chave muda quando o número de nós muda',
    'The hash depends on the key alone; the remainder is what changes.', 'O hash depende só da chave; o que muda é o resto.'),
  C('The old nodes delete their data and load it again from the start', 'Os nós antigos apagam os dados e carregam tudo de novo do começo',
    'Keys whose remainder agrees stay put.', 'As chaves cujo resto coincide ficam onde estão.')),
Q('ex-n79w1ner', 'rebalancing', 'medium',
  ('On the ring, a new node lands between two others. Which node do the keys it takes come from?',
   'No anel, um nó novo cai entre dois outros. De qual nó vêm as chaves que ele assume?'),
  ('Before it joined, where did those keys walk to?', 'Antes de ele entrar, até onde essas chaves andavam?'),
  C('A fifth from each of the old nodes, so that all stay equal', 'Um quinto de cada nó antigo, para que todos fiquem iguais',
    'Only the arc in front of the new node changes hands.', 'Só o arco à frente do nó novo muda de dono.'),
  C('The node before it on the ring', 'O nó anterior a ele no anel',
    'Keys belong to the first node clockwise after them, and that was never the one before.', 'As chaves pertencem ao primeiro nó depois delas no sentido horário, e esse nunca foi o anterior.'),
  C('The next node clockwise', 'O próximo nó no sentido horário',
    'Right: those keys used to walk on to it, and now meet the new node first.', 'Isso: essas chaves andavam até ele, e agora encontram o nó novo primeiro.', ok=True),
  C('Whichever node holds the most keys at the moment it joins', 'O nó que tiver mais chaves no momento em que ele entra',
    'Placement follows the hash of the node’s name, not the loads.', 'A posição segue o hash do nome do nó, não as cargas.')),
Q('ex-nehcjqjs', 'rebalancing', 'hard',
  ('With one point per node, the arcs of a ring come out uneven. What is done about it?',
   'Com um ponto por nó, os arcos de um anel saem desiguais. O que se faz a respeito?'),
  ('`ring(nodes, points=100)`.', '`ring(nodes, points=100)`.'),
  C('Nodes are added until the arcs even out by chance', 'Acrescentam-se nós até os arcos se equilibrarem por acaso',
    'More nodes means more arcs, still one per node and still uneven.', 'Mais nós são mais arcos, ainda um por nó e ainda desiguais.'),
  C('Keys are moved by hand from the busiest node each night', 'As chaves são movidas à mão do nó mais cheio toda noite',
    'Then a key’s place would no longer follow from its hash.', 'Aí o lugar de uma chave não decorreria mais do hash dela.'),
  C('Each node is put on the ring at many points instead of one', 'Cada nó é colocado no anel em muitos pontos em vez de um',
    'Right: virtual nodes, whose many small arcs add up close to a fair share.', 'Isso: nós virtuais, cujos muitos arcos pequenos somam perto de uma parte justa.', ok=True),
  C('The system goes back to hash modulo N, which is even', 'O sistema volta ao hash módulo N, que é uniforme',
    'It is even, and it moves four keys in five on every change.', 'Ele é uniforme, e move quatro chaves em cinco a cada mudança.')),
MC('ex-91gqtqy6', 'rebalancing', 'medium',
  ('Which of these does the ring’s line of the capture show? Choose all that apply.',
   'Quais destas a linha do anel na captura mostra? Marque todas as que se aplicam.'),
  ('Read the `ring` lines.', 'Leia as linhas `ring`.'),
  C('2177 rides moved', '2177 viagens mudaram',
    'Yes, all of them to `n5`.', 'Sim, todas para o `n5`.', ok=True),
  C('No ride moved between old nodes', 'Nenhuma viagem mudou entre nós antigos',
    'Yes: `0 between old ones`.', 'Sim: `0 between old ones`.', ok=True),
  C('Each node ended with exactly 2000 rides', 'Cada nó terminou com exatamente 2000 viagens',
    'They ended between 1622 and 2177.', 'Eles terminaram entre 1622 e 2177.'),
  C('More rides moved than with modulo', 'Mais viagens mudaram do que com módulo',
    'Modulo moved 7966.', 'O módulo moveu 7966.')),
# ---- replication
Q('ex-mtsnk19m', 'replication', 'easy',
  ('Somebody runs a `DELETE` on the rides table by mistake. What do the followers do?',
   'Alguém roda um `DELETE` na tabela de viagens por engano. O que os seguidores fazem?'),
  ('They replay the leader’s log.', 'Eles reaplicam o log do líder.'),
  C('Keep the rows, since a replica is a backup of the data from before', 'Guardam as linhas, já que uma réplica é um backup dos dados de antes',
    'That is the wrong picture: a backup is a copy from before, kept apart.', 'Essa é a imagem errada: um backup é uma cópia de antes, guardada à parte.'),
  C('Refuse the change, because followers accept writes only from the app', 'Recusam a mudança, porque os seguidores só aceitam escritas do aplicativo',
    'Followers take every change from the leader’s log.', 'Os seguidores recebem toda mudança do log do líder.'),
  C('Delete the same rows', 'Apagam as mesmas linhas',
    'Right: a mistake replicates as faithfully as a correct write.', 'Isso: um engano se replica tão fielmente quanto uma escrita correta.', ok=True),
  C('Hold the change until a person approves it', 'Seguram a mudança até uma pessoa aprovar',
    'Nothing in replication waits for a person.', 'Nada na replicação espera por uma pessoa.')),
Q('ex-azhv0kvk', 'replication', 'medium',
  ('The leader confirms each write at once and the followers catch up afterwards. What goes wrong when the leader dies?',
   'O líder confirma cada escrita na hora e os seguidores alcançam depois. O que dá errado quando o líder morre?'),
  ('What had it not sent yet?', 'O que ele ainda não tinha mandado?'),
  C('Every write had been waiting for the slowest follower', 'Toda escrita estava esperando o seguidor mais lento',
    'That is the cost of synchronous replication, and this is the other kind.', 'Esse é o custo da replicação síncrona, e esta é a outra.'),
  C('The writes it confirmed but had not sent are lost', 'As escritas que ele confirmou e ainda não mandou se perdem',
    'Right: confirmed to the client, never sent to a follower.', 'Isso: confirmadas ao cliente, nunca mandadas a um seguidor.', ok=True),
  C('The followers stop accepting reads until it comes back', 'Os seguidores param de aceitar leituras até ele voltar',
    'Followers go on answering reads, and one of them is promoted.', 'Os seguidores continuam respondendo leituras, e um deles é promovido.'),
  C('Reads sent to it had been returning old values', 'As leituras mandadas a ele estavam devolvendo valores antigos',
    'The leader is the one copy that is never behind.', 'O líder é a única cópia que nunca está atrasada.')),
N('ex-07e23mgw', 'replication', 'easy',
  ('In `replica.py`, how many milliseconds behind the leader does the follower run?',
   'No `replica.py`, quantos milissegundos atrás do líder o seguidor roda?'),
  ('The first line after the file name.', 'A primeira linha depois do nome do arquivo.'),
  800, 0, ('ms', 'ms')),
Q('ex-2f9frz9c', 'replication', 'medium',
  ('Ana docks her bicycle, and the app tells her the ride is still running. Which remedy fits?',
   'Ana devolve a bicicleta, e o aplicativo diz que a viagem ainda está em andamento. Qual remédio serve?'),
  ('She is the one person who knows the answer.', 'Ela é a única pessoa que sabe a resposta.'),
  C('Add more followers, so that one of them is current when she reads', 'Acrescentar seguidores, para que um deles esteja em dia quando ela ler',
    'Every follower replays the same log, late.', 'Todo seguidor reaplica o mesmo log, atrasado.'),
  C('Send her reads to a different follower each time she asks', 'Mandar as leituras dela a um seguidor diferente a cada pedido',
    'Each one may be behind, and by different amounts.', 'Cada um está atrasado, e cada um por um tanto.'),
  C('Read her own recent changes from the leader, not a follower', 'Ler as mudanças recentes dela no líder, não num seguidor',
    'Right: read-your-writes, for a while after she writes.', 'Isso: ler as próprias escritas, por um tempo depois que ela escreve.', ok=True),
  C('Give her reads a shorter timeout', 'Dar às leituras dela um timeout menor',
    'The follower answered at once, with the old value.', 'O seguidor respondeu na hora, com o valor antigo.')),
Q('ex-329793dr', 'replication', 'hard',
  ('A leader is cut off from the others but keeps running, and a follower is promoted in its place. What is the danger?',
   'Um líder fica isolado dos outros mas continua rodando, e um seguidor é promovido no lugar dele. Qual é o perigo?'),
  ('How many machines think they are the leader?', 'Quantas máquinas acham que são o líder?'),
  C('The promoted follower refuses reads until the old leader returns', 'O seguidor promovido recusa leituras até o líder antigo voltar',
    'A promoted follower serves reads and writes at once.', 'Um seguidor promovido atende leituras e escritas na hora.'),
  C('The new leader erases the old leader’s data when it is promoted', 'O líder novo apaga os dados do líder antigo quando é promovido',
    'Neither machine can reach the other to erase anything.', 'Nenhuma das máquinas alcança a outra para apagar nada.'),
  C('Two leaders accept writes for the same data at once', 'Dois líderes aceitam escritas para os mesmos dados',
    'Right: split brain, for as long as the old one believes it leads.', 'Isso: split brain, enquanto o antigo acreditar que lidera.', ok=True),
  C('None, since a promoted follower always has every write', 'Nenhum, já que um seguidor promovido sempre tem todas as escritas',
    'With asynchronous replication it is missing the last ones.', 'Com replicação assíncrona faltam as últimas.')),
# ---- quorums
Q('ex-zcb8zf49', 'quorums', 'easy',
  ('With N = 3, which pair guarantees that a read sees the last write?', 'Com N = 3, qual par garante que uma leitura veja a última escrita?'),
  ('R + W > N.', 'R + W > N.'),
  C('W = 1, R = 2', 'W = 1, R = 2',
    'R + W = 3, which is not greater than 3: two reads in three.', 'R + W = 3, que não é maior que 3: duas leituras em três.'),
  C('W = 2, R = 1', 'W = 2, R = 1',
    'R + W = 3 again: one read in three misses.', 'R + W = 3 de novo: uma leitura em três erra.'),
  C('W = 2, R = 2', 'W = 2, R = 2',
    'Right: 4 is greater than 3, so every read set overlaps the write set.', 'Isso: 4 é maior que 3, então todo grupo de leitura cruza o de escrita.', ok=True),
  C('W = 1, R = 1', 'W = 1, R = 1',
    'The first line of the capture: one read in three.', 'A primeira linha da captura: uma leitura em três.')),
N('ex-6dm7v97b', 'quorums', 'easy',
  ('With W = 1 and R = 1, how many of the three possible reads saw ST06 in the capture?',
   'Com W = 1 e R = 1, quantas das três leituras possíveis viram a ST06 na captura?'),
  ('The first line.', 'A primeira linha.'),
  1, 0, ('reads', 'leituras')),
Q('ex-zpv5xxrj', 'quorums', 'medium',
  ('N = 3, W = 3, R = 1. One replica goes down. What still works?', 'N = 3, W = 3, R = 1. Uma réplica cai. O que ainda funciona?'),
  ('Count what each side needs.', 'Conte do que cada lado precisa.'),
  C('Writes, because one replica is enough to confirm them', 'As escritas, porque uma réplica basta para confirmá-las',
    'W = 3: a write needs every replica, and one is down.', 'W = 3: uma escrita precisa de todas as réplicas, e uma caiu.'),
  C('Reads and writes, as two replicas are still a majority of three', 'Leituras e escritas, já que duas réplicas ainda são maioria de três',
    'A majority is enough only when W asks for a majority.', 'A maioria basta só quando o W pede uma maioria.'),
  C('Reads, since a read needs one replica and two are still up', 'As leituras, já que uma leitura precisa de uma réplica e duas continuam no ar',
    'Right: a read needs one replica; a write needs all three.', 'Isso: uma leitura precisa de uma réplica; uma escrita precisa das três.', ok=True),
  C('Neither', 'Nenhuma das duas',
    'Two replicas are still up, and a read asks one.', 'Duas réplicas continuam no ar, e uma leitura pede uma.')),
Z('ex-q15jtdgh', 'quorums', 'easy',
  ('A read is certain to meet the last write when R + W is greater than ___.',
   'Uma leitura tem certeza de encontrar a última escrita quando R + W é maior que ___.'),
  ('How many replicas hold each piece of data?', 'Quantas réplicas guardam cada dado?'),
  ['N'], ['N']),
# ---- failures
Q('ex-12y4w4wp', 'failures', 'easy',
  ('With a one-second timeout, the slow node and the hung node printed the same line. What does that show?',
   'Com um timeout de um segundo, o nó lento e o travado imprimiram a mesma linha. O que isso mostra?'),
  ('One of them would have answered.', 'Um deles teria respondido.'),
  C('Both nodes had crashed before the probe reached them', 'Os dois nós tinham caído antes de a sonda chegar a eles',
    'The slow one answered at five seconds.', 'O lento respondeu com cinco segundos.'),
  C('The slow node was hung too, since it answered nothing', 'O nó lento também estava travado, já que não respondeu nada',
    'It answered once the client waited long enough.', 'Ele respondeu quando o cliente esperou o bastante.'),
  C('Waiting cannot tell a node that is late from one that will never answer', 'Esperar não distingue um nó atrasado de um que nunca vai responder',
    'Right: it says how long you waited, not what happened.', 'Isso: ele diz quanto você esperou, não o que aconteceu.', ok=True),
  C('`probe.py` has a bug that hides the real error', 'O `probe.py` tem um bug que esconde o erro real',
    'The real error is the silence; there is nothing else to show.', 'O erro real é o silêncio; não há outra coisa para mostrar.')),
Q('ex-xkaqjes3', 'failures', 'medium',
  ('Port 8003 answered `Connection refused` at once. Why is that more informative than a timeout?',
   'A porta 8003 respondeu `Connection refused` na hora. Por que isso informa mais do que um timeout?'),
  ('Somebody had to send it.', 'Alguém precisou mandar isso.'),
  C('It proves the whole machine is switched off', 'Prova que a máquina inteira está desligada',
    'A switched-off machine sends nothing back at all.', 'Uma máquina desligada não devolve nada.'),
  C('It is a reply, so a running machine sent it back', 'É uma resposta, logo veio de uma máquina ligada',
    'Right: the machine is up and nothing listens on that port.', 'Isso: a máquina está no ar e nada escuta naquela porta.', ok=True),
  C('It means the network between the two machines is cut', 'Quer dizer que a rede entre as duas máquinas está cortada',
    'Across a cut link no reply arrives, and that is a timeout.', 'Por um link cortado não chega resposta, e isso é um timeout.'),
  C('It shows the node is slow and will answer later', 'Mostra que o nó está lento e vai responder depois',
    'The slow node was on port 8001, and it timed out like the hung one.', 'O nó lento estava na porta 8001, e estourou o tempo como o travado.')),
M('ex-89ex2pzj', 'drill', 'medium',
  ('Match each situation on the far side to what it is.', 'Associe cada situação do outro lado ao que ela é.'),
  ('Only one of them sends anything back.', 'Só uma delas devolve alguma coisa.'),
  [(('the process or the machine has stopped', 'o processo ou a máquina parou'), ('a crash', 'uma queda')),
   (('both machines fine, the link between them cut', 'as duas máquinas bem, o link entre elas cortado'), ('a network partition', 'uma partição de rede')),
   (('alive and working, three seconds late', 'viva e trabalhando, três segundos atrasada'), ('a slow node', 'um nó lento')),
   (('a running machine with nothing on the port', 'uma máquina ligada sem nada na porta'), ('connection refused', 'conexão recusada'))]),
Q('ex-dxx303sz', 'drill', 'hard',
  ('A team sets its heartbeat timeout very short, to fail over faster. What happens on a busy day?',
   'Um time põe o timeout dos heartbeats bem curto, para fazer failover mais rápido. O que acontece num dia movimentado?'),
  ('Busy nodes answer late.', 'Nós ocupados respondem atrasados.'),
  C('Nothing changes, since a shorter timeout only finds dead nodes sooner', 'Nada muda, já que um timeout menor só encontra nós mortos mais cedo',
    'It also declares slow nodes dead, and busy days make nodes slow.', 'Ele também declara mortos os nós lentos, e dias movimentados deixam nós lentos.'),
  C('Healthy leaders that are only slow get replaced', 'Líderes saudáveis que só estão lentos são substituídos',
    'Right: and each failover adds work to machines already busy.', 'Isso: e cada failover põe mais trabalho em máquinas já ocupadas.', ok=True),
  C('Failovers stop, because heartbeats are then sent less often', 'Os failovers param, porque os heartbeats passam a ser mandados com menos frequência',
    'The timeout is how long to wait, not how often to send.', 'O timeout é quanto esperar, não com que frequência mandar.'),
  C('Clients see fewer errors, as dead nodes are found sooner', 'Os clientes veem menos erros, já que nós mortos são achados mais cedo',
    'They see more: every needless failover interrupts them.', 'Veem mais: todo failover desnecessário os interrompe.')),
# ---- retries-and-idempotency
Q('ex-7p0638as', 'retries-and-idempotency', 'easy',
  ('Which of these is idempotent?', 'Qual destes é idempotente?'),
  ('Do it twice and compare.', 'Faça duas vezes e compare.'),
  C('Adding a fare to a customer’s bill', 'Somar uma tarifa à conta de um cliente',
    'Twice is two fares.', 'Duas vezes são duas tarifas.'),
  C('Setting dock 4 at Batel to empty, whatever it was before', 'Marcar a doca 4 do Batel como vazia, seja como estiver antes',
    'Right: set it twice and it is still empty.', 'Isso: marque duas vezes e ela continua vazia.', ok=True),
  C('Appending a ride to the end of a log file', 'Acrescentar uma viagem ao fim de um arquivo de log',
    'Twice is the ride in the log twice.', 'Duas vezes é a viagem duas vezes no log.'),
  C('Adding one to a station’s count of rides', 'Somar um à contagem de viagens de uma estação',
    'Twice adds two.', 'Duas vezes soma dois.')),
N('ex-9cnx1wak', 'retries-and-idempotency', 'easy',
  ('Without a request id, how many cents did the ledger hold for one ride?', 'Sem id do pedido, quantos centavos o livro-caixa guardou por uma viagem?'),
  ('Three charges of 450.', 'Três cobranças de 450.'),
  1350, 0, ('cents', 'centavos')),
Q('ex-xqx4g51m', 'retries-and-idempotency', 'medium',
  ('Why does the client in `retry.py` send the same request id on every attempt?',
   'Por que o cliente do `retry.py` manda o mesmo id do pedido em toda tentativa?'),
  ('What would a new id look like to the ledger?', 'Como um id novo pareceria ao livro-caixa?'),
  C('So that the server answers faster, having seen the id before', 'Para o servidor responder mais rápido, por já ter visto o id',
    'The id changes what is recorded, not how fast.', 'O id muda o que é registrado, não a velocidade.'),
  C('Because making a new id each time would be slower', 'Porque criar um id novo a cada vez seria mais lento',
    'Speed has nothing to do with it; a new id would make a new charge.', 'A velocidade não tem nada com isso; um id novo faria uma cobrança nova.'),
  C('Because the database limits each ride to one request id', 'Porque o banco limita cada viagem a um id de pedido',
    'The `UNIQUE` is on the request, not on the ride.', 'O `UNIQUE` está no pedido, não na viagem.'),
  C('So a retry is recognised as a repeat', 'Para uma nova tentativa ser reconhecida como repetição',
    'Right: one charge meant, one id, however many attempts.', 'Isso: uma cobrança pretendida, um id, quantas tentativas forem.', ok=True)),
Q('ex-37wxza9w', 'retries-and-idempotency', 'medium',
  ('Why add jitter to the backoff between retries?', 'Por que pôr jitter no backoff entre as tentativas?'),
  ('Picture a thousand clients failing at the same moment.', 'Imagine mil clientes falhando no mesmo instante.'),
  C('So clients that failed together retry apart', 'Para clientes que falharam juntos tentarem de novo separados',
    'Right: otherwise they all come back in the same instant.', 'Isso: senão todos voltam no mesmo instante.', ok=True),
  C('To make each wait shorter than the one before it', 'Para cada espera ser menor que a anterior',
    'The backoff doubles; the jitter only scatters it.', 'O backoff dobra; o jitter só espalha.'),
  C('To hide from the server how many times a client has retried', 'Para esconder do servidor quantas vezes um cliente tentou',
    'The server sees every attempt anyway.', 'O servidor vê toda tentativa de qualquer jeito.'),
  C('To give each attempt a fresh request id', 'Para dar a cada tentativa um id de pedido novo',
    'A fresh id on a retry is the mistake the section warns about.', 'Um id novo numa nova tentativa é o erro de que a seção avisa.')),
O('ex-nm4twmef', 'retries-and-idempotency', 'medium',
  ('Put in order what happens when `retry.py` runs without a request id and the first reply is lost.',
   'Ponha em ordem o que acontece quando o `retry.py` roda sem id do pedido e a primeira resposta se perde.'),
  ('The charge comes before the silence.', 'A cobrança vem antes do silêncio.'),
  [('the service records the charge', 'o serviço registra a cobrança'),
   ('the reply is lost', 'a resposta se perde'),
   ('the client waits and sends again', 'o cliente espera e manda de novo'),
   ('a second charge is recorded', 'uma segunda cobrança é registrada')],
  ('The charge is recorded before the reply is lost, which is why the retry charges twice.',
   'A cobrança é registrada antes de a resposta se perder, e é por isso que a nova tentativa cobra duas vezes.')),
Z('ex-894z2h9h', 'retries-and-idempotency', 'easy',
  ('An operation whose second run changes nothing is called ___.', 'Uma operação cuja segunda execução não muda nada se chama ___.'),
  ('The property that makes a retry safe.', 'A propriedade que torna seguro tentar de novo.'),
  ['idempotent'], ['idempotente']),
# ---- moving-the-work
N('ex-2wqt9eq6', 'moving-the-work', 'easy',
  ('With plan B, how many records crossed the network?', 'Com o plano B, quantos registros atravessaram a rede?'),
  ('Thirty-six partial counts, twelve already home.', 'Trinta e seis contagens parciais, doze já em casa.'),
  24, 0, ('records', 'registros')),
Q('ex-ayyhh20a', 'moving-the-work', 'medium',
  ('Which of these can each node compute on its own rides first, for the results to be combined afterwards?',
   'Qual destes cada nó consegue calcular primeiro sobre as próprias viagens, para os resultados serem combinados depois?'),
  ('Will the pieces add up?', 'Os pedaços somam?'),
  C('The median ride length per station', 'A mediana da duração das viagens por estação',
    'The median of three medians is not the median of all the rides.', 'A mediana de três medianas não é a mediana de todas as viagens.'),
  C('The total cents charged per station', 'O total de centavos cobrado por estação',
    'Right: a sum adds up in pieces, like a count.', 'Isso: uma soma se soma em pedaços, como uma contagem.', ok=True),
  C('The number of different customers who rode from each station', 'O número de clientes diferentes que saíram de cada estação',
    'A customer seen on two nodes would be counted twice when the pieces are added.', 'Um cliente visto em dois nós seria contado duas vezes ao somar os pedaços.'),
  C('The ride length below which 90% of rides fall, per station', 'A duração abaixo da qual ficam 90% das viagens, por estação',
    'Like a median, it needs the values together, not partial results.', 'Como uma mediana, precisa dos valores juntos, não de resultados parciais.')),
Q('ex-n5ed8wee', 'moving-the-work', 'medium',
  ('Plan A sent 19,958 of 30,000 rides across the network. Why about two in three?',
   'O plano A mandou 19.958 das 30.000 viagens pela rede. Por que cerca de duas em três?'),
  ('Three nodes; where does a ride already sit?', 'Três nós; onde uma viagem já está?'),
  C('A ride stays put only when its own node counts its station', 'Uma viagem só fica onde está quando o próprio nó conta a estação dela',
    'Right: with three nodes, that is about one ride in three.', 'Isso: com três nós, isso é cerca de uma viagem em três.', ok=True),
  C('One node in three was down, so its rides were sent twice', 'Um nó em cada três estava fora, então as viagens dele foram mandadas duas vezes',
    'Every node was up; the program simulates no failure.', 'Todo nó estava no ar; o programa não simula falha.'),
  C('The network dropped a third of the messages', 'A rede perdeu um terço das mensagens',
    'Nothing was lost: the counts matched the direct count.', 'Nada se perdeu: as contagens bateram com a contagem direta.'),
  C('Plan A compresses one ride in three before sending', 'O plano A comprime uma viagem em três antes de mandar',
    'Plan A sends each ride as it is; plan B is the one that shrinks.', 'O plano A manda cada viagem como está; o plano B é o que encolhe.')),
O('ex-q7szps2s', 'drill', 'medium',
  ('Put the steps of a MapReduce job in order.', 'Ponha os passos de um trabalho MapReduce em ordem.'),
  ('The step that crosses the network is in the middle.', 'O passo que atravessa a rede fica no meio.'),
  [('map over the data each machine holds', 'map sobre os dados que cada máquina guarda'),
   ('shuffle the results by key', 'shuffle dos resultados por chave'),
   ('reduce each group', 'reduce de cada grupo'),
   ('write the combined results', 'gravar os resultados combinados')],
  ('Map runs where the data already is; only after the shuffle does each key have all its pieces in one place.',
   'O map roda onde os dados já estão; só depois do shuffle cada chave tem todos os pedaços num lugar só.')),
# ---- drill
Q('ex-zp8s2a90', 'drill', 'hard',
  ('Rides are stored by hash of the station id. A job counts rides per station. How much has to cross the network for the grouping?',
   'As viagens estão guardadas por hash do id da estação. Um trabalho conta as viagens por estação. Quanto precisa atravessar a rede para o agrupamento?'),
  ('Is the question grouped by the partition key?', 'A pergunta agrupa pela chave de partição?'),
  C('Every ride, since a count needs a shuffle', 'Toda viagem, já que uma contagem precisa de shuffle',
    'A count needs a shuffle only when the data sits by another key.', 'Uma contagem só precisa de shuffle quando os dados estão por outra chave.'),
  C('About two rides in three, as in plan A', 'Cerca de duas viagens em três, como no plano A',
    'Plan A’s rides were stored by ride id, which is the reason they moved.', 'As viagens do plano A estavam guardadas pelo id da viagem, que é o motivo de terem mudado.'),
  C('One partial count per station per node, as in plan B', 'Uma contagem parcial por estação por nó, como no plano B',
    'Each station’s rides are on one node; there are no partial counts to combine.', 'As viagens de cada estação estão num nó só; não há contagens parciais para combinar.'),
  C('Nothing', 'Nada',
    'Right: each station’s rides are already together on one node.', 'Isso: as viagens de cada estação já estão juntas num nó.', ok=True)),
Q('ex-skn5q69w', 'drill', 'hard',
  ('A leaderless store picks the newest version by the time of the write, taken from each client’s clock. What is the risk?',
   'Um armazenamento sem líder escolhe a versão mais nova pela hora da escrita, tirada do relógio de cada cliente. Qual é o risco?'),
  ('Two clients, two clocks.', 'Dois clientes, dois relógios.'),
  C('Reads become slower, because comparing times costs more than comparing counters', 'As leituras ficam mais lentas, porque comparar horas custa mais do que comparar contadores',
    'The comparison is cheap either way; what it compares is the trouble.', 'A comparação é barata de qualquer jeito; o problema é o que ela compara.'),
  C('A client whose clock is behind writes a value that loses to an older one', 'Uma escrita mais nova, com a hora menor, perde para uma mais antiga',
    'Right: the newer write carries the smaller time, and the read keeps the old value.', 'Isso: a escrita mais nova leva a hora menor, e a leitura fica com o valor antigo.', ok=True),
  C('Nothing changes, as long as R + W is greater than N', 'Nada muda, desde que R + W seja maior que N',
    'The overlap finds every version; the clock then picks the wrong one.', 'A sobreposição encontra todas as versões; o relógio então escolhe a errada.'),
  C('Writes need more replicas to confirm them', 'As escritas precisam de mais réplicas para confirmar',
    'W does not depend on how versions are compared.', 'O W não depende de como as versões são comparadas.')),
M('ex-zj02pvcz', 'drill', 'medium',
  ('Match each term to what it describes.', 'Associe cada termo ao que ele descreve.'),
  ('Two are about when the leader answers.', 'Dois são sobre quando o líder responde.'),
  [(('synchronous replication', 'replicação síncrona'), ('confirms a write after a follower has it', 'confirma uma escrita depois que um seguidor a tem')),
   (('asynchronous replication', 'replicação assíncrona'), ('confirms at once; followers catch up', 'confirma na hora; os seguidores alcançam depois')),
   (('replication lag', 'atraso de replicação'), ('how far a follower is behind', 'quanto um seguidor está atrasado')),
   (('failover', 'failover'), ('promoting a follower when the leader stops', 'promover um seguidor quando o líder para'))]),
]
