from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
# ---- what-cap-says
Q('ex-rbfete4b', 'what-cap-says', 'easy',
  ('During a partition, what does CAP say each running machine has to choose between?',
   'Durante uma partição, entre o quê o CAP diz que cada máquina rodando precisa escolher?'),
  ('Think of `n3`, cut off, with a customer waiting.', 'Pense no `n3`, isolado, com uma cliente esperando.'),
  C('Answering now, or refusing until it is sure its answer is still current', 'Responder agora, ou recusar até ter certeza de que a resposta ainda está atual',
    'Right: answer and risk being stale, or refuse and stay correct.', 'Isso: responder e arriscar estar velho, ou recusar e continuar correto.', ok=True),
  C('Accepting writes, or accepting reads, but not both kinds of request', 'Aceitar escritas, ou aceitar leituras, mas não os dois tipos de pedido',
    'A node that chose consistency refused both the write and the read in the capture.', 'Um nó que escolheu consistência recusou tanto a escrita quanto a leitura na captura.'),
  C('Answering quickly, or answering correctly, on every ordinary request', 'Responder rápido, ou responder certo, em toda requisição comum',
    'That is the trade-off PACELC names for the days with no partition.', 'Essa é a troca que o PACELC nomeia para os dias sem partição.'),
  C('Tolerating the partition, or shutting down until it ends', 'Tolerar a partição, ou desligar até ela acabar',
    'P is not a choice: the cut happens either way, and the question is what to do during it.', 'O P não é escolha: o corte acontece de qualquer jeito, e a pergunta é o que fazer durante ele.')),
Q('ex-gkha2dzr', 'what-cap-says', 'medium',
  ('Why is "pick any two of C, A and P" the wrong picture for a system on several machines?',
   'Por que "escolha dois quaisquer entre C, A e P" é a imagem errada para um sistema em várias máquinas?'),
  ('Who decides whether a partition happens?', 'Quem decide se uma partição acontece?'),
  C('With enough replicas, a system can in fact have all three at once', 'Com réplicas suficientes, um sistema consegue de fato ter os três ao mesmo tempo',
    'More replicas do not stop a cut; they only change how many nodes sit on each side.', 'Mais réplicas não impedem um corte; só mudam quantos nós ficam de cada lado.'),
  C('The network decides whether it happens, so P is not a choice', 'Quem decide se ela acontece é a rede, e por isso o P não é escolha',
    'Right: the only choice left is C or A while the cut lasts.', 'Isso: a única escolha que sobra é C ou A enquanto o corte dura.', ok=True),
  C('C and A turn out to be one property under two names', 'C e A acabam sendo uma propriedade só com dois nomes',
    'They are opposite answers to the same cut: refuse, or answer.', 'São respostas opostas ao mesmo corte: recusar, ou responder.'),
  C('Partitions no longer happen inside one modern data centre', 'Partições não acontecem mais dentro de um data center moderno',
    'They are rarer, but a cable, a switch or a slow peer still produces one.', 'Elas são mais raras, mas um cabo, um switch ou um par lento ainda produzem uma.')),
Q('ex-ahcf1n25', 'what-cap-says', 'easy',
  ('What does the C of CAP mean?', 'O que quer dizer o C do CAP?'),
  ('It is not the C of ACID.', 'Não é o C do ACID.'),
  C('A transaction leaves the database’s rules intact', 'Uma transação deixa intactas as regras do banco',
    'That is the C of ACID, a different word with the same letter.', 'Esse é o C do ACID, outra palavra com a mesma letra.'),
  C('Every copy of a table has the same set of columns', 'Toda cópia de uma tabela tem o mesmo conjunto de colunas',
    'That is about the schema; CAP is about which value a read returns.', 'Isso é sobre o esquema; o CAP é sobre qual valor uma leitura devolve.'),
  C('Every read sees the latest completed write, as if there were one copy', 'Toda leitura vê a última escrita concluída, como se houvesse uma cópia só',
    'Right: linearisability, as though there were one copy.', 'Isso: linearizabilidade, como se houvesse uma cópia só.', ok=True),
  C('Data passes its quality checks before it is stored', 'O dado passa nas verificações de qualidade antes de ser guardado',
    'Checks at the door are lesson 7; they say nothing about copies agreeing.', 'Verificações na porta são da aula 7; não dizem nada sobre cópias concordarem.')),
MC('ex-5d2t0dgj', 'what-cap-says', 'medium',
  ('Which of these are true of availability as CAP defines it? Choose all that apply.',
   'Quais destas são verdadeiras sobre a disponibilidade como o CAP a define? Marque todas as que se aplicam.'),
  ('The definition is about each machine, not the month.', 'A definição é sobre cada máquina, não sobre o mês.'),
  C('Every running machine that gets a request answers it', 'Toda máquina rodando que recebe uma requisição a responde',
    'Yes: that is the definition in the proof.', 'Sim: essa é a definição da prova.', ok=True),
  C('An error does not count as an answer', 'Um erro não conta como resposta',
    'Yes: refusing with an error is exactly what giving up availability looks like.', 'Sim: recusar com um erro é exatamente a cara de abrir mão da disponibilidade.', ok=True),
  C('It is measured as the share of the month the service was up', 'Ela é medida como a fração do mês em que o serviço ficou no ar',
    'That is uptime, a measurement over time and another sense of the word.', 'Isso é uptime, uma medida ao longo do tempo e outro sentido da palavra.'),
  C('The majority side answering is enough to count as available', 'Basta o lado da maioria responder para contar como disponível',
    'Then the system chose consistency: the minority side refused.', 'Aí o sistema escolheu a consistência: o lado minoritário recusou.')),
Z('ex-xzvmxbs0', 'what-cap-says', 'medium',
  ('The consistency of CAP has a precise name: ___.', 'A consistência do CAP tem um nome preciso: ___.'),
  ('As though there were one copy, read in a line.', 'Como se houvesse uma cópia só, lida em linha.'),
  ['linearisability', 'linearizability', 'linearisable', 'linearizable'],
  ['linearizabilidade', 'linearizável', 'linearisability', 'linearizability']),
# ---- a-partition
N('ex-j5qf4frk', 'a-partition', 'easy',
  ('In the `cp` run, on how many nodes was `n1`’s write of 5 recorded?', 'Na execução `cp`, em quantos nós a escrita de 5 do `n1` ficou registrada?'),
  ('Read the line that starts `n1 write 5`.', 'Leia a linha que começa com `n1 write 5`.'),
  2, 0, ('nodes', 'nós')),
Q('ex-6a8szce2', 'a-partition', 'medium',
  ('In the `cp` run, why did `n3` refuse the read as well as the write?', 'Na execução `cp`, por que o `n3` recusou a leitura além da escrita?'),
  ('What could `n3` not know about its own copy?', 'O que o `n3` não tinha como saber sobre a própria cópia?'),
  C('The partition had wiped its copy of the count', 'A partição tinha apagado a sua cópia da contagem',
    'Its copy still said 6; the cut removes nothing.', 'A cópia dele ainda dizia 6; o corte não apaga nada.'),
  C('It could not know whether the majority had accepted a write it never saw', 'Não tinha como saber se a maioria tinha aceitado uma escrita que ele nunca viu',
    'Right: the majority might have accepted a write it never saw, and it had.', 'Isso: a maioria podia ter aceitado uma escrita que ele nunca viu, e aceitou.', ok=True),
  C('Once a node refuses one write, it refuses everything after it', 'Depois que um nó recusa uma escrita, ele recusa tudo o que vem depois',
    'Both refusals come from the same check, the majority, made afresh each time.', 'As duas recusas vêm da mesma verificação, a maioria, feita de novo a cada vez.'),
  C('It had seen the newer value on `n2` and would not contradict it', 'Tinha visto o valor mais novo no `n2` e não queria contradizê-lo',
    'It could not see `n2` at all: that is what the cut means.', 'Ele não enxergava o `n2` de jeito nenhum: é isso que o corte quer dizer.')),
N('ex-jmc40d3b', 'a-partition', 'easy',
  ('In the `ap` run, what did a read from `n3` return?', 'Na execução `ap`, o que uma leitura do `n3` devolveu?'),
  ('The line `n3 read:`.', 'A linha `n3 read:`.'),
  7, 0, ('bicycles', 'bicicletas')),
Q('ex-78vsq4pf', 'a-partition', 'medium',
  ('In the `ap` run, `n2` read 5 and `n3` read 7. Which statement is true?', 'Na execução `ap`, o `n2` leu 5 e o `n3` leu 7. Qual afirmação é verdadeira?'),
  ('One bicycle left, one came back.', 'Uma bicicleta saiu, uma voltou.'),
  C('`n3` is right, because its write came later than `n1`’s', 'O `n3` está certo, porque a escrita dele veio depois da do `n1`',
    'Later is not truer: `n3` never saw the ride taken at `n1`.', 'Depois não é mais verdadeiro: o `n3` nunca viu a viagem retirada no `n1`.'),
  C('`n2` is right, because it sits on the majority side', 'O `n2` está certo, porque fica do lado da maioria',
    'In `ap` mode the majority decides nothing, and `n2` never saw the return.', 'No modo `ap` a maioria não decide nada, e o `n2` nunca viu a devolução.'),
  C('Neither one is the true count of bicycles there', 'Nenhum dos dois é a contagem verdadeira de bicicletas',
    'Right: Rua XV holds 6, and each node saw half of what happened.', 'Isso: a Rua XV tem 6, e cada nó viu metade do que aconteceu.', ok=True),
  C('Both are right until somebody compares them', 'Os dois estão certos até alguém compará-los',
    'Each is a faithful report of what one node saw, and neither is the count.', 'Cada um relata fielmente o que um nó viu, e nenhum é a contagem.')),
Q('ex-vagbq1m1', 'a-partition', 'hard',
  ('A store that chose consistency runs on two nodes, and the link between them is cut. What happens to writes?',
   'Um banco que escolheu a consistência roda em dois nós, e o enlace entre eles é cortado. O que acontece com as escritas?'),
  ('Is one of two more than half?', 'Um de dois passa da metade?'),
  C('The node that was leader keeps accepting them', 'O nó que era líder continua aceitando',
    'The leader also sees one of two, which is not a majority.', 'O líder também vê um de dois, e isso não é maioria.'),
  C('Both sides accept them and merge after the cut', 'Os dois lados aceitam e combinam depois do corte',
    'That is the AP behaviour, which this store did not choose.', 'Esse é o comportamento AP, que este banco não escolheu.'),
  C('The node holding the newer data keeps accepting them', 'O nó com o dado mais novo continua aceitando',
    'Neither node can tell whether the other is newer without talking to it.', 'Nenhum nó sabe se o outro é mais novo sem falar com ele.'),
  C('Both sides refuse, because neither holds a majority', 'Os dois lados recusam, pois nenhum tem maioria',
    'Right: that is why such systems run three or five nodes.', 'Isso: é por isso que esses sistemas rodam com três ou cinco nós.', ok=True)),
Q('ex-57npp428', 'a-partition', 'medium',
  ('Why can a real node not know it is partitioned, as `replicas.py` lets it?',
   'Por que um nó real não tem como saber que está particionado, como o `replicas.py` permite?'),
  ('Lesson 9: what can a timeout tell apart?', 'Aula 9: o que um timeout consegue distinguir?'),
  C('Networks report a cut to the routers and not to the nodes themselves', 'As redes avisam um corte aos roteadores, e não aos próprios nós',
    'Nothing reports a cut to anybody; the symptom is silence.', 'Nada avisa um corte a ninguém; o sintoma é o silêncio.'),
  C('Silence from a cut peer looks like a slow one', 'O silêncio de um par cortado parece o de um lento',
    'Right: a timeout cannot tell a cut, a slow peer and a dead one apart.', 'Isso: um timeout não distingue um corte, um par lento e um morto.', ok=True),
  C('Nodes keep no clock with which to measure a wait', 'Os nós não têm relógio com que medir uma espera',
    'They have clocks; the trouble is that waiting does not explain itself.', 'Eles têm relógios; o problema é que a espera não se explica.'),
  C('Detecting a partition needs a vote of every node first', 'Detectar uma partição exige antes um voto de todos os nós',
    'A vote would need the very messages the cut is losing.', 'Um voto precisaria justamente das mensagens que o corte está perdendo.')),
# ---- choosing-consistency
Q('ex-cfmfw2yw', 'choosing-consistency', 'easy',
  ('What lets a CP system be sure only one side of a cut accepts writes?', 'O que permite a um sistema CP ter certeza de que só um lado do corte aceita escritas?'),
  ('Two groups cannot both have it.', 'Dois grupos não podem ter isso ao mesmo tempo.'),
  C('The side with the newest clock reading wins', 'Vence o lado com o relógio mais adiantado',
    'Clocks disagree, and a cut gives no way to compare them.', 'Relógios discordam, e um corte não dá como compará-los.'),
  C('Only one side of any cut ever holds a majority of the nodes', 'Só um lado de qualquer corte consegue ter a maioria dos nós',
    'Right: two of three on one side leaves no second majority anywhere.', 'Isso: dois de três de um lado não deixam segunda maioria em lugar nenhum.', ok=True),
  C('The client picks the side at random for each request', 'O cliente sorteia o lado a cada requisição',
    'A random pick could land on both sides over two requests.', 'Um sorteio poderia cair nos dois lados em duas requisições.'),
  C('Every write is copied to a backup before it is accepted', 'Toda escrita é copiada para um backup antes de ser aceita',
    'A backup is a copy, not a rule about who may write.', 'Um backup é uma cópia, não uma regra sobre quem pode escrever.')),
M('ex-9narw72z', 'choosing-consistency', 'medium',
  ('Match each cost of choosing consistency to when it is paid.', 'Associe cada custo de escolher a consistência ao momento em que é pago.'),
  ('Only one of them waits for a partition.', 'Só um deles espera uma partição.'),
  [(('the minority side refuses', 'o lado minoritário recusa'), ('only while a link is cut', 'só enquanto um enlace está cortado')),
   (('each write waits for a majority', 'cada escrita espera uma maioria'), ('on every write, cut or not', 'em toda escrita, com corte ou sem')),
   (('writes stop until a new leader is chosen', 'as escritas param até um novo líder ser escolhido'), ('when the coordinating machine fails', 'quando a máquina coordenadora cai'))]),
Q('ex-j9kpkg9g', 'choosing-consistency', 'medium',
  ('Which Roda Livre action belongs on the side that refuses during a cut?', 'Qual ação da Roda Livre pertence ao lado que recusa durante um corte?'),
  ('Could two yeses be undone?', 'Dois "sim" poderiam ser desfeitos?'),
  C('Showing the dock map to a customer about to walk', 'Mostrar o mapa de docas a um cliente prestes a sair andando',
    'A map slightly behind still helps; an error does not.', 'Um mapa um pouco atrasado ainda ajuda; um erro não.'),
  C('Unlocking `B017` for a customer', 'Destravar a `B017` para um cliente',
    'Right: one bicycle cannot be handed to two riders.', 'Isso: uma bicicleta não pode ser entregue a dois ciclistas.', ok=True),
  C('Recording a reading sent by a dock sensor', 'Registrar uma leitura enviada por um sensor de doca',
    'A reading is a fact that merges; a duplicate is dropped by its id.', 'Uma leitura é um fato que se combina; a duplicata cai pelo id.'),
  C('Counting yesterday’s rides for the morning report', 'Contar as viagens de ontem para o relatório matinal',
    'That reads a copy kept behind on purpose; no cut is involved.', 'Isso lê uma cópia mantida atrasada de propósito; não há corte envolvido.')),
Q('ex-qbzcmhft', 'choosing-consistency', 'hard',
  ('A payment refused during a cut, or a payment accepted on both sides. Why is the refusal the better failure?',
   'Um pagamento recusado durante um corte, ou um pagamento aceito dos dois lados. Por que a recusa é a falha melhor?'),
  ('Lesson 1 named two kinds of failure.', 'A aula 1 nomeou dois tipos de falha.'),
  C('A refusal is loud, and the client is free to try it again safely', 'A recusa é barulhenta, e o cliente tenta de novo com segurança',
    'Right, and an idempotent retry makes it safe; a double charge succeeds twice in silence.', 'Isso, e uma nova tentativa idempotente a torna segura; uma cobrança dupla dá certo duas vezes em silêncio.', ok=True),
  C('A double charge is merged into one at the end of the day', 'Uma cobrança dupla é combinada numa só no fim do dia',
    'A charge is a decision, not a count: there is nothing to merge it with.', 'Uma cobrança é uma decisão, não uma contagem: não há com o que combiná-la.'),
  C('Customers prefer an error message to a short delay', 'Os clientes preferem uma mensagem de erro a uma espera curta',
    'The argument is about which failure can be undone, not about taste.', 'O argumento é sobre qual falha pode ser desfeita, não sobre gosto.'),
  C('On a CP system a payment cannot be charged twice in any case', 'Num sistema CP um pagamento não pode ser cobrado duas vezes em caso algum',
    'A careless client can still send it twice; the refusal is what stops the cut doing so.', 'Um cliente descuidado ainda pode enviá-lo duas vezes; a recusa é o que impede o corte de fazer isso.')),
Q('ex-gprmr92j', 'choosing-consistency', 'medium',
  ('Which cost of choosing consistency is paid on a day when nothing is broken?', 'Qual custo de escolher a consistência é pago num dia em que nada está quebrado?'),
  ('The theorem does not mention it.', 'O teorema não o menciona.'),
  C('The minority side of the network refuses requests', 'O lado minoritário da rede recusa requisições',
    'That needs a cut; on a calm day there is no minority side.', 'Isso precisa de um corte; num dia calmo não há lado minoritário.'),
  C('Copies diverge and have to be merged later', 'As cópias divergem e precisam ser combinadas depois',
    'That is the bill of the AP side.', 'Essa é a conta do lado AP.'),
  C('Each write waits until a majority has answered', 'Cada escrita espera uma maioria responder',
    'Right: PACELC calls this the latency side of the trade.', 'Isso: o PACELC chama isso de lado da latência da troca.', ok=True),
  C('Every read compares timestamps across all the copies', 'Toda leitura compara horários entre todas as cópias',
    'Comparing timestamps is last write wins, an AP technique.', 'Comparar horários é a última escrita vence, uma técnica AP.')),
# ---- choosing-availability
Q('ex-kkvzc57r', 'choosing-availability', 'easy',
  ('In `merge.py`, why did last write wins keep 7?', 'No `merge.py`, por que a última escrita vence ficou com 7?'),
  ('Look at the two `at` fields.', 'Olhe os dois campos `at`.'),
  C('The rule always keeps whichever value is larger', 'A regra sempre fica com o valor que for maior',
    'It compares times, not values; a later 5 would have won.', 'Ela compara horários, não valores; um 5 posterior teria vencido.'),
  C('The return was stamped 08:05, which is later than the ride’s 08:02', 'A devolução tinha horário 08:05, posterior às 08:02 da viagem retirada',
    'Right: 08:05 beats 08:02, and the ride is thrown away.', 'Isso: 08:05 vence 08:02, e a viagem é jogada fora.', ok=True),
  C('The node that was cut off has the final say once it is back', 'O nó que ficou isolado tem a palavra final quando volta',
    'Which node was cut does not enter the rule at all.', 'Qual nó foi isolado nem entra na regra.'),
  C('A return cancels any ride taken from the same station', 'Uma devolução cancela qualquer viagem retirada da mesma estação',
    'The rule knows nothing of rides or returns, only timestamps.', 'A regra não sabe nada de viagens ou devoluções, só de horários.')),
N('ex-hnzz59yd', 'choosing-availability', 'easy',
  ('What count did the merged counter in `merge.py` give for ST02?', 'Que contagem o contador combinado do `merge.py` deu para a ST02?'),
  ('The line `merged counter:`.', 'A linha `merged counter:`.'),
  6, 0, ('bicycles', 'bicicletas')),
MC('ex-007qqv2h', 'choosing-availability', 'medium',
  ('What makes the counter safe to merge whenever two copies meet? Choose all that apply.',
   'O que torna o contador seguro de combinar sempre que duas cópias se encontram? Marque todas as que se aplicam.'),
  ('The last two lines of the output test two of them.', 'As duas últimas linhas da saída testam duas delas.'),
  C('The order of a merge makes no difference', 'A ordem da combinação não faz diferença',
    'Yes: "either order: True".', 'Sim: "either order: True".', ok=True),
  C('Merging the same copy twice changes nothing', 'Combinar a mesma cópia duas vezes não muda nada',
    'Yes: "merged twice: True".', 'Sim: "merged twice: True".', ok=True),
  C('Each node counts only what it saw itself', 'Cada nó conta só o que ele próprio viu',
    'Yes: that is what lets the merge take the larger number per node.', 'Sim: é isso que deixa a combinação ficar com o maior número por nó.', ok=True),
  C('The merge keeps the copy with the latest timestamp', 'A combinação fica com a cópia de horário mais recente',
    'That is last write wins, the rule that lost a bicycle.', 'Essa é a última escrita vence, a regra que perdeu uma bicicleta.'),
  C('The nodes elect a leader before they merge anything', 'Os nós elegem um líder antes de combinar qualquer coisa',
    'No leader is needed; that is the point of the shape.', 'Nenhum líder é preciso; é esse o ponto do formato.')),
Z('ex-xtxkqbs8', 'choosing-availability', 'easy',
  ('A data type built so that any two of its copies can be merged is called a ___.', 'Um tipo de dado construído para que quaisquer duas cópias dele se combinem se chama ___.'),
  ('Four capital letters, named in 2011.', 'Quatro letras maiúsculas, um nome de 2011.'),
  ['CRDT', 'CRDTs'], ['CRDT', 'CRDTs']),
Q('ex-h0xnjxfx', 'choosing-availability', 'hard',
  ('Why does last write wins depend on the nodes’ clocks?', 'Por que a última escrita vence depende dos relógios dos nós?'),
  ('Lesson 9: clocks disagree.', 'Aula 9: relógios discordam.'),
  C('Clocks decide which node becomes leader after a cut', 'Os relógios decidem que nó vira líder depois de um corte',
    'Last write wins has no leader; it only compares stamps.', 'A última escrita vence não tem líder; ela só compara horários.'),
  C('A fast clock lets an earlier write win', 'Um relógio adiantado faz uma escrita anterior vencer',
    'Right: the stamp, not the moment, decides.', 'Isso: quem decide é o horário anotado, não o momento.', ok=True),
  C('Two writes with the same stamp are both thrown away', 'Duas escritas com o mesmo horário são ambas jogadas fora',
    'A tie needs some rule, but the danger is a stamp that is wrong.', 'Um empate precisa de alguma regra, mas o perigo é um horário errado.'),
  C('The merge counts the seconds between the two writes', 'A combinação conta os segundos entre as duas escritas',
    'It compares two stamps and keeps one; it counts nothing.', 'Ela compara dois horários e fica com um; não conta nada.')),
Q('ex-tw89mtgm', 'choosing-availability', 'medium',
  ('Why did Dynamo’s shopping cart suit the side that answers during a cut?', 'Por que o carrinho de compras do Dynamo combinava com o lado que responde durante um corte?'),
  ('What happens to two versions of one cart?', 'O que acontece com duas versões de um carrinho?'),
  C('Carts are too small for a partition to affect them', 'Carrinhos são pequenos demais para uma partição afetá-los',
    'Size has nothing to do with it; any copied value can diverge.', 'Tamanho não tem nada a ver; qualquer valor copiado pode divergir.'),
  C('Carts are stored on one machine, out of reach of the network', 'Carrinhos ficam numa máquina só, fora do alcance da rede',
    'They were replicated, which is why two versions could exist.', 'Eles eram replicados, e por isso duas versões podiam existir.'),
  C('Two carts merge cleanly, and an error loses the sale', 'Dois carrinhos se combinam, e um erro custa uma venda ao site',
    'Right: a wrong cart for a minute is cheaper than a refused click.', 'Isso: um carrinho errado por um minuto sai mais barato que um clique recusado.', ok=True),
  C('Customers expect their cart to be out of date', 'Os clientes esperam que o carrinho esteja desatualizado',
    'Nobody expects it; the merge makes it rarely visible.', 'Ninguém espera; a combinação é que faz isso aparecer pouco.')),
# ---- pacelc
Q('ex-x6g6jbt9', 'pacelc', 'easy',
  ('What does the E in PACELC stand for?', 'O que quer dizer o E de PACELC?'),
  ('Read the name as a sentence.', 'Leia o nome como uma frase.'),
  C('Eventual, as in eventual consistency', 'Eventual, como em consistência eventual',
    'A tempting reading, but the letters spell an if and an else.', 'Uma leitura tentadora, mas as letras formam um se e um senão.'),
  C('Error, the reply a refusing node sends', 'Erro, a resposta que um nó que recusa envia',
    'Refusing belongs to the P half; E opens the other half.', 'Recusar é da metade P; o E abre a outra metade.'),
  C('Election, of a new leader after a crash', 'Eleição, de um novo líder depois de uma queda',
    'Elections exist, but they are not in the name.', 'Eleições existem, mas não estão no nome.'),
  C('Else: what to choose when nothing is partitioned', 'Senão: a escolha de quando não há partição',
    'Right: else, choose latency or consistency.', 'Isso: senão, escolha latência ou consistência.', ok=True)),
Q('ex-j4j6tbq2', 'pacelc', 'medium',
  ('Why is there a choice between latency and consistency when nothing is broken?', 'Por que existe uma escolha entre latência e consistência quando nada está quebrado?'),
  ('What does being sure wait for?', 'Pelo que ter certeza espera?'),
  C('A consistent read has to scan every row of the data set', 'Uma leitura consistente precisa varrer toda linha do conjunto de dados',
    'Consistency is about which copy answers, not how much is read.', 'Consistência é sobre qual cópia responde, não quanto se lê.'),
  C('Detecting partitions slows every request down a little', 'Detectar partições deixa toda requisição um pouco mais lenta',
    'The wait is for agreement, and it is there with or without detection.', 'A espera é pelo acordo, e existe com ou sem detecção.'),
  C('Agreeing with another copy costs a message there and back', 'Concordar com outra cópia custa uma mensagem de ida e outra de volta pela rede',
    'Right: waiting for another copy is what being sure costs.', 'Isso: esperar outra cópia é o preço de ter certeza.', ok=True),
  C('Consistent systems write every record to disk twice', 'Sistemas consistentes gravam todo registro no disco duas vezes',
    'Disk writes are not what the letters describe.', 'Gravações em disco não são o que as letras descrevem.')),
M('ex-efw8mmte', 'pacelc', 'medium',
  ('Match each PACELC pair to what the system does.', 'Associe cada par do PACELC ao que o sistema faz.'),
  ('The first letter pair is the cut; the second is the calm day.', 'O primeiro par de letras é o corte; o segundo é o dia calmo.'),
  [(('PA/EL', 'PA/EL'), ('answers during a cut, answers fast otherwise', 'responde no corte, responde rápido no resto do tempo')),
   (('PC/EC', 'PC/EC'), ('refuses during a cut, waits for agreement otherwise', 'recusa no corte, espera o acordo no resto do tempo')),
   (('PA/EC', 'PA/EC'), ('answers during a cut, waits for agreement otherwise', 'responde no corte, espera o acordo no resto do tempo')),
   (('PC/EL', 'PC/EL'), ('refuses during a cut, answers fast otherwise', 'recusa no corte, responde rápido no resto do tempo'))]),
Q('ex-at547013', 'pacelc', 'hard',
  ('Cassandra keeps three copies. Which levels make a read see the last write?', 'O Cassandra guarda três cópias. Que níveis fazem uma leitura ver a última escrita?'),
  ('Lesson 9: R + W > N.', 'Aula 9: R + W > N.'),
  C('`ONE` for writes and `QUORUM` for reads', '`ONE` nas escritas e `QUORUM` nas leituras',
    '1 + 2 = 3, which is not more than 3: the read can miss the copy that took the write.', '1 + 2 = 3, que não passa de 3: a leitura pode perder a cópia que recebeu a escrita.'),
  C('`QUORUM` for both', '`QUORUM` nos dois',
    'Right: 2 + 2 = 4 > 3, so the two always share a copy.', 'Isso: 2 + 2 = 4 > 3, então os dois sempre têm uma cópia em comum.', ok=True),
  C('`ONE` for both, on a fast enough network', '`ONE` nos dois, numa rede rápida o bastante',
    'Speed does not help: 1 + 1 can name two different copies.', 'Velocidade não ajuda: 1 + 1 pode cair em duas cópias diferentes.'),
  C('`QUORUM` for writes and `ONE` for reads', '`QUORUM` nas escritas e `ONE` nas leituras',
    '2 + 1 = 3 again: the one copy read may be the one the write skipped.', '2 + 1 = 3 de novo: a cópia lida pode ser a que a escrita pulou.')),
# ---- consistency-models
M('ex-75evdks3', 'consistency-models', 'medium',
  ('Match each consistency model to the surprise it rules out at Roda Livre.', 'Associe cada modelo de consistência à surpresa que ele impede na Roda Livre.'),
  ('Two of them are promises to one session.', 'Dois deles são promessas a uma sessão.'),
  [(('strong', 'forte'), ('a reader seeing 7 after another was told 5', 'um leitor ver 7 depois de outro ouvir 5')),
   (('read-your-writes', 'ler as próprias escritas'), ('ana’s finished ride still showing as open', 'a viagem encerrada de ana ainda aparecer aberta')),
   (('monotonic reads', 'leituras monotônicas'), ('the map going from 6 back to 5', 'o mapa voltar de 6 para 5')),
   (('eventual', 'eventual'), ('copies that never agree once writes stop', 'cópias que nunca concordam depois que as escritas param'))]),
Q('ex-9n7rnywa', 'consistency-models', 'easy',
  ('ana returns a bicycle and the app still shows her ride as open. Which guarantee is missing?',
   'ana devolve uma bicicleta e o aplicativo ainda mostra a viagem dela como aberta. Que garantia está faltando?'),
  ('It is about her own action.', 'É sobre a própria ação dela.'),
  C('Monotonic reads', 'Leituras monotônicas',
    'That stops going backwards after seeing something newer; she never saw the return.', 'Essa impede voltar atrás depois de ver algo mais novo; ela nunca viu a devolução.'),
  C('Read-your-writes', 'Ler as próprias escritas',
    'Right: her own write should be visible to her.', 'Isso: a escrita dela deveria ser visível para ela.', ok=True),
  C('Eventual consistency', 'Consistência eventual',
    'This is still eventual: the copies will agree later.', 'Isso ainda é eventual: as cópias vão concordar depois.'),
  C('Partition tolerance', 'Tolerância a partições de rede',
    'Nothing here needs a cut; one lagging copy is enough.', 'Nada aqui precisa de corte; basta uma cópia atrasada.')),
Q('ex-6w88ywqg', 'consistency-models', 'medium',
  ('What does eventual consistency promise?', 'O que a consistência eventual promete?'),
  ('It says nothing about the meantime.', 'Ela não diz nada sobre o meio-tempo.'),
  C('Every read is at most a second behind the latest write', 'Toda leitura fica no máximo um segundo atrás da última escrita',
    'It puts no bound on time at all.', 'Ela não põe limite de tempo nenhum.'),
  C('Copies agree a moment after each write', 'As cópias concordam um instante depois de cada escrita',
    'That is how it is heard; it promises less.', 'É assim que ela é ouvida; promete menos.'),
  C('Copies converge once the writes stop coming', 'As cópias acabam convergindo quando as escritas param',
    'Right, and not when, nor what is read on the way.', 'Isso, e não diz quando, nem o que se lê no caminho.', ok=True),
  C('A reader never sees an older value after a newer one', 'Um leitor nunca vê um valor mais velho depois de um mais novo',
    'That is monotonic reads, a stronger promise.', 'Essa é a leitura monotônica, uma promessa mais forte.')),
Q('ex-d5pjdf5a', 'consistency-models', 'hard',
  ('Why do read-your-writes and monotonic reads cost less than strong consistency?', 'Por que ler as próprias escritas e leituras monotônicas custam menos que a consistência forte?'),
  ('Who has to wait?', 'Quem precisa esperar?'),
  C('They are promises to one session', 'São promessas a uma sessão',
    'Right: only that session’s reads are steered or held, nobody else’s.', 'Isso: só as leituras daquela sessão são desviadas ou seguradas, as de mais ninguém.', ok=True),
  C('They skip the copies on the far side of the network', 'Elas pulam as cópias do outro lado da rede',
    'They may read any copy; what they constrain is which, for one reader.', 'Podem ler qualquer cópia; o que restringem é qual, para um leitor.'),
  C('They are only offered on a single machine with no replicas', 'Só são oferecidas numa máquina sem réplicas',
    'On one machine there would be nothing to promise.', 'Numa máquina só não haveria nada a prometer.'),
  C('They let the copies stop replicating for a while', 'Elas deixam as cópias pararem de replicar por um tempo',
    'Replication goes on; the promise is about what one reader sees.', 'A replicação continua; a promessa é sobre o que um leitor vê.')),
# ---- real-systems
Q('ex-agnk8ps9', 'real-systems', 'medium',
  ('Where does a PostgreSQL database on one machine sit in the figure, and why?', 'Onde fica, na figura, um banco PostgreSQL numa máquina só, e por quê?'),
  ('What would a cut separate?', 'O que um corte separaria?'),
  C('On the CP edge, as a consensus system with a leader', 'Na aresta CP, como um sistema de consenso com líder',
    'One machine runs no consensus; there is nobody to agree with.', 'Uma máquina não roda consenso; não há com quem concordar.'),
  C('On the AP edge, because a single machine answers everyone', 'Na aresta AP, porque uma máquina só responde a todos',
    'Answering everyone is easy when no copy can disagree.', 'Responder a todos é fácil quando nenhuma cópia pode discordar.'),
  C('Outside the triangle: CAP does not apply to SQL', 'Fora do triângulo: o CAP não se aplica a SQL',
    'The query language is irrelevant; the number of copies decides.', 'A linguagem de consulta não importa; quem decide é o número de cópias.'),
  C('On the C–A edge, because there is no network to cut between copies', 'Na aresta C–A, porque não há rede entre cópias para ser cortada',
    'Right: a second copy would move it to one of the other edges.', 'Isso: uma segunda cópia o levaria para uma das outras arestas.', ok=True)),
Q('ex-cc64mbhk', 'real-systems', 'medium',
  ('Unclean leader election is off and every in-sync copy of a Kafka partition is gone. What does Kafka do?',
   'A eleição de líder "suja" está desligada e todas as cópias em sincronia de uma partição do Kafka sumiram. O que o Kafka faz?'),
  ('Waiting is the C.', 'Esperar é o C.'),
  C('Promotes the most recent copy that is out of sync', 'Promove a cópia fora de sincronia mais recente',
    'That is what switching unclean election on allows, at the price of lost messages.', 'É isso que ligar a eleição suja permite, ao preço de mensagens perdidas.'),
  C('Waits for an in-sync copy to return', 'Espera até que uma cópia em sincronia volte',
    'Right: it refuses rather than lose messages.', 'Isso: ele recusa em vez de perder mensagens.', ok=True),
  C('Accepts writes on every broker and merges them later', 'Aceita escritas em todo broker e as combina depois',
    'Kafka keeps one leader per partition and does not merge.', 'O Kafka mantém um líder por partição e não combina.'),
  C('Deletes the partition and creates it again, empty', 'Apaga a partição e a cria de novo, vazia',
    'Nothing is deleted; the partition is unavailable until a copy returns.', 'Nada é apagado; a partição fica indisponível até uma cópia voltar.')),
Q('ex-tgy2bzd6', 'real-systems', 'easy',
  ('What changed about Amazon S3 in December 2020?', 'O que mudou no Amazon S3 em dezembro de 2020?'),
  ('Workarounds became dead weight.', 'Contornos viraram peso morto.'),
  C('Uploads became eventually consistent to make them faster', 'Os envios ficaram eventualmente consistentes para ficarem mais rápidos',
    'The change went the other way.', 'A mudança foi no sentido contrário.'),
  C('It began refusing writes whenever a region was cut off', 'Passou a recusar escritas sempre que uma região ficava isolada',
    'The change was about what a read returns after a write.', 'A mudança foi sobre o que uma leitura devolve depois de uma escrita.'),
  C('Overwrites began to be settled by last write wins across regions', 'As sobrescritas passaram a ser resolvidas por última escrita vence entre regiões',
    'The section names no such change.', 'A seção não cita mudança assim.'),
  C('Reads straight after a write became strongly consistent', 'As leituras logo após uma escrita ficaram fortemente consistentes',
    'Right: an overwritten file is read back in its new version.', 'Isso: um arquivo sobrescrito é lido de volta na versão nova.', ok=True)),
Q('ex-pshj2eqf', 'real-systems', 'hard',
  ('Why is "Cassandra is AP" a statement about a default rather than a fact?', 'Por que "o Cassandra é AP" é uma afirmação sobre um padrão, e não um fato?'),
  ('Its consistency level travels with each request.', 'O nível de consistência vai junto com cada requisição.'),
  C('`QUORUM` makes the minority side refuse', '`QUORUM` faz o lado minoritário recusar',
    'Right: per request, it can behave as CP.', 'Isso: por requisição, ele pode se comportar como CP.', ok=True),
  C('It was mislabelled for years and has really been CP all along', 'Foi mal rotulado por anos e sempre foi CP de verdade',
    'By default it answers on both sides; the label is right about the default.', 'Por padrão ele responde dos dois lados; o rótulo acerta sobre o padrão.'),
  C('It keeps a single copy, so CAP does not apply to it', 'Ele guarda uma cópia só, então o CAP não se aplica a ele',
    'It keeps several copies, which is why the levels exist.', 'Ele guarda várias cópias, e é por isso que os níveis existem.'),
  C('In a cluster of three nodes, AP and CP behave the same way', 'Num cluster de três nós, AP e CP se comportam do mesmo jeito',
    'The capture showed three nodes behaving in two different ways.', 'A captura mostrou três nós se comportando de dois jeitos diferentes.')),
# ---- cap-in-roda-livre
Q('ex-1medzjsh', 'cap-in-roda-livre', 'easy',
  ('Which question decides whether a piece of Roda Livre’s data goes on the side that refuses or the side that answers?',
   'Que pergunta decide se um dado da Roda Livre vai para o lado que recusa ou para o lado que responde?'),
  ('Imagine both sides of a cut saying yes.', 'Imagine os dois lados de um corte dizendo sim.'),
  C('How large the data is, and how quickly it grows each month', 'Quão grande o dado é, e quão rápido cresce a cada mês',
    'Volume is lesson 7’s question; it does not decide what a cut should do.', 'Volume é a pergunta da aula 7; não decide o que um corte deve fazer.'),
  C('Which database the company already runs for its other data', 'Que banco a empresa já roda para os outros dados',
    'That is choosing by letters for the whole company, the mistake the section names.', 'Isso é escolher pelas letras para a empresa inteira, o erro que a seção nomeia.'),
  C('If both sides said yes, could the two answers be merged afterwards?', 'Se os dois lados dissessem sim, daria para combinar as respostas depois?',
    'Right: if they merge, answer; if not, refuse.', 'Isso: se combinam, responda; se não, recuse.', ok=True),
  C('How many people read it on an ordinary day', 'Quantas pessoas o leem num dia comum',
    'Popular data can sit on either side.', 'Dado popular pode ficar de qualquer lado.')),
MC('ex-v4d5j8jb', 'cap-in-roda-livre', 'medium',
  ('Which of these can safely answer on both sides of a cut? Choose all that apply.', 'Quais destes podem responder com segurança dos dois lados de um corte? Marque todos os que se aplicam.'),
  ('Ask whether two answers merge.', 'Pergunte se duas respostas se combinam.'),
  C('The dock map in the app', 'O mapa de docas do aplicativo',
    'Yes: counts merge, and a map slightly behind still helps.', 'Sim: contagens se combinam, e um mapa um pouco atrasado ainda ajuda.', ok=True),
  C('Readings from the dock sensors', 'As leituras dos sensores das docas',
    'Yes: a reading is a fact, and duplicates are dropped by id.', 'Sim: uma leitura é um fato, e duplicatas caem pelo id.', ok=True),
  C('The payment for a ride', 'O pagamento de uma viagem',
    'No: a double charge becomes a refund and a phone call.', 'Não: uma cobrança dupla vira um estorno e um telefonema.'),
  C('Which customer holds bicycle `B017`', 'Que cliente está com a bicicleta `B017`',
    'No: one bicycle, one rider.', 'Não: uma bicicleta, um ciclista.')),
Q('ex-gdjhmc7g', 'cap-in-roda-livre', 'medium',
  ('What does a data platform promise in place of linearisability?', 'O que uma plataforma de dados promete no lugar da linearizabilidade?'),
  ('Lesson 2 made it a target.', 'A aula 2 a transformou numa meta.'),
  C('That every copy agrees with the source at every moment', 'Que toda cópia concorde com a fonte a todo momento',
    'That is linearisability itself, which the platform gave up on purpose.', 'Isso é a própria linearizabilidade, da qual a plataforma abriu mão de propósito.'),
  C('Freshness: a known delay, stated in advance and measured', 'Atualidade: um atraso conhecido, declarado antes e medido',
    'Right: behind by an amount it states and measures.', 'Isso: atrasada numa medida que ela declara e mede.', ok=True),
  C('That it answers on both sides of any network cut', 'Que responde dos dois lados de qualquer corte de rede',
    'The platform reads a copy; cuts in the app’s store are not its question.', 'A plataforma lê uma cópia; cortes no banco do aplicativo não são pergunta dela.'),
  C('That every report is recomputed from the source on each read', 'Que todo relatório é recalculado a partir da fonte a cada leitura',
    'That would put the platform back on the source’s clock and load.', 'Isso poria a plataforma de volta no relógio e na carga da fonte.')),
Q('ex-dg7v1nvs', 'cap-in-roda-livre', 'hard',
  ('Roda Livre adds reservations: a customer can hold a bicycle for ten minutes before riding. Which side should a reservation go on?',
   'A Roda Livre cria reservas: um cliente pode segurar uma bicicleta por dez minutos antes de pedalar. De que lado uma reserva deve ficar?'),
  ('Two customers, one bicycle.', 'Dois clientes, uma bicicleta.'),
  C('The answering side, since a reservation is just another entry on the map', 'O lado que responde, já que uma reserva é só mais uma entrada no mapa',
    'A map entry merges; two holds on one bicycle do not.', 'Uma entrada no mapa se combina; duas reservas de uma bicicleta não.'),
  C('Neither: it belongs in the nightly batch with the morning report', 'Nenhum: ela pertence ao lote noturno, com o relatório matinal',
    'A reservation is needed now, not tomorrow morning.', 'Uma reserva é necessária agora, não amanhã cedo.'),
  C('The refusing side: two holds cannot merge', 'O lado que recusa: duas reservas não se combinam',
    'Right: it is the unlock decision, ten minutes early.', 'Isso: é a decisão do destravamento, dez minutos antes.', ok=True),
  C('The answering side, provided timestamps settle any tie afterwards', 'O lado que responde, desde que horários resolvam o empate depois',
    'Last write wins would silently cancel one customer’s hold.', 'A última escrita vence cancelaria em silêncio a reserva de um cliente.')),
# ---- the-whole-map
O('ex-wdqksa3p', 'the-whole-map', 'easy',
  ('Put the stages of lesson 3’s lifecycle in order.', 'Ponha as etapas do ciclo de vida da aula 3 em ordem.'),
  ('The middle row of the map, left to right.', 'A linha do meio do mapa, da esquerda para a direita.'),
  [('generation', 'geração'), ('ingestion', 'ingestão'), ('storage', 'armazenamento'),
   ('transformation', 'transformação'), ('delivery', 'entrega')],
  ('Data is stored raw before it is transformed, so the raw copy survives a bad transformation.',
   'O dado é guardado bruto antes de ser transformado, para que a cópia bruta sobreviva a uma transformação ruim.')),
Q('ex-13k5v6g8', 'the-whole-map', 'easy',
  ('Lesson 7 only introduced checks at the door. Which course takes data quality further?',
   'A aula 7 só apresentou as verificações na porta. Que curso leva a qualidade do dado adiante?'),
  ('The transformation stage names two.', 'A etapa de transformação nomeia dois.'),
  C('`statistics`, the next course in the track', '`statistics`, o próximo curso da trilha',
    'It teaches what to do with a number once it can be trusted.', 'Ele ensina o que fazer com um número quando ele merece confiança.'),
  C('`data-cleaning`, which measures and repairs it', '`data-cleaning`, que mede e conserta a qualidade',
    'Right: quality measured and repaired in depth.', 'Isso: qualidade medida e consertada a fundo.', ok=True),
  C('`warehouse-modeling`, which organises the stored data', '`warehouse-modeling`, que organiza o dado guardado',
    'It models the warehouse; quality in depth is another course.', 'Ele modela o data warehouse; qualidade a fundo é outro curso.'),
  C('`streaming`, which handles late and duplicate events', '`streaming`, que trata eventos atrasados e duplicados',
    'It walks lesson 8’s region, not quality in general.', 'Ele percorre a região da aula 8, não a qualidade em geral.')),
Q('ex-6jjq11d9', 'the-whole-map', 'medium',
  ('Last write wins lost a bicycle and printed nothing. Which of the four recurring ideas is that?',
   'A última escrita vence perdeu uma bicicleta e não imprimiu nada. Qual das quatro ideias recorrentes é essa?'),
  ('Lesson 1’s `twice.py` was another one.', 'O `twice.py` da aula 1 foi outra.'),
  C('A loud failure, which names itself', 'Uma falha barulhenta, que se identifica',
    'Nothing stopped and nothing was named: that is the other kind.', 'Nada parou e nada foi nomeado: esse é o outro tipo.'),
  C('A copy that somebody declared to be behind', 'Uma cópia que alguém declarou atrasada',
    'A declared delay is honest; this loss was invisible.', 'Um atraso declarado é honesto; essa perda foi invisível.'),
  C('A quiet failure', 'Uma falha silenciosa',
    'Right: a plausible wrong number, the kind the profession exists to prevent.', 'Isso: um número errado e plausível, o tipo que a profissão existe para evitar.', ok=True),
  C('A trade-off with a right side in general', 'Uma troca com um lado certo em geral',
    'The section says no trade-off has a right side in general.', 'A seção diz que nenhuma troca tem lado certo em geral.')),
# ---- drill
O('ex-j5a9rzbs', 'drill', 'medium',
  ('Put the events of the `ap` run, and what follows it, in order.', 'Ponha os eventos da execução `ap`, e o que vem depois dela, em ordem.'),
  ('The cut comes before anything diverges.', 'O corte vem antes de qualquer divergência.'),
  [('the link to `n3` is cut', 'o enlace até o `n3` é cortado'),
   ('`n1` accepts 5 for itself and `n2`', 'o `n1` aceita 5 para si e para o `n2`'),
   ('`n3` accepts 7 on its own', 'o `n3` aceita 7 sozinho'),
   ('readers see 5 on `n2` and 7 on `n3`', 'leitores veem 5 no `n2` e 7 no `n3`'),
   ('the link heals and the copies are merged', 'o enlace volta e as cópias são combinadas')],
  ('Divergence needs the cut first, and the merge needs the link back.', 'A divergência precisa do corte antes, e a combinação precisa do enlace de volta.')),
Q('ex-avsz03d6', 'drill', 'hard',
  ('A store that chose consistency has five nodes, and a cut splits them three and two. Which side accepts writes?',
   'Um banco que escolheu a consistência tem cinco nós, e um corte os separa em três e dois. Que lado aceita escritas?'),
  ('More than half of five.', 'Mais da metade de cinco.'),
  C('The side of two, if the leader happens to be on it', 'O lado de dois, se o líder estiver nele',
    'Two of five is not a majority; the leader steps down without one.', 'Dois de cinco não é maioria; o líder deixa o posto sem ela.'),
  C('Both sides, until the cut has been detected', 'Os dois lados, até o corte ser detectado',
    'A CP store checks for a majority before accepting, detected or not.', 'Um banco CP verifica a maioria antes de aceitar, detectado ou não.'),
  C('Neither, since no side holds all five nodes', 'Nenhum, já que nenhum lado tem os cinco nós',
    'A majority is enough; unanimity would make every cut fatal.', 'Maioria basta; unanimidade tornaria todo corte fatal.'),
  C('The side of three, because three of five is a majority', 'O lado de três, que é maioria entre cinco',
    'Right: three of five is a majority, and there cannot be two.', 'Isso: três de cinco é maioria, e não pode haver duas.', ok=True)),
Q('ex-yfj1evg0', 'drill', 'hard',
  ('During a cut, the app still shows the dock map but greys out the unlock button. What has Roda Livre done?',
   'Durante um corte, o aplicativo ainda mostra o mapa de docas mas desativa o botão de destravar. O que a Roda Livre fez?'),
  ('Two pieces of data, two answers.', 'Dois dados, duas respostas.'),
  C('Chosen availability for the whole app, and failed to deliver it', 'Escolheu disponibilidade para o aplicativo inteiro, e não conseguiu entregá-la',
    'The greyed button is a deliberate refusal, not a failure of AP.', 'O botão desativado é uma recusa deliberada, não uma falha do AP.'),
  C('Chosen per piece of data: AP map, CP unlock', 'Escolheu por dado: mapa AP, destravamento CP',
    'Right: each part of the app got the answer its data needs.', 'Isso: cada parte do aplicativo recebeu a resposta de que o seu dado precisa.', ok=True),
  C('Chosen consistency for the whole app, apart from the cache', 'Escolheu consistência para o aplicativo inteiro, fora o cache',
    'The map answering during a cut is availability, whatever stores it.', 'O mapa respondendo durante um corte é disponibilidade, seja onde for guardado.'),
  C('Avoided the partition by keeping a copy on the phone', 'Evitou a partição guardando uma cópia no celular',
    'A copy on the phone is one more copy that can fall behind.', 'Uma cópia no celular é mais uma cópia que pode ficar atrasada.')),
Z('ex-jyxa86t6', 'drill', 'easy',
  ('PACELC: if there is a Partition, choose Availability or Consistency; Else, choose ___ or Consistency.',
   'PACELC: se há uma partição, escolha disponibilidade ou consistência; senão, escolha ___ ou consistência.'),
  ('What you pay to wait for another copy.', 'O que você paga para esperar outra cópia.'),
  ['latency'], ['latência', 'latency']),
]
