from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
# ---- this-course
Q('ex-c1hsmz49', 'this-course', 'easy',
  ('What does this course do with a word like "partition" or "stream"?',
   'O que este curso faz com uma palavra como "partição" ou "fluxo"?'),
  ('It is the map, not the territory.', 'Ele é o mapa, não o território.'),
  C('Names it, and shows it happening once', 'Dá nome a ela, e a mostra acontecendo uma vez',
    'Right: the vocabulary, seen once on your own machine.', 'Isso: o vocabulário, visto uma vez na sua máquina.', ok=True),
  C('Teaches the tools that implement it, in full depth and with every option', 'Ensina a fundo as ferramentas que a implementam, com todas as opções',
    'That is what the courses after it spend forty or seventy hours on.', 'É nisso que os cursos seguintes gastam quarenta ou setenta horas.'),
  C('Leaves it for a later course in the track to define properly', 'Deixa para um curso posterior da trilha definir direito',
    'The later courses assume the word; this is where it is learnt.', 'Os cursos seguintes supõem a palavra; é aqui que ela se aprende.'),
  C('Defines it in a glossary at the end', 'Define num glossário no fim',
    'There is no glossary: each word is met where it happens.', 'Não há glossário: cada palavra aparece onde acontece.')),
Q('ex-jq7g1rpb', 'this-course', 'easy',
  ('Where does the data used in this course come from?', 'De onde vêm os dados usados neste curso?'),
  ('Nothing is downloaded.', 'Nada é baixado.'),
  C('From a public data set published by a real bicycle-sharing company', 'De um conjunto público publicado por uma empresa real de bicicletas',
    'Roda Livre does not exist, and nothing is downloaded.', 'A Roda Livre não existe, e nada é baixado.'),
  C('From short programs the lessons print, run from fixed seeds', 'De programas curtos que as aulas mostram, com sementes fixas',
    'Right, which is why your numbers match the text.', 'Isso, e é por isso que os seus números batem com o texto.', ok=True),
  C('From files the platform copies to your machine', 'De arquivos que a plataforma copia para a sua máquina',
    'The platform runs and copies nothing; you run everything.', 'A plataforma não roda nem copia nada; você roda tudo.'),
  C('From the sample data inside pyarrow', 'Dos dados de exemplo que vêm no pyarrow',
    'pyarrow is a library for formats, not a source of data.', 'O pyarrow é uma biblioteca de formatos, não uma fonte de dados.')),
Q('ex-41j6zegk', 'this-course', 'medium',
  ('A lesson reaches the point where writing SQL queries would be the next step. What does it do?',
   'Uma aula chega ao ponto em que escrever consultas SQL seria o passo seguinte. O que ela faz?'),
  ('A map names regions.', 'Um mapa nomeia regiões.'),
  C('Teaches enough SQL to finish the example', 'Ensina SQL suficiente para terminar o exemplo',
    'That would be teaching another course’s subject badly.', 'Isso seria ensinar mal o assunto de outro curso.'),
  C('Skips the step without saying anything', 'Pula o passo sem dizer nada',
    'It says where the subject continues.', 'Ela diz onde o assunto continua.'),
  C('Names `sql-databases`, and stops', 'Cita `sql-databases`, e para',
    'Right: each edge of the course names the course beyond it.', 'Isso: cada borda do curso nomeia o curso além dela.', ok=True),
  C('Asks the student to look the syntax up online', 'Pede ao aluno que procure a sintaxe na internet',
    'The course points at a course, not at a search.', 'O curso aponta para um curso, não para uma busca.')),
# ---- one-question
Q('ex-4g9krzam', 'one-question', 'easy',
  ('Why could nobody at Roda Livre answer "which stations ran out last week" on Monday?',
   'Por que ninguém na Roda Livre conseguia responder "quais estações esvaziaram na semana passada" na segunda?'),
  ('Think about what each system was built for.', 'Pense no que cada sistema foi feito para fazer.'),
  C('It was spread over three systems', 'Ela estava espalhada por três sistemas',
    'Right: the data existed, but not in an answerable shape.', 'Isso: o dado existia, mas não num formato respondível.', ok=True),
  C('The question needed a machine-learning model to be trained first', 'A pergunta precisava antes de um modelo de machine learning treinado',
    'It asks what happened, not what will happen.', 'Ela pergunta o que aconteceu, não o que vai acontecer.'),
  C('Nobody had recorded which docks held bicycles', 'Ninguém tinha registrado quais docas tinham bicicleta',
    'The sensors record that every minute; they just keep it two days.', 'Os sensores registram isso a cada minuto; só guardam por dois dias.'),
  C('The app database was too slow to query', 'O banco do aplicativo era lento demais para consultar',
    'Speed was not the obstacle; shape and history were.', 'A velocidade não era o obstáculo; o formato e a história eram.')),
Q('ex-e10ja0fb', 'one-question', 'medium',
  ('The app database keeps the current state of every bicycle. Why is that a problem for Marta’s question?',
   'O banco do aplicativo guarda o estado atual de cada bicicleta. Por que isso é um problema para a pergunta de Marta?'),
  ('Her question is about last week.', 'A pergunta dela é sobre a semana passada.'),
  C('The current state is stored in a binary format that nobody can read', 'O estado atual fica num formato binário que ninguém consegue ler',
    'It is readable; it is just not history.', 'Ele é legível; só não é história.'),
  C('Last week’s state has been overwritten', 'O estado da semana passada foi sobrescrito',
    'Right: a system built to charge customers keeps now, not then.', 'Isso: um sistema feito para cobrar guarda o agora, não o antes.', ok=True),
  C('The state is only updated once a month', 'O estado só é atualizado uma vez por mês',
    'It is updated on every ride.', 'Ele é atualizado a cada viagem.'),
  C('Current state includes bicycles in broken docks', 'O estado atual inclui bicicletas em docas quebradas',
    'True, but that is a definition problem, not a history problem.', 'Verdade, mas isso é problema de definição, não de história.')),
Q('ex-qwv92bnb', 'one-question', 'medium',
  ('Which of these is the data engineer’s part of answering Marta’s question?',
   'Qual destas é a parte do engenheiro de dados ao responder a pergunta de Marta?'),
  ('Who makes the question answerable?', 'Quem torna a pergunta respondível?'),
  C('Deciding that "ran out" means zero bicycles available for five minutes or more', 'Decidir que "esvaziar" quer dizer zero bicicletas disponíveis por cinco minutos ou mais',
    'That definition is the analyst’s.', 'Essa definição é do analista.'),
  C('Predicting which stations will run out on Friday', 'Prever quais estações vão esvaziar na sexta',
    'That is the data scientist’s next question.', 'Essa é a próxima pergunta do cientista de dados.'),
  C('Putting the sensors, rides and repairs on one clock in one place', 'Pôr sensores, viagens e consertos num só relógio e num só lugar',
    'Right: that is what makes the question answerable at all.', 'Isso: é o que torna a pergunta respondível.', ok=True),
  C('Drawing the chart Marta will look at', 'Desenhar o gráfico que Marta vai ver',
    'The chart is the analyst’s delivery.', 'O gráfico é a entrega do analista.')),
Q('ex-vaz3sppq', 'one-question', 'hard',
  ('The spreadsheet arrives with a column `doca` instead of `dock`. Which outcome does a well-built load produce?',
   'A planilha chega com uma coluna `doca` em vez de `dock`. Que resultado uma carga bem feita produz?'),
  ('Compare a loud failure with a quiet one.', 'Compare uma falha barulhenta com uma silenciosa.'),
  C('It loads the file and marks every dock as unbroken', 'Carrega o arquivo e dá todas as docas como inteiras',
    'That is the quiet failure: a plausible, wrong table.', 'Essa é a falha silenciosa: uma tabela plausível e errada.'),
  C('It stops and says which column it could not find', 'Para e diz qual coluna não encontrou',
    'Right: nobody downstream receives a wrong answer.', 'Isso: ninguém adiante recebe uma resposta errada.', ok=True),
  C('It guesses that `doca` means `dock` and carries on', 'Adivinha que `doca` quer dizer `dock` e segue',
    'A guess that is right today is wrong the day the guess is wrong.', 'Um palpite certo hoje erra no dia em que o palpite errar.'),
  C('It skips the spreadsheet and loads the other two', 'Pula a planilha e carrega as outras duas',
    'Silently missing data is still a wrong answer.', 'Dado faltando em silêncio continua sendo resposta errada.')),
Q('ex-n56xzhpa', 'one-question', 'medium',
  ('Why did one Wednesday have 27 hours of sensor readings?',
   'Por que uma quarta-feira teve 27 horas de leituras de sensor?'),
  ('Curitiba is three hours behind UTC.', 'Curitiba está três horas atrás do UTC.'),
  C('The sensors sent each reading three times', 'Os sensores mandaram cada leitura três vezes',
    'Duplicates would multiply readings, not add exactly three hours.', 'Duplicatas multiplicariam leituras, não somariam exatas três horas.'),
  C('Readings began arriving in UTC', 'As leituras passaram a vir em UTC',
    'Right: three hours of one day were labelled as the next.', 'Isso: três horas de um dia foram rotuladas como do seguinte.', ok=True),
  C('Daylight saving time started that week', 'O horário de verão começou naquela semana',
    'It would move one hour, and Brazil no longer uses it.', 'Mudaria uma hora, e o Brasil não o usa mais.'),
  C('A dock was installed in another time zone', 'Uma doca foi instalada em outro fuso',
    'All twelve stations are in Curitiba.', 'As doze estações ficam em Curitiba.')),
# ---- the-roles
M('ex-kjk0zszc', 'the-roles', 'easy',
  ('Match each role to what it delivers.', 'Associe cada cargo ao que ele entrega.'),
  ('Ask what each one hands to somebody else.', 'Pergunte o que cada um entrega a alguém.'),
  [(('data engineer', 'engenheiro de dados'), ('data that arrives on time and correct', 'dado que chega na hora e correto')),
   (('analytics engineer', 'engenheiro de analytics'), ('agreed definitions of the business’s numbers', 'definições aceitas dos números do negócio')),
   (('data analyst', 'analista de dados'), ('answers to questions already asked', 'respostas a perguntas já feitas')),
   (('data scientist', 'cientista de dados'), ('predictions and experiments', 'previsões e experimentos')),
   (('machine learning engineer', 'engenheiro de machine learning'), ('a model answering in production', 'um modelo respondendo em produção'))]),
Q('ex-3zeyr5mt', 'the-roles', 'easy',
  ('What is wrong with the picture of data roles as a ladder?', 'O que há de errado na imagem dos cargos de dados como uma escada?'),
  ('Rungs are ranked; these are not.', 'Degraus têm hierarquia; estes não.'),
  C('They are different jobs, not ranks', 'São trabalhos diferentes, não postos',
    'Right: different deliveries, not seniority.', 'Isso: entregas diferentes, não senioridade.', ok=True),
  C('The ladder is upside down: engineers are the most senior', 'A escada está de cabeça para baixo: os engenheiros são os mais sêniores',
    'Turning the ladder over keeps the wrong idea of a ladder.', 'Virar a escada mantém a ideia errada de escada.'),
  C('There are really only two roles in the field, not five', 'Na prática só existem dois cargos na área, não cinco',
    'There are five names for five kinds of work.', 'Há cinco nomes para cinco tipos de trabalho.'),
  C('Analysts and scientists are the same job', 'Analista e cientista são o mesmo trabalho',
    'One explains what happened; the other predicts and tests.', 'Um explica o que aconteceu; o outro prevê e testa.')),
Q('ex-dm06qvka', 'the-roles', 'medium',
  ('Two dashboards show different totals for "active customers". Which role’s work is missing?',
   'Dois painéis mostram totais diferentes de "clientes ativos". O trabalho de qual cargo está faltando?'),
  ('Who owns the definitions?', 'Quem cuida das definições?'),
  C('The machine learning engineer’s', 'O do engenheiro de machine learning',
    'No model is involved in a count.', 'Nenhum modelo entra numa contagem.'),
  C('The data scientist’s', 'O do cientista de dados',
    'Prediction is not the problem; agreement is.', 'Previsão não é o problema; acordo é.'),
  C('The analytics engineer’s, who keeps one agreed definition', 'O do engenheiro de analytics, que mantém uma definição aceita',
    'Right: one definition in one place.', 'Isso: uma definição num lugar só.', ok=True),
  C('Nobody’s: dashboards always differ', 'De ninguém: painéis sempre diferem',
    'Two numbers for one thing is a defect, not a fact of life.', 'Dois números para uma coisa é defeito, não destino.')),
Q('ex-rabfrwm7', 'the-roles', 'medium',
  ('Caio’s model predicts demand well in his notebook but nothing in the app uses it. Whose work is that gap?',
   'O modelo de Caio prevê bem a demanda no notebook dele, mas nada no aplicativo o usa. Essa lacuna é trabalho de quem?'),
  ('Production is a different place from a notebook.', 'Produção é um lugar diferente de um notebook.'),
  C('The analyst’s', 'Do analista',
    'Analysts answer questions; they do not deploy models.', 'Analistas respondem perguntas; não põem modelos em produção.'),
  C('The data engineer’s, who feeds the model its data', 'Do engenheiro de dados, que alimenta o modelo',
    'He feeds the data; running the model in the app is another job.', 'Ele alimenta o dado; rodar o modelo no app é outro trabalho.'),
  C('The machine learning engineer’s', 'Do engenheiro de machine learning',
    'Right: a model running in production, fed and monitored.', 'Isso: um modelo rodando em produção, alimentado e monitorado.', ok=True),
  C('The data scientist’s, by definition', 'Do cientista de dados, por definição',
    'He proves it predicts; making it answer in the app is another job.', 'Ele prova que prevê; fazê-lo responder no app é outro trabalho.')),
MC('ex-8es8s248', 'the-roles', 'medium',
  ('Which of these make the data engineer’s work different from an analyst’s? Choose all that apply.',
   'Quais destas tornam o trabalho do engenheiro de dados diferente do de um analista? Marque todas as que se aplicam.'),
  ('Three were named.', 'Foram citadas três.'),
  C('It is software that runs every day', 'É software que roda todo dia',
    'Yes: a pipeline is never finished.', 'Sim: um pipeline nunca termina.', ok=True),
  C('Its users are mostly other systems and data people', 'Os usuários são, na maioria, outros sistemas e pessoas de dados',
    'Yes: Marta sees only its absence.', 'Sim: Marta só vê a falta dele.', ok=True),
  C('Its failures are quiet', 'As falhas dele são silenciosas',
    'Yes: a double load looks fine.', 'Sim: uma carga dupla parece normal.', ok=True),
  C('It needs no SQL', 'Não precisa de SQL',
    'It uses SQL every day.', 'Ele usa SQL todo dia.')),
Q('ex-v77k3r00', 'the-roles', 'hard',
  ('A job advert asks one person for pipelines, dashboards, A/B tests and model deployment. What is it really asking for?',
   'Uma vaga pede a uma pessoa pipelines, painéis, testes A/B e implantação de modelos. O que ela está pedindo de fato?'),
  ('Count the roles in the list.', 'Conte os cargos da lista.'),
  C('A senior data scientist', 'Um cientista de dados sênior',
    'Seniority does not merge four jobs into one.', 'Senioridade não junta quatro trabalhos num.'),
  C('A small team', 'Um time pequeno',
    'Right: the roles name kinds of work, and this is four.', 'Isso: os cargos nomeiam tipos de trabalho, e aqui há quatro.', ok=True),
  C('An analytics engineer', 'Um engenheiro de analytics',
    'That role is the definitions, not deployment or tests.', 'Esse cargo é das definições, não de implantação ou testes.'),
  C('A database administrator', 'Um administrador de banco de dados',
    'None of those four is keeping one database fast.', 'Nenhum dos quatro é manter um banco rápido.')),
Q('ex-zbcksvp8', 'the-roles', 'easy',
  ('Which question does the data engineer start from?', 'De que pergunta parte o engenheiro de dados?'),
  ('Tomorrow, and every day after.', 'Amanhã, e todo dia depois.'),
  C('What will happen, and why?', 'O que vai acontecer, e por quê?',
    'That is the data scientist’s.', 'Essa é a do cientista de dados.'),
  C('What happened last month?', 'O que aconteceu no mês passado?',
    'That is the analyst’s.', 'Essa é a do analista.'),
  C('Which model should we deploy to the app this quarter?', 'Que modelo devemos pôr no aplicativo neste trimestre?',
    'That is closer to the ML engineer.', 'Essa é mais do engenheiro de ML.'),
  C('Will the data be there, and right?', 'O dado vai estar lá, e certo?',
    'Right.', 'Isso.', ok=True)),
# ---- a-week-of-work
Q('ex-vxrg877x', 'a-week-of-work', 'easy',
  ('In Davi’s week, what were most of the items?', 'Na semana de Davi, o que era a maior parte dos itens?'),
  ('Two requests, one design question, and the rest.', 'Dois pedidos, uma questão de projeto, e o resto.'),
  C('New pipelines built from scratch', 'Pipelines novos construídos do zero',
    'Only the requests were new work.', 'Só os pedidos eram trabalho novo.'),
  C('Things that broke', 'Coisas que quebraram',
    'Right: six of nine.', 'Isso: seis de nove.', ok=True),
  C('Meetings about strategy and the platform’s future', 'Reuniões sobre estratégia e o futuro da plataforma',
    'There were none in the list.', 'Não havia nenhuma na lista.'),
  C('Training models for Caio', 'Treinar modelos para o Caio',
    'Caio trains his own models.', 'Caio treina os próprios modelos.')),
M('ex-j7qz0bdy', 'a-week-of-work', 'medium',
  ('Match each event of the week to the kind of work it is.', 'Associe cada acontecimento da semana ao tipo de trabalho que ele é.'),
  ('The table named each one.', 'A tabela nomeou cada um.'),
  [(('the Sunday file arrived at 09:40', 'o arquivo de domingo chegou às 09:40'), ('freshness', 'atualidade')),
   (('a new field `promo_code` was ignored', 'um campo novo `promo_code` foi ignorado'), ('schema change', 'mudança de esquema')),
   (('a ride appeared twice after a retry', 'uma viagem apareceu duas vezes depois de um retry'), ('idempotency', 'idempotência')),
   (('the API refused calls past 100 a minute', 'a API recusou chamadas acima de 100 por minuto'), ('rate limiting', 'limitação de taxa'))]),
Q('ex-sfkac7r3', 'a-week-of-work', 'medium',
  ('What does "a pipeline is built to be operated" ask of it?', 'O que "um pipeline é construído para ser operado" pede dele?'),
  ('Think of the person on call at 06:00.', 'Pense em quem está de plantão às 06:00.'),
  C('That it runs as fast as possible', 'Que rode o mais rápido possível',
    'Speed is not on the list.', 'Velocidade não está na lista.'),
  C('That it uses one language', 'Que use uma linguagem só',
    'Language is irrelevant to operating it.', 'A linguagem é irrelevante para operá-lo.'),
  C('That it reports failures and is safe to rerun', 'Que avise das falhas e rode de novo sem estrago',
    'Right: those three make it operable.', 'Isso: essas três o tornam operável.', ok=True),
  C('That only its author changes it', 'Que só o autor o altere',
    'The opposite: somebody else must be able to tell what it did.', 'O contrário: outra pessoa precisa conseguir dizer o que ele fez.')),
O('ex-zvwx16cx', 'a-week-of-work', 'easy',
  ('Put the levels of Monica Rogati’s pyramid in order, from the bottom.', 'Ponha os níveis da pirâmide de Monica Rogati em ordem, de baixo para cima.'),
  ('Each level rests on the one beneath.', 'Cada nível se apoia no de baixo.'),
  [('collect', 'coletar'), ('move and store', 'mover e guardar'), ('explore and transform', 'explorar e transformar'),
   ('aggregate and label', 'agregar e rotular'), ('learn and optimise', 'aprender e otimizar')],
  ('Learning comes last because it needs everything below it.', 'Aprender vem por último porque precisa de tudo o que está abaixo.')),
Q('ex-80pfjtex', 'a-week-of-work', 'medium',
  ('A company hires a data scientist before anyone has built the bottom of the pyramid. What happens, according to the section?',
   'Uma empresa contrata um cientista de dados antes de alguém construir a base da pirâmide. O que acontece, segundo a seção?'),
  ('Which levels are missing?', 'Que níveis estão faltando?'),
  C('Models on raw data work fine', 'Modelos sobre dado bruto funcionam',
    'There is no reliable data to build on.', 'Não há dado confiável sobre o qual construir.'),
  C('The scientist spends the first year doing data engineering', 'O cientista passa o primeiro ano fazendo engenharia de dados',
    'Right, usually without the tools for it.', 'Isso, em geral sem as ferramentas para isso.', ok=True),
  C('The company skips straight to optimisation', 'A empresa pula direto para a otimização',
    'The top cannot stand without the bottom.', 'O topo não fica de pé sem a base.'),
  C('Nothing changes; the levels are independent', 'Nada muda; os níveis são independentes',
    'Each level rests on the ones beneath it.', 'Cada nível se apoia nos de baixo.')),
Q('ex-92zyzdrp', 'a-week-of-work', 'medium',
  ('How is a data engineer different from a database administrator?', 'Em que um engenheiro de dados difere de um administrador de banco de dados?'),
  ('One database, or many systems?', 'Um banco, ou muitos sistemas?'),
  C('One tends a single system; the other moves data between many', 'Um cuida de um sistema; o outro move dado entre muitos',
    'Right: the engineer owns what happens in between.', 'Isso: o engenheiro responde pelo que acontece no meio.', ok=True),
  C('The administrator writes no SQL at all, only configuration', 'O administrador não escreve SQL nenhum, só configuração',
    'Administrators write a great deal of it.', 'Administradores escrevem muito SQL.'),
  C('The engineer never touches a database', 'O engenheiro nunca encosta num banco',
    'He reads from them every day.', 'Ele lê de bancos todo dia.'),
  C('They are two names for one job', 'São dois nomes para um trabalho',
    'The job borrows from administration; it is not it.', 'O ofício empresta da administração; não é ela.')),
# ---- where-it-came-from
O('ex-mby1mv6d', 'where-it-came-from', 'easy',
  ('Put the three eras in the order they began.', 'Ponha as três épocas na ordem em que começaram.'),
  ('1990s, late 2000s, mid-2010s.', 'Anos 1990, fim dos 2000, meados dos 2010.'),
  [('the warehouse and ETL', 'o data warehouse e o ETL'), ('big data on clusters', 'big data em clusters'),
   ('the cloud and ELT', 'a nuvem e o ELT')],
  ('ELT only made sense once storing raw data became cheap.', 'O ELT só fez sentido quando guardar dado bruto ficou barato.')),
Z('ex-n57pwq20', 'where-it-came-from', 'easy',
  ('In ETL, the T stands for ___.', 'No ETL, o T quer dizer ___.'),
  ('Extract, ___, load.', 'Extrair, ___, carregar.'),
  ['transform'], ['transformar', 'transformação', 'transform']),
Q('ex-jdpwb9m5', 'where-it-came-from', 'medium',
  ('Why did "data engineer" become a common title in the big-data era?', 'Por que "engenheiro de dados" virou título comum na era do big data?'),
  ('What did processing data turn into?', 'No que se transformou processar dados?'),
  C('Because warehouses were invented then', 'Porque os warehouses foram inventados então',
    'Warehouses are from the 1990s.', 'Warehouses são dos anos 1990.'),
  C('Because the work became writing programs', 'Porque o trabalho virou escrever programas',
    'Right: the work had become software engineering.', 'Isso: o trabalho tinha virado engenharia de software.', ok=True),
  C('Because the cloud made ETL unnecessary', 'Porque a nuvem tornou o ETL desnecessário',
    'The cloud came later, and moved the T rather than removing it.', 'A nuvem veio depois, e mudou o T de lugar em vez de removê-lo.'),
  C('Because relational databases stopped being used by web companies', 'Porque as empresas da web deixaram de usar bancos relacionais',
    'They are still the commonest source of all.', 'Eles ainda são a fonte mais comum de todas.')),
Q('ex-56rfkv30', 'where-it-came-from', 'medium',
  ('What made ELT cheaper than ETL in the cloud era?', 'O que tornou o ELT mais barato que o ETL na era da nuvem?'),
  ('Where does the transformation run in ELT?', 'Onde a transformação roda no ELT?'),
  C('Cheap storage and warehouses that scale', 'Armazenamento barato e warehouses que escalam',
    'Right.', 'Isso.', ok=True),
  C('Transformations became unnecessary', 'As transformações ficaram desnecessárias',
    'They still happen; they happen later.', 'Elas ainda acontecem; acontecem depois.'),
  C('Sources started sending clean, ready-to-use data to the warehouse', 'As fontes passaram a mandar dado limpo e pronto para o warehouse',
    'They did not, and they still do not.', 'Não passaram, e ainda não mandam.'),
  C('Loading became slower than transforming', 'Carregar ficou mais lento que transformar',
    'Speed of loading is not the reason given.', 'Velocidade de carga não é a razão dada.')),
MC('ex-3t41jsh9', 'where-it-came-from', 'medium',
  ('Which questions have stayed the same across all three eras? Choose all that apply.',
   'Quais perguntas ficaram iguais nas três épocas? Marque todas as que se aplicam.'),
  ('Four were named.', 'Foram citadas quatro.'),
  C('Did all of it arrive?', 'Chegou tudo?', 'Yes.', 'Sim.', ok=True),
  C('Did any of it arrive twice?', 'Alguma coisa chegou duas vezes?', 'Yes.', 'Sim.', ok=True),
  C('Which vendor is cheapest this year?', 'Que fornecedor é mais barato este ano?',
    'That changes with the tools; it is not one of the four.', 'Isso muda com as ferramentas; não é uma das quatro.'),
  C('Is it here in time?', 'Chegou a tempo?', 'Yes.', 'Sim.', ok=True)),
# ---- the-lab
Q('ex-p5n3gdy7', 'the-lab', 'easy',
  ('Which path does the course recommend for the lab, and why?', 'Que caminho o curso recomenda para o laboratório, e por quê?'),
  ('What does a virtual environment change on the computer?', 'O que um ambiente virtual muda no computador?'),
  C('Online, because it costs the computer nothing', 'Online, porque não custa nada ao computador',
    'It is named, not recommended: it depends on someone’s allowance.', 'Ele é citado, não recomendado: depende da cota de alguém.'),
  C('A virtual machine, because the transcripts match exactly', 'Máquina virtual, porque as transcrições batem exatamente',
    'True of the transcripts, but it costs gigabytes for a directory’s worth of lab.', 'Vale para as transcrições, mas custa gigabytes por um laboratório do tamanho de um diretório.'),
  C('Installed, because a virtual environment is just a directory', 'Instalado, porque um ambiente virtual é só um diretório',
    'Right: it touches nothing else and deleting it removes it.', 'Isso: não mexe em mais nada e apagá-lo o remove.', ok=True),
  C('Installed, because it needs administrator rights', 'Instalado, porque precisa de direitos de administrador',
    'A virtual environment needs none.', 'Um ambiente virtual não precisa de nenhum.')),
Q('ex-jaha64w8', 'the-lab', 'easy',
  ('What are pyarrow and fastavro in the lab for?', 'Para que servem o pyarrow e o fastavro no laboratório?'),
  ('Lesson 6.', 'Aula 6.'),
  C('Parquet, ORC and Avro files', 'Arquivos Parquet, ORC e Avro',
    'Right.', 'Isso.', ok=True),
  C('Running a database server', 'Rodar um servidor de banco de dados',
    'There is no server; SQLite is a file inside Python.', 'Não há servidor; o SQLite é um arquivo dentro do Python.'),
  C('Downloading the course data', 'Baixar os dados do curso',
    'Nothing is downloaded.', 'Nada é baixado.'),
  C('Drawing charts of the results', 'Desenhar gráficos dos resultados',
    'Neither draws anything.', 'Nenhum dos dois desenha nada.')),
Q('ex-m17fx74e', 'the-lab', 'medium',
  ('Why are the library versions pinned with `==`?', 'Por que as versões das bibliotecas são fixadas com `==`?'),
  ('Lesson 6 prints something that depends on them.', 'A aula 6 mostra algo que depende delas.'),
  C('Because newer versions do not exist', 'Porque versões mais novas não existem',
    'They will; the pin is about matching the text.', 'Vão existir; a fixação serve para bater com o texto.'),
  C('Because pip refuses to install without a version', 'Porque o pip se recusa a instalar sem versão',
    'pip installs the newest one when none is given.', 'O pip instala a mais nova quando nenhuma é dada.'),
  C('So your file sizes match the text', 'Para os seus tamanhos baterem com o texto',
    'Right: another version may write a different number of bytes.', 'Isso: outra versão pode escrever outro número de bytes.', ok=True),
  C('To make the installation faster', 'Para a instalação ficar mais rápida',
    'Pinning does not change the speed.', 'Fixar não muda a velocidade.')),
Z('ex-s0q4f2f3', 'the-lab', 'easy',
  ('A virtual environment is activated in bash with `___ .venv/bin/activate`.', 'Um ambiente virtual é ativado no bash com `___ .venv/bin/activate`.'),
  ('The same word reads a file into the current shell.', 'A mesma palavra lê um arquivo no shell atual.'),
  ['source'], ['source'], ignore_case=False),
N('ex-yne2e2ev', 'the-lab', 'easy',
  ('How many megabytes did the `.venv` directory take on the recording machine?', 'Quantos megabytes o diretório `.venv` ocupou na máquina da gravação?'),
  ('`du -sh .venv`.', '`du -sh .venv`.'),
  195, 0, ('MB', 'MB')),
Q('ex-97r6gbsn', 'the-lab', 'medium',
  ('What do the lines added to `~/.bashrc` do?', 'O que fazem as linhas acrescentadas ao `~/.bashrc`?'),
  ('They run in every new terminal.', 'Elas rodam em todo terminal novo.'),
  C('Install pyarrow again in each terminal', 'Instalam o pyarrow de novo em cada terminal',
    'Installing happens once; these only activate.', 'Instalar acontece uma vez; estas só ativam.'),
  C('Set the clock and activate the environment', 'Acertam o fuso e ativam o ambiente',
    'Right.', 'Isso.', ok=True),
  C('Make Python 3.12 the default for the whole system', 'Tornam o Python 3.12 o padrão do sistema inteiro',
    'They change nothing outside the terminal.', 'Elas não mudam nada fora do terminal.'),
  C('Start a database server at login', 'Iniciam um servidor de banco no login',
    'There is no server in this lab.', 'Não há servidor neste laboratório.')),
# ---- when-it-fails
Q('ex-yz6y03f5', 'when-it-fails', 'easy',
  ('`python3 -m venv .venv` says "ensurepip is not available". What is missing?', '`python3 -m venv .venv` diz "ensurepip is not available". O que está faltando?'),
  ('The message names it.', 'A mensagem diz o nome.'),
  C('The `python3-venv` package', 'O pacote `python3-venv`',
    'Right: Ubuntu packages it separately.', 'Isso: o Ubuntu o empacota à parte.', ok=True),
  C('An internet connection', 'Uma conexão com a internet',
    'Making an environment needs none.', 'Criar um ambiente não precisa de nenhuma.'),
  C('The pyarrow library', 'A biblioteca pyarrow',
    'pyarrow comes after the environment exists.', 'O pyarrow vem depois de o ambiente existir.'),
  C('Administrator rights on `~/roda`', 'Direitos de administrador sobre `~/roda`',
    'The directory is yours; the package is what is missing.', 'O diretório é seu; o que falta é o pacote.')),
Q('ex-gvbq53ag', 'when-it-fails', 'medium',
  ('A new terminal answers `import pyarrow` with `ModuleNotFoundError`, an hour after it worked. What is the likeliest cause?',
   'Um terminal novo responde `import pyarrow` com `ModuleNotFoundError`, uma hora depois de ter funcionado. Qual a causa mais provável?'),
  ('Which `python3` answered?', 'Qual `python3` respondeu?'),
  C('pyarrow uninstalled itself', 'O pyarrow se desinstalou sozinho',
    'Packages do not leave on their own.', 'Pacotes não saem sozinhos.'),
  C('The environment is not active', 'O ambiente não está ativo',
    'Right: the system’s Python has never heard of pyarrow.', 'Isso: o Python do sistema nunca ouviu falar do pyarrow.', ok=True),
  C('The disk filled up while the terminal was open', 'O disco encheu enquanto o terminal estava aberto',
    'A full disk fails when writing, not on import.', 'Disco cheio falha ao escrever, não no import.'),
  C('The version pin was wrong', 'A versão fixada estava errada',
    'It installed and worked an hour ago.', 'Ele instalou e funcionou há uma hora.')),
Q('ex-xcp8e3za', 'when-it-fails', 'hard',
  ('On Ubuntu 22.04, `pip install pyarrow==26.0.0` answers "No matching distribution found". What does that tell you?',
   'No Ubuntu 22.04, `pip install pyarrow==26.0.0` responde "No matching distribution found". O que isso diz a você?'),
  ('What is Ubuntu 22.04’s own Python?', 'Qual é o Python do próprio Ubuntu 22.04?'),
  C('The version was mistyped', 'A versão foi digitada errada',
    '26.0.0 exists; the transcript lists it.', 'A 26.0.0 existe; a transcrição a lista.'),
  C('pip needs upgrading', 'O pip precisa de atualização',
    'An old pip is not the reason here.', 'Um pip antigo não é a razão aqui.'),
  C('PyPI is down', 'O PyPI está fora do ar',
    'Then it could not list any versions at all.', 'Aí ele não conseguiria listar versão nenhuma.'),
  C('The Python is 3.10, older than pyarrow 26 needs', 'O Python é o 3.10, mais velho do que o pyarrow 26 precisa',
    'Right: it needs 3.11 or newer.', 'Isso: ele precisa do 3.11 ou mais novo.', ok=True)),
Q('ex-d6kqq06z', 'when-it-fails', 'easy',
  ('An error you do not recognise fills the screen. Where do you start reading?', 'Um erro que você não reconhece enche a tela. Por onde você começa a ler?'),
  ('The rest are its consequences.', 'O resto são as consequências.'),
  C('At the first error it printed', 'No primeiro erro que ele imprimiu',
    'Right: later lines are usually consequences.', 'Isso: as linhas seguintes costumam ser consequências.', ok=True),
  C('At the line with the most words', 'Na linha com mais palavras',
    'Length says nothing about cause.', 'O tamanho não diz nada sobre a causa.'),
  C('At the middle of the output', 'No meio da saída',
    'The middle is not special.', 'O meio não tem nada de especial.'),
  C('Nowhere: reinstall the operating system', 'Em lugar nenhum: reinstale o sistema operacional',
    'Rebuilding the lab costs a minute; the system is not involved.', 'Remontar o laboratório custa um minuto; o sistema não entra nisso.')),
# ---- a-first-look
N('ex-03609yzx', 'a-first-look', 'easy',
  ('How many of the six rides in `first.py` started at ST02?', 'Quantas das seis viagens do `first.py` saíram da ST02?'),
  ('Look at the `start_station` column.', 'Olhe a coluna `start_station`.'),
  3, 0, ('rides', 'viagens')),
Q('ex-2gyaks4c', 'a-first-look', 'medium',
  ('Why is the `KeyError` from `renamed.py` called the good kind of failure?', 'Por que o `KeyError` do `renamed.py` é chamado de tipo bom de falha?'),
  ('Compare it with `twice.py`.', 'Compare com o `twice.py`.'),
  C('Nobody gets a wrong number', 'Ninguém recebe número errado',
    'Right.', 'Isso.', ok=True),
  C('It fixes the column name by itself and carries on', 'Corrige o nome da coluna sozinho e segue em frente',
    'It fixes nothing; it stops.', 'Ele não corrige nada; para.'),
  C('It is rarer in practice than a quiet failure', 'Na prática é mais rara que uma falha silenciosa',
    'Rarity is not what makes it good.', 'Raridade não é o que a torna boa.'),
  C('It produces a smaller output', 'Produz uma saída menor',
    'Size is not the point.', 'O tamanho não é a questão.')),
Q('ex-jjyyn5hy', 'a-first-look', 'medium',
  ('`twice.py` printed 7 rides. What makes that failure dangerous?', '`twice.py` mostrou 7 viagens. O que torna essa falha perigosa?'),
  ('Did anything complain?', 'Alguma coisa reclamou?'),
  C('The program crashed halfway', 'O programa quebrou no meio',
    'It ran to the end without a word.', 'Ele rodou até o fim sem uma palavra.'),
  C('The output looks exactly as trustworthy as a correct one', 'A saída parece tão confiável quanto uma correta',
    'Right: nobody downstream can see it.', 'Isso: ninguém adiante consegue vê-la.', ok=True),
  C('Python refuses duplicates', 'O Python recusa duplicatas',
    'Python accepted it happily.', 'O Python aceitou numa boa.'),
  C('It changed the station names', 'Mudou os nomes das estações',
    'It changed a count, not a name.', 'Mudou uma contagem, não um nome.')),
Q('ex-qqr0abvc', 'a-first-look', 'hard',
  ('Which of these is a check that would have caught `twice.py` before anyone read its output?',
   'Qual destas é uma verificação que teria pegado o `twice.py` antes de alguém ler a saída?'),
  ('What is true of `ride_id` in a correct export?', 'O que vale para `ride_id` numa exportação correta?'),
  C('Checking the file is not empty', 'Conferir que o arquivo não está vazio',
    'It was not empty; it had one row too many.', 'Ele não estava vazio; tinha uma linha a mais.'),
  C('Checking the column names', 'Conferir os nomes das colunas',
    'The names were right this time.', 'Os nomes estavam certos dessa vez.'),
  C('Checking that every `ride_id` appears once', 'Conferir que cada `ride_id` aparece uma vez',
    'Right: R000002 appears twice.', 'Isso: R000002 aparece duas vezes.', ok=True),
  C('Checking that every station is ST01 to ST12', 'Conferir que toda estação é de ST01 a ST12',
    'ST05 is a valid station; the row is valid, just repeated.', 'ST05 é uma estação válida; a linha é válida, só repetida.')),
# ---- drill
Q('ex-x4h8hsjw', 'drill', 'medium',
  ('Marta’s chart doubled every number for one day, and nobody noticed for a week. Which part of the work failed?',
   'O gráfico de Marta dobrou todos os números de um dia, e ninguém percebeu por uma semana. Que parte do trabalho falhou?'),
  ('Loud or quiet?', 'Barulhenta ou silenciosa?'),
  C('The analyst’s definition of a ride', 'A definição de viagem do analista',
    'The definition was the same on every other day.', 'A definição foi a mesma em todos os outros dias.'),
  C('The data scientist’s model', 'O modelo do cientista de dados',
    'No model draws Marta’s chart.', 'Nenhum modelo desenha o gráfico de Marta.'),
  C('The guard against loading twice', 'A proteção contra carga dupla',
    'Right: a quiet failure in the bottom of the pyramid.', 'Isso: uma falha silenciosa na base da pirâmide.', ok=True),
  C('The dashboard software, which drew the chart', 'O software do painel, que desenhou o gráfico',
    'It drew exactly what it was given.', 'Ele desenhou exatamente o que recebeu.')),
Q('ex-vf592y44', 'drill', 'hard',
  ('Caio wants demand per station per hour for two years. The sensor server keeps two days. What has to exist first?',
   'Caio quer a demanda por estação e por hora de dois anos. O servidor dos sensores guarda dois dias. O que precisa existir antes?'),
  ('The pyramid’s second level.', 'O segundo nível da pirâmide.'),
  C('A better prediction model', 'Um modelo de previsão melhor',
    'There is nothing to train it on yet.', 'Ainda não há nada em que treiná-lo.'),
  C('A dashboard of today’s readings', 'Um painel das leituras de hoje',
    'Today is not two years.', 'Hoje não é dois anos.'),
  C('A larger sensor server', 'Um servidor de sensores maior',
    'That keeps more, but only from now; it is not a copy kept elsewhere.', 'Isso guarda mais, mas só a partir de agora; não é uma cópia guardada fora.'),
  C('A daily copy of the readings kept somewhere for longer', 'Uma cópia diária das leituras guardada em outro lugar por mais tempo',
    'Right: history only exists if somebody started keeping it.', 'Isso: história só existe se alguém começou a guardá-la.', ok=True)),
]
