from ex import C, Q, MC, N, Z, O, M

QUESTIONS = [
# ---- rows-and-columns
Q('ex-bchakmm1', 'rows-and-columns', 'easy',
  ('What mostly separates one file format from another, as far as speed goes?',
   'O que mais separa um formato de arquivo de outro, quando o assunto é velocidade?'),
  ('Think of the disk, not the syntax.', 'Pense no disco, não na sintaxe.'),
  C('The punctuation it uses to separate values, commas or braces', 'A pontuação que usa para separar valores, vírgulas ou chaves',
    'Spelling is the visible difference and the least important one.', 'A grafia é a diferença visível e a menos importante.'),
  C('Which values sit next to each other on the disk, and so what a reader must pass over', 'Quais valores ficam lado a lado no disco, e portanto o que um leitor precisa atravessar',
    'Right: the layout decides what a reader has to pass over.', 'Isso: o arranjo decide o que um leitor precisa atravessar.', ok=True),
  C('The file extension, which tells the operating system how to open it', 'A extensão do arquivo, que diz ao sistema operacional como abri-lo',
    'An extension is a label; renaming a file changes nothing inside it.', 'A extensão é um rótulo; renomear um arquivo não muda nada dentro dele.'),
  C('Whether the format was published as an open standard', 'Se o formato foi publicado como padrão aberto',
    'All five here are open; that says nothing about layout.', 'Os cinco daqui são abertos; isso não diz nada do arranjo.')),
Q('ex-mh7cx4c8', 'rows-and-columns', 'medium',
  ('The app writes one ride the moment a bicycle is docked. Which layout makes that write cheap?',
   'O aplicativo grava uma viagem no momento em que a bicicleta volta à doca. Que arranjo deixa essa gravação barata?'),
  ('Where does the new ride go in each layout?', 'Para onde vai a viagem nova em cada arranjo?'),
  C('Column-oriented, because each value lands in the run for its own column', 'Orientado a colunas, porque cada valor cai na sequência da sua coluna',
    'That is seven places to write for one ride.', 'Isso são sete lugares para gravar uma viagem.'),
  C('Either, because a write costs the same in any layout', 'Qualquer um, porque uma gravação custa o mesmo em qualquer arranjo',
    'The table in the section shows the two differ exactly here.', 'A tabela da seção mostra que os dois diferem exatamente aqui.'),
  C('Row-oriented, where the whole ride is one write at the end', 'Orientado a linhas, em que a viagem toda é uma gravação no fim',
    'Right: one write at the end of the file.', 'Isso: uma gravação no fim do arquivo.', ok=True),
  C('Column-oriented, once the values are compressed', 'Orientado a colunas, depois de comprimir os valores',
    'Compression makes the file smaller, not the single append cheaper.', 'A compressão deixa o arquivo menor, não deixa o acréscimo avulso mais barato.')),
Q('ex-a6gf8zv4', 'rows-and-columns', 'medium',
  ('Why does a column of `start_station` values compress so well in a columnar file?',
   'Por que uma coluna de valores `start_station` comprime tão bem num arquivo colunar?'),
  ('Look at the second half of the run of `rides.py`.', 'Olhe a segunda metade da execução de `rides.py`.'),
  C('Station codes are short strings', 'Códigos de estação são textos curtos',
    'Short helps a little; repetition is what helps a lot.', 'Ser curto ajuda um pouco; a repetição é o que ajuda muito.'),
  C('Its neighbours repeat twelve values', 'Os vizinhos repetem doze valores',
    'Right: alike values side by side are what a compressor feeds on.', 'Isso: valores parecidos lado a lado são o alimento do compressor.', ok=True),
  C('Columnar files sort every column alphabetically', 'Arquivos colunares ordenam toda coluna alfabeticamente',
    'Nothing is sorted; the rows keep the order they were written in.', 'Nada é ordenado; as linhas mantêm a ordem em que foram gravadas.'),
  C('The column is stored apart from the timestamps', 'A coluna é guardada separada dos instantes',
    'Being apart matters only because what is left together is alike.', 'Estar separada só importa porque o que fica junto é parecido.')),
M('ex-3sjc0c4r', 'rows-and-columns', 'easy',
  ('Match each format to its layout.', 'Associe cada formato ao seu arranjo.'),
  ('Two of the five store columns.', 'Dois dos cinco guardam colunas.'),
  [(('CSV', 'CSV'), ('rows, as text with one header', 'linhas, em texto com um cabeçalho')),
   (('JSON Lines', 'JSON Lines'), ('rows, as text with names on each', 'linhas, em texto com nomes em cada uma')),
   (('Avro', 'Avro'), ('rows, as binary in blocks', 'linhas, em binário, em blocos')),
   (('Parquet', 'Parquet'), ('columns, in row groups', 'colunas, em grupos de linhas')),
   (('ORC', 'ORC'), ('columns, in stripes', 'colunas, em faixas'))]),
# ---- csv
N('ex-515h7mk0', 'csv', 'easy',
  ('In the run of `comma.py`, how many fields did splitting on commas find in the line of ride R000101?',
   'Na execução de `comma.py`, quantos campos a quebra nas vírgulas encontrou na linha da viagem R000101?'),
  ('Its note has a comma inside.', 'A observação dela tem uma vírgula dentro.'),
  5, 0, ('fields', 'campos')),
Q('ex-7984g9z2', 'csv', 'easy',
  ('How does RFC 4180 write a field that contains a comma?', 'Como a RFC 4180 escreve um campo que contém uma vírgula?'),
  ('Look at `notes.csv`.', 'Olhe o `notes.csv`.'),
  C('It escapes the comma with a backslash before it', 'Escapa a vírgula com uma barra invertida antes dela',
    'That is a habit from other formats; RFC 4180 has no backslash rule.', 'Esse é um hábito de outros formatos; a RFC 4180 não tem regra de barra invertida.'),
  C('It replaces the comma with a semicolon in that field', 'Troca a vírgula por ponto e vírgula naquele campo',
    'That would change the data; the comma survives as it is.', 'Isso mudaria o dado; a vírgula sobrevive como está.'),
  C('It wraps the whole field in a pair of double quotes', 'Põe o campo inteiro entre um par de aspas duplas',
    'Right, and a quote inside such a field is written twice.', 'Isso, e uma aspa dentro desse campo é escrita duas vezes.', ok=True),
  C('It is not allowed; such a field must be cleaned first', 'Não é permitido; um campo assim precisa ser limpo antes',
    'It is allowed, and the `csv` module wrote one.', 'É permitido, e o módulo `csv` gravou um.')),
Q('ex-qwpsnbk8', 'csv', 'medium',
  ('A program reads `minutes` from a CSV and adds 5 to it, and Python raises `TypeError`. Why?',
   'Um programa lê `minutes` de um CSV e soma 5, e o Python levanta `TypeError`. Por quê?'),
  ('What did `repr(rows[1][2])` print?', 'O que `repr(rows[1][2])` imprimiu?'),
  C('The value came back as the string `\'12\'`, and adding an int to a string raises it', 'O valor voltou como o texto `\'12\'`, e somar um inteiro a um texto levanta esse erro',
    'Right: CSV carries text, and the reader has to convert it.', 'Isso: o CSV carrega texto, e quem lê precisa convertê-lo.', ok=True),
  C('The `csv` module stores numbers as floats, which cannot be added to integers', 'O módulo `csv` guarda números como float, que não se somam a inteiros',
    'A float and an int add perfectly well; and nothing was a float.', 'Float e int se somam perfeitamente; e nada ali era float.'),
  C('The file was written with the wrong encoding', 'O arquivo foi gravado com a codificação errada',
    'An encoding problem garbles letters; it does not change a type.', 'Problema de codificação embaralha letras; não muda tipo.'),
  C('The column was quoted, which marks it as text', 'A coluna estava entre aspas, o que a marca como texto',
    '`12` was not quoted, and quotes in CSV are about commas, not types.', '`12` não estava entre aspas, e aspas no CSV tratam de vírgulas, não de tipos.')),
Q('ex-1ka2bf1c', 'csv', 'medium',
  ('A reader opens a UTF-8 export as Latin-1. What happens to "Praça Tiradentes"?',
   'Um leitor abre como Latin-1 uma exportação em UTF-8. O que acontece com "Praça Tiradentes"?'),
  ('The run showed it.', 'A execução mostrou.'),
  C('Python raises a `UnicodeDecodeError` and stops', 'O Python levanta `UnicodeDecodeError` e para',
    'Latin-1 can decode any byte, so nothing stops: that is the danger.', 'O Latin-1 decodifica qualquer byte, então nada para: esse é o perigo.'),
  C('The `ç` is dropped and the rest reads fine', 'O `ç` some e o resto fica certo',
    'Nothing is dropped; one character becomes two.', 'Nada some; um caractere vira dois.'),
  C('It becomes `PraÃ§a`, with no error', 'Vira `PraÃ§a`, e nenhum erro aparece',
    'Right: two bytes read as two characters, silently.', 'Isso: dois bytes lidos como dois caracteres, em silêncio.', ok=True),
  C('The line is split in two at the cedilla', 'A linha é quebrada em duas na cedilha',
    'The cedilla is not a line break in either encoding.', 'A cedilha não é quebra de linha em nenhuma das codificações.')),
# ---- json
Q('ex-43sta9nv', 'json', 'easy',
  ('Which of these has no type of its own in JSON?', 'Qual destes não tem tipo próprio no JSON?'),
  ('Count the six.', 'Conte os seis.'),
  C('A missing value, written as `null`', 'Um valor ausente, escrito como `null`',
    '`null` is one of the six.', '`null` é um dos seis.'),
  C('A date, which has to be spelt as a string or a number', 'Uma data, que precisa ser escrita como texto ou como número',
    'Right: it has to be spelt as a string or a number.', 'Isso: ela precisa ser escrita como texto ou número.', ok=True),
  C('A list of values, written between brackets', 'Uma lista de valores, escrita entre colchetes',
    'An array is one of the six.', 'A lista é um dos seis.'),
  C('A true-or-false value', 'Um valor verdadeiro ou falso',
    '`true` and `false` are one of the six.', '`true` e `false` são um dos seis.')),
N('ex-fsmkhtas', 'json', 'easy',
  ('Of the 162 bytes of the ride printed by `as_json.py`, how many were field names in quotes?',
   'Dos 162 bytes da viagem impressa por `as_json.py`, quantos eram nomes de campos entre aspas?'),
  ('The last line of the run.', 'A última linha da execução.'),
  75, 0, ('bytes', 'bytes')),
Q('ex-3pq6vfdy', 'json', 'medium',
  ('A nightly job writes a file of 2 million events. Why would you choose JSON Lines over one JSON array?',
   'Um job noturno grava um arquivo de 2 milhões de eventos. Por que escolher JSON Lines em vez de uma lista JSON?'),
  ('Think about a reader, and about a file cut off halfway.', 'Pense em quem lê, e num arquivo cortado no meio.'),
  C('JSON Lines carries more types than an array of the same objects', 'JSON Lines carrega mais tipos que uma lista dos mesmos objetos',
    'Both use the same six types.', 'Os dois usam os mesmos seis tipos.'),
  C('A JSON array cannot hold more than a million elements', 'Uma lista JSON não comporta mais de um milhão de elementos',
    'There is no such limit in JSON.', 'Não existe esse limite no JSON.'),
  C('JSON Lines drops the field names, so the file is smaller', 'JSON Lines tira os nomes dos campos, então o arquivo fica menor',
    'Every line still carries every name.', 'Cada linha continua carregando todos os nomes.'),
  C('It is read one line at a time, and splits at any line break', 'É lido uma linha por vez e se divide em qualquer quebra de linha',
    'Right, and a damaged line costs one record, not the file.', 'Isso, e uma linha estragada custa um registro, não o arquivo.', ok=True)),
Z('ex-cjc2t5ye', 'json', 'easy',
  ('In JSON Lines, every record sits on its own ___.', 'No JSON Lines, cada registro fica na sua própria ___.'),
  ('The name says it.', 'O nome diz.'),
  ['line'], ['linha']),
# ---- parquet
O('ex-fy7qj243', 'parquet', 'medium',
  ('Put in order what a Parquet reader does to average `minutes` for rides after 25 September.',
   'Ponha em ordem o que um leitor de Parquet faz para tirar a média de `minutes` das viagens depois de 25 de setembro.'),
  ('It starts at the end of the file.', 'Ele começa pelo fim do arquivo.'),
  [('read the last bytes to learn the footer’s length', 'ler os últimos bytes para saber o tamanho do rodapé'),
   ('read the footer', 'ler o rodapé'),
   ('rule out row groups whose statistics end too early', 'descartar os grupos cujas estatísticas terminam cedo demais'),
   ('read the needed column chunks of the groups left', 'ler os pedaços de coluna necessários dos grupos que sobraram')],
  ('Nothing about the rows is known before the footer has been read.', 'Nada sobre as linhas é conhecido antes de o rodapé ser lido.')),
N('ex-ygn6x665', 'parquet', 'easy',
  ('Into how many row groups did `as_parquet.py` cut the 50,000 rides?', 'Em quantos grupos de linhas `as_parquet.py` cortou as 50.000 viagens?'),
  ('Groups of 20,000.', 'Grupos de 20.000.'),
  3, 0, ('row groups', 'grupos')),
Q('ex-e8c71d1j', 'parquet', 'medium',
  ('How did `as_parquet.py` know the first and last time in each row group without reading any ride?',
   'Como `as_parquet.py` soube o primeiro e o último horário de cada grupo sem ler nenhuma viagem?'),
  ('`metadata` is one part of the file.', '`metadata` é uma parte do arquivo.'),
  C('From the min and max of `started_at` that the footer keeps for each row group', 'Pelo mínimo e pelo máximo de `started_at` que o rodapé guarda para cada grupo',
    'Right: statistics per column chunk, kept in the footer.', 'Isso: estatísticas por pedaço de coluna, guardadas no rodapé.', ok=True),
  C('It worked them out from the row-group size and the seed in `rides.py`', 'Calculou pelo tamanho do grupo e pela semente de `rides.py`',
    'It never looked at `rides.py`; it read the file it wrote.', 'Ele nem olhou `rides.py`; leu o arquivo que gravou.'),
  C('Parquet sorts each group, so the first and last rows give the answer', 'O Parquet ordena cada grupo, então a primeira e a última linha dão a resposta',
    'Parquet sorts nothing, and reading those rows would be reading rides.', 'O Parquet não ordena nada, e ler essas linhas seria ler viagens.'),
  C('pyarrow scans the `started_at` pages, which are small', 'O pyarrow varre as páginas de `started_at`, que são pequenas',
    'Scanning pages is reading rides; it read the footer only.', 'Varrer páginas é ler viagens; ele só leu o rodapé.')),
Q('ex-q1wnm9d6', 'parquet', 'hard',
  ('Davi writes the month of rides to Parquet sorted by `bike_id` instead of by time. What happens to a question about rides after 25 September?',
   'Davi grava o mês de viagens em Parquet ordenado por `bike_id` em vez de por horário. O que acontece com uma pergunta sobre viagens depois de 25 de setembro?'),
  ('What would each group’s min and max of `started_at` be?', 'Qual seria o mínimo e o máximo de `started_at` em cada grupo?'),
  C('It fails, because the statistics no longer match the data', 'Ela falha, porque as estatísticas deixam de bater com os dados',
    'The statistics are still true; they just stop being useful.', 'As estatísticas continuam verdadeiras; só deixam de ser úteis.'),
  C('Nothing changes, because pyarrow re-sorts by time when it writes', 'Nada muda, porque o pyarrow reordena por horário ao gravar',
    'The writer keeps the order it is given.', 'O gravador mantém a ordem que recebe.'),
  C('Hardly any row group is skipped, because each spans the month', 'Quase nenhum grupo é pulado, porque cada um cobre o mês todo',
    'Right: each group spans the whole month, so none can be ruled out by date.', 'Isso: cada grupo cobre o mês inteiro, então nenhum pode ser descartado pela data.', ok=True),
  C('It is answered from the footer without reading any column', 'Ela é respondida pelo rodapé sem ler coluna nenhuma',
    'The footer rules groups out; it does not hold the minutes to average.', 'O rodapé descarta grupos; ele não guarda os minutos para a média.')),
Q('ex-ggh41enb', 'parquet', 'medium',
  ('`start_station` took 10,170 bytes encoded and compressed, and 160,049 with neither. What did most of the work?',
   '`start_station` ocupou 10.170 bytes codificado e comprimido, e 160.049 sem nenhum dos dois. O que fez a maior parte do trabalho?'),
  ('Twelve values, 20,000 rows.', 'Doze valores, 20.000 linhas.'),
  C('Snappy compression, which shrinks any text by about this much', 'A compressão Snappy, que encolhe qualquer texto mais ou menos nessa proporção',
    'The dictionary had already shrunk it; Snappy found little left.', 'O dicionário já tinha encolhido; o Snappy achou pouco a fazer.'),
  C('The dictionary: twelve codes stored once, a small number per row', 'O dicionário: doze códigos guardados uma vez, e um número pequeno por linha',
    'Right: Snappy then had little left to do.', 'Isso: depois disso o Snappy teve pouco a fazer.', ok=True),
  C('The footer statistics, which replace repeated values with a min and a max', 'As estatísticas do rodapé, que trocam valores repetidos por um mínimo e um máximo',
    'Statistics describe a chunk; they do not replace its values.', 'Estatísticas descrevem um pedaço; não substituem os valores dele.'),
  C('Removing the four-byte lengths in front of each code', 'Tirar os quatro bytes de tamanho na frente de cada código',
    'That alone would halve it, not divide it by fifteen.', 'Só isso cortaria pela metade, não dividiria por quinze.')),
Z('ex-bztk5wh3', 'parquet', 'medium',
  ('Skipping row groups by reading their statistics is called predicate ___.', 'Pular grupos de linhas lendo as suas estatísticas se chama predicate ___.'),
  ('The filter is pushed down to the file.', 'O filtro é empurrado para baixo, até o arquivo.'),
  ['pushdown', 'push-down', 'push down'], ['pushdown', 'push-down', 'push down']),
# ---- avro
Q('ex-g3cd625p', 'avro', 'easy',
  ('Where does an Avro file keep the names of its fields?', 'Onde um arquivo Avro guarda os nomes dos seus campos?'),
  ('Look at the first hundred bytes.', 'Olhe os primeiros cem bytes.'),
  C('Before each value, as in JSON', 'Antes de cada valor, como no JSON',
    'Avro records carry no names; that is why they are small.', 'Registros Avro não carregam nomes; é por isso que são pequenos.'),
  C('In a separate `.avsc` file that has to travel with it', 'Num arquivo `.avsc` separado que precisa ir junto',
    'A schema can be kept in such a file, but the container carries its own.', 'Um esquema pode ficar num arquivo assim, mas o contêiner carrega o seu.'),
  C('In the footer, after the last block', 'No rodapé, depois do último bloco',
    'That is Parquet’s and ORC’s place; Avro’s is the other end.', 'Esse é o lugar do Parquet e do ORC; o do Avro é a outra ponta.'),
  C('In the header, as JSON', 'No cabeçalho, uma vez, dentro do esquema em JSON',
    'Right: the schema as JSON, under `avro.schema`.', 'Isso: o esquema em JSON, sob `avro.schema`.', ok=True)),
Q('ex-vdfe2qgb', 'avro', 'medium',
  ('A ride written at 06:01:23 in Curitiba came back from the Avro file as 09:01:23+00:00. What does that mean?',
   'Uma viagem gravada às 06:01:23 em Curitiba voltou do arquivo Avro como 09:01:23+00:00. O que isso quer dizer?'),
  ('`timestamp-millis` holds one number.', '`timestamp-millis` guarda um número.'),
  C('The same instant, printed in UTC, because the value holds no time zone of its own', 'O mesmo instante, impresso em UTC, porque o valor não guarda fuso horário próprio',
    'Right: milliseconds since 1970 in UTC, and nothing else.', 'Isso: milissegundos desde 1970 em UTC, e nada mais.', ok=True),
  C('fastavro added three hours by mistake, which is a bug in the library', 'O fastavro somou três horas por engano, um defeito da biblioteca',
    '06:01 at UTC−3 and 09:01 at UTC are the same moment.', '06:01 em UTC−3 e 09:01 em UTC são o mesmo momento.'),
  C('The ride is now recorded as starting three hours later', 'A viagem agora consta como iniciada três horas depois',
    'The instant did not move; only how it is printed did.', 'O instante não se moveu; só o jeito de imprimir.'),
  C('Avro cannot store times, so it stored the text of the time in UTC', 'O Avro não guarda horários, então guardou o texto do horário em UTC',
    'It stored a number, through a logical type.', 'Ele guardou um número, por meio de um tipo lógico.')),
Q('ex-n5sjmdr7', 'avro', 'medium',
  ('Why does every Avro block end with the same sync marker?', 'Por que todo bloco Avro termina com o mesmo marcador de sincronia?'),
  ('Imagine starting to read in the middle of a large file.', 'Imagine começar a ler no meio de um arquivo grande.'),
  C('To check that no block was written twice', 'Para conferir que nenhum bloco foi gravado duas vezes',
    'A repeated block would carry the same marker too.', 'Um bloco repetido também levaria o mesmo marcador.'),
  C('So a reader finds where a block starts', 'Para quem lê achar onde um bloco começa',
    'Right: which is what makes the file splittable.', 'Isso: é o que torna o arquivo divisível.', ok=True),
  C('To separate the field values inside each record', 'Para separar os valores dos campos dentro de cada registro',
    'Records have no separators; the schema says where each value ends.', 'Registros não têm separadores; o esquema diz onde termina cada valor.'),
  C('To mark where the compression codec changes in the file', 'Para marcar onde o codec de compressão muda no arquivo',
    'One codec is named in the header for the whole file.', 'Um codec é nomeado no cabeçalho para o arquivo todo.')),
MC('ex-471f9m8n', 'avro', 'medium',
  ('Which of these make Avro a good fit for messages on a stream? Choose all that apply.',
   'Quais destas fazem do Avro uma boa escolha para mensagens num fluxo? Marque todas as que se aplicam.'),
  ('Think of one event, sent alone.', 'Pense num evento, enviado sozinho.'),
  C('A record is small, with no names in it', 'Um registro é pequeno, sem nomes',
    'Yes: a few dozen bytes for a ride.', 'Sim: algumas dezenas de bytes por viagem.', ok=True),
  C('It is row-oriented, so one record is written whole', 'É orientado a linhas, então um registro é gravado inteiro',
    'Yes: one event, one write.', 'Sim: um evento, uma gravação.', ok=True),
  C('Old data can be read with a new schema, by rules', 'Dados antigos podem ser lidos com um esquema novo, por regras',
    'Yes: readers and writers change at different times.', 'Sim: leitores e gravadores mudam em momentos diferentes.', ok=True),
  C('A reader can fetch one column without the others', 'Quem lê consegue buscar uma coluna sem as outras',
    'No: that is the columnar formats’ strength, not Avro’s.', 'Não: essa é a força dos formatos colunares, não do Avro.')),
# ---- orc
M('ex-69a757gp', 'orc', 'medium',
  ('Match each ORC term to its nearest Parquet counterpart.', 'Associe cada termo do ORC ao equivalente mais próximo no Parquet.'),
  ('The section’s table.', 'A tabela da seção.'),
  [(('stripe', 'stripe (faixa)'), ('row group', 'grupo de linhas')),
   (('row index', 'row index (índice de linhas)'), ('page statistics', 'estatísticas por página')),
   (('file footer', 'file footer (rodapé)'), ('footer', 'rodapé')),
   (('postscript', 'postscript'), ('the footer length and PAR1', 'o tamanho do rodapé e PAR1'))]),
Q('ex-v6gpqe73', 'orc', 'medium',
  ('`as_orc.py` asked for stripes of 64 KiB and got 33,792 rows and 16,208 rows. Why are they not round numbers?',
   '`as_orc.py` pediu faixas de 64 KiB e recebeu 33.792 e 16.208 linhas. Por que não são números redondos?'),
  ('What was the limit expressed in?', 'Em que unidade o limite foi dado?'),
  C('A stripe is cut when it reaches a size, not a row count', 'Uma faixa é cortada ao chegar a um tamanho, não a uma contagem',
    'Right: the writer closes a stripe when its estimate reaches the limit.', 'Isso: o gravador fecha a faixa quando a estimativa chega ao limite.', ok=True),
  C('ORC drops rows that do not fit evenly into a stripe', 'O ORC descarta linhas que não cabem certinho numa faixa',
    'Both stripes add up to 50,000; nothing was dropped.', 'As duas faixas somam 50.000; nada foi descartado.'),
  C('zstd compression removed the duplicated rides first', 'A compressão zstd tirou antes as viagens repetidas',
    'There were no duplicates, and compression removes no rows.', 'Não havia repetidas, e compressão não tira linhas.'),
  C('The row index needs a multiple of 10,000 and rounds the rest', 'O índice de linhas precisa de múltiplos de 10.000 e arredonda o resto',
    'Neither number is a multiple of 10,000, and nothing was rounded.', 'Nenhum dos dois é múltiplo de 10.000, e nada foi arredondado.')),
Q('ex-6yxnpvb6', 'orc', 'hard',
  ('A team runs a large Hive installation whose tables take updates and deletes. Which format do those tables need?',
   'Um time roda uma instalação grande de Hive cujas tabelas recebem atualizações e exclusões. Que formato essas tabelas precisam?'),
  ('Hive’s transactional tables.', 'As tabelas transacionais do Hive.'),
  C('Parquet, because it is the default of most new platforms', 'Parquet, porque é o padrão da maioria das plataformas novas',
    'Most new platforms are not this one; Hive’s transactional tables say otherwise.', 'A maioria das plataformas novas não é esta; as tabelas transacionais do Hive dizem outra coisa.'),
  C('Avro, because a format for updates has to be row-oriented', 'Avro, porque atualizar exige um formato orientado a linhas',
    'Hive’s transactional tables are columnar; layout is not the deciding fact here.', 'As tabelas transacionais do Hive são colunares; o arranjo não é o fato decisivo aqui.'),
  C('ORC, because Hive’s transactional mode accepts nothing else', 'ORC, porque o modo transacional do Hive só aceita esse',
    'Right: Hive’s transactional tables require it.', 'Isso: as tabelas transacionais do Hive o exigem.', ok=True),
  C('Any of the three binary formats, chosen per table', 'Qualquer um dos três formatos binários, escolhido por tabela',
    'Transactional tables in Hive accept one format.', 'Tabelas transacionais no Hive aceitam um formato.')),
# ---- the-same-data-five-ways
O('ex-jj8qcqez', 'the-same-data-five-ways', 'easy',
  ('Order the five files `five.py` wrote from the largest to the smallest.', 'Ordene os cinco arquivos que `five.py` gravou do maior para o menor.'),
  ('Names on every record cost the most.', 'Nomes em todo registro custam mais.'),
  [('rides.jsonl', 'rides.jsonl'), ('rides.csv', 'rides.csv'), ('rides.avro', 'rides.avro'),
   ('rides.parquet', 'rides.parquet'), ('rides.orc', 'rides.orc')],
  ('ORC and Parquet were close; on other data they can swap.', 'ORC e Parquet ficaram perto; em outros dados podem trocar de lugar.')),
N('ex-3wyvz4hp', 'the-same-data-five-ways', 'medium',
  ('How many bytes did the Parquet reader go through for the `minutes` column in `one_column.py`?',
   'Quantos bytes o leitor de Parquet atravessou para a coluna `minutes` em `one_column.py`?'),
  ('The first line of the run.', 'A primeira linha da execução.'),
  38312, 0, ('bytes', 'bytes')),
Q('ex-jxw7w6d3', 'the-same-data-five-ways', 'medium',
  ('Why did `five.py` pass `compression="none"` to the Parquet writer only?',
   'Por que `five.py` passou `compression="none"` só ao gravador de Parquet?'),
  ('What do the other writers do by default?', 'O que os outros gravadores fazem por padrão?'),
  C('Parquet cannot be read back by pyarrow when it is compressed', 'O pyarrow não consegue ler Parquet comprimido',
    '`as_parquet.py` read back a Snappy file without trouble.', '`as_parquet.py` leu de volta um arquivo Snappy sem problema.'),
  C('Of the five, only its writer compresses when nobody asks', 'Dos cinco, só o gravador dele comprime sem que se peça',
    'Right: so all five are compared on layout alone.', 'Isso: assim os cinco são comparados só pelo arranjo.', ok=True),
  C('To make Parquet look smaller than ORC in the comparison', 'Para o Parquet parecer menor que o ORC na comparação',
    'It came out larger than ORC; the aim was a fair comparison.', 'Ele saiu maior que o ORC; o objetivo era uma comparação justa.'),
  C('The other four formats have no compression to switch off', 'Os outros quatro formatos não têm compressão para desligar',
    'Avro and ORC both have codecs; their writers just leave them off.', 'Avro e ORC têm codecs; os gravadores só os deixam desligados.')),
Q('ex-vv91b3x2', 'the-same-data-five-ways', 'medium',
  ('Why does this lesson compare bytes rather than seconds?', 'Por que esta aula compara bytes em vez de segundos?'),
  ('Which of the two would be the same on your machine?', 'Qual dos dois seria igual na sua máquina?'),
  C('Seconds are too small to measure on 50,000 rows', 'Segundos são pequenos demais para medir em 50.000 linhas',
    'They are measurable; they are just not repeatable elsewhere.', 'Dá para medir; só não se repetem em outra máquina.'),
  C('Reading time does not depend on the format', 'O tempo de leitura não depende do formato',
    'It does; bytes read are a large part of it.', 'Depende; os bytes lidos são grande parte dele.'),
  C('Bytes are the same on every machine', 'Bytes são os mesmos em toda máquina',
    'Right, and they are what disks read and bills charge.', 'Isso, e são o que discos leem e contas cobram.', ok=True),
  C('pyarrow does not report how long a read took', 'O pyarrow não informa quanto tempo uma leitura levou',
    'Any program can time itself; the problem is what the number means elsewhere.', 'Qualquer programa mede o próprio tempo; o problema é o que o número quer dizer em outro lugar.')),
# ---- compression
Q('ex-6fajydw0', 'compression', 'medium',
  ('The gzipped CSV, 570,459 bytes, was smaller than every Parquet file. Why is it still the worse choice for analysis?',
   'O CSV com gzip, 570.459 bytes, ficou menor que todos os arquivos Parquet. Por que ainda é a pior escolha para análise?'),
  ('Size is one of four things.', 'Tamanho é uma de quatro coisas.'),
  C('gzip loses data that Parquet’s codecs keep', 'O gzip perde dados que os codecs do Parquet guardam',
    'gzip is lossless; the CSV comes back byte for byte.', 'O gzip não perde nada; o CSV volta byte a byte.'),
  C('It must be read whole, from the start', 'Precisa ser lido inteiro, desde o começo',
    'Right: no columns to skip to, and no place to split it.', 'Isso: nenhuma coluna para onde pular, e nenhum ponto para dividir.', ok=True),
  C('Spreadsheets cannot open a gzipped file', 'Planilhas não abrem arquivo com gzip',
    'Analysis here is done by programs, and that is not the reason.', 'A análise aqui é feita por programas, e esse não é o motivo.'),
  C('A gzipped file is larger again once it is in memory', 'Um arquivo com gzip volta a ficar maior quando está na memória',
    'So is Parquet; every compressed file grows when decompressed.', 'O Parquet também; todo arquivo comprimido cresce ao descomprimir.')),
Q('ex-mxzqkqj1', 'compression', 'medium',
  ('Why can ten workers share one large Parquet file but not one large `.csv.gz`?',
   'Por que dez trabalhadores conseguem dividir um arquivo Parquet grande mas não um `.csv.gz` grande?'),
  ('Where can each one start?', 'Onde cada um pode começar?'),
  C('Parquet files are smaller, so each worker is given less to read', 'Arquivos Parquet são menores, então cada trabalhador recebe menos',
    'Here the gzipped CSV was smaller; size is not what splits.', 'Aqui o CSV com gzip era menor; tamanho não é o que divide.'),
  C('Parquet compresses each page apart, and the footer says where', 'O Parquet comprime cada página à parte, e o rodapé diz onde',
    'Right: a worker can start at any row group.', 'Isso: um trabalhador pode começar em qualquer grupo.', ok=True),
  C('gzip uses a password that only one process at a time can hold', 'O gzip usa uma senha que só um processo pode ter',
    'gzip has no password; the stream has to be read from its start.', 'O gzip não tem senha; o fluxo precisa ser lido do começo.'),
  C('A CSV has no header to tell workers the column names', 'Um CSV não tem cabeçalho para dar aos trabalhadores os nomes das colunas',
    'This one has a header; the problem is the gzip stream.', 'Este tem cabeçalho; o problema é o fluxo gzip.')),
Q('ex-zk2vcn77', 'compression', 'easy',
  ('In `squeeze.py`, which codec shrank the Parquet file least?', 'Em `squeeze.py`, qual codec encolheu menos o arquivo Parquet?'),
  ('It was designed for speed.', 'Ele foi projetado para velocidade.'),
  C('gzip, the oldest of the three', 'gzip, o mais antigo dos três',
    'It took the file to 638,037, about half.', 'Ele levou o arquivo a 638.037, cerca da metade.'),
  C('zstd, which was released by Facebook', 'zstd, que foi lançado pelo Facebook',
    'It was the smallest Parquet, 633,691.', 'Foi o menor Parquet, 633.691.'),
  C('Snappy', 'Snappy',
    'Right: 907,079 bytes, the trade for speed.', 'Isso: 907.079 bytes, a troca pela velocidade.', ok=True),
  C('They all came out within a few bytes', 'Todos saíram com poucos bytes de diferença',
    'Snappy was 270,000 bytes behind the other two.', 'O Snappy ficou 270.000 bytes atrás dos outros dois.')),
MC('ex-0m7t1syy', 'compression', 'hard',
  ('Which of these files can be split between workers without reading them from the start? Choose all that apply.',
   'Quais destes arquivos podem ser divididos entre trabalhadores sem lê-los do começo? Marque todos os que se aplicam.'),
  ('Look for markers, footers or a codec that splits.', 'Procure marcadores, rodapés ou um codec que se divide.'),
  C('An Avro file compressed with a codec', 'Um arquivo Avro comprimido com um codec',
    'Yes: each block is compressed alone and ends with the sync marker.', 'Sim: cada bloco é comprimido sozinho e termina com o marcador.', ok=True),
  C('A Parquet file compressed with zstd', 'Um arquivo Parquet comprimido com zstd',
    'Yes: pages are compressed inside row groups the footer locates.', 'Sim: as páginas são comprimidas dentro de grupos que o rodapé localiza.', ok=True),
  C('A CSV compressed with gzip', 'Um CSV comprimido com gzip',
    'No: one stream, from the first byte.', 'Não: um fluxo só, desde o primeiro byte.'),
  C('A JSON Lines file compressed with gzip', 'Um arquivo JSON Lines comprimido com gzip',
    'No: the lines are splittable, the gzip stream around them is not.', 'Não: as linhas são divisíveis, o fluxo gzip em volta delas não.')),
# ---- schema-evolution
Q('ex-8076yv4a', 'schema-evolution', 'medium',
  ('September’s Avro file has no `kind`. October’s reader schema adds `kind` with the default "classic". What does the reader get?',
   'O arquivo Avro de setembro não tem `kind`. O esquema de leitura de outubro acrescenta `kind` com o padrão "classic". O que o leitor recebe?'),
  ('The first line of the run of `evolve.py`.', 'A primeira linha da execução de `evolve.py`.'),
  C('An error naming the field that is missing from the file', 'Um erro com o nome do campo que falta no arquivo',
    'That is what happens without a default.', 'Isso acontece sem padrão.'),
  C('The old rides, without a `kind` key', 'As viagens antigas, sem a chave `kind`',
    'The reader’s schema has `kind`, so every record gets one.', 'O esquema de leitura tem `kind`, então todo registro ganha um.'),
  C('The old rides, with `kind` set to null', 'As viagens antigas, com `kind` nulo',
    'Avro uses the reader’s default, not null.', 'O Avro usa o padrão de quem lê, não nulo.'),
  C('Each old ride, with `kind` filled in as classic', 'Cada viagem antiga, com `kind` igual a classic',
    'Right: filled from the reader’s default.', 'Isso: preenchido pelo padrão de quem lê.', ok=True)),
N('ex-d71yb9sc', 'schema-evolution', 'easy',
  ('What did `shifted.py` print as October’s average ride length?', 'O que `shifted.py` imprimiu como duração média das viagens de outubro?'),
  ('It was not the minutes.', 'Não eram os minutos.'),
  72.5, 0, ('minutes', 'minutos')),
Q('ex-pgg6r97t', 'schema-evolution', 'hard',
  ('Rewritten with `csv.DictReader` and `row["minutes"]`, which change to October’s export would `shifted.py` still get wrong?',
   'Reescrito com `csv.DictReader` e `row["minutes"]`, que mudança na exportação de outubro o `shifted.py` ainda erraria?'),
  ('Reading by name survives some changes and not others.', 'Ler pelo nome sobrevive a algumas mudanças e não a outras.'),
  C('A new column inserted before `minutes`', 'Uma coluna nova inserida antes de `minutes`',
    'That is exactly the change reading by name survives.', 'É exatamente a mudança a que a leitura por nome sobrevive.'),
  C('`minutes` recorded in seconds under the same name', '`minutes` registrado em segundos com o mesmo nome',
    'Right: the name still matches, so nothing fails and the average is wrong.', 'Isso: o nome continua batendo, então nada falha e a média fica errada.', ok=True),
  C('`minutes` renamed to `duration`', '`minutes` renomeado para `duration`',
    'That fails loudly with a `KeyError`, which is not getting it wrong quietly.', 'Isso falha alto com um `KeyError`, o que não é errar em silêncio.'),
  C('The columns reordered alphabetically', 'As colunas reordenadas alfabeticamente',
    'Order is what reading by name no longer depends on.', 'A ordem é justamente do que a leitura por nome deixa de depender.')),
Q('ex-qfr66vcg', 'schema-evolution', 'medium',
  ('Why does the section call both outcomes of `evolve.py` good ones?', 'Por que a seção chama de bons os dois resultados de `evolve.py`?'),
  ('Compare them with `shifted.py`.', 'Compare com `shifted.py`.'),
  C('Both read every old ride back successfully', 'Os dois leram de volta todas as viagens antigas',
    'The second read nothing back: it refused.', 'O segundo não leu nada: recusou.'),
  C('Neither of the two ends in a wrong number', 'Nenhum dos dois produz um número que esteja errado',
    'Right: one is correct and the other is loud.', 'Isso: um está certo e o outro é barulhento.', ok=True),
  C('Avro errors are caught by the schema registry before anyone sees them', 'Erros de Avro são pegos pelo registro de esquemas antes que alguém os veja',
    'There was no registry in this run; the error reached the program.', 'Não havia registro nesta execução; o erro chegou ao programa.'),
  C('A default value is always correct for old data', 'Um valor padrão está sempre certo para dados antigos',
    '"classic" happened to be true; a default can be wrong.', '"classic" por acaso era verdade; um padrão pode estar errado.')),
# ---- choosing-a-format
Q('ex-vacad3vq', 'choosing-a-format', 'medium',
  ('The city asks Roda Livre for a monthly file it will open in a spreadsheet. Which format?',
   'A prefeitura pede à Roda Livre um arquivo mensal que vai abrir numa planilha. Que formato?'),
  ('The first of the four questions.', 'A primeira das quatro perguntas.'),
  C('Parquet, because it is the smallest and keeps its types', 'Parquet, porque é o menor e guarda os tipos',
    'Its reader is a spreadsheet; who opens it decides first.', 'Quem lê é uma planilha; quem abre decide primeiro.'),
  C('Avro, so that the schema travels with the file', 'Avro, para o esquema viajar com o arquivo',
    'A spreadsheet user cannot open Avro.', 'Quem usa planilha não abre Avro.'),
  C('CSV in UTF-8, with a header and its delimiter and date format written down', 'CSV em UTF-8, com cabeçalho, e o delimitador e o formato de data documentados',
    'Right: who opens it decides first, and a spreadsheet opens CSV.', 'Isso: quem abre decide primeiro, e uma planilha abre CSV.', ok=True),
  C('JSON Lines, because a person can read it in an editor', 'JSON Lines, porque uma pessoa consegue lê-lo num editor',
    'Readable is not the same as opening in a spreadsheet.', 'Legível não é o mesmo que abrir numa planilha.')),
M('ex-p1dperqk', 'choosing-a-format', 'medium',
  ('Match each Roda Livre need to the format the section chose for it.', 'Associe cada necessidade da Roda Livre ao formato que a seção escolheu.'),
  ('Who writes, who reads, and how.', 'Quem grava, quem lê, e como.'),
  [(('dock events on the stream', 'eventos das docas no fluxo'), ('Avro', 'Avro')),
   (('rides kept for Marta’s questions', 'viagens guardadas para as perguntas de Marta'), ('Parquet', 'Parquet')),
   (('the report for the city', 'o relatório para a prefeitura'), ('CSV', 'CSV')),
   (('an existing Hive estate', 'um ambiente Hive existente'), ('ORC', 'ORC'))]),
Q('ex-ah9jhjza', 'choosing-a-format', 'hard',
  ('Payment events arrive one at a time, programs read them, and the payments team changes the event every few months. What fits best on the way in?',
   'Eventos de pagamento chegam um a um, programas os leem, e o time de pagamentos muda o evento a cada poucos meses. O que serve melhor na chegada?'),
  ('Row-shaped, and a schema that changes under readers.', 'Com forma de linha, e um esquema que muda por baixo de quem lê.'),
  C('Parquet, written one event per file', 'Parquet, gravado com um evento por arquivo',
    'A columnar file per event pays a footer for every row.', 'Um arquivo colunar por evento paga um rodapé por linha.'),
  C('Avro, written one record at a time', 'Avro, gravado um registro de cada vez',
    'Right: one record at a time, with rules for schema change.', 'Isso: um registro por vez, com regras para mudança de esquema.', ok=True),
  C('CSV, with a column added at the end each time the event changes', 'CSV, com uma coluna acrescentada no fim a cada mudança do evento',
    'Nothing would tell a reader which columns a line has.', 'Nada diria a quem lê quais colunas uma linha tem.'),
  C('JSON array files, one per day', 'Arquivos com lista JSON, um por dia',
    'An array is unreadable until its last bracket, and carries no schema.', 'Uma lista é ilegível até o último colchete, e não carrega esquema.')),
# ---- drill
Q('ex-xcy2qh8g', 'drill', 'medium',
  ('Marta needs the average ride length over two years of rides. Which property of the stored file matters most?',
   'Marta precisa da duração média das viagens em dois anos. Que propriedade do arquivo guardado importa mais?'),
  ('One column out of seven.', 'Uma coluna de sete.'),
  C('That a person can open it in an editor to check', 'Que uma pessoa consiga abri-lo num editor para conferir',
    'Nobody checks two years of rides by eye.', 'Ninguém confere dois anos de viagens no olho.'),
  C('That a new ride can be appended cheaply', 'Que uma viagem nova possa ser acrescentada barato',
    'That is the writer’s concern; Marta is reading.', 'Essa é a preocupação de quem grava; Marta está lendo.'),
  C('That each record carries its field names', 'Que cada registro carregue os nomes dos campos',
    'Names on every record are the cost, not the benefit.', 'Nomes em todo registro são o custo, não o benefício.'),
  C('That one column can be read without the others', 'Que uma coluna possa ser lida sem passar pelas outras',
    'Right: that is the columnar layout.', 'Isso: esse é o arranjo colunar.', ok=True)),
Z('ex-sw1g5caw', 'drill', 'medium',
  ('A Parquet reader opens the file at the end, because that is where the ___ is.', 'Um leitor de Parquet abre o arquivo pelo fim, porque é lá que está o ___.'),
  ('It holds the schema and the statistics.', 'Ele guarda o esquema e as estatísticas.'),
  ['footer'], ['rodapé', 'rodape']),
M('ex-j0qvemb6', 'drill', 'easy',
  ('Match each format to where its schema lives.', 'Associe cada formato ao lugar onde mora o seu esquema.'),
  ('Header, footer, or neither.', 'Cabeçalho, rodapé, ou nenhum dos dois.'),
  [(('CSV', 'CSV'), ('in a document beside the file', 'num documento ao lado do arquivo')),
   (('Avro', 'Avro'), ('in the header, as JSON', 'no cabeçalho, em JSON')),
   (('Parquet', 'Parquet'), ('in the footer, ending in PAR1', 'no rodapé, que termina em PAR1')),
   (('ORC', 'ORC'), ('in the file footer, before the postscript', 'no rodapé do arquivo, antes do postscript'))]),
Q('ex-npxmfg4z', 'drill', 'hard',
  ('ana converts the app’s daily CSV export to Parquet. Which problem of the CSV does the conversion not solve by itself?',
   'ana converte para Parquet a exportação diária em CSV do aplicativo. Que problema do CSV a conversão não resolve sozinha?'),
  ('Somebody still reads the CSV once.', 'Alguém ainda lê o CSV uma vez.'),
  C('Reading one column means reading every byte of the file', 'Ler uma coluna obriga a ler todos os bytes do arquivo',
    'The Parquet copy can be read one column at a time.', 'A cópia em Parquet pode ser lida uma coluna por vez.'),
  C('A type guessed wrongly on reading', 'Um tipo adivinhado errado no momento de ler o CSV',
    'Right: Parquet stores faithfully whatever type the conversion chose.', 'Isso: o Parquet guarda fielmente o tipo que a conversão escolheu.', ok=True),
  C('The file cannot be split between several workers', 'O arquivo não pode ser dividido entre vários trabalhadores',
    'The Parquet copy splits at its row groups.', 'A cópia em Parquet se divide nos grupos de linhas.'),
  C('Every value is stored as text, even the numbers', 'Todo valor é guardado como texto, até os números',
    'The Parquet copy stores numbers as numbers, if the conversion made them so.', 'A cópia em Parquet guarda números como números, se a conversão os fez assim.')),
]
