#!/usr/bin/env bash
# The terminal sessions quoted in lesson 2 of llm-observability, as a script
# that produces them.
#
# THE SCRIPT IS THE SOURCE AND ITS OUTPUT IS NOT COMMITTED. Every transcript in
# this lesson was copied from running it.
#
#   sudo bash ../../lab.sh up        # once
#   sudo bash captures.sh
#
# What is STAGED rather than typed, and not shown: ~/obs rebuilt as lesson 1
# leaves it (lab.sh reset), and the programs this lesson and lesson 1 show,
# read out of the lessons that show them whole (stage). Installing Presidio
# runs the pip lines this lesson shows.
#
# WHAT THE CUSTOMERS TYPED WAS WRITTEN BY THE COURSE: data/traffic.jsonl is
# generated by traffic.py, which this lesson shows, and every name, address,
# telephone number and order number in it is invented, under domains reserved
# for examples.
#
# THE MODEL'S REPLIES. llama3.2:3b (a80c4f17acd5) through Ollama 0.40.0, at
# temperature 0, taken 2026-10-07 on 4 cores and 15 GB with no GPU.
#
# presidio_try.py turns warnings off: on every run, tldextract (which
# Presidio's URL recogniser uses) may try to download the public suffix list,
# and falls back to the copy it ships with, printing a traceback that has
# nothing to do with the lesson. Presidio's scores are its own and are printed
# as it returned them.
#
# Recorded on Ubuntu 24.04, TZ=America/Sao_Paulo.
set -uo pipefail
cd "$(dirname "$0")"
. ../../lab/capture.sh
exec 9>/var/tmp/llmobs-capture.lock; flock 9

quiet lab reset
stage telemetry.py le-6wxafmfh/the-chain.md
stage assistant.py le-6wxafmfh/the-chain.md
stage tree.py le-6wxafmfh/the-chain.md
stage traffic.py le-pdj3wk00/what-customers-type.md
stage scan.py le-pdj3wk00/what-customers-type.md
stage leak.py le-pdj3wk00/a-second-net.md
stage misses.py le-pdj3wk00/what-patterns-miss.md
stage presidio_try.py le-pdj3wk00/what-patterns-miss.md
stage pseudo.py le-pdj3wk00/pseudonyms.md
stage replay.py le-pdj3wk00/keeping-less.md
stage expire.py le-pdj3wk00/keeping-less.md
quiet lab exec "$(python3 "$COURSE/lab/fences.py" block what-patterns-miss.md 'pip install presidio-analyzer==2.2.364 presidio-anonymizer==2.2.364')"
quiet lab exec 'python assistant.py "warm up" >/dev/null; rm -f spans.jsonl'

block traffic
on 'python traffic.py data/traffic.jsonl'
on 'wc -l data/traffic.jsonl'

block what-customers-type
on 'python scan.py'
on 'grep -m 3 "\"order\"" data/traffic.jsonl'

block at-the-source
on 'python assistant.py --feature order --user u021 "Hi, I am Joana Prado (joana.prado@example.com). My order MG-20481937 has not arrived after 12 working days. Is it lost?"'
on 'python tree.py --attrs | grep -E "app.question|app.reply|user.hash"'
on 'grep -c "joana.prado@example.com" spans.jsonl'
on 'grep -c "Joana Prado" spans.jsonl'

block exporter
on 'python leak.py raw.jsonl && grep -o "joana.prado@example.com" raw.jsonl | wc -l'
on 'python leak.py clean.jsonl --redact && grep -o "joana.prado@example.com" clean.jsonl | wc -l'
on 'python tree.py --spans clean.jsonl --attrs | grep "message.content"'

block misses
on 'python misses.py'

block presidio
on 'du -sh ~/llmobs'
on 'python presidio_try.py'
on 'python presidio_try.py 0.5'

block pseudonyms
on 'python pseudo.py'
on 'PSEUDONYM_KEY= python assistant.py --user u021 "How long is a gift card valid?"'

block expire
on 'rm -f spans.jsonl feedback.jsonl; python replay.py --from 2026-10-03 --to 2026-10-05'
on 'grep -c "app.question" spans.jsonl'
on 'python expire.py --now 2026-10-05T00:00 --days 1'
on 'grep -c "app.question" spans.jsonl'
