#!/usr/bin/env bash
# The terminal sessions quoted in lesson 2 of llm-observability, as a script
# that produces them.
#
# THE SCRIPT IS THE SOURCE AND ITS OUTPUT IS NOT COMMITTED. Every transcript in
# this lesson was copied from running it.
#
#   sudo bash ../../lab.sh up        # once
#   sudo bash captures.sh
#
# What is STAGED rather than typed, and not shown in the lesson: the lab
# (lab.sh reset), and copying the course's programs into ~/obs from
# ../../lab/code (telemetry.py, redact.py, assistant.py, replay.py, tree.py).
# The programs this lesson writes are put below and shown in it in full.
#
# WHAT THE CUSTOMERS TYPED WAS WRITTEN BY THE COURSE: data/traffic.jsonl is
# generated by ../../lab/traffic.py, and every name, address, telephone number
# and order number in it is invented, under domains reserved for examples.
# Replies come from extract-1, the lab's stand-in model (rag's lab/labgen.py).
#
# presidio_try.py turns warnings off: on every run, tldextract (which
# Presidio's URL recogniser uses) tries to download the public suffix list,
# cannot, and falls back to the copy it ships with, printing a traceback that
# has nothing to do with the lesson. Presidio's scores are its own and are
# printed as it returned them.
#
# Recorded on Ubuntu 24.04, Python 3.11, TZ=America/Sao_Paulo, on 2026-10-06.
set -uo pipefail
export TZ=America/Sao_Paulo LC_ALL=C.UTF-8
cd "$(dirname "$0")"
LAB_SH=${LAB_SH:-../../lab.sh}
CODE=$(cd "$(dirname "$LAB_SH")" && pwd)/lab/code
lab() { bash "$LAB_SH" "$@"; }
on() { printf 'ana@lab:~/obs$ %s\n' "$*"; lab exec "$*" 2>&1 || true; }
put() { lab exec "mkdir -p \"\$(dirname '$1')\" && cat > '$1'"; }
use() { for f in "$@"; do put "$f" < "$CODE/$f"; done; }
block() { printf '##### %s\n' "$1"; }
exec 9>/var/tmp/llmobs-capture.lock; flock 9
lab reset >/dev/null
use telemetry.py redact.py assistant.py replay.py tree.py
lab exec 'python assistant.py "warm up" >/dev/null; rm -f spans.jsonl'

put scan.py <<'PY'
"""scan.py: a week of what customers typed, and how much of it redact() would take out."""
import json
from collections import Counter

import redact

rows = [json.loads(line) for line in open("data/traffic.jsonl")]
total, hit, found = Counter(), Counter(), Counter()
for r in rows:
    total[r["feature"]] += 1
    f = redact.found(r["text"])
    hit[r["feature"]] += bool(f)
    found.update(f)
print("feature  requests  with something to redact")
for feature in total:
    print(f"{feature:8} {total[feature]:9} {hit[feature]:9}")
print("found:", dict(found))
PY

put misses.py <<'PY'
"""misses.py: what the patterns catch, what they miss, and what they catch by mistake."""
import redact

for text in ["Hi, I'm Joana Prado (joana.prado@example.com), order MG-20481937.",
             "my email is joana dot prado at example dot com",
             "call me on 11 5550-0142",
             "card 4111 1111 1111 1111, expires 09/28",
             "Is ISBN 978-0-14-143951-8 in stock?",
             "My CPF is 123.456.789-09"]:
    print(f"{text}\n  -> {redact.redact(text)}")
PY

put leak.py <<'PY'
"""leak.py: one customer message through an instrumented SDK, with and without a redacting exporter."""
import sys

from openai import OpenAI
from openinference.instrumentation.openai import OpenAIInstrumentor
from opentelemetry.sdk.trace import ReadableSpan, TracerProvider
from opentelemetry.sdk.trace.export import SimpleSpanProcessor, SpanExporter

import redact
import telemetry


class Redacting(SpanExporter):
    """Hands every span on to INNER with each string attribute, and each event's, passed through redact()."""

    def __init__(self, inner):
        self.inner = inner

    def export(self, spans):
        clean = lambda attrs: {k: redact.redact(v) if isinstance(v, str) else v for k, v in attrs.items()}
        return self.inner.export([ReadableSpan(
            name=s.name, context=s.context, parent=s.parent, resource=s.resource,
            attributes=clean(s.attributes), links=s.links, kind=s.kind, status=s.status,
            events=[type(e)(e.name, clean(e.attributes), e.timestamp) for e in s.events],
            start_time=s.start_time, end_time=s.end_time, instrumentation_scope=s.instrumentation_scope)
            for s in spans])

    def shutdown(self):
        self.inner.shutdown()


out = sys.argv[1]
exporter = telemetry.JsonlExporter(out)
if "--redact" in sys.argv:
    exporter = Redacting(exporter)
provider = TracerProvider()
provider.add_span_processor(SimpleSpanProcessor(exporter))
OpenAIInstrumentor().instrument(tracer_provider=provider)
OpenAI().chat.completions.create(model="extract-1", messages=[{"role": "user", "content":
    "Hi, I'm Joana Prado (joana.prado@example.com, +55 11 5550-0142). Is my order MG-20481937 lost?"}])
PY

put presidio_try.py <<'PY'
"""presidio_try.py: the same sentences through Presidio, which finds entities with a language model as well as patterns."""
import logging
import sys

from presidio_analyzer import AnalyzerEngine
from presidio_anonymizer import AnonymizerEngine

logging.disable(logging.WARNING)   # tldextract warns that it could not fetch a list; it uses its own copy
threshold = float(sys.argv[1]) if len(sys.argv) > 1 else 0.0
analyzer, anonymizer = AnalyzerEngine(), AnonymizerEngine()
for text in ["Hi, I'm Joana Prado (joana.prado@example.com), order MG-20481937.",
             "my email is joana dot prado at example dot com",
             "call me on 11 5550-0142",
             "card 4111 1111 1111 1111, expires 09/28",
             "Is ISBN 978-0-14-143951-8 in stock?",
             "My CPF is 123.456.789-09"]:
    found = analyzer.analyze(text=text, language="en", score_threshold=threshold)
    print(f"{anonymizer.anonymize(text=text, analyzer_results=found).text}")
    print("    " + (", ".join(f"{r.entity_type} {r.score:.2f}" for r in sorted(found, key=lambda r: r.start))
                     or "nothing found"))
PY

put pseudo.py <<'PY'
"""pseudo.py: why a user id is hashed with a key, and never without one."""
import hashlib
import time

import redact

guesses = [f"u{i:03d}" for i in range(1000)]          # the shape anyone can see the ids have
unkeyed = hashlib.sha256(b"u021").hexdigest()[:16]
t = time.perf_counter()
back = [g for g in guesses if hashlib.sha256(g.encode()).hexdigest()[:16] == unkeyed]
print(f"unkeyed {unkeyed}: {len(guesses)} guesses in {(time.perf_counter() - t) * 1000:.1f} ms find {back}")
keyed = redact.pseudonym("u021")
back = [g for g in guesses if hashlib.sha256(g.encode()).hexdigest()[:16] == keyed]
print(f"keyed   {keyed}: the same {len(guesses)} guesses find {back}")
PY

put expire.py <<'PY'
"""expire.py: take what people typed out of spans older than --days, and keep everything else."""
import argparse
import json
import os
from datetime import datetime, timedelta

TEXT = ("app.question", "app.reply")
p = argparse.ArgumentParser()
p.add_argument("--now", required=True)
p.add_argument("--days", type=int, required=True)
p.add_argument("--spans", default="spans.jsonl")
a = p.parse_args()

since = datetime.fromisoformat(a.now) - timedelta(days=a.days)
cutoff = since.timestamp() * 1e9
spans, expired = [json.loads(line) for line in open(a.spans)], 0
for s in spans:
    if s["start"] < cutoff and any(k in s["attributes"] for k in TEXT):
        for k in TEXT:
            s["attributes"].pop(k, None)
        expired += 1
with open(a.spans + ".new", "w") as f:
    f.writelines(json.dumps(s, ensure_ascii=False) + "\n" for s in spans)
os.replace(a.spans + ".new", a.spans)
print(f"{len(spans)} spans; text removed from {expired}, every one that started before {since:%Y-%m-%d %H:%M}")
PY

block what-customers-type
on 'python scan.py'
on 'grep -m 3 "\"order\"" data/traffic.jsonl'

block at-the-source
on 'python assistant.py --feature order --user u021 "Hi, I am Joana Prado (joana.prado@example.com). My order MG-20481937 has not arrived after 12 working days. Is it lost?"'
on 'python tree.py --attrs | grep -E "app.question|app.reply|user.hash"'
on 'grep -c "joana.prado@example.com" spans.jsonl'
on 'grep -c "Joana Prado" spans.jsonl'

block exporter
on 'python leak.py raw.jsonl && grep -o "joana.prado@example.com" raw.jsonl | wc -l'
on 'python leak.py clean.jsonl --redact && grep -o "joana.prado@example.com" clean.jsonl | wc -l'
on 'python tree.py --spans clean.jsonl --attrs | grep "message.content"'

block misses
on 'python misses.py'

on 'python presidio_try.py'
on 'python presidio_try.py 0.5'

block pseudonyms
on 'python pseudo.py'
on 'PSEUDONYM_KEY= python assistant.py --user u021 "How long is a gift card valid?"'

block expire
on 'rm -f spans.jsonl feedback.jsonl; python replay.py --from 2026-10-03 --to 2026-10-05'
on 'grep -c "app.question" spans.jsonl'
on 'python expire.py --now 2026-10-05T00:00 --days 1'
on 'grep -c "app.question" spans.jsonl'
