#!/usr/bin/env bash
# The machine every transcript in data-fundamentals was recorded on, built the
# way lesson 1 teaches a student to build theirs.
#
# THE STUDENT NEVER SEES THIS FILE. Lesson 1, section `the-lab`, gives them the
# commands, and every program the course runs is printed whole in the lesson
# that uses it. This script runs the section's `sh` fences, read out of the
# lesson itself and in order, so a transcript is what the student's machine
# prints; `lab/extract.py` reads the programs out of the lessons the same way.
#
# ONE LINUX COMPUTER AND ONE PERSON. ana has just joined the data team of Roda
# Livre, a bicycle-sharing service in Curitiba that does not exist: twelve
# stations, ninety bicycles, an app, a payments provider and a sensor in every
# dock. Everything the course measures is generated by programs the lessons
# print, from fixed seeds, so the numbers are the same on every run.
#
#   ~/roda         the working directory: the programs and what they write
#   ~/roda/.venv   Python 3.12 with pyarrow and fastavro, pinned
#
# STAGED rather than typed, because Ubuntu Server ships them and the container
# image leaves them out: python3, sudo, and the user ana in the group sudo as
# the first user of an Ubuntu Server install is. Also staged: the file
# ~/.sudo_as_admin_successful, which silences a two-line note a real machine
# prints once. The machine is a container rather than a virtual machine because
# the userland is the same and a container starts clean every time.
#
# APT and pip reach the network through this recording machine's HTTPS proxy
# and its certificate (PROXY and CA below); that is the recording machine's,
# not a step of the lesson.
#
#   bash lab.sh image                 build roda-lab:base and roda-lab:ready
#   bash lab.sh run LESSON < SCRIPT   run SCRIPT as ana in ~/roda, in a fresh
#                                     container, with every program the course
#                                     printed up to and including LESSON
#   bash lab.sh bare < SCRIPT         the same in roda-lab:base, before the
#                                     setup, for lesson 1's failures
#
# SCRIPT may call `on 'COMMAND'`, which prints the prompt and the command and
# then runs it in an interactive bash, the shell lesson 1's ~/.bashrc lines
# make; `block NAME` prints a separator the author splices by.
#
# Recorded on Ubuntu 24.04 with Python 3.12.3, pyarrow 26.0.0 and fastavro
# 1.13.1, TZ=America/Sao_Paulo.
set -euo pipefail

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
LESSON1=$HERE/lessons/le-tgvfkfr9
PROXY=${PROXY:-${HTTPS_PROXY:-}}
CA=${CA:-/root/.ccr/ca-bundle.crt}

net() {
  if [ -n "$PROXY" ]; then
    printf -- '--network host -e HTTPS_PROXY=%s -e https_proxy=%s -e PIP_CERT=/ca.crt -e SSL_CERT_FILE=/ca.crt -v %s:/ca.crt:ro' \
      "$PROXY" "$PROXY" "$CA"
  fi
}

# The `sh` fences of section `the-lab`, in order: what the student types.
setup_commands() {
  awk '/^```sh$/{on=1;next} /^```$/{on=0} on' "$LESSON1/the-lab.md"
}

HELPERS=$(cat <<'H'
export TZ=America/Sao_Paulo LC_ALL=C.UTF-8 COLUMNS=100
on() {
  printf 'ana@lab:%s$ %s\n' "$(pwd | sed "s|^$HOME|~|")" "$1"
  bash -ic "$1" 2>&1 | grep -v '^bash: \(cannot set terminal\|no job control\)' || true
}
block() { printf '##### %s\n' "$1"; }
H
)

image() {
  local base
  base=$(cat <<'B'
set -e
export DEBIAN_FRONTEND=noninteractive
if [ -n "${HTTPS_PROXY:-}" ]; then
  sed -i 's|http://|https://|g' /etc/apt/sources.list.d/ubuntu.sources
  printf 'Acquire::https::Proxy "%s";\nAcquire::https::CAInfo "/ca.crt";\n' "$HTTPS_PROXY" \
    > /etc/apt/apt.conf.d/99proxy
fi
apt-get update -qq >/dev/null
apt-get install -y -qq python3 sudo >/dev/null 2>&1
useradd -m -s /bin/bash -G sudo ana
echo 'ana ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/ana
touch /home/ana/.sudo_as_admin_successful
B
)
  docker rm -f roda-build >/dev/null 2>&1 || true
  # shellcheck disable=SC2046
  docker run --name roda-build --hostname lab $(net) ubuntu:24.04 bash -c "$base"
  docker commit roda-build roda-lab:base >/dev/null
  docker rm roda-build >/dev/null
  # shellcheck disable=SC2046
  docker run --name roda-build --hostname lab $(net) -u ana -w /home/ana roda-lab:base \
    bash -c "set -e; export PIP_PROGRESS_BAR=off; $(setup_commands)"
  docker commit roda-build roda-lab:ready >/dev/null
  docker rm roda-build >/dev/null
  echo 'roda-lab:base and roda-lab:ready built'
}

# Every lesson written up to and including $1, in the order of the topics,
# which is the course's order whether or not `lessons` names it yet.
lessons_upto() {
  python3 - "$HERE" "$1" <<'P'
import json, sys
here, last = sys.argv[1], sys.argv[2]
import os
for t in json.load(open(f'{here}/course.json'))['topics']:
    l = t['id']
    if os.path.isdir(f'{here}/lessons/{l}'):
        print(f'{here}/lessons/{l}')
    if l == last:
        break
P
}

run_in() {
  local img=$1 lesson=${2:-} work
  work=$(mktemp -d); chmod 755 "$work"
  if [ -n "$lesson" ]; then
    # shellcheck disable=SC2046
    python3 "$HERE/lab/extract.py" "$work" $(for d in $(lessons_upto "$lesson"); do ls "$d"/*.md; done) 2>/dev/null; chmod -R a+rX "$work"
  fi
  local script
  script=$(cat)
  local name="roda-run-$$-$RANDOM"
  # shellcheck disable=SC2046
  docker run --rm -i --name "$name" --hostname lab $(net) -u ana -w /home/ana \
    -v "$work:/files:ro" "$img" bash -c "
mkdir -p ~/roda && cp -r /files/. ~/roda/ 2>/dev/null; cd ~/roda
$HELPERS
$script" 2>&1
  rm -rf "$work"
}

case ${1:-} in
  image) image ;;
  run) run_in roda-lab:ready "${2:?lesson id}" ;;
  bare) run_in roda-lab:base "" ;;
  *) echo "usage: lab.sh image | run LESSON < SCRIPT | bare < SCRIPT" >&2; exit 2 ;;
esac
